### PR TITLE
Split assets package

### LINKED ISSUE #3317: Travis builds are failing because our asset package is too large to compile in the amount of memory they give us
We need to consider splitting the assets package into multiple smaller packages, probably aligned around function and role.  This would help builds and also change management, and potentially allow us to optionally pull in other components on demand.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3317 
Split the java console assets into their own package

### CODE REVIEW

**Comment by liggitt** [comment]
@spadgett review

**Comment by spadgett** [comment]
Working well for me. This cuts the size of bindata.go in half. Assuming there's no need to update `test-assets.sh` because the Java package won't often change.

I am seeing some 403 errors accessing the Java console, but I'm probably just not set up to run it. @liggitt ?

openshift-jvm

**Comment by liggitt** [comment]
@spadgett added testing of java bindata.go, PTAL

**Comment by spadgett** [comment]
LGTM

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
