### PR TITLE
tighten interfaces for template instance API

### PR DESCRIPTION
**Pull request by deads2k**
Tighten the interface in the strategy to what's needed.

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, not sure if this will cause @gabemontero any pain

**Comment by gabemontero** [comment]
On Mon, Aug 14, 2017 at 1:48 PM, Ben Parees <notifications@github.com>
wrote:

> lgtm, not sure if this will cause @gabemontero
> <https://github.com/gabemontero> any pain
>
Minimal churn ... 1 file overlaps, the specific changes in that file do not.

Thanks for heads up, as well as to @deads2k 's heads up at lunch

**Pull request merged**
