### PR TITLE
router: Fix ingress handling of nil rule value

### PR DESCRIPTION
**Pull request by marun**
Addresses [bz#1421632](https://bugzilla.redhat.com/show_bug.cgi?id=1421632)

cc: @openshift/networking

### CODE REVIEW

**Comment by knobunc** [comment]
[test]

**Comment by JacobTanenbaum** [comment]
LGTM

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
[test] It looks like it took more than 3 minutes for the pods to start.

**Comment by knobunc** [comment]
[merge] last flaked on https://github.com/openshift/origin/issues/12784

**Pull request merged**
