### PR TITLE
Bump: cadvisor 0.13.0-34-gc7908f7

### PR DESCRIPTION
**Pull request by sdodson**
Pick up the fix for https://github.com/GoogleCloudPlatform/kubernetes/issues/7906 ahead of rebase.

CC: @derekwaynecarr

### CODE REVIEW

**Comment by sdodson** [comment]
The customer that was seeing negative cpu resources available in a ravello nested KVM atop AWS has confirmed this fixed the issue for them.

**Comment by sdodson** [comment]
[test]

**Comment by smarterclayton** [comment]
My rebase will have this, can it wait a day or so?

**Comment by sdodson** [comment]
yup, will just pick it up in the rebase.

**Pull request closed without merging**
