### PR TITLE
Simplify reading of random bytes

### PR DESCRIPTION
**Pull request by rhcarvalho**
No need to use io.ReadFull, no need to convert error to string.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
[test]

**Comment by rhcarvalho** [comment]
@mfojtik PTAL [test]

**Comment by mfojtik** [comment]
@rhcarvalho I think the reason why we have `rand.Reader` used here is to allow it to override for unit tests. The `Reader` is just a var in 'rand' package, so you can fake it with 'not-very-rand' reader to have consistent results in tests.

**Comment by rhcarvalho** [comment]
There's no test in origin referencing `rand.Reader`.

In any case, `rand.Read` does exactly what we had re-implemented...
https://golang.org/src/crypto/rand/rand.go?s=714:787

IOW, there's no behavior change in any way, just less code to carry.

**Comment by mfojtik** [comment]
@rhcarvalho I see, LGTM then.

**Comment by rhcarvalho** [comment]
Can we merge it, or you want more LGTMs?

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
