### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by xiangpengzhao**
1. return nil instead of err when the value of err is nil.
2. fix wrong type.

### CODE REVIEW

**Comment by sosiouxme** [comment]
LGTM but travis is choking on "err" being redefined.

**Comment by xiangpengzhao** [comment]
The travis log shows: 
```
[WARNING] This version mismatch could lead to differences in execution between this run and the Origin CI systems.
pkg/gitserver/gitserver.go:160: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:156
pkg/gitserver/gitserver.go:166: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:156
pkg/gitserver/gitserver.go:174: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:156
pkg/gitserver/gitserver.go:183: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:156
pkg/gitserver/gitserver.go:196: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:156
pkg/gitserver/gitserver.go:200: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:196
pkg/gitserver/gitserver.go:254: declaration of "err" shadows declaration at pkg/gitserver/gitserver.go:225
pkg/gitserver/gitserver.go:336: declaration of "url" shadows declaration at pkg/gitserver/gitserver.go:9
pkg/gitserver/hooks.go:76: declaration of "err" shadows declaration at pkg/gitserver/hooks.go:57
pkg/gitserver/initializer.go:61: declaration of "err" shadows declaration at pkg/gitserver/initializer.go:44
pkg/gitserver/autobuild/autobuild.go:60: declaration of "err" shadows declaration at pkg/gitserver/autobuild/autobuild.go:42
pkg/gitserver/autobuild/autobuild.go:64: declaration of "err" shadows declaration at pkg/gitserver/autobuild/autobuild.go:60
pkg/gitserver/autobuild/autobuild.go:180: declaration of "err" shadows declaration at pkg/gitserver/autobuild/autobuild.go:146
[ERROR] PID 13137: hack/verify-govet.sh:74: `go tool vet -shadow -shadowstrict $test_dir` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/verify-govet.sh:74: `go tool vet -shadow -shadowstrict $test_dir`
[INFO]   Exiting with code 1.
make: *** [verify] Error 1
```

One of the related code blocks is:

```go
	abs, err := filepath.Abs(home)
	if err != nil {
		return nil, fmt.Errorf("can't make %q absolute: %v", home, err)
	}
	if stat, err := os.Stat(abs); err != nil || !stat.IsDir() {
		return nil, fmt.Errorf("GIT_HOME must be an existing directory: %v", err)
	}
```

But it seems that we shouldn't modify the code. Then how to solve the travis flake? Should the script `hack/verify-govet.sh` be modified?

@sosiouxme Thanks!

**Comment by knobunc** [comment]
LGTM [test]

**Comment by xiangpengzhao** [comment]
Travis still failed due to the same error as is mentioned in my above comment. How can we solve this? @sosiouxme @knobunc Thanks!

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/11240 (perhaps?) re-[test]

**Pull request closed without merging**
