### PR TITLE
add pr testing for sync plugin, some refactor of jenkins pluging pr t…

### PR DESCRIPTION
**Pull request by gabemontero**
…esting

@openshift/devex PTAL

@csrwng unless Ben works too much while on PTO, once everyone is happy, I'll need your authority to merge.

As an FYI, I'll be initiating 3 separate extended test runs in this PR to verify both the ginkgo focus and functionality of testing for the 3 jenkins plugins in question.

### CODE REVIEW

**Comment by gabemontero** [comment]
extended test run 1

[testextended][extended:core(openshift pipeline plugin)]

**Comment by csrwng** [comment]
LGTM pending extended tests passing

**Comment by gabemontero** [comment]
On Tue, Mar 7, 2017 at 2:03 PM, Cesar Wong <notifications@github.com> wrote:

> LGTM pending extended tests passing
>
Cool - thanks !

I'll post an update when all three runs are done.

**Comment by gabemontero** [comment]
ok test run 1 passed / looks good

test 2:

[testextended][extended:core(openshift pipeline build)]

**Comment by gabemontero** [comment]
ok test run 2 passed / looks good

test 3:

[testextended][extended:core(jenkins-client-plugin)]

**Comment by gabemontero** [comment]
@csrwng we are good to merge

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
A network hiccup processing ruby gems:

```
2017-03-08T07:05:51.891460000Z I0308 07:05:51.890183       1 sti.go:656] Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/minitest-5.4.2.gem)
2017-03-08T07:05:51.910771000Z I0308 07:05:51.909578       1 sti.go:656] An error occurred while installing minitest (5.4.2), and Bundler cannot
2017-03-08T07:05:51.911086000Z I0308 07:05:51.909601       1 sti.go:656] continue.
2017-03-08T07:05:51.911457000Z I0308 07:05:51.909614       1 sti.go:656] Make sure that `gem install minitest -v '5.4.2'` succeeds before bundling.
```

Seems overkill to open a flake for this one.  @bparees @csrwng - agree to just re-post the merge comment?

**Comment by csrwng** [comment]
[merge]

**Comment by gabemontero** [comment]
Thanks @csrwng :-)

**Comment by gabemontero** [comment]
this time we hit the "GCE Job Failing to Start API Server" that @stevekuznetsov emailed about on aos-devel:

```
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: An unknown error occurred: ''", "redirected": false, "status": -1, "url": "https://api.prtest-4042605.origin-ci-int-gce.dev.rhcloud.com:443/healthz/ready"}
```

Couldn't tell from the email thread if the issue was persistent or intermittent.  If I can catch @stevekuznetsov at his cube or if he gets a second to respond, we'll see if it make sense to repost the merge comment or wait until they make some progress.

**Comment by stevekuznetsov** [comment]
It's persistent and seems to have blocked merges for now. Still looking.

**Comment by gabemontero** [comment]
thanks for the clarification @stevekuznetsov

**Comment by gabemontero** [comment]
Looks like they have disabled the GCE job for the time being wrt merges.

@csrwng - please re-post the merge comment at your earliest convenience.  Thanks.

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
