### PR TITLE
Prepare for static deep-copy in 3.8 rebase

### PR DESCRIPTION
**Pull request by sttts**
This has no effect yet in 3.7 based master, but will make the 3.8 rebase much easier
with the deepcopy tags in place and test types moved into non-test packages to
be reachable by deepcopy-gen.

### CODE REVIEW

**Comment by deads2k** [comment]
/approve

For intent.  I think it will be a big help for the rebase and inert (yet correct) for our code at the moment.

**Comment by sttts** [comment]
The second commit is a pure move of the types plus the new tags.

**Comment by deads2k** [comment]
Seems like we should have at least *some* customization somewhere.  Squashed in an existing commit?  The clusterquota copier comes to mind.

**Comment by sttts** [comment]
> Seems like we should have at least some customization somewhere. Squashed in an existing commit? The clusterquota copier comes to mind.
> Merge state

Custom `.DeepCopy` funcs on types will still be supported. Note that this PR does not backport the new deepcopy-gen which actually uses the tags. I.e. existing `zz_generator_deepcopy.go` files should not be changed here. I only added some more packages to the list in `deepcopygen.go` because we will need that in the 3.8 rebase as well. Technically, we could drop that change here.

**Pull request merged**
