### PR TITLE
Added comment to clarify that oc cluster did not work on previous version

### PR DESCRIPTION
**Pull request by padajuan**
Added comment to clarify that oc cluster did not work on versions before that 1.3

### CODE REVIEW

**Comment by padajuan** [comment]
The related [Issue](https://github.com/openshift/origin/issues/11580)

**Comment by coreydaley** [comment]
@smarterclayton @luciddreamz I seem to recall us going over this (probably via email) about linking to the latest release instead of a specific release from the docs.  What do you guys think of this change? Just linking to the releases page?

**Comment by luciddreamz** [comment]
@coreydaley Seems fine, but probably reword this bit: " > oc cluster <option> are implemented on releases from 1.3.X, then take care with the tag that you will download"

**Comment by coreydaley** [comment]
@padajuan Can you update the wording to something like this?

Please be aware that the 'oc cluster' set of commands are only available in the 1.3.x or newer releases.

**Comment by csrwng** [comment]
@padajuan we need a similar change for the instructions for Windows and Mac OS where we link to the same URL. If you prefer, we can also do that in a follow-up PR, let me know.

**Comment by padajuan** [comment]
@csrwng You already got it ;)

**Comment by coreydaley** [comment]
@padajuan Can you remove the extra linebreak on line 152 please?

**Comment by coreydaley** [comment]
@csrwng LGTM

**Comment by coreydaley** [comment]
[test]

**Comment by csrwng** [comment]
LGTM as well ... @padjuan please squash your commits

**Comment by csrwng** [comment]
@padajuan ^^

**Comment by csrwng** [comment]
@padajuan looks like you still have an extra commit with no changes in your branch

**Comment by padajuan** [comment]
@csrwng Sorry, already it's ok

**Comment by csrwng** [comment]
@padajuan thx, @bparees ptal

**Comment by bparees** [comment]
[merge]

**Pull request merged**
