### PR TITLE
scale deploymentconfig

### PR DESCRIPTION
**Pull request by zhouying7780**
Scale up and scale down the deploymentconfig will update the `Spec.Replicas`

### CODE REVIEW

**Comment by zhouying7780** [comment]
Auto for case: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-9908 and 
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-11221

Check point : scale the deploymentconfig. 
(Since the two cases are similar so burn into one  Describe block.)

**Comment by tnozicka** [comment]
we test scaling in the other tests for sure, what value is this adding / which case is not already covered?

**Comment by tnozicka** [comment]
> Scale up and scale down the deploymentconfig will update the Spec.Replicas

sounds like cli test, not DCs

**Comment by zhouying7780** [comment]
The main checkpoint is :update the `Spec.Replicas` of DC.

**Pull request closed without merging**
