### PR TITLE
Regenerate bindata.go to fix assets tests

### PR DESCRIPTION
**Pull request by mnagy**

### CODE REVIEW

**Comment by liggitt** [comment]
Make sure you run hack/install-assets.sh locally to get the latest dependencies installed before building.

**Comment by mnagy** [comment]
@liggitt I'm seeing errors:
```
bower kubernetes-object-describer#0.0.14     not-cached git://github.com/kubernetes-ui/object-describer.git#0.0.14
bower kubernetes-object-describer#0.0.14        resolve git://github.com/kubernetes-ui/object-describer.git#0.0.14
bower kubernetes-object-describer#0.0.14       download https://github.com/kubernetes-ui/object-describer/archive/v0.0.14.tar.gz
bower kubernetes-object-describer#0.0.14        extract archive.tar.gz
bower kubernetes-object-describer#0.0.14       resolved git://github.com/kubernetes-ui/object-describer.git#0.0.14
bower                                         ECONFLICT Unable to find suitable version for kubernetes-object-describer
```

**Comment by liggitt** [comment]
Try hack/clean-assets.sh first

**Comment by liggitt** [comment]
@mnagy pretty sure what you're seeing is a known issue with Travis not being able to build assets, since Jenkins is passing. See #3320, #3317

**Comment by mnagy** [comment]
@liggitt Yeah, you are right. Closing.

**Pull request closed without merging**
