### PR TITLE
Set NOFILE to 128k/64k for master/node, set CORE=infinity

### PR DESCRIPTION
**Pull request by sdodson**
Partial/potential fix for https://bugzilla.redhat.com/show_bug.cgi?id=1221773

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by sdodson** [comment]
Original commit was actually 1024k rather than 128k, fixed that.

**Comment by sdodson** [comment]
@smarterclayton re [merge] please

**Comment by smarterclayton** [comment]
[merge]

**Comment by tdawson** [comment]
I have tested this on 100 node cluster.  It worked.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
