### PR TITLE
UPSTREAM: 17017: stop jsonpath panicing on bad array length

### PR DESCRIPTION
**Pull request by deads2k**
Picks https://github.com/kubernetes/kubernetes/issues/17016.

@liggitt let the 1.1.1 upstream picks begin...

### CODE REVIEW

**Comment by deads2k** [comment]
@liggitt This merged upstream and strictly better than what we have.  Any objection to merging it when we open 1.1.1?

**Comment by liggitt** [comment]
No objection

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
flake: https://github.com/openshift/origin/issues/5855

[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
dockerhub re[merge]

**Pull request merged**
