### PR TITLE
Fix travis assets test

### PR DESCRIPTION
**Pull request by liggitt**
Based on https://github.com/openshift/origin/pull/5636 and https://github.com/openshift/origin/pull/5572

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton PTAL
cc @sosiouxme @jwforres @spadgett

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Hrm, now seeing

```
pushd $ORIGIN_PATH
  hack/install-assets.sh
popd



Stdout from the command:

/data/src/github.com/openshift/origin ~
[install-assets] npm install --unsafe-perm
[install-assets] node_modules/protractor/bin/webdriver-manager update
[install-assets] bower cache clean --allow-root
[install-assets] bower update --allow-root


Stderr from the command:

+ ORIGIN_PATH=/data/src/github.com/openshift/origin
+ ASSET_BACKUP_DIR=/data/asset_dependencies
+ which npm
+ mkdir -p /data/asset_dependencies/node_modules
+ mkdir -p /data/asset_dependencies/bower_components
+ cp -rf /data/asset_dependencies/node_modules /data/src/github.com/openshift/origin/assets/node_modules
+ cp -rf /data/asset_dependencies/bower_components /data/src/github.com/openshift/origin/assets/bower_components
+ pushd /data/src/github.com/openshift/origin
+ hack/install-assets.sh
Build step 'Execute shell' marked build as failure
```

**Comment by liggitt** [comment]
Sigh. Dropping the `||` makes the script exit immediately on failure. Will look in a bit

**Comment by sosiouxme** [comment]
Well. I feel stupid :(

Thanks Jordan.

**Pull request merged**
