### PR TITLE
Fix device busy issues on serial e2e runs

### PR DESCRIPTION
**Pull request by pmorie**
Fixes the issue where serial e2e runs fail because of volumes that were not unmounted.

### CODE REVIEW

**Comment by pmorie** [comment]
@pweil- @ncdc @smarterclayton

**Comment by ncdc** [comment]
:+1:

**Comment by pweil-** [comment]
LGTM :cake:

**Comment by pmorie** [comment]
[test]

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
