### PR TITLE
Split prometheus alerting rules, add new automated recording rules

### PR DESCRIPTION
**Pull request by smarterclayton**
The recording rules can be used by federation

Testing this out @karkagis

### CODE REVIEW

**Comment by kargakis** [comment]
Looks good. I think we will still patch out `example-rules` because of the autoscaler.

**Comment by aweiteka** [comment]
+1 to this. thanks.

**Comment by smarterclayton** [comment]
Well, we'll replace the existing node autoscaler soon (when we move to full autoscaling cluster), so that would only be temporary.  However, if necessary we can figure out how to stomp it.

**Comment by smarterclayton** [comment]
@aweiteka prometheus-standalone.yaml is what is being used for the federation.

**Comment by smarterclayton** [comment]
@pgier this is a starting point for iteration for a standalone prometheus object.  I'm using this for federating a cluster, and config and rules are both split out so they must be provided separately (so not a precanned thing like the ops prometheus).

**Pull request merged**
