### PR TITLE
switch SDN to be vendored

### PR DESCRIPTION
**Pull request by deads2k**
this completes the arc for moving SDN to openshift/sdn

### CODE REVIEW

**Comment by danwinship** [comment]
Do we even need to vendor it? With https://github.com/openshift/sdn/pull/2 merged, the sdn node image should be getting build from that repo, so `origin/images/sdn` (and associated `Makefile`, etc, rules) can go away. And then when https://github.com/openshift/cluster-network-operator/pull/248 merges you can remove "`hypershift openshift-network-controller`" support from `cmd/hypershift/main.go`. And then nothing in origin will refer to openshift/sdn any more.

**Comment by danwinship** [comment]
ah, which is to say, close in favor of #23407 ?

**Comment by sttts** [comment]
> ah, which is to say, close in favor of #23407 ?

This one vendors. I think we still need it for some tests.

**Comment by danwinship** [comment]
> I think we still need it for some tests.

I think @deads2k fixed all those. `cmd/hypershift/main.go` is the only go file in origin (outside of `staging/src/github.com/openshift/sdn`) that imports anything from `github.com/openshift/sdn`

**Comment by tnozicka** [comment]
unconfirmed guess is that sdn might be hooked into test-cmd as that fails on it 
when removing it entirely in https://github.com/openshift/origin/pull/23407

**Pull request merged**
