### PR TITLE
Improve Dockerfile keyword highlighting in web console

### PR DESCRIPTION
**Pull request by spadgett**
Switch Ace editor themes for Dockerfiles so more keywords are highlighted.

openshift_web_console_and_openshift_web_console

/cc @jhadvig @jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
Also removed numeric highlighting like we do in YAML mode because it looks strange in the middle of strings and filepaths.

**Comment by jwforres** [comment]
[merge]

**Comment by jhadvig** [comment]
@spadgett looks much better :+1:

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
