### PR TITLE
UPSTREAM: 42491: make the system:authenticated group adder smarter

### PR DESCRIPTION
**Pull request by deads2k**
The larger change didn't make 1.6, but the smaller change did.  Revert the big one, use the little one.

@enj ptal

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
[test]

**Comment by enj** [comment]
LGTM.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
