### PR TITLE
Fix duplicate listing of PodNodeConstraints in the CombinedAdmissionControlPlugins list.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr @deads2k

### CODE REVIEW

**Comment by aveshagarwal** [comment]
[test]

**Comment by derekwaynecarr** [comment]
[test]

**Comment by deads2k** [comment]
Unless this is a blocker, can we delay until after the rebase lands?  https://github.com/openshift/origin/pull/15234

**Comment by derekwaynecarr** [comment]
@aveshagarwal - what is the impact of this happening twice in the chain (if any)?

**Comment by aveshagarwal** [comment]
@derekwaynecarr I dont see any impact.

**Comment by aveshagarwal** [comment]
@derekwaynecarr I just deleted the first entry of PodNodeConstraint to keep the order in  CombinedAdmissionControlPlugins (pkg/cmd/server/origin/master_config.go) and in defaultOffPlugins  (./pkg/cmd/server/start/admission.go)  in sync.

**Comment by deads2k** [comment]
Rebase landed.

**Comment by kargakis** [comment]
@stevekuznetsov seems like the same bot.

**Comment by kargakis** [comment]
TestAdmissionPluginChains fails consistently on every test run.

**Pull request closed without merging**
