### PR TITLE
Fix go cross compiler package names in release image

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@vbatts @smarterclayton should fix cross compilation (?)

**Comment by sdodson** [comment]
FWIW, for OSE we decided that we'd build windows clients as 32bit for greatest compatibility.

**Comment by vbatts** [comment]
looks like this will actually pull in the RPMS you expected to be there.

**Comment by smarterclayton** [comment]
Pull in the 32 bit windows as well I guess.

**Comment by smarterclayton** [comment]
We can do that in a follow up (@sdodson that's on you)

LGTM [merge]

**Pull request merged**
