### PR TITLE
bump(github.com/openshift/source-to-image): 28d8a6bf21d284b566e34cb83f5c94c8a67207d4

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

blocks some dependency cleanup work.

**Comment by soltysh** [comment]
@bparees are you sure the failures are not related to this PR, it looks like build are failing consistently.

**Comment by bparees** [comment]
@soltysh i'm pretty sure yes, i will investigate it later but for now i don't immediately see why this PR would cause those specific failures.

/retest

**Pull request merged**
