### PR TITLE
add update verb to routes/custom-host for admin role

### PR DESCRIPTION
**Pull request by rajatchopra**
Fix, as requested in https://bugzilla.redhat.com/show_bug.cgi?id=1524707
Also, to address issue #15772

@openshift/sig-networking

### CODE REVIEW

**Comment by rajatchopra** [comment]
[test]

**Comment by enj** [comment]
/hold

@openshift/sig-security 

Need to determine what this change actually means from a security and networking prescriptive.

**Comment by enj** [comment]
Clayton can you explain how adding this permission is OK?

**Comment by smarterclayton** [comment]
Users who can create something can edit it, because they can always delete it and recreate.  There is no security benefit to preventing this.

The original separation for online was:

1. online wasn't allowed to create or edit custom hosts or TLS certs
2. default origin/OCP allowed that for project admins, so as to indicate that this was a higher level of permission

In the future we may relax this to the edit role.

**Comment by enj** [comment]
@smarterclayton so does that mean we no longer need #18195 ?

**Comment by smarterclayton** [comment]
Yes, as described in the comments of the bug.

**Comment by liggitt** [comment]
/hold

I did not think we wanted namespaced users to be able to change their routes' hostnames.

**Comment by smarterclayton** [comment]
Bah, you're right.  Reading through the commit log reminded me of the
original subtleties.

original intent was to control three things

1. Can you request a custom host ("create" "routes/custom-host")
2. Can you change custom host ("update" "routes/custom-host")
3. Are you allowed to set TLS certificates on a route

Online only wanted 1, because 2 allows you to steal routes, and 3 allows
you to break some routers.  In general, out of the box we don't want to
give "update" "routes/custom-host" to anyone - I was wrong above.  We also
don't want to give everyone access to update tls certificates.

When we implemented this, we went through a long chain of argument on 3 -
should we even allow you to set TLS certs when you don't have permission to
create custom hosts.  Setting a publicly facing TLS cert doesn't have a ton
of value if your admin isn't letting you have a custom name, and the admin
is encouraged to use the default cert.  But even if the admin didn't have a
default cert, if they could still (via the API with a higher privileged
operation) set certs, they would be safe.  So we made it so that create
custom-host controlled setting TLS certs on the route, which solved the
online problem and preserved the less strictly tenanted use case as well -
an admin bot that wanted to set certs could be given create-host.

The set of people who should be able to update a host on a route is only
"update" "routes/custom-host".  The set of people who should be able to
update tls certificates on the route are:

1. people who can create custom-hosts (they could delete and recreate the
route, and we shouldn't be abusive)
2. people who can update custom-hosts (they can steal other people's
routes, and so we're not worried about them)

The check for updating TLS certificates should involve checking for either
of those permissions.  Strictly speaking:

1. "update" "routes/custom-host" should allow unrestricted changes to routes
2. "create" "routes/custom-host" should allow setting host on creation and
changing tls certificate
3. without those, you should be unable to set either host or tls certificate

We should update the strategy check for "update" to

1. check update if the host has changed, and if false, disallow any changes
2. if host hasn't changed but certs have, check "create", and if false,
disallow changes
3. allow changes

**Comment by rajatchopra** [comment]
Okay so the final proposed fix is in PR #18312
Closing this PR in favour of that.

**Pull request closed without merging**
