### PR TITLE
UPSTREAM: 47270: kubectl drain errors if pod is already deleted

### PR DESCRIPTION
**Pull request by derekwaynecarr**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1460067

xref https://github.com/kubernetes/kubernetes/pull/47270

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@marun -- ptal

**Comment by liggitt** [comment]
[merge][severity:bug]

**Comment by derekwaynecarr** [comment]
its a blocker, bumping severity.

[merge][severity:blocker]

**Pull request merged**
