### PR TITLE
Fixing livereload so that it works with https

### PR DESCRIPTION
**Pull request by rhamilto**
@jwforres, review and merge, please?

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@fabianofranz @jhadvig @benjaminapetersen @sg00dwin @spadgett FYI once this merges you won't need to hit F5 all the time anymore :)

thanks @rhamilto !

**Comment by benjaminapetersen** [comment]
yay! :grinning:

**Comment by jhadvig** [comment]
:metal:

**Comment by spadgett** [comment]
Looks like the certificate is going to expire in a few weeks (March 10).

**Comment by jwforres** [comment]
Can you fix the cert in your other PR?

**Comment by spadgett** [comment]
> Can you fix the cert in your other PR?

Yeah I'll take a look in #7221

**Pull request merged**
