### PR TITLE
Fix docs of oc

### PR DESCRIPTION
**Pull request by jprukner**
There is a fix of #4496 I suggest. Replace #4520 

@mfojtik PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
[merge]

**Comment by bparees** [comment]
@danmcp any idea why rosie is ignoring these merges?

**Comment by danmcp** [comment]
@mfojtik It's currently being ignored because the merge tag is before the commit.

**Comment by mfojtik** [comment]
@jprukner you have to stop pushing more commits after your PR is tagged to merge.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
actually the commit is dated in the future somehow.

**Comment by liggitt** [comment]
the code of the future!

**Comment by rhcarvalho** [comment]
@bparees that explains why it always show as "authored now"....

**Comment by bparees** [comment]
[merge]

**Comment by kargakis** [comment]
> the code of the future!

docs

**Pull request merged**
