### PR TITLE
Rewrite cluster-up to use rendering logic and bootkube start

### PR DESCRIPTION
**Pull request by mfojtik**
Changes in this PR are trying to re-assemble what the openshift 4.0 installer will do in order to bring the initial control plane up and running.

The way this will work is basically:

1) We generate the static pod manifests using the operator images that own the components (kube api server and controller manager) and the manifests for second stage that use daemonsets/configmaps/secrets.
2) We run `bootkube start` that will first move the static pod manifests into kubelet static pod manifest directory and wait until the initial control plane is up and running. Initial control plane use hostNetwork and hostPaths.
3) Once the initial control plane is running, bootkube will create the workload resources, secrets and config maps and wait until the second stage control plane is up and running
4) Once the daemonset based control plane is running, the bootkube will tear down the static pod control plane

At this point, the job of `cluster up` is done and users have working kubernetes control plane to add operators they will to run. 

/cc @deads2k 
/cc @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

Worth another round of squashing I think to get under 10 commits.  Feel free to squash mine.  Don't forget a note and the world's best bash one liner :).

**Comment by mfojtik** [comment]
@deads2k we actually need to wait for `bootkube start` to finish before moving on. If we don't they you are left with the bootstrap (phase 1) control plane which is not what you want. Waiting for `bootkube start` assures that the phase 2 control plane is up and running (daemonsets have pods).

**Comment by sttts** [comment]
> Why do I want daemonsets? Seems like we want
> 
> 1. static pod
> 2. initial important manifests created (no workloads)
> 3. CVO
> 
> Why bother with an in between daemonset? It doesn't seem to add value. And for the re-beginning of cluster up, why care what's running your API server?

The installer workflow defines what we want in cluster-up. In the installer we get one master node. That master node will be decommissioned and replaced by real master nodes. The daemonsets distribute our initial control plane over those new nodes.

We should not decide on this topic until we are 100% sure what the installer requires. The daemonsets do not hurt right now. Let's keep them for the time being. When we realize they are not needed in the installer, let's remove them in cluster-up as well.

Also note: the original idea was to use the configmaps and secrets in the daemonsets. We could still archieve that if we decide on a namespace structure which is compatible ("all in kube-system" will not work).

**Comment by mfojtik** [comment]
> > Why do I want daemonsets? Seems like we want
> > 
> > 1. static pod
> > 2. initial important manifests created (no workloads)
> > 3. CVO
> > 
> > Why bother with an in between daemonset? It doesn't seem to add value. And for the re-beginning of cluster up, why care what's running your API server?
> 
> The installer workflow defines what we want in cluster-up. In the installer we get one master node. That master node will be decommissioned and replaced by real master nodes. The daemonsets distribute our initial control plane over those new nodes.
> 
> We should not decide on this topic until we are 100% sure what the installer requires. The daemonsets do not hurt right now. Let's keep them for the time being. When we realize they are not needed in the installer, let's remove them in cluster-up as well.
> 
> Also note: the original idea was to use the configmaps and secrets in the daemonsets. We could still archieve that if we decide on a namespace structure which is compatible ("all in kube-system" will not work).

Agree, I think we should stick to what installer is (currently) doing. Which is `bootkube start` and that means the daemonsets are installed by bootkube. I think the workflow for the operator (if we keep using the same namespace) should be to "adopt" the daemonset provided by bootkube.

We should always keep our daemonset manifest files locked to the "released stable" version of images (4.0, 4.1, 4.2, etc.), where the CVO will decide whether an update of the control plane is needed or not once our operators are up and running. That means the operator can decide to "upgrade" the control plane from 4.0.0 -> 4.0.1234 as needed. 

What I like on this approach is:

1) It is tight to what the real installer will do and help is exercise this flow for every pull request (free testing for bootkube start/control plane)
2) It will allow us to test the "upgrade" flow as the initial control plane provided by rendering is the last stable version and CVO will probably just upgrade to the PR branch images (?)

However, I don't think we need to do this all in one PR, I'm fine with this providing just basic control plane for now and move to phase 2 as a second step (actually this branch already does the phase 2 and we are very close to have it fully functional here).

**Comment by mfojtik** [comment]
/retest

lets hope the new api operator image is available now :)

**Comment by mfojtik** [comment]
Reapplying the label as the last commits were just fixing the CI.

**Pull request merged**
