### PR TITLE
test: extend timeout in ICT tests to the IC controller resync interval

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/9856
Fixes https://github.com/openshift/origin/issues/9683

@mfojtik PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
The instantiate endpoint gives us a better way to trigger a deployment, but why does not having it mean we have to wait for the resync interval?

**Comment by kargakis** [comment]
> The instantiate endpoint gives us a better way to trigger a deployment, but why does not having it mean we have to wait for the resync interval?

Currently, if an image already exists and you create a DC with an ICT that references that image, you need to wait for the image change controller to resync the image stream and update the DC. /instantiate coupled with the image stream index used in the generic trigger controller fixes this.

**Comment by mfojtik** [comment]
@liggitt I think this will de-flake some of the deployment tests, but in the future we want to rework this once we have instantiate.

**Comment by liggitt** [comment]
Hmm, isn't that a regression?

**Comment by kargakis** [comment]
> Hmm, isn't that a regression from 3.2? This seems like making the tests pass by making them tolerate behavior we previously considered broken

We never tested this path before (image exists, dc is created). It may be the case that this was working for 3.2. I will test this in a while..

**Comment by kargakis** [comment]
Yes, this was working for 3.2 since the image change controller could start a deployment. /instantiate is not going to be merged for 3.3 so the only option left is to add a deployment config index in the image change controller. @deads2k another controller refactoring:) I will have a PR up for review later today.

**Comment by liggitt** [comment]
Can you open an issue to track that and revert these changes with the fix? We want tests to smack us if we break that behavior

**Comment by kargakis** [comment]
> Can you open an issue to track that and revert these changes with the fix? We want tests to smack us if we break that behavior

https://github.com/openshift/origin/pull/10456

**Pull request merged**
