### PR TITLE
Refactor graph veneers

### PR DESCRIPTION
**Pull request by deads2k**
Refactored the graph veneers to make it easier to follow the graph navigation.  As more edges are added, it becomes incredible unlikely that we'll actually have disconnected subgraphs for every service.  Something as simple as a secret, a service account, or a volume will cause disjoint services to to share a subgraph and you don't want status to treat said services as related. 

This pull treats all services as distinct (having two services related based on navigability to shared nodes isn't a good indicator anyway) and follows that idea to the logically conclusion in the veneers.

@smarterclayton This is specific to status (not the graph itself). Not sure who the reviewer should be.

### CODE REVIEW

**Comment by deads2k** [comment]
bump

**Comment by smarterclayton** [comment]
Will look tomorrow

On Jun 29, 2015, at 8:22 AM, David Eads <notifications@github.com> wrote:

bump

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3461#issuecomment-116634073>.

**Comment by deads2k** [comment]
Just in case you're worried, they don't charge us extra for the use of more letters..... :)

**Comment by deads2k** [comment]
comments addressed.  The diff is big enough with all the renames and type changes that I've squashed it in for easier reading.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
