### PR TITLE
OCPBUGS-7319: Unskip service session affinity tests

### PR DESCRIPTION
**Pull request by tssurya**
(cherry picked from commit 14d2ae41781c9332d73ebfdb2b194ec1bc63ebfe) (cherry picked from commit efb4c81470ac9e82d7e5997d7e4b50b0d3be0b43)

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by abhat** [comment]
LGTM.

**Comment by soltysh** [comment]
Manually adding cherry-pick-approved label, since the bot didn't pick it from https://github.com/openshift/origin/pull/27722#issuecomment-1429760210

**Pull request merged**
