### PR TITLE
resolve s2i perl test flake

### PR DESCRIPTION
**Pull request by jim-minter**
@bparees I think #17354 was going in the right direction, it was just missing HTTPD_START_SERVERS=1 as well.

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/hold
remove the hold when the extended tests pass.

**Comment by bparees** [comment]
@coreydaley fyi.

**Comment by coreydaley** [comment]
@bparees @jim-minter that would be awesome if this would fix the issue

**Comment by bparees** [comment]
Well this seems like the inverse problem, but we're still seeing the "live" count value instead of 1337:

```
CheckPageContains was looking for <span class="code" id="count-value">1337</span> but got   
<output truncated>
<span class="code" id="count-value">40</span>`
```

i'm also not sure how we're getting to "40" on that value (instead of 2 or 3 or something).  At one point in time the readiness/liveness probes were causing the counter to increase but i believe i fixed that by moving them to an explicit health check url instead of hitting the main page (which would bump the counter).

**Comment by jim-minter** [comment]
Off by two error.  Investigating.

**Comment by bparees** [comment]
Not sure what the "off by two" error was, but i'm redoing this PR here and it seemed to work ok at least locally: https://github.com/openshift/origin/pull/18357

**Pull request closed without merging**
