### PR TITLE
builds: use proxy specified in source strategy environment for s2i script download

### PR DESCRIPTION
**Pull request by csrwng**
Fixes BZ 1321309

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by nak3** [comment]
I feel that we should update our doc about this proxy settings. I am not sure about workflow, but who can do it..

https://docs.openshift.org/latest/dev_guide/builds.html#override-builder-image-scripts
https://docs.openshift.org/latest/install_config/http_proxies.html

**Comment by csrwng** [comment]
I'll submit a pull

**Comment by nak3** [comment]
Thank you!! @csrwng

**Pull request merged**
