### PR TITLE
UPSTREAM: Use patch in label and annotate

### PR DESCRIPTION
**Pull request by smarterclayton**
Referenced from #5107

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

On Oct 30, 2015, at 6:33 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6500/)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5536#issuecomment-152666133>.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Flake on int64 conversion [test]

**Comment by liggitt** [comment]
remove the `tryuntil` in our cmd test scripts now that these are using patch

**Comment by smarterclayton** [comment]
Kicking this out - not important enough to land

**Comment by smarterclayton** [comment]
Closing this, we'll get it next rebase.

**Pull request closed without merging**
