### PR TITLE
Updates `oc run` examples

### PR DESCRIPTION
**Pull request by jtslear**
* Removes a todo item from the list
* Test coverage provided by kubernetes/kubernetes#13917
* closes openshift/origin#8620

### CODE REVIEW

**Comment by jtslear** [comment]
I appear to be unable to regenerate the docs per the CI failure:

```
[vagrant@localhost origin]$ ./hack/update-generated-docs.sh
++ Building go targets for linux/amd64: tools/gendocs tools/genman
# github.com/openshift/origin/pkg/cmd/cli/cmd/login
pkg/cmd/cli/cmd/login/loginoptions.go:136: undefined: tls.RecordHeaderError
# github.com/openshift/origin/pkg/cmd/cli/cmd/observe
pkg/cmd/cli/cmd/observe/observe.go:360: exit.Stderr undefined (type *"os/exec".ExitError has no field or method Stderr)
pkg/cmd/cli/cmd/observe/observe.go:361: exit.Stderr undefined (type *"os/exec".ExitError has no field or method Stderr)
[ERROR] PID 10664: hack/common.sh:244: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO]          Stack Trace:
[INFO]            1: hack/common.sh:244: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO]            2: hack/build-go.sh:24: os::build::build_binaries
[INFO]   Exiting with code 1.
[ERROR] PID 10653: hack/update-generated-docs.sh:7: `"${OS_ROOT}/hack/build-go.sh" tools/gendocs tools/genman` exited with status 1.
[INFO]          Stack Trace:
[INFO]            1: hack/update-generated-docs.sh:7: `"${OS_ROOT}/hack/build-go.sh" tools/gendocs tools/genman`
[INFO]   Exiting with code 1.
```
@fabianofranz any ideas on the above?

**Comment by fabianofranz** [comment]
@jtslear never saw that, which `go version` are you using?

**Comment by jtslear** [comment]
@fabianofranz I'm using the vagrant dev environment in this case.
```
[vagrant@localhost origin]$ go version
go version go1.5.4 linux/amd64
```

**Comment by fabianofranz** [comment]
@jtescher that might be the reason, we target at Go 1.6+ for building `oc` and running `./hack/update-generated-docs.sh`. Make sure you are up-to-date.

**Comment by jtescher** [comment]
@fabianofranz s/jtescher/jtslear/

**Comment by fabianofranz** [comment]
> s/jtescher/jtslear/

oops sorry, @jtslear ^

**Comment by jtslear** [comment]
Assuming this builds properly, should I squash these two commits?

**Comment by jtslear** [comment]
:boom: @fabianofranz , it's now ready for review :-)

**Comment by fabianofranz** [comment]
@jtslear yes, please squash into one commit. Thanks for the PR!

**Comment by jtslear** [comment]
@fabianofranz tis done.

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by fabianofranz** [comment]
Flaked on https://github.com/openshift/origin/issues/11094
re[merge]

**Pull request merged**
