### PR TITLE
Minor: Remove stale omitempty comment in server types

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
trivial change @openshift/api-review

**Comment by imcsk8** [comment]
LGTM

**Comment by adelton** [comment]
LGTM, ack. This fixes the omission from 14617117fc680fe3f3a706cea57a923939d710fa.

**Comment by deads2k** [comment]
check the internal types, make them match, and fix your verify

/approve

**Comment by pravisankar** [comment]
Added missing auto generated swagger docs

**Comment by adelton** [comment]
Would it make sense to squash those two commits together?

/test unit

**Comment by pravisankar** [comment]
On Wed, Oct 4, 2017 at 11:57 PM, Jan Pazdziora <notifications@github.com>
wrote:

> Would it make sense to squash those two commits together?
>
done

**Comment by pravisankar** [comment]
test flake: cannot allocate memory
```
[WARNING] `go test` had the following output to stderr:
# testmain
2017/10/05 07:20:04 error reading input:  read /usr/lib/golang/pkg/linux_amd64_race/flag.a: cannot allocate memory
# testmain
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: error: ld returned 1 exit status
```

**Comment by pravisankar** [comment]
@adelton @deads2k one of you slap the approve tag again

**Pull request merged**
