### PR TITLE
RPMs: manipulate images path conditionally based on rpm %{dist}

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
Ok, if dist = el7ose then you get
`--images=registry.access.redhat.com/openshift3_beta/ose-${component}:${version}`
else you get 
`--images=openshift/origin-${component}:${version}`

If building with tito locally you'll need to add the following to your build command, there may be some way to do this automatically via tito.props
`--rpmbuild-options='--define "dist el7ose"'`

**Comment by sdodson** [comment]
@brenton PTAL

**Comment by sosiouxme** [comment]
*Looks* good... I assume we're going to put the necessary version tags on the docker images in registry.access.redhat.com?

**Comment by sdodson** [comment]
I believe Brenton is tagging the images with versions prior to pushing them.

**Comment by brenton** [comment]
@sdodson, I haven't tagged anything explicitly yet.  Let me sync with ejacobs to see if we wants this for beta1 or not.  We could technically get by with just using the latest tags.

**Comment by smarterclayton** [comment]
I don't think we should drop this.

**Comment by smarterclayton** [comment]
* Unless we absolutely have to.

**Comment by sosiouxme** [comment]
@smarterclayton suggested we hardcode "beta1" as the version injected by the specfile, unless we can get tito to inject the version (0.3.0-git.42.afe2a53...) correctly. This should help us when we need to push updates (beta1 or future). Whatever we put in there has to be a valid tag that we can apply in registry.access.redhat.com

**Comment by sdodson** [comment]
I think I can get tito to buid the proper ldflags from on os::build::ldflags in hack/common.sh which would fix `openshift version` which I imagine is requisite for image versions to work properly.

**Comment by smarterclayton** [comment]
Tito just needs to set a tag?

----- Original Message -----

**Comment by sdodson** [comment]
@smarterclayton The problem arises in the fact that brew doesn't build the RPMs from a git checkout. However `tito build` and `tito tag` do happen locally in the git checkout before shipping things off to brew. So I'm going to source hack/common.sh and store the ldflags generated from os::build::ldflags() in a specfile global and use that.

I spoke with Adam Miller a bit about why we're building via `go build` rather than `hack/build-go.sh` and I don't think we'll get that sorted out quickly enough to consider using `hack/build-go.sh` to build the RPMs.

**Comment by sdodson** [comment]
And yes, tito creates a tag of it's own when releasing like 'openshift-0.2.1-4'

**Comment by smarterclayton** [comment]
> On Feb 6, 2015, at 12:10 PM, Scott Dodson <notifications@github.com> wrote:
> 
> @smarterclayton The problem arises in the fact that brew doesn't build the RPMs from a git checkout. However tito build and tito tag do happen locally in the git checkout before shipping things off to brew. So I'm going to source hack/common.sh and store the ldflags generated from os::build::ldflags() in a specfile global and use that.
> 
We should already support loading those from a file - if possible making those fit together would be ideal.

> I spoke with Adam Miller a bit about why we're building via go build rather than hack/build-go.sh and I don't think we'll get that sorted out quickly enough to consider using hack/build-go.sh to build the RPMs.
> 
Ultimately build-cross (even if we only run it for one arch) is our official build script and is what we should be using.  By beta2 I'd like to have rpms building from that - do you see an obstacle to that?

**Comment by sdodson** [comment]
@smarterclayton I'll look at using build-cross in the future. I was told that the hack/* scripts would not run inside a mock chroot but that may have changed since Adam looked at it last.

For now I've updated the tito custom builder/tagger to inject the value of os::build::ldflags into the RPM build process and I've verified that it yields sane results.

    sdodson@sdodson: ~/git/Openshift/origin (set-images-format)$ openshift version
    openshift v0.2.2-131-ge9d5726cc2a554
    kubernetes v0.10.0-46-g72ad4f1

**Comment by smarterclayton** [comment]
K

----- Original Message -----

**Comment by sdodson** [comment]
Ok, ${version} is in after verifying RCM steps. Can we merge this now?

**Comment by smarterclayton** [comment]
LGTM

**Comment by sdodson** [comment]
[merge]

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
