### PR TITLE
Clean up e2e and enable testing in parallel

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes various broken parts of e2e tests after the rebase and introduces parallelism.

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton I'd be a much happier person if `core.sh` ran openshift tests and `kube.sh` ran upstream tests.  Do you have a fundamental objection?

**Comment by smarterclayton** [comment]
Not sure yet - we need to have a deeper discussion.  We definitely want to
be able to split their execution.  It's something to circle the wagons  on
before we add them to the merge queue, but that's in my short term radar.

**Comment by smarterclayton** [comment]
@jayunit100 see changes to e2e in Origin

**Comment by smarterclayton** [comment]
[merge] and will follow up with other tests later

**Comment by jayunit100** [comment]
`test-origin --extended core -d --skip-check --skip-image-cleanup` is the command needed, i think, to reproduce this?   not sure wether or not its ok to run the pure e2es as is or wether we need that vagrant plugin thing?

**Comment by jayunit100** [comment]
ah nvm, i guess `test/extended/core.sh` is the one we can use.

**Pull request merged**
