### PR TITLE
WIP - Bug 1765294: Add debug info in pull secret deletion tests

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@adambkaplan maybe link this one with Bug 1765294?

**Comment by dmage** [comment]
/retitle WIP - Bug 1765294: Debug flaking pull secret deletion test

**Comment by adambkaplan** [comment]
/retest

/assign @bparees 

This helps with debugging the flaking test, but it's still very unclear why OCM isn't deleting these secrets properly.

**Comment by adambkaplan** [comment]
@bparees can we green-button this to improve our debugging of the BZ?

GCP is flaking hard on this test (at least half of the current crop of failures include this test).

**Comment by adambkaplan** [comment]
/close

Replaced by #24226

**Pull request closed without merging**
