### PR TITLE
UPSTREAM: 49230: use informers for quota calculation

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1473042
bug 1473042

see: https://github.com/kubernetes/kubernetes/pull/49230

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
@deads2k - please review.

/cc @eparis @smarterclayton -- assuming we list all the referenced resources in our existing controller, this will improve the responsiveness of resource quota controller with out having a major memory impact.  opening this to evaluate for release-3.6 or soon after.

**Comment by smarterclayton** [comment]
I can't see how this is worse than today, so +1 by me.

**Comment by derekwaynecarr** [comment]
@smarterclayton - are we listing configmaps today in controllers, that is my only concern right now, but ran out of time to check at moment.

**Comment by smarterclayton** [comment]
GC lists everything

**Comment by deads2k** [comment]
I'm assuming it picked clean?  If so, lgtm.

**Comment by derekwaynecarr** [comment]
@deads2k 
i had to fixup for older machinery stuff, but yeah, clean for the most part.

[merge][severity:blocker]

**Pull request merged**
