### PR TITLE
Warn about deprecated commands

### LINKED ISSUE #15932: Deprecate any remaining legacy auth policy users in 3.7 release notes
Deprecate the following in 3.7 so we can remove them in 3.8:

1. Gated commands
2. The use of `oadm policy` commands against an older cluster (i.e. stop using the proxied endpoints internally in the server and via the client)
3. ??

cc @openshift/api-review @openshift/cli-review

### PR DESCRIPTION
**Pull request by simo5**
These commands still work against 3.6 servers, but we should start
warning that they will stop working once 3.7 is used.

Fixes #15932

### CODE REVIEW

**Comment by simo5** [comment]
@enj PTAL

**Comment by enj** [comment]
@simo5 wrong approach, please see these examples:

https://github.com/openshift/origin/blob/ce7709e81b90e24aebfb5366001645a7e7d78fd8/pkg/oc/admin/validate/node.go#L54

https://github.com/openshift/origin/blob/acd6597cd420914ef60b05de4e69cf1b0fae08c4/pkg/oc/admin/admin.go#L125-L137

**Comment by simo5** [comment]
@enj ok changed, PTAL

**Comment by simo5** [comment]
@enj all test pass and I would like to get this into 3.7 as it is not a code change

**Comment by enj** [comment]
/lgtm
/kind bug

@openshift/cli-review please approve.

**Comment by enj** [comment]
Added approved per @juanvallejo approval.

**Pull request merged**
