### PR TITLE
[Router] Use the consistent logic for determining values of boolean environment variables

### PR DESCRIPTION
**Pull request by louyihua**
Currently, there are different logics in different codes when determine a boolean environment variable is true or not. This PR makes such determination consistent so that a single environment variable will be treated as the same boolean value everywhere.

### CODE REVIEW

**Comment by csrwng** [comment]
/unassign
@openshift/sig-networking

**Comment by louyihua** [comment]
Seems another flake?

**Comment by smarterclayton** [comment]
This is not backwards compatible with old configs.  We can't merge this, because we would break anyone who depends on this behavior.

**Comment by smarterclayton** [comment]
This needs to be reverted.

**Comment by smarterclayton** [comment]
I'll caveat that with - it's unlikely this broke someone who set TRUE, got false, and was happy with that behavior.  However, changes like this are extremely dangerous because they could break old routers.  It's not clear to me that we should allow a change that tightens validation in this case (withholding revert decision right now)

**Pull request merged**
