### PR TITLE
Don't error when resource is deleted in TestEtcdStoragePath

### PR DESCRIPTION
**Pull request by smarterclayton**
[test] @enj this has flaked a lot recently

### CODE REVIEW

**Comment by enj** [comment]
This change is incorrect.  At worst you should be able to retry the delete until it is successful, but I see no reason to ignore the not found error.

**Comment by smarterclayton** [comment]
You're deleting something.  If it's not found... it no longer exists.  Your test doesn't take into account garbage collection ordering, namespace deletion, or a few other edge cases, so if you want to dig into that, see the linked jobs.

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/2378/testReport/junit/github/com_openshift_origin_test_integration%20%20%20/TestEtcd2StoragePath/

```
I0618 21:02:17.743573   16359 handler.go:146] kube-apiserver: POST "/api/v1/securitycontextconstraints" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.745205   16359 wrap.go:42] POST /api/v1/securitycontextconstraints: (1.837544ms) 201 [[Go-http-client/2.0] 127.0.0.1:52402]
I0618 21:02:17.752829   16359 handler.go:146] kube-apiserver: GET "/apis/extensions/v1beta1/thirdpartyresources" satisfied by gorestful with webservice /apis/extensions/v1beta1
I0618 21:02:17.753489   16359 wrap.go:42] GET /apis/extensions/v1beta1/thirdpartyresources: (839.205µs) 200 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
I0618 21:02:17.761377   16359 handler.go:146] kube-apiserver: GET "/api/v1/namespaces/kube-system" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.761414   16359 wrap.go:42] GET /api/v1/namespaces/kube-system: (200.904µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
I0618 21:02:17.762138   16359 handler.go:146] kube-apiserver: POST "/api/v1/namespaces" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.762172   16359 wrap.go:42] POST /api/v1/namespaces: (236.951µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
E0618 21:02:17.762399   16359 controller.go:149] unable to create required kubernetes system namespace kube-system: the server could not find the requested resource (post namespaces)
I0618 21:02:17.762739   16359 handler.go:146] kube-apiserver: GET "/api/v1/namespaces/kube-public" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.762777   16359 wrap.go:42] GET /api/v1/namespaces/kube-public: (190.113µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
I0618 21:02:17.763302   16359 handler.go:146] kube-apiserver: POST "/api/v1/namespaces" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.763344   16359 wrap.go:42] POST /api/v1/namespaces: (184.229µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
E0618 21:02:17.763517   16359 controller.go:149] unable to create required kubernetes system namespace kube-public: the server could not find the requested resource (post namespaces)
I0618 21:02:17.784181   16359 handler.go:146] kube-apiserver: GET "/api/v1/namespaces/default" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.784217   16359 wrap.go:42] GET /api/v1/namespaces/default: (200.618µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
I0618 21:02:17.784836   16359 handler.go:146] kube-apiserver: POST "/api/v1/namespaces" satisfied by gorestful with webservice /api/v1
I0618 21:02:17.784875   16359 wrap.go:42] POST /api/v1/namespaces: (198.902µs) 404 [[integration.test/v1.6.1+5115d708d7 (linux/amd64) kubernetes/3a5b733] 127.0.0.1:52402]
E0618 21:02:17.785139   16359 controller.go:162] unable to sync kubernetes service: the server could not find the requested resource (post namespaces)
I0618 21:02:18.076243   16359 request.go:638] Throttling request took 330.031972ms, request: DELETE:https://127.0.0.1:12000/api/v1/securitycontextconstraints/scc1
I0618 21:02:18.076861   16359 handler.go:146] kube-apiserver: DELETE "/api/v1/securitycontextconstraints/scc1" satisfied by gorestful with webservice /api/v1
I0618 21:02:18.076915   16359 wrap.go:42] DELETE /api/v1/securitycontextconstraints/scc1: (270.942µs) 404 [[Go-http-client/2.0] 127.0.0.1:52402]
```

**Comment by smarterclayton** [comment]
If you want to take over this please do.  Also, double check that you aren't hitting timing errors on your test - i.e. if you've got edge cases with respect to admission controllers, my series of PRs to reduce the number of caches is absolutely going to cause you to hit more of them (we're running with fewer and fewer cache mutation detectors, which means everything speeds up proportionally more)

**Comment by enj** [comment]
The two flakes I have seen so far were for the SCC and OAuth client objects.  I did not think the GC interacted with those objects.  Namespace deletion should not be a factor.  This has not been an issue before, so what exactly has changed?  I feel like ignoring those errors may mask other issues.

**Comment by smarterclayton** [comment]
```
E0618 21:02:17.762399   16359 controller.go:149] unable to create required kubernetes system namespace kube-system: the server could not find the requested resource (post namespaces)
```

That's incredibly suspicious.

**Comment by smarterclayton** [comment]
You're running in etcd2 mode - you should double check all the sanity assumptions for etcd in the test:

1. you have quorum on
2. you have etcd on fast storage
3. you are waiting for etcd to converge on membership before starting (the loop in etcdserver/run.go)

It kind of looks like something deleted a huge chunk of resources out of etcd here though.

**Comment by enj** [comment]
Superseded by #14969

**Pull request closed without merging**
