### PR TITLE
Use `oc get --raw` instead of `curl` in Swagger verification/update scripts

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

FYI @bparees 
@smarterclayton PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
format it.

**Comment by stevekuznetsov** [comment]
ack

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@smarterclayton  this is ready

**Comment by smarterclayton** [comment]
lgtm [merge]

**Pull request merged**
