### PR TITLE
Check for closed watches in deployerPodInvariantChecker

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @mfojtik 

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1694172

### CODE REVIEW

**Comment by dgoodwin** [comment]
Is this fix related to https://bugzilla.redhat.com/show_bug.cgi?id=1695048 (via @mfojtik)

**Comment by mfojtik** [comment]
@dgoodwin this is only fixing the empty type in events, that BZ is related to invalid subject access review request sent to apiserver. Auth team is investigating.

**Comment by dgoodwin** [comment]
I see, thanks.

**Pull request merged**
