### PR TITLE
test/extended/operators: include cluster-monitoring-operator 

### PR DESCRIPTION
**Pull request by paulfantom**
Test if cluster-monitoring-operator is reporting relatedObjects in its status.

Related to https://github.com/openshift/cluster-monitoring-operator/pull/373

/cc @s-urbaniak @sanchezl

### CODE REVIEW

**Comment by paulfantom** [comment]
All green now. Could I get correct labels to merge it?

/cc @s-urbaniak @bparees @deads2k @smarterclayton

**Comment by bparees** [comment]
@s-urbaniak i think you sabotaged your lgtm w/ the trailing emoji.

/lgtm

**Pull request merged**
