### PR TITLE
Bug 1866789: Remove problematic upstream client plugin test

### PR DESCRIPTION
**Pull request by akram**
@waveywaves @jkhelil fyi

### CODE REVIEW

**Comment by akram** [comment]
Blocks https://github.com/openshift/jenkins/pull/1107

**Comment by akram** [comment]
/retitle Bug 1866789: Remove problematic upstream client plugin test

**Comment by gabemontero** [comment]
@akram .... do you envision ever updating jenkins client plugin for 3.11 moving forward?

The client plugin e2e's I added in https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/jenkins-client-plugin technically only validate against OCP 4.x

I'm fine with merging this to unblock say jenkins core/dependent plugin security fixes, but *IF* you ever updating the client plugin on 3.11 (I personally think you should *NOT* because 3.11 is EOL .... only consider it if some major security flaw is identified), then either you guys have to validate it manually and hope for the best, or you create a 3.11 branch for client plugin based on whatever commit level is shipped there and create 3.11 versions of the plugin e2e's like what you see at https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/origin

Again, I think that is overkill, but want to make sure you are fully aware of the implications of removing this test here.

**Comment by akram** [comment]
for extended_builds  there are panic on many kubectl calls:
```
    error running &{/usr/bin/kubectl [kubectl --server=https://internal-api.ci-op-2lh6q0il-7a04a.origin-ci-int-gce.dev.rhcloud.com:8443 --kubeconfig=/tmp/admin.kubeconfig exec --namespace=e2e-tests-persistent-local-volumes-test-9lqtf security-context-98786517-d7f4-11ea-a277-0a580a830036 -- /bin/sh -c cat /mnt/volume1/test-file] []  <nil>  runtime/cgo: pthread_create failed: Resource temporarily unavailable
    SIGABRT: abort
    PC=0x7f04c93e8387 m=9 sigcode=18446744073709551610
```

looks like a flake

/test extended_builds

**Comment by akram** [comment]
> @akram .... do you envision ever updating jenkins client plugin for 3.11 moving forward?
> 
> The client plugin e2e's I added in https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/jenkins-client-plugin technically only validate against OCP 4.x
> 
> I'm fine with merging this to unblock say jenkins core/dependent plugin security fixes, but _IF_ you ever updating the client plugin on 3.11 (I personally think you should _NOT_ because 3.11 is EOL .... only consider it if some major security flaw is identified), then either you guys have to validate it manually and hope for the best, or you create a 3.11 branch for client plugin based on whatever commit level is shipped there and create 3.11 versions of the plugin e2e's like what you see at https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/origin
> 
> Again, I think that is overkill, but want to make sure you are fully aware of the implications of removing this test here.

@gabemontero indeed, we will do the validations manually. The process gets more and more complex for us to deliver fixes for cve's. We cannot afford to have distinct branches for this plugins of for tests now.

**Comment by gabemontero** [comment]
/lgtm

I'm only a reviewer in 3.11 @akram 

we'll need an approver from the OWNERS file

/assign @bparees

**Comment by akram** [comment]
`unit` task  now failing with:
```
[INFO] hack/build-go.sh exited with code 0 after 00h 00m 05s
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerfilePath 20ms
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerfileFromScratch 10ms
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerBuildError 0s
FAIL: github.com/openshift/origin/pkg/build/builder TestPushError 0s
FAIL: github.com/openshift/origin/pkg/build/builder TestGetStrategyError 0s
```

Only these 5 tests related to Docker fails. Another empty commit PR seems to show the same error. A previous test was failing with:
```
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerfilePath 10ms
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerfileFromScratch 0s
FAIL: github.com/openshift/origin/pkg/build/builder TestDockerBuildError 0s
FAIL: github.com/openshift/origin/pkg/build/builder TestPushError 0s
FAIL: github.com/openshift/origin/pkg/build/builder TestGetStrategyError 0s
FAIL: github.com/openshift/origin/pkg/network/node TestEgressVXLANMonitor 10ms
```

Re-running all the others .

/retest

**Comment by akram** [comment]
RHEL repository flake:
```
leveldb-1.12.0-5.el7.1.x86_64: [Errno 256] No more mirrors to try.
```

/test e2e-gcp

**Comment by akram** [comment]
/test images

flake again and over again

**Comment by akram** [comment]
```
2:python-rados-12.2.11-0.el7.x86_64: [Errno 256] No more mirrors to try.
``` 

/test e2e-gcp

**Comment by mtnbikenc** [comment]
Ignore me.
/test extended_builds

**Comment by waveywaves** [comment]
These tests are bound to fail, hence the reason for this PR which eliminates them. @akram can you confirm this ?
Can we override this PR ?

**Pull request merged**
