### PR TITLE
UPSTREAM: 66085: fix updateJob scheduling of resync

### PR DESCRIPTION
**Pull request by soltysh**
/assign @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
this looks fine, but was there a bug this was fixing? I couldn't actually find anything the old job was used for that looked problematic

**Comment by soltysh** [comment]
Other than https://github.com/kubernetes/kubernetes/issues/66071 I don't recall, but I figured out that this is important part of the controller so it's better to cherry pick it.

**Pull request merged**
