### PR TITLE
Bug 1711535: Convert tbe e2e to integration test

### PR DESCRIPTION
**Pull request by damemi**
Upstream changes from https://github.com/kubernetes/kubernetes/pull/81856

This is an update to a PR that was originally opened to do this, https://github.com/openshift/origin/pull/23523

### CODE REVIEW

**Comment by damemi** [comment]
The PR upstream has review comments saying it looks good at this point, just can't merge until master opens up again. So I've updated this PR with that feedback. I also brought in changes from another PR to get the stateless functionality for `ApplyFeatureGates`. So I'm ready for more review on this
/hold cancel

**Comment by soltysh** [comment]
Looks like you need to update the upstream version too. We'll merge this after the rebase lands, so I wouldn't hurry with updating the origin version until after we merge the rebase branch back to master.

**Comment by damemi** [comment]
/hold
for upstream merge/rebase

**Comment by damemi** [comment]
Upstream PR has been approved, so I've updated this with those changes

**Comment by damemi** [comment]
/hold cancel
once 4.3 master is open this will be ready to merge

**Comment by damemi** [comment]
Updated to include changes from https://github.com/kubernetes/kubernetes/pull/84766

**Pull request merged**
