### PR TITLE
use secret refs for redis password value so it is not exposed on the console

### PR DESCRIPTION
**Pull request by bparees**
bug 1233513

### CODE REVIEW

**Comment by bparees** [comment]
@coreydaley ptal

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/10773
[test]

**Comment by coreydaley** [comment]
@bparees lgtm, except your bindata needs regenerated
hack/update-generated-bindata.sh should do it for you

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
