### PR TITLE
[WIP] Fix cluster up on Windows

### PR DESCRIPTION
**Pull request by juanvallejo**
Work in progress...
Attempt to make `oc cluster up` work on Windows.

Currently fails with `Error: open /etc/resolv.conf: The system cannot find the path specified`
here: https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/clusterup/kubelet/dns.go#L27

cc @soltysh @deads2k @csrwng

### CODE REVIEW

**Comment by deads2k** [comment]
@mfojtik @csrwng should this be an active project right now?

**Comment by csrwng** [comment]
I vote for holding for now until we decide what to do

**Comment by mfojtik** [comment]
agree with @csrwng lets hold on this

**Comment by soltysh** [comment]
From the discussion I've had yesterday with @mfojtik my understanding is that we will want to have it working on windows machines, has anything changed between yesterday and now?

**Pull request closed without merging**
