### PR TITLE
UPSTREAM: 76455: More flake fixes in HPA legacy tests

### PR DESCRIPTION
**Pull request by joelsmith**
See https://github.com/kubernetes/kubernetes/pull/76455
This is the second half of the fixes from the upstream PR. Hopefully it will take care of https://bugzilla.redhat.com/show_bug.cgi?id=1695326
(Here's the first half: #22531)

### CODE REVIEW

**Comment by joelsmith** [comment]
@RobertKrawitz PTAL. Thanks!

**Comment by joelsmith** [comment]
It's reading from the chan (and ignoring what it reads), not writing to it. So it's waiting for at least one event to come through on the chan before proceeding.

**Comment by RobertKrawitz** [comment]
> It's reading from the chan (and ignoring what it reads), not writing to it. So it's waiting for at least one event to come through on the chan before proceeding.

+1

**Comment by RobertKrawitz** [comment]
/lgtm cancel
The UT failure looks like it's unrelated, but please verify that.

**Comment by joelsmith** [comment]
Looks like the unit test was just an unrelated flake as suspected. And now we wait another 2 hours to see if we can get e2e-aws-serial to pass.
/retest

**Comment by RobertKrawitz** [comment]
/lgtm

UT flakes aren't at all good, but there's no apparent connection between what failed and the test that this fixes.

**Pull request merged**
