### PR TITLE
SDN-5567: virt: add GA placeholder test

### PR DESCRIPTION
**Pull request by maiqueb**

### CODE REVIEW

**Comment by maiqueb** [comment]
@JoelSpeed as you can see in the last test execution logs, the new placeholder test now runs: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29375/pull-ci-openshift-origin-master-e2e-aws-ovn-virt-techpreview/1868669637495885824

Once this is in, we can add the stable lanes.

**Comment by JoelSpeed** [comment]
Looks like verify has failed because of some code generation, can you try and get that fixed please?

**Comment by maiqueb** [comment]
> Looks like verify has failed because of some code generation, can you try and get that fixed please?

Fixed @JoelSpeed o/

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by maiqueb** [comment]
@JoelSpeed had to rebase. 

Could you re-add your LGTM ? maybe wait after `verify` succeeds

**Pull request merged**
