### PR TITLE
[POST-REBASE] Fix //TODO: move me to kcmdutil

### PR DESCRIPTION
**Pull request by shiywang**

### CODE REVIEW

**Comment by smarterclayton** [comment]
lgtm

**Comment by smarterclayton** [comment]
Actually, I don't see Kube ErrExit in place in 1.5

**Comment by shiywang** [comment]
@smarterclayton click the wrong milestone, thanks, can we merge this ?

**Comment by smarterclayton** [comment]
The code that this replaces isn't in Origin yet - ErrExit must be checked, but I don't see that in the vendored kubernetes.

**Comment by shiywang** [comment]
@smarterclayton oh, yes, Kube [ErrExit](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go#L108) named a little different than  Origin [ErrExit](https://github.com/openshift/origin/blob/master/pkg/cmd/util/cmd.go#L22) Do you think I should change one of them to match this error message ?

**Comment by pweil-** [comment]
@openshift/cli-review

**Comment by pweil-** [comment]
[test]

**Pull request closed without merging**
