### PR TITLE
Don't default node selector for openshift admin manag-node cmd

### LINKED ISSUE #2384: osadm manage-node --list-pods should error
It currently returns nothing and exit code 0

### PR DESCRIPTION
**Pull request by pravisankar**
fixes #2384

### CODE REVIEW

**Comment by pravisankar** [comment]
@deads2k @fabianofranz PTAL

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by pravisankar** [comment]
[merge]

**Comment by pravisankar** [comment]
spurious failure, [merge]

**Pull request merged**
