### PR TITLE
Bug 1989169: Enable "Unidling should work with TCP" tests

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
the two "Unidling should work with TCP" tests did pass in this recent job:
  https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26460/pull-ci-openshift-origin-master-e2e-gcp/1437774641639723008
  
  
  I will continue to /test e2e-gcp on this PR so we can get a sense of how flaky the tests really are. There is a new
  bug filed to track any dev work that will be required to un-flake these tests (assuming they are flaky):
    https://bugzilla.redhat.com/show_bug.cgi?id=2003228

**Comment by jluhrsen** [comment]
for reference, the PR test dashboard: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=origin&pr=26460

**Comment by flavio-fernandes** [comment]
/lgtm
☺️

**Comment by jluhrsen** [comment]
@danwinship , I think these tests are no longer flaking. I ran the job 10 times in a row without a failure. you can
see it here: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=origin&pr=26460

I think it's safe to merge this.

**Comment by danwinship** [comment]
The bug is about them flaking under ovn-kubernetes. It appears that no ovn tests are being run by default in origin master right now? So you'd have to manually
/test e2e-aws-ovn
/test e2e-gcp-ovn

**Comment by danwinship** [comment]
hm, no gcp ovn job here
/test e2e-metal-ipi-ovn-dualstack

**Comment by jluhrsen** [comment]
> The bug is about them flaking under ovn-kubernetes. It appears that no ovn tests are being run by default in origin master right now? So you'd have to manually
> /test e2e-aws-ovn
> /test e2e-gcp-ovn

doh! I knew that. my bad. I saw the e2e-aws-ovn came back now and it did have one failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26460/pull-ci-openshift-origin-master-e2e-aws-ovn/1440695779755823104

This is the bz I filed to get these tests un-flakey:
  https://bugzilla.redhat.com/show_bug.cgi?id=2003228

**Comment by yselkowitz** [comment]
Are you sure about this? `[sig-network-edge][Feature:Idling] Unidling should handle many TCP connections by possibly dropping those over a certain bound [Serial] [Suite:openshift/conformance/serial]` has been consistently failing with OVN on ARM.

**Comment by jluhrsen** [comment]
> Are you sure about this? `[sig-network-edge][Feature:Idling] Unidling should handle many TCP connections by possibly dropping those over a certain bound [Serial] [Suite:openshift/conformance/serial]` has been consistently failing with OVN on ARM.

correct. I noted up in https://github.com/openshift/origin/pull/26460#issuecomment-925105728 that we need a bug to
get resolved so that the ovn version of this test will pass. I think I need to put a:

/hold

**Comment by danwinship** [comment]
> Are you sure about this? `[sig-network-edge][Feature:Idling] Unidling should handle many TCP connections by possibly dropping those over a certain bound [Serial] [Suite:openshift/conformance/serial]` has been consistently failing with OVN on ARM.

oh, where is that? I couldn't find any 4.10 ovn+serial tests in the testgrid

**Comment by yselkowitz** [comment]
FYI @deepsm007 this is a case that would benefit from aws-ovn-serial e2e.

**Comment by yselkowitz** [comment]
Please note that this test falls within the serial suite, and afaik there still isn't an e2e-aws-ovn-serial or equivalent to properly test this.  cc @deepsm007

**Comment by jluhrsen** [comment]
> Please note that this test falls within the serial suite, and afaik there still isn't an e2e-aws-ovn-serial or equivalent to properly test this. cc @deepsm007

I think it fails in the e2e-aws-ovn job too. At least it did [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26460/pull-ci-openshift-origin-master-e2e-aws-ovn/1441098575961395200) when I ran it last time. I was just going through my open PRs
this morning and figured to re-test it just to see if it somehow was magically fixed without anyone actually updating the [bz](https://bugzilla.redhat.com/show_bug.cgi?id=2003228).

**Pull request closed without merging**
