### PR TITLE
k8s 1.25.0

### PR DESCRIPTION
**Pull request by soltysh**
This brings back https://github.com/openshift/origin/pull/27416 which was reverted in https://github.com/openshift/origin/pull/27489

/hold 
until we solve problem with https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade/1583337789200535552

### CODE REVIEW

**Comment by stlaz** [comment]
/test lint
looks like a poorly written test job

**Comment by stbenjam** [comment]
/payload 4.12 ci blocking

Retesting for confirmation.  We don't want to reintroduce this just yet since we got a streak of 6 rejected payloads and then it stopped once this was reverted, but the above payload command did succeed.  The problems could've been something with infra... but I can't tell for sure from the logs.

**Comment by gnufied** [comment]
This also broke *all* CSI tests. I can't even do a `--dry-run`:

```
╰─redhat/vmware-vsphere-csi-driver-operator> TEST_CSI_DRIVER_FILES=./test/e2e/manifest.yaml ~/redhat/origin/openshift-tests run --dry-run openshift/csi
Oct 27 15:07:47.205: INFO: Driver loaded from path [./test/e2e/manifest.yaml]: &{DriverInfo:{Name:csi.vsphere.vmware.com InTreePluginName: FeatureTag: MaxFileSize:0 SupportedSizeRange:{Max:64Ti Min:1Gi} SupportedFsType:map[:{} ext4:{} xfs:{}] SupportedMountOption:map[dirsync:{}] RequiredMountOption:map[] Capabilities:map[block:true controllerExpansion:true exec:true fsGroup:true nodeExpansion:true offlineExpansion:true onlineExpansion:true persistence:true snapshotDataSource:false volumeLimits:false] RequiredAccessModes:[] TopologyKeys:[] NumAllowedTopologies:0 StressTestOptions:<nil> VolumeSnapshotStressTestOptions:<nil> PerformanceTestOptions:<nil>} StorageClass:{FromName:false FromFile: FromExistingClassName:thin-csi} SnapshotClass:{FromName:true FromFile: FromExistingClassName:} InlineVolumes:[] ClientNodeName: Timeouts:map[]}
Oct 27 15:07:47.220: INFO: Enabling in-tree volume drivers
panic: unable to find test External Storage [Driver: csi.vsphere.vmware.com] [Testpattern: Dynamic PV (default fs)] capacity provides storage capacity information

goroutine 1 [running]:
github.com/openshift/origin/pkg/test/ginkgo.testsForSuite.func1({0xc0055eccf0, 0x87}, {0x9366620, 0xc00564eee0})
        github.com/openshift/origin/pkg/test/ginkgo/ginkgo.go:23 +0x234
github.com/onsi/ginkgo/v2/internal.(*Suite).WalkTests(0xc0002de000, 0xc002efc9f0)
        github.com/onsi/ginkgo/v2@v2.1.5-0.20220909190140-b488ab12695a/internal/suite_patch.go:26 +0x12b
github.com/openshift/origin/pkg/test/ginkgo.testsForSuite()
        github.com/openshift/origin/pkg/test/ginkgo/ginkgo.go:19 +0xb7
github.com/openshift/origin/pkg/test/ginkgo.(*Options).Run(0xc0001ce540, 0xc4ab400, {0x8649c87, 0xf})
        github.com/openshift/origin/pkg/test/ginkgo/cmd_runsuite.go:153 +0x185
main.newRunCommand.func1.1()
        github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:320 +0x2d4
main.mirrorToFile(0x3a4b711?, 0xc0018c8000?)
        github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:457 +0x102
main.newRunCommand.func1(0xc001892c80?, {0xc0015cf9c0?, 0x2?, 0x2?})
        github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:301 +0x5c
github.com/spf13/cobra.(*Command).execute(0xc001892c80, {0xc0015cf9a0, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001892a00)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main.func1(0xc0018c8600?)
        github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:93 +0x8a
main.main()
        github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:94 +0x476
╭─ lakealder☯  ⸙-1.19.1   openshift:master                                         
```

**Pull request merged**
