### PR TITLE
UPSTREAM: <carry>: Fix to avoid REST API calls at log level 2.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr @eparis 

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1414813

### CODE REVIEW

**Comment by ncdc** [comment]
Commit message is incorrect. Needs to be `UPSTREAM: <carry>`

**Comment by aveshagarwal** [comment]
@ncdc fixed hopefully it is correct this time.

**Comment by derekwaynecarr** [comment]
LGTM [merge]

**Comment by eparis** [comment]
[test][merge] from whole internet being dead

**Comment by derekwaynecarr** [comment]
[test] [merge]

**Comment by eparis** [comment]
(FYI, i think they have merge turned off for rebase)

**Comment by derekwaynecarr** [comment]
@eparis -- thanks for the reminder, i was being dense.

**Comment by derekwaynecarr** [comment]
@eparis is there a merge-cancel action?

**Comment by eparis** [comment]
i think they just turned it off. so you can leave the tag.

**Comment by ncdc** [comment]
@aveshagarwal please rebase. New file location is vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/log.go

**Comment by aveshagarwal** [comment]
@ncdc fixed it. Thanks.

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
