### PR TITLE
Fix the client set generator

### PR DESCRIPTION
**Pull request by mfojtik**
- [x] fix the `APIPath` to point to `/oapi`
- [x] fix the non-namespaced types (projects, ...)
- [x] regenerate the client sets
- [x] add simple smoke test for the generated client set

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

@deads2k PTAL

**Comment by deads2k** [comment]
Do they work?

[test]

**Comment by mfojtik** [comment]
@deads2k guess we need some tests for them... I will work on it today/tomorrow.

**Comment by mfojtik** [comment]
@deads2k now they should work

**Comment by mfojtik** [comment]
(this have to wait for rebase first)

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@smarterclayton client sets can now be generated again, but I want to add a simple test that proves they work.

**Comment by deads2k** [comment]
My checklist:
* [ ] add a namespaced resource to the integration test
* [ ] confirm your verify script works (add one if you forgot to do it)
* [ ] followup issue to practice generating a shared clientset with multiple group.  We'll need to figure out how to do this for 1.5.

After that, I'd take this as a starting point.

**Comment by mfojtik** [comment]
@deads2k first and second bullet point should be already addressed here, I will create the follow up

**Comment by smarterclayton** [comment]
What's the first consumer of these client sets?

**Comment by mfojtik** [comment]
@deads2k https://github.com/openshift/origin/issues/10956

@smarterclayton an integration test :-) I think we can pick either deployments or builds and try to use the client set there. What are you thoughts?

**Comment by deads2k** [comment]
> What's the first consumer of these client sets?

Right now, I just want to make sure I have a way to generate them so we can shake out generation problems (one already found).

I see the next steps as: 
 1. no more non-generated clients.  You add a new API, use a generate clientset.
 1. prove that the generator can create a common clientset based on the `FutureGroupName` for two groups.

**Comment by mfojtik** [comment]
@deads2k do we want to migrate the existing controllers to use client sets at some point? (or maybe start with the CLI first)

**Comment by deads2k** [comment]
> @deads2k do we want to migrate the existing controllers to use client sets at some point? (or maybe start with the CLI first)

I think I'd try to generate a common clientset with `FutureGroupNames` first.  Getting there may force us to fix generator bugs in 1.5 for when we make the big switch.  In addition, it will give you the APIs you need to evaluate whether you can reasonably support new controller against old API servers.

After you've sorted that out, the CLI would probably be my next target.

**Comment by mfojtik** [comment]
@deads2k sound good to me.

**Comment by smarterclayton** [comment]
I'd prefer not to put these in our codebase if we can generate directly to
something like "openshift/client-go" and then back vendor them.

**Comment by liggitt** [comment]
Really? You wouldn't want to go the other direction? Generate here, then extract to client repo on version boundaries?

**Comment by smarterclayton** [comment]
I'm asking whether it helps or hurts.  Should our clients be generated
*onto* the versions provided by Kube in that client-go?  I.e. I don't want
Openshift and Kube client libraries to conflict in dependencies because we
extracted on a slightly different pkg/runtime boundary.

**Comment by deads2k** [comment]
> I'm asking whether it helps or hurts.  Should our clients be generated
> *onto* the versions provided by Kube in that client-go?  I.e. I don't want
> Openshift and Kube client libraries to conflict in dependencies because we
> extracted on a slightly different pkg/runtime boundary.

I hate having problems like this so much.  These aren't your grandfather's coding problems.  Oh wait, they are.

I think I'd still start with them here while we get the hang of actually generating something useful and deciding how we generate both grouped an ungrouped APIs in a sane inter-operable way.  Seems like for the short-term, we'd make sure we're compatible by godep-ing in the upstream client.

**Comment by smarterclayton** [comment]
We already godep in the upstream client.  It's just not split correctly yet.

**Comment by mfojtik** [comment]
@smarterclayton do we want to split it here in this PR or is this good for the start at least? The current generated client we have in repo is junk atm. This PR at least allows to experiment with it.

I agree with @deads2k that this is a good start and allows to experiment. I'm fine following up with improvements to generator to allow splitting and generating grouped/ungrouped APi clients.

**Comment by smarterclayton** [comment]
I'm fine with moving forward, but we need to be very clear before we start using them how we transition to external clients.

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@deads2k any final comments?

**Comment by deads2k** [comment]
> @deads2k any final comments?

Just a repeat of this: 

> I think I'd try to generate a common clientset with FutureGroupNames first. Getting there may force us to fix generator bugs in 1.5 for when we make the big switch. In addition, it will give you the APIs you need to evaluate whether you can reasonably support new controller against old API servers.

> After you've sorted that out, the CLI would probably be my next target.

If we can find problems with the generator before 1.5 ships, the next rebase will go easier.

[merge]

**Comment by mfojtik** [comment]
[merge] https://github.com/openshift/origin/pull/10861

**Comment by mfojtik** [comment]
[merge] https://github.com/openshift/origin/issues/11004

**Comment by mfojtik** [comment]
flake (https://github.com/openshift/origin/issues/8571)

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
