### PR TITLE
bug 1999288: [release-4.8]: bump openshift/kubernetes to the latest

### PR DESCRIPTION
**Pull request by ingvagabund**
To bring fixes from https://github.com/openshift/kubernetes/pull/1060

### CODE REVIEW

**Comment by ingvagabund** [comment]
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
    - [ ] verified
    - [x] does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
    - [ ] verified
    - [x] does not apply
3. For branches that are in the Maintenance lifecycle phase:
    - [x] The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or 
    - [ ] The bug is a security related bug
    - [ ] Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
    - [x] verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
    - [ ] verified
    - [x] does not apply

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
