### PR TITLE
Move extended build tests from ruby:2.x to ruby:2.5

### PR DESCRIPTION
**Pull request by adambkaplan**
Unblocks `e2e-aws-builds` - the `ruby:2.2` imagestreamtag was removed in openshift/cluster-samples-operator#158

### CODE REVIEW

**Comment by adambkaplan** [comment]
/retest

DNS for origin was pruned :/

**Comment by deads2k** [comment]
/hold

these files moving/moved in https://github.com/openshift/origin/pull/23453

**Comment by gabemontero** [comment]
/retitle "Bug 1754186: Move extended build tests from ruby:2.x to ruby:2.5"

**Pull request merged**
