### PR TITLE
TRT-1567: Revert #28589 "AUTH-483: Add a monitor test to check the existence of required-scc annotation in platform workloads"

### PR DESCRIPTION
**Pull request by DennisPeriquet**
Reverts #28589 ; tracked by [TRT-1567](https://issues.redhat.com//browse/TRT-1567)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

[4.16.0-0.ci-2024-03-16-025152](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.16.0-0.nightly/release/4.16.0-0.ci-2024-03-16-025152) is the first payload where this test failed the payload

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade
```

CC: @liouk

ps.  I noticed on https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregated-aws-ovn-upgrade-4.16-minor-release-openshift-release-analysis-aggregator/1768832918135771136 that although the aggregation points to https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade/1768832917330464768 as a failed job, the job passes.  So now, I'm wondering if this is an aggregation problem and not a test problem.  I see in your original PR that this should flake.

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/hold

I'm leaning toward this PR not being at fault.  But still not sure why the aggregator is calling this test a failure.

**Comment by DennisPeriquet** [comment]
i see this in the aggregated job summary:

```
: [sig-auth] all workloads in ns/openshift-must-gather-smq72 must set the 'openshift.io/required-scc' annotation expand_less | 0s
-- | --
{Passed 1 times, failed 0 times, skipped 0 times: we require at least 6 attempts to have a chance at success  name: '[sig-auth] all workloads in ns/openshift-must-gather-smq72 must set the ''openshift.io/required-scc''   annotation' testsuitename: openshift-tests summary: 'Passed 1 times, failed 0 times, skipped 0 times: we require at least 6 attempts   to have a chance at success' passes: - jobrunid: "1768832917330464768"   humanurl: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade/1768832917330464768   gcsartifacturl: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade/1768832917330464768/artifacts failures: [] skips: [] }
```

I think what's happening is that particular test passes only in 1 job but does not appear as passing in any other job; I checked 4 of the jobs and didn't see it in flaking or passing and that's probably what's causing the failure.

So now I wonder why is this test not running for all jobs? and if it is supposed to run for all jobs, then this revert makes sense.

**Comment by stbenjam** [comment]
/hold cancel
/approve
/lgtm

This needs to be reverted, dynamic names of namespaces should NOT be in test names.  So, it's causing payloads to fail and blowing up our table of known test names since each one is unique since it contains a namespace.

**Pull request merged**
