### PR TITLE
moved tools from cmd/ to tools/

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Looks like you need to update go files as well

**Comment by smarterclayton** [comment]
also move `hack/version.go` into its own `tools/godep-version` package

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Flake on waiting for `healthz` [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8149/console):
```
ERROR: gave up waiting for https://127.0.0.1:28443/healthz
```
#6031 

Everything built OK, though, ready for another look @smarterclayton

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
