### PR TITLE
Increase specificity of CSS .yaml-mode .ace-numeric style

### LINKED ISSUE #6415: Web console: incorrect number highlighting showing up in editor
We have a CSS rule to disable number highlighting in YAML files for Ace to avoid incorrect highlighting like this:

openshift_web_console

It's not being used, however:

openshift_web_console_and_web_console__warn_about_problems_with_routes_by_spadgett_ _pull_request__6353_ _openshift_origin

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #6415

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
