### PR TITLE
UPSTREAM: 44068: Use Docker API Version instead of docker version

### LINKED ISSUE #13281: Latest docker version breaks kubelet in 1.5.0-alpha.3
```
20s       20s       1         router-1-deploy           Pod                 Warning   FailedSync         {kubelet 10.34.129.45}   Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""
```

@csrwng @jimmidyson

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #13281 but builds on top of #14121 which fixes godeps, so that needs to land first when queue opens next week, so only 3 last commits count.

@derekwaynecarr ptal

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/14161
[test]

**Comment by soltysh** [comment]
Flake #14161
[test]

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/13693
[merge]

**Comment by soltysh** [comment]
Flake: https://github.com/openshift/origin/issues/10773
[merge]

**Comment by soltysh** [comment]
Flake: https://github.com/openshift/origin/issues/11016

[merge]

**Pull request merged**
