### PR TITLE
Added comment to clarify that oc cluster did not work on older releases

### PR DESCRIPTION
**Pull request by padajuan**
Added comment to clarify that oc cluster did not work on releases before 1.3.X.

### CODE REVIEW

**Comment by padajuan** [comment]
Related [issue](https://github.com/openshift/origin/issues/11580) opened

**Comment by padajuan** [comment]
The related [issue](https://github.com/openshift/origin/issues/11580)

**Comment by padajuan** [comment]
How could fail the CI build with a .md file modification? :D

**Comment by coreydaley** [comment]
@padajuan Currently all builds of origin on Travis CI are failing due to an issue that we are working on.  I'll go ahead and have this run through the Jenkins build system.

[test]

**Comment by coreydaley** [comment]
@padajuan Could you please clean up your pull request so that only the comment(s) you added are included? and not all of the end of line spaces that your editor removed.

**Comment by coreydaley** [comment]
Also fixes issue #11509

**Comment by csrwng** [comment]
@coreydaley @padajuan we already have a statement in the doc saying that 1.3 is required. 
Here: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#pre-requisites

Maybe what we should do is change the link to point to the latest 1.3.x release (https://github.com/openshift/origin/releases/tag/v1.3.1) explicitly until we figure out how to link to the latest.

**Comment by coreydaley** [comment]
@csrwng Then we will have to update the link every time there is a release of the 1.3.x version.  I don't think it's a bad idea to have another reminder about it near the link.

**Comment by csrwng** [comment]
@coreydaley right now the link takes you to the completely wrong location though... maybe we should then just link to the releases list (https://github.com/openshift/origin/releases/) and tell you near the link to find the release > 1.3

If we add the reminder near the link, we should also add it around every link

**Comment by coreydaley** [comment]
@padajuan You don't need to create a new pull request, you can just push your update to the same branch that you made the PR from.  Just an FYI.  https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by padajuan** [comment]
Yeah, my bad, I perform a git rebase erasing the las commit, then the PR closes it automatically :S, btw, there is another one, https://github.com/openshift/origin/pull/11585 , sorry about that

**Pull request closed without merging**
