### PR TITLE
remove oc cluster up experimental flags broken since 3.6.1

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/openshift/origin/issues/19234

`oc cluster up --logging` and `--metrics` were both experimental and both have been broken for a long time.  They didn't work as far back as 10 months ago here: https://github.com/openshift/origin/pull/14729, explicitly commented as failing 5 months ago here: https://github.com/openshift/origin/pull/17029, and now reported again here https://github.com/minishift/minishift/issues/2207.

The flags are experimental and apparently lightly used (4 releases of broken).  In addition, these components are trying to install in a way inconsistent with existing flow by directly injecting themselves into the running kubelet and running commands in its container.  Rather than save what we have, this pull cuts our losses and removes the code that doesn't work.  Any fresh attempt should follow the pattern we've established for other five components we have here: https://github.com/openshift/origin/tree/master/pkg/oc/bootstrap/clusterup/components .

@jcantrill @sdodson
@mfojtik @soltysh 
@smarterclayton @liggitt fyi

### CODE REVIEW

**Comment by deads2k** [comment]
@sdodson fyi

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/7760 May have just fixed it but I'd need @jcantrill to confirm

**Comment by deads2k** [comment]
> openshift/openshift-ansible#7760 May have just fixed it but I'd need @jcantrill to confirm. I have no strong opinions one way or the other on ensuring that logging and metrics continue to work for oc cluster up

@sdodson Was it broken for a year?  This hasn't worked since 3.6.1 at least.

**Comment by rgordill** [comment]
The problem for a long time ago has not been related with metrics and logging components, but with:
- Aligning metrics/logging upstream tags with origin ones: https://github.com/openshift/origin/issues/17676 
- "openshift-ansible" running in container: https://github.com/openshift/openshift-ansible/issues/7006

So if both are corrected, it should work. Indeed, I have them work with downstream version (aligned) and a workaround for the openshift-ansible dependencies (some extra packages installed).

From my experience, maybe logging is not needed in a dev environment, but metrics definitely, as they are a very helpful way to debug the CPU/memory consumption of an app, that is the first way to identify a memory leak or similar issues.

**Comment by mfojtik** [comment]
@deads2k how are we going to deal with this: https://github.com/mfojtik/origin/blob/4ad5bd470abff8cf241e94461b13cadcafdcbecb/pkg/oc/bootstrap/docker/up.go#L525

If we remove these components (or make them 'cluster add' components) then when somebody add them to cluster, we will need to adjust the web console url, right?

**Comment by deads2k** [comment]
> If we remove these components (or make them 'cluster add' components) then when somebody add them to cluster, we will need to adjust the web console url, right?

The problem isn't new.  Adding components can't be order dependent.  That leaves: discovered, controller managed, or manual edit on configmap.  I've got a controller if we want it.... https://github.com/openshift/origin/pull/19052

**Comment by deads2k** [comment]
> The problem for a long time ago has not been related with metrics and logging components, but with:
> 
> Aligning metrics/logging upstream tags with origin ones: #17676
> "openshift-ansible" running in container: openshift/openshift-ansible#7006
> So if both are corrected, it should work. Indeed, I have them work with downstream version (aligned) and a workaround for the openshift-ansible dependencies (some extra packages installed).

To be clear, none of us are against the feature.  We just want one that works and the current impl hasn't for a year.  So the bar is no longer "fix the break", but "make it work to begin with".  I'd be very happy to see logging and metrics sit alongside service-catalog and template-service-broker here: https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/clusteradd/cmd.go#L85-L111, but I don't think the existing, not working for a year, code is a step towards that.

**Comment by gbraad** [comment]
This also means `--service-catalog` is not part of the command options to
provide ?

**Comment by deads2k** [comment]
> This also means `--service-catalog` is not part of the command options to
> provide ?

That disappeared when `oc cluster add` became a thing.  Email forthcoming, but `--enable service-catalog` should do the trick

**Comment by mfojtik** [comment]
@jorgemoralespou the options will be listed (see https://github.com/openshift/origin/pull/19229 and https://github.com/openshift/origin/pull/19208/commits/8ad5537f88d33c3591f6b7120ccb8dda2c1d67b2#diff-83a38c5c15fee023e4ddb8c190f136c2R115)

Basically you can either use `--enable service-catalog,logging` or you can add them into existing cluster if you want to use them by `oc cluster add service-catalog,logging`. In future the list of components will expand as we will add more.

The `--service-catalog` and `--logging` flags are going to be removed. There is already PR in minishift repo that removing them.

**Comment by mfojtik** [comment]
/retest

(these 'FORWARD GCS CREDENTIALS TO REMOTE HOST' flakes are getting pretty annoying)

**Comment by jorgemoralespou** [comment]
@mfojtik I'm not good at go, but I think I only see service-catalog and
template-service-broker. That means that until a new oc binary lands a new
component will not be instantiable. Am I wrong?

**Comment by deads2k** [comment]
> @mfojtik I'm not good at go, but I think I only see service-catalog and
> template-service-broker. That means that until a new oc binary lands a new
> component will not be instantiable. Am I wrong?

@jorgemoralespou `--logging` and `--metrics` never worked in 3.9 and appear to have been failing in common cases (like minishift) since 3.6.1.  This doesn't break them (that happened before).  This removes the appearance that they work (they don't) and describes how they can be added when working install code is found.

**Comment by jorgemoralespou** [comment]
@deads2k I totally get it and understand, but what I'm concerned is that instead of trying to fix the underlying problem we just wipe it out. Then, if by any reason, we manage to make it work, we'll have to go back, change oc, wait for a new release,... and bringing incompatibilities between versions which complicates life of some users, minishift being one of them.

I would prefer we get @sdodson and whoever needs and fix the OpenShift ansible images. As Ramon said, the problem has easy fix and users have hacked it to make it work.

It's a shame we haven't been able to have this working since 3.6 IMHO. Not pointing anyone. I hope what I meant is properly understood.

**Comment by deads2k** [comment]
> @deads2k I totally get it and understand, but what I'm concerned is that instead of trying to fix the underlying problem we just wipe it out.

Claiming we didn't try to fix the underlying problem it isn't fair to any of us (me, @jcantrill, @sdodson).  When I first found out I looked at our code to see if looked like something that slipped during change we made recently, tracked pulls back to find the original failure, and raised the issue.  Once @jcantrill realized the issue, he asked for ansible help and tried to get it fixed.  And I know that @sdodson tried to fix it.  Stepping back and looking at the problems with the oc cluster up component install flow, it's not fair to say that we didn't try to fix it.

Looking at where all the other oc cluster up install components are (more are ready to move tomorrow) and understanding that we are dealing with a long broken thing, we need to reassess how it actually gets laid down and how we can sustainably deliver the feature.  The thinking of the past demonstratively failed.  We have a plan going forward.  We should work towards that.




> and bringing incompatibilities between versions which complicates life of some users, minishift being one of them.

3.10 is already a huge change.  I don't think that one more on the stack is that big a deal.  The summary I sent out of aos-devel shows how deep the changes go and gets on a componentized path with a different deployment model.

**Comment by jorgemoralespou** [comment]
@deads2k after reading the email sounds fair. I didn't mean to say you haven't tried to solve the issue, I'm just amazed that this issue is so complicated to solve.

Looking forward to test and contribute feedback to the new oc cluster. And thanks for the hard work.

**Comment by gbraad** [comment]
@deads2k willing to work more closely or sync more regularly with you guys... Concerned about but also interested in the coming changes. Hope to also make minishift an easy testbed for you to spin up test environments for this...

**Comment by deads2k** [comment]
> @deads2k willing to work more closely or sync more regularly with you guys... Concerned about but also interested in the coming changes. Hope to also make minishift an easy testbed for you to spin up test environments for this...

One of the requirements for adding the logging and metrics components is going to be CI tests in the existing `extended/clusterup.sh` file.  I don't think that origin CI is going to depend on minishift.

**Pull request merged**
