### PR TITLE
Restructure of mobile nav layout and presentation

### PR DESCRIPTION
**Pull request by sg00dwin**
Addresses https://github.com/openshift/origin/issues/3149

- [ ] Related - need to reduce label-filter min-width from 250px to 205px so that button doesn't wrap at 320px
 - change https://github.com/kubernetes-ui/label-selector/blob/master/styles/labelFilter.less#L29

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett Here's my pr and a list of remaining items

**Comment by sg00dwin** [comment]
@jwforres Revised nav

**Comment by jwforres** [comment]
@sg00dwin when you get back lets go ahead and deliver everything except the change that put the project nav in the same bar, if thats easy to do? This PR addresses other issues besides that right?

**Comment by sg00dwin** [comment]
screen shot 2015-08-25 at 1 57 15 pm

**Comment by sg00dwin** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
much better :)  [merge]

**Comment by spadgett** [comment]
Amazing what a difference one pixel makes.

Do we have a follow-on issue to get rid of the stacked hamburger menus?

**Comment by jwforres** [comment]
Opened https://github.com/openshift/origin/issues/4371

**Pull request merged**
