### PR TITLE
Add openshift/origin-gitserver to push-release.sh

### PR DESCRIPTION
**Pull request by csrwng**
Pushes gitserver regularly along with other openshift images

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @smarterclayton ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by liggitt** [comment]
believe it or not, this will conflict with https://github.com/openshift/origin/pull/5888 in the merge queue

**Comment by csrwng** [comment]
rebased [merge]

**Comment by csrwng** [comment]
[merge] again

**Comment by csrwng** [comment]
[test]

**Pull request merged**
