### PR TITLE
OCPBUGS-42237: bump ruby-3.0-ubi8 image to ruby-3.1-ubi8

### PR DESCRIPTION
**Pull request by sanchezl**
Fix tests that fail due to not finding ruby-3.0-ubi8 images.

### CODE REVIEW

**Comment by sanchezl** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1839118545531703296

**Comment by sanchezl** [comment]
* [previous job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1839118545531703296) still had some tests failing. Failing to find ruby:3.1-ubi8 tag (!?).
* rebased
* kicked off a [new job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1839353757872164864).

**Comment by adambkaplan** [comment]
/retitle OCPBUGS-42237: bump ruby-3.0-ubi8 image to ruby-3.1-ubi8

This is a band-aid over a ruby image EOL, caused by a samples operator upgrade. See [OKD-225](https://issues.redhat.com/browse/OKD-225).

The latest version of Ruby is `3.3-ubi9` - see full changes in [cluster-samples-operator#569](https://github.com/openshift/cluster-samples-operator/pull/569/files#diff-320a258d6cfe62a964e26d10c264fbe3b6e5af623a8025dc8af26f4258364ca2L158-L162)

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

**Comment by metlos** [comment]
/test e2e-gcp-ovn-image-ecosystem

I hope this is just a flakiness caused by the amount of time it takes for the build of the rails application to finish. The timeout is currently 10 minutes.

**Comment by metlos** [comment]
Trying to improve the situation by increasing the timeout to 15 minutes in https://github.com/openshift/origin/pull/29143

**Review by metlos — APPROVED** [review]

**Comment by metlos** [comment]
@sanchezl as I said above, the failure in the image-ecosystem testsuite was caused by flakiness caused by a low timeout. A repeated run of the job helped. I can't really comment on the failures in the `e2e-gcp-ovn` job in the `[sig-cli]` tests. I am unfamiliar with both the tests and the code they're testing.

**Comment by sanchezl** [comment]
@adambkaplan I missed a reference previously and had to re-push.

**Comment by ardaguclu** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29134/pull-ci-openshift-origin-master-e2e-agnostic-ovn-cmd/1841665264060469248 is failing due to the changes in this PR.

**Comment by sanchezl** [comment]
Updated for e2e-agnostic-ovn-cmd.

**Pull request merged**
