### PR TITLE
Upgrade note for restoring automatic=false behavior in 1.4

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik @smarterclayton

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@mfojtik updated swagger as well

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11240 [merge]

**Pull request merged**
