### PR TITLE
integration: retry instantiate on conflict

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/11318

@mfojtik

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by mfojtik** [comment]
lgtm

**Comment by kargakis** [comment]
yum flakes

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/9642 [test]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
[test]

**Pull request merged**
