### PR TITLE
Bug 1756421: Revert "CHECK(sttts): disables oc explain tests as our CRD are non-structural"

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
some tests are actually failing
```
fail [github.com/openshift/origin/test/extended/cli/explain.go:253]: Unexpected error:
    <*errors.errorString | 0xc003b2c260>: {
        s: "oc explain [\"rolebindingrestrictions.spec\" \"--api-version=authorization.openshift.io/v1\"] result {KIND:     RoleBindingRestriction\nVERSION:  authorization.openshift.io/v1\n\nDESCRIPTION:\n     <empty>} doesn't match pattern {FIELDS\\:.*}",
    }
    oc explain ["rolebindingrestrictions.spec" "--api-version=authorization.openshift.io/v1"] result {KIND:     RoleBindingRestriction
    VERSION:  authorization.openshift.io/v1
    
    DESCRIPTION:
         <empty>} doesn't match pattern {FIELDS\:.*}
occurred
```

**Comment by p0lyn0mial** [comment]
/lgtm cancel

just to keep the bot from reruning the tests.

**Comment by soltysh** [comment]
Some of CRDs might be missing the new schema generator, I guess.

**Comment by soltysh** [comment]
/close
in favor of https://github.com/openshift/origin/pull/24058

**Pull request closed without merging**
