### PR TITLE
allow dockersearcher to be setup after config is parsed

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal, this is for https://bugzilla.redhat.com/show_bug.cgi?id=1274134

the issue seemed to be that we were setting up the searcher prematurely and given that we have the ensure call, it's not obvious to me why it was being done where it was.

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[test]

**Pull request merged**
