### PR TITLE
Guard against missing error details kind or ID

### LINKED ISSUE #2574: "Cannot create undefined undefined" error message
If the `details` property is missing in the error response, we show `undefined` in the UI. This was creating from a source repository in the web console.

The error itself is legitimate, but we should handle error responses with no `details` in the client.

openshift_web_console

```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #2574

### CODE REVIEW

**Comment by spadgett** [comment]
@liggitt This was only a problem in newfromtemplate.js and createFromImage.js. I copied a 10 line function from one file to the other. Let me know if there's a common place to put utilities like that.

(See #2313)

**Comment by liggitt** [comment]
we can do anything as a filter function... add a TODO to refactor error and failure-related extraction

**Comment by spadgett** [comment]
I went ahead and changed it to a filter.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
