### PR TITLE
Add stack dump to log on sigquit of sti builder

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal.  note that I did not bother writing it to a file, only dumping it to the log.

**Comment by gabemontero** [comment]
Yep that looks like it.  Block until it gets the signal.  Glog the thread dump.  Continue.  No coordination with other threads via other channels.  And from the other examples we've seen, no daemon thread type concerns like with java.

Gabe

**Comment by bparees** [comment]
[merge]

**Comment by rhcarvalho** [comment]
Found this piece of code while reading `builder.go`, @bparees what was the intent when adding this? Do we still need it?

**Comment by bparees** [comment]
@rhcarvalho allows us to get a stack dump if things hang (which used to be a frequent issue in sti) by doing a kill -3 against the pid.  I'd say it's still worth having (frankly it should be default behavior in Go itself) though we haven't had to debug a hung stack lately.

**Comment by rhcarvalho** [comment]
Perhaps we can just C-\ (send SIGQUIT) to the hung program?

And using [GOTRACEBACK](https://golang.org/pkg/runtime/) we can control how much information is dumped.
I tried, GOTRACEBACK=crash will print all goroutine info and generate a core dump.

Don't you think what Go provides is enough?

**Comment by rhcarvalho** [comment]
Actually this code suppress the default Go behavior, as the program will keep running after receiving a SIGQUIT.

**Comment by bparees** [comment]
@rhcarvalho my reading of GOTRACEBACK is that it dumps that stuff on a crash, not on demand.  The case we had was not a crash, it was a deadlock.  

if there is an existing go mechanism that enables a stack dump to be taken on demand, we can definitely switch to that instead.  But it has to be on demand, not on crash/panic.

**Comment by rhcarvalho** [comment]
It is "on demand", try to send a SIGQUIT to any Go program.

For example, start the openshift server and then type Ctrl-\\.


```console
$ sudo openshift start --public-master=localhost 
W0209 14:25:28.329497   20362 start_master.go:271] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
W0209 14:25:28.330803   20362 start_master.go:271] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
I0209 14:25:28.998816   20362 plugins.go:71] No cloud provider specified.
I0209 14:25:29.136311   20362 start_master.go:382] Starting master on 0.0.0.0:8443 (v1.1.2-64-g632a0d6b-dirty)
I0209 14:25:29.136369   20362 start_master.go:383] Public master address is https://localhost:8443
I0209 14:25:29.136492   20362 start_master.go:387] Using images from "openshift/origin-<component>:v1.1.2"
^\SIGQUIT: quit
PC=0x440633

goroutine 6 [syscall]:
runtime.notetsleepg(0x5488b98, 0x3b60d1ea, 0x1)
        /usr/lib/golang/src/runtime/lock_futex.go:201 +0x52 fp=0xc208016768 sp=0xc208016740
runtime.timerproc()
        /usr/lib/golang/src/runtime/time.go:207 +0xfa fp=0xc2080167e0 sp=0xc208016768
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080167e8 sp=0xc2080167e0
created by runtime.addtimerLocked
        /usr/lib/golang/src/runtime/time.go:113 +0x1ba

goroutine 1 [runnable]:
math/big.nat.norm(0xc208762f00, 0x11, 0x25, 0xc20868f8c0, 0x21, 0x24)
        /usr/lib/golang/src/math/big/nat.go:61
....
goroutine 101 [select]:
k8s.io/kubernetes/pkg/util.Until(0xc2085df880, 0x3b9aca00, 0xc2084392c0)
        /home/rodolfo/openshift/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:122 +0x148
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
        /home/rodolfo/openshift/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:165 +0xfb

rax     0xfffffffffffffffc
rbx     0x3b60d1ea
rcx     0x440633
rdx     0x0
rdi     0x5488b98
rsi     0x0
rbp     0xc208016700
rsp     0xc2080166c0
r8      0x0
r9      0x0
r10     0xc2080166f8
r11     0x216
r12     0xc2083f9fb0
r13     0xc60dbcac02a40b54
r14     0x4a0543baf4a99ba2
r15     0x20
rip     0x440633
rflags  0x216
cs      0x33
fs      0x0
gs      0x0
```

**Comment by bparees** [comment]
ok, sounds like it is no longer needed.  That must be new behavior in go, it definitely wasn't present when this code was written.

**Pull request merged**
