### PR TITLE
Add debug logging to ldap search bind errors

### PR DESCRIPTION
**Pull request by liggitt**
logs bind errors encountered during the search phase

### CODE REVIEW

**Comment by liggitt** [comment]
@enj PTAL

cc @spurtell

**Comment by enj** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
#9681 re[merge]

**Comment by liggitt** [comment]
#9681 re[merge]

**Comment by kargakis** [comment]
Please post the log of the job in #9681 next time this occurs

**Pull request merged**
