### PR TITLE
[3.11] Bug 1822491: UPSTREAM: 89794: Clean up event messages for errors

### PR DESCRIPTION
**Pull request by jsafrane**
Backport 89794 into 3.11.

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@jsafrane is kube-controller-manager.log available in OCP 3.11 installation? The log messages refer to it but we weren't locate the file. If not, what is the equivalent file in OCP 3.11?

**Comment by gnufied** [comment]
@raghavendra-talur controller manager runs in a pod in OCP-3.11, you can get logs from that pod.

**Pull request merged**
