### PR TITLE
Injecting new required vars into origin.spec file

### PR DESCRIPTION
**Pull request by sdodson**
We may need to just copy the contents of .tito/lib/ from OSE to Origin if there are more changes here.

### CODE REVIEW

**Comment by sdodson** [comment]
@danyc97 this may help

**Comment by adammhaile** [comment]
Want to review but is there some context on why this change is needed?

**Comment by jupierce** [comment]
@adammhaile I don't know exact context, but if someone is using tito on origin, this brings it into line with the 3.10 ose repo. The additional variables are required.

**Comment by sdodson** [comment]
Centos PaaS SIG builds rpms from this repo but we've let the tito plugins which are required fall out of sync so they're running into problems. See the build.log here
https://cbs.centos.org/koji/taskinfo?taskID=500897

**Comment by adammhaile** [comment]
@jupierce Works for me then.

**Comment by DanyC97** [comment]
@sdodson much thanks for digging the delta, as you know i killed 2 days trying to understand where the prob is.

i wished either OCP will use same origin.spec file like everyone else in which case will force everyone to keep thigns working or at least a heads up and i'll be happy to create a PR.

Sadly i can't do what @sdodson done since i have no intern access, so much thanks again for your help @sdodson

**Pull request merged**
