### PR TITLE
Avoid using bsdtar for extraction during build

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
this seems to have pretty clearly broken binary build functionality :(

**Comment by bparees** [comment]
failure is:
```
F0812 15:05:16.451243       1 helpers.go:108] error: build error: unable to extract binary build input, must be a zip, tar, or gzipped tar, or specified as a file: exit status 2
```

**Comment by joelsmith** [comment]
@bparees I think I have fixed the issue. The shell wanted $0 instead of $1 for `-c` params. From bash(1):
`  If the -c option is present, then commands are read from the first non-option argument command_string.
  If there are arguments after the command_string, they are assigned to the positional  parameters, starting with $0`
I made a little test program that only extracts and that change seemed to fix it, so I expect this time things will go better.

**Comment by joelsmith** [comment]
[test]

**Comment by bparees** [comment]
@smarterclayton tested this syntax locally using a zip archive, tar archive, tar.gz archive, and tar.bz2 archive, all worked.

thanks @joelsmith!

[merge]

**Pull request merged**
