### PR TITLE
add missing rbac rule for builder

### PR DESCRIPTION
**Pull request by jim-minter**
bugzilla 1500519

### CODE REVIEW

**Comment by jim-minter** [comment]
needs tests: either hold from merging and will update, or will add as a follow up.

**Comment by bparees** [comment]
not (too) urgent, so let's hold this until the test that confirms the fix is in place.

/approve

**Comment by deads2k** [comment]
interesting.  How did we pass CI before?

lgtm

**Comment by bparees** [comment]
> interesting. How did we pass CI before?

we test for denial and this was still denying (since it denies by default, effectively).

we didn't have a test to confirm you *could* run something as root if you had the right permissions.  we're going to add a test for that in this PR though.

**Comment by jim-minter** [comment]
@bparees test added, ptal
(this needs to go in before freeze)

**Comment by csrwng** [comment]
the test /lgtm

**Comment by bparees** [comment]
woo, another fixture bites the dust.  @smarterclayton should be pleased.

/lgtm

**Pull request merged**
