### PR TITLE
Disable triggers while reaping a deploymentConfig

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @ironcladlou PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can you add a quick test case for this?

**Comment by kargakis** [comment]
Not sure on how I should go about testing this. The respective [Kubernetes](https://github.com/GoogleCloudPlatform/kubernetes/blob/2c545408968e0848b6b495f0b8b36800fcbb2c64/pkg/kubectl/stop_test.go#L29) unit test doesn't seem to be doing anything noteworthy other than enumerating the HTTP calls...

**Comment by kargakis** [comment]
@smarterclayton went ahead and added a simple test case, also made an api change to use interfaces for easy testing (eliminates the interface conversion in Stop), ptal

**Comment by kargakis** [comment]
I've refactored the mock methods under testclient (https://github.com/openshift/origin/pull/2440), will need to update this PR once that gets merged.

**Comment by smarterclayton** [comment]
Changes look fine to me, let me know when rebased

**Comment by kargakis** [comment]
rebased

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
