### PR TITLE
UPSTREAM: 14182: Distinguish image registry unavailable and pull failure

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This is a prerequisite to serial image pulling in Kubelet.

@smarterclayton @liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM does it also have tests upstream?

**Comment by smarterclayton** [comment]
p1 due to serial pull being on the blocker list.

**Comment by eparis** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
