### PR TITLE
Add protobuf to our types

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@liggitt made a few fixes on 26044 (that are already in the upstream PR).  I think this should pass - it doesn't actually turn proto on, but ensures we generate and run with it compiled.  PTAL

**Comment by liggitt** [comment]
what version is `bump(k8s.io/kubernetes/third_party/protobuf)` bumping to? why isn't that reflected in godeps?

**Comment by smarterclayton** [comment]
it's covered by hack/copy-kube-artifacts, i'll add it to godeps

**Comment by smarterclayton** [comment]
Rebased and fixed godep.

**Comment by smarterclayton** [comment]
Pretty sure this is a flake https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3467/consoleFull#205171772656c25df4e4b05b79524e5d52 on secret races:

```
hack/test-cmd.sh has failed: quota.sh:25: executing 'oc describe appliedclusterresourcequota/for-deads-by-annotation -n bar --as deads' expecting any result and text 'secrets.*18'; re-trying every 0.2s until completion or 60.000s
```

Never observes 18.

**Comment by smarterclayton** [comment]
@liggitt can you do a review?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
I'm going to merge this so the second part can make progress.  Add reviews afterwards as necessary.  [merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
