### PR TITLE
Rip policy ojects

### PR DESCRIPTION
**Pull request by simo5**
In preparation for API PR#46
In preparation for Client-Go PR#38

### CODE REVIEW

**Comment by simo5** [comment]
/hold
@enj PTAL

**Comment by deads2k** [comment]
/lgtm

I'm good with this merging.  Why the hold?

**Comment by deads2k** [comment]
That's weird.  I wonder if we lost the auto-approve

/approve

**Comment by simo5** [comment]
@deads2k I was confused too, thought maybe I touched something where Jordan could approve but you couldn't ?

**Comment by deads2k** [comment]
> @deads2k I was confused too, thought maybe I touched something where Jordan could approve but you couldn't ?

No.  We're both top level.  I'm not sure why the bot was being disobedient.

**Pull request merged**
