### PR TITLE
bump(github.com/openshift/source-to-image): 06c9446cd6b580cbcb13a1489efcb3e943b470af

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1480312
bug 1480312

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal, this was easier than fixing up the other PR.

**Comment by deads2k** [comment]
were you expecting to remove all the test files?

**Comment by bparees** [comment]
@deads2k yes

**Comment by bparees** [comment]
extended failures are known issues. merging.

**Pull request merged**
