### PR TITLE
fix build default import to v1 api

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/14039

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/api-review ptal/confirm this is the right fix

also @smarterclayton or @stevekuznetsov do we have any test frameworks for validating master-config processing that i can leverage to add some testing around this for the future?

**Comment by bparees** [comment]
[test]

**Comment by deads2k** [comment]
> also @smarterclayton or @stevekuznetsov do we have any test frameworks for validating master-config processing that i can leverage to add some testing around this for the future?

Do you mean something that lets you twiddle the config before launching a server?  `test-integration` does that using this https://github.com/openshift/origin/blob/master/test/util/server/server.go#L335

**Comment by deads2k** [comment]
Oh, looking at the fix I see its a serialization problem that would be internally consistent during an integration test.

**Comment by ncdc** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
I don't think we have anything like that.

**Pull request merged**
