### PR TITLE
Enable PostgreSQL replication tests for RHEL images

### PR DESCRIPTION
**Pull request by mnagy**
This should get merged after RHEL images are fixed and will be ready for testing.

@bparees fyi

### CODE REVIEW

**Comment by bparees** [comment]
rhel images are fixed.

[test]

**Comment by bparees** [comment]
oh.  nm.  *that* issue is not fixed yet :)

**Comment by mnagy** [comment]
[test][extended:core(images: postgresql: replication)]

**Comment by mnagy** [comment]
[testextendedonly][extended:core(images: postgresql: replication)]

**Comment by mnagy** [comment]
[testonlyextended][extended:core(images: postgresql: replication)]

**Comment by deads2k** [comment]
[test]

**Comment by mnagy** [comment]
[testonlyextended][extended:core(images: postgresql: replication)]

**Comment by mnagy** [comment]
Test fails with:
```
Running hack/../test/cmd/newapp.sh:148: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s...
FAILURE after 60.172s: hack/../test/cmd/newapp.sh:148: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
There was no output from the command.
There was no error output from the command.
```
@stevekuznetsov any ideas?

This can't be related to this PR, since I'm only touching extended tests.

**Comment by stevekuznetsov** [comment]
@bparees were there any lingering issues with image import that we know about?

**Comment by bparees** [comment]
@stevekuznetsov the fix @deads2k put in to parallelize imports was reverted, so we may be back to cases where we time out.  If there are other issues, @deads2k would be the guy to ask.

**Comment by mnagy** [comment]
@stevekuznetsov what do you mean by "image import"?

**Comment by stevekuznetsov** [comment]
That was a test flake occurring because `oc get imagesteams` timed out - we
couldn't import the image (due to an etcd failure most likely). Kick
Jenkins and hopefully it won't happen again.

**Comment by mnagy** [comment]
Ok.

re[test]

**Comment by mnagy** [comment]
Another flake.. Let's try one last time.. [test]

**Comment by mnagy** [comment]
This was fast, so one more time. [test]

**Comment by mnagy** [comment]
I give up. @bparees the failures are unrelated as far as I can tell and extended tests passed. Can we please get this merged?

**Comment by bparees** [comment]
going to let the extended test run one more time (just the extended test) and then i'll merge it if that passes.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@smarterclayton (test change, zero risk, please merge)

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
