### PR TITLE
ProjectRequestLimit plugin: ignore projects in terminating state

### PR DESCRIPTION
**Pull request by csrwng**
Fixes BZ 1324465

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k @derekwaynecarr

**Comment by deads2k** [comment]
lgtm, but I'm inclined to hold this for 1.2.x.

@csrwng do you think its a severe enough problem to warrant inclusion?

**Comment by csrwng** [comment]
IMHO it's not serious enough to be a blocker, but I'll defer to @abhgupta who owns this area
https://bugzilla.redhat.com/show_bug.cgi?id=1324465

**Comment by derekwaynecarr** [comment]
QE should comment if they want to re-use the same name in their tests (which this wont fix) or if they just want to create a new project with different name.

**Comment by csrwng** [comment]
Creating a project with a different name won't help... it's just a count of projects that you've requested.

**Comment by derekwaynecarr** [comment]
I understand that.  But the original source BZ was commenting on not being able to create a project again when the policy did not give access, and was not specific on if the new project shared the same name if I recall.

**Comment by abhgupta** [comment]
I had a quick offline discussion with @csrwng on this and it seems that the risk for this change is minimal and the benefit to the user experience is potentially big. The case is that the user is deleting their project and then trying to create another one within minutes. This could be when the user has run into some issues with their existing project and have resorted to deleting the project and starting afresh using some template. If they are blocked from creating a new project at this point, it just adds to their frustration and makes for a bad user experience.

My vote would be for getting this one in.

**Comment by csrwng** [comment]
@smarterclayton ^^

**Comment by smarterclayton** [comment]
So I can do the following:

1. Create project
2. Delete project
3. Goto 1

in rapid succession, and cause the server to blow up with projects, thus defeating the point of projects?  You should probably allow only 1 or 2 terminating projects to count.

**Comment by abhgupta** [comment]
@smarterclayton That's a good point - makes sense to restrict the number of projects in terminating state. However, mid-long term, wouldn't it also make sense to provide visibility via the console and the CLI to the user for their projects in terminating state? Probably just the project name/state without the ability to drill into the resource details would be good.

**Comment by liggitt** [comment]
the projects list acl should not use anything other than policy... I don't want to special case "access to the project OR your username in an annotation"

**Comment by abhgupta** [comment]
@liggitt Agreed - the role binding might be deleted.

**Comment by csrwng** [comment]
@smarterclayton thx, updated to only allow a maximum of 2 terminating projects to not count towards the total considered for admission.

**Comment by smarterclayton** [comment]
We could move role deletion to the very end of namespace deletion
@derekwaynecarr.

I think we should only allow 1 terminating project for now in this (make it
a variable, but doesn't have to be configurable unless we can come up with
a reason).

**Comment by smarterclayton** [comment]
2 is fine

**Comment by csrwng** [comment]
@deads2k still lgty ?

**Comment by deads2k** [comment]
> @deads2k still lgty ?

Yes, still lgtm.

If @smarterclayton approves.  Seems like that @abhgupta will get to pick it up in a point release even if it doesn't make 1.2.

**Comment by smarterclayton** [comment]
It's approved for 1.2

**Comment by abhgupta** [comment]
@deads2k @csrwng I am hoping this can be merged and be included in 3.2

**Comment by abhgupta** [comment]
Ignore my comment above - clayton beat me to the comment by just 1 second.

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
