### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by benjaminapetersen**
[Original PR](origin) against `console_1.3`. 

npm: remove grunt-google-cdn (unused)
bower: update hawtio-core-navigation to 2.0.56
npm: remove filerev (unused)
npm: remove pretty-bytes (unused)
npm: update lodash to 3.10.1 (max before 4.x.x)
npm: update less to 2.6.1 (latest)
npm: update clean-css to 3.4.12 (latest)
npm: update karma to 0.12.37 (max before 0.13.x, which incurs breaking changes)
npm: update karma-coverage to 0.2.7 (max before breaking changes)
npm: update karma-phantomjs-launcher to 1.0.0 (latest)
npm: update grunt-contrib clean (latest before 1.0.0), concat (latest before 1.0.0), connect (latest).  add serve-static as connect.static() is no longer a function
npm: update grunt-contrib-copy to 0.8.2 (latest before 1.0.0)
npm: update (to max) grunt-contrib-clean,concat,connect,copy,cssmin,htmlmin,imagemin,jshint,less,uglify,watch
npm: bump grunt-wiredep (latest), adjust wiredep settings
bower: add angular override to declare jQuery as dependency (for wiredep load ordering)
bower/nmp/wiredeps: update to use urijs instead of uri.js, change bower.json, Gruntfile wiredeps, index

@jwforres @spadgett reopened (with bindata now)

### CODE REVIEW

**Comment by jwforres** [comment]
@benjaminapetersen who was pulling in the urijs without the dot in it

**Comment by benjaminapetersen** [comment]
Hawtio.  the hawtio-core-navigation plugin.

**Comment by jwforres** [comment]
@gashcrumb can we update the hawio-core-navigation deps to depend on uri.js instead of urjs, they've registered both but their bower.json declares it as uri.js

**Comment by spadgett** [comment]
For what it's worth, the README on Github uses "uri.js"

> bower install uri.js

https://github.com/medialize/URI.js#using-urijs

**Comment by benjaminapetersen** [comment]
@spadgett yeah, I'm thinking thats the "right" one to use...

**Comment by benjaminapetersen** [comment]
- rebased on master
- added bindata back
- removed most of the bower stuff & added it to my other PR so this one is exclusively about npm updates
    - only overlap is the wiredeps angular dependency chunk in bower.json

**Comment by jwforres** [comment]
did QE have a chance to test your fork ami?  if not go ahead and run it again since you took the bower changes out of this pr

**Comment by benjaminapetersen** [comment]
Ok will do

**Comment by benjaminapetersen** [comment]
closing, this went into origin-web-console

**Pull request closed without merging**
