### PR TITLE
SkyDNS metrics fixes

### LINKED ISSUE #4494: Nodes expose some master-only Prometheus metrics with zero values
e.g. skydns metrics are registered on nodes even though skydns shouldn't be running there.

I haven't done a full review of other stuff but assume other node unrelated metrics will be in there. Metrics should only be reported from a component if they are valid metrics for that component; otherwise can impact on aggregations across the cluster.

From querying a node:

```
$ curl -k http://<node>:10255/metrics|grep dns
# HELP dns_dnssec_cache_miss_count Counter of DNSSEC requests that missed the cache
# TYPE dns_dnssec_cache_miss_count counter
dns_dnssec_cache_miss_count 0
# HELP dns_dnssec_ok_count Counter of DNSSEC requests that were valid
# TYPE dns_dnssec_ok_count counter
dns_dnssec_ok_count 0
# HELP dns_forward_count Counter of DNS requests forwarded
# TYPE dns_forward_count counter
dns_forward_count 0
# HELP dns_lookup_count Counter of DNS lookups performed
# TYPE dns_lookup_count counter
dns_lookup_count 0
# HELP dns_name_error_count Counter of DNS requests resulting in a name error
# TYPE dns_name_error_count counter
dns_name_error_count 0
# HELP dns_no_data_count Counter of DNS requests that contained no data
# TYPE dns_no_data_count counter
dns_no_data_count 0
# HELP dns_request_count Counter of DNS requests made
# TYPE dns_request_count counter
dns_request_count 0
```

### PR DESCRIPTION
**Pull request by jimmidyson**
Bumps skydns & fixes registration of dns metrics on nodes.

This switches completely to the baked-in skydns metrics, which will only be registered on the master when the skydns server is started.

There should be a future PR to upgrade skydns to be able to expose other metrics, e.g. response times & sizes.

### CODE REVIEW

**Comment by jimmidyson** [comment]
This PR now includes the skydns bump required for even richer Prometheus metrics.

**Comment by liggitt** [comment]
were those the only two upstream commits on the skydns godep?

**Comment by liggitt** [comment]
@smarterclayton should probably review this

**Comment by jimmidyson** [comment]
They were the only outstanding upstream commits, yes. Others have already been merged.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
