### PR TITLE
[DO_NOT_MERGE] Fixed failing e2e test

### PR DESCRIPTION
**Pull request by soltysh**
A possible remedy for failing jenkins test.

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
re[test]

**Comment by ncdc** [comment]
The retest isn't going to pass either because of the exec proxy failure

**Comment by soltysh** [comment]
There's already a fix for that in #1563

**Comment by liggitt** [comment]
@ncdc the exec proxy failure is intermittent... can you recreate it?

**Comment by ncdc** [comment]
Seems to happen pretty frequently to me. Hopefully Jordan's PR fixes things.

**Comment by liggitt** [comment]
My PR just fixes the switch back to the cluster admin... which is needed for `osc exec` to work, I guess...

**Pull request closed without merging**
