### PR TITLE
Bug 1323710: fix deploy --cancel message on subsequent calls

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1323710

@ironcladlou PTAL
Do you think there is anything else to be done here?

### CODE REVIEW

**Comment by ironcladlou** [comment]
Yeah, I think this makes more sense. I can still imagine some confusion since by observing the pods you can see the latest deployment is still in the process of being cancelled and has pods "Running" which could be interpreted as contradicting the "no deployment running" part combined with the "latest cancelled" part which makes it sound like everything has settled.

Not sure yet how else to tweak this other than to see if all the deployer pods have been terminated so you can be even more specific (e.g. "latest deployment is still being cancelled").

**Comment by kargakis** [comment]
@ironcladlou since we have documented --cancel's behavior (https://docs.openshift.org/latest/dev_guide/deployments.html#canceling-a-deployment), I would say we are ok with what we already have. How about adding that warning in the help of deploy too?

**Comment by kargakis** [comment]
Also I just noticed that in the deploy help, we talk about rolling back while the command doesn't have to do anything with it:

View, start, cancel, or retry a deployment

This command allows you to control a deployment config. Each individual deployment is exposed
as a new replication controller, and the deployment process manages scaling down old deployments
and scaling up new ones. **You can rollback to any previous deployment, or even scale multiple
deployments up at the same time.**

There are several deployment strategies defined:

* Rolling (default) - scales up the new deployment in stages, gradually reducing the number
  of old deployments. If one of the new deployed pods never becomes "ready", the new deployment
  will be rolled back (scaled down to zero). Use when your application can tolerate two versions
  of code running at the same time (many web applications, scalable databases)
* Recreate - scales the old deployment down to zero, then scales the new deployment up to full.
  Use when your application cannot tolerate two versions of code running at the same time
* Custom - run your own deployment process inside a Docker container using your own scripts.

If a deployment fails, you may opt to retry it (if the error was transient). Some deployments may
never successfully complete - in which case you can use the '--latest' flag to force a redeployment.
**When rolling back to a previous deployment, a new deployment will be created with an identical copy
of your config at the latest position.**

If no options are given, shows information about the latest deployment.


Should we point to the rollback command?

**Comment by ironcladlou** [comment]
>Should we point to the rollback command?

I don't see why not

**Comment by ironcladlou** [comment]
This LGTM

**Comment by kargakis** [comment]
I will add the cancel warning here and then merge it

**Comment by pweil-** [comment]
Minor change for cancellation messages.  Approving for 1.2 (cc @smarterclayton)

**Comment by kargakis** [comment]
updated help with the cancellation warning from https://docs.openshift.org/latest/dev_guide/deployments.html#canceling-a-deployment, got approval, [merge]

**Pull request merged**
