### PR TITLE
remove dockermachine from cluster up

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/openshift/origin/pull/19220

As I understand it, dockermachine was only for macs and pre-dated the native docker for mac.

@csrwng I think we discussed this before and you thought it was reasonable to remove at this point.

/assign @csrwng 
/assign @mfojtik 

Two mac victims for review! :)

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k the change looks good to me, will let @mfojtik tag it

**Comment by mfojtik** [comment]
LGTM, need to fix conflicts

**Comment by mfojtik** [comment]
@deads2k can you also remove the examples, see https://github.com/openshift/origin/issues/19226

**Comment by deads2k** [comment]
> @deads2k can you also remove the examples, see #19226

Rebased and done.

**Pull request merged**
