### PR TITLE
UPSTREAM: 51215: preserve specified dest path

### PR DESCRIPTION
**Pull request by juanvallejo**
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1469411
Also addresses BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1470962

**Before**
```
$ oc cp foo_dir pod_name:/tmp/bar_dir
$ oc rsh pod_name
sh-4.2$
sh-4.2$ ls /tmp
sh-4.2$ foo_dir
```

**After**
```
$ oc cp foo_dir pod_name:/tmp/bar_dir
$ oc rsh pod_name
sh-4.2$
sh-4.2$ ls /tmp
sh-4.2$ bar_dir
```

**Expected Command Behaviors After This Patch**
- **[ unchanged ]:** Copying a file `foo` to pod as `mypod:/tmp/` (trailing "/")
  - Will keep existing behavior of copying the file as `foo` with absolute path being `/tmp/foo` in the remote pod.
- **[ unchanged ]:** Copying a directory `foo_dir` to pod as `mypod:/tmp/` (trailing "/")
  - Will keep existing behavior of copying the directory as `foo_dir` with absolute path being `/tmp/foo_dir` in the remote pod.
- **[&nbsp;&nbsp;&nbsp;changed&nbsp;&nbsp;&nbsp;]:** Copying a file `foo` from local machine to pod as `mypod:/tmp/bar`
  - Will now honor `bar` as the final copied file's name, rather than always defaulting the file's name to `foo`
- **[&nbsp;&nbsp;&nbsp;changed&nbsp;&nbsp;&nbsp;]:** Copying a directory `foo_dir` to pod as `mypod:/tmp/bar_dir`
  - Will now honor `bar_dir` as the final copied directory's name, rather than always defaulting the directory's name to `foo_dir`.
- **[&nbsp;&nbsp;&nbsp;changed&nbsp;&nbsp;&nbsp;]:** Copying a directory `foo_dir` to pod as `mypod:/tmp` (no trailing slash)
  - Will now copy the *contents* of `foo_dir` into the `/tmp` directory (but will not copy the directory itself).
  - Before this patch, the user would receive a "permission denied" error instead; since it would attempt to create the directory under "/". Now, without the trailing slash after ":/tmp", it treats `/tmp` as the final directory's name - and if a directory by that name already exists, it merges the contents of both.
- **[&nbsp;&nbsp;&nbsp;changed&nbsp;&nbsp;&nbsp;]:** (Slightly changed) Copying a file `foo` to pod as `mypod:/tmp` (no trailing slash)
  - Will now return an error `tar: tmp: Cannot open: File exists` (it will try to honor `tmp` as copied file name, rather than old behavior of always using original file name)
  - Before this patch, returned the error `tar: can't open 'test': Permission denied`

cc @openshift/cli-review

### CODE REVIEW

**Comment by liggitt** [comment]
is this related to https://github.com/kubernetes/kubernetes/issues/41752 ?

**Comment by juanvallejo** [comment]
@liggitt 
> is this related to kubernetes/kubernetes#41752 ?

No, I believe that is a slightly different issue; The referenced bugzilla on this one deals with filenames and directories being copied with their original names, ignoring a differing specified destination name.

Will take a look at kubernetes/kubernetes#41752

**Comment by juanvallejo** [comment]
Closing as all changes are upstream and will be brought in with next rebase

**Pull request closed without merging**
