### PR TITLE
[DO NOT MERGE] test-all.sh

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
install-assets never finished re[test]

**Comment by deads2k** [comment]
@liggitt I might actually want to merge this bash insanity.  The difference in how `wait` works when executed from within a subshell (and by "works" I mean utterly fails) has led to a very duplicat-y script.  Any suggestions?

**Comment by liggitt** [comment]
I didn't know the wait command existed prior to today, so I'm probably not the right person to ask

**Comment by deads2k** [comment]
> I didn't know the wait command existed prior to today, so I'm probably not the right person to ask

Oh, but I'm sure you wanted to dive into the deep, dark recesses of bash!

@Miciah how ugly is this thing?  Is there a way to dry it out and still have the the `wait` work around the subshell thing?

**Comment by deads2k** [comment]
@smarterclayton @danmcp This saves about five minutes.  Is it worth the pain?

**Comment by smarterclayton** [comment]
Five minutes? Not that much, sad panda

**Comment by deads2k** [comment]
> Five minutes? Not that much, sad panda

Alright, now about including `install-assets.sh` in the image, so that we don't have to do that at least?  That can often take a stupidly long amount of time.  ~270 seconds, sometimes almost 10.

**Comment by liggitt** [comment]
that means we'll get mismatches on built assets whenever a dependency changes

**Comment by deads2k** [comment]
> that means we'll get mismatches on built assets whenever a dependency changes

Until a new AMI is built, right?  How often are we talking?  I could probably live with "every four weeks, this breaks until a new AMI is built".  Especially if we could recognize it.

**Comment by deads2k** [comment]
> Until a new AMI is built, right? How often are we talking? I could probably live with "every four weeks, this breaks until a new AMI is built". Especially if we could recognize it.

Alternatively, is it possible to cheaply detect a change before running a 5+ minute script?

**Comment by liggitt** [comment]
@jwforres any thoughts on ^^

**Comment by jwforres** [comment]
@liggitt its not just dependency updates, the way the vagrant script re-creates the git repository it totally blows everything away (or at least it used to), we have to install-assets to be able to run any of the asset tests.

We would need to look into whether we can specify an external directory for bower and npm to install the dependencies into during the base ami, and then perform a copy step during test/merge to move them into the locations that everything else expects.  And then update them if we detect bower.json or package.json has been updated.  This would cover everything except for those random cases we had where dependencies updated without updating versions, in which case we would need to just kick off a base_ami.

**Comment by kargakis** [comment]
irrelevant to this PR but how about an `update-all.sh` @deads2k ?

https://github.com/kubernetes/kubernetes/blob/master/hack/update-all.sh

@rhcarvalho fyi

**Comment by deads2k** [comment]
> irrelevant to this PR but how about an update-all.sh @deads2k ?

I like the intent, but I'd rather see it locate the files via a `find` rather than a hardcoded list.  And if you make one, add a `verify-all.sh` as well.

**Pull request closed without merging**
