### PR TITLE
Template tests verbosity

### PR DESCRIPTION
**Pull request by jim-minter**
@bparees template test improvements you requested the other day - split into 2 commits as one is quite noisy.
1) report on object readiness in blocking template tests
2) report pod state on template test failure - matches your work in builds/image_ecosystem.

### CODE REVIEW

**Comment by bparees** [comment]
pkg/template/controller/readiness_test.go:278: undefined: canCheckReadiness
pkg/template/controller/readiness_test.go:282: undefined: checkReadiness

otherwise lgtm.
/approve

**Comment by bparees** [comment]
interestingly you got some template test failures here so either your changes are bugged or this is a great chance to see if they gave us the info we need :)
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16765/test_pull_request_origin_extended_conformance_install_update/7591/

**Comment by jim-minter** [comment]
So the good news is that I think the logging is adequate (personally, I think it's too verbose and we should be saving all pod logs as artifacts, but hey).
I'll resolve the mistake I made and push that now so that this PR can go through.

The test failures were:
1) #16772 networking flake contacting php infrastructure when running s2i - happened three times - want to see if there's anything we can do about this
2) flake in templateinstance security tests, #16775 (need to debug this further)

I also think the build-logs functionality isn't working quite right after the init containers work - opened #16773 to follow-up.

**Comment by bparees** [comment]
> (personally, I think it's too verbose and we should be saving all pod logs as artifacts, but hey).

no particular disagreement here, but path of least resistance...

**Pull request merged**
