### PR TITLE
Bug 1825372 UPSTREAM: 88872: Detect flakes caused by container teardown races on CRI

### PR DESCRIPTION
**Pull request by tedyu**
This PR backports the following to 4.2 branch:

test: Detect flakes caused by container teardown races on CRI

https://bugzilla.redhat.com/show_bug.cgi?id=1825372 is the underlying BZ.

### CODE REVIEW

**Comment by rphillips** [comment]
88766 points to an issue and not a PR, ref: https://github.com/openshift/origin/pull/25129

Is this correct?

/hold

**Comment by tedyu** [comment]
@rphillips 
The upstream PR number has been fixed.

**Comment by rphillips** [comment]
This needs a bugzilla ticket number in the subject and my followup fix: https://github.com/kubernetes/kubernetes/pull/92051

**Comment by rphillips** [comment]
The PR also does not match the upstream PR. It needs to be verbatim or have attached commits showing where they have come from with `UPSTREAM: <PR#>: description` https://github.com/kubernetes/kubernetes/pull/88872/files

**Comment by tedyu** [comment]
Looking at the commit in master branch upstream :
```
commit 6d98b0a0f4fbb9c1032f5c47fa20f59489301138
Author: Clayton Coleman <ccoleman@redhat.com>
Date:   Sat Oct 19 18:10:11 2019 -0400

    Test that an always-fail container can't report the pod Succeeded
```
I see this line:
```
+                       var reBug88766 = regexp.MustCompile(`ContainerCannotRun.*rootfs_linux\.go.*kubernetes\.io~secret.*no such file or directory`)
```
In the backport PR,
```
commit ace84efcd682e1cdac673dcb730bfe5749ee12ca
Author: Ryan Phillips <rphillips@redhat.com>
Date:   Mon Apr 6 11:01:53 2020 -0500

    UPSTREAM: 88440: Report deleted pod status correctly
```
I don't see the line containing reBug88766.

I am open to suggestion on how the gap should be handled.

**Comment by tedyu** [comment]
Maybe we can initiate a backport PR which aligns the test with that from UPSTREAM: 88440.
Then follow with backports of flake detection PRs upstream.

**Comment by tedyu** [comment]
@rphillips 
What do you think of https://github.com/openshift/origin/pull/25129#issuecomment-645050624 ?

**Comment by tedyu** [comment]
@rphillips
Gentle ping.
See https://github.com/openshift/origin/pull/25129#issuecomment-645050624

**Comment by tedyu** [comment]
After some discussion, the porting of 88440 would not be done for release-4.2 because:

4.2.z is largely for critical and CVE fixes

Closing this PR.

**Pull request closed without merging**
