### PR TITLE
syscontainers: add mount for /var/log to origin

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
[test]

**Comment by giuseppe** [comment]
[test]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/12544
[merge]

**Comment by giuseppe** [comment]
it is still failing

**Comment by giuseppe** [comment]
@sdodson could you please take a look at this PR?  Tests are passing now

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
