### PR TITLE
OCPBUGS-15995: [release-4.8] bump openshift/kubernetes to the latest

### PR DESCRIPTION
**Pull request by jsafrane**
Updated using `hack/update-kube-vendor.sh 8b969e704241724b962a28da47f0224d09985959`.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
Mirroring - done
/lgtm
/approve

**Comment by soltysh** [comment]
/override ci/prow/e2e-agnostic-cmd

this test relies on old images, which are not updated in this repo

**Comment by soltysh** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

based on discussion with @jsafrane it doesn't look related

**Comment by jsafrane** [comment]
> Not mergeable. Job ci/prow/e2e-gcp-builds has not succeeded.

But it's not a required job...
/test e2e-gcp-builds

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp-builds
/override ci/prow/e2e-aws-fips 
the failures are not related to this PR, they seem to be coming from not maintained resources

**Pull request merged**
