### PR TITLE
tag a basic test as a smoke test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @smarterclayton 

i don't love this a a smoketest because it builds a ruby app which makes it vulnerable to rubygems being down, but it's as minimal a build e2e test as we seem to have.

**Comment by smarterclayton** [comment]
As a label `[Smoke]`?

How often has ruby gems been down over the last year, rough guess?

**Comment by bparees** [comment]
> How often has ruby gems been down over the last year, rough guess?

i've seen our builds fail to access rubygems a handful of times.  Dunno that it was actually down or there was some other networking issue when it failed.

**Comment by bparees** [comment]
> As a label [Smoke]?

updated.

**Comment by smarterclayton** [comment]
/lgtm

Force merging because we're going to add it to the job

**Pull request merged**
