### PR TITLE
Tearing down old deployment before bringing up new one for the recreate strategy

### PR DESCRIPTION
**Pull request by abhgupta**
Closes https://github.com/openshift/origin/issues/2638

### CODE REVIEW

**Comment by abhgupta** [comment]
@ironcladlou PTAL

**Comment by ironcladlou** [comment]
Should the scale up occur if the scale down fails?

**Comment by abhgupta** [comment]
@ironcladlou Aah, missed that! I have now moved the code around to error out if the previous deployment cannot be taken down.

**Comment by ironcladlou** [comment]
LGTM [merge]

**Pull request merged**
