### PR TITLE
Increase retained CI log size to 100M

### PR DESCRIPTION
**Pull request by ncdc**
Let's try doubling 50M to 100M to see if that helps.

@stevekuznetsov @danmcp

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by stevekuznetsov** [comment]
You could also zip it and keep the truncation if this isn't enough, my naive opinion is that the duplication of log messages should gain us a large win in size when we zip it.

**Comment by ncdc** [comment]
Good idea

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
