### PR TITLE
Update role binding docs

### PR DESCRIPTION
**Pull request by enj**
Just trying to clarify role binding creation based on all the fun @benjaminapetersen had.

Signed-off-by: Monis Khan <mkhan@redhat.com>

cc @openshift/api-review

### CODE REVIEW

**Comment by smarterclayton** [comment]
Rebase

**Comment by benjaminapetersen** [comment]
+1

**Comment by enj** [comment]
Rebased.

**Comment by smarterclayton** [comment]
Note you only need api review if the doc get worse :)

LGTM [merge]

**Pull request merged**
