### PR TITLE
Vendor Kube examples used in extended tests

### LINKED ISSUE #6583: Running extended tests messes with existing kubernetes checkout
Since #5718, an existing working k8s checkout in GOPATH and run extended tests will interfere with each other.

A first execution of `test/extended/core.sh` leaves k8s with HEAD detached at 4c8e6f4, and a subsequent execution fails for me, unless I manually checks out master again.

If I had uncommitted changes or any other thing in my k8s checkout, the test execution will fail (failing to git checkout into 4c8e6f4).

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixes #6583.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can't merge until after next rebase - however, maybe we want to put these not in godeps?  Godeps won't remember them on a `godep save` I don't think

**Comment by rhcarvalho** [comment]
@smarterclayton I noticed we already had some of the examples in our vendored copy of Kube, but not all. I can see two approaches to fix the problem:

## 1. Include all examples in origin
**Pros**: one less download step when running extended tests, extended tests can be run solely from having a clone of origin;
**Cons**: `examples/` need to be kept up to date every time we bump Kube.

## 2. Download a zip/tar.gz
Download a copy of Kube at the specific commit we're vendoring via `curl`, and extract the `examples/` directory overwriting `Godeps/_workspace/src/k8s.io/kubernetes/examples/`.

**Pros**: no need to keep examples in sync.
**Cons**: need to download the whole repository just to get the examples, multiple times every day.


--------------

I went with (1) because it was easier to get started, what solution would you like to have?

**Comment by rhcarvalho** [comment]
@smarterclayton I'm not sure about how much we rely on `godep save` for Kube, as it won't help us with patches any way. Somehow we already had examples there, including some `.go` files, just some files missing.

**Comment by kargakis** [comment]
@deads2k @liggitt isn't this already a part of the rebase process? https://github.com/openshift/origin/commit/f2a4378c684c09599ff1a0fc70a12c0298db62bb

**Comment by rhcarvalho** [comment]
Aha, so there's a third option as well...

## 3. Update hack/copy-kube-artifacts.sh

We could copy all examples via that script, so that examples are kept in sync after every rebase.

**Comment by liggitt** [comment]
that script is what we run during rebases

**Comment by rhcarvalho** [comment]
I went ahead with (3) + (1), updated the script `hack/copy-kube-artifacts.sh` to include all examples so that they can be used by extended tests.

The second commit adds/updates all of `examples/` as of https://github.com/kubernetes/kubernetes/commit/6614b833cbd47f4d8c375c941c38090e7ef1f067 (current master). We should use the same commit/ref as is `Godeps.json`, but I've been unable to find the current ref we have there (#7086).

The third commit bring us back to use the vendored kube instead of  trying to reuse an existing checkout in the GOPATH.

**Comment by rhcarvalho** [comment]
Update: the second commit now is based on the examples from the right commit (9da202e) -- thanks @liggitt

**Comment by rhcarvalho** [comment]
ready for review, @smarterclayton @liggitt PTAL

**Comment by smarterclayton** [comment]
shouldn't this be using GOPATH rather than OS_ROOT?

**Comment by rhcarvalho** [comment]
You're right, shouldn't be reverting to what it was before but rather point
to Godeps. Will update tomorrow when I get my hands on my laptop.

**Comment by smarterclayton** [comment]
I may cherry pick this into my PR but will tell you if i do.

**Comment by smarterclayton** [comment]
Cherry-picked into #7094

**Comment by rhcarvalho** [comment]
@smarterclayton I've updated to use the Godeps path in d84cceeaa834c3a37bbd5cb8cb90b949f974dd1b. We can close this when #7094 merges, but note we also want [some cleaning up](https://github.com/rhcarvalho/origin/commit/d84cceeaa834c3a37bbd5cb8cb90b949f974dd1b#diff-de146235e94f07b029f91b2603d00a54L11) from my last commit that is not in your PR (yet) -- otherwise the issue this is meant to fix will not be fixed.

**Comment by rhcarvalho** [comment]
@smarterclayton taking back what I said, 9471007b167adfb3c21faf09ff0f3b8c6f9e3763 contains the same changes removing the `go get` step. When #7094 merges we can close this PR and related issue.

**Comment by rhcarvalho** [comment]
Merged via #7094.

**Pull request closed without merging**
