### PR TITLE
report a useful error when wide mode is used with new-app/new-build

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/6165

@csrwng ptal

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng as some background on this...  new-app/new-build are half leveraging the upstream -o behavior, but not sufficiently for it to work in all cases (eg -o wide), so we need to catch the case where user's specified "wide" before the outputting is handled by the upstream code.

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by guangxuli** [comment]
@bparees @csrwng why we used` o.Action.Output == "wide"` in newapp.go and used `o.Output == "wide" `in newbuild.go. I see that both `Action.Output` and `Output` items are set by `o.Action.BindForOutput(cmd.Flags())   ` and` o.Output = kcmdutil.GetFlagString(c, "output")` in newapp.go and newbuild.go.  I think we use either **o.Action.Output** or **o.Output** to get -o value is more better.

**Comment by bparees** [comment]
@guangxuli I don't know why newbuild originally created the o.Output field instead of using o.Action.Output directly, but given that it does, this was a minimal sensible change that stuck w/ that pattern.  It doesn't really seem significant enough to worry about.

**Comment by guangxuli** [comment]
@bparees yeah, I am not  worry about this change :), but in PR https://github.com/openshift/origin/pull/12477 , I was extract a common Complete function to handle the same behavior for newbuild and newapp. I mean we could use one o.Action.Output or o.Output, so we could put the same action to the common Complete funciton. otherwise i have to put these two action(judge wide format) to `**(o*NewAppOptions) Complete**` and `**(o *NewBuildOptions) Complete**` respectively. I think it is not good method.

**Pull request merged**
