### PR TITLE
UPSTREAM: 17255: Improve describe for LimitRange resource based on us…

### PR DESCRIPTION
**Pull request by derekwaynecarr**
…er feedback

Fixes 

https://bugzilla.redhat.com/show_bug.cgi?id=1278908

### CODE REVIEW

**Comment by jwforres** [comment]
@derekwaynecarr what was the feedback, do we need to make console updates?

**Comment by derekwaynecarr** [comment]
@jwforres - the feedback was the CLI was missing the word "Default".  this change aligns the CLI with the web console.

**Comment by danmcp** [comment]
@derekwaynecarr Bump

**Comment by derekwaynecarr** [comment]
I can close this PR since it was merged upstream and should be picked up in the rebase in progress.

**Pull request closed without merging**
