### PR TITLE
3.10 Fixed subpath cleanup when /var/lib/kubelet is a symlink

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640077

https://github.com/kubernetes/kubernetes/pull/68741
https://github.com/kubernetes/kubernetes/pull/69565
@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @mfojtik 
for approval

**Comment by wongma7** [comment]
still hitting #21341

/retest

**Comment by jsafrane** [comment]
other 3.10 PRs got merged

/retest

**Pull request merged**
