### PR TITLE
React to imagelayers API changes

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton this adds the field for roundtripping, but doesn't appear to set the value.

**Comment by smarterclayton** [comment]
It does not, I was trying to make sure we still compiled.

**Comment by smarterclayton** [comment]
Updated with e2e and imageMissing logic

**Comment by smarterclayton** [comment]
This is now just the imageMissing change (bump done elsewhere)

**Comment by bparees** [comment]
no other code changes needed to adjust to the missing image marker?

**Comment by bparees** [comment]
(or a followup PR is needed in image-registry once this merges?)

**Comment by smarterclayton** [comment]
In this case no, registry works fine because we serve the manifest to the
client if we have based on whether the image stream references it, not
whether the image references it.  If the image object doesn't exist we can
still serve the raw manifest.

**Pull request merged**
