### PR TITLE
adding 'oc set resources'

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
intial commit to add a command to set resource requests/limits on
running pods.

### CODE REVIEW

**Comment by liggitt** [comment]
Don't we want this upstreamed at the same time?

**Comment by knobunc** [comment]
@liggitt: This just merged upstream as https://github.com/kubernetes/kubernetes/pull/27206.  @eparis and I wanted to get this into OpenShift 1.4 so we have to carry our own version for a release.  When the kubectl set stuff makes it into OpenShift, this version should be replaced.  But since @JacobTanenbaum implemented both, he is keeping the OpenShift version as close to the upstream Kube version as possible, while still working within the existing 'oc set' framework.  Is there a better approach that we should take to get this in?

**Comment by eparis** [comment]
@fabianofranz maybe you can help here...

**Comment by pweil-** [comment]
@openshift/cli-review

**Comment by knobunc** [comment]
[test] last failure was https://github.com/openshift/origin/issues/11240 (logs https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/7278/consoleText)

**Comment by kargakis** [comment]
Why don't you cherry-pick https://github.com/kubernetes/kubernetes/pull/27206 in our vendor dir as an UPSTREAM commit instead of bringing it in oc?

**Comment by fabianofranz** [comment]
> Why don't you cherry-pick kubernetes/kubernetes#27206 in our vendor dir as an UPSTREAM commit instead of bringing it in oc?

+1, if the command code is the same we should cherry-pick as an UPSTREAM commit. Documentation [here](https://github.com/openshift/origin/blob/master/HACKING.md#cherry-picking-an-upstream-commit-into-origin).

**Comment by kargakis** [comment]
The commit message should be: *UPSTREAM: 27206: Add kubectl set resources*

**Comment by kargakis** [comment]
And you also need to update completions and docs:

./hack/update-generated-completions.sh
./hack/update-generated-docs.sh

**Comment by JacobTanenbaum** [comment]
[test]

**Comment by knobunc** [comment]
[test] (in case @JacobTanenbaum was being ignored)

**Comment by eparis** [comment]
[merge]

**Comment by knobunc** [comment]
[test] since Jenkins seemed to explode on the last one.

**Comment by eparis** [comment]
[test][merge]

**Pull request merged**
