### PR TITLE
fix cluster up extended test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng i'm not sure why this wasn't using --version=latest before but i think it should be for the bulk of the tests, no?

Adding another test that runs w/o --version=latest makes sense to me, but we can't do that right now because current master actually can't bring up v3.7-alpha1 anyway.  so that's a follow up.

**Comment by bparees** [comment]
@csrwng bump, this now passes the new cluster up extended test job i created (which just runs the clusterup.sh bucket)

**Comment by csrwng** [comment]
@bparees I think that when we use --version="latest" infrastructure images are created with a pull policy of 'always'. If we want to test the local images, we may need to use the specific tag (git hash) that we used to build them.

**Comment by bparees** [comment]
> @bparees I think that when we use --version="latest" infrastructure images are created with a pull policy of 'always'. If we want to test the local images, we may need to use the specific tag (git hash) that we used to build them.

ok.  is there an easy way to grab that so i can just pass it to the script?

**Comment by csrwng** [comment]
@stevekuznetsov ? ^^

**Comment by stevekuznetsov** [comment]
```
$ git log --pretty=%h -n 1
```

?

**Comment by stevekuznetsov** [comment]
In our jobs we gather it like so:

https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended_conformance_install_update.yml#L19

And use it like so:

https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended_conformance_install_update.yml#L170

**Comment by bparees** [comment]
thanks @stevekuznetsov 
@csrwng updated.

**Comment by bparees** [comment]
(and updated the jenkins job to set ORIGIN_COMMIT)

**Comment by bparees** [comment]
(well, trying to update the job.  ci.jenkins looks dead)

**Comment by bparees** [comment]
the updated job definition is here:
https://github.com/openshift/aos-cd-jobs/pull/788/files

**Comment by csrwng** [comment]
@bparees lgtm on passing test

**Comment by bparees** [comment]
passed cluster up test here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_clusterup/11/consoleFull

**Comment by stevekuznetsov** [comment]
I don't see the cherry-pick :( @kargakis

**Pull request merged**
