### PR TITLE
Fix MySQL replication extended test race

### PR DESCRIPTION
**Pull request by mnagy**
This should fix a race condition in the MySQL replication test where we do not wait until the scaled-down slave pod is removed. We scale to 0, then back to 4 and after that, we list the pods and then later use that list for replication testing. However, if the previous slave won't disappear before we get the list of pods, we might end up with the old pod and then fail because it gets deleted. This can be see in this Jenkins job: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5541/consoleFull

Relevant logs:
```
STEP: after slave is scaled to 0 and then back to 4 replicas
deploymentconfig "mysql-slave" scaled
deploymentconfig "mysql-slave" scaled
deploymentconfig "mysql-helper" deleted
```
The last line is caused by the cleanup function. Error is here:
```
  Expected error:
      <*errors.StatusError | 0xc208745b00>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: ""},
              Status: "Failure",
              Message: "pods \"mysql-slave-1-j356i\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "mysql-slave-1-j356i",
                  Kind: "pods",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      pods "mysql-slave-1-j356i" not found
  not to have occurred
```

### CODE REVIEW

**Comment by mnagy** [comment]
I'd like to wait with testing until the PR parser is able to handle spaces in the focus argument.

**Comment by mnagy** [comment]
I'll try a workaround.. [testonlyextended][extended:core("replication")]

**Comment by mnagy** [comment]
Jenkins extended test is passing. @mfojtik can you review this one, please?

**Comment by jhadvig** [comment]
LGTM :+1: thanks for fixing this

**Comment by mnagy** [comment]
@csrwng mind merging this? @mfojtik is away and I'd like this to be merged ASAP

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
