### PR TITLE
Update java console to 1.0.38

### PR DESCRIPTION
**Pull request by gashcrumb**
This commit updates the java console and fixes the following reported bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1287094
https://bugzilla.redhat.com/show_bug.cgi?id=1286949
https://bugzilla.redhat.com/show_bug.cgi?id=1285763

It also contains a few misc tweaks and brings in an updated version of patternfly

@jwforres FYI...

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@gashcrumb your PR keeps segfaulting during compile, have you tried
compiling with these bindata.go files locally?

**Comment by gashcrumb** [comment]
@jwforres strange, yes I did compile it locally, but here let me give it another try just in case.

**Comment by gashcrumb** [comment]
@jwforres hmm, seems to crash here now too after exhausting memory.  Let me just do a little comparison between the files between the current version and this new one.

**Comment by gashcrumb** [comment]
@jwforres think I found the culprit, will push an update in a few...

**Comment by gashcrumb** [comment]
@jwforres FYI this builds fine here for me now, sourcemaps had gotten added to the build, took those out.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
