### PR TITLE
Enable tests since bug 1702743 was fixed

### PR DESCRIPTION
**Pull request by wewang58**
@openshift/devexp-qe pls help to review it 
/assign @adambkaplan    
thanks all

### CODE REVIEW

**Comment by wewang58** [comment]
@adambkaplan  I runned e2e test in my local hosts, it works, but e2e in ci, still got "Failed to import expected imagestreams".
should we wait pr(https://github.com/openshift/cluster-image-registry-operator/pull/259) merge, which using port 443 for registry service, then e2e-aws-builds pass?  but I saw the pr is targeted to 4.2.

**Comment by wewang58** [comment]
Seems I know the reason:  Error from server (NotFound): configs.samples.operator.openshift.io "instance" not found in ci env.

**Comment by bparees** [comment]
Not sure where that message came from but our config resource should be named "cluster" not "instance" at this point I believe, so perhaps there's some out of sync code/test somewhere?

**Comment by wewang58** [comment]
Retest it again, jobs succeeded now.

**Comment by adambkaplan** [comment]
Closing in favor of #22762 (in the merge pool)

**Pull request closed without merging**
