### PR TITLE
Collapse onto upstream authentication types where possible

### PR DESCRIPTION
**Pull request by deads2k**
I've done a first pass of duplicate authentication types with upstream.  I called out x509 separately, since upstream doesn't respect user UID on certs.  I don't think we care.  If we do, we should update upstream.

@liggitt @ncdc @enj

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
@liggitt if you're ok losing the x509 user UID ability (not done upstream), the rest of this review can be @enj

**Comment by liggitt** [comment]
> @liggitt if you're ok losing the x509 user UID ability (not done upstream)

I am

**Comment by deads2k** [comment]
@enj please review.

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/14043

re[test]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/14048 re[test]

**Comment by enj** [comment]
[merge]

**Pull request merged**
