### PR TITLE
Refactor stable layer count unit test to get rid of flake

### PR DESCRIPTION
**Pull request by csrwng**
Removes unpredictability due to concurrency in unit test. Now only tests the specific function.

Fixes https://github.com/openshift/origin/issues/9759

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
test failure hit flake https://github.com/openshift/origin/issues/9804

**Comment by csrwng** [comment]
[test]

**Comment by bparees** [comment]
flake. 
[merge]

**Comment by bparees** [comment]
@csrwng you are cursed.

flake https://github.com/openshift/origin/issues/9681

[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9195
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
wow.
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9195
[merge]

**Comment by bparees** [comment]
flake *https://github.com/openshift/origin/issues/9548
<https://github.com/openshift/origin/issues/9548>*
[merge]


On Wed, Jul 13, 2016 at 2:50 PM, OpenShift Bot <notifications@github.com>
wrote:

> continuous-integration/openshift-jenkins/merge FAILURE (
> https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/6210/)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/pull/9801#issuecomment-232451042>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3hI268Wd5JmM2nrS73nmsUNymzExks5qVTOGgaJpZM4JKduf>
> .
>



-- 
Ben Parees | OpenShift

**Comment by csrwng** [comment]
\o/

**Pull request merged**
