### PR TITLE
[WIP] parameterize a list of objects into a template 

### PR DESCRIPTION
**Pull request by csrwng**
## Overview

- Introduces a new endpoint /parameterizedtemplate that generates a template with parameterized values for certain aspects of the input resources. Supports _image references_ as an aspect to parameterize. Other aspects that can be added later include name, environment variables, secret names, etc.
- Adds CLI command to parameterize a list of objects or an existing template. The output of the command is a template with parameters for the aspects specified as an argument.

### Examples

_Parameterize existing deployment configs_
```
oc get dc -l app=myapp -o yaml | oc parameterize --aspects=image-refs -o yaml -f - > myapp_template.yaml
```

_Parameterize newly generated artifacts_
```
oc new-app https://github.com/example/repository.git -o yaml | oc parameterize --aspects=image-refs -o yaml -f - > myapp_template.yaml
```

## Use Cases

- A developer uses a local cluster (with minishift or cluster up) to create an application locally. The application includes build configs, deployment configs, pvcs, image streams, etc. The developer would like to export the artifacts to recreate the application on a production cluster (openshift online). Some of the images referenced locally may be different than what is desired in the next environment. The developer then:
  - Exports the set of local artifacts using `oc export`:
     ```
     oc export bc,dc,pvc,is -o yaml > myartifacts.yaml
     ```
  - Parameterizes the image references in the exported artifacts:
     ```
     oc parameterize --aspects image-refs -f myartifacts.yaml -o yaml > mytemplate.yaml
     ```
  - Alternatively stores the template in source control, and instantiates it in the production environment:
     ```
     oc new-app -f mytemplate.yaml -p MARIADB_IMAGE_REF=registry.access.redhat.com/rhscl/mariadb-101-rhel7:latest
     ```

- An application developer has created an application in a development cluster, they now want to promote it to staging and eventually production. Only deployment configs and artifacts related to running the application are desired. As in the previous case, the desired artifacts are exported (removing triggers from dc's and resolving images are outside the scope of this PR). The exported artifacts can then be parameterized into a template that allows modifying Docker references to the images to be used in the next environment.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can you describe the user actions (in the description of the PR) that would surround this action?  I.e. "a user has a running application on openshift, they do these things, then they call this api, then they do X"?

**Comment by csrwng** [comment]
Updated description with examples and use cases.

**Comment by jorgemoralespou** [comment]
@csrwng what aspects could be parameterised?

**Comment by jorgemoralespou** [comment]
I reply to myself, looking at the code only the image-refs can be parameterised.

**Comment by bparees** [comment]
@csrwng does this have a future or should it be closed?

**Comment by csrwng** [comment]
Let's close it for now. I think we need a better parameterize solution as described in the use cases for export. I don't necessarily want to be able to parameterize ALL image references, only the ones that I specify. For that, this is not enough.

**Pull request closed without merging**
