### PR TITLE
only kill and remove k8s managed containers

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by mfojtik** [comment]
lgtm

shouldn't we print a warning with sleep to give chance to users to cancel the removal? I can have k8s prefix for containers myself...

**Comment by bparees** [comment]
if you really think users will be sitting there watching the e2e test to do that....  if i do that, i need to add another arg to disable that wait so we can disable it in the jenkins tests so we don't make them unnecessarily longer.

**Comment by mfojtik** [comment]
another way would be to list containers before test a after test... then do
diff and remove k8s_

but I am ok with this fix.

**Comment by bparees** [comment]
@mfojtik see https://github.com/openshift/origin/issues/795 where i proposed doing the diff, my worry there is we'd kill containers that were launched during the test, so it's not totally safe.  Of course doing both would be safer than one or the other, but i'm not sure it's worth the effort.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
