### PR TITLE
Make yum packages comparable across base images

### PR DESCRIPTION
**Pull request by smarterclayton**
These are identical, and should be easily kept in sync.

@kargakis can you give this a once over?  I couldn't review these differences when I was making an unrelated change. I manually confirmed they are the same.

### CODE REVIEW

**Comment by kargakis** [comment]
> Took 5 hr 4 min

wtf

**Comment by smarterclayton** [comment]
I am deeply skeptical that *every* run of _install with this has failed... but with different flakes.

/retest

**Pull request merged**
