### PR TITLE
Bug 1180393 - Fail to access the Guestbook example

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by mfojtik** [comment]
this is used by template unit test....

**Comment by bparees** [comment]
@mfojtik this pull moves the guestbook template.json into fixtures and updates the template test to use it from there...

**Comment by bparees** [comment]
@smarterclayton review?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
