### PR TITLE
Bug 1461324 - Log image changes on verify-image-signature without --save

### PR DESCRIPTION
**Pull request by wozniakjan**
https://bugzilla.redhat.com/show_bug.cgi?id=1461324

### CODE REVIEW

**Comment by wozniakjan** [comment]
@bparees it actually says it, roughly in the middle of that page

"Using the --save flag on already verified image together with invalid GPG key or **invalid expected identity** causes the saved verification status to be removed, and the image will become unverified."

which is similar to the information the `oc` command gives us
https://github.com/openshift/origin/blob/5e0bfba0f09666c414d952d084a709f021c90c23/pkg/oc/admin/image/verify-signature.go#L45-L47

@bmcelvee  do you think maybe a red exclamation mark would be appropriate here? https://github.com/openshift/openshift-docs/blob/master/admin_guide/image_signatures.adoc

**Comment by bparees** [comment]
> "Using the --save flag on already verified image together with invalid GPG key or invalid expected identity causes the saved verification status to be removed, and the image will become unverified."

@wozniakjan that's not the same as removing the (unverified) signatures which is what happens, right?

**Comment by bmcelvee** [comment]
@wozniakjan I agree, it really couldn't hurt to call that line out in an "important" box. As is it's easy for a reader to gloss over it and run into trouble. I can open a docs PR now, or wait to see if additional docs updates are required for this PR.

**Comment by wozniakjan** [comment]
> @wozniakjan that's not the same as removing the (unverified) signatures which is what happens, right?

That may very well be. I read the code first and then tried to see if I can find corresponding information in docs and probably made an assumption a little to early. I don't think the code discriminates between verified/unverified signature, it removes all signatures if `expected-identity` does not match.
https://github.com/openshift/origin/blob/5e0bfba0f09666c414d952d084a709f021c90c23/pkg/oc/admin/image/verify-signature.go#L211-L218

> @wozniakjan I agree, it really couldn't hurt to call that line out in an "important" box. As is it's easy for a reader to gloss over it and run into trouble. I can open a docs PR now, or wait to see if additional docs updates are required for this PR.

@bmcelvee PR emphasizing the information in "important" box would be great I think, maybe also explicitly stating `...saved verified status with all previous signatures to be removed...` instead of original `...saved verification status to be removed...`

**Comment by wozniakjan** [comment]
@bparees thanks for the reminder, removing the WIP. Wasn't entirely sure whether docs update or more verbose logging, and in the end, both might complement each other well

**Comment by bparees** [comment]
> @bparees thanks for the reminder, removing the WIP. Wasn't entirely sure whether docs update or more verbose logging, and in the end, both might complement each other well

yeah i think both are good.

/lgtm

**Pull request merged**
