### PR TITLE
Remove not useful oadm router and registry help message

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
First of all, this command needs `--credentials` option.  
Secondly even if it shows yaml or json outputs, it just replaces `image: xxxxx` with `image: yyyyy`.

**Comment by liggitt** [comment]
I think it's valuable to have an example showing the alternate image option

**Comment by nak3** [comment]
Please compare with `--image` option to [first help example](https://github.com/openshift/origin/blob/4bc1af7d29eb1321fcb7fe25911c7935a5f526b4/pkg/cmd/admin/registry/registry.go#L48-L49). 

~~~
[root@ose3-master ~]# oadm registry -o yaml --credentials=/etc/openshift/master/openshift-registry.kubeconfig > no-image-option
[root@ose3-master ~]# oadm registry -o yaml --credentials=/etc/openshift/master/openshift-registry.kubeconfig --images='foo' > image-option
[root@ose3-master ~]# diff no-image-option image-option 
94c94
<             image: openshift/origin-docker-registry:v3.0.0.1
---
>             image: foo
~~~

Since it is almost same, I don't think it is not necessary. However, if you think it's valuable, I will send updated (with `--credentials` and change comment) PR. Please let me know, if I should update this PR.

**Comment by ncdc** [comment]
I'd recommend leaving in the image examples

**Comment by nak3** [comment]
OK, I see. I updated in https://github.com/openshift/origin/pull/3977 , so please close this PR.

**Pull request closed without merging**
