### PR TITLE
Fix OpenAPI spec to match Kube 1.6 structure

### LINKED ISSUE #14373: openshift-openapi-spec.json missing x-kubernetes-group-version-kind
The OpenShift OpenAPI JSON is missing the `x-kubernetes-group-version-kind` property to know what API group, version, and kind the schema is describing. The property is there in the upstream swagger.json.

OpenShift:

https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json

Upstream:

https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

@smarterclayton @jwforres

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #14373

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

Blocks release because we are inconsistent with generated docs that Kube requires / will require.

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
no conflicts in base or the item merging.

**Comment by smarterclayton** [comment]
Note the upstream commit is part of a very large PR - it just happens that there was the one commit that fixed this problem in it.

**Pull request merged**
