### PR TITLE
Upgrade dind image to fedora23

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by danwinship** [comment]
Wasn't go-in-f23 much slower than go-in-f21? Or did that get resolved one way or the other?

**Comment by eparis** [comment]
[merge] yes, 1.5 is slower, when 1.6 lands it gets a little faster again.

**Comment by marun** [comment]
I was thinking we should move to f23 to ensure we're using a supported version and one that matches the distro version of vm deployment.  While the compile penalty of moving to golang > 1.4 is considerable, but I don't think we really have a choice.

**Comment by marun** [comment]
@eparis re-merge?  no way an integration failure is related to a dind change.

**Comment by eparis** [comment]
[merge]
@marun : can you hunt down and link to, or file an issue?

**Comment by marun** [comment]
@eparis The ci job already reported #7243.

**Pull request merged**
