### PR TITLE
Clean up test/end-to-end/core.sh

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@bparees  PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
signing off on the old ui e2e test removal, its dead code

**Comment by smarterclayton** [comment]
LGTM

**Comment by bparees** [comment]
lgtm after a squash

**Comment by stevekuznetsov** [comment]
I'll squash after a green run on e2e

**Comment by stevekuznetsov** [comment]
@bparees got green, squashed, this is ready

**Comment by bparees** [comment]
[merge]

**Pull request merged**
