### PR TITLE
[release-4.1] Bug 1727917: FlattenListVisitor now continues traversal on errors and returns an aggregate

### PR DESCRIPTION
**Pull request by damemi**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1727917
4.2 fix (links to upstream PR as well): ~~https://github.com/openshift/kubernetes-cli-runtime/pull/2~~ https://github.com/openshift/kubernetes-cli-runtime/pull/3

### CODE REVIEW

**Comment by damemi** [comment]
@soltysh I added your test case to this for backport

**Comment by soltysh** [comment]
/title Bug 1727917: FlattenListVisitor now continues traversal on errors and returns an aggregate [release-4.1]

**Comment by mfojtik** [comment]
This has the right BZ state and priority, the fix soaked in master it is low risk, approving.

**Pull request merged**
