### PR TITLE
UPSTREAM: 16945: kubelet: Fallback to api server for pod status

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/5640

### CODE REVIEW

**Comment by kargakis** [comment]
Merged upstream: https://github.com/kubernetes/kubernetes/pull/16945

**Comment by deads2k** [comment]
@liggitt do we have a pick list for 1.1.1?

**Comment by liggitt** [comment]
not yet, waiting for the 1.0 branch to cur first, then I'll pick up looking at merges upstream from our stopping point

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
```
[INFO] Running a CLI command in a container using the service account
!!! Error in hack/../test/end-to-end/core.sh:142
	'out=$(oc run cli-with-token --attach --env=POD_NAMESPACE=test --image=openshift/origin:${TAG} --restart=Never -- cli status --loglevel=4 2>&1)' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:142 main(...)
Exiting with status 1

[FAIL] !!!!! Test Failed !!!!
```

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/5937 flake

re[merge]

**Pull request merged**
