### PR TITLE
[WIP] [DO-NOT-MERGE] [DO-NOT-REVIEW] pipelines on console

### PR DESCRIPTION
**Pull request by fabianofranz**
First rough, dirty, incomplete, and ugly draft of pipelines on the web console. PR intended for discussions about how the information flows in the pipeline and visual designs, not yet code review.

Per-project, does not yet manage CI/CD environments (dev, stage, prod, etc). At this point it's mostly a web console version of `oc status`, displayed as a flow/pipeline. The green boxes reflect the status of a given step (green being "completed", "deployed", etc). Clickable to display details on the right column. 

Ignore the "Debug" section at the bottom.

@jwforres @sspeiche @ajacobs21e 

pipelines1

### CODE REVIEW

**Comment by ajacobs21e** [comment]
+1 to clickable to show details on the right.
Will the selected block have a blue border like items on the overview page?

Do we want to show upcoming steps? It looks like these are both "finished" pipelines, aka there is no next step. Is that correct? If there was another step, do we want to show this as greyed out or something like that?

Do we want the steps of the pipelines to align vertically? Something like
a

In the second pipeline, are there two incoming sources leading into one pipeline?

**Comment by fabianofranz** [comment]
@ajacobs21e thanks for the comments!

That's correct, green denotes a "fulfilled" step, so all boxes being green means the entire pipeline is "finished". When you start a new build for example you would have the current (running) step with a different border color, and the upcoming steps greyed or not present. Let me adjust and then add a screen for that scenario. I'm using border colours but in earlier versions I had icons like in the [Patternfly cards](https://www.patternfly.org/patterns/aggregate-status-card/), that would also be an option. I'm also exercising with using colours in the arrows, which make it clear a transition happened (e.g. the build finished and successfully started a deployment, which is in progress).

Aligning vertically looks good, and we probably need to be smart to know when none of the pipelines have a build, for example, and adjust visually. 

In the second pipeline, the idea is that you have two inputs to do that build - both a builder image and source code. While in the first pipeline you only have an image that gets directly deployed (no source and no build involved).

**Comment by fabianofranz** [comment]
That said, what's not yet very clear is what we are going to use to track the progress of your sources (source code, image, etc) in the pipeline. I'm not sure if the information that started everything in the beginning of the pipeline (source code git commit id, image identifier, or something else) is available in all steps of the pipeline (build, deployment, service). BTW @jwforres feel free to add to this discussion other people that should be involved, tks.

**Comment by ajacobs21e** [comment]
@fabianofranz I thought I had posted this yesterday but I don't see it now - hopefully it wasn't so bad it was deleted :) I came up with two rough ideas for other ways to show detail within each step.

screen shot 2016-02-10 at 11 51 29 am

I was interpreting this as more "what's in the build stage" vs "what stage is this image in". I'm still not clear on the difference from Fabric8 but I'll try to not think about what they're doing for now.

**Comment by benjaminapetersen** [comment]
Subscribing myself because this is interesting :smile:

**Comment by ajacobs21e** [comment]
> Aligning vertically looks good, and we probably need to be smart to know when none of the pipelines have a build, for example, and adjust visually.

Do we know ahead of time if a build will skip a step? (or whatever the right terminology is)

**Comment by fabianofranz** [comment]
@ajacobs21e it has to be dynamic since you could always be adding new kinds of resources you don't yet have in a project.

**Comment by jorgemoralespou** [comment]
@fabianofranz 
In the sample pipeline you've described I think it's important to note that the Build creates an Image in an ImageSTream, and this Image/ImageStream will be the source for the deployment.
Also, I think it would be interesting to group steps like @ajacobs21e described, as for me it would be really 2 stages (build and deploy) with many tasks:

**Stage build**:
input -> Image, Git, ...
tasks -> clone source, build, post-build hooks, ...
output -> ImageStreamTag

**Stage deploy to dev**:
input -> ImageStreamTag
task -> pre-deploy hooks, Deploy to servers with selector xyz, post-deploy hooks, create/active service, create/active route, ...
output -> deploymentExitCode

Then this pipeline could be extended to include more stages to deploy to other environments (where the environment would be modeled as "project" or "labelSelector", or even combine 2 builds and 2 deployments as part of a pipeline.

Binding a pipeline to the resources is awkward. A pipeline is a set of actions with input and outputs. These will sometimes be modeled in one or many resources as labels, annotations, ... but we'll have to have a pipeline and stage construct to have information to relate things together.

**Comment by fabianofranz** [comment]
adding @bparees @smarterclayton

**Comment by ajacobs21e** [comment]
I took comments from Monday's meeting and updated my concepts:
pipelines2

What do you think of the structure @jwforres @bparees @fabianofranz @sspeiche ? The stages / order might be off, we can work that out later.

**Comment by sspeiche** [comment]
This is an interesting option for a "drill down" view, though seems like too much detail at first glance. I like the idea of breaking up the build steps like this (and other phases), though in reality we'd need to do some platform work to communicate build steps and progress into these (including "push to registry").

I worry that the grouping of stages (Build, Deployment, Service) overlaps directly with how Environment are currently visualized based on the fabric8 concepts. We should reconcile those differences. We should also think about how environments might be represented here, even though we don't have it yet, I guess we could surface some selected labels.

**Comment by ajacobs21e** [comment]
@sspeiche The [Fabric8 concept](https://invis.io/FM6036B68) has each pipeline labeled as "Build #X" - does that mean all of the steps they are showing are occurring within the block I have labeled as "build"? 

How does their pipeline intersect / overlap with our pipeline? I adapted my visuals to better align with theirs so we don't have two different looking pipelines but if they're showing very different things they should not look alike.

**Comment by smarterclayton** [comment]
Catherine and I were talking yesterday about how the pipeline overview
needs to have a concept of "operations", i.e. what is running in production
(25%, right hand view, summary) is important to summarize, because this is
a DevOps view.  Not Dev, not Ops.  And we'll expect to have multiple sub
views, but the overview of the console should always be devops.  You can
drill down into the current overview (more ops / topology) from that new
overview, or you can drill into the builds (more dev), but the overall page
is about summarizing what is changing and how it is impacting production

**Comment by smarterclayton** [comment]
It would be good to iterate a bit more on "exposing the status of the
current state" in this pipeline, then deep dive with catherine on how we
unify the "dev perspective" and "operational status" in the same overview -
what simplifications / unifications can be done.

**Comment by sspeiche** [comment]
I believe this effort (part of this card/PR) is to just experiment with what we can do today within a project and current APIs/data.

I think a specific Dev or Ops view is a 3rd priority, it is a devops view and we want to promote a devops way of thinking/working. If anyone wants to drill into any area, and their permissions allow them, they can get more details. Zoom into operations (ride side) verses zoom in on left side (development). The longer pipeline concept could include going further to left (business needs) and to the right (validating business value)

**Comment by smarterclayton** [comment]
That's basically what I'm saying.

**Comment by sspeiche** [comment]
@smarterclayton 👍 just confirming

**Comment by jorgemoralespou** [comment]
Hi,
I'm wondering if what @ajacobs21e is showing is what we intend to surface in the stages of our pipeline? And also how are we going to relate things?
To be honest I think we're mixing OpenShift concepts into CD concepts with respect to stages/pipelines.
A pipeline should show a complete sequence of steps (jobs, tasks) that need to be taken/executed to be completed with an output action. In this sense, I think that we should be showing 2 stages in the examples above: build and deploy to env.
If we want to combine, then with a more complex scenario where we involve other projects (environments) we could have more stages like: promote, test, integration test, functional test, approval, deploy to test/pre/prod.
In this sense, I see the fabirc8 concept having a grouping of stages in the environments (projects) where they will be affecting (which can be right given it will need authentication/authorization for actions to happen), so we would need, as @sspeiche a way to identify an environment and relate that to a stage.
If you see [Jenkins delivery pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Delivery+Pipeline+Plugin) or the [Fabric8 concept](https://invis.io/FM6036B68) you'll see that every initial action will create a full swimlane, hence "Build #xxx" in the fabric8 view. At the end this will identify an image ID that will be used through all the stages of the pipeline.

**Comment by smarterclayton** [comment]
Openshift concepts *are* CD concepts.  The simplest pipeline is two
steps, build and deploy, and there is only one env.  As complexity is
added, you would see more of what the fabric designs show.  Now that
we have automatic promotion in Openshift, we have to identify what
those steps look like as well.  I expect this view would become more
condensed over time and focus on the capsule summarization.

I don't think the current designs represent all of the concepts /
discussions either, so you're seeing a point in time exploration.

**Comment by jorgemoralespou** [comment]
@smarterclayton I was refering to the distinction we are making in the images between deployment and service. DeploymentConfig and Service are OpenShift concepts that I think maps to CD Deployment (having everything that's required for you application to run deployed in an env).
What I'm concerned is that we try to add visualizations to things like Service or map that as a stage. That's just part of the Deployment Stage.

I know that maybe I'm going too far, as this is just a mockup, but just wanted to make clear the distinction, that even names are same/similar they represent different (although approximate) things.

**Comment by smarterclayton** [comment]
Yes, the service / route are really the thin layer to the right and the
naming / grouping of the entire pipeline, while the deployment itself is
the meat of the ops view (if you're deploying right now that's more
important than the rest of the pipeline, then if there are any errors, and
then if your dependencies are erroring).  The wrinkle with both of these
pieces is that 1 deployment -> 1 service is just a common case, and we'll
have to deal with fan in, shards, and so forth in that section.

**Comment by danmcp** [comment]
@fabianofranz Needs to move to the ui repo if still valid.

**Pull request closed without merging**
