### PR TITLE
Bug 1729276: Using AWS when a secondary IP address is added the order of the list of InternalIPs is not preserved.

### PR DESCRIPTION
**Pull request by RobertKrawitz**

### CODE REVIEW

**Comment by rphillips** [comment]
Does the 'bump' commit need a different commit message?

**Comment by RobertKrawitz** [comment]
> Does the 'bump' commit need a different commit message?

@rphillips that appears to be the message that's required for that kind of commit.

**Comment by sjenning** [comment]
/approve
/lgtm
need z-stream manager for cherry-pick label

**Pull request merged**
