### PR TITLE
line continue should be instead by break

### PR DESCRIPTION
**Pull request by guangxuli**
/cc @mfojtik thanks.

### CODE REVIEW

**Comment by guangxuli** [comment]
@mfojtik PTAL,thanks.

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by guangxuli** [comment]
@mfojtik PTAL, merge failure, I check the error output, it is not related to this PR. It looks like a known problem.

**Comment by guangxuli** [comment]
@mfojtik PTAL，thanks.

**Comment by mfojtik** [comment]
[merge]

**Comment by guangxuli** [comment]
@mfojtik sorry to bother you again, can you trigger merge again or add a flake, thanks.

**Comment by guangxuli** [comment]
@mfojtik can you take a look for this PR? Thanks :)

**Comment by mfojtik** [comment]
@guangxuli this PR must be cursed ;-)

[merge]

**Pull request merged**
