### PR TITLE
Backport CNI 0.3.x support in openshift-sdn to 3.11

### PR DESCRIPTION
**Pull request by luksa**
Backport of #21975 to 3.11

### CODE REVIEW

**Comment by knrc** [comment]
FYI @dcbw

**Comment by luksa** [comment]
ping @dcbw 

can we get this in?

**Comment by BostjanBozic** [comment]
Any updates on this? Would be great if this can be backported to 3.11 due to Istio use case.

**Comment by lukasz-bielinski** [comment]
@luksa @dcbw  @smarterclayton @aveshagarwal @pweil @mfojtik @soltysh @ironcladlou

Hi, 

would it be possible to reopen this PR and backport and merge CNI plugin 0.3x into origin 3.11?

**Comment by lukasz-bielinski** [comment]
cc: approvers:
@pravisankar
@danwinship
@knobunc
@squeed
@rajatchopra

as mentioned above:

would it be possible to reopen this PR and backport and merge CNI plugin 0.3x into origin 3.11?

**Comment by knobunc** [comment]
3.11 isn't taking features any more.  What would the justification be for this @lukas-bednar @BostjanBozic ?

**Comment by lukasz-bielinski** [comment]
> 3.11 isn't taking features any more. What would the justification be for this @lukas-bednar @BostjanBozic ?

@knobunc  main reason is to run istio-cni which requires cni plugin version 0.3. 

detailed explanation here https://github.com/openshift/origin/issues/21891 

by the original author of these PR @luksa

**Comment by BostjanBozic** [comment]
@knobunc As @lukasz-bielinski mentioned, without this, automatic proxy sidecar injection for istio/OpenShift Service Mesh is only possible if privileged SCC is granted to `serviceAccount` deploying the workload, which is not an optimal solution.

**Comment by lukasz-bielinski** [comment]
@vrutkovs could you please look at this PR? Do you think it could be back ported?

**Comment by knrc** [comment]
We no longer support OCP 3.11 for ServiceMesh so this PR is no longer required.  To be honest I was surprised to see such an old PR get resurrected :)

**Comment by lukasz-bielinski** [comment]
@knrc  Some companies are still on 3.11 and line 4.x is pretty distant future for them.

Main thing here is, that we have code ready. What is only needed is just reopen and test. I believe it was just overlooked, that this pr was not merged when it was created by @luksa

I am only asking for reopen and retest. If tests will succeed I believe this pr could be merged.

**Comment by knrc** [comment]
@lukasz-bielinski Understood however we now only support OCP 4.4/4.5/4.6 with Service Mesh, i.e. we match the supported versions of OCP, so this is no longer needed for our use.

**Comment by kivio** [comment]
We are also using it and will be excellent for us to make this merged, It will make my company easier to migrate to a newer version of OCP. As service mesh will reduce complexity of our workloads.

**Comment by t-vignesh** [comment]
It will be useful if this can be merged.

**Pull request closed without merging**
