### PR TITLE
Revert "Revert "Refactored custom `tito` tagger and builder""

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Reverts openshift/origin#12727

@smarterclayton the new version of `tito` is in EPEL so this should be ready to go now

### CODE REVIEW

**Comment by smarterclayton** [comment]
Not knowing tito i trust you to merge ;)

**Comment by stevekuznetsov** [comment]
I'll wait on `base_ami` for this one (c'mon Jenkins ...)

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[merge]

**Pull request merged**
