### PR TITLE
Replace mongostat with mongo in mongodb example template

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/8740

### CODE REVIEW

**Comment by mfojtik** [comment]
(do no merge, still testing)

**Comment by mfojtik** [comment]
@bparees @rhcarvalho @sspeiche FYI (tested and working for both mongo26 and mongo24). Also this probe actually verifies the userdb is created and authentication works before pod is ready.

[test]

**Comment by bparees** [comment]
[testonlyextended][extended:core(mongodb)]

**Comment by mfojtik** [comment]
@gabemontero should be pulled to online as well...

**Comment by gabemontero** [comment]
@dak1n1 @ironcladlou FYI - the mongodb template that online pulls from origin is getting updated with this PR .... based on input from @bparees and @mfojtik , we'll want to update the templates currently installed in online dev int via `scripts/maintenance/templates/create.sh `at the first available opportunity.

**Comment by dak1n1** [comment]
@gabemontero we can't use create.sh anymore because of Ops security concerns, but we do have an RPM that contains the QE-tested versions of the Online templates. That RPM is openshift-scripts-online, and the templates live in /etc/openshift-online/templates/examples/. So once this merges I can get a new version of that package built and installed, and update the templates from there.

**Comment by gabemontero** [comment]
@dak1n1 gotcha - and sounds good re: updating those RPMs once these template PRs merge.

**Comment by mfojtik** [comment]
[test] again (it seems like a mongodb flake, but want to be sure the liveness probe is correct)

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(mongodb)]

**Comment by mfojtik** [comment]
@bparees replication flake reported here: https://github.com/openshift/origin/issues/8753

[merge]

**Comment by sspeiche** [comment]
FYI I got it working with Mongo 3.2 (SCL Beta) image as well. In fact, I couldn't get that image to work without using this readiness check (making this change)

**Pull request merged**
