### PR TITLE
place tmp secret files in tmpdir

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test] me

**Comment by liggitt** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
@liggitt got green

**Comment by liggitt** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@liggitt flake on E2E: https://github.com/openshift/origin/issues/8078, added failure cause. please re-tag

**Pull request merged**
