### PR TITLE
Refactor cli command cancelbuild and add unit tests.

### PR DESCRIPTION
**Pull request by guilhermebr**
Refactor based on openshift cmd guidelines and added unit tests for cancelbuild cli command.

Also fixed a minor bug in fake_builds.go

Related to #6316.

### CODE REVIEW

**Comment by guilhermebr** [comment]
@openshift/cli-review

**Comment by fabianofranz** [comment]
@bparees PTAL

**Comment by fabianofranz** [comment]
[test]

**Comment by bparees** [comment]
lgtm, post 3.3.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
