### PR TITLE
bump(github.com/openshift/source-to-image): 2878c1ab41784dab0a467e12a…

### PR DESCRIPTION
**Pull request by jupierce**
…200659506174e68

### CODE REVIEW

**Comment by php-coder** [comment]
@jupierce it fails because origin uses API that @oatmealraisin modified a bit. I have a fix: https://github.com/php-coder/origin/commit/89066104a1dc7de90bd68a53c32f0d8535e42f0e.patch You can apply it with `git am`.

**Comment by jupierce** [comment]
Thanks @php-coder . Incorporated.

**Comment by jupierce** [comment]
[test]

**Comment by jupierce** [comment]
@oatmealraisin Error in integration test: 
```
--- FAIL: TestNewAppDetectSource (0.00s)
	newapp_test.go:1795: lstat /tmp/s2i-test032612701/.git/objects: permission denied
```
Assuming related to git changes.

**Comment by gabemontero** [comment]
Any word on this bump @jupierce ?  Is @oatmealraisin debugging that integration test error?

**Comment by gabemontero** [comment]
cool / thanks @jupierce

**Comment by jupierce** [comment]
@gabemontero Sorry, I had missed @oatmealraisin 's pull request to augment this.

**Comment by jupierce** [comment]
@bparees All clear.

**Comment by bparees** [comment]
lgtm, thanks @oatmealraisin and @jupierce 
[merge]

**Pull request merged**
