### PR TITLE
UPSTREAM: 42622: Preserve custom etcd prefix compatibility for etcd3

### PR DESCRIPTION
**Pull request by enj**
https://bugzilla.redhat.com/show_bug.cgi?id=1393744

cc @liggitt 

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
[test]

**Comment by liggitt** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
please open a PR with a cherry-pick to the release-1.5 branch as well

**Comment by soltysh** [comment]
[merge]

**Comment by enj** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1393744

**Pull request merged**
