### PR TITLE
Stop using NormalizeResources in rulevalidation

### LINKED ISSUE #13430: `rulevalidation.Covers` should not use `authorizationapi.NormalizeResources`
xref: #13334

### PR DESCRIPTION
**Pull request by simo5**
Just remove it.

Fixes #13430

### CODE REVIEW

**Comment by enj** [comment]
Covers is used by reconciliation and diagnostics, so I am not sure we can remove it yet.  @deads2k WDYT?

**Comment by liggitt** [comment]
this makes resource group tests fail, but since we normalized before migrating to RBAC, we can drop all the `groupsToResources` code and the associated tests:

```
    github.com/openshift/origin/pkg/authorization/rulevalidation.TestResourceGroupCoveringEnumerated
    github.com/openshift/origin/pkg/authorization/rulevalidation.TestEnumeratedCoveringResourceGroup
    github.com/openshift/origin/pkg/authorization/rulevalidation.TestEnumeratedMissingPartOfResourceGroup
```

**Comment by simo5** [comment]
@liggitt all tests passed, can you approve ?

**Pull request merged**
