### PR TITLE
SDN types should used fixed width integers

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
Great, thanks.  Will look at merging right after rebase.

**Comment by smarterclayton** [comment]
Please rebase and I'll merge

**Comment by smarterclayton** [comment]
Thanks again, LGTM [merge]

**Pull request merged**
