### PR TITLE
bump(k8s.io/kubernetes): d2e5420de791a3a5234eb1c3d84921d68ae2b6d6

### PR DESCRIPTION
**Pull request by mfojtik**
Fixing wrong import path for kube-gen

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

merging to unbork file.

**Comment by deads2k** [comment]
> merging to unbork file.

Actually. @mfojtik this is going to mess up the next upstream bump.

**Comment by deads2k** [comment]
> Actually. @mfojtik this is going to mess up the next upstream bump.

merging for real now.  This is going to fail the commit checker, but it has to be a mismatched name or we'll miss upstream commits on the next sync.

**Comment by mfojtik** [comment]
@kargakis i hope the prow will not die now :-)

**Comment by kargakis** [comment]
not today

**Pull request merged**
