### PR TITLE
Add bootstrap kube:admin OAuth user

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

@openshift/sig-auth @smarterclayton @derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
woot!

**Comment by smarterclayton** [comment]
I mostly follow this.  Can you add an e2e in a follow up that verifies this flow works on a cluster if no idp is configured (create the secret, verify you get an oauth token, and the token works), or skips if no idp is configured?

**Comment by smarterclayton** [comment]
/lgtm

We can iterate more before beta if we have gaps

**Pull request merged**
