### PR TITLE
expose: Set route port

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/5044

Upstream PR: https://github.com/kubernetes/kubernetes/pull/15461

@smarterclayton @pweil- @bparees @thoraxe

### CODE REVIEW

**Comment by smarterclayton** [comment]
I had a question on the upstream.

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@smarterclayton should we set the route port only when exposing multiport services or even if the service has only one port?

**Comment by liggitt** [comment]
Always set it or the route is subject to breakage if the service adds a port

**Comment by kargakis** [comment]
ok

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
