### PR TITLE
Run upstream unit tests from hack/test-go.sh

### PR DESCRIPTION
**Pull request by pmorie**
Running the upstream unit tests will help us keep the Godep'd code stable and ensure that any patches we carry are tested appropriately.

### CODE REVIEW

**Comment by pmorie** [comment]
@smarterclayton @deads2k

**Comment by smarterclayton** [comment]
Is there something to actually run the tests?  Your 323 files broke github

**Comment by pmorie** [comment]
@smarterclayton hack/test-go.sh is in the second commit (accidentally)

**Comment by pmorie** [comment]
@smarterclayton I'm still sifting through failures

**Comment by deads2k** [comment]
This fixes the SA unit tests. https://github.com/openshift/origin/pull/3852

**Comment by pmorie** [comment]
@deads2k I've got a commit for that, but I'll rebase onto your change since clayton has already tagged it merge.

**Comment by pmorie** [comment]
@smarterclayton Your upstream pull https://github.com/GoogleCloudPlatform/kubernetes/pull/9971 doesn't have tests -- I'm not sure how you got into a green state in that upstream PR but I will probably add a skip for this package for now.

**Comment by pmorie** [comment]
Still sifting through failures, I'm going to reduce the examples down to the specific ones needed for the unit tests to pass.

It should be down to some godeps that I need to add, and that's about it.

**Comment by pmorie** [comment]
Decided that I will make a script to pull in the upstream artifacts like examples, etc.

**Comment by smarterclayton** [comment]
If godep was easy to take updates on I would suggest extending it, but for
now script it.  Also make sure the rebase script and doc references it

On Jul 22, 2015, at 6:56 PM, Paul Morie <notifications@github.com> wrote:

Decided that I will make a script to pull in the upstream artifacts like
examples, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3849#issuecomment-123897271>.

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@smarterclayton @deads2k should be ready for review.

**Comment by pmorie** [comment]
I recommend going commit by commit; it's easier to process all of it that way.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by pmorie** [comment]
@smarterclayton do you need to re-bless this one?  @deads2k had a change that went in ahead of mine that resulted in a merge conflict so I had to re-push

**Comment by pmorie** [comment]
@smarterclayton looks like there is a flake in jenkins...

**Comment by smarterclayton** [comment]
Or you broke the UI

[merge]

**Comment by pmorie** [comment]
@smarterclayton I'm investigating that possibility now!

**Pull request merged**
