### PR TITLE
pkg/synthetictests/operators: Set duration for operator-state transitions

### PR DESCRIPTION
**Pull request by wking**
To make it more clear that this test is covering behavior from the whole run, using the oldest event `.from` and the youngest event `.to` to bracket the measured region.

### CODE REVIEW

**Comment by wking** [comment]
[CI cluster flakes][1]:

```
INFO[2021-07-20T22:30:26Z] Running step e2e-gcp-upgrade-ipi-conf.       
INFO[2021-07-20T23:00:26Z] pod didn't start running within 30m0s: 
```

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26343/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1417609817228316672#1:build-log.txt%3A29

**Comment by wking** [comment]
[upgrade failed to install][1]:

```
level=info msg=Cluster operator image-registry Progressing is True with Error: Progressing: Unable to apply resources: unable to sync storage configuration: Get "https://storage.googleapis.com/storage/v1/b/ci-op-vvbzhb5x-db044-84dp4-image-registry-us-central1-ubxdeihr?alt=json&prettyPrint=false&projection=full": oauth2: cannot fetch token: 400 Bad Request
level=info msg=Progressing: Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
level=error msg=Cluster operator image-registry Degraded is True with Unavailable: Degraded: The deployment does not exist
level=info msg=Cluster operator insights Disabled is False with AsExpected: 
level=info msg=Cluster operator network ManagementStateDegraded is False with : 
level=info msg=Cluster operator storage Progressing is True with GCPPDCSIDriverOperatorCR_GCPPDDriverControllerServiceController_Deploying: GCPPDCSIDriverOperatorCRProgressing: GCPPDDriverControllerServiceControllerProgressing: Waiting for Deployment to deploy pods
level=info msg=Cluster operator storage Available is False with GCPPDCSIDriverOperatorCR_GCPPDDriverControllerServiceController_Deploying: GCPPDCSIDriverOperatorCRAvailable: GCPPDDriverControllerServiceControllerAvailable: Waiting for Deployment to deploy the CSI Controller Service
level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
level=error msg=The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
level=error msg=https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
level=error msg=The 'wait-for install-complete' subcommand can then be used to continue the installation
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: image-registry, storage
```

I've never seen that before.  But [seems like it's just me][2].

/test e2e-gcp-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26343/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1417679831423782912
[2]: https://search.ci.openshift.org/?maxAge=24h&type=build-log&search=Invalid+grant:+account+not+found

**Comment by wking** [comment]
[Success][1]:

```
[sig-arch] Monitor cluster while tests execute
Run #0: Failed expand_more	1h16m13s
Run #1: Passed expand_more	1h16m13s
...
: [bz-apiserver-auth] clusteroperator/authentication should not change condition/Available
Run #0: Failed expand_more	1h16m13s
Run #1: Passed expand_more	0s
```

I think the fake-pass run injected to make the case a non-fatal flake should use 0s duration.  Want me to file a follow-up to do that for `Monitor cluster while tests execute` too?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26343/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1417705070094454784

**Comment by bparees** [comment]
https://github.com/openshift/release/pull/20514 to stop triggering the metal test.

/override  ci/prow/e2e-metal-ipi-ovn-ipv6

**Pull request merged**
