### PR TITLE
Add ./hack/build-in-docker.sh script

### PR DESCRIPTION
**Pull request by mfojtik**
As discussed in #799 

This script will use the `openshift/origin-release` image to build the Origin Go sources using volume mount, so you don't need to have any Go packages installed in your host system. The output binaries are compiled against Fedora 20 Go+system libs, so they should work in Vagrant out of box (which eliminate the need to run ./hack/build-go.sh inside Vagrant). 

UPDATE:

As a bonus, the `./hack/build-in-docker.sh` script accepts '--check' option that will tell you if there are any issues with your code (golint for local branch + gofmt).

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
--check should always be run.

**Comment by smarterclayton** [comment]
well, gofmt should always be run.

**Comment by mfojtik** [comment]
@smarterclayton both should always run if you are a good developer ;-)

**Comment by smarterclayton** [comment]
Golint is a bit opinionated :)

----- Original Message -----

**Comment by smarterclayton** [comment]
gofmt should fail a build, i'm a bit on the fence about making golint fail anything

**Comment by mfojtik** [comment]
@smarterclayton golint should not fail, it is just informative. updating this PR

**Comment by mfojtik** [comment]
@smarterclayton second look?

**Comment by mfojtik** [comment]
@smarterclayton fixed

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
will add docs for this tomorrow

**Pull request merged**
