### PR TITLE
Bug 1981582: [release-4.6] use vpa package and add debug logs to olm test

### PR DESCRIPTION
**Pull request by exdx**
Signed-off-by: Daniel Sover <dsover@redhat.com>

supersedes #26326

### CODE REVIEW

**Review by ecordell — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
Patch manager comment: Not picking as it seems this needs to merge along with https://github.com/openshift/origin/pull/26326

**Comment by exdx** [comment]
> Patch manager comment: Not picking as it seems this needs to merge along with #26326 which is not ready

Sorry for the confusion: this PR supercedes #26326 which will be closed. This is ready to merge.

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.80

picked

**Pull request merged**
