### PR TITLE
Follow up feedback on signed output for tools extraction

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
/assign @wking 

feedback from #22555

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22577/pull-ci-openshift-origin-master-e2e-aws-serial/4828

**Pull request merged**
