### PR TITLE
fix pre-deploy hook args on cakephp example

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
[testextended][extended:core(images)]

**Comment by csrwng** [comment]
@bparees how is this fixing args (apart from changing the deployment strategy?)

**Comment by bparees** [comment]
@csrwng that's all it's doing.

**Comment by csrwng** [comment]
ahh nm, I see the predeploy hook is defined in "recreateParams" which would be ignored if strategy == "rolling"

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
@csrwng yeah which makes me wonder how this has ever worked... perhaps migratedb isn't that important? :/

**Comment by bparees** [comment]
@csrwng fyi it looks like the hook is in fact run either way.  whether it should be or not is a question to be resolved in https://github.com/openshift/origin/issues/10570

**Comment by csrwng** [comment]
interesting. well, at least the template is more correct now :)

**Comment by bparees** [comment]
evidently "images" is still catching an extra (and failing) TC, alas.. but the tests we care about passed.
[merge]

**Comment by bparees** [comment]
[testextended][extended:core(\[images\])]

**Pull request merged**
