### PR TITLE
Proposals for simplifying the router template 

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
envIf(name, defaultValue, pattern) grabs environment variables and validates them if validation fails return a default

annotation(userValue, defaultValue,pattern) grabs an annotation and validates returning a default if validation fails

I included some examples of the new functions removing lines from the router template. If there is agreement that this is valuable more of the simplification functions can be added

### CODE REVIEW

**Comment by smarterclayton** [comment]
Once we add a function to the template it becomes a public API and we cannot remove it without versioning.  So we need to fit that into our versioning strategy for router templates (and the planned ingress -> service -> endpoints changes to the template itself need to be part of that).  We should write up a description of the API provided to templates and changes to the template should be required to also modify the description.

**Comment by liggitt** [comment]
same goes for the passed-in data structure. we should have a test template that exercises the data structure and functions and make it part of a text (extended or otherwise) so we know if compatibility is broken

**Comment by JacobTanenbaum** [comment]
@knobunc

**Comment by knobunc** [comment]
The problem we are trying to solve is that we have things like:
```
              {{ with $healthIntv := index $cfg.Annotations "router.openshift.io/haproxy.health.check.interval" }}
                {{ if (matchPattern "[1-9][0-9]*(us|ms|s|m|h|d)?" $healthIntv) }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter {{$healthIntv}} weight {{$weight}}
                {{ else }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter 5000ms weight {{$weight}}
                {{ end }}
              {{ else }}
                {{ if (matchPattern "[1-9][0-9]*(us|ms|s|m|h|d)?" (env "ROUTER_BACKEND_CHECK_INTERVAL" "")) }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter {{env "ROUTER_BACKEND_CHECK_INTERVAL" "5000ms"}} weight {{$weight}}
                {{ else }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter 5000ms weight {{$weight}}
                {{ end }}
              {{ end }}
```

Which with these changes becomes:
```
              {{ with annotationIf ( index $cfg.Annotations "router.openshift.io/haproxy.health.check.interval" ) "5000ms" "[1-9][0-9]*(us|ms|s|m|h|d)?"}}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter {{.}} weight {{$weight}}
              {{ else }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter {{envIf "ROUTER_BACKEND_CHECK_INTERVAL" "5000ms" "[1-9][0-9]*(us|ms|s|m|h|d)?" }} weight {{$weight}}
              {{ end }}
```

But there's still a lot of redundancy, does something that returns the first matching value do the trick?
```
              {{ with firstMatch "[1-9][0-9]*(us|ms|s|m|h|d)?" (index $cfg.Annotations "router.openshift.io/haproxy.health.check.interval") (env "ROUTER_BACKEND_CHECK_INTERVAL" "") "5000ms" }}
  server {{$endpoint.IdHash}} {{$endpoint.IP}}:{{$endpoint.Port}} check inter {{.}} weight {{$weight}}
              {{ end }}
```

The plus of the last one is that it gets rid of the redundancy and the template becomes a little more clear.

**Pull request closed without merging**
