### PR TITLE
Adjust build test images for multi-arch support

### PR DESCRIPTION
**Pull request by yselkowitz**
This includes a [test image rebase](https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md).

/cc @sttts 
/cc @dmage

### CODE REVIEW

**Comment by yselkowitz** [comment]
FYI this is used in build and jenkins tests, and commented-out parts of image-eco.
/cc @gabemontero @adambkaplan @akram

**Comment by gabemontero** [comment]
```
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:21 +0000 UTC - event for nfs-server: {multus } AddedInterface: Add eth0 [10.129.2.14/23] from openshift-sdn
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:21 +0000 UTC - event for nfs-server: {kubelet ip-10-0-250-249.us-east-2.compute.internal} Pulling: Pulling image "quay.io/openshift/community-e2e-images:e2e-quay-io-redhat-developer-nfs-server-1-1-dlXGfzrk5aNo8EjC"
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:21 +0000 UTC - event for nfs-server: {kubelet ip-10-0-250-249.us-east-2.compute.internal} Failed: Failed to pull image "quay.io/openshift/community-e2e-images:e2e-quay-io-redhat-developer-nfs-server-1-1-dlXGfzrk5aNo8EjC": rpc error: code = Unknown desc = reading manifest e2e-quay-io-redhat-developer-nfs-server-1-1-dlXGfzrk5aNo8EjC in quay.io/openshift/community-e2e-images: manifest unknown: manifest unknown
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:21 +0000 UTC - event for nfs-server: {kubelet ip-10-0-250-249.us-east-2.compute.internal} Failed: Error: ErrImagePull
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:22 +0000 UTC - event for nfs-server: {kubelet ip-10-0-250-249.us-east-2.compute.internal} BackOff: Back-off pulling image "quay.io/openshift/community-e2e-images:e2e-quay-io-redhat-developer-nfs-server-1-1-dlXGfzrk5aNo8EjC"
Nov 12 13:15:19.751: INFO: At 2021-11-12 13:10:22 +0000 UTC - event for nfs-server: {kubelet ip-10-0-250-249.us-east-2.compute.internal} Failed: Error: ImagePullBackOff
```

^^ @yselkowitz last I dealt with this you need to engage with either @soltysh or @smarterclayton to manually pull the trigger on getting the mirrored image pushed to quay.io

https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md

**Comment by yselkowitz** [comment]
@sttts is also listed in OWNERS there, but I'm not picky :-)

**Comment by yselkowitz** [comment]
/cc @smarterclayton @soltysh @sttts
for a test image update.

**Comment by yselkowitz** [comment]
Ping @smarterclayton @soltysh @sttts for a test image update per https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md

**Comment by smarterclayton** [comment]
@soltysh can you do the image mirror for this PR?  If not I'll do it (hopfeully tomorrow, but might get delayed)

**Comment by soltysh** [comment]
Should be mirrored by now, let's see
/retest

**Comment by gabemontero** [comment]
I'm out next week

/assign @adambkaplan

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
the image bits
/hold 
for @adambkaplan last set of eyes

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
