### PR TITLE
Adding template instructional message to new-app output

### PR DESCRIPTION
**Pull request by jupierce**
To continue debate on #9708
@bparees @smarterclayton @deads2k @liggitt @jorgemoralespou

### CODE REVIEW

**Comment by bparees** [comment]
ok, game on.... :)

for those who need a refresher, here's what the new output looks like w/ this PR:

```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template simple for "simple"
     With parameters:
      ADMIN_USERNAME=admin8RT # generated
      ADMIN_PASSWORD=Mw2hwJak # generated
      REDIS_PASSWORD=Xt4Jh81h # generated
      SLAVE_SERVICE_NAME=redis-slave
     Message: Your admin credentials are admin8RT:Mw2hwJak
--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

"lgtm"

**Comment by smarterclayton** [comment]
It does not stand out enough.

**Comment by smarterclayton** [comment]
I'd probably expect leading and trailing newlines between the message and
the section above.  I also don't know that I expect "Message: ".

**Comment by bparees** [comment]
let's put "MESSAGE:" in all caps.

(kidding)


On Tue, Jul 12, 2016 at 9:05 PM, Clayton Coleman <notifications@github.com>
wrote:

> It does not stand out enough.
>
> On Tue, Jul 12, 2016 at 4:06 PM, Ben Parees <notifications@github.com>
> wrote:
>
> > ok, game on.... :)
> >
> > for those who need a refresher, here's what the new output looks like w/
> > this PR:
> >
> > [root@localhost origin]# oc new-app --template=simple
> > --> Deploying template simple for "simple"
> > With parameters:
> > ADMIN_USERNAME=admin8RT # generated
> > ADMIN_PASSWORD=Mw2hwJak # generated
> > REDIS_PASSWORD=Xt4Jh81h # generated
> > SLAVE_SERVICE_NAME=redis-slave
> > Message: Your admin credentials are admin8RT:Mw2hwJak
> > --> Creating resources ...
> > secret "testsecret" created
> > secret "testsecret2" created
> > --> Success
> > Run 'oc status' to view your app.
> >
> > "lgtm"
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/openshift/origin/pull/9806#issuecomment-232163556>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABG_pzq7nrqL6YxrCzBBCF-XD8sf1Quqks5qU_PXgaJpZM4JKqdc
> >
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/pull/9806#issuecomment-232226858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3voni8T1OkgEYPclLWk7NvFL7YJkks5qVDnugaJpZM4JKqdc>
> .
>



-- 
Ben Parees | OpenShift

**Comment by bparees** [comment]
I agree that "Message:" might not be the best label/prefix for the information.  newline sounds like a good idea too.

**Comment by bparees** [comment]
@smarterclayton @jupierce how about:

```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template simple for "simple"
     With parameters:
      ADMIN_USERNAME=admin8RT # generated
      ADMIN_PASSWORD=Mw2hwJak # generated
      REDIS_PASSWORD=Xt4Jh81h # generated
      SLAVE_SERVICE_NAME=redis-slave
      ========= Template Information ==========
      Your admin credentials are admin8RT:Mw2hwJak

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

?

**Comment by smarterclayton** [comment]
Too heavy.  I'd want it to look similar to how we display the
description of an image in new-app

**Comment by bparees** [comment]
image description like this?

```
--> Found Docker image c014669 (2 days old) from Docker Hub for "openshift/jenkins-1-centos7"

    * An image stream will be created as "jenkins-1-centos7:latest" that will track this image
    * This image will be deployed in deployment config "jenkins-1-centos7"
    * Ports 50000/tcp, 8080/tcp will be load balanced by service "jenkins-1-centos7"
      * Other containers can access this service through the hostname "jenkins-1-centos7"
    * This image declares volumes and will default to use non-persistent, host-local storage.
      You can add persistent volumes later by running 'volume dc/jenkins-1-centos7 --add ...'

```

Are you saying the message should just be a bullet that says something like "* This information:  [insert message]"?

(and then we'd make "With parameters" also a bullet?)

putting it all together:
```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template simple for "simple"
     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave
     * Template information: Your admin credentials are admin8RT:Mw2hwJak

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

?

**Comment by smarterclayton** [comment]
No, that image has no description it looks like.  The Ruby or Python
image should

**Comment by bparees** [comment]
```
--> Found Docker image 187ed02 (5 days old) from Docker Hub for "centos/ruby-23-centos7"

    Ruby 2.3 
    -------- 
    Platform for building and running Ruby 2.3 applications

    Tags: builder, ruby, ruby23, rh-ruby23

    * An image stream will be created as "ruby-23-centos7:latest" that will track this image
    * This image will be deployed in deployment config "ruby-23-centos7"
    * Port 8080/tcp will be load balanced by service "ruby-23-centos7"
      * Other containers can access this service through the hostname "ruby-23-centos7"

--> Creating resources with label app=ruby-23-centos7 ...
    imagestream "ruby-23-centos7" created
    deploymentconfig "ruby-23-centos7" created
    service "ruby-23-centos7" created
--> Success (DRY RUN)

```


So:
```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template for "simple"
     Simple
     ---------
     Your admin credentials are admin8RT:Mw2hwJak

     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

?

(note i've retained the bullets for the parameters section, i think they are an improvement).

I also removed the template name from the first line and used it in the header instead.

**Comment by smarterclayton** [comment]
Minor tweaks

```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template for "simple"

     Simple
     ---------
     Your admin credentials are admin8RT:Mw2hwJak

     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

**Comment by bparees** [comment]
i think the only tweak i see is the additional newline, works for me.

For templates that have no message what will we display?  just:
```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template for "simple"

     Simple
     ---------

     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

?

**Comment by bparees** [comment]
or maybe

```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template for "simple"

     Simple
     ---------
     No template deployment message provided

     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

?

**Comment by smarterclayton** [comment]
Eh, if you have no message, just a newline between template and "with parameters" (no title, no description)

**Comment by smarterclayton** [comment]
Sorry, if you have no title or description.

**Comment by smarterclayton** [comment]
Actually, if we don't respect those for templates that may be something:

1. Title or name (if 2 or 3)
2. Message if any
3. Description if no message

If nothing, just a newline

**Comment by bparees** [comment]
I think we always have a title (it's the template metadata name).  So if we're not going to display it as a "title" then we need to put it back in the first line ("deploying Simple for "simple") to at least make it clear somewhere what template we actually picked.

**Comment by smarterclayton** [comment]
The first line contains what the user entered (so the user knows that their input corresponded to something else).  I was referring to the "display name" of the template.

**Comment by bparees** [comment]
templates don't have "display names"

one more try:

```
[root@localhost origin]# oc new-app --template=simple
--> Deploying template [metadata.name] for "[user argument]"

     [metadata.name]  // only if (message!=null || description !=null)
     ---------    // only if (message!=null || description !=null)
     [message || description]    // only if (message!=null || description !=null)

     * With parameters:
        * ADMIN_USERNAME=admin8RT # generated
        * ADMIN_PASSWORD=Mw2hwJak # generated
        * REDIS_PASSWORD=Xt4Jh81h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    secret "testsecret" created
    secret "testsecret2" created
--> Success
    Run 'oc status' to view your app.
```

since metadata.name might be shown twice now, we can get fancier and say for:
--> Deploying template [metadata.name] for "[user argument]"

only print the metadata.name if we're not going to print it below.  or we can just always print it twice.

**Comment by smarterclayton** [comment]
Why don't templates have display names?

**Comment by bparees** [comment]
@smarterclayton it never came up.  Can't you ask the same question about deploymentconfigs, buildconfigs, etc?

**Comment by bparees** [comment]
(in other words if it's something we think we want, doesn't it belong on ObjectMeta?)

**Comment by smarterclayton** [comment]
The describers and the console should show display name for most things.

**Comment by smarterclayton** [comment]
It's an annotation we respect fairly consistently, and especially in new-app.

**Comment by bparees** [comment]
well there's still no guarantee we have one, so replace all my "metadata.name" references above with "annotation.disiplayName || metadata.name"

**Comment by smarterclayton** [comment]
sure.

**Comment by jupierce** [comment]
```
[root@localhost origin]# oc new-app --dry-run --template=guestbook-example
--> Deploying template "Guestbook Example" in project "default" for "guestbook-example"

     Guestbook Example
     ---------
     Your admin credentials are adminD2H:TXjHcM2B

     * With parameters:
        * ADMIN_USERNAME=adminD2H # generated
        * ADMIN_PASSWORD=TXjHcM2B # generated
        * REDIS_PASSWORD=fbMsRO0h # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
    route "frontend-route" created
    service "frontend-service" created
    service "redis-master" created
    service "redis-slave" created
    pod "redis-master" created
    replicationcontroller "guestbook" created
    replicationcontroller "redis-slave" created
--> Success (DRY RUN)
```

**Comment by bparees** [comment]
i'm happy with it, @smarterclayton may not like the redundancy of showing the template name twice.

**Comment by smarterclayton** [comment]
I don't.

**Comment by jupierce** [comment]
I think there is value in being able to glance at a consistent, highly prominent line and know what took place. This always benefits scripting/testing, but even with humans, your user (for reasons they will not understand) will otherwise sometimes see all the information they need in a concise message while at other times see a vague message and need to intuit the need to visually scan for a string floating above "---------". 

To that end, perhaps we can keep the --> line consistent/technical/parsable:
```
--> Deploying template "<meta.name>" [in project "default"] [for "<input>"]

     <display-name|meta.name>
     ---------
     <message|description>
```

The optional ``"for <input>"`` will not be shown if meta.name==input which eliminates the worst redundancy offender. Changing: 
```
--> Deploying template "guestbook-example" in project "default" for "guestbook-example"
```
into:
```
--> Deploying template "guestbook-example" in project "default"
```

This approach would ensure a well designed template (i.e. with a display-name) would not display any redundant information while being processed by new-app. Templates without display-names would have some redundancy, but it would afford us a consistent experience.

**Comment by bparees** [comment]
@jupierce it works for me, but i'm not the one who needs to be convinced :)

**Comment by smarterclayton** [comment]
Showing meta.name at least once is important, and what you've described is
the original intent of the first line of the new-app output.

**Comment by bparees** [comment]
it is being displayed at least once, so i'm not clear on your objection?

**Comment by jupierce** [comment]
Latest commit:

With display-name and message.
```
--> Deploying template guestbook-example

     Guestbook Example
     ---------
     Your admin credentials are adminACN:GNU6KwSa

     * With parameters:
        * ADMIN_USERNAME=adminACN # generated
        * ADMIN_PASSWORD=GNU6KwSa # generated
        * REDIS_PASSWORD=RpcaM0nG # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

Removing message:
```
--> Deploying template guestbook-example

     Guestbook Example
     ---------
     Example shows how to build a simple multi-tier application using Kubernetes and Docker

     * With parameters:
        * ADMIN_USERNAME=admin8CX # generated
        * ADMIN_PASSWORD=3uMo0EJQ # generated
        * REDIS_PASSWORD=he0IEsi0 # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

Removing display-name:
```
--> Deploying template guestbook-example

     guestbook-example
     ---------
     Example shows how to build a simple multi-tier application using Kubernetes and Docker

     * With parameters:
        * ADMIN_USERNAME=admin5AS # generated
        * ADMIN_PASSWORD=PYxeDWJO # generated
        * REDIS_PASSWORD=XaFPMNN6 # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

Removing description:
```
--> Deploying template guestbook-example

     * With parameters:
        * ADMIN_USERNAME=adminLDJ # generated
        * ADMIN_PASSWORD=MVXwd0dB # generated
        * REDIS_PASSWORD=xVqmPMLF # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

**Comment by jupierce** [comment]
@smarterclayton How is the latest output looking to you?

**Comment by smarterclayton** [comment]
If a template author has a really good description AND a message, do
we want to show both?  If we only show one, it means the web UI sees
both but the cli only sees one.  I don't think we want to encourage
authors to copy their description into their message.

**Comment by jupierce** [comment]
How about: 
```
--> Deploying template "<meta.name>" [in project "default"] [for "<input>"]

     <display-name|meta.name> [- <description>]
     ---------
     [message]
   
     [parameters]
```
Where "---------" would only be included if (message||parameter) existed. 

Which would yield something like:
```
     Guestbook Example - Example shows how to build a simple multi-tier application using Kubernetes and Docker
     ---------
     Your admin credentials are adminACN:GNU6KwSa

     * With parameters:
        * ADMIN_USERNAME=admin8CX # generated
        * ADMIN_PASSWORD=3uMo0EJQ # generated
        * REDIS_PASSWORD=he0IEsi0 # generated
        * SLAVE_SERVICE_NAME=redis-slave
```

**Comment by smarterclayton** [comment]
No, we don't put descriptions on the title line because they can be very
long and wrap (also, that would mean images and templates are being laid
out differently, which is wrong).

<display-name|meta.name>
----------------------------
[description]

[message]

No less than 1 empty line between description and message

**Comment by jupierce** [comment]
Sure thing! Here is the latest:

With display-name, description, and message:
```
--> Deploying template good-guestbook

     Good Guestbook Example
     ---------
     Example shows how to build a simple multi-tier application using Kubernetes and Docker

     Your admin credentials are adminV06:BldxxCpU.

     * With parameters:
        * ADMIN_USERNAME=adminV06 # generated
        * ADMIN_PASSWORD=BldxxCpU # generated
        * REDIS_PASSWORD=0tvAtImp # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

With display-name, description:
```
--> Deploying template ok-guestbook

     OK Guestbook Example
     ---------
     Example shows how to build a simple multi-tier application using Kubernetes and Docker

     * With parameters:
        * ADMIN_USERNAME=adminWXM # generated
        * ADMIN_PASSWORD=8Sda4qjn # generated
        * REDIS_PASSWORD=QvabSQoq # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

With only description:
```
--> Deploying template poor-guestbook

     poor-guestbook
     ---------
     Example shows how to build a simple multi-tier application using Kubernetes and Docker

     * With parameters:
        * ADMIN_USERNAME=adminNH8 # generated
        * ADMIN_PASSWORD=I7ahHSEV # generated
        * REDIS_PASSWORD=VAiem4V1 # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

With no explanatory metadata:
```
--> Deploying template bad-guestbook

     * With parameters:
        * ADMIN_USERNAME=adminEVQ # generated
        * ADMIN_PASSWORD=MbYsd2of # generated
        * REDIS_PASSWORD=tkC0jgU6 # generated
        * SLAVE_SERVICE_NAME=redis-slave

--> Creating resources ...
```

**Comment by smarterclayton** [comment]
Looks good

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9457
[merge]

**Comment by smarterclayton** [comment]
[merge] #9457

**Comment by smarterclayton** [comment]
[merge] #9680

**Comment by smarterclayton** [comment]
[test] secret mount issue

**Comment by smarterclayton** [comment]
[test] applied cluster resource quota

**Comment by bparees** [comment]
[merge]

**Pull request merged**
