### PR TITLE
Bug 1316352: use platform-agnostic helper in oc edit

### PR DESCRIPTION
**Pull request by kargakis**
ref issue: https://bugzilla.redhat.com/show_bug.cgi?id=1316352

### CODE REVIEW

**Comment by kargakis** [comment]
cc: @fabianofranz

**Comment by fabianofranz** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
aws flake

[merge]

**Comment by kargakis** [comment]
aws flake again [merge]

**Comment by kargakis** [comment]
mergemergemerge[merge]mergemergemerge

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
image import flake [merge]

**Pull request merged**
