### PR TITLE
Ignore Search Registries for Build Controller Config

### PR DESCRIPTION
**Pull request by adambkaplan**
This will allow https://github.com/openshift/api/pull/192 to bump cleanly in origin.

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

hold is pending PM approval/sign-off.

**Comment by adambkaplan** [comment]
/hold cancel

PM approval from @mpbarrett and @sspeiche

**Comment by adambkaplan** [comment]
/retest

Install failure due to AWS timeout

**Comment by adambkaplan** [comment]
/retest

CI bot why have you forsaken me?

**Pull request merged**
