### PR TITLE
Add the both ROUTER_SERVICE*SNI_PORT

### PR DESCRIPTION
**Pull request by cw-aleks**
We want to use more the one router on the same node => Router sharding.

There is also a bugzilla entry https://bugzilla.redhat.com/show_bug.cgi?id=1343083

### CODE REVIEW

**Comment by knobunc** [comment]
LGTM

@ramr PTAL

**Comment by ramr** [comment]
LGTM

**Comment by ramr** [comment]
[test]

**Comment by ramr** [comment]
re [test]

**Comment by ramr** [comment]
[test] again

**Comment by knobunc** [comment]
@eparis check and merge please?

**Comment by eparis** [comment]
[merge]

**Pull request merged**
