### PR TITLE
Update s2i to fix setting environment

### PR DESCRIPTION
**Pull request by php-coder**
Related PR: https://github.com/openshift/source-to-image/pull/509

PTAL @bparees

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, thanks @php-coder and @mnagy 
[merge]

**Comment by kargakis** [comment]
@mfojtik

**Comment by mfojtik** [comment]
another one..

**Comment by bparees** [comment]
Another what? This wasn't your regression, it got introduced later during a refactor.

**Comment by mfojtik** [comment]
@bparees another rebase breaker ;-)) don't worry already fixed the conflicts :)

**Pull request merged**
