### PR TITLE
refactor buildImage function parameters

### PR DESCRIPTION
**Pull request by guangxuli**
When I read the code of building process, i found that there are 9 parameters in func 'buildImage'.  So many parameters that are inappropriate, I think we can add some parameters refactoring which make the code more easier to read.

### CODE REVIEW

**Comment by guangxuli** [comment]
@mfojtik ptal, thanks!

**Comment by guangxuli** [comment]
@bparees thanks, I have modified the verify error. Can you review the code for this PR.

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
