### PR TITLE
Fix godeps

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik @sttts this is the fix godeps PR that should clean the godeps mess, for now at least. 

What worries me is that during `godep save` we're failing on `github.com/kr/pretty` which is needed somewhere in tests in one of the dependent packages. I don't want to add it yet, but after go getting it I was able to successfully run `godep save`, so I'm wondering. 

This definitely fixes the image related godeps and additionally I found we don't need `github.com/flynn/go-shlex` anymore, so I dropped this one as well. ptal

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by sttts** [comment]
Flake https://github.com/openshift/origin/issues/13945

**Comment by sttts** [comment]
re[test]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/14122

[test]

**Comment by mfojtik** [comment]
LGTM, tested the signature work and seems to all work fine. Good job!

[merge]

**Pull request merged**
