### PR TITLE
bump(github.com/openshift/source-to-image): 07947a6f4fee815cbe97db93c026d8aa4c9804a9

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/10773
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
extended tests failed due to disk space limitations.

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13050
[test]

**Pull request merged**
