### PR TITLE
auto-manage system roles on startup

### PR DESCRIPTION
**Pull request by deads2k**
Remove system:* roles and rolebindings from policy.json.  One master start, the system:* roles are diffed into the existing system:* roles and created/updated as appropriate.  system:* rolebindings are checked for equivalence and covers and mutated appropriately.

This obviates the need for system:* role permissions to be updated manually since we own those roles

@liggitt ptal
@smarterclayton approval?  This would eliminate manual steps like @liggitt had to describe in his note.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Post 3.0.  We need to have a longer discussion about whether we own system: or not.

**Comment by deads2k** [comment]
> Post 3.0.

This has an impact on the user-facing `policy.json`.  If we don't make a choice before 3.0, and we do decide that we own those roles (likely), then we'll have a needlessly confusing file.

The argument for owning those roles is pretty straightforward.  We own those roles in order to bind them to specific serviceaccounts in "openshift-infra".  Those serviceaccounts are used to run internal components of OpenShift that must have sufficient permissions to perform their responsibilities.  Those responsibilities are likely to have different implementations over time, but it's unreasonable for a user to expect to deny power to a build controller (as a for instance).  Since we need to remain working seamlessly over upgrades and we are only binding these roles to internal components, we should be able to change them at will.

**Comment by smarterclayton** [comment]
We can always create a new "system-policy.json" and help users make the split.  The issue comes with the first update - this will be a good test for us to properly deal with it.

**Comment by deads2k** [comment]
If we want to be able to run the e2e (basic functionality) test against older generated configs, then we need this feature. None of the older images I have to choose from can produce compatible configurations because the system:* policy roles are out of date.

**Comment by smarterclayton** [comment]
Let's focus on just starting the server and the API being available.

**Comment by deads2k** [comment]
> Let's focus on just starting the server and the API being available.

Short term or long term?  As a long term test, it seems reasonable to expect the core functionality that worked when the config was created to continue working.

**Comment by smarterclayton** [comment]
Sure.

**Comment by deads2k** [comment]
I'd like to close on whether or not we should do this.  I think it's a must-have to have seamless upgrades for internal components.

**Comment by smarterclayton** [comment]
We need to write up the larger upgrade plan for deployments and then describe how this fits.  Traditionally this would be broken into two phases - add extra policy prior to upgrade, perform complete roll out, remove old permissions (equivalent to add column, support both, remove old).  We will probably put that in tooling, not necessarily in the product since anything we do has to work with rolling upgrades.

**Comment by deads2k** [comment]
> We will probably put that in tooling, not necessarily in the product since anything we do has to work with rolling upgrades.

Since we're supposed to support backward and forward compatibility, we can never remove old permissions, only add new ones.

**Comment by smarterclayton** [comment]
We can remove old permissions during a migration by telling administrators whether they want to remove them.

**Comment by deads2k** [comment]
I still think we should claim ownership of these and automatically mutate them, but with the new reconcile command this isn't strictly needed.

**Pull request closed without merging**
