### PR TITLE
Remove alpha versions based on TechPreviewNoUpgrade feature

### PR DESCRIPTION
**Pull request by soltysh**
/hold
for testing

This will be needed to bring back https://github.com/openshift/cluster-kube-apiserver-operator/pull/1536 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1538

/assign @benluddy @bertinatto

### CODE REVIEW

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial

**Comment by deads2k** [comment]
/hold

still missing the data in k/k

**Comment by soltysh** [comment]
> still missing the data in k/k

the data re in k/k, see https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/integration/etcd/data.go#L473-L489 and https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/integration/etcd/data.go#L400-L409

the if proposed in this PR, makes sure we don't remove them from that map when the techpreview is on, in all other cases, since these are alpha APIs we don't enable by default, they are removed from the reference maps.

**Pull request closed without merging**
