### PR TITLE
README for nginx router

### PR DESCRIPTION
**Pull request by rajatchopra**
Steps to start nginx router on openshift

@weliang1 PTAL Thank you.

@openshift/sig-networking

### CODE REVIEW

**Comment by weliang1** [comment]
Please update " –images=openshift/nginx-router" to "--images=openshift/nginx-router", and delete " [root@qe-weliang-37master-etcd-nfs-1 ~]" from the file.

Then LGTM

**Comment by rajatchopra** [comment]
Thanks @weliang1 Fixed.

**Comment by imcsk8** [comment]
LGTM

**Comment by rajatchopra** [comment]
Closing in favour of #17096, because I happened to create this patch from a branch on openshift/origin itself.

**Pull request closed without merging**
