### PR TITLE
Update sample app README to use login and project commands

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by soltysh** [comment]
This is very unfortunate PR, since `osc build-logs` won't work with this change, see:
```
[vagrant@openshiftdev origin]$ osc build-logs ruby-sample-build-1
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "\"/osapi/v1beta1/proxy/buildLogs/ruby-sample-build-1?namespace=test\" is forbidden because test-admin cannot proxy on buildLogs with name \"ruby-sample-build-1\" in test",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

**Comment by fabianofranz** [comment]
@soltysh Seems you are testing with Vagrant, correct? The complete process worked fine with a simple build from source, so let me check it it's related to Vagrant only.

**Comment by soltysh** [comment]
Correct, it was on vagrant. For the discussion around the problems with
build logs after logging in you can have a look at my PR #1549.

**Comment by fabianofranz** [comment]
@soltysh Confirmed the issue (outside vagrant).

@smarterclayton @bparees The use of `osc login` breaks the `osc build-logs` part of sample app's flow in README because now only cluster admins are allowed to proxy (related discussion in https://github.com/openshift/origin/pull/1549). Should we revert the use of login here for now, or leave it as is until build logs get moved?

**Comment by bparees** [comment]
@fabianofranz yes we should definitely revert this and in the future if we're adding commands to the readme, they should be added to the e2e steps at the same time (which would have caught this issue)

**Comment by soltysh** [comment]
+1

**Comment by fabianofranz** [comment]
@bparees This was on e2e already, but was part of a separate PR merged before docs. I'll make sure it's in the same PR in future.

Actually instead of reverting everything in README we can just run the `build-logs` command as cluster admin, and keep everything else as is. It's in fact what e2e is doing since https://github.com/openshift/origin/commit/16df0e885d6dcc5b912eebb861e2ea69b1d3fdb2. I'll open a PR with the change.

**Comment by fabianofranz** [comment]
@bparees @soltysh https://github.com/openshift/origin/pull/1617

**Comment by bparees** [comment]
Sounds good. Thanks! 

Ben Parees | OpenShift

**Comment by soltysh** [comment]
@fabianofranz that's even better, thx for doing this :+1:

**Pull request merged**
