### PR TITLE
Log the reload output for admins in the router logs

### LINKED ISSUE #8142: Router reload info not displayed in logging
Users can't figure out why reload is failing.  Make it loggable. Also, we print -x which is too much output.  Fix the output.

### PR DESCRIPTION
**Pull request by smarterclayton**
Trim down the output for debugging. Remove -x

@ramr

Fixes #8142

### CODE REVIEW

**Comment by ramr** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@ramr having trouble understanding how this change could break the router

**Comment by smarterclayton** [comment]
Maybe the pipe fail?

**Comment by ramr** [comment]
Yeah, it should be the pipefail since the first time in there would be no haproxy processes and that cause us to fail before we start an haproxy process.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
