### PR TITLE
Add navbar-utility-mobile to error.html

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://github.com/openshift/origin/issues/8198

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
@sg00dwin Low risk enough for 1.2, I think. Needs bindata in that case.

**Comment by sg00dwin** [comment]
@spadgett bindata added

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
