### PR TITLE
[release-3.11] Bug 1769952: React to openshift/ruby-hello-world change

### PR DESCRIPTION
**Pull request by adambkaplan**
Update build, cmd, and integration tests to use centos/ruby-25-centos7 image

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 

We had a green run before I squashed.

**Comment by adambkaplan** [comment]
@akram looks like the BZ bots got confused a bit. 4.1 bug is in `MODIFIED` state now.

**Comment by bparees** [comment]
/bugzilla override

almost entirely non-shipping file changes and this is blocking critical delivery of other PRs.  Only shippping change is a minor text/help output change.

**Pull request merged**
