### PR TITLE
Bug 2038481: Flake failed sandboxes from bug in new guard pods

### PR DESCRIPTION
**Pull request by jluhrsen**
more info in https://bugzilla.redhat.com/show_bug.cgi?id=2038481

essentially, two new guard pods are being started in 4.10+ and
are incorrectly being restarted on a cordoned node and when the
node is rebooted those pods fail to set up sandboxes right away
before the underlying network config file is present. This can
be reverted when the PR to fix this is merged:
  https://github.com/openshift/library-go/pull/1287

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold
looks like the possible [real fix](https://github.com/openshift/library-go/pull/1287#issuecomment-1016414473) for this was merged. I'll check the results of that and get back to this if needed.

**Comment by vrutkovs** [comment]
Still happens fairly often:
* [1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015675633569792)
* [2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015675675512832)
* [3](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015676141080576)
* [4](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015676971552768)

/retest

**Comment by jluhrsen** [comment]
> Still happens fairly often:
> 
> * [1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015675633569792)
> * [2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015675675512832)
> * [3](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015676141080576)
> * [4](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484015676971552768)
> 
> /retest

right, I had assumed the "real fix" was all that was needed. Actually it was just the foundation in library-go that needed to go
in before the 3 real fixes could land. those are here:
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1295
https://github.com/openshift/cluster-kube-scheduler-operator/pull/397
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/591

I will check in on those and if they don't look like they'll be merged in a timely fashion (I get the sense they will be),
then we can see about merging this origin PR.

**Comment by deads2k** [comment]
The explanation in the bugs makes sense.

/lgtm
/approve
/hold

verify failure is real.

**Comment by deads2k** [comment]
merged in https://github.com/openshift/origin/pull/26776

**Pull request closed without merging**
