### PR TITLE
wait for group cache in templateinstance tests

### LINKED ISSUE #16654: [Conformance][templates] templateinstance impersonation tests should pass impersonation creation tests [Suite:openshift/conformance/parallel]
Details: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16652/test_pull_request_origin_extended_conformance_install_update/7228/

```
Expected error:
    <*errors.StatusError | 0xc421d33b80>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "TemplateInstance.template.openshift.io \"test\" is invalid: spec.requester.username: Forbidden: you do not have permission to set username",
            Reason: "Invalid",
            Details: {
                Name: "test",
                Group: "template.openshift.io",
                Kind: "TemplateInstance",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueForbidden",
                        Message: "Forbidden: you do not have permission to set username",
                        Field: "spec.requester.username",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    TemplateInstance.template.openshift.io "test" is invalid: spec.requester.username: Forbidden: you do not have permission to set username
not to have occurred
```

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #16654

(builds on https://github.com/openshift/origin/pull/16979)

@gabemontero fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
So is a fair summary:
1) validation had to be augmented to deal with garbage collection mutation of the object based on the client it uses and by extension the serialization used
2) extended tests needed to be augmented to better ensure data was in fact deleted between one test run and the next

thanks

**Comment by jim-minter** [comment]
@gabemontero I think there were three issues causing flakes:
1) not waiting for group cache to sync after changing group memberships (affected two tests, causing permissions problems)
2a) not waiting for cascading deletion to complete before trying to reinstantiate an identical object (caused rare unexpected AlreadyExists errors)
2b) GC sometimes reordered json fields when removing the finaliser on the templateinstance, causing the update to be rejected by the api server, causing knock-on strangeness to happen on cascaded deletion (hence changes to validation logic)

2a 2b are already on the merge queue at #16979, this just builds upon that commit.

**Comment by gabemontero** [comment]
On Mon, Oct 23, 2017 at 4:28 PM, Jim Minter <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> I think there were three
> issues causing flakes:
>
>    1. not waiting for group cache to sync after changing group
>    memberships (affected two tests, causing permissions problems)
>    2a) not waiting for cascading deletion to complete before trying to
>    reinstantiate an identical object (caused rare unexpected AlreadyExists
>    errors)
>    2b) GC sometimes reordered json fields when removing the finaliser on
>    the templateinstance, causing the update to be rejected by the api server,
>    causing knock-on strangeness to happen on cascaded deletion (hence changes
>    to validation logic)
>
> 2a 2b are already on the merge queue at #16979
> <https://github.com/openshift/origin/pull/16979>, this just builds upon
> that commit.
>
gotcha ... ok that break down helps after revisiting the changes - thanks

**Pull request merged**
