### PR TITLE
Update minimum Docker version

### PR DESCRIPTION
**Pull request by rhcarvalho**
According to the official docs at:
https://docs.openshift.org/latest/install_config/install/prerequisites.html

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees PTAL

**Comment by rhcarvalho** [comment]
We might improve this PR if https://github.com/openshift/openshift-docs/pull/1450 merges. Instead of mentioning a specific version, we might just link to the docs.

**Comment by bparees** [comment]
you want to wait for that to merge?

**Comment by bparees** [comment]
(docs pull merged, might as well update this to use the anchor, though it won't work until the docs get rebuilt)

**Comment by rhcarvalho** [comment]
@bparees updated to include the link to the official docs. I think it is fine to be merged even before the docs are rebuilt, because it will still point at the right page (but will lead you to the top of the page).

**Comment by bparees** [comment]
sounds good, thanks!  [merge]

**Pull request merged**
