### PR TITLE
UPSTREAM: 40497: Make HandleError prevent hot-loops

### PR DESCRIPTION
**Pull request by pweil-**
Ref https://github.com/openshift/origin/issues/13025

Also includes UPSTREAM: 40553: Adjust global log limit to 1ms which builds on 40497 (they were merged separately into 1.5 due to refactoring in master)

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/11903.

[merge]

**Pull request merged**
