### PR TITLE
Bug 1388025 - Update NetworkDiagDefaultLogDir description

### PR DESCRIPTION
**Pull request by pravisankar**
Description string fixes.

Fixes Bug 1388025 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1388025)

### CODE REVIEW

**Comment by pravisankar** [comment]
@knobunc  very minor update in description, please merge

**Comment by pravisankar** [comment]
[merge]

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
[merge]

Flake https://github.com/openshift/origin/issues/11682

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/10663 [merge]

**Pull request merged**
