### PR TITLE
Fix detection of Python projects

### LINKED ISSUE #6562: oc new-app detection for Python
I initially flagged this issue under the ``sti-python`` as https://github.com/openshift/sti-python/issues/85 with the aim of getting comments from the maintainers of it, but no response as yet, so adding it here now.

The problem is that ``oc new-app`` when detecting if a Git repository under the Source strategy is a Python application, is not looking for the ``setup.py`` file, which would identify it as a Python application where package dependencies are listed in the ``setup.py`` file rather than a ``requirements.txt`` file.

For some reason it is looking for ``config.py`` when ``config.py`` has no significance that I know of in the Python world.

The ``assemble`` script in ``sti-python`` itself only treats ``requirements.txt`` and ``setup.py`` as significant and a trigger for package installation etc.

Perhaps someone looked at the Ruby detector and since it used ``config.ru`` wrongly though that Python should use ``config.py``. I can see no other reason why ``config.py`` would be used.

### PR DESCRIPTION
**Pull request by rhcarvalho**
Closes #6562.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by mfojtik** [comment]
LGTM

@sYnfo PTAL

**Comment by bparees** [comment]
lgtm.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by deads2k** [comment]
re[merge]

**Comment by deads2k** [comment]
[test]

**Comment by nak3** [comment]
Could you please update doc? @rhcarvalho @bparees @deads2k 

https://docs.openshift.org/latest/dev_guide/new_app.html#language-detection
https://docs.openshift.com/enterprise/3.1/dev_guide/new_app.html#language-detection

**side note:** As for `3.1.x`, `v3.1.0.4-5-gebe80f5` doesn't have this fix. I'm not exactly sure how openshift's doc is versioning this kind of fix, though I filed here https://bugzilla.redhat.com/show_bug.cgi?id=1272856

**Comment by rhcarvalho** [comment]
@nak3 thanks. I've opened a docs pull request with a fix as referenced above.

**Pull request merged**
