### PR TITLE
Support specifying StorageClass while creating volumes

### PR DESCRIPTION
**Pull request by gnufied**
Add support for specifying StorageClass when user is creating
volumes via oc set volume command

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by gnufied** [comment]
@childsb done. PTAL

**Comment by gnufied** [comment]
It seems to have flaked on https://github.com/openshift/origin/issues/11024

**Comment by rootfs** [comment]
claim-mode -> access-mode?

**Comment by eparis** [comment]
claim-mode is already in oc volume, changes would break existing setups. We could create a `--claim-access-mode` and work to deprecate `--claim-mode` if you wanted.  But not in this PR.

**Comment by eparis** [comment]
What does `oc set volume` do if I have a `--claim-name=` and `--claim-size=` but the claim (by name) exists already? Does it just ignore the size? Does it try to create a new PVC (and fail?)

How about the access mode? The SC?

**Comment by gnufied** [comment]
In first case - user's input is rejected outright and she gets following error:

```
─kube_scripts/xaos_openshift_master> oc set volume dc/mysql5 --add --claim-mode=rwo --claim-name='sandbox6-data' --mount-path='/sandbox2' --name='sandbox7-data' --type='persistentVolumeClaim' --claim-size="5G"
error: persistentvolumeclaims "sandbox6-data" already exists
```

How about Access mode? The values are not overwritten unless user explicitly uses `--overwrite`

**Comment by eparis** [comment]
[merge]

**Comment by eparis** [comment]
[merge] it was a flake

**Pull request merged**
