### PR TITLE
Allow cluster daemonsets to use maxSurge

### PR DESCRIPTION
**Pull request by Miciah**
Change the "[sig-arch] Managed cluster should only include cluster daemonsets that have maxUnavailable update of 10 or 33 percent" test to allow daemonsets to specify `maxUnavailable` 0 with `maxSurge` 10%.

The intention of this test is to verify that cluster components have parameters configured for rolling updates to ensure a reasonable balance between rapid rollout and minimum availability during upgrades.  At the time this test was written, the only way to accomplish that goal was to set an appropriate `maxUnavailable` value.  Since then, the `maxSurge` parameter has been added to the available parameters for daemonsets (see <https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/1591-daemonset-surge>).  Now, a daemonset can ensure rapid rollout and minimum availability using `maxSurge`.  However, when `maxSurge` is used, `maxUnavailable` must be zero. Thus this PR changes the test to allow `maxUnavailable` to be zero if `maxSurge` is set to 10%.

* `test/extended/operators/daemon_set.go`: Don't mark a daemonset as invalid if it has maxSurge set to 10%.  Include the `maxSurge` value in the violation message when neither `maxUnavailable` nor `maxSurge` is set appropriately.
* `cmd/openshift-tests/minimal.go`:
* `pkg/test/ginkgo/testNames.txt`:
* `test/extended/testdata/bindata.go`:
* `test/extended/util/annotate/generated/zz_generated.annotations.go`: Update test name.

### CODE REVIEW

**Comment by Miciah** [comment]
@mfojtik, could you approve this change?  This PR is related to https://github.com/openshift/cluster-dns-operator/pull/358, which is intended to fix a 4.13 release blocker.  I'll want to backport both this origin PR and the cluster-dns-operator PR to their respective release-4.13 branches.

**Comment by Miciah** [comment]
@bparees, could you approve this change?  (Maybe I should just avoid changing the test name so I wouldn't need to ping approvers from multiple `OWNERS` files...)

**Comment by Miciah** [comment]
https://github.com/openshift/origin/compare/35bf4473e6cae0f8ef4748fe6216967411c93462..1219706cf49d08e6bf707e2274ef144b9b4d92b8 updates the test name per comments on Slack.

**Comment by gcs278** [comment]
Agree with the update.
/lgtm

**Comment by Miciah** [comment]
https://github.com/openshift/origin/compare/1219706cf49d08e6bf707e2274ef144b9b4d92b8..b28b8148fb6d7ca23b2b6ad106303794587d873b fixes a gofmt issue.

**Comment by Miciah** [comment]
[e2e-gcp-ovn-rt-upgrade failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27819/pull-ci-openshift-origin-master-e2e-gcp-ovn-rt-upgrade/1643091950049431552) because one of the kube-apiserver pods didn't come up.  As far as I can tell, the installer pod for master-1 didn't get created; [`event-filter.html`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/27819/pull-ci-openshift-origin-master-e2e-gcp-ovn-rt-upgrade/1643091950049431552/artifacts/e2e-gcp-ovn-rt-upgrade/gather-must-gather/artifacts/event-filter.html) shows no matches for component "kube-apiserver-operator-installer-controller" and message "master-1", and `host_service_logs/masters/kubelet_service.log` from [`must-gather.tar`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/27819/pull-ci-openshift-origin-master-e2e-gcp-ovn-rt-upgrade/1643091950049431552/artifacts/e2e-gcp-ovn-rt-upgrade/gather-must-gather/artifacts/must-gather.tar) does not have any matches for the regexp `openshift-kube-apiserver/installer-.*master-1`, so I guess cluster-kube-apiserver-operator never created the pod for master-1.  I'm not sure how to diagnose this further, so let's just rerun the test for now to see whether the issue reoccurs.  
/test e2e-gcp-ovn-rt-upgrade

**Comment by Miciah** [comment]
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27819/pull-ci-openshift-origin-master-e2e-aws-ovn-serial/1643274924913070080) because `[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured` failed.  [Search.ci shows similar failures](https://search.ci.openshift.org/?search=promQL+query+returned+unexpected+results%3A%5C%5CnALERTS&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) for other PRs and repositories.  I filed https://issues.redhat.com/browse/OCPBUGS-11402 with more details.
/test e2e-aws-ovn-serial

**Pull request merged**
