### PR TITLE
dind-ovn: use golang binaries instead of python ones

### PR DESCRIPTION
**Pull request by rajatchopra**
Dependent on upstream PR: https://github.com/openvswitch/ovn-kubernetes/pull/173

Signed-off-by: Rajat Chopra <rchopra@redhat.com>

@dcbw PTAL. Thanks.

### CODE REVIEW

**Comment by imcsk8** [comment]
LGTM

**Comment by rajatchopra** [comment]
@dcbw Added commit to adapt for changes made in https://github.com/openvswitch/ovn-kubernetes/pull/192
Please review again. Thanks.

**Pull request merged**
