### PR TITLE
Bug 1206419 - Handle empty namespace slice plus message fix

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Comment by soltysh** [comment]
[merge] again :disappointed_relieved:

**Comment by kargakis** [comment]
Travis is green at last. Can someone merge this before another goverment ddoses GitHub? :sweat_smile:

**Comment by soltysh** [comment]
[merge] :wink:

**Comment by kargakis** [comment]
:clap: :clap: :clap:

**Comment by soltysh** [comment]
I need to use my lucky hand with my own PR.

**Pull request merged**
