### PR TITLE
add openshift ex config patch to modify master-config.yaml

### PR DESCRIPTION
**Pull request by deads2k**
Introduces `openshift ex config patch path/to/master-config.yaml --patch '{}'` to allow master config mutation without using `sed`.  The scheme changes and patch flag additions may take us a little while to work out, this gives us a removable command to play with and see if it suits us.

@fabianofranz 
@soltysh @stevekuznetsov

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by soltysh** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by fabianofranz** [comment]
+1 LGTM

**Comment by deads2k** [comment]
yum re[merge]

**Comment by smarterclayton** [comment]
When would I use this over improvements to the other patch?

**Comment by deads2k** [comment]
> When would I use this over improvements to the other patch?

Two problems:
1. Our config objects exist in a different scheme and a lot of code, include patch, rely on a single scheme.  It's not insurmountable, but not something I want to rush into either.  I'd want to create a new API group and find a way to decode using a "trust me" serialized version.

2. The upstream patch changes looks like they're going to take a little while.  I think they'll come around, but this is blocking our ability to fully test conformance on different configs now (audit  in particular).

I figured on having an experimental command until we get everything sorted out in a few weeks and pick up changes in another rebase.

**Comment by stevekuznetsov** [comment]
>  but this is blocking our ability to fully test conformance

To be fair, this is the Golang program that we can write to alleviate our block:

```go
package main

import (
	"io/ioutil"
	"os"

	"github.com/openshift/origin/pkg/cmd/server/api/v1"
	"gopkg.in/yaml.v2"
)

func main() {
	var config v1.MasterConfig

	rawInput, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}

	err = yaml.Unmarshal(rawInput, &config)
	if err != nil {
		panic(err)
	}

	config.AuditConfig.Enabled = true

	rawOutput, err := yaml.Marshal(config)
	if err != nil {
		panic(err)
	}

	err = ioutil.WriteFile(os.Args[1]+".updated", rawOutput, os.O_WRONLY|O_CREATE)
	if err != nil {
		panic(err)
	}
}
```

**Comment by mfojtik** [comment]
yey! 👍

**Comment by smarterclayton** [comment]
That's fine - I would expect though that the upstream patch command
replace this command.

**Comment by deads2k** [comment]
> That's fine - I would expect though that the upstream patch command
> replace this command.

Agreed.  yum re[merge]

**Pull request merged**
