### PR TITLE
Support multiple HTML5 consoles and embed the openshift-jvm console

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@liggitt @gashcrumb @jstrachan WIP, the golang changes are here, will work on the Gruntfile changes next

**Comment by jwforres** [comment]
@liggitt ready to review, the java console is embedded and launchable

**Comment by jwforres** [comment]
@gashcrumb FYI I have this pulling in v1.0.6-build at the moment, any time you guys wants to bump the version you will modify the version in hack/install-assets.sh and then

```
rm -rf assets/openshift-jvm
hack/install-assets.sh
hack/build-assets.sh
```

and then open a PR with the updated hack/install-assets.sh and the updated bindata.go

For this PR let me know when you are ready for the initial drop into openshift and then we can bump the version and merge this (once jordan reviews it)

**Comment by gashcrumb** [comment]
@jwforres awesome.  I did put out a 1.0.7 that makes the right fonts show up (at least this was an issue I was seeing locally) and also tidies up the directory structure slightly as a result, you might want that.

I'm sure there will be CSS work necessary as well, but might as well get it working and get an initial merge first :-)

**Comment by jwforres** [comment]
updated to use 1.0.7 and squashed commits

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
unrelated failure [merge]

**Comment by jwforres** [comment]
re[merge]

**Pull request merged**
