### PR TITLE
Reconcile non-resource-urls

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1372579

### CODE REVIEW

**Comment by liggitt** [comment]
[test]
@deads2k PTAL

**Comment by liggitt** [comment]
flaked on #9624, re[test]

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
"An interaction with AWS failed due to our API request limit being saturated."
😞 
[merge]

**Pull request merged**
