### PR TITLE
Add a new simple start-local server option for quick iteration

### PR DESCRIPTION
**Pull request by smarterclayton**
Replaces previous local dev use of `openshift start`.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@bparees @deads2k this is a shim to unblock Ben's team for now.  Before we break `openshift start master` we need to spend 15 minutes having an equiv here.

**Comment by bparees** [comment]
@openshift/sig-developer-experience ptal/try out the next time you need to run a local cluster.

**Comment by mrunalp** [comment]
Any chance we can add cri-o support here as well? :) I can follow up after this is merged.

**Comment by bparees** [comment]
/lgtm

thank you @smarterclayton

**Comment by bparees** [comment]
this PR in bunny form: https://www.youtube.com/watch?v=iflAxNx8twY

**Pull request merged**
