### PR TITLE
pruned govet whitelist

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Got rid of whitelist entries that were not hiding any shadowed variables. 

@deads2k  PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@deads2k all green

**Comment by deads2k** [comment]
govet passed [merge]

**Comment by stevekuznetsov** [comment]
@deads2k version drift between Travis and Jenkins `go vet` ... made one update to satisfy version of `go vet` on Jenkins. Will bump Jenkins version as well: https://github.com/openshift/vagrant-openshift/pull/401

**Comment by stevekuznetsov** [comment]
[test] me

**Comment by deads2k** [comment]
more shadowing resolved.  re[merge]

**Comment by rhcarvalho** [comment]
Go vet was not run for go1.6

```
hack/verify-govet.sh
Unknown go version 'go', skipping go vet.
```

https://travis-ci.org/openshift/origin/jobs/111497786#L231

I'm fixing it in https://github.com/openshift/origin/pull/8889, but there are several shadow errors that look like legit uses of `if err := ...; err != nil`.

I came here trying to understand why we enable shadow given it is not false-positive free:
https://groups.google.com/d/msg/golang-nuts/fbxCYRPKTuM/6pKJ8qPdw6AJ

> In any case the vet -shadow feature is disabled for a reason. It does not give the level of confidence the other analyses do.
> (Rob Pike)

**Pull request merged**
