### PR TITLE
[3.9] up: default openshift imagepolicy admission

### PR DESCRIPTION
**Pull request by mfojtik**
pick https://github.com/openshift/origin/pull/19908 for origin 3.9 (to run tests), will pick this for ose.

/cc @soltysh 
/cc @thoraxe 
/cc @smarterclayton

### CODE REVIEW

**Comment by jpeeler** [comment]
This is hitting #19887.

**Comment by slaskawi** [comment]
@mfojtik Any update on this?

**Comment by mfojtik** [comment]
@openshift/sig-networking seems like the haproxy failure is permanent?

**Comment by mfojtik** [comment]
@slaskawi this fix was merged into master so it will be available in 3.10 release (or HEAD). I don't think we rebuild the 3.9 binaries and publish them, so you can pull this patch locally and just `make build WHAT=cmd/oc` to get this fix.

**Comment by slaskawi** [comment]
@mfojtik hmmm and do you publish the nightly binaries somewhere? We are using `oc cluster up` for our internal CI infrastructure, so building it up seems a bit... problematic ;)

**Comment by slaskawi** [comment]
Found it (from Clayton's email). Thanks for cherry-picking this!

**Pull request merged**
