### PR TITLE
[wip] built trap framework for bash

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Rules:
 1. no trap shall ever `set -e`
 2. no trap shall ever `exit`
 3. traps may expect return code in `$RETURN`
 4. traps should `return` with `$RETURN`
 4. traps that fail can scream all they want. but nobody's listening
 5. trap handlers must always be single function calls
 6. users can expect subsequent `os::util::trap::add` calls to *append* their traps to the end of the list of handlers

@Miciah @eparis  PTAL

@deads2k FYI

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]me

**Comment by stevekuznetsov** [comment]
`os::log::error_exit` and the like are going to have to be re-written to some extent for this. The functions as they stand make a lot of assumptions about how they're called that just aren't going to be true anymore. This stack of cards keeps tumbling down...

**Comment by stevekuznetsov** [comment]
In order to have a functioning stack trace, we need to enable `set -o errtrace`, which will propagate the handler trapped on `ERR` into functions, expansions, and subshells. This is absolutely necessary in order to be able to chase the call stack from the spot of the error.

This also means that as the function calls pop back up the stack, every time one fails another `ERR` is signalled and our wonderful stack trace handler (from `os::log::errexit`) is run once more.

It is therefore necessary for the `ERR` handlers to exit after all of them have run once, so that they aren't run for every context that is currently in flight. This means that *some error handler must use `exit`*.

We need to ensure that every handler is able to handle a signal, so we cannot let any handler use `exit` unless we can guarantee that they are the last handler in the chain.

We can make that guarantee either by:
*a)* enforcing through review that `os::log::install_errexit` is called after all other handlers are installed
*b)* some medium-weight machinery inside of `os::util::trap`. 

I'm going to try option *b)* because option *a)* is going to cause a nearly untrace-able bug for someone when the chain of handlers exits early, and I don't want to be causing anyone that pain.

**Comment by deads2k** [comment]
@eparis @Miciah We got burned yesterday by a trap handler that was returning success instead of failure.  It caused failing tests to show as "pass" which could have led to mayhem if we hadn't caught it.

Can this change guarantee that won't happen again?  If so, assuming most of the work is already done, I'm inclined to do this an have some sort of detection to a less good algorithm for OS X users and use this in our merge queue.

@liggitt If we make a parallel path, can you check OS X?
@pweil- fyi

**Comment by stevekuznetsov** [comment]
The approach that @Miciah and I came up with previously that was not compatible with OSX had the following premises:

 * Hold a list of all handlers for every signal. For every signal, trap a handler that knows how to access that list *at runtime* and determine what to do. 
 * Run each handler in that list in a subshell in order to sandbox it. It seems as though children of a process can kill each other, so this was OK for all of our process cleanup. 
 * We furthermore need to have another associative array of "privileged handlers." These are necessary in order to have support for a stack trace. As noted above, the ERR signal handler must be propagated into every context, so if that handler does not `exit`, it will be called recursively over and over again up the entire stack. Therefore, while we're ensuring that all other handlers that are registered are run in a sandbox and *cannot* use `exit` to kill the shell, we need to ensure that this privileged handler *can* do that.
 * We need to ensure that no handler is able to corrupt the original exit signal of the script, which we can only ensure in the non-associative proposal by ensuring every handler `returns` the correct value, but we get this for free in the associative case as we sandbox the handlers and can `return` ourselves after they're done.
 * We need to ensure locality of the return code variable. For instance, if a handler is run and has an error, it will issue the `ERR` signal handler, and will corrupt the "real" exit code for following handler chains. We can achieve this in the non-associative proposal by declaring a read-only variable at the start of the handler chain, and running the entire handler chain inside of a subshell so the variable's scoped correctly. This causes issues because we need to enable the privileged handler to kill the shell, which it cannot do in a subshell. We can also achieve this in the associative proposal as we can declare the readonly variable local to the one function that is trapped on the signal, and we get the locality of the variable for free.

I think there are many strong reasons to use the associative approach. The obvious downside is that it's not OSX compatible. It's not clear to me how to achieve a "separate but equal" algorithm for OSX and I don't really think that's the correct way forward. We *could* use Bash trickery to emulate associative arrays in version 3.2, but I'm not happy about that approach - it's fairly fragile and impossible to reason about without background knowledge.

We could also just ask @liggitt *et al* to upgrade their Bash version and fail the scripts if someone tries to install handlers with an incompatible version of Bash. We already do this with Go, and the releases of Bash are backwards-compatible, so I don't really see why this would be a terrible idea.

**Comment by stevekuznetsov** [comment]
@smarterclayton @liggitt suggest a different approach, similar to the best approach detailed above.

Have one master function for each "important" signal (currently `ERR` and `EXIT`) that consumes many envars, each of which turn on a trap feature. We trap this function and use helpers to flip the envars. At runtime, trap determines what to run. We can sandbox, etc, just the same.

**Comment by stevekuznetsov** [comment]
While I'm rebuilding this, I just want to share the following bug I found caused by our lovely language:
```sh
$ set +o | grep errexit
set -o errexit

$ options="$( set +o | grep errexit )"
$ echo "${options}"
set +o errexit

$ ( set +o | grep errexit )
set -o errexit

$ eval 'set +o | grep errexit'
set -o errexit

$ bash -c 'set +o | grep errexit'
set +o errexit

$ options=`set +o | grep errexit`
$ echo "${options}"
set +o errexit
```

Apparently shell options only sometimes trickle down to subshells, etc.

**Comment by stevekuznetsov** [comment]
@Miciah @deads2k @eparis PTAL current commits. After review I'll squash them and rebase to bring in `hack/lib/util/environment.sh`.

Still [WIP] on refactoring `cleanup_openshift`, timing, and any other misc I find into the trap framework.

**Comment by Miciah** [comment]
In case it's any comfort, it looks like the behaviour you describe is as documented, if you do not have POSIX mode enabled (`set -o posix`).  Bash executes commands in a "command execution environment" that includes the set of options that are set.  `eval` is executed in the execution environment where you run the command.  `bash -c` starts a new shell and thus a new execution environment, which does not inherit options.  Command substitution and parentheses run the given command in the a new shell execution environment that inherits options (among other things).  `errexit` is generally inherited with other options:

"Command substitution, commands grouped with parentheses, and asynchronous commands are invoked in a subshell environment that is a duplicate of the shell environment [...]."

However, `errexit` is not inherited for command substitution in POSIX mode:

"Subshells spawned to execute command substitutions inherit the value of the `-e` option from the parent shell. When not in POSIX mode, Bash clears the `-e` option in such subshells."

https://www.gnu.org/software/bash/manual/html_node/Command-Execution-Environment.html

**Comment by stevekuznetsov** [comment]
migrated to version 3 of this pull, closing

**Pull request closed without merging**
