### PR TITLE
Switch back to kapi instead of v1 for RCs in deployment describer

### PR DESCRIPTION
**Pull request by ncdc**
Part of #13732 

@sttts @liggitt @deads2k @mfojtik @soltysh @kargakis @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
lgtm [merge]

**Comment by mfojtik** [comment]
👍

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/13942 [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/14020 [merge]

**Pull request merged**
