### PR TITLE
Bug 1206109 - Default empty tag slice to 'latest'

### PR DESCRIPTION
**Pull request by kargakis**
https://bugzilla.redhat.com/show_bug.cgi?id=1206109

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis the proper format is to make PR title 'Bug XYZ - Description' (or commit message). Without description one must go to BZ ;-) people are lazy nowadays ;-)

**Comment by mfojtik** [comment]
LGTM (just change the commit message)

**Comment by kargakis** [comment]
> @kargakis the proper format is to make PR title 'Bug XYZ - Description' (or commit message). Without description one must go to BZ ;-) people are lazy nowadays ;-)

:ok:

**Comment by mfojtik** [comment]
[merge] thanks!

**Pull request merged**
