### PR TITLE
bump(k8s.io/kubernetes): d2e5420de791a3a5234eb1c3d84921d68ae2b6d6

### PR DESCRIPTION
**Pull request by deads2k**
Matches https://github.com/openshift/kubernetes/commits/openshift-3.7

### CODE REVIEW

**Comment by deads2k** [comment]
merging as marker.

**Comment by deads2k** [comment]
@mfojtik alright, the upstream fork is now up to date with the openshift code so you can generate the new clients there.

**Comment by deads2k** [comment]
@sttts side comment.  Can you see a reasonable way to regenerated the kube clients in openshift without dropping back to the fork?  That would be nice.

**Comment by mfojtik** [comment]
@deads2k does this accommodate all moves i did in https://github.com/openshift/origin/pull/15427 ?

**Comment by deads2k** [comment]
> @deads2k does this accommodate all moves i did in #15427 ?

No.  It gives you a base to create your fork from though in openshift/kubernetes

**Comment by sttts** [comment]
> Can you see a reasonable way to regenerated the kube clients in openshift without dropping back to the fork? That would be nice.

I don't see any bigger problem with that, at worst a a two digit number of bash code.

**Pull request merged**
