### PR TITLE
The first letter should be small in htpasswd.go errors.New

### PR DESCRIPTION
**Pull request by YuPengZTE**
The first letter is capitalized in errors.New

### CODE REVIEW

**Comment by liggitt** [comment]
actually, the others should be lowercased

**Comment by YuPengZTE** [comment]
Thanks @liggitt, then I change  the capital letters to small letters.

**Comment by liggitt** [comment]
Lgtm post 1.3

**Comment by liggitt** [comment]
[merge]

**Comment by danmcp** [comment]
@YuPengZTE I am closing this PR since the source branch no longer exists.

**Pull request closed without merging**
