### PR TITLE
Add error messages to test framework when changing user

### PR DESCRIPTION
**Pull request by tnozicka**
Helps uncover https://github.com/openshift/origin/issues/17805 and those error mesages should have been there anyways.

### CODE REVIEW

**Comment by tnozicka** [comment]
flake https://github.com/openshift/origin/issues/17829
/retest

**Comment by tnozicka** [comment]
flake https://github.com/openshift/origin/issues/17829 again
/retest

**Comment by deads2k** [comment]
@tnozicka This ends up hiding the original error types.  That causes some calling code (sometimes multiple levels up) to fail.  See comment on error handling for `RequestToken` call sites.

**Comment by mfojtik** [comment]
@tnozicka agree with David, can we throw there some V(5) glog.Infos instead?

**Comment by tnozicka** [comment]
I'll check it but I don't think that any non direct caller should check those error types for exactly this reason, or am I wrong?

**Comment by tnozicka** [comment]
@deads2k would you mind sharing where that is used? I've found possibly only https://github.com/openshift/origin/blob/1eed81f10256f22d4f3426722b44ae47eaf3fba7/test/integration/oauth_basicauth_test.go#L357-L369 and integration passed.

**Comment by deads2k** [comment]
> @deads2k would you mind sharing where that is used? I've found possibly only

This is usually an exercise for the reader.  First one is free, but the second counts as a favor. :)

 1. https://github.com/openshift/origin/blob/master/pkg/cmd/util/tokencmd/request_token.go#L151
 2. https://github.com/openshift/origin/blob/master/pkg/cmd/util/tokencmd/request_token.go#L73
 3. https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/loginoptions.go#L227
 4. https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/loginoptions.go#L75
 5. https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/login.go#L187
 6. https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/login.go#L70
 7. checked here https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/login.go#L72

**Comment by tnozicka** [comment]
thanks @deads2k, I didn't want to abuse your time but I though you already knew the place (based on your previous comment) and the path to it from the low level seemed like backtracing all the calls 7 level up with exponential growth.

I went with `github.com/pkg/errors` so the underlying type can be unwrapped.

**Comment by deads2k** [comment]
The problem with doing it this way is that it's no longer the standard way of dealing with a golang error and our project standard isn't to attempt unwrapping.  Having done this in java, you either have to convert the entire code base or you don't do it at all.  Mix and match fails unexpectedly in frustrating spots.

**Comment by tnozicka** [comment]
I would look at it from different point. The way it was done was non-standard - checking error type is "allowed" only for the direct caller and this rouge code did it several layers up. The standard Go way is to wrap an error into a string (erasing the type), adding context. This wrapping make the error look the same way as it was wrapped normally into a string for any caller not aware of the wrapping - fulfilling the standard we have. In addition it allows unwrapping to fix the places where we were breaking the standard way by checking error type several layers up.

Also the package is already vendored.

**Pull request closed without merging**
