### PR TITLE
UPSTREAM: 29171: Fix order of determineContainerIP args

### PR DESCRIPTION
**Pull request by pmorie**
Upstream patch of kubernetes/kubernetes#29171

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@liggitt light is green, trap is clean

**Comment by liggitt** [comment]
do we know of anything this is currently causing problems with, or can we wait until we pick it up from upstream?

**Comment by pmorie** [comment]
@liggitt it prevents pod IP via downward API from working when you're using a network plugin.

**Comment by liggitt** [comment]
ok, [merge]

**Pull request merged**
