### PR TITLE
Use SkyDNS prometheus metrics

### LINKED ISSUE #3589: [post-rebase-work] disable skydns metrics
We should remove our own metrics now that prometheus is the default.  See  https://github.com/deads2k/origin/commit/84d4f1f855780f8444bfdbdaade83cbe2244cf0a#commitcomment-11981756

@smarterclayton  is probably the most familiar with what needs doing.

### PR DESCRIPTION
**Pull request by smarterclayton**
Requires an upstream patch to SkyDNS

Fixes #3589

@deads2k

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by deads2k** [comment]
Fix your upstream commit and then lgtm.

**Comment by smarterclayton** [comment]
fix it how

**Comment by smarterclayton** [comment]
Ah, fixed.  Thanks

**Comment by deads2k** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
