### PR TITLE
[WIP] add service catalog proxy to secure TSB

### PR DESCRIPTION
**Pull request by deads2k**
creates a proxy that terminates basic auth and attaches a token instead.

Needs tests.

@bparees @pmorie @pweil- @liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
Uh... this seems not a good idea

**Comment by smarterclayton** [comment]
I'm a -1 just on the overhead this is creating in our process, plus the touch points in the code, plus I have no intention of supporting this.  Am I correct in understanding the core issue is basic credentials -> service account token?  Why isn't this a simple filter over 3 endpoints in the master that takes Basic user:pass -> service account bearer?  You only have to protect the SC endpoints, right?

**Comment by deads2k** [comment]
> I'm a -1 just on the overhead this is creating in our process, plus the touch points in the code

It keeps the openshift API server clean and the permissions correct.  All other "solutions" I've heard muddy code we actually need to keep.  This is just something we delete in one release without any further touch points.

**Comment by smarterclayton** [comment]
TSB isn't an unrelated thing.  It's something we support.  

I do agree that TSB should be minimally coupled to the rest of the code - I guess I don't know what the distinction is between TSB the http.Handler (initialized with an Authenticator and Authorizer, that also happens to do translation of basic auth to service account) to Registry the component beyond the particular deployment style.  The registry only supports service account tunneled via BASIC, and SB only supports basic.

**Comment by liggitt** [comment]
If TSB were its own component (which it is logically and behaviorally),  it could do that basic to bearer plumbing just like the registry does,  and that would be fine. 

I agree that we should not introduce that plumbing to the API server handler to suit a component that wants to take advantage of the API server's deployment convenience but does not want to conform to the API server's conventions

**Comment by bparees** [comment]
>  does not want to conform to the API server's conventions

it wants to, desperately, believe me.  unfortunately its callers/consumers are not on that same page just yet...

**Comment by liggitt** [comment]
>> does not want to conform to the API server's conventions
>
> it wants to, desperately, believe me. unfortunately its callers/consumers are not on that same page just yet...

sorry, didn't mean to anthropomorphize the handlers, I know they hate that

**Comment by smarterclayton** [comment]
I'm somewhat skeptical of the argument that everything on the API server
process must follow a set of rules, and that this particular bit (a filter
that intercepts /broker/X and transcribes basic to bearer) is the straw
that breaks the camels back.

We don't want to ship anonymous endpoints that grant root access.  We don't
want to create net new deployment artifacts that complicate everyone else's
life outside of the apiserver folks.  We don't want to ship with no
concrete way to exercise and validate the service catalog experience in
real environments.

A filter on a few paths that is something we can remove when the TSB
conforms is the only thing I've seen so far that at least moves in the
right direction.


On Jun 13, 2017, at 6:19 PM, Ben Parees <notifications@github.com> wrote:

does not want to conform to the API server's conventions

it wants to, desperately, believe me. unfortunately its callers/consumers
are not on that same page just yet...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14623#issuecomment-308265330>,
or mute
the thread

**Comment by smarterclayton** [comment]
I do want to note that I'm most interested in outcomes that lead to
everyone getting most of what they want.  I'm less interested in
outcomes where some people go home unhappy.

**Comment by smarterclayton** [comment]
* unhappier

**Comment by bparees** [comment]
>  I'm less interested in outcomes where some people go home unhappy.

I guess i need to rewrite my compass goals...

**Comment by smarterclayton** [comment]
Aim high so the shotgun hits the guy on the ledge behind you

**Comment by jim-minter** [comment]
I'm wondering if there is anything I could/should add to the template service broker which can help, and in what timescale this would make sense?
e.g. could the tsb be hauled forward in the api server handler chain using something like WithPatternsHandler so that it's above the existing authz/n, then it should itself do a user/password verification (somehow) and sar the resulting user in some way to check they have access?

I'd need a bit of hand fleshing out the details but am happy to implement if it helps?

**Comment by deads2k** [comment]
> I'd need a bit of hand fleshing out the details but am happy to implement if it helps?

I'd rather see effort put into actually structuring this so that we end up with a reasonable end product.  It's a logically separate component, let's separate it.  We're already depending on microservices to run the service catalog, let's have this run as a proper microservice with its own API server.  There is no structural reason for it to exist in the main API server process at all.  It was only put there because the installer at the time didn't deal with microservices.  Service catalog made it take them into consideration, let's use that ability to architect our product in a maintainable way.

**Comment by jim-minter** [comment]
I don't disagree - I was wondering if there was a shorter term step that could/should get auth on the thing before taking the step to break it out into a separate api server.

**Comment by bparees** [comment]
@deads2k @liggitt @smarterclayton what's the next step here?

**Pull request closed without merging**
