### PR TITLE
have TemplateInstance objects appear in swagger spec

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@bparees not sure if/when something like this ought to be merged? I think doing so would mean we could pull the updates to the API docs which would help support my trello card.

**Comment by bparees** [comment]
seems like a question for @openshift/api-review 

are all the apis that are being pulled in by this appropriately commented as "experimental"?

**Comment by jim-minter** [comment]
hmm, it doesn't entirely help anyway as the API docs only include the legacy endpoints, not API groups, and TemplateInstances are non-legacy...

**Comment by smarterclayton** [comment]
They should be showing up in openapi

On Jun 28, 2017, at 12:42 PM, Jim Minter <notifications@github.com> wrote:

hmm, it doesn't entirely help anyway as the API docs only include the
legacy endpoints, not API groups, and TemplateInstances are non-legacy...

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14942#issuecomment-311717923>,
or mute
the thread

**Comment by bparees** [comment]
lgtm
[merge][severity:lowrisk]

**Pull request merged**
