### PR TITLE
pull in recent jenkins template, imagestream updates

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

this is using the new `make update-examples` stuff after merging some changes in openshift/library which merged changes from openshift/jenkins

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/hold
needs to pass image_eco/builds.

**Comment by gabemontero** [comment]
just curious, won't a failure in builds or image_eco block the merge?  or are those not blocking jobs?

**Comment by bparees** [comment]
> just curious, won't a failure in builds or image_eco block the merge? or are those not blocking jobs?

they are non-blocking jobs.

**Comment by gabemontero** [comment]
@bparees - the image_eco system failure was insightful wrt our constrained resources issue

the deployment got far enough along that it passed the readiness check, however jenkins start was not fully complete before the timeout as indicated by the end of the jenkins logs ... the updated datat / update center stuff was still in progress

I think the template changes themselves are verified in that they did not break deployment startup.

And once these changes merge, we can then start instantiating our ext tests with the update center stuff turned off, and these constrained resource situations should be better.

**Comment by gabemontero** [comment]
extended_builds had only 1 instance of the "not progressing" bail out noted ... but no major breaks cause of a malformed template or image stream

the latest image_eco had 1 scl failure and 3 of our jenkins too slow, etc. messages ... similar to the last run, though there was only 1 instance of the too slow in the last run

**Comment by gabemontero** [comment]
all the tests passed this time @bparees 

/unhold

**Comment by gabemontero** [comment]
not sure if you need to unhold as a "merger" @bparees  ... i've removed the label manually

**Comment by bparees** [comment]
@gabemontero the command is /hold cancel.

**Comment by gabemontero** [comment]
:-) thank you

**Pull request merged**
