### PR TITLE
Fix output of git basic credentials in builder

### PR DESCRIPTION
**Pull request by csrwng**
Fixes BZ 1267583

### CODE REVIEW

**Comment by csrwng** [comment]
@jhadvig @bparees ptal

**Comment by liggitt** [comment]
@stevekuznetsov the sooner we can re-enable go vet, the better

**Comment by csrwng** [comment]
@liggitt go vet didn't catch this one because I suppose having a variable as your format is still valid

**Comment by stevekuznetsov** [comment]
@liggitt hoping for this week or weekend now that some of LDAP is in

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by csrwng** [comment]
rebased [merge]

**Comment by jhadvig** [comment]
:+1:

**Pull request merged**
