### PR TITLE
Generate 1.5 release client, remove 1.4 and 1.3 clients

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@soltysh

**Comment by soltysh** [comment]
You need to fix the integration tests, specifically `test/integration/clientset_test.go` which uses 1.3 clientsets. Otherwise LGTM.

**Comment by mfojtik** [comment]
LGTM as well. 

At some point we need to talk how to extract that clientset into a separate Go package.

**Comment by soltysh** [comment]
> At some point we need to talk how to extract that clientset into a separate Go package.

I'm inclined to say, let's wait for what upstream figures out and just apply that. Instead of re-inventing the wheel.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
