### PR TITLE
OCPBUGS-34448: Skip monitortests collection for openshift-oauth-apiserver on hypershift

### PR DESCRIPTION
**Pull request by cblecker**
As hypershift clusters don't have the `openshift-oauth-apiserver`, skip this step if the test is running against a hypershift cluster.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by dgoodwin** [comment]
If I'm reading this right, the original code appears to do what you want, if that oauth namespace is there we want to return a not supported reason which is meant to be a way for the framework to simply disable a test because it isn't supported in that configuration. Hypershift was rightly already triggering this as far as  I can see. I think all that's going on here is we're logging something at error level when it should be at info:

logrus.WithError(nsErr).Errorf("  Finished CollectData for %s with not-supported error", testName)

Which is certainly confusing, but I think the original code already has the functionality you want, this is just a logging flub. Let me know if I've got anything wrong here and this is actually causing severe problems.

/lgtm cancel

**Comment by stbenjam** [comment]
The test is already skipped, the error should just be softened to a warning.

Alternative https://github.com/openshift/origin/pull/28865


/close

**Pull request closed without merging**
