### PR TITLE
Launch integration test with our etcd

### PR DESCRIPTION
**Pull request by deads2k**
Uses our etcd to launch integration tests and adds an etcd dump if the test fails.

@stevekuznetsov second commit.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Bash LGTM

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/6077

**Comment by deads2k** [comment]
first commit is https://github.com/openshift/origin/pull/6646, so this is good.

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
re[test]

**Pull request merged**
