### PR TITLE
images with interfaces

### PR DESCRIPTION
**Pull request by deads2k**
One possible way to handle "I need helpers for two different versions".  It doesn't win for beauty, but this is what the "define your own interface" approach looks like.

@smarterclayton @liggitt ptal
@legionus as promised

### CODE REVIEW

**Comment by legionus** [comment]
@deads2k can you port the `dockerregistry` as well ?

**Comment by deads2k** [comment]
> @deads2k can you port the dockerregistry as well ?

I haven't dug through usage yet.  This looked ugly enough that I figured we should all opt-in.

**Comment by smarterclayton** [comment]
Ugh.  I haven't thought about the alternatives, but it's definitely ugh.

**Comment by smarterclayton** [comment]
It's maybe not so ugh that I wouldn't say it is at least usable.  But...

**Comment by legionus** [comment]
I know I ask noob question, but still: why can't we move `github.com/openshift/origin/pkg/image/apis/image/internal/...` and type `DockerImageReference` with methods to separate repository and use it in the `origin` and `dockerregistry` ?

In our API `DockerImageReference` is represented by the string and there will not be new external dependencies. The new repository will not have dependencies on `docker/distribution` or on other external repository. So we can put this repository in the vendor directory and do not get any cyclic dependencies.

**Comment by deads2k** [comment]
> I know I ask noob question, but still: why can't we move github.com/openshift/origin/pkg/image/apis/image/internal/... and type DockerImageReference with methods to separate repository and use it in the origin and dockerregistry ?

I just hadn't done it yet.  I'm still considering the repercussions of doing this and hoping someone comes up with a better idea.  @liggitt has failed me in that regard :) .

The question that naturally follows is: where should such helpers live.  We're going to have many of them and ideally the dockerregistry does not rely on openshift/origin at all.  However, a separate repo for each little bit we have ends up looking a lot like pre-osgi jars.  I lived through that.  It wasn't fun.

**Comment by liggitt** [comment]
> can't we move github.com/openshift/origin/pkg/image/apis/image/internal/...

To be clear, we would just move the helpers to be referenced by the dockerregistry, likely not the internal types

**Comment by legionus** [comment]
> ideally the dockerregistry does not rely on openshift/origin at all.

https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/util.go#L30
https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/util.go#L170-L184

**Comment by sttts** [comment]
This looks ok'ish for read-only helpers and simple mappings from versioned types to `...Reference`. I am not convinced at all that this will scale in any way to generic algorithms which modify objects. We will end up with something like internal types, but without the consistency enforcing machinery around (roundtripping, conversion-gen, etc.). 

The whole dogma of "do not publish internal types" is questionable IMO. I still see the internal types as a library to implement generic algorithms on API types. I would love to see `staging/src/k8s.io/api-internal` with dependencies to anything but k8s.io/api and apimachinery cut-off. Everything non-trivial will eventually lead to internal types anyway, in one way or the other.

**Comment by deads2k** [comment]
> https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/util.go#L30
> https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/util.go#L170-L184

Is that just one example or is that the only remaining linkage?

**Comment by deads2k** [comment]
> Is that just one example or is that the only remaining linkage?

If that is the only remaining linkage, we can assess whether or not we want to copy it.  I haven't looked to see how big it is, but at a certain point I'd make the tradeoff to copy and split rather than remain coupled.

**Pull request closed without merging**
