### PR TITLE
UPSTREAM: 59170: Fix kubelet PVC stale metrics

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1542135

### CODE REVIEW

**Comment by mfojtik** [comment]
/approve

@smarterclayton I think this will have to cherry-pick to release-3.9 right? and we should hold till the branch cut is complete?

**Comment by jsafrane** [comment]
/cherrypick release-3.9

> If the PR lands after the release is cut, ensure developers apply /cherrypick release-3.9 comment to ensure a new PR is opened against origin/release-3.9.

let's see how this works...

**Pull request merged**
