### PR TITLE
Resurrect extensions/v1beta1.HPA

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
[test]

**Comment by ncdc** [comment]
@sttts was most of `UPSTREAM: <drop>: resurrect extensions/v1beta1.HPA` just copy/paste from the last revision before it was dropped from extensions?

**Comment by sttts** [comment]
@ncdc plus a number of conversion fixes if I remember right, taken from your kubecompat commit.

**Comment by ncdc** [comment]
@DirectXMan12 ptal

**Comment by DirectXMan12** [comment]
the conversion seem reasonable, but you appear to be missing some protobuf pieces (so the round-trip test is failing on that).

**Comment by ncdc** [comment]
I will have a PR shortly that fixes the protobuf issues. If that passes tests before @sttts is up tomorrow, we can merge it, or he can pick my commits and run with them.

**Comment by ncdc** [comment]
Ok mine is #14037

**Comment by sttts** [comment]
@ncdc green

**Comment by sttts** [comment]
@mfojtik @DirectXMan12 ptal. this is green and waiting to merge.

**Comment by sttts** [comment]
[merge]

**Pull request merged**
