### PR TITLE
remove lastModified from policy and policybinding

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/9290

[test]

### CODE REVIEW

**Comment by deads2k** [comment]
[merge]

**Comment by smarterclayton** [comment]
Is this a breaking API change?  Since you've removed a field that was previously serialized?

**Comment by smarterclayton** [comment]
It would be safer to return modificationTimestamp = creationTimestamp

**Comment by deads2k** [comment]
> It would be safer to return modificationTimestamp = creationTimestamp

As discussed in person, not safer if someone was actually using the field as it was documented.  Reverting.

**Pull request merged**
