### PR TITLE
NO-JIRA: Introduce version annotation test for Windows nodes

### PR DESCRIPTION
**Pull request by jrvaldes**
This PR proposes a new group of tests targeting Windows nodes in the test cluster and introduces a simple Windows-specific check as the first step in providing test coverage for Windows nodes.

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

Thanks for doing this @jrvaldes!

**Comment by jrvaldes** [comment]
@deads2k   please consider overriding the failed tests as they are unrelated to the proposed change.

**Comment by jrvaldes** [comment]
> @deads2k please consider overriding the failed tests as they are unrelated to the proposed change.

@celebdor   could you help with the failed tests?

**Pull request merged**
