### PR TITLE
test/cmd: build.sh can't reach old openshift/origin:v1.1 image

### PR DESCRIPTION
**Pull request by smarterclayton**
Change to use centos:7 which is more consistent.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Labeling to unblock (fixed the parts of the test that also needed to change due to rename)

**Comment by adambkaplan** [comment]
@benluddy can you please let us know why you would like this PR to be backported to 4.3?

**Comment by benluddy** [comment]
Hi @adambkaplan, 4.3 backport PRs appear to be repeatedly running into this issue on presubmits (https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-oc-release-4.3-e2e-cmd).

**Comment by adambkaplan** [comment]
/cherry-pick release-4.3

@smarterclayton we'll need BZs for this...

**Comment by benluddy** [comment]
Thanks!

**Comment by gabemontero** [comment]
Need this for 4.2 as well ... see https://github.com/openshift/origin/pull/24511

/cherrypick release-4.2

**Pull request merged**
