### PR TITLE
unit test for newapp dockerimagelookup

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng @smarterclayton ptal

**Comment by bparees** [comment]
[test]

**Comment by csrwng** [comment]
why is this an integration test?

**Comment by bparees** [comment]
good question.  it started out differently.

**Comment by bparees** [comment]
@csrwng moved to unit test

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by smarterclayton** [comment]
It only has to be an integration test if it calls out to git clone or load
docker images.

**Comment by bparees** [comment]
> It only has to be an integration test if it calls out to git clone or load
docker images

in my head it was originally going to be creating and looking up imagestreams, etc, obviously it ended up much simpler.

**Pull request merged**
