### PR TITLE
add --timeout flag to oc rsh

### PR DESCRIPTION
**Pull request by juanvallejo**
`oc rsh` currently has a timeout of 10 seconds hardcoded for pod
requests made to the server. This patch adds a flag `--timeout` to make
this time user-configurable

cc @fabianofranz

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by fabianofranz** [comment]
Needs to generate docs and completions. @liggitt PTAL

**Comment by juanvallejo** [comment]
re[test]

**Comment by kargakis** [comment]
LGTM

**Comment by juanvallejo** [comment]
@fabianofranz PTAL

**Comment by fabianofranz** [comment]
[merge]

**Comment by juanvallejo** [comment]
[integration](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/6182/) test flaked on https://github.com/openshift/origin/issues/9203
[conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6299/) test flaked on https://github.com/openshift/origin/issues/9548
re[test]

**Comment by juanvallejo** [comment]
[conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6422/) test flaked on https://github.com/openshift/origin/issues/9548 re[test]

**Comment by fabianofranz** [comment]
re[merge]

**Pull request merged**
