### PR TITLE
Run image policy in all namespaces

### PR DESCRIPTION
**Pull request by deads2k**
Potentially dangerous, but it we'll be the last special case. Let's see what happens

### CODE REVIEW

**Comment by deads2k** [comment]
@derekwaynecarr @smarterclayton @bparees @adambkaplan this was interesting.  Are we confident enough to have a single set of rules here or do we want to keep the runlevel exclusion....

/hold

so no one accidentally merges

**Comment by smarterclayton** [comment]
ImagePolicy should fail open unless someone sets a restrictive policy.  I guess we just have to say the replacement image policy has to be per namespace or be scoped.

**Comment by bparees** [comment]
@deads2k sorry, can you clarify what the runlevel exclusion meant in terms of imagepolicy enforcement behavior?

**Pull request closed without merging**
