### PR TITLE
Bump cobra and pflag with improved suggestions

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[merge]

**Comment by deads2k** [comment]
@fabianofranz Can you can make an upstream pull request to get kube in sync?  Its painful to deal with distinct levels during a rebase.

**Comment by deads2k** [comment]
@kargakis FYI, so we don't lose this by accident.

**Comment by kargakis** [comment]
> @fabianofranz Its painful to deal with distinct levels during a rebase.

true

**Comment by fabianofranz** [comment]
@deads2k @kargakis on it.

**Pull request merged**
