### PR TITLE
UPSTREAM: 65447: Resolve potential devicePath symlink when MapVolume

### PR DESCRIPTION
**Pull request by wongma7**
this is to fix https://bugzilla.redhat.com/show_bug.cgi?id=1594201 for 3.11
I do not know how to test it with containerized kubelet, I assume our e2e will.
@openshift/sig-storage kindly review please ty.

### CODE REVIEW

**Comment by wongma7** [comment]
whoops, I am missing the patch that added EvalSymlinks to nsenter to begin with....

**Comment by wongma7** [comment]
/hold
we will pick up EvalSymlinks in the rebase

**Comment by wongma7** [comment]
/test unit
https://github.com/openshift/origin/issues/20196

**Comment by wongma7** [comment]
We need also https://github.com/kubernetes/kubernetes/pull/64426 since we are changing the mount interface & all fake mounters are affected
/hold cancel
/assign @jsafrane
please review, ty

**Comment by wongma7** [comment]
/assign @smarterclayton
for approval please. Thank you!

**Comment by childsb** [comment]
@smarterclayton ping

**Comment by knobunc** [comment]
/lgtm
/approve

Over to you @smarterclayton

**Pull request merged**
