### PR TITLE
Fix pullthrough serve blob

### LINKED ISSUE #8613: HEAD on the docker registry for a pull through image looks like it is downloading contents
That's bad.  Or at least not good.

### PR DESCRIPTION
**Pull request by miminar**
Don't attempt to copy any data on a HEAD.

Closes #8613

### CODE REVIEW

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
Tested manually with `tcpdump`.

**Comment by miminar** [comment]
Looks like flake #9775 
```
Running test/end-to-end/core.sh:29: executing 'oc get -n test pods' expecting any result and text 'frontend.+Running'; re-trying every 0.2s until completion or 120.000s...
FAILURE after 119.691s: test/end-to-end/core.sh:29: executing 'oc get -n test pods' expecting any result and text 'frontend.+Running'; re-trying every 0.2s until completion or 120.000s: the command timed out
```
[test]

**Comment by miminar** [comment]
@legionus PTAL

**Comment by legionus** [comment]
@miminar Can you add integration test for that ?

**Comment by miminar** [comment]
@legionus would a unit test do?

**Comment by legionus** [comment]
I think you can use any test that checks for this.

**Comment by mfojtik** [comment]
@miminar do we need to backport this?

**Comment by miminar** [comment]
@mfojtik it would be nice. Once merged, I'll do the backport. I haven't yet got the chance to finish the tests though.

**Comment by miminar** [comment]
@legionus, @soltysh: unit tests added.

**Comment by miminar** [comment]
@smarterclayton fyi

**Comment by legionus** [comment]
LGTM

@mfojtik We need to backport it.

**Comment by soltysh** [comment]
LGTM 

[merge]

**Comment by liggitt** [comment]
let's get the blob ACL PR in first

**Comment by miminar** [comment]
Yeah, it will conflict for sure.

**Comment by miminar** [comment]
Flake #10263. re-[test]

**Comment by miminar** [comment]
Flake #10263. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3930/console#13129876456cbb9a5e4b02b88ae8c2f77

 re-[test]

**Comment by miminar** [comment]
Flake #10263. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3930/

re-[test]

**Comment by miminar** [comment]
Flake https://github.com/openshift/origin/issues/10263. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3930/

re-[test]

**Comment by miminar** [comment]
I just don't know, how to defeat `"The Origin test job could not be run again for this pull request."` message without altering commits. In the end, I gave up and re-signed the last commit to move forward.

**Comment by stevekuznetsov** [comment]
@miminar as the bot requests, you need to have the failed Jenkins job link. The sentence telling you that this link is necessary also has a hyperlink to the failed job it is searching for. This job is the job that was triggered  by the bot, so it will be `test_pr_origin`, not one of the sub-jobs like `test_pull_requests_origin_networking`. This is a required feature as you could have both failed merge and test jobs in the PR at the same time. The bot needs to know for which failed job you are declaring flakes to have been found.

**Comment by miminar** [comment]
@stevekuznetsov thanks! That's 1:0 for the bot. I'm sure I'll win next time.

**Comment by miminar** [comment]
Flake openshift/origin#10274. Job https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7632/
And flake #9490. re-[test]

**Comment by stevekuznetsov** [comment]
@miminar I'm actually impressed, with your newest comment you found two other bugs in the bot ... I didn't even realize the first way you linked to an issue was a valid thing ... give me a moment.

**Comment by miminar** [comment]
I'm always glad to help. :smile:

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
yum flake, [test]

**Comment by miminar** [comment]
@mfojtik can you please merge?

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
