### PR TITLE
Continue project cache evaluation in the presence of evaluation errors

### LINKED ISSUE #11449: Invalid roleRef in a rolebinding omits project from project list
if a policybinding contains an invalid roleRef, the project containing the policybinding disappears from the projects list

binding.yaml:
```yaml
apiVersion: v1
kind: PolicyBinding
metadata:
  name: foo:default
policyRef:
  name: default
  namespace: foo
roleBindings:
- name: myrole
  roleBinding:
    metadata:
      creationTimestamp: 2016-10-19T16:10:33Z
      name: myrole
      namespace: foo
      resourceVersion: "415"
      uid: 8ffecfb4-9616-11e6-b105-00e092001ba4
    roleRef:
      name: myrole
      namespace: foo
```

oc new-project foo
oc create -f binding.yaml
oc get projects

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #11449

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by liggitt** [comment]
[test]

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
test failed on #11240 [merge]

**Comment by marun** [comment]
networking job flaked with #11452

**Comment by liggitt** [comment]
[test]

**Pull request merged**
