### PR TITLE
Bug 1338679: emit events on failure to create a deployer pod

### PR DESCRIPTION
**Pull request by kargakis**
Fixes regression caused by https://github.com/openshift/origin/pull/8652
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1338679

@smarterclayton @ironcladlou @mfojtik PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

[merge]

**Comment by kargakis** [comment]
[test] ?

**Comment by mfojtik** [comment]
@kargakis it seems like @openshift-bot took PTO

**Comment by kargakis** [comment]
@mfojtik nah, it just woke up

**Comment by mfojtik** [comment]
@kargakis he must be from US

**Comment by kargakis** [comment]
> @kargakis he must be from US

Look at its info - "Raleigh, NC" ;)

**Pull request merged**
