### PR TITLE
UPSTREAM: 32662: Change the default volume type of GlusterFS provisioner

### PR DESCRIPTION
**Pull request by jsafrane**
Let there be 3 replicas by default.

### CODE REVIEW

**Comment by jsafrane** [comment]
[test]

**Comment by jsafrane** [comment]
[test]

**Comment by gnufied** [comment]
lgtm !

**Comment by gnufied** [comment]
This seems to have flaked on https://github.com/openshift/origin/issues/9548 and https://github.com/openshift/origin/issues/9490

**Comment by gnufied** [comment]
So the remaining flakes in this PR are similar to https://github.com/openshift/origin/issues/11094 , where it is simply taking longer time than 5 minutes to delete a namespace. 

I tried to find out, if something is there in the PR which is causing this. But the failling tests have nothing to do with gluster volume provisioning at all. 

cc @rootfs

**Comment by jsafrane** [comment]
@childsb, can you please approve this PR?

**Comment by childsb** [comment]
[merge]

**Pull request merged**
