### PR TITLE
Attempt to show server error returned while establishing remote command

### LINKED ISSUE #5619: Server errors establishing remote command connections are masked
Continuation of https://github.com/openshift/origin/issues/5602
#5525 no longer reads the request body and attempts to convert it to an error when the response code is not the expected upgrade response

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5619

### CODE REVIEW

**Comment by liggitt** [comment]
@ncdc PTAL

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
This is LGTM

**Comment by smarterclayton** [comment]
You are cleared for super merge

**Comment by liggitt** [comment]
green jenkins at https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6662
updated with upstream commit number

**Pull request merged**
