### PR TITLE
show error when cluster up fails

### PR DESCRIPTION
**Pull request by deads2k**
Annoying little oversight.  I need to see my failures.

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k it already does print out an error 
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/up.go#L309-L312

Is there a specific case that it's not doing that for you?

**Comment by deads2k** [comment]
It's related to other changes I'm messing with, but it's more normal to print it out at the top level to make sure you don't miss anything.  This makes any early return print out an error instead of being missed.  I can move the existing logic if need be, but it really needs to be top level.

**Comment by deads2k** [comment]
I can even skip on a typed error if you like, but we need this check.

**Comment by csrwng** [comment]
> I can even skip on a typed error if you like, but we need this check.

I like that. If you return a typed error from the Run command that'd prevent double printing of errors.

**Comment by deads2k** [comment]
> I can even skip on a typed error if you like, but we need this check.
> I like that. If you return a typed error from the Run command that'd prevent double printing of errors.

Take a look.  I moved the printing out to the higher level using the `error` interface.

**Pull request merged**
