### PR TITLE
Remove release image definitions from this repo

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Remove release image definitions from this repo

The container manifests and configuration for pushes now lives at
`openshift/release/projects/origin-release`.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

/assign @smarterclayton

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Depends on #15959

**Comment by smarterclayton** [comment]
Oops, just lgtm

**Comment by stevekuznetsov** [comment]
@smarterclayton not sure what you meant to do there

**Comment by smarterclayton** [comment]
Is this really to merge?  Implied it was waiting for something else

On Aug 25, 2017, at 4:14 AM, OpenShift Merge Robot <notifications@github.com>
wrote:

@stevekuznetsov <https://github.com/stevekuznetsov> PR needs rebase

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/15962#issuecomment-324853712>,
or mute
the thread

**Comment by stevekuznetsov** [comment]
The prereq PR merged over night. The pipeline in release on api.ci is pushing to the hub. Nothing else required.

**Pull request merged**
