### PR TITLE
run the bare kube controllers

### PR DESCRIPTION
**Pull request by deads2k**
This runs the kube controllers separately based on their command to avoid any customization and set us up to run them as-is, without modification in a future release (double lease thing).

@smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'm looking at memory numbers but I'm probably going to have to require that informers not be duplicated in 3.7 until we get other things under control.  I'm ok with a clean patch that we plan on removing that provides them in and this structure, but the memory numbers aren't good enough to do this yet.

**Comment by deads2k** [comment]
> I'm looking at memory numbers but I'm probably going to have to require that informers not be duplicated in 3.7 until we get other things under control. I'm ok with a clean patch that we plan on removing that provides them and uses this structure, but the memory numbers aren't good enough to do this yet.

Why do you believe memory usage will improve going forward?

**Comment by smarterclayton** [comment]
Memory usage will improve or the beatings will continue.

**Comment by deads2k** [comment]
Alright, I've create a carry patch to allow us to shim in our informers.  It's ugly, but I think its better than carrying a separate config generation.

I'll make a followup to remove building the config.

/assign mfojtik

**Comment by deads2k** [comment]
This doesn't work because of the multiple informer starts caused by sending our informers to the kube-controller process.  This may require greater violence.

**Comment by deads2k** [comment]
Wow, green

**Comment by deads2k** [comment]
etcd
/retest

**Comment by mfojtik** [comment]
/lgtm

Potential fix for https://bugzilla.redhat.com/show_bug.cgi?id=1491202

**Pull request merged**
