### PR TITLE
[release-4.4] Bug 1829327: annotations exist, else forbidden: unable to validate

### PR DESCRIPTION
**Pull request by soltysh**
Manual cherry-pick of https://github.com/openshift/origin/pull/24828

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
failing to build:

```
STEP 5: RUN make build WHAT=cmd/openshift-tests;     mkdir -p /tmp/build;     cp /go/src/github.com/openshift/origin/_output/local/bin/linux/$(go env GOARCH)/openshift-tests /tmp/build/openshift-tests
hack/build-go.sh cmd/openshift-tests -mod=vendor
++ Building go targets for linux/amd64: cmd/openshift-tests
# github.com/openshift/origin/test/extended/util
test/extended/util/framework.go:1026:32: too many arguments in call to c.Projects().Get
test/extended/util/framework.go:1026:33: undefined: context
[ERROR] hack/lib/build/binaries.sh:224: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" -gcflags "${gogcflags}" "${nonstatics[@]}"` exited with status 2.
[ERROR] hack/lib/build/binaries.sh:138: `local -a binaries=("$@")` exited with status 2.
[ERROR] hack/build-go.sh exited with code 2 after 00h 00m 54s
make: *** [build] Error 2
```

/hold

**Comment by soltysh** [comment]
@bparees sorry missed that bit, should be fix now.

**Comment by bparees** [comment]
/hold cancel

patch window is closed so this'll have to go in this week instead.

**Pull request merged**
