### PR TITLE
add a test for fetchruntimeartifacts failure

### PR DESCRIPTION
**Pull request by PI-Victor**
* rename one variable to upercase URL

### CODE REVIEW

**Comment by PI-Victor** [comment]
[test]
[testextended][extended:core(builds)]
cc: @bparees

**Comment by PI-Victor** [comment]
*sigh 
flake : https://github.com/openshift/origin/issues/12479

https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/985/consoleFull#123465095256cbb9a5e4b02b88ae8c2f77

the test. however. passes:
```
• [SLOW TEST:27.325 seconds]
[builds][Slow] update failure status
/data/src/github.com/openshift/origin/test/extended/builds/failure_status.go:159
  Build status failed assemble runtime artifacts 
  /data/src/github.com/openshift/origin/test/extended/builds/failure_status.go:158
    should contain the failure reason related to failing to fetch runtime image artifacts
    /data/src/github.com/openshift/origin/test/extended/builds/failure_status.go:157
------------------------------
SSSSSSSSS
```

**Comment by bparees** [comment]
squash please

**Comment by bparees** [comment]
i've updated your comment to just run your new test.

**Comment by PI-Victor** [comment]
@bparees squashed. forgot you could filter specific tests as well, thanks!

**Comment by bparees** [comment]
[merge]

**Pull request merged**
