### PR TITLE
deploy: cleanup dc controller

### PR DESCRIPTION
**Pull request by kargakis**
Since upstream are going to support up to two old releases, there is no
reason for us to continue supporting pre 1.1 clients. This commit makes
the deployment config controller a maintainable piece of code again after
a long time:)

@mfojtik @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
Add a release note and @brenton that 3.1 -> 3.4 upgrade will not be allowed
directly.

On Oct 18, 2016, at 5:58 PM, Michail Kargakis <notifications@github.com>
wrote:

[test]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/11426#issuecomment-254651846>,
or mute
the thread

**Comment by brenton** [comment]
@smarterclayton, The upgrade playbooks today require that customers upgrade sequentially without skipping any steps.

**Comment by kargakis** [comment]
Release note added: https://github.com/openshift/openshift-docs/issues/2933#issuecomment-254803980

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11240 [test]

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
[merge]

**Comment by mfojtik** [comment]
approved for 3.4

[merge]

**Pull request merged**
