### PR TITLE
configchange: correlate triggers with the generated cause

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/7663

@smarterclayton @ironcladlou PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by ironcladlou** [comment]
LGTM, thanks

**Comment by kargakis** [comment]
@smarterclayton anything else you need here?

**Comment by kargakis** [comment]
Will merge this first thing tomorrow morning..

**Comment by smarterclayton** [comment]
Example output?

**Comment by kargakis** [comment]
Example output of what? This handles multiple image change triggers by correlating one of them with the deployment cause and deciding if it should proceed or not (due to a race with the imagechange controller)

**Comment by smarterclayton** [comment]
Nm, this LGTM.  Thought this was the status issue.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Report from a user that might be related to this:

-----------------

I have a weird behaviour I can't explain (os 1.1.3).
We're pushing layers directly to OS registry, and it generally deploys new versions as they arrive on the registry.
We sometimes want to test different versions, and therefore edit the dc to use a specific tag:

  triggers:
  - imageChangeParams:
      containerNames:
      - resque
      from:
        kind: ImageStreamTag
        name: myis:my-test-tag
    type: ImageChange
  - type: ConfigChange

Problem is: while the dc is edited ("deploymentconfig "mydc" edited"), the new pods are not deployed. If I force the deploy with oc deploy, I have new pods, but still using a old image sha:

4 weeks ago     172.30.68.98:5000/myproject/myis@sha256:7388a042d0a7ee...  <same>

We have pushed many layers since, that sha was the "latest" 4 weeks ago.

Any idea what could cause this, and how to fix it?

**Comment by kargakis** [comment]
Copying my answer from the list for clarity:

I don't think so.

1) We don't redeploy on trigger changes (only on podtemplate changes). That's why the deployment never starts automatically here.
2) By having the imagechange trigger set to "automatic: false" we never resolve the tag (see https://github.com/openshift/origin/issues/6934 and my fix for it https://github.com/openshift/origin/pull/7439)

**Pull request merged**
