### PR TITLE
Enable PodDistruptionBudget

### LINKED ISSUE #10938: post-rebase: Enable the disruption budget controller and add its e2e tests
We want to test with it before we've gotten out of 1.4.

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #10938.

@smarterclayton is there something else needed you were thinking of?

@deads2k I have a question regarding ServiceAccounts and `SharedIndexInformer`. If a controller (here `DisruptionController` [does not have](https://github.com/openshift/origin/blob/ffdeb1bb546339f62722f507e1a12bdb9701c4c2/pkg/cmd/server/bootstrappolicy/infra_sa_policy.go#L693-L732) explicit access rights to Pods, but can access them through that `SharedIndexInformer` is ok? If the same controller would like to access pods directly, it would need such an access right, why then using this cache, it's not required anymore?

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by deads2k** [comment]
> If the same controller would like to access pods directly, it would need such an access right, why then using this cache, it's not required anymore?

We never built one that checks permissions on an individual client being submitted.  Informers are non-mutating and at least one client in the process had rights, so we let it through.

**Comment by soltysh** [comment]
@deads2k can I be the picky one complaining that this is not cool about it? Is there a plan (sometime in the future) to fix it, or we're cool with the current state of world?

**Comment by deads2k** [comment]
> @deads2k can I be the picky one complaining that this is not cool about it? Is there a plan (sometime in the future) to fix it, or we're cool with the current state of world?

I think we're ok with the state of the world.  For now.

**Comment by soltysh** [comment]
@smarterclayton any objections for merge?

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by soltysh** [comment]
Flake #11016 

re-[merge]

**Comment by soltysh** [comment]
It looks like I'm constantly hitting #11016, I need to investigate this more before actually merging.

**Comment by soltysh** [comment]
@mfojtik @kargakis so I am able to reproduce consistently the timeouts, with this PR. I'll be digging deeper what might be causing that.

**Comment by soltysh** [comment]
@smarterclayton this required 2 additional changes upstream and an extension to policy, so that regular users should be able to use it. Mind taking a look once again?

**Comment by soltysh** [comment]
After discussion with @smarterclayton about security implications PDB will be enabled only for cluster admins. I've dropped the commit updating policy. Upon green tests I'll merge this in.

**Comment by kargakis** [comment]
Have you also enabled the eviction subresource?

**Comment by soltysh** [comment]
Rebased and waiting for green tests...

**Comment by mfojtik** [comment]
[merge]

**Comment by smarterclayton** [comment]
Lgtm [merge]

On Oct 21, 2016, at 5:52 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test SUCCESS (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/10440/) (Base
Commit: fa658ac
<https://github.com/openshift/origin/commit/fa658ac235c367d3ddec80c3130e720c7952d9a4>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/11187#issuecomment-255474369>,
or mute
the thread

**Pull request merged**
