### PR TITLE
UPSTREAM: track origin of reflectors

### PR DESCRIPTION
**Pull request by deads2k**
Adding a `name` field to reflectors to make it easier to figure out which reflector is having trouble.  This can happen for authentication and/or authorization problems.

Now the messages look like this:
```
E0618 09:38:02.509745   25120 reflector.go:164] pkg/admission/namespace/exists/admission.go:102: Failed to list *api.Namespace: Get https://10.13.137.63:8443/api/v1/namespaces: dial tcp 10.13.137.63:8443: connection refused
```

@liggitt @smarterclayton If we want this, I'll open an upstream pull.

### CODE REVIEW

**Comment by deads2k** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/10024

**Comment by deads2k** [comment]
@smarterclayton This keeps the diff small enough for us to carry as a patch.

**Comment by smarterclayton** [comment]
That's fine

**Comment by deads2k** [comment]
We'll get this in the next rebase.

**Pull request closed without merging**
