### PR TITLE
Revert "Bug 1763936: Disable node-Service and pod-Service granular checks"

### PR DESCRIPTION
**Pull request by smarterclayton**
Reverts openshift/origin#24185, insufficient justification provided for disablement.

### CODE REVIEW

**Comment by danwinship** [comment]
> The test was not being run in 4.2

(it was marked `[Slow]` until recently upstream)

**Comment by smarterclayton** [comment]
It is not flaky in the stress tests.  Is it flaky in e2e-aws

**Comment by smarterclayton** [comment]
This does not look flaky to me:

**Pull request merged**
