### PR TITLE
Normalize extended tests into test/extended/*.sh

### PR DESCRIPTION
**Pull request by smarterclayton**
Fix readmes. Split networking into its own suite.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k @mfojtik

I may rename all to core (to match e2e)

On Sep 14, 2015, at 2:56 AM, OpenShift Bot <notifications@github.com> wrote:

Origin Action Required: Pull request cannot be automatically merged, please
rebase your branch from latest HEAD and push again

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4658#issuecomment-139979553>.

**Comment by smarterclayton** [comment]
[merge]

**Comment by deads2k** [comment]
I'm pretty sure this broke all extended tests.  See the https://ci.openshift.redhat.com/jenkins/job/origin_extended/ job and https://ci.openshift.redhat.com/jenkins/job/origin_extended/53/consoleText as a for instance.

**Comment by liggitt** [comment]
@smarterclayton did you get a clean extended run before merging?

**Comment by smarterclayton** [comment]
They are intentionally broken right now while they are being changed.

On Sep 15, 2015, at 9:31 AM, Jordan Liggitt <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> did you get a clean
extended run before merging?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4658#issuecomment-140394366>.

**Pull request merged**
