### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by rhcarvalho**
Code changed, comment drifted.

Follows up on #9165.

@deads2k PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
[merge]

**Comment by rhcarvalho** [comment]
Can we try again?

**Comment by deads2k** [comment]
[test][merge]

**Comment by rhcarvalho** [comment]
@deads2k can we try again?

**Comment by deads2k** [comment]
> @deads2k can we try again?

Wait for one day to let the pulls that have waited on the rebase merge in.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
