### PR TITLE
Fix URL for build webhooks docs in console

### PR DESCRIPTION
**Pull request by jhadvig**
Just a small fix of docs link in console

### CODE REVIEW

**Comment by jhadvig** [comment]
[test]

**Comment by mmahut** [comment]
[test]

**Comment by jhadvig** [comment]
[test] again

**Comment by soltysh** [comment]
@jhadvig since you're changing assets don't forget to run build-assets step see [here](https://github.com/openshift/origin/tree/master/assets#before-opening-a-pull-request) and [here](https://github.com/openshift/origin/tree/master/assets#production-builds) for more details.

**Comment by jhadvig** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
