### PR TITLE
[WIP] always run extended test builds with loglevel 5

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@bparees assume the previous runs did not show the problem or had something else?

**Comment by bparees** [comment]
> @bparees assume the previous runs did not show the problem or had something else?

correct, previous runs succeeded except for "end_to_end" which looked like something else, i didn't dig into it.

**Comment by bparees** [comment]
and now the GCP run failed with:

```
Wednesday 07 March 2018  01:08:23 +0000 (0:00:01.545)       0:10:11.344 ******* 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/tmp/openshift_gcp_provision.sh"], "delta": "0:00:40.555783", "end": "2018-03-07 01:09:04.453270", "msg": "non-zero return code", "rc": 1, "start": "2018-03-07 01:08:23.897487", "stderr": "WARNING: mode is deprecated. Please use subnet-mode instead.\nERROR: (gcloud.compute.networks.create) Could not fetch resource:\n - Quota 'SUBNETWORKS' exceeded.  Limit: 450.0 globally.", "stderr_lines": ["WARNING: mode is deprecated. Please use subnet-mode instead.", "ERROR: (gcloud.compute.networks.create) Could not fetch resource:", " - Quota 'SUBNETWORKS' exceeded.  Limit: 450.0 globally."], "stdout": "", "stdout_lines": []}
```

@stevekuznetsov any chance we're running out of quota on GCP?  (not that that would cause any of the other flakes we're chasing, but it would be good to resolve if so)

**Comment by derekwaynecarr** [comment]
These are not the flakes we are looking for :-)

**Comment by derekwaynecarr** [comment]
So this flaked on invalid pod transition.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18867/test_pull_request_origin_extended_conformance_install/8602/

@sjenning - gift that keeps on giving.

But it’s not the flake we are looking for.

**Comment by derekwaynecarr** [comment]
@sjenning this pr appears to flake on pod invariants somehow yet your fix should be in master (not 3.9 yet)
https://github.com/openshift/origin/pull/18867#issuecomment-370996185

**Comment by derekwaynecarr** [comment]
Actually I got it backwards, your change went into to 3.9 but not master yet.

**Comment by derekwaynecarr** [comment]
trying to induce a flake.  last run succeeded.

/test extended_conformance_install

**Comment by stevekuznetsov** [comment]
Requested more subnets. Looking into whether some are not getting cleaned up.

**Pull request closed without merging**
