### PR TITLE
make build event checking tolerant of latency

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/13894

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
@oatmealraisin ptal

**Comment by bparees** [comment]
@oatmealraisin bump

**Comment by oatmealraisin** [comment]
@bparees lgtm, interesting wait package

**Comment by bparees** [comment]
[merge]

**Pull request merged**
