### PR TITLE
UPSTREAM: 46463: AWS: consider instances of all states in DisksAreAtt…

### PR DESCRIPTION
**Pull request by wongma7**
…ached, not just "running"

### CODE REVIEW

**Comment by wongma7** [comment]
https://github.com/kubernetes/kubernetes/pull/46463

**Comment by wongma7** [comment]
[test]

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by wongma7** [comment]
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1457510

**Pull request merged**
