### PR TITLE
api: enable serialization tests for Pod{Exec,Attach}Options

### PR DESCRIPTION
**Pull request by kargakis**
Partially addresses https://github.com/openshift/origin/issues/5529

@deads2k @liggitt

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
```
ok  	github.com/openshift/origin/pkg/api	8.564s
```

**Comment by deads2k** [comment]
lgtm, but add indicators for your flakes here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/ before merging.

**Comment by kargakis** [comment]
I wish I could remember my Jenkins pass

@danmcp should I request a new account?

**Comment by deads2k** [comment]
> lgtm, but add indicators for your flakes here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/ before merging.

@liggitt @pweil- @bparees I'd like to enforce this during reviews.  We can now categorize flakes and inspect the console logs for errors using regexes (I know, two problems), but it helps to prioritize which flakes really matter.  It doesn't take long and adding indicators with description links to github issues will make people more aware of what's happening.

**Comment by pweil-** [comment]
@deads2k :+1:  - do we have any docs on adding the indicators?

**Comment by deads2k** [comment]
> @deads2k  - do we have any docs on adding the indicators?

Nothing specific.  It's this plugin: https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer, but the jenkins page itself is pretty easy to use.

**Comment by kargakis** [comment]
```
FAILURE: Generation of fresh spec failed:
[INFO] Creating certificates for the OpenShift server
Generated new key pair as /tmp/openshift/generate-swagger-spec/openshift.local.config/master/serviceaccounts.public.key and /tmp/openshift/generate-swagger-spec/openshift.local.config/master/serviceaccounts.private.key
[INFO] Creating OpenShift node config
Generating node credentials ...
Created node config for 172.18.9.226 in /tmp/openshift/generate-swagger-spec//openshift.local.config/node-172.18.9.226
[INFO] Creating OpenShift config
Wrote master config to: /tmp/openshift/generate-swagger-spec/openshift.local.config/master/master-config.yaml
Generating node credentials ...
Created node config for 172.18.9.226 in /tmp/openshift/generate-swagger-spec/openshift.local.config/node-172.18.9.226
[INFO] To debug: export KUBECONFIG=/tmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig
[INFO] openshift v1.1.1-263-gaaf67e1
kubernetes v1.2.0-alpha.4-851-g4a65fa1
etcd 2.2.2
[INFO] Server logs will be at:    /tmp/openshift/generate-swagger-spec//logs/openshift.log
[INFO] Test artifacts will be in: /tmp/openshift/generate-swagger-spec//artifacts
[INFO] Config dir is:             /tmp/openshift/generate-swagger-spec//openshift.local.config
[INFO] Using images:              openshift/origin-${component}:latest
[INFO] MasterIP is:               https://127.0.0.1:38443
[INFO] Scan of OpenShift related processes already up via ps -ef	| grep openshift : 
ec2-user  5558  5557  0 19:13 ?        00:00:00 /bin/bash /data/src/github.com/openshift/origin/hack/update-generated-swagger-spec.sh _output/verify-generated-swagger-spec
ec2-user  5642  5558  0 19:13 ?        00:00:00 grep openshift
[INFO] Starting OpenShift server
[INFO] OpenShift server start at: 
Wed Jan 27 19:13:35 EST 2016
ERROR: gave up waiting for https://127.0.0.1:38443/healthz

!!! Error in /data/src/github.com/openshift/origin/hack/../hack/util.sh:370
	'return 1' exited with status 1
Call stack:
	1: /data/src/github.com/openshift/origin/hack/../hack/util.sh:370 start_os_master(...)
	2: /data/src/github.com/openshift/origin/hack/update-generated-swagger-spec.sh:50 main(...)
Exiting with status 1
```
[test]

**Comment by kargakis** [comment]
@deads2k added https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/56aa4bf4e4b089752bb437f3/ for the failure I posted above though I am not sure if that problem goes deeper

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
