### PR TITLE
Upstream e2e accidentally disabled during rebase

### PR DESCRIPTION
**Pull request by smarterclayton**
We had no explicit reference to their suite, and they refactored.

Also disable a failing test until it can be debugged.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@liggitt @mfojtik

**Comment by smarterclayton** [comment]
Also restored some output that was deleted during the rebase

**Comment by mfojtik** [comment]
@smarterclayton thanks!

**Comment by smarterclayton** [comment]
@marun @knobunc failure from networking e2e suite:

```
unexpected fault address 0x7984
fatal error: fault
[signal 0xb code=0x1 addr=0x7984 pc=0x8b5641]

goroutine 77 [running]:
runtime.throw(0x254f538, 0x5)
	/usr/lib/golang/src/runtime/panic.go:547 +0x90 fp=0xc820c3e3d8 sp=0xc820c3e3c0
runtime.sigpanic()
	/usr/lib/golang/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820c3e428 sp=0xc820c3e3d8
k8s.io/kubernetes/test/e2e/framework.(*PodStateVerification).filter(0xc82075b1d8, 0x616552746f4e7372, 0x7964, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:596 +0x81 fp=0xc820c3ec30 sp=0xc820c3e428
k8s.io/kubernetes/test/e2e/framework.(*ClusterVerification).WaitFor.func1(0x1c26c20, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630 +0x7a fp=0xc820c3ed10 sp=0xc820c3ec30
k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc820580440, 0xc8205d0990, 0xc82068bbc0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:181 +0x77 fp=0xc820c3ed58 sp=0xc820c3ed10
k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc820580440, 0xc8205d0990, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:143 +0x8a fp=0xc820c3eda0 sp=0xc820c3ed58
k8s.io/kubernetes/pkg/util/wait.Poll(0x3b9aca00, 0x2e90edd000, 0xc8205d0990, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:137 +0x4f fp=0xc820c3edc8 sp=0xc820c3eda0
k8s.io/kubernetes/test/e2e/framework.(*ClusterVerification).WaitFor(0xc820c3f1c8, 0x1, 0x2e90edd000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629 +0x17f fp=0xc820c3eea8 sp=0xc820c3edc8
k8s.io/kubernetes/test/e2e.runClientServerBandwidthMeasurement.func1()
```

**Comment by smarterclayton** [comment]
Failures in quota and scheduling: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2212/testReport/

**Comment by smarterclayton** [comment]
@abhgupta do we need to enable the PodAffinity filters, or is the feature not ready?

**Comment by abhgupta** [comment]
@smarterclayton the code seemed to be in place - its the tests that seem to be broken. I was able to find reference to this upstream where these tests ([Feature:PodAffinity]) are being disabled.

https://github.com/kubernetes/kubernetes/issues/25398
https://github.com/kubernetes/kubernetes/pull/26697

**Comment by smarterclayton** [comment]
@derekwaynecarr re: quota

**Comment by marun** [comment]
@smarterclayton That looks like a failure of a new kube e2e test (networking_perf.go), and it should be disabled pending us having a chance to make sure it can run against origin.

**Comment by mfojtik** [comment]
LGTM

**Comment by smarterclayton** [comment]
NodeAffinity was a bug in the test - the annotation JSON was not valid JSON.

**Comment by abhgupta** [comment]
@smarterclayton yes, I saw yesterday that there was an extra comma in the annotation json - but since the test was disabled upstream, I didn't think that was the only issue. I should have highlighted that.

**Comment by derekwaynecarr** [comment]
It looks like there is a delay in observing pod deletions in quota for replenishment in each of the failed scenarios, but there was no delay in observing replenishment for the other resource types.

**Comment by smarterclayton** [comment]
Is it using the shared pod informer?

On Jun 17, 2016, at 1:07 PM, Derek Carr <notifications@github.com> wrote:

It looks like there is a delay in observing pod deletions in quota for
replenishment in each of the failed scenarios, but there was no delay in
observing replenishment for the other resource types.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9390#issuecomment-226825908>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p2Wb9o-Ciov8YIoCSZEDdLO3TByKks5qMtRmgaJpZM4I31-C>
.

**Comment by mfojtik** [comment]
i thought it was wrong on purpose to exercise the invalid JSON.

Sent from my phone

On 17 Jun 2016, at 17:22, Clayton Coleman <notifications@github.com> wrote:

NodeAffinity was a bug in the test - the annotation JSON was not valid JSON.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9390#issuecomment-226799071>, or mute
the thread
<https://github.com/notifications/unsubscribe/AACsaKJh0Kya8rwjCEShSHKduuhRNNxyks5qMruogaJpZM4I31-C>
.

**Comment by smarterclayton** [comment]
The NodeAffinity test is failing because LimitPodHardAntiAffinityTopology is turned on.  It's not enabled upstream during their e2e runs - did we turn it on for a reason?

**Comment by smarterclayton** [comment]
The admission controller fails due to it.

**Comment by smarterclayton** [comment]
Spawned #27645

**Comment by smarterclayton** [comment]
Spawned #9414 for quota and secret

**Comment by smarterclayton** [comment]
[merge] to get e2e back on

**Comment by resouer** [comment]
@smarterclayton if we swallow the err in admission, user will got failure when they disable validation, is this expected?

**Comment by smarterclayton** [comment]
User will see the validation error (a 422 Invalid that identifies the
field is incorrect)

**Pull request merged**
