### PR TITLE
bump(github.com/openshift/source-to-image): 49dac82c5f1521e95980c71ff0e092b991fc1b09

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jupierce ptal, mostly trying to get your fix for the symlink issue into origin for our extended tests.

[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by jupierce** [comment]
[testextended][extended:core(secrets)]

**Comment by jupierce** [comment]
@bparees Full extended build test failed on an unrelated timeout, so I changed to focus on secrets suite. Looks like the current failure arises from 
"E0725 13:08:20.509676       1 postexecutorstep.go:328] /bin/sh: /tmp/rm-injections: Permission denied" 
An inability to execute the removal script. My change should not have that effect. I don't suppose there is a way to ssh into the test system and analyze images after the fact is there?

**Comment by bparees** [comment]
@jupierce not trivially.  I've been seeing that injections failure in our current builds as well, it needs to be looked into.  eg you can see it here:

https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_build_tests/357/consoleFull
```
E0725 02:26:22.653688       1 postexecutorstep.go:315] /bin/sh: /tmp/rm-injections: Permission denied
```

so it's not introduced by this PR, anyway...

**Comment by bparees** [comment]
pretty confident we've introduce no *new* issues here. [merge]

**Pull request merged**
