### PR TITLE
[DO_NOT_MERGE] more commit reversion testing

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
one of these PRs appears to be responsible for this new integration test failure:
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4103/console
```
Running TestAuthorizationSubjectAccessReview...
failed  TestAuthorizationSubjectAccessReview
```

the authorization related upstream PR seems most likely.  will try it in isolation later.

**Comment by liggitt** [comment]
I don't think so. The error seems to be an etcd flake setting up the integration test

```
F1122 00:16:23.840500    9837 etcd.go:38] Unable delete key: 100: Key not found (/kubernetes.io) [1030]
```

I've seen that in the past

**Comment by liggitt** [comment]
More specifically, I don't think the HEAD verb PR could cause that

**Comment by bparees** [comment]
@liggitt it's more than a flake, it's failed 3-4 runs in a row.  but i agree the head verb PR doesn't look that promising as a suspect, it just seemed like an easy starting point to test.

**Comment by bparees** [comment]
had at least one successful merge, so i guess the flake theory has legs.

**Pull request closed without merging**
