### PR TITLE
TRT-1656: Revert #28750 "OCPBUGS-33041: Add RoleBinding for BuildConfig Webhooks"

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts #28750 ; tracked by [TRT-1656](https://issues.redhat.com//browse/TRT-1656)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

TestWebhook test is failing on minor upgrades due to a problem with AUTH-509, until that's resolved we need to kick this out of the payload.  It can be reintroduced when /payload testing verifies minor upgrades succeed

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload 4.16 nightly blocking
```

CC: @adambkaplan

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

This unblocks OpenShift controller manager PRs

**Comment by stbenjam** [comment]
/hold cancel

Please don't hold this; OpenShift policy is if you break payloads, you get reverted, even at the expense of broken presubmits.

**Pull request merged**
