### PR TITLE
UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function

### PR DESCRIPTION
**Pull request by jim-minter**
https://github.com/moby/moby/issues/36516
https://github.com/moby/moby/pull/36517

fixes https://github.com/openshift/origin/issues/18862

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k how does this play with glide up now updating everything?

**Comment by mrunalp** [comment]
:+1:

**Comment by deads2k** [comment]
> @deads2k how does this play with glide up now updating everything?

We can sort it out after we fix our queue.  It's some work.

@mfojtik

**Comment by deads2k** [comment]
@mfojtik I created https://github.com/openshift/moby-moby/tree/b68221c as a spot to start the fork from.  I'm not yet familiar with the commit format for the bot

**Pull request merged**
