### PR TITLE
prevent build updates from reverting the build phase

### PR DESCRIPTION
**Pull request by bparees**
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1425320

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
@coreydaley fyi

**Comment by bparees** [comment]
known extended build failure.
[merge]

**Comment by bparees** [comment]
backport to 1.5: https://github.com/openshift/origin/pull/13075

**Pull request merged**
