### PR TITLE
make cgroup imports linux-only

### PR DESCRIPTION
**Pull request by liggitt**
cgroups.ParseCgroupFile is only available on linux

fixes https://github.com/openshift/origin/issues/14718

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@bparees PTAL

**Comment by bparees** [comment]
lgtm
[testextended][extended:core(build with a quota)]

**Comment by bparees** [comment]
guess it's time to add cross-compiling checks to the merge queue? :(

**Comment by liggitt** [comment]
> guess it's time to add cross-compiling checks to the merge queue? :(

eh, it's rare and easy to fix when it happens

**Comment by liggitt** [comment]
[merge]

**Comment by bparees** [comment]
7 hours for a test job to fail. Wheee.

Ben Parees | OpenShift

**Comment by bparees** [comment]
in case anyone wants to investigate why the test took 6 hours, job was here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/3355/

[test]

**Comment by bparees** [comment]
So up to the integration test stage, things should have only taken maybe an hour.

Within the integration test stage, I see no successful test taking longer than 84s (and most of them are sub 1s), meaning I don't see any individual tests that appeared to get "stuck" but ultimately pass after consuming a bunch of time.

And then at the end of the stage we just fail:
```
There was no error output from the command.
Running test/end-to-end/core.sh:387: executing 'oc delete pod cli-with-token' expecting success...
SUCCESS after 0.257s: test/end-to-end/core.sh:387: executing 'oc delete pod cli-with-token' expecting success
Standard output from the command:
pod "cli-with-token" deleted

There was no error output from the command.
Connection to 172.18.7.30 closed by remote host.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
```

I don't know what that next command was that failed/hung or why.

**Pull request merged**
