### PR TITLE
UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function

### PR DESCRIPTION
**Pull request by jim-minter**
https://github.com/moby/moby/issues/36516
https://github.com/moby/moby/pull/36517

### CODE REVIEW

**Comment by bparees** [comment]
@derekwaynecarr @mrunalp we need to decide if we think this is critical for 3.9.  S2I was still using docker-engine in 3.9 so it is not vulnerable to the bug, what we aren't sure of is whether any other aspect of origin/k8s is.

**Comment by bparees** [comment]
I think https://bugzilla.redhat.com/show_bug.cgi?id=1550644 and https://bugzilla.redhat.com/show_bug.cgi?id=1552670 indicates we need this in 3.9

**Comment by mrunalp** [comment]
@bparees Yes, I agree that we should add this to 3.9.

**Comment by bparees** [comment]
/lgtm
(with @derekwaynecarr's concurrence)

**Comment by liggitt** [comment]
title of `UPSTREAM: docker/docker: 36517: ensure hijackedConn implements CloseWrite function` will make travis happier

**Comment by bparees** [comment]
> I think https://bugzilla.redhat.com/show_bug.cgi?id=1550644 and https://bugzilla.redhat.com/show_bug.cgi?id=1552670 indicates we need this in 3.9

@juanvallejo this may address your 2 bugs

**Comment by liggitt** [comment]
adding carries to this dependency mean we need a fork at https://github.com/openshift/docker-docker and a glide.yaml update or the next `glide update` will revert this

**Comment by bparees** [comment]
> adding carries to this dependency mean we need a fork at https://github.com/openshift/docker-docker and a glide.yaml update or the next glide update will revert this

yeah that's what i was afraid of.

**Comment by bparees** [comment]
/hold
(for commit text update)

**Comment by eparis** [comment]
3.9 milestone gets you near the top.   retest-not-required gets you to the very top   :)

**Comment by bparees** [comment]
> 3.9 milestone gets you near the top. retest-not-required gets you to the very top :)

which is where this should be since it could be causing some of our test flakes in the 3.9 branch (it is definitely causing them in master).

it also saves our merge queue some work retesting something for no good reason.

**Comment by liggitt** [comment]
reported upstream in https://github.com/kubernetes/kubernetes/issues/61557

**Pull request merged**
