### PR TITLE
Remove double-enabled build controllers

### LINKED ISSUE #4311: Atomic builds attempting to interact with Build / BuildConfig API endpoints
Running with the atomic-enterprise binary my logs are spammed with the following, even before deploying anything into the environment.

```
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.146977    3986 reflector.go:209] pkg/build/controller/factory/factory.go:105: Failed to watch *api.Build: the server could not find the requested resource
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.326368    3986 reflector.go:180] pkg/build/controller/factory/factory.go:69: Failed to list *api.Build: the server could not find the requested resource
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.707623    3986 reflector.go:180] pkg/build/controller/factory/factory.go:239: Failed to list *api.BuildConfig: the server could not find the requested resource
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.711134    3986 reflector.go:180] pkg/build/controller/factory/factory.go:197: Failed to list *api.Pod: the server could not find the requested resource
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.711647    3986 reflector.go:180] pkg/build/controller/factory/factory.go:166: Failed to list *api.Build: the server could not find the requested resource
Aug 21 13:36:28 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:28.713724    3986 reflector.go:180] pkg/build/controller/factory/factory.go:274: Failed to list *api.BuildConfig: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.155463    3986 reflector.go:209] pkg/build/controller/factory/factory.go:105: Failed to watch *api.Build: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.328207    3986 reflector.go:180] pkg/build/controller/factory/factory.go:69: Failed to list *api.Build: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.708608    3986 reflector.go:180] pkg/build/controller/factory/factory.go:239: Failed to list *api.BuildConfig: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.712122    3986 reflector.go:180] pkg/build/controller/factory/factory.go:197: Failed to list *api.Pod: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.712241    3986 reflector.go:180] pkg/build/controller/factory/factory.go:166: Failed to list *api.Build: the server could not find the requested resource
Aug 21 13:36:29 ose3-master.example.com atomic-openshift-master[3986]: E0821 13:36:29.714593    3986 reflector.go:180] pkg/build/controller/factory/factory.go:274: Failed to list *api.BuildConfig: the server could not find the requested resource
```

Current as of 57a09dfc7138dbbd75056f6533ea33129180d654

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #4311

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton review

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
We were testing build races.

**Comment by deads2k** [comment]
> [merge]

Wait, why didn't atomic tests catch this?

**Comment by liggitt** [comment]
> Wait, why didn't atomic tests catch this?

atomic tests don't make sure builds work... a spammy controller failure probably doesn't break anything else

**Comment by liggitt** [comment]
though I could easily see the double-enabled controller causing problems with builds... maybe our merge queue attests to that

**Comment by smarterclayton** [comment]
HAHAH just kidding

**Comment by deads2k** [comment]
> though I could easily see the double-enabled controller causing problems with builds... maybe our merge queue attests to that

@bparees

**Comment by bparees** [comment]
i doubt it, @csrwng tested multiple buildcontrollers, in fact we have integration tests that run that way.  we tolerate it as far as we know.

**Pull request merged**
