### PR TITLE
Reorganize Atomic Registry directories, test and Makefile

### PR DESCRIPTION
**Pull request by aweiteka**
* Organize deployments into subdirectories with a single test and Makefile.
* Culling some template files that are no longer required for RBAC.
* Update README files to point to upstream docs and images

### CODE REVIEW

**Comment by aweiteka** [comment]
@smarterclayton plz review/merge.

**Comment by smarterclayton** [comment]
Did you resolve the problem you had with ip?

**Comment by aweiteka** [comment]
> Did you resolve the problem you had with ip?

Yes.

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Pull request merged**
