### PR TITLE
fix jobs package import naming

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov fyi
@soltysh next time you refactor extended tests, please make sure they still compile :)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by soltysh** [comment]
@bparees ups, sorry. I was pretty sure I did check that.

**Comment by deads2k** [comment]
@bparees How long does compilation take?  We could force extended tests to compile before allowing merge.

**Comment by soltysh** [comment]
:+1: upstream does that, it shouldn't be that much.

**Comment by bparees** [comment]
@deads2k it's pretty quick, i'd be in favor of that.

**Pull request merged**
