### PR TITLE
enable daemonset

### PR DESCRIPTION
**Pull request by pweil-**
Fixing https://github.com/openshift/origin/pull/6772

For some reason my other PR got screwed up and has 0 commits

TODO: 

1.  ~~rebase~~
1.  ~~pick up var from https://github.com/openshift/origin/pull/6772#discussion_r50994762~~

### CODE REVIEW

**Comment by pweil-** [comment]
[test][extended:core]

**Comment by pweil-** [comment]
manual e2e run since the jenkins is flaky:


```
[vagrant@openshiftdev origin]$ sudo -E test/extended/core.sh --ginkgo.focus="Daemon set"
Note: checking out '4a65fa1'.
... snip...
=== RUN "Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/daemon_set.go":
I0127 19:41:42.545755    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
I0127 19:41:46.690584    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
I0127 19:41:46.693220    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
    ok       Daemon set should run and stop simple daemon (24.222506034s)
=== RUN "Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/daemon_set.go":
I0127 19:42:06.767642    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
I0127 19:42:10.788538    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
I0127 19:42:10.789086    9136 loader.go:241] Config loaded from file /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig
    ok       Daemon set should run and stop complex daemon (16.095523015s)

... snip ...
```

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
Assuming this last test run is green, folks are ok with my manual extended test, and there are no other comments this should be ready for merging.

**Comment by smarterclayton** [comment]
[test]

**Comment by pweil-** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM, can you also enable the daemonset e2e tests?

**Comment by deads2k** [comment]
> LGTM, can you also enable the daemonset e2e tests?

Looks like that's already been done.  [merge]

**Comment by smarterclayton** [comment]
They're not enabled, they're in the skip list.  You have to remove them from the skip list

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/6854/files#diff-de146235e94f07b029f91b2603d00a54L56

**Comment by pweil-** [comment]
For `DaemonRestart` (if that's what you're referring to) we should be able to enable that one after the next rebase since https://github.com/kubernetes/kubernetes/issues/19023 and https://github.com/kubernetes/kubernetes/issues/17829 are now closed

**Comment by smarterclayton** [comment]
K

**Pull request merged**
