### PR TITLE
Add quota controller metrics

### PR DESCRIPTION
**Pull request by deads2k**
Adds metrics to the clusterquota controller so we can see what's running slow in the HA env.

@liggitt can you help me with magic incantation to get a dev ami?

### CODE REVIEW

**Comment by liggitt** [comment]
building in https://ci.openshift.redhat.com/jenkins/job/fork_ami/273/parameters/

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
re[test]

**Comment by danmcp** [comment]
@deads2k bumped instance size and setup ram disk since it hadn't been added there yet: https://ci.openshift.redhat.com/jenkins/job/fork_ami/274/

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/fork_ami/276/ is going to be the one, I can feel it!

**Comment by deads2k** [comment]
upstream is going in. [merge]

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by deads2k** [comment]
@stevekuznetsov all my ami builds have failed on this: https://ci.openshift.redhat.com/jenkins/job/fork_ami/276/consoleFull#-81879505056be39f6e4b05b79524e57bd

**Pull request merged**
