### PR TITLE
e2e: run router header test on AWS/GCP/Azure only

### PR DESCRIPTION
**Pull request by frobware**
This is a follow-up to https://github.com/openshift/origin/pull/24093 which breaks (or flakes on) OpenStack.

Rather than trying to run down all the flakes on all the platforms in
4.3 I've changed the router header test to run against the following
platforms only:

- AWS
- Azure
- GCP

A new BZ[1] has been opened to ensure that the other platforms are not
forgotten.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1772125

### CODE REVIEW

**Comment by ironcladlou** [comment]
To avoid doing anything at all on those platforms (and also providing output about the skipping),  I believe you can add a `g.Skip()` call during a platform check added to `g.BeforeEach()`

**Comment by frobware** [comment]
> To avoid doing anything at all on those platforms (and also providing output about the skipping), I believe you can add a `g.Skip()` call during a platform check added to `g.BeforeEach()`

Done in https://github.com/openshift/origin/pull/24145/commits/0e40910ff426967a37505acf618ff8b9401f0382

**Comment by mandre** [comment]
Thanks for looking into it. LGTM.

**Comment by ironcladlou** [comment]
Thanks!

/lgtm

**Pull request merged**
