### PR TITLE
Enable FSGroup in restricted and hostNS SCCs

### PR DESCRIPTION
**Pull request by pmorie**
Making this WIP PR to do some CI testing while we finish manually testing this.

cc @pweil- @bparees @smarterclayton

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
[test]

**Comment by ironcladlou** [comment]
cc @dgoodwin

**Comment by smarterclayton** [comment]
Have we fixed the other impacts of this in postgres?  Will we need a release warning for 1.2?

**Comment by pmorie** [comment]
@smarterclayton We have fixed postgres, and there will be a migration for the oldest data sets that might have an issue with it.  We will need release notes.

**Comment by pmorie** [comment]
[test]

earlier failures due to etcd flake

**Comment by pmorie** [comment]
@bparees am I doing the extended directives wrong?

**Comment by bparees** [comment]
@pmorie I think you want:
[testonlyextended][extended:core(FSGroup),core(postgresql),core(mysql),core(mongodb)]

(it'll work with the test tag too, but i don't want this to run all the test, and you'll have to clean up your existing test tag)

**Comment by pmorie** [comment]
@bparees RFE: [test:help]

**Comment by pmorie** [comment]
[testonlyextended][extended:core(FSGroup)]

@bparees can you remove your comment?  I want to get a clean test run on just fsgroup tests, and I will post test results for manual tests for the extended image tests.

**Comment by bparees** [comment]
@pmorie done. no good deed goes unpunished.

**Comment by bparees** [comment]
@pmorie done. no good deed goes unpunished.

**Comment by pmorie** [comment]
@bparees I sentence you to watch all red squad episodes of later-day star trek

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@smarterclayton @pweil- @bparees I think this should be merged.  I've tested postgresl, mongo, and mysql, run the extended e2es, etc.  The postgresql replication e2e failed, looks unrelated, and that test is on the flaky list anyway.

**Comment by pweil-** [comment]
Based on the email discussion saying that manual tests with a plan to revert is fine, I agree.  @pmorie stand by the big red revert button in case of disaster.

[merge]

**Comment by pmorie** [comment]
[test]

**Comment by smarterclayton** [comment]
Seeing some flakiness in some FS tests, not sure it's this but some investigation would be good https://ci.openshift.redhat.com/jenkins/job/origin_extended/710/testReport/

**Comment by pmorie** [comment]
@smarterclayton It looks like the flakes in question aren't in the tests themselves but the `JustBeforeEach` section:

```
EmptyDir volumes [JustBeforeEach]
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/empty_dir.go:113
  when FSGroup is specified [Feature:FSGroup]
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/empty_dir.go:56
    volume on tmpfs should have the correct mode using FSGroup
    /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/empty_dir.go:55

    Mar  6 13:59:26.374: rolebindings "view" is forbidden: Namespace e2e-tests-job-irun4 is terminating
```

...but I'll keep an eye out and do some more checks myself.

**Comment by liggitt** [comment]
@marun ^^

**Comment by marun** [comment]
@liggitt Would it make sense to add an error handler around the role addition to ignore errors related to namespace termination?

**Comment by liggitt** [comment]
I would skip the namespace if it is terminating, and log but tolerate failing the role addition

**Pull request merged**
