### PR TITLE
hack/env should support incremental rsync to the container

### PR DESCRIPTION
**Pull request by smarterclayton**
Falls back to tar. Preparation for CI testing from release images

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Networking tests no longer work against release-1.3 because of networking-minimal.sh change.  @knobunc can you get someone to create a patch to 1.3 for that.

**Comment by knobunc** [comment]
@marun can you please take a look at the issue @smarterclayton raised about the networking-minimal.sh change.  Thanks.

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
