### PR TITLE
don't lowercase metric labels

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/unassign @mfojtik 

@gabemontero, @smarterclayton asked that we not lowercase this stuff and just use the constants as is instead. ptal and let me know if there's anywhere else i probably need to touch.

@jim-minter are we lowercasing anything in template metrics?  it didn't look like it, but if we are point me in the right direction and i'll include it in this PR.

**Comment by gabemontero** [comment]
the build prometheus extended test will need some updates as well @bparees

**Comment by bparees** [comment]
@gabemontero updated.

**Pull request merged**
