### PR TITLE
Ignore node created self targeting mirror pods in PodNodeConstraints

### PR DESCRIPTION
**Pull request by enj**
This change updates the PodNodeConstraints admission plugin to ignore mirror pods that are created by a node with PodSpec.NodeName that matches the given node's name.

Thus nodes are allowed to create mirror pods that target themselves.

The NodeRestriction plugin continues to guarantee that nodes can only create and delete mirror pods that target themselves.  These mirror pods are also prevented from referencing any API objects.

Bug 1579605

Signed-off-by: Monis Khan <mkhan@redhat.com>

/kind bug
/assign @simo5 @liggitt
@openshift/sig-security @openshift/sig-master

### CODE REVIEW

**Comment by cucushift** [comment]
>This change updates the PodNodeConstraints admission plugin to ignore mirror pods that are created by a node with PodSpec.NodeName that matches the given node's name.
hi mo, `pods created by node` does it mean using `/etc/origin/node/node.kubeconfig` ?

**Comment by enj** [comment]
> hi @enj , pods created by node does it mean using /etc/origin/node/node.kubeconfig to create pods?

More specifically it is a user whose name starts with `system:node:` and is in the `system:nodes` group.

**Comment by cucushift** [comment]
@enj thanks.

**Pull request merged**
