### PR TITLE
[AUTO][OLM][OCP-24057] Check OLM pods termination message should be "FallbackToLogsOnError"

### PR DESCRIPTION
**Pull request by bandrade**
PR Created to automate test case: @ecordell @njhale @kevinrizza. please have a review. Thanks! cc: @cuipinghuo @scolange @chengzhang1016 @emmajiafan @jianzhangbjz @tbuskey

Success execution evidence:
```
./openshift-tests run all --dry-run | grep "Have terminationMessage" | ./openshift-tests run -f -

I1226 05:20:06.506364   19393 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
I1226 05:20:08.070638   19400 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
started: (0/1/1) "[Feature:Platform] OLM should Have terminationMessagePolicy defined as FallbackToLogsOnError [Suite:openshift/conformance/parallel]"

I1226 05:20:25.734686   19834 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
Dec 26 05:20:25.777: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Dec 26 05:20:26.236: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Dec 26 05:20:26.792: INFO: 0 / 0 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Dec 26 05:20:26.792: INFO: expected 0 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Dec 26 05:20:26.792: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
Dec 26 05:20:26.969: INFO: e2e test version: v0.0.0-master+$Format:%h$
Dec 26 05:20:27.119: INFO: kube-apiserver version: v1.17.0
Dec 26 05:20:27.290: INFO: Cluster IP family: ipv4
[BeforeEach] [Top Level]
  /home/bandrade/go/src/github.com/openshift/origin/test/extended/util/test.go:60
[BeforeEach] [Feature:Platform] OLM should
  /home/bandrade/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:154
STEP: Creating a kubernetes client
[It] Have terminationMessagePolicy defined as FallbackToLogsOnError [Suite:openshift/conformance/parallel]
  /home/bandrade/go/src/github.com/openshift/origin/test/extended/operators/olm.go:150
Dec 26 05:20:27.332: INFO: Running 'oc --namespace=openshift-operator-lifecycle-manager --config=/home/bandrade/QE/ocp4-aws-ipi-vagrant-4.4/cluster/auth/kubeconfig get pods -o=jsonpath={range .items[*].spec}{.containers[*].name}{"  "}'
Dec 26 05:20:28.808: INFO: Running 'oc --namespace=openshift-operator-lifecycle-manager --config=/home/bandrade/QE/ocp4-aws-ipi-vagrant-4.4/cluster/auth/kubeconfig get pods -o=jsonpath={range .items[*].spec}{.containers[*].terminationMessagePolicy}{"t"}'
Dec 26 05:20:29.943: INFO: Counters: %!s(int=4) %!s(int=4)
[AfterEach] [Feature:Platform] OLM should
  /home/bandrade/go/src/github.com/openshift/origin/test/extended/util/client.go:120
[AfterEach] [Feature:Platform] OLM should
  /home/bandrade/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:155
Dec 26 05:20:29.944: INFO: Waiting up to 7m0s for all (but 100) nodes to be ready
Dec 26 05:20:30.351: INFO: Running AfterSuite actions on all nodes
Dec 26 05:20:30.351: INFO: Running AfterSuite actions on node 1

passed: (22.3s) 2019-12-26T08:20:30 "[Feature:Platform] OLM should Have terminationMessagePolicy defined as FallbackToLogsOnError [Suite:openshift/conformance/parallel]"

1 pass, 0 skip (22.3s)

```

### CODE REVIEW

**Comment by bandrade** [comment]
We have a test case for this and we run on most of test runs manually so I think it's reasonable to have automation for that.

**Comment by jianzhangbjz** [comment]
@shawn-hurley Could you help review it and give approve? Thanks!

**Comment by bandrade** [comment]
Closing since it has merged in https://github.com/openshift/openshift-tests/pull/19

**Pull request closed without merging**
