### PR TITLE
Drop docker-in-docker dev cluster support

### PR DESCRIPTION
**Pull request by danwinship**
This has been broken since `openshift start` went away
/cc @dcbw

### CODE REVIEW

**Comment by danwinship** [comment]
/assign @soltysh 
since he's the one who killed off "openshift start"
(no one was ever using this except the networking team, and we're not using it since 3.x)

**Comment by deads2k** [comment]
/approve

needs rebase

**Comment by AkihiroSuda** [comment]
What's the alternative to this now?

**Pull request merged**
