### PR TITLE
Wait for the builder service account to get registry secrets in extended tests

### PR DESCRIPTION
**Pull request by mfojtik**
@bparees FYI I hope that this should fix the authentication error when pushing to internal Docker registry. Andy pointed me to end-to-end test where we are doing the same (but using `oc` command ;-).

@ncdc PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
[test][extended:all]

**Comment by mfojtik** [comment]
@bparees OK, so this won't fix the problem :-( I can still see the authentication error, but it is random....

**Comment by liggitt** [comment]
do you have an example of the auth error?

**Comment by liggitt** [comment]
also, this feels like the sort of thing we'd want in a beforeEach

**Comment by mfojtik** [comment]
@bparees which is strange, because this PR will make sure that builder has the secrets it needs for pushing to internal registry.

@liggitt yes:

```console
I0824 13:25:12.275614       1 cfg.go:44] Locating docker auth for image 172.30.229.84:5000/extended-test-build-sti-env-uo3pd/test:latest and type PUSH_DOCKERCFG_PATH
I0824 13:25:12.275697       1 cfg.go:52] Problem accessing /root/.docker/config.json: stat /root/.docker/config.json: no such file or directory
I0824 13:25:12.275725       1 sti.go:151] Pushing 172.30.229.84:5000/extended-test-build-sti-env-uo3pd/test:latest image ...
F0824 13:25:16.087713       1 builder.go:47] Build error: Failed to push image: Error pushing to registry: Authentication is required.
```

**Comment by mfojtik** [comment]
@liggitt true, but apparently it is not causing this problem... I think service account is fast enough to be populated (but the helper is good to have anyway just to make sure ;-)

**Comment by mfojtik** [comment]
@liggitt the "Problem accessing..." error is random. For some builds (same build parameters) it works and for some it fails.

**Comment by liggitt** [comment]
The presence of the secret is one thing to check. When is the registry getting created? The generated dockercfg secrets get updated after the registry service resolves to a particular IP...

**Comment by mfojtik** [comment]
@liggitt the registry is created before we start the tests.

**Comment by liggitt** [comment]
ok

**Comment by mfojtik** [comment]
@liggitt https://github.com/openshift/origin/blob/master/hack/test-extended/default/run.sh#L44

**Comment by liggitt** [comment]
can you see the pod definition for a failed build and see if it had the docker secret mounted?

**Comment by mfojtik** [comment]
@liggitt I have to make it fail again... but for some reason the tests are passing for me now...

btw. I refactored this PR to be `JustBeforeEach`... I think we can merge this one

**Comment by bparees** [comment]
lgtm [merge]

**Comment by bparees** [comment]
lgtm [merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
