### PR TITLE
Fixes filename completion

### PR DESCRIPTION
**Pull request by fabianofranz**
Not bumping spf13/cobra now since it contains wider changes, but this cherry-picked fix is important. Pretty much filename completions is broken.

@openshift/team-project-committers this should get in.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Filename completions aren't a regression, and aren't critical path.  Are regular completions broken?

**Comment by fabianofranz** [comment]
@smarterclayton No, it's just filename completions.

**Comment by eparis** [comment]
I have a hard time justifying this strongly for 3.1 at this point but it is a 3.0 v 3.1 regression. It works in 3.0.

**Comment by liggitt** [comment]
it's been annoying me for weeks but I hadn't debugged it yet

**Comment by smarterclayton** [comment]
@jwforres from an experience perspective is this important enough to risk a
break?

**Comment by jwforres** [comment]
@smarterclayton Its pretty irritating in its current state... i would lean on the putting it in side since the changeset doesn't seem that large

**Comment by jwforres** [comment]
@fabianofranz tested on windows?

**Comment by fabianofranz** [comment]
@jwforres we only provide bash completions, I don't think they work on Windows.

**Comment by jwforres** [comment]
@fabianofranz just meant, you've tested the binaries from the current build that would contain this change, unless these packages just dont even get built into the windows binaries?

**Comment by fabianofranz** [comment]
@jwforres got it, let me test real quick.

**Comment by jwforres** [comment]
yep just a sanity check

/me is paranoid

**Comment by fabianofranz** [comment]
@jwforres contrib doesn't go into the binaries, but Cobra does. I just tested on Win10, all good.

**Comment by smarterclayton** [comment]
Approved

**Comment by fabianofranz** [comment]
:+1:

**Comment by jwforres** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
