### PR TITLE
UPSTREAM: 33141: don't mutate original TLS config

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test][extended:networking]

**Comment by danwinship** [comment]
> [test][testextended][extended:networking]

extended networking tests are disabled in master (it just does "echo FIXME; exit 0") and need other fixes beyond this one; I just filed #11039 with all the fixes plus the patch to reenable the tests, and kicked off a test run there

**Comment by liggitt** [comment]
upstream has LGTM, networking test in https://github.com/openshift/origin/pull/11039 passed, [merge]

**Comment by danwinship** [comment]
extended networking tests passed on #11039: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/9083/

**Pull request merged**
