### PR TITLE
bump(github.com/coreos/etcd):v3.1.0

### LINKED ISSUE #13215: Godep.json contains two etcd versions
Current master a86ef13e1e70f9b74ae2b41e392b4f4a61db8e46 has two versions of etcd:
```
$ jq -r '.Deps[] | select(.ImportPath | startswith("github.com/coreos/etcd")) | .Rev' Godeps/Godeps.json | sort -u
83347907774bf36cbb261c594a32fd7b0f5dd9f6
8ba2897a21e4fc51b298ca553d251318425f93ae
```

It breaks godep restore:
```
$ ./hack/godep-restore.sh 
HEAD is now at e36e043... Fix doc version
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
fatal: remote github.com/openshift-remote already exists.
HEAD is now at 07b16b6... Merge pull request #121 from KevinMGranger/fix/url_prefix_slash
HEAD is now at bd3c8e8... Add extra methods to control the number of times a call is expected.
HEAD is now at eb47ba8... metadata: use ctxhttp to support cancelation in Go 1.4
Starting to download all godeps. This takes a while
godep: error restoring dep (github.com/coreos/etcd/integration): Wanted to restore rev 83347907774bf36cbb261c594a32fd7b0f5dd9f6, already restored rev 8ba2897a21e4fc51b298ca553d251318425f93ae for another package in the repo
godep: error restoring dep (github.com/coreos/etcd/proxy/grpcproxy): Wanted to restore rev 83347907774bf36cbb261c594a32fd7b0f5dd9f6, already restored rev 8ba2897a21e4fc51b298ca553d251318425f93ae for another package in the repo
godep: error restoring dep (github.com/coreos/etcd/proxy/grpcproxy/cache): Wanted to restore rev 83347907774bf36cbb261c594a32fd7b0f5dd9f6, already restored rev 8ba2897a21e4fc51b298ca553d251318425f93ae for another package in the repo
godep: Error restoring some deps. Aborting check.
[ERROR] PID 14092: hack/godep-restore.sh:77: `"${GODEP}" restore` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/godep-restore.sh:77: `"${GODEP}" restore`
[INFO]   Exiting with code 1.
```

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #13215. This is a followup to #12600. 

@smarterclayton mind taking a look, you've bumped etcd but missed these 3 dirs, was that intentionally or this needs to go in?

@legionus @dmage fyi
@ncdc fyi, for the next rebase

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by smarterclayton** [comment]
We don't use grpc proxy, and we don't run their integration tests.  Was this just what an automated restore created?

**Comment by soltysh** [comment]
> We don't use grpc proxy, and we don't run their integration tests. 

We explicitly no, but k8s uses integration which then brings grpc see [here](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go#L39).

> Was this just what an automated restore created?

It currently fails during `hack/godep-restore.sh`, unfortunately `hack/godep-save.sh` is not working due to at least one of upstream patches that added `pkg/util/version` from 1.6 which is not available in 1.5. So this is rather half manual, half automated process to make sure we have restorable godeps, which will be needed for the next rebase.

**Comment by smarterclayton** [comment]
I'm fine with adding them.

On Mar 3, 2017, at 3:51 PM, Maciej Szulik <notifications@github.com> wrote:

We don't use grpc proxy, and we don't run their integration tests.

We explicitly no, but k8s uses integration which then brings grpc see here
<https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go#L39>
.

Was this just what an automated restore created?

It currently fails during hack/godep-restore.sh, unfortunately
hack/godep-save.sh is not working due to at least one of upstream patches
that added pkg/util/version from 1.6 which is not available in 1.5. So this
is rather half manual, half automated process to make sure we have
restorable godeps, which will be needed for the next rebase.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/13216#issuecomment-284066745>,
or mute
the thread

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
