### PR TITLE
Bug 1882030: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison

### PR DESCRIPTION
**Pull request by damemi**
4.6 PR: https://github.com/openshift/kubernetes/pull/318

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by markmc** [comment]
(patch manager) important performance fix for issue seen by real-world users; relatively low risk given the review and testing it has had

**Pull request merged**
