### PR TITLE
update watch-endpoint-slices to usable shape

### PR DESCRIPTION
**Pull request by deads2k**
The openshift-tests image in payloads doesn't include the latest origin changes.  This means we have to get the `watch-endpoint-slices` working in its final shape before we can enable it.

This PR
1. updates how backend-disruption.json determine aggregated keys for historical data
2. a soft-stop for watch-endpoint-slices to ease collection
3. per-node monitor.interval so we can track exactly which nodes to check
4. only sample endpoints that are currently serving

### CODE REVIEW

**Review by dgoodwin — COMMENTED** [review]
/lgtm
/hold

Held pending your test PR results.

Job runs look correct, data file is as we'd expect, runs with multiple disruptions are getting grouped as they were before and showing properly in spyglass as well.

**Comment by deads2k** [comment]
/override ci/prow/e2e-aws-ovn-fips

ifnra, proof passed.

**Comment by deads2k** [comment]
followups committed.

**Comment by deads2k** [comment]
/override ci/prow/e2e-aws-ovn-serial 

passed

**Comment by deads2k** [comment]
nothing merged in the interim. merging

**Pull request merged**
