### PR TITLE
Bug 1343426: list deployments correctly in oc deploy

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik @ironcladlou 

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1343426

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
[merge]

(yum flake)

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/5448 flaked 

[merge]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
