### PR TITLE
add more e2e-cmd

### PR DESCRIPTION
**Pull request by deads2k**
builds on https://github.com/openshift/origin/pull/23432 to free more tests

### CODE REVIEW

**Comment by deads2k** [comment]
starting point we agreed to in slack to get back our test-cmd tests.

**Comment by deads2k** [comment]
We have a chicken and egg issue with https://github.com/openshift/origin/pull/23452 .  it touches test-cmd, but this won't pass aws-builds without it.  If everything else is green, we could consider merging over it.

**Comment by adambkaplan** [comment]
/hold

@mfojtik need https://github.com/openshift/origin/pull/23452 to land first, unblocks e2e-aws-builds

**Comment by deads2k** [comment]
> /hold
> 
> @mfojtik need #23452 to land first, unblocks e2e-aws-builds

This blocks bringing in hundreds of CLI, controller, and server tests.  Are you sure we cannot merge past a known broken builds issue?

**Comment by adambkaplan** [comment]
/hold cancel

per conversation with @deads2k , will drop `test-cmd` changes in #23452

**Comment by deads2k** [comment]
no conflict with https://github.com/openshift/origin/pull/23451/files , tested green one commit back.  Current batch failed.  Merging to so we can get back these several hundred tests.

**Comment by deads2k** [comment]
opened https://bugzilla.redhat.com/show_bug.cgi?id=1732860

**Pull request merged**
