### PR TITLE
OpenStack: Restore in-tree cinder provisioner tests

### PR DESCRIPTION
**Pull request by mandre**
This reverts commit 43284bbffa7f410b210214d2d3ce6692a1b75e76.

### CODE REVIEW

**Comment by mandre** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27789/pull-ci-openshift-origin-master-e2e-openstack-ovn/1634104275875401728 shows that all the `\[sig-storage\].*\[Driver: cinder\]` tests passed. It should be good to merge.

@soltysh if you could take a look. This reverts https://github.com/openshift/origin/pull/27613 that you reviewed.

/assign @soltysh

**Comment by jsafrane** [comment]
/lgtm
from storage POV

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
