### PR TITLE
Fix jenkins plugin hang

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

the wait used to work when jenkins was in a separate project which we deleted before this point .. the project delete would terminate jenkins

now that we are deferring project delete, we cannot depend on that for the `oc logs dc/jenkins -f` ... but we can just kill that when we are done and dump the data we got

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/retest
/hold
(holding because i don't know if imageeco is actually blocking currently or not...i think it is)

**Comment by gabemontero** [comment]
OK, the jenkins tests passed, and the durations were back to the previous norm (typically 3 to 4 minutes).

The 2 tests that failed are mongodb related ... perhaps the flakes @coreydaley has been chasing.

Will start to triage

**Comment by bparees** [comment]
/hold

This is going to keep failing until image eco is fixed. Best solution is to
update this pr to move the test back into build. That will hopefully also
clear the image eco run. If that doesn't work you may need to reopen the pr
after moving the test.


Ben Parees | OpenShift

**Comment by gabemontero** [comment]
test moved back to test/extended/builds @bparees

**Comment by gabemontero** [comment]
Forgot to change the describe label ...jenkins_plugin.go did not run

Will update momentarily

**Comment by gabemontero** [comment]
ginkgo describe text updated @bparees - mirrors what we have in pipeline.go - please re-label the PR at your convenience

**Comment by gabemontero** [comment]
still running image_eco ... I'll close / reopen after the current test run completes

**Comment by gabemontero** [comment]
The jenkins_plugins.go tests are running right now ... the first one completed in the expected amount of time

**Comment by bparees** [comment]
I don't see image_eco in the list of tests being run...I think that test report is just cumulative.  should be ok as is.

**Comment by gabemontero** [comment]
ah .. yep you are right re: image_eco and an old run

**Comment by gabemontero** [comment]
And all the jenkin_plugin.go tests passed and their durations were all in single digit minute durations

**Comment by gabemontero** [comment]
gcp hit flake https://github.com/openshift/origin/issues/19058 this time

**Comment by gabemontero** [comment]
gcp Stage PROVISION CLOUD RESOURCES [00h 00m 37s] failed.

**Pull request merged**
