### PR TITLE
Image api cleanup

### PR DESCRIPTION
**Pull request by ncdc**
Remove json tags from internal API.

Remove ImageRepository*.

Remove TagReference.DockerImageReference from internal.

Make Image its own field instead of being embedded for ImageStreamTag
and ImageStreamImage. Remove ImageName as it's now available at
Image.Name.

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton 

I haven't updated swagger yet because it's easier to wait until your PR merges to avoid the conflicts.

**Comment by ncdc** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by ncdc** [comment]
@smarterclayton gah Jordan already deleted the comment, ha. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/2862/ is the run that's about to finish up.

**Comment by smarterclayton** [comment]
Refactoring large chunks of our code right before release shows determination, grit, and not a small amount of lunacy.  I salute you, sir!  

[merge]

**Pull request merged**
