### PR TITLE
remove cluster up cruft

### PR DESCRIPTION
**Pull request by deads2k**
Removes unnecessary code from cluster up.

@mfojtik As I recall, remote docker support was removed in 3.10.  This assumes that is gone.  I also remember that we made the decision to only support linux and that other platforms would have to use VMs because the kubelet only supports linux.  This deletes code that existed to support those platforms and use-cases.

This also removes `oc cluster status`.  That command was pulling config information that hasn't existed in multiple releases, so it wasn't functioning properly anyway, no one complained, and it's value is dubious.

/assign @mfojtik

### CODE REVIEW

**Comment by bparees** [comment]
>  This also removes oc status. That command was pulling config information that hasn't existed in multiple releases, so it wasn't functioning properly anyway, no one complained, and it's value is dubious.

it is used in https://github.com/openshift/origin/blob/master/hack/test-end-to-end-docker.sh#L79 which I am in the process of re-enabling since your disabling of it allowed the registry to regress.

So if you want to strip the function down, fine, but don't delete it unless you're going to fix test-end-to-end-docker.sh properly.

/hold

**Comment by bparees** [comment]
my effort to re-enable it is here: https://github.com/openshift/origin/pull/21040

**Comment by deads2k** [comment]
> it is used in https://github.com/openshift/origin/blob/master/hack/test-end-to-end-docker.sh#L79 which I am in the process of re-enabling since your disabling of it allowed the registry to regress.
> 
> So if you want to strip the function down, fine, but don't delete it unless you're going to fix test-end-to-end-docker.sh properly.
> 
> /hold

This doesn't do what you think it does.  Since 3.10, this simply returns whether the kube-apiserver is up.  It gives no report of the actual status of the cluster, since the openshift control plane isn't checked.

`oc cluster status` never reported valuable health.  If you really want that level of "check", you can use `oc get --raw /heathz` instead.

/hold cancel.

**Comment by mfojtik** [comment]
I agree with David, to check if cluster is up you should either use `/healthz` or `oc wait`. 
We might re-add `cluster status` but I guess it will report something similar as CVO operator status.

/lgtm

**Pull request merged**
