### PR TITLE
e2e - Dump State for Prometheus

### PR DESCRIPTION
**Pull request by adambkaplan**
Dump Prometheus pod state and logs on prometheus builds failure.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@bparees @stevekuznetsov think this one may need to be hand-merged. `e2e-aws-image-ecosystem` and `e2e-aws-all` should be skipped, but are not.

**Comment by bparees** [comment]
@stevekuznetsov let me know when you're done triaging this PR

**Comment by bparees** [comment]
(I got a pass on image eco over here: https://github.com/openshift/builder/pull/42 so maybe it'll manage to pass here too.  but it still shouldn't be getting triggered).

**Comment by bparees** [comment]
passed aws-builds which is the only thing this affects.  merging.

**Pull request merged**
