### PR TITLE
Tolerate NotFound on delete, remove roles on policybinding deletion

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1468629

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge][severity:blocker]

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
