### PR TITLE
fixup coreos dep bump

### PR DESCRIPTION
**Pull request by sjenning**
@eparis @liggitt 

https://github.com/openshift/origin/commit/e20b7480b71d75bc7d165bef35e0788009cc4e0f did not update Godeps.json

### CODE REVIEW

**Comment by eparis** [comment]
[merge]

**Comment by eparis** [comment]
why are you not [merge]ing?

**Comment by mfojtik** [comment]
@sjenning @eparis the commit message must be `bump(...` in order to fix this... in this case bump the coreos even though we are not really bumping it.

Also are we sure the coreos we have in godeps is the version you're bumping it here? The coreos was bumped to match kube level during the rebase.

**Comment by eparis** [comment]
[merge] sucka

**Comment by ncdc** [comment]
Assuming this is the correct hash, can we just click the Merge button?

**Comment by sjenning** [comment]
@mfojtik yes, i verified that the code for coreos/etcd in the deps does, in fact, match that upstream commit id.  @ncdc fine by me!

**Comment by mfojtik** [comment]
@ncdc I think we can :-)

**Comment by ncdc** [comment]
Ok I'm happy to click the button assuming @smarterclayton and @danmcp don't object

**Comment by eparis** [comment]
let 'em yell at me.

**Comment by smarterclayton** [comment]
Please don't self merge, it means we don't get AMIs built and QE doesn't get notifications.

**Comment by smarterclayton** [comment]
Self merge is reserved for repo broken / release process stuff.

**Comment by ncdc** [comment]
This is "repo broken" for Godep use.

**Comment by eparis** [comment]
and we don't need AMIs or QE   :)

**Comment by smarterclayton** [comment]
From one of the test runs - is this related?

```
can't load package: package github.com/coreos/etcd/cmd: cannot find package "github.com/coreos/etcd/cmd" in any of:
	/usr/lib/golang/src/github.com/coreos/etcd/cmd (from $GOROOT)
	/data/src/github.com/coreos/etcd/cmd (from $GOPATH)
!!! Error in hack/install-etcd.sh:33
	'./build' exited with status 1
Call stack:
```

**Comment by smarterclayton** [comment]
On master, right now:

```
○ hack/install-etcd.sh
can't load package: package github.com/coreos/etcd/cmd: cannot find package "github.com/coreos/etcd/cmd" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/coreos/etcd/cmd (from $GOROOT)
	/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/cmd (from $GOPATH)
	/Users/clayton/projects/origin/src/github.com/coreos/etcd/cmd
!!! Error in hack/install-etcd.sh:33
	'./build' exited with status 1
Call stack:
	1: hack/install-etcd.sh:33 main(...)
Exiting with status 1
```

**Comment by smarterclayton** [comment]
Reverted.

**Pull request merged**
