### PR TITLE
remove use_local env

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
should have been removed in my PR to remove this function... this variable does nothing anymore.

@smarterclayton ptal.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
also removed the --latest-images flag since that's what the --images value is defaulting to...  can't image why we'd want both of those set.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
