### PR TITLE
UPSTREAM: 45286: When pods are terminated we should detach the volume

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1446788

### CODE REVIEW

**Comment by gnufied** [comment]
[test]

**Comment by smarterclayton** [comment]
Are there ansible changes planned to set this annotation?

**Comment by gnufied** [comment]
@smarterclayton there are no ansible change necessary to set this annotation. The annotation solely exists to make sure if *at all* kubelet was started with `keep-terminated-pod-volumes` option, controller honours it too. 

We are going to deprecated that flag. https://github.com/kubernetes/kubernetes/issues/45615 
Also by default that flag is not set in kubelet. It was an oversight on our part to introduce such a flag in first place.

**Comment by eparis** [comment]
please don't set the annotation. ever. period. no.

**Comment by childsb** [comment]
[merge]

**Comment by smarterclayton** [comment]
Two unrelated flakes [test]

**Comment by eparis** [comment]
[test] https://github.com/openshift/origin/issues/10773

**Comment by smarterclayton** [comment]
[merge] flake on oc get frontend pods in 60s

**Pull request merged**
