### PR TITLE
Automated cherry pick of #15213 #16219 #16340 #17080 #18221 on release-3.6

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #15213 #16219 #16340 #17080 #18221 on release-3.6.

#15213: Not found errors must match object in migration
#16219: Use discovery based version gating for policy commands
#16340: Decrement retries count during migration
#17080: Correctly handle NotFound errors during migration
#18221: Fix issues with oc adm migrate authorization

### CODE REVIEW

**Comment by enj** [comment]
/assign @simo5 @mrogers950 

Well, this was painful.

I know the shell based tests in d970765b25c59d3fb5127266a0e2403426fca5fb need to be fixed since they should not fail with a 3.6 server.  Otherwise this is ready for a review.

**Comment by simo5** [comment]
Are there any major changes I should look into compared to the master version ?

**Comment by enj** [comment]
@simo5 @mrogers950 the main difference is that these commands were not deprecated in 3.6, so they can still be run without issue.  Just take a look at the diff as a whole and confirm that it does not violate expectations for 3.6.  Overall the patches applied pretty cleanly once I figured out everything that was needed.

**Comment by simo5** [comment]
I do not see any blatant violation, I had to think on the gating but it seem reasonable to backport.

**Comment by enj** [comment]
Closing since 3.6 CI is broken.

**Pull request closed without merging**
