### PR TITLE
Strip build tags from integration, they are not needed

### PR DESCRIPTION
**Pull request by smarterclayton**
@liggitt follow up from rebase, we don't need tags because we can either a) fail the tests (what this PR does) or b) skip the test if docker can't be connected to.  For now, just going with fail.

One step closer to being a standard build / test.

[test]

### CODE REVIEW

**Comment by liggitt** [comment]
all the test files need gofmt

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@sosiouxme TestClusterResourceOverridePluginWithLimits is failing (we weren't running it before) - if you can help me debug I'd appreciate it

**Comment by smarterclayton** [comment]
@derekwaynecarr review last commit then i'm going to merge

**Comment by smarterclayton** [comment]
[test]

**Comment by sosiouxme** [comment]
When I tried TestClusterResourceOverridePluginWithLimits from your branch it worked... Did you fix it? In https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3503/consoleFull it appeared that the clusterresourceoverride admission controller was disabled, but I couldn't see how.

**Comment by smarterclayton** [comment]
Yes, I fixed it early this afternoon (by setting nil action, rather than
empty action).

The controller was previously disabled because it required the "etcd" build
flag which we never set.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
