### PR TITLE
install ceph-common pkg on origin to support rbd provisioning

### PR DESCRIPTION
**Pull request by rootfs**
fixing https://bugzilla.redhat.com/show_bug.cgi?id=1411244
@sdodson

### CODE REVIEW

**Comment by sdodson** [comment]
@rootfs is there a reasonable way to install the contents of ceph-common on the non RPM based image (Dockerfile)?

**Comment by sdodson** [comment]
Hmm, I think we should add a yum step to install it in Dockerfile too, I'm not certain of the distinction between Dockerfile and Dockerfile.centos. @tdawson may be able to help

**Comment by rootfs** [comment]
@sdodson Haven't tried other os dist yet. 

I am open to any directions. The fix is a convenient addition to current yum install. If additional yum step is provided, I'll add to it.

**Comment by sdodson** [comment]
Looking at images/base/Dockerfile which this image builds atop it's already got yum transactions so I think we're already relying on yum for the entire image set. I'd say lets go ahead and add ceph-common to images/origin/Dockerfile too, you'd basically copy the entire yum block from Dockerfile.centos7 but drop origin from INSTALL_PKGS

**Comment by rootfs** [comment]
@sdodson updated

how about node image? It has ceph-common now but if base has ceph-common, node image can skip it.

**Comment by sdodson** [comment]
@rootfs Yeah I guess since we have xfsprogs and e2fsprogs in base lets move it all into base image and remove from node, please add it to the other Dockerfiles in base too.

**Comment by rootfs** [comment]
@sdodson added to other base and removed from node.

**Comment by rootfs** [comment]
@sdodson can you merge it? OSE 3.5 still doesn't have the fix. Thanks

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
@rootfs I lack permissions. @childsb can you merge?

**Comment by jsafrane** [comment]
[merge]

**Comment by smarterclayton** [comment]
Looks like tests were never run on this?

**Comment by smarterclayton** [comment]
I don't see brad online, reverting.

**Comment by smarterclayton** [comment]
Reverted.

**Comment by smarterclayton** [comment]
Always remember to let the merge queue do it's job!  :)

**Pull request merged**
