### PR TITLE
Bug 1992596: e2e/cli: Finish basicresources.sh migration

### PR DESCRIPTION
**Pull request by deejross**
This is the unrevert for #26578 that broke metal builds. This unrevert includes the proposed metal and IPv6 changes from #26593.

### CODE REVIEW

**Comment by deads2k** [comment]
passing metal-ovn-ipv6 is a requirement for this PR before merge.

**Comment by soltysh** [comment]
> assing metal-ovn-ipv6 is a requirement for this PR before merge.

I see metal green and changes from https://github.com/openshift/origin/pull/26593 included as well.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
