### PR TITLE
[WIP] Ability to delete any type of resource from the UI

### PR DESCRIPTION
**Pull request by gruiz17**
Here is a collection of screenshots:

http://imgur.com/a/YvYRj

TODO:

- refactor deleting projects to use this directive too

### CODE REVIEW

**Comment by gruiz17** [comment]
@jwforres alright, I finished it.

**Comment by danmcp** [comment]
@gruiz17 Needs rebase.

@jwforres Review please.

**Comment by jwforres** [comment]
@danmcp we are holding off on this PR temporarily while I make the major navigational changes, since this will need updates to fit into that new layout.

Changing title back to [WIP] till then.

**Comment by ajacobs21e** [comment]
@jwforres @gruiz17 If you delete an item that you have to scroll to below the fold, does the success alert appear at the top of your current view or does the page scroll to the top to display the message?

**Comment by jwforres** [comment]
I'm guessing neither one currently, do you have a preference?

**Comment by jwforres** [comment]
@gruiz17 the major changes to Browse have merged now, so you can look at making this work in the new layout now

@ajacobs21e we need to think about where the delete icon should show up on the various pages, will we have it on the lists or only on the individual pages?

**Comment by ajacobs21e** [comment]
@jwforres displaying the alert at the top of the current scroll position is ideal. I asked patternfly if that's supported with the current alerts. 

Do you expect users to delete items individually or would they want to bulk delete a handful of items at once? There might not be real estate for  the same delete pattern in the list that we're using for the project page.

**Comment by gruiz17** [comment]
@jwforres @ajacobs21e sorry i've been MIA, i was working on another project for my work :bow: 

I will merge all of the newest changes in, and i'll have a gif ready soon!

**Comment by gruiz17** [comment]
@jwforres @ajacobs21e 

I've created a new pull request based on the new design!
for now, it only allows for deletion of individual resources from the resource pages themselves.

https://github.com/openshift/origin/pull/4836

**Pull request closed without merging**
