### PR TITLE
UPSTREAM: 46034: Event aggregation: include latest event message in aggregate event

### PR DESCRIPTION
**Pull request by sjenning**
needed for https://github.com/openshift/origin/pull/14693 to work properly

https://github.com/kubernetes/kubernetes/pull/46034

@derekwaynecarr @smarterclayton

### CODE REVIEW

**Comment by sjenning** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by sjenning** [comment]
@smarterclayton this needs the `severity: blocker` tag to merge

**Comment by smarterclayton** [comment]
[severity:blocker] removes useful data for end users [merge]

**Comment by smarterclayton** [comment]
Daemonset flake

**Comment by smarterclayton** [comment]
This daemonset flake happens a lot, can we open an issue and run it to
ground?

On Jun 22, 2017, at 2:15 AM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/merge FAILURE (
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1081/)
(Base Commit: 3233254
<https://github.com/openshift/origin/commit/3233254bf22a1c6beffde48ee81657a465479cde>)
(PR Branch Commit: 542bcdd
<https://github.com/openshift/origin/commit/542bcdd512a258efe351ec41708eb263949cd122>)
(Extended Tests: blocker)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14793#issuecomment-310286031>,
or mute
the thread

**Pull request merged**
