### PR TITLE
Compare object DN to BaseDN using structured comparison

### PR DESCRIPTION
**Pull request by liggitt**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1399781

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
[extended:ldap]

**Comment by enj** [comment]
Nice.  LGTM.

**Comment by soltysh** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
I think you'll also need [testextended]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/858/) failed from the following flakes:
 - [ldap_groups](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/858/) failed on: https://github.com/openshift/origin/issues/9379

re-[testextended]

**Comment by liggitt** [comment]
re[test]

**Comment by liggitt** [comment]
ldap extended test passes, hit [error](https://github.com/openshift/origin/pull/11996/files#r90588335) publishing junit results

[merge]

**Comment by mfojtik** [comment]
thanks @liggitt !

**Pull request merged**
