### PR TITLE
Bug 1330201 - Periodically sync k8s iptables rules

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by danwinship** [comment]
don't we already do this? I see lots of apparently-unnecessary iptables-related stuff in the logs...

**Comment by dcbw** [comment]
> don't we already do this? I see lots of apparently-unnecessary iptables-related stuff in the logs...

We don't unconditionally resync the proxy rules, though I think that's an oversight in OpenShift.  Upstream k8s has code that calls SyncLoop() (in vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go) but that only happens when the standalone kube-proxy is spawned, not when the OpenShift node proxy is started.

But proxy rules are resynced any time endpoints or services change, so I guess the problem is if you have a fairly stable cluster with long-running services and pods, and in between somebody screws around with the iptables rules manually.

**Comment by dcbw** [comment]
@pravisankar @danwinship note that while this fixes the problem of people unintentionally breaking OpenShift by messing around with iptables rules they should be touching, it does make the iptables-restore performance problem worse.  We already have bug reports from nodes running 100s of pods where iptables-restore takes 10+ seconds to complete due to the number of iptables rules present.  This fix will not make that problem better.  This is a problem that needs to be fixed somehow, possibly by being smarter about whether iptables rules need to be synced every single time, possibly by kernel improvements.

In any case, LGTM.

**Comment by dcbw** [comment]
[merge]

**Pull request merged**
