### PR TITLE
 wait for kube controllers to be ready before starting informers

### PR DESCRIPTION
**Pull request by deads2k**
3.8 pick of https://github.com/openshift/origin/pull/17859

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov Looks like these router tests are borked.  Known problem?

**Comment by stevekuznetsov** [comment]
Not known to me @knobunc

**Comment by soltysh** [comment]
/retest

On Thu, Jan 4, 2018 at 5:39 AM, OpenShift CI Robot <notifications@github.com

**Comment by deads2k** [comment]
This needs a green e2e before we merge it.

**Comment by mfojtik** [comment]
@deads2k https://github.com/openshift/origin/pull/17966 will make it green when https://github.com/openshift/origin/issues/17985 is resolved.

**Pull request merged**
