### PR TITLE
Set charset with content type

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@jwforres @spadgett PTAL... we weren't setting this, which meant that utf-8 content in login pages, etc, got rendered strangely as iso-8859-1 text.

**Comment by liggitt** [comment]
[test]

**Comment by spadgett** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
merge https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5473/ flaked on https://github.com/openshift/origin/issues/6053
re[merge]

**Pull request merged**
