### PR TITLE
Don't use KubeletConfig 'StartUpdates' channel for blocking kubelet

### PR DESCRIPTION
**Pull request by pravisankar**
Now kubelet will block on network plugin intialization for the node SDN setup to complete.

### CODE REVIEW

**Comment by pravisankar** [comment]
Depends on https://github.com/openshift/openshift-sdn/pull/221 (needs bump pr once this is merged)

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by liggitt** [comment]
what changed in the kubelet that allowed us to move the wait into the SDN layer?

**Comment by liggitt** [comment]
cc @smarterclayton as the originator of the StartUpdates channel... this look good to you?

**Comment by pravisankar** [comment]
On Fri, Dec 4, 2015 at 1:27 PM, Jordan Liggitt <notifications@github.com>
wrote:

> what changed in the kubelet that allowed us to move the wait into the SDN
> layer?
>
> Network plugin support in kubelet. More details:
https://trello.com/c/o7LT58cW

**Comment by dcbw** [comment]
LGTM; Init() gets called by kubelet and since both our plugins are now Kube plugins (previously the ovssubnet was not a kube plugin) we can remove StartUpdates entirely and rely on upstream kubelet calling our network plugin's Init() function (which will block).

**Comment by smarterclayton** [comment]
The change in general is fine (this closes the need for it), will do a
follow up on Monday for final review.

On Dec 4, 2015, at 7:03 PM, Dan Williams <notifications@github.com> wrote:

LGTM; Init() gets called by kubelet and since both our plugins are now Kube
plugins (previously the ovssubnet was not a kube plugin) we can remove
StartUpdates entirely and rely on upstream kubelet calling our network
plugin's Init() function (which will block).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/6202#issuecomment-162113984>.

**Comment by pravisankar** [comment]
Added openshift-sdn bump pr, now this is ready for merge.
@dcbw @smarterclayton PTAL

**Comment by smarterclayton** [comment]
LGTM but will leave sign off for @dcbw.  Which reminds me that we need a test case for SDN that can run as part of our regular CI flow.

**Comment by dcbw** [comment]
@smarterclayton LGTM.  I don't have merge privs so somebody else has to push the button.

**Comment by pravisankar** [comment]
[merge]

**Comment by pecameron** [comment]
Hi Dan,
Out of curiosity what is LGTM?
phil

**Comment by danwinship** [comment]
@pecameron "LGTM" = "Looks Good To Me". "PTAL" = "Please Take A Look"

**Comment by pecameron** [comment]
On 12/09/2015 09:03 AM, Dan Winship wrote:
>
> @pecameron <https://github.com/pecameron> "LGTM" = "Looks Good To Me".
> "PTAL" = "Please Take A Look"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/6202#issuecomment-163246284>.
>
Thanks
phil

**Pull request merged**
