### PR TITLE
add loadavg to node exporter whitelist.  this is not in cadvisor either.

### PR DESCRIPTION
**Pull request by jeremyeder**
There's no way to get loadavg at the moment.

### CODE REVIEW

**Comment by jeremyeder** [comment]
The errors are build errors.  Should not be related to this PR.

**Comment by smarterclayton** [comment]
Why do we care about loadavg?  What part of it isn't captured in our CPU calculations on the root slice?

**Comment by jeremyeder** [comment]
load on one set of infra nodes is ~2x the load on others.  CPU is mostly identical.

load avg tells about processes blocked on disk i/o, too.  it's not perfect (nothing is).  No single counter/metrics tells us everything.

I am going through things in zabbix that we lost.  This is one of the the most obvious and valuable (it was also in my metrics prio spreadsheet)

**Comment by smarterclayton** [comment]
You are getting those errors because you have to generate the bin data when you change the prometheus template.

**Comment by jeremyeder** [comment]
I'm getting node_load avg data now, thanks!

**Pull request closed without merging**
