### PR TITLE
Remove auto trigger

### PR DESCRIPTION
**Pull request by xiuwang**
@gabemontero The auto trigger always make sample-pipeline failed. Please help reivew this

### CODE REVIEW

**Comment by gabemontero** [comment]
@xiuwang you have to run `make update` when changing json or yaml in the tests to update bindata.go

**Comment by gabemontero** [comment]
Also, any chance you have some sample output when it fails?  At first blush I would say it does not "always" fail as this particular sample is exercised in the e2e's

**Comment by xiuwang** [comment]
Thanks Gabe.
Sample-pipeline always failed.
$ oc get builds -n wxj1
NAME                          TYPE              FROM          STATUS     STARTED       DURATION
nodejs-postgresql-example-1   Source            Git@93a4c44   Complete   2 hours ago   1m49s
sample-pipeline-1             JenkinsPipeline                 Failed     2 hours ago   
nodejs-postgresql-example-2   Source            Git@93a4c44   Complete   2 hours ago   1m26s

[rollout:latest:deploymentconfig/nodejs-postgresql-example] error: #2 is already in progress (Pending).
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
in catch block
[Pipeline] echo
Caught: hudson.AbortException: rollout:latest returned an error;
{err=error: #2 is already in progress (Pending).
, verb=rollout, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=wxj1 --token=XXXXX rollout latest deploymentconfig/nodejs-postgresql-example , out=, status=1}

[Pipeline] End of Pipeline
ERROR: rollout:latest returned an error;
{err=error: #2 is already in progress (Pending).
, verb=rollout, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=wxj1 --token=XXXXX rollout latest deploymentconfig/nodejs-postgresql-example , out=, status=1}

Finished: FAILURE

**Comment by gabemontero** [comment]
thanks @xiuwang 

And I see now, while we "use" that bc, we don't start builds with it.  We use it for our delete bc / delete job test.

That said, as I'm in the process of moving the jenkins e2e's, and we have a longer term goal of removing the examples/jenkins stuff, we'll just go with your fix for now.

e2e's are green, so I'll 

/lgtm

but we'll need 

@adambkaplan 

to approve given we had to update bindata

**Review by adambkaplan — APPROVED** [review]
/approve

**Pull request merged**
