### PR TITLE
Bug 1769015: Uncomment the lines to verify oc explain for networking related CRDs

### PR DESCRIPTION
**Pull request by abhat**
Depends on: https://github.com/openshift/cluster-network-operator/pull/398

### CODE REVIEW

**Comment by danwinship** [comment]
> doesn't match pattern {(?s)DESCRIPTION:.*FIELDS:.*spec.*<.*>.*(status.*<.*>.*)?}

Of the old `network.openshift.io` types, only `EgressNetworkPolicy` has a `spec`, so you're going to have to add the others to `specialTypes`.

**Comment by abhat** [comment]
@soltysh can you review the changes to the `explain tests`?

**Comment by knobunc** [comment]
@soltysh is this good?  Can you approve?

**Pull request merged**
