### PR TITLE
catalog: edit view role to have required rbac rules

### PR DESCRIPTION
**Pull request by jpeeler**
Adds rules for the view role to have add,list,watch permissions on
serviceinstances and servicebindings.

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1496753

### CODE REVIEW

**Comment by enj** [comment]
/hold

Let's stop monkeying with the cluster roles directly and use the logic from `oc auth reconcile`.  I will see if I can post an example on Monday.

**Comment by enj** [comment]
@jpeeler see if something like this works for you:

Replace all the role messing code with:

```go
for _, role := range GetServiceCatalogRBACDelta() {
	if _, err := (&reconciliation.ReconcileRoleOptions{
		Confirm:                true,
		RemoveExtraPermissions: false,
		Role: reconciliation.ClusterRoleRuleOwner{ClusterRole: &role},
		Client: reconciliation.ClusterRoleModifier{
			Client: kubeClient.Rbac().ClusterRoles(),
		},
	}).Run(); err != nil {
		return errors.NewError("could not reconcile service catalog cluster role %s", role.Name).WithCause(err)
	}
}
```


And add a new `rbac.go` file (check these rules):

```go
package openshift

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kubernetes/pkg/apis/rbac"

	"github.com/openshift/origin/pkg/cmd/server/bootstrappolicy"
)

func GetServiceCatalogRBACDelta() []rbac.ClusterRole {
	return []rbac.ClusterRole{
		{
			ObjectMeta: v1.ObjectMeta{
				Name: bootstrappolicy.AdminRoleName,
			},
			Rules: []rbac.PolicyRule{
				rbac.NewRule("create", "update", "delete", "get", "list", "watch").Groups("servicecatalog.k8s.io").Resources("serviceinstances", "servicebindings").RuleOrDie(),
				rbac.NewRule("create", "update", "delete", "get", "list", "watch").Groups("settings.k8s.io").Resources("podpresets").RuleOrDie(),
			},
		},
		{
			ObjectMeta: v1.ObjectMeta{
				Name: bootstrappolicy.EditRoleName,
			},
			Rules: []rbac.PolicyRule{
				rbac.NewRule("create", "update", "delete", "get", "list", "watch").Groups("servicecatalog.k8s.io").Resources("serviceinstances", "servicebindings").RuleOrDie(),
				rbac.NewRule("create", "update", "delete", "get", "list", "watch").Groups("settings.k8s.io").Resources("podpresets").RuleOrDie(),
			},
		},
		{
			ObjectMeta: v1.ObjectMeta{
				Name: bootstrappolicy.ViewRoleName,
			},
			Rules: []rbac.PolicyRule{
				rbac.NewRule("get", "list", "watch").Groups("servicecatalog.k8s.io").Resources("serviceinstances", "servicebindings").RuleOrDie(),
			},
		},
	}
}
```

**Comment by pmorie** [comment]
This is blocking QE so I would prefer to do refactors later @enj

**Comment by enj** [comment]
> This is blocking QE so I would prefer to do refactors later

Then use the code I wrote for you already.

**Comment by enj** [comment]
/hold

I would like sign off from @eparis to merge tech debt.

**Comment by simo5** [comment]
@jpeeler is there something blocking you from using the code @enj provided ?

**Comment by jpeeler** [comment]
No, I just had to rebuild/retest.

**Comment by eparis** [comment]
/retest
what is wrong with these computers!

**Comment by gabemontero** [comment]
@bparees - this is the service catalog PR discussed during scrum

**Comment by pmorie** [comment]
Flake #16929 

/test extended_conformance_install_update

**Pull request merged**
