### PR TITLE
fail immediately on multimatch error

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/6671

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@smarterclayton ptal.  I don't feel great about this fix, it feels sledge-hammery, but i need to go to bed.

**Comment by bparees** [comment]
'oc new-app https://github.com/openshift/sti-ruby.git --context-dir="2.0/test/puma-test-app" -o yaml' expecting success and text 'contextDir: 2.0/test/puma-test-app': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
error: multiple images or templates matched "ruby": 2

so rejecting multiple matches isn't going to work either, unless you always want to force users to specify things explicitly, because we register what are effectively multiple matches (eg ruby:2.0 and ruby:2.2) for everything.

**Comment by bparees** [comment]
(specifically we're matching the supports annotation multiple times)

**Comment by bparees** [comment]
(which also leaves me dubious this is a regression, we've had multiple imagestreams for a long time and if the correct behavior is to fail on multiple matches, then new-app should have been failing for a long time and it wasn't)

**Comment by smarterclayton** [comment]
Let's talk in person

**Comment by bparees** [comment]
probably needs work to clean up tests, but @smarterclayton ptal to see if you agree with the new behavior and implementation.  In particular the way the UsageError is produced seems wrong to me (I would have assumed we could just return the err and something else would be responsible for invoking UsageError, maybe i'm just doing it wrong but that didn't seem to be happening)

Sample output below:

multiple local(not in dockerhub) image matches:
```
$ docker images | grep image1
test/image1                                          latest              60e65a8e4030        3 weeks ago         196.6 MB
test2/image1                                         latest              60e65a8e4030        3 weeks ago         196.6 MB

$ oc new-app image1 --dry-run
error: 
The argument "image1" could apply to the following Docker images or OpenShift image streams:

* Docker image "test/image1:latest", 60e65a8, from local, author The CentOS Project <cloud-ops@centos.org>
  Use --docker-image="test/image1:latest" to specify this image or template

* Docker image "test2/image1:latest", 60e65a8, from local, author The CentOS Project <cloud-ops@centos.org>
  Use --docker-image="test2/image1:latest" to specify this image or template

origin (newapp_matches)$ oc new-app --dry-run --docker-image="test2/image1:latest"
W0116 16:01:25.677811   26264 pipeline.go:153] Could not find an image stream match for "test2/image1:latest". Make sure that a Docker image with that tag is available on the node for the deployment to succeed.
--> Found Docker image 60e65a8 (3 weeks old) from  for "test2/image1:latest"
    * This image will be deployed in deployment config "image1"
    * [WARNING] Image "image1" runs as the 'root' user which may not be permitted by your cluster administrator
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/image1 --port=[port]' later
--> Creating resources with label app=image1 ...
--> Success (DRY RUN)
```

Multiple python imagestreams available:
```
$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git --dry-run
error: 
The argument "python" could apply to the following Docker images or OpenShift image streams:

* Image stream "python" (tag "latest") in project "test"
  Use --image-stream="test/python" to specify this image or template

* Image stream "python" (tag "latest") in project "openshift"
  Use --image-stream="openshift/python" to specify this image or template

$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git --dry-run --image-stream="test/python"
I0116 16:00:05.504218   26078 newapp.go:566] Using "https://github.com/GrahamDumpleton/wsgi-hello-world.git" as the source for build
--> Found image a4b4c60 (4 hours old) in image stream "python" under tag :latest for "test/python"
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
--> Success (DRY RUN)
```

Partial match for docker image:
```
$ oc new-app test/scratchimage2 -o yamlerror: 
The argument "test/scratchimage2" only partially matched the following Docker image or OpenShift image stream:

* Docker image "test/scratchimage:latest", 5d31f4e, from local
  Use --docker-image="test/scratchimage:latest" to specify this image or template
```

partial match for imagestream:
```
$ oc new-app openshift/jenkin -o yaml
error: 
The argument "openshift/jenkin" only partially matched the following Docker image or OpenShift image stream:

* Image stream "jenkins" (tag "latest") in project "openshift"
  Use --image-stream="openshift/jenkins" to specify this image or template
```

multiple types of matches:
```
$ oc new-app jenkin -o yaml
error: 
The argument "jenkin" could apply to the following Docker images or OpenShift image streams:

* Image stream "jenkins" (tag "latest") in project "openshift"
  Use --image-stream="openshift/jenkins" to specify this image or template

* Template "jenkins-ephemeral" in project "openshift"
  Use --template="jenkins-ephemeral" to specify this image or template

* Template "jenkins-persistent" in project "openshift"
  Use --template="jenkins-persistent" to specify this image or template
```

**Comment by smarterclayton** [comment]
```
$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git --dry-run
error: 
The argument "python" could apply to the following Docker images or OpenShift image streams:

* Image stream "python" (tag "latest") in project "test"
  Use --image-stream="test/python" to specify this image or template

* Image stream "python" (tag "latest") in project "openshift"
  Use --image-stream="openshift/python" to specify this image or template
```

should result in test/python being chosen because a) user has created image stream 'python' in their local namespace and b) they did not specify a tag.

I think the others are all correct.

**Comment by bparees** [comment]
@smarterclayton ok, i'm trying to decide the best way to implement that behavior w/o making the search logic even more complex.

The "easy" solution is for the ImageStreamSearcher to simply stop iterating namespaces if it finds an exact match.  

the "right" solution would be to return both matches but then choose the first one..the problem there is you're returning two exact matches and we've already concluded that returning two exact matches is an error.

Returning the openshift namespace match as a partial match isn't a great answer either since 
1) if there's an exact match it's just going to get ignored so there's no point in returning it anyway
2) if it's the best match, we're going to tell the user they only had a partial match and need to rerun the command specifying the name exactly.

right now i'm leaning towards just stopping iterating namespaces if an exact match is found.

**Comment by smarterclayton** [comment]
It should certainly stop for "resolve".  However, for "search" it should not stop.  I would expect if it finds a match in a namespace, it should return only that as exact and all the others as inexact (being the first in the namespace search order means exact).

**Comment by bparees** [comment]
> It should certainly stop for "resolve". However, for "search" it should not stop. 

the current implementation doesn't make this distinction easy, since resolve just calls Search.

**Comment by bparees** [comment]
@smarterclayton ok, behavior updated, ptal

**Comment by bparees** [comment]
create:

```
$  oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git  --dry-run
--> Found image f429f51 (5 minutes old) in image stream "python" under tag :latest for "python"
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
--> Success (DRY RUN)
```

search:
```
$ oc new-app -S pythonImage streams (oc new-app --image-stream=<image-stream> [--code=<source>])
-----
python
  Project: t1
  Tags:    latest
python
  Project: openshift
  Tags:    2.7, 3.3, 3.4, latest

Docker images (oc new-app --docker-image=<docker-image> [--code=<source>])
-----
python
  Registry: Docker Hub
  Tags:     latest
```

and if you delete the "python" imagestream in the local project:
```
$  oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git  --dry-run
--> Found image ec180c9 (4 days old) in image stream "python in project openshift" under tag :latest for "python"
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
--> Success (DRY RUN)
```

**Comment by bparees** [comment]
1/2 again but some scary stacks on the failure.

Ben Parees | OpenShift

**Comment by bparees** [comment]
@smarterclayton can i get a sign off?

**Comment by smarterclayton** [comment]
The describe you pasted looks like it has a quoting bug:

`--> Found image ec180c9 (4 days old) in image stream "python in project openshift"`

**Comment by bparees** [comment]
> The describe you pasted looks like it has a quoting bug:

@smarterclayton not one introduced by this change, but yes... fixed.

```
$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git  --dry-run
--> Found image ec180c9 (5 days old) in image stream "python" in project "openshift" under tag :latest for "python"
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
--> Success (DRY RUN)
```

**Comment by bparees** [comment]
added quotes around ":latest" as well.

**Comment by bparees** [comment]
@smarterclayton removed the extraneous field and change the log item to level 5.

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Pull request merged**
