### PR TITLE
Add new CL quickstarts, new CL config and updated bindata

### PR DESCRIPTION
**Pull request by sjug**
Cluster Loader uses an additional `IDENTIFIER` parameter in the template that is not in the default quickstarts, which causes breakage as described in https://github.com/openshift/origin/issues/23195.

Rather than modifying the existing quickstarts, I've just added our own for this. This PR also needs the changes in https://github.com/openshift/origin/pull/23306 to fix the issue.

### CODE REVIEW

**Comment by sjug** [comment]
@bparees can you please approve this (after review) or suggest someone who may be able to?

**Comment by bparees** [comment]
@sjug it looks good to me, does https://github.com/openshift/origin/pull/23306 need to merge before this will pass tests?

**Comment by sjug** [comment]
@bparees Yes, it need that PR to get merged in first.

**Comment by bparees** [comment]
/approve
/lgtm
/hold

@sjug you should be able to remove the hold when this is mergeable.

**Pull request merged**
