### PR TITLE
[stage] UPSTREAM: 53167: Do not GC exited containers in running pods

### PR DESCRIPTION
**Pull request by sjenning**
stage pick for https://github.com/openshift/origin/pull/16896

@derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
/test extended_conformance_gce
--

**Comment by sjenning** [comment]
was waiting for https://github.com/openshift/origin/pull/16907 to merge so i could rebase.  rebase is complete. removing hold.

**Pull request merged**
