### PR TITLE
Support router reencrypt automatically for service serving certs

### PR DESCRIPTION
**Pull request by smarterclayton**
`destinationCACertificate` is currently required on routes. However,
service serving certs would allow reencrypt for any internal connection
without having to specify a certificate, because the router has
serving-ca.crt injected automatically.

Allow `destinationCACertificate` to be empty, and update the router to
accept a configurable default destination CA certificate path. In the
template router, when a route has an empty destinationCACertificate use that
default (if set) as the ca-file. If no default is set, do not verify the
backend. If using the default destination also add `verifyhost` with the
short service DNS name (`SVC.NAMESPACE.svc`) which the serving CA signs for,
so that HAProxy will require a matching backend.

Future work might include letting the client specify an annotation to
override verifyhost if another certificate allocator is in play, or
combining multiple ca-files.

TODO:
* [ ] determine whether no default destination and no specified destination should be `verify none` or a hard failure (possibly a message)
* [x] add an e2e test for all three new scenarios
* [ ] document the change

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

@openshift/networking this allows applications using serving certificates (like router, logging, metrics, web console, registry console) to get reencrypt for free with no possibility of MITM.  Basically no-certs-required, full end-to-end.

@jwforres since you asked nicely :)

**Comment by smarterclayton** [comment]
Card https://trello.com/c/zZb7gAMi

**Comment by jwforres** [comment]
Thank you 🎉   this has been really irritating that it didn't "just work" when you use a serving cert

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Will merge when master opens

**Comment by smarterclayton** [comment]
Master is open, [merge]

**Comment by smarterclayton** [comment]
[merge] deployment config flake

**Comment by smarterclayton** [comment]
Flake was https://github.com/openshift/origin/issues/14180

**Pull request merged**
