### PR TITLE
configchange: abort update once an image change is detected

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/7464

@ironcladlou PTAL

### CODE REVIEW

**Comment by ironcladlou** [comment]
I think this should do it. Worth adding a test?

**Comment by kargakis** [comment]
Will add

**Comment by kargakis** [comment]
@ironcladlou test added, PTAL

**Comment by kargakis** [comment]
[test]

**Comment by ironcladlou** [comment]
LGTM once tests pass

**Comment by kargakis** [comment]
all green, [merge]

**Pull request merged**
