### PR TITLE
Update imagestreams in build and image-ecosystem

### PR DESCRIPTION
**Pull request by yselkowitz**
- builds: upgrade php to 7.4
- image_ecosystem: specify available architectures for each S2I image
- image_ecosystem: update imagestreams
- image_ecosystem: add ubi7 imagestreams and x86-only dotnet

### CODE REVIEW

**Comment by yselkowitz** [comment]
this is one step in updating imagestreams for RHEL 8.4 and RHSCL 3.8
django hot deploy is a known issue
/assign @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
