### PR TITLE
[3.9] Apps: Fix DC recreate strategy to wait only for running pods

### PR DESCRIPTION
**Pull request by tnozicka**
backport of https://github.com/openshift/origin/pull/19029

/assign @mfojtik

### CODE REVIEW

**Comment by tnozicka** [comment]
All 3 jobs blocked on https://github.com/openshift/origin/issues/19973

**Comment by tnozicka** [comment]
flake https://github.com/openshift/origin/issues/20640

**Comment by tnozicka** [comment]
@mfojtik the 3.9 CI itself is borked on https://github.com/openshift/origin/issues/19973

**Comment by tnozicka** [comment]
ok, that one is fixed, by we have only moved a step to new failure https://github.com/openshift/origin/issues/20679

**Comment by soltysh** [comment]
/hold
Not sure if we are able to merge this in automatically @mfojtik, and it's only wasting our resources re-testing this over and over again.

**Comment by tnozicka** [comment]
nobody is willing to fix the CI :/
/close

**Pull request closed without merging**
