### PR TITLE
[3.7] Drop image signature annotations

### PR DESCRIPTION
**Pull request by miminar**
Backports openshift/origin#19037

Resolves: [rhbz#1557607](https://bugzilla.redhat.com/show_bug.cgi?id=1557607)

/assign @bparees

### CODE REVIEW

**Comment by miminar** [comment]
```
  1. Hosts:    ci-prtest-7ec2229-7-ig-m-j9ch
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "package_version":
               Some required package(s) are available at a version
               that is higher than requested
                 docker-1.13.1
               This will prevent installing the version you requested.
               Please check your enabled repositories or adjust openshift_release.
```

I suppose origin 3.7 ci/cd is out of interest now. @bparees but we want to merge this anyway, right?

**Comment by bparees** [comment]
> I suppose origin 3.7 ci/cd is out of interest now. @bparees but we want to merge this anyway, right?

generally we don't backport to old origin releases, but this is bad enough it would be nice to have it.

And we certainly need the 3.7 CI working for the things that *are* important enough to backport, so paging @stevekuznetsov and @paradigm for the CI failure.

**Comment by bparees** [comment]
@miminar let's punt on this backport.  it's not the sort of thing we normally backport to 3.7 and the CI system is broken.  (If the CI system weren't broken i'd say let's merge it, but I don't want to deal w/ getting this through a broken merge queue)

@smarterclayton how important is having CI work against older origin branches, to you?

**Comment by miminar** [comment]
understood

**Pull request closed without merging**
