### PR TITLE
image: set error when we receive unknown schema for the image

### PR DESCRIPTION
**Pull request by mfojtik**
@dmage @soltysh 

The error we get is:

```console
I0913 06:32:59.350152   24974 importer.go:551] unsupported manifest type: *manifestlist.DeserializedManifestList
```

This will result into the .Image field to be nil which we then later panic on. I'm not sure how this was not broken before or if something changed in DockerHub. The mongo and redis images in DockerHub both have manifest lists, but we should be converting them to schema2 automatically?

This PR just propagate that error to image stream status instead of panicking the importer. We should investigate further.

### CODE REVIEW

**Comment by soltysh** [comment]
We've agreed with Michal to have it still, since it prevents nasty panics and provides more friendly error.

/lgtm

**Comment by mfojtik** [comment]
@smarterclayton we might need to backport this down to 3.3 as z-stream :-(((

**Comment by deads2k** [comment]
Nothing merged since this started and can't until this goes in.  Marking retest-not-required just to hurry it along.

**Comment by mfojtik** [comment]
/test cmd

etcd timeout

**Comment by bparees** [comment]
still failing a dockerhub integration test:

```
--- FAIL: TestImageStreamImportDockerHub (1.98s)
    			imageimporter_test.go:837: unexpected repository: &image.RepositoryImportStatus{Status:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"one of the images from this repository failed to import", Reason:"ImportFailed", Details:(*v1.StatusDetails)(nil), Code:0}, Images:[]image.ImageImportStatus{image.ImageImportStatus{Tag:"latest", Status:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Success", Message:"", Reason:"", Details:(*v1.StatusDetails)(nil), Code:0}, Image:(*image.Image)(0xc4207e4c00)}, image.ImageImportStatus{Tag:"3.5", Status:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Success", Message:"", Reason:"", Details:(*v1.StatusDetails)(nil), Code:0}, Image:(*image.Image)(0xc4207e5c00)}, image.ImageImportStatus{Tag:"3.5-windowsservercore", Status:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"dockerimage.image.openshift.io \"mongo:3.5-windowsservercore\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc42053e060), Code:404}, Image:(*image.Image)(nil)}}, AdditionalTags:[]string{"3.4", "3.4-windowsservercore", "3.4-rc", "3.3", "3.3-windowsservercore", "3.2", "3.2-windowsservercore", "3.2-rc", "3.1", "3.0", "3.0-windowsservercore", "2.8", "2.7", "2.6", "2.4", "2.2", "3.5.12", "3.5.12-windowsservercore", "3.5.11", "3.5.11-windowsservercore", "3.5.10", "3.5.10-windowsservercore", "3.5.9", "3.5.9-windowsservercore", "3.5.8", "3.5.8-windowsservercore", "3.5.7", "3.5.7-windowsservercore", "3.5.6", "3.5.6-windowsservercore", "3.5.5", "3.5.5-windowsservercore", "3.4.9", "3.4.8", "3.4.7", "3.4.7-windowsservercore", "3.4.6", "3.4.6-windowsservercore", "3.4.5", "3.4.5-windowsservercore", "3.4.4", "3.4.4-windowsservercore", "3.4.3", "3.4.3-windowsservercore", "3.4.2", "3.4.1", "3.4.1-windowsservercore", "3.4.0", "3.4.0-windowsservercore", "3.4.0-rc5-windowsservercore", "3.4.0-rc5", "3.4.0-rc4-windowsservercore", "3.4.0-rc4", "3.4.0-rc3-windowsservercore", "3.4.0-rc3", "3.4.0-rc2-windowsservercore", "3.4.0-rc2", "3.3.15", "3.3.15-windowsservercore", "3.3.14", "3.3.14-windowsservercore", "3.3.12", "3.3.12-windowsservercore", "3.3.11", "3.3.11-windowsservercore", "3.3.10", "3.3.9", "3.3.8", "3.3.6", "3.3.5", "3.2.16", "3.2.16-windowsservercore", "3.2.15", "3.2.15-windowsservercore", "3.2.14", "3.2.14-windowsservercore", "3.2.13", "3.2.13-windowsservercore", "3.2.12", "3.2.12-windowsservercore", "3.2.11", "3.2.11-windowsservercore", "3.2.10", "3.2.10-windowsservercore", "3.2.9", "3.2.9-windowsservercore", "3.2.8", "3.2.7", "3.2.6", "3.2.5", "3.2.4", "3.2.3", "3.2.1", "3.2.0", "3.2.0-rc6", "3.2.0-rc4", "3.2.0-rc3", "3.2.0-rc2", "3.2.0-rc1", "3.1.9", "3.1.8", "3.1.7", "3.1.6", "3.1.5", "3.1.4", "3.0.15", "3.0.15-windowsservercore", "3.0.14", "3.0.14-windowsservercore", "3.0.13", "3.0.13-windowsservercore", "3.0.12", "3.0.12-windowsservercore", "3.0.11", "3.0.10", "3.0.9", "3.0.8", "3.0.7", "3.0.6", "3.0.5", "3.0.4", "3.0.3", "3.0.2", "3.0.1", "3.0.0", "3.0.0-rc8", "3.0.0-rc7", "3.0.0-rc6", "2.8.0", "2.8.0-rc5", "2.8.0-rc4", "2.8.0-rc3", "2.8.0-rc0", "2.7.8", "2.7.7", "2.7.6", "2.7.5", "2.6.12", "2.6.11", "2.6.10", "2.6.9", "2.6.8", "2.6.7", "2.6.6", "2.6.5", "2.6.4", "2.6.1", "2.4.14", "2.4.13", "2.4.12", "2.4.11", "2.4.10", "2.2.7", "2", "3", "3-windowsservercore", "3.4-rc-windowsservercore", "rc", "rc-windowsservercore", "unstable", "unstable-windowsservercore", "windowsservercore"}}
    		FAIL
```

**Comment by mfojtik** [comment]
@bparees yeah, @dmage is working on alternative solution... continuing this path I will have to ignore the NotFound tags (we failed to fetch them because they are pointing to windows manifests...)

**Pull request merged**
