### PR TITLE
Bug 1926146: e2e: skip http2 router tests in proxied environment

### PR DESCRIPTION
**Pull request by stlaz**
/assign @frobware

### CODE REVIEW

**Comment by frobware** [comment]
I'm expecting https://github.com/openshift/origin/pull/25874 to fix the issues for idle tests and also failing in the proxy job.

**Comment by frobware** [comment]
These changes https://github.com/openshift/origin/pull/25874#issuecomment-776885859 show that the idling test will now pass in the proxy job. As http/2 tests are currently disabled (planned to be re-enabled in 4.8) I propose we close this close this as I will do a broader change that covers http/2, gRPC and h2spec for the router (and the proxy job).

**Comment by stlaz** [comment]
/close
should be fixed by another PR as stated in https://github.com/openshift/origin/pull/25878#issuecomment-776897888

**Pull request closed without merging**
