### PR TITLE
UPSTREAM: 46542: Ignore pods for quota marked for deletion whose node is unreachable

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/46542

xref https://bugzilla.redhat.com/show_bug.cgi?id=1455743

@derekwaynecarr

### CODE REVIEW

**Comment by sjenning** [comment]
flake https://github.com/openshift/origin/issues/15900

/retest

**Comment by sjenning** [comment]
rebase is done. @derekwaynecarr can i get lgtm on this?

**Comment by liggitt** [comment]
Coming in with 1.7.8 picks in https://github.com/openshift/origin/pull/16722

**Comment by sjenning** [comment]
closing in favor of #16722

**Pull request closed without merging**
