### PR TITLE
add support to build different tags in hack script

### PR DESCRIPTION
**Pull request by jpeeler**
This adds the tag to the calculated FROM line, which for this branch is v3.9.0. (Backport of #19917.)

### CODE REVIEW

**Comment by jpeeler** [comment]
/test gcp
flake #19887

**Comment by jpeeler** [comment]
@bparees Any chance for a green button here given that CI for 3.9 is unpassable currently?

**Comment by bparees** [comment]
i can, although i wonder if we should even bother w/ this.  we don't generally backport changes into origin.

also did you open an issue for the failing 3.9 test that is blocking this?

**Comment by jpeeler** [comment]
@bparees I need this change to make catalog CI work. The failing 3.9 test does have an issue open.

**Pull request merged**
