### PR TITLE
Bug 1890901: Fixes the wrong file path(/var/lib//var/lib/haproxy/conf/haproxy.conf) for the CI test to pass

### PR DESCRIPTION
**Pull request by miheer**
Fixes the wrong file path(/var/lib//var/lib/haproxy/conf/haproxy.conf) for the CI test to pass

### CODE REVIEW

**Comment by frobware** [comment]
@miheer you're going to need to create a bugzilla for this.

/assign @knobunc

**Comment by miheer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1890901

**Comment by frobware** [comment]
/hold

Waiting for #25647 and also blocked on https://bugzilla.redhat.com/show_bug.cgi?id=1893657



It will continue to fail in CI until that merges.

**Comment by frobware** [comment]
> /hold
> 
> Waiting for #25647 and also blocked on https://bugzilla.redhat.com/show_bug.cgi?id=1893657
> 
> It will continue to fail in CI until that merges.

/hold cancel

**Comment by gabemontero** [comment]
OK you got a clean e2e-gcp with https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25626/pull-ci-openshift-origin-release-3.11-e2e-gcp/1323305068413325312 @frobware 

I think we are on path / true "flakes" vs. issues

**Pull request merged**
