### PR TITLE
UPSTREAM: 56408: admission: do not leak admission plugin config types outside of the plugin

### PR DESCRIPTION
**Pull request by sttts**
For https://bugzilla.redhat.com/show_bug.cgi?id=1531439.

### CODE REVIEW

**Comment by deads2k** [comment]
I expected ripples into the openshift code.  We don't register anything?

**Comment by sttts** [comment]
> I expected ripples into the openshift code. We don't register anything?

Me too. Haven't looked into details, but it compiles. And after https://github.com/openshift/origin/pull/18111/files#diff-993f8edd422e7a353de4d88a20ceb669L45 the `ConfigScheme` is gone. So it looks like we didn't register anything. Which leads to the question: what do we test about admission configuration?

**Comment by deads2k** [comment]
> Which leads to the question: what do we test about admission configuration?

Integration tests.

**Pull request merged**
