### PR TITLE
[RPMs] Ease the upgrade to v1.0.6

### PR DESCRIPTION
**Pull request by sdodson**
- Create /var/lib/origin symlink for upgrades
 - Add obsoletes on openshift < 1.0.6

### CODE REVIEW

**Comment by sdodson** [comment]
@ashcrow or @maxamillion mind taking a look?

These changes are already in the COPR build at
https://copr.fedoraproject.org/coprs/maxamillion/origin-next/build/116643/

**Comment by ashcrow** [comment]
@sdodson the changes makes sense and seem sane. LGTM.

**Comment by sdodson** [comment]
Thanks for taking a look.

@brenton Based on how well the obsoletes goes with origin we'll consider doing the same for the transition between openshift -> atomic-openshift when the time comes. Ready to merge if it looks good to to.

**Comment by brenton** [comment]
[merge]

**Pull request merged**
