### PR TITLE
oc new-app --list

### PR DESCRIPTION
**Pull request by fabianofranz**
This is a small change that gives us the ability to list all templates, image streams and local (from client) Docker images, through `oc new-app --list`. Pairs nicely with `oc new-app --search <thing>`.

Caveat: we only list Docker images from the client, not from the Docker registry (would potentially return too many things, e.g. from Docker Hub).

Possible variations: instead of having both `--list` and `--search <thing>`, use just one of them that will search if an argument were provided, and list everything in case of no args. Another idea is to make `oc new-app` (without arguments or flags) behave as the list (currently errors as "need to provide one or more...").

@smarterclayton looks valuable?

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@smarterclayton @csrwng @kargakis fyi

**Comment by csrwng** [comment]
Not sure that the list of local docker images would be that useful and could potentially be very long. Maybe just listing the stored templates and builder image streams would be useful, like rhc gives you the list of cartridges (or like we do in the web console).

**Comment by smarterclayton** [comment]
Yeah, list of local docker images is probably going to have a lot of crap
in it.

On Wed, Jul 29, 2015 at 4:00 PM, Cesar Wong <notifications@github.com>
wrote:

> Not sure that the list of local docker images would be that useful and
> could potentially be very long. Maybe just listing the stored templates and
> builder image streams would be useful, like rhc gives you the list of
> cartridges (or like we do in the web console).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3933#issuecomment-126079428>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
--list is generally valuable.  I would not try to combine it with --search
though.  There's an open question

Also, add -S and -L so I don't have to type --list and --search all the
time.

On Tue, Jul 28, 2015 at 4:04 PM, Fabiano Franz <notifications@github.com>
wrote:

> [test]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3933#issuecomment-125737338>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
... there's an open question about whether search should just take a single
argument - the text to search for - instead of using all the arguments.

On Wed, Jul 29, 2015 at 4:05 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> --list is generally valuable.  I would not try to combine it with --search
> though.  There's an open question
>
> Also, add -S and -L so I don't have to type --list and --search all the
> time.
>
> On Tue, Jul 28, 2015 at 4:04 PM, Fabiano Franz <notifications@github.com>
> wrote:
>
>> [test]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3933#issuecomment-125737338>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fabianofranz** [comment]
@smarterclayton @csrwng Makes sense. So I updated this to only list stored templates and image streams, and updated the examples and flag descriptions to make it clear. `--list` and `--search <thing>` are separated and can't be combined. PTAL

**Comment by smarterclayton** [comment]
Looks fine

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
