### PR TITLE
add unit test for OCP-10189

### PR DESCRIPTION
**Pull request by SSshahan**
QE add more check for start-build according to [OCP-10189](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-10189), could you please help review? Thanks!

### CODE REVIEW

**Comment by SSshahan** [comment]
@soltysh  could you have a look this pr? why it always hit this [error](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19525/test_pull_request_origin_unit/12739/) in different ways of `Factory` creation?  It is strange that although use the `NewFactory()` function from k8s, it also hit this error. Thanks in advance!

**Comment by SSshahan** [comment]
@gabemontero  Now the above problem I hit has been addressed, could you help to review this case?  Thanks!

**Comment by gabemontero** [comment]
/lgtm

@openshfit/sig-developer-experience fyi

**Comment by SSshahan** [comment]
@soltysh could you help to add the approval label if you look good? Thanks!

**Comment by soltysh** [comment]
/hold

I don't want to introduce such tests, we'll be revamping the printing in the next release after k8s 1.11 lands. This will definitely change! I'd suggest the test be more about testing functionality not the output, that's the current approach we're trying to force upstream and I won't merge anything like this downstream, either.

**Comment by SSshahan** [comment]
@soltysh got it.  Did you have any link to the related issue for revamping printing, so that QE could have an adjustment for the cases we have in advance?

**Comment by soltysh** [comment]
@SSshahan there's no specific issue, you'd need to look for mine and @juanvallejo's prs in kuberentes repo.

**Comment by soltysh** [comment]
But as a rule of thumb, do not rely on any particular output in the CLI, we never guarantee it being stable. Rather it's better to verify if the action performed actual updates/changes to the resource. That's what we'll be moving towards with testing as well.

**Comment by SSshahan** [comment]
OK, will close the pr. Thanks!

**Pull request closed without merging**
