### PR TITLE
test/integration: pass HostConfig at image creation time for router tests

### PR DESCRIPTION
**Pull request by dcbw**
@danmcp this might work...

Fixes https://github.com/openshift/origin/issues/11591

### CODE REVIEW

**Comment by danmcp** [comment]
[test]

**Comment by pweil-** [comment]
LGTM.  As of v1.24 the start api no longer accepts the HostConfig (deprecated in 1.10)

https://docs.docker.com/engine/reference/api/docker_remote_api/#v124-api-changes

**Comment by danmcp** [comment]
hack/verify-gofmt.sh
!!! gofmt needs to be run on the following files: 
./test/integration/router_test.go

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
