### PR TITLE
add kubepodcrashlooping to list of ignored alerts

### PR DESCRIPTION
**Pull request by bparees**
this is only being added temporarily until
https://bugzilla.redhat.com/show_bug.cgi?id=1842002 is resolved,
after which this PR must be reverted.

### CODE REVIEW

**Comment by bparees** [comment]
> Won't you need to link a bug from the PR subject to backport to 4.5? 

not if i just override the bz req.  which is what i plan to do.

> Also, my preference for a test-side fix would be a six-minute post-install sleep (or a kube-apiserver Progressing=True sleep, capped at 6m) to give the API server time to settle down. But I'm fine with whatever in the short term

this seemed to be the approach @smarterclayton preferred, post-install sleeps were apparently rejected previously.

**Comment by smarterclayton** [comment]
Post install sleep won't fix this - this test runs AFTER the rest of the tests, and looks back 2 hours.  Adding 6m won't fix it unfortunately unless it happens that upgrade takes longer than 2 hours, which is not something to rely on.  I originally thought it was the wait but the test is much smarter now and our product regressing a bit.

**Comment by wking** [comment]
/lgtm

[GCP][1] failed to build with:

```
Pulling image registry.svc.ci.openshift.org/ocp/builder:golang-1.13 ...
error: build error: failed to pull image: Error: image ocp/builder:golang-1.13 not found
```

/retest

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-gcp/8341

**Comment by bparees** [comment]
```
Pulling image registry.svc.ci.openshift.org/ocp/builder:golang-1.13 ...
error: build error: failed to pull image: Error: image ocp/builder:golang-1.13 not found
```

that seems like an error that should not happen...  @stevekuznetsov

**Comment by wking** [comment]
> that seems like an error that should not happen...

[Seems rare][1].  But yeah, would be nice if it didn't happen at all :).

[1]: https://search.svc.ci.openshift.org/?search=failed+to+pull+image.*golang.*not+found

**Comment by bparees** [comment]
@openshift/openshift-team-monitoring not that this test is really your concern but fyi.

**Comment by wking** [comment]
[FIPS][1] Kube API went dark before bootstrap complete, and install failed.  [e2e-cmd][2] failed in setup with:

```
Cluster operator authentication Progressing is True with _WellKnownNotReady: Progressing: got '404 Not Found' status while trying to GET the OAuth well-known https://10.0.0.4:6443/.well-known/oauth-authorization-server endpoint data
```

[serial][3] made it to the tests, but failed on:

```
sig-api-machinery] Namespaces [Serial] should delete fast enough (90 percent of 100 namespaces in 150 seconds) [Suite:openshift/conformance/serial] 
```

[upgrade][4] failed on `Service was unreachable during disruption for at least 48s`.

/retest

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-aws-fips/3270
[2]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-cmd/5897
[3]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-aws-serial/14584
[4]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-gcp-upgrade/4441

**Comment by wking** [comment]
Poking in [the FIPS failure][1]'s [log bundle][2]:

```
$ grep '"attempt": [^0]' bootstrap/containers/*.inspect 
bootstrap/containers/cloud-credential-operator-ad0c8f95af28155d280a26416ede6a94adc46f57b724f6b54f08905018d6fb83.inspect:      "attempt": 11,
bootstrap/containers/cluster-version-operator-1f6115911bbfa402033b04dcbee0fee34760f69d80d236666a3d7c712efb9cd1.inspect:      "attempt": 1,
bootstrap/containers/kube-apiserver-de38bbc76573b2c14da39eb8d966dc8698dd0286d75acc0827901dce64405bf6.inspect:      "attempt": 1,
bootstrap/containers/kube-apiserver-insecure-readyz-7526e4441fd4413f7fc6fbc29785f486342621c74dc7c7639725328ed9834008.inspect:      "attempt": 2,
bootstrap/containers/kube-apiserver-insecure-readyz-bc4f1fa5dda3d31498b9cc06bbe86318697aa3e36567948b1d592180979ebb46.inspect:      "attempt": 1,
bootstrap/containers/kube-controller-manager-c1d4b4e90e251f9e20e1afa9ab9a7adc648230fb16ce667325e847daa6a52126.inspect:      "attempt": 1,
bootstrap/containers/kube-scheduler-ba28db102059ca25af13633430885cdfa3f9c4efafdf3dc6f02bf4fd15294a57.inspect:      "attempt": 1,
bootstrap/containers/setup-4affb608eb4017587629de44dcf89e31b8a8e40fc52884027c8e061e8b573b73.inspect:      "attempt": 1,
$ tail -n2 bootstrap/containers/cloud-credential-operator-ad0c8f95af28155d280a26416ede6a94adc46f57b724f6b54f08905018d6fb83.log 
time="2020-06-11T01:02:38Z" level=info msg="setting up AWS pod identity controller"
time="2020-06-11T01:02:38Z" level=fatal msg="unable to register controllers to the manager" error="AWS_POD_IDENTITY_WEBHOOK_IMAGE is not set"
```

I don't see anyone talking about that yet; will spin off into a fresh bug...

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-aws-fips/3270
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-aws-fips/3270/artifacts/e2e-aws-fips/installer/

**Comment by wking** [comment]
This time [upgrade][1] died on install with `_WellKnownNotReady`, so I filed [rhbz#1846203](https://bugzilla.redhat.com/show_bug.cgi?id=1846203) for that one too.

/test e2e-gcp-upgrade

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-e2e-gcp-upgrade/4442

**Comment by wking** [comment]
We're backsliding :p.  [Verify][1]:

```
2020/06/11 08:15:41 Building src
2020/06/11 08:17:56 Build src failed, printing logs:
2020/06/11 08:17:56 error: Unable to retrieve logs from failed build: build src is in an error state. No logs are available.
```

/retest

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25094/pull-ci-openshift-origin-master-verify/13712

**Pull request merged**
