### PR TITLE
Try moving extended tests to bindata

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov this may have problems, since we have some hygiene problems with our fixture data.  Not everything is going to play well here, especially things that do docker builds.

**Comment by smarterclayton** [comment]
Looks like this is working - we won't get kube e2e though until 1.6 rebase lands.

@bparees because your tests pull in a lot of stuff

**Comment by bparees** [comment]
looks reasonable to me, but what's the motivation?  making the extended test execution more self-contained?

**Comment by bparees** [comment]
[testextedend][extended:core(builds)]
(you'll want to run a lot more extended buckets than that, but we still have the issue of running out if thin pool space when we run too many tests)

**Comment by smarterclayton** [comment]
So you can run e2e tests from the rpm built binary.  Kube is doing this as
well, but eventually you just e2e test from this.

I'm going to move test-cmd into this as wel.

On Mar 12, 2017, at 11:29 PM, OpenShift Bot <notifications@github.com>
wrote:

continuous-integration/openshift-jenkins/testextended Running (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/13/)
(Base Commit: 18b1328
<https://github.com/openshift/origin/commit/18b1328a85d32551f434f05676436dbc64c4dc87>)
(Extended Tests: core(builds))

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/13361#issuecomment-286007760>,
or mute
the thread

**Comment by stevekuznetsov** [comment]
@bparees we want to be able to ship actually functional tests in the `origin-tests` RPM, etc

**Comment by smarterclayton** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by smarterclayton** [comment]
I've fixed all the normal build problems, any other comments @stevekuznetsov or @bparees or @csrwng ?

Once the image_ecosystem tests run I'm going to merge this and then advise people on how to fix.

**Comment by smarterclayton** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by csrwng** [comment]
LGTM

**Comment by smarterclayton** [comment]
Green.  Will merge tomorrow unless other comments.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
ActivateDevice flake [merge]

**Pull request merged**
