### PR TITLE
Add logging for etcd integration tests

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@csrwng I plan to merge this once the integration tests pass with it

**Comment by csrwng** [comment]
@liggitt I'd added somewhat different logging here: https://github.com/csrwng/origin/commit/cb48b75625667fb27ad1dc55557c3afd270e1f01

My guess is that one of two things is happening:
1)  a goroutine from the previous test is still active when we capture the list of root keys. When we get to the point of deleting one of them, we fail ... in that case it'd be useful to get a dump of goroutines at the time we get the list to see what's lingering from the previous test

2) deleting a key somehow triggers the deletion of another key that was in the original list... which I would think is less likely.

**Comment by liggitt** [comment]
1 shouldn't be possible... each integration test runs in its own process
2 also shouldn't be possible, but I'm logging just in case

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
