### PR TITLE
pin dependencies for 3.9

### PR DESCRIPTION
**Pull request by deads2k**
`_output/depcheck pin --glide.yaml=glide.yaml --glide.lock=glide.lock` and pinning openshift/api and openshift/client-go to a branch

@openshift/sig-master 

@mfojtik we're missing 147a3ddb66658b65c022b3b36be0cb94e2a3c478 in the kube fork, so we can't update :(

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k commit added

**Comment by deads2k** [comment]
Forks are fixed.  Ran `hack/update-deps.sh` and got what we expected.

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/18823

/retest

**Pull request merged**
