### PR TITLE
Use  webconsole.config.openshift.io/v1 API group

### PR DESCRIPTION
**Pull request by spadgett**
See https://github.com/openshift/api/pull/29

/assign @deads2k 
@jwforres cc

### CODE REVIEW

**Comment by spadgett** [comment]
We might need to wait until there's a v3.9.0-alpha.2. Cluster up with fail with alpha.1 with these changes since it won't recognize the new type.

**Comment by deads2k** [comment]
@stevekuznetsov @bparees Where do we capture the container logs for the clusterup tests?  https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18056/test_pull_request_origin_extended_clusterup/286/

**Comment by deads2k** [comment]
> We might need to wait until there's a v3.9.0-alpha.2. Cluster up with fail with alpha.1 with these changes since it won't recognize the new type.

@smarterclayton Can we get a new tag?  We just switched API objects and I'd like to complete the cut over

**Comment by spadgett** [comment]
The extended cluster up test is still trying to use alpha.1 even though there's an alpha.2 tag.

@stevekuznetsov It looks like we don't have all of the git tags when `oc` is built for these tests. Locally when I `git fetch --tags upstream` and build `oc`, it clusters up with alpha.2.

@bparees FYI

**Comment by spadgett** [comment]
@stevekuznetsov Disregard, it looks like the tests are passing now. I might have been looking at an old log.

**Pull request merged**
