### PR TITLE
Truncate rev.Git.Message on the first line

### LINKED ISSUE #13841: oc status commit message on builds destroys layout
```
oc status
In project OpenShift CI (ci) on server https://api.ci.openshift.org:443

bc/oauth-proxy docker builds Dockerfile on docker.io/library/busybox:latest
  -> istag/oauth-proxy:latest
  build #9 succeeded 5 seconds ago

bc/oauth-proxy-binary docker builds https://github.com/openshift/oauth-proxy.git on docker.io/openshift/origin-release:golang-1.7
  -> istag/oauth-proxy:binaries
  build #9 succeeded 21 seconds ago - 423edf1: Add -client-secret-file and -cookie-secret-file (Clayton Coleman <ccoleman@redhat.com>)
  build #3 failed 5 days ago - 2ce1a72: Add an OpenShift auth provider (Clayton Coleman <ccoleman@redhat.com>)

bc/prometheus docker builds Dockerfile on docker.io/library/busybox:latest
  -> istag/prometheus:latest
  build #11 succeeded 3 days ago
  build #4 failed 5 days ago

bc/prometheus-binary docker builds https://github.com/openshift/prometheus.git on docker.io/openshift/origin-release:golang-1.7
  -> istag/prometheus:binaries
  build #9 succeeded 3 days ago - 9fbeefc: UPSTREAM: Allow bearer token and basic auth to be discovered

In order to automate simple discovery in a tenanted system, add support
for `__bearer_token__', `__basic_auth_username__`, and
`__basic_auth_password__` to be set during relabel and applied to the
client config. (Clayton Coleman <ccoleman@redhat.com>)
  build #4 failed 5 days ago - bd1182d: Merge pull request #2415 from prometheus/beorn7/release (Björn Rabenstein <bjoern@rabenste.in>)

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

The full commit message is probably not useful, or at minimum should be aligned.  I'd be inclined to truncate on the first completed line.

### PR DESCRIPTION
**Pull request by matthyx**
Fixes #13841

### CODE REVIEW

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/14385
/retest

**Comment by stevekuznetsov** [comment]
@bparees I still don't understand why we are doing all this... there is a specific field in the commit object that we want. It's the subject. We should use `git log -1 --pretty=%s` to extract it and only it from the commit instead of all this stuff with `git show`, truncation, and now line splitting  ...

**Comment by bparees** [comment]
flake `2017-07-30T03:41:54.115379000Z F0730 03:41:54.114669       1 helpers.go:119] error: build error: fatal: unable to access 'https://github.com/openshift/ruby-hello-world/': Could not resolve host: github.com; Unknown error`

presumably a network issue, possibly an issue w/ GCe provisioning in general.

/retest

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/15548
/retest

**Pull request merged**
