### PR TITLE
UPSTREAM: 27048: fixes to the kubectl scaler

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@smarterclayton @ironcladlou @mfojtik this is huge for UX

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
Right after the rebase?

**Comment by kargakis** [comment]
I am fine with it

**Comment by kargakis** [comment]
@mfojtik can I get a review for this?

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
conformance tests never came up, re[merge]

**Pull request merged**
