### PR TITLE
Bug 2043042: Additional checks for requestheaders.go

### PR DESCRIPTION
**Pull request by slaskawi**
https://bugzilla.redhat.com/show_bug.cgi?id=2043042

This Pull Request adds a generation check and a missing `X-CSRF-Token` header to the `[Serial] [sig-auth][Feature:OAuthServer] [RequestHeaders] [IdP]`. This should help stabilizing the test or at least, make failure investigation easier in the future.

It also adds additional check to make explicitly sure the CAO is stable before executing the test.

### CODE REVIEW

**Comment by slaskawi** [comment]
First one went fine, let's see the second pass.

/retest

**Comment by slaskawi** [comment]
Second run is fine, let's try more

/test all

**Comment by slaskawi** [comment]
Fourth run is fine, last time lucky...

/test all

**Comment by deads2k** [comment]
heavily tested, no conflict with other merges

**Pull request merged**
