### PR TITLE
More 'help' usability improvements

### PR DESCRIPTION
**Pull request by fabianofranz**
- Remove usage from the list of available commands in help
- Fix help line breaks
- Better footer messages in help
- Fixes base command reference (osc || openshift cli) in help
- ~~Makes global options osc options --help~~ actually back to `osc options`

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton @jwforres

**Comment by jwforres** [comment]
what is the difference between `osc options` and `osc options --help`

**Comment by fabianofranz** [comment]
@jwforres None, they do exactly the same.

**Comment by jwforres** [comment]
When you run openshift we say

"Use "openshift help [command]" for more information about that command."

And when you run openshift cli we say

"Use "openshift cli <command> --help" for more information about a given command."

The phrasing and the use of [ ] vs < > is inconsistent

**Comment by fabianofranz** [comment]
@jwforres Any preference? I was keeping the admin and cli with separate templates (admin being mostly the default Cobra template), but I agree it should be consistent. I would say to use `<command>` since `[--this]` is usually used to refer optional flags.

**Comment by jwforres** [comment]
@fabianofranz I agree \<command\> is better than [command]

**Comment by smarterclayton** [comment]
Any other comments?

**Comment by fabianofranz** [comment]
@jwforres fixed

**Comment by jwforres** [comment]
@smarterclayton nothing else from me

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
