### PR TITLE
clean up wording of oc status build/deployment descriptions

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/6585

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov @deads2k ptal.  guessing this is going to cause a bunch of test failures, i'll fix those after the wording change is agreed on.

**Comment by bparees** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Changes LGTM - will read much better for humans. Maybe not so much @deads2k

**Comment by bparees** [comment]
[merge]

**Pull request merged**
