### PR TITLE
Bug 1839933: UPSTREAM: 91307: CSI: Modify VolumeAttachment check to use Informer/Cache

### PR DESCRIPTION
**Pull request by jsafrane**
Fix slow attach in OCP >= 4.4.

https://bugzilla.redhat.com/show_bug.cgi?id=1839933
https://github.com/kubernetes/kubernetes/pull/91307
cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
This PR should not touch scheduler unit tests that timed out twice in this PR...

**Comment by humblec** [comment]
LGTM from my side and this is a critical fix too !

**Pull request merged**
