### PR TITLE
Vagrant setup for ovs-simple as an overlay network

### PR DESCRIPTION
**Pull request by rajatchopra**
Pulls down this [repo](https://github.com/openshift/openshift-sdn) and creates an overlay network automatically. To enable, just set OPENSHIFT_SDN=ovs-simple

    export OPENSHIFT_DEV_CLUSTER=1
    export OPENSHIFT_SDN=ovs-simple
    make clean
    vagrant up

### CODE REVIEW

**Comment by rajatchopra** [comment]
@mrunalp review please

**Comment by mrunalp** [comment]
LGTM

**Comment by rajatchopra** [comment]
[test]

**Comment by rajatchopra** [comment]
[merge]

**Pull request merged**
