### PR TITLE
make start.config non-mutating, fix --kubeconfig handling

### PR DESCRIPTION
**Pull request by liggitt**
Extension of https://github.com/openshift/origin/pull/1128

@smarterclayton this is worthwhile to get in now:
* makes the 11,000,000 different ways of running `openshift start` testable
* lets you trigger external kubernetes mode with either `--kubernetes=...` or `--kubeconfig=...`
* prevents credentials in --kubeconfig from being sent to the wrong server if --kubernetes was also set and pointed somewhere else
* lays the groundwork for separating start into stages later (input stage, host calculation/defaulting stage, bootstrapping/cert generation stage, execute stage)

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k review my commits?

**Comment by deads2k** [comment]
Well, my schedule definitely didn't include 2am... :)

**Comment by deads2k** [comment]
I like it.  I just want to make sure I can launch it in an integration test and then I'd say it's good.

**Comment by smarterclayton** [comment]
> On Feb 25, 2015, at 11:24 PM, Jordan Liggitt <notifications@github.com> wrote:
> 
> Extension of #1128
> 
> @smarterclayton this is worthwhile to get in now:
> 
> makes the 11,000,000 different ways of running openshift start testable
Citation needed

**Comment by deads2k** [comment]
> Citation needed

Authorization integration tests are needed and this fix makes it easy to do.  By clearly splitting responsibilities in start.go, we were able to write a series of unit tests to catch edges, both on general defaulting and on the bindings of those config values to the command line.

**Comment by smarterclayton** [comment]
That was a joke on the 11 million

**Comment by smarterclayton** [comment]
See comments, otherwise this looks like an excellent refactoring, thank you David and Jordan

**Comment by liggitt** [comment]
comments addressed, squashed as much as I plan to (david's together for credit/blame, mine together for credit/blame, two small unrelated fixes as separate commits)

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
the test worked, probably a transient.  re[merge]

**Pull request merged**
