### PR TITLE
update go-bindata

### PR DESCRIPTION
**Pull request by liggitt**
Related to #3586

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@jwforres review, but don't merge yet

**Comment by jwforres** [comment]
So what does the mode=493 do

**Comment by liggitt** [comment]
mode and modtime are used to preserve file mode and timestamps in the getters that return assets. we're not using them, but I'm locking them to 755 and timestamp=1 to avoid artificial diffs on travis/jenkins

**Comment by jwforres** [comment]
ah i see your comment now, 493 == 755

changes LGTM whenever you want to merge

**Comment by jwforres** [comment]
Oddly enough this is producing a single diff line right now:

```
-	info := bindataFileInfo{name: "404.html", size: 3414, mode: os.FileMode(436), modTime: time.Unix(1439316095, 0)}
+	info := bindataFileInfo{name: "404.html", size: 3414, mode: os.FileMode(493), modTime: time.Unix(1, 0)}
```

**Comment by liggitt** [comment]
it's probably producing lots, we just show the initial chunks of the diff...

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
