### PR TITLE
[WIP][cluster add] Report error adding router if web ports are in use

### LINKED ISSUE #10665: oc cluster up should check and error/warn if ports 80/443 already in use
If port 80 is already in use by a web server on the hist when running ``oc cluster up``, there is no error or warning when starting up. What happens is that the router pod keeps failing instead and so although the web interface works and can deploy applications, you can't access the deployed applications. If you use docker logs on dead router containers they show no errors.

The ``oc cluster up`` command should perhaps do a TCP connection to both 80 and 443 when run and warn that the ports are already in use and that routing may not work for applications.

So what normally expect to see from ``docker ps`` is:

```
CONTAINER ID        IMAGE                                                                                                          COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
33a27c112089        172.30.42.184:5000/myproject/wagtail@sha256:5df865eb590ec71fb9a45b9a98b7a8863e65bed3cbf0bf8fd70d6a5d1ca74984   "container-entrypoint"   15 minutes ago      Up 15 minutes                                                                          k8s_wagtail.a0b2fe21_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_f2f9920b
55130194ce03        172.30.42.184:5000/myproject/hello@sha256:4488e828e3cf7ba562dd213838fa0a527bd99b08a93447a5711becfcf094247d     "container-entrypoint"   15 minutes ago      Up 15 minutes                                                                          k8s_hello.7407bde5_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_441f972b
0a90f8b8b932        openshift/origin-haproxy-router:v1.3.0-alpha.3                                                                 "/usr/bin/openshift-r"   15 minutes ago      Up 15 minutes                                                                          k8s_router.b2493d1b_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_4dd0cbb3
7797adc309f7        openshift/origin-docker-registry:v1.3.0-alpha.3                                                                "/bin/sh -c 'DOCKER_R"   15 minutes ago      Up 15 minutes                                                                          k8s_registry.37080643_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_187bf85b
122ce3815535        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   15 minutes ago      Up 15 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:1936->1936/tcp   k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_44567a6e
3a577c8b5af9        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   15 minutes ago      Up 15 minutes                                                                          k8s_POD.f98c0130_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_fc361b0b
c7ded9a6ee05        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   15 minutes ago      Up 15 minutes                                                                          k8s_POD.f98c0130_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_b704106c
8531bddd7ce7        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   15 minutes ago      Up 15 minutes                                                                          k8s_POD.e4a40125_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_bd2782e1
eaceae32fe3f        openshift/origin:v1.3.0-alpha.3                                                                                "/usr/bin/openshift s"   15 minutes ago      Up 15 minutes                                                                          origin
```

If start up Apache httpd server on port 80 and run ``oc cluster up``, then out all looks normal.

```
- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.0-alpha.3 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Checking Docker version ... OK
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.178.53 as the server IP
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ...
   Already on project "myproject" on server "https://192.168.178.53:8443".
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.178.53:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

The router pod doesn't show as running in ``docker ps``.

```
CONTAINER ID        IMAGE                                                                                                          COMMAND                  CREATED             STATUS              PORTS               NAMES
476eb0da098b        172.30.42.184:5000/myproject/wagtail@sha256:5df865eb590ec71fb9a45b9a98b7a8863e65bed3cbf0bf8fd70d6a5d1ca74984   "container-entrypoint"   31 seconds ago      Up 30 seconds                           k8s_wagtail.a0b2fe21_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_57c70440
24ff28b1005e        172.30.42.184:5000/myproject/hello@sha256:4488e828e3cf7ba562dd213838fa0a527bd99b08a93447a5711becfcf094247d     "container-entrypoint"   32 seconds ago      Up 32 seconds                           k8s_hello.7407bde5_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_8448fa36
fc09d8f5251c        openshift/origin-docker-registry:v1.3.0-alpha.3                                                                "/bin/sh -c 'DOCKER_R"   46 seconds ago      Up 46 seconds                           k8s_registry.37080643_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_b042101c
a258fb54eb4f        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   47 seconds ago      Up 46 seconds                           k8s_POD.f98c0130_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_90e35c2b
8d02c9a742d7        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   47 seconds ago      Up 46 seconds                           k8s_POD.e4a40125_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_994a0097
77d7d0f706c8        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   47 seconds ago      Up 46 seconds                           k8s_POD.f98c0130_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_70fa4e88
aff1d797b617        openshift/origin:v1.3.0-alpha.3                                                                                "/usr/bin/openshift s"   58 seconds ago      Up 57 seconds                           origin
```

If you run ``docker ps -a`` you can though see many failed router pods.

```
CONTAINER ID        IMAGE                                                                                                          COMMAND                  CREATED              STATUS              PORTS               NAMES
6160dacd9ae2        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   10 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_55b57733
6e7c0140583d        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   24 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_18dd0ab7
1750c23d341e        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   38 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_424b467e
a8567a2edc80        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   51 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_cbb66b1a
c157a4d62e7a        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   52 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_0908136f
4811d6bb8506        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   58 seconds ago       Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_24e74743
589d8af5cf32        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   About a minute ago   Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_b635041d
3d4af8c45b8e        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   About a minute ago   Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_524edd4a
7418063b633b        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   About a minute ago   Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_bfcc582a
cdb3377f69d6        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   About a minute ago   Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_a1a8fbb0
b317f733e393        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   2 minutes ago        Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_1a7804f2
c43af56738b0        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   2 minutes ago        Created                                 k8s_POD.561a4a31_router-1-dz2wk_default_f57c2c14-6b35-11e6-9a94-8edd4be1d78f_1a40c13f
476eb0da098b        172.30.42.184:5000/myproject/wagtail@sha256:5df865eb590ec71fb9a45b9a98b7a8863e65bed3cbf0bf8fd70d6a5d1ca74984   "container-entrypoint"   2 minutes ago        Up 2 minutes                            k8s_wagtail.a0b2fe21_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_57c70440
24ff28b1005e        172.30.42.184:5000/myproject/hello@sha256:4488e828e3cf7ba562dd213838fa0a527bd99b08a93447a5711becfcf094247d     "container-entrypoint"   2 minutes ago        Up 2 minutes                            k8s_hello.7407bde5_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_8448fa36
fc09d8f5251c        openshift/origin-docker-registry:v1.3.0-alpha.3                                                                "/bin/sh -c 'DOCKER_R"   2 minutes ago        Up 2 minutes                            k8s_registry.37080643_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_b042101c
a258fb54eb4f        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   2 minutes ago        Up 2 minutes                            k8s_POD.f98c0130_wagtail-2-3l4ms_myproject_e8615470-6b38-11e6-9a94-8edd4be1d78f_90e35c2b
8d02c9a742d7        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   2 minutes ago        Up 2 minutes                            k8s_POD.e4a40125_docker-registry-1-ldnfy_default_f59e60f5-6b35-11e6-9a94-8edd4be1d78f_994a0097
77d7d0f706c8        openshift/origin-pod:v1.3.0-alpha.3                                                                            "/pod"                   2 minutes ago        Up 2 minutes                            k8s_POD.f98c0130_hello-1-2bfkb_myproject_c7ba53cb-6b36-11e6-9a94-8edd4be1d78f_70fa4e88
aff1d797b617        openshift/origin:v1.3.0-alpha.3                                                                                "/usr/bin/openshift s"   2 minutes ago        Up 2 minutes                            origin
```

As said above, using ``docker logs`` on any of the router pods shows no log messages at all, so would have to guess issue is that something is running on port 80.

### PR DESCRIPTION
**Pull request by adambkaplan**
Fixes #10665

### CODE REVIEW

**Comment by bparees** [comment]
/unassign @deads2k 
(you can ignore it for now I guess since it's a WIP)

**Comment by deads2k** [comment]
/assign @mfojtik 

this screams, "i broke when I switched to remote docker".

**Comment by adambkaplan** [comment]
My understanding is if `--host-ports=true` for the router, it will bind to the host machine's HTTP and HTTPS ports. Is this not the case?

**Comment by adambkaplan** [comment]
Closing, since there's been quite a few changes to cluster up since this change was written.

**Pull request closed without merging**
