### PR TITLE
SCC admission plugin: extract name to a constant

### PR DESCRIPTION
**Pull request by php-coder**
I hope that it won't create unnecessary package coupling.

PTAL @pweil- @liggitt
CC @simo5

### CODE REVIEW

**Comment by php-coder** [comment]
Test flake https://github.com/openshift/origin/issues/17873
/test extended_conformance_gce

**Comment by php-coder** [comment]
@pweil- @enj PTAL

**Comment by enj** [comment]
/approve

@deads2k please LGTM if you are happy with the change to the dependency graph.

**Comment by deads2k** [comment]
> /approve
> 
> @deads2k please LGTM if you are happy with the change to the dependency graph.

We may end up taking this in the other direction (dependency-wise), but I'm ok with it for now since we already depend in that direction.

/lgtm

**Comment by php-coder** [comment]
Test flake #17969
/test extended_conformance_gce

**Comment by php-coder** [comment]
Test flake #17605
/test extended_conformance_install

**Comment by php-coder** [comment]
Tests failed because of #17985 
I'll re-run them later when it will be fixed.

**Comment by php-coder** [comment]
e2e test failed because of #18000
/test end_to_end

**Comment by php-coder** [comment]
Test flake #16994 
/test extended_conformance_install

**Comment by php-coder** [comment]
The following 3 tests failed:
- `[Feature:Builds][Conformance] build without output image building from templates should create an image from a S2i template without an output image reference defined [Suite:openshift/conformance/parallel]`
- `[sig-api-machinery] Downward API should provide host IP as an env var [Conformance] [Suite:openshift/conformance/parallel] [Suite:k8s]`
- `[sig-storage] Projected should be able to mount in a volume regardless of a different secret existing with same name in different namespace [Suite:openshift/conformance/parallel] [Suite:k8s]`

Most likely all they were killed by timeout:
```
[INFO] test/extended/conformance.sh exited with code 0 after 01h 38m 58s
make: *** [test-extended] Terminated

	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
```

/test extended_conformance_gce

**Pull request merged**
