### PR TITLE
UPSTREAM: 19481: make patch call update admission chain after applyin…

### PR DESCRIPTION
**Pull request by deads2k**
…g the patch

@csrwng  try building on top of this.
@liggitt ptal

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by csrwng** [comment]
see comments in upstream pull

**Comment by deads2k** [comment]
@csrwng fixed.

**Comment by csrwng** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
