### PR TITLE
Introduce staging

### PR DESCRIPTION
**Pull request by tnozicka**
We need to stop modifying files in `vendor` directory because due to it OpenShift itself can't be vendored by other projects!

There are two main issues with it:
1. Golang conventions say that `vendor` is disposable and the tools threat it that way. 
Meaning they will strip it and for [a good reason](https://github.com/Masterminds/glide/blame/245caced2b16358b1c5e267691b17e9ee9952127/docs/vendor.md#L23-L26). Also [proposing support for our use case](https://github.com/golang/dep/issues/982) to [golang/dep](https://github.com/golang/dep) didn't went very well.

2. The unit of dependency is a repository
We vendor code that can't be found in any repository because due to patches the upstream repo is unusable and we don't periodically mirror the patches to our fork or we don't even have one for some repos.

This PR is tying to solve 1. By having the patched code in different folder vendor directory can be stripped and you can hack it by forcing dependency tool to use similar enough upstream revision and rewrite them with symlinks to `staging`. It  preserves the easy workflow and testability we had, and takes us a step forward to 2.

To address 2. we need to periodically sync the content of staging into appropriate repositories in github.com/openshift. Kubernetes does this so we can probably adopt that approach or slightly modify it in future.

CC: @sttts @smarterclayton @deads2k @mfojtik

### CODE REVIEW

**Comment by deads2k** [comment]
This does not appear to match the use of staging upstream, where we make use of it to indicate code that is owned by the containing org and is pushed out.  I wouldn't expect to have external repos in my staging folders here.

**Comment by tnozicka** [comment]
@deads2k yes, this is a bit different considering those are forks but the workflow is the same. We need to publish that content (patched forks) to our fork's repositories. If you can thing of better name for the staging dir I am open to it.

**Comment by deads2k** [comment]
> @deads2k yes, this is a bit different considering those are forks but the workflow is the same. We need to publish that content (patched forks) to our fork's repositories. If you can thing of better name for the staging dir I am open to it.

If you want to publish certain repos out of our vendor folders, why not just publish those out of our vendor folder?  That would keep the overall ownership of various directories consistent.

**Comment by tnozicka** [comment]
@deads2k we shouldn't store patches in vendor because that folder is supposed to be disposable.

If a dependency tool will strip vendor, you can still create a symlink e.g. from vendor/k8s.io/kubernetes into vendor/github.com/openshift/origin/staging/src/k8s.io/kubernetes to vendor exactly the version of kubernetes, openshift was tested with.

Including external repositories is harder because for a particular e.g. OpenShift commit it's hard to find the corresponding versions in all of those fork repositories unless you are using a tag. (I know there is a kubernetes-sha in upstream but you have to find the closest commit in the main repo touching staging/... to use it - and do that for every fork

**Comment by sttts** [comment]
We can call the staging dir `forks`. Then the name matches the purpose.

About usage: does a `cd vendor/k8s.io/kubernetes; patch -p1 < $KUBE_ROOT/my-kube-patch.diff` work?

**But**, I agree with @deads2k's doubts:

In our current development process we do not fork apimachinery, apiserver, etc. but we fork k8s.io/kubernetes. Moving the vendor/k8s.io/kubernetes/staging repos somewhere else is misleading IMO, and probably complicates our main development process for the sake of easier vendoring. Instead I would expect that we export/publish the staging dirs from our openshift/kubernetes fork, potentially using the same publish scripting as upstream. Then the main origin development stays easy (and as near to upstream as possible) and we can also reach (2).

Moreover, if we really want to fulfil (2) (I think we should), we have to get our openshift/kubernetes fork up-to-date. There is an issue for that: https://github.com/openshift/aos-cd-jobs/issues/279.

**Comment by tnozicka** [comment]
I am fine with calling it `forks` if that's what we can agree on.

> In our current development process we do not fork apimachinery, apiserver, etc. but we fork k8s.io/kubernetes. Moving the vendor/k8s.io/kubernetes/staging repos somewhere else is misleading IMO, and probably complicates our main development process for the sake of easier vendoring. Instead I would expect that we export/publish the staging dirs from our openshift/kubernetes fork, potentially using the same publish scripting as upstream. Then the main origin development stays easy (and as near to upstream as possible) and we can also reach (2).

@sttts I agree with what you're saying here.

> Moreover, if we really want to fulfil (2) (I think we should), we have to get our openshift/kubernetes fork up-to-date. There is an issue for that: openshift/aos-cd-jobs#279.

Yes, and not just that. I found 5 other repositories we cary patches to that we have to create forks for and sync the changes there. (namely: `github.com/containers/image` `github.com/docker/engine-api` `github.com/docker/distribution` `github.com/emicklei/go-restful-swagger12` `github.com/opencontainers/runc`)

@sttts @deads2k openshift/aos-cd-jobs#279 seems like doing it 2 ways and I have my doubts about that. I get what's that trying to do - updating Godeps back in origin to reach consistency. But assuming there will always be N number of commits in between those 2 it will give you a false feeling of consistency that is broken in the interim.
I believe it would be cleaner and easier to sync it only 1 way and that's also what Kubernetes does AFIK. 
Go through vendored packages in `forks` and for every commit to particular package that's not in `github.com/openshift/<fork-name>` create a commit containing `openshift-sha` in its name and push it to `github.com/openshift/<fork-name>`.
If I move the k8s.io symlinks from https://github.com/tnozicka/origin/tree/introduce-staging/vendor/k8s.io to `staging` that algorithm should also cover publishing those repositories from `staging/src/k8s.io/kubernetes/staging` and do what @sttts is mentioning above

**Comment by deads2k** [comment]
> updating Godeps back in origin to reach consistency.

That needs to be done or you still can't vendor based on our fork.  If you do it with a bot, the delta will be minimal and won't require having a separate vendor folder for our deps.

**Comment by tnozicka** [comment]
The issue is that if pick a random commit in origin this will randomly work or not :/
I would rather consistently specify it.

Also with the move form vendor into staging/forks there might be a door opening for not having to do that at all. Dependency tool will strip a vendor and by convention it is allowed to, but if we have it in staging and the tool supports "subpath"/"alternateRoot" you can include it directly from origin

**Comment by tnozicka** [comment]
> That needs to be done or you still can't vendor based on our fork.

@deads2k you can vendor it - it is actually what kubernetes does. if you want to find the appropriate commits e.g. in client-go - from the kubernetes commit you picked, find the latest commit on your way back in git tree that modifies staging/client-go (like go to github enter staging/client-go and it tells you e.g. f6401. Then run:
```
REPO=client-go && git --git-dir=${GOPATH}/src/k8s.io/${REPO}/.git --work-tree=${GOPATH}/src/k8s.io/${REPO} log --all --follow -- kubernetes-sha | grep -B4 f6401
```
and you have the corresponding client-go commitId that you use for your vendoring tool

**Comment by tnozicka** [comment]
giving up

**Pull request closed without merging**
