### PR TITLE
add etcd dump for integration test

### PR DESCRIPTION
**Pull request by deads2k**
Adds debugging for https://github.com/openshift/origin/issues/9803

@smarterclayton @soltysh review in principle, I'd like to merge this.  I'm willing to add it to add the tests if we want to.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by kargakis** [comment]
LGTM

**Comment by deads2k** [comment]
[merge] The next time we need it, I'll add it to all tests.

**Comment by deads2k** [comment]
merge pretest-success to gather more info for the next failure.

**Pull request merged**
