### PR TITLE
Bug 1275003: expose: Set route port based on service target port

### PR DESCRIPTION
**Pull request by kargakis**
Route should be using the port used from the endpoints of the service
and not the port the service is exposing.

@pweil- @smarterclayton @thoraxe

### CODE REVIEW

**Comment by kargakis** [comment]
Note that this changes the behavior of port inheritance for exposing services as services.

So previously in `oc expose svc/mysql --name=mysql2 --generator=service/v2` mysql2 would inherit the ports mysql was exposing, now it will expose the ports that mysql's endpoints are serving on.

To be honest, I am not sure why someone would expose services as services...

**Comment by smarterclayton** [comment]
[test]

**Comment by kargakis** [comment]
> Note that this changes the behavior of port inheritance for exposing services as services.
> 
> So previously in oc expose svc/mysql --name=mysql2 --generator=service/v2 mysql2 would inherit the ports mysql was exposing, now it will expose the ports that mysql's endpoints are serving on.
> 
> To be honest, I am not sure why someone would expose services as services...

I have restored the previous behavior because I think this was wrong. A multiport service could have the same target port for every port.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
