### PR TITLE
remove juanvallejo from OWNERS files

### PR DESCRIPTION
**Pull request by juanvallejo**
cc @soltysh @deads2k

### CODE REVIEW

**Comment by bparees** [comment]
/assign @soltysh 
(since your name is being substituted, you should probably be the one to sign off :) )

**Comment by mfojtik** [comment]
😢

**Comment by danwinship** [comment]
> openshift-ci-robot reacted with hooray emoji

well, I guess the bot never liked you...

**Comment by soltysh** [comment]
> well, I guess the bot never liked you...

:man_facepalming: :stuck_out_tongue_closed_eyes:

**Pull request merged**
