### PR TITLE
Allow denying a prompted OAuth grant, allow configuring X-Remote-User header

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k grab bag of stuff I found when writing docs

**Comment by deads2k** [comment]
Minor comments, otherwise lgtm.

**Comment by liggitt** [comment]
comments addressed

**Comment by liggitt** [comment]
[merge]

**Comment by deads2k** [comment]
travis lies.  lgtm [merge]

**Pull request merged**
