### PR TITLE
update load-etcd for new client

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/13584

@jim-minter ptal.

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by deads2k** [comment]
re[merge]

**Comment by deads2k** [comment]
@stevekuznetsov Is there any better error reporting you can build on this page to help me track down matching flakes: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/40/ ?  Something like our junit style reporting which at least gives a specific test would help find matches and encourage flake issues.

re[merge]

**Comment by stevekuznetsov** [comment]
jUnit is on and exposed the error on that page:

screenshot from 2017-04-11 11-41-47

What are you looking for?

**Comment by stevekuznetsov** [comment]
Also if that's your excuse for you and @mfojtik not doing the good thing for the community and pointing out the flakes three different times in this PR ... apology not accepted.

**Comment by deads2k** [comment]
> What are you looking for?

That error looks really generic.  That's actually the error, not just a "something somewhere went wrong" indicator for the ansible job?

**Comment by stevekuznetsov** [comment]
> That error looks really generic. That's actually the error, not just a "something somewhere went wrong" indicator for the ansible job?

That's the error Ansible spit out after trying to connect to the VM for ten minutes and failing. Unfortunately we just don't have anything more specific to show here.

**Comment by dobbymoodge** [comment]
@stevekuznetsov @deads2k Hey, when we see this error: `provision an AWS EC2 instance.[localhost] aws-up : wait for SSH to be available` - there's a better-than-zero chance the instance is running and waiting for input in emergency mode:
image

We need to figure out the best strategy for pruning these. Until then, maybe check behind these jobs and see if they left any debris like this.

**Comment by stevekuznetsov** [comment]
Whoa, that's weird. We should look to see how they get to that state and figure out how to work around it -- it may be an issue with how the Ansible modules make API calls to provision these instances.

**Pull request merged**
