### PR TITLE
admission_test.go: backport TestAdmitPrivileged() from Kubernetes

### LINKED ISSUE #16467: SCC is performing defaulting during a pod update
The rolling update command mutates pods.  The pod is running as the privileged scc.  An admin comes along and tries to run rolling update on that set.  An error is thrown because SCC defaults capabilities from a less restrictive role, preventing the update.

Workarounds:
* admin goes and removes themselves from less restrictive SCCs
* we fix defaulting so that it prefers more open defaults (already in progress?)

In this case, the pod is already part of the privileged SCC, and we know this is an update operation.  Since it's an update operation, we can't mutate all but a select group of fields.  Instead, we should probably revalidate the pod under the existing SCC and fail if the editing user doesn't have permission to mutate that object, but *not* perform defaulting for other SCCs.  Or we could not perform defaulting at all on updates (but if we ever loosen pod update rules we might break, so better safe than sorry).

Also applies to PSP

Initial pod:

```
{"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/foo/pods","resourceVersion":"34211"},"items":[{"metadata":{"name":"e2e-test-nginx-rc-wbt2p","generateName":"e2e-test-nginx-rc-","namespace":"foo","selfLink":"/api/v1/namespaces/foo/pods/e2e-test-nginx-rc-wbt2p","uid":"190536f8-9e88-11e7-a98d-42010a800002","resourceVersion":"34106","creationTimestamp":"2017-09-21T04:48:23Z","labels":{"run":"e2e-test-nginx-rc"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"foo\",\"name\":\"e2e-test-nginx-rc\",\"uid\":\"19039c2c-9e88-11e7-a98d-42010a800002\",\"apiVersion\":\"v1\",\"resourceVersion\":\"34090\"}}\n","openshift.io/scc":"privileged"},"ownerReferences":[{"apiVersion":"v1","kind":"ReplicationController","name":"e2e-test-nginx-rc","uid":"19039c2c-9e88-11e7-a98d-42010a800002","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"default-token-0x530","secret":{"secretName":"default-token-0x530","defaultMode":420}}],"containers":[{"name":"e2e-test-nginx-rc","image":"gcr.io/google_containers/nginx-slim:0.7","resources":{},"volumeMounts":[{"name":"default-token-0x530","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"role":"app"},"serviceAccountName":"default","serviceAccount":"default","nodeName":"ci-cc-conformance-17-ig-n-qrz4","securityContext":{},"imagePullSecrets":[{"name":"default-dockercfg-dv21w"}],"schedulerName":"default-scheduler"},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:23Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:25Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:23Z"}],"hostIP":"10.128.0.5","podIP":"172.16.6.82","startTime":"2017-09-21T04:48:23Z","containerStatuses":[{"name":"e2e-test-nginx-rc","state":{"running":{"startedAt":"2017-09-21T04:48:24Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"gcr.io/google_containers/nginx-slim:0.7","imageID":"docker-pullable://gcr.io/google_containers/nginx-slim@sha256:dd4efd4c13bec2c6f3fe855deeab9524efe434505568421d4f31820485b3a795","containerID":"docker://8dd0be5b415be66e6fb86d2fca13c2556891ca934683d23c953cb1fabfd4815f"}],"qosClass":"BestEffort"}}]}
```

Mutation made by admin

```
{"kind":"Pod","apiVersion":"v1","metadata":{"name":"e2e-test-nginx-rc-wbt2p","generateName":"e2e-test-nginx-rc-","namespace":"foo","selfLink":"/api/v1/namespaces/foo/pods/e2e-test-nginx-rc-wbt2p","uid":"190536f8-9e88-11e7-a98d-42010a800002","resourceVersion":"34106","creationTimestamp":"2017-09-21T04:48:23Z","labels":{"deployment":"1976bc8c0c48b9f2f1c2ee5f29c3c924-orig","run":"e2e-test-nginx-rc"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"foo\",\"name\":\"e2e-test-nginx-rc\",\"uid\":\"19039c2c-9e88-11e7-a98d-42010a800002\",\"apiVersion\":\"v1\",\"resourceVersion\":\"34090\"}}\n","openshift.io/scc":"privileged"},"ownerReferences":[{"apiVersion":"v1","kind":"ReplicationController","name":"e2e-test-nginx-rc","uid":"19039c2c-9e88-11e7-a98d-42010a800002","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"default-token-0x530","secret":{"secretName":"default-token-0x530","defaultMode":420}}],"containers":[{"name":"e2e-test-nginx-rc","image":"gcr.io/google_containers/nginx-slim:0.7","resources":{},"volumeMounts":[{"name":"default-token-0x530","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"role":"app"},"serviceAccountName":"default","serviceAccount":"default","nodeName":"ci-cc-conformance-17-ig-n-qrz4","securityContext":{},"imagePullSecrets":[{"name":"default-dockercfg-dv21w"}],"schedulerName":"default-scheduler"},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:23Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:25Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-09-21T04:48:23Z"}],"hostIP":"10.128.0.5","podIP":"172.16.6.82","startTime":"2017-09-21T04:48:23Z","containerStatuses":[{"name":"e2e-test-nginx-rc","state":{"running":{"startedAt":"2017-09-21T04:48:24Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"gcr.io/google_containers/nginx-slim:0.7","imageID":"docker-pullable://gcr.io/google_containers/nginx-slim@sha256:dd4efd4c13bec2c6f3fe855deeab9524efe434505568421d4f31820485b3a795","containerID":"docker://8dd0be5b415be66e6fb86d2fca13c2556891ca934683d23c953cb1fabfd4815f"}],"qosClass":"BestEffort"}}
```

422 error is returned:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"e2e-test-nginx-rc-wbt2p\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n{\"Volumes\":[{\"Name\":\"default-token-0x530\",\"HostPath\":null,\"EmptyDir\":null,\"GCEPersistentDisk\":null,\"AWSElasticBlockStore\":null,\"GitRepo\":null,\"Secret\":{\"SecretName\":\"default-token-0x530\",\"Items\":null,\"DefaultMode\":420,\"Optional\":null},\"NFS\":null,\"ISCSI\":null,\"Glusterfs\":null,\"PersistentVolumeClaim\":null,\"RBD\":null,\"Quobyte\":null,\"FlexVolume\":null,\"Cinder\":null,\"CephFS\":null,\"Flocker\":null,\"DownwardAPI\":null,\"FC\":null,\"AzureFile\":null,\"ConfigMap\":null,\"VsphereVolume\":null,\"AzureDisk\":null,\"PhotonPersistentDisk\":null,\"Projected\":null,\"PortworxVolume\":null,\"ScaleIO\":null,\"StorageOS\":null}],\"InitContainers\":null,\"Containers\":[{\"Name\":\"e2e-test-nginx-rc\",\"Image\":\"gcr.io/google_containers/nginx-slim:0.7\",\"Command\":null,\"Args\":null,\"WorkingDir\":\"\",\"Ports\":null,\"EnvFrom\":null,\"Env\":null,\"Resources\":{\"Limits\":null,\"Requests\":null},\"VolumeMounts\":[{\"Name\":\"default-token-0x530\",\"ReadOnly\":true,\"MountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"SubPath\":\"\"}],\"LivenessProbe\":null,\"ReadinessProbe\":null,\"Lifecycle\":null,\"TerminationMessagePath\":\"/dev/termination-log\",\"TerminationMessagePolicy\":\"File\",\"ImagePullPolicy\":\"IfNotPresent\",\"SecurityContext\":{\"Capabilities\":\n\nA: {\"Add\":null,\"Drop\":[\"MKNOD\"]},\"Privileged\":false,\"SELinuxOptions\":{\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c45,c35\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"role\":\"app\"},\"ServiceAccountName\":\"default\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"ci-cc-conformance-17-ig-n-qrz4\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":{\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c45,c35\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":[],\"FSGroup\":null},\"ImagePullSecrets\":[{\"Name\":\"default-dockercfg-dv21w\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\nB: null,\"Privileged\":false,\"SELinuxOptions\":null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"role\":\"app\"},\"ServiceAccountName\":\"default\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"ci-cc-conformance-17-ig-n-qrz4\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":null,\"FSGroup\":null},\"ImagePullSecrets\":[{\"Name\":\"default-dockercfg-dv21w\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\n","reason":"Invalid","details":{"name":"e2e-test-nginx-rc-wbt2p","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n{\"Volumes\":[{\"Name\":\"default-token-0x530\",\"HostPath\":null,\"EmptyDir\":null,\"GCEPersistentDisk\":null,\"AWSElasticBlockStore\":null,\"GitRepo\":null,\"Secret\":{\"SecretName\":\"default-token-0x530\",\"Items\":null,\"DefaultMode\":420,\"Optional\":null},\"NFS\":null,\"ISCSI\":null,\"Glusterfs\":null,\"PersistentVolumeClaim\":null,\"RBD\":null,\"Quobyte\":null,\"FlexVolume\":null,\"Cinder\":null,\"CephFS\":null,\"Flocker\":null,\"DownwardAPI\":null,\"FC\":null,\"AzureFile\":null,\"ConfigMap\":null,\"VsphereVolume\":null,\"AzureDisk\":null,\"PhotonPersistentDisk\":null,\"Projected\":null,\"PortworxVolume\":null,\"ScaleIO\":null,\"StorageOS\":null}],\"InitContainers\":null,\"Containers\":[{\"Name\":\"e2e-test-nginx-rc\",\"Image\":\"gcr.io/google_containers/nginx-slim:0.7\",\"Command\":null,\"Args\":null,\"WorkingDir\":\"\",\"Ports\":null,\"EnvFrom\":null,\"Env\":null,\"Resources\":{\"Limits\":null,\"Requests\":null},\"VolumeMounts\":[{\"Name\":\"default-token-0x530\",\"ReadOnly\":true,\"MountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"SubPath\":\"\"}],\"LivenessProbe\":null,\"ReadinessProbe\":null,\"Lifecycle\":null,\"TerminationMessagePath\":\"/dev/termination-log\",\"TerminationMessagePolicy\":\"File\",\"ImagePullPolicy\":\"IfNotPresent\",\"SecurityContext\":{\"Capabilities\":\n\nA: {\"Add\":null,\"Drop\":[\"MKNOD\"]},\"Privileged\":false,\"SELinuxOptions\":{\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c45,c35\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"role\":\"app\"},\"ServiceAccountName\":\"default\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"ci-cc-conformance-17-ig-n-qrz4\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":{\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c45,c35\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":[],\"FSGroup\":null},\"ImagePullSecrets\":[{\"Name\":\"default-dockercfg-dv21w\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\nB: null,\"Privileged\":false,\"SELinuxOptions\":null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"role\":\"app\"},\"ServiceAccountName\":\"default\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"ci-cc-conformance-17-ig-n-qrz4\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":null,\"FSGroup\":null},\"ImagePullSecrets\":[{\"Name\":\"default-dockercfg-dv21w\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\n","field":"spec"}]},"code":422}
```

Can potentially block important operations for admins.

### PR DESCRIPTION
**Pull request by php-coder**
This simplifies backporting kubernetes/kubernetes#52849 that is required for #16467

PTAL @openshift/sig-security

### CODE REVIEW

**Comment by liggitt** [comment]
I wouldn't expect anything other than the accessors to be picked from that PR, which are net new

**Comment by php-coder** [comment]
@liggitt Do you mean that we don't need to backport tests (especially from `admission_test.go`)?

**Comment by liggitt** [comment]
Correct. The only changes in that PR I'd expect us to pick up are the accessors, not the PSP admission changes. SCC would need changes almost identical, but parallel to, the PSP changes (and could use the same accessor approach)

**Comment by php-coder** [comment]
@liggitt At least this change from `provider.go` has the tests in `admission_test.go` file: https://github.com/kubernetes/kubernetes/pull/52849/commits/89ae6f2b20ff71a1ba5371db2f0162c37796f6a0 that's a bit unexpected from the first sight.

I thought that it's good to port them back too, but they require `TestAdmitPrivileged()` function.

Anyway, having these tests wound't hurt and also reduce the differences between our code and Kubernetes.

@liggitt If you object against this PR, please, close it. Otherwise, lgtm wouldn't hurt :)

**Comment by liggitt** [comment]
> @liggitt At least this change from provider.go has the tests in admission_test.go file: kubernetes/kubernetes@89ae6f2 that's a bit unexpected from the first sight.
> 
> I thought that it's good to port them back too, but they require TestAdmitPrivileged() function.
> 
> Anyway, having these tests wound't hurt and also reduce the differences between our code and Kubernetes.

Both are related to podsecuritypolicy, which we don't use yet. We don't backport unnecessary changes between releases... we just pick up the changes when we pick up the kube release.

**Pull request closed without merging**
