### PR TITLE
Add a changelog generator for GitHub releases

### PR DESCRIPTION
**Pull request by smarterclayton**
hack/update-changelog.sh openshift/origin v1.X.X v1.Y.Y

### CODE REVIEW

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
Can we use `tito` here?

**Comment by smarterclayton** [comment]
Does tito handle PRs?

**Comment by stevekuznetsov** [comment]
No just commits

**Comment by smarterclayton** [comment]
This is for GitHub and we link to PRs, so no.

On Jan 25, 2017, at 5:28 PM, Steve Kuznetsov <notifications@github.com>
wrote:

No just commits

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12657#issuecomment-275253319>,
or mute
the thread

**Pull request merged**
