### PR TITLE
make the router integration tests run as part of test-end-to-end

### PR DESCRIPTION
**Pull request by deads2k**
The router tests require images, no other integration test (that I found) does that.  This splits them out.

### CODE REVIEW

**Comment by kargakis** [comment]
Does it make more sense to move this in the extended suite?

**Comment by deads2k** [comment]
> Does it make more sense to move this in the extended suite?

That's going to require more detailed knowledge.  An issue is appropriate, but I think this can solve the immediate need without increasing debt outside this area.  We won't let new tests in.

**Comment by stevekuznetsov** [comment]
@deads2k 

```
KUBE_COVER=" " KUBE_RACE=" " OS_TEST_PACKAGE=test/end-to-end hack/test-integration.sh
[INFO] [CLEANUP] Cleaning up temporary directories
[WARNING] Skipping build due to OPENSHIFT_SKIP_BUILD
[ERROR] PID 9662: hack/test-integration.sh:51: `testexec="$(os::util::find::built_binary "${name}.test")"` exited with status 1.
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5058/consoleFull#941768175898c58db7602c31c0eab717

**Comment by deads2k** [comment]
@stevekuznetsov yeah.  Got advice for me on where to look?

**Comment by deads2k** [comment]
> @stevekuznetsov yeah. Got advice for me on where to look?

Oh, this is due to the skip build thing somehow?  What's that about?

**Comment by stevekuznetsov** [comment]
Router tests can't run inside of a container, either. We build inside of the container, then skip build and just run tests with the built binary outside of it. You'll want to add the test building logic

**Comment by deads2k** [comment]
@stevekuznetsov ok, if I'm understanding correctly, I'll need to update the jenkins jobs in a way that can't be done until this change merges since the new packages it will be building doesn't exist until this merges.

What can you suggest as a path forward?  I could move these tests.  Merge them (this would lose the tests for a little while).  Update the aos jobs to do the separate build in a container and run outside of one.  Merge that (this would restore the tests), and then confirm that the split jobs work.

How does that sound?

**Comment by stevekuznetsov** [comment]
The `hack/test-integration.sh` script expects the test binary that we use to be named whatever the test name is:

```sh
package="${OS_TEST_PACKAGE:-test/integration}"
name="$(basename ${package})"

# build the test executable
if [[ -n "${OPENSHIFT_SKIP_BUILD:-}" ]]; then
  os::log::warning "Skipping build due to OPENSHIFT_SKIP_BUILD"
else
	"${OS_ROOT}/hack/build-go.sh" "${package}/${name}.test"
fi
testexec="$(os::util::find::built_binary "${name}.test")"
```

You're building the integration binary in the job but not the end-to-end one:

```
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/integration.test hack/env make build-integration-test
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test -o check -o build -k
```

I guess an incremental step here is to update `make build-integration-test` to also build the e2e binary. Then, split it out once the new job is ready to use it. You'll need to add the e2e binary to the set of `$OS_BUILD_ENV_PRESERVE` in the job YAML, which is fine as if the preserve file is not found `hack/env` will just skip over it.

**Comment by stevekuznetsov** [comment]
```
+ hack/env make build-integration-test
[INFO] Pulling the openshift/origin-release:golang-1.8 image to update it...
Trying to pull repository registry.access.redhat.com/openshift/origin-release ... 

Trying to pull repository docker.io/openshift/origin-release ... 
golang-1.8: Pulling from docker.io/openshift/origin-release
Digest: sha256:c09258dfdee28cc0a875592bc82c573356b6909d64d3ea5cad905614978c1dbc
hack/build-go.sh test/end-to-end.test
++ Building go targets for linux/amd64: test/end-to-end.test
?   	github.com/openshift/origin/test	[no test files]
hack/build-go.sh took 108 seconds
```

@deads2k

**Comment by deads2k** [comment]
@stevekuznetsov looks like we're doing better now.

**Comment by stevekuznetsov** [comment]
@kargakis are we really supposed to be panicing the registry?

```
[INFO] Docker registry start with GCS
Running test/end-to-end/core.sh:207: executing 'docker run -e REGISTRY_STORAGE="gcs: {}" openshift/origin-docker-registry:bf5200f' expecting failure and text 'No bucket parameter provided'...
SUCCESS after 1.115s: test/end-to-end/core.sh:207: executing 'docker run -e REGISTRY_STORAGE="gcs: {}" openshift/origin-docker-registry:bf5200f' expecting failure and text 'No bucket parameter provided'
There was no output from the command.
Standard error from the command:
time="2017-07-31T18:19:25.130062271Z" level=info msg="version=v2.4.1+unknown" 
E0731 18:19:25.132069       1 clientcmd.go:223] invalid configuration: no configuration has been provided
panic: No bucket parameter provided

goroutine 1 [running]:
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x7f1c13cfdec8, 0xc4207fb5c0, 0xc4200b7b80, 0x7f1c13cfdec8)
	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-origin5JYlGw/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:121 +0x4cb
github.com/openshift/origin/pkg/cmd/dockerregistry.Execute(0x32766a0, 0xc42011c510)
	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-origin5JYlGw/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:82 +0x502
main.main()
	/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-origin5JYlGw/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/cmd/dockerregistry/main.go:58 +0x264
```

**Comment by kargakis** [comment]
> @kargakis are we really supposed to be panicing the registry?

A question for @dmage @legionus

**Comment by dmage** [comment]
https://github.com/openshift/origin/commit/005c45dffd86ff22a350f4129417e4c600c84fbc

This test was added to check if we are compiled with GCS driver. Panic is an upstream behaviour in case of misconfigured driver. So yes, we are.

**Pull request merged**
