### PR TITLE
oc: show ready pods next to deployments

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/6426

@mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis can we have test?

**Comment by kargakis** [comment]
@mfojtik [test] added, ptal

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/12060 [test]

**Comment by kargakis** [comment]
@mfojtik ping

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11292 [merge]

**Comment by kargakis** [comment]
flake is https://github.com/openshift/origin/issues/12157

**Comment by kargakis** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge] yum flake..

**Comment by mfojtik** [comment]
yum... [merge]

**Comment by mfojtik** [comment]
@kargakis so close :-) if not yum then dnf... [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/8571 [merge]

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
