### PR TITLE
Tito tagging vX.Y.Z

### PR DESCRIPTION
**Pull request by sdodson**
This teaches tito to tag openshift as "v%{version}" rather than the normal %{name}-%{version}-%{release} by way of additional changes to our existing custom tagger.

This does not currently support --use-version as tito does allow you configure the forcedversiontagger. PR for that https://github.com/dgoodwin/tito/pull/163

The first commit sets the stage for tito to work properly so i've included it in this PR.

### CODE REVIEW

**Comment by brenton** [comment]
I think it will be helpful for distro maintainers to upstream this so I'm all for that.  I don't think we'd want to incorporate tito tagging into the Origin release process though.

**Comment by sdodson** [comment]
@brenton Ok, then I'll look at adding steps to bump the RPM version, commit, and ldflags to hack/build-release.sh  Is that the most logical place in the release workflow? It's not entirely clear to me if cutting an official release includes all the steps prior to steps 1-6 in HACKING.md

**Comment by brenton** [comment]
@sdodson You can take a look at https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/build_openshift3.rb#L32.  That is used by the `openshift3_ami` job on https://ci.openshift.redhat.com/jenkins/.  That jobs handles most of the Origin release process.

As long as whatever we do doesn't break that CI job or complicate local development I think we can merge changes that improve distro maintenance.  Otherwise we'll need to talk with Clayton a bit.

**Comment by detiber** [comment]
@sdodson @brenton If we want to make this available for downstream users and not actually use tito to tag for origin, then we should probably have the version set to 0.4.1, that way downstream builds would be 0.4.1.x by default instead of 0.4.x.

**Comment by sdodson** [comment]
I think i'll hack up something quick that automates the git tag release step and updates the specfile at the same time.

**Comment by sdodson** [comment]
@brenton #1323 can handle tagging and bumping the specfile independently of tito

**Comment by sdodson** [comment]
I think this particular PR should be ready to go `tito tag`, `tito tag -u` both seem to work and generate the appropriate changelogs. The assumption would be that these would only be used downstream and that something else, like #1323 will be used to maintain the specfile upstream though that's not required.

**Comment by brenton** [comment]
That's awesome.  I'll look through the code again first thing tomorrow morning.

**Comment by smarterclayton** [comment]
@brenton what's the latest on this and the other release related pulls?  Can you triage them for close / moved / remains open?

**Comment by soltysh** [comment]
Maybe here https://github.com/openshift/origin/blob/master/docs/debugging-openshift.md ?

**Comment by soltysh** [comment]
Ignore that last comment of mine, wrong window. Sorry.

**Comment by brenton** [comment]
[merge]

**Pull request merged**
