### PR TITLE
Make oc cluster up install service-catalog by default

### PR DESCRIPTION
**Pull request by pmorie**
cc @bparees @spadgett @jboyd01 @jpeeler @luksa

### CODE REVIEW

**Comment by bparees** [comment]
/cc @mfojtik @deads2k 

This also has ramifications for the minishift+CDK teams so they should be informed.  What's the motivation for doing this, and for doing it this late in 3.9?  Among other things defaulting this on means it takes much longer for the cluster to start up.

**Comment by bparees** [comment]
you'll need to modify the cluster up extended test to ensure --service-catalog=false is now tested explicitly.

**Comment by deads2k** [comment]
/hold

@pmorie Given changes coming in 3.10, I'd prefer to wait to make this a default until the dust settles.  Is there a specific need driving this for 3.9?

**Comment by pmorie** [comment]
> Given changes coming in 3.10

Will you elaborate on what changes you're referring to, and why this is affected by them?

> Is there a specific need driving this for 3.9?

It's enabled in the installer by default in 3.7 onward - I think our story for oc cluster up should match the installer defaults.

WDYT?

**Comment by deads2k** [comment]
> Will you elaborate on what changes you're referring to, and why this is affected by them?

We're moving towards static pods and then components on top of that, installed with a structure of well-known templates already done by webconsole and tsb.

The issue I have with it is that the service catalog is installed differently than the "normal" install path of both the webconsole and the templateservicebroker in both cluster up and ansible.  I don't want to install a component by default that is "special".

Conform to the standard installation practices in 3.10 and having a default list of enable components seems ok.  

In addition, restructuring I'm actively doing at the moment will make the installation of components go much faster, adding it won't slow down cluster-up as much.



> It's enabled in the installer by default in 3.7 onward - I think our story for oc cluster up should match the installer defaults.

In general, I don't think the defaults for the constrained dev tool need to match the defaults for a production installation.

**Pull request closed without merging**
