### PR TITLE
fix non-compliant build integration tests

### PR DESCRIPTION
**Pull request by deads2k**
Removes pointless CRUD tests for builds to eliminate the fake API servers for builds.

@liggitt @kargakis step one on my path to eliminating all fake master API servers from our integration test, which will make it easier to launch separate etcds and run multiple integration tests in parallel.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
@liggitt On a clean integration run (regardless of e2e or test-cmd), I'd like to force merge to get us moving towards where we want to go.

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
I wouldn't force merge, though

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
