### PR TITLE
Bug 1850109: remove problematic upstream client plugin test

### PR DESCRIPTION
**Pull request by gabemontero**
@adambkaplan @akram @waveywaves fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
@bparees the e2e-gcp-builds passed with just my removal of the problematic portion in https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25179/pull-ci-openshift-origin-master-e2e-gcp-builds/1274727599406321664

if you search the successful tests you'll see 

`[sig-builds][Feature:Builds][sig-devex][Feature:Jenkins][Slow]  openshift pipeline build jenkins-client-plugin tests using the  ephemeral template [Suite:openshift] | 3m49s`

with a non trivial time ... it ran

As I said in the other PR, of course this can merge after your skip PR as needed

**Comment by gabemontero** [comment]
another passing jenkins client plugin test with it re-enabled after Ben's PR merge 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/25179/pull-ci-openshift-origin-master-e2e-gcp-builds/1274834458737905664

`[sig-builds][Feature:Builds][sig-devex][Feature:Jenkins][Slow]  openshift pipeline build jenkins-client-plugin tests using the  ephemeral template [Suite:openshift] | 3m27s`

**Comment by bparees** [comment]
lgtm but will let @akram sign off since it's disabling a test(that i understand is re-enabled by your other PR, i just don't want this going in w/o @akram and team understanding the relationship and being ok w/ the changes)

**Comment by gabemontero** [comment]
> lgtm but will let @akram sign off since it's disabling a test(that i understand is re-enabled by your other PR, i just don't want this going in w/o @akram and team understanding the relationship and being ok w/ the changes)

agreed @bparees @akram

**Comment by gabemontero** [comment]
install cluster flake in e2e-cmd

/retest

**Comment by gabemontero** [comment]
/assign @akram 

With https://github.com/openshift/jenkins-client-plugin/pull/338 I've proven both successful and failed test job run in the jenkins-client-plugin repo ... basically that is the replacement from the build e2e test I've removed here

Your team should take over that e2e and grow it as you all deem appropriate.

if you agree, go ahead and lgtm

/retes

**Comment by akram** [comment]
great work @gabemontero , that seems perfect, we will take over it and build on top

/test e2e-cmd
/lgtm

**Pull request merged**
