### PR TITLE
Bug 1926977: adjust route host for redis/nodejs to accomodate new apiserver restrictions

### PR DESCRIPTION
**Pull request by gabemontero**
https://github.com/openshift/openshift-apiserver/pull/167#issuecomment-775524042

https://github.com/openshift/cluster-samples-operator/pull/355

### CODE REVIEW

**Comment by gabemontero** [comment]
gcp iam pain

/test e2e-gcp-image-ecosystem

**Comment by gabemontero** [comment]
bunch of `Get "https://api.ci-op-z6ln1kb7-08e24.origin-ci-int-gce.dev.openshift.com:6443/api/v1/namespaces/kube-system/configmaps/cluster-config-v1": dial tcp: lookup api.ci-op-z6ln1kb7-08e24.origin-ci-int-gce.dev.openshift.com on 172.30.0.10:53: no such host` in image-eco

/test e2e-gcp-image-ecosystem

**Comment by gabemontero** [comment]
ok clean image eco run

the rest is just unrelated flakes

/retest

**Comment by gabemontero** [comment]
all tests green @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
the apiserver change is in 4.7 as well

/cherrypick release-4.7

**Comment by gabemontero** [comment]
unrelated errors e2e-gcp errors 

/test e2e-gcp

**Comment by gabemontero** [comment]
unrelated errors e2e-aws-fips

/test e2e-aws-fips

**Pull request merged**
