### PR TITLE
test/extended/prometheus: ensure multus exposes metrics over TLS

### PR DESCRIPTION
**Pull request by paulfantom**
Follow up to https://github.com/openshift/cluster-network-operator/pull/563

### CODE REVIEW

**Comment by lilic** [comment]
> [ERROR] hack/verify-gofmt.sh exited with code 1 after 00h 00m 01s

This is the error, failed twice. 🤷‍♀️ 

/hold

**Comment by lilic** [comment]
/hold

Still failing....

**Comment by paulfantom** [comment]
Rebased and ran `gofmt` as this was causing issues with verify.

/unhold

**Comment by s-urbaniak** [comment]
@paulfantom 
>  Not mergeable. Needs bugzilla/valid-bug label.
I guess this is for 4.6 then right?

**Comment by paulfantom** [comment]
> I guess this is for 4.6 then right?

Yup.

/hold

**Comment by s-urbaniak** [comment]
ping @paulfantom: is this still relevant?

**Comment by paulfantom** [comment]
no, it is not relevant anymore

/close

**Pull request closed without merging**
