### PR TITLE
Remove redundant extended networking sanity tests

### PR DESCRIPTION
**Pull request by marun**
The same tests are now available in the kube e2e suite.

cc: @openshift/networking

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by danwinship** [comment]
Yup, those tests are in kubernetes/test/e2e/networking.go. LGTM

**Comment by knobunc** [comment]
LGTM too.  @eparis, merge please?

**Comment by dcbw** [comment]
LGTM.  Did that stuff literally get copied over from Kube?

**Comment by danwinship** [comment]
No, other way around. The PR to move them to kube (https://github.com/kubernetes/kubernetes/pull/13568) just got stalled for a long time.

**Comment by pravisankar** [comment]
LGTM [merge]

**Comment by marun** [comment]
@pravisankar please try again.

**Comment by pravisankar** [comment]
re[merge]

**Pull request merged**
