### PR TITLE
Bump K8s label selector to next version

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres pr to update version in bower

**Comment by jwforres** [comment]
needs bindata

**Comment by jwforres** [comment]
hold off and i'll get another release with your other label selector pr

**Comment by jwforres** [comment]
ok you need to increase to v0.0.15 and then need to build bindata

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
