### PR TITLE
Fix DC reaper to deal with invalid resource name.

### PR DESCRIPTION
**Pull request by tnozicka**
It was deleting all RCs because apimachinery .AsSelector() ignores errors and returns MatchAll selector in that case.)

apimachinery issue: https://github.com/kubernetes/apimachinery/issues/31

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1517700

### CODE REVIEW

**Comment by tnozicka** [comment]
btw. `oc delete` which just uses `kubectl delete` doesn't validate resourceName (regexp) - cc @fabianofranz

**Comment by mfojtik** [comment]
hrm, I wonder how can this cause a race, the changes /lgtm

**Comment by tnozicka** [comment]
@mfojtik I think the race was always there, the changes just revealed it

**Comment by tnozicka** [comment]
submit queue stuck...
/test all

**Comment by tnozicka** [comment]
@mfojtik tests are passing, awaiting lgtm
/approve

**Pull request merged**
