### PR TITLE
Fix kubelet status stage

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1450461

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

**Comment by eparis** [comment]
[merge][severity: blocker]

**Comment by kargakis** [comment]
> continuous-integration/openshift-jenkins/merge Waiting: You are in the build queue at position: 14

@eparis the severity tag doesn't seem to be working?

**Comment by eparis** [comment]
@kargakis the tag doesn't get priority (yet). I'm just trying to remind myself and others to get in the habit.

also, since this is the last stage blocker i'm aware of and it got a green test, I'm going to merge by hand and make @derekwaynecarr deal with it if I break things.

**Comment by kargakis** [comment]
@openshift/team-continuous-delivery fyi, stage fix

**Comment by stevekuznetsov** [comment]
Severity doesn't imply anything about queue positioning. by the way.

**Pull request merged**
