### PR TITLE
Fix for haproxy reload stops pulling config

### LINKED ISSUE #7657: Router stops pulling config
As far as i could debug, it only happens with 1.1.3 image, after a while running the router stop refreshing the config. Some requests returns 503 error and some works fine.
Looking up the stats page i could see lot of broken endpoints and missing too.

Router pods was running and accepting connections, here's the logs:

```
I0225 21:33:06.320921       1 router.go:161] Router is including routes in all namespaces
E0225 21:37:38.938909       1 ratelimiter.go:50] error reloading router: wait: no child processes
---
+ config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ haproxy_conf_dir=/var/lib/haproxy/conf
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_be.map -o /var/lib/haproxy/conf/os_edge_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_expose.map -o /var/lib/haproxy/conf/os_edge_http_expose.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_redirect.map -o /var/lib/haproxy/conf/os_edge_http_redirect.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_reencrypt.map -o /var/lib/haproxy/conf/os_reencrypt.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_sni_passthrough.map -o /var/lib/haproxy/conf/os_sni_passthrough.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_tcp_be.map -o /var/lib/haproxy/conf/os_tcp_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=276
+ '[' -n 276 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 276
E0225 21:37:40.752585       1 ratelimiter.go:50] error reloading router: wait: no child processes
```

Destroying the pod seems to solve the issue, i'll keep looking for more info.

@smarterclayton

### PR DESCRIPTION
**Pull request by ramr**
fixes #7657   and replaces PR #7781 

  o  Set default template router reload interval to 5 seconds.
  o  Send graceful shutdown signal to all haproxy processes + wait for process to start listening.
      Along with the liveness probe this takes care of the unhealthy cases.

@smarterclayton  PTAL Thx

### CODE REVIEW

**Comment by ramr** [comment]
@smarterclayton  made the changes - what else did you want on this PR? PTAL thx

**Comment by smarterclayton** [comment]
LGTM [merge], can you ping QE and make sure they test this?  Also, Ben will have to rebase.

**Comment by ramr** [comment]
Will do - mentioning @zhaozhanqi  and @knobunc  here but will send them an email as well.

**Comment by zhaozhanqi** [comment]
@ramr 

I updated the code by manually and do the test, this works fine, no this kind of error 'ratelimiter.go:50] error reloading router: wait: no child processes ' found in logs

1. Update the code 
2.  rebuild openshift
     make clean && make
3. cp the binary 'openshift' to haproxy/bin and rebuild haproxy image
4. start openshift and create router
5. create pod/service/route
6. check the router container log

**Comment by smarterclayton** [comment]
You may want to try rapid changes with reload interval set to 0.  Even
with a steady stream of route changes there should be no errors and no
traffic disruption.

**Comment by knobunc** [comment]
LGTM

**Comment by smarterclayton** [comment]
Router test is failing, taking merge away.

**Comment by smarterclayton** [comment]
[test]

**Comment by ramr** [comment]
pull in syn packets eat changes, rebase and fix for [test]s

**Comment by ramr** [comment]
@smarterclayton  fixed the tests + rebased with @knobunc eat SYN packets changes.

**Comment by smarterclayton** [comment]
[test] again for flakes

**Comment by smarterclayton** [comment]
Squash the last two and then we'll merge.

**Comment by ramr** [comment]
@smarterclayton  done.

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Pull request merged**
