### PR TITLE
bump(github.com/openshift/openshift-sdn): 72d9ab84f4bf650d1922174e6a90bd06018003b4

### PR DESCRIPTION
**Pull request by dcbw**
Includes these openshift-sdn PRs:

https://github.com/openshift/openshift-sdn/pull/268
https://github.com/openshift/openshift-sdn/pull/267
https://github.com/openshift/openshift-sdn/pull/266
https://github.com/openshift/openshift-sdn/pull/245

### CODE REVIEW

**Comment by dcbw** [comment]
@pravisankar @danwinship @knobunc @eparis

**Comment by eparis** [comment]
It seems there were questions/comments in https://github.com/openshift/openshift-sdn/pull/268 which were unaddressed...

**Comment by danwinship** [comment]
I replied on 268. It was just a misunderstanding about what the code was supposed to do.

travis failure seems seems either flaky or else related to the kubernetes rebase?

**Comment by dcbw** [comment]
re[test]

**Comment by dcbw** [comment]
Test flake is https://github.com/openshift/origin/issues/8128

**Comment by eparis** [comment]
[test]

**Comment by eparis** [comment]
[merge]

**Pull request merged**
