### PR TITLE
Expand short isimage id refs

### LINKED ISSUE #2980: Shorthand ImageStreamImage references don't work properly everywhere
If you create a spec tag from ref like this:

```
from:
  kind: ImageStreamImage
  name: andyapp@d3194760
  namespace: andyproj1
```

this is what's added to status.tags:

```
items:
- created: 2015-06-09T00:48:32Z
  dockerImageReference: 172.30.242.180:5000/andyproj1/andyapp:d3194760
  image: d3194760
tag: byid
```

Note the dockerImageReference looks like a tag pull spec (andyapp:d31...). This is because the call to DockerImageReference.String() here https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestream/strategy.go#L227 sets ID to d3194760 in my case, which doesn't parse as a digest (https://github.com/openshift/origin/blob/master/pkg/image/api/helper.go#L142-L147), so the implementation treats it like a tag pull spec.

This pull spec isn't valid. Even with a correction so it looks like `172.30.242.180:5000/andyproj1/andyapp@d3194760` or `172.30.242.180:5000/andyproj1/andyapp@sha256:d3194760`, the registry doesn't support pulling images unless the full digest is used.

### PR DESCRIPTION
**Pull request by ncdc**
When setting a spec.tag's from with kind=ImageStreamImage, if from.name
is a shortened image id, resolve it to the full id so the tag event's
dockerImageReference and image fields are correct.

Fixes #2980

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton PTAL

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
I've got 1 update pending that I'll push in a couple of minutes.

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
