### PR TITLE
Remove sudo call from hack/test-cmd.sh

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This won't work. We need to remove the etcd cruft to have reasonably-sized log files on the Jenkins server. etcd writes its data stores with elevated privileges, so we need to determine how to stop that from happening before we remove this `sudo`.

**Comment by liggitt** [comment]
what is starting etcd from hack/test-cmd.sh with elevated privileges?

**Comment by liggitt** [comment]
[test]

**Comment by stevekuznetsov** [comment]
I think it's run as part of the all-in-one? I'm not sure, since the OpenShift bits don't need `sudo` here.

**Comment by liggitt** [comment]
updated to conditionally use sudo

**Comment by stevekuznetsov** [comment]
No etcd garbage left over for the artifacts ... LGTM. Looks like you have good mojo @liggitt

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
