### PR TITLE
Rename 'osc' to 'oc' and 'osadm' to 'oadm'

### PR DESCRIPTION
**Pull request by smarterclayton**
Preserve old symlinks.  Part of #2628

[merge]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Silly assets...

**Comment by smarterclayton** [comment]
Fixes #1007

**Comment by nak3** [comment]
The subject of this PR is wrong? You renamed "osc" to "oc", right?

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
