### PR TITLE
UPSTREAM: 21095: Provide current namespace to InClusterConfig

### PR DESCRIPTION
**Pull request by liggitt**
Makes in-cluster-config work without any extra pod modifications

Holding for rebase

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton for review of POD_NAMESPACE-related changes in origin. Hold on merge, since it has an UPSTREAM commit

**Comment by liggitt** [comment]
flake https://github.com/openshift/origin/issues/7243 - [test]

**Comment by smarterclayton** [comment]
LGTM, merge when reopen

**Comment by liggitt** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
Doesn't look like a flake, I'll dig into the test failures

**Comment by liggitt** [comment]
s/testclient.Action/core.Action/ after rebase landed. clean pick from upstream now. [merge]

**Pull request merged**
