### PR TITLE
UPSTREAM: 45352: Pod (Anti)affinity shouldn't be respected across namespaces.

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1483119
Upstream fix+unit test:
kubernetes/kubernetes#45352
kubernetes/kubernetes#45152

Origin 3.6 fix: 
https://github.com/openshift/origin/pull/16016

/cc @sjenning @aveshagarwal @deads2k 

Only difference between #16016  and this one is, podAntiAffinity and podAffinity are in Annotations rather than in pod Spec.

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
It seems the error is happening at PID 12531: /tmp/origin_version.sh:2: `os::build::version::get_vars` exited with status 127.? Anything I could do to pass this?

**Comment by stevekuznetsov** [comment]
No, sorry, that is a red herring. The real issue was:

```
+ hack/env make build-router-e2e-test
make: *** No rule to make target `build-router-e2e-test'.  Stop.
```

**Comment by stevekuznetsov** [comment]
Question @ravisantoshgudimetla @sjenning why is this going into Origin, not OSE?

**Comment by sjenning** [comment]
@stevekuznetsov sorry, there have been so many PRs with this change, I didn't notice this was against Origin.  

@ravisantoshgudimetla can reopen against OSE 3.5?

**Comment by ravisantoshgudimetla** [comment]
Sure @sjenning. I will raise against ose 3.5 but before that, I want to push these changes to ose 3.6 and it is failing at etcd installation.

**Pull request closed without merging**
