### PR TITLE
Bug 1725027: --output flag to release info does not include all options

### PR DESCRIPTION
**Pull request by zhouying7780**
fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=1725027
@xingxingxia   @tnozicka  Please help review. thanks.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Please update the Git commit with the appropriate email address for you as a user (needs to match your GitHub profile).

**Comment by zhouying7780** [comment]
cc @openshift/cli-review

**Comment by zhouying7780** [comment]
Since the origin repo has updated , will close this and open a new PR.

**Pull request closed without merging**
