### PR TITLE
Bug 1804239: picks dynamic reloading for CSR signing controllers

### PR DESCRIPTION
**Pull request by p0lyn0mial**
It also reverts [csrsuicider](https://github.com/openshift/kubernetes/commit/182a52879f09d158d97a2040d1bbb7a5f2c3fedf#diff-35876a32e10f599f8f7363775a8e734c) commit as it is no longer needed since the controller knows how to reload the signing cert dynamically.

quite a clean pick, I had to manually revert the commit and regenerate the files.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
do we want to move it to `4.4` as well?

**Comment by soltysh** [comment]
/title Bug 1804239: picks dynamic reloading for CSR signing controllers

**Comment by soltysh** [comment]
/retitle Bug 1804239: picks dynamic reloading for CSR signing controllers

**Comment by p0lyn0mial** [comment]
Do we want to move it to `release-4.3`? I haven't seen a PR.

**Pull request merged**
