### PR TITLE
Platform independent image builds

### PR DESCRIPTION
**Pull request by ironcladlou**
Make the build/release process more generic to allow multiple release targets
such as core and image binaries. This makes the build/release process once
again platform independent (provided docker is available on the host), and
re-enables support for build-release/build-images on OSX.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@smarterclayton This solves it. It would have been much simpler to just include the binary in the release tar, but this does the job.

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
@smarterclayton If you also think this fixes the problem, maybe we could get it merged for beta1 with a refactor followup? I avoided the hello image because it seems to have a binary committed rather than following the bin directory convention, and I didn't want to do too much at once yet.

**Comment by smarterclayton** [comment]
Not beta1

**Comment by ironcladlou** [comment]
Alright, but it's unfortunate that what's in master went from working to broken suddenly.

**Comment by smarterclayton** [comment]
Also build assets

**Comment by ironcladlou** [comment]
@smarterclayton 
>Also build assets

Can you elaborate on this? I'm happy to keep running with the PR for beta2.

**Comment by smarterclayton** [comment]
If the release image was capable of building assets (not by default, but in a mode we can run) it would benefit folks deving on weird systems.

**Comment by smarterclayton** [comment]
We can nuke the committed binary - it was convenient, that's all.

**Comment by csrwng** [comment]
This is working for me on boot2docker:
```sh
#!/bin/sh
docker run \
   -v $GOPATH/src/github.com/openshift/origin:/go/src/github.com/openshift/origin \
   -v /usr/local/bin/docker:/usr/bin/docker \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -e OS_VERSION_FILE="" \
   openshift/origin-release hack/build-images.sh
```

**Comment by ironcladlou** [comment]
@csrwng One nit with that approach is that you're building bind mounted source through the VM rather than letting the origin-release container build from the source that was prepared and streamed to it.

@smarterclayton I had one more idea to revise what I have here: what if instead of building just 1 release tar and pulling down the image binaries separately place_bins was modified to produce the release tar (excluding image binaries), and a second image binaries tar (including only image binaries)? Then the build-release.sh could:

1. Pull down and verify the release tar
2. Pull down and verify image tar(s)
3. Untar both to the same place

I think that seems more internally consistent than what I have so far.

**Comment by smarterclayton** [comment]
Yes.

----- Original Message -----

**Comment by ironcladlou** [comment]
@smarterclayton Check this new revision out.

**Comment by smarterclayton** [comment]
Do hello-Openshift as well

**Comment by ironcladlou** [comment]
@smarterclayton 

Ready for another review. I think I managed to get the release builder just generic enough to support our core/images splits.

**Comment by ironcladlou** [comment]
@smarterclayton I know you've been busy with an upstream refactor, so I promise to ping you about this only once a day. :relaxed:

**Comment by ironcladlou** [comment]
Rebased.

**Comment by ironcladlou** [comment]
@smarterclayton Psssst.

**Comment by smarterclayton** [comment]
Have you got a passing jenkins test?

**Comment by ironcladlou** [comment]
Figures... it was green for days and when you come back around everything's red red red

**Comment by ironcladlou** [comment]
Rebased again, waiting for results.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
