### PR TITLE
Add short TTL cache to token authentication

### PR DESCRIPTION
**Pull request by liggitt**
Addresses frequent etcd lookups due to high-volume controllers

Fixes authenticator aspect of https://bugzilla.redhat.com/show_bug.cgi?id=1464579

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by enj** [comment]
@openshift/sig-security

**Comment by smarterclayton** [comment]
Generally LGTM - a 10s window on either side is not a large deal for a huge reduction in peak load during request storms.

**Comment by liggitt** [comment]
upstream commits are merged, any last comments from @openshift/sig-security?

do we still want this for 3.6.1? https://github.com/openshift/origin/pull/15662 is ready and green as well

**Pull request merged**
