### PR TITLE
UPSTREAM: 37721: Fix logic error in graceful deletion

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref https://bugzilla.redhat.com/show_bug.cgi?id=1397356

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

**Comment by eparis** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by eparis** [comment]
#12039 but for 1.4

**Comment by derekwaynecarr** [comment]
fixed issue re [merge]

**Pull request merged**
