### PR TITLE
better error message for missing dockerfile

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/5434

### CODE REVIEW

**Comment by bparees** [comment]
[test]

@smarterclayton please sanity check this, i'm mostly wondering if it's going to cause failures in the case where a Dockerfile is being supplied via the -D argument (but that would have failed before too, just with a less useful error message).

**Comment by smarterclayton** [comment]
If it does fail it isn't your fault - we should definitely have a follow up to test that.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
