### PR TITLE
Use kubectl constants for dc reaper interval/timeout

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
@ironcladlou review plx

**Comment by ironcladlou** [comment]
Warm cookies and a tall glass of [merge] :cookie:

**Comment by kargakis** [comment]
Had to rebase after the rebase/scale renaming

**Comment by ironcladlou** [comment]
[merge] again

**Comment by mfojtik** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
