### PR TITLE
[release-3.11] Bug 1758375: fix haproxy reload crash when processing ECDSA keys

### PR DESCRIPTION
**Pull request by Miciah**
This is manual cherry-pick of openshift/router#39.

### CODE REVIEW

**Comment by Miciah** [comment]
Reformatted with gofmt from Go 1.10.

**Comment by ironcladlou** [comment]
@Miciah can you update this to use the cert data from https://github.com/openshift/router/pull/43?

**Comment by Miciah** [comment]
Updated with newer cert data.

**Comment by Miciah** [comment]
/hold
The Jenkins job is continuously failing on an SSH permissions issue.

**Comment by Miciah** [comment]
Looks like we may be past the SSH permission issue.
/test extended_clusterup
/test end_to_end
/test extended_conformance_install

**Comment by Miciah** [comment]
CI looks good.
/hold cancel

**Comment by Alveel** [comment]
Hi, any update on this?

We'd like to use ECDSA certificates but this is stopping us from doing so :smile:

**Comment by Miciah** [comment]
What version of OpenShift are you using?  This fix is merged and shipped in OCP 3.11.154.

**Comment by Alveel** [comment]
Huh. I was so sure I saw this issue was open, not merged. Maybe I mixed it up with another issue.

Apologies, ignore my previous comment!

**Pull request merged**
