### PR TITLE
v1.11.1

### PR DESCRIPTION
**Pull request by liggitt**
Prereqs:
* [x] merge https://github.com/openshift/kubernetes/pull/66
* [x] merge https://github.com/openshift/api/pull/75
* [x] set up openshift/kubernetes -> forks publishing (https://github.com/openshift/origin/pull/20395 and CI config)
* [x] merge https://github.com/openshift/client-go/pull/56
* [x] merge https://github.com/openshift/library-go/pull/21
* [x] merge https://github.com/openshift/service-serving-cert-signer/pull/19
* [x] discard TMP glide yaml commit, rerun update-deps
* [x] get green origin CI

follow-up:
* [ ] enable fork publishing for 1.11.1

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @deads2k @mfojtik 

ready for review while we wait for green CI and I get the bot set up on the new fork branches. dropped upstream commits listed in the description of https://github.com/openshift/kubernetes/pull/66

**Comment by mfojtik** [comment]
Changes LGTM.

**Comment by ravisantoshgudimetla** [comment]
@liggitt Are the test failures flakes? If yes, after rebase could this be manually merged?

**Comment by deads2k** [comment]
unit - `github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/tests TestStartingResourceVersion 5.78s`

gcp, no output

cross - `cannot allocate memory`

/retest

**Comment by liggitt** [comment]
green CI on 3f9c90a3f3c87575e1f3cd6095c284bef81a1ee5

dropped TMP glide yaml commit, reran update-deps, only incoming changes were glide.lock/glide.yaml files from upstream merges

**Comment by deads2k** [comment]
lgtm.  Last run was green, no diff. merging.

**Pull request merged**
