### PR TITLE
UPSTREAM: 17973: Validate pod spec.nodeName

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by deads2k** [comment]
upstream pull?

**Comment by deads2k** [comment]
and unit test

**Comment by fabianofranz** [comment]
Upstream PR is https://github.com/kubernetes/kubernetes/pull/17973

**Comment by fabianofranz** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
```
Running  oc describe dc test-deployment-config...
FAILURE: oc describe dc test-deployment-config: the output content test failed
Standard output from the command:
Name:		test-deployment-config
Created:	1 seconds ago
Labels:		<none>
Latest Version:	Not deployed
Triggers:	Config
Strategy:	Recreate
Template:
  Selector:	name=test-deployment
  Replicas:	1
  Containers:
  NAME			IMAGE						ENV
  ruby-helloworld	127.0.0.1:5001/openshift/origin-ruby-sample	TEST=value
Latest Deployment:	<none>
No events.

There was no error output from the command.
[FAIL] !!!!! Test Failed !!!!
```
[merge]

**Comment by deads2k** [comment]
@stevekuznetsov update the "FAILURE: ..." string to show me what content it was looking for.

**Comment by stevekuznetsov** [comment]
There is a PR in flight that does that

**Pull request merged**
