### PR TITLE
Fix several typos

### PR DESCRIPTION
**Pull request by rhcarvalho**
Hi everyone! I used OpenShift Origin's repo as my first test target for [typokiller](https://github.com/rhcarvalho/typokiller).

Happy to see just a small amount of typos, kudos to you all! Great job!

### CODE REVIEW

**Comment by jhadvig** [comment]
@rhcarvalho thanks for fixing this. Could you please squash into one commit, since basically both commits are just fixing typos ?

**Comment by rhcarvalho** [comment]
@jhadvig I had it separate because the capitalization cases seemed debatable. I've squashed it all into one commit now.

**Comment by jhadvig** [comment]
@rhcarvalho thanks. LGTM

**Comment by jhadvig** [comment]
[test]

**Comment by jhadvig** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
@rhcarvalho thanks for doing this!

**Comment by mfojtik** [comment]
@rhcarvalho can you do the same for https://github.com/openshift/source-to-image ? ;-)

**Comment by rhcarvalho** [comment]
@mfojtik :yum: yes

**Pull request merged**
