### PR TITLE
Add RHSCL 2.3 docker images to image streams

### PR DESCRIPTION
**Pull request by hhorak**
Adds PHP 7.0, Perl 5.24, MySQL 5.7 and Redis 3.2 based on CentOS 7 and RHEL 7

### CODE REVIEW

**Comment by bparees** [comment]
@hhorak you need to run hack/update-generated-bootstrap-bindata.sh and check in the file it updates.

have you tested these new imagestreams w/ the various sample templates that consume them?
https://github.com/openshift/origin/tree/master/examples/quickstarts

do you intend to provide a redis quickstart?
https://github.com/openshift/origin/tree/master/examples/db-templates

would it make sense to provide a full app quickstart example that uses redis?  (we have full app quickstarts for mysql, mongo, and postgres, as you can see above)

we have extended tests i'll run against this PR once you update the bootstrap file which will also test that the templates+sample apps still work, but you may save some digging by testing them yourself first.

**Comment by hhorak** [comment]
> have you tested these new imagestreams w/ the various sample templates that consume them?
> https://github.com/openshift/origin/tree/master/examples/quickstarts

Not yet, but I should try that as part of the learn-OpenShift-more experience. But if anybody would do it before to not block this PR, I won't be mad..

> do you intend to provide a redis quickstart?
> https://github.com/openshift/origin/tree/master/examples/db-templates

I've added it to this PR, but to be honest, I don't really know how to test it -- I tried to import it as examples show and saw:
`template "redis-ephemeral" created`
Does that mean anything else than that the JSON file has correct syntax?

> would it make sense to provide a full app quickstart example that uses redis? (we have full app quickstarts for mysql, mongo, and postgres, as you can see above)

It would make sense to me, although we'll see whether I'll be able to make it. So far I stole a simple app from GCE example, which might be used for that purpose: https://github.com/hhorak/guestbook-redis-python

**Comment by bparees** [comment]
> Does that mean anything else than that the JSON file has correct syntax?

not really.  it sounds like you ran "oc create -f yourtemplate.json" which "installs" the template, but if you want to instantiate it, you need to run "oc new-app -f yourtemplate.json" and then confirm that all the stuff you expected to see deployed, got deployed.

**Comment by oatmealraisin** [comment]
@hhorak bump

**Comment by oatmealraisin** [comment]
@bparees @hhorak fwiw, I've tested all of these changes w/ updated quickstart templates, as well as the db templates. If we're OK with not having a Redis quickstart, could we merge?

**Comment by bparees** [comment]
@oatmealraisin @luciddreamz indicated the cakephp example wouldn't work w/ the new php image, did you test that change?

**Comment by bparees** [comment]
@hhorak please squash your commits

**Comment by oatmealraisin** [comment]
@bparees No you're right, I've been testing Perl 5.24 and MySQL 5.7, per my card :) Sorry for the impatience

**Comment by bparees** [comment]
@oatmealraisin please open a new PR that updates the imagestreams for perl 5.24 and mysql5.7 so we can get that merged, since this PR is blocked by other challenges.

**Comment by luciddreamz** [comment]
@bparees I'll update CakePHP to version 2.9.3 before lunch today so we can unblock the PHP 7 portion of the request. Is Redis 3.2 blocked as well?

**Comment by bparees** [comment]
@luciddreamz redis doesn't have to be blocked, but ideally i wanted to see an example that used it as part of delivering it.  we can live w/ the just the db-template that @hhorak has supplied.

I also haven't seen any confirmation the redis db-template has been tested.

**Comment by luciddreamz** [comment]
The MySQL ephemeral and persistent database examples should also be updated. They currently reference version 5.6, but this should be updated to 5.7 alongside this PR.

Here are the locations in MySQL ephemeral, but note that this should also be updated in the same places in the persistent example:

- https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-ephemeral-template.json#L8
- https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-ephemeral-template.json#L13
- https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-ephemeral-template.json#L249

**Comment by luciddreamz** [comment]
Our default PHP example, CakePHP, has been updated to support PHP 5.5, PHP 5.6, and PHP 7: openshift/cakephp-ex/pull/51

**Comment by oatmealraisin** [comment]
@luciddreamz :) Already got it #12126

**Comment by hhorak** [comment]
> @hhorak please squash your commits

Done.

I've also managed to get the redis-ephemeral template working, although still have troubles with persistent volumes (claim in pending state indefinitely). But since there are the same changes as in mysql templates, I hope it is generally fine. One thing I did not get though (and took me quite a lot of time to realize) -- the templates omit the "image" value, which obviously does not work without changing. It is the same case in other templates, but why not using e.g. centos image from docker hub there?

**Comment by hhorak** [comment]
Rebased once again after merging #12126.

**Comment by bparees** [comment]
> the templates omit the "image" value, which obviously does not work without changing. It is the same case in other templates, but why not using e.g. centos image from docker hub there?

the point of leaving the "image" field blank in the deploymentconfig (which I assume is what you are referring to) is to ensure the value is picked up from the ImageChangeTrigger associated with the deploymentconfig.

**Comment by bparees** [comment]
changes lgtm, merging.
[merge]

**Comment by hhorak** [comment]
> the point of leaving the "image" field blank in the deploymentconfig (which I assume is what you are referring to) is to ensure the value is picked up from the ImageChangeTrigger associated with the deploymentconfig.

Yes, that was what I was referring to. My understanding is that ImageChangeTrigger did not work for me because I took image from external registry, which was not being updated. Or because of anything else, still a lot of gray areas on my end :)

**Comment by bparees** [comment]
> My understanding is that ImageChangeTrigger did not work for me because I took image from external registry, which was not being updated. 

when it's external it won't trigger just because you pushed a new image to the registry(because pushing to the registry won't cause an update in the imagestream), but it will still be resolved when a deployment is requested manually, and also the imagestreamtrigger will fire when the imagestream is first updated on the initial import from the registry.

**Comment by bparees** [comment]
@hhorak you need to update our tests because the expect specific imagestreams to exist:

```
hack/test-cmd.sh has failed: newapp.sh:203: executing 'oc new-app --search --image-stream=php' expecting success and text 'Tags:\s+5.5, 5.6, latest'
```

since you've added 5.7, you need to update the test to expect 5.7 as part of the output from that command.

**Comment by hhorak** [comment]
> since you've added 5.7, you need to update the test to expect 5.7 as part of the output from that command.

It's actually 7.0, but I see the point. Giving it another try.

**Comment by bparees** [comment]
@hhorak next issues:

```
examples_test.go:143: ../examples/db-templates/redis-ephemeral-template.json does not have a test case defined
	examples_test.go:143: ../examples/db-templates/redis-persistent-template.json does not have a test case defined
```

you need to update examples_test.go to list your 2 new templates, you can copy the examples that are there for the other db-templates.

**Comment by hhorak** [comment]
> you need to update examples_test.go to list your 2 new templates, you can copy the examples that are there for the other db-templates.

Ok, fixed, let's see how far we'll get this time.

**Comment by bparees** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
@hhorak latest failure is a known flake..  squash your commits and i'll merge assuming the extended test run i just kicked off passes.

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11016

**Comment by hhorak** [comment]
Squashed.

**Comment by bparees** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
