### PR TITLE
Cherry-pick graceful deletion fixes into origin

### PR DESCRIPTION
**Pull request by smarterclayton**
15900 and 15930

Referenced by #5107

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Crap, version check... sigh.

**Comment by smarterclayton** [comment]
@derekwaynecarr quick review please

**Comment by smarterclayton** [comment]
[test]

**Comment by derekwaynecarr** [comment]
LGTM - I was happy to see this does not use event recorder ;-)  [merge]

**Pull request merged**
