### PR TITLE
use secrets in sample templates

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
Previous run failed with a GCE error which I have fixed.

**Comment by jim-minter** [comment]
That's already more churn than I guess was anticipated, and following the subsequent comments imply more of it still - perhaps worth ignoring them? :-/

- The removal of the ADMIN_* template parameters implies making updates to README.md, but this may well have quite a lot of bit rot anyway and it might be worth just opening a ticket to rescan through it properly at some other time.

- Was there a recent effort to move from json->yaml for these kinds of file?

- Personally I'm in two minds about specifying all these no-op hooks ("/bin/true"), but they do have the advantage their existence brought to the surface the fact that the DC probably isn't labelling these properly at the moment.

**Comment by bparees** [comment]
> That's already more churn than I guess was anticipated

yeah, more than i anticipated too :(

> The removal of the ADMIN_* template parameters implies making updates to README.md, but this may well have quite a lot of bit rot anyway and it might be worth just opening a ticket to rescan through it properly at some other time.

yeah i was just removing them because they are unused (weirdly we weren't even passing them to the DB pod, we were only passing them to the app pod, not sure what the history is there.  maybe once upon a time the app pod was using admin creds to setup the DB or something).  I can fix the readme.

> Was there a recent effort to move from json->yaml for these kinds of file?

there was, but @PI-Victor was doing it and i think ultimately it was probably a mistake to try to do them all in a single PR, I think we need to go back and do chunks at a time that can be more easily tested and reviewed (eg do all the extended test fixtures in one PR).  

In any case i'm not adding that churn to this PR :)

> Personally I'm in two minds about specifying all these no-op hooks ("/bin/true"), but they do have the advantage their existence brought to the surface the fact that the DC probably isn't labelling these properly at the moment.

unfortunately this template really serves two purposes:
1) as an example of how to do certain things in templates (it's probably no longer serving that purpose...this was the first template that ever existed and the only one, for a while)
2) it's leveraged by various tests meaning they have certain expectations that the template will exercise certain functionality

so stripping out "no-op" stuff will potentially remove test coverage.

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11887

**Comment by bparees** [comment]
@jim-minter readme updated.

**Comment by PI-Victor** [comment]
need to make a large rebase of that PR (not gonna lie, not looking fw to that), i still think it can pass if it's of immediate interest.

**Comment by PI-Victor** [comment]
also, i haven't touched the extended tests fixtures. it only contains the examples folder. with readmes and related code.

**Comment by jim-minter** [comment]
@bparees: lgtm

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/12773
[merge]

**Pull request merged**
