### PR TITLE
UPSTREAM: 16223: Concurrency fixes in status.Manager

### PR DESCRIPTION
**Pull request by smarterclayton**
Referenced from #5107 @liggitt @derekwaynecarr

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by derekwaynecarr** [comment]
@smarterclayton - looks to be test case unused import errors, otherwise lgtm

**Comment by smarterclayton** [comment]
This needs the other status manager changes to be sane, closing and supplanted by #5554

**Pull request closed without merging**
