### PR TITLE
Revert: Pass the container name to deployment config log options

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/10598

I will open a follow-up issue to discuss how to fix the original issue without breaking the backward compatibility.

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis @jwforres @deads2k PTAL

**Comment by deads2k** [comment]
You had a separate commit for tests?

[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10002 [merge]

Looks like the replication controller and the deployer pod both exist and run but for some reason the watch for the running deployment expires, and we end up reporting that the replication controller wasn't found.

**Comment by mfojtik** [comment]
https://github.com/openshift/origin/issues/9355 [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10635 [merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10663 [merge]

**Pull request merged**
