### PR TITLE
Change imagestreamtag sorting

### PR DESCRIPTION
**Pull request by miminar**
- Sort istags alphabetically during schema conversion
- Version prefix matters when sorting tags names

Forward-port of openshift/ose#932

### CODE REVIEW

**Comment by soltysh** [comment]
The error from test is valid:
```
test/cmd/images.sh:286: executing 'oc get is perl --template '{{(index .status.tags 0).tag}}'' expecting success and text 'latest'
FAILURE after 0.218s: test/cmd/images.sh:286: executing 'oc get is perl --template '{{(index .status.tags 0).tag}}'' expecting success and text 'latest': the output content test failed
Standard output from the command:
5.16
```
Latest has to go first always.

**Comment by miminar** [comment]
@soltysh this list is a result of conversion from internal to v1 scheme, right? Why the `latest` has to be first here?

The `oc describe is <isname>` and importer still sort the tags in expected way.

**Comment by mfojtik** [comment]
not having :latest in the list of imported tags (when the # of tags we import is limited) will likely cause problems :-) I would pickup :latest as first and then every other tags.

**Comment by soltysh** [comment]
> @soltysh this list is a result of conversion from internal to v1 scheme, right? Why the latest has to be first here?

That conversion also does sorting, iirc. I had a discussion with @smarterclayton about it long time ago. We need to provide stable output, both from our CLI and API.

**Comment by miminar** [comment]
> not having :latest in the list of imported tags (when the # of tags we import is limited) will likely cause problems :-) I would pickup :latest as first and then every other tags.

As I said before, the change doesn't affect which tags the importer picks up. It affects the order of tags in a serialized image stream though. I don't see it as very important but you may know better. @smarterclayton suggested to start sorting the tags in conversions alphabetically to have a stable sort algorithm without bugs :-).

**Pull request merged**
