### PR TITLE
cli: use the image namespace for image change trigger

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1539575

### CODE REVIEW

**Comment by smarterclayton** [comment]
We shouldn't be setting any namespace here...

**Comment by smarterclayton** [comment]
If the tag is in the same namespace as the object we should be leaving it empty.  This change *always* sets the tag which is not correct.

**Comment by mfojtik** [comment]
@smarterclayton this change only sets the namespace if the namespace is part of the image stream tag (eg. `openshift/ruby:12`) it will set the namespace to `openshift`. If the namespace is not provided (eg. `ruby:12`) then it won't set any namespace at all.

**Comment by smarterclayton** [comment]
That's fine then, thanks for clarifying (the change looked like Namespace
would always be set).

**Pull request merged**
