### PR TITLE
UPSTREAM: 42622: Preserve custom etcd prefix compatibility for etcd3

### PR DESCRIPTION
**Pull request by enj**
cc @liggitt 

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
[test]

**Comment by liggitt** [comment]
LGTM [merge]

**Comment by soltysh** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by liggitt** [comment]
do we need an OSE pick or are we still fast-forwarding?

**Comment by enj** [comment]
> do we need an OSE pick or are we still fast-forwarding?

@mfojtik @danmcp ^ ?

**Comment by danmcp** [comment]
@liggitt @enj No need for a pick until after code freeze.

**Comment by enj** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1393744

**Pull request merged**
