### PR TITLE
support for reencrypt routes in the same vserver

### PR DESCRIPTION
**Pull request by rajatchopra**
More of an RFE - https://bugzilla.redhat.com/show_bug.cgi?id=1431655

### CODE REVIEW

**Comment by rajatchopra** [comment]
@kmunson1973 @Miciah - If any of you could glance over this one. Thanks.

**Comment by rajatchopra** [comment]
@knobunc, could we get this merged?

**Comment by knobunc** [comment]
[merge]

**Comment by lihongan** [comment]
@rajatchopra please see logs below:

```
error: Encountered an error on POST request to URL https://10.66.144.115/mgmt/tm/ltm/rule: HTTP code: 400; error from F5: 01070151:3: Rule [/Common/openshift_passthrough_irule] error: /Common/openshift_passthrough_irule:87: error: [missing an expression][ ]
/Common/openshift_passthrough_irule:82: error: [undefined procedure:  [class match $servername_lower equals ssl_reencrypt_servername_dg] ][if { [class match $servername_lower equals ssl_passthrough_servername_dg] } {
              pool [class match -value $servername_lower equals ssl_passthrough_servername_dg]
              SSL::disable
              HTTP::disable
            }
            else if { [class match $servername_lower equals ssl_reencrypt_servername_dg] } {
              pool [class match -value $servername_lower equals ssl_reencrypt_servername_dg]
              SSL::enable serverside
            }]

```

**Comment by lihongan** [comment]
@rajatchopra I think I found the root cause, it should be `elseif` not `else if`, I can update the irule manually on F5 server.

**Pull request merged**
