### PR TITLE
Allow cluster up and rsync when no ipv6 on container host

### LINKED ISSUE #10850: oc cluster up   fails if ipv6.disable=1
On a Fedora24 host that runs with ipv6.disable=1 (so no ipv6 support), docker etc. all run fine.  But the oc-client-tools binary is unhappy:

##### Version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63
docker-1.12.0-6.gitad4812e.fc26.x86_64 rpm   (because f24 base one fails without ipv6)

##### Steps To Reproduce
# oc cluster up

##### Current Result
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: Docker run error rc=1
     Details:
       Image: openshift/origin:latest
       Entrypoint: [/bin/bash]
       Command: [-c cat /proc/net/tcp /proc/net/tcp6]
[....] 
      Error Output:
         cat: /proc/net/tcp6: No such file or directory

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #10850

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
[testonlyextended][extended:core(rsync)]

**Comment by jim-minter** [comment]
@csrwng I think we hit https://github.com/coreos/etcd/issues/6534 - does this count as a flake?

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/11400
[test]

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
