### PR TITLE
Exposes 'config' to manage .kubeconfig files

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton Simply exposing the `osc config` set of commands *as is* for now. Custom stuff will come later.

@deads2k I'll propose upstream installing the printer (`AddPrinterFlags`) to `kubectl config view`, that will allow different output formats (json, templates). Thoughts?

**Comment by fabianofranz** [comment]
[test]

**Comment by smarterclayton** [comment]
When would an end user use config?

**Comment by fabianofranz** [comment]
@smarterclayton To manage preferences and servers (as in `rhc servers`) for example, aren't those valid use cases?
```
$osc config set preferences.colors true

$osc config set-cluster my_company_server --server=https://openshift.corp.com --certificate-authority=path/to/my/cafile
$osc config set-context my_company --cluster=my_company_server --user=my_user
$osc config use-context my_company
```

**Comment by smarterclayton** [comment]
When we introduce the projects/login command, when would I use this?  Why is it called "set-cluster"?  What's a cluster?

Config I can see as a rarely used option.  I don't know how some of the other things are supposed to fit in.

**Comment by smarterclayton** [comment]
I'm not saying we shouldn't add this, I want to know how users will use this and what the plan is.

**Comment by fabianofranz** [comment]
@smarterclayton Right, this was not meant to be *the* solution to manage preferences, servers or user profiles. Since this set of subcommands is available from upstream and reading confs from `.kubeconfig` files already works, I wanted to expose this as a "`.kubeconfig` file manager" until we have proper `setup`, `login`, `project` and related user-friendly commands that will manage configs by not exposing its complexity and nomenclature. After that we can just remove this or make it more obscure feature for advanced users. Makes sense?

**Comment by smarterclayton** [comment]
Yes.  Can you mark these as experimental (like other commands) and help users understand what they do?

Also, make sure these properly print out "openshift cli" or "osc" in their help text - I noticed that a few other commands were showing kubectl.

**Comment by smarterclayton** [comment]
What's the decision on .openshiftconfig and .kubeconfig?

**Comment by deads2k** [comment]
> I'll propose upstream installing the printer (AddPrinterFlags) to kubectl config view, that will allow different output formats (json, templates). Thoughts?

I don't feel strongly.  The file itself is always a yaml file and it is always exists on the user's disk and it's never marshalled over the wire, so I don't know that I'd call printers necessary, but it doesn't bother me either.  Congruence is nice.

**Comment by deads2k** [comment]
> What's the decision on .openshiftconfig and .kubeconfig?

We had talked about having a separate .openshiftconfig that conforms to a .kubeconfig file format, but adds additional fields to a context object (either `-kubernetes-context`, or `-kubernetes-cluster` and `-kubernetes-user`).  That way `kubectl` could still read the file without any difficulty and we'd be able to merge in a .kubeconfig in our hierarchy (if we so chose) in order to ease the transition.  

How it could be done:
 1.  User already has kubernetes installed.  They've been working with it a while and have a working .kube/.kubeconfig file.
 1.  User wants to add openshift on top of their kubernetes, so they log into openshift and supply a context name for their existing kubernetes.
 1.  We build a .openshift/.openshiftconfig file for them that has the openshift information and points to the existing -kubernetes-context in their .kubeconfig file.

By having .openshiftconfig, we can reasonably have first class fields for our additional options and I think that will make it more human parsable.  The side effect is that `kubectl config *` commands will not work properly against .openshiftconfig files.

**Comment by fabianofranz** [comment]
@smarterclayton Nice, moved `config` to experimental for now, and will handle `.openshiftconfig` and other stuff separately. I'll been drafting a few things about `osc login` already, I'll share that later today.

**Comment by fabianofranz** [comment]
@deads2k I specifically felt the need to use templates in `config view` when writing the tests for it and trying to parse and deal with the results, but your argument is valid.

**Comment by smarterclayton** [comment]
I think I lead David's way - let's leave it as yaml only until someone asks.

**Comment by smarterclayton** [comment]
----- Original Message -----
> > What's the decision on .openshiftconfig and .kubeconfig?
> 
> We had talked about having a separate .openshiftconfig that conforms to a
> .kubeconfig file format, but adds additional fields to a context object
> (either `-kubernetes-context`, or `-kubernetes-cluster` and
> `-kubernetes-user`).  That way `kubectl` could still read the file without
> any difficulty and we'd be able to merge in a .kubeconfig in our hierarchy
> (if we so chose) in order to ease the transition.
> 
> How it could be done:
>  1.  User already has kubernetes installed.  They've been working with it a
>  while and have a working .kube/.kubeconfig file.
>  1.  User wants to add openshift on top of their kubernetes, so they log into
>  openshift and supply a context name for their existing kubernetes.
>  1.  We build a .openshift/.openshiftconfig file for them that has the
>  openshift information and points to the existing -kubernetes-context in
>  their .kubeconfig file.
> 
> By having .openshiftconfig, we can reasonably have first class fields for our
> additional options and I think that will make it more human parsable.  The
> side effect is that `kubectl config *` commands will not work properly
> against .openshiftconfig files.

Two scenarios:

1. User is starting from OpenShift, then works backwards to Kube
2. User starts with Kube and adds OpenShift

Can we just symlink one to the other when we try to create?  I.e. we look for both, we symlink the other if only one exists, if neither exists we create .openshiftconfig and symlink .kubeconfig?  On Windows I don't think kubectl is something we will worry about, it's just linux and Mac.

**Comment by fabianofranz** [comment]
[merge] this as simply exposing `kubectl config` through `openshift-experimental`, will handle the other issues separately.

**Pull request merged**
