### PR TITLE
Add back origin-sdn-ovs

### PR DESCRIPTION
**Pull request by andrewklau**
For some reason this was removed. Without this pods created get a cni configuration issue.

### CODE REVIEW

**Comment by andrewklau** [comment]
Not sure why these always fail for me :(

**Comment by kargakis** [comment]
flaked on https://github.com/openshift/origin/issues/11114

/retest

**Comment by andrewklau** [comment]
Should this also be added in the release-3.6 branch?

**Comment by kargakis** [comment]
If you need it in 3.6, then yes.

**Comment by dcbw** [comment]
@adammhaile it was removed in that commit inadvertently, I believe.  If @kargakis meant to remove the SDN components from the node Dockerfiles completely, then he would have also changed the comment he touched to remove mention of "SDN components" too, I would expect:

```
-LABEL io.openshift.tags="openshift,node" \
-      io.k8s.display-name="OpenShift Origin Node" \
-      io.k8s.description="This is a component of OpenShift Origin and contains the software for individual nodes when using SDN."
+LABEL io.k8s.display-name="OpenShift Origin Node" \
+      io.k8s.description="This is a component of OpenShift Origin and contains the software for individual nodes when using SDN." \
+      io.openshift.tags="openshift,node"
```

The SDN components are meant to be distributed in the node image; I haven't heard any modification to that policy though I could be wrong.

What specific errors are you seeing in your downstream builds?  Can we help fix those?

**Comment by dcbw** [comment]
@adammhaile can you enlighten me as to how the Dockerfiles in dist-git (eg, pkgs.devel openshift-enterprise-node-docker/Dockerfile) are synced with the corresponding ones in origin/ose?

For example, openshift-enterprise-dockerregistry-docker/Dockerfile contains `INSTALL_PKGS="atomic-openshift-dockerregistry" && \` while in origin that corresponding line is images/dockerregistry/Dockerfile `RUN INSTALL_PKGS="origin-dockerregistry" && \`.  What scripts do the change from 'origin->atomic-openshift', and if so, would they need to be updated to do origin-sdn-ovs -> atomic-openshift-sdn-ovs too?  Or do they handle it automatically?

**Comment by stevekuznetsov** [comment]
There is not really any relationship between dist-git and ose ... yet. Lots of work to try to get them to be identical but it seems to have stalled.

**Comment by stevekuznetsov** [comment]
@smunilla and @jupierce will know more

**Comment by adammhaile** [comment]
I'm still pretty new to this team, so hopefully I'm 100% on this, but
basically dist-git has separate branches for the internal (rhel, AOS)
versions of things. So, for Openshift 3.6 RHEL 7 we have this branch in
dist-git:
http://dist-git.app.eng.bos.redhat.com/cgit/rpms/openshift-enterprise-dockerregistry-docker/log/?h=rhaos-3.6-rhel-7
The Dockerfile in that is updated manually.
However, there is the file `.osbs-logs/Dockerfile.git.last`:
http://dist-git.app.eng.bos.redhat.com/cgit/rpms/openshift-enterprise-dockerregistry-docker/tree/.osbs-logs/Dockerfile.git.last?h=rhaos-3.6-rhel-7

That file is supposed to match what is in origin & ose repos. Our process
checks that file against ose (which *should* be the same as origin) and if
that is different then Dockerfile.git.last it throws an error and then
someone has to got and look at the file, discern the intent, and update the
Dockerfile in the root with a RHEL version of that intent.

**Comment by dcbw** [comment]
@adammhaile so it looks like what happened was that Origin containers got broken by https://github.com/openshift/origin/commit/2f7d826ad6bed85e00b3df3db40f25bebb965662#diff-b5321710e6dadcda38c38e45d57c6337L17 in March, but OCP got fixed up by @tdawson in 942aa9a9 to dist-git's openshift-enterprise-node-docker repo.  @andrewklau just finally fixed Origin, but that was then automatically synced over to openshift-enterprise-node-docker which broke the builds, and then required manual fixup.

But it looks like everything is OK now?  v3.6.173.0.1 1" of the openshift-enterprise-node-docker Dockerfile has the atomic-openshift-sdn-ovs RPM in the INSTALL_PKGS line, and does not have the offending "origin-sdn-ovs" package that Origin needs instead.  Can you confirm?

**Comment by adammhaile** [comment]
Correct, I believe we are good now.

**Pull request merged**
