### PR TITLE
 Use dns go bindings instead of dig command for dns resolution in egress network policy

### PR DESCRIPTION
**Pull request by pravisankar**
Also fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=1575583

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/sig-networking @knobunc @danwinship PTAL

**Comment by knobunc** [comment]
@smarterclayton can you approve this please if you find it acceptable?  Thanks

**Comment by smarterclayton** [comment]
I don't have any objection to this, if Ben is fine with this for 3.10 so am
I.

**Comment by knobunc** [comment]
@smarterclayton I am fine with it for 3.10.  I've approved it, but can't approve the change to origin.spec.

**Pull request merged**
