### PR TITLE
UPSTREAM: <carry>: taint-controller-tests: double 'a bit of time' to avoid flakes

### PR DESCRIPTION
**Pull request by sttts**
Follow-up of https://github.com/openshift/origin/issues/13941

Also fixes https://github.com/openshift/origin/issues/13946.

### CODE REVIEW

**Comment by deads2k** [comment]
open upstream and rename this commit.

**Comment by deads2k** [comment]
@derekwaynecarr you're an approver on pkg/controller.  This is a carry we don't need to carry.

**Comment by sttts** [comment]
done

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
upstream is lgtm'ed.  Will merge on green check job.

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/11452 https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/1541/

**Comment by deads2k** [comment]
check is green. failure is #11452 merging

**Pull request merged**
