### PR TITLE
Clean up references to NETWORKING_DEBUG

### PR DESCRIPTION
**Pull request by marun**
#9601 attempted to rename NETWORKING_DEBUG to DLV_DEBUG but missed
a couple of references.

cc: @soltysh @stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Changes LGTM ... sorry about the drift. The friction with networking in the scripts seems to be never-ending. Hopefully we can converge on reasonable shared defaults/names.

**Comment by soltysh** [comment]
Yeah, sorry about that. The changes LGTM.

[merge]

**Comment by marun** [comment]
@stevekuznetsov The irony is that I proposed OPENSHIFT_USE_DEBUGGER when I enabled support for delve in the networking tests in #6205, but was told to use a networking-specific name.  I'm definitely on board with convergence - the less complexity the better - it just might take a while to unwind the results of the previous policy.

**Comment by soltysh** [comment]
Weird failure:
```
FAILURE after 0.300s: hack/test-cmd.sh:228: executing 'openshift ex validate node-config /tmp/openshift/test-cmd//openshift.local.config/node-172.18.4.214/node-config.yaml' expecting success and text 'SUCCESS': the output content test failed
```
I'll re-merge but if it fails again you'll have to rebase your PR, probably.

[merge]

**Pull request merged**
