### PR TITLE
OCPBUGS-27217: [4.15] Live migration suite e2e

### PR DESCRIPTION
**Pull request by martinkennelly**
4.16 PR: https://github.com/openshift/origin/pull/28462

### CODE REVIEW

**Comment by martinkennelly** [comment]
@neisw Hey Forest, we need to backport this to 4.15. The feature was first made available in 4.15.

**Comment by martinkennelly** [comment]
clean cherry-pick of bc4586aae2844d020689b8bbbb68dab33f1f5b26 but i needed to rerun `go mod tidy and go mod vendor`

**Comment by neisw** [comment]
/hold
This seems odd and I don't see that your migration is running but want to point out https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/28524/pull-ci-openshift-origin-release-4.15-e2e-metal-ipi-sdn/1746847432982925312.  

{  fail [github.com/openshift/origin/test/extended/ci/job_names.go:90]: job name "metal-ipi-sdn" has mismatched network type in name (expected `ovn`, found `sdn`)

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/28524/pull-ci-openshift-origin-release-4.15-e2e-metal-ipi-sdn/1746847432982925312/artifacts/e2e-metal-ipi-sdn/baremetalds-devscripts-setup/build-log.txt

`+(network.sh:118): openshift_sdn_deprecated(): printf '4.15\n%s\n' 4.15
+(ocp_install_env.sh:282): generate_ocp_install_config(): NETWORK_TYPE=OVNKubernetes`

You can remove the hold when ready, still need risk assessed cherry pick labeling

**Comment by neisw** [comment]
Seeing that failure in a [4.15 nightly](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm/1746942664256786432) so seems safe to say it isn't related to this pr

**Comment by martinkennelly** [comment]
/unhold

Its unrelated yes. Thank you for highlighting it.

**Comment by martinkennelly** [comment]
@dgoodwin 

Judging from here [1] youve the powers to add both labels?

[1] https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/origin/_pluginconfig.yaml

**Pull request merged**
