### PR TITLE
auto egress IP fixes

### PR DESCRIPTION
**Pull request by danwinship**
Some fixes to the auto egress IP code

### CODE REVIEW

**Comment by danwinship** [comment]
From @pravisankar 's too-late comments on #16561:

> omitempty?

fixed

> Do we expect egress IP to work for IPV6 as well? If not, may be we should add ipv4 check here and in netnamespace.EgressIPs validation.

No... but we aren't requiring IPv4 in most of the other places we only support IPv4 either. I'll file a bug about that.

> We already know the nodeIP (map key), don't need to duplicate in the map value
nodesByNodeIP map[string]*sets.String ?

I guess technically it would work to have one map from node IP to (just) egress IP, and a second map from egress IP to (just) node IP, but I prefer it with the struct, which makes it more obviously parallel to the namespace maps, where we do need the structs

> Since this method will not return an error may be this method can have no return value.

Yeah... I was going to fix that, but then I didn't. It seems like it *could* return an error potentially in the future...

> If assignedIP is already set, then drop the traffic for this namespace?

Because of previous checks, it's guaranteed that it's either unset, or already this IP.

> When namespace is deleted, where are we deleting vnid from namespacesByVNID map?

Fixed

> Failed link may not have desired IP address, we could log an error and continue

Fixed

> We should not call this for single-tenant/subnet plugin as it depends on NetNamespaces. I think, we should move this to node.policy.StartEgressIP?

Fixed

**Comment by danwinship** [comment]
> > Do we expect egress IP to work for IPV6 as well? If not, may be we should add ipv4 check here and in netnamespace.EgressIPs validation.
> 
> No... but we aren't requiring IPv4 in most of the other places we only support IPv4 either. I'll file a bug about that.

#16660

**Comment by danwinship** [comment]
@eparis need an approval from you for "API changes" (I just belatedly marked the new EgressIP fields `+optional`.)

**Comment by smarterclayton** [comment]
Is there an egress extended test?

**Comment by danwinship** [comment]
No, but there are some unit tests.

I guess it would be possible to test in the extended tests, given that pod-to-(public)-node-IP traffic is considered external, so we could run a server in a hostNetwork=true pod on one node and host an egress IP on another...

**Comment by smarterclayton** [comment]
Something we can queue up for 3.8, but i'd like to have at least one
extended test for all features that runs in reasonable time.  GCE runs with
subnet today.

**Pull request merged**
