### PR TITLE
Clear conntrack entries for externalIPs 

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
This brings in two Upstream commits to clear conntrack entries for externalIP addresses

fixes: 
https://bugzilla.redhat.com/show_bug.cgi?id=1632192
https://bugzilla.redhat.com/show_bug.cgi?id=1679260

### CODE REVIEW

**Comment by dcbw** [comment]
@JacobTanenbaum commits need a ':' between PR # and the commit message, says the travis test. After that:
/lgtm

**Comment by dcbw** [comment]
AWS install resource timeouts
/retest

**Comment by dcbw** [comment]
still more AWS install resource timeouts
/retest

**Comment by knobunc** [comment]
@derekwaynecarr can you approve this backport please?  It's a udp conntrack fix.

**Comment by knobunc** [comment]
@eparis can you approve this backport please? It's a udp conntrack fix.

**Comment by JacobTanenbaum** [comment]
@eparis @derekwaynecarr @smarterclayton PTAL could you approve this backport? It is a udp conntrack fix

**Pull request merged**
