### PR TITLE
Correct quoting issue with Forwarded field in HAproxy 1.8

### PR DESCRIPTION
**Pull request by AlbertoPeon**
Solves https://github.com/openshift/origin/issues/20211 (full description on the issue)

### CODE REVIEW

**Comment by AlbertoPeon** [comment]
the tests surely didn't fail because of my pull request?

**Comment by AlbertoPeon** [comment]
It seems I cannot retry the tests myself? Could you advise @knobunc @smarterclayton @ironcladlou ?

It will also be great if this change could be backport to v3.10 as it can break things.

**Comment by AlbertoPeon** [comment]
@ironcladlou @knobunc @smarterclayton , sorry for being a pain, but apparently there are still some transient errors making the test to fail.

**Comment by AlbertoPeon** [comment]
PR rebased with latest changes in master. Could this be retested again? @ironcladlou

**Comment by ironcladlou** [comment]
@knobunc, didn't know about that command, thanks!

**Comment by ironcladlou** [comment]
@AlbertoPeon thanks again for this fix, and for your patience getting through the merge queue!

**Pull request merged**
