### PR TITLE
Rebase service catalog to 0.1.9

### PR DESCRIPTION
**Pull request by jpeeler**

### CODE REVIEW

**Comment by pmorie** [comment]
No whammies

:game_die: :game_die:

**Comment by jpeeler** [comment]
/test extended_conformance_install

Last failure due to:
```
One or more required container images are not available:
                   openshift/origin-docker-registry:dab76e8
```

**Comment by jmrodri** [comment]
I verified this patch upstream.

**Comment by jpeeler** [comment]
GCP test is failing and is blocked by https://github.com/openshift/origin/issues/18823

**Comment by jpeeler** [comment]
flake #18486

/test extended_networking_minimal

**Pull request merged**
