### PR TITLE
Speculative bump of gRPC to 1.2.1 to test for hangs

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton compilable version of https://github.com/openshift/origin/pull/17720... i also bumped the grpc vendored by etcd.

@liggitt @soltysh FYI

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton was the intent here mimic the changes in https://github.com/coreos/etcd/pull/8867 ? I think we will require bump of etcd, don't think just the grpc bump will do the trick?

**Comment by soltysh** [comment]
+1 for etcd bump, which seems easier, esp. that we don't carry any patches anymore, iirc

**Comment by smarterclayton** [comment]
I'm not sure we should be bumping the Kube gRPC version.  The risk of breaking the node is too high.

**Pull request closed without merging**
