### PR TITLE
Change api version in examples

### PR DESCRIPTION
**Pull request by jhadvig**
@mfojtik @kargakis PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
[test][extended:core]

**Comment by mfojtik** [comment]
@jhadvig need to make sure none of the tests are reading that files (should not break anything, just want to make sure ;-)

**Comment by jhadvig** [comment]
@mfojtik yeah Im already doing checks

**Comment by deads2k** [comment]
I'd like a hold on this until after we've disabled https://github.com/openshift/origin/pull/4992.  

Even after we disable that REST endpoint, we should keep at least a few v1beta3 objects as fixtures to make sure the client properly converts and sends to the proper API version.

@ironcladlou

**Comment by ironcladlou** [comment]
@deads2k 
>I'd like a hold on this until after we've disabled #4992.
>Even after we disable that REST endpoint, we should keep at least a few v1beta3 objects as fixtures to make sure the client properly converts and sends to the proper API version.

I agree; I'm actually stuck on the #4992 at the moment tracking down an issue which was only exposed because of the v1beta3 example files used in `test-cmd.sh`.

**Comment by jhadvig** [comment]
@ironcladlou agreed.
What about we update only the sample-apps templates with docker and custom build for now and leave others when your PR lands ?

**Comment by danmcp** [comment]
@jhadvig Bump

**Comment by jhadvig** [comment]
@deads2k @ironcladlou I've updated the PR to only change the sample-app templates and we can change the rest when https://github.com/openshift/origin/pull/4992 landes.

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
