### PR TITLE
e2e - Dump State for Prometheus

### PR DESCRIPTION
**Pull request by adambkaplan**
Dump Prometheus pod state and logs on prometheus builds failure.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 

Want to see if the Prometheus flake dumps useful state.

**Comment by bparees** [comment]
/approve

feel free to self-lgtm when you're ready.

**Comment by gabemontero** [comment]
@adambkaplan ... just a minor suggestion ... in case their CR has useful / concise encapsulations of state, dumping that as well, like I did for the samples operator CR, could lend some context to the pod logs you are dumping .... see https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L127-L137

**Comment by bparees** [comment]
@adambkaplan while you're exercising this, please keep an eye on any other failures in aws-builds that need to be investigated as well.  I saw a jenkins pipeline test failure last night (that I did not have time to investigate) for example.

thanks

**Comment by adambkaplan** [comment]
/retest

One last time to see if the Prometheus test flakes.

**Pull request closed without merging**
