### PR TITLE
UPSTREAM: 23746: A pod never terminated if a container image registry was unavailable

### LINKED ISSUE #8176: Pods stuck in Terminating in 3.2.0.5
Created a lot of pods (1000 across 2 nodes, approx 500 per node).  Then deleted the namespace:

```
# oc delete ns clusterproject0
```

It started doing something because only 319 pods remain out of the 1000.  But now it refuses to go further.  Environment state and logs are below.

I haven't seen this before -- last similar run was on 3.2.0.1, though I only went to 250 pods per node at that code level (things worked ok).

```
# openshift version
openshift v3.2.0.5
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

# oc get no
NAME                                       STATUS                     AGE
dell-r620-01.perf.lab.eng.rdu.redhat.com   Ready,SchedulingDisabled   19d
dell-r730-01.perf.lab.eng.rdu.redhat.com   Ready                      19d
dell-r730-02.perf.lab.eng.rdu.redhat.com   Ready                      19d

# oc get ns
NAME               STATUS        AGE
clusterproject0    Terminating   1d
default            Active        19d
management-infra   Active        19d
openshift          Active        19d
openshift-infra    Active        19d

# oc delete ns clusterproject0
Error from server: namespaces "clusterproject0" cannot be updated: The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
```

All of the stuck-in-terminating pods were scheduled and run on one of the nodes.  The other node was able to successfully terminate all pods that were running there.

From the master:
```
Mar 21 12:18:36 dell-r620-01.perf.lab.eng.rdu.redhat.com atomic-openshift-master[6683]: E0321 12:18:36.451332    6683 namespace_controller.go:139] unexpected items still remain in namespace: clusterproject0 for gvr: { v1 pods}
Mar 21 12:18:37 dell-r620-01.perf.lab.eng.rdu.redhat.com atomic-openshift-master[6683]: W0321 12:18:37.223252    6683 reflector.go:289] /usr/lib/golang/src/runtime/asm_amd64.s:2232: watch of *api.ServiceAccount ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [24072046/23943693]) [24073045]
```

From the node that can't terminate it's pods:
```
Mar 21 12:22:49 dell-r730-01.perf.lab.eng.rdu.redhat.com atomic-openshift-node[7438]: W0321 12:22:49.119784    7438 kubelet.go:1850] Unable to retrieve pull secret clusterproject0/default-dockercfg-woua1 for clusterproject0/hellopods505 due to secrets "default-dockercfg-woua1" not found.  The image pull may not succeed.
```

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #8176 

cc @smarterclayton @liggitt @derekwaynecarr

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by derekwaynecarr** [comment]
LGTM , thanks @ncdc for getting this cherry pick.

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@derekwaynecarr I'm delegating to you to babysit the tests here :p

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
Hit https://github.com/kubernetes/kubernetes/issues/22639
[test]

**Comment by derekwaynecarr** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
```
--- FAIL: TestNewAppRunBuilds-2 (2.21s)
	newapp_test.go:1198: successful input image source build with no repository: unexpected error: no match for "centos/mongodb-26-centos7"
```

[test]

**Comment by ncdc** [comment]
```
Summarizing 3 Failures:

[Fail] deployments: parallel: test deployment test deployment [It] should run a deployment to completion and then scale to zero 
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:29

[Fail] [job] openshift can execute jobs controller [It] should create and run a job in user project 
/data/src/github.com/openshift/origin/test/extended/jobs/jobs.go:26

[Fail] Kubectl client Update Demo [It] should scale a replication controller [Conformance] 
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go:1469

Ran 118 of 383 Specs in 1327.214 seconds
FAIL! -- 115 Passed | 3 Failed | 0 Pending | 265 Skipped 
```

[test]

**Comment by smarterclayton** [comment]
Approved

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
Conformance test failed due to an unrelated networking issue:

```
Cannot find a valid baseurl for repo: extras/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
```

**Comment by smarterclayton** [comment]
[merge]

**Comment by ncdc** [comment]
[merge]

**Comment by smarterclayton** [comment]
font awesome broken again @jwforres

**Comment by ncdc** [comment]
[test]

**Comment by liggitt** [comment]
fontawesome fix merged

**Comment by mdshuai** [comment]
@ncdc How to make the pod status to "RegistryUnavailable" ? I use a unavailable registry for a pod, but it can't return this error "the registry is unavailable".

**Comment by ncdc** [comment]
@mdshuai it was @derekwaynecarr who did all the hard work researching this. Derek, do you have any suggestions for QE?

**Comment by derekwaynecarr** [comment]
the error would only occur if docker itself returned a 50x error.  I do not know a reliable way to force docker to return this as using an unavailable registry would have been a 40x error.

**Pull request merged**
