### PR TITLE
Fix up destination MAC of auto-egress-ip packets

### PR DESCRIPTION
**Pull request by danwinship**
Auto egress packets from pods on nodes other than the one with the egress IP were getting dropped. This turns out to be because the packets will be ignored if you output them on tun0 but they don't have tun0's MAC address as the destination MAC. (For local pods, the default route is via tun0, so the MAC is correct, but for remote pods, the default route is via the tun0 on their node, so the MAC was wrong for the node it eventually ended up on.) 

Also includes two other auto-egress-ip OVS flow fixes.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501876
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507871

### CODE REVIEW

**Comment by danwinship** [comment]
oops, it's actually broken

**Comment by danwinship** [comment]
@knobunc had to tweak it to not try to read the actual tun0 MAC address from unit tests

**Comment by danwinship** [comment]
added another fix, for https://bugzilla.redhat.com/show_bug.cgi?id=1507871

**Comment by knobunc** [comment]
/retest

Flaked on https://github.com/openshift/origin/pull/17105

**Comment by knobunc** [comment]
/retest

Flaked on #17105

**Pull request merged**
