### PR TITLE
Fix oadm router f5 flags

### PR DESCRIPTION
**Pull request by Miciah**
#### Fix oadm router F5 flags

`NewCommandF5Router`: Call `F5Router.Bind` so that the `openshift-f5-router` command's `-f5-*` flags work.

This commit fixes a defect introduced in commit f88e8dc5a2635f0158a7ed0435960b5d5812987f.

#### Fix typo in comment for NewCommandF5Router

Fix a typo in a comment.

-

@rajatchopra, I think this will fix the problem that QE reported.

-

[test]

### CODE REVIEW

**Comment by ramr** [comment]
LGTM   @rajatchopra  is travelling  
@danmcp  can you please merge? Thx

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
@Miciah can you link the fixed issue?

**Comment by liggitt** [comment]
also, go ahead and squash the commits

**Comment by liggitt** [comment]
and you'll need to update completions:
```
Generating fresh completions...

Diffing current completions against freshly generated completions...

diff -Naupr /home/travis/gopath/src/github.com/openshift/origin/rel-eng/completions/bash/openshift /home/travis/gopath/src/github.com/openshift/origin/_output/verify-generated-completions//rel-eng/completions/bash/openshift

--- /home/travis/gopath/src/github.com/openshift/origin/rel-eng/completions/bash/openshift	2015-09-11 17:12:59.000000000 +0000

+++ /home/travis/gopath/src/github.com/openshift/origin/_output/verify-generated-completions//rel-eng/completions/bash/openshift	2015-09-11 17:16:27.514480914 +0000

@@ -4630,6 +4630,13 @@ _openshift_infra_f5-router()

     flags+=("--cluster=")

     flags+=("--config=")

     flags+=("--context=")

+    flags+=("--f5-host=")

+    flags+=("--f5-http-vserver=")

+    flags+=("--f5-https-vserver=")

+    flags+=("--f5-insecure")

+    flags+=("--f5-password=")

+    flags+=("--f5-private-key=")

+    flags+=("--f5-username=")

     flags+=("--fields=")

     flags+=("--help")

     flags+=("-h")

FAILURE: Generated completions out of date. Please run hack/update-generated-completions.sh

make: *** [verify] Error 1
```

**Comment by Miciah** [comment]
QE reported the problem in Trello.  Would you like me to create an issue on Github?

**Comment by liggitt** [comment]
no problem, I assumed there was a BZ

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[test]

**Pull request merged**
