### PR TITLE
[release-4.5] Bug 1846451: UPSTREAM: 90419: update strategy used to reuse CPUs from init containers in CPUManager

### PR DESCRIPTION
**Pull request by cynepco3hahue**
ref: kubernetes/kubernetes#90419

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@sjenning Can I please get the `cherry-pick-approved` label?

**Comment by sjenning** [comment]
@cynepco3hahue that is the job of the patch-manager.

However, I will say they hesitate to approve medium severity bzs for z-stream release.

**Comment by markmc** [comment]
> @cynepco3hahue that is the job of the patch-manager.
> 
> However, I will say they hesitate to approve medium severity bzs for z-stream release.

(patch manager here)

Right, I'm vaguely aware of the justification for this backport, but it would have been nice to see that written down in the bz

**Pull request merged**
