### PR TITLE
refactored test/cmd/deployments to use wrapper methods

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/cc @deads2k 

@ironcladlou  @pweil-  PTAL -- please review and ensure that the expectations (success, failure, with/without text) are correct to what you expected from the tests previously.

### CODE REVIEW

**Comment by bparees** [comment]
deployments are @ironcladlou / @pweil-

**Comment by stevekuznetsov** [comment]
Whoops, copy-paste error. Sorry!

**Comment by deads2k** [comment]
@kargakis ptal?

**Comment by kargakis** [comment]
LGTM

**Comment by deads2k** [comment]
@kargakis thanks, merge at your discretion.

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
