### PR TITLE
update-external-examples to include .NET Core 2.1

### PR DESCRIPTION
**Pull request by tmds**
update-external-examples to include .NET Core 2.1.

@bparees ptal

I can limit this to .NET Core only if that is preferable.

### CODE REVIEW

**Comment by bparees** [comment]
@tmds the cmd test is failing because this PR pulled in the new wildfly image, can you update the test to expect the new image?

```
test/cmd/debug.sh:81: executing 'oc debug isimage/wildfly@sha256:b98dabc8e8f79975c2393e22cf58e7e07137a28a88555ee43b479d2f934a4cb0 -o yaml' expecting success and text 'image: docker.io/openshift/wildfly-130-centos7'
```

basically test/cmd/debug.sh:81 needs to be updated to expect docker.io/openshift/wildfly-140-centos7 instead.

**Comment by bparees** [comment]
(you may need to scan for other references to 130 as well that may need to be updated/augmented)

**Comment by hhorak** [comment]
lgtm

**Comment by bparees** [comment]
@tmds thanks, please squash your commits and i'll merge.

**Pull request merged**
