### PR TITLE
bug 1999288: [release-4.8]: sync with openshift/kubernetes@release-4.8

### PR DESCRIPTION
**Pull request by ingvagabund**
To bring fixes from https://github.com/openshift/kubernetes/pull/1060

### CODE REVIEW

**Comment by ingvagabund** [comment]
https://github.com/opencontainers/runc/pull/3166 needs to be backported into https://github.com/openshift/opencontainers-runc.

**Comment by kolyshkin** [comment]
> [opencontainers/runc#3166](https://github.com/opencontainers/runc/pull/3166) needs to be backported into https://github.com/openshift/opencontainers-runc.

It's a bit more than that 😄 

Done in https://github.com/openshift/opencontainers-runc/pull/10

**Comment by ingvagabund** [comment]
Closing in favor of https://github.com/openshift/origin/pull/26886

**Pull request closed without merging**
