### PR TITLE
restrict project requests to human users: ones with oauth tokens

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/6567

Introduces a `system:humans` group.

@csrwng ptal

### CODE REVIEW

**Comment by csrwng** [comment]
The policy change and cmd test LGTM. I don't know enough about the authenticator to have a say on the change to master_config.go. @liggitt ?

**Comment by liggitt** [comment]
looks fine.. trying to think of a group name I like better, but can't

**Comment by deads2k** [comment]
[merge]

**Comment by liggitt** [comment]
needs associated doc issue/pull, probably to add `system:humans` and `system:serviceaccounts` to this page:
https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#users-and-groups

**Comment by deads2k** [comment]
Unit test timeout.  Will look on Monday.  [Merge]

**Comment by smarterclayton** [comment]
I'm not sure I agree with this change.  Part of our strategy for spinning up apps and testing them from jenkins is going to come from creating new projects and then throwing them away.  We aren't going to give jenkins the ability to create projects or namespaces directly, therefore it still needs to be possible for Jenkins to create namespace projects.  Jenkins is most definitely not a human, therefore we wouldn't add him to the humans group.  It may be enough just to add them to the cluster role binding, but I don't think that flies because the human granting it needs to have the ability to allow the permission.  The limitation is not well thought through enough w.r.t. the actual use cases the system needs to support.

Furthermore, this group is not "humans".  It's "things that are authenticated via oauth" which would be better named "system:oauth-token-authenticated".  I'd be ok with "self-provisioners" containing auth-token-authenticated, I'm not with "humans" being directly mapped.  The jump between that logic and "humans" is not clear - so don't bother.

Finally - this broke Macs because 'base -d' doesn't work.  I'll take care of extracting it into a utility.

**Comment by liggitt** [comment]
Rename of group is fine. That name is awkward, but the concept is awkward, so...

Cmd test works on my Mac… weird

**Comment by smarterclayton** [comment]
Probably have a different base64 version - mine only has `-D`.  What's the source of your base64?

**Comment by liggitt** [comment]
dunno... `which base64` shows `/usr/bin/base64`, so it's not a homebrew one or anything

**Comment by smarterclayton** [comment]
Me too, man page contains: "Mac OS X 10.7                  February 8,
2011                  Mac OS X 10.7"

**Comment by liggitt** [comment]
me too... weird

**Pull request merged**
