### PR TITLE
Bug 1845772: [release-4.2] kubelet: block non-forwarded packets from crossing the localhost boundary

### PR DESCRIPTION
**Pull request by joelsmith**
This is a release-4.2 cherry-pick of https://github.com/openshift/origin/pull/25141

### CODE REVIEW

**Comment by bparees** [comment]
removing valid bug label pending explicit confirmation from someone who has access to the bug, that its upstream clone (4.3.z) has been verified.

**Comment by joelsmith** [comment]
Closing since 4.2 is EOL

**Comment by joelsmith** [comment]
/close
Sorry for reopening - only high/critical issues being fixed in 4.2.

**Pull request closed without merging**
