### PR TITLE
NO-JIRA: bump golang to 1.21 and to latest o/k master 

### PR DESCRIPTION
**Pull request by soltysh**
/assign @dinhxuanvu

### CODE REVIEW

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
I'm seeing this error `operator "cluster-samples-operator" contained an invalid image-references file: input image stream has multiple versions defined for version kubectl for all the tags 1.28.2,1.29.0,1.29.1`.

**Comment by soltysh** [comment]
> I'm seeing this error `operator "cluster-samples-operator" contained an invalid image-references file: input image stream has multiple versions defined for version kubectl for all the tags 1.28.2,1.29.0,1.29.1`.

Yeah, that was solved yesterday, we need to retest it. 

/retest

**Comment by dinhxuanvu** [comment]
Looks like infra failure on ci/prow/e2e-metal-ipi-ovn-ipv6 test.
/retest

**Pull request merged**
