### PR TITLE
fix grammar of resource create message

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@liggitt ptal.

**Comment by liggitt** [comment]
looks fine, bindata needs updating. @spadgett can you pick this up in one of your PRs to spare Ben installing the UI toolchain to fix a typo?

**Comment by bparees** [comment]
i've got the toolchain

**Comment by bparees** [comment]
(I just always forget the process :) )

**Comment by liggitt** [comment]
`hack/install-assets.sh && hack/build-assets.sh` and commit

**Comment by liggitt** [comment]
your bindata diff should be identical to your change

**Comment by bparees** [comment]
@liggitt i meant i forget to do it.  anyway it's done now.  thanks!
[merge]

**Pull request merged**
