### PR TITLE
Rest validation of binary builds is more aggressive

### PR DESCRIPTION
**Pull request by smarterclayton**
The change to validate ObjectMeta *before* the custom strategy
resulted in this failure.

[merge]

### CODE REVIEW

**Comment by liggitt** [comment]
Doesn't strategy.PrepareForCreate get a shot at the object first? This seems like it would belong there

**Comment by smarterclayton** [comment]
It's ObjectMeta first.  Someone changed it to run before the strategy
validation ran.

**Comment by liggitt** [comment]
Strategy.PrepareForCreate, then ValidateObjectMeta(), then Strategy.Validate()

It got added in https://github.com/kubernetes/kubernetes/pull/15191/files#diff-e95024cd74e17563bb837df487a9af11R83

I agree common validation should run post strategy-validation, but that wouldn't help you here unless you were mutating in strategy.Validate... which you're not, and you shouldn't :)

**Comment by smarterclayton** [comment]
It's fine [test]

**Pull request merged**
