### PR TITLE
Show latest deployment in deploy config describe

### PR DESCRIPTION
**Pull request by ironcladlou**
Render the latest deployment when describing a deployment config.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Also closed #874

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
@smarterclayton This needs evaluated for a milestone.

**Comment by smarterclayton** [comment]
Add a hack/test-cmd entry

**Comment by ironcladlou** [comment]
@smarterclayton 
>Add a hack/test-cmd entry

Done.

**Comment by smarterclayton** [comment]
[merge]

**Comment by ironcladlou** [comment]
@smarterclayton I accidentally squashed the commits here and pushed right as you tagged. I cancelled the running build. Can you re-tag?

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
