### PR TITLE
[RPMS] Require device-mapper-persistent-data >= 0.6.2

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1361579

### CODE REVIEW

**Comment by sdodson** [comment]
@tdawson mind reviewing this real quick?

**Comment by sdodson** [comment]
Relaxed the requirement to be 0.6.2 which will ship soon, we'll hold this until that's shipped.

**Comment by ncdc** [comment]
PR title says 0.6.3 but commit is 0.6.2

**Comment by sdodson** [comment]
@ncdc 0.6.2 is in centos now, merge?

**Comment by tdawson** [comment]
I just verified that device-mapper-persistent-data 0.6.2-1.el7_2 is now in RHEL7.

**Comment by tdawson** [comment]
[merge]

**Pull request merged**
