### PR TITLE
Allow PATCH in an API CORS setup

### PR DESCRIPTION
**Pull request by fabianofranz**
Allows the PATCH method to be used in a REST API CORS setup.

Upstream: https://github.com/kubernetes/kubernetes/pull/35978

@jwforres

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by jwforres** [comment]
@openshift/api-review any issues with this change?

**Comment by deads2k** [comment]
> @openshift/api-review any issues with this change?

Looks fine.

**Comment by smarterclayton** [comment]
Same

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/10773 re[merge]

**Pull request merged**
