### PR TITLE
Bug 1874061: Add diff to tests, since e2e-cmd relies on it

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
/lgtm
This is only temporary to unblock e2e-cmd (broken by switch to ubi8) while we work on migrating it to e2e

**Comment by yselkowitz** [comment]
https://github.com/openshift/images/pull/35/ should render this unnecessary.

**Comment by soltysh** [comment]
Closing in favor of https://github.com/openshift/images/pull/35

**Pull request closed without merging**
