### PR TITLE
UPSTREAM: 34028: Add --dry-run option to `oc create` sub-commands

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/34028

Fixes https://github.com/openshift/origin/issues/10426

List of commands to address:

- [x] `oc create [-f ...]`
- [x] `oc create clusterresourcequota`
- [x] `oc create deploymentconfig`
- [x] `oc create identity`
- [x] `oc create imagestream`
- [x] `oc create policybinding`
- [x] `oc create route`
- [x] `oc create user`
- [x] `oc create useridentitymapping`

cc @openshift/cli-review @smarterclayton

### CODE REVIEW

**Comment by juanvallejo** [comment]
@openshift/cli-review PTAL

**Comment by fabianofranz** [comment]
Once https://github.com/kubernetes/kubernetes/pull/34502 and https://github.com/openshift/origin/pull/10993 merges, we could add a `verify-cli-conventions.sh` check to make sure every command under `create` has a `--dry-run` flag.

**Comment by fabianofranz** [comment]
Overall LGTM, let's see how upstream goes.

**Comment by juanvallejo** [comment]
@fabianofranz Sounds good, thanks for taking a look! I've added the `oc create -f ...` command as well to the list, [per this suggestion upstream](https://github.com/kubernetes/kubernetes/pull/34028#issuecomment-251903042).

**Comment by juanvallejo** [comment]
@fabianofranz Upstream merged! https://github.com/kubernetes/kubernetes/pull/34028
@soltysh Added the `dry-run` option to `kubectl apply` to this PR as well if that is okay with you: https://github.com/openshift/origin/pull/11238/commits/d9d259ba72ce8575790d2b40f8bcbd67d8369a7b

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
`oc create route edge --dry-run -o yaml` doesn't seem to work

**Comment by juanvallejo** [comment]
@smarterclayton thanks, will address this

**Pull request merged**
