### PR TITLE
[DO NOT MERGE] eliminate platforms to check timing

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by smarterclayton** [comment]
Just a note: `hack/test-go.sh took 562 seconds` is *insane* and is probably due to coverage.  We should disable coverage during the merge / test queue.

**Comment by liggitt** [comment]
Coverage makes things insanely slow, since it runs a package at a time

**Comment by smarterclayton** [comment]
Let's nuke it.

**Comment by deads2k** [comment]
I thought coverage was already disabled: https://github.com/openshift/origin/blob/master/hack/test-go.sh#L99,  https://github.com/openshift/origin/blob/master/hack/test-go.sh#L99, and https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/run_openshift_tests.rb#L89.

**Comment by smarterclayton** [comment]
In
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5423/consoleFull
I see coverage numbers.

**Pull request closed without merging**
