### PR TITLE
UPSTREAM: 21706: Ensure created service account tokens are available to the token controller

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test][extended:core]

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
merged upstream, [merge]

**Comment by smarterclayton** [comment]
Think this is flaking now https://ci.openshift.redhat.com/jenkins/job/origin_extended/700/testReport/junit/(root)/Extended%20Core/ServiceAccounts_should_ensure_a_single_API_token_exists/

**Comment by liggitt** [comment]
I have two follow ups I'll pull in with the rebase

**Pull request merged**
