### PR TITLE
Bump github.com/docker/go-units

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/11967
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1232251
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1404571

Upstream bump: https://github.com/kubernetes/kubernetes/pull/38130

Bump [github.com/docker/go-units](https://github.com/docker/go-units/) to include https://github.com/docker/go-units/pull/22 which improves the precision of human durations ("about an hour ago", "2 days ago", etc).

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@openshift/cli-review

**Comment by juanvallejo** [comment]
LGTM

cc @liggitt

**Comment by ncdc** [comment]
Post 1.5 rebase, if you don't mind?

**Comment by fabianofranz** [comment]
> Post 1.5 rebase, if you don't mind?

Sure, no problem.  ;)

**Comment by fabianofranz** [comment]
[merge]

**Comment by ncdc** [comment]
```
--- FAIL: TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation (0.00s)
	rest_test.go:1012: Unexpected failure creating service Internal error occurred: Failed to allocate requested HealthCheck nodePort 30200: provided port is already allocated
panic: interface conversion: interface is nil, not *api.Service [recovered]
	panic: interface conversion: interface is nil, not *api.Service
goroutine 105 [running]:
panic(0x16cb320, 0xc42034cc40)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.tRunner.func1(0xc4205792c0)
	/usr/local/go/src/testing/testing.go:579 +0x474
panic(0x16cb320, 0xc42034cc40)
	/usr/local/go/src/runtime/panic.go:458 +0x271
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/service.TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation(0xc4205792c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/service/rest_test.go:1014 +0x58c
testing.tRunner(0xc4205792c0, 0x1988650)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530
```

**Pull request merged**
