### PR TITLE
UPSTREAM(go-dockerclient): 408: fix stdin-only attach

### LINKED ISSUE #5507: One way attach to a pod (stdin only) doesn't close when stdin is EOF
Prior to the last rebase, binary builds were closing normally when the output was completed streaming to the server.  Now, in master (1.0.7) I'm seeing the client exec call stay open even after EOF is read from stdin

Binary build flow:

1. Client connects to server, body is a tar stream
2. Server starts a pod, waits for it to be running
3. Server attaches to the pod with stdin only, provides request body as input
4. Binary is streamed from client to server, and server to pod.
5. Exec client keeps running until the pod terminates

This is not the expected behavior - are we ignoring EOF in the stream code now?

### PR DESCRIPTION
**Pull request by ncdc**
Fix stdin-only attach so it doesn't wait for stdout/stderr to complete
before returning. If hijackOptions.stdout and hijackOptions.stderr are
nil, don't try to copy from the container's streams to ioutil.Discard,
as that keeps the attach session open as long as the container is
running. Instead, only copy stdout/stderr if they're non-nil.

Fixes #5507

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[extended:core]

**Comment by smarterclayton** [comment]
[test]

On Oct 30, 2015, at 5:32 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6485/)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5547#issuecomment-152656311>.

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
:snowflake: city

```
Error from server: imageStream "newrepo" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in test/cmd/images.sh:115
	'oc tag mysql:5.5 newrepo:latest' exited with status 1
Call stack:
	1: test/cmd/images.sh:115 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:276
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:276 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
