### PR TITLE
Bug 1850719: Measure container restarts over an interval instead of absolute

### PR DESCRIPTION
**Pull request by hexfusion**
Manual cherry-pick of https://github.com/openshift/origin/pull/25115 into 4.4

### CODE REVIEW

**Comment by hexfusion** [comment]
passes locally..
/test verify

**Comment by hexfusion** [comment]
cc @smarterclayton @bparees 

unblocking disruptive test for 4.4

**Comment by bparees** [comment]
i fixed up the BZ deps but i think this will still be stuck on the 4.5 BZ verification:

/bugzilla refresh

**Comment by bparees** [comment]
@hexfusion if this test is failing in 4.4, the severity should be higher.  if it's not failing in 4.4, then you're probably going to get pushback from the patch manager about the need to backport this.

/lgtm
/approve

**Pull request merged**
