### PR TITLE
Bug 2066865: bump openshift/kubernetes

### PR DESCRIPTION
**Pull request by jsafrane**
To skip azure topology tests with CSI migration enabled. See https://github.com/openshift/kubernetes/pull/1230 and the BZ for details.

I also regenerated the test annotations in the second commit.

cc @openshift/storage

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by jsafrane** [comment]
checking my power here
/override ci/prow/e2e-gcp

**Pull request merged**
