### PR TITLE
do not tag for pushing if there is no output target

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@rhcarvalho ptal. fyi this was causing extended test failures (the tag operation fails if there's no output reference to tag it to).  We need to get better about running them/checking them.

**Comment by bparees** [comment]
[testonlyextended][extended:core(build without output image)]

**Comment by bparees** [comment]
[merge]

**Comment by rhcarvalho** [comment]
ack

**Pull request merged**
