### PR TITLE
make cluster up use local config path by default

### PR DESCRIPTION
**Pull request by deads2k**
Update `oc cluster up` to use `openshift.local.clusterup` as a base directory instead of tmp by default.

This is a first step towards removing `--use-existing-config` (default action, delete the config if you want fresh, or specify a different directory), `--host-data-dir` (if you need point somewhere, put that content in the expected location), `host-volumes-dir` (use the location we provision), `host-pv-dir` (use the location we provision).

/assign @mfojtik 
/assign @soltysh

### CODE REVIEW

**Comment by deads2k** [comment]
@mfojtik @soltysh @bparees it failed, but notice the pretty installation logs we now have: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/18944/test_pull_request_origin_extended_clusterup/576/artifacts/scripts/clusterup/artifacts/noargs/openshift.local.clusterup/logs/

**Comment by deads2k** [comment]
`error instantiating Build from BuildConfig myproject/ruby-hello-world (0): Error resolving ImageStreamTag ruby-22-centos7:latest in namespace myproject: unable to find latest`

Is that something that needs an image import to succeed?

**Comment by bparees** [comment]
> Is that something that needs an image import to succeed?

yes

**Comment by deads2k** [comment]
@mfojtik think I found the problem, setting the value in all clusterup tests to avoid accidental re-use.

**Comment by deads2k** [comment]
superceded

**Pull request closed without merging**
