### PR TITLE
Add openssh-clients package to f5-router

### PR DESCRIPTION
**Pull request by pecameron**
cherry-pick pr/21430 (v3.11) to 3.10

bug: 1645755
https://bugzilla.redhat.com/show_bug.cgi?id=1645755

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@pweil- PTAL

**Comment by pecameron** [comment]
@knobunc PTAL

**Comment by pecameron** [comment]
@knobunc @dcbw There has been some interest in fixing bug 1645755. This was fixed in 3.11 and cherry picked here. Is there anything more to do on this PR? PTAL

**Comment by dcbw** [comment]
Travis flake is well-known on 3.10

`/home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 129: OS_GIT_MAJOR: unbound variable`

**Comment by dcbw** [comment]
/lgtm

@knobunc could you please approve? Thanks!

**Comment by pecameron** [comment]
@dcbw The test problems have nothing to do with the backport. What do we do about this?
/retest

**Comment by pecameron** [comment]
@dcbw any thoughts on what to do with this?
@knobunc Could you please approve it if nothing needs to be changed?
/assign @pweil- PTAL

**Comment by pecameron** [comment]
Travis problem: /home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 129: OS_GIT_MAJOR: unbound variable
has nothing to do with this PR. What do we do about this? @dcbw @pweil-

**Comment by pecameron** [comment]
@pweil- @knobunc @dcbw @squeed This is the actual bug that was reported in 3.10. It was fixed in 3.11 and back ported here. Its been over a month waiting for the next step. What does it take to move this forward?

**Comment by pecameron** [comment]
@pweil- @knobunc @dcbw @squeed This is the actual bug that was reported in 3.10. It was fixed in 3.11 and back ported here. The PR goes back to 4/22. What do I need to do to get this to make progress? PTAL

**Comment by pecameron** [comment]
@smarterclayton @ironcladlou This has been hanging around for a while now. Could you please help me to move this forward? I will make whatever changes you think are needed. Thanks. PTAL

**Comment by ironcladlou** [comment]
Thanks for your patience, took us a while to get our attention back here.

/approve

**Comment by ironcladlou** [comment]
@knobunc forgot my OWNERs fixes are stuck in limbo — can you tag this?

**Comment by pecameron** [comment]
@ironcladlou As far as I can tell the travis-ci error doesn't have anything to do with the Docker file changes. If it does, what do I need to do to get past this? Thanks!

**Comment by knobunc** [comment]
@stevekuznetsov do you know who the Travis Bot herder is?  Thanks

**Pull request merged**
