### PR TITLE
BZ 1370045: Fix pushing to GCS storage

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

@smarterclayton review pls.

**Comment by smarterclayton** [comment]
Only manual testing here?

**Comment by mfojtik** [comment]
@smarterclayton I tried to apply the second fix (https://github.com/docker/distribution/pull/1703) and still no luck, getting "upload resumed at wrong offest: 508 != 254".

**Comment by mfojtik** [comment]
@smarterclayton ok, with the second fix I'm only getting `err.code="blob upload invalid" err.message="blob upload invalid"` and I don't see the offset anymore...

**Comment by mfojtik** [comment]
@smarterclayton tested manually and verified it works.

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by bdurrow** [comment]
My test still fails:
builder.go:204] Error: build error: Failed to push image. Response from registry is: blob upload unknown

**Comment by bdurrow** [comment]
I was able to work around the problem doing the following:

Added the middleware config as indicated here:
https://github.com/openshift/origin/issues/10324

Pulled in some upstream patches, I think the only required on is #1817.

PATCH_TMP=/tmp/patch-tmp
GOHOME=/tmp/go
cd ${GOHOME}/src/github.com/openshift/origin &&
git clean -f &&
git clean -fd &&
git fetch origin &&
git reset --hard 5983e63d531dcc379e254882c8e2ec32e9f9226d &&
cd vendor/github.com/docker/distribution &&
rm -rf $PATCH_TMP &&
mkdir -p $PATCH_TMP &&
git clone --bare https://github.com/docker/distribution $PATCH_TMP &&
#UPSTREAM: docker/distribution: 1688: Pass through known errors
git --git-dir=$PATCH_TMP diff ba92700..3730470b641dcb7ebe50e32512ad4565fa340027 | patch --batch -p1 --no-backup-if-mismatch --reject-file=- &&
git add -A ./ &&
git commit -am "UPSTREAM: docker/distribution: 1688: Pass through known errors" &&
#UPSTREAM: docker/distribution: 1817: Blobwriter: call BlobWriter.Size after BlobWriter.Close
git --git-dir=$PATCH_TMP diff 4ecea4b311d968fb789e30a78c8c6510996a9183..eca581cf36d7994b171f8b357f78de1d923474ff | patch --batch -p1 --no-backup-if-mismatch --reject-file=- || true &&
git add -A ./ &&
git commit -am "UPSTREAM: docker/distribution: 1817: Blobwriter: call BlobWriter.Size after BlobWriter.Close" &&
#UPSTRAM: docker/distribution: 1782: Update "Accept" header parsing for list values
git --git-dir=$PATCH_TMP diff 75882f0..8907f7d1899a578e3e5d10ec34ec49f1841fb154 | patch --batch -p1 --no-backup-if-mismatch --reject-file=- || true &&
git add -A ./ &&
git commit -am "UPSTREAM: docker/distribution: 1817: Avoid formatting errors with %#v" &&
#UPSTREAM: docker/distribution: 1817: Avoid formatting errors with %#v
git --git-dir=$PATCH_TMP diff b49f8ed..e015cbadd6b93e12b58f84b6f1c3640995bce034 | patch --batch -p1 --no-backup-if-mismatch --reject-file=-  &&
git add -A ./ &&
git commit -am "UPSTREAM: docker/distribution: 1817: Avoid formatting errors with %#v" &&
#UPSTREAM: docker/distribution: 1787: Re-add support for non-resumable digests 
git --git-dir=$PATCH_TMP diff 1fc752c..ccfa25cf000f460199484bda4b3c89d52a388c6b | patch --batch -p1 --no-backup-if-mismatch --reject-file=- &&
git add -A ./ &&
git commit -am "UPSTREAM: docker/distribution: 1787: Re-add support for non-resumable digests" &&
rm -rf $PATCH_TMP &&
cd ${GOHOME}/src/github.com/openshift/origin &&
git tag --force v1.3.0-alpha.3-distributionv2.4-workaround &&
sudo make release

Thank you for your time,

Brad

**Comment by mfojtik** [comment]
@bdurrow I tested this patch against GCS and I got my image pushed just fine. I think your fix might be better, but I tested that as well before I ended up with the "quick fix" and I was still seeing the error.

**Comment by mfojtik** [comment]
@bdurrow I tested on the latest OpenShift Docker Registry image (2.4.0)

**Comment by mfojtik** [comment]
@bdurrow you can try it using `docker.io/mfojtik/test-registry:v4` (which has this fix applied)

**Comment by bdurrow** [comment]
Upstream PR 1705 is against 2.4 instead of master and my be preferred. I tried the openshift/origin-docker-registry:latest last night and got the failure I mentioned above.  The build was from 2 hours earlier so I believe this PR (10640) was included.

**Comment by bdurrow** [comment]
@mfojtik, My test with docker.io/mfojtik/test-registry:v4 just passed.

**Pull request merged**
