### PR TITLE
Bug 1713446: toggle ssh parameters if ssh-auth source secret includes a known_host…

### PR DESCRIPTION
**Pull request by gabemontero**
…s setting

/assign @adambkaplan 

@openshift/openshift-team-developer-experience FYI

since the repos are different between 3.x and 4.x simply had to duplicate the 4.x change in the builder repo into the origin repo.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@gabemontero jenkins-driven tests may be broken due to recent infra changes

**Comment by gabemontero** [comment]
yep considered that @adambkaplan but I had an e2e-gcp-crio flake

next time I'll remember to use slash test e2e-gcp-crio instead 

but certainly we'll need to confirm the situation when it comes time to merging ... it would be good to get an extended builds run with this PR

**Comment by gabemontero** [comment]
OK everything is passing but e2e-gcp-crio

It is looking like perhaps an openshift ansible error during install.  Here is the snippet in question:

```
TASK [openshift_examples : Remove defunct quickstart template files] ***********
task path: /usr/share/ansible/openshift-ansible/roles/openshift_examples/tasks/x86_64_examples.yml:42
Thursday 19 September 2019  20:14:45 +0000 (0:00:00.657)       0:23:35.157 **** 
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=/usr/share/openshift/examples/quickstart-templates/nodejs.json) => {"changed": false, "item": "/usr/share/openshift/examples/quickstart-templates/nodejs.json", "path": "/usr/share/openshift/examples/quickstart-templates/nodejs.json", "state": "absent"}
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=/usr/share/openshift/examples/quickstart-templates/cakephp.json) => {"changed": false, "item": "/usr/share/openshift/examples/quickstart-templates/cakephp.json", "path": "/usr/share/openshift/examples/quickstart-templates/cakephp.json", "state": "absent"}
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=/usr/share/openshift/examples/quickstart-templates/dancer.json) => {"changed": false, "item": "/usr/share/openshift/examples/quickstart-templates/dancer.json", "path": "/usr/share/openshift/examples/quickstart-templates/dancer.json", "state": "absent"}
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=/usr/share/openshift/examples/quickstart-templates/django.json) => {"changed": false, "item": "/usr/share/openshift/examples/quickstart-templates/django.json", "path": "/usr/share/openshift/examples/quickstart-templates/django.json", "state": "absent"}

TASK [openshift_examples : Remove defunct quickstart templates from openshift namespace] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_examples/tasks/x86_64_examples.yml:52
Thursday 19 September 2019  20:14:46 +0000 (0:00:00.946)       0:23:36.103 **** 
failed: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] (item=nodejs-example) => {"changed": false, "cmd": ["oc", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "delete", "templates/nodejs-example"], "delta": "0:00:00.322513", "end": "2019-09-19 20:14:47.290180", "failed_when_result": true, "item": "nodejs-example", "msg": "non-zero return code", "rc": 1, "start": "2019-09-19 20:14:46.967667", "stderr": "Unable to connect to the server: dial tcp: lookup internal-api.ci-op-gq5pmphf-f8b79.origin-ci-int-gce.dev.rhcloud.com on 10.142.0.5:53: no such host", "stderr_lines": ["Unable to connect to the server: dial tcp: lookup internal-api.ci-op-gq5pmphf-f8b79.origin-ci-int-gce.dev.rhcloud.com on 10.142.0.5:53: no such host"], "stdout": "", "stdout_lines": []}
failed: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] (item=cakephp-example) => {"changed": false, "cmd": ["oc", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "delete", "templates/cakephp-example"], "delta": "0:00:00.195711", "end": "2019-09-19 20:14:47.672470", "failed_when_result": true, "item": "cakephp-example", "msg": "non-zero return code", "rc": 1, "start": "2019-09-19 20:14:47.476759", "stderr": "Unable to connect to the server: dial tcp: lookup internal-api.ci-op-gq5pmphf-f8b79.origin-ci-int-gce.dev.rhcloud.com on 10.142.0.5:53: no such host", "stderr_lines": ["Unable to connect to the server: dial tcp: lookup internal-api.ci-op-gq5pmphf-f8b79.origin-ci-int-gce.dev.rhcloud.com on 10.142.0.5:53: no such host"], "stdout": "", "stdout_lines": []}
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=dancer-example) => {"changed": false, "cmd": ["oc", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "delete", "templates/dancer-example"], "delta": "0:00:00.272583", "end": "2019-09-19 20:14:48.118411", "failed_when_result": false, "item": "dancer-example", "msg": "non-zero return code", "rc": 1, "start": "2019-09-19 20:14:47.845828", "stderr": "Error from server (NotFound): templates.template.openshift.io \"dancer-example\" not found", "stderr_lines": ["Error from server (NotFound): templates.template.openshift.io \"dancer-example\" not found"], "stdout": "", "stdout_lines": []}
ok: [ci-op-gq5pmphf-f8b79-ig-m-fxm5] => (item=django-example) => {"changed": false, "cmd": ["oc", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "delete", "templates/django-example"], "delta": "0:00:00.225765", "end": "2019-09-19 20:14:48.517479", "failed_when_result": false, "item": "django-example", "msg": "non-zero return code", "rc": 1, "start": "2019-09-19 20:14:48.291714", "stderr": "Error from server (NotFound): templates.template.openshift.io \"django-example\" not found", "stderr_lines": ["Error from server (NotFound): templates.template.openshift.io \"django-example\" not found"], "stdout": "", "stdout_lines": []}
```

I *believe* that corresponds to https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_examples/tasks/x86_64_examples.yml#L84-L93

though the line numbers in the error don't match with the latest openshift-ansible 3.11 branch.

Should we even be failing that step if the items we are trying to delete are not found??

@sdodson - who is covering 3.11.x openshift-ansible install questions these days?

@bparees @adambkaplan FYI

I'll retest again to see how consistent this is

**Comment by gabemontero** [comment]
ansible install failed much earlier this time with https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23782/pull-ci-openshift-origin-release-3.11-e2e-gcp-crio/162

/retest

**Comment by gabemontero** [comment]
ok the ansible install worked this time, but there are a bunch of k8s e2e pre test flakes with nodes supposedly not fully ready

I'll ask during scrum or on slack about this e2e-gcp-crio test (pkg/build/builder triggered it) ... it is only 3.11 .... perhaps it has rotted on the vine

**Comment by sdodson** [comment]
> @sdodson - who is covering 3.11.x openshift-ansible install questions these days?

@jcpowermac right now, but that looks like a failure in the SDN pod if the ip address is a node ip or GCP infra if it's GCP dns server that IP address corresponds to.

**Comment by gabemontero** [comment]
@bparees - do you have any recollections on who owns / who created / who knows about this e2e-gcp-crio job which appears to only be enabled on 3.11 ?

Just thought I would double check before throwing it over the wall to forum-testplatform, etc. ... given its narrow focus in openshift/release (https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml#L181-L183) it smells like a snowflake.

It has never been able to get past kube-system pods readiness checks, with the logs having messages about config.json formats being incorrect and the 8443 ports already in use.

**Comment by sdodson** [comment]
> @bparees - do you have any recollections on who owns / who created / who knows about this e2e-gcp-crio job which appears to only be enabled on 3.11 ?

I think that was @umohnani8, if not they'd know.

**Comment by bparees** [comment]
> @bparees - do you have any recollections on who owns / who created / who knows about this e2e-gcp-crio job which appears to only be enabled on 3.11 ?

also possibly @mrunalp @nalind and the containers team since it's probably their job.

**Comment by gabemontero** [comment]
> > @bparees - do you have any recollections on who owns / who created / who knows about this e2e-gcp-crio job which appears to only be enabled on 3.11 ?
> 
> also possibly @mrunalp @nalind and the containers team since it's probably their job.

Yeah I asked @nalind in scrum yesterday and he had no recollection of it.

@umohnani8 @mrunalp ?

**Comment by umohnani8** [comment]
@gabemontero I added the e2e-aws jobs for cri-o for 4.1 and 4.2. Not sure who added the e2e-gcp-cri-o job for 3.11. @mrunalp will know

**Comment by adambkaplan** [comment]
@smarterclayton Looks like `pkg/build/builder` was there when the `gcp-crio` job was created. Do you recall why?

**Comment by gabemontero** [comment]
See https://github.com/openshift/release/pull/5210 for a summary of the exchange I had with @mrunalp , who created the e2e-gcp-crio job, and his team's current priorities wrt to it.

**Pull request merged**
