### PR TITLE
Fix kubernetes go 1.5 travis flakes

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
We still have to pickup https://github.com/kubernetes/kubernetes/issues/14138 to fix the flakes in travis.

**Comment by mfojtik** [comment]
@kargakis @deads2k FYI

**Comment by mfojtik** [comment]
@kargakis go 1.5.1 passed travis \o/ PTAL

**Comment by kargakis** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Comment by liggitt** [comment]
fyi, this was immediately reverted upstream, the latest rebase will drop it. the 1.5.1 races are more systemic... I think an actual change to the informer framework is needed, not just a fix to the tests

**Pull request merged**
