### PR TITLE
Updating 3.7 images to build on Container Pipeline Service.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
- Added cccp.yml for source image.
- Deleted dockerregistry, node, origin and pod Dockerfile.centos7
  as they are exact replicas.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@stevekuznetsov @tdawson ping

**Comment by sdodson** [comment]
I don't see any obvious problems with this but that assumes that the .centos7 files aren't in use by any of our CI/CD processes which I'm not sure of.

**Comment by mohammedzee1000** [comment]
@sdodson @stevekuznetsov I have restored toe Dockerfile.centos7 s. PTAL

**Pull request closed without merging**
