### PR TITLE
Don't show errors in name field until blurred

### LINKED ISSUE #4828: Name field should not show errors until you're done typing
The field error message can flicker as you type in the name field on the from image page in the UI, for example, when you type a `-` until you type another character. We can fix the problem by only showing errors on field blur or perhaps debounce.

@jwforres

### PR DESCRIPTION
**Pull request by spadgett**
Check for `$touched` rather than `$dirty`, which is true only when the input loses focus.

Fixes #4828

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
If you don't change the value but tab through the field does $touched get set? Or does $touched only get set if the field is also $dirty?

**Comment by spadgett** [comment]
If you tab out without changing the value, $touched is set.

**Comment by jwforres** [comment]
So if you tab through a required field and don't set a value then its going to warn you that its required... yeah I guess that's ok.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
