### PR TITLE
The kube major/minor version is missing from /version in 3.9

### PR DESCRIPTION
**Pull request by smarterclayton**
Works fine in 3.10

### CODE REVIEW

**Comment by smarterclayton** [comment]
Caused a conformance test failure.

@mfojtik this probably needs to make it into OSE3.9.  I'm going to certify against the origin version for the conformance results, but without this we return empty strings in gitMajor and gitMinor from /version.

**Comment by mfojtik** [comment]
@smarterclayton I will pick this for OSE

**Comment by smarterclayton** [comment]
GCP is failing on a router test (router can't access backend pod), I swear we fixed something like this in master @openshift/networking 

Going to force merge since this is unrelated to the change (i added more debug info to the test).

**Pull request merged**
