### PR TITLE
restore deep copy generation

### PR DESCRIPTION
**Pull request by deads2k**
We still need deep copy for types we haven't move (those should probably be moved) and internal types (these will stay).  Found this while messing with the rebase.

/assign mfojtik

@bparees @enj fyi

### CODE REVIEW

**Comment by deads2k** [comment]
@kargakis can you point me at directions for the cherry-pick bot?

**Comment by kargakis** [comment]
@deads2k `/cherrypick release-3.x` is what you want?

**Comment by enj** [comment]
@simo5 this is probably what broke your deep copies.

**Comment by mfojtik** [comment]
wow green tests. so rare these days

**Pull request merged**
