### PR TITLE
UPSTREAM: 51644: do not update init containers status if terminated

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/51644

xref https://bugzilla.redhat.com/show_bug.cgi?id=1486356

@derekwaynecarr @bparees

### CODE REVIEW

**Comment by sjenning** [comment]
@derekwaynecarr @smarterclayton can I get review/approval on this?

**Comment by sjenning** [comment]
flaking on https://github.com/openshift/origin/issues/16323

**Comment by stevekuznetsov** [comment]
```
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v3.6.0
               Configured registries: docker.io
```

WTF?

**Pull request merged**
