### PR TITLE
Tolerate 1.20 error message in test-cmd

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @soltysh

### CODE REVIEW

**Comment by tnozicka** [comment]
vpc limit
/retest

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
gcp-upgrade flake fin in https://github.com/openshift/origin/pull/25737
/retest

**Comment by tnozicka** [comment]
limited to test-cmd,
aws is borked, gcp-upgrade flakes on different things and infra - both unrelated
/override ci/prow/e2e-aws-fips
/override ci/prow/e2e-gcp-upgrade

**Comment by tnozicka** [comment]
gcp infra flake again
/retest

**Pull request merged**
