### PR TITLE
handle case where we have no build start time

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jwforres ptal, i went with this option over setting the start time==completion time because i'd rather lie a little in the description than lie completely in the recorded fields.

**Comment by bparees** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM

**Comment by jwforres** [comment]
Yeah i agree. I went with the same approach in the web console PR

**Comment by bparees** [comment]
[merge]

**Pull request merged**
