### PR TITLE
Tweak clientset, lister, informer generated code locations

### PR DESCRIPTION
**Pull request by ncdc**
- Add generated shared informers
- Fix lister generation
- Place clientsets, listers, and shared informers under `pkg/<api group>/generated`.

Supersedes #13961 #13962 

@mfojtik @soltysh @pweil- @smarterclayton @deads2k @liggitt @sttts @pmorie @derekwaynecarr @bparees

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
Green tests

**Comment by soltysh** [comment]
LGTM

**Comment by deads2k** [comment]
lgtm

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
#13942 [merge]

**Pull request merged**
