### PR TITLE
Disable create form inputs and submit button while the API request is happening

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/5374

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL  i went ahead and disabled the form inputs as well

**Comment by spadgett** [comment]
Looks good... Do we have the problem on the create flow forms as well?

**Comment by jwforres** [comment]
Hmmm yep looks like it, just from looking at the source.

**Comment by jwforres** [comment]
@spadgett updated to include both the create forms, and double checked it on latest safari and IE

**Comment by jwforres** [comment]
[test]

**Comment by spadgett** [comment]
The cancel button is disabled by the fieldset, correct?

LGTM

**Comment by jwforres** [comment]
I will double check. I think the reason the submit button is special is
because it has its own ng-disabled.

**Comment by jwforres** [comment]
Yep it gets disabled.

[merge]

**Comment by jwforres** [comment]
[test]

**Pull request merged**
