### PR TITLE
oc describe build output improvements

### LINKED ISSUE #5247: Build and build config describers are poorly laid out and not useful to users
Probably need to be reorganized for structure, a lot of the duplicate fields are confusing or not properly presented.  Engage UX and others.  A lot of fields can probably be unified, or simplified.

### PR DESCRIPTION
**Pull request by php-coder**
Trello card: https://trello.com/c/l8CyWprA/863-3-clean-up-the-build-describe-output
Fix #5247

PTAL @bparees @jwforres @smarterclayton 

Note: build config describer mostly unchanged.

Example output:
```console
$ oc describe build ruby-hello-world-1 
Name:			ruby-hello-world-1
Created:		58 seconds ago
Labels:			app=ruby-hello-world
				buildconfig=ruby-hello-world
				openshift.io/build-config.name=ruby-hello-world
Annotations:	openshift.io/build.number=1
				openshift.io/build.pod-name=ruby-hello-world-1-build

Status:			Complete
Started:		Fri, 01 Apr 2016 14:22:36 UTC
Duration:		46s
Build Config:	ruby-hello-world
Build Pod:		ruby-hello-world-1-build

Strategy:			Source
URL:				https://github.com/openshift/ruby-hello-world.git
Commit:				bd94cbb (Merge pull request #52 from bparees/stdout)
Author/Committer:	Ben Parees
From Image:			DockerImage centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
Output to:			ImageStreamTag ruby-hello-world:latest
Push Secret:		builder-dockercfg-m9x7z

Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  58s		58s		1	{default-scheduler }						Normal		Scheduled	Successfully assigned ruby-hello-world-1-build to localhost.localdomain
  57s		57s		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Pulled		Container image "openshift/origin-sti-builder:v1.1.4" already present on machine
  56s		56s		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Created		Created container with docker id 328f9f39f368
  56s		56s		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Started		Started container with docker id 328f9f39f368
```

```console
$ oc describe bc/ruby-hello-world
Name:			ruby-hello-world
Created:		11 minutes ago
Labels:			app=ruby-hello-world
Annotations:	openshift.io/generated-by=OpenShiftNewApp
Latest Version:	1

Strategy:			Source
URL:				https://github.com/openshift/ruby-hello-world.git
From Image:			ImageStreamTag ruby-22-centos7:latest
Output to:			ImageStreamTag ruby-hello-world:latest
Triggered by:		Config, ImageChange
Webhook GitHub:		https://localhost:8443/oapi/v1/namespaces/test/buildconfigs/ruby-hello-world/webhooks/Fbklht-OP-w1EMEWOJXY/github
Webhook Generic:	https://localhost:8443/oapi/v1/namespaces/test/buildconfigs/ruby-hello-world/webhooks/xshVl6kq2OYcdLJYabPl/generic

Build				Status		Duration	Creation Time
ruby-hello-world-1 	complete 	46s 		2016-04-01 14:22:33 +0000 UTC
```

### CODE REVIEW

**Comment by jwforres** [comment]
This is looking a lot better, the only thing i'm not sure about is that all the source details are before the Strategy: Source line.

**Comment by php-coder** [comment]
@jwforres Yes, I can re-order them:

```console
$ oc describe build ruby-hello-world-1 
...
Strategy:		Source
From Image:		DockerImage centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
Output to:		ImageStreamTag ruby-hello-world:latest
Push Secret:	builder-dockercfg-m9x7z

URL:				https://github.com/openshift/ruby-hello-world.git
Commit:				bd94cbb (Merge pull request #52 from bparees/stdout)
Author/Committer:	Ben Parees
```

```console
$ oc describe bc/ruby-hello-world
...
Strategy:			Source
From Image:			ImageStreamTag ruby-22-centos7:latest
Output to:			ImageStreamTag ruby-hello-world:latest
Triggered by:		Config, ImageChange
Webhook GitHub:		https://localhost:8443/oapi/v1/namespaces/test/buildconfigs/ruby-hello-world/webhooks/Fbklht-OP-w1EMEWOJXY/github
Webhook Generic:	https://localhost:8443/oapi/v1/namespaces/test/buildconfigs/ruby-hello-world/webhooks/xshVl6kq2OYcdLJYabPl/generic

URL:	https://github.com/openshift/ruby-hello-world.git
```

**Comment by bparees** [comment]
i'm not convinced we need a line break between the strategy/from/etc block and the url/commit/etc block.

all those items are config/input into the buildconfig or build that was run, so i think they can be grouped together ("From Image" has just as much impact on your build result as your "URL", for example, and either one can change for a given build)

putting the URL right under the strategy seems desirable since for most cases we'd then have:

```
Strategy: Source
URL: https://foo.bar/foo.git
```

which has a very natural flow to it, imo

**Comment by bparees** [comment]
otherwise i second @jwforres, this is a huge improvement, thanks!

**Comment by bparees** [comment]
will Author/Committer show two values if they are different?  (under what circumstances could they be different?  i'm not up on my git terminology :) )

**Comment by jwforres** [comment]
Author is the original author of the commit (I think) and then in cases
where someone does a rebase that includes someone else's commits, then the
committer can be different, example see the 1.3 console branch
https://github.com/openshift/origin/pull/8214/commits

**Comment by php-coder** [comment]
>will Author/Committer show two values if they are different?

@bparees Yes, it will show 2 values on the same line. For example:
```Author/Committer:   Ben Parees / Slava Semushin```

> (under what circumstances could they be different? i'm not up on my git terminology :) )

When you're `cherry-pick`-ing someone's commit or applying it with `git am` AFAIR.

**Comment by bparees** [comment]
> @bparees Yes, it will show 2 values on the same line. For example:
Author/Committer: Ben Parees / Slava Semushin

cool, sounds good.

**Comment by php-coder** [comment]
>i'm not convinced we need a line break between the strategy/from/etc block and the url/commit/etc block.

I've combine them together.

**Comment by bparees** [comment]
@php-coder can you paste a sample of the new output for a BC and build?  I think we're in good shape but it'd be easier to confirm w/ a sample.

**Comment by php-coder** [comment]
@bparees I updated the example in the description.

**Comment by bparees** [comment]
I hate that we called our build sequence id "last version" but that's part of the api, so not your problem :)

can I see an example with a BC/build that declares 2+ image input sources, some with 1 path and some with multiple paths?  this template contains the skeleton for such a BC:
https://github.com/openshift/origin/blob/master/test/extended/fixtures/test-imagesource-build.yaml

**Comment by php-coder** [comment]
>can I see an example with a BC/build that declares 2+ image input sources, some with 1 path and some with multiple paths?

@bparees Yes, sure:

```console
$ oc describe bc/imagesourcebuild
Name:			imagesourcebuild
Created:		6 minutes ago
Labels:			build=imagesourcebuild
Annotations:	<none>
Latest Version:	1

Strategy:		Source
URL:			https://github.com/openshift/ruby-hello-world.git
From Image:		ImageStreamTag openshift/ruby:latest
Force Pull:		yes
Output to:		ImageStreamTag imagesourceapp:latest
Image Source:	copies /usr/lib/jenkins/jenkins.war from openshift/jenkins:latest to injected/dir
Triggered by:	<none>

Build				Status		Duration			Creation Time
imagesourcebuild-1 	running 	running for 3m4s 	2016-04-04 12:21:05 +0000 UTC


$ oc describe build/imagesourcebuild-1
Name:			imagesourcebuild-1
Created:		3 minutes ago
Labels:			build=imagesourcebuild
				buildconfig=imagesourcebuild
				openshift.io/build-config.name=imagesourcebuild
Annotations:	openshift.io/build.number=1
				openshift.io/build.pod-name=imagesourcebuild-1-build

Status:			Complete
Started:		Mon, 04 Apr 2016 12:21:08 UTC
Duration:		3m5s
Build Config:	imagesourcebuild
Build Pod:		imagesourcebuild-1-build

Strategy:			Source
URL:				https://github.com/openshift/ruby-hello-world.git
Commit:				bd94cbb (Merge pull request #52 from bparees/stdout)
Author/Committer:	Ben Parees
From Image:			DockerImage centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
Force Pull:			yes
Output to:			ImageStreamTag imagesourceapp:latest
Image Source:		copies /usr/lib/jenkins/jenkins.war from openshift/jenkins-1-centos7@sha256:be195f14530529244b45995aa7220b21b0eb407a37739c43ba9aaa6a5b4f0732 to injected/dir
Push Secret:		builder-dockercfg-y92fy

Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  3m		3m		1	{default-scheduler }						Normal		Scheduled	Successfully assigned imagesourcebuild-1-build to localhost.localdomain
  3m		3m		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Pulled		Container image "openshift/origin-sti-builder:v1.1.4" already present on machine
  3m		3m		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Created		Created container with docker id 25acb47b78a6
  3m		3m		1	{kubelet localhost.localdomain}	spec.containers{sti-build}	Normal		Started		Started container with docker id 25acb47b78a6
```

**Comment by smarterclayton** [comment]
Looking pretty good.  Can we use the short name printer for the images
(there should be a helper for that, if there isn't we should create it and
open an issue to use it most places)

**Comment by bparees** [comment]
@smarterclayton i think @php-coder tried to shorten the names and found they weren't pullable once he truncated the hash...  is there some other shortening mechanism you're referring to?

**Comment by php-coder** [comment]
>@smarterclayton i think @php-coder tried to shorten the names and found they weren't pullable once he truncated the hash..

Yes, it doesn't work:

```console
$ docker pull centos/ruby-22-centos7@sha256:990326b
Trying to pull repository docker.io/centos/ruby-22-centos7 ... failed
manifest unknown: manifest unknown
$ docker pull centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
Trying to pull repository docker.io/centos/ruby-22-centos7 ... sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c: Pulling from centos/ruby-22-centos7

Digest: sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
Status: Image is up to date for docker.io/centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c
```

**Comment by smarterclayton** [comment]
For image stream tags, the expectation is the default command is:

  oc describe istag/ruby-22-centos@sha256:990326b

not docker pull.

The docker pull may be a bug that is fixable.

**Comment by bparees** [comment]
ok but in this case it's a DockerImage, not an ImageStreamTag:

`From Image:         DockerImage centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c`

so we'd truncate when it's an imagestreamtag reference and not when it's a dockerimage reference?

**Comment by smarterclayton** [comment]
Yeah.

**Comment by php-coder** [comment]
>so we'd truncate when it's an imagestreamtag reference and not when it's a dockerimage reference?

In case of imagestreamtag there is nothing to truncate because we're not showing this hash:
```console
$ oc describe bc/s2i-test | grep ImageStreamTag
From Image:		ImageStreamTag java:8
Output to:		ImageStreamTag s2i-test:latest
$ oc get istag
NAME      DOCKER REF                                                                     UPDATED       IMAGENAME
java:8    java@sha256:cedc6a5dcba447e77a300351faeae6f926d2b22cd384d35d102fc4bfb117abd2   4 hours ago   sha256:cedc6a5dcba447e77a300351faeae6f926d2b22cd384d35d102fc4bfb117abd2
```

**Comment by smarterclayton** [comment]
The docker pull issue is fixable, but only if we can patch the registry to
redirect from the short digest to the long digest on a specific error
code.  It might be worth carrying, I'll open an issue.

**Comment by smarterclayton** [comment]
Spawned https://github.com/openshift/origin/issues/8354 for image pull by
short ID

**Comment by php-coder** [comment]
@smarterclayton What else I should improve as part of this PR? Add truncation for (unimplemented yet) docker's sums? Show truncated sum for ImageStreamTags?

**Comment by smarterclayton** [comment]
we can avoid truncation for now, are the examples up to date?

**Comment by php-coder** [comment]
@smarterclayton yes, they are up to date.

**Comment by bparees** [comment]
@jwforres @smarterclayton i'm good w/ this going into 3.2, does it have api/ux approval?

**Comment by smarterclayton** [comment]
Approved for 3.2

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
woo. nice work @php-coder

**Comment by php-coder** [comment]
PR https://github.com/kubernetes/kubernetes/pull/23988 for showing multiple labels/annotations on multiple lines was merged.

**Pull request merged**
