### PR TITLE
upstream azure fixes

### PR DESCRIPTION
**Pull request by rootfs**
fix https://bugzilla.redhat.com/show_bug.cgi?id=1506708 and https://bugzilla.redhat.com/show_bug.cgi?id=1513859

### CODE REVIEW

**Comment by rootfs** [comment]
@eparis @childsb @jsafrane @gnufied

**Comment by deads2k** [comment]
@rootfs Do you have a bugzilla to link to in the description?

**Comment by rootfs** [comment]
@deads2k not yet. This is an accumulated patch around multiple issues.

**Comment by rootfs** [comment]
@deads2k BZ created.

**Comment by rootfs** [comment]
@eparis can you merge? thanks

**Comment by rootfs** [comment]
/assign @deads2k 
can you approve? need it for a couple BZs.

**Comment by deads2k** [comment]
> /assign @deads2k
> can you approve? need it for a couple BZs.

I'll 
/approve

but because we're currently branching (jobs running as we speak), I need to 

/hold

until this afternoon and you'll have to open a pull to release-3.8 too once we have it.

**Pull request merged**
