### PR TITLE
Order builds according to creation timestamps

### LINKED ISSUE #3826: Builds are not sorted properly
```
[vagrant@openshiftdev ~]$ oc get builds --watch
NAME                  TYPE      STATUS      POD
ruby-hello-world-1    Source    Complete    ruby-hello-world-1-build
ruby-hello-world-10   Source    Cancelled   ruby-hello-world-10-build
ruby-hello-world-2    Source    Error       ruby-hello-world-2-build
ruby-hello-world-3    Source    Cancelled   ruby-hello-world-3-build
ruby-hello-world-4    Source    Cancelled   ruby-hello-world-4-build
ruby-hello-world-5    Source    Cancelled   ruby-hello-world-5-build
ruby-hello-world-6    Source    Error       ruby-hello-world-6-build
ruby-hello-world-7    Source    Cancelled   ruby-hello-world-7-build
ruby-hello-world-8    Source    Cancelled   ruby-hello-world-8-build
ruby-hello-world-9    Source    Complete    ruby-hello-world-9-build
```

Maybe we should use few zeroes, or just do a better numeric sort?

### PR DESCRIPTION
**Pull request by mnagy**
This PR builds on top of @rhcarvalho's #3890.

Fixes #3826.

### CODE REVIEW

**Comment by mnagy** [comment]
@kargakis well, if you think so :) I've double checked and am of the opinion that sorting them won't cause any trouble, they don't seem to be used after printing. I still don't like it out of principle, but the code is pretty ugly with the copying.

Updated with no extra copying.

**Comment by mnagy** [comment]
Seems like tests are flaky.

**Comment by rhcarvalho** [comment]
I think instead of sorting as a side effect of printing, we should have a printer that doesn't know about sorting -- it just prints whatever you pass to it, and just change the place where we pass a `BuildList` to have it sorted there.

**Comment by mfojtik** [comment]
LGTM, this is following upstream pattern (see printing events)

**Comment by mnagy** [comment]
@rhcarvalho the problem is that the code that passes `BuildList` is in kubernetes and it doesn't know about Builds.

**Comment by mfojtik** [comment]
[test]

**Comment by rhcarvalho** [comment]
Yep, I take back my comment above, I see [printing events](https://github.com/openshift/origin/blob/4bc1af7d29eb1321fcb7fe25911c7935a5f526b4/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource_printer.go#L876) is doing that. And there seems to be no problem with sorting the slice in place, as every invocation of the command gets a new fresh slice from calling the API.

**Comment by mnagy** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
