### PR TITLE
Add ut test for the function getContainerNameOrID

### PR DESCRIPTION
**Pull request by menghao11**
add ut test for the function getContainerNameOrID

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9414
[merge]

**Comment by menghao11** [comment]
@bparees what's wrong with this PR? Does my PR merge success?How should I do to make this ok?

**Comment by bparees** [comment]
It's not your pr, just issues with our CI system. 

[merge]

**Pull request merged**
