### PR TITLE
fix image_source.go extended test

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/9120

@csrwng @bparees PTAL

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
we got a networking test flake, unrelated to this change (only image_source.go uses the yaml file changed by this PR).

Can someone rehit the merge button please?  Thanks.

**Comment by csrwng** [comment]
[merge]

**Comment by smarterclayton** [comment]
If we're going to ensure this works we need to preserve at least one test that flags as a failure.

**Comment by gabemontero** [comment]
Looks like https://github.com/openshift/origin/pull/9132 introduced unit tests to deal with the CCT/ICT permutations discussed.  If I'm reading that right, then the images_source.go test can focus on the build aspects it was looking to validate.

**Comment by bparees** [comment]
@gabemontero +1, this isn't the right place to test DC triggering behavior, but @kargakis should make sure the CCT/ICT tests cover this case when we fix the behavior so we don't end up removing it again in the future.

**Comment by kargakis** [comment]
You don't need this. I am restoring the old behavior in https://github.com/openshift/origin/pull/9132

**Comment by gabemontero** [comment]
I started this pull before I saw how quickly you moved on restoring the old
behavior.  If we see any more flakes I'll just cancel this PR.

**Comment by gabemontero** [comment]
issue 9132 has merged ... closing this out, will monitor the build extended tests and verify that the image_source.go test is now passing again

**Pull request closed without merging**
