### PR TITLE
enable registry middleware acceptschema2

### PR DESCRIPTION
**Pull request by aweiteka**
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by ncdc** [comment]
Also need to change the default here https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L173

**Comment by ncdc** [comment]
cc @vbatts

**Comment by smarterclayton** [comment]
Also need to double check Ansible.

**Comment by mfojtik** [comment]
@miminar @legionus PTAL

**Comment by legionus** [comment]
Yep. Also need to change the default in the [middleware code](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L173) and in the [ansible](https://github.com/openshift/openshift-ansible/blob/f39408aada18ab6cf6f87d00f11ddeb3984816b9/roles/openshift_hosted/templates/registry_config.j2#L74)

**Comment by miminar** [comment]
[test][testextended][extended:core(builds)][extended:core(imageapis)]

**Comment by miminar** [comment]
testextended][extended:core(imageapis)]

**Comment by vbatts** [comment]
@miminar (carrying forward the conversation of https://github.com/openshift/origin/pull/8938#issuecomment-288074642)

Does "accepting" schema2 mean "forcing" schema2? It does not sound like it would.

**Comment by miminar** [comment]
> Does "accepting" schema2 mean "forcing" schema2? It does not sound like it would.

@vbatts That's correct. It's up to the client, what version of schema it will upload. Setting the `acceptschema2` to **`true`** only allows for the schema to be accepted - docker (1.10+ will not fall back to schema 1). Older clients or rh docker daemon running with a flag to enforce schema 1 will still push schema 1 regardless of this option.

Do we need `acceptschema1` as well? :smile:

**Comment by miminar** [comment]
Apparently, there cannot be two different extended focus statements. Trying one more time with a regexp:
[testextended][extended:core(builds|imageapis)]

**Comment by ncdc** [comment]
AFAIK we require docker 1.10, if not 1.12. cc @smarterclayton @sdodson @brenton @eparis to confirm.

**Comment by mtrmac** [comment]
I would very much like `acceptschema2` to be `true` by default. I don’t see anything about “skipping schema1” in this PR.

**Comment by brenton** [comment]
@ncdc Here's the docker support matrix for ocp:

3.0, 3.1 = docker 1.8
3.2, 3.3 = docker 1.10
3.4 = docker 1.12

**Comment by ncdc** [comment]
Thanks @brenton. Given that info, I don't see any need to support schema 1 in our registry any more. Anyone disagree?

**Comment by brenton** [comment]
I'm pretty sure images from registry.access.redhat.com use v2.s1.  Would that no longer supporting this schema cause breakage?

**Comment by ncdc** [comment]
I don't think we're talking about removing support for v2.s1. We're just talking about allowing v2.s2. Right?

**Comment by smarterclayton** [comment]
What's the status on his?

**Comment by aweiteka** [comment]
Based on the comments this is safe to merge.

**Comment by aweiteka** [comment]
@mfojtik I recommend pulling this into the next release. Sooner than later would be good to have some time with origin testing.

**Comment by ncdc** [comment]
It'll have to wait until next sprint starts (4/24)

**Comment by aweiteka** [comment]
@mfojtik ping

**Comment by mfojtik** [comment]
@legionus @miminar ?

**Comment by miminar** [comment]
> I don't think we're talking about removing support for v2.s1. We're just talking about allowing v2.s2. Right?

That's right. To be precise, this concerns just the manifests created via a push to the integrated registry. We already allow for consuming v2.s2 either by taging or image import.

@aweiteka can you please change `false` to `true` [here](https://github.com/openshift/origin/blob/f023bc98a22d10ce9b3181cdfb0e24a728a05531/pkg/dockerregistry/server/repositorymiddleware.go#L173) as well?

Hmm, looking at [this](https://github.com/openshift/origin/blob/f023bc98a22d10ce9b3181cdfb0e24a728a05531/test/end-to-end/core.sh#L622) I believe there's a bit more work todo in our tests. @aweiteka do you perhaps want me to take over?

[testextended][extended:core(builds|imageapis|images)]

**Comment by aweiteka** [comment]
> Hmm, looking at this I believe there's a bit more work todo in our tests. @aweiteka do you perhaps want me to take over?

@miminar that would be great, if you don't mind. :)

**Comment by smarterclayton** [comment]
This is required for 3.6

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@dmage do you think you can help get this over the hump since @miminar has a billion things going on?

**Comment by dmage** [comment]
I'll take a look as soon as I've finished with registry pruning.

re[testextended][extended:core(builds|imageapis|images)]

**Comment by legionus** [comment]
[testextended][extended:core(builds|imageapis|images)][severity:blocker]

**Comment by smarterclayton** [comment]
[merge][severity:blocker]

Unless there's a good reason still?

**Comment by smarterclayton** [comment]
Daemmonset flake, force merging

**Pull request merged**
