### PR TITLE
protect static pods from exec/attach

### PR DESCRIPTION
**Pull request by deads2k**
From https://github.com/kubernetes/kubernetes/pull/42280.

As we add static pods to run API servers, we'll want this protection.

Adds an admission plugin which can be used to protect static pods from exec or attach and closes the pods/exec security loophole.

For "normal" administrative pods, we have daemonsets. Static pods tend to have very sensitive information in them. That node itself can be protected by being unscheduleable or tainted, but the exec hole is still open. If you managed to exec to a static pod, you can end up getting very powerful secrets that were intended to be outside the API.

@openshift/api-review

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by smarterclayton** [comment]
Alternative.  Can we gate this on having cluster-admin?  It is useful
to exec in to static pods for debugging.

**Comment by deads2k** [comment]
> Alternative.  Can we gate this on having cluster-admin?  It is useful
> to exec in to static pods for debugging.

I can.

**Comment by deads2k** [comment]
Not needed anymore.

**Pull request closed without merging**
