### PR TITLE
runs the etcd vertical test on a platform that supports MachineAPI

### PR DESCRIPTION
**Pull request by p0lyn0mial**
the test fails on `metal` - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/245/pull-ci-openshift-cluster-baremetal-operator-master-e2e-metal-ipi-serial-ipv4/1524036156033863680

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
we are actually reverting https://github.com/openshift/origin/pull/27126

**Pull request closed without merging**
