### PR TITLE
bump(github.com/openshift/source-to-image): 07947a6f4fee815cbe97db93c026d8aa4c9804a9

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@stevekuznetsov 
```
13:59:29 + rsync --delete --exclude=_output/ '--exclude=_output/*' -a -e 'vagrant ssh --' . :/data/src/github.com/openshift/origin
14:15:18 Write failed: Broken pipe
14:15:18 rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
14:15:18 rsync: connection unexpectedly closed (10286 bytes received so far) [sender]
14:15:18 rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
14:15:18 Build step 'Execute shell' marked build as failure
```

[test]

**Comment by stevekuznetsov** [comment]
@smarterclayton https://github.com/openshift/origin/pull/13172#issuecomment-283459333

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Pull request merged**
