### PR TITLE
handle update conflicts in webconsole component install

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/openshift/origin/issues/20203

handle an update conflict

### CODE REVIEW

**Comment by deads2k** [comment]
/retest

@simo5 you hit this too.

**Comment by simo5** [comment]
I did, more than once.
/lgtm

**Comment by smarterclayton** [comment]
@deads2k a chicken has returned to the roost:

```
=== RUN   TestStuckMethodCount
--- FAIL: TestStuckMethodCount (0.01s)
	healthy_gprc_test.go:59: expected 0, got 1
```

**Comment by deads2k** [comment]
sni
/retest

**Comment by deads2k** [comment]
sni
/retest

**Comment by deads2k** [comment]
Cluster up passed.  This is fixing a flake and the unit failure is unrelated.  The current batch has failed. merging.

**Comment by praveenkumar** [comment]
@deads2k can we backport it to 3.10 branch because now for us CI fails same as what you fixed here, also once it backported can you folks also update the 3.10 origin images?  => https://ci.centos.org/job/minishift-pr/4762/consoleFull

**Comment by mireczatko** [comment]
still failing installing minishift-1.24.0-linux-amd64, is there some workaround?

**Pull request merged**
