### PR TITLE
Revert "Retry import to the docker hub on 401"

### PR DESCRIPTION
**Pull request by smarterclayton**
Reverts openshift/origin#8558

[merge]

### CODE REVIEW

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@liggitt wow

**Comment by smarterclayton** [comment]
[merge]

**Comment by soltysh** [comment]
Oh man, pullthrough is stopping us from removing that ;)
re-[merge]

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
