### PR TITLE
OVS parsing improvements

### PR DESCRIPTION
**Pull request by danwinship**
The more-complicated version of #17313. This takes advantage of the fact that "ovs-ofctl dump-flows" lets you pass a filter, so rather than getting back the whole list of flows and parsing each one, we can just ask for a much smaller set of flows to begin with.

In particular:
- in AlreadySetUp() we can `DumpFlows("table=%d", ruleVersionTable)` and get back only the single flow we're looking for
- in getPodDetailsBySandboxID(), we can `DumpFlows("table=20,arp")` and only get back the flows that *might* be the one we're looking for. (You can't match on the `actions` field, so there's no way to request only the flow that has the specific `note` that we're looking for. We *could* store the first 4 bytes of the sandbox ID in the cookie and then add that to the filter, I guess, but this code doesn't get run much anyway...)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Nice

**Comment by danwinship** [comment]
@dcbw PTAL
(and @smarterclayton can you /approve this for pkg/util?)

**Comment by smarterclayton** [comment]
/approve

but not reviewed

**Pull request merged**
