### PR TITLE
commonize bc input across strategies; better insure bc ouput is set

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/6357

@deads2k @kargakis PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can you paste what the new output looks like?

**Comment by gabemontero** [comment]
OK, here is a "standalone" build config example (I left the `pushes to` text the way it was, but the associated image_pipeline fix fixed scenarios where it was not showing up.  I tweaked the `build of..` piece to make them consistent and use the Namer/ResourceName for the istag):

```
		 In project example on server https://example.com:8443
		
		bc/ruby-22-centos7 docker build of https://github.com/openshift/ruby-hello-world with istag/ruby-22-centos7:latest
		  pushes to istag/ruby-hello-world:latest
		  not built yet
```

Here is a svc/dc/bc example (where the multi-line `<-` connection I again left as is, and only tweaked the `source build of .... with` line, again leveraging the Namer/ResourceName for the istag):

```
		 In project example on server https://example.com:8443
		
		svc/sinatra-example-1 - 172.30.17.47:8080
		  dc/sinatra-example-1 deploys istag/sinatra-example-1:latest <-
		    bc/sinatra-example-1 source build of git://github.com/mfojtik/sinatra-example-1 with docker.io/centos/ruby-22-centos7:latest 
		      build #1 running for about a minute (can't push to image)
		    deployment #1 waiting on image or update
```

**Comment by smarterclayton** [comment]
do we need " of "?  Does it add anything over:

"docker build git://... with ..."

Is " on " better than " with "?

**Comment by gabemontero** [comment]
On Sun, Jun 26, 2016 at 8:08 PM, Clayton Coleman <notifications@github.com>
wrote:

> do we need " of "? Does it add anything over:
>
> "docker build git://... with ..."
>

I think "of" will help newbies make the connection, where as, yes, it seems
unnecessary for the initiated.  Plus I think it adds some balance with the
use
of "on" for the next part.


> Is " on " better than " with "?
>

Yes, I'll s/with/on

**Comment by gabemontero** [comment]
@smarterclayton - did I convince you to keep the "of" in "docker build of" ?

**Comment by smarterclayton** [comment]
Space is tight but if you think it reads better I won't object.  We need to
make every character count until we add wrapping and flow control to the
status layout engine.

On Jun 27, 2016, at 6:53 PM, Gabe Montero <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> - did I convince you to
keep the "of" in "docker build of" ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9559#issuecomment-228927191>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p7hzd_ZN1snPwZJfjD9icIbyztV5ks5qQH6QgaJpZM4I-KqS>
.

**Comment by gabemontero** [comment]
ok, actually, you've convinced me with that last clarification.

`docker build of <src repo>` is now `docker builds <src repo>`

Also, the `pushes to` for standalone builds always seemed a bit inconsistent to me in comparison to the svc->dc->bc chain.  I've changed it to `->`.

**Comment by gabemontero** [comment]
Oh, I also removed some "no image set.." text that I had added.

@smarterclayton @kargakis @deads2k agreement on the wording changes?  alterations / suggestions on the code changes before posting the merge comment?

**Comment by kargakis** [comment]
To be honest, I prefer "pushes to" than the arrow but won't stand against it if all of the rest like it.

**Comment by smarterclayton** [comment]
We did that for a couple of reasons, mostly space,  but also because this
is a natural breakpoint in the flow

On Jun 28, 2016, at 12:58 PM, Michail Kargakis <notifications@github.com>
wrote:

To be honest, I prefer "pushes to" than the arrow but won't stand against
it if all of the rest like it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9559#issuecomment-229164263>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p8MfPB4jWM_KOja7eXuoZetHX5hvks5qQXzogaJpZM4I-KqS>
.

**Comment by deads2k** [comment]
lgtm

**Comment by gabemontero** [comment]
thanks @deads2k 

if I read @smarterclayton 's and @kargakis 's comments correctly, we have enough consensus for `->` replacing `pushes to` - can one of you three post the merge comment?

thanks

**Comment by deads2k** [comment]
> if I read @smarterclayton 's and @kargakis 's comments correctly, we have enough consensus for -> replacing pushes to - can one of you three post the merge comment?

Just giving them their final warning. :)

[merge]

**Comment by smarterclayton** [comment]
That was not agreement with pushes to.

**Comment by smarterclayton** [comment]
"That" = us "->"

**Comment by smarterclayton** [comment]
but the change in the PR works for me.

**Comment by gabemontero** [comment]
Apologies on the misread - thanks on the sign-off gentlemen

**Comment by gabemontero** [comment]
Test failed because of ci.openshift hiccup ...

**Comment by gabemontero** [comment]
origin_check had a failure with `TestClusterQuotaFuzzer` - no use of `oc status` there

origin_integration had a failure with the end-to-end runs waiting for the frontend svc to finish coming up (by attempting to curl to the svc endpoint)

**Comment by gabemontero** [comment]
@deads2k - could I get another merge comment, see if we can squeeze past those two flakes ?

**Comment by smarterclayton** [comment]
[merge]

**Comment by gabemontero** [comment]
Both the conformance and integration tests failed with an env hiccup during build:  `curl: (7) Failed connect to copr.fedorainfracloud.org:443; Connection timed out`

**Comment by bparees** [comment]
[merge]

**Comment by kargakis** [comment]
> but the change in the PR works for me.

Technically, it works for everybody :)

**Pull request merged**
