### PR TITLE
make assetconfig a top level type

### PR DESCRIPTION
**Pull request by deads2k**
@liggitt @smarterclayton API change need to split the webconsole out.  This never went into openshift/api, so I'd like to see it merged.

@spadgett fyi

### CODE REVIEW

**Comment by smarterclayton** [comment]
lgtm

**Comment by deads2k** [comment]
@liggitt minimal conflict potential.  Eliminates the only carry in https://github.com/openshift/origin-web-console-server .  After that we can rebase origin-web-console-server at our leisure.

**Comment by deads2k** [comment]
> @liggitt minimal conflict potential. Eliminates the only carry in https://github.com/openshift/origin-web-console-server . After that we can rebase origin-web-console-server at our leisure.

And come to think of it, until we do something with the assetconfig types, I don't think we'll care for quite a while.

**Pull request merged**
