### PR TITLE
oc: Add more doc and examples in oc get

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/5325

@deads2k PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6447 flake

[merge]

**Comment by kargakis** [comment]
istag flake

[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6065 flake

[merge]

**Pull request merged**
