### PR TITLE
WIP: convert cluster_up_down from md to adoc format

### PR DESCRIPTION
**Pull request by finp**
Motivation:
AeroGear Mobile Services [1]  requires OpenShift, and we need to include specific requirements from this document, which we could pull in if the doc is in asciidoc format. 
Tasks:
1. Convert to adoc with fidelity wrt original md file (in progress)
2. Update links to this doc (done)
3. Insert tags [2] to reference specific parts of doc
4. Remove md file (not done)

[1] https://docs.aerogear.org
[2] http://mrhaki.blogspot.com/2014/04/awesome-asciidoc-include-partial-parts.html

fixes https://github.com/openshift/origin/issues/20054

### CODE REVIEW

**Comment by bparees** [comment]
@finp can you remove the old .md file in this PR?

/assign @mfojtik  @deads2k

**Comment by finp** [comment]
@bparees  still WIP, need to reformat asciidoc to get it to render as nicely as the markdown. 
Leaving the md file in place to pick up any changes in master until the reformatting task is complete. At that point, I'll remove the md file and remove WIP from PR text and ping you again

**Comment by pmacko1** [comment]
@finp waiting for an update regarding docker versioning, parked

**Comment by bparees** [comment]
is this still moving forward?

**Comment by pmacko1** [comment]
@bparees yes, waiting for a merge regarding docker versioning, still present in our backlog

**Comment by finp** [comment]
@pmacko1  what exactly are you waiting on? https://github.com/openshift/origin/pull/20367 ?

**Comment by pmacko1** [comment]
https://github.com/openshift/origin/pull/20338 @finp

**Comment by finp** [comment]
looks like we don't have bandwidth for this, sorry, closing :(

**Pull request closed without merging**
