### PR TITLE
Adds completion for oc rsh command

### PR DESCRIPTION
**Pull request by akram**
Adds completion for oc rsh command

### CODE REVIEW

**Comment by akram** [comment]
solves #7676

**Comment by fabianofranz** [comment]
`rsh` doesn't take the container name as the second argument, so `__oc_require_pod_and_container` is not a good fit. I would suggest a completion only for the first argument (pod). It seems to be the first command to use that syntax, so it would be a new entry in the list of bash completions func. Something like:

```
# first arg is a pod name
        oc_rsh)
            if [[ ${#nouns[@]} -eq 0 ]]; then
                __oc_parse_get pods
            fi;
            return
            ;;
```

**Comment by akram** [comment]
@fabianofranz thanks.
I've rebased it and fixed issues with indent on my editor as well.
can you PTAL ?

**Comment by fabianofranz** [comment]
LGTM, [merge]

**Pull request merged**
