### PR TITLE
WIP: image: use context.Context consistently 

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton FYI

Should I create some default reasonable `context.Context` we can re-use or it would be use-case specific?

### CODE REVIEW

**Comment by mfojtik** [comment]
@fabianofranz i guess we should sweep the client code for unbound http requests that does not use the context.Context for timeouts/deadlines.

**Comment by mfojtik** [comment]
(this is WIP, want to spend more time sweeping the importer code)

**Comment by soltysh** [comment]
> (this is WIP, want to spend more time sweeping the importer code)

Why not finish just this part and merge. The sweeping being a separate PR?

**Comment by smarterclayton** [comment]
Better to leave as background or TODO.

**Pull request closed without merging**
