### PR TITLE
Update CONTRIBUTING.adoc

### PR DESCRIPTION
**Pull request by ecwpz91**

### CODE REVIEW

**Comment by ecwpz91** [comment]
Added note to Step 1 of "Application Build, Deploy, and Update Flow" of example sample applications.

**Comment by ecwpz91** [comment]
Updated documentation with notes from experience while performing deployment walk-through.

**Comment by ecwpz91** [comment]
No description provided.

**Comment by danmcp** [comment]
@ecwpz91 Looks like you have some rebase issues.

**Comment by ecwpz91** [comment]
@danmcp Ah, advise on how to fix? Unsure of how this happened... Also, I but am pretty new to git altogether.

**Comment by ecwpz91** [comment]
@danmcp OK, so I think I fixed, how can we confirm? Apologies for any inconvenience...

**Comment by danmcp** [comment]
@ecwpz91 Doesn't look fixed.  The easiest way to fix is probably to:

- Remember which commits have your changes.
- git reset --hard upstream/master  #upstream being the remote for openshift
- git cherry-pick <commi-id>  #for each of your commits
- git push origin <branch> --force

You will also want to collapse your commits into 1.  So before you push you should git rebase -i upstream/master

**Comment by ecwpz91** [comment]
OK, I'm getting "Everything up-to-date" response after executing the last bullet, 'git push origin --force'. 

So, hopefully this is now fixed, and please let me know otherwise...

Also, how could I be better about not having this happen again in the future? I'm trying to only save my changes locally without affecting my fork until I wanted to make a "significant" contribution.

Here are the steps that I've gone through in order to attempt this desired outcome:

1. Retrieve the stable release.
  * git checkout master
  * git pull
  * git checkout -b stable_proposed

2. Make some changes and save, accordingly.

3. Rebase (local only) to backup changes until I'm ready to push into fork for others to see.
  * git fetch upstream
  * git rebase upstream/master
  * git add --all
  * git stash

Also, I don't want to make any changes to the master for the time being. So, what should I do prevent any potential workflow interruption in the future?

**Comment by ecwpz91** [comment]
@danmcp Also, I noticed that above the merge says "openshift:master from *unknown repository*".

I think that this is because in the early stages of my 'git' maturity, I had deleted a version of this repository and then re-forked it. :grimacing:

Could the issue be that since there isn't an associated repo, github is having problems merging the changes?

Hope this helps somewhat, because locally I think I've done all I can. Unless, you have something else you'd like me to try?

**Comment by danmcp** [comment]
@ecwpz91 You have probably fixed the issue locally.  But you are correct that this PR is no longer connected.  I would next try closing this PR and opening a new one.

**Comment by ecwpz91** [comment]
@danmcp Done. Apologies for the delay, didn't realize I was the one who needed to close this PR at first!

**Pull request closed without merging**
