### PR TITLE
Bug 1703512: [release-3.11] backport #77069

### PR DESCRIPTION
**Pull request by ingvagabund**
Backporting https://github.com/kubernetes/kubernetes/pull/77069 to 3.11.

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1703512

### CODE REVIEW

**Comment by jim-minter** [comment]
@ingvagabund, thank-you.  This looks close to me.  A few comments:

1- AFAICS, rather than duplicate the `isBackendPoolOnSameLB` function from upstream, which this backport depends on, you have munged that logic into the caller in azure_vmss.go.  I am concerned about that approach because of the divergence from upstream.  This is not the cleanest code in the world and we are somewhat dependent on upstream help here; given what we've seen so far I think it is reasonably likely that we will need to request further backports here in future; it is much easier to reason about with upstream engineers when divergence is absolutely minimal.  For that reason I would definitely prefer it if `isBackendPoolOnSameLB` was brought in and no mungeing.

2- when I tried this I did a global search/replace for compute/mgmt/2017-12-01/compute -> compute/mgmt/2019-03-01/compute, which shows a few missing in your PR, might be worth checking these out in case they dropped on the way

Thanks!

**Comment by jim-minter** [comment]
@ingvagabund I think what I'm suggesting is to add a commit at the top of the patchset which brings in https://github.com/kubernetes/kubernetes/pull/76759 as well as a prerequisite - it looks pretty clean to do.

**Comment by ingvagabund** [comment]
If we want to keep the azure part as close to the upstream as possible, we might also pick:
- https://github.com/kubernetes/kubernetes/pull/74593
- https://github.com/kubernetes/kubernetes/pull/74490
- https://github.com/kubernetes/kubernetes/pull/75107
- https://github.com/kubernetes/kubernetes/pull/75314
- https://github.com/kubernetes/kubernetes/pull/75333
- https://github.com/kubernetes/kubernetes/pull/76487

@jim-minter WDYT? What would be the impact of backporting all azure changes since the last release-3.11 rebase?

**Comment by jim-minter** [comment]
@ingvagabund I think this is a great suggestion; I'm in favour.  I've reviewed all the links you put above and at first glance I believe that these would all be clearly helpful for both ARO and non-ARO users.
Would this get us to the point where our vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure would be identical to latest v1.11 upstream?

Applying https://github.com/kubernetes/kubernetes/pull/75333 is important for ARO and we didn't even know it was there :(
Applying https://github.com/kubernetes/kubernetes/pull/74490 should allow ARO to remove a legacy RBAC rule which we didn't want to carry anyway

The others provide stability and scalability fixes which are welcome across the board.

**Comment by jim-minter** [comment]
@mjudeikis worth you being looped in here

**Comment by ingvagabund** [comment]
Found more to apply to get a clean path without merge conflicts
- https://github.com/kubernetes/kubernetes/pull/72268
- https://github.com/kubernetes/kubernetes/pull/71942
- https://github.com/kubernetes/kubernetes/pull/71778
- https://github.com/kubernetes/kubernetes/pull/70518
- https://github.com/kubernetes/kubernetes/pull/70638
- https://github.com/kubernetes/kubernetes/pull/70400
- https://github.com/kubernetes/kubernetes/pull/68182
- https://github.com/kubernetes/kubernetes/pull/69202
- https://github.com/kubernetes/kubernetes/pull/69065
- https://github.com/kubernetes/kubernetes/pull/69020
- https://github.com/kubernetes/kubernetes/pull/68611

**Comment by jim-minter** [comment]
@ingvagabund what's the status of this PR?

**Comment by ingvagabund** [comment]
@jim-minter the PR is ready for review. I don't have means/knowledge to validate if the change will not break openshift, resp. if there is no other change missing. Can anyone on your team carry the validation steps?

**Comment by jim-minter** [comment]
We can build a release and run it through our tests, but product engineering needs to be responsible for the overall QE / sign-off for this PR.

**Comment by y-cote** [comment]
We built a release off this PR and had a run through our e2e testing and nothing wrong was reported.

**Comment by ingvagabund** [comment]
> We built a release off this PR and had a run through our e2e testing and nothing wrong was reported.

@y-cote happy to hear that. @jim-minter will the e2e testing be sufficient for merging this PR? Or, do you think there is more to validate before we give the PR the right labels?

**Comment by jim-minter** [comment]
@ingvagabund the QE and overall responsibility for merge lies with product engineering, not service delivery.  Yannick ran this through our e2e and it worked - there's not much more we can say.

**Comment by mgahagan73** [comment]
I think I discovered this bug while running a testcase that scaled the vm's up and down which I think is currently part of e2e testing for ARO. I don't think there is a specific test for this beyond exercising the scale up/down code paths with existing tests but I don't see any reason not to include this fix as I believe it reduced the number of test flakes we were seeing in the past.

**Comment by ingvagabund** [comment]
Sounds the PR is ready for merging then.

**Comment by ingvagabund** [comment]
@mfojtik @smarterclayton @jim-minter can out set the right labels?

**Comment by mfojtik** [comment]
I think this require a 3.11 BZ with backport request that will explain what bugs exactly are being fixed it. Since this is backporting 27 commits I would say the risk is medium here, so a proper justification is required.

I can see that all those were merged into kube release-1.11 which seems like it won't put us on high risk.

Technically this looks good to me, but I would like to have either @smarterclayton or @derekwaynecarr sign off on this as well.

**Comment by jim-minter** [comment]
Backporting https://github.com/kubernetes/kubernetes/pull/77069 enables use of a new Microsoft API for VMSS management which was not GA at the point where 1.11 was released.  Using this API removes an entire class of race conditions from OpenShift/VMSS and hence ARO cluster management.

By inspection, I am confident in the Microsoft team's decision-making wrt the additional 1.11 fixes that we would like to backport here.  They improve upstream robustness; applying them here will remove the delta between us and upstream (having a delta is not in our favour) and make it easier to collaborate with MSFT on any issues raised on this codebase in the future.

**Comment by smarterclayton** [comment]
In the event we find issues, which upstream branch will those land in, and which branches will they be in?

Will this also be back ported to 4.1?

**Comment by derekwaynecarr** [comment]
Agree with change.

@jim-minter can we get a listing of what is getting put in this release that may not exist in 4.2+ or is it safe to assume this is a full listing?

/approve
/lgtm

**Pull request merged**
