### PR TITLE
Remove OPENSHIFT_PROFILE as we now integrate debug directly

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
This prevented profiles from being captured on test-cmd which made me angry.

**Comment by deads2k** [comment]
@liggitt we discussed this earlier.  I wanted to go this route with all binaries (protect the endpoint with authn/authz), but you weren't sure. You ready?

**Comment by smarterclayton** [comment]
Note I just took out the usage of the env var in test scripts, this is preserved as a binary thing until we're ready to kill it.  I don't think any binary that includes serviceability doesn't already have authz though.

**Pull request merged**
