### PR TITLE
add ext test for openshift secret to jenkins credential sync

### PR DESCRIPTION
**Pull request by gabemontero**
extended test for https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration

@openshift/sig-developer-experience

### CODE REVIEW

**Comment by gabemontero** [comment]
[(5) Make openshift secrets available in jenkins as credentials [jenkins_integration]](https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration)

**Comment by bparees** [comment]
/lgtm
/hold
you can remove the hold if it passes tests.

**Comment by gabemontero** [comment]
test passed in extended builds and was not the failure in the two conformance tests

removed hold tag

/retest

**Pull request merged**
