### PR TITLE
Add systemd notify support

### PR DESCRIPTION
**Pull request by sdodson**
openshift now notifies systemd once startup is finished. This will delay startup
of any systemd dependencies until openshift has finished initializing. This is
particularly useful for ensuring that openshift-sdn-master does not attempt to
start before the embedded etcd has initialized.

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by smarterclayton** [comment]
Godep changes need to be in their own commits with the form `bump(<package>):<commit>`.

Also, does this correctly cross compile on windows?

**Comment by sdodson** [comment]
@smarterclayton I'll move the godeps stuff into a separate commit, is there a process for adding godeps documented somewhere? The godeps docs didn't seem to work for me but I may not have go setup 100% correctly.

Not sure about windows cross compiling, it shouldn't have any hard dependency on systemd as it just attempts to send a packet to os.Getenv("NOTIFY_SOCKET") with contents of 'READY=1' and moves on if there's an error. How do we generally test that? I don't have access to a windows host here but I can try at home.

**Comment by smarterclayton** [comment]
It should be documented in HACKING.md

The release build runs a cross compile build inside a docker container - if that's passes we're probably ok.  However, at one point importing the dbus library the systemd integration uses would fail windows compilation.

**Comment by sdodson** [comment]
@smarterclayton Should be fixed up now. It cross compiles just fine too.

**Comment by smarterclayton** [comment]
Can you trim the go-systems dependency so it is only that one directory?  I don't think anything beyond the daemon package is necessary.

**Comment by sdodson** [comment]
@smarterclayton ok, removed everything except for go-systemd/daemon and the LICENSE file

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
