### PR TITLE
Retry import from the DockerHub on 401

### LINKED ISSUE #7429: test-cmd new-app image stream import flake
`hack/../test/cmd/newapp.sh:104: executing 'oc get imagestreamtags wildfly:10.0' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out`

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11250/consoleText

### PR DESCRIPTION
**Pull request by smarterclayton**
Follow on to #8558

Fixes #7429 #8399 #8444

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by soltysh** [comment]
LGTM, merge as soon as tests are green.

**Comment by smarterclayton** [comment]
We're going to hold off on this for 1.2 just because of risk.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Flaked on https://github.com/openshift/origin/issues/8491 [test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Adding a workaround for the legacy client (it's less work than ripping out
the code).

**Comment by smarterclayton** [comment]
role assignment flake

**Comment by smarterclayton** [comment]
[test]

**Comment by soltysh** [comment]
Additional changes LGTM.

**Comment by smarterclayton** [comment]
Given that flakes are blocking final merges, I'm merging this (we've had a lot of soak time). [merge]

**Comment by smarterclayton** [comment]
Flake https://github.com/openshift/origin/issues/8606 [merge]

**Pull request merged**
