### PR TITLE
UPSTREAM: 9384: Increase clarity in empty_dir volume plugin

### PR DESCRIPTION
**Pull request by pmorie**
@smarterclayton @pweil- I was updating the upstream PR for empty_dir tonight and felt that these changes clarified things significantly.

### CODE REVIEW

**Comment by pmorie** [comment]
Related to: https://github.com/GoogleCloudPlatform/kubernetes/pull/9384

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@derekwaynecarr shot out of a cannon

**Comment by pmorie** [comment]
@deads2k what say you

**Comment by deads2k** [comment]
I'm fine with the change in general, but I'm against more UPSTREAM patches in this area unless they are functionally required.  This area of code was the most gnarly to try rebase.  I'd prefer to live with the old names and messages until the kube pull merges.

**Comment by pmorie** [comment]
@deads2k I estimate about 95% likelihood that all of these patches (except for possibly securitycontext for emptyDir) will drop out in the next rebase -- in fact, this PR is to bring origin into alignment w/ my upstream PR.

**Comment by pmorie** [comment]
@deads2k

> This area of code was the most gnarly to try rebase.

I have no doubt of that.  I had the patches stacked most inconveniently:

1.  EmptyDir + nonroot
2.  EmptyDir + securityContext
3.  Fix idempotency bug
4.  maybe one other little flake one in there

**Comment by pmorie** [comment]
Oops.

**Comment by pmorie** [comment]
@liggitt commit msg updated

**Comment by pmorie** [comment]
[test] again

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
