### PR TITLE
[OCPBUGS-7833] fix escapes

### PR DESCRIPTION
**Pull request by qJkee**
Fix regex escapes in test skips

### CODE REVIEW

**Comment by bparees** [comment]
This needs a make update.

Also it looks like @jsafrane has another version of this pr:  https://github.com/openshift/origin/pull/27744

So I think one of the two can be closed

**Comment by qJkee** [comment]
well, here i have one more line to add =)

**Comment by jsafrane** [comment]
@qJkee, I'm fixing the storage + snapshot rules here: https://github.com/openshift/origin/pull/27745. I don't like skipping exact test names, because there will always be some new tests that will break it.
BTW, please tag `@openshift/storage` before skipping our tests, this could have been a simple comment on your initial PR.

**Comment by bparees** [comment]
looks like https://github.com/openshift/origin/pull/27745 is going to go through (has all the labels) so to avoid a potential rebase conflict:

/hold

**Pull request closed without merging**
