### PR TITLE
bump(github.com/openshift/source-to-image): ebe28eafd63b691ccd917dcad1af1c0e5ba15abd

### PR DESCRIPTION
**Pull request by bparees**
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1427691

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
@csrwng last one.

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@smarterclayton are the poddisruption tests permanently broken in the 3.4 branch?  wondering if i'm going to need to manually merge this PR since it's against 3.4.
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/1159/

[test]

**Comment by bparees** [comment]
same pod disruption problems here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/1167/

**Comment by smarterclayton** [comment]
Can you open a PR to exclude those from 1.4?

On Mar 1, 2017, at 6:40 PM, Ben Parees <notifications@github.com> wrote:

same pod disruption problems here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/1167/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/13174#issuecomment-283508366>,
or mute
the thread

**Comment by bparees** [comment]
> Can you open a PR to exclude those from 1.4?

@smarterclayton yeah, i've just added a commit to this PR.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Pull request merged**
