### PR TITLE
Add additional timeout when waiting for namespace removal

### LINKED ISSUE #17780: integration failure:  TestProjectRequestError
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_integration/11977/#githubcomopenshiftorigintestintegrationrunner-testintegration

/assign mfojtik deads2k 
Assuming it's caused by the rebase
/sig master

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #17780.

I've added additional wait period which solves the problem in this case. Without it I was reliably able to reproduce the problem once in a 4-5 runs, with it I run it close to 30 times without a failure. I think it's a reasonable approach until/if @ironcladlou will fix the terminating namesake problem. I've added there a TODO to remove the `wait.Poll` afterwards.

@mfojtik @deads2k ptal

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM but probably need check from @ironcladlou if we haven't regressed something in GC

**Comment by mfojtik** [comment]
@soltysh tests are broken because of https://github.com/openshift/origin/issues/17985

**Comment by soltysh** [comment]
> @soltysh tests are broken because of #17985

 /o\ omg it's a complete disaster today 😭

**Comment by ironcladlou** [comment]
See https://github.com/openshift/origin/issues/17780#issuecomment-355392277 for more details pointing towards a root cause. I don't think the problem is related to the GC. What if we change [this timeout](https://github.com/openshift/origin/blob/master/test/integration/project_request_test.go#L104) to 30 seconds?

**Comment by ironcladlou** [comment]
Created https://github.com/openshift/origin/pull/17991 to replace this PR.

**Comment by ironcladlou** [comment]
The fix in this PR is itself flaky, as it's possible for

**Pull request closed without merging**
