### PR TITLE
Fix extended networking tests

### PR DESCRIPTION
**Pull request by marun**
The networking extended job broke a couple of weeks ago due to the rebase and since then a couple of additional regressions have slipped in.  This PR fixes the added breakage and temporarily disables the tests broken by the rebase so the job can still serve its purpose of detecting breakage introduced outside of the networking team.

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by marun** [comment]
@eparis @rajatchopra @pravisankar Assuming the tests pass, please merge asap to fix the ci job.

**Comment by eparis** [comment]
What is the issue/pr to re-enable/fix the broken services test?

**Comment by marun** [comment]
@eparis Good call: #7261

**Comment by dcbw** [comment]
LGTM

**Comment by eparis** [comment]
[merge]

**Pull request merged**
