### PR TITLE
fix up template instance controller permissions

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/17260

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal, i'm taking a guess at what the intended permissions was here.... not sure why the lack of this permission wasn't causing issues though.

**Comment by jim-minter** [comment]
Thanks for the PR.  I think that given that the previous line was nonsense, and that things have been working fine forever, it's best to remove the line rather than fix it up to something else.
The reasons why "it works" must be twofold - 1) we're using a cache, which bypasses RBAC, and 2) the TIC has admin role on all projects anyway.

**Comment by bparees** [comment]
@jim-minter ok, i'll rework this to just strip the line.

**Comment by bparees** [comment]
@jim-minter updated.

**Pull request merged**
