### PR TITLE
Workaround for broken quota admission test

### PR DESCRIPTION
**Pull request by dmage**
/cc @bparees @deads2k

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k you mentioned there were some changes to quota in the rebase.  Can you please help @dmage understand what they were and what the right way to fix this is so we don't have to wait 10 mins in our tests?

in the meantime, this workaround is ok with me.
/lgtm

**Comment by dmage** [comment]
flake #17697
/retest

**Comment by deads2k** [comment]
@dmage @bparees does your problem sound like this: https://github.com/openshift/origin/issues/17803 ?  Your fix looks like it is.

**Comment by dmage** [comment]
@deads2k I'm not 100% sure how it works, but probably yes. Notifications from the watcher for quota come with a long delay.

**Pull request merged**
