### PR TITLE
resolve s2i python test flake

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter heh, i was trying this over here:
https://github.com/openshift/origin/pull/17354

it didn't seem to fix it.

or at least it didn't fix it for dancer.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17354/test_pull_request_origin_extended_image_ecosystem/179/#image_ecosystemperlslow-hot-deploy-for-openshift-perl-image-dancer-example-should-work-with-hot-deploy-suiteopenshift

**Comment by bparees** [comment]
/lgtm
/hold
remove the hold when it passes image_eco.

**Comment by jim-minter** [comment]
snort. I'm confident that in the python case at least, multiple worker processes will definitely be able to cause this flake.

**Pull request merged**
