### PR TITLE
Disable TestImageStreamImportDockerHub integration test to unblock the queue

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
The p0 issue is here: https://github.com/openshift/origin/issues/16323

**Comment by mfojtik** [comment]
flake:  https://github.com/openshift/origin/issues/16330

/retest

**Comment by bparees** [comment]
only test left is GCE and it can't break that.  manually merging.

**Comment by deads2k** [comment]
@stevekuznetsov I think we need to pick this into the stage branch to be able to merge any pulls into the stage branch, correct?

**Comment by stevekuznetsov** [comment]
Seems correct yes. Let me handle that

**Pull request merged**
