### PR TITLE
add upload template button to new views

### PR DESCRIPTION
**Pull request by gruiz17**

### CODE REVIEW

**Comment by danmcp** [comment]
@gruiz17 Needs rebase

@jwforres Review please

**Comment by jwforres** [comment]
@gruiz17 sorry for the delay reviewing this

This looks like it is creating the template resource in the project, and then letting you pick it from the list.  The user experience I would expect is that you upload your template and immediately go into the page with the form and Create button.  This flow shouldn't result in the template resource being added to the project.

cc @bparees in case you have a different opinion

**Comment by bparees** [comment]
@jwforres I agree that taking you directly into the "create" page makes sense, but i'm less clear on your suggestion that it shouldn't result in the resource being added to the project.  I guess I can see the argument for either behavior.  Maybe there should be a checkbox for "register this template with my project" vs "one-off instantiate from this template"?

**Comment by smarterclayton** [comment]
I think it's useful to optionally register it.  One benefit of creating it of course is that you can recreate at any time from that origin template.

**Comment by danmcp** [comment]
Closing due to age and inactivity.

**Pull request closed without merging**
