### PR TITLE
Revert "SDN-5202:Porting testing for netConfig and UDN and CIDR overlapping tests from upstream"

### PR DESCRIPTION
**Pull request by tssurya**
Reverts openshift/origin#29041

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by martinkennelly** [comment]
May not be needed if https://github.com/openshift/origin/pull/29179 is the fix.

**Comment by neisw** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview https://github.com/openshift/ovn-kubernetes/pull/2318

**Comment by neisw** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview openshift/ovn-kubernetes#2318

**Comment by neisw** [comment]
/close 
Neither individual revert fixed the issue but https://github.com/openshift/origin/pull/29179 did

**Pull request closed without merging**
