### PR TITLE
e2e requestheaders idp: fix ingress CA cert location

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
/test e2e-aws-fips
looks like ci-operator is broken, too

**Comment by stlaz** [comment]
https://github.com/openshift/cluster-ingress-operator/pull/377 broke the serial tests, something else apparently broke the ci-operator

**Comment by stlaz** [comment]
/test e2e-aws-fips 
template fix merged

**Comment by smarterclayton** [comment]
Merging to reduce failures.  Test passed and does not impact other tests.

**Pull request merged**
