### PR TITLE
Fixes handling lists in convert

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1393230

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11747 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/10988 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11887 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/10988 re[merge]

**Comment by liggitt** [comment]
and on https://github.com/openshift/origin/issues/11900

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11900 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11900 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11900 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11900 re[merge]

**Comment by liggitt** [comment]
Actually, the failing namespace is related to the one added in this PR. Probably not a flake, but a weird interaction between the two test namespaces

**Comment by liggitt** [comment]
Can you get a clean test-cmd.sh run locally?

**Comment by fabianofranz** [comment]
I couldn't really see a relation in a first glance, let me dig a little deeper. I get a clean `hack/test-cmd.sh migrate`, trying the full suite now.

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/10988 re[merge]

**Pull request merged**
