### PR TITLE
Revert "Finish basicresources.sh migration"

### PR DESCRIPTION
**Pull request by deads2k**
This reverts commit 80a16e97e559cc26f5990edb1b998f3345a9c6af.

This is blocking all nightly payload promotion because it is failing metal-ovn-ipv6.  It's late eastern time, but this wasn't the worst break yesterday so I didn't understand what happened until now.

https://amd64.ocp.releases.ci.openshift.org/releasestream/4.10.0-0.nightly/release/4.10.0-0.nightly-2021-11-11-072405

To get payloads working again we are going to revert in keeping with [Improving CI Signal](https://docs.google.com/document/d/16E0dLFLbLBTe0J4fUd_55I-8bJc9t22BwsdWqFuutaQ/edit)  .

The attempted fix did not resolve the issue https://github.com/openshift/origin/pull/26593

### CODE REVIEW

**Comment by deads2k** [comment]
the original PR is https://github.com/openshift/origin/pull/26578

**Comment by deejross** [comment]
/lgtm

Once #26593 gets merged I should be able to re-apply the other tests in a new PR.

**Comment by deads2k** [comment]
this was a clean revert that appears to do no damage.  the metal tests are failing pre-install, so this didn't impact it.  I'm manually merging to  help unstick us.

**Pull request merged**
