### PR TITLE
Allow template and image streams in the catalog to embed icons as data-uris

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@csrwng review but dont merge yet, want to verify that a large (width/height) image won't screw up the page

**Comment by jwforres** [comment]
Fixed it to restrict the visible width of the images both in the table layout and modal dialog.

**Comment by jwforres** [comment]
actually think i need to limit max-height as well...

**Comment by jwforres** [comment]
Ok, only setting max-height for the catalog tiled layout. in the modal the image can be as tall it wants since the page can scroll cleanly with a modal open.

**Comment by csrwng** [comment]
LGTM, looks like travis flakiness

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
