### PR TITLE
Export git origin release

### PR DESCRIPTION
**Pull request by ingvagabund**
So we can set the openshift_release ansible inventory variable during deployment

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Can you just use the git minor and major yourself and not need to thread through like this?

**Comment by ingvagabund** [comment]
If I do
```sh
( source hack/lib/init.sh; os::build::rpm::get_nvra_vars; echo "${OS_GIT_MAJOR}.${OS_GIT_MINOR}" ) > ORIGIN_RELEASE
```

in the current origin master HEAD I will get `3.7+`. So I would have to do something like
```sh
( source hack/lib/init.sh; os::build::rpm::get_nvra_vars; echo "${OS_GIT_MAJOR}.${OS_GIT_MINOR}" | sed "s/+//" ) > ORIGIN_RELEASE
```

As long as that is ok, I am fine with that.

**Comment by stevekuznetsov** [comment]
Yeah I hate that we add the `+` too. Your second suggestion looks fine to me.

**Comment by ingvagabund** [comment]
Cool, closing this then.

**Pull request closed without merging**
