### PR TITLE
added go vet struct tags testing

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt  This adds `go tool vet -structtags`

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
note: update swagger spec

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
