### PR TITLE
UPSTREAM: 62913: make a simple dynamic client that is easy to use

### PR DESCRIPTION
**Pull request by deads2k**
no conflicts?  Unpossible.

@bparees

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

@liggitt says he's bumping.

**Comment by liggitt** [comment]
bump is in https://github.com/openshift/origin/pull/19512

**Comment by bparees** [comment]
so should this be closed?

**Comment by liggitt** [comment]
no, not a rebase, just bumping the vendored origin/kubernetes, and wanted to hold UPSTREAM commits to avoid confusing the bot (and me)

**Pull request merged**
