### PR TITLE
Deprecate build-logs in favor of logs

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis do we have deprecation warning in build-logs? 

LGTM

**Comment by kargakis** [comment]
I am not sure if we want to add a derpecation warning now. It's up to @bparees and @smarterclayton

**Comment by bparees** [comment]
the sooner the better imho...  @smarterclayton ?

**Comment by smarterclayton** [comment]
Add it

On Nov 2, 2015, at 7:52 AM, Ben Parees <notifications@github.com> wrote:

the sooner the better imho... @smarterclayton
<https://github.com/smarterclayton> ?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5568#issuecomment-153008848>.

**Comment by kargakis** [comment]
```
[vagrant@openshiftdev sample-app]$ oc build-logs ruby-sample-build-1
Command "build-logs" is deprecated, use "logs" instead.
I1102 14:31:25.943479       1 sti.go:448] ---> Installing application source ...
I1102 14:31:25.946130       1 sti.go:448] ---> Building your Ruby application from source ...
```

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
```
# github.com/openshift/origin/pkg/cmd/cli/cmd
_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/logs_test.go:19: not enough arguments in call to NewCmdLogs
FAIL	github.com/openshift/origin/pkg/cmd/cli/cmd [build failed]
```

test fixed re[merge]

**Comment by liggitt** [comment]
regenerate completions:
```
-_openshift_cli_build-logs()
-{
-    last_command="openshift_cli_build-logs"
-    commands=()
-
-    flags=()
-    two_word_flags=()
-    flags_with_completion=()
-    flags_completion=()
-
-    flags+=("--follow")
-    flags+=("-f")
-    flags+=("--nowait")
-    flags+=("-w")
-
-    must_have_one_flag=()
-    must_have_one_noun=()
-}
-
 _openshift_cli_deploy()
 {
     last_command="openshift_cli_deploy"
@@ -3830,7 +3811,6 @@ _openshift_cli()
     commands+=("status")
     commands+=("project")
     commands+=("start-build")
-    commands+=("build-logs")
     commands+=("deploy")
     commands+=("rollback")
     commands+=("new-build")
FAILURE: Generated completions out of date. Please run hack/update-generated-completions.sh
make[1]: Leaving directory `/data/src/github.com/openshift/origin'
```

**Comment by liggitt** [comment]
make sure all completions and verify-* scripts run

**Comment by kargakis** [comment]
[test]

**Comment by liggitt** [comment]
[merge]

**Comment by kargakis** [comment]
Hit https://github.com/openshift/origin/issues/5526

re[merge]

**Comment by kargakis** [comment]
tribute to @jhadvig

**Comment by jhadvig** [comment]
aww :broken_heart:

**Pull request merged**
