### PR TITLE
jenkins client plugin PR testing

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal @openshift/devex @jupierce  fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[testextended][extended:core(jenkins-client-plugin)]

**Comment by bparees** [comment]
lgtm but i'd run all the jenkins image ecosystem tests and all the pipeline tests.

**Comment by gabemontero** [comment]
On Mon, Feb 20, 2017 at 3:16 PM Ben Parees <notifications@github.com> wrote:

> lgtm but i'd run all the jenkins image ecosystem tests and all the
> pipeline tests.
>
yep that is my plan - just starting with the precise spec the pr job will
use

**Comment by gabemontero** [comment]
ok pr spec looks good ... now jenkins image eco system:

[testextended][extended:core(openshift pipeline plugin)]

**Comment by gabemontero** [comment]
jenkins image eco system passed ... now going to pipeline builds:

[testextended][extended:core(openshift pipeline build)]

**Comment by gabemontero** [comment]
openshift pipeline build passed as well ... i think this is vetted @bparees

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
During the merge conformance tests failed.

Build without output image - source strategy build has this failure in the build log:

```
2017-02-21T10:05:25.495846000Z I0221 10:05:25.474505       1 tar.go:286] Adding to tar: /tmp/s2i-build132347290/upload/src/views/main.erb as src/views/main.erb
2017-02-21T10:05:25.562888000Z I0221 10:05:25.557756       1 sti.go:656] ---> Installing application source ...
2017-02-21T10:05:25.563204000Z I0221 10:05:25.561835       1 sti.go:656] ---> Building your Ruby application from source ...
2017-02-21T10:05:25.563548000Z I0221 10:05:25.561850       1 sti.go:656] ---> Running 'bundle install --deployment --without development:test' ...
2017-02-21T10:05:25.564163000Z I0221 10:05:25.562693       1 sti.go:660] /opt/rh/rh-ruby22/root/usr/bin/ruby: error while loading shared libraries: libruby.so.2.2: cannot open shared object file: No such file or directory
```

@bparees indicated in scrum that this is a new regression that he is investigating that is essentially blocking the merge queue for everyone.  Will circle back to this after he has been able to make some progress.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
