### PR TITLE
Grant use of the NFS plugin in hostmount-anyuid SCC, to enable NFS re…

### PR DESCRIPTION
**Pull request by pmorie**
…cycler pods to run

Fixes bug 1324418

@pweil- @childsb @swagiaal

### CODE REVIEW

**Comment by pweil-** [comment]
:+1:

**Comment by pweil-** [comment]
Oh, can you update the description line to say it allows NFS so it shows in the describe (line 23)

**Comment by pmorie** [comment]
Ah yes, my bad

**Comment by pmorie** [comment]
[test]

**Comment by pweil-** [comment]
approved to fix blocker with PV recycler

LGTM [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
