### PR TITLE
1.3 picks

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

cc @smarterclayton @derekwaynecarr

**Comment by derekwaynecarr** [comment]
cadvisor picks lgtm.

**Comment by ncdc** [comment]
```
curl: (7) Failed connect to copr.fedorainfracloud.org:443; Connection timed out
error: running '/bin/sh -c cd "/var/lib/origin" && curl -L -o /etc/yum.repos.d/origin-next-epel-7.repo https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo &&     INSTALL_PKGS="libmnl libnetfilter_conntrack openvswitch       libnfnetlink iptables iproute bridge-utils procps-ng ethtool socat openssl       binutils xz kmod-libs kmod sysvinit-tools device-mapper-libs dbus       ceph-common iscsi-initiator-utils" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /usr/lib/systemd/system/origin-node.service.d /usr/lib/systemd/system/docker.service.d &&     chmod +x /usr/local/bin/* /usr/bin/openshift-*' failed with exit code 7
[ERROR] PID 16605: hack/build-images.sh:64: `'/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc' ex dockerbuild images/node openshift/node:latest` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/build-images.sh:64: `'/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc' ex dockerbuild images/node openshift/node:latest`
[INFO] 		  2: hack/build-images.sh:98: build
[INFO] 		  3: hack/build-images.sh:123: image
[INFO]   Exiting with code 1.
make: *** [release] Error 1
Build step 'Execute shell' marked build as failure
```

Might be #9203 

[test]

**Comment by ncdc** [comment]
@smarterclayton @liggitt PTAL

**Comment by liggitt** [comment]
DeepEqual commit LGTM

**Comment by liggitt** [comment]
were these cadvisor picks upstream, or a godep bump? can we bump to the same level?

**Comment by ncdc** [comment]
Assuming they're all in the latest cadvisor tag that's in 1.3.x, I can switch to a godep bump. I'll check.

**Comment by ncdc** [comment]
@liggitt the 3 cadvisor PRs in this PR are not in any upstream cadvisor tag yet. It might be worth bumping up to the latest 0.23 release (Seth has a PR to bump 1.3 here https://github.com/kubernetes/kubernetes/pull/30307) and then cherry picking the additional ones from master that we care about. Or we could cherry pick these into the 0.23 branch and get them into Kube 1.3, and then cherry pick here.

**Comment by ncdc** [comment]
Correction, 1380 is in v0.23.7+. I've submitted https://github.com/google/cadvisor/pull/1421 to pick 1358 and 1395 to the release-v0.23 branch

**Comment by ncdc** [comment]
@liggitt @derekwaynecarr updated to bump cadvisor to the tip of the release-v0.23 branch. I then re-picked 1359 as it's not in that branch. If this looks good to you, please tag.

**Comment by ncdc** [comment]
This had 1 green jenkins run and then it got bit by the workspace checkout conflict issue. [test] again but this can be merged...

**Comment by liggitt** [comment]
@derekwaynecarr has merge

**Comment by ncdc** [comment]
I need to restore the cadvisor test.go file that the `godep update` removed. Coming up in a few.

**Comment by ncdc** [comment]
Updated, now without the deleted test file.

**Comment by derekwaynecarr** [comment]
[merge]

**Pull request merged**
