### PR TITLE
UPSTREAM: 10841: Default --ignore-not-found to true for delete --all

### LINKED ISSUE #3602: delete-all has a new flake
"Error from server: pods "db-1-deploy" not found"  See this log: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3520/consoleText

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3602
Upstream PR at https://github.com/GoogleCloudPlatform/kubernetes/pull/10841

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by deads2k** [comment]
I guess an upstream lgtm is good enough to take this as a patch.  If the upstream patch ends up rejected, you need to pull this back out.

[merge]

**Comment by liggitt** [comment]
@ncdc hub flake, I think:
```
--- FAIL: TestImage (0.91s)
	client_test.go:105: unexpected error: error getting X-Docker-Token from openshift/origin-not-found: Get http://index.docker.io/v1/repositories/openshift/origin-not-found/images/: EOF
```
Re[merge]

**Comment by liggitt** [comment]
@csrwng is this indicative of a hub error?
```
error: no image or template matched "mysql"
!!! Error in hack/test-cmd.sh:501
  '[ "$(oc new-app mysql --name=db | grep db)" ]' exited with status 1
Call stack:
  1: hack/test-cmd.sh:501 main(...)
Exiting with status 1
```
Re[merge]

**Comment by liggitt** [comment]
```
--- FAIL: TestRunAll (2.03s)
	newapp_test.go:686: emptyDir volumes: Error mismatch! Expected <nil>, got no image or template matched "mysql": the image "ee2cb077006e3385648619d6adf66d5ac53cfb11c4b2708636c5be0a12b23ff7" in repository "library/mysql" was not found and may have been deleted
```
Re[merge]

Will spawn an issue to separate tests with external dependencies to a separate suite

**Comment by liggitt** [comment]
grrrrr
```
/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
```
[merge]

**Comment by csrwng** [comment]
@liggitt yup, it looks like we have a good number of external dependencies, including git repos, github images, etc.

**Pull request merged**
