### PR TITLE
remove unused describe user function

### PR DESCRIPTION
**Pull request by PI-Victor**
i think this is a left over from this PR:
https://github.com/openshift/origin/pull/8293/files#diff-677cd147da9da054b24bb9a600046af9L267

can we remove this now, since i can not find a use for it anywhere?

@php-coder  @bparees PTAL

### CODE REVIEW

**Comment by php-coder** [comment]
Indeed it looks unused. I don't mind to remove it.

**Comment by bparees** [comment]
lgtm [merge]

**Comment by PI-Victor** [comment]
@php-coder @bparees thaks for the quick response.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
