### PR TITLE
don't attempt to call create on files that don't exist

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test][extended:core(builds)

**Comment by bparees** [comment]
@csrwng ptal.  this has been broken ever since https://github.com/openshift/origin/pull/4286 because it was trying to run oc create on a file that's not being created anymore.

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]
@smarterclayton this is the last extended test issue that i know of for the devex team.

**Pull request merged**
