### PR TITLE
By default, push images as multiple tags beyond :latest

### PR DESCRIPTION
**Pull request by smarterclayton**
Push :vX.Y and :vX.Y.Z instead of just :latest

### CODE REVIEW

**Comment by smarterclayton** [comment]
@brenton @pweil- @stevekuznetsov @jupierce this changes our fundamental tagging strategy for origin:

Master always goes to latest, v3.9, and v3.9.0, even after we tag for v3.9.0.  So during dev for 3.10 we will always have a 3.10 latest tag, which ansible and cluster up can use.  Specific tags like alpha would be created for back compat.

**Comment by smarterclayton** [comment]
Once it works for origin, going to clone to all the other repos

**Comment by smarterclayton** [comment]
Updated to tag as latest only when the current branch is master.

**Comment by brenton** [comment]
cc/ @sdodson

**Pull request merged**
