### PR TITLE
Setup aliases for imageStream*

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM, although I probably wouldn't alias imageRepository since it's going away. Also, any interest in aliasing imageStreamTags and imageStreamImages?

**Comment by kargakis** [comment]
> LGTM, although I probably wouldn't alias imageRepository since it's going away.

I know it's going away but until then I'll have to type it a couple of times more:) 
> Also, any interest in aliasing imageStreamTags and imageStreamImages?

Hmm, how about `istag` and `isimage`? Looks confusing though I cannot think of something better atm.

**Comment by ncdc** [comment]
You shouldn't ever need to type imageRepository any more.

I was thinking `ist` and `isi` but I guess your suggestions are a bit more readable.

**Comment by kargakis** [comment]
> You shouldn't ever need to type imageRepository any more.

You are right. I got so used to it that I just noticed I could use `imageStream`. Which also is wild though:)
I'm removing the `ir` alias and adding those I mentioned.

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
@kargakis as a follow up, we should document this somewhere in openshift-docs properly, I mean **all** aliases we have.

**Comment by kargakis** [comment]
> @kargakis as a follow up, we should document this somewhere in openshift-docs properly, I mean all aliases we have.

:+1:

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
