### PR TITLE
Bug 1785023: Restore ResourceQuota e2e test for life of a secret

### PR DESCRIPTION
**Pull request by adambkaplan**
This reverts commit adc358016eb4ed8d539c448f829869fa63135964, reversing
changes made to 4db88247520a1467b09b41ea8ce0301a45a54b36 in openshift/origin#24754

### CODE REVIEW

**Comment by adambkaplan** [comment]
Needs openshift-controller-manager#84 to land first

**Comment by bparees** [comment]
@adambkaplan the changes in this PR don't look right?

**Comment by bparees** [comment]
nm

/lgtm

**Comment by adambkaplan** [comment]
@danehans my understanding is that these tests are still run in 4.4 and 4.3

**Comment by danehans** [comment]
@adambkaplan ok, I think I understand the situation now. To confirm, this PR enables the tests b/c https://github.com/openshift/openshift-controller-manager/pull/84 merged. PR 84 has been backported to 4.4 and 4.3, so we should now no longer see the CI flakes, correct?

**Comment by adambkaplan** [comment]
> To confirm, this PR enables the tests b/c openshift/openshift-controller-manager#84 merged. PR 84 has been backported to 4.4 and 4.3, so we should now no longer see the CI flakes, correct?

@danehans that is correct.

**Pull request merged**
