### PR TITLE
[release-3.7] UPSTREAM: 55631: Parse and return the last line in the log even if it is partial

### PR DESCRIPTION
**Pull request by runcom**
Same as https://github.com/openshift/origin/pull/17198 but for `release-3.7`.

@derekwaynecarr @mrunalp PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis we should allow merge to 3.7 branches ;-)

@stevekuznetsov i think this will have to go via green button.

/test

**Comment by stevekuznetsov** [comment]
Branch weirdness will be fixed once we move away from `mungegithub` and to `tide`.

/lgtm
/approve

**Comment by derekwaynecarr** [comment]
I want to hold on this until the upstream PR is actually merged.

**Comment by stevekuznetsov** [comment]
Misunderstood comment from @mfojtik

**Comment by runcom** [comment]
@derekwaynecarr @stevekuznetsov we need this for 3.7 as well, could any of you merge this? (Upstream has merged)

**Comment by runcom** [comment]
just found out the repo to backport, closing.

**Comment by runcom** [comment]
As requested elsewhere by @smarterclayton - this is back porting https://github.com/openshift/origin/pull/17198 to `release-1.7`

**Comment by runcom** [comment]
Being back ported https://github.com/openshift/origin/pull/17546

**Pull request closed without merging**
