### PR TITLE
Include build hook in describer

### PR DESCRIPTION
**Pull request by rhcarvalho**
All forms of using the hook are transformed into a single equivalent
representation, listing commands/args as a string array, so that
individual arguments can be distiguished unambiguously, as opposed to
representing the hook as a string.

Example output:

```console
$ oc describe build rails-postgresql-example-1
Name:                   rails-postgresql-example-1
Created:                21 hours ago
Labels:                 app=rails-postgresql-example,buildconfig=rails-postgresql-example,openshift.io/build-config.name=rails-postgresql-example,template=rails-postgresql-example
Annotations:            openshift.io/build.number=1
                        openshift.io/build.pod-name=rails-postgresql-example-1-build
Build Config:           rails-postgresql-example
Started:                2016-02-24 16:31:40 +0000 UTC
Finished:               2016-02-24 16:31:46 +0000 UTC
Duration:               6s
Build Pod:              rails-postgresql-example-1-build
Strategy:               Source
URL:                    https://github.com/rhcarvalho/rails-ex.git
Ref:                    build-hook
Commit:                 7f3c2c0c5c0878e3ba12e3e8b8f4d8936ab775e0
Author:                 Rodolfo Carvalho
Committer:              Rodolfo Carvalho
Message:                Add build post commit hook to run tests
From Image:             DockerImage centos/ruby-22-centos7@sha256:98cef73f621fa92e1bd8f701d7c7d0e4830d234e8d1f44e6e180dfd02029c7ba
Output to:              ImageStreamTag rails-postgresql-example:latest
Post Commit Hook:       ["/bin/sh", "-ic", "bundle exec rake test"]
Push Secret:            builder-dockercfg-ewdww
Git Commit:             7f3c2c0c5c0878e3ba12e3e8b8f4d8936ab775e0
Revision Author:        Rodolfo Carvalho <rhcarvalho@gmail.com>
Revision Committer:     Rodolfo Carvalho <rhcarvalho@gmail.com>
Revision Message:       Add build post commit hook to run tests
Status:                 Failed
No events.
```

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees PTAL

**Comment by rhcarvalho** [comment]
[test]

**Comment by smarterclayton** [comment]
Can you guys add a card for 1.3 to clean up the builder describe output so it looks as good as the pod layout?  We could use some nesting here, this is getting hard to scan.

**Comment by rhcarvalho** [comment]
@smarterclayton thanks! Trello'ed https://trello.com/c/l8CyWprA

**Comment by rhcarvalho** [comment]
@smarterclayton are you fine with the output for the build post commit hook?
I tried to make it a single string, but quoting got too hard to get right in all cases.

**Comment by bparees** [comment]
lgtm [merge]

**Pull request merged**
