### PR TITLE
Automated cherry pick of #13563

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #13563 on release-1.4.

#13563: Update namespace finalizer to delete RoleBindingRestrictions

### CODE REVIEW

**Comment by enj** [comment]
@deads2k backport for 1.4, please merge.

**Comment by deads2k** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@enj did the `ose/enterprise-3.4` tests pass for this? we expect the suite to fail for `origin/release-1.4`

**Comment by enj** [comment]
@stevekuznetsov we cannot test this on OSE 3.4: https://github.com/openshift/ose/pull/519#issuecomment-291135147

I would like to revert this feature in Origin 1.4 (and also close this PR) if it does not get into OSE 3.4.

**Comment by enj** [comment]
Closing per https://github.com/openshift/ose/pull/519#issuecomment-299496505

Origin 1.4 is out of sync with OSE 3.4 but I think we can live with that.

**Pull request closed without merging**
