### PR TITLE
Allow insecure path Allow routes to override Redirect routes without …

### LINKED ISSUE #14950: path based routing with mixed tls
We are having issues with mixing path based routing. The issue spawns from https://github.com/tnozicka/openshift-acme

Is the correct behaviour to only accept one type of termination?

ie. 

https://www.example.com/ <-- termination=reencrypt --> web1
https://www.example.com/path <-- termination=edge --> web2

The path based route is "accepted" but only routes to web1 unless the path is also set to termination=reencrypt

This also happens with non tls

https://www.example.com/ <-- termination=edge --> web1
http://www.example.com/path <-- no tls --> web2

Again the /path is accepted but only routes to web1

### PR DESCRIPTION
**Pull request by jam13**
…breaking the reverse

Fixes #14950

### CODE REVIEW

**Comment by smarterclayton** [comment]
Seems reasonable, @openshift/sig-networking

**Comment by imcsk8** [comment]
LGTM

**Comment by tnozicka** [comment]
@openshift/sig-networking tests are green - can someone please review it?

**Comment by jam13** [comment]
Is there something wrong with this commit, or is the testing just broken?

**Comment by jperville** [comment]
Hello @jam13 , just the tests are flaking. I am using your haproxy config template with great success (to use the openshift-acme controller with edge/redirect routes) and I just want this PR to be merged.

**Comment by jam13** [comment]
I've run retest on it at least 5 times before and it's always failed on the
last stage. Are the tests really that unreliable?

**Comment by tnozicka** [comment]
@jam13 it succeeded last time but after that new test was added to the test suite, that's why I hit retest today (to trigger the new one because it's required). Unfortunately the new `ci/openshift-jenkins/extended_conformance_crio` test has been constantly failing for the last 2 days. It's failed on all of my PRs so no need to blame yours.

@stevekuznetsov can you disable the broken test?

**Comment by tnozicka** [comment]
@openshift/sig-networking could you please review it? It has been waiting for review more than a month...

**Comment by stevekuznetsov** [comment]
Test has been turned on for less than 24 hours! But yes we were monitoring stability and it seems to be lower than acceptable.

**Comment by tnozicka** [comment]
@openshift/sig-networking @knobunc @rajatchopra @smarterclayton @pecameron tests are green - can someone please review it? This PR has been sent on Aug 18 :/

**Comment by kargakis** [comment]
Hrm, seems like this breaks because of special characters
```
{"event-GUID":"31e874a0-ff6f-11e7-9468-3945ffe2fe64","event-type":"pull_request","level":"info","msg":"cannot checkout release-3.8\r: error checking out release-3.8\r: exit status 1. output: error: pathspec 'release-3.8?' did not match any file(s) known to git.\n","org":"openshift","plugin":"cherrypick","pr":15847,"repo":"origin","time":"2018-01-22T12:24:50Z"}
```
Nice catch.

**Pull request merged**
