### PR TITLE
update the URL of git server

### PR DESCRIPTION
**Pull request by guangxuli**
The URL of git server should be updated, now it looks like this "git-myproject.router.default.svc.cluster.local"

### CODE REVIEW

**Comment by guangxuli** [comment]
@soltysh ptal, thanks!

**Comment by bparees** [comment]
@csrwng please give this a quick review

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
re[merge]

**Comment by guangxuli** [comment]
@stevekuznetsov How to handle this CI failure, it looks like not caused by this commit.

**Comment by stevekuznetsov** [comment]
You are still in the merge queue, we merge serially so once everyone ahead of you in the queue merges this will go in. The failure in test doesn't impact the merge.

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/9548

re-[merge]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/9402

re-[merge]

**Pull request merged**
