### PR TITLE
UPSTREAM: 29134: Improve quota controller performance

### PR DESCRIPTION
**Pull request by derekwaynecarr**
/cc @deads2k @ncdc

### CODE REVIEW

**Comment by deads2k** [comment]
@derekwaynecarr any conflicts in the pick I should worry about?

**Comment by deads2k** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
yes, the code upstream is in a different location (resource_quota_controller) versus (resources.go) after some of our refactors.

**Comment by derekwaynecarr** [comment]
re[merge]

**Pull request merged**
