### PR TITLE
Update example commands for oadm router

### PR DESCRIPTION
**Pull request by pweil-**
Fixes https://github.com/openshift/origin/issues/4237

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by pweil-** [comment]
merge failed with rsync command flakes.  Please remerge

**Comment by liggitt** [comment]
```
Generating fresh docs...
Diffing current docs against freshly generated docs
diff -Naupr /data/src/github.com/openshift/origin/docs/generated/oadm_by_example_content.adoc /data/src/github.com/openshift/origin/_output/verify-generated-docs/docs/generated/oadm_by_example_content.adoc
--- /data/src/github.com/openshift/origin/docs/generated/oadm_by_example_content.adoc	2015-09-10 17:04:43.694316000 +0000
+++ /data/src/github.com/openshift/origin/_output/verify-generated-docs/docs/generated/oadm_by_example_content.adoc	2015-09-10 17:43:24.384874103 +0000
@@ -253,13 +253,13 @@ Install a router
   $ openshift admin router --dry-run
 
   // See what the router would look like if created
-  $ openshift admin router -o json
+  $ openshift admin router -o json --credentials=/path/to/openshift-router.kubeconfig --service-account=myserviceaccount
 
   // Create a router if it does not exist
-  $ openshift admin router router-west --create --replicas=2
+  $ openshift admin router router-west --credentials=/path/to/openshift-router.kubeconfig --service-account=myserviceaccount --replicas=2
 
   // Use a different router image and see the router configuration
-  $ openshift admin router region-west -o yaml --images=myrepo/somerouter:mytag
+  $ openshift admin router region-west -o yaml --credentials=/path/to/openshift-router.kubeconfig --service-account=myserviceaccount --images=myrepo/somerouter:mytag
 ----
 ====
 
FAILURE: Generated docs out of date. Please run hack/update-generated-docs.sh
```

**Comment by pweil-** [comment]
docs generated

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
