### PR TITLE
e2e-oauth-authn: support sha256 prefixed tokens

### PR DESCRIPTION
**Pull request by sttts**
Add e2e for https://github.com/openshift/kubernetes/pull/208.

### CODE REVIEW

**Comment by sttts** [comment]
Infra.

/retest

**Comment by stlaz** [comment]
LGTM, needs rebase

**Comment by sttts** [comment]
openshift/kubernetes#208 merged.

/retest

**Comment by sttts** [comment]
Route stops working during upgrade.

/retest

**Comment by sttts** [comment]
/override ci/prow/e2e-cmd

cmd tests are broken and this PR only adds e2e tests (which succeeded).

**Comment by stlaz** [comment]
/hold
for whatever reason, the test appears to fail on FIPS

**Comment by sttts** [comment]
/retest

https://github.com/openshift/kubernetes/pull/302 merged.

**Comment by sttts** [comment]
/override ci/prow/e2e-gcp-builds

Changed e2e test has nothing to do with ci/prow/e2e-gcp-builds.

**Pull request merged**
