### PR TITLE
Simplify the status for template labels

### PR DESCRIPTION
**Pull request by smarterclayton**
@fabianofranz

### CODE REVIEW

**Comment by smarterclayton** [comment]
@csrwng moved it up and out, and stopped showing component labels for now.  Need to come back to this now that we can describe upstream resources.

**Comment by smarterclayton** [comment]
@csrwng please review and merge

**Comment by csrwng** [comment]
LGTM, however I don't think I can [merge]

**Comment by smarterclayton** [comment]
[merge]

You probably deserve the ability.  Remind me to add you

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
