### PR TITLE
Fix for log time bug

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1276212

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres for review

**Comment by jwforres** [comment]
@spadgett is this going to conflict with your changes

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
@jwforres does this need me to rebase? or just a good kick

**Comment by jwforres** [comment]
@spadgett was this the one you were going to just include with you changes?

**Comment by spadgett** [comment]
I've changed this file now, so it's probably easier to include in my pull request

**Comment by jwforres** [comment]
closing this PR then

**Comment by spadgett** [comment]
Fix included in #5537.

**Pull request closed without merging**
