### PR TITLE
[DO NOT MERGE] - Switch to headless Chrome for UI e2e

### LINKED ISSUE #2286: Flake in phantomjs e2e UI test
```
Running "protractor:phantomjs" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.154.243.30:41468/wd/hub
Spec started


/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Error communicating with the remote browser. It may have died.
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'ip-10-154-243-30', ip: '10.154.243.30', os.name: 'Linux', os.arch: 'amd64', os.version: '3.18.3-201.fc21.x86_64', java.version: '1.8.0_45'
Driver info: driver.version: PhantomJSDriver
    at new bot.Error (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:20
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at [object Object].fulfill (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1520:10
==== async task ====
WebDriver.takeScreenshot()
    at [object Object].webdriver.WebDriver.schedule (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.takeScreenshot (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:979:15)
    at [object Object].to.(anonymous function) [as takeScreenshot] (/data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/protractor.js:62:25)
    at ScreenshotReporter.reportSpecResults (/data/src/github.com/openshift/origin/assets/node_modules/protractor-screenshot-reporter/index.js:123:10)
    at [object Object].jasmine.NestedResults.totalCount [as reportSpecResults] (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at [object Object].jasmine.Spec.finishCallback (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2470:21)
    at [object Object].jasmine.Spec.finish (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2475:8)
    at [object Object].onComplete (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at [object Object].jasmine.Queue.next_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
[launcher] Process exited with error code 1
>> 
Fatal error: protractor exited with code: 1
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #2286

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
Did this get ugly?

**Comment by liggitt** [comment]
I got it working in a devenv. Got bogged down in getting prereqs installed on the base ami, but can pick it up again

**Comment by liggitt** [comment]
@jwforres FYI, I had started working on this to get rid of protractor. the install bits of this would need to move to the base ami

**Comment by liggitt** [comment]
the initial lists should still be populating the page

**Comment by jwforres** [comment]
Closing, PR replaced by https://github.com/openshift/origin/pull/4288

**Pull request closed without merging**
