### PR TITLE
STOR-2136: Remove CSI snapshot webhook tests

### PR DESCRIPTION
**Pull request by Phaow**
- We don't need these CSI snapshot webhook tests any more, because we are no longer deploying snapshot webhook stuff in OCP.

Ref -> https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/219

### CODE REVIEW

**Comment by Phaow** [comment]
/assign @gnufied @jsafrane 
Could you help take a look when you get a chance? Thank you!

**Comment by eggfoobar** [comment]
@Phaow Can you please run `make update` to update the generated annotation test list.

**Comment by Phaow** [comment]
> @Phaow Can you please run `make update` to update the generated annotation test list.

@eggfoobar Good catch, sorry I forgot it before I file the PR! Fixed.

**Comment by eggfoobar** [comment]
> > @Phaow Can you please run `make update` to update the generated annotation test list.
> 
> @eggfoobar Good catch, sorry I forgot it before I file the PR! Fixed.

No worries, thanks so much for fixing this 😄

**Comment by gnufied** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn

**Comment by gnufied** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-serial

**Pull request merged**
