### PR TITLE
refactored test/cmd/secrets to use helper methods

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.  I want the tty and edit to merge first.

**Comment by stevekuznetsov** [comment]
@deads2k rebased and ready

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by stevekuznetsov** [comment]
Flake waiting for the health endpoint:
```
ERROR: gave up waiting for https://127.0.0.1:28443/healthz

!!! Error in hack/test-cmd.sh:362
	'return 1' exited with status 1
Call stack:
	1: hack/test-cmd.sh:362 main(...)
Exiting with status 1
```

**Comment by stevekuznetsov** [comment]
Flake in `build-images`:
```
Get https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo: dial tcp 209.132.184.54:443: no route to host
!!! Error in hack/build-images.sh:62
	'docker build -t $1:latest $2' exited with status 1
Call stack:
	1: hack/build-images.sh:62 image(...)
	2: hack/build-images.sh:81 main(...)
Exiting with status 1
```

I feel like I've seen more flakes this week due to us hitting external endpoints than ever before.

**Comment by stevekuznetsov** [comment]
@deads2k needs a new tag

**Comment by deads2k** [comment]
> @deads2k needs a new tag

Find a flake issue that this matches or open one.

**Comment by deads2k** [comment]
re[merge]

**Comment by stevekuznetsov** [comment]
@deads2k have more faith!
https://github.com/openshift/origin/issues/6040

**Pull request merged**
