### PR TITLE
Add example env vars

### PR DESCRIPTION
**Pull request by rhcarvalho**
Add examples of how to set environment variables for S2I and Docker strategy builds.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@mfojtik @bparees PTAL

**Comment by bparees** [comment]
lgtm.  should merge after https://github.com/openshift/origin/pull/4562

**Comment by rhcarvalho** [comment]
It won't break anything if merged before... the env is already part of
dockerStrategy, just not used.

**Comment by bparees** [comment]
I know but I don't want to confuse people who see it and assume that means
it can be used.

Ben Parees | OpenShift

**Comment by bparees** [comment]
[merge]

**Pull request merged**
