### PR TITLE
Force hello-openshift nonzero exit via env var

### PR DESCRIPTION
**Pull request by ncdc**
For testing readiness checks, canary deployments, etc.

Also add /echo handler to display headers and query params.

### CODE REVIEW

**Comment by ncdc** [comment]
@csrwng @ironcladlou @smarterclayton

**Comment by csrwng** [comment]
LGTM ... something else that would be helpful would be some stdout output ... I used it in my own hello pod to test streaming logs.

**Comment by ncdc** [comment]
Ok. I don't think this is a must-merge for 3.0, btw.

**Comment by ncdc** [comment]
stdout output added

**Comment by smarterclayton** [comment]
We should roll this into https://github.com/openshift/origin/pull/1903

**Comment by ejemba** [comment]
added to #1903 . Check the readme or the comments.

**Pull request closed without merging**
