### PR TITLE
add Dockerfile for openshift-apiserver image

### PR DESCRIPTION
**Pull request by sanchezl**
Add `Dockerfile.rhel` for CI and release builds.
Add `Dockerfile` for local builds.

### CODE REVIEW

**Comment by deads2k** [comment]
how can this pass without the binaries present?

**Comment by sanchezl** [comment]
> how can this pass without the binaries present?

The images are built by a prow job. The image requires https://github.com/openshift/origin/pull/23278, but it wont be built until the CI job is updated in a separate PR to actually create the image.

**Pull request merged**
