### PR TITLE
oc: Cosmetic fixes in oc status

### PR DESCRIPTION
**Pull request by kargakis**
* Adds a newline between the environment and the suggestions in case
of no errors or warnings
* Doesn't suggest 'oc status -v' anymore if none of the displayed errors
have any suggestions
* Makes less verbose the 'oc describe/oc get all' suggestion

Fixes https://github.com/openshift/origin/issues/6279

@smarterclayton @deads2k @fabianofranz

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by kargakis** [comment]
Needed some unit test updates. It's fine now.
```
$ make check WHAT=pkg/cmd/cli/describe/
TEST_KUBE=1 hack/test-go.sh pkg/cmd/cli/describe/  
ok  	github.com/openshift/origin/pkg/cmd/cli/describe	0.076s
hack/test-go.sh took 4 seconds
```

**Comment by kargakis** [comment]
```
The command '/bin/sh -c yum install -y libmnl libnetfilter_conntrack openvswitch     libnfnetlink iptables iproute bridge-utils procps-ng ethtool socat openssl     binutils xz kmod-libs kmod sysvinit-tools device-mapper-libs dbus     && yum clean all' returned a non-zero code: 1
!!! Error in hack/build-images.sh:62
	'docker build -t $1:latest $2' exited with status 1
Call stack:
	1: hack/build-images.sh:62 image(...)
	2: hack/build-images.sh:81 main(...)
Exiting with status 1
make: *** [release] Error 1
```

[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6065 flake

[merge]

**Pull request merged**
