### PR TITLE
Fix edit

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/7085 and adds necessary but insufficient code for https://github.com/openshift/origin/issues/7090 .
Fixes https://github.com/openshift/origin/issues/7147

@kargakis This picks one of your pulls too.  They help, but don't eliminate our problems.  I'll have to have a go at lists separately to keep us from regressing.

### CODE REVIEW

**Comment by kargakis** [comment]
Tested it and it works fine. LGTM but Clayton asked for tests using sed

**Comment by deads2k** [comment]
> Tested it and it works fine. LGTM but Clayton asked for tests using sed

@liggitt @smarterclayton `sed` on mac OS is non-compatible isn't it?  That whole `-i ` and `-i`, right?  I don't think I can call the wrapper function from a subshell doing an exec.  How about the precious snowflakes that are mac users sort out how to write the test? :)

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
opened https://github.com/openshift/origin/issues/7151 for @liggitt  to figure out.  `sed -i` is incompatible.

**Comment by csrwng** [comment]
```sed -i``` seems to work fine on my Mac

**Comment by deads2k** [comment]
> sed -i seems to work fine on my Mac

With or without a space?  I've been reverted a lot, I have no way to actually test it, and I'm not sure of exactly how the command array is build or parsed on mac os.

**Comment by csrwng** [comment]
So this works (and I guess yes, you need to have some argument to -i)
```
sed -e "s/foo/bar" -i "" somefile
```

**Comment by kargakis** [comment]
let's move the discussion in https://github.com/openshift/origin/issues/7151

**Comment by smarterclayton** [comment]
We have os::util::sed for a reason

**Comment by liggitt** [comment]
can't do `export EDITOR="os::util::sed"`, can you?

**Comment by smarterclayton** [comment]
Can't, but it has the right pattern.

**Comment by smarterclayton** [comment]
Actually... you can export that function I think to the subshell.

**Comment by smarterclayton** [comment]
Or just generate the right prefix into the editor variable with a
variant function

**Pull request merged**
