### PR TITLE
bump(fsouza/go-dockerclient): 42d06e2b125654477366c320dcea99107a86e9c2

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
updating to the current go-dockerclient.  @smarterclayton or @deads2k ptal.

[test]

**Comment by deads2k** [comment]
Make the corresponding pull upstream as well so that we stay in sync.

**Comment by bparees** [comment]
@deads2k done: https://github.com/kubernetes/kubernetes/pull/12770

**Comment by deads2k** [comment]
> @deads2k done: kubernetes/kubernetes#12770

I don't mind taking it in both if you need it now.  The manual reconciliation during a rebase is just painful.  Do you want both?

**Comment by bparees** [comment]
[test]

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
