### PR TITLE
switch rbac sync to container objects to make watch work

### PR DESCRIPTION
**Pull request by deads2k**
There may be additional optimizations possible, but this resolves the coarse grained, "omg, why are you listing over and over and over again" problem.

@smarterclayton @ncdc 
[test]

### CODE REVIEW

**Comment by enj** [comment]
LGTM (well, as good as something like this can be...)

Merge once tests pass.

**Comment by deads2k** [comment]
[merge]

**Comment by enj** [comment]
@deads2k the failure may be related (or we need to open a new flake issue):

```
=== RUN   TestPolicyBasedRestrictionOfBuildCreateAndCloneByStrategy
masterAddr: "127.0.0.1:12000"
Created project integration
--- FAIL: TestPolicyBasedRestrictionOfBuildCreateAndCloneByStrategy (36.95s)
	build_admission_test.go:230: timed out waiting for the condition
	etcd.go:126: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-runtime.call32.json"
FAIL
```

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
@eparis this has green tests.  It speeds up test-cmd by 30+ minutes each run

**Comment by ncdc** [comment]
I'm ok manually merging this since we don't have a way to jump this to the top of the merge queue. Does that work for you @smarterclayton @eparis ?

**Comment by deads2k** [comment]
Merging to speed up the test time for every pull.

**Pull request merged**
