### PR TITLE
Rename 'Management Console' to 'Web Console'

### LINKED ISSUE #2444: "Management Console" terminology
From a conversation recently with @joefern1 and @mpbarrett, there was a desire to sync up language in marketing materials and documentation to "web console" instead of "Management Console". After some brief poking around, the only spot I could find of an actual reference to "Management Console" in the product was the title bar in browser.

If the decision is indeed to switch that terminology, I presume the title bar (and any other instances in the product itself) should probably change as well.

cc: @liggitt

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #2444

### CODE REVIEW

**Comment by liggitt** [comment]
@spadgett review

**Comment by spadgett** [comment]
Nit: Two references to "management console" in `assets/README.md`.

There are a bunch of references in `openshift-docs`. Track under a separate issue?

**Comment by adellape** [comment]
@spadgett Yeah, I'll be following up to update the docs.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
