### PR TITLE
Registry's Azure Driver

### PR DESCRIPTION
**Pull request by spinolacastro**

### CODE REVIEW

**Comment by pweil-** [comment]
Depends on https://github.com/openshift/origin/pull/5404

**Comment by miminar** [comment]
@spinolacastro: #5404 is merged now. You may safely rebase on top of master.

**Comment by spinolacastro** [comment]
@miminar,@pweil- Done!

**Comment by miminar** [comment]
LGTM

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
[test]
@pweil- I believe this is good to go. Do we need to document it somewhere?

**Comment by pweil-** [comment]
@miminar - the relevant place would be https://docs.openshift.org/latest/install_config/install/docker_registry.html#storage-for-the-registry but I don't see driver information there now.  Couldn't hurt to add in the supported drivers.  I would've guessed we had at least an s3 example somewhere but didn't see it right away.

**Comment by pweil-** [comment]
LGTM - @smarterclayton, should we wait until 3.1.1 is cut (I'm assuming yes)?

**Comment by smarterclayton** [comment]
Yes, will merge right after and will be in 1.1.2

**Comment by pweil-** [comment]
re[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
