### PR TITLE
update template to allow 32 vs. 64 bit JVM selection for Jenkins

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/devex ptal / fyi

### CODE REVIEW

**Comment by bparees** [comment]
need to generate bootstrap

**Comment by coreydaley** [comment]
lgtm

**Comment by gabemontero** [comment]
bindata.go update pushed

**Comment by bparees** [comment]
lgtm but should hold until the jenkins image changes are merged.

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
thx @bparees

**Comment by gabemontero** [comment]
The merge is still cooking, but the origin check failed trying to verify swagger when it could not start a server:

```
11:20:46 ===== Verifying API Swagger Spec =====
11:20:46 Generating a fresh spec...
11:23:31 FAILURE: Generation of fresh spec failed:
11:23:31 Generated new key pair as /openshifttmp/openshift/generate-swagger-spec/openshift.local.config/master/serviceaccounts.public.key and /openshifttmp/openshift/generate-swagger-spec/openshift.local.config/master/serviceaccounts.private.key
11:23:31 Generating node credentials ...
11:23:31 Created node config for 172.17.0.2 in /openshifttmp/openshift/generate-swagger-spec//openshift.local.config/node-172.17.0.2
11:23:31 Wrote master config to: /openshifttmp/openshift/generate-swagger-spec/openshift.local.config/master/master-config.yaml
11:23:31 Running hack/lib/start.sh:295: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s...
11:23:31 FAILURE after 159.427s: hack/lib/start.sh:295: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s: the command timed out
11:23:31 Standard output from the command:
11:23:31 Standard error from the command:
11:23:31 The connection to the server 127.0.0.1:38443 was refused - did you specify the right host or port?
11:23:31 ... repeated 385 times
11:23:31 
[ERROR] PID 25384: hack/lib/cmd.sh:618: `return "${return_code}"` exited with status 1.
```

I'm not seeing this in the list of 51 flakes currently on origin.  If need be then, if the merge fails, I'll open one up.

Can't tell why that start failed from the data available.

**Comment by gabemontero** [comment]
Opened flake https://github.com/openshift/origin/issues/13224 for the previously reference item.  Only issue during the merge run.

@bparees - could you please post the merge comment again ?

**Comment by bparees** [comment]
[merge]

**Pull request merged**
