### PR TITLE
Prevent POODLE vulnerability in HAProxy router

### PR DESCRIPTION
**Pull request by elyscape**
This deals with a few TODO items in some of the images.

### CODE REVIEW

**Comment by elyscape** [comment]
Rebased onto master.

**Comment by danmcp** [comment]
@knobunc Needs review.

**Comment by elyscape** [comment]
After rebasing, only POODLE needed to be handled.

**Comment by elyscape** [comment]
Rebased onto master again. It probably wasn't necessary but I did it anyway!

**Comment by pweil-** [comment]
@knobunc bump

**Comment by knobunc** [comment]
@pweil- @smarterclayton -- Do we care about any web browsers that can't speak SSLv3?

**Comment by pweil-** [comment]
> Do we care about any web browsers that can't speak SSLv3

I believe the major browsers disabled it at the end of 2014.  IMO if we aren't going to break a bunch of folks it seems safest to disable it in haproxy too, folks still have the option to turn it back on.

**Comment by smarterclayton** [comment]
I agree - we should be regularly updating to have a secure router ootb.
However, any change to the support ciphers / suites should be a release
note.  Also, we should update the "secure settings comment" alongside it.

**Comment by knobunc** [comment]
@openshift/networking FYI

[merge]

**Comment by knobunc** [comment]
@smarterclayton how do we get this into the release notes?

**Comment by smarterclayton** [comment]
https://github.com/openshift/openshift-docs/issues/4021

**Pull request merged**
