### PR TITLE
WRKLDS-1449: Update etcd test data for 1.31 release

### PR DESCRIPTION
**Pull request by atiratree**
to fix https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-kubernetes-1647-nightly-4.18-e2e-vsphere-ovn-techpreview-serial/1833870039334260736

### CODE REVIEW

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
> /lgtm

/hold
for payload job result

**Pull request merged**
