### PR TITLE
Add EXPOSE to our public Dockerfile

### PR DESCRIPTION
**Pull request by smarterclayton**
@liggitt review

### CODE REVIEW

**Comment by liggitt** [comment]
do you care about 10250 for the node?

**Comment by smarterclayton** [comment]
Hrm... no, since it wouldn't be behind a service.

On Wed, Jul 1, 2015 at 2:37 PM, Jordan Liggitt <notifications@github.com>
wrote:

> do you care about 10250 for the node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3536#issuecomment-117791103>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
ok, LGTM

**Comment by smarterclayton** [comment]
[merge]

On Wed, Jul 1, 2015 at 2:43 PM, Jordan Liggitt <notifications@github.com>
wrote:

> ok, LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3536#issuecomment-117792536>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request merged**
