### PR TITLE
Add v2 registry

### PR DESCRIPTION
**Pull request by ncdc**
Add v2 registry. Note, it can't be used until Docker 1.6 is out, so this is just preliminary at this point.

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@smarterclayton Jenkins is happy

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by ncdc** [comment]
The merge failed with this:

```
Selenium standalone server started at http://10.154.238.167:44477/wd/hub
Spec started

/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Error communicating with the remote browser. It may have died.
```

I assume that's unrelated to this PR.

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
