### PR TITLE
Fix parameter mismatch in template creation

### PR DESCRIPTION
**Pull request by csrwng**
Also hides images section if no images detected in template.

### CODE REVIEW

**Comment by csrwng** [comment]
@jwforres ptal
@mfojtik - FYI, this fixes the issue you saw today

**Comment by spadgett** [comment]
@csrwng I made a similar change in #1957. If we merge your change, I can roll back that part of the fix.

**Comment by csrwng** [comment]
@spadgett yours was there first. I'll close this one. thx!

**Comment by csrwng** [comment]
Fixed in #1957

**Pull request closed without merging**
