### PR TITLE
Bug 1720332: images/kube-proxy: update to 4.1, add iptables wrappers

### PR DESCRIPTION
**Pull request by squeed**
This backports the image change in #23163.

This image is currently unused, but is needed by third-parties. So soak time will have no effect.

### CODE REVIEW

**Comment by eparis** [comment]
I don't see a 4.2 bugzilla which was VERIFIED that this was fixed in 4.2.

I also don't see how this solves $whatever the problem is. It just changes where the iptables binaries come from, right? Can I get a better explaination of the problem and how it is fixed in the bugzilla(s)?

**Comment by squeed** [comment]
Turns out this broke the build in 4.2 - need #23250 to merge.

@eparis This is a bit of a funny thing - we are building this image exclusively for third-party network vendors who don't use openshift-sdn, so that they don't have to deploy an out-of-tree kube-proxy binary. Otherwise, it's not deployed. So, QE isn't really doing any validation.

We can't use the existing iptables binaries because of the RHEL7+8 problem: they use very different netfilter mechanisms, and there's no consistent kernel API. The *only* branching point we can use is which binary is symlinked on the host. This is what we do in production for openshift-sdn in 4.1, so this is bringing kube-proxy in-line with what is already deployed and tested.

**Comment by squeed** [comment]
FWIW, the PR to have the operator install standalone kube-proxy for 4.2 is https://github.com/openshift/cluster-network-operator/pull/201 and is QE'd in SDN-247. We probably won't backport the operator change, but still shoud to release the 4.1 image for partners to do development

**Comment by eparis** [comment]
we'll re-review next week. but this is going to miss 4.1.4.  the need for 23250 scares me enough not to destabilize 4.1.4  :)

**Comment by squeed** [comment]
OK, cherry-picked the fixes so that it builds in ART too, not just OSBS.

@pecameron, please review + lgtm
@eparis let me know if this still scares you. It's not deployed by default, so it shouldn't be too scary ;-)

**Comment by jwforres** [comment]
@knobunc I would like group lead sign-off on this one before approving a cherry-pick given it sounds like there is no QE involvement with validating this

**Comment by knobunc** [comment]
This is needed for third-party SDN plugins.  It is not used by the OpenShift SDN, so it can not destabilize the core product.  But this change fixes a problem we found with the SDN image, and it will be a problem for third-party images, and thus should be back-ported.  Thanks!

/approve
/lgtm

**Comment by squeed** [comment]
FYI, *after* this merges, we need to notify Adam Haile to tweak some settings in the ART pipeline.

**Comment by crawford** [comment]
@squeed Can you distill the above description (from both you and @knobunc) and include it in the commit message?

**Comment by squeed** [comment]
@crawford updated both commits.

**Comment by derekwaynecarr** [comment]
@knobunc @squeed thanks for the updates.

approved.

**Pull request merged**
