### PR TITLE
[release-4.4] Bug 1856258: bump cadvisor for incorrect diskstats fix

### PR DESCRIPTION
**Pull request by sjenning**
Pick of https://github.com/openshift/origin/pull/25140
4.5 https://github.com/openshift/origin/pull/25173

xref https://bugzilla.redhat.com/show_bug.cgi?id=1856258

Reviewer note: First commit is just a `make update-deps` with no changes to sync with drift.  Second commit is the actual bump to cadvisor.

@harche

### CODE REVIEW

**Comment by sdodson** [comment]
Clearing cherry-pick-approved after examining the failed tests. These are all build errors, @sjenning PTAL

**Comment by harche** [comment]
@sjenning not sure what's going on with the CI, the failures don't seem like related to the changes.

**Comment by sjenning** [comment]
backport is not trivial due to dependency conflict
```
vendor/github.com/fsouza/go-dockerclient/client.go:553:14: undefined: http.NewRequestWithContext
```

**Pull request closed without merging**
