### PR TITLE
bump(github.com/Microsoft/go-winio):4f1a71750d95a5a8a46c40a67ffbed8129c2f138

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by mfojtik** [comment]
@smarterclayton this broke my rebase branch big time :-)

**Comment by smarterclayton** [comment]
Sorry, it blocked releasing alpha.1 which was a prereq to your rebase.

I don't think this commit is in the correct format, so if you had
already done a godeps import that contains all the per-package
versions feel free to continue using it.

**Pull request merged**
