### PR TITLE
Remove Deployment resource

### PR DESCRIPTION
**Pull request by ironcladlou**
Remove the deprecated Deployment resource.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Thanks for picking this up, I had started to look at this in a separate branch.

**Comment by ironcladlou** [comment]
cc @smarterclayton @abhgupta

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
Fixes https://github.com/openshift/origin/pull/2534

This was the last part of clean-up required by that issue.

**Comment by ironcladlou** [comment]
Let there be [merge]

**Pull request merged**
