### PR TITLE
Use standard images for multi minion scenarios

### PR DESCRIPTION
**Pull request by danmcp**

### CODE REVIEW

**Comment by danmcp** [comment]
@mrunalp @rajatchopra Review please

**Comment by mrunalp** [comment]
@danmcp will test it out, thanks

**Comment by danmcp** [comment]
@sosiouxme Might want to rethink some of this but this is a quick fix to not override box_url and name in the provider settings.

**Comment by sosiouxme** [comment]
This makes sense to me for now; I don't understand node networking enough now to even approach configuring multi-node for other providers, but hopefully soon.

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
