### PR TITLE
Unpack and change versions of Template objects in origin-version-change

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton @bparees initial attempt. PTAL

This seems to work well for the sample-app templates.

### CODE REVIEW

**Comment by smarterclayton** [comment]
runtime.DecodeList will get things in, then use resource.AsVersionedList with the preferred versions.

**Comment by mfojtik** [comment]
@smarterclayton there is just AsVersionedObject which want *Info that contains RESTClient, or I'm missing something.

**Comment by mfojtik** [comment]
@smarterclayton this also works:

```
func changeTemplateObjectsVersion(t *templateapi.Template) {
	if errs := kruntime.DecodeList(t.Objects, api.Scheme); len(errs) > 0 {
		log.Fatalf("Unable to decode Template objects: %v", errs)
	}
	for i, obj := range t.Objects {
		if newObj, err := api.Scheme.ConvertToVersion(obj, *outputVersion); err != nil {
			t.Objects[i] = newObj
		}
	}
}
```

**Comment by mfojtik** [comment]
@smarterclayton btw. is is OK that output template or any other object has fields fields like "creationTimestamp" set to 'null'? And "status" set to {} ?

**Comment by smarterclayton** [comment]
Not every object in a template is guaranteed to be in the scheme.  If conversion fails you have to leave the object as is.  Part of that is what AsVersionedObject is supposed to do.

**Comment by smarterclayton** [comment]
It is, although in the future we want to avoid that.  Also, by doing this you apply defaults (which isn't bad) just not optimal in all cases.

**Comment by mfojtik** [comment]
@smarterclayton updated to use AsVersionedObject, ptal :)

**Comment by smarterclayton** [comment]
lgtm [merge]

**Pull request merged**
