### PR TITLE
OCPBUGS-37837: vertical scaling test should not rely on CPMS replicas

### PR DESCRIPTION
**Pull request by hasbro17**
The vertical scaling test will currently timeout on waiting for the CPMS status.readyReplicas to scale up to 4 where as in practice that may not happen. Ensuring that the cluster membership is 3 and checking that the old member has been removed is enough of a signal that vertical scaling has successfully completed.

### CODE REVIEW

**Comment by hasbro17** [comment]
/payload-aggregate ?

Checking if I can aggregate the scaling job somehow (probably not).

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by hasbro17** [comment]
Okay all the scaling test runs have passed.
This is failing across the board but I've seen this elsewhere so not sure this is related.
```
 [bz-kube-storage-version-migrator] clusteroperator/kube-storage-version-migrator should not change condition/Available 
 
2 unexpected clusteroperator state transitions during e2e test run.  These did not match any known exceptions, so they cause this test-case to fail:

Aug 02 18:33:00.646 E clusteroperator/kube-storage-version-migrator condition/Available reason/KubeStorageVersionMigrator_Deploying status/False KubeStorageVersionMigratorAvailable: Waiting for Deployment
Aug 02 18:33:00.646 - 4s    E clusteroperator/kube-storage-version-migrator condition/Available reason/KubeStorageVersionMigrator_Deploying status/False KubeStorageVersionMigratorAvailable: Waiting for Deployment

1 unwelcome but acceptable clusteroperator state transitions during e2e test run.  These should not happen, but because they are tied to exceptions, the fact that they did happen is not sufficient to cause this test-case to fail:

Aug 02 18:33:05.083 W clusteroperator/kube-storage-version-migrator condition/Available reason/AsExpected status/True All is well (exception: Available=True is the happy case)
```

Running again to see if the scaling test flakes:

/test e2e-aws-ovn-etcd-scaling
/test e2e-gcp-ovn-etcd-scaling
/test e2e-azure-ovn-etcd-scaling
/test e2e-vsphere-ovn-etcd-scaling

**Comment by hasbro17** [comment]
Good enough for me. The scaling test itself is passing consistently now. The jobs trip up on the storage version migrator test but I don't think that's related to the scaling test.

**Comment by tjungblu** [comment]
> Good enough for me. 

for me as well. Thanks @hasbro17 

/lgtm

**Comment by tjungblu** [comment]
/hold

in case you want to still adjust anything

**Comment by hasbro17** [comment]
Update to fix a typo and an extraneous comment. Should be the same otherwise.
/cc @dusk125

**Comment by tjungblu** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6 

unrelated installation issue

**Comment by tjungblu** [comment]
then let's 
/retest-required

**Pull request merged**
