### PR TITLE
Bug 1949096: Restore private git clone tests

### PR DESCRIPTION
**Pull request by adambkaplan**
Restore build tests that clone source from a private git repository.
This test utilizes a private repostiory - nodejs-ex-private - that is
hosted on GitHub in the openshift-github-testing organization. The build
test jobs have been updated to provide source secrets for this
repostitory, allowing code to be cloned via SSH or HTTPS.

Note - needs https://github.com/openshift/release/pull/16992 to merge for tests to function properly.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/retest

gcp hit quota limits

**Comment by adambkaplan** [comment]
@otaviof these tests now work and should pass :smile_cat:

**Comment by adambkaplan** [comment]
/cc @coreydaley @gabemontero @otaviof @alicerum 

PTAL - this is the last item needed to complete https://issues.redhat.com/browse/BUILD-194

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/hold

aws-serial is perma-failing.

**Review by rolfedh — APPROVED** [review]

**Comment by xiuwang** [comment]
The e2e test suites passed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26015/pull-ci-openshift-origin-master-e2e-gcp-builds/1380826327560491008

/label qe-approve

**Comment by adambkaplan** [comment]
/retitle Bug 1949096: Restore private git clone tests

**Review by otaviof — APPROVED** [review]

**Comment by adambkaplan** [comment]
/hold cancel

aws-serial test fixed.

**Comment by adambkaplan** [comment]
/hold

gcp-builds was broken by the samples operator sync.

**Comment by adambkaplan** [comment]
/hold cancel

EOL samples fixed.

**Pull request merged**
