### PR TITLE
UPSTREAM: google/cadvisor: 1588: disable thin_ls due to excessive iops

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1417265

related: https://github.com/google/cadvisor/pull/1588

### CODE REVIEW

**Comment by ncdc** [comment]
/sad

lgtm

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by jboero** [comment]
Odd as this is an issue for one of my nodes and not the other (both backed by NVMe storage) as one is using storage via /dev/loop and the other isn't.

Is there no workaround to disable thin_ls via KUBELET_ARGS or redirecting /usr/sbin/thin_ls symlink?
Thx
JohnnyB

**Comment by sjenning** [comment]
@jboero yes.  the workaround in the xref bz is to bind mount `true` over `thin_ls`

```
mount --bind /bin/true /usr/sbin/thin_ls
```

**Pull request merged**
