### PR TITLE
Added tests for pod-network CLI command

### PR DESCRIPTION
**Pull request by pravisankar**
Trello card: https://trello.com/c/r6pvGxVR/179-2-add-tests-for-pod-network-admin-cli-commands-supportability-techdebt

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[testextended][extended:networking]

**Comment by knobunc** [comment]
[test]

**Comment by knobunc** [comment]
LGTM.

**Comment by pravisankar** [comment]
flake test https://github.com/openshift/origin/issues/9701
re[test]

**Comment by knobunc** [comment]
re[test]

**Comment by pravisankar** [comment]
[testextended][extended:networking]

**Comment by danwinship** [comment]
lgtm [merge]

**Pull request merged**
