### PR TITLE
Only known images used by tests: Fix for Hypershift

### PR DESCRIPTION
**Pull request by alvaroaleman**
This test currently fails for hypershift, because the
`[sig-auth][Feature:OAuthServer] [Headers] expected headers returned from the token URL`
test uses the release image to determine the oauth server image as it
can not derive that from a running pod, as the oauth server is deployed
in the management cluster.

Ref https://issues.redhat.com/browse/HOSTEDCP-257

### CODE REVIEW

**Comment by soltysh** [comment]
@alvaroaleman how adding that image to a list of allowed images will help, if you're saying that the test fails reading that image in the first place because oauth-server is running in the management cluster, which I assume the hosted cluster doesn't have access to, or am I missing something. Can you point me to a CI failure where I can observe that?

**Comment by alvaroaleman** [comment]
@soltysh thanks for the reviewing. There is code that starts a pod with the release image to then extract the oauth server image from it when there is no running oauth-server: https://github.com/openshift/origin/blob/176aeb92845af9eb50b1d0fe8e98a78dee29215e/test/extended/util/oauthserver/oauthserver.go#L489-L532

The pulling of the release image then trips the test. Sample failure is here (search for `[sig-arch] Only known images used by tests`): https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-e2e-aws-pooled-periodic-conformance/1465017674403680256
```
Cluster accessed images that were not mirrored to the testing repository or already part of the cluster, see test/extended/util/image/README.md in the openshift/origin repo:

quay.io/openshift-release-dev/ocp-release:4.9.9-x86_64 from pods:
  ns/e2e-test-htpasswd-idp-fnfsk pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-expiration-fbpld pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-expiration-jqhd5 pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-expiration-tkvf8 pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-expiration-w45gk pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-ldap-idp-8d496 pod/extract-release-imagerefs node/ip-10-0-134-82.ec2.internal
  ns/e2e-test-oauth-server-headers-6597n pod/extract-release-imagerefs node/ip-10-0-140-48.ec2.internal
  ns/e2e-test-oauth-server-headers-6q88k pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-7vtpb pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-fqzbq pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-g46bl pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-gj2pw pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-mm5gc pod/extract-release-imagerefs node/ip-10-0-143-55.ec2.internal
  ns/e2e-test-oauth-server-headers-s4x69 pod/extract-release-imagerefs node/ip-10-0-140-48.ec2.internal
```

**Comment by alvaroaleman** [comment]
@soltysh could you have another look, please? Feel free to ping me in Slack if the above explanation is insufficient

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
