### PR TITLE
remove old version check for sup group test

### PR DESCRIPTION
**Pull request by pweil-**
We are well past the supported version now, removing old check that was bad at parsing `-rc` style versions and skipping the test.

### CODE REVIEW

**Comment by pweil-** [comment]
[testextended][extended:core(security)]

**Comment by pweil-** [comment]
```
[security] supplemental groups
/data/src/github.com/openshift/origin/test/extended/security/supplemental_groups.go:80
  Ensure supplemental groups propagate to docker
  /data/src/github.com/openshift/origin/test/extended/security/supplemental_groups.go:79
    should propagate requested groups to the docker host config [local]
    /data/src/github.com/openshift/origin/test/extended/security/supplemental_groups.go:77
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 684 Specs in 23.623 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 683 Skipped
```

[merge]

**Comment by pweil-** [comment]
flake https://github.com/openshift/origin/issues/11887 [merge]

**Comment by mfojtik** [comment]
[merge]

flake: https://github.com/openshift/origin/issues/11887

**Pull request merged**
