### PR TITLE
Adjust some tests to be more flexible

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@directxman12 @kargakis flake in deployment update on scaling from idle:

```

/data/src/github.com/openshift/origin/test/extended/idling/idling.go:309
Expected error:
    <*util.ExitError | 0xc821390990>: {
        Cmd: "oc idle
--config=/tmp/extended-test-cli-idling-4qadi-8bob3-user.kubeconfig
--namespace=extended-test-cli-idling-4qadi-8bob3 --resource-names-file
/tmp/openshift-extended-tests/idling-services-489782643",
        StdErr: "Marked service
extended-test-cli-idling-4qadi-8bob3/idling-echo to unidle resource
DeploymentConfig extended-test-cli-idling-4qadi-8bob3/idling-echo
(unidle to 2 replicas)\nerror: unable to scale DeploymentConfig
extended-test-cli-idling-4qadi-8bob3/idling-echo to 0, but still
listed as target for unidling: Operation cannot be fulfilled on
deploymentconfigs \"idling-echo\": the object has been modified;
please apply your changes to the latest version and try again",

```
from https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/10705/

[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
> @directxman12 @kargakis flake in deployment update on scaling from idle: ``` /data/src/github.com/openshift/origin/test/extended/idling/idling.go:309 Expected error: <*util.ExitError | 0xc821390990>: { Cmd: "oc idle --config=/tmp/extended-test-cli-idling-4qadi-8bob3-user.kubeconfig --namespace=extended-test-cli-idling-4qadi-8bob3 --resource-names-file /tmp/openshift-extended-tests/idling-services-489782643", StdErr: "Marked service extended-test-cli-idling-4qadi-8bob3/idling-echo to unidle resource DeploymentConfig extended-test-cli-idling-4qadi-8bob3/idling-echo (unidle to 2 replicas)\nerror: unable to scale DeploymentConfig extended-test-cli-idling-4qadi-8bob3/idling-echo to 0, but still listed as target for unidling: Operation cannot be fulfilled on deploymentconfigs \"idling-echo\": the object has been modified; please apply your changes to the latest version and try again", ```

@DirectXMan12 we should probably use patch instead of update in https://github.com/openshift/origin/blob/125ed10fa7103f46c5aa1593210ca0e1d417ea4b/pkg/unidling/util/scale.go#L95 for DCs and RCs. You already patch the service.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
I really wish scale would patch.

**Pull request merged**
