### PR TITLE
Bug 1180393 - Fail to access the Guestbook example

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
@bparees I swear I did this change a long time ago :-) It must sneak out from my Config -> List commits.

**Comment by bparees** [comment]
@mfojtik file history shows it's been broken since november (by a commit you did during a rebase :) ), i believe.

just further proof in my mind that no one is using this and we shouldn't be carrying it as an example.

**Comment by smarterclayton** [comment]
You need to fix the template output I believe (since it's used in the test case)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
