### PR TITLE
Bug 1873043: Rebase to kube 1.19.2

### PR DESCRIPTION
**Pull request by tnozicka**
Bring in kube 1.19.2 https://github.com/openshift/kubernetes/pull/361

/cc @soltysh @sttts

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by tnozicka** [comment]
/hold
`[sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial]` is segfaulting

https://github.com/openshift/origin/blame/ba7fb79a65f5e3668a36ffdadb154a8dfc2e93d8/test/extended/etcd/etcd_storage_path.go#L231

**Comment by tnozicka** [comment]
/hold cancel
the apimachinery test got fixed by MCO PR

**Pull request merged**
