### PR TITLE
Local registry config should only search home dir, not working dir

### PR DESCRIPTION
**Pull request by smarterclayton**
The docker daemon behavior (inherited from kubelet code) is not
consistent with docker client behavior. Instead, clients should only
search the home dir.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1696366

@sttts this fixes your issue

### CODE REVIEW

**Comment by smarterclayton** [comment]
@soltysh as well - docker client supports ~/.docker/config.json, I retained support for `~/.dockercfg` because we have e2es that use it and kube secrets we create to internal registry are still in that format, so we would be breaking back compat with use of these commands inside clusters

From docker docs

> You can log into any public or private repository for which you have credentials. When you log in, the command stores credentials in $HOME/.docker/config.json on Linux or %USERPROFILE%/.docker/config.json on Windows, via the procedure described below.

**Comment by sttts** [comment]
lgtm

**Pull request merged**
