### PR TITLE
UPSTREAM: 10866: don't check extension for single files

### LINKED ISSUE #3712: `oc create` seems broken in 1.0.2
Doesn't seem to work if file is passed in with `-f`, although same file works with cat to stdin:

```
$ oc create  -f ~/tmp/serviceaccount
error: you must provide one or more resources by argument or filename

$ cat ~/tmp/serviceaccount| oc create -f -
serviceaccounts/metrics
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3712
Upstream PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/10866

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k review

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
Protractor flake, [merge]

**Pull request merged**
