### PR TITLE
Use a safer delete of registry pod in test-cmd

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by ncdc** [comment]
FYI test failure was transient (hack/test-cmd.sh: line 76: openshift: command not found) #1579

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
