### PR TITLE
Favor --show-token over --token for whoami

### PR DESCRIPTION
**Pull request by liggitt**
I badly want to be able to do `oc whoami --token=<some-token>`, but we made that the long form of `oc whoami -t` instead.

Deprecate --token and --context in favor of --show-token and --show-context, so in a release we can switch back to using those for building the client

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k @smarterclayton @fabianofranz 

will open a doc PR to sweep in favor of the short flags if this meets with approval

**Comment by smarterclayton** [comment]
I really hope no one has baked this into their CI flows.

**Comment by liggitt** [comment]
[test]

**Comment by deads2k** [comment]
I'm strongly in favor of this, even though it will be breaking.

**Comment by smarterclayton** [comment]
Because -t is common use I'm ok with redefining "--token" but leaving "-t" unchanged.

**Comment by liggitt** [comment]
sounds good. this PR hides and marks as deprecated `--token` and `--context`. I'll queue up removing the overridden behavior in 1.5
[merge]

**Comment by fabianofranz** [comment]
One more use case for my idea of boolean kinda string flag type.  :)

```
--token
--token=<some-token>
```

**Comment by fabianofranz** [comment]
@openshift/cli-review

**Comment by fabianofranz** [comment]
Needs release notes.

**Pull request merged**
