### PR TITLE
BZ_1324273:  BC edit form dirty when deleting Key-Value pair

### PR DESCRIPTION
**Pull request by jhadvig**
@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM. @smarterclayton for approval, currently unable to remove env vars from BCs if you don't edit anything else. Fix is tiny

**Comment by smarterclayton** [comment]
Approved

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by smarterclayton** [comment]
```

PhantomJS 1.9.8 (Linux) KeyValuesController #deleteEntry should delete
the key/value from the scope FAILED
	TypeError: 'undefined' is not a function (evaluating '$scope.form.$setDirty()')
	    at /data/src/github.com/openshift/origin/assets/app/scripts/directives/oscKeyValues.js:9
	    at /data/src/github.com/openshift/origin/assets/test/spec/directives/oscKeyValuesSpec.js:118

```

**Comment by jwforres** [comment]
@jhadvig I am guessing the form needs to be mocked on the scope for the
spec test

**Comment by jhadvig** [comment]
@jwforres @smarterclayton yep, had to update the spec. Fixed now

**Comment by jhadvig** [comment]
For some reason the extended tests are failing
~~~
Stderr from the command:

info: password for stats user admin has been set to Oe0EDRrgU2
I0407 04:29:20.292459   19308 plugins.go:62] Registered admission plugin "ServiceAccount"
I0407 04:29:20.303551   19308 plugins.go:46] Registered cloud provider "aws"
I0407 04:29:20.304499   19308 plugins.go:46] Registered cloud provider "gce"
I0407 04:29:22.373375   19398 plugins.go:62] Registered admission plugin "ServiceAccount"
I0407 04:29:22.388801   19398 plugins.go:46] Registered cloud provider "aws"
I0407 04:29:22.389899   19398 plugins.go:46] Registered cloud provider "gce"
!!! Error in test/extended/conformance.sh:51
	'return $out' exited with status 1
Call stack:
	1: test/extended/conformance.sh:51 main(...)
Exiting with status 1
~~~

@smarterclayton maybe a flake ?

**Comment by jwforres** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
