### PR TITLE
Replace all hardcoded default tags with DefaultImageTag

### PR DESCRIPTION
**Pull request by kargakis**
Plus move DefaultImageTag under the image api

### CODE REVIEW

**Comment by ncdc** [comment]
I'm pretty sure @smarterclayton was talking about having per ImageStream default tags...

**Comment by smarterclayton** [comment]
Yes, latest will be converted to mean something when you push.

**Comment by smarterclayton** [comment]
I'm going to merge this and we'll do the other fix later [merge] (andy we can't forget that)

**Comment by ncdc** [comment]
@smarterclayton https://trello.com/c/NIqsCzlx/404-allow-user-to-specify-an-image-stream-s-default-tag-imageregistry-codefreeze

**Pull request merged**
