### PR TITLE
Make deployments minreadyseconds test more tolerant to infra

### PR DESCRIPTION
**Pull request by tnozicka**
Fixes https://github.com/openshift/origin/issues/16025

Will run several test runs here to ses that the flake isn't occurring anymore.

### CODE REVIEW

**Comment by tnozicka** [comment]
jenkins AWS provisioning issues
/retest

**Comment by tnozicka** [comment]
adding do-not-merge label so we can test it few times before merging.

(Not that it means much but I have been running 5 parallel instances of this test throughout the night on my laptop and each succeeded ~467 without any flake)

**Comment by tnozicka** [comment]
round 1 passed
/test all

**Comment by kargakis** [comment]
flaked on https://github.com/openshift/origin/issues/14962

/retest

**Comment by tnozicka** [comment]
e2e flaked on https://github.com/openshift/origin/issues/14962
install_update flaked on https://github.com/openshift/origin/issues/16072
/retest

**Comment by tnozicka** [comment]
round 2 passed
/test all

**Comment by tnozicka** [comment]
install_update flake https://github.com/openshift/origin/issues/15988
/retest

**Comment by tnozicka** [comment]
removing do-not-merge label since the success will be 3rd in a row

**Pull request merged**
