### PR TITLE
Update java console

### PR DESCRIPTION
**Pull request by gashcrumb**
Notable changes

* JMX plugin won't send X-Authorization header anymore
* Camel plugin improvements

@jwforres FYI

### CODE REVIEW

**Comment by jwforres** [comment]
@gashcrumb should this be updating the regular bindata?  we just had a fix merge related to the minified templates in our bindata, can you try rebasing on master and clean/install/build assets again

**Comment by gashcrumb** [comment]
@jwforres I didn't think it should either, but maybe that outstanding merge was it.  Let me try rebasing...

**Comment by gashcrumb** [comment]
@jwforres hmm, re-based my branch and even just doing `./hack/install-assets.sh && ./hack/build-assets.sh` changes those two files even without bumping the java console version, thoughts?

**Comment by jwforres** [comment]
You ran clean-assets first?

**Comment by gashcrumb** [comment]
@jwforres trying now...  Did recently do a nodejs upgrade here, but I can't imagine that would change this...

**Comment by gashcrumb** [comment]
@jwforres that was it, thanks!  Just the two files changed now...

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
