### PR TITLE
Fix printing error messages for new-app

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@csrwng @soltysh PTAL

**Comment by soltysh** [comment]
:+1: on @csrwng's idea regarding `errors.NewAggregate`

**Comment by mfojtik** [comment]
@csrwng @soltysh updated, PTAL

**Comment by csrwng** [comment]
LGTM

**Comment by mfojtik** [comment]
@smarterclayton merge?

**Comment by smarterclayton** [comment]
Why aren't we returning resolution errors alongside our matches?  Seems wrong to hide them.

**Comment by csrwng** [comment]
Errors can happen in one resolver while another one can find a match. If a match is found, do we still want to print the errors?

**Comment by smarterclayton** [comment]
I think it depends on the match.  We may need to allow a match and an error to be returned (partial success) and let the caller handle the error.  glog.Errorf in library code is usually an indicator we should be returning an error.  It's possible resolver should be ([]match, []error) or similar.  ErrMultiplrMatch is looking like a code smell.

**Comment by smarterclayton** [comment]
The only think we need an error for multiple matches is across resolver types (so we can disambiguate on the cli).

**Comment by danmcp** [comment]
@mfojtik Bump

**Comment by mfojtik** [comment]
@danmcp I will close this and open a new PR since the conflicts are pretty bad and a lot of code was changed in meanwhile.

**Pull request closed without merging**
