### PR TITLE
UPSTREAM: 49120: Modify podpreset lister to use correct namespace

### PR DESCRIPTION
**Pull request by jpeeler**
upstream pick for https://bugzilla.redhat.com/show_bug.cgi?id=1473374
bug 1473374

### CODE REVIEW

**Comment by jpeeler** [comment]
upstream PR is lgtm/approved [test]

**Comment by jpeeler** [comment]
[test]

**Comment by jpeeler** [comment]
flake #15387

**Comment by jpeeler** [comment]
[test]

**Comment by eparis** [comment]
[merge]

**Pull request merged**
