### PR TITLE
UPSTREAM: 60069: Fix race in healthchecking etcds leading to crashes

### PR DESCRIPTION
**Pull request by deads2k**
likely candidate for https://bugzilla.redhat.com/show_bug.cgi?id=1636141

@mfojtik seems fairly likely.

/assign @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
/retest
/lgtm

@deads2k yeah, that looks like it, good job!

**Comment by smarterclayton** [comment]
We need to update Jenkins to have a new push token that can push to the “ci-pr-images” namespace that the job can use.  Ping testplstform - the Jenkins docker credentials on ci.openshift.redhat.com need to be updated with a service account token that can push to that namespace (and has create image stream rights, so probably the builder service account)

**Pull request closed without merging**
