### PR TITLE
Fix multi attach log spam

### PR DESCRIPTION
**Pull request by gnufied**
This PR fixes multiattach log spam. 

Subsequent PRs are for fixing test flakes and a lock error. All these PRs have already been merged into master.

### CODE REVIEW

**Comment by gnufied** [comment]
cc @childsb @rootfs

**Comment by rootfs** [comment]
merge into master or staging branch?

**Comment by gnufied** [comment]
@rootfs this is for merge into stage branch. All the commits here have already been merged into master.

**Comment by deads2k** [comment]
Are these already in openshift/origin:master?

**Comment by deads2k** [comment]
> Are these already in openshift/origin:master?

@gnufied I think I found them in the git log.  If I'm mistaken be sure to open pulls for any that were missed.

/approve

**Comment by gnufied** [comment]
@deads2k yes all commits here has already been commited/merged into master.

**Pull request merged**
