### PR TITLE
return back the name you GETed for ISI

### PR DESCRIPTION
**Pull request by deads2k**
Makes the name you requested match the name you get.

@jwforres See how this works out for you.
@smarterclayton you're the one who made them mismatch.  Objections?

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
I think I made them mismatch for Jessica...

This is the correct change - no one who was using it before is any more broken than they are today.  Partial name retrieval is still viable for non-mismatched names - the previous code could be broken if you tagged a new image with the same prefix and deleted the old one silently.

**Comment by smarterclayton** [comment]
This is a 1.3.1 candidate.

**Comment by deads2k** [comment]
> I think I made them mismatch for Jessica...

@jwforres see, you requested that we break your cache. :)

**Comment by liggitt** [comment]
> @jwforres see, you requested that we break your cache. :)

The correct response is "I have no memory of that"

**Comment by jwforres** [comment]
I have no memory of that.  I do remember it was originally completely
broken, it was returning the image stream name as the name.

**Comment by smarterclayton** [comment]
Anyway, why are you caching on image stream image name?  You should be
caching on image.name

On Sep 19, 2016, at 5:59 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test SUCCESS (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8997/)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/10996#issuecomment-248140603>,
or mute
the thread

**Comment by liggitt** [comment]
Pretty sure it's a generic data layer cache… get object named foo from cache or from the API (then cache by metadata.name of the retrieved object)

**Comment by jwforres** [comment]
Exactly what @liggitt said, we have a generic data cache, I'd rather not
special case this unless it's necessary.

**Comment by smarterclayton** [comment]
It's probably fine in the context of the UI as it is today.  Something that
showed apps across projects or a pipeline view would probably see more
misses.  We'll get more real world examples with the new release process
hopefully.

**Comment by jwforres** [comment]
@deads2k confirmed my cache works with this change

**Comment by deads2k** [comment]
@mfojtik ptal

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
