### PR TITLE
TemplateInstance metrics update

### PR DESCRIPTION
**Pull request by jim-minter**
@bparees @gabemontero @smarterclayton this PR would update TemplateInstance metrics in line with the discussion at https://docs.google.com/document/d/1L8xh5blVzWGO5uC0oXAEFjGto9SpaEY4EY7MjAHH_bI

### CODE REVIEW

**Comment by gabemontero** [comment]
@bparees @jim-minter - a question, with the understanding that comparing the controller for templates and the controller for builds might be of the apples to oranges variety, at least in this instance:

Quick historical context:  when first implementing bld metrics with https://github.com/openshift/origin/pull/15440, I made a foray into updating metrics in the build controller's FSM, and we hit various timing windows resulting in either double counting, missed decrements, etc.  So we ultimately punted on doing it that way.

So part of @jim-minter 's change here includes incrementing the new total counter in the template controller.  Do we think this is viable, or have not seen any issues with it, because:

1) counters, with inc() only, are simpler to maintain than gauges
2) the template controller, or the "template scenario", is such that it is not vulnerable to the same timing isuses
3) some combination of 1) and 2)
4) other reason(s) not immediately occurring to me?

thanks

**Comment by bparees** [comment]
@gabemontero i think it's simpler in this case because only the template controller itself puts things into a terminal state, whereas w/ builds the flows are much more complicated.

**Comment by gabemontero** [comment]
thanks @bparees , so basically my 2), but with more precise detail :-)

**Comment by gabemontero** [comment]
but of course the next step for me given that will be how much of this PR I can mimic verbatim

**Comment by jim-minter** [comment]
I think it's worth debating if we want to do the "single gauge reflecting the current longest running (stuck) item" approach - this could get rid of the slightly arcane histogram use in this PR.

**Comment by gabemontero** [comment]
Yeah, one of my takeaways from the SRE videos was that the examples leveraging `predict_linear(..)` for alerts really resonated with me, and that function is suppose to only be used with a gauge.

**Comment by bparees** [comment]
/hold


Ben Parees | OpenShift

**Comment by bparees** [comment]
@jim-minter i know you have other responsibilities now but if it's immediately obvious to you why the integration test is failing, can you fix this up?  If not i'll try to get to it this week.

Thanks

**Comment by bparees** [comment]
fixing this PR up here: https://github.com/openshift/origin/pull/19133
/close

**Pull request closed without merging**
