### PR TITLE
Better error message when pod with name of deployer pod already exists

### PR DESCRIPTION
**Pull request by pmorie**
@ironcladlou The existing message isn't terribly helpful without the actual name.

### CODE REVIEW

**Comment by pmorie** [comment]
@detiber This is one we need in the environment we're building.  Let's discuss what has to happen to put it there.

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@smarterclayton your imprimatur?

**Comment by ironcladlou** [comment]
Good catch, [merge]

**Pull request merged**
