### PR TITLE
DO NOT MERGE - Expose all container ports creating from source in the UI

### LINKED ISSUE #3764: UI only includes first port in generated service
`oc new-app` exposes all container ports in the generated service (although it looks like it has an option to only include the first port, which is hard-coded to `false` at the moment)

The UI only includes the first container port in the generated service, and leaves it nameless (which is allowed for a single port).

@csrwng was the a reason to only include the first container port in the service?
@spadgett the UI should be consistent with new-app. That probably means including all container ports as service ports, and adding generated names to the service ports

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #3764 

@csrwng ptal

### CODE REVIEW

**Comment by bparees** [comment]
with this change, if the user chooses to create a route for the service, which service gets a route?

**Comment by csrwng** [comment]
you're still creating a single service, do you mean which port the route points to?

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
@csrwng I was under the impression this is creating a service for all exposed ports in the image now, not just a single service.  no?

the test case says ""should create service ports for all exposed ports"

**Comment by bparees** [comment]
ok, @csrwng straightened me out.  I see now it's a single service with multiple ports.

@rajatchopra @pweil- how does a route definition handle a service that has multiple ports?  which port does it route to?

**Comment by liggitt** [comment]
Routes don't handle multi port services well yet, do they?

**Comment by pweil-** [comment]
> how does a route definition handle a service that has multiple ports? which port does it route to?

It will try to make a backend entry for each server/port combination so they are not well supported when mixing protocols (say ssh and http) in a service.  There is a trello card for this that is being prioritized.

**Comment by bparees** [comment]
given @pweil- 's statement, i'm not convinced we should merge this.  We need to understand if it's going to cause routing to break when routing to images that expose multiple ports.

**Comment by liggitt** [comment]
It's not just a protocol issue, the route assumes all ports should be routed to. You could have two http ports that serve completely different content and should not be pooled

**Comment by liggitt** [comment]
This is to be consistent with `oc new-app`. If there's an issue we should fix that

**Comment by bparees** [comment]
@liggitt yes it's true it's brokenish for new-app too, but new-app doesn't create a route for you.  

so at least in theory if you decide to go create a route after running new-app, you could also go create a proper service.

**Comment by liggitt** [comment]
Ok, should wait until routes are fixed to add this, then. Add a comment to the issue to indicate it is blocked on route fixes

**Comment by pweil-** [comment]
link for what it's blocking on: https://trello.com/c/UyLwfTY6/33-route-spec-and-support-mulitple-ports-protocols-routing

**Comment by danmcp** [comment]
@spadgett Bump and needs a rebase.

**Comment by spadgett** [comment]
@pweil- I don't have access to the card or the link is broken... Are the route changes in plan?

**Comment by pweil-** [comment]
@spadgett - this card is still in the New list on the networking board

**Comment by spadgett** [comment]
@liggitt OK if I close this until the route changes are done?

**Comment by liggitt** [comment]
sure, the tracking issue is fine

**Pull request closed without merging**
