### PR TITLE
[stage] UPSTREAM: 49016: PV controller: resync informers manually

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501152

cc @openshift/sig-storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
flake: #16929

**Comment by deads2k** [comment]
@jsafrane backport to stage?

**Comment by deads2k** [comment]
The resync for other shared informer consumers would be skipped until their requested resync came about, right?  Did that feature break somehow?

**Comment by jsafrane** [comment]
rebased to stage

@deads2k, it's fix for this bug: https://github.com/kubernetes/kubernetes/issues/49905#issuecomment-319367328. PV controller may start when informer sync period is already fixed and can't be changed.

**Comment by deads2k** [comment]
> @deads2k, it's fix for this bug: kubernetes/kubernetes#49905 (comment). PV controller may start when informer sync period is already fixed and can't be changed.

That sounds like a bug.  Who is starting it?  We fixed the GC start problem.

**Comment by jsafrane** [comment]
It's started as usual controller in controller-manager, nothing special about it. And someone complained (@liggit?) that we should not force all controllers to have 15 second resync period, that's too often. So I added manual resync.

**Comment by jsafrane** [comment]
```
        "Auto-merging vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go", 
        "CONFLICT (content): Merge conflict in vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go", 
```

This PR does not touch `kuberuntime_manager.go`...

/test all

**Comment by deads2k** [comment]
> It's started as usual controller in controller-manager, nothing special about it. And someone complained (@liggit?) that we should not force all controllers to have 15 second resync period, that's too often. So I added manual resync.

@liggitt is the skip logic that avoids resyncing everyone broken?

**Comment by jsafrane** [comment]
> And someone complained (@liggit?) that we should not force all controllers to have 15 second resync period

Found the complaint: https://github.com/kubernetes/kubernetes/issues/48941

**Comment by deads2k** [comment]
> And someone complained (@liggit?) that we should not force all controllers to have 15 second resync period
> Found the complaint: kubernetes/kubernetes#48941

@liggitt was that before we ensured startup order and had the opt-in resync?

**Comment by liggitt** [comment]
> @liggitt was that before we ensured startup order

probably

> and had the opt-in resync?

not sure what that is referring to. I still think a 15 second resync, no matter how it is done, is way too short. we have better patterns for retrying failed objects at a shorter interval without resyncing the whole list.

**Comment by deads2k** [comment]
> not sure what that is referring to. I still think a 15 second resync, no matter how it is done, is way too short. we have better patterns for retrying failed objects at a shorter interval without resyncing the whole list.

No other consumers would see a resync.  Only this controller that asked would see it.

I agree it is too short, but this doesn't look better than actually specifying the resync since it doesn't hurt other consumers.

**Comment by wongma7** [comment]
would like to point out it's not just for retrying failed cases, it's a fundamental assumption in the pv controller which is apparently "space shuttle" code and hard to change? The reason for this bug is basically there is a "syncUnboundClaim" but no "syncUnboundVolume": if a volume has just been created, there is no reason to assume there exists a claim looking for it. but if a claim has just been created, obviously the controller should find a volume for it.

another case from today: a `Bound` volume's pvc is deleted. "syncClaim" will get triggered, but it should not be syncClaim's responsibility to update the `Bound` volume to `Released`. that is the job of "syncVolume," which can only be triggered by the periodic resync...

**Comment by liggitt** [comment]
> it's a fundamental assumption in the pv controller which is apparently "space shuttle" code and hard to change?

requiring resync of all objects to stay responsive on subsets of objects that need reprocessing is an assumption that does not scale and should be redesigned.

**Comment by jsafrane** [comment]
> requiring resync of all objects to stay responsive on subsets of objects that need reprocessing is an assumption that does not scale and should be redesigned.

While I agree with this, nobody complained so far that PV controller is too slow. Compare with A/D controller that syncs all pods with attachable volumes every 100 ms.

Redesign is on long-term TODO list, I added a card to our board. https://trello.com/c/ARmicYxn/577-speed-up-pv-controller

**Comment by deads2k** [comment]
At any rate, there are now better ways to solve this and you should use them instead of this.  However, this is the current state upstream and is better than the bug at the moment.

/lgtm

**Comment by deads2k** [comment]
@jsafrane you you also open the pull against master so it doesn't regress.

**Comment by deads2k** [comment]
@jsafrane holding this until the openshift/origin:master pull is open and labeled.

**Comment by deads2k** [comment]
@jsafrane I'm sorry about this, but @eparis found a special-case in online that lets us avoid this problem. repoint to master?  still lgtm

**Comment by jsafrane** [comment]
opened PR against master in #16965

**Comment by jsafrane** [comment]
master counterpart is merged, can we merge this one?

**Comment by eparis** [comment]
going to close this one, we'll get it in stage tomorrow night on the next stage rebase.

**Pull request closed without merging**
