### PR TITLE
Update etcd test data for 1.30 release

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Address the e2e failure:

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_kubernetes/1953/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-serial/1783666697446625280

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@sairameshv PTAL

**Review by sairameshv — COMMENTED** [review]
LGTM

However, I would like to request @soltysh to take a look

**Comment by soltysh** [comment]
This is missing changes, closing in favor of https://github.com/openshift/origin/pull/28770

**Pull request closed without merging**
