### PR TITLE
Move registry and router out of experimental commands

### LINKED ISSUE #2596: Remove registry/router from `openshift ex`
@smarterclayton is there any reason why it remains experimental?

### PR DESCRIPTION
**Pull request by kargakis**
Closes #2596

### CODE REVIEW

**Comment by kargakis** [comment]
@liggitt fyi

**Comment by bparees** [comment]
any openshift-doc or training materials that are affected by this?  @thoraxe fyi.

**Comment by thoraxe** [comment]
I think we've been using osadm for registry/router for a while now, but I'll double check.

**Comment by kargakis** [comment]
> any openshift-doc or training materials that are affected by this? @thoraxe fyi.

Grepped both repos, found nothing in openshift-doc, some references in training still left. I will submit a PR fixing them shortly.

**Comment by kargakis** [comment]
training PR: https://github.com/openshift/training/pull/229

There are still references using `openshift ex` but that material are for beta1 and beta2 versions with a `**THIS DOCUMENT IS DEPRECATED. PLEASE CHECK THE README FOR THIS REPO**` note on them so I didn't bother updating those.

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
