### PR TITLE
Fix issue#2655; bz1225410; rebase openshift-sdn Godeps

### PR DESCRIPTION
**Pull request by rajatchopra**
Auto registration of nodes should work now - @sdodson @detiber Tested locally with vagrant, needs more testing especially in a reboot scenario.
Pods spun up manually or by the builder can reach the internet (though they cannot reach pods on another node) - @csrwng Tested locally, needs testing with the STI builder.

### CODE REVIEW

**Comment by sdodson** [comment]
I'm wondering if this exacerbates the issue with docker being configured to use a bridge that doesn't exist. Without clearing docker's bridge config docker won't start and the node stops before it attempts to initialize the sdn. I think we need to work towards a solution that at runtime gerates the docker network options.

@detiber FYI

**Comment by rajatchopra** [comment]
This fix requires a system setting on all the nodes:
net.bridge.bridge-nf-call-iptables=0

**Comment by rajatchopra** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1225410 has been marked verified.
@mrunalp Review please. And kindly mark for merge if it looks good to you.,

**Comment by mrunalp** [comment]
[merge]

**Comment by smarterclayton** [comment]
Reverted by https://github.com/openshift/origin/issues/2655 because it requires Docker restarts while the Kubelet is running

**Pull request merged**
