### PR TITLE
Updating tests for new S2I postCommit code

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal

**Comment by bparees** [comment]
Ok, it's still running e2e-conformance-k8s, must be predicated on what files you touch.  Open a bug for the failing tests or create an issue at openshift/release for the fact that the job in general is unreliable (I think the issue is more infrastructure than test related, I think the cluster these tests are running on is too small, which is causing timeouts).

**Comment by bparees** [comment]
and point them here to demonstrate this job is never passing: https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/pull-ci-openshift-origin-master-e2e-conformance-k8s

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/21337

**Pull request closed without merging**
