### PR TITLE
apps: react to library-go move

### PR DESCRIPTION
**Pull request by mfojtik**
Only last two commits are relevant.

### CODE REVIEW

**Comment by mfojtik** [comment]
/hold cancel

if this merges before pre-reqs it just means we get them faster ;-)

**Comment by deads2k** [comment]
Holy conflicts

**Comment by soltysh** [comment]
/hold
to stop bot from re-testing

**Comment by mfojtik** [comment]
/hold cancel

rebased and fixed

**Comment by mfojtik** [comment]
reapplying lgtm, fixed rebase  conflict

**Pull request merged**
