### PR TITLE
Set OS_OUTPUT_GOPATH=1 to build in a local GOPATH

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
Works fine, thanks

**Comment by elyscape** [comment]
This works for me. Thanks for your help!

**Comment by stefwalter** [comment]
@smarterclayton This breaks cloning the repo and running 'make' or 'hack/build-go.sh'. Is that intentional? One must first put the following in ```.bashrc```:

```
export OS_OUTPUT_PATH=1
```

**Comment by smarterclayton** [comment]
The assumption is that we are good Go citizens, so "go get
github.com/openshift/origin && make" should work.  Is that not the case for
you?

**Comment by smarterclayton** [comment]
However, I can buy the argument that "make" should default to
"OS_OUTPUT_GOPATH=1" because that's the default behavior of "make" projects.

**Comment by stefwalter** [comment]
> The assumption is that we are good Go citizens, so "go get github.com/openshift/origin && make" should work.  Is that not the case for you?

"Get off my lawn" and all that :) I contribute to many projects, if each of them wanted to be opinionated about my home directory and environment ... I'd get a bit grumpy.

But yeah, I guess I should setup Go properly on my machines.

> However, I can buy the argument that "make" should default to "OS_OUTPUT_GOPATH=1" because that's the default behavior of "make" projects.

Will do that.

**Pull request merged**
