### PR TITLE
[DO NOT MERGE] UPSTREAM: 37288: Improve quota scope descriptions

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/37288

Fixes https://github.com/openshift/origin/issues/11985
Based on web-console PR https://github.com/openshift/origin-web-console/pull/887

cc @fabianofranz @jwforres

### CODE REVIEW

**Comment by fabianofranz** [comment]
SGTM

**Comment by ncdc** [comment]
This isn't going to go in upstream as is because it mentions builds. I also don't think this warrants an UPSTREAM pull here. It can wait for the next rebase after the one in progress (i.e. for 1.6) in whatever shape it's in at that point.

@jwforres

**Comment by jwforres** [comment]
Agree with both points here.

**Comment by fabianofranz** [comment]
Let's rephrase it in the upstream PR, mention the upstream PR in a comment in the original issue and tag it with `post-rebase` so that we verify and close it once the next (1.6) rebase lands with the fix.

**Pull request closed without merging**
