### PR TITLE
explicitly prohibit updates to imagestream tags that are not spec tags

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/18519

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @deads2k ptal

the net effect of this is that if you edit an IST that was only pushed, the update results in adding a new spec tag to the IS:
```
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      foo: bar
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
```

Which near as i can tell is absolutely required because that's where the annotations are stored, so you can't add annotations w/o introducing a spec tag.

I would certainly rather this go through the mainline defaulting logic instead of what i'm doing, but it sounds like that might not be a realistic option.

**Comment by bparees** [comment]
(the other option is that we just say "you shouldn't be updating ISTs that were only pushed, the current behavior is acceptable")

**Comment by deads2k** [comment]
I don't actually know how other clients will interpret this.  Without an import policy, it doesn't sound that bad.

**Comment by bparees** [comment]
one bad thing about this:  since "From" is empty, it results in rather user unfriendly errors when you run "oc import-image", e.g.:

```
error: the tag "latest" does not exist on the image stream - choose an existing tag to import or use the 'tag' command to create a new tag
```

Clearly having a spec.tag with an empty "From" is not handled well by oc import-image.  So this may not be the right solution.  (In theory i could also craft the "From" value to point to the internal registry, but that seems a bit dubious)

/hold

**Comment by bparees** [comment]
@deads2k @smarterclayton ok i've reworked this to just reject the update w/ a clean message telling you why your imagestreamtag update is being rejected. ptal again.

/hold cancel

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by bparees** [comment]
implicit approval from @smarterclayton and @deads2k, lgtm'ing

/hold

**Comment by deads2k** [comment]
Makes me sad, but I doubt we fix it now.

lgetm

**Comment by bparees** [comment]
@deads2k I think it's /cherrypick and anyway I don't deem this critical enough to backport to 3.9 at this point (just in case this new error behavior causes unexpected problems, i'd rather let it soak for a release).

**Pull request merged**
