### PR TITLE
Fix a typo of logging code in pkg/router/template/router.go

### PR DESCRIPTION
**Pull request by louyihua**
The call to `Info()` should be `Infof()` in line 679 or the output is incorrect.

### CODE REVIEW

**Comment by ramr** [comment]
LGTM    [test]

**Comment by ramr** [comment]
@knobunc  some merge goodness please. Thx

**Comment by knobunc** [comment]
[merge]

**Comment by louyihua** [comment]
Seems there are some check errors unrelated to the code in this PR, so should the tests be run again or any other solutions?

**Comment by knobunc** [comment]
Yum mirror failure.  [merge]

**Pull request merged**
