### PR TITLE
Grafana example to use prometheus service

### LINKED ISSUE #18500: Avoid using routes for prometheus by using services instead
https://github.com/openshift/origin/blob/d5f8d8b4877885df02fe09082ac7ed07696209ac/examples/grafana/setup-grafana.sh#L53

I think it would be better to avoid going through the route to query prometheus. Maybe deploying grafana in the same project than prometheus or joining the projects will be better instead.

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #18500

### CODE REVIEW

**Comment by mrsiano** [comment]
what do you think about make this change optional ?!
so we ca use both svc and route.
we can have the svc as default.
see also 
https://github.com/openshift/origin/pull/18353

**Comment by e-minguez** [comment]
I agree it will be better to have it optional. Shall I close the issue then?
What about [this playbook](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_grafana) you've created as well? I think it will be better to use it instead a script. Are both going to be supported?
Thanks!

**Comment by mrsiano** [comment]
what do you think about merge you PR as well?, if so I guess we need the issue open.

I'm not sure if both are going to be supported.
I agree we need to use ansible as the main method to deploy it, but meanwhile what do you think about keep them both ?

**Comment by e-minguez** [comment]
I'd say to just keep the playbook, it is much more elegant :) (to be honest, I created the PR because I didn't know about the playbook)

**Pull request closed without merging**
