### PR TITLE
add --sub-path opt to set-volume cmd

### PR DESCRIPTION
**Pull request by juanvallejo**
Fixes https://github.com/openshift/origin/issues/16275

Adds a `--sub-path` option to `oc set volume ...`.
Updates command to match web-console functionality.

cc @openshift/cli-review

### CODE REVIEW

**Comment by fabianofranz** [comment]
Worth adding some tests to test/cmd/volumes.sh.

**Comment by fabianofranz** [comment]
Not necessarily part of this PR, but while reviewing I noticed this cmd doesn't protect against mutually exclusive flags like `--list --mount-path=/foo` (and now `--list --sub-path`). Of course having a `set` command that does `--remove` and `--list` is a good part of the cause. It's hard to fix a bad cmd usability design now, but we should open an issue to at least try to make the set of flags behave correctly against each other. ;)

**Comment by juanvallejo** [comment]
@fabianofranz 
> Not necessarily part of this PR, but while reviewing I noticed this cmd doesn't protect against mutually exclusive flags like --list --mount-path=/foo (and now --list --sub-path). Of course having a set command that does --remove and --list is a good part of the cause. It's hard to fix a bad cmd usability design now, but we should open an issue to at least try to make the set of flags behave correctly against each other. ;)

Sounds good to me, will open issue to track this

**Comment by juanvallejo** [comment]
@fabianofranz 
> Worth adding some tests to test/cmd/volumes.sh.

Thanks, done!

**Pull request merged**
