### PR TITLE
WIP: sync deps with godep scripts

### PR DESCRIPTION
**Pull request by sjenning**
We recently merged scripts to restore and save godeps so developers can do this in a less error prone way.  However, a restore-then-save isn't currently a no-op, which is should be.

This PR is a the result of a ```hack/godep-restore``` on an empty ``GOPATH``, then a ```hack/godep-save.sh```.  If this adds or removes a dep that is needed or not needed, the scripts need to be adjusted to make an exception for those packages.

@smarterclayton @liggitt @ncdc @eparis

### CODE REVIEW

**Comment by liggitt** [comment]
things that look odd to me:

* `github.com/docker/distribution` deleted packages
* `x/sys/windows` deleted packages (these have been deleted and readded multiple times recently... we should figure out why)

**Comment by ncdc** [comment]
I think the docker/distribution packages moved to "vendor" under the
distribution godep as part of the GCS enablement PR, right @smarterclayton?

**Comment by ncdc** [comment]
@sjenning you'll have to reword your commit to say something like `bump(fix all the things)` 😄 to be able to pass the commit message checker.

**Comment by smarterclayton** [comment]
I'm going to hold this until after the rebase.

On Jun 28, 2016, at 12:46 PM, Andy Goldstein <notifications@github.com>
wrote:

@sjenning <https://github.com/sjenning> you'll have to reword your commit
to say something like bump(fix all the things) 😄 to be able to pass the
commit message checker.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9607#issuecomment-229161056>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_pzRZmo441A-TRd9vc32RxRRxZ-jBks5qQXoqgaJpZM4JAONI>
.

**Comment by smarterclayton** [comment]
Some of them.  Not all.

**Comment by sjenning** [comment]
After the rebase, this is no where near right anymore.  Closing for now.  Will reopen when I have time to look at it again.

**Pull request closed without merging**
