### PR TITLE
retrieve keys from cache.Delta objects properly

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/9830

@smarterclayton ptal

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton i'm not clear from this comment: https://github.com/openshift/origin/issues/9830#issuecomment-232491765 if you think there is another case where we're handling this incorrectly?  From what i can tell, builds are the only users of DeltaFIFO in origin.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
The service controller does it, but was fixed in Kube 1.4.  Leaving as is
for 1.3

**Comment by bparees** [comment]
not sure why tests got re-kicked on this, but extended passed here:
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/439/

[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
