### PR TITLE
Bug 2044210: [baremetal] remove wait condition when deleting extraworkers

### PR DESCRIPTION
**Pull request by andfasano**
Do not wait for workers to be cleaned up on teardown. Setup in any case will take care of waiting previously deleted ones (impacts only serial jobs)

### CODE REVIEW

**Comment by bfournie** [comment]
/lgtm
Just waiting for test results, also will need a BZ.

**Comment by ardaguclu** [comment]
Since this PR has already been waiting valid-bug label, I'll run retest one more time for serial job;

/test e2e-metal-ipi-serial

**Pull request merged**
