### PR TITLE
Add details for field.Required

### PR DESCRIPTION
**Pull request by pweil-**
Fixes issue #7118 

@deads2k rebased and addressed the remaining feedback in https://github.com/openshift/origin/pull/9198#r67919429.  Was there anything before this is ready to merge?

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
re[test]

**Comment by pweil-** [comment]
flake https://github.com/openshift/origin/issues/11016 and unrelated govet complaints

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/10773 re[test]

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/11094 re[test]

**Comment by pweil-** [comment]
[merge]

**Pull request merged**
