### PR TITLE
tests: allow `watch` to timeout

### PR DESCRIPTION
**Pull request by wozniakjan**
There appears to be probably multiple issues with https://github.com/openshift/origin/issues/16940

One could be that the `WaitLoop` with timeout 60s watching `Build` and `BuildConfig` events appears to never finish because the timeout is restarted every time an event on either of the watches appears. 

- This is a run just with @enj commit to client rate limiting and `TestConcurrentBuildImageChangeTriggerControllers` fails with `panic: test timed out after 5m0s`
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/17930/consoleText
and one of the goroutines being stuck at 
https://github.com/openshift/origin/blob/5843432e015a1abe1087b0404a9cb1f5c0267923/test/common/build/controllers.go#L460

- Added here a bunch of debugging statements (note that despite some tests failing, Jenkins thinks it succeeded) and the second `WaitLoop2` probably never finishes
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/17940/consoleText

Another issue is that test sometimes runs out of memory which I have not addressed yet:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/17971/consoleText
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/17972/consoleText

ptal @openshift/sig-developer-experience

### CODE REVIEW

**Comment by bparees** [comment]
@wozniakjan this change seems reasonable to me though i'm not sure why turning off rate-limiting would be the thing that causes it to become a problem?

in anycase i'm happy to merge this independently while you continue your investigation if you want to remove the WIP.

/approve

**Comment by wozniakjan** [comment]
> this change seems reasonable to me though I'm not sure why turning off rate-limiting would be the thing that causes it to become a problem?

@bparees I, unfortunately, am unable to provide an answer yet, only more questions. I have tried to log the events there and thought this could help me understand but never got any output from the tests, only panicking and running out of memory

It is very well possible that this PR is treating only a symptom instead of the issue @enj has reported so I would like to keep it [WIP] for a little bit and I am hoping that today I will get some more insight

**Comment by wozniakjan** [comment]
Some progress thanks to @dmage and @legionus. A high volume of events I was seeing on both channels is actually a sign of closed channel and receive operator returns 'nil' events. I suspect that might be a side-effect of @enj's [rate limiting](https://github.com/wozniakjan/origin/blob/bbcd6fe94fd915e4a8d7b4db98ddbc7cfe1a0c4e/test/util/client.go#L275) (the config timeout is 1 minute as well as test timeout for these two watches) which means these watch loops need to be aware of server potentially closing the channel and re-instantiate the watch.

Maybe using [reflector](https://github.com/kubernetes/client-go/blob/e1b1ad35184abf07819079215c7374ade5b576c9/tools/cache/reflector.go#L48) instead of a naked watch?

**Comment by enj** [comment]
Have you tried removing that timeout and also using `x, ok := <-ch` to see if the channel is actually closed?

**Comment by enj** [comment]
OK, let us drop the timeout then (integration tests will still timeout in 5 mins).  Is any change required with no timeout specified?

**Comment by wozniakjan** [comment]
Wouldn't we rather have the tests robust enough to be able to work through a watch timing out? I think using reflector from kube client could help with this

**Comment by enj** [comment]
> Wouldn't we rather have the tests robust enough to be able to work through a watch timing out? I think using reflector from kube client could help with this

All of our tests will fail in some way if the network stops working.  In general we will always have some level of flakiness.

**Comment by wozniakjan** [comment]
> Is any change required with no timeout specified?

not for this test, but `TestIntegration/TestOAuthServiceAccountClientEvent` still appears to be flaky
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19759/test_pull_request_origin_integration/18066/

**Comment by wozniakjan** [comment]
@bparees, @enj I have updated this PR. 
1) commit adds deterministic timeout for the "watch loops" which should make it easier to reason about the time required for the test
2) commit adds a check for closed channels, this should help to discover and understand flakes in the future if anything appears

However, given the cause of https://github.com/openshift/origin/issues/16940 was setting `restclient.Config.Timeout` to one minute and no other flake appears in this test, it is not necessary to merge this, it doesn't fix anything but I think both could be beneficial for future debugging.

**Comment by wozniakjan** [comment]
> However, given the cause of #16940 was setting restclient.Config.Timeout to one minute and no other flake appears in this test,
> 
> where is that being fixed?

Nowhere yet, currently no need for changing it because default timeout is plenty, but should be changed here if this moves forward https://github.com/openshift/origin/pull/16850/commits/85420ea55d71cefd12631d0855cad52ded499c82

**Pull request merged**
