### PR TITLE
UPSTREAM: 29618|drop: Fix kubelet to not accept negative eviction (hard, soft) thresholds

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes bz#1357825

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ncdc

**Comment by ncdc** [comment]
It's not a drop

**Comment by aveshagarwal** [comment]
@ncdc why? as it is already merged in kube, so should be available in next rebase?

**Comment by liggitt** [comment]
I think we'd just wait for this to come in in a rebase...

**Comment by ncdc** [comment]
WFM. Avesh please set the UpcomingRelease keyword on the bz.

**Comment by ncdc** [comment]
Closing since we'll wait for this in the next rebase

**Pull request closed without merging**
