### PR TITLE
Restore graceful shutdown of DNS server

### PR DESCRIPTION
**Pull request by Miciah**
Restore signal handling and graceful shutdown of DNS that had been added in https://github.com/openshift/origin/pull/19987/commits/c802e2226b524a83e3c7ddb0500cbb289fecea8c but was subsequently lost during rebase in https://github.com/openshift/origin/commit/564ee038cff669480ccecd7e999d3f41464b30ff.

Graceful shutdown is necessary to ensure that when OpenShift's DNS server shuts down, we remove it from the dnsmasq configuration.

This commit fixes bug 1624448.

https://bugzilla.redhat.com/show_bug.cgi?id=1624448

@knobunc @ironcladlou @sdodson @smarterclayton

### CODE REVIEW

**Comment by Miciah** [comment]
/retest

Looks like a flake:

    + ssh -F /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install/workspace/.config/origin-ci-tool/inventory/.ssh_config openshiftdevel sudo chmod o+rw /etc/environment
    ++ export status=FAILURE
    ++ status=FAILURE
    + set +o xtrace
    ########## FINISHED STAGE: FAILURE: FORWARD PARAMETERS TO THE REMOTE HOST [00h 00m 00s] ##########

**Comment by Miciah** [comment]
@smarterclayton, cherry picking failed because https://github.com/openshift/origin/pull/20914/commits/2924ec1167688f39b7a088222439c773e96395a3, which renames `pkg/cmd/server/start/start_network.go` to `pkg/cmd/server/start/network/start_network.go`, is in master but not in release-3.11.  We don't want that commit in release-3.11, right?

**Comment by smarterclayton** [comment]
Correct.

On Sep 18, 2018, at 6:21 PM, Miciah Dashiel Butler Masters <
notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton>, cherry picking failed
because 2924ec1
<https://github.com/openshift/origin/commit/2924ec1167688f39b7a088222439c773e96395a3>,
which renames pkg/cmd/server/start/start_network.go to
pkg/cmd/server/start/network/start_network.go, is in master but not in
release-3.11. We don't want that commit in release-3.11, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/21009#issuecomment-422432562>,
or mute
the thread

**Pull request merged**
