### PR TITLE
UPSTREAM: 16717: Ensure HPA has valid resource/name/subresource, validate path segments

### LINKED ISSUE #5675: HPA scaleRef needs validation
Added upstream in https://github.com/kubernetes/kubernetes/pull/16717, need to pull in

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5675, merged upstream

### CODE REVIEW

**Comment by liggitt** [comment]
[test]
@smarterclayton

**Comment by smarterclayton** [comment]
LGTM

**Comment by liggitt** [comment]
flake https://github.com/openshift/origin/issues/5683
[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
