### PR TITLE
UPSTREAM: 64049: Fix race in TestSchedulerWithVolumeBinding to avoid setting predicate ordering.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@sjenning @smarterclayton 

To address: https://openshift-gce-devel.appspot.com//build/origin-ci-test/pr-logs/pull/19720/test_pull_request_origin_unit/13193/

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@sjenning @smarterclayton ping.

**Comment by aveshagarwal** [comment]
@sjenning @smarterclayton any comment?

**Comment by aveshagarwal** [comment]
@smarterclayton @derekwaynecarr could you approve?

**Comment by sjenning** [comment]
we'll get this on the 3.11 rebase

**Pull request closed without merging**
