### PR TITLE
Fix clientset group names

### LINKED ISSUE #14183: shared informers don't compile?
```
# github.com/openshift/origin/pkg/deploy/generated/informers/externalversions/apps/v1
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/externalversions/apps/v1/deploymentconfig.go:32: client.AppsV1 undefined (type clientset.Interface has no field or method AppsV1)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/externalversions/apps/v1/deploymentconfig.go:32: not enough arguments to return
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/externalversions/apps/v1/deploymentconfig.go:35: client.AppsV1 undefined (type clientset.Interface has no field or method AppsV1)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/externalversions/apps/v1/deploymentconfig.go:35: not enough arguments to return
# github.com/openshift/origin/pkg/deploy/generated/informers/internalversion/apps/internalversion
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/internalversion/apps/internalversion/deploymentconfig.go:32: client.Apps undefined (type internalclientset.Interface has no field or method Apps)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/internalversion/apps/internalversion/deploymentconfig.go:32: not enough arguments to return
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/internalversion/apps/internalversion/deploymentconfig.go:35: client.Apps undefined (type internalclientset.Interface has no field or method Apps)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/deploy/generated/informers/internalversion/apps/internalversion/deploymentconfig.go:35: not enough arguments to return
# github.com/openshift/origin/pkg/sdn/generated/informers/externalversions/network/v1
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/externalversions/network/v1/clusternetwork.go:32: client.NetworkV1 undefined (type clientset.Interface has no field or method NetworkV1)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/externalversions/network/v1/clusternetwork.go:32: not enough arguments to return
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/externalversions/network/v1/clusternetwork.go:35: client.NetworkV1 undefined (type clientset.Interface has no field or method NetworkV1)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/externalversions/network/v1/clusternetwork.go:35: not enough arguments to return
# github.com/openshift/origin/pkg/sdn/generated/informers/internalversion/network/internalversion
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/internalversion/network/internalversion/clusternetwork.go:32: client.Network undefined (type internalclientset.Interface has no field or method Network)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/internalversion/network/internalversion/clusternetwork.go:32: not enough arguments to return
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/internalversion/network/internalversion/clusternetwork.go:35: client.Network undefined (type internalclientset.Interface has no field or method Network)
/Users/clayton/projects/origin/src/github.com/openshift/origin/pkg/sdn/generated/informers/internalversion/network/internalversion/clusternetwork.go:35: not enough arguments to return
```

### PR DESCRIPTION
**Pull request by ncdc**
pkg/deploy's API group name is apps.openshift.io, but the previous clientset generation keyed off of the directory name (deploy from pkg/deploy) to determine the group name incorrectly. This fixes that issue (and the same thing for pkg/sdn -> network.openshift.io).

Fixes #14183

@deads2k @liggitt @sttts @smarterclayton @mfojtik

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by deads2k** [comment]
lgtm

**Comment by mfojtik** [comment]
LGTM as well, nice catch.

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
