### PR TITLE
UPSTREAM(go-dockerclient): 408: fix stdin-only attach

### PR DESCRIPTION
**Pull request by ncdc**
Fix bugs related to the initial implementation of upstream PR 408.

Continuation of #5547

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by ncdc** [comment]
```
bower es5-dom-shim#*                            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/termi/ES5-DOM-SHIM.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Connection timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out
```

[test]

**Comment by ncdc** [comment]
Another github timeout. [test]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
