### PR TITLE
Bug 1804843: Useless Test Change

### PR DESCRIPTION
**Pull request by eparis**

### CODE REVIEW

**Comment by eparis** [comment]
I just set the 4.3.z BZ VERIFIED so
/bugzilla refresh

**Comment by eparis** [comment]
The parent bug is now VERIFIED but target release 4.4.0 so
/bugzilla refresh

**Comment by eparis** [comment]
and that just wrong :-(

**Comment by AlexNPavel** [comment]
(Testing a new bugzilla command that was just added)
/bugzilla assign-qa

**Comment by AlexNPavel** [comment]
Looks like it's fixed

**Pull request closed without merging**
