### PR TITLE
Bug 1784837: Poll for Service Catalog basic usage test

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Fix this error:
```console

[Feature:Platform] Service Catalog should check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel] expand_less | 2m27s
-- | --
fail [github.com/openshift/origin/test/extended/operators/service_catalog.go:127]: Unexpected error:     <*util.ExitError \| 0xc003c2ca20>: {         Cmd: "oc --namespace=e2e-test-service-catalog-w8766 --config=/tmp/admin.kubeconfig create -f /tmp/e2e-test-service-catalog-w8766-config.json",         StdErr: "unable to recognize no matches for kind \"ClusterServiceBroker\" in version \"servicecatalog.k8s.io/v1beta1\"",         ExitError: {             ProcessState: {

...
```
Details in: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23186/pull-ci-openshift-origin-master-e2e-aws-fips/509

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@shawn-hurley Could you help add the `approve` label? thanks!
@jmrodri Could you help add the `lgtm` label? Thanks!

**Comment by jianzhangbjz** [comment]
Running logs in my local
```console
mac:origin jianzhang$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0-0.nightly-2019-12-15-230238   True        False         114m    Cluster version is 4.2.0-0.nightly-2019-12-15-230238
mac:openshift-tests jianzhang$ ./openshift-tests run all --dry-run | grep "\[Feature:Platform\] Service Catalog should" | ./openshift-tests run --junit-dir=./ -f -
started: (0/1/1) "[Feature:Platform] Service Catalog should check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel]"

I1216 18:24:19.408538   22476 trace.go:116] Trace[1993268772]: "Reflector ListAndWatch" name:github.com/openshift/origin/pkg/monitor/operator.go:279 (started: 2019-12-16 18:24:07.879945 +0800 CST m=+26.629385943) (total time: 11.528103862s):
Trace[1993268772]: [11.52799751s] [11.52799751s] Objects listed
I1216 18:24:19.408956   22476 trace.go:116] Trace[1699762754]: "Reflector ListAndWatch" name:github.com/openshift/origin/pkg/monitor/node.go:96 (started: 2019-12-16 18:24:07.879673 +0800 CST m=+26.629113762) (total time: 11.529154745s):
Trace[1699762754]: [11.529098041s] [11.529098041s] Objects listed
I1216 18:24:50.104549   22476 trace.go:116] Trace[721886400]: "Reflector ListAndWatch" name:github.com/openshift/origin/pkg/monitor/operator.go:126 (started: 2019-12-16 18:24:07.879684 +0800 CST m=+26.629125090) (total time: 42.224503577s):
Trace[721886400]: [42.224392178s] [42.224392178s] Objects listed
Dec 16 18:24:20.710: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Dec 16 18:24:23.897: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Dec 16 18:24:24.718: INFO: 0 / 0 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Dec 16 18:24:24.718: INFO: expected 0 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Dec 16 18:24:24.718: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
Dec 16 18:24:24.999: INFO: e2e test version: v0.0.0-master+$Format:%h$
Dec 16 18:24:25.275: INFO: kube-apiserver version: v1.14.6+59395b3
Dec 16 18:24:25.573: INFO: Cluster IP family: ipv4
[BeforeEach] [Top Level]
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/util/test.go:60
[BeforeEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:151
STEP: Creating a kubernetes client
[BeforeEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/util/client.go:109
Dec 16 18:24:28.102: INFO: configPath is now "/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/configfile834331652"
Dec 16 18:24:28.102: INFO: The user is now "e2e-test-service-catalog-7cflk-user"
Dec 16 18:24:28.102: INFO: Creating project "e2e-test-service-catalog-7cflk"
Dec 16 18:24:29.528: INFO: Waiting on permissions in project "e2e-test-service-catalog-7cflk" ...
Dec 16 18:24:29.786: INFO: Waiting for ServiceAccount "default" to be provisioned...
Dec 16 18:24:30.182: INFO: Waiting for ServiceAccount "deployer" to be provisioned...
Dec 16 18:24:30.547: INFO: Waiting for ServiceAccount "builder" to be provisioned...
Dec 16 18:24:30.999: INFO: Waiting for RoleBinding "system:image-pullers" to be provisioned...
Dec 16 18:24:31.563: INFO: Waiting for RoleBinding "system:image-builders" to be provisioned...
Dec 16 18:24:32.077: INFO: Waiting for RoleBinding "system:deployers" to be provisioned...
Dec 16 18:24:33.407: INFO: Project "e2e-test-service-catalog-7cflk" has been fully provisioned.
[BeforeEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/operators/service_catalog.go:40
STEP: Enable Service Catalog
Dec 16 18:24:33.407: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch servicecatalogapiserver cluster -p {"spec":{"managementState":"Managed"}} --type=merge'
Dec 16 18:24:38.325: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-apiserver -o=jsonpath={.items[0].status.phase}'
Dec 16 18:24:41.323: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-apiserver -o=jsonpath={.items[0].status.phase}'
Dec 16 18:24:47.325: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-apiserver -o=jsonpath={.items[0].status.phase}'
Dec 16 18:24:48.844: INFO: servicecatalogapiserver works well!
Dec 16 18:24:48.844: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch servicecatalogcontrollermanager cluster -p {"spec":{"managementState":"Managed"}} --type=merge'
Dec 16 18:24:53.945: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:24:59.946: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:25:02.947: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:25:05.947: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:25:08.948: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:25:14.942: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get pods -n openshift-service-catalog-controller-manager -o=jsonpath={.items[0].status.phase}'
Dec 16 18:25:16.605: INFO: servicecatalogcontrollermanager works well!
[It] check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel]
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/operators/service_catalog.go:104
STEP: Check Service Catalog apiservice
Dec 16 18:25:19.606: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get apiservices v1beta1.servicecatalog.k8s.io -o=jsonpath={.status.conditions[0].reason}'
Dec 16 18:25:20.910: INFO: v1beta1.servicecatalog.k8s.io apiservice works well!
STEP: Deploy a fake broker
Dec 16 18:25:20.910: INFO: current namespace:e2e-test-service-catalog-7cflk
Dec 16 18:25:20.910: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig process -f /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-deployment.yaml -p NAMESPACE=e2e-test-service-catalog-7cflk'
Dec 16 18:25:25.177: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig create -f /tmp/e2e-test-service-catalog-7cflk-config.json'
deployment.extensions/ups-broker created
Dec 16 18:25:26.411: INFO: Install:/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-deployment.yaml successfully
Dec 16 18:25:26.411: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig process -f /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-service.yaml -p NAMESPACE=e2e-test-service-catalog-7cflk'
Dec 16 18:25:30.839: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig create -f /tmp/e2e-test-service-catalog-7cflk-config.json'
service/ups-broker created
Dec 16 18:25:32.258: INFO: Install:/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-service.yaml successfully
Dec 16 18:25:32.258: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig process -f /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-broker.yaml -p NAMESPACE=e2e-test-service-catalog-7cflk'
Dec 16 18:25:36.572: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig create -f /tmp/e2e-test-service-catalog-7cflk-config.json'
clusterservicebroker.servicecatalog.k8s.io/ups-broker created
Dec 16 18:25:53.948: INFO: Install:/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-broker.yaml successfully
Dec 16 18:25:56.954: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get clusterservicebroker ups-broker -o=jsonpath={.status.conditions[0].status}'
STEP: create {/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-instance.yaml serviceinstance ups-instance ProvisionedSuccessfully}
Dec 16 18:25:58.713: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig process -f /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-instance.yaml -p NAMESPACE=e2e-test-service-catalog-7cflk'
Dec 16 18:26:04.784: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig create -f /tmp/e2e-test-service-catalog-7cflk-config.json'
serviceinstance.servicecatalog.k8s.io/ups-instance created
Dec 16 18:26:05.997: INFO: Install:/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-instance.yaml successfully
Dec 16 18:26:08.999: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get serviceinstance -n e2e-test-service-catalog-7cflk ups-instance -o=jsonpath={.status.conditions[0].reason}'
STEP: create {/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-binding.yaml servicebinding ups-binding InjectedBindResult}
Dec 16 18:26:10.295: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig process -f /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-binding.yaml -p NAMESPACE=e2e-test-service-catalog-7cflk'
Dec 16 18:26:14.667: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig create -f /tmp/e2e-test-service-catalog-7cflk-config.json'
servicebinding.servicecatalog.k8s.io/ups-binding created
Dec 16 18:26:15.894: INFO: Install:/var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/fixture-testdata-dir670804217/test/extended/testdata/service_catalog/ups-binding.yaml successfully
Dec 16 18:26:18.896: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get servicebinding -n e2e-test-service-catalog-7cflk ups-binding -o=jsonpath={.status.conditions[0].reason}'
Dec 16 18:26:20.163: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get secret -n e2e-test-service-catalog-7cflk'
STEP: unbind from this instance
Dec 16 18:26:21.807: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig delete servicebinding -n e2e-test-service-catalog-7cflk ups-binding'
Dec 16 18:26:26.721: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get servicebinding -n e2e-test-service-catalog-7cflk'
Dec 16 18:26:31.843: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get secret -n e2e-test-service-catalog-7cflk'
STEP: delete this ups instance
Dec 16 18:26:33.390: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig delete serviceinstance -n e2e-test-service-catalog-7cflk ups-instance'
Dec 16 18:26:39.880: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get serviceinstance -n e2e-test-service-catalog-7cflk'
STEP: set Service Catalog to Unmanaged
Dec 16 18:26:42.595: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch servicecatalogapiserver cluster -p {"spec":{"managementState":"Unmanaged"}} --type=merge'
Dec 16 18:26:47.228: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get servicecatalogapiserver -n openshift-service-catalog-apiserver cluster -o=jsonpath={.spec.managementState}'
Dec 16 18:26:49.873: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch daemonset apiserver -n openshift-service-catalog-apiserver -p {"spec":{"template":{"spec":{"priorityClassName":"test"}}}}'
Dec 16 18:26:54.401: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get daemonset apiserver -n openshift-service-catalog-apiserver -o=jsonpath={.spec.template.spec.priorityClassName}'
Dec 16 18:26:57.145: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch servicecatalogcontrollermanager cluster -p {"spec":{"managementState":"Unmanaged"}} --type=merge'
Dec 16 18:27:04.800: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get servicecatalogcontrollermanager -n openshift-service-catalog-controller-manager cluster -o=jsonpath={.spec.managementState}'
Dec 16 18:27:06.107: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig patch daemonset controller-manager -n openshift-service-catalog-controller-manager -p {"spec":{"template":{"spec":{"priorityClassName":"test"}}}}'
Dec 16 18:27:10.681: INFO: Running 'oc --namespace=e2e-test-service-catalog-7cflk --config=/Users/jianzhang/42-kueconfig get daemonset controller-manager -n openshift-service-catalog-controller-manager -o=jsonpath={.spec.template.spec.priorityClassName}'
[AfterEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/util/client.go:101
Dec 16 18:27:13.346: INFO: Deleted {user.openshift.io/v1, Resource=users  e2e-test-service-catalog-7cflk-user}, err: <nil>
Dec 16 18:27:13.618: INFO: Deleted {oauth.openshift.io/v1, Resource=oauthclients  e2e-client-e2e-test-service-catalog-7cflk}, err: <nil>
Dec 16 18:27:13.917: INFO: Deleted {oauth.openshift.io/v1, Resource=oauthaccesstokens  MABoI5fHQ8ClfGB4saX5WwAAAAAAAAAA}, err: <nil>
[AfterEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:152
Dec 16 18:27:13.917: INFO: Waiting up to 7m0s for all (but 100) nodes to be ready
STEP: Destroying namespace "e2e-test-service-catalog-7cflk" for this suite.
[AfterEach] [Feature:Platform] Service Catalog should
  /Users/jianzhang/goproject/src/github.com/openshift/origin/test/extended/operators/service_catalog.go:67
STEP: delete this ups broker
Dec 16 18:27:16.289: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get clusterservicebroker'
Dec 16 18:27:17.565: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig delete clusterservicebroker ups-broker'
Dec 16 18:27:31.159: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get clusterserviceclass'
STEP: disable servicecatalogapiserver
Dec 16 18:27:33.736: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig patch servicecatalogapiserver cluster -p {"spec":{"managementState":"Removed"}} --type=merge'
Dec 16 18:27:38.839: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:41.842: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:44.842: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:50.838: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:53.841: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:56.840: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver'
Dec 16 18:27:58.054: INFO: Error running /usr/local/bin/oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-apiserver:
Error from server (NotFound): namespaces "openshift-service-catalog-apiserver" not found
Dec 16 18:27:58.054: INFO: Disable servicecatalogapiserver successfully.
STEP: disable servicecatalogcontrollermanager
Dec 16 18:27:58.055: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig patch servicecatalogcontrollermanager cluster -p {"spec":{"managementState":"Removed"}} --type=merge'
Dec 16 18:28:02.606: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:05.611: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:08.606: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:11.611: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:14.611: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:17.608: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:20.610: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:23.610: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:26.606: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:29.609: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:32.606: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:35.607: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:38.611: INFO: Running 'oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager'
Dec 16 18:28:41.203: INFO: Error running /usr/local/bin/oc --namespace= --config=/Users/jianzhang/42-kueconfig get ns openshift-service-catalog-controller-manager:
Error from server (NotFound): namespaces "openshift-service-catalog-controller-manager" not found
Dec 16 18:28:41.203: INFO: Disable servicecatalogcontrollermanager successfully.
Dec 16 18:28:41.210: INFO: Running AfterSuite actions on all nodes
Dec 16 18:28:41.210: INFO: Running AfterSuite actions on node 1

passed: (4m33s) 2019-12-16T10:28:41 "[Feature:Platform] Service Catalog should check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel]"

```

**Comment by shawn-hurley** [comment]
I am concerned that this is failing consistently on GCP in what appears to be the same way. Can we make sure that the failure is something other than this change and is a flake

**Comment by jianzhangbjz** [comment]
@shawn-hurley I'm not sure why these tests always failed on GCP. But, I'm sure that this PR will fix the failure of the Service Catalog. Could you help give approval? Thanks!
image

**Comment by shawn-hurley** [comment]
I am happy to approve once we understand the implications of adding it. It seems to me that we are 100% fixing the service catalog test, but I am worried that we are somehow introducing a failure, Those same tests have failed pretty consistently, so I would like to see if those are known flakes and have bugs open for them OR if we are introducing them somehow.

**Comment by shawn-hurley** [comment]
/approve cancel
/hold 

We need to rethink this test see: 
https://github.com/openshift/origin/pull/24315

**Comment by wking** [comment]
/retitle Bug 1784837: Poll for Service Catalog basic usage test

**Comment by jianzhangbjz** [comment]
No ServiceCatalog supports for 4.5, colse it.

**Pull request closed without merging**
