### PR TITLE
[DO_NOT_MERGE] hardcode OS_BUILD_ENV_TMP_VOLUME to chase the etcd timeouts

### PR DESCRIPTION
**Pull request by mfojtik**
Just to exercise the tests.

### CODE REVIEW

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/ 3070-3079 and https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/ 7941-7950

**Comment by mfojtik** [comment]
first one passed \o/

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/14385

/test extended_networking_minimal

**Comment by deads2k** [comment]
10 out of 10 for integration.

**Comment by deads2k** [comment]
8 out of 10 for test-cmd, looks like docker hub flakes (different failure mode, not etcd timeout) for the failing two.  Looks like we found it.

**Pull request closed without merging**
