### PR TITLE
Revert "Reapply "OCPBUGS-18865: Reapply "Merge pull request #28944 from vrutkovs/in-cluster-fixes-v4"""

### PR DESCRIPTION
**Pull request by neisw**
Reverts openshift/origin#29058

[4.18.0-0.nightly-2024-11-10-205924](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.18.0-0.nightly/release/4.18.0-0.nightly-2024-11-10-205924) has overall-analysis failure related to techpreview-serial failures (excludes aws).  2 of the failures [azure](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial/1855718150620844032) and [gcp](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview-serial/1855718083503591424) are kube-api-http1/2 endpoint related.

Staging now, will hold for review.

`/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial `
`/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview-serial`

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview-serial

**Comment by vrutkovs** [comment]
/hold cancel
/lgtm

Seems there is an OVN bug for gcp/azure (it even crashes in payload-job rehearsal)

**Comment by neisw** [comment]
Thanks @vrutkovs.  I saw those failures in the payload-job runs covering azure ovn minor upgrade but seemed like sippy showed them outside this PR as well so I didn't hold it but thanks for recognizing it.

We should be able to verify with `/payload-aggregate periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-azure-ovn-upgrade 10`

**Comment by vrutkovs** [comment]
Re-apply: https://github.com/openshift/origin/pull/29282

**Pull request merged**
