### PR TITLE
Hide storage-admin role by default

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by abhgupta** [comment]
Partial fix for https://bugzilla.redhat.com/show_bug.cgi?id=1437302

**Comment by liggitt** [comment]
[test]

**Comment by abhgupta** [comment]
LGTM

**Comment by enj** [comment]
LGTM

cc @jwforres @benjaminapetersen FYI

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
