### PR TITLE
run jenkins java builds in memory constrained pods

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
/hold
(until image ecosystem tests pass)

**Comment by bparees** [comment]
/lgtm
/hold cancel
(image eco failure was not related to pipelines/jenkins)

**Comment by bparees** [comment]
/hold
/test extended_builds
looks like it's the builds test that exercises the pipeline?

**Comment by bparees** [comment]
(feel free to remove the hold once the builds test passes)

**Comment by jim-minter** [comment]
@bparees @gabemontero this adds an additional gradle build test case which will pass once https://github.com/openshift/jenkins/pull/442 is merged and a new centos image is pushed.

**Comment by bparees** [comment]
/lgtm
/retest
(remove the hold when you're happy it's passing)

**Comment by bparees** [comment]
(syntax for unholding is "/hold cancel")

**Comment by bparees** [comment]
extended builds passed.

/hold cancel

**Pull request merged**
