### PR TITLE
Don't monitor image-registry disruption when replicas == 1

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-1347](https://issues.redhat.com//browse/TRT-1347)

Metal and  other on-prem platforms don't have HA storage available, so image-registry runs with a single replica.  High disruption is expected when it's not running HA, so let's disable the monitor test whenever we encounter this.

### CODE REVIEW

**Comment by dgoodwin** [comment]
The code looks fine, I just wanted to check that image registry does not report 0 in the backend-disruption.json file, it should be omitted entirely, but doesn't look like we've got a clean metal run yet, so I'll lgtm, and hold and feel free to cancel if you can confirm we don't report 0s. I don't *think* we will but these things have a way of surprising me.

/lgtm
/hold

**Comment by stbenjam** [comment]
@dgoodwin https://github.com/openshift/origin/pull/28425 was the alternative I mentioned in stand-up, I think that's the one I prefer if it passes tests.  WDYT?

**Comment by stbenjam** [comment]
Closed in favor of https://github.com/openshift/origin/pull/28425

**Pull request closed without merging**
