### PR TITLE
[WIP] Deployment conditions

### PR DESCRIPTION
**Pull request by kargakis**
Trello card: https://trello.com/c/OIggCmzo/699-5-deployments-downstream-conditions

@mfojtik this aligns Conditions with our Phases - we can follow-up with another pull that adds all the replica failures found in replication controllers.

@openshift/api-review for the api changes - we can wait for the resolution of perma-failed upstream before moving forward with this but I don't think there is any disagreement over deployment conditions in general.

Still needs some tests and to ensure phases won't overwrite pause/resume when appropriate but the general idea is here.

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by smarterclayton** [comment]
API approved.  Expectation is that we may change the constants on conditions if the upstream design diverges, but Conditions as is are fine.

**Comment by mfojtik** [comment]
[(5) Deployments: DOWNSTREAM conditions](https://trello.com/c/OIggCmzo/699-5-deployments-downstream-conditions)

**Comment by kargakis** [comment]
Closing in favor of https://github.com/openshift/origin/pull/9874

**Pull request closed without merging**
