### PR TITLE
Fix asset build so that it leaves the dev environment in place without having to re-launch grunt serve

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett @benjaminapetersen thoughts?  This has been really bugging me now that I've switched to primarily testing in Chrome.

**Comment by spadgett** [comment]
awesome, LGTM

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
@jwforres yay!

**Pull request merged**
