### PR TITLE
fix deploy test to use actual master

### PR DESCRIPTION
**Pull request by deads2k**
Updates the deploy tests to use an actual master. This one is slightly more involved.

@liggitt @kargakis

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by kargakis** [comment]
LGTM on green

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
hadn't seen this before: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8142/consoleText

```
2016/01/4 11:16:31 etcdserver: saved snapshot at index 10001
2016/01/4 11:16:31 etcdserver: compacted raft log at 5001
2016/01/4 11:19:07 wal: segmented wal file /tmp/openshift-integration/etcd/member/wal/0000000000000001-0000000000002a4f.wal is created

```

**Comment by liggitt** [comment]
I think the relevant line is `2016/01/4 11:10:55 etcdhttp: got unexpected response error (etcdserver: request timed out)`, which we have seen before

**Pull request merged**
