### PR TITLE
OCPVE-383: feat: added the early and late upgrade suite tests for RT kernel

### PR DESCRIPTION
**Pull request by jeff-roche**
This PR aims to add early and late tests for RT kernel testing during upgrade cycles. The goal is to validate the RT kernel is working as expected before and after upgrading Openshift.

### CODE REVIEW

**Comment by eggfoobar** [comment]
/lgtm

/cc @DennisPeriquet 

Hey @DennisPeriquet, does this look good for our initial talk on running tests before and after upgrade?

**Comment by DennisPeriquet** [comment]
it looks good.

I'd like to try some jobs that run in the 4.14 nightly/ci payloads.  Which one(s) is(are) good candidate(s)?

**Comment by DennisPeriquet** [comment]
> it looks good.
> 
> I'd like to try some jobs that run in the 4.14 nightly/ci payloads. Which one(s) is(are) good candidate(s)?

Thinking about this ... I need those tests before we can run /payload to test them -- so this is not relevant.  I'd like to understand how the this affects the cluster under test -- when the early part of the test runs, will it affect the cluster such that other tests may fail?

The only thing I can thi

**Comment by DennisPeriquet** [comment]
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by jeff-roche** [comment]
> > it looks good.
> > I'd like to try some jobs that run in the 4.14 nightly/ci payloads. Which one(s) is(are) good candidate(s)?
> 
> Thinking about this ... I need those tests before we can run /payload to test them -- so this is not relevant. I'd like to understand how the this affects the cluster under test -- when the early part of the test runs, will it affect the cluster such that other tests may fail?

Relevant tests for a successful skip: `ci/prow/e2e-gcp-ovn-upgrade`
Relevant tests for a successful run: `ci/prow/e2e-gcp-ovn-rt-upgrade`

To answer your questions about the effect this has on the cluster: We intentionally added the disruptive tag because any other tests running at the same time would be effected by lack of cpu. In terms of the state the cluster is left in after tests, there are no changes made to the cluster configuration so these tests shouldn't have an effect on other tests. This just hit the CPU with some basic tests to validate cpu latency. These invocations of the tests don't actually test what that latency is, just that the tools can run

**Comment by DennisPeriquet** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by DennisPeriquet** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by DennisPeriquet** [comment]
Trying the `/payload-job` again since the [first one](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-28027-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/1678443289885282304) didn't even finish the initial installation.

**Comment by DennisPeriquet** [comment]
The [job on the second attempt](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-28027-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/1678750578244587520) ran all the way through this time and your tests look like they ran.  Does this test have anything to do with your changes?

```
: [sig-arch][Late] operators should not create watch channels very often [apigroup:apiserver.openshift.io] [Suite:openshift/conformance/parallel] expand_less
--
Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 4s | {  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 4s | {  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_less | 4s
{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
```

Also,that job took 4h19m (which seems long), [other runs of that job](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.14/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade%22%7D%5D%7D&sortField=timestamp&sort=desc) seem to take ~3h45m or so.

**Comment by jeff-roche** [comment]
> The [job on the second attempt](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-28027-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/1678750578244587520) ran all the way through this time and your tests look like they ran. Does this test have anything to do with your changes?
> 
> ```
> : [sig-arch][Late] operators should not create watch channels very often [apigroup:apiserver.openshift.io] [Suite:openshift/conformance/parallel] expand_less
> --
> Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 4s | {  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
> Run #0: Failed expand_less4s{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 4s | {  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
> Run #0: Failed expand_less | 4s
> {  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"cloud-credential-operator\" produces more watch requests than expected: watchrequestcount=104, upperbound=96, ratio=1.08",     ] to be empty Ginkgo exit error 1: exit with code 1}
> ```
> 
> Also,that job took 4h19m (which seems long), [other runs of that job](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.14/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade%22%7D%5D%7D&sortField=timestamp&sort=desc) seem to take ~3h45m or so.

Those failing jobs don't have to do with us. 

The length addition is due to the fact that we added 3 tests that are about 10 minutes each

**Comment by DennisPeriquet** [comment]
This seems like a very long time -- that's 30 min added to each job that runs this.  Is there anything you can do to make it a bit shorter?

**Comment by jeff-roche** [comment]
> This seems like a very long time -- that's 30 min added to each job that runs this. Is there anything you can do to make it a bit shorter?

@DennisPeriquet the additional 30 minutes is only added to E2E upgrade jobs that are running Kernel RT under the hood. As far as I have found this will only have a tangible effect on `ci/prow/e2e-gcp-ovn-rt-upgrade`. All other E2E upgrade jobs will have an immediate skip for these tests have next to zero time impact since the first thing these tests do is check for the RT kernel and skip if it is not detected.

**Comment by DennisPeriquet** [comment]
@jeff-roche The job runs that make up the [aggregated-gcp-ovn-rt-upgrade-4.14-minor](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-ovn-rt-upgrade-4.14-minor-release-openshift-release-analysis-aggregator/1678696415565451264) on the 4.14 nightly stream are already the longest coming in at about 3.75h when they pass; this will slow our nightly payloads down.

Two ideas our team suggested:

1) is it possible to run these tests in a non-upgrade job? these jobs tend to be shorter
2) how about making it a separate job?

Also, does it have to be one of the jobs for our payload streams?

**Comment by jeff-roche** [comment]
This work has shifted to https://github.com/openshift/release/pull/41293

**Pull request closed without merging**
