### PR TITLE
deploy: drop paused conditions

### PR DESCRIPTION
**Pull request by kargakis**
Paused conditions are not so useful with the current state of pausing
in deployment configs. If we ever start pausing the deployer container
then it may make sense to surface a paused condition in the deployment
status. For now since we don't pause rollouts, we can depend on our
cli tooling to let users know that their deployment configs are paused.

Fixes https://github.com/openshift/origin/issues/11656

@mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
Does the web console not use them?

**Comment by kargakis** [comment]
> Does the web console not use them?

I don't think so. @jwforres ?

**Comment by mfojtik** [comment]
[test]

**Comment by jwforres** [comment]
@spadgett what are you using to detect paused state

**Comment by kargakis** [comment]
@jwforres @spadgett for now (and probably the best way) I would suggest checking that dc.generation == dc.status.generation and dc.spec.paused=true.

**Comment by spadgett** [comment]
Right now we only check `dc.spec.paused`

**Comment by mfojtik** [comment]
@liggitt @kargakis so I assume this is safe to merge for 1.4 as it fixes the hot loop (and some of our BZ bugs apparently).

**Comment by kargakis** [comment]
@mfojtik if it would be just "safe", it shouldn't be enough to merge it at this point.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
