### PR TITLE
pin openshift group name mappings when referencing from openshift groups

### PR DESCRIPTION
**Pull request by deads2k**
This allows us to properly update the openshift groups without creating new groups or updating the incorrect mappings.

@stevekuznetsov  includes https://github.com/openshift/origin/pull/5104

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Small nit on bash test, otherwise LGTM

**Comment by deads2k** [comment]
> OpenShift is not a valid group UID source for this sync job ? Not really sure, this is difficult to parse

It's message for a pathological, unreachable state

**Comment by stevekuznetsov** [comment]
@deads2k That is also true.

**Comment by deads2k** [comment]
steve's commit lgtm

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
