### PR TITLE
Bug 1766365: TestNamespaceCondition integration test fails

### PR DESCRIPTION
**Pull request by p0lyn0mial**
this pull deprecates https://github.com/openshift/origin/pull/23830

### CODE REVIEW

**Comment by eparis** [comment]
are we still working on this? I'm don't understand how https://github.com/openshift/origin/pull/23830 and this relate.

**Comment by p0lyn0mial** [comment]
> are we still working on this? I'm don't understand how #23830 and this relate.

I think it is worth taking as this pull fixes an integration test. The previous pull #23830 had targeted `master` which became `4.3` and already has the fix.

**Comment by p0lyn0mial** [comment]
@eparis please tag the pull.

**Comment by crawford** [comment]
I don't see where this change has first been verified against 4.3. Can you update the BZ with its parent (targeted against 4.3)?

**Comment by derekwaynecarr** [comment]
the test had already merged upstream.

**Pull request merged**
