### PR TITLE
[release-3.10] Bug 1696394: Set reasonable DNSIP consistent with kubelet

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/sig-network-edge @knobunc PTAL

**Comment by pravisankar** [comment]
Similar to https://github.com/openshift/origin/pull/22485 except some conflicts/changes in pkg/cmd/server/start/bootstrap_node.go
@ironcladlou @Miciah @knobunc  PTAL

**Comment by pravisankar** [comment]
Test failure not related to this pr:
```
[INFO] [22:39:13+0000] No compiled `commitchecker` binary was found. Attempting to build one using:
[INFO] [22:39:13+0000]   $ hack/build-go.sh tools/rebasehelpers/commitchecker
/home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 129: OS_GIT_MAJOR: unbound variable
[INFO] [22:39:14+0000] 		Stack Trace: 
[INFO] [22:39:14+0000] 		  1: hack/lib/constants.sh:129: `ldflags+=($(os::build::ldflag "${OS_GO_PACKAGE}/pkg/version.majorFromGit" "${OS_GIT_MAJOR}"))`
[INFO] [22:39:14+0000] 		  2: hack/lib/build/binaries.sh:172: os::build::ldflags
[INFO] [22:39:14+0000] 		  3: hack/lib/build/binaries.sh:156: os::build::internal::build_binaries
[INFO] [22:39:14+0000] 		  4: hack/build-go.sh:25: os::build::build_binaries
[INFO] [22:39:14+0000]   Exiting with code 1.
```
/override continuous-integration/travis-ci/pr

**Comment by pravisankar** [comment]
Build failure not related to this pr.
```
[INFO] [07:27:03+0000]   $ hack/build-go.sh tools/rebasehelpers/commitchecker
/home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 129: OS_GIT_MAJOR: unbound variable
[ERROR] [07:27:07+0000] PID 4454: hack/lib/constants.sh:129: `ldflags+=($(os::build::ldflag "${OS_GO_PACKAGE}/pkg/version.majorFromGit" "${OS_GIT_MAJOR}"))` exited with status 1.
```
@stevekuznetsov @sdodson  I see that previous commits on release-3.10 branch are merged with '/override continuous-integration/travis-ci/pr' tag, can you add this tag to this pr or let me know what's needed to merge this pr?

**Comment by sdodson** [comment]
/hold
CI is looping on retests, clear this once the travis-ci status is green or overridden.

The last time I overrode that status it resulted in problems and I'm not familiar with those failures so I don't feel comfortable overriding it. I suggest asking @knobunc

**Comment by sdodson** [comment]
Overridden on behalf of @knobunc

**Pull request merged**
