### PR TITLE
Enable gzip compression

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by deads2k** [comment]
if you're ready, I'm ready.

/lgtm

**Comment by liggitt** [comment]
yup, all set

**Comment by mfojtik** [comment]
(the failures seems to be related to getting logs from failed hook pods, which is related to journald i believe).

**Comment by liggitt** [comment]
> (the failures seems to be related to getting logs from failed hook pods, which is related to journald i believe).

hmm... that's slightly suspicious... there was an issue upstream about streaming logs with this feature enabled

https://github.com/kubernetes/kubernetes/issues/54205#issuecomment-346176210
https://github.com/kubernetes/kubernetes/pull/51508#issuecomment-346473687

**Comment by liggitt** [comment]
/hold

yeah... all five runs failed with that logs error

I don't see that logs error occur on job failures on other PRs

@ilackarms FYI, enabling compression seems to break another logs case

**Comment by derekwaynecarr** [comment]
moved this out of the 3.9 milestone, hold this PR until kube 1.10.

**Pull request closed without merging**
