### PR TITLE
Clean up the root folder

### PR DESCRIPTION
**Pull request by smarterclayton**
Move any directory or file that is not strictly required for core code maintenance into contrib/

@sdodson @rajatchopra @maxamillion your names are on recent committer lists to these directories - I need to go make sure relative directories are preserved, and I suspect some tweaks will be required to the rpms (which I'll go do), but at least FYI for now.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Also fyi @brenton @detiber

**Comment by smarterclayton** [comment]
[test]

**Comment by brenton** [comment]
@dgoodwin, can you checkout this PR and give a recommendation on how tito would be happy?  The short of it is the `./rel-eng` dir is moving under `./contrib` and the spec file was moved to `./contrib/rpm`.

~~~~
git checkout -b smarterclayton-use_contrib master
git pull https://github.com/smarterclayton/origin.git use_contrib
~~~~

@smarterclayton, is this just for aesthetic releases or people getting confused in some way?  I think tito assumes a certain directory structure but devan will definitely know how tito can handle this.  Maybe we could use a hidden `./.rel-eng` directory or configuration file.  Ultimate tito needs to know where to find it's configuration file and it's typically in the root of the git repo.   From there I think it assumes the source you want to bundle is in the same directory as the spec file.

@sdodson, you'll probably want to follow this too.

**Comment by sdodson** [comment]
I'll wait for Devan to suggest how to keep tito happy. Once we figure that out I'm happy to fix-up the specfile as needed.

**Comment by dgoodwin** [comment]
Yeah unfortunately will break tito.

The spec move to contrib/rpm/origin.spec is the first issue, that's required to be at the git root for the package being built today. There are PR's out to change that but none can be merged yet, it's a little tricky as tito supports multi-project git repos, so we need metadata about what package lives where in the tree so we can export *just* the sub-tree for that source when doing builds. Today that is defined as where the spec file lives, in a single project repo that would mean the root of the git repo. This one is probably solvable in tito given some time.

The move of rel-eng/ to contrib is the second issue, tito configuration is assumed to be at  rel-eng/tito.props but as of 0.6.0, you can use .tito instead, which would get it a little more out of the way. Bit of a chicken and egg situation here, we can't really configure where the configuration lives. I'm not sure if we can work past that, we could search for it on every execution but that's going to be a bit slow. Probably best if we have some defined location(s) to check for config. I would suggest use of .tito for this one.

Is origin actually using tito? Do we need to push all tito config to downstream repos?

**Comment by smarterclayton** [comment]
@brenton we don't have to rapidly change this, but this is trying to get
the repo in a more presentable state to outsiders.  .tito would be fine, as
well as Devan's question about whether it has to be in the repo.

Is there an issue with the spec file moving?  This is my ideal structure,
but if it causes significant work we can delay some of it.

On Mon, Sep 14, 2015 at 9:16 AM, Devan Goodwin <notifications@github.com>
wrote:

> Yeah unfortunately will break tito.
>
> The spec move to contrib/rpm/origin.spec is the first issue, that's
> required to be at the git root for the package being built today. There are
> PR's out to change that but none can be merged yet, it's a little tricky as
> tito supports multi-project git repos, so we need metadata about what
> package lives where in the tree so we can export *just* the sub-tree for
> that source when doing builds. Today that is defined as where the spec file
> lives, in a single project repo that would mean the root of the git repo.
> This one is probably solvable in tito given some time.
>
> The move of rel-eng/ to contrib is the second issue, tito configuration is
> assumed to be at rel-eng/tito.props but as of 0.6.0, you can use .tito
> instead, which would get it a little more out of the way. Bit of a chicken
> and egg situation here, we can't really configure where the configuration
> lives. I'm not sure if we can work past that, we could search for it on
> every execution but that's going to be a bit slow. Probably best if we have
> some defined location(s) to check for config. I would suggest use of .tito
> for this one.
>
> Is origin actually using tito? Do we need to push all tito config to
> downstream repos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4655#issuecomment-140071297>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by dgoodwin** [comment]
You can move rel-eng to .tito today and that should be fine, assuming we update for the non-tito files in there (looks like just bash completions and some files the spec uses)

I'd suggest keeping the spec file at / for now, and I can work to try to find a way around that in a future tito release. I think we might be developing a need for a more verbose configuration of what projects live where in the source tree, which would allow us to also specify where exactly their spec file lives.

**Comment by sdodson** [comment]
> Is origin actually using tito? Do we need to push all tito config to downstream repos?

It's used to build SRPMs that are submitted to a [COPR](https://copr.fedoraproject.org/coprs/maxamillion/origin-next), though we should probably update that to actually use the COPR releaser.

**Comment by brenton** [comment]
The other useful part of having the specfile upstream is that we get to have these conversations earlier in the dev cycle instead of it being a surprise when refactorings like this are needed.  :)

It would be nice if tito could support configuring the link between a specfile and the source arbitrarily in configuration.  Alternatively, if the dirs didn't change on us all the time we could probably get away with symlinking the needful in to `.contrib/rpm` to make tito happy.

**Comment by sdodson** [comment]
@smarterclayton 

Now that we have a crontib directory would you be ok with including more items from third party repos and asking those crontibutors to submit pull requests against origin for updates? Right now we distribute imagestreams and templates from several other repos via the ansible module, it's sort of a mess. I'd prefer seeing them in the contrib directory of this repo rather than collating them in openshift-ansible, this would also allow us to ensure that content is updated when users update origin/aos.

See https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/examples-sync.sh#L12-L18 for the list of places we're pulling content from

**Comment by smarterclayton** [comment]
Yes

On Mon, Sep 14, 2015 at 10:35 AM, Scott Dodson <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton>
>
> Now that we have a crontib directory would you be ok with including more
> items from third party repos and asking those crontibutors to submit pull
> requests against origin for updates? Right now we distribute imagestreams
> and templates from several other repos via the ansible module, it's sort of
> a mess. I'd prefer seeing them in the contrib directory of this repo rather
> than collating them in openshift-ansible, this would also allow us to
> ensure that content is updated when users update origin/aos.
>
> See
> https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/examples-sync.sh#L12-L18
> for the list of places we're pulling content from
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4655#issuecomment-140100411>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
I can make a root symlink.  Part of the reason I'm doing this is that some
of these are details that are not front and center to 100% of the people
who use the repo.  The more things we have in the repo, the harder it is
for people assessing Origin as a community to explore.  It may not seem
like it, but every line in the directory listing in GitHub has a measurable
impact on the number of people who leave our github page without doing
things.

On Mon, Sep 14, 2015 at 9:43 AM, Brenton Leanhardt <notifications@github.com
> wrote:

> The other useful part of having the specfile upstream is that we get to
> have these conversations earlier in the dev cycle instead of it being a
> surprise when refactorings like this are needed. :)
>
> It would be nice if tito could support configuring the link between a
> specfile and the source arbitrarily in configuration. Alternatively, if the
> dirs didn't change on us all the time we could probably get away with
> symlinking the needful in to .contrib/rpm to make tito happy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4655#issuecomment-140079240>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
doing things = engaging with OpenShift / AEP / Origin

On Mon, Sep 14, 2015 at 10:37 AM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> I can make a root symlink.  Part of the reason I'm doing this is that some
> of these are details that are not front and center to 100% of the people
> who use the repo.  The more things we have in the repo, the harder it is
> for people assessing Origin as a community to explore.  It may not seem
> like it, but every line in the directory listing in GitHub has a measurable
> impact on the number of people who leave our github page without doing
> things.
>
> On Mon, Sep 14, 2015 at 9:43 AM, Brenton Leanhardt <
> notifications@github.com> wrote:
>
>> The other useful part of having the specfile upstream is that we get to
>> have these conversations earlier in the dev cycle instead of it being a
>> surprise when refactorings like this are needed. :)
>>
>> It would be nice if tito could support configuring the link between a
>> specfile and the source arbitrarily in configuration. Alternatively, if the
>> dirs didn't change on us all the time we could probably get away with
>> symlinking the needful in to .contrib/rpm to make tito happy.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/4655#issuecomment-140079240>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by brenton** [comment]
@sdodson, could you see if we could symlink things in to `./contrib/rpm` to make tito work?

**Comment by sdodson** [comment]
Yeah, I'll give it a shot later today.

**Comment by smarterclayton** [comment]
Using #4850 instead

**Pull request closed without merging**
