### PR TITLE
Calculate correct bottom scroll position

### LINKED ISSUE #5577: Follow log doesn't work on iOS
The follow log link takes you to the bottom, but doesn't stay active. I suspect the code that detects auto-scroll vs user scroll is not working properly.

/cc @jwforres

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #5577

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL. I tested Chrome, Firefox, IE 10, Safari, and iOS.

**Comment by jwforres** [comment]
LGTM, @openshift/team-project-committers fixes auto-scrolling behavior on iOS, we were miscalculating the scroll to position

**Comment by smarterclayton** [comment]
Approved

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
```
Synchronizing [origin@master] from origin...
fatal: Unable to create '/data/src/github.com/openshift/origin-bare/refs/heads/master.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
ssh: connect to host 54.152.169.57 port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh: connect to host 52.91.219.63 port 22: Connection timed out
fatal: Could not read from remote repository.
```

**Comment by jwforres** [comment]
@danmcp have you seen that before? Lock failure creating the bare repos?

[merge]

**Comment by liggitt** [comment]
Infrastructure flakes recorded at https://github.com/openshift/origin/issues/5627

**Comment by danmcp** [comment]
@jwforres Yeah.  Known nagging issue.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
