### PR TITLE
Cherry-picking upstream commits prior to the next rebase

### PR DESCRIPTION
**Pull request by abhgupta**

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by abhgupta** [comment]
re[test] - seems like a transient failure

**Comment by abhgupta** [comment]
[merge] failed on a transient error, retrying...

**Comment by abhgupta** [comment]
[merge] failed on a transient error (TestSimpleImageChangeTriggerFrom), retrying one last time...

**Pull request merged**
