### PR TITLE
Bug 1881135: image_ecosystem: remove mongodb tests

### PR DESCRIPTION
**Pull request by yselkowitz**
/cc @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
you gotta run `make update-gofmt` and `make update-generated`

**Comment by yselkowitz** [comment]
@gabemontero remaining test failure is optional and looks unrelated

**Comment by gabemontero** [comment]
/assign @adambkaplan 
for approval

Adam - after we merge this, we will be removing the mongodb based template and adding a postgresql based template in samples operator, and then switching this test to the postgresql one.

/lgtm

**Review by adambkaplan — COMMENTED** [review]
/hold

Since we are so close to code freeze and this is not a GA release blocker, we are holding until 4.7 opens.
Once merged we can backport this deprecation to an early 4.6.z release.

**Comment by gabemontero** [comment]
/hold cancel

per confirmation from @crawford and @smarterclayton 

@yselkowitz - how about we consolidate this with https://bugzilla.redhat.com/show_bug.cgi?id=1881573 and use https://bugzilla.redhat.com/show_bug.cgi?id=1881573 for this PR since the mongodb imagestreams will get removed with that BZ as well

**Comment by yselkowitz** [comment]
FWIW https://github.com/openshift/cluster-samples-operator/pull/326 is being used for that BZ but doesn't include the complete deprecation of all mongodb samples, only 3.4 which is going EOL soon.  Do you want to add to that PR or handle them separately?

**Comment by gabemontero** [comment]
> FWIW [openshift/cluster-samples-operator#326](https://github.com/openshift/cluster-samples-operator/pull/326) is being used for that BZ but doesn't include the complete deprecation of all mongodb samples, only 3.4 which is going EOL soon. Do you want to add to that PR or handle them separately?

For now, separate PRs in case we hit bumps with complete removal and nodejs template switch

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
