### PR TITLE
UPSTREAM: 71573: Correctly Clear conntrack entry on endpoint changes when using nodeport

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
https://github.com/kubernetes/kubernetes/pull/71573

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1659204

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@smarterclayton could you take a look at this?

**Comment by knobunc** [comment]
/approve

@smarterclayton can you approve this backport please?

**Pull request merged**
