### PR TITLE
the open dockerfile need to be closed

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by csrwng** [comment]
[test]

**Comment by guangxuli** [comment]
@csrwng ptal,thanks.

**Comment by csrwng** [comment]
LGTM, will merge after 1.3 is released

**Comment by guangxuli** [comment]
@csrwng Can this PR be merged? thanks.

**Comment by csrwng** [comment]
Yes [merge]

**Comment by csrwng** [comment]
Flake https://github.com/openshift/origin/issues/11016
[merge]

**Comment by csrwng** [comment]
Flake https://github.com/openshift/origin/issues/11016
[merge] again

**Pull request merged**
