### PR TITLE
Bug 1707162: Block access to MCS

### PR DESCRIPTION
**Pull request by danwinship**
In conjunction with the MCS/approver changes happening elsewhere, this attempts to block all (non-privileged / non-`CAP_NET_ADMIN`) pods from being able to reach the MCS.

There are two commits, and both are hacks which are assumed to be temporary; if we want to keep something like this, we can reimplement the functionality more cleanly later.

The `OUTPUT` rule in the pod netns blocks direct connections from a pod to the MCS (including via egress IP, or via multus-created interfaces). The `FORWARD` rule in the pod netns blocks connections from a pod to the MCS via an egress-router. The `OUTPUT` rule in the root netns blocks direct connections from hostNetwork pods to the MCS. (I'm not sure that the `FORWARD` rule in the root netns actually does anything at this point... but it's not hurting.)

The `RestrictedEndpointsAdmission` part blocks attempts to create Services pointing to the MCS. (The `EndpointController` bypasses the `RestrictedEndpointsAdmission` controller, but it should not be possible for anyone who isn't already a cluster admin to create a hostNetwork pod on a master, or create a Service in a Namespace that already has a hostNetwork pod on a master, so they should not be able to create a Service pointing to the MCS without explicitly setting the Endpoints.) Without this part, someone could create a Service of type `LoadBalancer` pointing to the MCS, and that would bypass all of the iptables rules.

I originally started trying to make the restricted pods in `RestrictedEndpointsAdmission` be configurable, but it was a lot of work for something that's really just an ugly hack anyway. (And if it was going to be an exposed feature, we'd want it to work differently)

### CODE REVIEW

**Comment by knobunc** [comment]
Thanks @danwinship.  I appreciate the work on this over the weekend.

**Comment by squeed** [comment]
Looks good to me. Not lgming until @dcbw has a chance for review.

**Comment by cgwalters** [comment]
The commit message says:
> this attempts to block all (non-privileged / non-CAP_NET_ADMIN) pod

But I don't see where we conditionalize?

**Comment by danwinship** [comment]
Yeah, we block access for all pods, but privileged/`CAP_NET_ADMIN` pods could remove the iptables rules we added if they wanted to, so they're not actually blocked.

**Comment by cgwalters** [comment]
Fallout in https://bugzilla.redhat.com/show_bug.cgi?id=1710226

**Pull request merged**
