### PR TITLE
catalog: update roles to use rbac.authorization.k8s.io

### PR DESCRIPTION
**Pull request by jpeeler**
For #16297

### CODE REVIEW

**Comment by pmorie** [comment]
/assign @enj 

We should hold off on merging this until master opens for 3.8, at this point.

**Comment by enj** [comment]
@jpeeler these _look_ correct, but how did you go about generating them?  My recommendation is to create the legacy origin authz resources and then ask for them in the RBAC format from the server.  That way the server handles all the conversions so you know they are correct.

**Comment by jpeeler** [comment]
I generated them manually and tested to ensure they were correct. @enj how would I query the server for authz rules in the updated RBAC format?

**Comment by enj** [comment]
@jpeeler create the resources using the old (non-RBAC) template.

Then request the resources with `.rbac` appended after the resource type such as:

```
oc get clusterrole.rbac servicecatalog-serviceclass-viewer -o yaml
```

This will cause the client to `GET` `/apis/rbac.authorization.k8s.io/v1beta1/clusterroles/servicecatalog-serviceclass-viewer`, and the server will handle all conversions.

**Comment by jpeeler** [comment]
The RBAC roles were updated in another PR.

**Pull request closed without merging**
