### PR TITLE
UPSTREAM: 44625: Retry secret reference addition on conflict

### PR DESCRIPTION
**Pull request by liggitt**
also includes test fixes from 44996 and 45151

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
Bug fix that prevents flakes.

**Comment by deads2k** [comment]
@liggitt Since we don't always clean anymore, I guess we can race and get an extra.  That test-cmd test probably wants to be updated.  The point was to be sure that the projects were accounted together.  The exact number wasn't particularly important.

**Comment by liggitt** [comment]
> @liggitt Since we don't always clean anymore, I guess we can race and get an extra.

We shouldn't be able to with a single controller and etcd, which is what that test runs with

**Comment by liggitt** [comment]
included in https://github.com/openshift/origin/pull/14033

**Pull request closed without merging**
