### PR TITLE
HAProxy router fix for ip whitelist exceeding max config arguments that haproxy allows.

### PR DESCRIPTION
**Pull request by ramr**
Changes to use a file based acl if the annotation for the ip whitelist exceeds the max haproxy config line arguments.

fixes bugz #1598738

/cc @openshift/sig-network-edge

### CODE REVIEW

**Comment by Miciah** [comment]
/lgtm

But... How much would it hurt performance (a) to use a file always and (b) to write the file using the template? Doing so could simplify the code, obviate the need for `validateHAProxyWhiteList`, and increase re-usability for other template-based routers.

**Comment by ramr** [comment]
@Miciah yeah agree using a file always would be simpler. Bu it does come with a performance effect if a lot of routes use that annotation - does mean more IO + the processing is sequential so it makes for a slower startup. If there's not a lot of routes using that annotation, then it would be ok.

**Comment by imcsk8** [comment]
LGTM

**Pull request merged**
