### PR TITLE
Revert openshift sdn plugin auto detection on the node

### PR DESCRIPTION
**Pull request by pravisankar**
When openshift master and node are started at the same time, we could end up in a race condition when node tries to auto detect the network plugin. Issues: https://github.com/openshift/origin/pull/10724 and https://github.com/openshift/origin/pull/10473

We need a better solution. This PR will keep the master/node plugin validation in https://github.com/openshift/origin/pull/9147 but reverts the plugin auto detection feature.

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL
@sdodson @brenton please revert corresponding change in openshift-ansible

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Needs sign off

**Comment by danwinship** [comment]
LGTM

**Comment by smarterclayton** [comment]
@knobuc you approve for 1.3?

**Comment by knobunc** [comment]
I approve.  [merge]

**Pull request merged**
