### PR TITLE
f5 node watch fix - needs a cache to process 'MODIFY' events

### PR DESCRIPTION
**Pull request by rajatchopra**
Poor code before, never accounted that nodes that were already created before F5 is launched will only get a MODIFIED event. This code takes care of that (and ignores the subsequent MODIFY events caused by status updates).

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389706

@pravisankar Please review. Thanks for the hint.
cc @openshift/networking

### CODE REVIEW

**Comment by dcbw** [comment]
LGTM

**Comment by rajatchopra** [comment]
[test]

**Comment by pravisankar** [comment]
[merge]

**Comment by eparis** [comment]
[merge]

**Pull request merged**
