### PR TITLE
Backport edits to tests for 1.5 CI

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/cc @smarterclayton we need to version our CI badly....

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]
[merge]

**Comment by stevekuznetsov** [comment]
We also need ec35afb13d6f723c09bcf70b29e58f77a4496949

**Comment by stevekuznetsov** [comment]
Passed conformance, should be good now. [merge]

**Comment by stevekuznetsov** [comment]
Thanks @smarterclayton ... have we always had one queue for all the branches? Seems inefficient

**Comment by smarterclayton** [comment]
Yes, we need prow

On Mar 11, 2017, at 8:44 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Thanks @smarterclayton <https://github.com/smarterclayton> ... have we
always had one queue for all the branches? Seems inefficient

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/13353#issuecomment-285867521>,
or mute
the thread

**Pull request merged**
