### PR TITLE
Revert "Bug 1683057: Fix router metrics test flakes"

### PR DESCRIPTION
**Pull request by smarterclayton**
Reverts openshift/origin#24075

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_oc/143/pull-ci-openshift-oc-master-e2e-aws/478

### CODE REVIEW

**Comment by ironcladlou** [comment]
I think https://github.com/openshift/origin/pull/24085 fixes the AWS flake introduced by https://github.com/openshift/origin/pull/24075

**Comment by smarterclayton** [comment]
Superseded by correct fix: #24085

**Pull request closed without merging**
