### PR TITLE
Fix OAuth state encoding - 1.4

### PR DESCRIPTION
**Pull request by liggitt**
Cherry-pick of #12068

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by mfojtik** [comment]
@enj ptal

**Comment by enj** [comment]
Not sure what `make: *** No rule to make target verify-commits` means but code LGTM.

cc @stevekuznetsov

**Comment by liggitt** [comment]
it means the jenkins job won't work with non-master branches now

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
