### PR TITLE
Refactor rest of controllers to use ProjectsService

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Currently based off of `bpeterse/refactor-project-service` (which is first commit listed)

- updates rest of pages that were previously using ProjectController to now use ProjectsService
- eliminates remaining `ng-controller` directives 
- defines rest of controllers in routes

@jwforres @spadgett this is WIP because somewhere in this set of changes is where the tests are failing with the message I mentioned before:

```
WARN [proxy]: failed to proxy /app/views/projects.html (connect ECONNREFUSED 127.0.0.1:9876)
PhantomJS 1.9.8 (Mac OS X) ERROR
  Some of your tests did a full page reload!
ERROR: 'Error: [$compile:tpload] Failed to load template: views/projects.html
http://errors.angularjs.org/1.3.8/$compile/tpload?p0=views%2Fprojects.html
```
I'll be working on diagnosing this.  There isn't any reason `views/projects.html` should fail to load, I'm not even working on that template in this PR.  I suspect timing issues....

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
[TEST] cuz Im sure they fail. e2e has issues, I believe promise resolution now messes with the timeouts that tests currently rely on to pass.

**Comment by benjaminapetersen** [comment]
[TEST]

**Comment by benjaminapetersen** [comment]
Yay, tests passed.  Still tinkering a bit before ill ping for another review.  Not merge ready.

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett ping for review, doing a fork_ami now.  
(first commit on this branch is still `bpeterse/refactor-project-service`, so the fork_ami will get everything).

**Comment by spadgett** [comment]
When you rebase, can you verify that delete route works (#6150)?

Might update the description if no longer a WIP.

**Comment by jwforres** [comment]
It looks like some of the templates you just removed the ng-controller designations but others you actually removed the divs.  Was there a reason for doing some one way and some the other way.

**Comment by benjaminapetersen** [comment]
@spadgett will check the delete route again (and update the description).  @jwforres agree, repeating the fixture is gross... and intended to only remove the ng-controller not the divs to avoid conflict w/ @sg00dwin stuff coming, I'll double check this again as well.

**Comment by benjaminapetersen** [comment]
@jwforres aha, I know why.  I deleted the outermost `<div>` if there was no `class="content"` or anything else to indicate it should be left.  Nested `<div>`'s survived.  For consistency, I'll put back the outer `<div>` and leave it plain.  Steve can update templates when his changes are ready.

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett ping for review again. checklist above done.

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
bindata.go is getting a diff

**Comment by benjaminapetersen** [comment]
[TEST]

**Comment by benjaminapetersen** [comment]
[TEST]

**Comment by benjaminapetersen** [comment]
Nice, finally survived testing.  Creating a new fork_ami for QE as well.

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
