### PR TITLE
Fix go vet errors

### PR DESCRIPTION
**Pull request by rhcarvalho**
This fixes several issues pointed out by running `go vet` (`hack/verify-govet.sh`).

### CODE REVIEW

**Comment by rhcarvalho** [comment]
[test]

@bparees PTAL

**Comment by kargakis** [comment]
LGTM

Can you also update the scripts with the same changes I had at https://github.com/openshift/origin/pull/8717?

**Comment by kargakis** [comment]
> Can you also update the scripts with the same changes I had at #8717?

Oh, I see there is https://github.com/openshift/origin/pull/8889. ok

**Comment by rhcarvalho** [comment]
@bparees @kargakis PTAL
Want this in so we can proceed to #8889 and get Travis green there as well with vet running on 1.6 and 1.5.

**Comment by bparees** [comment]
sorry lost track of this one, lgtm
[merge]

**Pull request merged**
