### PR TITLE
F5: handle HTML responses gracefully

### PR DESCRIPTION
**Pull request by Miciah**
The F5 iControl REST API sometimes returns error responses with HTML payloads instead of JSON.  (This has been observed for HTTP 401 and 404 responses.) Gracefully handle such responses by ignoring the error and response payload for HTTP 4xx and 5xx responses if decoding fails.

Before this commit, if the F5 iControl REST API returned an HTML response, the rest_request method would return an error that rendered as follows:

    error: Decoder.Decode failed: invalid character '<' looking for beginning of value

After this commit the rest_request method will produce an error that renders similar to the following:

    error: HTTP code: 401.

This commit fixes bug 1316463.

https://bugzilla.redhat.com/show_bug.cgi?id=1316463

-

[test]

-

@ramr

### CODE REVIEW

**Comment by liggitt** [comment]
this seems like the wrong place to be fixing this issue... is the f5 API really so unstable?

**Comment by ramr** [comment]
@liggitt why do you say that? The alternative to not doing it here, would be to check in multiple different places which becomes too onerous. This is looking at the response back from F5 - if its JSON, it would get parsed and returned - if not, then its some other content type and we pick out the HTTP error code as we don't want to `scrape` the content for errors (there's multitudes of ways that could change/fail).  

Now I know we requested for a content type of `application/json`, we should get back JSON but that might not always be the case. A well behaved HTTP server should reply back with acceptable content or then a not-acceptable 406 response but that's often not the case with most servers - try a request with  "Accept: application/postscript" on a few servers of choice and see what you get back.

We could dump that response content out in the error message - that would be useful. 

@Miciah from my side, this LGTM

**Comment by Miciah** [comment]
The F5 iControl REST API is both unstable and underspecified.  A lot of JSON responses are undocumented, so most of the code was written by trial-and-error, and it turns out that some responses do change between minor F5 BIG-IP revisions (see #7566 for an example).  The API guide does not indicate that HTML responses should ever be returned.

I don't know where else we would implement this unless you want us to take all this parsing logic out of `rest_request` and move it up the chain to its callers or its callers' callers.

I don't think including the full HTML body in the error would be a good idea because it would be just add a lot of noise and make it harder to pick out the error.  An HTTP error code (401, 404, or anything else it turns out F5 BIG-IP can return with an HTML payload) seems specific enough without adding noise.

**Comment by deads2k** [comment]
> The alternative to not doing it here, would be to check in multiple different places which becomes too onerous.

I'm not familiar with project, but we can't fix the F5 REST API?  Seems like that would make life better for everyone.

**Comment by Miciah** [comment]
Are you suggesting we submit support tickets to F5 regarding the shortcomings in its REST API and documentation? That's probably a good idea, but in the mean time, how do we cope with the API as it is?

**Comment by deads2k** [comment]
> Are you suggesting we submit support tickets to F5 regarding the shortcomings in its REST API and documentation? That's probably a good idea, but in the mean time, how do we cope with the API as it is?

One doesn't necessarily preclude the other.   I suspect that links to issues or bugs would be enough to assuage @liggitt's concerns.

**Comment by Miciah** [comment]
@ramr, as far as I know, engineering does not have a formal support agreement with F5, so I'd suggest inquiring with our contacts at F5 via E-mail to determine the best way to file tickets.

We want to ascertain exactly when F5 BIG-IP may send HTML responses instead of JSON, point out gaps in the API documentation, and see about getting some guarantees with respect to the stability of the APIs that we are using.

I can help in documenting specific concerns in detail.  However, because F5's servers reject any E-mail I send, I cannot initiate communications myself.

**Comment by knobunc** [comment]
Fix LGTM too.

**Comment by eparis** [comment]
@rajatchopra @ramr can you two send an e-mail complain to the F5 people you know, if @Miciah didn't?  And we'll merge this after this release crunch is over.

**Comment by caphrim007** [comment]
@Miciah @eparis I can assist with this as I know who to ask here. I'll PM you

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
