### PR TITLE
cluster up: docker beta instructions

### PR DESCRIPTION
**Pull request by csrwng**
Adds instructions for Docker beta setup

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
@ironcladlou fyi

**Comment by bparees** [comment]
lgtm, have to take your word for the accuracy of the commands.

**Comment by csrwng** [comment]
[merge]

**Comment by csrwng** [comment]
```
[Fail] [k8s.io] Networking [k8s.io] [Flaky] Granular Checks [It] should function for pod communication on a single node 
```
[merge]

**Comment by csrwng** [comment]
[merge]

**Comment by svefors** [comment]
Docker beta has removed the pinata feature and aims to provide configuration options through the GUI. Perhaps docker-machine-driver-xhyve is the way to go?

**Comment by ironcladlou** [comment]
I'm not actually settled on any useful workflow with `oc cluster` using the D4M Beta due to the intrinsic single-VM assumption. Origin wants to "own" the Docker host in a variety of ways, which is fine and meshes well conceptually with docker-machine as I can create new machines for every Origin cluster I want to work with and treat them as disposable. The D4M VM does not seem to be disposable in this regard, unless I'm missing something. How can I work with multiple Origin instances using D4M, and what are the risks to my D4M VM (and thus other non-Origin containers) once Origin is running inside it?

**Comment by csrwng** [comment]
@ironcladlou good questions... however, it's not that different than using 'cluster up' on your local linux box which has only a single docker instance. Even if you run non-containerized openshift locally on Linux, the kubelet pretty much wants to take over your docker daemon. Perhaps Dind could give us a better isolation story... will require more investigation.

**Comment by ironcladlou** [comment]
>@ironcladlou good questions... however, it's not that different than using 'cluster up' on your local linux box which has only a single docker instance. Even if you run non-containerized openshift locally on Linux, the kubelet pretty much wants to take over your docker daemon. Perhaps Dind could give us a better isolation story... will require more investigation.

Yeah, that's fair, and is the way I usually run Origin on a Fedora machine- however, since switching to macOS I've come to prefer the docker-machine method and have started taking for granted having isolated daemons for special purposes. I guess given the design of D4M this is probably not considered a majority use case.

**Comment by ironcladlou** [comment]
@svefors 
>Docker beta has removed the pinata feature and aims to provide configuration options through the GUI. Perhaps docker-machine-driver-xhyve is the way to go?

Do you happen to have a link to more info about the removal?

**Comment by ironcladlou** [comment]
Errmmm... https://forums.docker.com/t/pinata-missing-in-latest-mac-beta-1-11-2-beta15/15541/30

**Comment by svefors** [comment]
yes, that is the one. I assume they want docker-machine to handle the pinata use cases. Like you say "prefer the docker-machine method and have started taking for granted having isolated daemons for special purposes".

**Comment by csrwng** [comment]
Closing in favor of PR #9809

**Pull request closed without merging**
