### PR TITLE
test: Move the prometheus alerts test to the beginning of the suite

### PR DESCRIPTION
**Pull request by smarterclayton**
Otherwise some tests trigger temporary alerts

### CODE REVIEW

**Comment by paulfantom** [comment]
/hold

Testing for firing alerts shouldn't be done at the beginning of the test suite. Doing this can lead to shipping OpenShift installation with firing alerts.
If there are any "temporary" alerts, those should either have:
- extended `for` clause, if alert quickly goes away
- `info` severity, if we want it to be surfaced only in dashboard
- include alert name in test expression to exclude that alert

Second solution would need tweaking test expression to allow `info` alerts firing.

**Comment by LiliC** [comment]
Note that I already started working on end of run tests for alerts checking. https://github.com/openshift/origin/pull/24492 it detects correctly the OLM alert that is firing every time, whereas we have been seeing flakes which is why I suspect this PR was opened. ( Note that the PR is in WIP. Feedback welcome. :)

**Comment by paulfantom** [comment]
Excluding `info` alerts is done in https://github.com/openshift/origin/pull/24500

**Comment by smarterclayton** [comment]
Going to merge this now while we sort out how to suppress temporary alerts during runs in serial, disruptive, and upgrade tests (which will always generate some number of fired alerts).

**Pull request merged**
