### PR TITLE
Run cluster-up using separate processes

### PR DESCRIPTION
**Pull request by deads2k**
Builds on https://github.com/openshift/origin/pull/18536 .  It removes the old options.

Possible fallout here:
 1. logging ? - webconsole wiring perhaps?
 2. metrics ? - webconsole wiring perhaps?
 3. running from old config?  - our config structure looks entirely different.

/assign @mfojtik 
/assign @soltysh

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k dunno what changed but the static pods are now running just fine on OSX and everything seems to work just fine :-)

**Comment by mfojtik** [comment]
@deads2k while testing this, the cluster up is currently broken when you have firewalld enabled... the webconsole is not able to bind on 443.

**Comment by mfojtik** [comment]
@deads2k i would rule out 3. as we said that we are not supporting "old" structure anymore. If you run 3.7 or 3.9 cluster and want to run 3.10 you have to start new config.

**Comment by deads2k** [comment]
@mfojtik pretty heavily modified.  

@juanvallejo Looks like we're failing the cross build.  Might need to rewrite the recursive copy....

**Comment by deads2k** [comment]
removing hold, master is now open.

**Pull request merged**
