### PR TITLE
Do not merge: This is for debugging tests

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by deads2k** [comment]
**unpossible!** no code changes in origin since the failures!

**Comment by mrunalp** [comment]
The machine-os-content for 4.3 was old.. It was fixed around 17:00 Eastern.

**Comment by deads2k** [comment]
> The machine-os-content for 4.3 was old.. It was fixed around 17:00 Eastern.

old how?  We should have been able to run skewed against whatever was in HEAD before the kube bump merge.

**Comment by mrunalp** [comment]
The 4.3 machine-os-content was 132 days old. The rebase PR when merged must have used the 4.2 machine-os-content which is way more recent.

**Pull request closed without merging**
