### PR TITLE
simplify openshift controller lease

### PR DESCRIPTION
**Pull request by deads2k**
This removes our original plug.  Since ansible always sets the new election mode in 3.7 (here https://github.com/openshift/openshift-ansible/blob/24d2349eb93272eb71a9d6f8a5fc28f2b04881e9/roles/openshift_master/tasks/upgrade/v3_7/master_config_upgrade.yml#L2-L5), we are safe to make use of it in 3.9

This actually removes the choice of name since that isn't flexibility that is actually needed at the moment.

@openshift/sig-master

### CODE REVIEW

**Comment by deads2k** [comment]
@openshift/api-review @derekwaynecarr this removes the `/controllers` endpoint as we previously discussed.  It didn't work since 3.7 anyway (the delete half) and the get half wasn't documented or used or consistent with kube-controller-manager anyway.

**Comment by deads2k** [comment]
This might actually help stability.  Found a leasing bug in the scheduler.  Bumping priority.

**Comment by mfojtik** [comment]
/retest

@deads2k seems like this PR is a flake magnet

**Comment by deads2k** [comment]
Fixes flaky scheduler, current batch failed, doesn't conflict with current pull in test.  Green tests are still valid.

merging

**Pull request merged**
