### PR TITLE
Fix csi-mock tests

### PR DESCRIPTION
**Pull request by jsafrane**
Run csi-mock sidecars as privileged so they can access CSI driver socket and enable the tests.

We get coverage of these features:

* Skipping attach for non-attachable drivers.
* Passing pod info to CSI drivers on `NodePublish` call.

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
/test e2e-aws
cc @openshift/storage for review.

**Comment by bertinatto** [comment]
/assign @mfojtik 
for approval

**Comment by mfojtik** [comment]
re-enabling disabled tests 👍 

/lgtm

**Pull request merged**
