### PR TITLE
Add build logs and pod logs to default auth policy

### PR DESCRIPTION
**Pull request by csrwng**
Includes upstream PR https://github.com/GoogleCloudPlatform/kubernetes/pull/7541

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k please take a look

**Comment by deads2k** [comment]
authorization rules lgtm.  Why are these two commits in the same pull?  I don't see the relationship.

**Comment by csrwng** [comment]
I guess I could make different pulls... but basically without the first commit 'osc log <pod>' defaults to following the log and there's no way to tell it not to follow it. The relationship is that with this pull we are now able to do 'osc log <pod>' :-)

**Comment by deads2k** [comment]
> without the first commit 'osc log ' defaults to following the log and there's no way to tell it not to follow it.

Ah.  That wasn't obvious to me.  [merge]

**Comment by smarterclayton** [comment]
```
--- FAIL: TestEnumeratedCoveringResourceGroup (0.00s)
	policy_comparator_test.go:237: expected true, but got false
	policy_comparator_test.go:241: expected [], but got [PolicyRule{Verbs:[delete], Resources:[builds/log], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[update], Resources:[builds/log], ResourceNames:[], Restrictions:{<nil>}}]
--- FAIL: TestEnumeratedMissingPartOfResourceGroup (0.00s)
	policy_comparator_test.go:241: expected [PolicyRule{Verbs:[delete], Resources:[buildlogs], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[update], Resources:[buildlogs], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[delete], Resources:[buildconfigs/instantiate], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[update], Resources:[buildconfigs/instantiate], ResourceNames:[], Restrictions:{<nil>}}], but got [PolicyRule{Verbs:[update], Resources:[buildlogs], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[delete], Resources:[buildlogs], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[delete], Resources:[buildconfigs/instantiate], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[update], Resources:[buildconfigs/instantiate], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[delete], Resources:[builds/log], ResourceNames:[], Restrictions:{<nil>}} PolicyRule{Verbs:[update], Resources:[builds/log], ResourceNames:[], Restrictions:{<nil>}}]
FAIL
coverage: 35.4% of statements
```

**Comment by csrwng** [comment]
tests fixed

**Pull request merged**
