### PR TITLE
Add .NET Core CentOS ImageStreams

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/openshift/origin/issues/18330

These images are built from: https://github.com/redhat-developer/s2i-dotnetcore/.

@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
@tmds you'll need to run hack/update-generated-bindata.sh and include the generated file in your PR

otherwise lgtm.

**Comment by bparees** [comment]
also please consider contributing your imagestreams here:
https://github.com/openshift/library#contributing

as that will eventually be the centralized location for imagestreams.

**Comment by tmds** [comment]
@bparees thanks. I'll look into adding these streams to openshift/library too.

**Comment by bparees** [comment]
please squash your commits

**Comment by tmds** [comment]
@bparees commits squashed.

**Comment by tmds** [comment]
One of the build logs shows an issue using the registry.centos.org registry:

>      Error: [ImageStream "dotnet" is invalid: spec.tags[2.0].from.name: Forbidden: registry "registry.centos.org" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 3 more ..., ImageStream "dotnet-runtime" is invalid: spec.tags[2.0].from.name: Forbidden: registry "registry.centos.org" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 3 more ...]

**Comment by bparees** [comment]
> One of the build logs shows an issue using the registry.centos.org registry:

>      Error: [ImageStream "dotnet" is invalid: spec.tags[2.0].from.name: Forbidden: registry "registry.centos.org" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 3 more ..., ImageStream "dotnet-runtime" is invalid: spec.tags[2.0].from.name: Forbidden: registry "registry.centos.org" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 3 more ...]

Hm.  @miminar @smarterclayton @liggitt any opinions on adding *.centos.org to our list of default whitelisted registries?

**Comment by smarterclayton** [comment]
Sigh....

On Feb 5, 2018, at 8:34 AM, Ben Parees <notifications@github.com> wrote:

One of the build logs shows an issue using the registry.centos.org registry:

 Error: [ImageStream "dotnet" is invalid: spec.tags[2.0].from.name:
Forbidden: registry "registry.centos.org" not allowed by whitelist:
"172.30.1.1:5000", "docker.io:443", "*.docker.io:443",
"*.redhat.com:443", and 3 more ..., ImageStream "dotnet-runtime" is
invalid: spec.tags[2.0].from.name: Forbidden: registry
"registry.centos.org" not allowed by whitelist: "172.30.1.1:5000",
"docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 3 more
...]

Hm. @miminar <https://github.com/miminar> @smarterclayton
<https://github.com/smarterclayton> @liggitt <https://github.com/liggitt>
any opinions on adding *.centos.org to our list of default whitelisted
registries?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/18348#issuecomment-363140282>,
or mute
the thread

**Comment by bparees** [comment]
> Sigh....

@smarterclayton i'm not sure how to proceed based on that answer...

**Comment by tmds** [comment]
> @miminar @smarterclayton @liggitt any opinions on adding *.centos.org to our list of default whitelisted registries?

@miminar @smarterclayton @liggitt ping. Is it ok to whitelist centos.org? Or should we look at moving our images (to dockerhub?)?

**Comment by bparees** [comment]
adding centos registry here:
https://github.com/openshift/origin/pull/18597

**Comment by bparees** [comment]
whitelist updated
/retest

**Pull request merged**
