### PR TITLE
OCPBUGS-2991: Bump openshift/kubernetes to latest master

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-2991

### CODE REVIEW

**Comment by vrutkovs** [comment]
Both gcp-ovn and aws-ovn-fips fail on
>[sig-devex][Feature:Templates] template-api TestTemplate [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]
>[sig-devex][Feature:Templates] template-api TestTemplateTransformationFromConfig [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]

**Comment by dgoodwin** [comment]
> Both gcp-ovn and aws-ovn-fips fail on
> 
> > [sig-devex][Feature:Templates] template-api TestTemplate [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]
> > [sig-devex][Feature:Templates] template-api TestTemplateTransformationFromConfig [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]

I can see these failing outside this PR, it looks like it just flares up from time to time and then gets better. It's failing sometimes in both 4.12 and 4.13. 

However it's also failing in a bunch of optional jobs... 

Meanwhile sippy doesn't seem to be seeing the failures even though they're in the db. I'm not sure this PR is safe just yet, investigating...

**Comment by dgoodwin** [comment]
I think it's a regression in here @gnufied , that test you pointed to is mostly failing in presubmits, probably from this exact PR, if you look to periodics there are alarmingly few hits: https://search.ci.openshift.org/?search=template-api+TestTemplate&maxAge=48h&context=1&type=junit&name=periodic.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

These do appear to be busted on multiple jobs in here, possibly everything that runs it:

[sig-devex][Feature:Templates] template-api TestTemplate [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]
[sig-devex][Feature:Templates] template-api TestTemplateTransformationFromConfig [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]

**Comment by dobsonj** [comment]
/lgtm cancel
to sort out test failures

**Comment by vrutkovs** [comment]
library-go bump is breaking tests - https://github.com/openshift/library-go/pull/1429 would revert the change in question

**Comment by soltysh** [comment]
> library-go bump is breaking tests - [openshift/library-go#1429](https://github.com/openshift/library-go/pull/1429) would revert the change in question

@vrutkovs can you point me into exact failure where this is failing, hard-coding the namespace to `default` seems fishy, maybe the tests are wrong assuming the namespace is always that

**Comment by vrutkovs** [comment]
[`ab1483c` (#27566)](https://github.com/openshift/origin/pull/27566/commits/ab1483cee7f4e72f4f88642feb83473b8fa0545f) should fix the failing tests

**Pull request closed without merging**
