### PR TITLE
Remove requirement of having deprecated clusterNetworkCIDR/hostSubnetLength in master.networkConfig

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
Currently in order for openshift to start the first entry in clusterNetworks and the old clusterNetworkCIDR/hostSubnetLength have to match. Change it
so the older clusterNetworkCIDR/hostSubnetLength fields are no longer required.

Bug [1534779](https://bugzilla.redhat.com/show_bug.cgi?id=1534779)

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@pravisankar PTAL

**Comment by smarterclayton** [comment]
This is not backwards compatible - old config would be broken if you merged this.  We don't drop support for old config without a new major api version.

**Comment by JacobTanenbaum** [comment]
@pravisankar Yes this works with 'oc cluster up'

**Comment by imcsk8** [comment]
looks good

**Comment by dcbw** [comment]
@JacobTanenbaum what happens when there's old-style config?

**Comment by pravisankar** [comment]
On Wed, Feb 21, 2018 at 11:11 AM, Dan Williams <notifications@github.com>
wrote:

> @JacobTanenbaum <https://github.com/jacobtanenbaum> what happens when
> there's old-style config?
>
As part of conversions, it will be converted to new-style/internal config

**Comment by pravisankar** [comment]
Copying for posterity:

Jacob: I tested an old config file that just had the deprecated fields and it worked with this PR. I thought my changes to the conversion function changed the deprecated fields into the new struct internally. Unless my understanding is wrong old configs would only be wrong if a user tried to add the new clusterNetworks config struct while using the deprecated fields

Clayton: Ok, I misread the PR then.  If an old config file with only the old fields specified still works, then you can relax the requirement that the old field be specified.

**Comment by JacobTanenbaum** [comment]
@knobunc @smarterclayton is there something I need to do to push this forward?

**Pull request merged**
