### PR TITLE
ignore unrelated build+pod events during tests

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/7680

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
@bparees the change LGTM, but what would be creating other pods? Afaik, in integration tests, all that's making changes to the system is the test, no?

**Comment by bparees** [comment]
The pod check was just paranoia. It's the build check I'm primarily
concerned with.

Ben Parees | OpenShift

**Comment by bparees** [comment]
compile error fixed.  [merge]

**Pull request merged**
