### PR TITLE
Preserve valueFrom when merging envs in deployment strategy params

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/10831

@kargakis @bparees PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
(still need to be tested)

**Comment by bparees** [comment]
lgtm.  this is simpler than what is needed for the build case.

**Comment by mfojtik** [comment]
@bparees unfortunately it doesn't work for me... I have DC:

```yaml
  strategy:
    recreateParams:
      post:
        execNewPod:
          command:
          - /bin/echo
          - $HELLO
          containerName: ruby-ex
          env:
          - name: HELLO
            valueFrom:
              configMapKeyRef:
                key: hello
                name: configmap
        failurePolicy: Abort
```

and I can verify that the vars are set properly:

```console
Started deployment #10
--> Scaling ruby-ex-9 down to zero
--> Scaling ruby-ex-10 to 1 before performing acceptance check
--> Waiting up to 10m0s for pods in deployment ruby-ex-10 to become ready
----> adding env: api.EnvVar{Name:"HELLO", Value:"", ValueFrom:(*api.EnvVarSource)(0xc4209d6780)}
--> post: Running hook pod ...
$HELLO
--> post: Success
--> Success
```

@smarterclayton @kargakis is there something I'm missing to enable the valueFrom?

**Comment by mfojtik** [comment]
@smarterclayton @kargakis @bparees nvmd, PEBKAC, I need to do `/bin/bash -c "echo $HELLO"` so:

```console
Started deployment #12
--> Scaling ruby-ex-11 down to zero
--> Scaling ruby-ex-12 to 1 before performing acceptance check
--> Waiting up to 10m0s for pods in deployment ruby-ex-12 to become ready
----> adding env: api.EnvVar{Name:"HELLO", Value:"", ValueFrom:(*api.EnvVarSource)(0xc4209c4900)}
--> post: Running hook pod ...
moto
--> post: Success
--> Success
```

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees I see, build will filter out them as they are not whitelisted and then re-create the env map from serialized build object. Then it will require to call whatever kube use for expanding `valueFrom` (and presumably the builder will need a kube client to fetch configMap references).

Will leave the build part for you then ;-)

**Comment by kargakis** [comment]
Needs a test:)

**Comment by mfojtik** [comment]
@kargakis got a test, let make it prove https://github.com/openshift/origin/issues/10990

**Comment by kargakis** [comment]
Great, thanks! LGTM [merge]

**Pull request merged**
