### PR TITLE
Various build/test fixes

### PR DESCRIPTION
**Pull request by ncdc**
- Update `hack/test-go.sh` so it can handle symlinks for testing `vendor/k8s.io/*` symlinked dirs
- Fix `hack/verify-generated-clientsets.sh` so it actually verifies
- Regenerate clientsets (broken by #14285)

cc @deads2k @liggitt @smarterclayton @mfojtik @stevekuznetsov

### CODE REVIEW

**Comment by ncdc** [comment]
Note this won't merge yet at least because of this failure, now that we're testing client-go:

```
vendor/k8s.io/client-go/util/flowcontrol/backoff_test.go:32: cannot use tc (type *"github.com/openshift/origin/vendor/k8s.io/client-go/util/clock".FakeClock) as type *"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/clock".FakeClock in argument to NewFakeBackOff
```

**Comment by smarterclayton** [comment]
That was from the controller collapse, just a simple move of clock

**Comment by ncdc** [comment]
@smarterclayton thanks, fixing

**Comment by ncdc** [comment]
[test]

**Comment by stevekuznetsov** [comment]
`hack/test-go.sh` changes LGTM

**Comment by ncdc** [comment]
[test]

**Comment by liggitt** [comment]
odd timeout:
```
=== RUN   TestServerRunWithSNI
E0530 23:17:08.420516    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:35368: use of closed network connection); will try again.
E0530 23:17:23.927130    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:45901: use of closed network connection); will try again.
E0530 23:17:31.157532    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:44016: use of closed network connection); will try again.
E0530 23:17:41.419541    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:41267: use of closed network connection); will try again.
E0530 23:17:52.608752    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:42771: use of closed network connection); will try again.
E0530 23:17:58.150723    1768 serve.go:150] Error serving 127.0.0.1:0 (accept tcp 127.0.0.1:35640: use of closed network connection); will try again.
panic: test timed out after 2m0s
goroutine 226 [running]:
panic(0x1b1cdc0, 0xc4203ce6c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:918 +0x14e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78
goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc420194780, 0x1d58a2c, 0x14, 0x1ee2fe8, 0x4ca101)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc420194780)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc420194780, 0xc42071fd20)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x1ee7040, 0x2849440, 0x2, 0x2, 0xc42058dd78)
	/usr/local/go/src/testing/testing.go:799 +0x4eb
testing.(*M).Run(0xc42071fef0, 0x30)
	/usr/local/go/src/testing/testing.go:743 +0x130
main.main()
	github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/options/_test/_testmain.go:118 +0x2f9
goroutine 17 [syscall, 2 minutes, locked to thread]:
```

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@liggitt if this looks good to you I'm going to tag it. The test failures have been that odd one you pasted and github connectivity problems.

**Comment by ncdc** [comment]
[merge][severity: blocker]

**Comment by ncdc** [comment]
@smarterclayton I think this is failing because there is so much testing going on in parallel on the VM that the 2-minute test timeout for `TestServerRunWithSNI` is being exceeded. This test is very CPU heavy, using a full core for the majority of the duration of the test execution (generating certs). The test passes for me both locally in an F25 VM, and in EC2 on RHEL. Not sure what the best course of action is here...

**Comment by ncdc** [comment]
```
(pprof) top10
8.25s of 8.60s total (95.93%)
Dropped 96 nodes (cum <= 0.04s)
Showing top 10 nodes out of 43 (cum >= 8.26s)
      flat  flat%   sum%        cum   cum%
     5.51s 64.07% 64.07%      5.51s 64.07%  math/big.addMulVVW
     1.42s 16.51% 80.58%      7.90s 91.86%  math/big.nat.montgomery
     0.92s 10.70% 91.28%      0.92s 10.70%  runtime.memmove
     0.12s  1.40% 92.67%      0.22s  2.56%  math/big.nat.divLarge
     0.08s  0.93% 93.60%      7.99s 92.91%  math/big.nat.expNNMontgomery
     0.07s  0.81% 94.42%      0.08s  0.93%  runtime.scanobject
     0.06s   0.7% 95.12%      0.06s   0.7%  math/big.subVV
     0.05s  0.58% 95.70%      0.05s  0.58%  math/rand.(*rngSource).Seed
     0.02s  0.23% 95.93%      0.05s  0.58%  math/big.nat.clear
         0     0% 95.93%      8.26s 96.05%  crypto/rand.Prime
```

**Comment by smarterclayton** [comment]
Maybe we should disable the test.

**Comment by stevekuznetsov** [comment]
In what world is a test that starts the entire server (ten? times) a _unit_ test? What's the unit under test? The 2min timeout and placement in the unit test bucket seems innappropriate.

**Comment by ncdc** [comment]
Table-driven tests are idiomatic go, so I don't see anything inherently wrong there. You could argue that this maybe should be an integration test. However, this test, with its 10 iterations, takes about 6 seconds in my VM on my laptop. So you would think that 2 minutes would leave plenty of head room to spare, but apparently not in our full CI environment.

**Comment by ncdc** [comment]
Edit - 6 seconds on my laptop was with `go test`. Using `hack/test-go.sh`, which has coverage enabled, takes ~33 seconds.

I modified the test to use go 1.7 subtests and to run the subtests in parallel, and that decreases the time to about 18 seconds. Of course, this is being run in isolation, so who knows if/when we'd bump up against that 2 minute timeout on a fully loaded CI run...

Alternatively, I could add a <carry> patch that just skips this test. What do you all want to do?

**Comment by liggitt** [comment]
> Alternatively, I could add a patch that just skips this test. What do you all want to do?

long-term I'd rather see the certs pre-generated with 100 year lifetimes

**Comment by stevekuznetsov** [comment]
> so I don't see anything inherently wrong there. 

Only thing wrong is trying to get this to fit into the short timeout -- can we just move them into the integration package and not worry about this?

**Comment by ncdc** [comment]
> long-term I'd rather see the certs pre-generated with 100 year lifetimes

@liggitt do you want me to do that now?

**Comment by liggitt** [comment]
> @liggitt do you want me to do that now?

opened https://github.com/kubernetes/kubernetes/pull/46751

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
Tests are "green" (the one failure was being slow to delete everything in a namespace).

**Pull request merged**
