### PR TITLE
Suggest `oc policy` lookup on unauthorized request

### PR DESCRIPTION
**Pull request by juanvallejo**
Related Trello Card:
https://trello.com/c/04lpfTQR/451-8-cli-improved-flows-and-ux-in-the-cli-evg-ux-p3

Performing commands such as `oc get users` when logged in as a user with
no `cluster read` access produces errors such as `User <user> cannot list
all users in the cluster` but no suggestion to the user on how to
resolve this problem.

This patch appends a suggestion to use `oc policy` to look up which users
have permission to perform the current action.

##### Before
`$ oc login -u unauthorizeduser -p any`
```
$ oc get users
> User "unauthorizeduser" cannot list all users in the cluster.
```

##### After
`$ oc login -u unauthorizeduser -p any`
```
$ oc get users
> User "unauthorizeduser" cannot list all users in the cluster. Try "oc policy who-can list users"
```

@openshift/cli-review

### CODE REVIEW

**Comment by smarterclayton** [comment]
Won't all the people who don't have access to list users... not have access to see who can list users?

**Comment by juanvallejo** [comment]
@smarterclayton This has not been the case for me. When I log in as a user that does not have the `cluster-reader` role, I can still perform `oc policy who-can list users`

```
Namespace: unauthorizeduser
Verb:      list
Resource:  users

Users:  system:admin
        system:serviceaccount:openshift-infra:namespace-controller
        authorizeduser

Groups: system:cluster-admins
        system:cluster-readers
        system:masters

```

**Comment by liggitt** [comment]
a few things:
1. this shouldn't be an API change... it makes no sense to tell an API user to invoke a CLI operation
2. typically, users without permissions can't query clusterpolicy
3. querying policy won't tell you anything about cluster-level objects
4. your example CLI call is telling you who can query users inside a namespace, not at the cluster scope. `oc policy who-can get users --all-namespaces` actually tells you what you can do at the cluster scope, and a normal user would be forbidden from making that call.

**Comment by juanvallejo** [comment]
@liggitt 
> this shouldn't be an API change... it makes no sense to tell an API user to invoke a CLI operation
typically, users without permissions can't query clusterpolicy
querying policy won't tell you anything about cluster-level objects
your example CLI call is telling you who can query users inside a namespace, not at the cluster scope. oc policy who-can list users --all-namespaces actually tells you what you can do at the cluster scope, and a normal user would be forbidden from making that call.

Thanks for clarifying this. Should this PR be closed, or would it be still be worth telling a user (from the client) to perform `oc policy ...` within the namespace?

**Comment by liggitt** [comment]
I think the PR should be closed. I don't think the message from the API is the right place to suggest commands to run

**Pull request closed without merging**
