### PR TITLE
Fix web console dev env certificate problems for OS X Chrome

### PR DESCRIPTION
**Pull request by spadgett**
Reuse the livereload certificate and key for Grunt serve since it has CN localhost. The default grunt-contrib-connect certificate uses CN 0.0.0.0, which Chrome doesn't like.

Otherwise Chrome on OS X repeatedly warns

> NET::ERR_CERT_COMMON_NAME_INVALID
>
> This server could not prove that it is localhost; its security certificate is from 0.0.0.0. This may be caused by a misconfiguration or an attacker intercepting your connection.

/cc @jwforres @rhamilto @benjaminapetersen

### CODE REVIEW

**Comment by spadgett** [comment]
@benjaminapetersen can you try this and tell me if it fixes the cert problems for you?

**Comment by jwforres** [comment]
if we are going to use it for more than livereload can we rename the key and cert files

**Comment by spadgett** [comment]
Renamed the files.

**Comment by benjaminapetersen** [comment]
Nice, that was fast!  Pulling it down to try now.

**Comment by benjaminapetersen** [comment]
Looks like it works!  

FWIW, making a comment about the `NET::ERR_CERT_AUTHORITY_INVALID` that I got instead.  Going into Safari & trusting the cert to get it into keychain then made Chrome happy.  Would be good to doc this somewhere.  I'm not sure if it should go in contributing.adoc under a mac heading, or a comment in the gruntfile... thoughts?

**Comment by rhamilto** [comment]
Nice work, @spadgett!  [Step 8](https://github.com/openshift/origin/blob/master/assets/README.md#getting-started) is no longer required.  Remove that?

**Comment by benjaminapetersen** [comment]
Ah, nice, that README is a better place to make note of using Safari to accept the cert.

**Comment by spadgett** [comment]
Updated the certificates so that they should be good for a year and updated the README. @benjaminapetersen can you check again to see if everything still looks good?

**Comment by benjaminapetersen** [comment]
checking

**Comment by benjaminapetersen** [comment]
Works well for me!

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
Increase to 10 yrs on the cert otherwise LGTM

**Comment by spadgett** [comment]
Set to expire in 10 years now.

**Comment by spadgett** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Yay. This cert thing has become a pain.

**Comment by spadgett** [comment]
Test flake

```
FAILURE after 30.418s: hack/../test/cmd/builds.sh:58: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to-docker --to openshift/origin:v1.1-test' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: can't lookup images: Timeout: request did not complete within allowed duration
error: only a partial match was found for "openshift/origin:v1.1": "openshift/origin:v1.1"

The argument "openshift/origin:v1.1" only partially matched the following Docker image or OpenShift image stream:

* Docker image "openshift/origin:v1.1"
  Use --docker-image="openshift/origin:v1.1" to specify this image or template
```

**Pull request merged**
