### PR TITLE
add db sample templates

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@danmcp ptal.
@sspeiche @mfojtik @ewolinetz  fyi, these are likely relevant to the app demo work you're doing...  all I did to validate them was instantiate them, so if you guys could actually try them out (ie make sure the DBs are usable/connectable) that'd be nice too.

**Comment by danmcp** [comment]
@bparees Where do we put the rhel ones?

**Comment by bparees** [comment]
@danmcp ok, rhel7 support added.  note that the services created by these templates do NOT have the OS name in them, so you still can't create both templates in the same project.  Having the OS name in the service seemed annoying from the perspective of an app that might want to start out using the centos version of the DB images and then switch to rhel later.

also I got the beta channel registry name and used it, but i have no way to validate that right now, so someone ought to try those out.

**Comment by danmcp** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
@bparees I assume that scaling/replica is out of scope here and require
another set if templating. correct?

**Comment by bparees** [comment]
@mfojtik yeah, this is the dead simple case.  I did debate stealing your replica template json for the mongo template but decided against it.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
