### PR TITLE
Adjust defaults to better handle self-hosting and bootstrapping

### PR DESCRIPTION
**Pull request by smarterclayton**
@deads2k as discussed although I bumped the default for pods-per-core rather than removing.

### CODE REVIEW

**Comment by smarterclayton** [comment]
This blocks landing static pods because atomic has only one core and can only run 10 pods on the master.

**Comment by deads2k** [comment]
> @deads2k as discussed although I bumped the default for pods-per-core rather than removing.

What value does that have over floating like upstream does?  We hit a situation where it was better to not have this value.  Why is it better to do this than to be consistent with upstream?

Just the question.  lgtm otherwise.

**Comment by smarterclayton** [comment]
I'm thinking about the true pathological cases where we let the limit off and someone suddenly gets "max-pods" scheduled.  With this change and the defaults that would be at 6 cores, whereas with no defaults it could happen on 1 core.  I'm neither strongly for or against, so your call

**Comment by smarterclayton** [comment]
Removed, david convinced me we should do what upstream does wherever possible.

**Pull request merged**
