### PR TITLE
OCPBUGS-25730: Kuryr: Ignore Upgradeable=False on operators tests

### PR DESCRIPTION
**Pull request by dulek**
Kuryr SDN is removed from 4.15 and 4.14 blocks upgrades if it's configured. This patch makes sure operator tests are ignoring such a condition.

### CODE REVIEW

**Comment by itzikb-redhat** [comment]
Tested with 4.14.7 
The following tests passed

`"[sig-arch][Early] Managed cluster should [apigroup:config.openshift.io] start all core operators [Skipped:Disconnected] [Suite:openshift/conformance/parallel]"
"[sig-cluster-lifecycle][Feature:Machines][Early] Managed cluster should have same number of Machines and Nodes [apigroup:machine.openshift.io] [Suite:openshift/conformance/parallel]"`

**Review by gryf — APPROVED** [review]
/lgtm

**Pull request merged**
