### PR TITLE
Fix a func name and return value in the comment 

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Fix a func name from  NewStorage  to NewREST  and modify the description for return value.

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by kargakis** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
post-1.3

**Comment by yuexiao-wang** [comment]
@liggitt PTAL
Can this commit be merged?

**Comment by kargakis** [comment]
@yuexiao-wang we are on a code freeze. Only high priority patches will be merged until we release 1.3

**Comment by kargakis** [comment]
[merge]

**Comment by mfojtik** [comment]
Flake: https://github.com/openshift/origin/issues/10989

[merge]

**Comment by yuexiao-wang** [comment]
@mfojtik PTAL
Thanks!

**Pull request merged**
