### PR TITLE
Use DeepEqual instead of field by field comparison

### PR DESCRIPTION
**Pull request by rhcarvalho**

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees PTAL.

@gabemontero you might want to see this :)
You probably had problems because you were trying to compare `url.URL` with `*url.URL`.

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
@rhcarvalho thx for the ptr (no pun intended :-) ) / info

**Comment by rhcarvalho** [comment]
@gabemontero :tada: you make me laugh!

**Comment by rhcarvalho** [comment]
(partially reverted by #6578)

**Pull request merged**
