### PR TITLE
Add a simple shell extension

### PR DESCRIPTION
**Pull request by smarterclayton**
See upstream details in https://github.com/kubernetes/kubernetes/pull/13885 on how to use this. For testing

@jwforres @benjaminapetersen

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by mfojtik** [comment]
@smarterclayton is this something we should watch re: build-logs ?

**Comment by smarterclayton** [comment]
Only for the web console

On Sep 14, 2015, at 11:00 AM, Michal Fojtik <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> is this something we
should watch re: build-logs ?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4647#issuecomment-140107890>.

**Comment by stefwalter** [comment]
@smarterclayton One thing I believe is missing is that there needs to be some indication of when the logs or exec stream has actually started. Due to the many parts (and latency) involved, UIs need to display a spinner while connecting. That spinner should then disappear once we know we're receiving a log stream (even if nothing arrives over that log stream, ie: no container log output yet).

**Comment by smarterclayton** [comment]
We can return a zero length response on one of the write channels I guess.

On Sep 16, 2015, at 3:12 AM, Stef Walter <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> One thing I believe is
missing is that there needs to be some indication of when the logs or exec
stream has actually started. Due to the many parts (and latency) involved,
UIs need to display a spinner while connecting. That spinner should then
disappear once we know we're receiving a log stream (even if nothing
arrives over that log stream, ie: no container log output yet).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4647#issuecomment-140651395>.

**Comment by jwforres** [comment]
@spadgett

**Comment by spadgett** [comment]
@smarterclayton In my testing, the server closes the websocket for the log when it reaches the end of the current content, even if a build is still in progress. Is there something I need to do to prevent that?

**Comment by liggitt** [comment]
@spadgett are you passing the follow parameter?

**Comment by spadgett** [comment]
@liggitt that worked, thank you

**Comment by spadgett** [comment]
@smarterclayton this should work well for the web console

**Comment by jwforres** [comment]
@smarterclayton still planning to merge this into origin directly, or were you now planning to wait for a rebase after the k8s PR goes in?

**Comment by smarterclayton** [comment]
Will probably cherry pick after upstream merge

On Sep 28, 2015, at 3:29 PM, Jessica Forrester <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> still planning to merge
this into origin directly, or were you now planning to wait for a rebase
after the k8s PR goes in?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4647#issuecomment-143744107>.

**Comment by benjaminapetersen** [comment]
ping!
Just checking in on this one to see timeline on merge.

**Comment by smarterclayton** [comment]
I'll port the upstream over shortly.

On Oct 2, 2015, at 9:47 AM, Ben Petersen <notifications@github.com> wrote:

ping!
Just checking in on this one to see timeline on merge.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4647#issuecomment-145025959>.

**Comment by smarterclayton** [comment]
The websocket carry has been merged.  This is only the example of how to use it, @jwforres up to you on what you want to see in terms of an example extension.

**Comment by jwforres** [comment]
@stefwalter here's a reference for you to get started with the terminal stuff

**Comment by liggitt** [comment]
When we actually add this, we'd probably pair this with a console extension that added links from pods

**Pull request closed without merging**
