### PR TITLE
Bug 1903524: [3.11] UPSTREAM: 97013: Fix FibreChannel volume plugin corrupting filesystem on detach

### PR DESCRIPTION
**Pull request by jsafrane**
FibreChannel volume plugin misses one important step when removing a device: "multipath -f". It flushes all multipath buffers to its individual paths. Without it, a filesystem on the device may get corrupted.

~~/hold~~
* The PR is not upstream yet, see https://github.com/kubernetes/kubernetes/pull/97013
  * We may need to merge it even before though, upstream is frozen...
* ~I need to test it.~ Testsed with iSCSI instead of FC.

### CODE REVIEW

**Review by tsmetana — APPROVED** [review]
/lgtm

**Comment by jsafrane** [comment]
/hold cancel
upstream is still frozen.

**Comment by jsafrane** [comment]
Test failures:

* cmd: `Docker registry lookup failed: toomanyrequests: You have reached your pull rate limit. ` (or a ruby image).

* extended_clusterup: `oc get is -n openshift ruby ` ... `expecting any result and text 'latest'; re-trying every 1s until completion or 600.000s: the command timed out`. I believe it's docker pull limit too.

* extended_conformance_install: most probably it's this failure:
    ```
                            "message": "runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized", 
                            "reason": "KubeletNotReady", 
                            "status": "False", 
                            "type": "Ready"
    ...
    1. Hosts:    localhost
     Play:     Restart nodes
     Task:     Wait for node to be ready
     Message:  Failed without returning a message.
     ... 
    ```
    This looks like failing since 2020-11-12.

* e2e-gcp:  `Failed: Failed to pull image "gcr.io/k8s-authenticated-test/serve-hostname-amd64:1.0": rpc error: code = Unknown desc = repository gcr.io/k8s-authenticated-test/serve-hostname-amd64 not found: does not exist or no pull access`. Some recent e2e-gcp tests are green, might be a flake.

/retest

**Comment by sdodson** [comment]
/override ci/openshift-jenkins/extended_conformance_install
Bug on that https://bugzilla.redhat.com/show_bug.cgi?id=1902067
/override ci/openshift-jenkins/cmd

**Pull request merged**
