### PR TITLE
add cakephp back in with upstream fix landing

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
hitting cluster setup flakes in early failures

**Comment by gabemontero** [comment]
more install on gcp pain

while try a single test in case that helps minimize the gcp pain

/test e2e-gcp-image-ecosystem

**Comment by gabemontero** [comment]
image eco passed, including the readded tests

/assign @adambkaplan 

/retest

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
