### PR TITLE
remove unused privileged clients from master config

### PR DESCRIPTION
**Pull request by mfojtik**
[test]

@deads2k FYI

### CODE REVIEW

**Comment by deads2k** [comment]
This is beautiful.

lgtm [merge]

**Comment by mfojtik** [comment]
@deads2k we're back in business

**Comment by mfojtik** [comment]
re-[test]

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/14385

re-[test]

**Comment by deads2k** [comment]
No conflicts with the head of queue or commits merged the base.

**Pull request merged**
