### PR TITLE
fix tsb error message

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by bparees** [comment]
opened issue https://github.com/openshift/origin/issues/15035
[merge]

**Comment by bparees** [comment]
repo mirror issue.  @stevekuznetsov not sure if it's worth you looking at?

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1227/testReport/junit/(root)/Verify%20upgrade%20targets/_localhost__Check_latest_available_OpenShift_RPM_version/

```
{u'package_found': False, u'returncode': 1, u'stdout': u'Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was \nNo timestamp for file\n', u'cmd': u'/usr/bin/repoquery --plugins --quiet --pkgnarrow=repos --queryformat=%{version}|%{release}|%{arch}|%{repo}|%{version}-%{release} --config=/tmp/tmp4WjReN origin', u'results': {}, u'stderr': u'Repository centos-openshift-origin is listed more than once in the configuration\nRepository centos-openshift-origin-testing is listed more than once in the configuration\nRepository centos-openshift-origin-debuginfo is listed more than once in the configuration\nRepository centos-openshift-origin-source is listed more than once in the configuration\nFile /var/cache/yum/x86_64/7Server/epel/metalink.xml does not exist\n'}
```

[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/15039 [merge]

**Comment by stevekuznetsov** [comment]
@sosiouxme @rhcarvalho depends on how you guys want to handle the above -- unclear how often customers will hit the weird `yum` mirror stuff but it may be nice to gloss over that in the check, unclear.

**Comment by sosiouxme** [comment]
@stevekuznetsov I don't think this was actually one of the checks, it was just a random repoquery by an upgrade task:

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1227/consoleText

```
TASK [Check latest available OpenShift RPM version] ****************************
task path: /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/pre/verify_upgrade_targets.yml:16
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-07-04 16:15:55.100249", 
    "msg": {
        "cmd": "/usr/bin/repoquery --plugins --quiet --pkgnarrow=repos --queryformat=%{version}|%{release}|%{arch}|%{repo}|%{version}-%{release} --config=/tmp/tmp4WjReN origin", 
        "package_found": false, 
        "results": {}, 
        "returncode": 1, 
        "stderr": "Repository centos-openshift-origin is listed more than once in the configuration\nRepository centos-openshift-origin-testing is listed more than once in the configuration\nRepository centos-openshift-origin-debuginfo is listed more than once in the configuration\nRepository centos-openshift-origin-source is listed more than once in the configuration\nFile /var/cache/yum/x86_64/7Server/epel/metalink.xml does not exist\n", 
        "stdout": "Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was \nNo timestamp for file\n"
    }
}
```

Regardless, yum usage is mainly succeed/fail... there's not much way to get a structured error message and so you're left with parsing the human-readable text if you want to know what happened. I think it would likely be a good idea to make it standard to retry so that little blips in repo availability don't torpedo a long install/upgrade... possibly even clear the yum cache and retry when there's an error.

**Comment by stevekuznetsov** [comment]
Oh sorry, totally misunderstood that task title. Agreed re: bad messages. All of the RPM tools are written in Python so some part of that communication issue stems from Python --> shell --> Python :(

**Pull request merged**
