### PR TITLE
SCC check API: refactor

### PR DESCRIPTION
**Pull request by sdminonne**
@mfojtik  ref #8199 and #8776
FYI @deads2k

### CODE REVIEW

**Comment by sdminonne** [comment]
[test]

**Comment by sdminonne** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by sdminonne** [comment]
re[test]

**Comment by soltysh** [comment]
LGTM [merge]

**Comment by soltysh** [comment]
Flake appears to be related to #11016.

re-[merge]

**Pull request merged**
