### PR TITLE
Allow recursive DNS to be enabled via a config flag

### PR DESCRIPTION
**Pull request by smarterclayton**
Paves the way for making this a cluster config option.

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test] @liggitt

**Comment by smarterclayton** [comment]
@sosiouxme judging by upstream conversations I want to make this optional, but disabled by default.

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/10455/console
looks like it hung, we need timeouts on integration tests

**Comment by sosiouxme** [comment]
Agreed so that the default is not an open resolver. I understood though
that upstream was going to change the default insertion so that
/etc/resolv.conf in pods just points at master DNS. I agree with the logic
that doing this fixes DNS in various use cases, however this would break
DNS even worse without the master DNS being recursive; so should those two
settings (recursive DNS <=> only-master DNS) be bound to the same option?

**Comment by liggitt** [comment]
> I understood though that upstream was going to change the default insertion so that /etc/resolv.conf in pods just points at master DNS

They did, we're carrying a patch that preserves our old behavior.

Recursive DNS is set on the master, only-master DNS is determined by the node, and is currently not configurable

**Comment by smarterclayton** [comment]
@liggitt is that flag in our rebase?

**Comment by liggitt** [comment]
They didn't make it a flag, they made it the only option. Our carry makes "master+host" resolv.conf the only option... do you need a config flag in the node config as well for this? :-/

**Comment by smarterclayton** [comment]
I hate this.

**Comment by smarterclayton** [comment]
@liggitt any more comments?

**Comment by smarterclayton** [comment]
silence is consent [merge]

**Comment by liggitt** [comment]
aaaaaand I just made it to my 9:30am emails. what did @sdodson and you decide yesterday about how the node dns setup should interact with this?

**Comment by liggitt** [comment]
no other concerns about this PR specifically, just wondering if the node will break if we turn on recursive lookups

**Comment by sdodson** [comment]
> aaaaaand I just made it to my 9:30am emails. what did @sdodson and you decide yesterday about how the node dns setup should interact with this?

We decided nodes will run dnsmasq routing cluster.local queries to the kube svc IP, other queries routed to the node's upstream resolvers. The node will be configured to use dnsmasq thus providing host level access to skydns. dnsmasq will only be available via local interfaces, no iptables rules opening port 53 on the node. We'll set the clusterDNS ip to the local node's ip address so pods use dnsmasq too.

One side effect of this is that we're leaking the node's ip address into pods, is that a concern?

I'm not sure what to do about the carry where we add clusterDNS + host's resolvers. If sky dns isn't recursing by default it seems like we'd want to leave it as it is right now. If we could default to recursing and assume that non dev environments will be configured via ansible disabling recursion and ensuring dnsmasq is deployed we could drop the carry.

**Comment by smarterclayton** [comment]
That seems a scary change for existing clusters - not sure we can do
that seamlessly.

Suggest we continue to have recursion default false and get the local
DNSmasq in place.

**Comment by sosiouxme** [comment]
On Wed, Feb 10, 2016 at 4:11 PM, Jordan Liggitt <notifications@github.com>
wrote:

> no other concerns about this PR specifically, just wondering if the node
> will break if we turn on recursive lookups
>
The node should not break with recursive lookups on; it should actually
work better. Would recommend it for deployments not on the open internet.

**Pull request merged**
