### PR TITLE
bypass oc.Run() --follow --wait output flakes

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/9185

@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, though i thought at some point @PI-Victor and @mfojtik had convinced me with that "--wait" you should never hit a timeout waiting for the logs from "--follow".  We do this pattern in a lot of places.

**Comment by gabemontero** [comment]
I wouldn't characterize what I saw as a timeout waiting for logs.  It looked more like some data got lost when gathering build output via `oc.Run("start-build").Args(..., "--follow", "--wait").Output()`

When it reproduced locally, when this missing data situation occurred, before failing the test, I ran an `oc logs -f bc/...`, and when getting the full output that way, found the specific strings that were missing from the output gathered via `oc.Run(...).Output()`

**Comment by gabemontero** [comment]
After reproducing several times in a row when using `--follow` from `oc.Run()`, with the changes in this PR, the test then passed consistently.

**Comment by bparees** [comment]
> When it reproduced locally, when this missing data situation occurred, before failing the test, I ran an oc logs -f bc/..., and when getting the full output that way, found the specific strings that were missing from the output gathered via oc.Run(...).Output()

interesting.  does it seem like the --follow was missing entries from the top of the log file? the end of the log file?

**Comment by gabemontero** [comment]
Both before and after.

**Comment by bparees** [comment]
@gabemontero that's a little terrifying....

**Comment by gabemontero** [comment]
Well, perhaps I'm misreading something :-)  Perhaps in the error condition, the output produced is not the full build output as I was expecting.  Once I saw the desired string in the full build output, I just went down that path.

Here is an [instance on jenkins](https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/230/testReport/junit/%28root%29/Extended/_builds__Slow__the_s2i_build_should_support_proxies_start_build_with_broken_proxy_should_start_a_build_and_wait_for_the_build_to_to_fail/) if you want to see for yourself.

My local repos had the same look and feel.

**Comment by bparees** [comment]
>  Perhaps in the error condition, the output produced is not the full build output as I was expecting.

yeah so in the example you provided, the "log output" of "sample-build-1" probably is not the actual log output, it's probably some other output being returned by the start-build command (likely the name of the build it started).  why it didn't wait/output the log i'm not sure, but at least it is probably not a partial log, it's something else entirely, i suspect.

**Comment by gabemontero** [comment]
The test failure was a deployments extended test in the conformance run - unrelated to the extended test changed here.

**Comment by gabemontero** [comment]
@bparees - so I ran the scenario from the command line, and the output produce there matches what was seen in the extended test, and confirms your speculation.

Unless we think the start-build error message is incorrect (I don't know the history, but it seems like an OK message to me - perhaps errors are getting wrapped in errors when that was not originally the case, but reasonable minds could argue on the cleaner of the current message vs. the greater detail of the other one), then I think to confirm the intent of this test case, which is to ensure that the bad proxy definition was detected, the full build logs need to be scanned, and hence this PR's changes are goodness.  

Typically, we would tell users to dump the build logs, no?

**Comment by bparees** [comment]
yeah, so it seems like what happened here is that the build failed before we even attempted to wait for it, and so you get an error that you can't wait for a failed build.  it's not ideal, but i'm not gonna worry about it... agree that your fix is the right answer for making the test more robust.

and it probably only affects cases where we expect the build to fail as part of the test, so we shouldn't need to update other places where we're doing the --wait --follow pattern.

good find!

**Comment by gabemontero** [comment]
cool - thanks!

With the failed/unrelated test while waiting to merge, we need to resubmit the merge comment, no?

**Comment by bparees** [comment]
nope, it'll still attempt to merge it once it gets to the top of the queue.  the testing while in queue is just to save time so that if someone hits the "merge all the successfully tested PRs" button, the PR will be mergeable.  failing that test doesn't prevent it potentially merging via the normal process.

**Comment by gabemontero** [comment]
OK cool thx.

**Comment by gabemontero** [comment]
@bparees with the merge job aborted can you repost the merge comment?
Thanks.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
The integration run of the merge / test_pr_origin job hit https://github.com/openshift/origin/issues/9213

**Comment by bparees** [comment]
[merge]

**Comment by smarterclayton** [comment]
The behavior of the client command is wrong - we shouldn't be failing out, we should be reporting the build failed and dumping the logs.  Please open an issue to fix start-build.

**Comment by bparees** [comment]
@smarterclayton https://github.com/openshift/origin/issues/9452

**Pull request merged**
