### PR TITLE
Fixes panic on round tripper when TLS under a proxy

### PR DESCRIPTION
**Pull request by fabianofranz**
@ncdc PTAL. I'll open upstream if it makes sense.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1336337
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1323666

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by ncdc** [comment]
I don't think this will make things any worse 😉

There needs to be a corresponding upstream pull to Kube and then this needs to turn into an UPSTREAM commit

**Comment by ncdc** [comment]
@liggitt

**Comment by fabianofranz** [comment]
@ncdc updated to UPSTREAM PR https://github.com/kubernetes/kubernetes/pull/25690.

**Comment by liggitt** [comment]
LGTM, would like a test. Did you sweep the generic proxy handler to make sure a similar fix is not needed?

**Comment by fabianofranz** [comment]
@liggitt @ncdc Unfortunately I don't think this can be properly tested. I'd need a certificate from a trusted authority [here](https://github.com/fabianofranz/origin/blob/5c8e213996bff40da08204e967bc185aa7bc5f39/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/roundtripper_test.go#L46), so that I could set `clientTLS` to `nil` in the test case to test if it would trust based on the system (instead of having to provide a `RootCA`). Do you foresee any other strategy?

**Comment by liggitt** [comment]
I actually meant expecting an error rather than a panic

**Comment by fabianofranz** [comment]
@liggitt Of course. You have to set `clientTLS` to `nil` in the test case to simulate [this](https://github.com/fabianofranz/origin/blob/5c8e213996bff40da08204e967bc185aa7bc5f39/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/roundtripper.go#L128-L130) condition. It happens when you have a valid cert authority (so [no explicit cert provided by config, nor insecure](https://github.com/fabianofranz/origin/blob/5c8e213996bff40da08204e967bc185aa7bc5f39/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport/transport.go#L55-L57)).

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
