### PR TITLE
disable autoscaling v2alpha1 by default

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/14935

@mfojtik @DirectXMan12 

@bparees this is the group I was talking about.  Not sure if you use it or not.

### CODE REVIEW

**Comment by bparees** [comment]
not aware of us using any of those in oc cluster up today.  @csrwng ?

**Comment by deads2k** [comment]
[test]

**Comment by sttts** [comment]
/ref https://github.com/openshift/origin/issues/13732

lgtm

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
[severity:blocker]

**Comment by deads2k** [comment]
hmmm. I think you're tagged right.  re[merge]

**Pull request merged**
