### PR TITLE
Bug 1703885: test/extended/router: Fix curl timeout, log dumping, template parameters, and router readiness probes

### PR DESCRIPTION
**Pull request by Miciah**
#### `test/extended/router`: Fix curl timeout logic

Fix `waitForRouteToRespond`, `waitForRouterOKResponseExec`, and `expectRouteStatusCodeRepeatedExec` to honor their timeout parameter values and to specify a timeout for each curl invocation.

Before this change, each function used its timeout parameter value as the number of times to retry the curl command and did not specify a timeout value to that command.  As a result, each command invocation could keep trying indefinitely, and the function could keep retrying the command for far longer than the timeout period that the caller indicated.

Follow-up to https://github.com/openshift/origin/pull/12346 and https://github.com/openshift/origin/pull/19073.

* `test/extended/router/config_manager.go` (`waitForRouteToRespond`):
* `test/extended/router/scoped.go` (`waitForRouterOKResponseExec`)
(`expectRouteStatusCodeRepeatedExec`): Keep retrying until the amount of time that is indicated by the timeout value has elapsed.  Specify a timeout value of 5 seconds to curl using the `-m` option.

#### `test/extended/router/unprivileged`: Fix log dump

Fix the prefix for the pod name used in the unprivileged router test so that the pod's logs will be dumped on test failures.

Follow-up to https://github.com/openshift/origin/pull/21557.

* `test/extended/router/unprivileged.go`: Call `DumpPodLogsStartingWith` with the "router-" prefix instead of the "unprivileged-router" prefix.

#### `test/extended/router`: Delete `SCOPE` template param

Delete the `SCOPE` template parameter in the various router template fixtures, and add `ROUTER_NAME` (default value "test-scoped") and `UPDATE_STATUS` (default value "true") parameters to the `router-scoped.yaml` template fixture.

Most tests were not using the `SCOPE` parameter, and in the one test that did, its use evoked the following warning from `oc new-app`:

    warning: --param no longer accepts comma-separated lists of values.

* `test/extended/router/unprivileged.go`:
* `test/extended/testdata/router/router-scoped.yaml`: Replace the `SCOPE` template parameter with `ROUTER_NAME` and `UPDATE_STATUS` parameters.
* `test/extended/testdata/router/router-override-domains.yaml`:
* `test/extended/testdata/router/router-override.yaml`: Delete the `SCOPE` parameter.
* `test/extended/testdata/bindata.go`: Regenerate.

#### `test/extended/router`: Enable metrics, fix readiness

Fix the router template test fixtures that use the router's `/healthz/ready` endpoint for their readiness probes to enable HAProxy metrics, which are required for the endpoint to return OK.

Without HAProxy metrics enabled, the router pods that tests created using these fixtures never became ready.

Follow-up to https://github.com/openshift/origin/pull/21592.

* `test/extended/testdata/router/router-override-domains.yaml`:
* `test/extended/testdata/router/router-override.yaml`:
* `test/extended/testdata/router/router-scoped.yaml`: Enable HAProxy metrics.
* `test/extended/testdata/bindata.go`: Regenerate.

### CODE REVIEW

**Comment by Miciah** [comment]
[Suite:openshift/test-cmd][Serial][Disruptive] test-cmd: test/cmd/policy-storage-admin.sh [Suite:openshift] expand_less	18s
    fail [github.com/openshift/origin/test/extended/cmd/cmd.go:117]: Expected
        <[]error | len:1, cap:1>: [
            {
                s: "error waiting for the pod 'test-cmd' to complete: the pod errored trying to run the command",
            },
        ]
    to have length 0

/test e2e-cmd

**Comment by ironcladlou** [comment]
/approve
/lgtm

Thanks, this looks helpful

**Comment by Miciah** [comment]
I'm hoping https://github.com/openshift/origin/pull/23622 will fix one of the test failures.

**Comment by ironcladlou** [comment]
Since it doesn't apply cleanly and since 4.1 EOL is approaching, it would be nice to understand 4.1's CI status going forward to help decide whether this is worth manually backporting...

**Pull request merged**
