### PR TITLE
Fix multicast test to run under ovs-networkpolicy plugin

### PR DESCRIPTION
**Pull request by danwinship**
We're currently testing multicast only on the multitenant plugin, but we should be testing it on ovs-networkpolicy too. (In particular, with conformance-gce now running ovs-networkpolicy, we should test that multicast works, rather than only testing that it *doesn't* work when you don't enable it.)

### CODE REVIEW

**Comment by smarterclayton** [comment]
This *just* broke the GCP publish job.  I'm reverting because I need to publish new openshift ansible images so we can make GCP blocking.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_openshift_ansible_extended_conformance_gce/374/

**Comment by smarterclayton** [comment]
Sorry, hopefully this will be something that can go in tomorrow once i have the new jobs up

**Comment by danwinship** [comment]
Sorry, I was assuming this wouldn't merge yet because it would break the tests, but it appears to have merged without ever actually passing tests?

**Comment by smarterclayton** [comment]
GCP isn't blocking this week (sent an email on monday)

**Comment by smarterclayton** [comment]
GCP is blocking now, you should be free to reenable this (and the GCP test should run on your PR and block merge if it also breaks again)

**Pull request merged**
