### PR TITLE
Remove generated name from container ports

### LINKED ISSUE #3755: `oc new-app` should not generate port names for containers
`oc new-app` will generate port names with hash values. Container port names are optional, and generated values are not useful.

```
oc new-app https://github.com/openshift/nodejs-ex
```
```
"ports":[{"name":"n-f65f834a-8080","containerPort":8080,"protocol":"TCP"}]
```

The web console removed generated port names in #3752.

@deads2k @liggitt

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3755

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k @csrwng PTAL

**Comment by deads2k** [comment]
I'm afraid that this will have unintended consequences when the value is later used to derive names for the `ServiceSpec.ServicePort[x].Name` that has different validation rules.  Is that chain entirely lost now?

**Comment by liggitt** [comment]
Updated service to generate a port name from the port number and protocol

**Comment by liggitt** [comment]
@smarterclayton this removes the generated name from containerports, and pins the generated name for service ports to "<port>-<protocol>". We don't generate endpoints from new-app... any other implications of the change to the generated ServicePort name?

**Comment by smarterclayton** [comment]
LGTM

**Comment by deads2k** [comment]
@spadgett does the web console need to resync on this?

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by spadgett** [comment]
@deads2k #3752 has the same change for the web console.

**Comment by deads2k** [comment]
> @deads2k #3752 has the same change for the web console.

I'm not seeing it.  The `ServiceSpec.ServicePort[x].Name` has changed, not just the container port.

**Comment by liggitt** [comment]
Just checked... the UI is only generating a single service port currently, and leaving it nameless (which is allowed for a single port). Not sure what the reason for that was, but @spadgett should open an issue to track making the UI consistent (expose all container ports as named service ports)

**Comment by liggitt** [comment]
Spawned https://github.com/openshift/origin/issues/3764

**Pull request merged**
