### PR TITLE
An example configuration that applies files to all nodes

### PR DESCRIPTION
**Pull request by smarterclayton**
Create the three files, and then the "ops" container in the daemonset
will periodically update the provided files. Rotation can be managed by
the process as well.

@kwoodson @twiest example, tested locally

### CODE REVIEW

**Comment by smarterclayton** [comment]
@derekwaynecarr

**Comment by smarterclayton** [comment]
@eparis what i mentioned today

**Comment by kwoodson** [comment]
@twiest @mwoodson @smarterclayton, what do you see as the next steps here?  

I envision that we create an openshift_ops_monitoring_role that does the following:
- said role manages the configmap (oc_configmap module to manage idempotency)
When ConfigMap updates, is a container restart required?
If so, we detect changes and trigger an update.  What does this process look like with a daemonset?
- module to manage daemonset idempotency
- add this role to the config loop
- update the daemonset image to point to our rhel7 building image
- update the configmap with the real settings

Some questions to think about:
- Can this be a generic way to deliver files to the node? I saw you mentioned the registry cert.
- Since masters are unschedulable, how do daemonsets apply to masters?
- Is this our strategy for running only on scale groups until prometheus lands?
- What's the timeline for prometheus? Could effort be put in to move us to prometheus faster?

Thanks for this @smarterclayton.  This pattern seems superior to the alternatives.

**Pull request closed without merging**
