### PR TITLE
extended: do not run suites if FOCUS is given

### PR DESCRIPTION
**Pull request by miminar**
Also make sure not to run serial tests that have been run among parallel ones already.

Do not use `-suite` when `FOCUS` is given.

### CODE REVIEW

**Comment by miminar** [comment]
Note that the following will fail because #15807 is still not merged:

/test extended_image_registry

**Comment by bparees** [comment]
/unassign @danwinship @jim-minter 
/assign @smarterclayton 

lgtm but needs review by the keepers of the extended test framework execution logic.

**Comment by smarterclayton** [comment]
This is really complex, not sure I want this much code to solve this problem.

**Comment by miminar** [comment]
Obsoleted by #16919

**Pull request closed without merging**
