### PR TITLE
Support multiple Dockerfiles with custom-docker-builder

### PR DESCRIPTION
**Pull request by colemickens**
This would enable me to use the custom docker build with my project that utilizes many dockerfiles at the same level in a repository to build various docker images from one repo.

### CODE REVIEW

**Comment by pmorie** [comment]
Suggest a more descriptive name for this PR/commit

LGTM otherwise, @bparees ?

**Comment by bparees** [comment]
yeah please squash and update the descriptions on your commits, but it looks good otherwise.

**Comment by colemickens** [comment]
Fixed.

**Comment by bparees** [comment]
[merge]

**Comment by colemickens** [comment]
Small question, what's the publish cadence for that Dockerfile?

**Comment by bparees** [comment]
it's automated by pushes to the repo, so you should be good to pick it up:
https://registry.hub.docker.com/u/openshift/origin-custom-docker-builder/builds_history/127163/

**Comment by colemickens** [comment]
So, I fear that this was a bad change to introduce. The openshift/origin-custom-docker-builder image is based on openshift/origin-base which is based on centos:centos7 which ships docker 1.3. The `-f` option was added in docker 1.5.

My apologies for not testing this more thoroughly before submitting. I'm currently proceeding with a custom builder that I'm testing locally, and then I can revisit this.

In this case, should I submit a PR backing out my change, or will a maintainer do so for me?

**Comment by bparees** [comment]
yeah that dawned on me a few hours ago, but I was hoping by some miracle centos was on 1.5 :)

i'll revert it.

**Comment by colemickens** [comment]
Reverted by #1177. Thanks.

**Comment by colemickens** [comment]
Reverted by #1177.

**Pull request merged**
