### PR TITLE
refactor commits for emptyDir to match upstream PRs

### PR DESCRIPTION
**Pull request by pmorie**
@deads2k

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@deads2k PTAL -- let me know your thoughts.  I have some little cleanups to do but they should be no problem if this looks good to you.

**Comment by pmorie** [comment]
Cc @smarterclayton

**Comment by deads2k** [comment]
So clean!

Can you the first bit of the sha to the main part of the commit so it smacks the rebaser more fully when they're pairing commits?  You has asked about squashing the reverts before.  I don't really care one way or the other.  I'm just happy to have them manageable.

**Comment by deads2k** [comment]
and sanity returns!  [merge]

**Pull request merged**
