### PR TITLE
Remove erroneous instance of `${OS_IMAGE_COMPILE_GOFLAGS}`

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton I think you forgot this in https://github.com/openshift/origin/pull/12430

[test]

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I don't think we understand [merge] in a review.

**Comment by smarterclayton** [comment]
Wondered about that.

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/13057/) failed from the following flakes:
 - [integration](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10272/consoleFull#-19549555635762928fe4b031e1b25ced2a) failed on: #12558 

re[merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/13079/) failed from the following flakes:
 - [integration](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10300/consoleFull#-21289005105762928fe4b031e1b25ced2a) failed on: #12558 

re[merge]

**Pull request merged**
