### PR TITLE
fix protobuff generation for pkg/sdn/api/v1/generated.proto

### PR DESCRIPTION
**Pull request by PI-Victor**
i think someone forgot to run this whenever they updated the file.
@bparees PTAL. 

p.s: also i don't think we do a good job checking for this as we do for swagger-specs/desc, any ideas for a fix?

### CODE REVIEW

**Comment by PI-Victor** [comment]
@bparees 
i can write a script for this and make it part of `make verify`, however i need the protoc binary available in travis to run it when doing `make verify`. not sure if doing a wget to the pre-compiled binary would be the way to go?

**Comment by bparees** [comment]
@smarterclayton are we not already verifying protobuf generations?

@knobunc your team so defer to you for merging.

**Comment by knobunc** [comment]
LGTM.  @danw PTAL and merge.

**Comment by danwinship** [comment]
[merge]

**Comment by knobunc** [comment]
@bparees this is comments-only... is it worth getting in despite the freeze?

**Comment by bparees** [comment]
@knobunc your call, really, but if it were me i'd probably merge it since it's basically zero-risk.

**Comment by knobunc** [comment]
[merge]

**Comment by smarterclayton** [comment]
We are running the verifications but it looks like they are not working.  Please open a p1 issue for that.

**Comment by smarterclayton** [comment]
Fixed in https://github.com/openshift/origin/pull/10703, will be merged after it.

**Pull request merged**
