### PR TITLE
Bug 1695554 - SDN may be very slow to start up after a reboot

### PR DESCRIPTION
**Pull request by danwinship**
Cleaning up pods on startup may involve doing CNI DELETEs. When Multus is in use, this will require making apiserver calls, and it will try to use the kubernetes service IP, which openshift-sdn may not have set
up yet, resulting in network errors and timeouts. Fix this by doing the deletes in a goroutine, so SDN can continue initializing and set up the proxy.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695554

### CODE REVIEW

**Comment by danwinship** [comment]
@dcbw: my initial fix, but maybe we want to fix this by pointing multus at the "real" apiserver instead (hence the wip tag)

**Comment by danwinship** [comment]
hrmph
/hold

**Comment by dcbw** [comment]
@danwinship I think we should do both?
/lgtm

**Pull request merged**
