### PR TITLE
Fix logic to determine whether nsenter mounter should be used

### LINKED ISSUE #18050: cluster up fails with latest Docker for Mac
`oc cluster up --version=latest` hangs with the latest Docker for Mac version. Docker for Mac has switched VM file formats from qcow to raw in this release, which might be related.

Here is my origin container log:

[origin.log](https://github.com/openshift/origin/files/1619639/origin.log)

##### Version

Docker for Mac Version 17.12.0-ce-mac46 (21698)

oc v3.9.0-alpha.1+a90f8af-96
kubernetes v1.9.0-beta1
features: Basic-Auth

##### Steps To Reproduce
1. Install latest stable Docker for Mac version
2. Run "oc cluster up --version=latest"

##### Current Result
Cluster up hangs waiting fo the web console pod to start.

/kind bug
/priority p1
/assign @csrwng

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #18050

### CODE REVIEW

**Comment by csrwng** [comment]
/unassign @jim-minter 
/unassign @coreydaley 
/assign @soltysh 
/assign @juanvallejo 

This fixes really bad logic to determine whether to use the nsenter mounter on cluster up. I'm sure it made sense at some point and has degraded over time.

/cc @spadgett

**Comment by spadgett** [comment]
I tested and can confirm this fixes the problem. Thanks!

**Pull request merged**
