### PR TITLE
Fix 'address already in use' errors in integration tests

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
Might fix https://github.com/openshift/origin/issues/1674

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k review. Not sure if this fixes the "already in use" error (it was very sporadic), but it at least doesn't seem to make it worse. We weren't closing the listener from the unstarted httptest server before, so I'm actually not sure how we ever successfully bound to the allocated port.

**Comment by deads2k** [comment]
worth a try.  [merge]

**Pull request merged**
