### PR TITLE
Moved LabelSelector and LabelFilter to their own bower component

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@liggitt review

**Comment by jwforres** [comment]
i'm the excluding font-awesome css that gets included from the dependency in kubernetes-label-selector since we have other magic to include font-awesome as part of patternfly

**Comment by jwforres** [comment]
ui spec tests are failing because of the added module dependency, will fix tomorrow

**Comment by smarterclayton** [comment]
This ready?

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
