### PR TITLE
dind: update to f24 (and go 1.6)

### LINKED ISSUE #9760: Networking tests are using Go 1.5
I tried to bump our min requirements in the build and the networking extended tests failed.  We don't work against Go 1.5 anymore and need to ensure we get Go updated properly.

```
[INFO] Targeting subnet plugin: redhat/openshift-ovs-subnet
[INFO] Launching a docker-in-docker cluster for the subnet plugin
Cleaning up docker-in-docker containers
Cleanup up configuration to avoid conflict with a future cluster
Cleaning up volumes used by docker-in-docker daemons
Configured network plugin: redhat/openshift-ovs-subnet
Ensuring compatible host configuration
Launching containers
Provisioning nettest-master
Adding '172.17.0.3	nettest-node-1' to hosts file
Adding '172.17.0.4	nettest-node-2' to hosts file
Building openshift

Detected Go version: go version go1.5.4 linux/amd64.
Origin builds require Go version 1.6 or greater.

[ERROR] PID 164: hack/common.sh:258: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:258: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:31: os::build::build_binaries
[INFO]   Exiting with code 2.
[INFO] Saving cluster configuration
```

### PR DESCRIPTION
**Pull request by marun**
Fixes #9760

### CODE REVIEW

**Comment by marun** [comment]
[testextended][extended:networking]

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by danwinship** [comment]
LGTM [merge]

**Comment by marun** [comment]
flake #9681 

re-[merge]

**Pull request merged**
