### PR TITLE
reconnect --image (bug 1196982)

### PR DESCRIPTION
**Pull request by deads2k**
The --image flag was bound, but dropped from the origin.MasterConfig object.  I've reconnect them.

@sdodson Can you confirm success?
@liggitt Can you review?
@brenton Want to assign the bugzilla defect to me?

I'll look to see if there's some reasonable test we can add (obviously there wasn't one before), but i'd like to get reviews on the actual change moving ahead.

### CODE REVIEW

**Comment by liggitt** [comment]
ImageFormat, LatestReleaseImages are not hooked up either

**Comment by deads2k** [comment]
> ImageFormat, LatestReleaseImages are not hooked up either

See, I'll bet you thought that those were wired up before our change (7b38bcfd022405c40e1756daec57a67b9d0ff67f)....  Near as I can tell, they weren't

**Comment by liggitt** [comment]
you're right... stopped being used in cfe9d1ef. please remove them so I can be less confused :)

**Comment by sdodson** [comment]
It'd be very helpful to log the value on startup as we did before too. See https://github.com/liggitt/origin/commit/9a80a301e916b394c087e46ad3887d13c708d3ba#diff-d4dc54f7fce1452a5e0513db45344018L296

I'm not sure if --latest worked, I never used i.

**Comment by deads2k** [comment]
> please remove them so I can be less confused

removed



> It'd be very helpful to log the value on startup as we did before too.

logging now

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
@sdodson --images worked for you, correct?  I got

```
openshift start --images=docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-${component}:v0.3.3

Using images from "docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-:v0.3.3"
```

```
openshift start --latest-images

Using images from "openshift/origin-<component>:latest"
```

and 
```
openshift start

Using images from "openshift/origin-<component>:v0.3.3"
```

**Comment by sdodson** [comment]
@deads2k looks good, thanks for the quick turn around.

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
server start dial error on the asset server.  Should be fixed by https://github.com/openshift/origin/pull/1176

re[merge]

**Pull request merged**
