### PR TITLE
added go vet composite literals testing

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt This adds `go tools vet -composites`

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by liggitt** [comment]
lgtm, [merge]

**Comment by liggitt** [comment]
rebase

**Comment by stevekuznetsov** [comment]
@liggitt rebased

**Comment by liggitt** [comment]
LGTM, [merge]

**Pull request merged**
