### PR TITLE
ipfailover - control preempt strategy

### PR DESCRIPTION
**Pull request by pecameron**
This allows the admin to control the VRRP preempt strategy.
The default strategy, preempt_delay <sec>, switches to the higher
priority master after a <sec> (default 300) delay. The second
strategy, nopreempt, suppresses switchin when a higher priority host
becomes available.

The 'oc adm ipfailover --preempt-strategy' option can set the desired
strategy. --preempt-strategy sets the OPENSHIFT_HA_PREEMPTION
environment variable.

bug 1465987
https://bugzilla.redhat.com/show_bug.cgi?id=1465987

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc PTAL

**Comment by knobunc** [comment]
@openshift/networking FYI

**Comment by knobunc** [comment]
`FAILURE: Generated completions out of date. Please run hack/update-generated-completions.sh`

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
