### PR TITLE
Statically compile OpenShift

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
That looks like a no.

**Comment by smarterclayton** [comment]
I have to add glibc-static to the release image.  Not a priority right now.

**Comment by kargakis** [comment]
Can run oc in alpine/scratch finally

**Comment by smarterclayton** [comment]
Which is kind of a non-goal, which is partially why I'm not sure when we might need this.  Not sure exactly how this will play with FIPS and CC either.

**Pull request closed without merging**
