### PR TITLE
suggest can-i for what-can-i-do

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/9051.

@kargakis ptal,  will open upstream.

### CODE REVIEW

**Comment by deads2k** [comment]
upstream at https://github.com/spf13/cobra/pull/285

**Comment by kargakis** [comment]
Can you also rename whatcanido.go to cani.go?

**Comment by deads2k** [comment]
> Can you also rename whatcanido.go to cani.go?

done

**Comment by kargakis** [comment]
LGTM [merge]

@mfojtik you should be able to rebase without any conflicts on top of this

**Comment by deads2k** [comment]
removed merge tag.  Upstream unit tests discovered that a nested command that has subcommands AND an implementation always fails here.

As a for instance: `oc create foo`.  That should fail because create doesn't take args, but it actually fails because there's no subcommand for it.  Must be why they have that check.  To my knowledge, there's no flag saying, "this is just a container for other commands", but I'll take a deeper look.

**Comment by kargakis** [comment]
@deads2k is this still blocked on upstream work?

**Comment by deads2k** [comment]
Yes I think we want spf13/cobra#284 and then maybe one more followup.

**Pull request closed without merging**
