### PR TITLE
Drop service IP check at SDN master startup

### PR DESCRIPTION
**Pull request by danwinship**
At startup, the SDN master does a bunch of sanity checks on the network configuration, one of which is making sure that all Services have ClusterIPs inside the serviceNetworkCIDR. However, given that we don't allow making changes to serviceNetworkCIDR anyway, this is mostly redundant.

It also makes life really difficult if you want to try to forcibly change serviceNetworkCIDR behind OpenShift's back (https://trello.com/c/mb9sKIUR). In theory, you ought to be able to delete all services, change serviceNetworkCIDR, restart the master, restart all the nodes, and then recreate the services. But that doesn't actually work, because the "kubernetes" service gets recreated automatically any time you delete it, so when you get to the "restart the master" step, it will fail, because there will be an existing "kubernetes" service in the old serviceNetworkCIDR.

@openshift/networking PTAL, especially @pravisankar since you initially added this check (in https://github.com/openshift/openshift-sdn/pull/195). The issue it refers to (https://github.com/openshift/openshift-sdn/issues/194) doesn't give any reason why this was something we felt we needed to prevent the user from doing in code, rather than just saying "well don't do that then"...

### CODE REVIEW

**Comment by knobunc** [comment]
Should we at least print a warning?  What will happen without the check?  Will the service IP addresses be reassigned?  Or will they just not work?

**Comment by danwinship** [comment]
They won't work.

We *could* print a warning, but should we? You need to do at least two unsupported things in a row to get to this point (deleting the default ClusterNetwork and then changing serviceNetworkCIDR), and there are several additional steps you'll need to do to get things working again after this (restarting all the nodes, etc). So, either you know exactly what you're doing and you don't need a warning, or you have absolutely no clue what you're doing and you need a lot more than just a warning...

I also considered treating the "kubernetes" service specially, and skipping the check if that was the only service defined, but still erroring out if any *other* services with bad IPs were defined. But that results in a slightly more complicated migration procedure. (You need to delete all services before changing serviceNetworkCIDR, then restart, then delete the "kubernetes" service *again*.)

For comparison, note that we do not validate that pod IP addresses are inside clusterNetworkCIDR. (Though we *do* validate that HostSubnet subnets are inside clusterNetworkCIDR... that doesn't create any problems for us though, so I didn't remove it.)

**Comment by knobunc** [comment]
The only advantage to a warning is that if someone more expert is digging through the logs to try to work out why the customer is screaming, there's a hint there.

**Comment by dcbw** [comment]
I'd go for warning too, it would make debugging this crystal clear when somebody shoots themselves in the foot and comes back to us for help...

**Comment by danwinship** [comment]
OK, thinking about it a little, since the "Service is not in serviceNetworkCIDR" case can only happen after deleting and recreating ClusterNetwork, and since there are also other ways you can shoot yourself in the foot by doing that, I made it log an error when it recreates ClusterNetwork. In this case "recreating ClusterNetwork" is defined as "creating ClusterNetwork when a default NetNamespace already exists". Oh, but that won't catch anything in the single-tenant case... I guess I could check whether any HostSubnets exist instead? I don't think we can base it on whether the "kubernetes" service exists, because that gets created very very early. Maybe we should do multiple tests... Thoughts?

**Comment by danwinship** [comment]
This was split out from a larger startup validation PR, and I'm going to merge it back in to that and resubmit...

**Pull request closed without merging**
