### PR TITLE
Skip the HAProxy config manager until it is deflaked

### PR DESCRIPTION
**Pull request by smarterclayton**
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_extended_conformance_install/13740/

### CODE REVIEW

**Comment by smarterclayton** [comment]
@ironcladlou @ramr this is causing some pile ups in the queues, disabling while you investigate.

**Comment by ramr** [comment]
@smarterclayton  looked at this a wee bit earlier. That error seems to point to a missing service.
So either that the service has suddenly disappeared in the middle of the run (which would be odd) or there's some other error being sent to the oc client and it is not being reported at:
https://github.com/openshift/origin/blob/master/pkg/oc/cli/create/route/route.go#L27

There is no indication of a service going away in the router logs - would have expected the endpoints to go away for routes using that service (unless the watch didn't yet get that notification).

**Comment by smarterclayton** [comment]
Where is that service created?

**Comment by ramr** [comment]
In the config manager tests:  https://github.com/openshift/origin/blob/master/test/extended/router/config-manager.go
using https://github.com/openshift/origin/blob/master/test/extended/testdata/router-config-manager.yaml

**Comment by smarterclayton** [comment]
Batch passed, but didn't get merged - manual merge

**Pull request merged**
