### PR TITLE
Mount /var/log into node container

### PR DESCRIPTION
**Pull request by sdodson**
So that fluentd works properly

### CODE REVIEW

**Comment by sdodson** [comment]
@sosiouxme should this be :ro ? anything else you can think of we need to get logging components working in containerized environments?

**Comment by sosiouxme** [comment]
No, needs to be RW - the node creates symlinks in /var/log with kube metadata in the name that fluentd uses.

@richm I think you were the one that discovered this - was there anything else about /var/log permissions or anything that was required?

**Comment by richm** [comment]
@sosiouxme it was for the origin docs - https://github.com/richm/openshift-docs/commit/12bb34d11b27269ff6f6cf76f762eec2a41fce96
and yes, it has to be rw, because fluentd needs to write files that keep track of the log position

**Comment by sdodson** [comment]
@sosiouxme good enough to merge? We'll need to replicate this in the ansible installer anyway as it lays down its own modified services that run containerized node. I'll link that here once I've done it.

**Comment by sosiouxme** [comment]
@sdodson LGTM

**Comment by sdodson** [comment]
@brenton mind merging this? The equivalent has already been merged in ansible.

**Comment by brenton** [comment]
[merge]

**Pull request merged**
