### PR TITLE
move unrelated extended tests out of [images]

### PR DESCRIPTION
**Pull request by PI-Victor**
fixes: https://github.com/openshift/origin/issues/10375
@mfojtik is this ok, am i missing something?
cc @bparees

### CODE REVIEW

**Comment by mfojtik** [comment]
@PI-Victor it looks ok to me. @deads2k ?

**Comment by deads2k** [comment]
> @PI-Victor it looks ok to me. @deads2k ?

Still a little annoyed that we got kicked out of using our own API group for a tag, but not annoyed enough to fight for it.  [merge]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/9457 (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8036/) re[test]

**Comment by PI-Victor** [comment]
@deads2k was just trying to figure out if there's an issue open, thank you!

**Comment by bparees** [comment]
[testextended][extended:core(imageapis)]

**Comment by bparees** [comment]
this pr needed a slight tweak, redoing here:
https://github.com/openshift/origin/pull/10520

**Pull request closed without merging**
