### PR TITLE
UPSTREAM: ValidateSchema in visitors must check malformed JSON

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/3452

### CODE REVIEW

**Comment by fabianofranz** [comment]
[merge]

**Comment by liggitt** [comment]
@fabianofranz did this get reverted? can we get a test to make sure it stays fixed?

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@liggitt Tests added. This was fixed upstream, but with a different strategy: https://github.com/GoogleCloudPlatform/kubernetes/pull/9357.

**Comment by fabianofranz** [comment]
@liggitt Rebase with the solution from upstream. Tests added. Any other comment?

**Comment by liggitt** [comment]
to be clear, is this cherry picked from upstream, or a fix that needs to go upstream?

**Comment by fabianofranz** [comment]
@liggitt cherry-picked from upstream (and reverted the fix we previously did only here, not upstream)

**Comment by liggitt** [comment]
if a rebase is imminent, I'd rather wait to pick this up naturally. @smarterclayton?

**Comment by smarterclayton** [comment]
Rebase is imminent.

On Tue, Jun 30, 2015 at 2:08 PM, Jordan Liggitt <notifications@github.com>
wrote:

> if a rebase is imminent, I'd rather wait to pick this up naturally.
> @smarterclayton <https://github.com/smarterclayton>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3497#issuecomment-117287269>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fabianofranz** [comment]
Sounds good, I'll add just the tests after the rebase lands.

**Comment by fabianofranz** [comment]
Fixed by the latest rebase.

**Pull request closed without merging**
