### PR TITLE
osc describe is should show spec tags when status empty

### PR DESCRIPTION
**Pull request by smarterclayton**
Handle image streams without status.Tags

```
$ osc describe is/wildfly
Name:			wildfly
Created:		11 minutes ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2015-06-08T20:27:35Z
Docker Pull Spec:	openshift/wildfly-8-centos

Tag	Spec	Created		PullSpec				Image
latest		11 minutes ago	openshift/wildfly-8-centos:latest	3495ad898a5a8e0ce96c62410202c5bc42d7f8184dfe6c5d74d300e519e835bd
test	other			<n/a>					<n/a>
```

@spadgett

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@ncdc review

**Comment by ncdc** [comment]
LGTM

**Comment by smarterclayton** [comment]
Approved [merge]

**Pull request merged**
