### PR TITLE
Expose version as prometheus metric

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
@smarterclayton Anyone to look at this teeny PR?

**Comment by jimmidyson** [comment]
This PR allows us to build dashboards showing versions of openshift components deployed in the cluster, & useful for alerts to ensure cluster components are kept at consistent versions.

**Comment by smarterclayton** [comment]
Did you get an equivalent added to upstream Kube?

**Comment by jimmidyson** [comment]
Yeah - kubernetes/kubernetes#14407, merged.

**Comment by smarterclayton** [comment]
LGTM [merge].  Be sure any satellite binaries we create reference the version package (most should)

**Pull request merged**
