### PR TITLE
reenable static building of hello pod

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/5363

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal, w/ the refactor you did to the release scripts i don't think the goflags were being processed correctly anymore.  this attempts to fix it, but it may undo some of the refactoring you were trying to accomplish.

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
Let me test the release scripts and get back to you.

**Comment by bparees** [comment]
bump

**Comment by bparees** [comment]
rebump

**Comment by smarterclayton** [comment]
Why not?  LGTM [merge]

**Pull request merged**
