### PR TITLE
Fix for Bug 1211210 in the ui where the tile list for builder images don...

### PR DESCRIPTION
**Pull request by sg00dwin**
...'t clear correctly in some situations.

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres ready for review and merge

**Comment by jwforres** [comment]
@sg00dwin LGTM but it is missing bindata.go updates

**Comment by sg00dwin** [comment]
@jwforres: updated pr with bindata along with, animation css fix

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
@jwforres is this still in the queue to pass merge tests?

**Comment by jwforres** [comment]
re [merge]

**Pull request merged**
