### PR TITLE
Move verify-upstream-commits to a separate make target

### PR DESCRIPTION
**Pull request by soltysh**
One another cherry-pick of https://github.com/openshift/origin/pull/12056 against 1.3 branch, per @liggitt request. @stevekuznetsov fyi as well

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/10951

re-[test]

**Comment by soltysh** [comment]
Hmmm... the failures are not related to the changes I've introduced. I wonder if test worked with 1.3 in the first place, @stevekuznetsov you might know?

**Comment by stevekuznetsov** [comment]
Origin's tests are not set up to handle 1.3 -- we are testing everything with Docker 1.12, etc. Until I have more bandwidth or someone volunteers to help these tests are going to remain mostly meaningless.

**Comment by soltysh** [comment]
With that in mind I'm closing this PR, if needed ping me I'll re-open it.

**Comment by liggitt** [comment]
tests were passing in the 1.3 release branch as of https://github.com/openshift/origin/pull/11308#issuecomment-253707729

is there a way to lock the image used to test? it's important we have the ability to verify fixes against our release branches

**Comment by liggitt** [comment]
@danmcp, thoughts on origin CI jobs for release branches?

**Comment by danmcp** [comment]
@liggitt I would worry about the maintenance of them.  There are already a lot of previous release combinations we have a had time keeping running with the correct docker/golang.

**Comment by stevekuznetsov** [comment]
@liggitt there is a way, and we are using it in the OSE queue today. We just have to build from `base_ami` on every job -- if you have the time, looking at the OSE pull request job should give you the info you need to reconfigure all of Origin's jobs to do this. I just don't have the bandwidth for it right now.

**Comment by smarterclayton** [comment]
We really need release branches with CI.  Probably needs to be folded into the other work going on though given limited attention.

**Comment by stevekuznetsov** [comment]
With the caveat that run time will be much longer, we should be able to copy the logic from the OSE job to build non-branch tests from the base AMI. We'd also need to update Rosie.

**Comment by smarterclayton** [comment]
Waiting for us to look at summit queue or improving Jenkins pr builder
might be enough.  Alternatively we should backport docker incompatibility
bugs into the older branches.

On Dec 30, 2016, at 11:49 AM, Steve Kuznetsov <notifications@github.com>
wrote:

With the caveat that run time will be much longer, we should be able to
copy the logic from the OSE job to build non-branch tests from the base
AMI. We'd also need to update Rosie.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12118#issuecomment-269793685>,
or mute
the thread

**Comment by soltysh** [comment]
Closing due to age.

**Pull request closed without merging**
