### PR TITLE
UPSTREAM: 33489: Log test error

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
Wut, new flake?  Awesome

**Comment by liggitt** [comment]
nah, existing, fixed in https://github.com/openshift/origin/pull/11088

**Comment by liggitt** [comment]
known flake https://github.com/openshift/origin/pull/11088
upstream has lgtm, [merge]

**Pull request merged**
