### PR TITLE
Validate usernames don't contain problematic URL sequences

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton take a look. I want to change the auth layer to use a client interface, but want to wait until the rest refactor happens

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
@smarterclayton something is screwy with integration tests... wondering if it's related to the integration test changes. I see this in the jenkins run:
```
--- FAIL: TestUserInitialization (0.01 seconds)
	userclient_test.go:67: unexpected error: userIdentityMapping "" is invalid: [metadata.name: required value, user.metadata.name: required value]
FAIL
--- FAIL: TestUserLookup (0.01 seconds)
	userclient_test.go:205: unexpected error: userIdentityMapping "" is invalid: [metadata.name: required value, user.metadata.name: required value]
```

but got clean runs locally (when I definitely shouldn't have)

**Comment by smarterclayton** [comment]
Possible integration tests aren't rebuilding correctly.  Maybe the -c option is bad

**Pull request merged**
