### PR TITLE
kube rebase

### PR DESCRIPTION
**Pull request by deads2k**
Followup issues here: https://github.com/openshift/origin/issues/3537

Commits that are not upstream.  We need to either remove them or decide to carry patches.  This is the wall of shame:
 - [ ] 272fe767c184ac6e13bb726017a40e6bb60c3738  @liggitt 
 - [ ] d51199576cee066a9445bcc3c9f4367ce6d63249  @smarterclayton 
 - [ ] b0e4ce49b866ce92013a35cff217bff6af910645 @smarterclayton 
 - [ ] 316b55976ad3fbb96c617ad2b3c905c8d03b5b35 @smarterclayton 
 - [ ] e1006fa1264e9625ba4f26d1f6e5165481de14f8 @pmorie 
 - [ ] bff15af49613c0ab06362516e9163d5f2c77bd0e @pmorie  this doesn't match its kube pull
 - [ ] 285a3a04014daebc3f2315b075303b8652c80419 @smarterclayton 
 - [ ] e0a1540cf1ff3624a907fc3d5c9446460a05d21f @smarterclayton 

Current upstream list to diff through:

 - [x] commit 19f85548a34addccc7ff99bc5491018382281639
Author: kargakis <kargakis@users.noreply.github.com>
    Bug 1223252: UPSTREAM: label: Invalidate empty or invalid value labels

 - [x] commit 78b14c08165fe350cfd41bda20ac2f7a3e47b277
Author: fabianofranz <contact@fabianofranz.com>
    UPSTREAM: fixes kubectl config set-credentials examples

 - [x] commit aa4ccd6aea02455603dd0e26179adaaa1a43989f
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Ensure service account does not exist before deleting added/updated tokens

 - [x] commit baaf293a3c1a2c72c73a9452387ddfe6ecdd8abf
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Add logging for invalid JWT tokens

 - [x] commit 5f43fd1246b9daec39ca4c0ac7f6f9071054fd42
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: fix emptyDir idempotency bug

 - [x] commit 3646ad4736e7270ea02040eba1c49945bc958db9
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Make util.Empty public

 - [x] commit a13e3a39237771e8391a71b0bc8ba37d6b07bba9
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: use api.Scheme.DeepCopy()

 - [x] commit 4c1e6205395f5844f3b1d57e5fa0bcd03e448298
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Allow recyclers to be configurable

 - [x] commit bff15af49613c0ab06362516e9163d5f2c77bd0e
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: Handle SecurityContext correctly for emptyDir volumes

 - [x] commit 0887c48349783510ebe68db3a2f248db83f56120
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: add client field mappings for v1

 - [x] commit 0bf83e27b7e8a5d402d048fa9457052136e97a3a
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Validate port protocol case strictly

 - [x] commit a8bc579343f812da19276e2dc2c8faab66c1ef9f
Author: Andy Goldstein <agoldste@redhat.com>
    UPSTREAM: fix exec infinite loop

 - [x] commit 8756e5976d90b4fcbcee8066eb896ac5802bc1ae
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Fix bug where network container could be torn down before other pods

 - [x] commit bce2a9652804b54ae094e1b95be3fbffd4b8f182
Author: Ben Parees <bparees@redhat.com>
    UPSTREAM Fix ReadinessProbe: seperate readiness and liveness in the code
    
 - [x] commit 5de517cd4a690a599e33555593bbc88a20f86562
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Don't pretty print by default

 - [x] commit 22979c86bca500a4e3c8e0835498292da7003a69
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Add CephFS volume plugin

 - [x] commit f05b1a1e66b0a3aa79058f679389971e633fed89
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: search for mount binary in hostfs

 - [x] commit f5783976abad6b74744dd3c93cf38e538e263070
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Rate limit scheduler to bind pods burst qps

 - [x] commit 17e8ae62d27f31ae9b3019590f5d0cbc36e2185d
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: Expand variables in containers' env, cmd, args

 - [x] commit dbeba03207ff353e602f7ad8b87a8ca5ee3b37f2
Author: Paul Weil <pweil@redhat.com>
    UPSTREAM: work with SC copy, error formatting, add GetSCCName to provider

 - [x] commit 5a6667087fd51c5b312e842851d1d35b8527f328
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM its bad to spawn a gofunc per quota with large number of quotas

 - [x] commit aeaa7496137cedd0f8667f1e2732eac7cbd68ed8
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: add simple variable expansion

 - [x] commit e0a1540cf1ff3624a907fc3d5c9446460a05d21f
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: nsenter path should be relative

 - [x] commit 897481e879340817ace0c24b76b917eaff5c8e11
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Add omitempty to RBD/ISCSI volume sources

 - [x] commit 1fc020bbbc78a1390147e6f38c12bc8e2353ab1c
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: validate service account name in pod.spec

 - [x] commit 2f421f56a35e7a46dfd73b37fc21b99b5eacdad5
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: EmptyDir volumes for non-root 2/2

 - [x] commit 864ab6af653b0f2acdddae7509040414e3f2e260
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Added stop channel to prevent thread leak from watch

 - [x] commit 285a3a04014daebc3f2315b075303b8652c80419
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Run had invalid arguments

 - [x] commit e22854b9ea6c65fb4c90daff61421ebd054e9512
Author: deads2k <deads@redhat.com>
    UPSTREAM: kill namespace defaulting

 - [x] commit 35eb9d6fbd6893a03d9aade290e1006d6e1deca2
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Add Pod IP to pod describe

 - [x] commit 3c4e5b88d698ab48cf8b2e449e3d1eb30332b1f2
Author: deads2k <deads@redhat.com>
    UPSTREAM: add debug output for client calls

 - [x] commit b6c5065fd31d839a62ca2e9417967024315b653c
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: rest_client logging is generating too many metrics

 - [x] commit 92f11fa8c415c151ba50bdfcc691f93efe203f0f
Author: Paul Morie <pmorie@gmail.com>
    UPSTREAM: Support emptydir volumes for containers running as non-root

 - [x] commit 417ffe1de503da43bd3394943dc16d233ea3f35e
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Allow OSDN to signal ready

 - [x] commit 316b55976ad3fbb96c617ad2b3c905c8d03b5b35
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Allow pod start to be delayed in Kubelet

 - [x] commit 6271a2122623e93e6f33b8255a3a812b47891885
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Decrease columns and refactor get pods layout

 - [x] commit 09e07b1a9d9677be940ae65f1b366c7b990d8c3d
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Add available volumes to index when not present

 - [x] commit fde38012948d0c1c91a0e9ce3dbda4b4e60674f3
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: GCEPD mounting on Atomic

 - [x] commit d5f29e1ce29188af0be67ba2a2dba28e81073208
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Adds ISCSI to PV and fixes a nil pointer issue

 - [x] commit d0256ac98aac1e2657e809a0396dbb12e2f5c993
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Normalize and fix PV support across volumes

 - [x] commit 92ab13bc1ba6ff79ca8c5bf4b40592048ae82e4d
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: Added PV support for NFS

 - [x] commit 508684fe39ebe33f4babbfa5b305d3b89a95707f
Author: markturansky <mturansk@redhat.com>
    UPSTREAM: PV Recycling support

 - [x] commit debc2e760847a31b65d2990613b7f5c19c719e25
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Kubelet should log events at V(3)

 - [x] commit b6e452e82a36dcec080d82cd543c45e90d09c4d2
Author: deads2k <deads@redhat.com>
    UPSTREAM: Improve signature consistency for ValidateObjectMetaUpdate

 - [x] commit 98bb68f8e5f4987a509d8ccb7e7e637c9162e1d7
Author: deads2k <deads@redhat.com>
    UPSTREAM: kube: update describer for dockercfg secrets

 - [x] commit cf7aa2365dcc442ecaeb0c5fb09a1c285832333d
Author: deads2k <deads@redhat.com>
    UPSTREAM: kube: expose name validation method

 - [x] commit 587bea9a2321f9dd1ab3c77bbb51698cdf01be18
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: v1 Secrets/ServiceAccounts needed a conversion

 - [x] commit ea0c893171f01a483bd61657b3e55a0f31fd6819
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Alter default Kubernetes API versions

 - [x] commit 8280b5c546b9a8dabf6f14f232a2d9d090b16657
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM: Pass memory swap limit -1 by default

 - [x] commit 0bf6e4e0d7a66276a4f8dd470b4e7b45789673f9
Author: Cesar Wong <cewong@redhat.com>
    UPSTREAM: Remove CORS headers from pod proxy responses

 - [x] commit 8de1707a9ee8ec0de661afa8276b77315503ac0a
Author: kargakis <kargakis@users.noreply.github.com>
 - [x] commit 15449d46324c7d8848950c9c0af25855aa302579
Author: Salvatore Dario Minonne <salvatore-dario.minonne@amadeus.com>
    UPSTREAM: adding downward api volume plugin

 - [x] commit 8451cf41806d641840b9a17ba1cbc17e1f6fcc01
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Split resource.AsVersionedObject

 - [x] commit a6cca930d5bee2a4767b9d6b725e6f21c26d263b
Author: fabianofranz <contact@fabianofranz.com>
    UPSTREAM: ToJSON must support support forcing a JSON syntax check

 - [x] commit 387485296bc973bacd68fd4be83b1d8ee70fa9c1
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Improve deep copy to work with OpenShift

 - [x] commit b4a03338b4698a4e09cea0929212ab6b7e026bbd
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Enable LimitSecretReferences in service account admission

 - [x] commit d19d7cd0399ed5f14bc33ee43198ca959b7131b0
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: process new service accounts

 - [x] commit f68ca860ac4939eea414dc66b7f416096732f113
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: remove client facet from metrics

 - [x] commit 154ef255adde15001ade61af3c46021a95063938
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Insert 'svc' into the DNS search paths

 - [x] commit 24bbeeaa17792ca488101c96d259417933ed8c0f
Author: Paul Weil <pweil@redhat.com>
    UPSTREAM: security context constraints

 - [x] commit 348d85b9608b316541a520fd5edf98eca7c2508d
Author: Cesar Wong <cewong@redhat.com>
    UPSTREAM: Fix proxying of URLs that end in "/" in the pod proxy

 - [x] commit 4bc52ddafeae3f8fdef1fe7a99520036372bf129
Author: deads2k <deads@redhat.com>
    UPSTREAM: make getFromCache more tolerant

 - [x] commit b0e4ce49b866ce92013a35cff217bff6af910645
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Support kubelet initialization in order

 - [x] commit 8a786d53c8fc2d9fbb569b16afb86e5bc21d167f
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Fix error in quantity code conversion

 - [x] commit 3f9d1ae2a4269c963bdfc8e1342f85549cda6376
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Fix namespace controller to tolerate not found items

 - [x] commit 94e746d9d77c9cad6f53c84feda88893dac530d1
Author: Michal Fojtik <mfojtik@redhat.com>
    UPSTREAM: Match the isDefaultRegistryMatch with upstream

 - [x] commit 405872df2da7132500848ab2dc5098b4b5127d5d
Author: fabianofranz <contact@fabianofranz.com>
    UPSTREAM: json marshalling error must manifest earlier in resource visitors

 - [x] commit 712bf97d88218c44f25b67921007bff9d55d0149
Author: kargakis <kargakis@users.noreply.github.com>
    Bug 1224089: UPSTREAM: expose: Better error formatting and generic flag message

 - [x] commit d45f019fce51bf0bac2db4170ee9cba13144f358
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Backport schema output fixes

 - [x] commit 8565f74e5071ad2c23c41926cea0e06bd0a65e51
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Add "Info" to go-restful ApiDecl

 - [x] commit b7b2b6012626c52300881e32698034c080a29db7
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Hack date-time format on *util.Time

 - [x] commit 0acfb140fe77f31d29718f6ec9cdeff4065908da
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Expose OPTIONS but not TRACE

 - [x] commit b056d0d2de54abbe0aa13ad048b3a3c9dd2f0591
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Patch needs a type for swagger doc

 - [x] commit 02ca3af6e8130ba8b5d30ed9fda159769f92017e
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: fix omitempty on service account in v1beta3

 - [x] commit 52b9f448ada95e77055707c870d86c1d09ce01a4
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Add contiguous allocator

 - [x] commit 0c0ccaead2966b3c8e535288cb24e5bdfad9c21d
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Force explicit namespace provision

 - [x] commit cb4774062b0b1c68eec102f397020a181ba55c66
Author: derekwaynecarr <decarr@redhat.com>
    UPSTREAM Do not set container requests in limit ranger for Kube 1.0

 - [x] commit 652c143407f94d617166813aaa531913aa871db1
Author: deads2k <deads@redhat.com>
    UPSTREAM: kube: serialize dockercfg files with auth

 - [x] commit 5f4fbffcc764ada565ce751ba2e5afef8c101802
Author: deads2k <deads@redhat.com>
    UPSTREAM: kube: cleanup unused service account tokens

 - [x] commit 6a1ea0c8b259567bdc535b12f88004e84648baab
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Disable systemd activation for DNS

 - [x] commit cb8fb53c311afa8573ce9dfa8ef435b8719e7832
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Handle missing resolv.conf

 - [x] commit 34b0e11875d7e20ae5d1b6041aa42c70df369401
Author: kargakis <kargakis@users.noreply.github.com>
    UPSTREAM: Show pods number when describing services

 - [x] commit e4d365ea56bf0405e6e237c94ea15551325ef687
Author: deads2k <deads@redhat.com>
    UPSTREAM: kube: add pull secrets to service accounts

 - [x] commit efe354969078ad6df8ad6b0fb75ed7013f6e795f
Author: kargakis <kargakis@users.noreply.github.com>
    UPSTREAM: rename resize to scale

 - [x] commit 31b0ed7fda3cfda563586b658477e0394532c958
Author: Michal Fojtik <mfojtik@redhat.com>
    UPSTREAM: Add 'docker.io' and 'index.docker.io' to default registry

 - [x] commit 32614247e04a1edf9cc66a79cbfe7552c1e04667
Author: Abhishek Gupta <abhgupta@redhat.com>
    UPSTREAM: Allowing ActiveDeadlineSeconds to be updated for a pod

 - [x] commit 5d0de577dae3bf02d6cf21e37bc0a6231bfb7868
Author: Andy Goldstein <agoldste@redhat.com>
    UPSTREAM: Add support for pluggable Docker exec handlers

 - [x] commit 2c4b9b6ecd7bd5bfb4dbb290437572a238d4f6da
Author: kargakis <kargakis@users.noreply.github.com>
    UPSTREAM: expose: Use separate parameters for default and custom name

 - [x] commit db32d2e193f559247888f9732abcfea0b2c3e127
Author: Jordan Liggitt <jliggitt@redhat.com>
    UPSTREAM: Add groups to service account JWT

 - [x] commit 53cbac771975e75e3d08a140d9a23796e0224930
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: print more useful error

 - [x] commit a4b61028acf908bdf5ed4c8c7d594b7e9d617091
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: implement a generic webhook storage

 - [x] commit b45d0b45157ec52451121cca955a6b53f0ba8ba1
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Suppress aggressive output of warning

 - [x] commit ff7fb128b72bb2c7c9701e17b11214fd3a6d9538
Author: Clayton Coleman <ccoleman@redhat.com>
    UPSTREAM: Disable UIs for Kubernetes and etcd

### CODE REVIEW

**Comment by liggitt** [comment]
test

- [ ] commit 19f85548a34addccc7ff99bc5491018382281639
    Author: kargakis <kargakis@users.noreply.github.com>
    Date:   Wed May 20 11:08:59 2015 +0200
    Bug 1223252: UPSTREAM: label: Invalidate empty or invalid value labels
- [ ] commit 19f85548a34addccc7ff99bc5491018382281639
    Author: kargakis <kargakis@users.noreply.github.com>
    Date:   Wed May 20 11:08:59 2015 +0200
    Bug 1223252: UPSTREAM: label: Invalidate empty or invalid value labels

**Comment by liggitt** [comment]
Issue tracking upstream v1 API diffs: https://github.com/openshift/origin/issues/3331

**Comment by deads2k** [comment]
COMPILES!

**Comment by deads2k** [comment]
I'm still going through unit tests, but I think it's reasonable for @ncdc to check out e2e:

```
[INFO] Pre-pulling and pushing ruby-20-centos7
latest: Pulling from docker.io/openshift/ruby-20-centos7
befe95af4705: Download complete 
befe95af4705: Error downloading dependent layers 
d5de68d8a256: Error pulling image (latest) from docker.io/openshift/ruby-20-centos7, Driver devicemapper failed to create image rootfs befe95af4705ab93f5f12aa987bd3606543538d0e3124add624d216dbbeda29a: Unknown device 7322fbe74aa5632b33a400959867c8ac4290e9c5112877a7754be70cfe5d66e9 0959867c8ac4290e9c5112877a7754be70cfe5d66e9 
7322fbe74aa5: Download complete 
FATA[0006] Error pulling image (latest) from docker.io/openshift/ruby-20-centos7, Driver devicemapper failed to create image rootfs befe95af4705ab93f5f12aa987bd3606543538d0e3124add624d216dbbeda29a: Unknown device 7322fbe74aa5632b33a400959867c8ac4290e9c5112877a7754be70cfe5d66e9
```

**Comment by ncdc** [comment]
@deads2k congrats, you've hit another devicemapper snafu in our Jenkins VMs :-1: I'm pretty sure this is unrelated to any code changes.

**Comment by smarterclayton** [comment]
Le sigh

On Wed, Jul 1, 2015 at 4:37 PM, Andy Goldstein <notifications@github.com>
wrote:

> @deads2k <https://github.com/deads2k> congrats, you've hit another
> devicemapper snafu in our Jenkins VMs [image: :-1:] I'm pretty sure this
> is unrelated to any code changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3524#issuecomment-117818164>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
I separate interesting from boring and squash this down tomorrow.

**Comment by smarterclayton** [comment]
You need the disable UI patch (which I don't see here)

**Comment by smarterclayton** [comment]
I don't see the mount changes from https://github.com/GoogleCloudPlatform/kubernetes/pull/9976

**Comment by deads2k** [comment]
@smarterclayton please check for https://github.com/openshift/origin/commit/d45f019fce51bf0bac2db4170ee9cba13144f358

**Comment by deads2k** [comment]
@fabianofranz please check for https://github.com/openshift/origin/commit/405872df2da7132500848ab2dc5098b4b5127d5d

**Comment by deads2k** [comment]
@liggitt issue for https://github.com/openshift/origin/commit/d19d7cd0399ed5f14bc33ee43198ca959b7131b0

**Comment by deads2k** [comment]
@kargakis please check for https://github.com/openshift/origin/commit/8de1707a9ee8ec0de661afa8276b77315503ac0a

**Comment by deads2k** [comment]
[test]

**Comment by fabianofranz** [comment]
LGTM in relation to both

https://github.com/fabianofranz/origin/commit/405872df2da7132500848ab2dc5098b4b5127d5d
https://github.com/fabianofranz/origin/commit/a6cca930d5bee2a4767b9d6b725e6f21c26d263b

No need to pick any of them.

**Comment by fabianofranz** [comment]
https://github.com/openshift/origin/commit/78b14c08165fe350cfd41bda20ac2f7a3e47b277

also LGTM, no need to cherry-pick.

**Comment by kargakis** [comment]
> @kargakis please check for 8de1707

You have ported [replace.go](https://github.com/deads2k/origin/blob/rebase/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/replace.go) and [patch.go](https://github.com/deads2k/origin/blob/rebase/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/patch.go) so this is fine. Note that we have an [issue](https://github.com/openshift/origin/issues/3503) about replacing `update` with `replace` and `patch`. I think you will have to handle it here since there is no [NewCmdUpdate](https://github.com/openshift/origin/blob/f21a80e484e2ccc705a74a815df4a48e536c1acc/pkg/cmd/cli/cmd/wrappers.go#L70) in our Kube anymore.

**Comment by deads2k** [comment]
@pweil-   please check for https://github.com/openshift/origin/commit/dbeba03207ff353e602f7ad8b87a8ca5ee3b37f2

**Comment by deads2k** [comment]
@fabianofranz  please review a42e35775c39d4048d22cc363fedf9496d1e6539

**Comment by deads2k** [comment]
@kargakis please review 6eb0fb511d71267fffa7abfac9619d36f338b280

**Comment by deads2k** [comment]
@liggitt please review 
 1. bbd8fd7d6dce68eef5e8d3030729eea9b00c78a8
 1. d4934095517558ab95990b1c8841b0f9530880cd

**Comment by deads2k** [comment]
@csrwng  please review ccee2a5a879c4b7421fe144a7c4e87e3164ad3a5

**Comment by deads2k** [comment]
@smarterclayton please review or delegate
 1. 8c68b47cf97aac4309cdf8c2f3c683594285e7d3 - swagger API changes
 1. 5099100d44859f987cd82bd64b68dd39bd52ee3c - NewProxier port range
 1. 22f8b6115d9f9ae9b70da9953e766be95542357a - nodecontroller change
 1. bb9d7f21cd6443a6df5afb883b8d8755f29b250c - update conversion/deep-copy generator
 1. 61942b27fc09034128327763cbbe1a048bba47c0 - DeepCopy in Scheme?
 1. 4036e713bb48e090cda88a42bb0cd268cba2929b - prevent skydns metrics panic

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
@liggitt confirm that this is a UI flake: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3504/consoleText

**Comment by deads2k** [comment]
re[test]

**Comment by fabianofranz** [comment]
LGTM

**Comment by deads2k** [comment]
squashed down the boring.

@liggitt feeling lucky?

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by danmcp** [comment]
[vipmerge]

**Comment by deads2k** [comment]
> [vipmerge]

I wanted to say that so bad! :)

**Comment by liggitt** [comment]
"very important pull"

**Pull request merged**
