### PR TITLE
test/extended/prometheus: temporarily disable scheduler metrics checks

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @brancz @sttts @paulfantom

### CODE REVIEW

**Comment by brancz** [comment]
For explanation: all of the PRs referenced in the comment need to be merged for this test to be green again, so we're disabling it, waiting to see the PRs go green, and then re-enabling it.

**Comment by sttts** [comment]
We need this to avoid the chicken and egg problem switching over scheduler metrics to secure ports.

/lgtm
/approve

**Comment by brancz** [comment]
(as a follow up, the monitoring config for the scheduler and controller-manager will be moved out of the cluster-monitoring-operator to the respective second level operator, as each team/component owns its own monitoring configuration, then situation like this won't have to involve the monitoring team in the future)

**Pull request merged**
