### PR TITLE
add tmp volume so scratch image will work

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
fixes https://github.com/openshift/origin/issues/2579

**Comment by bparees** [comment]
@ncdc or @derekwaynecarr ptal.

**Comment by ncdc** [comment]
@bparees can you try http://koji.fedoraproject.org/koji/buildinfo?buildID=640661 to see if it fixes things?

**Comment by bparees** [comment]
@ncdc yeah that seems to work, but if it's all the same to you i'd still like to merge this so people on older versions of docker won't be broken... doesn't seem to do any harm.

**Comment by ncdc** [comment]
@bparees if you tested these changes and they worked for you, then LGTM.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
