### PR TITLE
Ensure only endpoints are specified in `oc idle`

### PR DESCRIPTION
**Pull request by DirectXMan12**
When you call `oc idle` with only names, it treats those names as
endpoints.  However, if you manually specify a different resource
in "resource/name" format, `oc idle` would panic, as it was expecting
only endpoints.  This commit throws an error instead when this situation
is encountered.

This PR also contains a fix for a typo in the `oc idle` help text.

Fixes bug 1365838 
Fixes bug 1365803

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @ncdc @mdshuai 

Fixes rhbz#1365838 and rhbz#1365803

**Comment by ncdc** [comment]
As discussed with Solly, waiting on a test case before merging

**Comment by ncdc** [comment]
cc @smarterclayton

**Comment by DirectXMan12** [comment]
I added a test in test/cmd

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
