### PR TITLE
Update glog godep

### PR DESCRIPTION
**Pull request by jim-minter**
Currently the sha of our glog godep does not actually seem to exist anywhere in the upstream glog repository.  Bumping to latest.

[test]

### CODE REVIEW

**Comment by jim-minter** [comment]
@soltysh fyi

**Comment by soltysh** [comment]
@jim-minter some of our deps are using our local forks, see [hack/godep-restore.sh](https://github.com/openshift/origin/blob/3929053bbbb0f65a5d72689781cdff0f12474afa/hack/godep-restore.sh#L68-L78) for them. This is for those deps we have additional changes. Having said that, I'm closing this PR.

**Comment by jim-minter** [comment]
@stevekuznetsov, what is the purpose of https://github.com/openshift/glog /  https://github.com/openshift/glog/commit/335da9dda11408a34b64344f82e9c03779b71673 ?

Is there a reason we don't just use upstream glog + rewrite the two places that call the additional function we carry as in this PR?

**Comment by stevekuznetsov** [comment]
> what is the purpose of https://github.com/openshift/glog

I'm assuming for rebases and Godeps? @deads2k could give you a better answer.

> what is the purpose of openshift/glog@335da9d

To support an API that was not available to us before.

> Is there a reason we don't just rewrite the two places that call the additional function

**Comment by ncdc** [comment]
I actually like what Jim's done, but given that I'm doing the kube 1.5 rebase now, I'd rather not merge anything that bumps a godep unless it's absolutely critical.

**Comment by ncdc** [comment]
@jim-minter feel like bumping up to latest glog HEAD (basically to pick up https://github.com/golang/glog/commit/65d674618f712aa808a7d0104131b9206fc3d5ad)?

**Comment by soltysh** [comment]
It would be nice to bump glog in k8s as well.

**Comment by ncdc** [comment]
Agreed, but we could go first if needed, right?

**Comment by soltysh** [comment]
Either is fine with me. We'll pick upstream only in 1.6 rebase, so these are totally separate for now.

**Comment by jim-minter** [comment]
@ncdc the broad effect of that one additional commit https://github.com/golang/glog/commit/65d674618f712aa808a7d0104131b9206fc3d5ad beyond where we and k8s are currently is a whole pile of log pollution (if flag.Parse() - not pflag - hasn't been called before any given glog invocation).  The patch was added to glog to protect against a use case that isn't really present for us or k8s.  Making the bump could potentially affect all our codebase including tests and utilities, and in a fair number of cases because we wrap k8s routines/frameworks, honestly it would be better if k8s went first.

But see https://github.com/kubernetes/kubernetes/issues/17162, which is a pretty reasonable viewpoint.  I don't think it's worth the effort to go to anything but 44145f04b68cf362d9c4df2182967c2275eaefed.

**Comment by ncdc** [comment]
That's fine

**Comment by jim-minter** [comment]
@ncdc I think testing just hit flake #12558; would you hit merge?

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
