### PR TITLE
Clean MySQL template defaults

### PR DESCRIPTION
**Pull request by rhcarvalho**
- Remove lots of noise from the template
- Mark required field as required

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees ptal

**Comment by bparees** [comment]
```FAILURE: Generated bootstrap bindata out of date. Please run hack/gen-bootstrap-bindata.sh```

also needs a squash, otherwise lgtm.

**Comment by rhcarvalho** [comment]
@bparees squashed.

**Comment by bparees** [comment]
i think this will need hack/gen-bootstrap-bindata.sh run.

**Comment by rhcarvalho** [comment]
> i think this will need hack/gen-bootstrap-bindata.sh run.

Indeed. Updated, thanks.

**Comment by bparees** [comment]
lgtm [merge]

**Comment by rhcarvalho** [comment]
@bparees I think the test failure is infra related:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/1677/console
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
error: running '/bin/sh -c cd "/var/lib/origin" && INSTALL_PKGS="kmod keepalived iproute psmisc nmap-ncat net-tools" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all' failed with exit code 1
!!! Error in hack/build-images.sh:65
```

```
test_pull_requests_origin_conformance ERROR (as above)
test_pull_requests_origin_check PASSED
test_pull_requests_origin_integration PASSED
test_pull_requests_origin_networking PASSED
```

**Comment by bparees** [comment]
seems so, we'll see what happens when it gets to the merge attempt.
[test]

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9195
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
