### PR TITLE
Revert emptydir scc

### PR DESCRIPTION
**Pull request by dgoodwin**
Feature obsoleted by https://github.com/openshift/origin/pull/7641

### CODE REVIEW

**Comment by pweil-** [comment]
cc @liggitt @smarterclayton 

@dgoodwin the upstream commit messages need formatted

**Comment by dgoodwin** [comment]
Updated.

**Comment by liggitt** [comment]
This LGTM, @pweil-?

**Comment by pweil-** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by pweil-** [comment]
healthz flake

re[merge]

**Comment by bparees** [comment]
vagrant plugin victim. [merge]

**Pull request merged**
