### PR TITLE
Migrate miscellaneous Bash utilities into the `hack/lib` library

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@Miciah PTAL the second commit

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Squashed, @danmcp please tag for merge

**Comment by danmcp** [comment]
@stevekuznetsov There is a merge conflict.

**Comment by stevekuznetsov** [comment]
@danmcp sorry, hard to see that these days when the GitHub icon is always grey. Fixed

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
