### PR TITLE
describe: Use spec.replicas when describing a deployment

### LINKED ISSUE #3367: oc deploy shows an incorrect status
Scale up an initial deployment to 10.  oc deploy and oc status display the wrong message.

```
$ oc deploy nodejs-frontend
nodejs-frontend #1 deployed 5 minutes ago - 10 pods reducing to 1
```

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #3367

@ironcladlou @smarterclayton PTAL

### CODE REVIEW

**Comment by ironcladlou** [comment]
Is this just to correct the assumption made by the project status describer code? Couldn't it look at the RC.Spec.Replicas as the "desired" if the deployment is complete?  The annotation is set in just one place (the deployment config controller) for use by the deployment process, and I'm not sure if it makes sense add another modification site here. Am I missing another use case?

**Comment by kargakis** [comment]
> Is this just to correct the assumption made by the project status describer code? Couldn't it look at the RC.Spec.Replicas as the "desired" if the deployment is complete? The annotation is set in just one place (the deployment config controller) for use by the deployment process, and I'm not sure if it makes sense add another modification site here. Am I missing another use case?

We could modify the describer code to look at the spec instead but that lagging annotation will stay hidden until it comes back again to haunt us.:)

**Comment by ironcladlou** [comment]
>We could modify the describer code to look at the spec instead but that lagging annotation will stay hidden until it comes back again to haunt us.:) 

What other system components besides the deployer code performing the deployment cares about the annotation value? The describer could continue to look at the annotation for non-terminal deployments. The mistake the project code is making is that it assumes the annotation value has meaning after the deployment enters a terminal state. When the deployment's complete it should rely on the spec value.

Should you really be able to scale a running deployment? That's another discussion.

**Comment by smarterclayton** [comment]
Yes, you should, because the autoscaler is going to do it.  The user cares
about running deployments.  If the describer is using that value
incorrectly, we should fix it, but if the value is wrong, that's a larger
problem.

On Jun 30, 2015, at 11:56 AM, Dan Mace <notifications@github.com> wrote:

We could modify the describer code to look at the spec instead but that
lagging annotation will stay hidden until it comes back again to haunt
us.:)

What other system components besides the deployer code performing the
deployment cares about the annotation value? The describer could continue
to look at the annotation for non-terminal deployments. The mistake the
project code is making is that it assumes the annotation value has meaning
after the deployment enters a terminal state. When the deployment's
complete it should rely on the spec value.

Should you really be able to scale a running deployment? That's another
discussion.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3509#issuecomment-117237362>.

**Comment by kargakis** [comment]
> If the describer is using that value incorrectly, we should fix it, but if the value is wrong, that's a larger problem.

This. Since we have that annotation, let's keep it updated. The scaler is the most appropriate place to do so.

**Comment by smarterclayton** [comment]
As per Dan I'm not sure the value is wrong.  Although the last scale should
probably clear it.

On Jun 30, 2015, at 12:01 PM, Michail Kargakis <notifications@github.com>
wrote:

If the describer is using that value incorrectly, we should fix it, but if
the value is wrong, that's a larger problem.

This. Since we have that annotation, let's keep it updated. The scaler is
the most appropriate place to do so.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3509#issuecomment-117238585>.

**Comment by smarterclayton** [comment]
Dan, is there a reason *not* to reset the annotation?

On Tue, Jun 30, 2015 at 12:02 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> As per Dan I'm not sure the value is wrong.  Although the last scale
> should probably clear it.
>
> On Jun 30, 2015, at 12:01 PM, Michail Kargakis <notifications@github.com>
> wrote:
>
> If the describer is using that value incorrectly, we should fix it, but if
> the value is wrong, that's a larger problem.
>
> This. Since we have that annotation, let's keep it updated. The scaler is
> the most appropriate place to do so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3509#issuecomment-117238585>.
>
>


-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Or clear it?

On Tue, Jun 30, 2015 at 12:57 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Dan, is there a reason *not* to reset the annotation?
>
> On Tue, Jun 30, 2015 at 12:02 PM, Clayton Coleman <ccoleman@redhat.com>
> wrote:
>
>> As per Dan I'm not sure the value is wrong.  Although the last scale
>> should probably clear it.
>>
>> On Jun 30, 2015, at 12:01 PM, Michail Kargakis <notifications@github.com>
>> wrote:
>>
>> If the describer is using that value incorrectly, we should fix it, but
>> if the value is wrong, that's a larger problem.
>>
>> This. Since we have that annotation, let's keep it updated. The scaler is
>> the most appropriate place to do so.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3509#issuecomment-117238585>.
>>
>>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
Just to clarify, when I asked "should it be possible to scale a running deployment", I meant "should it be possible to scale an in-progress deployment." As in, a scale concurrent with the deployment process which is using a locally cached value of desired replicas.

**Comment by ironcladlou** [comment]
It could be safely cleared for a completed deployment. For a failed deployment, we scale back up the last completed deployment to the annotation value from the failed deployment, after which we could clear it. Although I don't see the harm in keeping it around.

**Comment by smarterclayton** [comment]
It's a question of cleanliness - if we can cheaply clear it, and we own it,
we should clear it.

On Tue, Jun 30, 2015 at 1:31 PM, Dan Mace <notifications@github.com> wrote:

> It could be safely cleared for a completed deployment. For a failed
> deployment, we scale back up the last completed deployment to the
> annotation value from the failed deployment, after which we could clear it.
> Although I don't see the harm in keeping it around.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3509#issuecomment-117272033>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Let's reach a decision - do we want to clear this on completion, or leave it equal to the user?  If we leave it, it'll tempt callers to depend on it, and when autoscaling happens the value will be wrong (or at least, won't match).

**Comment by ironcladlou** [comment]
I think the DeployerPodController should clear it while transitioning the deployment to complete. This PR can be redone to fix the project status code for #3367 rather than setting the annotation on scale. A new PR will be necessary for the clearing.

**Comment by kargakis** [comment]
:updated:

**Comment by ironcladlou** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
