### PR TITLE
[4.2] Bug 1808549: UPSTREAM: 88146: remove duplicate pv delete commands

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1808549

/sig storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/retitle [4.2] Bug 1808548: UPSTREAM: 88146: remove duplicate pv delete commands

**Comment by jsafrane** [comment]
/retitle [4.2] Bug 1808549: UPSTREAM: 88146: remove duplicate pv delete commands

**Comment by sdodson** [comment]
Previous 4.2 release requires a rebuild so revoking cherry-pick-approved for now.

**Pull request merged**
