### PR TITLE
bug 1915945: UPSTREAM: 96990: Increase preemption timeout from 1 minute to 2 minutes

### PR DESCRIPTION
**Pull request by ingvagabund**
Backporting https://github.com/kubernetes/kubernetes/pull/96990

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
These should be in our k8s fork, and re-vendored here.

**Comment by ingvagabund** [comment]
o/k: https://github.com/openshift/kubernetes/pull/530

**Comment by ingvagabund** [comment]
/hold cancel
o/k revendored

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
