### PR TITLE
Make v1beta3 the default API version for clients

### PR DESCRIPTION
**Pull request by smarterclayton**
First commit is in a different pull

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@derekwaynecarr I ended up making the project admission control allow CREATE on an empty namespace in order to make cluster access review work (I currently have it as namespace scoped).  We may end up needing to create a "both" scope...

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@derekwaynecarr @deads2k review at your leisure, this is going in though.

**Comment by smarterclayton** [comment]
@liggitt did the UI test actually prevent me from breaking the UI?!?!?!

**Comment by liggitt** [comment]
shockingly, yes

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
