### PR TITLE
tito builder/tagger cleanup

### PR DESCRIPTION
**Pull request by maxamillion**
This is mostly just clean up to make the code more [pep8](https://www.python.org/dev/peps/pep-0008/) friendly

    - don't use mixed spacing tab width
    - string formatting
    - add vim modeline for sanity
    - handle/remove possible newlines from ldflags

### CODE REVIEW

**Comment by maxamillion** [comment]
ping @sdodson @tdawson - please review

**Comment by sdodson** [comment]
https://github.com/openshift/origin/pull/5934/files?w=1 to minimize whitespace diff when reviewing

**Comment by sdodson** [comment]
LGTM, I've verified that build and release continue to work as expected.

**Comment by sdodson** [comment]
@brenton this is good to go

**Pull request merged**
