### PR TITLE
deflake second level timing issue in TestDescribeBuildDuration

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/9139

@csrwng PTAL

@bparees FYI

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM
[merge]

**Comment by gabemontero** [comment]
TestTriggers_imageChange_nonAutomatic failed in the integration run.  Unrelated to this change.  I'll rebase and see if a fix was picked up in the interim.

**Comment by gabemontero** [comment]
@csrwng could you please re-post the merge comment, see if we can get past the last flake

**Comment by csrwng** [comment]
@gabemontero I think it should still be in the merge queue

**Comment by csrwng** [comment]
[merge]

**Comment by smarterclayton** [comment]
TestTriggers was a flake https://github.com/openshift/origin/issues/9213

**Pull request merged**
