### PR TITLE
Fixes `get --show-labels` for OpenShift resources

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/9114

WIP fixes deployment configs, still need to check and fix other OpenShift resources if needed. Also pending tests.

@smarterclayton are you ok with exposing `append*Labels` funcs in the printer upstream?

### CODE REVIEW

**Comment by smarterclayton** [comment]
Yes, it should be exposed upstream.

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@smarterclayton please review.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
