### PR TITLE
UPSTREAM: 58753: Fix kubectl explain for cronjobs

### LINKED ISSUE #18261: oc explain does not work for cronjobs
```
$ oc version
oc v3.9.0-alpha.3+8220060-167
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.ci.openshift.org:443
openshift v3.7.0-rc.0+bd64aab-99
kubernetes v1.7.6+a08f5eeb62
$ oc explain cronjobs
error: Couldn't find resource for "batch/v1, Kind=CronJob"
$ oc get cronjobs --all-namespaces
NAMESPACE   NAME                SCHEDULE    SUSPEND   ACTIVE    LAST SCHEDULE   AGE
origin-ci   jenkins-team-sync   0 0 * * *   False     1         18d             18d
```
/assign @soltysh 
/sig master
/kind bug

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #18261.

@kargakis fyi
/assign @juanvallejo

### CODE REVIEW

**Comment by juanvallejo** [comment]
Mind adding a case for cronjobs in our test as well? https://github.com/openshift/origin/blob/master/test/cmd/explain.sh

**Comment by soltysh** [comment]
Added.

**Pull request merged**
