### PR TITLE
UPSTREAM: 53446: kubelet: add latency metrics to network plugin manager

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/53446

Right now, we can't account for all the time spent in the PLEG loop.  We have `kubelet_docker_operations_latency_microseconds` to account for container runtime delays but nothing to capture delays due to the CNI plugin.  This PR adds those metrics.

xref https://bugzilla.redhat.com/show_bug.cgi?id=1486914

@smarterclayton @eparis @smarterclayton @jeremyeder @DirectXMan12 @dcbw 

Adding do-not-merge until rebase completes.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
holding pending https://github.com/openshift/origin/pull/16615

pick looks good though.

**Comment by eparis** [comment]
/hold cancel
looks like the rebase merged.

**Comment by sjenning** [comment]
ugh. left out a colon in the UPSTREAM commit msg.  can i get re-lgtm?

**Pull request merged**
