### PR TITLE
Tests: don't clone openshift/origin where possible

### LINKED ISSUE #7430: Use binary builds for extended tests that fetch origin repo
We carry some extended tests that fetch the origin repo (jenkins/kubernetes is one of those). We should investigate to switch to binary builds to make that tests faster and not re-clone origin several times.

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #7430.

### CODE REVIEW

**Comment by mmilata** [comment]
Modified `jenkins/kubernetes_plugin.go` to not clone origin. There's some template preprocessing that's needed in order to use binary builds - could be avoided by making a copy of the template but I didn't like the idea of maintaining two almost identical files in the repo.

**Comment by bparees** [comment]
@mmilata how is it being excluded currently?  (which bucket is it being excluded from)?

**Comment by mmilata** [comment]
@bparees it's listed in `EXCLUDED_TESTS` here: https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L262

**Comment by bparees** [comment]
yeah you can remove it from there.  it doesn't matter all that much because it's already excluded by being marked Slow and it is indeed slow.  Also the excluded tests are still run when you explicitly request a ginkgo filter, so when we do our extended test job it does get run. but for cleanliness, sure remove that line.

**Comment by bparees** [comment]
also that text doesn't actually match any current test description....

**Comment by bparees** [comment]
ah i guess it matches by concatenation, nm

**Comment by mmilata** [comment]
Removed from the excluded list.

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[testextended][extended:core(jenkins)]

**Comment by bparees** [comment]
lgtm, will merge if/when extended tests pass.

@gabemontero this jenkins test is one of the ones you're moving into image_ecosystem in another PR, right?

**Comment by mmilata** [comment]
The test failure looks like something that might've been fixed by #11508. Let's try again.
[testextended][extended:core(jenkins)]

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
On Fri, Oct 21, 2016 at 11:20 AM, Ben Parees <notifications@github.com>
wrote:

> lgtm, will merge if/when extended tests pass.
>
> @gabemontero <https://github.com/gabemontero> this jenkins test is one of
> the ones you're moving into image_ecosystem in another PR, right?
>
yep i'll rebase when this merges ... and @mmilata looks to have
incorporated the fixes to kubernetes_plugin.go
as well

**Comment by bparees** [comment]
@gabemontero this already merged, but between your comment and a few from @smarterclayton i'm thinking github is just finally delivering old email responses you guys sent.

**Comment by gabemontero** [comment]
Yeah I made that last comment a few days ago.  We are good here (as of Tue Oct 25 2:50 Eastern).

**Pull request merged**
