### PR TITLE
Apps: raise failing-dc timeout to avoid flakes

### PR DESCRIPTION
**Pull request by tnozicka**
@mfojtik fix for the flake you saw earlier (https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17576/test_pull_request_origin_end_to_end/6624/)

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
@mfojtik I think this is not because of the timeout but logs issue https://github.com/openshift/origin/issues/17747 by `the output content test failed`

**Comment by deads2k** [comment]
> /hold
> @mfojtik I think this is not because of the timeout but logs issue #17747 by the output content test failed

I agree

/lgtm cancel

**Pull request closed without merging**
