### PR TITLE
remove jenkins autoprovision logic+config

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k ok i think i stripped this down to the parts you need, ptal.

/assign @deads2k

**Comment by bparees** [comment]
@gabemontero fyi

**Comment by gabemontero** [comment]
Perhaps on your to-do list since this is WIP @bparees but we'll need to update https://github.com/openshift/origin/tree/master/examples/jenkins/pipeline/README.md to list for each sample the jenkins template needs to be new-app'ed before the sample template.

**Comment by bparees** [comment]
> Perhaps on your to-do list since this is WIP @bparees but we'll need to update https://github.com/openshift/origin/tree/master/examples/jenkins/pipeline/README.md to list for each sample the jenkins template needs to be new-app'ed before the sample template.

it was not, thanks.  and of course there are product docs that will need updating as well.  

/cc @bmcelvee

**Comment by deads2k** [comment]
I'm glad to see this.  We'll pick up stragglers when we start snipping out old API.

/lgtm

**Pull request merged**
