### PR TITLE
Add github.com/Microsoft/go-winio as required by github.com/docker/go…

### LINKED ISSUE #8861: Build Release Error
[provide a description of the issue]
Hit into error while running build-release.sh on Fedora 23 amd64

##### Version
Latest source code from openshift/origin
go version go1.5.4 linux/amd64

##### Steps To Reproduce
1. Git clone the latest source code from master
2. cd hack
3. ./build-release.sh

##### Current Result
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Building go targets for darwin/amd64: cmd/openshift cmd/oc
++ Building go targets for windows/amd64: cmd/openshift cmd/oc
Godeps/_workspace/src/github.com/docker/go-connections/sockets/sockets_windows.go:7:2: cannot find package "github.com/Microsoft/go-winio" in any of:
	/usr/local/go/src/github.com/Microsoft/go-winio (from $GOROOT)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/Microsoft/go-winio (from $GOPATH)
	/go/src/github.com/Microsoft/go-winio
!!! Error in hack/../hack/common.sh:301
	'GOOS=${platform%/*} GOARCH=${platform##*/} go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]}"' exited with status 1
Call stack:
	1: hack/../hack/common.sh:301 os::build::build_binaries(...)
	2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in hack/../hack/common.sh:253
	'os::build::build_binaries "${OS_CROSS_COMPILE_TARGETS[@]}"' exited with status 1
Call stack:
	1: hack/../hack/common.sh:253 os::build::build_binaries(...)
	2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in ./build-release.sh:45
	'docker run -e "OS_ONLY_BUILD_PLATFORMS=${OS_ONLY_BUILD_PLATFORMS-}" -i --cidfile="${context}/cid" openshift/origin-release' exited with status 0 1
Call stack:
	1: ./build-release.sh:45 main(...)
##### Expected Result
Binary build finished without error.

### PR DESCRIPTION
**Pull request by sdodson**
…-connections

Fixes #8861

### CODE REVIEW

**Comment by sdodson** [comment]
@smarterclayton PTAL wasn't sure if this should be pushed into kubernetes as it seems their godep management is slightly different?

**Comment by sdodson** [comment]
[test]

**Comment by smarterclayton** [comment]
I'm not sure why you're having to add this?

**Comment by smarterclayton** [comment]
I think this is a gap with the fedora golang packaging.

**Comment by sdodson** [comment]
> I think this is a gap with the fedora golang packaging.

I was hitting this on RHEL 7 golang-1.6.2. I was getting the same error as in the linked issue.

**Comment by smarterclayton** [comment]
Packaged by the same people.  This does not happen when we build from the
Golang provided binaries in the docker image.  What's the difference?

**Comment by mfojtik** [comment]
i believe i am adding some of these in the rebase

**Comment by sdodson** [comment]
Are you building windows oc binaries?

**Comment by sdodson** [comment]
> i believe i am adding some of these in the rebase

cool, seems the problem was introduced in the last rebase.

**Comment by smarterclayton** [comment]
Why is our windows build not currently broken?

On May 24, 2016, at 1:23 PM, Michal Fojtik <notifications@github.com> wrote:

i believe i am adding some of these in the rebase
On May 24, 2016 6:45 PM, "OpenShift Bot" <notifications@github.com> wrote:

> continuous-integration/openshift-jenkins/test FAILURE (
> https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/4023/)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/9006#issuecomment-221332575>
>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/9006#issuecomment-221341176>

**Comment by sdodson** [comment]
Perhaps it is, no tag contains 4d3cc39a so I doubt we've built a release since this dependency was added.

**Comment by smarterclayton** [comment]
We build releases every commit from Origin.

**Comment by smarterclayton** [comment]
Basically there is something different between upstream Golang and RHEL
golang.

**Comment by smarterclayton** [comment]
Ah, we're not building Windows.  [merge]

**Comment by smarterclayton** [comment]
You need to fit the Go conventions.  Going to cherry-pick and fix.

**Pull request closed without merging**
