### PR TITLE
Enable minimization of net e2e runtime

### PR DESCRIPTION
**Pull request by marun**
Backporting to release-1.3 as per https://github.com/openshift/origin/pull/11504#issuecomment-255621071

cc: @knobunc @smarterclayton

### CODE REVIEW

**Comment by marun** [comment]
[test]

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/11381 [test]

**Comment by marun** [comment]
flake #11381 re-[test]

**Comment by marun** [comment]
I think this is ready to merge - the networking job passed which is the only thing this PR affects.

**Comment by smarterclayton** [comment]
[test]

**Comment by marun** [comment]
flakes #11381 #11452 re-[test]

**Comment by knobunc** [comment]
```
--- FAIL: TestRouterServiceUnavailable (0.52s)
	router_test.go:973: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
```

**Comment by marun** [comment]
Seems like the 1.3 branch is even worse for flakes than master.  I'm going to propose we go ahead and merge.  The networking job passed once already, and that's the only thing that this PR affects.  Or is there a good reason to continue wasting everyone's collective time?

**Comment by knobunc** [comment]
@marun isn't that version error a real problem?

**Comment by marun** [comment]
@knobunc Sure, but it doesn't have anything to do with this change.  If the networking job can run, this pr is doing its job.

**Comment by marun** [comment]
I'm assuming the problem in question is related to #10750

**Comment by knobunc** [comment]
@marun I'm ok with merging this.  @smarterclayton how do you feel?

**Comment by smarterclayton** [comment]
Basically, moving to Docker 1.12 broke unit tests for the release-1.3 branch.  @danmcp doesn't really have any support for multiple VMs today (one per release) which is something we're trying to fix elsewhere.  I'll probably just merge this, but we ultimately can't have release branches unless we can prevent the base VM from breaking old releases.

**Comment by marun** [comment]
@smarterclayton do you still want to see this merge?

**Comment by marun** [comment]
bump. why is this still here?

**Comment by marun** [comment]
This must not be important, but I'll leave the branch in case anyone wants to reopen.

**Pull request closed without merging**
