### PR TITLE
Allow update on hostsubnets

### PR DESCRIPTION
**Pull request by pravisankar**
Needed when host IP changes.

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by danwinship** [comment]
LGTM

**Comment by danwinship** [comment]
@pravisankar travis failure is real:

    _output/local/go/src/github.com/openshift/origin/pkg/client/testclient/fake.go:186: cannot use FakeHostSubnet literal (type *FakeHostSubnet) as type client.HostSubnetInterface in return argument:
    
    	*FakeHostSubnet does not implement client.HostSubnetInterface (missing Update method)

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[merge]

**Pull request merged**
