### PR TITLE
add buildUpdate validation to protect spec

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/3237

@csrwng ptal

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM

**Comment by deads2k** [comment]
@smarterclayton do we want this one for 3.0 or post?

**Comment by smarterclayton** [comment]
Nothing mutates spec post build?

**Comment by deads2k** [comment]
> Nothing mutates spec post build?

Not anymore. :)  [test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
