### PR TITLE
Rename pkg/sdn to pkg/network, for consistency with its API

### PR DESCRIPTION
**Pull request by danwinship**
@deads2k wanted this

This is on top of #15781, but that should be merged soon. Only the last two commits ("Rename pkg/sdn to pkg/network, for consistency with its API" and "Regenerate files") are for this PR.

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

bumping queue priority because this one is going to suck to rebase.

**Comment by deads2k** [comment]
hrm, bot didn't obey and now you have to rebase again. sorry.

/lgtm

**Comment by danwinship** [comment]
it was actually already needs-rebase when I pushed it, because I based it on top of #15781 rather than master (and apparently there was some change in master that this PR conflicted with that #15781 didn't).

**Comment by deads2k** [comment]
@danwinship for rebases, it's the same old rosie rules, but you have to re-apply your tags manually.

**Pull request merged**
