### PR TITLE
JSON examples migration to v1beta3 leftovers

### PR DESCRIPTION
**Pull request by soltysh**
@smarterclayton @mfojtik this is the result of updated origin-version-change from #2653.

[test] in the mean time

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by bparees** [comment]
@smarterclayton i assume you're ok with merging this since you're about to remove v1b1?

**Comment by smarterclayton** [comment]
No concerns.

----- Original Message -----

**Comment by bparees** [comment]
[merge]

**Pull request merged**
