### PR TITLE
Add API Group server info to UI config

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM @benjaminapetersen have you tested your stuff in combination with these changes?

**Comment by liggitt** [comment]
updated dev config.js as well... what do you think of `apis` instead of `apiGroups`?

**Comment by jwforres** [comment]
either one seems reasonable

**Comment by liggitt** [comment]
I think I prefer `/apis`. @benjaminapetersen you want to test with this commit or just pull it into your PR?

**Comment by benjaminapetersen** [comment]
I'm fine with that change. I can update my PR once this is merged in?

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
