### PR TITLE
disable the oauth server in kubeapiserver

### PR DESCRIPTION
**Pull request by deads2k**
The oauthconfig is about to become truly optional.  https://github.com/openshift/cluster-authentication-operator/pull/59  is needed.

/assign @mfojtik @soltysh

### CODE REVIEW

**Comment by deads2k** [comment]
@openshift/sig-auth

**Comment by mfojtik** [comment]
LGTM

Will leave it for @enj or @ericavonb to have chance to see and tag.

**Comment by deads2k** [comment]
known flake.  merging

**Pull request merged**
