### PR TITLE
Updating tests for new S2I postCommit code

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign bparees

@bparees ptal

**Comment by bparees** [comment]
/lgtm
(unfortunately you're stuck until api.ci comes back)

**Comment by coreydaley** [comment]
Nooooooooooooo!

**Comment by coreydaley** [comment]
@bparees These tests that I updated have nothing to do with these failures.  Can this get merged some other way?

**Comment by bparees** [comment]
@coreydaley please start opening BZs on these flakes, this is ridiculous.

**Comment by coreydaley** [comment]
@bparees I'll open them in the morning.  
Do we need Bugzillas or github issues?

**Comment by bparees** [comment]
BZs.  we're not using github issues for flakes anymore.

**Comment by bparees** [comment]
actually first re-open this PR as a new PR, it seems like e2e-conformance-k8s isn't being run on new PRs from what i see and i don't know how to get the bot stop running it here.

**Pull request closed without merging**
