### PR TITLE
only run scheduled image import on tags marked scheduled

### PR DESCRIPTION
**Pull request by jim-minter**
https://bugzilla.redhat.com/show_bug.cgi?id=1515060

### CODE REVIEW

**Comment by jim-minter** [comment]
@bparees does the above change look plausible to you to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1515060?  Can you see any potential bad side-effects?

I think I've just changed `if !(partial && tagImportable(tagRef)) && !tagNeedsImport(stream, tag, tagRef, true) {` to `if !(!partial && tagImportable(tagRef)) && !tagNeedsImport(stream, tag, tagRef, true) {` (i.e. prepended a `!` to `partial`) and run De Morgan a couple of times.

Will see it causes any tests to fail and will add a test before removing [WIP].

**Comment by bparees** [comment]
Since the updated logic appears to boil down to:

if we're NOT doing a partial import, import all tags
if we are doing a partial import and this tag needs to be imported, import it

it certainly looks superficially sane to me.

However i think i need a better understanding of what kicks off a "scheduled" import vs someone manually running "oc import-images" against the IS.  What actually happens to mark a particular tag as "needsImport" when the scheduled import fires?

**Comment by bparees** [comment]
ok i found the scheduled tag logic and i see that it just bumps the tag's spec generation which makes it newer than the status generation, which will make needsImport be true the next time around.

after taking way too long to think my way through what is happening, i think your change is sane.

under the old logic, effectively it did this:

if we're importing all tags and this tag needs importing, import it
if we're not importing all tags, import this tag

Which is backwards (hence your change) but probably subtly wrong enough that most people wouldn't notice since under most circumstances you're still going to get the imports you want/need.

seems like we do need a new test for this though.

**Comment by smarterclayton** [comment]
We might want to have a way to force a poll.  The hard part is that the
scheduler spaces out its set.  Ideally, we'd be able to change the config
dynamically and have it update.

For now, the current testing is sufficient.

**Comment by bparees** [comment]
@jim-minter you've got failing unit test compilation.  that's not normally a flake:

```
[WARNING] While the jUnit report found no failed tests, the `go test` process failed.
[WARNING] This usually means that the unit test suite failed to compile.
[ERROR] hack/test-go.sh exited with code 1 after 00h 34m 48s
make: *** [test-unit] Error 1
[ERROR] PID 12862: hack/lib/build/en
```

**Comment by jim-minter** [comment]
TestUnregisterMetricAndUntrackRateLimiterUsage in vendor/k8s.io/kubernetes/pkg/util/metrics panicked.  Never seen that before, works locally, and wanted to see if it happens again.

**Pull request merged**
