### PR TITLE
Bug 2106897: Remove oc image info test that uses mysql, aligns with 4.7+ version of this test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@dmage @soltysh ptal

same as what was done in https://github.com/openshift/origin/pull/25744/files for https://bugzilla.redhat.com/show_bug.cgi?id=1904679

**Review by wking — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
/hold

want to be sure @dmage and @soltysh get a say on this since it's test coverage for their components.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
no QE impact so manually cherry-pick approving

**Pull request merged**
