### PR TITLE
UPSTREAM: 34020: Allow empty annotation values

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/34020

Fixes:
https://github.com/openshift/origin/issues/11175

Annotations with empty values can be used, for example, in oadm
diagnostics logging. This patch removes the client-side check for empty
values in an annotation key-value pair.

**Before**
```
$ oc annotate pod zookeeper-1 openshift.io/node-selector="" --overwrite
error: invalid annotation format: openshift.io/node-selector=
```

**After**
```
$ oc annotate pod zookeeper-1 openshift.io/node-selector="" --overwrite
pod "zookeper-1" annotated
```

```
$ oc get po/zookeeper-1 --template='{{.metadata.annotations}}'
map[... openshift.io/node-selector: openshift.io/scc:anyuid test-label:test]
```

@openshift/cli-review

### CODE REVIEW

**Comment by liggitt** [comment]
needs upstream

**Comment by fabianofranz** [comment]
Does this work without quotes?

```
oc annotate pod zookeeper-1 openshift.io/node-selector= --overwrite
```

**Comment by juanvallejo** [comment]
@fabianofranz 
> Does this work without quotes?

Yeah, just checked both `oc label` and `oc annotate` and they both work without labels, as long as the `=` is present after the key value

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by fabianofranz** [comment]
re[merge]

**Comment by juanvallejo** [comment]
integration test flaked on https://github.com/openshift/origin/issues/11240

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/11240 re[merge]

**Pull request merged**
