### PR TITLE
Fix deploymentConfig defaulting

### LINKED ISSUE #2242: Rolling Params missing in application-template-stibuild.json
Ref https://github.com/openshift/origin/issues/2216#issuecomment-102035323

@ironcladlou  A change you made to the sample template?

/cc @spadgett

### PR DESCRIPTION
**Pull request by ironcladlou**
The deploymentConfig defaulting was just completely wrong. Fix it
so that defaults are applied properly.

Closes #2242.

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
The messed up logic I had somehow worked with the CLI. I didn't bother investigating why, just fixed it so it works in all contexts.

**Comment by ironcladlou** [comment]
Related to #2216.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
