### PR TITLE
trt-1042: collect watch request counts

### PR DESCRIPTION
**Pull request by neisw**

### CODE REVIEW

**Comment by neisw** [comment]
Verified operators should not create watch channels very often is still running:


https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/28431/pull-ci-openshift-origin-master-e2e-gcp-ovn/1734617996812357632/artifacts/e2e-gcp-ovn/openshift-e2e-test/artifacts/junit/junit_e2e__20231212-175356.xml

**Comment by stbenjam** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/28431/pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade/1734617998376833024/artifacts/e2e-gcp-ovn-upgrade/openshift-e2e-test/artifacts/junit/operator-watch-requests_20231212-175023-autodl.json

Looks really good

/lgtm

**Pull request merged**
