### PR TITLE
UPSTREAM: 54763: increase iptables max wait from 2 seconds to 5 seconds

### PR DESCRIPTION
**Pull request by rajatchopra**
https://bugzilla.redhat.com/show_bug.cgi?id=1506396

Upstream PR https://github.com/kubernetes/kubernetes/pull/54763

### CODE REVIEW

**Comment by eparis** [comment]
```
iptables_test.go:612: For 1.4.22 expected -w2 got [-w5]
iptables_test.go:612: For 1.5.0 expected -w2 got [-w5]
iptables_test.go:612: For 2.0.0 expected -w2 got [-w5]
```

**Comment by eparis** [comment]
CI is going to fail until the upstream PR is referenced.

**Comment by imcsk8** [comment]
LGTM

**Pull request merged**
