### PR TITLE
eliminate basic auth flags

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/1704.
Upstream: https://github.com/GoogleCloudPlatform/kubernetes/pull/6768

This eliminates the username and password flags from all the commands except `osc login`

### CODE REVIEW

**Comment by deads2k** [comment]
@fabianofranz

**Comment by fabianofranz** [comment]
LGTM, resolves this TODO: https://github.com/openshift/origin/blob/e9f34a955cba82eb8689efdc564797d80bb8182e/pkg/cmd/cli/cmd/login.go#L63

**Comment by deads2k** [comment]
Updated comment.  [merge]

**Comment by deads2k** [comment]
re[merge]

**Pull request merged**
