### PR TITLE
Resize to scale rename

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/2562

### CODE REVIEW

**Comment by kargakis** [comment]
@smarterclayton @ironcladlou  PTAL

**Comment by ironcladlou** [comment]
LGTM although I'm not familiar with all the places that would be affected by the rename. Is a docs PR needed for this?

**Comment by kargakis** [comment]
> LGTM although I'm not familiar with all the places that would be affected by the rename. Is a docs PR needed for this?

Yep, I need to update docs as well:(
I'll ping you once it's done

**Comment by ironcladlou** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by ironcladlou** [comment]
[merge]

**Pull request merged**
