### PR TITLE
oc volume and oadm manage-node fixes

### LINKED ISSUE #3542: Should be able to overwrite (change type) of volume in oc volume
A dc existed with type emptyDir and mount path /var/run/openshift.  I should be able to overwrite it without specifying a name (in this case, because it's not ambiguous)

```
$ oc volume dc/master --add -m /var/run/openshift/ --secret-name=openshift-master --type=secret --overwrite
Generated volume name: 1c1d6339-2036-11e5-a89c-7831c1b76042
error: deploymentconfigs/master volume mount '/var/run/openshift/' already exists for container 'origin'
```

Should have overwrote the mount type because there was only one mount and my input wasn't ambiguous

### LINKED ISSUE #3708: manage-node has inconsistent output
When these nodes are found:

```
 oc get nodes
NAME                         LABELS                                              STATUS
claytons-macbook-pro.local   kubernetes.io/hostname=claytons-macbook-pro.local   Ready
openshiftdev.local           kubernetes.io/hostname=openshiftdev.local           NotReady
```

Empty node should display headers:

```
$ oadm manage-node --list-pods --selector=''
$ _
# displays no output, should probably print something to stderr such as "Node has no pods"
```

Passing -o yaml should display an empty yaml list:

```
$ oadm manage-node --list-pods --selector='' -o yaml
$ _
# displays no output
```

### PR DESCRIPTION
**Pull request by pravisankar**
- oc volume will allow changing volume type in case of unabiguous mount-path
- Print consistent output for oadm manage-node --list-pods

closes #3542 , closes #3708

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
@fabianofranz  @liggitt  PTAL

**Comment by ncdc** [comment]
Split into 2 separate PRs?

**Comment by pravisankar** [comment]
@fabianofranz  updated

**Comment by fabianofranz** [comment]
LGTM

**Comment by pravisankar** [comment]
[merge]

**Pull request merged**
