### PR TITLE
UPSTREAM: Reduce reaper poll interval and wait while resizing

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton fyi

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
Expected this flake to happen since now the timeout is reduced from 5 minutes to 20 seconds....

**Comment by kargakis** [comment]
I suggest either commenting that delete all out and adding a TODO for uncommenting when the replciationController manager will be faster or bumping the timeout back to 5 minutes. @smarterclayton thoughts?

**Comment by smarterclayton** [comment]
Why did we need to lower the timeout?

**Comment by kargakis** [comment]
> Why did we need to lower the timeout?

We didnt' actually. It seems a reasonable time in an era of a fast rc manager...

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
