### PR TITLE
add declarative pipeline example to build extended test suite

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/hold
(pending passing extended builds test)
/retest

**Comment by gabemontero** [comment]
All the tests passed, including extended builds @bparees 

I'll see if it accepts my unhold

**Comment by gabemontero** [comment]
yes it does ;-)

**Comment by bparees** [comment]
the system works! :)

**Comment by gabemontero** [comment]
well, the label is removed .... but it is not on the merge queue yet ... will be patient, check back in a bit

**Comment by gabemontero** [comment]
ah - now it is

**Pull request merged**
