### PR TITLE
Fix output from `oc get clusterPolicy` is hard to read

### PR DESCRIPTION
**Pull request by shiywang**
fix problem #12303

### CODE REVIEW

**Comment by liggitt** [comment]
I thought the output of `oc get *` was supposed to be single-line

**Comment by shiywang** [comment]
@liggitt Do you mean this #12303 issue is a feature instead of a problem? should I close this pr ?

**Comment by liggitt** [comment]
I'm not sure what the solution is, but I don't think multiline output here is correct. Perhaps we cannot display all the role names in this printer

**Comment by shiywang** [comment]
@fabianofranz Do you have any advice ?

**Comment by pweil-** [comment]
@openshift/cli-review

**Comment by juanvallejo** [comment]
@liggitt
> I'm not sure what the solution is, but I don't think multiline output here is correct. Perhaps we cannot display all the role names in this printer

Would it make sense to maybe display the truncated list of roles by default, and introduce a new flag that would force the entire list to display? (We could also only display the truncated list in the human readable printer and have users use `-o yaml` or -o `json` to view the full list) WDYT?

cc @fabianofranz

**Comment by liggitt** [comment]
I don't think truncation is good. We have the wide flag, right? That seems as good a flag as any if we want to conditionally include a potentially massive column

**Comment by shiywang** [comment]
@liggitt @juanvallejo not sure exactly what you mean, I use `oc get clusterPolicy -o wide`, the outputs still have the some problem, @liggitt do you mean we should check `options.Wide` to treat them differently ?

**Comment by liggitt** [comment]
> Do you mean we should check options.Wide to treat them differently ?

Exactly. Possibly include the role column when outputting in wide mode, otherwise just include something like the number of roles?

**Comment by fabianofranz** [comment]
Only include the roles column when in `-o wide` mode (will still have the problem, but that's ok in the wide output), in normal mode make it display the number of roles, and make sure it's displayed nicely in `oc describe clusterpolicy <name>`.

**Comment by shiywang** [comment]
In this function:https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L2421, `formatWideHeaders` is a little hard-coded unlike `handler.printFunc` which we can reimplement in our code, Do we have a workaround not changing upstream code ? if changing upstream is necessary, should we refactory the `formatWideHeaders`?  Have any ideas ? @fabianofranz @juanvallejo @liggitt

**Comment by shiywang** [comment]
@liggitt @juanvallejo @fabianofranz  I copied the upstream code to our repo by file, seems it can not pass the compiled, I also use `git patch\apply`, it doesn't work either (not base on lastest commit), Do we have a better way to copy the upstream code to our code: vendor/k8s.io/kubernetes/pkg/

**Comment by kargakis** [comment]
@shiywang the commit message for the upstream commit needs to be ` 	UPSTREAM: 39428: Move ..`. Also note that we are not merging upstream commits until the [rebase](https://github.com/openshift/origin/pull/12143) lands.

**Comment by shiywang** [comment]
@kargakis oh, I got it, thanks

**Pull request closed without merging**
