### PR TITLE
Bug 1802262: Loosen help tests for oc rsh

### PR DESCRIPTION
**Pull request by soltysh**
4.3 backport of https://github.com/openshift/origin/pull/24420

/assign @sallyom

### CODE REVIEW

**Comment by sdodson** [comment]
@soltysh @sallyom what's the status of e2e-conformance-k8s?

**Comment by sdodson** [comment]
/hold
Please clear when the e2e-conformance-k8s failures are understood.

**Comment by soltysh** [comment]
> Please clear when the e2e-conformance-k8s failures are understood.

They are weird since that particular tests git checkouts k8s directly and build kubectl. This PR is not touching this in any way and should not be affected. Lemme retry this test one more time.
/retest

**Comment by sdodson** [comment]
Dropping `cherry-pick-approved` from this PR so it doesn't merge outside of the merge window.

**Pull request merged**
