### PR TITLE
convert ldap group sync tests to e2e

### PR DESCRIPTION
**Pull request by mrogers950**
This restores the old ldap_groups.sh extended test to run in a container.  
Depends on https://github.com/openshift/origin/pull/23347 (will drop commit and rebase when it merges)

### CODE REVIEW

**Comment by mrogers950** [comment]
@deads2k @enj @stlaz the tests are working, please review. The groupsync.sh script is the old ldap_groups.sh modified to run in a pod, but the test sequence is retained.

**Comment by deads2k** [comment]
Looks plausible.  If the command fails, it turns red? Mind creating a pull with an exit 1 in the groupsync script so I can see it?

/approve

**Comment by enj** [comment]
Diff from 3.11 to now:

```
diff -dwB test/extended/ldap_groups.sh test/extended/testdata/ldap/groupsync.sh
```

```diff
6c6
< source "$(dirname "${BASH_SOURCE}")/../../hack/lib/init.sh"
---
> source "/usr/hack/lib/init.sh"
10a10,12
> export KUBECONFIG="${ADMIN_KUBECONFIG}"
> LDAP_SERVICE_IP="${LDAP_SERVICE}"
> 
20,83d21
< os::log::info "Starting server"
< 
< os::util::ensure::iptables_privileges_exist
< os::util::environment::use_sudo
< os::cleanup::tmpdir
< os::util::environment::setup_all_server_vars
< 
< os::log::system::start
< 
< os::start::configure_server
< os::start::server
< 
< export KUBECONFIG="${ADMIN_KUBECONFIG}"
< 
< os::start::registry
< oc rollout status dc/docker-registry
< 
< oc login ${MASTER_ADDR} -u ldap -p password --certificate-authority=${MASTER_CONFIG_DIR}/ca.crt
< oc new-project openldap
< 
< # create all the resources we need
< oc create -f test/extended/testdata/ldap
< 
< is_event_template=(               \
< "{{with \$tags := .status.tags}}" \
<     "{{range \$tag := \$tags}}"   \
<         "{{\$tag.tag}} "          \
<     "{{end}}"                     \
< "{{end}}"                         \
< )
< is_event_template=$(IFS=""; echo "${is_event_template[*]}") # re-formats template for use
< 
< os::test::junit::declare_suite_start "extended/ldap-groups/setup"
< # wait until the last event that occurred on the imagestream was the successful pull of the latest image
< os::cmd::try_until_text "oc get imagestream openldap --template='${is_event_template}'" 'latest' "$((60*TIME_SEC))"
< 
< # kick off a build and wait for it to finish
< oc start-build openldap  --follow --wait \
<     --from-dir=$(dirname "${BASH_SOURCE}")/../../images/openldap
< 
< server_ready_template=(                                  \
< "{{with \$items := .items}}"                             \
<     "{{with \$item := index \$items 0}}"                 \
<         "{{range \$map := \$item.status.conditions}}"    \
<             "{{with \$state := index \$map \"type\"}}"   \
<                 "{{\$state}}"                            \
<             "{{end}}"                                    \
<             "{{with \$valid := index \$map \"status\"}}" \
<                 "{{\$valid}} "                           \
<             "{{end}}"                                    \
<         "{{end}}"                                        \
<     "{{end}}"                                            \
< "{{end}}"                                                \
< )
< server_ready_template=$(IFS=$""; echo "${server_ready_template[*]}") # re-formats template for use
< 
< # wait for LDAP server to be ready
< os::cmd::try_until_text "oc get pods -l deploymentconfig=openldap-server --template='${server_ready_template}'" "ReadyTrue " "$((60*TIME_SEC))"
< 
< oc login -u system:admin -n openldap
< os::test::junit::declare_suite_end
< 
< LDAP_SERVICE_IP=$(oc get --template="{{ .spec.clusterIP }}" service openldap-server)
< 
95,96d32
< oc login -u system:admin -n default
< 
108a45
>        os::log::info "working dir ${WORKINGDIR}"
110c47
< 	cp test/extended/authentication/ldap/${current_schema}/* ${WORKINGDIR}
---
>        cp /tmp/ldap/${current_schema}/* ${WORKINGDIR}
128a66
>                os::util::sed "s@LDAP_CA@${LDAP_CA}@g" ${config}
```

**Comment by enj** [comment]
LGTM, just waiting on failure results from #23514

**Comment by stlaz** [comment]
eh, failed on building the test image, looks like expired RHEL subscription? -.-
/retest

**Pull request merged**
