### PR TITLE
Add username and password flags for request-token

### PR DESCRIPTION
**Pull request by wjiangjay**
```
openshift ex tokens request-token --server=https://MASTER_HOST:8443 -u username -p password                                                                                                                           
mX6ncaE7dbItJoa8JMxZI9wk8j1h6-iW5MX8ohSxOR0
```

### CODE REVIEW

**Comment by deads2k** [comment]
Why would I use this instead of `oc login` followed by `oc whoami -t`?

I don't think we want to keep `request-token` long term.

**Comment by liggitt** [comment]
in fact, as an experimental command, I'd consider dropping it now

**Comment by deads2k** [comment]
> in fact, as an experimental command, I'd consider dropping it now

Agree.

**Comment by wjiangjay** [comment]
Means we will not support generating new token via cli any more?

**Comment by liggitt** [comment]
logging in generates a new token and saves it, which is preferable.

**Comment by wjiangjay** [comment]
@liggitt ok, got it

**Pull request closed without merging**
