### PR TITLE
Default qps/burst to historical values

### PR DESCRIPTION
**Pull request by liggitt**
Default empty qps/burst values to historical values

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton @deads2k this would have prevented qos-gate

**Comment by smarterclayton** [comment]
QOS-gate - love it

**Comment by deads2k** [comment]
> QOS-gate - love it

I'm still bitter and I blame you! :)

**Comment by deads2k** [comment]
lgtm.  Surprised the fuzzer didn't need updating though.

**Comment by smarterclayton** [comment]
Is it kwaz-gate or queue-oh-ess-gate?

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
> Surprised the fuzzer didn't need updating though.

you can stop being surprised

**Comment by liggitt** [comment]
[merge]

**Comment by deads2k** [comment]
> you can stop being surprised

Good, that one worried me.

**Pull request merged**
