### PR TITLE
Fix network test exclusion

### PR DESCRIPTION
**Pull request by danwinship**
Completes https://github.com/openshift/kubernetes/pull/382 by revendoring and making the corresponding origin-side changes (resulting in a bunch of tests being un-skipped under ovn-kubernetes, and eventually in third-party network plugins).

### CODE REVIEW

**Comment by marun** [comment]
@danwinship lgtm, and I appreciate your taking the time to fix the docs!

**Comment by knobunc** [comment]
/approve

Thanks Dan

**Pull request merged**
