### PR TITLE
Bug 1737386: pkg/network: skip OPENSHIFT-MASQ for traffic already marked for masquerade

### PR DESCRIPTION
**Pull request by squeed**
Fixes: [1737386](https://bugzilla.redhat.com/show_bug.cgi?id=1737386)
Parent bz: [1726045](https://bugzilla.redhat.com/show_bug.cgi?id=1726045)

This backports the following openshift/sdn commits:
- c171df175a6be9ae9c97f84b0f8601f0443fb1f5 (openshift/sdn#13)
- b6e0ec16c9c35829a2b6b55fc6ebb3a3438420cb (openshift/sdn#17)

### CODE REVIEW

**Comment by squeed** [comment]
TooManyBuckets
/retest

**Comment by squeed** [comment]
TooManyBuckets still
/retest

**Comment by eparis** [comment]
needs review/lgtm

**Comment by eparis** [comment]
Still awaiting engineering team to review/lgtm/approve

**Pull request merged**
