### PR TITLE
Update oc logs examples, docs, bashcomp

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@smarterclayton are you ok with this?

**Comment by mfojtik** [comment]
@kargakis still LGTM ;-)

**Comment by kargakis** [comment]
This might break people but I guess we'll have it since it's already upstream

**Comment by kargakis** [comment]
upstream changes removed since they got in in the last rebase

[merge]

**Pull request merged**
