### PR TITLE
[WIP/PROPOSAL] Streamline openshfit development with `oc cluster up`

### PR DESCRIPTION
**Pull request by PI-Victor**
I really wanted to ditch vagrant+ scripts and oc cluster up looks promising for development. Didn't want to do this too comprehensive as i'm not sure if it's wanted, so for now it's a proposal.

This will "inject" a locally compiled `openshift` binary on top of `openshift/origin:latest` starting the cluster with your openshift dev version.

a faster ./make-release.sh although it doesn't update the docker-builder and s2i-builder images for now. if the feature is of any interest, will do that as well.

@csrwng since you are the master of oc cluster -  PTAL.
cc @bparees 
credits go to @rhcarvalho for the "slice" scripts :)

```
[ipalade@openshift-lab ~]$ oc cluster up --binary-path /home/ipalade/origin/_output/local/bin/linux/amd64/openshift
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... 
   Pulling image openshift/origin:latest
   Pulled 1/4 layers, 26% complete
   Pulled 2/4 layers, 72% complete
   Pulled 3/4 layers, 86% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Injecting custom OpenShift binary ... 
   Creating temporary Dockerfile
   Building OpenShift custom image
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK

```

p.s. renamed errors from the `bootstrap/docker` package to dockerErr since it clashes with Go's `errors` package.

### CODE REVIEW

**Comment by bparees** [comment]
there's actually already at least 2 variants on this, though neither are fully documented yet.  @csrwng created a docker proxy that will bindmount your local openshift binary into the origin images when they are started, so you don't have to build them.  and I think @derekwaynecarr might have explored another option in this space, i can't remember for sure.

so.. +1 in that clearly it's a good idea.  -1 in that we seem to be duplicating efforts, we need to stabilize one and document it.

**Comment by PI-Victor** [comment]
@bparees at least i broke even. :)
agreed they should be documented, i didn't find anything to be honest, i didn't know where to look besides https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md?
i'll be closing this, then. If you don't have to rebuild the images even better.

@csrwng can you link your efforts here so that i can use that, would be very useful?

**Comment by csrwng** [comment]
Hi @PI-Victor, you can find my proxy here:
https://github.com/csrwng/bindmountproxy/
I'm still going to be out on pto til July 6, so my involvement will be at best limited, but I agree with you and @bparees that we need a solution everyone can use and not duplicate efforts.

**Comment by PI-Victor** [comment]
@csrwng thank you, enjoy your PTO!

**Pull request closed without merging**
