### PR TITLE
Remove non-functional gu workload tests.

### PR DESCRIPTION
**Pull request by dgoodwin**
These never pass.

Also removing the non-gu workload tests flagged as broken two years ago.

### CODE REVIEW

**Review by fromanirh — COMMENTED** [review]
without `test/extended/topology_manager/resourcealign.go`, the remaining code in `test/extended/topology_manager/` is dead, so if you want to go this path you may want to remove the entire directory.

**Comment by dgoodwin** [comment]
Ack, thanks @fromanirh , does a delete all and restore when working sound ok to you?

**Comment by dgoodwin** [comment]
Updated to remove more dead code.

**Comment by DennisPeriquet** [comment]
@fromanirh do you happen to know what "gu" means? -- for example, the name of some tests mentions "gu workload".  Thanks.

**Comment by DennisPeriquet** [comment]
@fromanirh thanks for the link.  TIL a new word -- "gu" :-)

**Pull request merged**
