### PR TITLE
Bump the source-to-image and go-dockerclient

### PR DESCRIPTION
**Pull request by mfojtik**
This bump allow us to consume the recently added "injection" support to the container that runs the assemble which we intend to use in secrets injection stuff.

The go-dockerclient bump is required to access UploadToContainer() function.

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees PTAL

@php-coder FYI, once this gets merged, you don't have to do rebase for the secrets PR.

**Comment by liggitt** [comment]
Are we bumping the go-dockerclient consistent with upstream? If not, open a PR there to keep us in sync? Also need to run upstream e2e tests around portforward/exec/attach to make sure we don't regress there.

**Comment by mfojtik** [comment]
@liggitt thanks for reminder, will open an upstream PR.

**Comment by mfojtik** [comment]
@liggitt upstream PR: https://github.com/kubernetes/kubernetes/pull/19478

**Comment by bparees** [comment]
lgtm but per @liggitt's comment maybe it's safer to wait for k8s to pick this up, if we can get it in quickly.

**Comment by mfojtik** [comment]
@bparees I just fixed the upstream bump and it should be merged shortly. I synced the go-dockerclient across s2i/origin repos, so we should be fine as soon as k8s merges.

**Comment by mfojtik** [comment]
Probably need to add more commits to s2i, hold on merging this.

**Comment by mfojtik** [comment]
@liggitt @bparees the upstream PR is ok-to-merge now, can we merge this?

**Comment by mfojtik** [comment]
[test]

**Comment by liggitt** [comment]
let's hold this until after 1.1.1

**Comment by mfojtik** [comment]
@liggitt ack

**Comment by mfojtik** [comment]
@liggitt the upstream PR was merged, feel free to merge this after we cut 1.1.1.

**Comment by bparees** [comment]
@ncdc this bump includes the s2i always-pull-images-or-fail fix.

**Comment by mfojtik** [comment]
1.1.1 is out, [merge] ? :-) (at least two PR's are currently blocked by this ;-)

**Comment by mfojtik** [comment]
flake.. re-[merge]

**Pull request merged**
