### PR TITLE
Deprecate --api-version in oc config set-cluster

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1420280

PTAL @liggitt

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by liggitt** [comment]
LGTM

**Comment by fabianofranz** [comment]
device mapper flake re[test]

**Comment by fabianofranz** [comment]
[merge][severity: blocker]

**Pull request merged**
