### PR TITLE
refactored preservedFile()

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton PTAL

Refactored to make the method cleaner, removed the error pipeline from the method.

### CODE REVIEW

**Comment by kargakis** [comment]
I don't think we gain anything from this. The pipelining actually keeps this cleaner. @smarterclayton the next rebase will pick up the edit from upstream fyi. There are a couple of commits/PRs we have since they pulled our version in, should we push those upstream?

**Comment by kargakis** [comment]
@soltysh until you have a PR for the rebase, I would suggest opening an issue and documenting all those things we have to take into account.

**Comment by stevekuznetsov** [comment]
@kargakis having a method take in a parameter and never do anything with it except for regurgitate it smells bad. Having a method that's used two ways, one when one input variable is `nil` and one where it's not, smells bad. An entire use-case of a method that ignores the fact that the method has a return value also is weird. Figuring out what this method did and why it even accepted the `err` as a parameter was hard. Imo, this is an improvement for readability. If the code is changing soon, however, and this will be deprecated I don't feel strongly on it.

**Comment by deads2k** [comment]
> @kargakis having a method take in a parameter and never do anything with it except for regurgitate it smells bad. Having a method that's used two ways, one when one input variable is nil and one where it's not, smells bad. An entire use-case of a method that ignores the fact that the method has a return value also is weird. Figuring out what this method did and why it even accepted the err as a parameter was hard. Imo, this is an improvement for readability. If the code is changing soon, however, and this will be deprecated I don't feel strongly on it.

That's enough preference that its not worth this commit.  I wouldn't've coded it with `preservedFile`, but when I reviewed it it wasn't unreasonable.

**Comment by deads2k** [comment]
> There are a couple of commits/PRs we have since they pulled our version in, should we push those upstream?

@kargakis Yeah, those will need to go upstream.  We won't want to carry a separate `edit` command.  I'd like to see our factoring go upstream, but that'd be a bigger bit of work.

**Comment by stevekuznetsov** [comment]
@deads2k so this change will not be considered?

**Comment by deads2k** [comment]
> @deads2k so this change will not be considered?

No.  It's excessively opinionated without a clear benefit and provides no additional value.  This is a slightly more detailed, "put your brace on a new line" pull.

**Pull request closed without merging**
