### PR TITLE
CLI completions for persistent flags

### PR DESCRIPTION
**Pull request by fabianofranz**
Persistent flags completions don't work. This fixes completions for persistent flags in every command and also makes important flags like `--config` and certificate flags complete with filenames correctly.

Fixes https://github.com/openshift/origin/issues/4477
Fixes https://github.com/openshift/origin/issues/5695

### CODE REVIEW

**Comment by fabianofranz** [comment]
Will need to rebase (regenerate completions) when https://github.com/openshift/origin/pull/5704 lands.
FYI @jwforres 
@openshift/team-project-committers I know but crowds want this so badly.

**Comment by liggitt** [comment]
too big, 1.1.1

**Comment by jwforres** [comment]
@fabianofranz so do we still get any benefit from 5704?  or should we kill the merge on that

**Comment by liggitt** [comment]
5704 fixes all the flags I care about... keep it

**Comment by fabianofranz** [comment]
5704 fixes filename completions local flags, this fixes filename completions of persistent flags and actually normal completions of persistent flags (which apparently never worked).

**Comment by fabianofranz** [comment]
@liggitt don't you care about `--config`? master admins do.  :)

**Comment by liggitt** [comment]
5704 is reasonable for today, this is too big

**Comment by fabianofranz** [comment]
Ok

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
Rebased on top of https://github.com/openshift/origin/pull/5704 (which this one depends).

**Comment by eparis** [comment]
#5704 good, fixes regression.

This one ok, not upstream, not a regression, doesn't qualify as .1 in my mind.

**Comment by fabianofranz** [comment]
bump

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
