### PR TITLE
Show less output in test-cmd.sh

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

@stevekuznetsov do you have an issue for the "expect_success", "expect_failure", "expect_message", "expect_not_message" commands you wanted for test-cmd?  I want those two and I want a junit output option for them.

**Comment by stevekuznetsov** [comment]
There is an issue [here](https://github.com/openshift/origin/issues/4929). Please create one for JUnit and assign me.

**Comment by mfojtik** [comment]
LGTM

(and we should clean up the output from other tests as well)

**Comment by stevekuznetsov** [comment]
I'm on it.

**Comment by stevekuznetsov** [comment]
Once I get the `prune-groups` pulls straightened out, this is my next priority.

**Comment by smarterclayton** [comment]
@ncdc flake in https://api.travis-ci.org/jobs/89128842/log.txt?deansi=true on TestPortForward

**Comment by ncdc** [comment]
That's a new one. I haven't seen a 'send on closed channel' error with spdystream before.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
