### PR TITLE
add openshift-test patch workflow, derived from rh kernel spec file

### PR DESCRIPTION
**Pull request by jeremyeder**
This adds a small test-patch workflow optimization to openshift originally implemented in the RH kernel srpm.  It's purpose is to make it easy to apply a test patch to an unpacked SRPM, and to eventually rebuild the RPM without having to manually edit the spec file to add patch lines each time.

There is a 0-byte place-holder patch called ```openshift-test.patch``` in the root of the code base.

There are also 2 new functions added to the spec file:
```
ApplyPatch
ApplyOptionalPatch
```

openshift-test.patch uses ApplyOptionalPatch, and is skipped in the common-case where it is zero bytes.  If it is not zero bytes, the patch will be applied.

Finally, there is a new variable called ```buildid``` added to the spec file that allows a custom token be embedded within the RPM name.  This helps to distinguish between real builds and test builds.

### CODE REVIEW

**Comment by danmcp** [comment]
@sdodson Review please

**Comment by sdodson** [comment]
So the desired workflow is install the SRPM, hack up a patch in $RPM_SOURCE_DIR/openshift-test.patch then use rpmbuild? Why wouldn't you just work in the github checkout and build using tito with the ultimate goal of submitting an upstream PR rather than an RPM specfile patch?

As it is now tito fails so this would break our workflows. I'm not entirely sure why.

```
$ tito build --test --srpm
Building package [v0.0.1]
Wrote: /tmp/tito/origin-git-6440.72a61d3.tar.gz
error: Bad file: /tmp/tito/rpmbuild-originrSVEvf/SOURCES/openshift-test.patch: No such file or directory



RPM build errors:
    Bad file: /tmp/tito/rpmbuild-originrSVEvf/SOURCES/openshift-test.patch: No such file or directory


Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 367, in main
    return builder.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 144, in run
    self.srpm()
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 219, in srpm
    output = run_command_print(cmd)
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 445, in run_command_print
    raise RunCommandException(command, p.poll(), "\n".join(output))
tito.exception.RunCommandException: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-originrSVEvf" --define "_sourcedir /tmp/tito/rpmbuild-originrSVEvf/SOURCES" --define "_builddir /tmp/tito/rpmbuild-originrSVEvf/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define "ldflags -X github.com/openshift/origin/pkg/version.majorFromGit 1 -X github.com/openshift/origin/pkg/version.minorFromGit 0+ -X github.com/openshift/origin/pkg/version.versionFromGit v1.0.6-630-g72a61d3-dirty -X github.com/openshift/origin/pkg/version.commitFromGit 72a61d3 -X k8s.io/kubernetes/pkg/version.gitCommit 86b4e77 -X k8s.io/kubernetes/pkg/version.gitVersion v1.1.0-alpha.1-653-g86b4e77" --define "commit 72a61d3dfe12b45d7f25fd7ab64d1a9fcc0a3150"   --nodeps -bs /tmp/tito/rpmbuild-originrSVEvf/SOURCES/origin-git-6440.72a61d3/origin.spec
```

**Comment by sdodson** [comment]
@dgoodwin ^^

**Comment by dgoodwin** [comment]
Hmm looking this over, it's possible tito's --test can do this for you very cleanly @jeremyeder, no spec file changes required and no need to manually generate and write out patch files.

You would just clone the origin repo, make changes as you like, commit them normally to your branch, then when you want to make an rpm run: tito build --rpm --test

This takes the latest git HEAD (so you must commit your work to have it land in the rpm), and generates an rpm with a customized release indicating the base version (last tagged release), the number of commits since, and the exact git hash you ran it on.

Add -i to automatically install it on the current host after.

There's also a way to actually base off a tag, and apply all commits since as either one big patch or multiple patches (in some cases), and these get automatically added to spec file when it's being built. This is typically used more for "downstream" releases of an upstream open source project, and it's a little more permanent than it sounds like what you're after, but it seems like --test is probably pretty close.

Tito author's thought, use tito for this! :) I can work to make it better if needed but it sounds like --test might be really close to what you want, and it would keep the spec nice and clean.

**Comment by jeremyeder** [comment]
@dgoodwin no experience with tito -- can I use it w/OSE ?

**Comment by dgoodwin** [comment]
Yeah I think we use it to build and release all rpms across the board. (correct me if I'm wrong @sdodson) You just need to yum install tito (avail in Fedora and EPEL) and you're good to start doing the above process.

**Comment by sdodson** [comment]
Yes, you should be able to build origin rpms using `tito build --test --rpm` and it will include whatever is committed to your branch at that point in time. The only thing to note is that origin does not bump the specfile version, ever. That's left as an exercise for downstream projects but it should always be buildable.

**Comment by jeremyeder** [comment]
Ahh, this did it.  ```tito build --test --rpm --dist=.el7.TEST``` I'll try using it for a while.  My challenge will be ensuring my branch is in sync with the exact RPM versions I want to test.

**Comment by dgoodwin** [comment]
Cool, ping me if you there's anything I can help with!

**Comment by jeremyeder** [comment]
Closing for now.

**Pull request closed without merging**
