### PR TITLE
enable storage interface functions

### PR DESCRIPTION
**Pull request by deads2k**
Storage needs a list of interfaces that matches the API group its going to be referenced for with a version specified that's actually `GroupVersion` string.  Now even though that is fully qualifying and should allow for a shared set, no such set exists.  This builds the thing that's required several layers under.

@soltysh this fixed the create for me.

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by soltysh** [comment]
friday re-[merge]

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
