### PR TITLE
Renamed extended tests files by removing directory name from certain files

### PR DESCRIPTION
**Pull request by soltysh**
One of my remarks was not addressed in #6987 additionally I tried to unify the naming scheme. 

@mfojtik @smarterclayton ptal

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by smarterclayton** [comment]
That looks like a real failure?

**Comment by soltysh** [comment]
Yup, it looks like one. Will dig into in the morning.

**Comment by soltysh** [comment]
I had line break in jobs.go filename :/

**Comment by mfojtik** [comment]
@soltysh can you rebase?

**Comment by soltysh** [comment]
On it.

**Comment by soltysh** [comment]
Merge fail due to yum problems:
```
One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
```
re-[merge]

**Comment by bparees** [comment]
package name for "jobs.go" should probably have been changed to jobs instead of job w/ the rename.

also broken an import in extended_tests.go (fixing the import here: https://github.com/openshift/origin/pull/7200, will leave it up to you if you want the package renamed)

**Comment by marun** [comment]
Renaming test/extended/networking/networking_test.go -> test/extended/networking/extended.go broke the extended networking job because now there are no test files to build the networking test binary.  Unless anyone has objections, I'll rename to test/extended/networking/extended_test.go.

**Comment by marun** [comment]
Rename is included in #7244

**Pull request merged**
