### PR TITLE
RPMs: Provide both a host and guest tuning profile

### PR DESCRIPTION
**Pull request by sdodson**
openshift-node-host and openshift-node-guest profiles are to be used
for bare metal and virtual machine installations respectively. The rpm
installation scripts determine which profile is most appropriate based
on the output of the 'tuned-adm recommend' command so the user should
not need to make a selection on their own.

A manpage has been created as well.

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
re[test]

**Comment by sdodson** [comment]
re[test]

**Comment by sdodson** [comment]
@sosiouxme mind mergin this? In addition to providing profiles for both bare metal and virtual guest it fixes a problem introduced in https://github.com/openshift/origin/commit/ba6df48e727c4a3763d0fdbfe87e40f3d4c0a63d which prevent the profiles from loading properly.

**Comment by sosiouxme** [comment]
[merge]

**Pull request merged**
