### PR TITLE
Docker client CloseWrite follow-up

### PR DESCRIPTION
**Pull request by jim-minter**
Follow up of #18882 based on reworkings upstream (the original work was apparently problematic when the docker client was connecting to the server over TLS).

### CODE REVIEW

**Comment by jim-minter** [comment]
@liggitt ptal

**Comment by jim-minter** [comment]
also @mfojtik @bparees

**Comment by bparees** [comment]
@jim-minter so do we need to plan to get this into s2i and also 3.9? (and anywhere else we ported this?)  or is the TLS scenario not one that is problematic for our usage?

**Comment by jim-minter** [comment]
If this PR is judged fit to merge, I'll open a similar one against S2I.  I don't know if it's wanted against 3.9 or not.  I personally don't believe the TLS scenario matters to us, but others may disagree.

**Comment by bparees** [comment]
thanks @jim-minter

**Comment by mfojtik** [comment]
@jim-minter can this wait after we land the rebase? /cc @liggitt

**Comment by jim-minter** [comment]
@mfojtik IMO yes, it can wait.

**Comment by liggitt** [comment]
/retest
can proceed

**Comment by bparees** [comment]
/remove-lifecycle stale
/lifecycle frozen

/assign @mfojtik 

have we picked this up from upstream already?  If not, it should be merged.

**Comment by soltysh** [comment]
/hold 
for the rebase to land

**Pull request closed without merging**
