### PR TITLE
Make stanzas in test-cmd.sh independent

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@smarterclayton can I have this merged? Then Travis will finally accept https://github.com/openshift/origin/pull/2089 and https://github.com/openshift/origin/pull/2158

**Comment by smarterclayton** [comment]
Still failing

**Comment by kargakis** [comment]
@smarterclayton this is ready

**Comment by kargakis** [comment]
re[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
