### PR TITLE
Bump to kube 1.19-rc.2

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by sttts** [comment]
This will fail on https://github.com/openshift/origin/pull/25308.

**Comment by sttts** [comment]
The test results here are not relevant because they must run against 1.19 kube.

cluster-bot test runs of this PR and openshift/kubernetes#166:

- **e2e**: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1286578187295264768
- **e2e-serial**: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1286578613730152448

**Comment by damemi** [comment]
Pr to skip the failing `Kubectl client Simple pod should return command exit codes` test is here: https://github.com/openshift/origin/pull/25322

**Comment by marun** [comment]
> Pr to skip the failing `Kubectl client Simple pod should return command exit codes` test is here: #25322

I've included the skip in this PR to speed up testing: https://github.com/openshift/origin/pull/25314/commits/cbab573c5414fa82bfd16cadc826830ab87d2a3a#diff-6ba77494282f6e840f44b01ce97335af

**Comment by marun** [comment]
@sttts I've added the etcd-storage-path fix and skipped everything that was discussed as being skippable (with bz's as appropriate). 

I also reviewed the alpha feature gates in rules.go to make it obvious which are perpetual skips (e.g. gpu), which are alpha this release and should be reviewed next release, and which are beta this release and need to be enabled by the relevant teams in 4.6 (with tracking bz's to ensure it gets done).

**Comment by sttts** [comment]
`go.sum content is incorrect - did you run go mod tidy?`

**Comment by marun** [comment]
> go.sum content is incorrect - did you run go mod tidy?

🤦 updated

**Comment by marun** [comment]
The gcp-upgrade failures are persistent:

- `[sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial] [Suite:openshift]` 
- `[sig-network-edge] Application behind service load balancer with PDB is not disrupted`

**Comment by sttts** [comment]
/override ci/prow/e2e-cm

Still broken. @soltysh is working on fixing it.

**Comment by sttts** [comment]
/override ci/prow/e2e-cmd

Still broken. @soltysh is working on fixing it.

**Comment by sttts** [comment]
Look like random flake.

/test e2e-aws-serial

**Comment by sttts** [comment]
Install flake, PR history looks different. Moreover, this PR does not change the installer.

/test e2e-gcp

**Comment by bparees** [comment]
manually merged after review of passing tests in test history and discussion with @sttts and @marun

**Pull request merged**
