### PR TITLE
[WIP] re-enable complex console test scenarios

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[test] again

**Comment by fabianofranz** [comment]
[test] again

**Comment by fabianofranz** [comment]
[test] again

**Comment by fabianofranz** [comment]
[test] again

**Comment by fabianofranz** [comment]
[test] again

**Comment by danmcp** [comment]
@fabianofranz Bump

**Pull request closed without merging**
