### PR TITLE
Move SCC back into Origin

### PR DESCRIPTION
**Pull request by smarterclayton**
Should not be in upstream

### CODE REVIEW

**Comment by smarterclayton** [comment]
@pweil- can you review so that when the rebase happens we can do this move?  I want to remove packages declared in upstream code that really belong to us.

**Comment by pweil-** [comment]
yes, will take a look

**Comment by pweil-** [comment]
Looks straight forward to me.  

[test]

**Comment by pweil-** [comment]
Is the intent here to leave all the type definitions, storage registration, and cli code in upstream and just move the actual implementation.  If so, I think this covers it.

**Comment by smarterclayton** [comment]
As much as possible, for now.

**Comment by smarterclayton** [comment]
Going to hold this while David tries the "fork repo version" of rebase.

**Pull request closed without merging**
