### PR TITLE
Move verify-upstream-commits to a separate make target

### PR DESCRIPTION
**Pull request by soltysh**
Cherry-pick https://github.com/openshift/origin/pull/12056 to fix jenkins on non-master branch.

@liggitt @stevekuznetsov

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
And 1.3 too

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@derekwaynecarr this is the PR to unblock the 1.4 queue -- which PR were you noticing no tests triggering on?

**Comment by soltysh** [comment]
> And 1.3 too

In #12118

**Pull request merged**
