### PR TITLE
default sourceSecret for build

### PR DESCRIPTION
**Pull request by Mangirdaz**
When running openshift in secure environment we use secured GIT service. To enable users to use S2I generated builds, OR UI builds we need to be able to set default git source secret if none is provided.

Secret is provisioned centrally in each project, we just need to inject it to each and every build where it does not exist.

@csrwng @jim-minter ping

### CODE REVIEW

**Comment by Mangirdaz** [comment]
If this goes in, will change ansible to add one more variable to master-config.yml
```
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
      BuildDefaults:
        configuration:
          apiVersion: v1
          kind: BuildDefaultsConfig
          gitHTTPProxy: http://my.proxy:8080
          **sourceSecret: scmsecret**
```

Tested and works.

**Comment by stevekuznetsov** [comment]
Looks like some other generated documentation is out of date - try:

```sh
$ make update
```

That should catch all of them!

**Comment by Mangirdaz** [comment]
yes, checking now...

**Comment by liggitt** [comment]
I don't think I agree with having a cluster wide setting for a named sourceSecret, which has to be satisfied by a different actual secret in every namespace

**Comment by Mangirdaz** [comment]
It brings challenge how to lifecycle it,  but this is just to enable users to use "Example projects" in our internal git. It would be expectation that users either delete or change this secret when they become more mature users.

We could create global secret somewhere (openshift-infra namespace) but what to do with users who want to overwrite it, or delete it... It brings absolute new level of complexity...

suggestions are more than welcome :)

**Comment by bparees** [comment]
Since this is really just a secret "ref", and still requires the secret actually exist in every local project, i have mixed feelings, but mostly i think it's going to cause confusion when user's buildconfigs automatically reference a secret that doesn't exist in their project.  (On the plus side, every user can have their own unique secret still, they just have to make sure they create it in their project w/ the shared name being defined by the defaulting logic)

Or are you also proposing that a cluster-wide secret value is created/made available in every project?  (secrets can't be shared across projects, so you'd need to create it in each project).

**Comment by Mangirdaz** [comment]
My initial goal was to have cluster wide secret available in each project. As there is case when openshift runs in closed environments. 

What if we add checking to ref secret ONLY if it exist in the project?

So this will means:
1. If there a secret in project - it will be used.
2. If secret does not exist - default behavior. 
3. if user want, he/she can replace secret with their own and it will be used.
4. if user users its own secret with different name - it will be used.

So we would have ability to create builds in secure environments and user-experience will not change.

**Comment by csrwng** [comment]
@Mangirdaz @bparees I think it would be helpful to obtain the default from a current project annotation if it exists. That way you can specify which secret exists based on your project template (in addition to having a global value). We do this in other admission controls like runonceduration:
https://github.com/openshift/origin/blob/master/pkg/quota/admission/runonceduration/admission.go#L94

**Comment by bparees** [comment]
ignoring secret refs that can't be resolved is problematic because it will make it harder for the user to discover their error if they made a mistake in creating the reference.

if we're going to default the secret ref, we also need a way for users to opt out of the default (because they don't want to use any secret at all), not sure how they can do that since they'd have to specify a reference to avoid getting the default value.

**Comment by Mangirdaz** [comment]
we can just check, in certain order:

Check if global default secret is set:
    TRUE: 
        Check if user user any other secret as ref 
              TRUE: use default behavior, use user secret
              FALSE: check if global default secret exist
                      TRUE: use it in the build
                      FALSE: default behavior - dont use anything 
     FALSE: use default behavior.

Secret can be set in two ways with higher priority on project annotation vs master config.
1. project annotation
2. master-config file

**Comment by bparees** [comment]
that flow sounds ok to me as long as the admission controller is capable of checking if a secret exists or not.

**Comment by Mangirdaz** [comment]
Challenge accepted!

**Comment by liggitt** [comment]
that means that admission controller either needs to watch all secrets or do live lookups at create time. I still think a cluster-wide default name that gets resolved within specific namespaces is really hard to understand

**Comment by Mangirdaz** [comment]
as much as I care this can stay "undocumented feature" but we need this to make these **** build working in over-secure environments :D

**Comment by jim-minter** [comment]
Hi @Mangirdaz this pull has got confusing to review because it's somehow full of extraneous commits.  I think this is maybe because you are requesting a pull from your master branch.  I think it might help if you create a feature branch on Mangirdaz/origin and put your commit(s) there, and have that be reviewed.  That might also help with the conflicts.  Ping me on freenode if you want any advice walking through this.

**Comment by Mangirdaz** [comment]
will open new one

**Pull request closed without merging**
