### PR TITLE
UPSTREAM: 56503: MustRunAsNonRoot should reject a pod if it has non-numeric USER

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @liggitt @pweil- @openshift/sig-security

### CODE REVIEW

**Comment by simo5** [comment]
Pr is ok, but there are still a couple of comments upstream, will LGTM once merged in kube

**Comment by php-coder** [comment]
Test flake #17263
/test extended_conformance_install

**Comment by php-coder** [comment]
Test flake #17574
/test cmd

**Pull request merged**
