### PR TITLE
added go vet unreachable code testing

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt This adds `go tool vet -unreachable`

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by liggitt** [comment]
Go ahead and rebase these on master now that the framework went in

**Comment by stevekuznetsov** [comment]
@liggitt They're all rebased now

**Comment by liggitt** [comment]
LGTM, [merge]

**Pull request merged**
