### PR TITLE
UPSTREAM: 22516: kubectl: set maxUnavailable to 1 if both fenceposts resolve to zero

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @ironcladlou fyi

Fixes https://github.com/openshift/origin/issues/7700 and https://bugzilla.redhat.com/show_bug.cgi?id=1313158

### CODE REVIEW

**Comment by kargakis** [comment]
Merged upstream, merging here too [merge]

**Comment by liggitt** [comment]
it's not merged into the 1.2 branch, which is what we'll be based on... trying to think how best to manage the rebase, cherry picks upstream, and cherry picks here

**Comment by kargakis** [comment]
@liggitt this particular patch is a cherry-pick candidate upstream. We can push for the other patch that was just merged (https://github.com/openshift/origin/pull/7828) as a cherry-pick candidate too if we want but these patches are not 8000 lines so I am not sure it's worth the hassle...

**Comment by liggitt** [comment]
ok [merge]

**Pull request merged**
