### PR TITLE
[Release 3.10] vxlan backport

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
backport of https://github.com/openshift/origin/pull/20024

accompanied by api changes https://github.com/openshift/api/pull/90

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
extended_clusterup seeing this test flake https://github.com/openshift/origin/issues/20757

**Comment by danwinship** [comment]
looks good, I think. Were there any interesting changes from 3.11?

**Comment by JacobTanenbaum** [comment]
@danwinship There where no changes required.

**Comment by JacobTanenbaum** [comment]
@deads2k @liggitt PTAL

**Pull request closed without merging**
