### PR TITLE
Bug 2095623: Revert "Disable azure-file tests"

### PR DESCRIPTION
**Pull request by bertinatto**
This reverts commit 40a803314046e70f1ad9a8db6eaf4e9fece176f3. Azure File tests should have been fixed by https://github.com/openshift/origin/pull/27244 and https://github.com/openshift/release/pull/29477.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
I see successful Azure File tests in both [1] and [2].

@ravisantoshgudimetla are there any other jobs I should look into before merging this PR?

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27259/pull-ci-openshift-origin-master-e2e-azure/1537229221984735232
[2] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-azure-upgrade/1537229287315214336

**Comment by jsafrane** [comment]
>         "Operator \"kube-storage-version-migrator-operator\" produces more watch requests than expected: watchrequestcount=232, upperbound=174, ratio=1.3333333333333333",

/test e2e-azure

**Comment by bertinatto** [comment]
/hold cancel
Some GCP and AWS are failing, but this PR doesn't affect tests from those jobs

**Pull request merged**
