### PR TITLE
don't explicitly set the jvm architecture, let the image pick one

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal.  I think this parameter/setting the env pre-dated the image auto-choosing the right architecture.  it's now causing confusion for users who set their memory like to a high value, but don't change the arch to 64 bit, so they still end up with a 32bit jvm.  (which, you'd think would cause errors when you try to run a large heap with a 32bit jvm, but maybe openjdk handles that differently).

**Comment by gabemontero** [comment]
@bparees - I'm good with the rationale

but this instance (re)ignites for me the questions of whether the jenkins templates should be converted to yaml.  Or maybe provide yaml versions if deleting the json files breaks dependencies, etc.

With yaml though, we could provide a comment section that explains "hey, we don't set it by default, but if you want to override the default arch decision the image makes, set this template parameter"

**Comment by bparees** [comment]
> With yaml though, we could provide a comment section that explains "hey, we don't set it by default, but if you want to override the default arch decision the image makes, set this template parameter"

no user would see that comment anyway (the user's instantiating the template are not looking at the raw json/yaml, they're looking at the web console), so I doubt it would help much.

We could have put such an explanation of the parameter in the parameter.description field(if we kept the parameter, but that would rely on people scrolling through all the parameters and reading the description), or the overall template description could include an explanation of the env var to set if you want to set the arch.  (Could also be part of the message that's shown to users when that instantiate the template..."your jenkins has been provisioned with $ARCH, if you want to override that, set the env var to something else".

But for now i'm content to have faith in our defaulting and assume that anyone who needs to change the arch can go find+set the env var themselves.

**Comment by gabemontero** [comment]
On Thu, Sep 28, 2017 at 11:20 AM, Ben Parees <notifications@github.com>
wrote:

> With yaml though, we could provide a comment section that explains "hey,
> we don't set it by default, but if you want to override the default arch
> decision the image makes, set this template parameter"
>
> no user would see that comment anyway (the user's instantiating the
> template are not looking at the raw json/yaml, they're looking at the web
> console), so I doubt it would help much.
>
Good point

> We could have put such an explanation of the parameter in the
> parameter.description field(if we kept the parameter, but that would rely
> on people scrolling through all the parameters and reading the
> description), or the overall template description could include an
> explanation of the env var to set if you want to set the arch. (Could also
> be part of the message that's shown to users when that instantiate the
> template..."your jenkins has been provisioned with $ARCH, if you want to
> override that, set the env var to something else".
>
> But for now i'm content to have faith in our defaulting and assume that
> anyone who needs to change the arch can go find+set the env var themselves.
>
Cool

**Pull request merged**
