### PR TITLE
o Add locking around ops that change state. Its better to go   lockless eventually and use a "shadow" (cloned) copy of the   config when we do a reload. o Fixes as per @smarterclayton review comments.

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by deads2k** [comment]
@danmcp another unprotected one.  Also, why is our bot master specific?

**Comment by danmcp** [comment]
@deads2k You should talk to the person who added the branch about protecting it.

As far as the bot.  There are a few steps to enable multiple branches.  

1) Have branch specific images to corresponding to any special requirements in the branches if necessary.
2) Update the jobs to accept a branch.  That's only been done for test so far [test] for far.  [testonlyextended] and [merge] are not covered yet.
3) Update the bot to allow multiple branches (only takes a few seconds when we are ready)

**Comment by deads2k** [comment]
Now with protection.

@smarterclayton we're going to run a service stream on 1.2?

**Comment by smarterclayton** [comment]
I'm considering it.

**Comment by smarterclayton** [comment]
But right now I'm just getting everything I need to cut 1.2, given that none of our infra is set up to support it.

**Pull request merged**
