### PR TITLE
oc: update valid arguments for upstream commands

### PR DESCRIPTION
**Pull request by kargakis**
@openshift/cli-review

### CODE REVIEW

**Comment by oatmealraisin** [comment]
lgtm, @bparees @fabianofranz merge?

Most of this is autogen, correct?

**Comment by bparees** [comment]
@kargakis did you really mean to assign @oatmealraisin on this?

**Comment by kargakis** [comment]
More like @juanvallejo actually, sorry :)

**Comment by fabianofranz** [comment]
LGTM

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11318 [test]

**Comment by kargakis** [comment]
yum [test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/9642 [test]

**Pull request merged**
