### PR TITLE
Make hook containers inherit environment

### LINKED ISSUE #2005: Deployment hook environment isn't inherited from target container
When defining a deployment lifecycle hook, only the environment specified on the hook itself is present in the environment of the hook container. The hook container environment should be inherited from the container the hook points to, and additional environment specified on the hook definition should override the inherited defaults.

### PR DESCRIPTION
**Pull request by ironcladlou**
Fixes  #2005

### CODE REVIEW

**Comment by pmorie** [comment]
LGTM

**Comment by smarterclayton** [comment]
copy resource limits

**Comment by ironcladlou** [comment]
@smarterclayton 
>copy resource limits

I'll make another PR for that.

**Comment by smarterclayton** [comment]
Also, go and do a review of all the pod template items that might need to be copied in that one.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
