### PR TITLE
make prometheus example work on older servers

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton PTAL

Fixes: https://github.com/openshift/origin/issues/14666

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge][severity:bug]

**Comment by mfojtik** [comment]
actually green button merge this, no conflict expected and this is too small to run 2h merge.

**Comment by smarterclayton** [comment]
This is intentional.

**Comment by smarterclayton** [comment]
Please revert this, we do not support everything in 3.5 for this template.

**Comment by smarterclayton** [comment]
Reverted in #14776

**Pull request merged**
