### PR TITLE
Re-enable scheduler serial tests

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Re-enabling scheduler serial tests with some picks from upstream. Will fix them, if they don't pass.

/cc @deads2k @sjenning

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@deads2k seems serial scheduling tests are passing with my pr.

**Comment by ravisantoshgudimetla** [comment]
:retest

**Comment by sjenning** [comment]
looks like you need to gofmt `test/extended/util/test.go`

**Comment by ravisantoshgudimetla** [comment]
@sjenning - This should pass now. Can you lgtm this PR once this passes tests?

**Comment by ravisantoshgudimetla** [comment]
@sjenning - Adding lgtm label here?

**Comment by ravisantoshgudimetla** [comment]
Waiting on https://github.com/openshift/origin/pull/22546 to merge

/hold.

**Pull request merged**
