### PR TITLE
Add a test to check that Docker strategy sets resource limits

### PR DESCRIPTION
**Pull request by nalind**
Add a test that checks that the builder sets resource limits for Docker strategy builds, and extend the test for s2i strategy builds to check for CPU resource limits.

### CODE REVIEW

**Comment by nalind** [comment]
Not expected to pass without https://github.com/openshift/builder/pull/341.

**Comment by coreydaley** [comment]
Have you been able to run these two tests together using cluster bot yet?

**Comment by nalind** [comment]
Yes.  The conversion of cpu.weight values to a cpu.shares value in [cgroupsv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1651315260671397888) is imprecise because it's all done with integer math, but I think it passes in [cgroupsv1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1651315260549763072).  I'm about to try to correct that.

**Comment by nalind** [comment]
I think it'll pass now, but [it's timing out](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1651951423375544320) during the build that the test runs.  It's happening before we start to process any RUN instructions which would bt be affected by the changes we're making here, which makes it rather confusing.

**Comment by nalind** [comment]
Bringing up a 4.12 aws,cgroupsv2 cluster with the bot, updating the builder image in the controller configuration, and pointing the tests at it, they pass.  That was on a second attempt, because I forgot to update the builder image before I ran the tests the first time, and the tests both failed while looking for "QUOTA=40000" in the build logs.

**Comment by nalind** [comment]
Still timing out testing Docker strategy in an [aws,cgroupsv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1653035047042682880) test cluster, though the corresponding s2i strategy test passed just fine.

**Comment by nalind** [comment]
The original report didn't mention anything about `cpu.shares`/`cpu.weight`, so I'm taking that out to see if that's triggering the timeouts in the test.  The rounding errors converting from v1 to v2 to v1 to v2 (and possibly to v1 to v2 again) accumulate quickly.

**Comment by nalind** [comment]
Okay, with the new test reworked to force an error so that the whole log will show up, the new and updated tests are passing for [cgroups v1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1653479118525698048), but it's still timing out for [cgroups v2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1653479061193756672).  Re-running that in case it's a flake.

**Comment by nalind** [comment]
Bumping the CPU limits and switching the Docker-strategy build to use a smaller base image seems to have done the trick - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1656637396793430016 shows the new test and the updated test both passing.

**Pull request closed without merging**
