### PR TITLE
Fix deployer pod tolerations

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/17445

Don't want to block this on missing unit tests, I'm going to add issue for that.

### CODE REVIEW

**Comment by tnozicka** [comment]
/lgtm cancel
there are some worries about the need to filter tolerations

**Comment by mfojtik** [comment]
@smarterclayton can you elaborate what you want to filter in tolerations?

**Comment by danielkucera** [comment]
Hi, what are we waiting for, guys?

**Comment by mfojtik** [comment]
@smarterclayton ping

https://bugzilla.redhat.com/show_bug.cgi?id=1584910

/remove-lifecycle stale

**Pull request merged**
