### PR TITLE
updated tmpdir for e2e-docker

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Fixes https://github.com/openshift/origin/issues/8050

@smarterclayton PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by stevekuznetsov** [comment]
e2e flake [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13076/console):
```
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
info: password for stats user admin has been set to GDsFvYgQtB
Error from server: Timeout: timed out waiting for deployment test/failing-dc-mid-1 to start after 10s
!!! Error in hack/../hack/../test/end-to-end/core.sh:198
	'oc logs -f dc/failing-dc-mid' exited with status 1
```

potentially https://github.com/openshift/origin/issues/7616 ?

@deads2k unrelated flake on 1/2 runs, "green" enough? Logs show up fine https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13077/artifact/origin/artifacts/test-end-to-end-docker/

**Comment by deads2k** [comment]
> @deads2k unrelated flake on 1/2 runs, "green" enough?

Have you written indicators?

**Comment by stevekuznetsov** [comment]
@deads2k unclear how to best indicate it - @liggitt what is the definitive mark of that issue?

**Comment by liggitt** [comment]
the message "cpu.shares: no such file or directory" in the /artifact/origin/artifacts/test-end-to-end-docker/logs/container-origin.log file. not sure failure indications can look in artifacts

**Comment by deads2k** [comment]
> the message "cpu.shares: no such file or directory" in the /artifact/origin/artifacts/test-end-to-end-docker/logs/container-origin.log file. not sure failure indications can look in artifacts

not wit this tool.  Indicating on the symptom line may be the next best option.

[merge]

**Comment by liggitt** [comment]
it manifests in a bunch of different places (dc scale, builds, all over... possibly anywhere we can create a container)

**Pull request merged**
