### PR TITLE
fix mutex for projectstatus

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/3677

@kargakis

### CODE REVIEW

**Comment by liggitt** [comment]
Simply to just do the data load in parallel, process serially, no mutex needed?

**Comment by deads2k** [comment]
@smarterclayton added `parallel.Run` as well.

@ironcladlou ptal

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
