### PR TITLE
always flake on non-zero disruption for pod network communication so …

### PR DESCRIPTION
**Pull request by deads2k**
…we can find it in CI

not the easiest thing to do, but this kept the code paths unified.

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

need to confirm that backend disruption has the values we expect before merge.

**Comment by dgoodwin** [comment]
Looks fine but I think we've got a much bigger problem, all the "should be available" tests do not appear to be running in your presubmits, nor anywhere in [sippy](https://sippy.dptools.openshift.org/sippy-ng/tests/4.14?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522current_runs%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25227%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257D%252C%257B%2522id%2522%253A99%252C%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522should%2520be%2520available%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage). Did this accidentally get broken during the refactors?

**Comment by deads2k** [comment]
> Also I'd argue this would be better accomplished in the dashboard, show the % of results that are non-zero by NURP. This would be far more discoverable than a test that someone has to remember to lookup by name.

@dgoodwin what's the plan to go from "p95 is high", to finding the runs?

**Comment by dgoodwin** [comment]
Just below the main graphs you'll see a panel for Most Recent Runs, expand that and you've got the last few hundred runs with links right to the prow job, and the disruption value right beside them.

**Comment by deads2k** [comment]
link please?  Networking and myself have been looking for this.

**Comment by dgoodwin** [comment]
https://grafana-loki.ci.openshift.org/d/ISnBj4LVk/disruption?orgId=1

Will show whatever runs match your filters selected.

**Comment by deads2k** [comment]
Can you link to the network connection tests with only non-zero values showing?

**Comment by dgoodwin** [comment]
We don't have that yet, I was saying above that dash would be a more discoverable place to do this. 

In the meantime though if anyone needs to query this, hit the down arrow by Last 200 Job Runs, select Explore, you can now edit the query to include DisruptionSeconds > 0. [Resulting URL links are sharable](https://grafana-loki.ci.openshift.org/explore?left=%7B%22datasource%22:%22P8042CABD7873BED6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-bigquery-datasource%22,%22uid%22:%22P8042CABD7873BED6%22%7D,%22rawSql%22:%22SELECT%5Cn%20%20JobName,%5Cn%20%20BackendName,%5Cn%20%20DisruptionSeconds%20AS%20Seconds,%5Cn%20%20JobRunStartTime,%5Cn%20%20Platform,%5Cn%20%20Release,%5Cn%20%20UpgradeType,%5Cn%20%20Network,%5Cn%20%20Topology,%5Cn%20%20JobRunName%5CnFROM%5Cn%20%20%60openshift-ci-data-analysis.ci_data.UnifiedBackendDisruption%60%5CnWHERE%5Cn%20%20Release%20IN%20%28%274.14%27%29%5Cn%20%20AND%20UpgradeType%20in%20%28%27minor%27,%27micro%27%29%5Cn%20%20AND%20Architecture%20IN%20%28%27amd64%27%29%5Cn%20%20AND%20BackendName%20IN%20%28%27ingress-to-console-new-connections%27,%27kube-api-new-connections%27,%27service-load-balancer-with-pdb-new-connections%27%29%5Cn%20%20AND%20Network%20IN%20%28%27sdn%27,%27ovn%27%29%5Cn%20%20AND%20Topology%20in%20%28%27ha%27%29%5Cn%20%20AND%20Platform%20in%20%28%27aws%27,%27azure%27,%27gcp%27,%27metal%27,%27vsphere%27%29%5Cn%20%20AND%20JobRunStartTime%20%3E%20TIMESTAMP_MILLIS%281691347061192%29%5Cn%20%20AND%20JobRunStartTime%20%3C%20TIMESTAMP_MILLIS%281693939061192%29%5Cn%20%20AND%20DisruptionSeconds%20%3E%200%5CnORDER%20BY%5Cn%20%20JobRunStartTime%20DESC%5CnLIMIT%5Cn%20%20200%22,%22format%22:1,%22connectionArgs%22:%7B%22location%22:%22US%22%7D,%22project%22:%22openshift-ci-data-analysis%22,%22location%22:%22US%22,%22editorMode%22:%22code%22,%22sql%22:%7B%22columns%22:%5B%7B%22type%22:%22function%22,%22parameters%22:%5B%5D%7D%5D,%22groupBy%22:%5B%7B%22type%22:%22groupBy%22,%22property%22:%7B%22type%22:%22string%22%7D%7D%5D,%22limit%22:50%7D,%22rawQuery%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D&orgId=1).

**Pull request closed without merging**
