### PR TITLE
[release-3.11] Bug 1855852: Backport HAProxy report all backend metrics

### PR DESCRIPTION
**Pull request by sgreene570**
This is the 3.11.z backport of https://github.com/openshift/router/pull/132
---

When no servers are exposed, backend metrics are needed to see
how many requests are making it to a service. If we don't report
them users can't see when no pods are up (a crashlooping service
for instance would have no metrics at all because no pods are
ready). Always report all backend metrics. Increases cardinality
by O(routes), but prometheus is a lot faster now.

### CODE REVIEW

**Comment by Miciah** [comment]
/lgtm
Thanks!

**Comment by Miciah** [comment]
@sgreene570, #25131 got https://github.com/openshift/router/pull/127/commits/4aa8e05c8306bdbd87555447bb0cb50be819e278, and this PR gets https://github.com/openshift/router/pull/132/commits/3b287c6d70a8c4269bbc8576c4b408327c8fe5dd, but did we get https://github.com/openshift/router/pull/128/commits?  I'm asking because https://github.com/openshift/router/pull/141/commits for 4.4 included all of the aforementioned commits.

**Comment by sgreene570** [comment]
> @sgreene570 did we get https://github.com/openshift/router/pull/128/commits? 

Looks like we did not. Shall I add those commits here ?

**Comment by sgreene570** [comment]
Amended this PR to include https://github.com/openshift/router/pull/128/commits for backporting.

**Comment by sgreene570** [comment]
test failures may have been resolved by recent CI fixes
/retest

**Comment by sgreene570** [comment]
These changes are not passing CI due to an index of out range panic
/hold

**Comment by sgreene570** [comment]
Dropped the additional commits mentioned in https://github.com/openshift/origin/pull/25271#issuecomment-656916542 since they were problematic. We can address those backports in the future if a need arises.

**Comment by sgreene570** [comment]
> test "unit" failed: could not create watcher for pod: unknown (get pods)

/retest

**Pull request merged**
