### PR TITLE
add timing statements to scripts to watch in jenkins

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
infrastructure re[test]

**Comment by deads2k** [comment]
install-assets 270
build-base-images 27
build-release 194
build-images 112
build-go 33
verifies ~10
unit-test 260
test-cmd 157
test-integration 832
e2e (including assets) 307
test-assets 27
total 2229 = 37 minutes (+ 3 more for ec2 setup)

**Comment by deads2k** [comment]
@liggitt I want this.  I suspect install-assets is sometimes insane and this would help harvest run times.

**Comment by deads2k** [comment]
@sdodson @Miciah is there a better way to do this?  I want wall-clock time on scripts without having to chase every call to the script.

**Comment by sdodson** [comment]
Looks fine to me, if there's a larger script that's calling all of these tasks in sequence you could re-factor the timings out to that script but if these are each being called individually I think the way you've done it makes sense.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
