### PR TITLE
Improve the image stream describer

### PR DESCRIPTION
**Pull request by smarterclayton**
Multiple entries

```
$ oc describe is wildfly

		Unique Images:	3
		Tags:		5

		latest
		  pushed image

		  * registry:5000/foo/bar@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
		      17 months ago
		    registry:5000/foo/bar@sha256:062b80555a5dd7f5d58e78b266785a399277ff8c3e402ce5fa5d8571788e6bad
		      17 months ago

		spec1
		  tagged from foo/bar:latest

		  * registry:5000/foo/bar@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
		      17 months ago

		spec2
		  tagged from mysql/latest@sha256:e52c6534db85036dabac5e71ff14e720db94def2d90f986f3548425ea27b3719

		  * mysql:latest
		      17 months ago	sha256:e52c6534db85036dabac5e71ff14e720db94def2d90f986f3548425ea27b3719

		spec3
		  updates automatically from registry mysql

		  ~ importing latest image ...
		  ! error: Import failed (NotFound): Image not found due to error
		      292 years ago
		  * mysql:latest
		      17 months ago	sha256:e52c6534db85036dabac5e71ff14e720db94def2d90f986f3548425ea27b3719

		spec4
		  reference to registry mysql:2
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Spawned https://github.com/openshift/origin/issues/10404

**Comment by smarterclayton** [comment]
@jwforres

**Comment by jwforres** [comment]
the indentation on "importing latest image" feels wrong, it needs something in front of it like you did with the ! on the error, a few ideas:

```
 ?  importing latest image...
(?) importing latest image...
(i) importing latest image...
<?> importing latest image...
```

**Comment by jwforres** [comment]
even just having the -> in front of the importing row would look less strange

**Comment by jwforres** [comment]
feels like a lot of whitespace between all the rows of detail on the tag, i could at least see dropping the newline between the description and the tags

**Comment by jwforres** [comment]
only other thing i'm debating is whether it should have something like a History label above the tag history

**Comment by smarterclayton** [comment]
I could trim "current" arrow down to just right arrow, or replace it
with *, and use > for importing

**Comment by smarterclayton** [comment]
Yeah, too much white space when little data, and not enough when there is a lot.

Single tag also looks wierd.

**Comment by jwforres** [comment]
if the arrow was supposed to mean "current" then why is it showing up next
to all of the old images?

**Comment by smarterclayton** [comment]
?  Should only show up next to the currently tagged one.

**Comment by smarterclayton** [comment]
Updated descriptions above

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@mfojtik @bparees any suggestions

**Comment by bparees** [comment]
"tagged from" strikes me as weird phrasing.  "tag source" "image source", even "tag from" seems more logical to me because at this point i don't care about the action that created it, i care about what it represents.

how about listing the supports annotation values when present?

what is unique images telling me that i actually need to know/care about?

what is the number of tags telling me, since you proceed to list all the tags anyway?  do i really care?

**Comment by smarterclayton** [comment]
> "tagged from" strikes me as weird phrasing. "tag source" "image source", even "tag from" seems more logical to me because at this point i don't care about the action that created it, i care about what it represents.

The message is there to help the user understand whether the tag is automatically updated or not.  There are two automatic methods - local tag references, and scheduled.  There are two manual methods - push, and tagging.  So the string needs to be a "process of" not just "how it happened".

> how about listing the supports annotation values when present?

What about the other annotations?  Does an end user need to know all of them?

> what is unique images telling me that i actually need to know/care about?

Quota

> what is the number of tags telling me, since you proceed to list all the tags anyway? do i really care?

limit range on # of tags

**Comment by bparees** [comment]
>  There are two manual methods - push, and tagging. So the string needs to be a "process of" not just "how it happened".

so aren't there really 3+ mechanisms?  imported, tagged, pushed?

> What about the other annotations? Does an end user need to know all of them?

no, but supports seems at least as relevant as "tags", so if you're going to do that one, doing supports seems logical to me.

**Comment by smarterclayton** [comment]
On Aug 18, 2016, at 11:23 AM, Ben Parees <notifications@github.com> wrote:

There are two manual methods - push, and tagging. So the string needs to be
a "process of" not just "how it happened".

so aren't there really 3+ mechanisms? imported, tagged, pushed?


Yes, which is why pushed has different output.  Tagged means "you tagged
this in once right now".  Do you feel the output doesn't convey that?

What about the other annotations? Does an end user need to know all of them?

no, but supports seems at least as relevant as "tags", so if you're going
to do that one, doing supports seems logical to me.

How would a human use supports?  Most of the time it roughly matches tags.
Does console show supports?

**Comment by bparees** [comment]
>  Tagged means "you tagged this in once right now". Do you feel the output doesn't convey that?

It conveys it as long as that wording is only used when i explicilty did an "oc tag" operation, and not:

* when I ran a build that pushed to this imagestream
* when i create the imagestream and it auto-found+imported the tag initially
* when i create the imagestreamtag with "scheduled=true" and it got this value from the auto-import process

> How would a human use supports? Most of the time it roughly matches tags. Does console show supports?

not sure, only thing i know definitely uses it is new-app, but that seems like it would make it enough of a first class concept that people would care.

**Comment by bparees** [comment]
(I should note, in case it's not obvious, i'm reviewing the output you provided, not the code)

**Comment by jwforres** [comment]
updated output in https://github.com/openshift/origin/pull/10405#issue-171039683 LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
