### PR TITLE
Deployment hooks inherit resources and working dir

### PR DESCRIPTION
**Pull request by ironcladlou**
Make deployment hooks inherit resources and working dir from the
base container. Refactor the pod building code and improve the unit
tests.

### CODE REVIEW

**Comment by ironcladlou** [comment]
This is a followup to #2007.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by ironcladlou** [comment]
[merge] again to see if test-cmd.sh is flaking.

**Comment by ironcladlou** [comment]
[test] me.

**Comment by derekwaynecarr** [comment]
Want to make sure I understand this for resources.  Can each hook have different resource requirements in the deployment process (CPU / Memory)?  

So we set resources on the pod that does the deployment on the deployment strategy, but the resources here are whatever is explicitly defined on the container spec for the individual hooks called from that pod? 

So that would use the defaults or whatever was explicitly set on that spec, right?

**Comment by ironcladlou** [comment]
>Want to make sure I understand this for resources. Can each hook have different resource requirements in the deployment process (CPU / Memory)?

The hook's resources will mirror the resources of the container to which the hook refers. The hook resources cannot be set directly by the user.

>So we set resources on the pod that does the deployment on the deployment strategy, but the resources here are whatever is explicitly defined on the container spec for the individual hooks called from that pod? So that would use the defaults or whatever was explicitly set on that spec, right?

So, the idea is that pod based hooks are generally clones of your primary deployment container, and so likely need the same resources. For example, if you're deploying a rails container in a frontend pod, and want to make a hook run a rails migration, your hook container (which will refer to/be based upon the rails container) likely needs a similar environment.

Resources on the strategy to be applied to the deployer pod seem like they would be mostly useful for a custom strategy; the recreate and upcoming rolling strategy have absolutely minimal CPU/memory requirements (they're just making a few API calls and waiting around).

**Pull request merged**
