### PR TITLE
Bug 1761815: Informers can miss notifications

### PR DESCRIPTION
**Pull request by p0lyn0mial**
clean pick-up.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
will add a BZ once approved.

**Comment by p0lyn0mial** [comment]
> /home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 108: OS_GIT_MAJOR: unbound variable

the script is broken, I will have to fix it.

**Comment by soltysh** [comment]
> > /home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 108: OS_GIT_MAJOR: unbound variable
> 
> the script is broken, I will have to fix it.

Ignore it, we don't rely on travis, we have our own testing infra, it should not block your PR.

**Comment by p0lyn0mial** [comment]
/hold

until the upstream PR merges

**Comment by p0lyn0mial** [comment]
/hold

@deads2k if we want to squeeze in without fixing `Travis CI` step then you need to manually merge it.

**Comment by soltysh** [comment]
There was not 4.0 release, this is not needed.
/close

**Pull request closed without merging**
