### PR TITLE
UPSTREAM: 11694: http proxy support for exec/pf

### PR DESCRIPTION
**Pull request by ncdc**
Pull in support for http proxy with exec/attach/port forward that just missed the last rebase by a few hours. Note, this only pulls in the `pkg` file. The other changes in 11694 are all e2e test related, and they're not 100% correct and had to be corrected in a series of follow-ups, so I chose not to include any of that here. They can come in with the next rebase, if that's ok.

@sdodson @deads2k @liggitt @smarterclayton @brenton

### CODE REVIEW

**Comment by liggitt** [comment]
Is this the latest state of the spdy roundtripper upstream including any follow-up fixes? If so, LGTM

**Comment by ncdc** [comment]
@liggitt I diffed w/the upstream file and it came out clean.

**Comment by ncdc** [comment]
After spending 15 minutes trying to figure out why `hack/cherry-pick.sh` wasn't working (#5395), I gave up and did it by hand...

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[merge]

**Comment by smarterclayton** [comment]
Probably because it's already merged?

On Oct 26, 2015, at 9:33 AM, Andy Goldstein <notifications@github.com>
wrote:

After spending 15 minutes trying to figure out why hack/cherry-pick.sh
wasn't working (#5395 <https://github.com/openshift/origin/pull/5395>), I
gave up and did it by hand...

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5397#issuecomment-151134409>.

**Comment by ncdc** [comment]
It merged upstream, but a few hours after we started our rebase, so it missed getting into origin with the rebase. The problem is cherry-pick.sh doesn't support binary diffs for git apply. I have an open PR to fix that.

**Pull request merged**
