### PR TITLE
Community NodeJS builder image examples from ryanj/origin-s2i-nodejs

### PR DESCRIPTION
**Pull request by ryanj**
@gshipley said I should send a PR for my NodeJS s2i builder imagestream examples.

Not sure if this is the best place for them... feel free to send suggestions if not.

### CODE REVIEW

**Comment by ryanj** [comment]
Installation notes: https://github.com/ryanj/origin-s2i-nodejs#installation

**Comment by bparees** [comment]
I think we should just keep the imagestream definitions for these community images in the image github repo itself, rather than elevating them to the origin repo (we don't do this for any other community image, or even things like the middleware images).

We should also consider moving @ryanj's nodejs repos into the openshift-s2i community org.

**Comment by ryanj** [comment]
Thanks @bparees!

Here is the imagestream reference in my repo: https://github.com/ryanj/origin-s2i-nodejs/blob/master/centos7-s2i-nodejs.json

@jawnsy would you be able to clone my repo into the openshift-s2i org so it's easier to find?  We can repoint the upstream reference to openshift-s2i as well (if you have maintainers available).

**Comment by jawnsy** [comment]
@ryanj Can do! I'm curious how we can handle confusion about this versus the other one: https://github.com/sclorg/s2i-nodejs-container

Ideally we should cross-link between them and have a clear statement about when users should choose both. Also what's the relationship between the two of these?

**Comment by bparees** [comment]
@jawnsy +1, i'm worried about the potential confusion as well.

The relationship between them is sclorg's is the official nodejs image for openshift, built using SCL packages which are supported by redhat, and for which a rhel image is available in addition to the centos version.  

This (ryan's) image is a community maintained image built using latest/unsupported(by redhat) versions of nodejs.  So it offers an additional set of nodejs versions that redhat doesn't offer/support, primarily.

**Comment by jawnsy** [comment]
@bparees Is there an upstream/downstream type relationship between these? Or are they completely separate projects? Do they share common code? Just wondering how we intend to handle maintenance of this. If we find bugs, do we have to remember to patch them both?

**Comment by bparees** [comment]
@jawnsy they're basically completely separate.  @ryanj created them based on what was in sclorg, but i think it's significantly diverged since then and there's no definitive plan/intent to keep them in sync.

**Comment by pweil-** [comment]
closing due to inactivity

**Pull request closed without merging**
