### PR TITLE
remove unnecessary internal client

### PR DESCRIPTION
**Pull request by deads2k**
found while trying to unwind admission config enough to make a forward building kubeapiserver.

/assign @sttts

### CODE REVIEW

**Comment by ironcladlou** [comment]
@pravisankar PTAL

**Comment by pravisankar** [comment]
/hold
Build is failing with this error:
# github.com/openshift/origin/pkg/cmd/server/origin
pkg/cmd/server/origin/master_config.go:158:2: kubeInternalClient declared and not used

**Comment by deads2k** [comment]
/hold

in case I get lucky

**Pull request closed without merging**
