### PR TITLE
NO-JIRA: techpreview can install unstable CRDs

### PR DESCRIPTION
**Pull request by deads2k**
IOU found based on https://search.ci.openshift.org/?search=has+an+unstable+version&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=4.16&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

oops.  Otherwise this is looking good.  Need to check again next week.

/assign @JoelSpeed

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by deads2k** [comment]
jira bot is so annoying.

**Comment by deads2k** [comment]
"I want to improve our product"
"before you do that, could fill out these forms in triplicate?"
:exploding_head:

**Pull request merged**
