### PR TITLE
OpenShift SDN update

### PR DESCRIPTION
**Pull request by dcbw**
Pulls in a number of fixes, including:

https://github.com/openshift/openshift-sdn/pull/234
https://github.com/openshift/openshift-sdn/pull/220
https://github.com/openshift/openshift-sdn/pull/229
https://github.com/openshift/openshift-sdn/pull/230
https://github.com/openshift/openshift-sdn/pull/236
https://github.com/openshift/openshift-sdn/pull/237
https://github.com/openshift/openshift-sdn/pull/238

### CODE REVIEW

**Comment by dcbw** [comment]
@danwinship clayton'll want a +1 from somebody...

**Comment by danwinship** [comment]
The travis failure is actually real; openshift-sdn's pkg/ovs panics at startup if ovs isn't installed, but that breaks the tests. I guess I can make it only fail only when you call ovs.NewTransaction(); that will still result in openshift bailing out during startup.

**Comment by dcbw** [comment]
@danwinship PTAL

**Comment by danwinship** [comment]
Looks good except can you re-grab the latest master to get https://github.com/openshift/openshift-sdn/pull/236 too? Then LGTM.

**Comment by dcbw** [comment]
@danwinship done; PTAL

**Comment by dcbw** [comment]
@smarterclayton @liggitt @eparis PTAL

**Comment by danwinship** [comment]
LGTM

**Comment by eparis** [comment]
[test]

**Comment by eparis** [comment]
Looks like https://github.com/openshift/origin/issues/6149
which was closed as a dup of
https://github.com/openshift/origin/issues/6447

**Comment by smarterclayton** [comment]
[merge]

**Comment by eparis** [comment]
[merge] because it is the same flake again.

**Comment by dcbw** [comment]
@eparis different flake this time; mind a retry?

Warning: Permanently added '52.90.98.163' (ECDSA) to the list of known hosts.
fatal: '/data/src/github.com/openshift/source-to-image-bare' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by eparis** [comment]
only if you link to the flake bug report

**Comment by eparis** [comment]
[merge] because this flake is https://github.com/openshift/origin/issues/6321

**Comment by dcbw** [comment]
Flake city today?  "The command "make install-travis" failed and exited with 2 during ."

**Comment by dcbw** [comment]
Yay, more flake:

FAILURE after 10.734s: hack/../test/cmd/templates.sh:62: executing 'oc policy add-role-to-user admin test-user' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again

**Comment by dcbw** [comment]
Most recent flakage is ENOSPC.

2016-01-07 17:40:51.715588 I | profile: cpu profiling enabled, cpu.pprof
Error from server: User "system:anonymous" cannot list pods in project "default"
Dry run enabled - no modifications will be made. Add --confirm to remove images
hack/../test/cmd/../../hack/cmd_util.sh: line 276: cannot create temp file for here-document: No space left on device
!!! Error in hack/../test/cmd/../../hack/cmd_util.sh:195
	'return 1' exited with status 1

**Comment by dcbw** [comment]
@eparis merge again if you could?  Thanks!

**Comment by eparis** [comment]
[merge] AGAIN

**Comment by dcbw** [comment]
@eparis oh hey it worked; [merge] again?

**Comment by pravisankar** [comment]
re-[merge]

**Pull request merged**
