### PR TITLE
Use a recent version of aws-sdk-go

### PR DESCRIPTION
**Pull request by scality-gdoumergue**

### CODE REVIEW

**Comment by pweil-** [comment]
@scality-gdoumergue commit needs formatted according to https://github.com/openshift/origin/blob/master/HACKING.md#updating-other-godeps-from-upstream.  

What is the reason for this update?

**Comment by scality-gdoumergue** [comment]
@pweil- I've created this PR because aws-sdk-go v. 1.0.8 doesn't follow AWS authentication requirements. It still works with AWS's S3, because it doesn't strictly implements the requirements. But it doesn't work with other S3 implementations, like s3.scality.com for example, that follows authentication/signature requirements.

I'll try and correct this PR today.

**Comment by pweil-** [comment]
@scality-gdoumergue thanks that will help reviewers.  

We need to keep our dependencies in line with Kubernetes (mostly) and the [latest rebase](https://github.com/openshift/origin/pull/13483/commits/81b1d388dacc216d0eddba8573fbb64ff953962d) is bumping to v1.6.10-2-gf4c689b4.  Is that going to be good enough for your use case?  

If not we'd probably want to update upstream first and pull in the change that way.

cc @sttts

**Comment by scality-gdoumergue** [comment]
aws-sdk-go v1.6.10 works great, when will Kubernetes latest rebase be available for openshift?

**Comment by pweil-** [comment]
> aws-sdk-go v1.6.10 works great, when will Kubernetes latest rebase be available for openshift?

great!  The rebase is currently undergoing stabilization so it's getting close to landing.  You can subscribe to https://github.com/openshift/origin/pull/13483 to monitor progress.

**Pull request closed without merging**
