### PR TITLE
Add SSL information to the backend

### PR DESCRIPTION
**Pull request by git001**
Please take a look into the documentation.

http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-send-proxy-v2-ssl

### CODE REVIEW

**Comment by danmcp** [comment]
@eparis Review please.

**Comment by danmcp** [comment]
@knobunc @eparis Please review

**Comment by knobunc** [comment]
@ramr @rajatchopra is there a reason we are not passing this information?

http://cbonte.github.io/haproxy-dconv/1.5/configuration.html#5.1-accept-proxy indicates v2 is supported (unlike http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt which states it only supports sending it).

**Comment by ramr** [comment]
@knobunc  @rajatchopra might know more but it could well be due to an older version of haproxy when this was done initially (maybe a haproxy 1.4 vs 1.5 thing). 

In any case, think that using `send-proxy-v2-ssl-cn` might be more appropriate for SNI case
- aka in the `be_sni` backend.

@git001 , there's also the `be_no_sni` case to consider - that one would probably need the option  without the cn `send-proxy-v2-ssl`
https://github.com/git001/origin/blob/ec6b1ab6106fb6171875a5b2e13cbdb40d146494/images/router/haproxy/conf/haproxy-config.template#L146

Thx

**Comment by knobunc** [comment]
@imcsk8 Can you take a look at this and shepherd it in please?

**Comment by git001** [comment]
I will send a new patch which fits to the current master branch

**Pull request closed without merging**
