### PR TITLE
Fix error event type panic in StatefulSet e2e tests

### PR DESCRIPTION
**Pull request by sttts**
Should fix https://github.com/openshift/origin/pull/13905#issuecomment-297881950.

### CODE REVIEW

**Comment by sttts** [comment]
[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@sttts did not fix the problem: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1023/

**Comment by deads2k** [comment]
flaked on https://github.com/openshift/origin/issues/13943 and https://github.com/openshift/origin/issues/13942

**Comment by deads2k** [comment]
re[test]

**Comment by sttts** [comment]
@deads2k the panic is gone. But a broken watch showed up.

**Comment by deads2k** [comment]
> @deads2k the panic is gone. But a broken watch showed up.

oh, awesome.  People will think they're the same.  Add details to the issue?


If the test is using watch.Until, it's probably not handling watch window expiration with a relist operation.

**Comment by deads2k** [comment]
flake fix. merging

**Pull request merged**
