### PR TITLE
oc: print more info when getting a dc

### PR DESCRIPTION
**Pull request by kargakis**
@ironcladlou @smarterclayton @fabianofranz

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM (but this will make the `oc get` output more wide, which might look terrible on small terminals ;-)

**Comment by kargakis** [comment]
This is similar to `oc get rc`
```
NAME       IMAGE                      TRIGGERS                    VERSION   SELECTOR
database   ruby-helloworld-database   ConfigChange                1         name=database
frontend   ruby-helloworld            ConfigChange, ImageChange   0         name=frontend
[vagrant@localhost sample-app]$ oc get rc
CONTROLLER   CONTAINER(S)               IMAGE(S)                            SELECTOR                                                        REPLICAS   AGE
database-1   ruby-helloworld-database   openshift/mysql-55-centos7:latest   deployment=database-1,deploymentconfig=database,name=database   0          6s
```
Also there is movement upstream to start hiding info that may be considered verbose: https://github.com/kubernetes/kubernetes/pull/19689

**Comment by fabianofranz** [comment]
I'd keep that label as `LATEST` instead of `VERSION`, other than that LGTM.

**Comment by smarterclayton** [comment]
The width budget is ~100 characters

**Comment by kargakis** [comment]
This is going to vary based on the selector...

**Comment by kargakis** [comment]
I am going to put IMAGE under `-o wide` as per https://github.com/kubernetes/kubernetes/issues/19775

**Pull request closed without merging**
