### PR TITLE
fix readme link in hacking.md for extended tests

### PR DESCRIPTION
**Pull request by PI-Victor**
@bparees can you merge this?
the link is currently point to https://github.com/openshift/origin/blob/master/test/exte%0Anded/README.md :)

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by PI-Victor** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8480/consoleFull

the same as https://github.com/openshift/origin/issues/11750
except this also has this as well

```
[Fail] [k8s.io] Probing container [It] should *not* be restarted with a /healthz http liveness probe [Conformance] 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/container_probe.go:373
```
@bparees does this qualify as a different issue? seems to be a part of the same test suite

**Comment by PI-Victor** [comment]
L.E.: updated the current issue

**Comment by bparees** [comment]
@PI-Victor i think what you did is right. thanks!
[test]

**Pull request merged**
