### PR TITLE
Make oc rsh behave more like ssh

### PR DESCRIPTION
**Pull request by smarterclayton**
This enables rsync, because rsync expects a ssh like execution:

    ssh <host> [command]

This makes rsh work like that:

    oc rsh <pod> [command]

The command will be executed directly.  Adds -t and -T to control TTY
execution (just like SSH).  Does not implement the -n behavior of SSH for
allocating an empty stdin.

@bparees makes rsync easier, still seems to be hanging from #4535

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
What's the hang scenario/command?

**Comment by smarterclayton** [comment]
See the last comment in the linked issue

**Comment by liggitt** [comment]
starting to debug this. added a debug commit in https://github.com/liggitt/origin/commits/rsh_like_ssh

client output:
```
$ rsync -avvv -e "oc rsh" pod.json docker-registry-1-7bcv6:/var/tmp/
opening connection using: oc rsh docker-registry-1-7bcv6 rsync --server -vvvlogDtpre.iLsfx . /var/tmp/  (8 args)
rsh: []string{"docker-registry-1-7bcv6", "rsync", "--server", "-vvvlogDtpre.iLsfx", ".", "/var/tmp/"}
remotecommand: reading error stream
remotecommand: copying to remoteStdin
remotecommand: copying from remoteStdin
remotecommand: copying stdout
remotecommand: waiting for stdout/stderr
remotecommand: copying stderr
sending incremental file list
[sender] make_file(pod.json,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=197
received 1 names
recv_file_list done
get_local_name count=1 /var/tmp/
generator starting pid=197
delta-transmission enabled
recv_generator(pod.json,1)
pod.json is uptodate
send_files(1, pod.json)
generate_files phase=1
send_files phase=1
recv_files(1) starting
recv_files(pod.json)
recv_files phase=1
generate_files phase=2
send_files phase=2
send files finished
total: matches=0  hash_hits=0  false_alarms=0 data=0
recv_files phase=2
generate_files phase=3
recv_files finished
generate_files finished
<HANG>
```

server output:
```
Client.hijack: waiting on <-errChanIn
<HANG>
```

client-side, I don't see anything misbehaving... will dig into hijack

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Hang is https://github.com/openshift/origin/issues/4581

**Comment by smarterclayton** [comment]
[merge], docker 1.7.1 has landed in base ami

**Pull request merged**
