### PR TITLE
Update templates to use navigateResourceURL filter where appropriate

### PR DESCRIPTION
**Pull request by benjaminapetersen**
- also a minor update to projectOverviewURL, allow for string or object

@jwforres @spadgett this is pt1 of breaking down my [project service PR]([breaking down this PR](https://github.com/openshift/origin/pull/5953)).

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM but missing bindata

**Comment by benjaminapetersen** [comment]
@jwforres generated bindata.

[TEST] just cuz.

**Comment by benjaminapetersen** [comment]
@jwforres bindata!!

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
