### PR TITLE
Support push secrets in the custom builder

### PR DESCRIPTION
**Pull request by ncdc**
Fixes bug 1230642

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM

**Comment by mfojtik** [comment]
LGTM

**Comment by bparees** [comment]
lgtm.  @smarterclayton can we get approval?  non-shipping code, blah blah.

**Comment by liggitt** [comment]
Is there already plumbing in the API for specifying a push secret for a custom build strategy?

**Comment by liggitt** [comment]
or do those get computed independent of strategy from the build output

**Comment by bparees** [comment]
@liggitt this is about how to consume the secret once it's present.  the custom image has to do that, nothing else can do it for it.

**Comment by ncdc** [comment]
They're mounted into the build pod regardless of strategy. What Ben said :-)

**Comment by bparees** [comment]
@liggitt with a custom image you're on your own to manage pushing any output (be it an image push or ftp'ing a war file), we just give you all the info you may need to do it.

**Comment by csrwng** [comment]
@bparees - so a user may want additional secrets in their custom builder. Would those be attached to the service account you specify ? or do we need to add more plumbing in the api to do that?

**Comment by bparees** [comment]
@csrwng I think we need more plumbing for that, but i'm not sure?  This came up in our discussion with ops yesterday.

**Comment by liggitt** [comment]
> @bparees - so a user may want additional secrets in their custom builder

@kwoodson, @bparees and I were talking about that yesterday. Right now, the only thing the buildconfig can specify should be added to the build pod is `env` vars. Plumbing secrets through custombuild params to the pod is also important, but not in place right now.

**Comment by csrwng** [comment]
likely a post-3.0 item

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
