### PR TITLE
use exutil.DumpPod* to dump build states on jenkins failures

### PR DESCRIPTION
**Pull request by jim-minter**
Not clear why `https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/308/testReport/junit/(root)/Extended/_image_ecosystem__jenkins__Slow__openshift_pipeline_plugin_jenkins_plugin_test_context___jenkins_plugin_test_trigger_build_with_slave__Suite_openshift_/` failed - possibly a transitory build failure.  Add yet more logging.

### CODE REVIEW

**Comment by jim-minter** [comment]
verify extended_image_ecosystem passes then unhold

**Comment by bparees** [comment]
/hold cancel
failing image eco test was unrelated to these changes.

**Pull request merged**
