### PR TITLE
UPSTREAM: 49120: Modify podpreset lister to use correct namespace

### PR DESCRIPTION
**Pull request by jpeeler**
upstream pick for https://bugzilla.redhat.com/show_bug.cgi?id=1471725
bug 1471725

### CODE REVIEW

**Comment by jpeeler** [comment]
upstream PR is lgtm/approved [test]

**Comment by liggitt** [comment]
needs rebase

**Comment by liggitt** [comment]
lgtm [merge][severity:blocker]

**Comment by jpeeler** [comment]
[test]

**Comment by jpeeler** [comment]
[test] flake #15337

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]

**Comment by eparis** [comment]
flake was fixed by https://github.com/openshift/origin/pull/15353  merging by hand.

**Pull request merged**
