### PR TITLE
[BZ1394716] Report false diagnostic message for curator-ops DeploymentConfig

### PR DESCRIPTION
**Pull request by jcantrill**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1394716

cc @sosiouxme @openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
@fabianofranz LGTM

**Comment by fabianofranz** [comment]
LGTM, but I'll leave the final word to @sosiouxme.  ;)

**Comment by jcantrill** [comment]
@rhcarvalho can you approve since @sosiouxme is onleave for a while?

**Comment by rhcarvalho** [comment]
I don't really know the context, but from the BZ (I added a link to the description) this looks reasonable.

Are there any automated tests for the multiple conditions?

**Comment by jcantrill** [comment]
@rhcarvalho There are none that would capture this issues.  Unit tests for diagnostics is rare because of the complexity of introducing them.  I believe the issue with this bug was it was reporting a missing component because we did not check for it.

**Comment by rhcarvalho** [comment]
From a code change stand-point LGTM. @jcantrill did you check it fixes the bug? It if does then let's get this merged :)

**Comment by jcantrill** [comment]
It does resolve the bug.  I'll take that as a [merge]

**Pull request merged**
