### PR TITLE
Project config validation

### PR DESCRIPTION
**Pull request by mfojtik**
Add admission validation for https://github.com/openshift/api/pull/172

/cc @deads2k

### CODE REVIEW

**Comment by mfojtik** [comment]
(the bump is suspicious, i will rerun update-deps in centos VM... this one happened in container with bind-mounted origin)

**Comment by deads2k** [comment]
fix your bump and lgtm

**Comment by mfojtik** [comment]
bump fixed, adding lgtm.

**Comment by mfojtik** [comment]
(added updated openapi)

**Pull request merged**
