### PR TITLE
build extended tests: don't use large Jenkins image unnecessarily

### PR DESCRIPTION
**Pull request by jim-minter**
No need to pull openshift/jenkins-1-centos7 or do yum install -y httpd - save time & bandwidth!

### CODE REVIEW

**Comment by jim-minter** [comment]
[test][testextended][extended:core(build can have Dockerfile input)]

**Comment by bparees** [comment]
lgtm but not good to jenkins apparently..

**Comment by bparees** [comment]
[testextended][extended:core(build can have Dockerfile input)]

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
extended failure is a known issue.
[merge]

**Pull request merged**
