### PR TITLE
Allow overriding the registry URL when image pruning

### PR DESCRIPTION
**Pull request by ncdc**
`osadm prune images` sends HTTP requests to the registry to perform
pruning tasks. If the registry URL determined by the pruner is
inaccessible from the machine where the prune command is being run, you
can now change the URL via the --registry-url-override flag.

Fixes bug 1227285

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton PTAL

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
Haven't seen this test flake before:

```
!!! Error in hack/test-cmd.sh:395
  'osc new-app library/php mysql -l no-source=php-mysql' exited with status 1
```

**Comment by smarterclayton** [comment]
Usually docker doesn't respond.

----- Original Message -----

**Pull request merged**
