### PR TITLE
hack/verify-upstream-commits.sh: take into account pkg/build/vendor dir

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @soltysh

### CODE REVIEW

**Comment by soltysh** [comment]
@ncdc @sttts fyi, since you're doing the current rebase

LGTM [merge]

**Comment by ncdc** [comment]
Yuck 👅

**Comment by soltysh** [comment]
> Yuck 👅

Sigh... I learned that earlier today as well and my reaction was exactly the same.

**Comment by php-coder** [comment]
@bparees @smarterclayton BTW why we started to use a separate vendor dir? What are the benefits?

**Comment by bparees** [comment]
> @bparees @smarterclayton BTW why we started to use a separate vendor dir? What are the benefits?

we are vendoring different levels of the deps.

**Comment by smarterclayton** [comment]
Kubernetes contains docker client versions which we can't easily change.  Our build system needs newer versions.

**Comment by smarterclayton** [comment]
Maybe if we didn't include all of computing...

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
