### PR TITLE
UPSTREAM: 58375: Recheck if transformed data is stale when doing live lookup during update

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
/retest

@mfojtik do we know if this is a known issue in 3.8 CI?

**Comment by runcom** [comment]
3.8 branch is failing becase there's no tagged 3.8 version of the service catalog on docker hub (it's happening with CRI-O jobs as well)

**Comment by liggitt** [comment]
@mfojtik failure is unrelated to the PR and other end-to-end tests are green

**Comment by mfojtik** [comment]
Already merged and tested on master, low risk, needed fix. The CI failure is unrelated, merging by hand.

**Pull request merged**
