### PR TITLE
Switch origin-release to build from Go 1.6

### LINKED ISSUE #8113: Release image won't build because Go removed the tools package
openshift/release will no longer build.

```
Step 5 : RUN mkdir $TMPDIR &&     go get golang.org/x/tools/cmd/cover github.com/tools/godep github.com/golang/lint/golint
 ---> Running in f3a4fa2464b8
[91mpackage golang.org/x/tools/cmd/cover
	imports github.com/tools/godep
	imports github.com/golang/lint/golint
	imports go/types: unrecognized import path "go/types"
[0mRemoving intermediate container f3a4fa2464b8
The command '/bin/sh -c mkdir $TMPDIR &&     go get golang.org/x/tools/cmd/cover github.com/tools/godep github.com/golang/lint/golint' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #8113
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Increases build times for release to 25 minutes

**Comment by smarterclayton** [comment]
Looks like detection of TLS errors in go http changed (they altered
the error response)

**Comment by smarterclayton** [comment]
`make release` will now only build linux.  Will make some changes to vagrant after this so that we can ensure cross-compile is performed for merge (just not for test PR).

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@deads2k @liggitt test-cmd fails because run selects batch/v1 instead
of extensions/v1beta1 for jobs.

This change is still compiling with the go in centos (1.4), since we
don't use the release binary for test-cmd.sh and this change doesn't
alter the golang in the image.  Do we have a race / flake in run?

**Comment by deads2k** [comment]
> Do we have a race / flake in run?

Does it actually flake or is always failing when compiled on 1.6?  @liggitt wired us up to the `RESTMapper` created by API registration, so I guess this could be a change in import traversal order again?

**Comment by smarterclayton** [comment]
hack/test-cmd.sh wasn't complied with Go 1.6 - as in, it's a flake in 1.4 (or something else changed in the repo).  Only e2e and later are tested with it until centos updates

**Comment by smarterclayton** [comment]
[merge]

**Comment by deads2k** [comment]
Yeah, its not flaking.  That's the 1.6 behavior.  I'm looking into why now.

**Comment by smarterclayton** [comment]
Merge queue builds differently than test queue.  So yes, go 1.6 problem with import order.

**Comment by deads2k** [comment]
> Merge queue builds differently than test queue. So yes, go 1.6 problem with import order.

Its breaking because there's no preference for ordering when doing `Scheme.ObjectKind` and the import order determines which is registering first: extensions or batch.

If we want stable output from `oc run` you need to specify the generator *and* the `--output-version` for now.  They know that `ObjectKind` is broken, but they haven't figure out how to fix it yet.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Fixes #8113

**Pull request merged**
