### PR TITLE
don't run serial tests any more when FOCUS is specified

### PR DESCRIPTION
**Pull request by jim-minter**
follow up from #16842, may also solve the same issue as #16806

### CODE REVIEW

**Comment by jim-minter** [comment]
@smarterclayton @bparees @miminar let's try this?

**Comment by bparees** [comment]
we can't do this by itself, it means our nightly extended test jobs won't run the [Serial] tests.  (we use focus to run all the [builds] and [image_ecosystem] tests and some of them are marked [Serial])

if there's a plan for how $FOCUS + [Serial] tests are going to be run, we'll need to include it in this PR.

**Comment by smarterclayton** [comment]
Not supported.  Find a different solution.  The only serial tests should be those that need while cluster access.  Are you thinking of disruptive tests?

/lgtm

**Comment by smarterclayton** [comment]
"Whole"

**Comment by smarterclayton** [comment]
Or maybe slow tests?

**Comment by bparees** [comment]
i'm thinking of tests like our build test that confirms that the next build is started immediately after the last one.  When it's run on an overloaded parallel environment, the timings become impossible to confirm.  When it's run serially, it's rock solid and we ensure that we have not regressed the "next build starts when the previous build finishes" behavior.

And merging a PR that immediately disables existing tests strikes me as the wrong answer and is just asking for regressions.

This also makes it impossible run those tests locally, which is kinda the whole point of FOCUS in the first place.

At a minimum, anything currently marked [Serial] should be marked conformance so they continue to get run until we have an actual solution to this problem.

**Comment by bparees** [comment]
i'm also reasonably sure this behavior is going to confuse the heck out of someone in the future when they attempt to do a FOCUS on a [Serial] test and it won't run.

**Comment by bparees** [comment]
talked with @smarterclayton about this some more, sounds like he is going to create a serial bucket that runs all the serial tests.  I can live w/ that, though i still think this will confuse people trying to run individual serial tests locally via FOCUS.

My other suggestion would be to run with something like `--ginkgo.focus=$FOCUS.*?[Serial]|[Serial].*?$FOCUS` for the serial portion.  It won't work with 100% of regexes people might use, but it should work for most of them.

**Comment by miminar** [comment]
> i'm also reasonably sure this behavior is going to confuse the heck out of someone in the future when they attempt to do a FOCUS on a [Serial] test and it won't run.

:+1:

This renders most of the tests in `extended_image_registry` job untestable - both locally and in CI.

> Not supported. Find a different solution. The only serial tests should be those that need while cluster access. Are you thinking of disruptive tests?

In case of serial registry tests - several tests apply different registry configuration (read-only on/off acceptschema2 on/off etc.), which restarts the registry. Such tests cannot be run in parallel with other tests interacting with registry.

**Comment by smarterclayton** [comment]
I'd rather not have that complexity.  Avoid making tests serial, and maybe
we'll add a serial job to PR that people can focus.

On Oct 12, 2017, at 8:19 PM, Ben Parees <notifications@github.com> wrote:

talked with @smarterclayton <https://github.com/smarterclayton> about this
some more, sounds like he is going to create a serial bucket that runs all
the serial tests. I can live w/ that, though i still think this will
confuse people trying to run individual serial tests locally via FOCUS.

My other suggestion would be to run with something like
--ginkgo.focus=$FOCUS.*?[Serial]|[Serial].*?$FOCUS for the serial portion.
It won't work with 100% of regexes people might use, but it should work for
most of them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/16846#issuecomment-336316120>,
or mute
the thread

**Comment by bparees** [comment]
> I'd rather not have that complexity. Avoid making tests serial, and maybe we'll add a serial job to PR that people can focus. 

Seems like @miminar gave a pretty good reason for needing serial tests and prefixing/appending [Serial] does not seem that complex, especially compared to the other things that are being done to run our extended tests.

**Comment by bparees** [comment]
/hold
(we can't just disable all the registry tests w/o a plan)

**Comment by miminar** [comment]
> (we can't just disable all the registry tests w/o a plan)

We've just discussed this with @kargakis. We can provide a custom script for this particular job in here: https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_extended_image_registry.yml
that would invoke `ginkgo` directly to test exactly what we need.

**Comment by bparees** [comment]
> We've just discussed this with @kargakis. We can provide a custom script for this particular job in here: https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_extended_image_registry.yml
that would invoke ginkgo directly to test exactly what we need.

still means it'll be harder to run the tests locally (you'll have to invoke ginkgo manually there too) but sure.

**Comment by miminar** [comment]
> still means it'll be harder to run the tests locally (you'll have to invoke ginkgo manually there too) but sure.

Yes, it's a workaround until the extended scripts will be generic enough to select what needs to be run and what not.

**Comment by miminar** [comment]
> We can provide a custom script for this particular job in here

Initial untested version is here: openshift/aos-cd-jobs#729

**Comment by smarterclayton** [comment]
Let's just create a serial pr job that supports focus.  Let's stop hacking around bad decisions we made years ago.

Also, any serial registry test should be installing its own registry and hacking that.  Updating the core registry is a bad pattern.  I'm not aware of any reason why you can't spin up the registry image and point it as openshift.  Should work fine.

**Comment by bparees** [comment]
> Let's just create a serial pr job that supports focus. Let's stop hacking around bad decisions we made years ago.

how do you propose to do that?  is that not still going to be ginkgo.focus="$FOCUS.*[Serial]" ?

The whole challenge here is selecting the set of tests that contain both [Serial] and $FOCUS.

**Comment by stevekuznetsov** [comment]
+100 to Ben's regex solution because it's simple and unblocks this. the underlying issues are:

 - if your test is serial you're doing something sub-optimally (not starting your own registry to test against, not validating controller logic with fake event stream etc
 - we should not try to tackle the test selection problem in bash
 - this "organic" script is out of hand 

We should spend the time to tackle these top-down (change Ginkgo? remove serial tests?) but we should not allow that effort to roadblock running the current serial tests we have

**Comment by jim-minter** [comment]
closing for #16919

**Pull request closed without merging**
