### PR TITLE
increase wait time on imagestreams

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This is a band-aid so we flake less often while a real fix is made. All waits now allow 2 minutes until timeout.
@bparees @deads2k FYI

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by bparees** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
@stevekuznetsov Why would I believe this would make me flake less often?  Why wouldn't I think that something was wedged and this will just make me wait twice as long?  Do you have some data that indicates that it was actively doing work for a minute before?

**Comment by bparees** [comment]
@deads2k 
https://github.com/openshift/origin/issues/6259#issuecomment-165549813

**Comment by deads2k** [comment]
@bparees if I'm reading that comment right, all the other image streams start importing, but the mysql never does.  mysql is created before some of the others and they appear to be running (or at least kicking off) quickly.  I'm still not seeing the indication that its taking a really long time for mysql in particular and I haven't seen total time to import in successful cases either for comparison.

**Comment by bparees** [comment]
@deads2k it appears to me they are importing sequentially, i don't think that log is complete (hence the 60s timeout being hit right after wildfly starts...clearly it was doing something before the log excerpt provided, likely importing other images)

i've never looked into the image import controller, but my assumption and observation is that it's a sequential process and i don't know how it chooses the ordering.

and I still think the fact that it takes 60s to import needs to be investigated (hence why this doesn't close the original issue) but it may reduce the flaking if our assumption is correct.

**Comment by bparees** [comment]
@deads2k `The sever gets the shutdown signal milliseconds after the wilfdly image is imported,`

shutdown signal meaning we hit the 60s timeout.  so that doesn't sound like "wedged", it sounds like it ran out of time.

**Comment by liggitt** [comment]
on the successful test run:
```
Running hack/../test/cmd/builds.sh:76: executing 'oc get is ruby-22-centos7' expecting any result and text 'latest'; re-trying every 0.2s until completion or 120.000s...
SUCCESS after 29.058s: hack/../test/cmd/builds.sh:76: executing 'oc get is ruby-22-centos7' expecting any result and text 'latest'; re-trying every 0.2s until completion or 120.000s
...
Running hack/../test/cmd/images.sh:49: executing 'oc get imagestreamtags wildfly:latest' expecting success; re-trying every 0.2s until completion or 120.000s...
SUCCESS after 18.067s: hack/../test/cmd/images.sh:49: executing 'oc get imagestreamtags wildfly:latest' expecting success; re-trying every 0.2s until completion or 120.000s
...
Running hack/../test/cmd/newapp.sh:21: executing 'oc get imagestreamtags mysql:latest' expecting success; re-trying every 0.2s until completion or 120.000s...
SUCCESS after 66.343s: hack/../test/cmd/newapp.sh:21: executing 'oc get imagestreamtags mysql:latest' expecting success; re-trying every 0.2s until completion or 120.000s
...
Running hack/../test/cmd/newapp.sh:144: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 120.000s...
SUCCESS after 52.793s: hack/../test/cmd/newapp.sh:144: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 120.000s
```

I can see how these edged over a minute... I'm concerned the imports are taking so long

**Comment by bparees** [comment]
Agree, issue #6259 will stay open to cover that though.

**Comment by liggitt** [comment]
if import performance has increased dramatically, the issue open to address that needs to be higher priority and not probably not tagged as a test-flake issue

**Pull request closed without merging**
