### PR TITLE
S2I 1604a01 bump

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @bparees @oatmealraisin

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@oatmealraisin looks like your s2i changes are causing problems when we try to bring them into origin:

```
In suite "github.com/openshift/origin/pkg/generate/app/cmd", test case "TestEnsureHasSource" failed:
=== RUN   TestEnsureHasSource
--- FAIL: TestEnsureHasSource (0.00s)
	newapp_test.go:352: lstat /tmp/s2i-test716827242/.git/objects: permission denied
```

and

```
In suite "github.com/openshift/origin/pkg/generate/git", test case "TestParseRepository" failed:
=== RUN   TestParseRepository
--- FAIL: TestParseRepository (0.00s)
	git_test.go:110: ParseRepository returned err: lstat /tmp/s2i-test612389032/.git/objects: permission denied
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a8aa9]
```

**Comment by oatmealraisin** [comment]
@bparees roger, on it

**Comment by bparees** [comment]
[merge]

**Comment by php-coder** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4926/consoleFull failed because of https://github.com/openshift/origin/issues/10228

**Comment by php-coder** [comment]
@oatmealraisin Unfortunately, it still fails:
```
--- FAIL: TestNewAppDetectSource (0.00s)
```
Full log is here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4815/consoleFull

**Comment by php-coder** [comment]
I'm closing this because there is a newer PR for S2I bump: #10359

**Pull request closed without merging**
