### PR TITLE
 UPSTREAM: 62146: Fix daemon-set-controller bootstrap RBAC policy

### PR DESCRIPTION
**Pull request by deads2k**
@jeremyeder per request

@openshift/sig-master

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

wait for  #19512

**Comment by enj** [comment]
Sigh, no tests 😞

**Comment by mshutt** [comment]
@deads2k Does this wind up getting cherry-picked to 3.9?  I'm already going to simply patch this in our existing 3.7.2 and 3.9 clusters.

**Pull request merged**
