### PR TITLE
start building real binaries for builders

### PR DESCRIPTION
**Pull request by deads2k**
Rather than continuing to rename the openshift binary, this starts building actual binaries for the openshift sti and docker builders.  It also removes them from openshift-infra

@smarterclayton @bparees 
@smunilla @adammhaile these seem like likely targets for RPM subpackages.

### CODE REVIEW

**Comment by smarterclayton** [comment]
How big are these new binaries?

On Nov 17, 2017, at 12:27 PM, OpenShift Merge Robot <
notifications@github.com> wrote:

/lgtm cancel //PR changed after LGTM, removing LGTM. @bparees
<https://github.com/bparees> @deads2k <https://github.com/deads2k>
@juanvallejo <https://github.com/juanvallejo> @mfojtik
<https://github.com/mfojtik>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/17366#issuecomment-345308909>,
or mute
the thread

**Comment by smarterclayton** [comment]
I don’t need two binaries (one for sti and one for docker).  If we split
them, ben needs to bring them together.

On Nov 17, 2017, at 12:27 PM, OpenShift Merge Robot <
notifications@github.com> wrote:

/lgtm cancel //PR changed after LGTM, removing LGTM. @bparees
<https://github.com/bparees> @deads2k <https://github.com/deads2k>
@juanvallejo <https://github.com/juanvallejo> @mfojtik
<https://github.com/mfojtik>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/17366#issuecomment-345308909>,
or mute
the thread

**Comment by deads2k** [comment]
> How big are these new binaries?

85-ish megs each.



> I don’t need two binaries (one for sti and one for docker).  If we split
> them, ben needs to bring them together.

They are separate (distinct names) today.  If we attempt to combine them, how about we do that by combining the commands under a single command instead of having them react to different naming schemes.

**Comment by bparees** [comment]
> If we attempt to combine them, how about we do that by combining the commands under a single command instead of having them react to different naming schemes.

That's going to be a migration/compatibility pain.  Unless someone wants to promise me that I only have to support exactly matched controllers+buildimages.  (Which is not an unreasonable assumption since the controller creates the pod referencing the buildimage, but among other things it doesn't fly on our GCE conformance test)

**Comment by deads2k** [comment]
> That's going to be a migration/compatibility pain. Unless someone wants to promise me that I only have to support exactly matched controllers+buildimages. (Which is not an unreasonable assumption since the controller creates the pod referencing the buildimage, but among other things it doesn't fly on our GCE conformance test)

Seems like you could write a binary with proper subcommands and shim it with a bash script in your image for the purpose of migration.

**Comment by smarterclayton** [comment]
Binary would just support name variants like today.  Ben and I talked and
will follow up as this evolves.  Also, git-clone can't be deleted, ben
needed it.

So we'll have 5 85m binaries.

**Pull request closed without merging**
