### PR TITLE
Add osadm to tarball

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
Because of this, we cannot use `oscadm` command after docker install with 
~~~
$ docker run -d --name "openshift-origin" --net=host --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    openshift/origin start
$ docker exec -it openshift-origin bash
[root@dhcp-217-31 openshift]# openshift version
openshift v0.4.3-285-geffa12c
kubernetes v0.14.1-582-gb12d75d
[root@dhcp-217-31 openshift]# oscadm                                                                    
bash: oscadm: command not found
~~~

**Comment by nak3** [comment]
Failed Travis build, please see pull/1862

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by nak3** [comment]
Hmm... I know why Travis build failed, but I don't understand why jenkins tests also failed. This patch added just one line to the shell script.

**Comment by smarterclayton** [comment]
[merge] again

**Pull request merged**
