### PR TITLE
Fix up net.bridge.bridge-nf-call-iptables after kubernetes breaks it

### PR DESCRIPTION
**Pull request by danwinship**
Patch from Dan Williams

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1294061

@eparis @smarterclayton

### CODE REVIEW

**Comment by danwinship** [comment]
(replaces #6686)

**Comment by eparis** [comment]
[test]

**Comment by eparis** [comment]
This is (obviously) a horrible hack we will work to fix after release. I tested and found a value of 1 before this patch and a value of 0 running a node with this patch.

There are obviously other ways to bikeshed the hack, but this is a hack that works, is an obvious TODO to clean up, and it LGTM.

**Comment by smarterclayton** [comment]
Approved, please open an issue to fix this (is it upstream, etc) and link it back here.

**Comment by smarterclayton** [comment]
[merge]

**Comment by eparis** [comment]
@smarterclayton https://trello.com/c/vnvUCQPG/112-remove-the-bridge-nf-call-iptables-hack-sdn

**Comment by dcbw** [comment]
Real fix is at https://github.com/openshift/openshift-sdn/pull/251

**Pull request merged**
