### PR TITLE
Fixed the sample-app readme

### PR DESCRIPTION
**Pull request by soltysh**
@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
align with e2e?

**Comment by bparees** [comment]
also why is this needed?

**Comment by soltysh** [comment]
The docs weren't up to date, eg. see [this](https://github.com/openshift/origin/pull/1946/files#diff-197bc032a41e8d501903d70f899e02a8R142) I'll have a look at e2e right away, but I'm positive it's working there as we wouldn't have merge working :wink:

**Comment by bparees** [comment]
ok, remove the unnecessary pwds and lgtm.

**Comment by soltysh** [comment]
Done.

**Comment by bparees** [comment]
@deads2k looks like this got missed in some recent updates?

[merge]

**Pull request merged**
