### PR TITLE
Revert "bump(k8s): 1.26"

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts openshift/origin#27694 ; tracked by OCPBUGS-7616

#27694 is suspected of breaking all vsphere CI.  The process to get this fixed is long since it requires an upstream fix, backport to upstream 1.26 and then bringing it into openshift. 

**Note**: We can defer the decision on whether to merge this revert until Monday, but with CoreOS 9.2 about to land I'd feel better having CI in the best shape it can be for all platforms.

cc: @sanchezl @soltysh

### CODE REVIEW

**Comment by stbenjam** [comment]
/hold

Will decide on Monday

**Comment by deads2k** [comment]
I'll be out on monday, but if this is needed.

Also, how did payload testing not reveal a vsphere problem?

/approve

**Comment by stbenjam** [comment]
> Also, how did payload testing not reveal a vsphere problem?

Looks like only blocking was tested

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-sdn

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by EmilienM** [comment]
The e2e-openstack-ovn error has been fixed via https://github.com/openshift/openstack-test/pull/88 and can safely be ignored.

**Pull request merged**
