### PR TITLE
Bug 1809862: log snippet test; failed git clone within init container

### PR DESCRIPTION
**Pull request by gabemontero**
this new test should only pass once https://github.com/openshift/openshift-controller-manager/pull/77 merges

/assign @bparees 

@openshift/openshift-team-developer-experience FYI

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/hold

@gabemontero please do make sure the test doesn't pass w/o your PR changes being merged, but i agree it shouldn't (logsnippet should be empty w/o your PR)

**Comment by gabemontero** [comment]
our new test failed as expected @bparees 

```

[sig-builds][Feature:Builds][Slow]  update failure status  Build status Docker fetch source failure should  contain the Docker build fetch source failure reason and message  [Suite:openshift] expand_less | 46s
-- | --
fail [github.com/openshift/origin/test/extended/builds/failure_status.go:118]: Should not get an error or timeout getting LogSnippet Unexpected error:     <*errors.errorString \| 0xc0002b31b0>: {         s: "timed out waiting for the condition",     }     timed out waiting for the condition occurred

```

the other tests in that file passed

**Comment by gabemontero** [comment]
passing e2e-gcp-builds

/hold cancel

/retest

**Pull request merged**
