### PR TITLE
Support local domain resolution(/etc/hosts) for egress network policy

### PR DESCRIPTION
**Pull request by pravisankar**
We use dig to query nameservers for domain resolution unlike ping
which looks at /etc/nsswitch.conf, /etc/hosts, nameservers to resolve
IP addrs.
Local domain resolution with /etc/hosts is helpful in some
specific use cases like testing dns name changes. To support this,
now we also query /etc/hosts using getent when dig fails to resolve.

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by pravisankar** [comment]
[test]

**Comment by danwinship** [comment]
> Local domain resolution with /etc/hosts is helpful in some specific use cases like testing dns name changes.

Hadn't we explicitly rejected this use case in the original design? If you don't care about the *actual* DNS results, you can just configure EgressNetworkPolicies with IP addresses...

**Comment by pravisankar** [comment]
On Tue, May 16, 2017 at 6:17 AM, Dan Winship <notifications@github.com>
wrote:

> Local domain resolution with /etc/hosts is helpful in some specific use
> cases like testing dns name changes.
>
> Hadn't we explicitly rejected this use case in the original design? If you
> don't care about the *actual* DNS results, you can just configure
> EgressNetworkPolicies with IP addresses...
>
Originally we ignored this use case because of the limitation of
dig/nslookup utilities (/etc/hosts lookup is only patched in Solaris).
Supporting this will help at least these 2 use cases:

- Cluster where all the nodes/master are addressed by names instead of IPs
for ease of use (all IP<->name mapping for all nodes/master is present in
/etc/hosts). This is similar to openshift vagrant cluster.
- Testing dns name changes will be trivial, don't need to setup local dns
servers like bind, etc.

**Comment by danwinship** [comment]
> Cluster where all the nodes/master are addressed by names instead of IPs for ease of use (all IP<->name mapping for all nodes/master is present in /etc/hosts). This is similar to openshift vagrant cluster.

Where the nodes/master are addressed by not-real-DNS names. Yes, the vagrant and dind clusters do that, but is that at all common in real deployments? I would expect most real deployments to have real hostnames. (And do people really want to write EgressNetworkPolicy rules involving the master and nodes anyway?)

> Testing dns name changes will be trivial, don't need to setup local dns servers like bind, etc.

But this code only looks in /etc/hosts if dig fails, so it doesn't let you test changes to the IPs of real hosts, only fake hostnames.

**Comment by pravisankar** [comment]
On Wed, May 17, 2017 at 9:08 AM, Dan Winship <notifications@github.com>
wrote:

> Cluster where all the nodes/master are addressed by names instead of IPs
> for ease of use (all IP<->name mapping for all nodes/master is present in
> /etc/hosts). This is similar to openshift vagrant cluster.
>
> Where the nodes/master are addressed by not-real-DNS names. Yes, the
> vagrant and dind clusters do that, but is that at all common in real
> deployments? I would expect most real deployments to have real hostnames.
> (And do people really want to write EgressNetworkPolicy rules involving the
> master and nodes anyway?)
>
 May be not very common in real deployments. Definitely this is not a
strong argument for this change.

Testing dns name changes will be trivial, don't need to setup local dns
> servers like bind, etc.
>
> But this code only looks in /etc/hosts if dig fails, so it doesn't let you
> test changes to the IPs of real hosts, only fake hostnames.
>
Yes, /etc/hosts is for resolving fake hostnames and that helps in testing.
With this change, we will be on par with what ping does (looks at
/etc/hosts and nameservers) and this is only an additive change.
So we need to answer whether we want to keep an additive change if that
helps in testing?

**Comment by pravisankar** [comment]
Closing this PR.
OpenShift networking team had a discussion on this and the majority agreement was not to support resolving names in /etc/hosts for EgressNetworkPolicy as this is not very common in real production environments and if we want to test domain name changes, we should create a local DNS server.

**Pull request closed without merging**
