### PR TITLE
e2e: honor $USE_IMAGES during registry's deployment

### PR DESCRIPTION
**Pull request by miminar**
Without passing `--images=`, the image will default to
`openshift/origin-${component}:${version}`.

### CODE REVIEW

**Comment by miminar** [comment]
@stevekuznetsov PTAL

**Comment by stevekuznetsov** [comment]
What if `$USE_IMAGES` is unset? Or set but empty?

**Comment by miminar** [comment]
> What if $USE_IMAGES is unset? Or set but empty?

ehh .. one line, one fail.. that's 100% failure :-(. Updated.
[test]

**Comment by stevekuznetsov** [comment]
LGTM

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
one more [test]

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
yum flake, [test]

**Comment by miminar** [comment]
@mfojtik can we please merge this?

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
