### PR TITLE
Revert "Better warning for --build-loglevel with binary builds"

### PR DESCRIPTION
**Pull request by bparees**
Reverts openshift/origin#19120

fixes https://github.com/openshift/origin/issues/19319

@nak3 @soltysh @juanvallejo fyi

### CODE REVIEW

**Comment by bparees** [comment]
@nak3 please create a new PR that fixes the message but retains its status as a warning, not an error.

**Comment by bparees** [comment]
@coreydaley or @gabemontero please give this a quick signoff.

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/19282
/retest

**Comment by liggitt** [comment]
> flake #19282

fixed in https://github.com/openshift/origin/pull/19321

**Comment by nak3** [comment]
@bparees Thank you & I'm sorry for my mistake. I will send the PR after this revert was done.

But please allow me to learn from this my mistake. The error is from this code:

https://github.com/openshift/origin/blob/709739b1182cab9c9d078b1e4133da9bfa153b8e/test/extended/builds/failure_status.go#L192-L193

, and it runs binary build with `--build-loglevel=5`. 

Removing `--build-loglevel` from this binary build code (`statusfail-assemblescript`) was not an option to fix the broken test? I understood `warning`->`error` broke the test, but I would like to learn why this code needs to have `--build-loglevel=5` with binary build, (which does not make sense actually).

**Comment by nak3** [comment]
I'm sorry, I found the comment in https://github.com/openshift/origin/pull/19120#issuecomment-380513891 Please disregard my question above.

**Comment by nak3** [comment]
@bparees Thank you so much. I understand and learned a lot.

**Pull request merged**
