### PR TITLE
Revert "UPSTREAM: 71804: Use UnmountMountPoint util to clean up subpaths"

### PR DESCRIPTION
**Pull request by wking**
Reverts openshift/origin#22396

This is leading to many, many CI failures, including all of the nine runs of https://testgrid.k8s.io/redhat-openshift-release-blocking#redhat-release-openshift-origin-installer-e2e-aws-4.0&sort-by-flakiness= since the test was added.  Revert to get us going again while we look into why.

CC @wongma7, @jwforres, @abhinavdahiya

### CODE REVIEW

**Comment by wking** [comment]
Also CC @jsafrane, @bertinatto.  Not sure what I need to do about [Travis][1]:

```
The following commits contain vendor changes but aren't declared as UPSTREAM or bump(*) commits:
```

Anyone who does is welcome to fix my commit or create their own reverting PR to unstick CI.

[1]: https://travis-ci.org/openshift/origin/builds/511887330#L475

**Comment by wking** [comment]
[integration][1]:

```
FAIL: github.com/openshift/origin/test/integration/runner TestIntegration/TestImageStreamImportRedHatRegistry 4m53.93s
FAIL: github.com/openshift/origin/test/integration/runner TestIntegration 60ms
```

Not much on why?

/test integration

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22412/pull-ci-openshift-origin-master-integration/4394/build-log.txt

**Comment by jsafrane** [comment]
> The following commits contain vendor changes but aren't declared as UPSTREAM or bump(*) commits:

@wking, commit message must be in format `UPSTREAM: 71804: revert ...`

**Comment by wking** [comment]
> commit message must be in format `UPSTREAM: 71804: revert ...`

Can you force-push to my branch or create a new PR?  I'm restricted to GitHub's web UI for the next few hours, and they still don't seem to support amending commit messages.

**Comment by jsafrane** [comment]
Force pushed.

**Pull request merged**
