### PR TITLE
remove grep -P usage

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton PTAL

fixes https://github.com/openshift/origin/issues/6862

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
```
FAILURE after 30.212s: hack/../test/cmd/builds.sh:64: executing 'oc new-build -D $'FROM centos:7' --no-output' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: only a partial match was found for "centos:7": "centos:7"
```

@smarterclayton please re-tag

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@smarterclayton please kick again

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
