### PR TITLE
hack/test-end-to-end.sh won't start on IPv6 system

### PR DESCRIPTION
**Pull request by smarterclayton**
Go selects the ipv6 port for the kubelet. We should select a bind
address based on the master's selection, instead of the hackery we are
doing now.

Will merge only when queue lightens up

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@ironcladlou this and DNS are now fixed for IPv6 systems.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

On Nov 3, 2015, at 1:03 AM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6687/)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5624#issuecomment-153249182>.

**Comment by ironcladlou** [comment]
Tested locally, IT LIVES! Thanks! LGTM

**Comment by ironcladlou** [comment]
[merge]

**Comment by ironcladlou** [comment]
Woops, accidentally tagged this. Deleted the tag.

**Comment by ironcladlou** [comment]
@liggitt @smarterclayton pretty please merge this one

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
