### PR TITLE
Tweak headings and add separator on create page

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1233488

Add separator to make it more obvious these are two different options rather than one form.

openshift_web_console

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
Need to update the UI e2e tests:
```
1)  authenticated e2e-user should view the create page
  - Expected 'Create Using Your Code' to equal 'Create'.
      at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/e2e/test.js:152:47)
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
```

**Comment by spadgett** [comment]
[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
