### PR TITLE
System container: add wrapper to read environment variables from the service file

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
[test]

**Comment by giuseppe** [comment]
@tdawson this is probably the last change required (for now) to get system containers installed using  openshift-ansible latest (the changes there were merged last Friday):

https://github.com/openshift/openshift-ansible/pull/3109

**Comment by sdodson** [comment]
LGTM, failure looks unrelated
[merge]

**Comment by giuseppe** [comment]
how to retrigger the merge?

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
flake https://github.com/openshift/origin/issues/12923

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
