### PR TITLE
use a valid docker1.9 image for extended image test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[test]
[testextended][extended:core(build can have Dockerfile input)]

**Comment by bparees** [comment]
@gabemontero ptal, this should fix the remaining image extended test failure.

**Comment by gabemontero** [comment]
Yeah, I was going to suggest a similar change at some point but then wondered if we wanted to vet origin-base for some reason and let it go.

Anyway, a long winded "lgtm"

**Comment by bparees** [comment]
if it looked like the docker1.10 changes were more impending i would have preferred to leave it, but i think the only advantage to using the origin image is that that image will likely be available locally in the ec2 instance, whereas the jenkins image will need to be pulled if some other test hasn't pulled it already.

[merge]

**Pull request merged**
