### PR TITLE
Disable auto deploy in pipeline template

### PR DESCRIPTION
**Pull request by dongboyan77**
To [bz](https://bugzilla.redhat.com/show_bug.cgi?id=1383804) , could I disable auto deploy in pipeline build template? Thanks @bparees

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik will this work these days?  last i knew we needed the ICT and automatic=true if we wanted imagestream resolution.

**Comment by bparees** [comment]
@kargakis

**Comment by kargakis** [comment]
You can have manual deployments with `oc rollout latest` (and auto=false) in 1.4

**Comment by bparees** [comment]
@kargakis that doesn't help since in our case the deployment is triggered by the jenkins job, but i think you had @gabemontero update the jenkins plugin to use the instantiate endpoint so in theory that means this would work ok?

**Comment by kargakis** [comment]
Yes, `oc rollout latest` uses the instantiate endpoint too

**Comment by bparees** [comment]
tested this w/ the latest jenkins image and it appears to work correctly.
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11114
flake https://github.com/openshift/origin/issues/10336

@dongboyan77 this also needs hack/update-generated-bootstrap.sh run, but i've created another PR that includes this change and another one, so i'm going to just close this:
https://github.com/openshift/origin/pull/11646

**Comment by dongboyan77** [comment]
@bparees ok, thanks

**Pull request closed without merging**
