### PR TITLE
Bundle resize command

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
@mfojtik fyi

**Comment by kargakis** [comment]
@smarterclayton any reason we don't use resize?

**Comment by mfojtik** [comment]
LGTM 

Thanks for adding this! Having to use `osc update --patch` is pretty awful :-)

**Comment by smarterclayton** [comment]
Because it needs to handle deployment configs and it's more complicated.  We can't merge this until it supports DCs.  In the meantime, you'll soon be able to use https://github.com/openshift/origin/pull/1758

**Comment by smarterclayton** [comment]
It's ok to leave it open, we just need to go and do the rest of the work :)

----- Original Message -----

**Comment by kargakis** [comment]
Tab completion gets messed up with so many branches. I can re-write it later.

**Pull request closed without merging**
