### PR TITLE
fix select error handling after WaitForRunningBuild

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/devex fyi

fix the panic

```
panic(0x512e0c0, 0xf08fa50)
 /usr/lib/golang/src/runtime/panic.go:489 +0x2cf
 github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate.(*binaryInstantiateHandler).handle(0xc437c069c0, 0x7f767c03d528, 0xc43427c960, 0x0, 0x0, 0x0, 0x0)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate/rest.go:231 +0x3f5
 github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate.(*binaryInstantiateHandler).ServeHTTP(0xc437c069c0, 0xf115400, 0xc42d56e920, 0xc4326d8600)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate/rest.go:159 +0x9b
 github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1(0xf115400, 0xc42d56e920, 0xc4326d8600)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:256 +0x5f1
 github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints.restfulConnectResource.func1(0xc436118600, 0xc4319da3c0)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1109 +0xe0
 github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc436118600, 0xc4319da3c0)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:144 +0x207
 github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4211c50e0, 0xf115300, 0xc42d56e900, 0xc4326d8600)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
 github.com/openshift/origin/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4211c50e0, 0xf115300, 0xc42d56e900, 0xc4326d8600)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
 github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5b272fb, 0x1c, 0xc4211c50e0, 0xc421fad7a0, 0xf115300, 0xc42d56e900, 0xc4326d8600)
 /tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
 github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4222a4dc0, 0xf115300, 0xc42d56e900, 0xc4326d8600)
```

first seen in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16727/test_pull_request_origin_extended_builds/452/

### CODE REVIEW

**Comment by bparees** [comment]
I think this fix is good, but unless we're the only ones calling WaitForRunningBuild, we need to consider changing the behavior to always return the input object like it used to.  (See the PR I tagged you and @deads2k into)

and we'll need to backport this to stage.

**Comment by gabemontero** [comment]
according to `guru` the only other use is in `pkg/build/registry/buildlog/rests.go` and it checks for error appropriately

**Comment by gabemontero** [comment]
ok experimental unit is not suppose to block merge .... don't appear to be on the merge queue yet but will monitor this weekend

**Comment by bparees** [comment]
was missing the bug label. fixed.

**Pull request merged**
