### PR TITLE
carry: Proceed during violated rolling updates

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @ironcladlou 

Fixes https://github.com/openshift/origin/issues/7271

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
I thought I saw you open the carry upstream?

**Comment by kargakis** [comment]
> I thought I saw you open the carry upstream?

Yes, that's the first commit here. The second commit is what we are going to carry since upstream they don't want it.

**Comment by smarterclayton** [comment]
Link to the discussion on not-wanting it?

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/21273#discussion_r53082595
https://github.com/kubernetes/kubernetes/pull/21273#issuecomment-185731141

**Comment by smarterclayton** [comment]
I'm ok with new pods that *never* become available blocking the deployment
- that's what deployment are supposed to do.

On Fri, Feb 19, 2016 at 12:18 PM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
> I'm ok with new pods that *never* become available blocking the deployment - that's what deployment are supposed to do.

Then what's the story with https://github.com/openshift/origin/issues/7271 ? :)

**Comment by smarterclayton** [comment]
That was invalid *old* deployment.  Invalid new deployment should of course
fail (although the end result of invalid new deployment failed should be
old deployment scaled back to previous value, not left at 0)

On Fri, Feb 19, 2016 at 12:22 PM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
> That was invalid *old* deployment. Invalid new deployment should of course fail (although the end result of invalid new deployment failed should be old deployment scaled back to previous value, not left at 0)

So the rolling updater needs to take into account new unready pods as they scale up and never allow the *old* deployment run in the first place.

**Comment by smarterclayton** [comment]
Did not parse.  I would say: "the rolling updater needs to consider new unready pods that have never been ready as blocking update.  the rolling updater, if it can't make progress by scaling up new pods due to surge, should make progress by scaling down old unready pods, then old ready pods, until it can make progress scaling up new pods.  Unavailability may be breached on the old deployment if surge cannot pick up the slack".

**Comment by kargakis** [comment]
> if it can't make progress by scaling up new pods due to surge, should make progress by scaling down old unready pods, then old ready pods, until it can make progress scaling up new pods

Let me give an example:

1. *first rollout*
Deployment A comes up. Healthy.

1. *second rollout*
Old deployment A is still healthy. Scales down.
New deployment B scales up but misconfigured probes turn it to unready. Currently we **DO NOT FAIL** the deployment and minAvailable is violated.

In the second rollout we should never be able to scale up. Thus, we decrease the chances we end up with an old unready deployment (because currently B becomes old unready when the third rollout runs). That's why you hit #7271, you scaled up an invalid deployment and we allowed you to do so.

**Comment by smarterclayton** [comment]
>  should make progress by scaling down old unready pods, then old ready
pods, until it can make progress scaling up new

Then omit the "old ready pods" comment here, "should make progress by
scaling down old unready pods until it can make progress scaling up new"

**Comment by kargakis** [comment]
Old unready are the first pods that are scaled down anyway. https://github.com/kubernetes/kubernetes/pull/21273 makes the rolling updater behave more like upstream deployments: take into account the size of the deployment at a given point (old.spec.replicas+new.spec.replicas), subtract minimum available, subtract new unavailable. I think if new pods never become available, then we will stop progressing at some point and eventually fail (so we don't need any further changes for both bugs). Need to test it.

**Comment by smarterclayton** [comment]
Yes, that sounds correct.

**Comment by kargakis** [comment]
21273 is enough for both bugs! Will merge https://github.com/openshift/origin/pull/7307 once upstream is lgtm'd

**Pull request closed without merging**
