### PR TITLE
config file should be closed

### PR DESCRIPTION
**Pull request by guangxuli**
config file should be close after function exit.

### CODE REVIEW

**Comment by liggitt** [comment]
thanks, can you do a quick sweep for other unclosed `os.Open` calls while you're at it?

**Comment by guangxuli** [comment]
@liggitt  PTAL I have sweeped all other unclosed file, and modify the code.

**Comment by guangxuli** [comment]
@liggitt  ptal, thanks!

**Comment by guangxuli** [comment]
@danmcp ptal,thanks!

**Pull request closed without merging**
