### PR TITLE
add persistent examples to quickstarts

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@luciddreamz step 1.  ptal.

**Comment by bparees** [comment]
@luciddreamz bump

**Comment by luciddreamz** [comment]
@bparees Everything looks good here

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@sdodson who typically handles pulling additional templates into OCP?  That's the next stop for these.

**Comment by sdodson** [comment]
I generally have but I think this change would be pulled in by simply running roles/openshift_examples/examples_sync.sh and opening a PR with those changes.

**Pull request merged**
