### PR TITLE
[1.5][BACKPORT] Pull-through using insecure transport based on tag import policy

### PR DESCRIPTION
**Pull request by miminar**
Insecure istag now allows for insecure transport.

Resolves: [bz#1421954](https://bugzilla.redhat.com/show_bug.cgi?id=1421954)

This is a backport of #13114

### CODE REVIEW

**Comment by mfojtik** [comment]
Approved for 1.5.

[merge]

**Comment by miminar** [comment]
@mfojtik updated for #13280

**Comment by mfojtik** [comment]
[merge]

**Comment by miminar** [comment]
The failure https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check_future/906/consoleFull#-178241838856bf4006e4b05b79524e5923 is strange. I couldn't reproduce it locally. I've enabled debug logging in the test to get more details if it fails.

**Comment by miminar** [comment]
I made the failing test more robust.

**Comment by miminar** [comment]
Flake https://github.com/openshift/origin/issues/12784 in job https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/915/. re-[test].

**Comment by miminar** [comment]
Finally. I failed to see an error except for

    FAIL	github.com/openshift/origin/pkg/dockerregistry/server	7.604s

until I found `[INFO] Full output from `go test` logged at /openshifttmp/openshift/test-go/logs/test-go.log`. In there, I found there's a data race. With that in mind I was able to reproduce locally by adding `-race` parameter to `go test`. I'm dumping my experience here in case somebody struggles with a unit test failing in jenkins and passing locally.

The race should be fixed now.

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
The failure seems like GCE infra flake, so I think this is good to merge. Will give it one more chance to pass the test first.

**Comment by miminar** [comment]
@mfojtik just a GCE failure. This should be ready now.

**Comment by mfojtik** [comment]
@miminar the merge tag will fail of that GCE test is not fixed :-)

@stevekuznetsov to the rescue.

**Comment by stevekuznetsov** [comment]
Logic [does exist](https://github.com/openshift/origin/blob/master/hack/test-go.sh#L216-L225) and used to work to detect the races in `go test` as races don't lead to failed tests -- I had an issue open against Go as well, they said they'd make races fail tests as well. Looks like API server never came up in GCE -- we've seen that before sometimes, I'd just re-test for now until we are harvesting more logs to get to the bottom of it.

**Comment by mfojtik** [comment]
@stevekuznetsov I've seen this 4x today ;-)

[test]

**Comment by stevekuznetsov** [comment]
Nothing in the master logs that show why?

**Comment by miminar** [comment]
> Nothing in the master logs that show why?

@stevekuznetsov I can find neither master logs nor node logs nor their configs in the artifacts. I feel kind of helpless.

**Comment by stevekuznetsov** [comment]
That's a shame. I'll try to get better logging for us.

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
Unrelated failure:

```
05:29:53     should be applied to XFS filesystem when a pod is created [It]
05:29:53     /go/src/github.com/openshift/origin/test/extended/localquota/local_fsgroup_quota.go:149
05:29:53 
05:29:53     Expected
05:29:53         <string>: 
05:29:53     not to equal
05:29:53         <string>: 
```

@mfojtik can we try another merge?

**Comment by miminar** [comment]
[test]

**Comment by mfojtik** [comment]
seem like another flake...

[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by miminar** [comment]
@mfojtik merge? :smile:

**Comment by mfojtik** [comment]
[merge]

**Comment by miminar** [comment]
Yum flake while building images. @mfojtik can you get it another go?

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
