### PR TITLE
force the docker registry ip to be constant

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Add a note to the README indicating that the registry will only work if you're using kube or openshift with the same service CIDR.

**Comment by bparees** [comment]
That's already somewhat implied by the setup step that has you set the insecure-registry to 172.30.17.0/24 but i'll make it more explicit.

**Comment by bparees** [comment]
@smarterclayton better?

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
