### PR TITLE
add image-pusher role

### PR DESCRIPTION
**Pull request by deads2k**
Adds a `system:image-pusher` specifically for the purpose.

@liggitt Who would you like to assign?

### CODE REVIEW

**Comment by deads2k** [comment]
@stefwalter subin asked for this.  I'm not sure what his github ID is.

**Comment by stefwalter** [comment]
@sub-mod CC

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/5937

re[merge]

**Comment by deads2k** [comment]
infrastructure re[merge]

**Comment by deads2k** [comment]
build issue fixed, re[merge]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/5855

re[merge]

**Comment by deads2k** [comment]
`test-integration.sh` couldn't start etcd.  re[merge]

**Comment by deads2k** [comment]
This happens well after my changes, but I want to be sure.  Will open issue on clean [merge]

```
!!! Error in hack/../test/end-to-end/core.sh:295
	'docker push ${DOCKER_REGISTRY}/cache/prune' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:295 main(...)
Exiting with status 1

[FAIL] !!!!! Test Failed !!!!
```

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/5855 re[merge]

**Pull request merged**
