### PR TITLE
UPSTREAM: 58301: Limit all category to apps group for ds/deployment/r…

### PR DESCRIPTION
**Pull request by deads2k**
…eplicaset

@juanvallejo @liggitt fixed it upstream, we just need to pick it.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1523493

/assign liggitt
/assign @juanvallejo

### CODE REVIEW

**Comment by liggitt** [comment]
do we need it for our resources that are surfaced in two groups as well? looks like the original bz referenced routes

**Comment by deads2k** [comment]
> do we need it for our resources that are surfaced in two groups as well? looks like the original bz referenced routes

Already fixed.  Hence my comment about, "try doing this" for you.  Regrettably, I thought of it post-merge.

**Comment by deads2k** [comment]
@smarterclayton @stevekuznetsov I don't see the gcp job in prow.  Am I just missing it?

**Pull request merged**
