### PR TITLE
Add virtual resource for SAR checks

### PR DESCRIPTION
**Pull request by legionus**
Needed for https://github.com/openshift/image-registry/pull/73

### CODE REVIEW

**Comment by bparees** [comment]
/approve
@openshift/api-review any concerns?  the decision to add this role was made here:
https://github.com/openshift/image-registry/pull/73#issuecomment-372432081

**Comment by deads2k** [comment]
> @openshift/api-review any concerns? the decision to add this role was made here:
> openshift/image-registry#73 (comment)

As a general statement, the prometheus scraper clusterrole looks like a very good candidate for clusterrole aggregation.  The new permission looks fine.

**Comment by bparees** [comment]
closing and reopening to try to kick prow, something is stuck.

**Comment by bparees** [comment]
@stevekuznetsov this seems stuck, tracer didn't give me any insight, but for example the unit test job actually completed days ago.  prow still thinks it is "pending" and i can't make it rerun it.

**Pull request merged**
