### PR TITLE
Copy creationTimestamp from the image

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/12051

### CODE REVIEW

**Comment by mfojtik** [comment]
@miminar || @legionus PTAL

**Comment by miminar** [comment]
[test]

**Comment by legionus** [comment]
LGTM

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/10988 and https://github.com/openshift/origin/issues/11016

[merge]

**Pull request merged**
