### PR TITLE
remove dead controller fields

### PR DESCRIPTION
**Pull request by deads2k**
We have a couple dead external controller fields and one dead internal controller field.

@openshift/api-review 
/assign @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k is this because we use the kube controllers field?

**Comment by deads2k** [comment]
> @deads2k is this because we use the kube controllers field?

Because of the controllers slice in the controllerconfig

**Comment by mfojtik** [comment]
@deads2k serialization_test is still not happy

**Comment by deads2k** [comment]
> @deads2k serialization_test is still not happy

?  I see it as green.

**Comment by mfojtik** [comment]
@deads2k swear I saw a failure before I retested this ;)

**Comment by deads2k** [comment]
@mfojtik bump

**Pull request merged**
