### PR TITLE
bz 1276319 - Fix oc rsync deletion with tar strategy

### PR DESCRIPTION
**Pull request by csrwng**
Fixes deletion of files when --delete is specified and copying from remote to local filesystem. Also ensures that all files (including .hidden files) are deleted in remote directory when copying from local to remote and --delete is specified.

Adds test to validate that files are deleted when copying from container to local filesystem

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by csrwng** [comment]
[testonlyextended][extended:core(rsync)]

**Comment by bparees** [comment]
lgtm.  @openshift/team-origin-committers approval please.  i think it's important this goes in because
1) it ensures equivalent behavior for tar vs rsync
2) we don't want to have to change this behavior after shipping it since it would be a compatibility problem.

**Comment by smarterclayton** [comment]
Approved on Ben's affirmative, [merge]

**Comment by bparees** [comment]
[testonlyextended][extended:core(rsync)]

**Comment by liggitt** [comment]
github flake, re[testonlyextended][extended:core(rsync)]

**Comment by soltysh** [comment]
flake on install-asssets.
[testonlyextended][extended:core(rsync)]

**Pull request merged**
