### PR TITLE
add swagger permissions

### PR DESCRIPTION
**Pull request by deads2k**
Fixes permission problem from https://github.com/openshift/origin/issues/17872

/assign php-coder
/assign simo5

@openshift/sig-security 

@php-coder see if this gets you to the next failure.

### CODE REVIEW

**Comment by php-coder** [comment]
@deads2k Thanks! It fixes #17872 but #17766 is still there:
```console
$ oc explain Pod | head -3
DESCRIPTION:
     Pod is a collection of containers that can run on a host. This resource is
     created by clients and scheduled onto hosts.
$ oc explain BuildConfig
error: Couldn't find resource for "/v1, Kind=BuildConfig"
```
Moreover, it didn't work for `system:admin` too:
```console
$ oc login -u system:admin
Logged into "https://10.34.129.148:8443" as "system:admin" using existing credentials.
$ oc explain BuildConfig --loglevel=8
I1219 14:43:36.253599    6657 loader.go:357] Config loaded from file /home/coder/.kube/config
I1219 14:43:36.268564    6657 round_trippers.go:414] GET https://10.34.129.148:8443/swagger-2.0.0.pb-v1
I1219 14:43:36.268582    6657 round_trippers.go:421] Request Headers:
I1219 14:43:36.268591    6657 round_trippers.go:424]     Accept: application/json, */*
I1219 14:43:36.268597    6657 round_trippers.go:424]     User-Agent: oc/v1.8.1+0d5291c (linux/amd64) kubernetes/0d5291c
I1219 14:43:36.282442    6657 round_trippers.go:439] Response Status: 200 OK in 13 milliseconds
I1219 14:43:36.282470    6657 round_trippers.go:442] Response Headers:
I1219 14:43:36.282483    6657 round_trippers.go:445]     Cache-Control: no-store
I1219 14:43:36.282493    6657 round_trippers.go:445]     Content-Type: application/octet-stream
I1219 14:43:36.282500    6657 round_trippers.go:445]     Etag: "F39E448EBD7E1637C4FAC80D05E985AF21DB63770187B2BB850F6AEA6E7CC81D2DCCD6581F7950692E63B581871213C1017BD3D7FA2DDA271E649E04B109D4C1"
I1219 14:43:36.282509    6657 round_trippers.go:445]     Last-Modified: Tue, 19 Dec 2017 13:38:40 GMT
I1219 14:43:36.282518    6657 round_trippers.go:445]     Vary: Accept-Encoding
I1219 14:43:36.282527    6657 round_trippers.go:445]     Date: Tue, 19 Dec 2017 13:43:36 GMT
I1219 14:43:36.284844    6657 round_trippers.go:445]     Accept-Ranges: bytes
I1219 14:43:36.385181    6657 request.go:871] Response Body:
00000000  0a 03 32 2e 30 12 80 1b  0a 1f 4f 70 65 6e 53 68  |..2.0.....OpenSh|
00000010  69 66 74 20 41 50 49 20  28 77 69 74 68 20 4b 75  |ift API (with Ku|
00000020  62 65 72 6e 65 74 65 73  29 12 20 76 33 2e 39 2e  |bernetes). v3.9.|
00000030  30 2d 61 6c 70 68 61 2e  30 2b 31 63 32 34 64 31  |0-alpha.0+1c24d1|
00000040  38 2d 32 33 33 2d 64 69  72 74 79 1a f7 19 4f 70  |8-233-dirty...Op|
00000050  65 6e 53 68 69 66 74 20  70 72 6f 76 69 64 65 73  |enShift provides|
00000060  20 62 75 69 6c 64 73 2c  20 61 70 70 6c 69 63 61  | builds, applica|
00000070  74 69 6f 6e 20 6c 69 66  65 63 79 63 6c 65 2c 20  |tion lifecycle, |
00000080  69 6d 61 67 65 20 63 6f  6e 74 65 6e 74 20 6d 61  |image content ma|
00000090  6e 61 67 65 6d 65 6e 74  2c 0a 61 6e 64 20 61 64  |nagement,.and ad|
000000a0  6d 69 6e 69 73 74 72 61  74 69 76 65 20 70 6f 6c  |ministrative pol|
000000b0  69 63 79 20 6f 6e 20 74  6f 70 20 6f 66 20 4b 75  |icy on top of Ku|
000000c0  62 65 72 6e 65 74 65 73  2e 20 54 68 65 20 41 50  |bernetes. The A [truncated 10718165 chars]
F1219 14:43:36.408781    6657 helpers.go:119] error: Couldn't find resource for "/v1, Kind=BuildConfig"
```

**Comment by php-coder** [comment]
Test flake https://github.com/openshift/origin/issues/17769
/test unit

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/17897

/retest

**Pull request merged**
