### PR TITLE
bump(github.com/fsouza/go-dockerclient) c68e3a80d465c178e452c843ccd9928570893203

### PR DESCRIPTION
**Pull request by csrwng**
Includes fix for BZ 1255502

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by mfojtik** [comment]
@csrwng is this with sync of what we have in source-to-image repo?

**Comment by csrwng** [comment]
@mfojtik, no... will create a pull there as well. Thx for reminding me

**Comment by liggitt** [comment]
might need to wait on this... @ncdc has exec changes in flight that might need to go in concurrent with this

**Comment by liggitt** [comment]
also, did we ever resolve the version compatibility issues? will this version work against older dockers?

**Comment by csrwng** [comment]
yes, it checks the version of server API 
https://github.com/fsouza/go-dockerclient/pull/365

**Comment by liggitt** [comment]
we need to stay in sync with upstream on the go-dockerclient used... so this needs to be paired with a PR there, but you may want to check with @ncdc first. this version will break `oc exec` until his changes are ready

**Comment by csrwng** [comment]
cool, @ncdc I'll leave it up to you to do the proper updates after your changes go in

**Pull request closed without merging**
