### PR TITLE
Debug should not have 15s timeout

### PR DESCRIPTION
**Pull request by smarterclayton**
Also remove duplicated code and support ImageStreamImage

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k review

**Comment by deads2k** [comment]
lgtm pending test.  looks like there's already one for `istag` in `test/cmd/debug.sh`

**Comment by deads2k** [comment]
re[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
