### PR TITLE
Remove `subjectaccessreviews.v1.` hacks from `test/cmd/authentication.sh`

### PR DESCRIPTION
**Pull request by abstractj**
Fixes: #13158

[test]

//cc @enj

### CODE REVIEW

**Comment by enj** [comment]
LGTM

[merge][severity:lowrisk] minor changes to test code.

**Comment by abstractj** [comment]
flake #13158
[test]

**Comment by abstractj** [comment]
flake #13158
re-[test]

**Comment by abstractj** [comment]
flake #14485
re-[test]

**Pull request merged**
