### PR TITLE
add warning for missing security allocator

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/2938

@liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
`hack/test-cmd.sh: line 99: openshift: command not found`  and a UI failure.  re[merge]

**Comment by deads2k** [comment]
delete-all failure, re[merge]

**Pull request merged**
