### PR TITLE
Fixes openshift-tests run-upgrade dry-run failure asking for KUBERNETES_MASTER

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Similar to https://github.com/openshift/origin/pull/28165
This change is for `run-upgrade`

### CODE REVIEW

**Comment by Rajalakshmi-Girish** [comment]
@vrutkovs I missed to change for `run-upgrade`.
Can you PTAL?

**Comment by Rajalakshmi-Girish** [comment]
> The change looks fine, but I don't think `run-upgrade` is meant to be run in dry-mode. What's the expected result here?

The `--dry-run` flag is valid for `run-upgrade` too.
```
[root@maxwells1 origin]# ./openshift-tests run-upgrade --help
Run an upgrade test suite against an OpenShift server

 This command will run one of the following suites against a cluster identified by the current KUBECONFIG file. See the suite description for more on what actions the suite will take.

 If you specify the --dry-run argument, the actions the suite will take will be printed to the output.
---------
---------
```

**Comment by vrutkovs** [comment]
It is, but what's the output you're expecting? `run-upgrade` is a single test effectively, it cannot be separated into a smaller ones. I don't think dry run makes any sense for it, but since its a global flag it would certainly apply

**Comment by Rajalakshmi-Girish** [comment]
> It is, but what's the output you're expecting? `run-upgrade` is a single test effectively, it cannot be separated into a smaller ones. I don't think dry run makes any sense for it, but since its a global flag it would certainly apply

From the `./openshift-tests run-upgrade --help` command output, I see three suites available under this:
```
Available upgrade suites:

all
  Run all tests.

platform
  Run only the tests that verify the platform remains available.

none
  Don't run disruption tests.
```

We have been running below commands in our internal CI job to verify the built openshift-tests binary:
```
openshift-tests run kubernetes/conformance --dry-run
openshift-tests run-upgrade --dry-run --to-image quay.io/openshift/community-e2e-images:e2e-3-k8s-gcr-io-e2e-test-images-sample-apiserver-1-17-4-AC3A0x1ePf4fLoiv all
```
Please find the attached file for the dry-run output that we get in our CI job.
[run-upgrade-dry-run.txt](https://github.com/openshift/origin/files/12375323/run-upgrade-dry-run.txt)

**Comment by Rajalakshmi-Girish** [comment]
@vrutkovs Please check the above reply.

**Comment by vrutkovs** [comment]
>I see three suites available under this

Right, this starts upgrade and optionally runs some monitor tests in the background - but its pointless to run just one monitor tests separately, even if dry run would output its name.

I agree with the code change here, but I don't think it would produce anything useful - monitors running during uprgade are useless unless the upgrade is running in the background

**Comment by Rajalakshmi-Girish** [comment]
> > I see three suites available under this
> 
> Right, this starts upgrade and optionally runs some monitor tests in the background - but its pointless to run just one monitor tests separately, even if dry run would output its name.
> 
> I agree with the code change here, but I don't think it would produce anything useful - monitors running during uprgade are useless unless the upgrade is running in the background

@vrutkovs do you think disabling the `--dry-run` flag for `run-upgrade` is the right thing to do?

**Comment by Rajalakshmi-Girish** [comment]
We have decided to remove the `openshift-tests run-upgrade --dry-run` command from our Job.
Please close this PR if you feel it is irrelevant.

**Pull request closed without merging**
