### PR TITLE
use src distinct directory for context-dir builds

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1419235

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11016
[test]

**Comment by bparees** [comment]
[test]

@stevekuznetsov the future jobs do not look healthy:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/59/

**Comment by stevekuznetsov** [comment]
@bparees not due to them being "future" jobs but yes lots of flakes esp in GCE

**Pull request merged**
