### PR TITLE
Update openshift-object-describer to 1.1.1

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/3992

partially fixes test flake with missing bindata

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
[merge] [test]

**Comment by liggitt** [comment]
nope:
```
Stderr from the command:
hack/test-assets.sh: line 29: Godeps/_workspace/bin/go-bindata: No such file or directory
```

**Comment by jwforres** [comment]
@liggitt heh amazingly because of a different issue than what update fixed:

```
bower uri.js#1.14.1                          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/medialize/URI.js.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection timed out
```

**Comment by jwforres** [comment]
[merge] [test]

**Comment by jwforres** [comment]
Should we retry bower update once if it fails just to catch spurious network errors with github?

**Comment by smarterclayton** [comment]
Yeah probably.  I'm going to fix vagrant to error on this.

**Pull request merged**
