### PR TITLE
bump(github.com/openshift/source-to-image): d6f07ef78301e6773bae926828c01c86629e6357

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1480312
bug 1480312

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal, not sure why we seem to keep adding+removing the test files in the vendoring but i think removing them is correct.

**Comment by jim-minter** [comment]
> not sure why we seem to keep adding+removing the test files in the vendoring but i think removing them is correct.

Agreed.  In a similar vein, can pkg/test be removed from this PR?

**Pull request closed without merging**
