### PR TITLE
IR-471: Add test for ChunkSizeMiB configuration for Registry

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @flavianmissi

### CODE REVIEW

**Comment by neisw** [comment]
Presume we don't expect the test to run without `[OCPFeatureGate:ChunkSizeMiB]` enabled,  would we get that running a techpreview payload job like `periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview`?

**Comment by deepsm007** [comment]
> Presume we don't expect the test to run without `[OCPFeatureGate:ChunkSizeMiB]` enabled, would we get that running a techpreview payload job like `periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview`?

Yes, it is part of TechPreviewNoUpgrade featureset. We can run a payload job to verify

**Comment by deepsm007** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview

**Comment by deepsm007** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview

**Comment by deepsm007** [comment]
> @deepsm007: trigger 1 job(s) for the /payload-(with-prs|job|aggregate|job-with-prs|aggregate-with-prs) command
> 
> * periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/5af60de0-409e-11ef-8af2-049762e5a6ab-0

All tests passed https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-28932-ci-4.17-e2e-aws-ovn-techpreview/1811890937970823168

**Pull request merged**
