### PR TITLE
handle missing dockerfile with docker strategy

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1287999

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
@mfojtik ptal.

[test]

**Comment by mfojtik** [comment]
LGTM, I don't think we have a way to specify the dockerfile path directly, do we?

**Comment by bparees** [comment]
you mean if your dockerfile is not Dockerfile?  no, new-app does not support repositories like that as far as i know.
[merge]

**Pull request merged**
