### PR TITLE
Migrate build environment utilities from common.sh

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Utility functions related to the Docker container build environment
should be in their own library file, not `common.sh`. In addition to
migrating them, this patch improves Bash-isms in the functions.

@smarterclayton FYI
@Miciah PTAL the second commit

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
Bash changes are very tame in this one, just added quotes where necessary. [merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8752/) failed from the following flakes:
 - [integration](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8752/consoleFull#138599232556bf4006e4b05b79524e5923) failed on: https://github.com/openshift/origin/issues/12017

re[merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8875/) failed from the following flakes:
 - [conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8875/testReport/junit/(root)/Extended/_k8s_io__Port_forwarding__k8s_io__With_a_server_that_expects_a_client_request_should_support_a_client_that_connects__sends_data__and_disconnects__Conformance_/) failed on: #11662 

re[merge]

**Pull request merged**
