### PR TITLE
Package up install-router.sh for inclusion in RPMs

### PR DESCRIPTION
**Pull request by sdodson**
This is temporary. If we're looking for this to be a complete solution for OSE we'll also need to modify the image name.

### CODE REVIEW

**Comment by sdodson** [comment]
@pweil- and @sosiouxme relevant to your interests

**Comment by sosiouxme** [comment]
Need the same thing for the docker registry (so it can alert the master when it gets updated images).

https://github.com/openshift/origin/blob/master/hack/install-registry.sh

**Comment by pweil-** [comment]
I'm starting to think we should just convert this to use getopts.  The next person that has another file/cert/whatever is going to run into the same trouble but `hack/install-router -r ~/route.json -c ~/thecert.pem -i routerId -m https://masterurl:8443` seems like a decent solution.  

What do you think @sosiouxme @thoraxe @sdodson?

**Comment by thoraxe** [comment]
It would be nice if you could specify files and other things on the cli, and have the script automatically ingest them and turn them into appropriate vars.

**Comment by sdodson** [comment]
I was going to suggest that we convert `pod.json` into a template similar to how install-registry.sh and examples/sample-app/docker-registry-template.json do things. But I found out that template parameters are only evaluated for environment variables so this won't work for adjusting the image name from 'openshift/docker-registry' to 'openshift3_beta/docker-registry' so we're stuck with sed manipulation regardless.

We could just keep adding things to /etc/sysconfig/openshift and have scripts source that file if it exists and has the variable we want use it otherwise use script local defaults. This may be nice because it would promote re-use, i hope, perhaps not in practice.

**Comment by smarterclayton** [comment]
#1053 removes the need for this pull.  Router installation is a separate command, and hack/install-router is gone.

**Comment by detiber** [comment]
https://github.com/openshift/origin/pull/1043 Is the correct PR for the router command

**Pull request closed without merging**
