### PR TITLE
migrate use of s.DefaultConvert to autoConvert

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

per direction from @smarterclayton in https://github.com/openshift/origin/pull/8821

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
A build extended test failed:

  Building from a template
  /data/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:58
    should create an s2i build with a quota and run it [It]
    /data/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:57

QUOTA=6000 was expected, but I see QUOTA=-1 in the logs.

Will need to investigate this before merging.

**Comment by bparees** [comment]
> QUOTA=6000 was expected, but I see QUOTA=-1 in the logs.
Will need to investigate this before merging.

known issue: https://github.com/openshift/origin/issues/8427
@mrunalp might be interested in looking at the logs though.

**Comment by gabemontero** [comment]
Ah - cool - thanks

**Pull request merged**
