### PR TITLE
update spec file for latest build

### PR DESCRIPTION
**Pull request by maxamillion**

### CODE REVIEW

**Comment by smarterclayton** [comment]
What's the strategy here?  Last we talked about this, the spec file was maintained outside the origin process.  I'm not sure we care about the spec file tracking with origin - it feels more like a downstream consumer of the origin repo.

**Comment by brenton** [comment]
I guess the issue is we either need to completely remove it from origin or make it useful for the community. Someone in the community commented on the version problems they hit when trying to use our specfile which eventually led to https://github.com/openshift/origin/pull/1323.  Given that we know someone sees value in it I don't see why we wouldn't upstream our specfile.

**Comment by sdodson** [comment]
I guess I could teach tito to override the version information in the spec file with information from os::build::os_version_vars. This would allow us to leave the specfile as is never updating the version and only updating it when there are changes to the RPM build process. We'd document that the RPM must be built using tito.

**Comment by maxamillion** [comment]
I had all this stuff held in another repo but I was told the dev team wanted it tracked in the main repo.

@jwhonce @sdodson  ?

**Comment by maxamillion** [comment]
Errr... for some reason my browser didn't load everyone else's comments until after I posted mine ... feel free to ignore.

**Comment by smarterclayton** [comment]
I just don't think the tito pattern (tags + packages) applies to openshift/origin directly right now.  I believe it applies to a sub repo (something like dist git).  Since we are not automatically revving it each time, and the change log automation isn't something we particularly care about right now, it's definitely not ideal to have this in between state.

----- Original Message -----

**Comment by jwhonce** [comment]
@sdodson I believe the only reason the spec file and packaging was moved into the orgin repo was to reduce the number of repos by one. Yes?

**Comment by sdodson** [comment]
@jwhonce I didn't really have strong reasoning for moving it into the origin repo. I just thought the other repo was a temporary incubation area and the intention was to include it in the origin repo. I'd agree that having an additional repo just for the packaging is a bad idea though.

**Comment by smarterclayton** [comment]
The spec file is "downstream" of OpenShift.  I would prefer not to mix the two if we can avoid it.  Having the spec repo downstream and pinned is better (to me, at first blush) than reverting to the default Tito behavior on the origin repo (tag + spec file change + commit).

**Comment by sdodson** [comment]
The outcome of discussions at the arch review is that the specfile in this repo will not be kept up to date with regard to RPM %{version} %{commit} and %{ldflags}. Those wishing to build RPMs will either need to update the specfiles on their own or use [tito](https://github.com/dgoodwin/tito) to manage their builds. The specfile will otherwise be kept up to date so feel free to submit PRs related to the actual packaging.

See #1309 for more information on the custom tagger/builder.

**Comment by brenton** [comment]
Closing this since PR #1309 is on it's way.

**Pull request closed without merging**
