### PR TITLE
Fixed routes from root

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
@derekwaynecarr all three checks flaked?

**Comment by liggitt** [comment]
jenkins (test and merge):
```
error: timed out waiting for the condition
!!! Error in hack/test-cmd.sh:689
  'oc delete all --all' exited with status 1
```

**Comment by liggitt** [comment]
re[merge]

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
