### PR TITLE
Add commas between pod template ports in UI

### LINKED ISSUE #3991: Pod template ports run together in UI
openshift_web_console

@jwforres

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #3991 

openshift_web_console

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres ptal

**Comment by jwforres** [comment]
Does it wrap ok?

**Comment by spadgett** [comment]
openshift_web_console

We might want a non-breaking space before `(TCP)` and host port? Not crazy how it wraps below the icon, but it's consistent with other fields in the pod template.

**Comment by jwforres** [comment]
Yeah lets do the non breaking space so we keep the protocol with the port.
I agree the alignment isn't great but i dont want to spend too much time on
this until we've implemented the overview changes

**Comment by spadgett** [comment]
Here is non-breaking space and host port at 275px. (`&thinsp;` with `class=nowrap` actually.)

openshift_web_console

Here's a wider screen width.

openshift_web_console

No host port.

openshift_web_console

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
