### PR TITLE
Carry our own webhooks implementation

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@ncdc

**Comment by soltysh** [comment]
LGTM

**Comment by soltysh** [comment]
Although I wonder why you dropped the idea of having this mechanism upstream, especially that they were eager to have it after getting it fleshed out.

**Comment by smarterclayton** [comment]
Eh, Daniel raised too many questions :)

I also think the use case for this is more limited than it seems.

On Aug 31, 2015, at 6:19 AM, Maciej Szulik <notifications@github.com> wrote:

Although I wonder why you dropped the idea of having this mechanism
upstream, especially that they were eager to have it after getting it
fleshed out.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4426#issuecomment-136324308>.

**Comment by soltysh** [comment]
Let's keep it on our radar, I'd like to work on fleshing it out and implementing it upstream, but I guess that'll be post 3.1.

**Comment by smarterclayton** [comment]
It needs a use case upstream, I don't know what that use case is yet.
 [merge]​

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by soltysh** [comment]
> It needs a use case upstream, I don't know what that use case is yet. [merge]​

Finishing a job is an example use-case, which also covers our build scenario.

**Comment by smarterclayton** [comment]
Why would a web hook finish a job?

On Tue, Sep 1, 2015 at 6:24 AM, OpenShift Bot <notifications@github.com>
wrote:

> Merged #4426 <https://github.com/openshift/origin/pull/4426>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4426#event-397579852>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by soltysh** [comment]
My bad, I was thinking the other way around where there will be a webhook notification of a finished job. Whereas we want to trigger something from a webhook. I'll just hide, since weird thoughts come to my mind recently :wink:

**Comment by soltysh** [comment]
Ok, now I have a valid use-case that makes sense :wink: In the scheduled job proposal (https://github.com/kubernetes/kubernetes/pull/11980) we allow starting a job based on a schedule or on demand, which can be a webhook, for example.

**Comment by smarterclayton** [comment]
Ok, that's a use case I can live with.

On Sep 1, 2015, at 3:27 PM, Maciej Szulik <notifications@github.com> wrote:

Ok, now I have a valid use-case that makes sense [image: :wink:] In the
scheduled job proposal (kubernetes/kubernetes#11980
<https://github.com/kubernetes/kubernetes/pull/11980>) we allow starting a
job based on a schedule or on demand, which can be a webhook, for example.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4426#issuecomment-136834129>.

**Pull request merged**
