### PR TITLE
git: copy struct fields and lose the s2i dependency

### PR DESCRIPTION
**Pull request by mfojtik**
Prepare pkg/git to be moved to library-go, lose the s2i dependency and just copy the s2i struct fields.

/cc @deads2k 
/cc @smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
assuming you pass CI, 

/lgtm

There was another spot using that dep for git url parsing.  Perhaps we clear both at once?

**Comment by mfojtik** [comment]
@deads2k yeah, part 2: https://github.com/openshift/origin/pull/20736

**Comment by gabemontero** [comment]
@bparees fyi

**Comment by mfojtik** [comment]
@bparees pkg/git should be moved to library-go

**Comment by bparees** [comment]
@mfojtik started here: https://github.com/openshift/library-go/pull/23

**Pull request merged**
