### PR TITLE
added start-build parameters to cli.md

### PR DESCRIPTION
**Pull request by PI-Victor**
these parameters are incompletely mentioned [here](https://github.com/openshift/origin/blob/6c5e302139b031bbad3451eaa8420691e37e4ef1/docs/generated/oc_by_example_content.adoc#oc-start-build)

they are however mentioned [in the code]
(https://github.com/openshift/origin/blob/6c5e302139b031bbad3451eaa8420691e37e4ef1/docs/generated/oc_by_example_content.adoc#oc-start-build)

nor are they mentioned in the [official docs](https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html) - i will submit a PR fixing that in the openshift-docs repo.

### CODE REVIEW

**Comment by mfojtik** [comment]
@PI-Victor there are more coming :-) see: https://github.com/openshift/origin/pull/5961

**Comment by mfojtik** [comment]
@PI-Victor mind to way merging this and add the `-e` and `--build-loglevel` as well?

**Comment by PI-Victor** [comment]
sure no problem, sorry i did forget about you adding the --build-loglevel and -e options.
let me add those as well and amend  the commit.
there's also  [hack/verify-generated-docs.sh](https://github.com/openshift/origin/blob/master/hack/verify-generated-docs.sh) that generates docs for the oc command [docs/generated/oc_by_example_content.adoc](https://github.com/openshift/origin/blob/master/docs/generated/oc_by_example_content.adoc#oc-start-build) from [this example in the code](https://github.com/openshift/origin/blob/0e3fe6c2e465b807b6bd5e9aadd9e7632ace9277/pkg/cmd/cli/cmd/startbuild.go#L52) here's the [specific PR](https://github.com/openshift/origin/pull/3325). Should we add all the parameters in the code example so that they can be auto-generated and included in the cli_by_example.adoc ?

**Comment by PI-Victor** [comment]
i've updated the pr to include both parameters. let me know if you want to add what i've mentioned above as well.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
