### PR TITLE
Align project with upstream resources that exist outside of namespace

### PR DESCRIPTION
**Pull request by derekwaynecarr**
@jwforres - FYI, this is the change I want to make to align with Kubernetes:

https://github.com/GoogleCloudPlatform/kubernetes/pull/3613

We will need to update our UI to use project.Name only.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
will update UI code tomorrow morning.

**Comment by jwforres** [comment]
@derekwaynecarr so looks like three lines have to change in UI code, all in assets/app/scripts/services/data.js  just search for project.metadata.namespace and switch it to project.metadata.name

**Comment by derekwaynecarr** [comment]
@jwforres - please review.  I am confused on why Travis is being flaky.

**Comment by jwforres** [comment]
@derekwaynecarr the change looks good but you need to update bindata.go for the TEST_ASSETS=true travis job to pass.  To do that you'll need to run hack/install-assets.sh and then run hack/build-assets.sh and check in the updated bindata.go file

as far as the other travis flakiness with the processes being killed during the tests, I think other folks have been seeing that randomly as well

**Comment by derekwaynecarr** [comment]
@jwforres - followed prescribed steps, things are better, but it is still complaining about an error.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
