### PR TITLE
OCPBUGS-19527: retry Prometheus client creation

### PR DESCRIPTION
**Pull request by simonpasquier**
The creation of the Prometheus client does lots of requests to the Kubernetes API behind the scene. This change adds a retry logic to avoid test failures due to transient API errors.

### CODE REVIEW

**Comment by simonpasquier** [comment]
@bparees friendly ping :)

**Comment by bparees** [comment]
> @bparees friendly ping :)

Sorry for missing this, for the future please tag me directly if you're assuming i'm going to review/approve a PR, i don't look at auto/bot-assigned PRs because there are way too many and the assignment is pretty random 


/lgtm
/approve

**Pull request merged**
