### PR TITLE
Fix gitserver hang when cloning with --depth=1

### PR DESCRIPTION
**Pull request by csrwng**
Fixes hang when pushing to gitserver and new-app is invoked

BZ https://bugzilla.redhat.com/show_bug.cgi?id=1334147

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees PTAL

**Comment by csrwng** [comment]
[testonlyextended][extended:core(gitserver)]

**Comment by bparees** [comment]
lgtm but failure needs analysis (i didn't look at the logs but i'll guess it's the xip io issue?

**Comment by csrwng** [comment]
@bparees the extended test failure happened because no tests were found to run... and yes, it looks like all our gitserver tests have been commented out because of the .xip.io flake

[test]

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
