### PR TITLE
[WIP] Changed runtime.EmbeddedObject references to point to runtime.Object 

### LINKED ISSUE #2063: Switch from runtime.EmbeddedObject to runtime.Object
`runtime.EmbeddedObject` is obsolete.  We should be using `runtime.Object` instead.  This type is used inside of our API objects.

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Changing reference to `Kubernetes runtime.EmbeddedObject` to point to `runtime.Object`, as `EmbededObject `is obsolete.

Fixes #2063

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by danmcp** [comment]
@stevekuznetsov Needs a rebase

**Comment by smarterclayton** [comment]
Needs rebase

**Comment by stevekuznetsov** [comment]
@smarterclayton Will look at this post-July 13th

**Pull request closed without merging**
