### PR TITLE
support credentials for incremental s2i builds

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/4127

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik @gabemontero ptal.  test cases (maybe extended ones?) to follow.

i ended up refactoring a lot of the auth logic, i think it's cleaner now, and our build logs are nicer/quieter as well.

**Comment by bparees** [comment]
@csrwng this is the pull/push secrets PR i mentioned.  ptal.

**Comment by bparees** [comment]
@csrwng @gabemontero @mfojtik bump for review.

**Comment by bparees** [comment]
[test]

**Comment by csrwng** [comment]
The origin portion LGTM. I assume the STI part was reviewed in a separate PR?

**Comment by bparees** [comment]
yeah the s2i bits were reviewed when they went into s2i.

**Comment by gabemontero** [comment]
OK, reviewed this PR, along with https://github.com/openshift/origin/issues/4135, https://github.com/openshift/source-to-image/issues/261, and https://github.com/openshift/source-to-image/issues/263 for reference.

igtm

**Comment by bparees** [comment]
Thanks, merging, will do extended tests in a separate PR.
[merge]

**Pull request merged**
