### PR TITLE
Migration script (release-1.4 cherry-pick)

### PR DESCRIPTION
**Pull request by kargakis**
@stevekuznetsov @sjenning

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
LGTM -- @smarterclayton anything before merge?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Be sure to send an email to the dev list about this.

**Comment by kargakis** [comment]
@smarterclayton I have opened PRs for having this in release-1.5 and master but I am wondering if we need to have it there?

**Comment by smarterclayton** [comment]
Yes in both.

**Pull request merged**
