### PR TITLE
WIP: Testing  CICD Service Catalog, do not merge 

### PR DESCRIPTION
**Pull request by jboyd01**
Needed a PR for trigging the CICD job, do not merge.

### CODE REVIEW

**Comment by soltysh** [comment]
@jboyd01 changing title to WIP... will add appropriate label and make sure the PR is never merged.

**Comment by stevekuznetsov** [comment]
@jboyd01 if you have a moment -- add the jUnit report flags to the `ginkgo` call so we can have a nicer view into what failed

**Comment by jboyd01** [comment]
@stevekuznetsov  RE jenkins & ginkgo - better reporting sounds like a great idea.  Looks like this requires changing the source that is running the ginkgo test though and that is upstream, I'll take a look at doing that but I'll have to first ensure it fits in with the upstream configuration.

I just added inclusion of the unit tests which ran fine.  Do I need to do any special handling to get good reporting of go unit tests?    My guess is it needs to report in junit format?  Do we have any use of https://github.com/jstemmer/go-junit-report or something similar?

**Comment by stevekuznetsov** [comment]
In origin we have `tools/junitreport` -- you can see how we use it in [our unit tests](https://github.com/openshift/origin/blob/master/hack/lib/test/junit.sh#L184)

For Ginkgo you should just be able to pass the `-report-dir` flag (don't quote me on that flag name)

**Pull request closed without merging**
