### PR TITLE
e2e: disable broken hostAlias test

### PR DESCRIPTION
**Pull request by ironcladlou**
https://bugzilla.redhat.com/show_bug.cgi?id=1695278

### CODE REVIEW

**Comment by wking** [comment]
[images][1]:

```
error: could not run steps: some steps failed:
  * could not wait for build: the build node failed after 3m20s with reason GenericBuildFailed: Generic Build failure - check logs for details.
  * could not wait for build: the build cli failed after 4m2s with reason GenericBuildFailed: Generic Build failure - check logs for details.
  * could not wait for build: the build template-service-broker failed after 4m6s with reason GenericBuildFailed: Generic Build failure - check logs for details.```
```

Dunno what's going on there, but in the hopes that it's a flake...

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22454/pull-ci-openshift-origin-master-images/4236/build-log.txt

**Comment by wking** [comment]
[Same build errors][1].  I don't see how they could possibly be the result of this PR.  Digging around...

**Comment by wking** [comment]
[This][1] (launched ~2 hours ago from a separate origin PR) got through e2e-aws, so kicking this one again to try and break through the flake.

/test images

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22430/pull-ci-openshift-origin-master-e2e-aws/6176

**Comment by wking** [comment]
Hello, Prow?

/test images

**Comment by smarterclayton** [comment]
Nm, I didn't see we got a green.

Force merging to unblock the queues.

**Pull request merged**
