### PR TITLE
UPSTREAM: 383: support HTTP Multiple Choices in pagination

### PR DESCRIPTION
**Pull request by rootfs**
Fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1461374

@eparis @childsb

### CODE REVIEW

**Comment by eparis** [comment]
@liggitt you deal with vendor a lot, does he need anything else here?  (he's working on actually doing a full rebase in upstream kube)

**Comment by liggitt** [comment]
It needs to include the name of the component being vendored in the commit title 

github.com/gophercloud/gophercloud

 There are more details and examples in the Travis failure

**Comment by rootfs** [comment]
Commit message updated and verified locally

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
@eparis @liggitt @childsb can you merge? green is gold...

**Comment by childsb** [comment]
<bc> liggitt : is the vendor component msg correct on this pr now? 
<liggitt>	bc: if travis is happy, I'm happy
[merge][severity:blocker]

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
