### PR TITLE
bump(github.com/RangelReale/osincli): fababb0555f21315d1a34af6615a16eaab44396b

### PR DESCRIPTION
**Pull request by enj**
Adds [PKCE](https://tools.ietf.org/html/rfc7636) support to `osincli`.

xref: #10871

### CODE REVIEW

**Comment by enj** [comment]
[test]

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by enj** [comment]
Not sure what this is about...

```
=== RUN   TestCreateSetsMetadata
2016-10-10 14:08:47.443485 I | etcdserver: name = foo
2016-10-10 14:08:47.443558 I | etcdserver: data dir = /tmp/etcd159922421
2016-10-10 14:08:47.443606 I | etcdserver: member dir = /tmp/etcd159922421/member
2016-10-10 14:08:47.443644 I | etcdserver: heartbeat = 10ms
2016-10-10 14:08:47.443676 I | etcdserver: election = 100ms
2016-10-10 14:08:47.443709 I | etcdserver: snapshot count = 0
2016-10-10 14:08:47.443757 I | etcdserver: advertise client URLs = http://127.0.0.1:44438
2016-10-10 14:08:47.443801 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:37784
2016-10-10 14:08:47.443920 I | etcdserver: initial cluster = foo=http://127.0.0.1:37784
2016-10-10 14:08:47.459142 I | etcdserver: starting member 1dfff579f8331a57 in cluster eac3595b9d7c0578
2016-10-10 14:08:47.459254 I | raft: 1dfff579f8331a57 became follower at term 0
2016-10-10 14:08:47.459336 I | raft: newRaft 1dfff579f8331a57 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-10-10 14:08:47.459391 I | raft: 1dfff579f8331a57 became follower at term 1
2016-10-10 14:08:47.462515 I | etcdserver: set snapshot count to default 10000
2016-10-10 14:08:47.462573 I | etcdserver: starting server... [version: 3.1.0-alpha.1, cluster version: to_be_decided]
2016-10-10 14:08:47.469103 I | membership: added member 1dfff579f8331a57 [http://127.0.0.1:37784] to cluster eac3595b9d7c0578
2016-10-10 14:08:47.564082 I | raft: 1dfff579f8331a57 is starting a new election at term 1
2016-10-10 14:08:47.564178 I | raft: 1dfff579f8331a57 became candidate at term 2
2016-10-10 14:08:47.564259 I | raft: 1dfff579f8331a57 received vote from 1dfff579f8331a57 at term 2
2016-10-10 14:08:47.564359 I | raft: 1dfff579f8331a57 became leader at term 2
2016-10-10 14:08:47.564431 I | raft: raft.node: 1dfff579f8331a57 elected leader 1dfff579f8331a57 at term 2
2016-10-10 14:08:47.565129 I | etcdserver: setting up the initial cluster version to 3.1
2016-10-10 14:08:47.565848 N | membership: set the initial cluster version to 3.1
2016-10-10 14:08:47.566268 I | etcdserver: published {Name:foo ClientURLs:[http://127.0.0.1:44438]} to cluster eac3595b9d7c0578
2016-10-10 14:08:47.591639 I | etcdserver: name = foo
2016-10-10 14:08:47.591699 I | etcdserver: data dir = /tmp/etcd398647760
2016-10-10 14:08:47.591749 I | etcdserver: member dir = /tmp/etcd398647760/member
2016-10-10 14:08:47.591790 I | etcdserver: heartbeat = 10ms
2016-10-10 14:08:47.591828 I | etcdserver: election = 100ms
2016-10-10 14:08:47.591866 I | etcdserver: snapshot count = 0
2016-10-10 14:08:47.591916 I | etcdserver: advertise client URLs = http://127.0.0.1:46574
2016-10-10 14:08:47.591963 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:40544
2016-10-10 14:08:47.592019 I | etcdserver: initial cluster = foo=http://127.0.0.1:40544
2016-10-10 14:08:47.607532 I | etcdserver: starting member bdf6bbf5fc19b874 in cluster 8bc74d893de29b4e
2016-10-10 14:08:47.607642 I | raft: bdf6bbf5fc19b874 became follower at term 0
2016-10-10 14:08:47.607721 I | raft: newRaft bdf6bbf5fc19b874 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-10-10 14:08:47.607778 I | raft: bdf6bbf5fc19b874 became follower at term 1
2016-10-10 14:08:47.610910 I | etcdserver: set snapshot count to default 10000
2016-10-10 14:08:47.610964 I | etcdserver: starting server... [version: 3.1.0-alpha.1, cluster version: to_be_decided]
2016-10-10 14:08:47.615309 I | membership: added member bdf6bbf5fc19b874 [http://127.0.0.1:40544] to cluster 8bc74d893de29b4e
2016-10-10 14:08:47.658341 I | raft: bdf6bbf5fc19b874 is starting a new election at term 1
2016-10-10 14:08:47.658454 I | raft: bdf6bbf5fc19b874 became candidate at term 2
2016-10-10 14:08:47.658511 I | raft: bdf6bbf5fc19b874 received vote from bdf6bbf5fc19b874 at term 2
2016-10-10 14:08:47.658585 I | raft: bdf6bbf5fc19b874 became leader at term 2
2016-10-10 14:08:47.658644 I | raft: raft.node: bdf6bbf5fc19b874 elected leader bdf6bbf5fc19b874 at term 2
2016-10-10 14:08:47.659581 I | etcdserver: published {Name:foo ClientURLs:[http://127.0.0.1:46574]} to cluster 8bc74d893de29b4e
2016-10-10 14:08:47.659884 I | etcdserver: setting up the initial cluster version to 3.1
2016-10-10 14:08:47.660249 N | membership: set the initial cluster version to 3.1
2016-10-10 14:08:47.698082 I | etcdserver: skipped leadership transfer for single member cluster
2016-10-10 14:08:47.970716 I | etcdserver: skipped leadership transfer for single member cluster
==================
WARNING: DATA RACE
Read by goroutine 51:
  internal/race.Read()
      /usr/lib/golang/src/internal/race/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /usr/lib/golang/src/sync/waitgroup.go:67 +0xfa
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).goAttach()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:1533 +0x46
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).sync()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:1052 +0x376
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*raftNode).start.func1()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/raft.go:249 +0x152f

Previous write by goroutine 31:
  internal/race.Write()
      /usr/lib/golang/src/internal/race/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /usr/lib/golang/src/sync/waitgroup.go:125 +0xf9
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func1()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:580 +0x84
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:645 +0xbec

Goroutine 51 (running) created at:
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*raftNode).start()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/raft.go:254 +0x31a
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:564 +0x1f8

Goroutine 31 (running) created at:
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).start()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:503 +0x7b0
  github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).Start()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:476 +0x32
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).launch()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:183 +0x2fd
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing.NewUnsecuredEtcdTestClientServer()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:275 +0x80
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:40 +0x43
  github.com/openshift/origin/pkg/image/registry/image/etcd.newStorage()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/image/registry/image/etcd/etcd_test.go:23 +0x72
  github.com/openshift/origin/pkg/image/registry/image/etcd.TestCreateSetsMetadata()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/image/registry/image/etcd/etcd_test.go:231 +0x3ed
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:473 +0xdc
==================
--- PASS: TestCreateSetsMetadata (0.87s)
```

**Comment by liggitt** [comment]
impressive... @smarterclayton, you ever seen a WaitGroup race?

**Comment by smarterclayton** [comment]
Wow.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
