### PR TITLE
Bump github.com/openshift/service-serving-cert-signer

### PR DESCRIPTION
**Pull request by enj**
Fixes origin bumps again.

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
/hold

@soltysh please confirm this will not mess with the rebase.

/assign @bparees

**Comment by bparees** [comment]
I still think SCSS should be pinned so we stop hitting this problem.

if you need to bump it, you can update the pin.

**Comment by soltysh** [comment]
@

> /cc @smarterclayton because I suspect there's about to be a larger discussion about bumping during the rebase.

We try not to bump these during the rebase, unless necessary.

**Comment by soltysh** [comment]
@enj you might need to fix the generated changes

**Pull request merged**
