### PR TITLE
UPSTREAM: 51962: ignore unknown resource version in scaler error

### PR DESCRIPTION
**Pull request by juanvallejo**
Fixes https://github.com/openshift/origin/issues/16056
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/51962

cc @openshift/cli-review

### CODE REVIEW

**Comment by fabianofranz** [comment]
PTAL @soltysh

**Comment by soltysh** [comment]
The error looks like a flake, since you haven't touched that code, I've openend https://github.com/openshift/origin/issues/16404

/retest
/lgtm

**Comment by juanvallejo** [comment]
@liggit ping

**Comment by liggitt** [comment]
is this just a cosmetic fix that cleans up and error message, but does not actually fix an error condition? if so, let's not carry cherry-picks for that

**Comment by juanvallejo** [comment]
@liggitt thanks, will close this PR.
Upstream PR [1] has merged.
Tagged issue [2] as `post-rebase`.

1. https://github.com/kubernetes/kubernetes/pull/51962
2. https://github.com/openshift/origin/issues/16056

**Pull request closed without merging**
