### PR TITLE
UPSTREAM: 59279: nodelifecycle: set OutOfDisk unknown on node timeout

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/59279

xref https://bugzilla.redhat.com/show_bug.cgi?id=1541263

@derekwaynecarr @wjiangjay

### CODE REVIEW

**Comment by sjenning** [comment]
flake https://github.com/openshift/origin/issues/17883 https://github.com/openshift/origin/issues/17556
/retest

**Comment by aveshagarwal** [comment]
@derekwaynecarr could you approve this?

**Comment by aveshagarwal** [comment]
flake: https://github.com/openshift/origin/issues/18136

**Pull request merged**
