### PR TITLE
make event checking more robust

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton I have low confidence this resolves https://github.com/openshift/origin/issues/1443 but it's the only thing i see that's slightly questionable in the test behavior for the image change test case.  i have not been able to reproduce the failure you're seeing.

[test]

**Comment by smarterclayton** [comment]
Comment is wierd - add can never get collapsed into modified.

**Comment by smarterclayton** [comment]
I'll try it localy

**Comment by bparees** [comment]
I thought that's exactly what FIFO does if the ADD is in queue when the MODIFIED comes in?

**Comment by smarterclayton** [comment]
This is the watch - it's showing you underlying etcd changes.

**Comment by bparees** [comment]
as @smarterclayton explained to me, this WATCH doesn't suffer from the event conflation behavior of FIFO so this fix doesn't do anything useful.  closing.

**Pull request closed without merging**
