### PR TITLE
UPSTREAM: 45940: apiserver: no Status in body for http 204

### LINKED ISSUE #14213: apiserver received an error that is not an unversioned.Status
[provide a description of the issue]
E0516 02:46:29.934047  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.936172  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.936884  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.938625  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.939359  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.941478  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.942056  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.943602  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.944462  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.945731  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.946286  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.947860  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.948086  107960 apiserver.go:487] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E0516 02:46:29.949984  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
E0516 02:46:29.952112  107960 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body

##### Version
[provide output of the `openshift version` or `oc version` command]
[root@c3-container-cloud06 ~]# openshift version
openshift v1.5.0
kubernetes v1.5.2+43a9be4
etcd 3.1.0

##### Steps To Reproduce
1. [step 1] Just run `/usr/bin/openshift start master --config=/etc/origin/master/master-config.yaml --loglevel=1`
2. [step 2]

##### Expected Result
No such error output
##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
cc @kargakis @mfojtik @pweil- @deads2k @liggitt @sttts @soltysh @smarterclayton

### PR DESCRIPTION
**Pull request by sttts**
Fixes #14213

### CODE REVIEW

**Comment by sttts** [comment]
[test]

**Comment by sttts** [comment]
Flake #13943

**Comment by sttts** [comment]
re[test]

**Comment by kargakis** [comment]
lgtm [merge]

**Pull request merged**
