### PR TITLE
gitserver: allow anonymous access when using uid/pwd auth

### PR DESCRIPTION
**Pull request by csrwng**
Allows anonymous access when ALLOW_ANON_GIT_PULL is true. Brings the uid/pwd auth method to parity with the server auth method.

### CODE REVIEW

**Comment by csrwng** [comment]
@gabemontero or @mnagy ptal

**Comment by gabemontero** [comment]
No unit tests?

**Comment by csrwng** [comment]
@mnagy addressed your comment and removed wrong/extraneous check in the auth function.
@gabemontero added a TODO for the refactor needed for unit tests. That should be addressed in a follow up PR.

**Comment by gabemontero** [comment]
IGTM

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
