### PR TITLE
Bug 1940518: resources: remove metal3 from broken pods

### PR DESCRIPTION
**Pull request by honza**
This can be merged after this: https://github.com/openshift/cluster-baremetal-operator/pull/121

### CODE REVIEW

**Comment by sadasu** [comment]
/lgtm
The CI failure seems unrelated to the changes proposed in the PR.

**Review by ravisantoshgudimetla — APPROVED** [review]
/approve

cc @soltysh

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
