### PR TITLE
UPSTREAM: 25161: Sort resources in quota errors to avoid duplicate events

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1333122

### CODE REVIEW

**Comment by deads2k** [comment]
we run upstream unit tests, can you pull back the test changes too?

**Comment by deads2k** [comment]
> we run upstream unit tests, can you pull back the test changes too?

Also, did the `hack/cherry-pick.sh` script not do that automatically?

**Comment by derekwaynecarr** [comment]
@deads2k - I had not used the script to do the cherry-pick, I don't remember why.  Used the script this time, and all should be good now.

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@derekwaynecarr 

```
[WARNING] `go test` had the following output to stderr:
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go:98: undefined: api.ResourceServicesNodePorts
```

**Comment by derekwaynecarr** [comment]
[test]

**Comment by pmorie** [comment]
LGTM, I am fine to tag this merge on green -- looks exactly like the upstream PR.

**Comment by ncdc** [comment]
It looks like the conformance test from https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/4363/ hung, so I aborted it. Also, prior to getting stuck, one of the tests failed because the node stopped reporting its status. Rekicking the [test].

**Comment by eparis** [comment]
[merge]

**Pull request merged**
