### PR TITLE
WIP: Add liveness and readiness probes to examples

### PR DESCRIPTION
**Pull request by mfojtik**
Update database and application examples to include readiness and liveness probes.

NOTE: Ignore @kargakis commit ;-)

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees @mnagy @rhcarvalho please sanity check the values. It is mostly based on my observation on how fast the DB's are started. I would prefer TCP socket check for database liveness probes because I don't want to increase memory usage of the container by periodically executing a command.

**Comment by rhcarvalho** [comment]
@mfojtik what reasoning did you use for `timeoutSeconds` and `initialDelaySeconds`?

**Comment by mfojtik** [comment]
@rhcarvalho initialDelaySeconds because there is no reason to try when the db is initializing... the events will be full of failed probes. It is safe to wait couple seconds to make sure DB is properly initialized. `timeoutSeconds` is because we don't want to hang on broken DB connection forever. DB should be fast in response, if it is slow, we consider it as unhealthy.

**Comment by rhcarvalho** [comment]
Hmm, sorry if I was not clear.

What is the reason for the values you picked for those two fields? Every template seems to have different values for those: 1, 15, 10, ...

**Comment by mfojtik** [comment]
@rhcarvalho https://github.com/openshift/origin/pull/7689#issuecomment-190217403

**Comment by rhcarvalho** [comment]
So you picked each of them out of independent observation?

For me it's strange to compare the templates and see:

```diff
+                "livenessProbe": {
+                  "timeoutSeconds": 1,
+                  "initialDelaySeconds": 10,
```

For Mongo and PostgreSQL, but initial delay of 15 seconds for MySQL... do we need to make special cases?

Same for `readinessProbe` which is 1/3, 1/10, 1/5...

**Comment by mfojtik** [comment]
@rhcarvalho liveness probe should be executed after readiness probe which is why it has 15 seconds.

**Comment by bparees** [comment]
> For Mongo and PostgreSQL, but initial delay of 15 seconds for MySQL... do we need to make special cases?

what do you mean by special cases?  Each DB is a special case.  You need to set an initial delay sufficient to prevent k8s from deciding your container is dead before it even starts, and killing it.

Given that each image is running a different thing, each has different startup times, and needs a different delay.

**Comment by bparees** [comment]
@mfojtik why are the readiness probe initial delays all shorter than the liveness probe initial delay?  I would have expected the opposite.  If you don't expect it to be live for 15 seconds, why would you expect it to be ready after 10s?

(that said, failing a liveness probe is catastrophic, failing a readiness probe is not, so perhaps that is a reason to do readiness probes sooner than liveness)

**Comment by mfojtik** [comment]
@bparees they both start when you create the pods, so the liveness probe initial delay is longer to first make the service "ready" :-) liveness is not started after readiness.

**Comment by bparees** [comment]
> @bparees they both start when you create the pods, so the liveness probe initial delay is longer to first make the service "ready" :-) liveness is not started after readiness.

i know they start together, but the way you have it now, you're saying "i don't expect this to be live for 15 seconds, but after 10s start checking it for readiness" which means you basically expect it to fail readiness for at least 5s.  Which again, isn't really terrible since it has little impact, it just looks a little strange.

**Comment by mfojtik** [comment]
@bparees what I did was:

1) Deploy and watch the container logs
2) When the DB logs says "accepting connections" I pick that as initialDelay for readiness. We can start readiness check sooner and more frequently. It might produce ugly event errors and paint the Pod to orange, so there should be some initialDelay to prevent that. 
3) When the db is ready (turn blue), then give it some extra time and start checking if it lives. Since that is only tcp check, it is pretty fast and the db should be ready at that time.

Liveness probe should have greater initialDelays because they are fatal (container restarts). Maybe we should set it even higher to avoid restarts on really slow systems.

**Comment by mfojtik** [comment]
@bparees @rhcarvalho so to summarize, I will:

1) Start the readiness check sooner if possible.
2) Set the initialDelay for liveness probe higher (to avoid killing container that is just slow to initialize)

I don't think that having the same numbers for all databases is the best option, because the time they all are "ready" is different (mysql ~ 10s, postgresql ~5s, mongo ~3s). I don't want other services/apps wait longer only to make it look good in template and I don't think "maintenance" of different numbers is a burden. I guess in the future we will be tweaking those numbers and looking for the golden path.

**Comment by mfojtik** [comment]
@bparees updated.

**Comment by bparees** [comment]
lgtm aside from the extraneous commit

**Comment by mfojtik** [comment]
@bparees commit removed. [merge]

**Comment by mfojtik** [comment]
re [merge]

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
