### PR TITLE
remove template instantiate from current process

### PR DESCRIPTION
**Pull request by deads2k**
Removing bad usages of the factory requires cleaning this up and the pull got reasonably large/complex as I went through.

/assign @mfojtik 
/assign @soltysh

### CODE REVIEW

**Comment by deads2k** [comment]
@mfojtik also fixes a non-indepotent service catalog installation bug.

**Comment by deads2k** [comment]
@mfojtik lgtm via irc

**Comment by deads2k** [comment]
@stevekuznetsov @bparees test seems wedged again.  Jenkins log says success but it doesn't finish and report back.

Can we either fix the regex, fix the problem, or take the test back to non-blocking?

**Comment by bparees** [comment]
the wedging needs to be fixed regardless of taking the other actions.  it's not wedging in anything specific to our tests that i see.

as for narrowing it, i have a PR here: 
https://github.com/openshift/release/pull/729

but @stevekuznetsov will have to guide it through being rolled out i think.

**Comment by deads2k** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19111/test_pull_request_origin_extended_image_ecosystem/765/ also wedged.

/test extended_image_ecosystem

**Comment by kargakis** [comment]
```
[91m[1m• Failure [60.057 seconds][0m
[service-catalog] ServiceInstance
[90m/data/src/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/test/e2e/framework/framework.go:89[0m
  [91m[1mshould verify an Instance can be deleted if referenced service class does not exist. [It][0m
  [90m/data/src/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/test/e2e/instance.go:81[0m

  [91mExpected error:
      <*errors.errorString | 0xc420270440>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred[0m
```
/retest

**Comment by deads2k** [comment]
/hold

for investigation of the service-catalog failure.  it seems fairly consistent.

**Comment by deads2k** [comment]
spoke with test owners via email and irc

/skip
/hold cancel

**Pull request merged**
