### PR TITLE
Rename dry-run to confirm for prune commands

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton @derekwaynecarr @tnguyen-rh PTAL

**Comment by derekwaynecarr** [comment]
Is there a doc PR?

**Comment by ncdc** [comment]
Not yet but I'll do it.

**Comment by ncdc** [comment]
Docs PR: https://github.com/openshift/openshift-docs/pull/442

**Comment by ironcladlou** [comment]
LGTM

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
