### PR TITLE
Add delete-namespace* flags

### PR DESCRIPTION
**Pull request by mkumatag**
These flags will be helpful while debugging the tests

### CODE REVIEW

**Comment by pweil-** [comment]
/assign @soltysh 

Maciej, are you the best one to review this or can you assign it to the right person?  Thanks!

**Comment by mkumatag** [comment]
> Isn't setting `DELETE_NAMESPACE` envvar, see here: https://github.com/openshift/origin/blob/master/test/extended/util/test.go#L62

seems like that does magic for deleting the samespace but I was more interested in DeleteNamespaceOnFailure which retains the data only for the failures!

**Comment by soltysh** [comment]
@mkumatag you can still run an individual test manually and with `DELETE_NAMESPACE` keep the namespace. This is only for local dev so that shouldn't be a problem. We will never allow setting this anywhere in our CI or alike.

**Comment by mkumatag** [comment]
That is how I'm running it now.. 😁

**Pull request closed without merging**
