### PR TITLE
Bug 1751124: UPSTREAM: 83727: Optionally run e2e pod as privileged for SELinux

### PR DESCRIPTION
**Pull request by bertinatto**
Optionally run e2e pod as privileged for SELinux

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold

Upstream not merged yet.

**Comment by bertinatto** [comment]
/hold cancel
Merged in upstream.

**Comment by bertinatto** [comment]
/retitle Bug 1751124: UPSTREAM: 83727: Optionally run e2e pod as privileged for SELinux

**Comment by knobunc** [comment]
/lgtm
I'll approve when the approver change gets through...

**Pull request merged**
