### PR TITLE
Bug 2093234: Add regex filter and intervals duration to e2e-charts

### PR DESCRIPTION
**Pull request by pmtk**
* Adds a filter (JS RegExp) to filter the chart
* Adds a duration to each event (both occurrences and summary on the right side of the chart)

### CODE REVIEW

**Comment by stbenjam** [comment]
This is very cool.  Can you file a bug and add it to the title?

/lgtm

**Comment by dgoodwin** [comment]
This is extremely high value for us on TRT, thank you!

**Pull request merged**
