### PR TITLE
UPSTREAM: 41366: Change default reconciler sync period to 1 minute

### PR DESCRIPTION
**Pull request by mfojtik**
Ref: https://github.com/openshift/origin/issues/13025

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@smarterclayton 👍 or 👎 for 1.5?

**Comment by mfojtik** [comment]
@soltysh just pushed the fix.

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/13050

[test]

**Comment by smarterclayton** [comment]
@openshift/storage needs to weigh in, i thought the argument was for but it's been a while.

**Comment by mfojtik** [comment]
@jsafrane any concerns?

**Comment by mfojtik** [comment]
[test]

**Comment by jsafrane** [comment]
lgtm

**Comment by jsafrane** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
