### PR TITLE
resolve `groups "impersonategroup" already exists` error

### LINKED ISSUE #16013: [Conformance][templates] templateinstance impersonation tests should pass impersonation update tests
```
/tmp/openshift/build-rpm-release/tito/rpmbuild-originTkCUS7/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateinstance_impersonation.go:180
Expected error:
    <*errors.StatusError | 0xc4213f1880>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "groups \"impersonategroup\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "impersonategroup",
                Group: "",
                Kind: "groups",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    groups "impersonategroup" already exists
not to have occurred
```

Seen: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15624/test_pull_request_origin_extended_conformance_gce/6794/#-conformancetemplates-templateinstance-impersonation-tests-should-pass-impersonation-update-tests

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #16013

### CODE REVIEW

**Comment by jim-minter** [comment]
@bparees I think this should fix the issue, wdyt?

**Comment by mfojtik** [comment]
/test extended_conformance_gce

flake: https://github.com/openshift/origin/issues/16025

**Comment by jim-minter** [comment]
flake #16025 again

/retest

@bparees don't know if you just want to merge this one in.

**Pull request merged**
