### PR TITLE
Given we don't restrict on Travis success.  Make what it does report …

### PR DESCRIPTION
**Pull request by danmcp**
…be 100% reliable and fast.  So when it does fail we know something is truly wrong.

### CODE REVIEW

**Comment by danmcp** [comment]
@smarterclayton @jwforres @bparees Thoughts?

**Comment by liggitt** [comment]
This doesn't look fast

**Comment by danmcp** [comment]
@liggitt Indeed.  It has to start before it finishes.  It's currently on 19615 and this one is 19635.  Once this merges the queue won't take so long to get through.

**Comment by bparees** [comment]
+1, i might start looking at travis results now..

**Comment by danmcp** [comment]
And the results are in:

1.4: 3min 15s
1.5.1: 5min 47s

And it only uses the available workers which helps.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
Why are we still skipping running gofmt? Also govet against the patches at least would be nice.

**Comment by kargakis** [comment]
> Why are we still skipping running gofmt? Also govet against the patches at least would be nice.

I see we run them for 1.4

**Pull request merged**
