### PR TITLE
reintroduce missing conversions for imagestream kind and lowercase build trigger types

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/3754

### CODE REVIEW

**Comment by liggitt** [comment]
Does this fix https://github.com/openshift/origin/issues/3754?

**Comment by bparees** [comment]
it will when i get the conversion actually working.

**Comment by bparees** [comment]
@deads2k ptal.
[test]

**Comment by deads2k** [comment]
In the `v2` api, will you disallow "ImageStream" as a valid input?

**Comment by deads2k** [comment]
You encountered a pretty painful conversion generator limitation.  Can you either write a unit test that inspects the registered conversions and flags ones that won't function as expected or open an issue to do the same?

otherwise, lgtm.

**Comment by bparees** [comment]
@deads2k yeah we'll probably ban ImageStream (and empty Kind values) in the future.

**Comment by bparees** [comment]
@deads2k i'd definitely rather fix the limitation than add test cases that confirm everyone defines two way converions.  https://github.com/openshift/origin/issues/3897

**Comment by bparees** [comment]
[merge]

**Pull request merged**
