### PR TITLE
favicon.ico not copied during asset build

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett  the ico version of our favicon was never getting included during the build.  I guess its been falling back to the png everywhere in the built console.  Also removed the top favicon.ico and the refs in the grunt server modRewrite because that one is never referenced (we use the one underneath images)

FYI @sg00dwin

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
@spadgett noticed i dont get a diff that i deleted the top level favicon.ico do you have that one locally?

**Comment by spadgett** [comment]
> noticed i dont get a diff that i deleted the top level favicon.ico do you have that one locally?

I'll test.

**Comment by spadgett** [comment]
```
➜  find . -name '*.ico'
./assets/app/favicon.ico
./assets/app/images/favicon.ico
...
```

**Comment by spadgett** [comment]
```
➜  app git:(master) rm favicon.ico
➜  app git:(master) ✗ g status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    favicon.ico
```

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
