### PR TITLE
OCPBUGS-2927: [release-4.12] Bump kubernetes to latest release-4.12

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes https://issues.redhat.com/browse/OCPBUGS-2927

### CODE REVIEW

**Comment by vrutkovs** [comment]
>Status code: 502 for http://base-4-12-rhel8.ocp.svc/rhel-8-appstream/repodata/ce862aa1763c7a2e01d8e0c5cdeac950aef325fde5d3ee439f2c9aaf82135a5f-comps.xml

/retest

**Comment by vrutkovs** [comment]
/hold

Also needs https://github.com/openshift/library-go/pull/1437

**Review by soltysh — APPROVED** [review]
/approve

**Comment by vrutkovs** [comment]
/hold cancel

all required tests passed

**Comment by dgoodwin** [comment]
Confirmed all three bumped dependencies match the latest commits on their respective branches.

/lgtm

**Pull request merged**
