### PR TITLE
Expose /apis/metrics/ on the master as a passthrough to Heapster

### PR DESCRIPTION
**Pull request by smarterclayton**
Exposed to allow development against a "real" metrics service endpoint.
Emulates behavior that will be provided through the endpoint aggregator.

Requires access to the various metrics endpoints as the user.

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Note that we can't remap the group without also rewriting responses.

**Comment by liggitt** [comment]
why not actually register the api group and type, and do the proxying weirdness in the rest handler for that type? I don't like the violence being done to `StartAPI`

**Comment by deads2k** [comment]
> why not actually register the api group and type, and do the proxying weirdness in the rest handler for that type? I don't like the violence being done to StartAPI

I haven't looked into this pull, but as I recall the impl, this is doing an escalation against heapster somewhere down the chain and doing that and claiming the actual kube name worried me.

**Comment by smarterclayton** [comment]
Yeah this is primarily to pre-enable metrics as it will actually (almost)
be exposed for end users to start testing and debugging.  It can be
disabled by an admin by denying auth so we have an easy out.  API
registration doesn't work because heapster is our first "proto" registered
API server, but doesn't do innate auth (it does delegated auth).  This code
makes origin master the auth delegator (so if auth is broken we have bigger
problems), but does *not* overlay (as david has requested) into the correct
group name so that in the future we can just remove this and selectively
enable metrics.

**Comment by liggitt** [comment]
> API registration doesn't work because heapster is our first "proto" registered API server, but doesn't do innate auth (it does delegated auth). 

What do you mean by that? Why can't the same proxy stuff be done inside a REST handler?

**Comment by smarterclayton** [comment]
Heapster today (exposing v1alpha1 metrics) does not do authz inside its
package.  OpenShift master *does* in front of /api/.  This PR does that in
/apis/alpha.metrics.k8s.io/* as well.

I don't think the REST handler is more correct of a path - the scenario
here is api federation but without the authz being delegated to the
backend.  So to reduce the risk that we'd have a back compat challenge when
federation lands, we remap the group from metrics->alpha.metrics.k8s.io and
do not register it in discovery.

**Comment by smarterclayton** [comment]
I crave alternative workarounds that are as minimal and as easy to remove in the future.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Just going to punt on this for now.  @derekwaynecarr  is going to add a card to his board to add authz to heapster so it can participate.

**Pull request closed without merging**
