### PR TITLE
[DO NOT MERGE] Find etcd hang

### PR DESCRIPTION
**Pull request by deads2k**
[test]

### CODE REVIEW

**Comment by deads2k** [comment]
@danmcp `/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 28: openshift: command not found` https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8213/console

In case you're still chasing it.

**Comment by deads2k** [comment]
@danmcp another infrastructure one I've not seen before:

```
Warning: Permanently added '52.90.123.233' (ECDSA) to the list of known hosts.
remote: error: unable to create temporary file: File exists        
remote: fatal: failed to write object        
error: unpack failed: unpack-objects abnormal exit
To verifier:/data/src/github.com/openshift/origin-bare

```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8211/console

**Comment by deads2k** [comment]
This https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8235/artifact/origin/artifacts/e2e/logs/container-origin.log indicates that sometimes we recover (pop the value of the channel for the request) in 10 seconds and sometimes we don't.  However, when we recover, it happens all at once.

```
2016-01-06 20:44:40.105954 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851670
2016-01-06 20:44:44.886962 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851686
2016-01-06 20:44:45.261729 I | etcdserver: #### Eventual success! for 9822940875676851670
2016-01-06 20:44:45.262195 I | etcdserver: #### Eventual success! for 9822940875676851686
2016-01-06 20:44:54.994505 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851929
2016-01-06 20:45:02.015316 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851953
2016-01-06 20:45:04.650957 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851971
2016-01-06 20:45:04.994731 I | etcdserver: #### STILL TIMED OUT! for 9822940875676851929
2016-01-06 20:45:11.021531 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676851979
2016-01-06 20:45:12.015480 I | etcdserver: #### STILL TIMED OUT! for 9822940875676851953
2016-01-06 20:45:14.651166 I | etcdserver: #### STILL TIMED OUT! for 9822940875676851971
2016-01-06 20:45:18.041536 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676852019
2016-01-06 20:45:20.677742 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676852057
2016-01-06 20:45:21.021746 I | etcdserver: #### STILL TIMED OUT! for 9822940875676851979
2016-01-06 20:45:23.298727 I | etcdserver: #### Eventual success! for 9822940875676852019
2016-01-06 20:45:23.298831 I | etcdserver: #### Eventual success! for 9822940875676852057
2016-01-06 20:45:55.927170 I | etcdserver: #### FAILED ON TIMEOUT! for 9822940875676853543
2016-01-06 20:46:02.492942 I | etcdserver: #### Eventual success! for 9822940875676853543

```

**Comment by deads2k** [comment]
@danmcp Not all logs are showing up in the jenkin's artifact view.  When e2e runs, it creates a container called "origin".  The log collection should be gathering it like this: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8292/artifact/origin/artifacts/e2e/logs/  .  Instead, I have a lot of runs where it is missing like this: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8305/artifact/origin/artifacts/e2e/logs/ .

Where can I find the settings that do the artifact collection?  I'll add debugging to the container log dumping script too, but I know we've had trouble with collection in general.

**Comment by danmcp** [comment]
@deads2k https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/download_artifacts_origin.rb

**Comment by deads2k** [comment]
When things go badly, we slow down in this branch of this method.  I've added tracing to try to tighten the ranges.  Its not `apply`.

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/server.go#L434-L486

**Comment by deads2k** [comment]
@liggitt

**Comment by deads2k** [comment]
We're stuck somewhere in these lines: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/raft.go#L158-L171 because server.go isn't writing to the channel and gets blocks writing to done

**Comment by deads2k** [comment]
its in here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/raft.go#L158-L168

**Comment by deads2k** [comment]
see: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8332/artifact/origin/artifacts/e2e/logs/container-origin.log

**Comment by deads2k** [comment]
This method sometimes gets really slow: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go#L481-L509

**Comment by deads2k** [comment]
It's this method call here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go#L505  as pulled from this log here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8346/artifact/origin/artifacts/e2e/logs/container-origin.log

**Comment by bparees** [comment]
@danmcp this comment is a lie:
https://github.com/openshift/origin/pull/6542#issuecomment-170058536

the job it lists actually failed (because i was updating the vagrant plugin)

**Comment by bparees** [comment]
@deads2k you're going to want to re-test this PR, but i don't want to touch things until @danmcp can take a look at why it marked the test as successful.

**Comment by deads2k** [comment]
> @deads2k you're going to want to re-test this PR, but i don't want to touch things until @danmcp can take a look at why it marked the test as successful.

@bparees I'm manually kicking jobs.  That really confuses the comments in this pull.

**Comment by bparees** [comment]
@deads2k ah, ok.

**Comment by deads2k** [comment]
Alright, we've gotten it narrowed down to this line: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go#L392.  Sometimes (in this run, once per 600 calls) it takes about 4000 times longer than normal.  Instead of 9 milliseconds, it takes 35 seconds.  There are other less severe "pauses" in the log on this line too.

Based on other logging in the file, we're never writing more than 1 meg at a time, so that sort of pause is crazy.

At this point, I'm stuck.  I don't understand why the write characteristics would change so dramatically.

@liggitt @danmcp @smarterclayton @vbatts I don't know what to do next.  

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8360/artifact/origin/artifacts/e2e/logs/container-origin.log

```
I0108 18:12:44.991885   16029 tracker.go:103] #### InspectionPoint wal.sync.sync.635 (<nil>) took 34.416856046 seconds instead of about 0.009141104 from
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/wal/tracker.go:79 (0x1889d31)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go:399 (0x188e59a)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go:542 (0x188fba9)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/raft.go:186 (0x11dadd0)
/usr/lib/golang/src/runtime/asm_amd64.s:2232 (0x440441)

I0108 18:12:44.991984   16029 tracker.go:103] #### InspectionPoint wal.save.sync.634 (writing 2 entries for term=2, vote=1231859792466236092, commit=719, size=15) took 34.417077631 seconds instead of about 0.009247741 from
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/wal/tracker.go:79 (0x1889d31)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/wal/wal.go:540 (0x188f897)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/raft.go:186 (0x11dadd0)
/usr/lib/golang/src/runtime/asm_amd64.s:2232 (0x440441)

I0108 18:12:44.992048   16029 tracker.go:103] #### InspectionPoint raft.save.634 (writing 2 entries for term=2, vote=1231859792466236092, commit=719, size=15) took 34.417375708 seconds instead of about 0.009686583 from
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/tracker.go:79 (0x11ec3f1)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/raft.go:183 (0x11daa24)
/usr/lib/golang/src/runtime/asm_amd64.s:2232 (0x440441)

```

**Comment by smarterclayton** [comment]
Kind of sounds like underlying filesystem iops starvation.  @twiest can you
tell us how to figure out what IOP starvation looks like on EC2 to ensure
that's not the case?

Is a snapshot running?

**Comment by deads2k** [comment]
> Is a snapshot running?

I don't think so. 
```
[deads@deads-dev-01 origin]$ grep "snapshot" container-origin.log.6
2016-01-08 18:10:11.756646 I | etcdserver: snapshot count = 0
2016-01-08 18:10:11.766865 I | etcdserver: set snapshot count to default 10000
```

**Comment by liggitt** [comment]
> Is a snapshot running?

No, happens well separated from snapshots (I've seen it around etcd index 7500, for example)

**Comment by twiest** [comment]
> Kind of sounds like underlying filesystem iops starvation.  @twiest can you
tell us how to figure out what IOP starvation looks like on EC2 to ensure
that's not the case?

What we do is we use `iostat -x /dev/vol 1` and we look at the %util. If it's at 100%, then all iops are being utilized.

You can also double check that with `iostat /dev/vol 1` and look at the TPS and compare that to the number you expect. It will be around the total number of iops, but probably not exactly it.

**Comment by deads2k** [comment]
> What we do is we use iostat -x /dev/vol 1 and we look at the %util. If it's at 100%, then all iops are being utilized

@stevekuznetsov plan on this as a follow-up to the SAR stats.

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8754 is weird.

```bash
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 3"
e2e/logs/etcd.log:I0118 13:40:54.742965   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12354 (<nil>) took 3.313391774 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:40:54.743026   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12350 (writing 6 entries for term=2, vote=4287051779525723081, commit=13671, size=15) took 3.3140381740000002 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:40:54.743052   21114 tracker.go:103] #### InspectionPoint raft.save.12351 (writing 6 entries for term=2, vote=4287051779525723081, commit=13671, size=15) took 3.316313584 seconds instead of about 0.010280002 from
e2e/logs/etcd.log:I0118 13:40:58.225986   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12355 (<nil>) took 3.479649672 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:40:58.226033   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12351 (writing 7 entries for term=2, vote=4287051779525723081, commit=13678, size=15) took 3.480501992 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:40:58.226047   21114 tracker.go:103] #### InspectionPoint raft.save.12352 (writing 7 entries for term=2, vote=4287051779525723081, commit=13678, size=15) took 3.482563918 seconds instead of about 0.010280002 from
e2e/logs/etcd.log:I0118 13:41:09.024015   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12357 (<nil>) took 3.725290284 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:41:09.024054   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12353 (writing 11 entries for term=2, vote=4287051779525723081, commit=13694, size=15) took 3.726141701 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:41:09.024067   21114 tracker.go:103] #### InspectionPoint raft.save.12354 (writing 11 entries for term=2, vote=4287051779525723081, commit=13694, size=15) took 3.729033993 seconds instead of about 0.010280002 from
e2e/logs/etcd.log:I0118 13:41:20.612008   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12361 (<nil>) took 3.750288434 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:41:20.612071   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12357 (writing 2 entries for term=2, vote=4287051779525723081, commit=13700, size=15) took 3.750922108 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:41:20.612089   21114 tracker.go:103] #### InspectionPoint raft.save.12358 (writing 2 entries for term=2, vote=4287051779525723081, commit=13700, size=15) took 3.753561758 seconds instead of about 0.010280002 from
e2e/logs/etcd.log:I0118 13:41:23.941658   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12362 (<nil>) took 3.32593144 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:41:23.941702   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12358 (writing 3 entries for term=2, vote=4287051779525723081, commit=13703, size=15) took 3.326565932 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:41:23.941714   21114 tracker.go:103] #### InspectionPoint raft.save.12359 (writing 3 entries for term=2, vote=4287051779525723081, commit=13703, size=15) took 3.329103237 seconds instead of about 0.010280002 from
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 4"
e2e/logs/etcd.log:I0118 13:41:16.858045   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12360 (<nil>) took 4.326641935 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:41:16.858089   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12356 (writing 2 entries for term=2, vote=4287051779525723081, commit=13698, size=15) took 4.327538719 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:41:16.858101   21114 tracker.go:103] #### InspectionPoint raft.save.12357 (writing 2 entries for term=2, vote=4287051779525723081, commit=13698, size=15) took 4.330276044 seconds instead of about 0.010280002 from
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 5"
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 6"
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 7"
e2e/logs/etcd.log:I0118 13:41:05.294573   21114 tracker.go:103] #### InspectionPoint wal.sync.sync.12356 (<nil>) took 7.064592854 seconds instead of about 0.006630209000000001 from
e2e/logs/etcd.log:I0118 13:41:05.294618   21114 tracker.go:103] #### InspectionPoint wal.save.sync.12352 (writing 5 entries for term=2, vote=4287051779525723081, commit=13683, size=15) took 7.065476479 seconds instead of about 0.007452005 from
e2e/logs/etcd.log:I0118 13:41:05.294638   21114 tracker.go:103] #### InspectionPoint raft.save.12353 (writing 5 entries for term=2, vote=4287051779525723081, commit=13683, size=15) took 7.068182567 seconds instead of about 0.010280002 from
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 8"
[deads@deads-dev-01 test-without-ramdisk-01]$ grep -r "####" * | grep "took 9"
```

This all suggests that something happened between 13:40 and 13:42.  During that time, the queue.pdf indicates that the "blocked" category grew, but the runq-sz is low.  iops.pdf shows higher bwrtn/s, but 100kb/s is hardly "high" and the overall writes per second aren't super high.

**Comment by stevekuznetsov** [comment]
@deads2k FYI the `%util` data is in the `sar.log`. You could download the log and use `sar -d -f <file>` to get that data. I'll add it to the logging PR as well if you want to pull in a new commit.

**Comment by deads2k** [comment]
Testing an insane theory; this is the last one I've got.  What if we're not assigned our entire local disk upon the ec2 image provision?  What if sometimes the backing storage isn't ready and they silently increase our allocation?  It would probably be invisible in most circumstances, but a sync would mean "wait for guarantee of persistence" that they respect and causes etcd to wait.

This would explain why after cleaning up, we can't reproduce the problem.  It would explain why it happens at about the same spot every time.  It would explain why we hit this condition with very few iops.  The only problem is that its a pretty crazy theory.  I've added a `dd` to allocate and then remove a large file to try to reserve the space.

**Comment by deads2k** [comment]
@liggitt Tremendous improvement.  No more problems in test-integration or test-cmd.  Some problems in test-e2e, but all of it below the 5 second timeout threshold.  Looks like I have my tomorrow work.

@pweil- @danmcp If this works in the actual queue, I'm pretty sure this it's worth "immunity to all flakes for the next release" :)

**Comment by deads2k** [comment]
BEST FLAKE EVER!

**Comment by smarterclayton** [comment]
I think this just happened again for me

**Pull request closed without merging**
