### PR TITLE
update version change to handle lists

### PR DESCRIPTION
**Pull request by deads2k**
Update version change to handle `api.List`.

@mfojtik I think I saw you in this code (or at least using it) a while back.  ptal.

### CODE REVIEW

**Comment by smarterclayton** [comment]
I thought this merged in a  different change

**Comment by deads2k** [comment]
> I thought this merged in a different change

It hasn't yet.  I thought it would be useful in general, but it's included in #2611 if that gets in quickly.

**Comment by deads2k** [comment]
someone else must have found it.

**Comment by mfojtik** [comment]
@soltysh beat you to it

**Comment by soltysh** [comment]
Yup, it was just merged in #2653.

**Pull request closed without merging**
