### PR TITLE
Refactor startbuild cli cmd and create new unit tests

### PR DESCRIPTION
**Pull request by guilhermebr**
Refactor StartBuild command based on openshift cmd guidelines and added new test.

This PR have parts subtracted from #11290 to make the PR more clean.

### CODE REVIEW

**Comment by guilhermebr** [comment]
@openshift/cli-review

**Comment by pweil-** [comment]
@openshift/cli-review

**Comment by juanvallejo** [comment]
[test]

**Comment by fabianofranz** [comment]
@csrwng PTAL

**Pull request closed without merging**
