### PR TITLE
UPSTREAM: 84561: FIPS changes for passing unit tests

### PR DESCRIPTION
**Pull request by rphillips**
`GOLANG_FIPS=1 make test-unit`with the FIPS `go-1.12.12-2-openssl-fips` compiler will pass after these changes.

* Bumps a few test certificates to get unit tests passing.
* GCM 24 is not FIPS certified, so that test is disabled.

What is somewhat surprising is the jose error is not captured within the unit tests.

upstream ref: https://github.com/kubernetes/kubernetes/pull/84561

### CODE REVIEW

**Comment by mrunalp** [comment]
@sttts fyi.

**Comment by sttts** [comment]
Looks good. Please open the same PR upstream, with the exception of the k8s.io/apiserver/pkg/storage/value/encrypt/aes/aes_test.go change maybe.

**Comment by sttts** [comment]
the commit msg must then be `UPSTRAM: 12345: ...`

**Comment by rphillips** [comment]
upstream https://github.com/kubernetes/kubernetes/pull/84561

**Comment by sttts** [comment]
Don't forget to change the commit message here with the PR number.

**Pull request merged**
