### PR TITLE
add some optimizations to build code

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by guangxuli** [comment]
@soltysh ptal, thanks!

**Comment by soltysh** [comment]
Builds are @bparees field

**Comment by bparees** [comment]
not looking at this until 3.3 ships.

**Comment by bparees** [comment]
@guangxuli you didn't have to close this, we're just not going to have a chance to review/merge it until 3.3 is done.

**Comment by guangxuli** [comment]
sorry, @bparees, I made a wrong understand, and I had not look this message util this time. I wil recreate a PR. thanks.

**Pull request closed without merging**
