### PR TITLE
Changing quickstart credentials to secrets

### PR DESCRIPTION
**Pull request by jupierce**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1233513

@bparees Should this go beyond quickstarts? Jenkins templates? All examples?

### CODE REVIEW

**Comment by jupierce** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
> @bparees Should this go beyond quickstarts? Jenkins templates? All examples?

quickstarts, db-templates, and jenkins should probably all be done.  Actually jenkins shouldn't have any passwords in it anymore.

**Comment by bparees** [comment]
@jupierce the quickstarts directory is updated via script, you need to update the files in their original repos and then run the hack/update-external-examples.sh script.  (see the readme in the quickstarts directory, though it should be fixed to say "do not modify/add files to this directory" instead of just "Do not add files to this directory")

**Comment by bparees** [comment]
@jwforres fyi

**Comment by jupierce** [comment]
WIP until:
openshift/cakephp-ex#48
openshift/dancer-ex#51
openshift/django-ex#67
openshift/nodejs-ex#75
openshift/rails-ex#71

**Comment by jupierce** [comment]
Quickstarts have now been synched with hack script.

**Comment by bparees** [comment]
lgtm, will wait on extended tests to finish.

**Comment by bparees** [comment]
@jupierce the mongo petset replication failure is a new one.

**Comment by jupierce** [comment]
@bparees I've been looking at it, but that test doesn't even use the modified templates. It uses: https://raw.githubusercontent.com/sclorg/mongodb-container/master/examples/petset/mongodb-petset-persistent.yaml

As best I can tell, the cause is:
```
Nov 30 13:08:54.128: INFO: At 2016-11-30 13:06:54 -0500 EST - event for mongodb-replicaset-0: {default-scheduler } FailedScheduling: SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "mongo-data-mongodb-replicaset-0", which is unexpected.
```

**Comment by bparees** [comment]
@jupierce hm.  may well be a flake i suppose.

**Comment by jupierce** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
back to the known failure.  merging w/ your additional petset debug changes.
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11887
[merge]

**Comment by jupierce** [comment]
Incorporating changes for #12075

**Comment by bparees** [comment]
[merge]

**Pull request merged**
