### PR TITLE
UPSTREAM: 37380: Improve error reporting in Ceph RBD provisioner

### PR DESCRIPTION
**Pull request by jsafrane**
@childsb @rootfs, PTAL

### CODE REVIEW

**Comment by jsafrane** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1395547

**Comment by jsafrane** [comment]
[test]

**Comment by rootfs** [comment]
LGTM thanks!

**Comment by childsb** [comment]
[test]

**Comment by childsb** [comment]
[merge]

**Pull request merged**
