### PR TITLE
enforce server version requirement for service catalog

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/14762

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal.  I *think* based on the way we've versioned releases historically, all pending releases will be higher than `3.6.0-alpha2` (and locally built images today will be `v3.6.0-alpha.2+b70d790-379-dirty` (modulo the commitid) which again is higher than 3.6.0-alpha2)

**Comment by bparees** [comment]
```
Error: Enabling the service catalog requires a server level of 3.6.0-alpha.2 or above, this server is version 3.6.0-alpha.2+261feaa-380-dirty
```

hm. investigating.

**Comment by bparees** [comment]
ugh.  semver treats the commit as the "build" and doesn't treat build as relevant for ordering.

**Comment by csrwng** [comment]
@bparees is there anything we can check on the server itself instead of looking at a version number? For example try to hit a known group api endpoint?

**Comment by bparees** [comment]
ok added some hackery that should handle the "i'm building locally on top of alpha.2 and i've probably already got the fixes needed" case.

once we cut alpha.3, we can probably just prereq alpha.3 or above and call it a day.

**Comment by bparees** [comment]
not if we're just trying to understand the policybinding requirement/non-requirement.  nothing about the api changed other than whether you can create a rolebinding when a policybinding hasn't been created, as far as i know.

**Comment by csrwng** [comment]
ic, got it

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge][severity:blocker]

**Comment by bparees** [comment]
@csrwng in hindsight i wonder if this is going to prevent this from being used with OCP.  we may be a bit stuck here.  I'm somewhat inclined to just require 3.6+ and deal w/ the fact that until we ship a new 3.6 release, it won't work for people using the released images.  (and of course even after we ship a new 3.6, it won't work if you go back and use the alpha).  wdyt?

Adding more special casing for OCP vs Origin isn't very appealing.

**Comment by csrwng** [comment]
We don't have a pre-release portion with the OCP version, so I don't think the code as is would cause problems. My inclination would be to leave as is unless we know it's broken.

**Comment by bparees** [comment]
> We don't have a pre-release portion with the OCP version, so I don't think the code as is would cause problems. My inclination would be to leave as is unless we know it's broken.

I was assuming the -pre would be treated as later than w/o the pre (since it is a longer string), but it looks like semver treats 3.6.0 as coming after 3.6.0-alpha2 (which makes sense given that it's a pre-release) so i think we are ok.

**Pull request merged**
