### PR TITLE
UPSTREAM: 76455: Fix flakes in HPA tests

### PR DESCRIPTION
**Pull request by joelsmith**
See https://bugzilla.redhat.com/show_bug.cgi?id=1695807
and the upstream PR https://github.com/kubernetes/kubernetes/pull/76455

### CODE REVIEW

**Comment by joelsmith** [comment]
retest didn't trigger. Closing and re-opening to see if that will do it.

**Comment by joelsmith** [comment]
I'm going to have the unit test run as many times as possible 
/test unit

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
I'm a script re-running unit tests during the night, plus retrying any failed tests
/test unit
/retest

**Comment by joelsmith** [comment]
Even doing many runs of the unit test CI job the flake hasn't popped up (see https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/pull/22531/pull-ci-openshift-origin-master-unit/ where none of the flakes were this one).

Seth, could you please review this? Clayton, are we okay to merge this and will you be reworking #22527?

/assign @sjenning 
/cc @smarterclayton

**Comment by joelsmith** [comment]
As suggested by @RobertKrawitz, changed to only write to the chan while not holding the lock. This should make it impossible to hit the kind of deadlock we were seeing before.

**Comment by RobertKrawitz** [comment]
After discussion in slack,
/lgtm

**Comment by joelsmith** [comment]
I squashed and changed the commit message to reference the upstream PR https://github.com/kubernetes/kubernetes/pull/76455

**Pull request merged**
