### PR TITLE
Extend NodeConfig to support other container runtimes

### PR DESCRIPTION
**Pull request by slp**
This allows us instructing kubelet to use a specific container runtime.

### CODE REVIEW

**Comment by smarterclayton** [comment]
We can already do this through the kubeletArguments.  Don't add new top level flags that are pure kubelet arguments.

**Comment by smarterclayton** [comment]
Did you have an issue with using kubeletArguments?

**Comment by slp** [comment]
@smarterclayton IMHO those arguments are critical, and it's better to have them parsed and validated locally, in the same way as we already do with DockerConfig, among others.

Also, this makes easier using them as flags, so you can run something like:

```
openshift start --container-runtime=remote --remote-runtime-endpoint=unix:///var/log/crio.sock --remote-image-endpoint=unix:///var/log/crio.sock
```

That said, I'm pretty new to OpenShift internals, so if I'm wrong or there's a better way to do this, please let me know.

**Comment by enj** [comment]
We use config files for almost all configuration params.  Let's not make these special snowflakes.

**Comment by slp** [comment]
@enj Do you disagree about extending NodeConfig, having the options as flags, or both?

About having them as flags, while I can totally understand not wanting to add one for every option, I think in this is case is justified, as it facilitates running OpenShift with an alternative runtimes (like CRI-O). You'd just need to grab the container image, and run it with the proper arguments.

Also, choosing a container runtime is a pretty important option. Why would it be less justified having a flag for it than having one for, let's say, "recursive-resolv-conf"?

**Comment by enj** [comment]
My suggestion is the same as Clayton's: use `KubeletArguments` for all parameters that have a 1:1 mapping with kube.  So, do not extend node config and do not add flags.

> it facilitates running OpenShift with an alternative runtimes (like CRI-O). You'd just need to grab the container image, and run it with the proper arguments.

Editing a config file is not hard.

> Also, choosing a container runtime is a pretty important option

Which we would configure through ansible + the node config file.

> Why would it be less justified having a flag for it than having one for, let's say, "recursive-resolv-conf"?

Probably because the argument does not exist in kube?

**Comment by slp** [comment]
> Editing a config file is not hard.

> Which we would configure through ansible + the node config file.

Both options are quite impractical for the user that intends to run a containerized instance of OpenShift for development purposes.

> Probably because the argument does not exist in kube?

We also have DockerExecHandlerName and DockerShimSocker, and I'm pretty sure kube also has an argument for each one of those.

**Comment by enj** [comment]
> Both options are quite impractical for the user that intends to run a containerized instance of OpenShift for development purposes.

I fail to see how making a change to a config file is hard.

> We also have DockerExecHandlerName and DockerShimSocker, and I'm pretty sure kube also has an argument for each one of those.

Seems like a mistake on our part.

---

This does not warrant a command line flag.  So no matter what you have to edit a config file.  Thus you do not gain much even if you do add fields to node config.

**Comment by slp** [comment]
> I fail to see how making a change to a config file is hard.

It's not hard on a full deployment. But if you intend to run OpenShift in a container, as described [here](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container), it's quite a nuisance. It pretty much kills the user experience.

**Comment by smarterclayton** [comment]
That's why we have oc cluster up, which has provisions for editing the
config.

**Comment by slp** [comment]
> That's why we have oc cluster up, which has provisions for editing the config.

OK, so let's forget about running the OpenShift container manually (and the contents of this PR) and focus on using "oc cluster up". Right now, this command requires Docker.

Would a PR for implementing the possibility of bootstrapping with an alternative CR be eventually accepted? Is it too big a change and would be better to discuss the details of its implementation first? If so, where should it be discussed, on a GH Issue or on the mailing list?

**Comment by smarterclayton** [comment]
It's a big change, it's definitely a discussion. Bringing it up on the
mailing list or in an issue to describe the use case and to talk about the
design intent and goals of cluster up.  It's going to be complicated
because cluster up is about a zero effort single node install using docker,
but the future might involve it being a tool that helps to quickly install
clusters and has a way to perform advanced installs.

To run manually today, you'd generate a config (using the --write-config
flag on openshift start), edit the config to set the runtime, and then
start it using the --master-config and --node-config flags.  You don't need
docker for that.

On Aug 30, 2017, at 3:02 AM, Sergio López <notifications@github.com> wrote:

That's why we have oc cluster up, which has provisions for editing the
config.

OK, so let's forget about running the OpenShift container manually (and the
contents of this PR) and focus on using "oc cluster up". Right now, this
command requires Docker.

Would a PR for implementing the possibility of bootstrapping with an
alternative CR be eventually accepted? Is it too big a change and would be
better to discuss the details of its implementation first? If so, where
should it be discussed, on a GH Issue or on the mailing list?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/16031#issuecomment-325901478>,
or mute
the thread

**Comment by smarterclayton** [comment]
You can also just use this issue to describe what use case you want to
make easy and we can discuss here.

**Comment by slp** [comment]
@smarterclayton The leifmotiv was making OpenShift as independent as possible from Docker/Moby. A possible first milestone would've been making it easy to use it with a CRI-based runtime on both full deployments, as well as in minimal, single-node installations for developers.

I see oc/boostrap seems to be pretty well modularized. But, on a second thoutght, it's probably not worth the effort.

I'm closing this. Thanks for your answers and sorry for the noise.

**Pull request closed without merging**
