### PR TITLE
Update README with the dynamic endpoint/service creation

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs @jsafrane PTAL .

**Comment by jsafrane** [comment]
[test]

**Comment by humblec** [comment]
[test]

**Comment by eparis** [comment]
[test]  i'm leaning towards not taking this PR. customers shouldn't be looking in there. openshift docs are more important to our customers...

**Comment by humblec** [comment]
iic, we need to set the milestone to 1.4 as this is part of glusterfs dynamic provisioner feature.

**Comment by liggitt** [comment]
Agree. Upstream picks of docs aren't necessary

**Comment by eparis** [comment]
Please review the openshift docs and make sure those are correct. I think we have enough churn that I'm going to close this issue. Thank you, and sorry!

**Pull request closed without merging**
