### PR TITLE
UPSTREAM:9870: PV Recycler config

### PR DESCRIPTION
**Pull request by markturansky**
@pweil-  @deads2k 

I applied both upstream PRs in a single commit.  I originally had 2 but the 2nd (9870) was changing some of the edits from 12063.  

There will, unfortunately, be a 3rd PR to add to this functionality due to upstream request for smaller PRs to make VolumeConfig digestible.  I can keep them up to date in a Kube branch (last rebased version) and apply them as a single patch into OS until it's entirely merged upstream.

### CODE REVIEW

**Comment by deads2k** [comment]
I'd prefer to have one commit per upstream pull request.  Also, please rename the reverts to "UPSTREAM: revert <old commit hash>: <upstream number>: description".  That makes them come back in our normal upstream log check during the rebase.

**Comment by markturansky** [comment]
@deads2k will do.  I don't think it patched correctly anyway.  Also need to grab the 3rd PR for this ... :/

**Comment by markturansky** [comment]
@deads2k @pweil-  Re-patched as individual commits.

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
jenkins failures:
```
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume	0.028s	coverage: 17.0% of statements
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cephfs
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs_test.go:39: unknown volume.Spec field 'Name' in struct literal
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs_test.go:42: unknown volume.Spec field 'Name' in struct literal
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/aws_ebs	0.042s	coverage: 30.3% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cephfs [build failed]
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/empty_dir	0.042s	coverage: 69.5% of statements
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/gce_pd	0.046s	coverage: 26.7% of statements
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/git_repo	0.034s	coverage: 72.1% of statements
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/host_path
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go:182: cannot use nil as type volume.VolumeConfig in argument to ProbeVolumePlugins
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/glusterfs	0.033s	coverage: 65.7% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/host_path [build failed]
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/iscsi	0.031s	coverage: 40.8% of statements
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/nfs
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/nfs/nfs_test.go:241: cannot use nil as type volume.VolumeConfig in argument to ProbeVolumePlugins
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/metadata	0.059s	coverage: 72.9% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/nfs [build failed]
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/persistent_claim	0.039s	coverage: 70.4% of statements
```

**Comment by rhcarvalho** [comment]
This is blocking QE on some Trello cards that depend on PVs and PVCs:
- https://trello.com/c/CgbBR2Sj
- https://trello.com/c/ZNMI7j81

Any ETA on when this might get merged? I'm particularly interested in this line https://github.com/openshift/origin/pull/4384/files#diff-d5743d081660f6153bf9bd1b5b0c0e0bR59 on secrets.go

**Comment by deads2k** [comment]
I'm fine with it, once the tests pass.

**Comment by markturansky** [comment]
Fixing the tests now

**Comment by deads2k** [comment]
@markturansky  take a look at the jenkins failure, see if its a flake, and if so find or open an issue. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4705/

[merge] guessing that it is a flake

**Comment by markturansky** [comment]
The same test failed in both Jenkins test/merge queues.  It is the same one found here: https://github.com/openshift/origin/issues/4468

**Comment by deads2k** [comment]
> The same test failed in both Jenkins test/merge queues. It is the same one found here: #4468

Can you take a deeper look?  Based on the neighboring jobs, it looks like this is a problem with this pull.

**Comment by markturansky** [comment]
Unrelated flake in just 1 of Travis' 2 builds:  `TestRequestExecuteRemoteCommand`   Not related to volumes.

12603 & 13310 just got merged upstream.  The commits on this PR are accurate.  The 3rd (9870) might need to be repatched based on upstream feedback as it gets more closely reviewed.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
