### PR TITLE
OCPBUGS-44257:fixing build s2i ruby test data inline with latest ruby version(>=3.0)

### PR DESCRIPTION
**Pull request by prabhapa**
**OCPBUGS-44257:fixing build s2i ruby test data inline with latest ruby version(>=3.0)**

The test data for s2i image creation with source type as binary has issues post base image upgrade to ruby 3.0 (test/extended/testdata/builds/test-env-build.json) This is because webrick server is removed from default ruby libraries from 3.0 version,hence a webserver should be installed externally.The test data is missing this causing permanant failure post ruby 3.0 upgrade.

This fix is updating the test data with required dependencies to create a stable app to fulfill the testcase criteria.

signed-off by : prabhakar(ppalepu@redhat.com)

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

@Moebasim @prabhapa as a follow up, I recommend submitting a pull request to add your GitHub IDs to the following OWNERS files as approvers. This will grant you permission to `/approve` pull requests for these parts of the repo.

- https://github.com/openshift/origin/blob/master/test/extended/builds/OWNERS
- https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/OWNERS

**Comment by prabhapa** [comment]
closing this in favour of #29355

**Pull request closed without merging**
