### PR TITLE
clean up cluster up loglevel 1

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees if we're leaving log level 1 only for reporting progress, we should fix these other ones:

```
$ find ./pkg/oc/bootstrap -name "*.go" | xargs grep -F "V(1)."
./pkg/oc/bootstrap/docker/dockerhelper/helper.go:		glog.V(1).Infof("Error getting container %q log: %v", container, err)
./pkg/oc/bootstrap/docker/down.go:		glog.V(1).Infof("error: cannot kill socat: %v", err)
./pkg/oc/bootstrap/docker/down.go:		glog.V(1).Infof("Error stopping origin container: %v", err)
./pkg/oc/bootstrap/docker/down.go:			glog.V(1).Infof("Error stopping container %s: %v", name, err)
./pkg/oc/bootstrap/docker/down.go:			glog.V(1).Infof("Error removing container %s: %v", name, err)
./pkg/oc/bootstrap/docker/errors/errors.go:	glog.V(1).Infof("Unexpected error: %v", err)
./pkg/oc/bootstrap/docker/openshift/ansible.go:	glog.V(1).Infof("Wrote inventory to local file: %s", file.Name())
./pkg/oc/bootstrap/docker/openshift/ansible.go:	glog.V(1).Infof("Uploading file %s to host destination: %s", file.Name(), dest)
./pkg/oc/bootstrap/docker/openshift/ansible.go:		glog.V(1).Infof("Generated ansible inventory:\n %s\n", inventory.String())
./pkg/oc/bootstrap/docker/openshift/ansible.go:		glog.V(1).Infof("Running image %s with playbook: %s", image, playbook)
./pkg/oc/bootstrap/docker/openshift/ansible.go:		glog.V(1).Infof("With binding: %s", configBind)
./pkg/oc/bootstrap/docker/openshift/ansible.go:		glog.V(1).Infof("With binding: %s", inventoryBind)
./pkg/oc/bootstrap/docker/openshift/helper.go:		glog.V(1).Infof("Found more than one node, will attempt to remove duplicate nodes")
./pkg/oc/bootstrap/docker/openshift/helper.go:			glog.V(1).Infof("Deleting extra node %s", nodesToRemove[i])
./pkg/oc/bootstrap/docker/openshift/helper.go:	glog.V(1).Infof("Copying OpenShift config to local directory %s", tempDir)
./pkg/oc/bootstrap/docker/openshift/helper.go:	glog.V(1).Infof("Reading node config from %s", configPath)
./pkg/oc/bootstrap/docker/openshift/helper.go:		glog.V(1).Infof("Could not read node config: %v", err)
./pkg/oc/bootstrap/docker/openshift/helper.go:	glog.V(1).Infof("Reading master config from %s", configPath)
./pkg/oc/bootstrap/docker/openshift/helper.go:		glog.V(1).Infof("Could not read master config: %v", err)
./pkg/oc/bootstrap/docker/openshift/helper_unix.go:		glog.V(1).Infof("error: cannot kill socat: %v", err)
./pkg/oc/bootstrap/docker/openshift/helper_unix.go:	glog.V(1).Infof("Started socat with pid: %d", cmd.Process.Pid)
./pkg/oc/bootstrap/docker/run/run.go:				glog.V(1).Infof("Error deleting container %q: %v", id, err)
./pkg/oc/bootstrap/docker/up.go:		glog.V(1).Infof("Failed to check Docker API version: %v", err)
```

**Comment by bparees** [comment]
@csrwng I didn't remove all the ones you referenced, I think some of them are still useful progress indicators, but, updated.

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/14385
/retest

**Pull request merged**
