### PR TITLE
SNO topology: the oauth-server should only have a single replica now

### PR DESCRIPTION
**Pull request by stlaz**
/assign @romfreiman

### CODE REVIEW

**Comment by stlaz** [comment]
/retest
The test we're looking for seem to have passed (see it in the history)

Retesting for other tests to make this be ready to merge if you want it to.

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by omertuc** [comment]
ci/prow/e2e-aws-serial

**Comment by romfreiman** [comment]
@smarterclayton can u please skip the e2e-aws-single-node and make this pr merged? It cannot pass at this point, but the relevant change did pass.

**Pull request merged**
