### PR TITLE
oc: more status fixes

### PR DESCRIPTION
**Pull request by kargakis**
@deads2k @stevekuznetsov @ramr PTAL

Fixes https://github.com/openshift/origin/issues/7832

@jwforres @spadgett fyi

### CODE REVIEW

**Comment by deads2k** [comment]
Add a unit test, then lgtm.

**Comment by kargakis** [comment]
unit test added

**Comment by deads2k** [comment]
[merge]

**Comment by kargakis** [comment]
@deads2k not sure what failed here. Probably related to the way we now test godeps?
```
Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
!!! Error in hack/test-go.sh:270
	'go test ${gotest_flags} ${test_packages}' exited with status 1
Call stack:
	1: hack/test-go.sh:270 main(...)
Exiting with status 1
make[1]: *** [test-unit] Error 1
```

**Comment by deads2k** [comment]
> @deads2k not sure what failed here. Probably related to the way we now test godeps?

looks like you just forgot to update the test for your new strings.

**Comment by kargakis** [comment]
Hm, must have been blind for a second

**Pull request merged**
