### PR TITLE
update aggregator to match latest kube

### PR DESCRIPTION
**Pull request by deads2k**
This updates openshift to use the latest aggregation APIs.

@liggitt I didn't add comments in the existing groups, since we aren't going to have new versions in openshfit for a while.

### CODE REVIEW

**Comment by deads2k** [comment]
@jpeeler @sdodson @pmorie @derekwaynecarr @bparees @kargakis 

Be aware that the schema for APIService is being bumped to beta and being changed to match the (hopefully) final state in kube 1.7.

**Comment by bparees** [comment]
uh.  so i need to go update all my cluster up stuft to use v1beta1 instead of v1alpha1?

**Comment by sdodson** [comment]
@ewolinetz fyi

**Comment by deads2k** [comment]
> uh. so i need to go update all my cluster up stuff to use v1beta1 instead of v1alpha1?

And you need `groupPriorityMinimum` and `versionPriority` instead of `priority`.

**Comment by bparees** [comment]
@deads2k how soon can we get this in the queue?  i can't put the cluster up PR in the merge queue until this goes in.

**Comment by liggitt** [comment]
@deads2k all the generated.pb.go changes with no accompanying descriptor changes are unexpected. what version of go did you run with? (gzip differences will output different gzipped manifests)

**Comment by liggitt** [comment]
just the question on the generated.pb.go changes, LGTM otherwise

**Comment by deads2k** [comment]
> just the question on the generated.pb.go changes, LGTM otherwise

@liggitt grrrr. Probably 1.8.  Just normal kube env.

**Comment by deads2k** [comment]
reran with 1.7, no changes.

[test]

**Comment by deads2k** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by deads2k** [comment]
@smarterclayton green if you're still manually tending

**Pull request merged**
