### PR TITLE
Replace oadm with oc adm in documentation and code

### PR DESCRIPTION
**Pull request by mfojtik**
Partially fixes: https://github.com/openshift/openshift-docs/issues/1845

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton do we want `oc adm` everywhere?

**Comment by mfojtik** [comment]
@liggitt do we want mix of `oadm` and `oc adm` in various places?

**Comment by smarterclayton** [comment]
I would prefer oadm in any admin documentation for now.

**Comment by mfojtik** [comment]
k, closing this PR, I agree oadm is better for admin documentation.,

**Pull request closed without merging**
