### PR TITLE
Issue #21153 update the console URI not to redirect 127.0.0.1

### PR DESCRIPTION
**Pull request by praveenkumar**
This is what an easy fix we see to make sure the user doesn't affect with #21153 issue from minishift point of view.

cc @mfojtik @deads2k

### CODE REVIEW

**Comment by gbraad** [comment]
LGTM

**Comment by JyotiRani** [comment]
IS this issue fixed? i am still facing this issue with 3.11

**Comment by rplescia** [comment]
Doesn't seem like this has been fixed, I'm still having this issue

**Pull request merged**
