### PR TITLE
[RPMS] Switch requires from docker-io to docker

### PR DESCRIPTION
**Pull request by sdodson**
Per request of Red Hat docker team.

CC: @lsm5

### CODE REVIEW

**Comment by sdodson** [comment]
Note, we'd expect docker in RHEL7/Centos to keep `Provides: docker-io` for the lifetime of RHEL7 or until such a time that OSE 3.1 and OSE 3.0 are EOL'd.

**Comment by tdawson** [comment]
:+1: 
Yes, it's time to do this.

**Comment by sdodson** [comment]
@brenton PTAL

**Comment by brenton** [comment]
[merge]

**Comment by lsm5** [comment]
thanks!!

**Pull request merged**
