### PR TITLE
Bug 1953127: undisable NetworkPolicy tests

### PR DESCRIPTION
**Pull request by danwinship**
Previously #26197; I had closed that because someone else did the rebase from o/k, but I forgot that we still needed the commit fixing rules.go

### CODE REVIEW

**Comment by knobunc** [comment]
/override ci/prow/e2e-gcp-builds
It's perma-failing, and not required...

**Comment by danwinship** [comment]
/skip
(to make prow notice that e2e-gcp-builds is no longer needed)

**Pull request merged**
