### PR TITLE
hypershift, kubevirt: Migrate just one worker

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by davidvossel** [comment]
/hold

we need to see the kubevirt lane pass before removing the hold

**Comment by qinqon** [comment]
Conformance took more than 4h 
`
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2023-10-11T18:26:11Z"}
```

**Pull request closed without merging**
