### PR TITLE
Bug 1873043: Bump to kube 1.19.0

### PR DESCRIPTION
**Pull request by marun**
Required to get e2e-gcp and e2e-aws-fips passing against openshift/kubernetes.

### CODE REVIEW

**Comment by mfojtik** [comment]
/retest

looks like upgrade failed on OLM problem that was fixed meanwhile and serial failed on infra

**Comment by tnozicka** [comment]
at last 2 e2e-gcp failed on https://bugzilla.redhat.com/show_bug.cgi?id=1879591
/retest

**Comment by tnozicka** [comment]
this time a slow CI pull
```
2020/09/16 15:41:32 Container cp-secret-wrapper in pod e2e-gcp-ipi-install-loki completed successfully
2020/09/16 15:47:22 pod didn't start running within 10 minutes: 
* Container test is not ready with reason CreateContainerError and message context deadline exceeded
2020/09/16 15:48:27 pod didn't start running within 10 minutes: 
* Container test is not ready with reason CreateContainerError and message context deadline exceeded
```
/retest

**Comment by tnozicka** [comment]
infra
/retest

**Comment by tnozicka** [comment]
gcp IAM flake
/retest

**Comment by deads2k** [comment]
This fixes the promotion problem we're having with golang 1.15 based payload.

**Pull request merged**
