### PR TITLE
UPSTREAM: 29119: Allow PVs to specify supplemental GIDs

### PR DESCRIPTION
**Pull request by wongma7**
https://github.com/kubernetes/kubernetes/pull/29119/

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by wongma7** [comment]
fixed `vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager_test.go:193: too many arguments in call to NewVolumeManager`

**Comment by smarterclayton** [comment]
Is there an e2e test for this change?

**Comment by wongma7** [comment]
No, do I need to add one before this can be merged?

**Comment by smarterclayton** [comment]
I think it might be good to add one upstream that verifies it - not a prereq for this to merge, but important in the long run to ensure the feature keeps working even through refactors and in the unified environment.  Verifying within a running pod that a mounted PV with supplemental groups has the right supplemental groups inside the container prevents having to test this manually in regressions.

**Comment by wongma7** [comment]
OK, I am working on a test now.

**Comment by pmorie** [comment]
Yeah +1 to an upstream e2e.  I've talked w/ Matthew a little about that today, he's on the right track.

**Comment by wongma7** [comment]
pr for e2e here https://github.com/kubernetes/kubernetes/pull/30084

**Comment by pweil-** [comment]
We have an issue but recording this here for awareness: https://github.com/openshift/origin/issues/9361

Introducing an annotation that changes security controlled behavior is dangerous.   This annotation allows access to supplemental groups that you may not be allowed to use based on your SCC grants.  In addition, we need to ensure that we check prior to upgrade that nothing is using this annotation so that when the cluster is upgraded they cannot exercise this behavior while bypassing admission checks (ie. crash my pod so the kubelet picks it up again and we get the new sup group).

cc @mfojtik since the issue is assigned to you and @pmorie

**Comment by liggitt** [comment]
transitive access to a gid needed to actually use a pv doesn't bother me, though I wish the gid was a first-class field on the PV rather than an annotation

**Comment by pweil-** [comment]
Discussed with @liggitt on IRC.  If folks are comfortable with saying that if you have access to the PV then you have access to the GID regardless of what policy says then I'm less worried about this.  Let's be clear in SCC and volume documentation that this behavior exists and that admins need to be aware of it.

**Comment by smarterclayton** [comment]
I'm ok with that, since PV is a delegation of higher level powers anyway.

**Comment by ncdc** [comment]
I'm planning on pulling this in as part of my big 1.3 cherry-picks PR. I can pull in 30084 as well once that merges. Is it ok to close this?

**Comment by wongma7** [comment]
OK, closing.

**Pull request closed without merging**
