### PR TITLE
Record kube Event first/last timestamp as intervals if possible

### PR DESCRIPTION
**Pull request by dgoodwin**
[TRT-685](https://issues.redhat.com//browse/TRT-685)

### CODE REVIEW

**Comment by neisw** [comment]
Job Failure Risk Analysis for sha: f50033c85e1d5c88ef6d9eaf9809734a793de451

| Job Name | Failure Risk |
|:---|:---:|
|[pull-ci-openshift-origin-master-e2e-agnostic-ovn-cmd](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-agnostic-ovn-cmd/1618954776408494080)|High|
|[pull-ci-openshift-origin-master-e2e-azure-ovn-etcd-scaling](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-azure-ovn-etcd-scaling/1618954777255743488)|High|
|[pull-ci-openshift-origin-master-e2e-gcp-csi](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-gcp-csi/1618954778073632768)|High|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-gcp-ovn/1618954778912493568)|Medium|
|[pull-ci-openshift-origin-master-e2e-openstack-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-openstack-ovn/1618954783966629888)|Medium|
|[pull-ci-openshift-origin-master-e2e-vsphere-ovn-etcd-scaling](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-vsphere-ovn-etcd-scaling/1618954784792907776)|High|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-cgroupsv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-cgroupsv2/1618954776479797248)|Medium|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-fips](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-fips/1618954776567877632)|Medium|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-upgrade/1618954776748232704)|High|
|[pull-ci-openshift-origin-master-e2e-metal-ipi-sdn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-metal-ipi-sdn/1618954783110991872)|High|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-etcd-scaling](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-etcd-scaling/1618954776525934592)|Medium|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-serial](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-serial/1618954776693706752)|High|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn-etcd-scaling](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-gcp-ovn-etcd-scaling/1618954779759742976)|Medium|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-single-node](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node/1618954776660152320)|High|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-aws-ovn-upgrade/1618954776794370048)|High|
|[pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27686/pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6/1618954782318268416)|High|

**Comment by dgoodwin** [comment]
giphy

**Comment by DennisPeriquet** [comment]
Work continues in https://github.com/openshift/origin/pull/27649

**Pull request closed without merging**
