### PR TITLE
bump o/k for the updated network policy tests

### PR DESCRIPTION
**Pull request by stlaz**
/assign @ibihim 
/cc @astoycos

### CODE REVIEW

**Comment by stlaz** [comment]
updating: I had to run `make update` with go 1.18 (compared to originally running with 1.19) to make `verify` pass

**Comment by stlaz** [comment]
/retest-required
install failures

**Comment by stlaz** [comment]
/test e2e-gcp
looks like there were some networking issues

**Review by soltysh — APPROVED** [review]
/approve

**Review by ibihim — APPROVED** [review]
/lgtm

**Comment by stlaz** [comment]
/test e2e-aws-fips
the failing tests appear to already have a BZ?

**Comment by stlaz** [comment]
/test e2e-aws-serial
looks like ovn-kube issues

**Comment by stlaz** [comment]
/test e2e-gcp-builds
appears unrelated

**Comment by stlaz** [comment]
/close
looks like fixing this in o/k was enough

**Pull request closed without merging**
