### PR TITLE
Add Server HTTP header with OpenShift version

### PR DESCRIPTION
**Pull request by mfojtik**
```
[root@openshiftdev origin]# curl -iks https://0.0.0.0:8443 | grep Server
Server: OpenShift/v0.4.3-257-g359d235-dirty
```

Fixes https://github.com/openshift/origin/issues/1828 additionally show the version on the login screen, next to the welcome text.

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton @bparees PTAL

**Comment by mfojtik** [comment]
@smarterclayton @bparees the only concern I have with this is security, as we are exposing the version by default and there is no option to disable it. If you concerned more about this than me currently, then I can add such option :-)

**Comment by smarterclayton** [comment]
Why would we do this?  What benefit does it provide?

**Comment by mfojtik** [comment]
@smarterclayton see https://github.com/openshift/origin/issues/1828

**Comment by smarterclayton** [comment]
Is an end user going to need this?  Does this incentivize clients to use code version to make decisions?

**Comment by ncdc** [comment]
I would think the client would specify a desired api version.

**Comment by mfojtik** [comment]
@ncdc @smarterclayton this is not about the API version, but about the 'server' version. If we make some changes to the server, clients can check and make decisions based on whether the feature they want to use is available. Also it makes the bugs reporting easier, as you can always check the version of the server you are sending requests to.

**Comment by smarterclayton** [comment]
I'm not opposed to returning this info but it might be better to do it on /version instead of every call, mostly due to security reasons (/version can be locked down by an admin).

**Comment by smarterclayton** [comment]
The scenario you described is exactly what I don't want to do - have clients using this number to determine features

**Comment by ncdc** [comment]
It is about api version. The problem is the api is evolving so some things may break until it stabilizes.

**Comment by mfojtik** [comment]
@smarterclayton currently the Server header is returned only on entrypoint, not in all requests. And yeah, I agree that checking features is not the best use-case here. But it might be useful for bug reporting.

**Comment by mfojtik** [comment]
@smarterclayton I can go ahead and open an issue on kube to gather this feedback. I think either camelCase or use dash is reasonable. (btw. I updated this PR with changes and I think we should merge it at some point, as this is hanging here for couple months ;-)

**Comment by ncdc** [comment]
It's also a possible way for malicious clients to discover if a server contains known vulnerabilities based on its version

**Comment by mfojtik** [comment]
@ncdc yeah that was my concern as well, there should be a way how to disable it.

**Comment by ncdc** [comment]
@mfojtik I would say if we do this, it should be disabled by default, with a means to enable it.

**Comment by smarterclayton** [comment]
Add this to version, which is already controllable by security.  Not to the headers.

**Comment by mfojtik** [comment]
@smarterclayton I just found that this information is already there:

```
}[root@openshiftdev origin]# curl -iks https://0.0.0.0:8443/version 
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 21 Apr 2015 12:58:24 GMT
Content-Length: 140

{
  "major": "0",
  "minor": "14.1+",
  "gitVersion": "v0.14.1-582-gb12d75d",
  "gitCommit": "b12d75d",
  "gitTreeState": "not a git tree"

```

**Comment by smarterclayton** [comment]
That's kube though - not OpenShift.

----- Original Message -----

**Comment by mfojtik** [comment]
@smarterclayton can we hijack our version information into this?

**Comment by smarterclayton** [comment]
Maybe add a top level "openshift" object with fields below it that match kube

----- Original Message -----

**Comment by TomasTomecek** [comment]
To support Michal here, this the code we use to distinguish  between 0.4.1 and 0.4.3: https://github.com/DBuildService/osbs/blob/master/osbs/core.py#L176

**Comment by smarterclayton** [comment]
So in general we do not want to support using version numbers to check for function for clients.  I'm ok with us returning a structured value for you, but be very careful doing that because we may eventually have conflicting version numbers coming back from other places.

----- Original Message -----

**Comment by danmcp** [comment]
@mfojtik This still valid?  Needs a rebase.

**Comment by smarterclayton** [comment]
I don't think we have a clear path forward on this.  I would prefer this value be part of an API document.

**Comment by mfojtik** [comment]
@smarterclayton agree, closing this and moving to post-30

**Pull request closed without merging**
