### PR TITLE
Fix wrong type for printf

### PR DESCRIPTION
**Pull request by yu-song**
Fix wrong type for printf

### CODE REVIEW

**Comment by enj** [comment]
@Miciah I will let you decide since I do not know your intent.

**Comment by Miciah** [comment]
Yeah, `%v` should be `%T`.

(That line traces all the way back to https://github.com/openshift/origin/pull/9885/files#diff-cbe61dec94c120466223271f21bcd664R98, but `%T` definitely makes more sense.)

**Comment by yu-song** [comment]
cc @pweil-  
I have changed it to %T.

**Comment by enj** [comment]
Squash.

**Comment by enj** [comment]
[test]

**Comment by yu-song** [comment]
@pweil- 
Excuse me, I have changed %v to %T. Please review again,.
Thanks very much.

**Comment by mfojtik** [comment]
LGTM @yu-song can you please squash the commits into one?

**Comment by yu-song** [comment]
Thank you for yours hint.

**Comment by pweil-** [comment]
re[test]

**Comment by pweil-** [comment]
[merge]

**Pull request merged**
