### PR TITLE
Revert "[release-4.14] OCPBUGS-22720: Use Centos 8 Stream mysql image in tests"

### PR DESCRIPTION
**Pull request by vrutkovs**
Reverts openshift/origin#28365

### CODE REVIEW

**Comment by sdodson** [comment]
/hold
The original change doesn't seem to have broken things on 4.14. I think we can tolerate this in 4.14 until we've sorted out 4.15 but we should not continue too much longer with the change reverted in 4.15. I see #28374 is reintroducing the change on mater branch.

**Comment by soltysh** [comment]
/hold cancel
Actually I've noticed this failing in some instances of 4.14: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1801/pull-ci-openshift-kubernetes-release-4.14-e2e-aws-ovn-cgroupsv2/1725084481922011136

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp-ovn-image-ecosystem
to unblock merges to 4.14

**Pull request merged**
