### PR TITLE
Output uppercase, hex, 2-character padded serial.txt

### LINKED ISSUE #6055: `oadm ca` should generate serial.txt that is compatible with openssl
OpenSSL requires the serial.txt to be "a text file containing the next serial number to use in hex"

`oadm ca` currently consumes and writes serial.txt as a text file with decimal numbers. Switching to hex would be a strict increase in serial number, so would not cause problems with existing certs, and would allow the serial text file to be used by openssl as well.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #6055

Decimal can always decode as hex, so when we make this switch, we'll just jump several serial numbers forward.

### CODE REVIEW

**Comment by liggitt** [comment]
@detiber PTAL

**Comment by detiber** [comment]
@liggitt lgtm.

Now if only we could create the etcd peer certs with oadm CA :)

**Comment by liggitt** [comment]
`oadm ca create-client-server-what-am-i-maybe-everything-cert`

**Comment by detiber** [comment]
Hey, I didn't design etcd in a way that it uses the same cert as a client and a server cert for the peer connection :)

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
