### PR TITLE
Revert back to the "normal" apiserver authentication

### PR DESCRIPTION
**Pull request by deads2k**
Blocked on https://github.com/openshift/openshift-ansible/issues/5056

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k the PR this was blocked on has been closed, what's the latest status?

**Comment by deads2k** [comment]
@bparees rebased

**Comment by deads2k** [comment]
@bparees @jim-minter can you guys put the test back to the way I initially built it, where the daemonset and service were located in the namespace that the ansible installer was going to lay them into?  Alternatively, you can try to wire your roles up properly.

**Comment by jim-minter** [comment]
@deads2k what do you mean by "you can try to wire your roles up properly" - what is the issue?  Also, https://github.com/openshift/origin/issues/16622 is open to get us to the point where ansible is automatically setting up the TSB in our CI clusters.

**Comment by bparees** [comment]
@deads2k https://github.com/openshift/openshift-ansible/issues/5056 has closed, is this still blocked on anything?

**Comment by bparees** [comment]
@deads2k i'm still not clear on if anything is holding this up and/or if there are still test changes that need(or should) to go with this

**Comment by deads2k** [comment]
> @deads2k i'm still not clear on if anything is holding this up and/or if there are still test changes that need(or should) to go with this

Nothing needed for 3.7.

**Comment by bparees** [comment]
talked to @deads2k and this is failing for reasons that are unclear w/o being able to get TSB logs.

we're hoping that once @jim-minter's work to use the cluster-wide TSB installed by ansible, in extended tests, it will be easier to get the right logs to see why this is failing.

(@deads2k contends that the TSB is crashing, and i'm not sure it'll be any easier to get the logs if that's true, but i guess we'll cross that bridge when we get to it).

in the meantime:
/retest

**Comment by bparees** [comment]
also to follow up on the request to revert the TSB tests:  At some point @deads2k wrote the TSB tests to share an TSB installed at the cluster level (which would align w/ how things will work once @jim-minter's effort to get us using the ansible installed TSB lands).  At some future point, the tests were reworked to use a TSB instance per test.  I do not recall the change or the reasoning for it, though I do recall a number of flakes in the tests and some iteration to resolve them.

In any case, once @jim-minter's change lands to be able to use the ansible installed TSB, we will be changing the tests back to not using their own TSB, so @deads2k will get his wish.  

@deads2k also expressed concern that when we go to a single TSB, our tests may start conflicting.  I think we're safe from that since our tests do not manipulate the catalog, and everything they do do is done in a test-scoped namespace (provision/deprovision).

But if we ever did introduce tests that need to register new templates(or worse, de-register some), or change which namespaces the TSB monitors for templates to offer in the catalog, we'll need to keep that concern in mind.

**Comment by deads2k** [comment]
bump bot

**Pull request merged**
