### PR TITLE
oc rsync: allow multiple include or exclude patterns

### LINKED ISSUE #8185: oc rsync allow multiple exclude or include patterns
Currently, `oc rsync` does not allow multiple --exclude or --include flags. Rsync itself allows multiple flags to be passed, but the flags library grabs the last flag value and uses that. Looking at the spf13/pflag library, there is a StringSlice flag type that may be usable. The StringSlice is a comma separated list. I'm not sure if it's the most ideal solution as StringSlice would not be a direct passthrough of flags to rsync. Some translation would be necessary to go from a comma separate list to multiple flags.

rsync standard: `rsync src dst --exclude=file1.txt --exclude=file2.txt`
using StringSlice: `oc rsync src dst --exclude=file1.txt,file2.txt`

##### Version
`oc v1.1.4` on OSX 10.10 and Windows 7

##### Steps To Reproduce
`oc rsync ./ pod-1-asdfg:/opt/app-root/src/ --exclude=file1.txt --exclude=file2.txt`

##### Current Result
`file2.txt` is the only file that is excluded

##### Expected Result
Both `file1.txt` and `file2.txt` should be excluded

### PR DESCRIPTION
**Pull request by csrwng**
Allows multiple --include/--exclude flags to be specified, or a comma-separated list of patterns
Fixes #8185

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
updated generated docs

**Comment by csrwng** [comment]
[testextended][extended:core(rsync)]

**Pull request merged**
