### PR TITLE
add instructions for insecure registry config

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton review please.  i used 172.30.17.0/24 as i think that's the subnet we're using for services.  I assume 172.0.0.0/24 was a typo on your part, or i've forgotten my subnet masking rules.

**Comment by mfojtik** [comment]
LGTM

btw. how hard would be to make a certificate and add it into docker registry container and to the host? (or automate this)

**Comment by bparees** [comment]
well i don't think we can distribute one (that would sort of defeat the purpose of having a cert after all).  So that leaves automatically generating a self-signed cert and injecting it.  Assuming that a self-signed cert would get past this problem, which it probably would not.  (I assume docker would still consider that untrusted).  So...not simple?

**Comment by bparees** [comment]
[merge]

**Pull request merged**
