### PR TITLE
Bug 1819276: use rbac vs direct scc edit for s2i root bld test

### PR DESCRIPTION
**Pull request by gabemontero**
Update to our old s2i root build via privileged SCC test 

Stemming from ask from @bparees in https://coreos.slack.com/archives/CB48XQ4KZ/p1585580675154600

Using recommendation from @smarterclayton and docs at https://docs.openshift.com/container-platform/4.1/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth as a reference

/assign @bparees 

@bparees - the slack thread mentions 4.3
- so we will want to backport this, correct?
- if so, is there a tracking BZ for this already?

### CODE REVIEW

**Comment by gabemontero** [comment]
sorry forgot - @openshift/openshift-team-developer-experience FYI ... see description for details

**Comment by bparees** [comment]
/lgtm

@gabemontero no BZ yet.  as for backporting, yeah it'd be nice to have it back to 4.3.  No further than that is necessary imho.

**Comment by gabemontero** [comment]
My role binding construction was not quite right @bparees ... will need to update:

```
fail [github.com/openshift/origin/test/extended/builds/s2i_root.go:106]: Unexpected error:
    <*errors.StatusError | 0xc002ade460>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "RoleBinding.rbac.authorization.k8s.io \"privileged-builder-rolebinding\" is invalid: roleRef.kind: Unsupported value: \"\": supported values: \"Role\", \"ClusterRole\"",
            Reason: "Invalid",
            Details: {
                Name: "privileged-builder-rolebinding",
                Group: "rbac.authorization.k8s.io",
                Kind: "RoleBinding",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueNotSupported",
                        Message: "Unsupported value: \"\": supported values: \"Role\", \"ClusterRole\"",
                        Field: "roleRef.kind",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    RoleBinding.rbac.authorization.k8s.io "privileged-builder-rolebinding" is invalid: roleRef.kind: Unsupported value: "": supported values: "Role", "ClusterRole"
```

**Comment by gabemontero** [comment]
Well, if I could get a cluster up today, I'd actually try this out locally before testing in the PR:

```
fail [github.com/openshift/origin/test/extended/builds/s2i_root.go:110]: Unexpected error:
    <*errors.StatusError | 0xc001bfdcc0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "RoleBinding.rbac.authorization.k8s.io \"privileged-builder-rolebinding\" is invalid: [roleRef.apiGroup: Unsupported value: \"rbac.authorization.k8s.io/v1\": supported values: \"rbac.authorization.k8s.io\", subjects[0].apiGroup: Unsupported value: \"v1\": supported values: \"\"]",
            Reason: "Invalid",
            Details: {
                Name: "privileged-builder-rolebinding",
                Group: "rbac.authorization.k8s.io",
                Kind: "RoleBinding",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueNotSupported",
                        Message: "Unsupported value: \"rbac.authorization.k8s.io/v1\": supported values: \"rbac.authorization.k8s.io\"",
                        Field: "roleRef.apiGroup",
                    },
                    {
                        Type: "FieldValueNotSupported",
                        Message: "Unsupported value: \"v1\": supported values: \"\"",
                        Field: "subjects[0].apiGroup",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    RoleBinding.rbac.authorization.k8s.io "privileged-builder-rolebinding" is invalid: [roleRef.apiGroup: Unsupported value: "rbac.authorization.k8s.io/v1": supported values: "rbac.authorization.k8s.io", subjects[0].apiGroup: Unsupported value: "v1": supported values: ""]
```

another update coming @bparees  ... apologies 

/hold

**Comment by gabemontero** [comment]
I'll unhold when either a) the test passes here, or b) I get a cluster up and can try it out locally

**Comment by gabemontero** [comment]
ok updated test is passing now @bparees ... just dealing with non-related problems in the other e2es

/hold cancel

**Comment by gabemontero** [comment]
trying upgrade again after https://github.com/openshift/cluster-svcat-controller-manager-operator/pull/73 merged (saw elements of that in last upgrade failure) and subsequent CI updates noted in https://coreos.slack.com/archives/CEKNRGF25/p1585746383178000

/test e2e-gcp-upgrade

**Pull request merged**
