### PR TITLE
UPSTREAM: 63416: Retry certificate approval on conflict errors

### LINKED ISSUE #19430: [gce] Conflict when approving the CSR
Seen this flake in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19424/test_pull_request_origin_extended_conformance_gce/19348/
 
```
 1. Hosts:    ci-prtest-5a37c28-19348-ig-m-st4c
     Play:     masters
     Task:     Bootstrap all nodes that were identified with bootstrap metadata
     Message:  [{u'cmd': u'/bin/oc adm certificate approve csr-jh7qw', u'returncode': 0, u'results': {}}, {u'cmd': u'/bin/oc adm certificate approve csr-klkjj', u'returncode': 1, u'results': {}, u'stderr': u'Error from server (Conflict): Operation cannot be fulfilled on certificatesigningrequests.certificates.k8s.io "csr-klkjj": the object has been modified; please apply your changes to the latest version and try again\n', u'stdout': u'No resources found\n'}]
```

Opened and closed https://github.com/kubernetes/kubernetes/pull/62846 after talking to @deads2k 

@sdodson i guess we have to make the ansible retry on conflict in this case (and check the preconditions first).

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #19430

### CODE REVIEW

**Comment by liggitt** [comment]
cc @sdodson

**Comment by smarterclayton** [comment]
Uh oh

**Comment by smarterclayton** [comment]
Upstream is missing a break.

**Comment by smarterclayton** [comment]
No, upstream has the break.  Downstream missing it?

**Comment by liggitt** [comment]
Pick wasn't clean. I missed it.

**Pull request merged**
