### PR TITLE
oc: add -o revision in rollout latest

### LINKED ISSUE #10864: oc deploy --latest can't wait for the deployment and return correct exist status
For people that are controlling OpenShift from scripts, there needs to be a way to rollout a new deployment and wait for it, returning meaningful exist code.

Right now the closest seems to be using `oc deploy --latest --follow` that waits for the deployment to finish, but does not tell you if it actually got deployed or failed. (It returns 0 even if the deployment fails; rightfully, because it followed just the logs and that went fine.)

This is a major problem when you want to control the deployment from a script or pipeline. 

Let's consider the following use case:
1. build a new image and push it
2. `oc deploy --latest` to rollout the new version
2.1 wait for it and make sure it got deployed or fail
3. run tests against the new instance

You have to know that it got deployed successfully at step 2. otherwise it makes no sense to run those tests.

This should be done in the same command with a flag like `--wait`. It will be quite common operation e.g. in pipelines.

(I am aware this functionality is moving to `oc rollout`, but I did not want to reference it since it's not merged yet. I am fine with fixing this just there, not in `oc deploy`.)

@kargakis This is the one we discussed over IRC a bit.

It's pipeline related so @bparees might be interested or have some good insights.

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik ptal

cc: @openshift/cli-review 

Now users can wait for specific deployment revisions to finish by:
```shell
REVISION=$(oc rollout latest dc/foo -o revision)
oc rollout status dc/foo --revision=$REVISION
```

Fixes #10864

### CODE REVIEW

**Comment by kargakis** [comment]
@mfojtik I am also backporting https://github.com/kubernetes/kubernetes/pull/34443 so to fix https://github.com/openshift/origin/issues/10864

**Comment by fabianofranz** [comment]
LGTM

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11370 [test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11381 [merge]

**Comment by kargakis** [comment]
#11381 [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11240 [test]

**Pull request merged**
