### PR TITLE
Retry OVS flow checks in extended networking a few times if they fail

### LINKED ISSUE #12855: flake: OVS generic should add and remove flows when nodes are added and removed
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/1073/

    /data/src/github.com/openshift/origin/test/extended/networking/ovs.go:150
    Flows after deleting node should be same as before creating it
    Expected
        <bool>: false
    to be true
    /data/src/github.com/openshift/origin/test/extended/networking/ovs.go:149

### PR DESCRIPTION
**Pull request by danwinship**
The OVS tests occasionally flake, which I assume is because there's no synchronization between the changes we make (creating/deleting nodes/pods/services) and our checking the flows, so in some cases we might check the flows before the node has actually changed them. So if we don't get the expected answers the first time, then retry.

Closes #12855 

(Tests are failing for entirely random reasons on my machine right now so this isn't tested yet, and I'm going to run it a few times before requesting review just to give it a chance to flake if it was going to.)

### CODE REVIEW

**Comment by danwinship** [comment]
[testextended][extended:networking]

**Comment by danwinship** [comment]
@openshift/networking PTAL

The current flake turned out to actually be because of the multicast code; in the "send multicast packets to all other nodes" flow, the "all other nodes" could get written out in any order, so sometimes the before-adding-a-new-node and after-deleting-a-new-node flows would be different:

    -cookie=0x0, table=111, priority=100 actions=move:NXM_NX_REG0[]->NXM_NX_TUN_ID[0..31],set_field:172.17.0.3->tun_dst,output:1,set_field:172.17.0.2->tun_dst,output:1,goto_table:120
    +cookie=0x0, table=111, priority=100 actions=move:NXM_NX_REG0[]->NXM_NX_TUN_ID[0..31],set_field:172.17.0.2->tun_dst,output:1,set_field:172.17.0.3->tun_dst,output:1,goto_table:120

Since we were already sorting output ports in the "send multicast packets to all pods in this vnid on this node" flows, I fixed it to sort the other-nodes flow too.


However, since the bug described in the original comment does still theoretically exist (and probably not just theoretically since we'd seen OVS flakes in the past, pre-multicast), and I'd already written the code to fix that before finding the real bug, this has the exponential-backoff-retry fix too.

And also, it changes the error handling so that if one of the flow checks does fail, the failure message will include the flows as well so we don't have to just guess why they didn't match (eg, https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/1129/consoleFull#57253582056cbb9a5e4b02b88ae8c2f77. That's how I actually found the multicast bug.)

**Comment by danwinship** [comment]
Poke pokey poke. #13093 just hit this flake too though fortunately it managed to merge anyway for some reason.

And we're going to need to cherry-pick this to 3.5 too...

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
