### PR TITLE
Speed up DC reaper

### PR DESCRIPTION
**Pull request by deads2k**
The DC reaper takes forever. This removes the unnecessary waits and updates the observation to use a watch.

@fabianofranz ptal.  You or @juanvallejo probably want to sweep all of them.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@deads2k I think this addresses #10068

**Comment by fabianofranz** [comment]
cc @mfojtik

**Comment by mfojtik** [comment]
yes, this might help, but need fixing the reaper unit test.

-- 
Michal Fojtik

**Comment by soltysh** [comment]
It would be nice to upstream this, afterwards. They're using the same logic, iirc.

**Comment by deads2k** [comment]
> It would be nice to upstream this, afterwards. They're using the same logic, iirc.

I opened an upstream fixing one and tagged fabiano.

**Comment by fabianofranz** [comment]
Related upstream: https://github.com/kubernetes/kubernetes/pull/30383

**Comment by deads2k** [comment]
infrastructure re[test]

**Comment by kargakis** [comment]
@deads2k can you rebase so we can get this merged?

**Comment by deads2k** [comment]
> @deads2k can you rebase so we can get this merged?

@kargakis its a nice to have.  The test updates are nasty enough that I don't think I'm going to have it done for 1.3.

Unit testing gone wrong.

**Pull request closed without merging**
