### PR TITLE
Re-enable multi-node PV e2e test

### PR DESCRIPTION
**Pull request by tsmetana**
The previous failures should have been fixed in the PR#22886

### CODE REVIEW

**Comment by tsmetana** [comment]
just to be sure...
/test e2e-aws

**Comment by tsmetana** [comment]
I had to disable the AWS multi node test. It doesn't count with the multi-AZ clusters and will not work without bigger change. This has to be resolved upstream first though.

**Comment by tsmetana** [comment]
The NFS tests work OK so I've enabled only those so far. I have a PR for the AWS EBS fix upstream:
https://github.com/kubernetes/kubernetes/pull/78697

**Comment by deads2k** [comment]
yay

/approve

**Pull request closed without merging**
