### PR TITLE
[release-4.5] Bug 1843462: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage

### PR DESCRIPTION
**Pull request by soltysh**
4.5 cherry-pick of https://github.com/openshift/origin/pull/25060
/assign @tnozicka

### CODE REVIEW

**Comment by mfojtik** [comment]
/override ci/prow/e2e-aws-disruptive

this test is blocked on https://github.com/openshift/release/pull/9696

**Comment by soltysh** [comment]
This is blocked on https://github.com/openshift/origin/pull/25091 to be delivered onto 4.5

**Comment by mfojtik** [comment]
vsphere is irrelevant to this change and all jobs passed... this is fixing 4.5.0 blocker bug and have to ship today, merging with button.

**Pull request merged**
