### PR TITLE
UPSTREAM: <drop>: Disable timeouts on kubelet pull and logs

### LINKED ISSUE #9221: [builds][Conformance] build without output image building from templates [It] should create an image from "test-s2i-no-outputname.json" S2i template without an output image reference defined
```
   9708 Jun 08 08:11:35 ESC[91mESC[1m• Failure [33.538 seconds]ESC[0m
   9709 Jun 08 08:11:35 [builds][Conformance] build without output image
   9710 Jun 08 08:11:35 ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:49ESC[0m
   9711 Jun 08 08:11:35   building from templates
   9712 Jun 08 08:11:35   ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:48ESC[0m
   9713 Jun 08 08:11:35     ESC[91mESC[1mshould create an image from "/data/src/github.com/openshift/origin/test/extended/fixtures/test-s2i-no-outputname.json" S2i template without an output image reference defined [It]ESC[0m
   9714 Jun 08 08:11:35     ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:47ESC[0m
   9715 Jun 08 08:11:35 
   9716 Jun 08 08:11:35     ESC[91mExpected error:
   9717 Jun 08 08:11:35         <*exec.ExitError | 0xc820be22e0>: {
   9718 Jun 08 08:11:35             ProcessState: {
   9719 Jun 08 08:11:35                 pid: 26591,
   9720 Jun 08 08:11:35                 status: 256,
   9721 Jun 08 08:11:35                 rusage: {
   9722 Jun 08 08:11:35                     Utime: {Sec: 0, Usec: 103657},
   9723 Jun 08 08:11:35                     Stime: {Sec: 0, Usec: 9805},
   9724 Jun 08 08:11:35                     Maxrss: 23636,
   9725 Jun 08 08:11:35                     Ixrss: 0,
   9726 Jun 08 08:11:35                     Idrss: 0,
   9727 Jun 08 08:11:35                     Isrss: 0,
   9728 Jun 08 08:11:35                     Minflt: 6007,
   9729 Jun 08 08:11:35                     Majflt: 0,
   9730 Jun 08 08:11:35                     Nswap: 0,
   9731 Jun 08 08:11:35                     Inblock: 0,
   9732 Jun 08 08:11:35                     Oublock: 0,
   9733 Jun 08 08:11:35                     Msgsnd: 0,
   9734 Jun 08 08:11:35                     Msgrcv: 0,
   9735 Jun 08 08:11:35                     Nsignals: 0,
   9736 Jun 08 08:11:35                     Nvcsw: 2008,
   9737 Jun 08 08:11:35                     Nivcsw: 2,
   9738 Jun 08 08:11:35                 },
   9739 Jun 08 08:11:35             },
   9740 Jun 08 08:11:35             Stderr: nil,
   9741 Jun 08 08:11:35         }
   9742 Jun 08 08:11:35         exit status 1
   9743 Jun 08 08:11:35     not to have occurredESC[0m
   9744 Jun 08 08:11:35 
   9745 Jun 08 08:11:35     /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:45


 12613 Jun 08 08:19:02 [Fail] [builds][Conformance] build without output image building from templates [It] should create an image from "/data/src/github.com/openshift/origin/test/  12613 extended/fixtures/test-s2i-no-outputname.json" S2i template without an output image reference defined
  12614 Jun 08 08:19:02 /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:45
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Track https://github.com/kubernetes/kubernetes/issues/27588

Fixes #9221 

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
F0616 21:40:43.106339   11345 master.go:285] listen tcp4 127.0.0.1:38443: bind: address already in use
```

when generating swagger @stevekuznetsov

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@liggitt @csrwng looks like there is log flakiness:

```
Running test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default'...
FAILURE after 0.016s: test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed
Standard output from the command:
Waiting for pod test/cli-with-token-2 to be running, status is Pending, pod ready: false
```

**Comment by smarterclayton** [comment]
I mean attach flakiness.  So we're back to being unable to rely on attach?

**Comment by smarterclayton** [comment]
@mfojtik we saw other flakiness in attach, correct?

**Comment by smarterclayton** [comment]
[test]

**Comment by mfojtik** [comment]
@smarterclayton I don't remember other flakiness in attach

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Steve has been tracking several races, although I think they exist even
before engine-api.

On Jun 17, 2016, at 4:12 AM, OpenShift Bot <notifications@github.com> wrote:

Merged #9392 <https://github.com/openshift/origin/pull/9392>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9392#event-695644834>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p8AS4PcawdG63Dz6nlHzjh8rG9Azks5qMlbigaJpZM4I39JM>
.

**Comment by stevekuznetsov** [comment]
#9108 #9309

**Pull request merged**
