### PR TITLE
testing the test

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by deads2k** [comment]
[test] to see if the bot runs

**Comment by deads2k** [comment]
@sttts if this tests against the proper branch, then the branch here can save you from rebase hell looking for green.

**Comment by sttts** [comment]
is this the same as `origin/rebase-1.6.1-base`? So just the fork point?

**Comment by deads2k** [comment]
> is this the same as origin/rebase-1.6.1-base? So just the fork point?

Ah, looks like.  Didn't realize you already had one.  Do you have rights to push to your existing one?  If not, this is close to mess with until the morning.

**Pull request closed without merging**
