### PR TITLE
Fix oc status unit test

### PR DESCRIPTION
**Pull request by kargakis**
@deads2k unit tests are broken w/o this.

[merge]

Fixes https://github.com/openshift/origin/issues/6423

### CODE REVIEW

**Comment by liggitt** [comment]
Hold on, how did a breaking change make it into master without this?

**Comment by kargakis** [comment]
> Hold on, how did a breaking change make it into master without this?

If we don't provide a fixed time, then every time these tests run, they are using time.Now() as the current time and times in oc status ("#8 build running for 2 days") will vary (note that test fixtures are using timestamps). We merged https://github.com/openshift/origin/pull/6379 yesterday and the test was using "hours" but now the difference makes up to "days" :)

**Comment by liggitt** [comment]
Ah, makes sense

**Comment by liggitt** [comment]
Though aren't the creation time stamps in the fixture ignored and overwritten at create time?

**Comment by kargakis** [comment]
> Though aren't the creation time stamps in the fixture ignored and overwritten at create time?

I am not sure this is supposed to happen when adding resources from [paths](https://github.com/kubernetes/kubernetes/blob/08c2cba266ba5205a8c5341279ded49776f64cee/pkg/client/unversioned/testclient/fixture.go#L108).

**Comment by liggitt** [comment]
Ah, fixture loader, not live API requests. Carry on :)

**Pull request merged**
