### PR TITLE
Remove Custom HPA Setup

### PR DESCRIPTION
**Pull request by DirectXMan12**
This commit removes the custom HPA controller setup.  This means the HPA
can no longer read from the OpenShift Heapster, but that's fine, since
we deploy metrics-server in openshift-ansible as of
openshift/openshift-ansible#8907.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @deads2k finally :boom:
@frobware thanks for the ansible end of things
@sjenning FYI

**Comment by deads2k** [comment]
At what point during an upgrade is it available?  Once we stabilize, this makes sense, but does it work during the upgrade too?

**Comment by DirectXMan12** [comment]
it's installed as part of the metrics playbook by default, so it should be available as soon as that playbook runs, I believe.

**Comment by DirectXMan12** [comment]
> Is that before or after the binaries on disk are updated?

Need to check.  If I had to guess, probably after.  There's no reason it couldn't be run before, though, in case of upgrades.

If it's run after, there'll be a brief gap in HPA functionality.  If a brief gap in HPA functionality is not acceptable during upgrade, we'd have to introduce a new option to toggle between Heapster and aggregated APIs for the HPA, and re-implement the logic that's in the kube controller setup.  I don't want that to be an option long-term, though (and I kind-of don't want people to be able to set it long-term at all).  What do we want to do in that case?

**Comment by deads2k** [comment]
> If it's run after, there'll be a brief gap in HPA functionality. If a brief gap in HPA functionality is not acceptable during upgrade, we'd have to introduce a new option to toggle between Heapster and aggregated APIs for the HPA, and re-implement the logic that's in the kube controller setup. I don't want that to be an option long-term, though (and I kind-of don't want people to be able to set it long-term at all). What do we want to do in that case?

You hope that its brief, but if something goes wrong it could take a while.  I see these choices:
 1. You risk having broken HPA while an upgrade is in process and hope that no customer ever gets stuck.
 2. You install the metrics server *before* you roll the binaries over.
 3. You install the metrics server in 3.10 and then fix the code in 3.11.

Of those, option 2 seems more palatable than the rest.   Is it practical?

**Comment by DirectXMan12** [comment]
Of course, I'd prefer option 2 as well, although that means we have to have special upgrade logic for that playbook (you can't really install components on OpenShift before the API server comes up ;-)).

@frobware (who did the ansible bits here) WDYT about installing metrics server first on upgrade.

**Comment by deads2k** [comment]
@smarterclayton @liggitt discussion of risk during rollout for new HPA.   Left to my own devices I'd choose 2 or if that isn't possible, I'd default to 3.  Anyone want to speak up and take the risk on 1?


You hope that its brief, but if something goes wrong it could take a while. I see these choices:

1. You risk having broken HPA while an upgrade is in process and hope that no customer ever gets stuck.
2. You install the metrics server before you roll the binaries over.
3. You install the metrics server in 3.10 and then fix the code in 3.11.

**Comment by frobware** [comment]
> @frobware (who did the ansible bits here) WDYT about installing metrics server first on upgrade.

Will look into how upgrades work. I hope we don't have to duplicate parts of the openshift-metrics playbook (i.e., the place we've just added the metrics-server logic).

**Comment by sjenning** [comment]
Until 3.11
/hold

**Comment by DirectXMan12** [comment]
This should be rebased and ready for merge one the ansible PR merges.

**Comment by DirectXMan12** [comment]
@deads2k or @liggitt can we get this merged today?  The corresponding ansible PR is approved for merging...

**Comment by deads2k** [comment]
> @deads2k or @liggitt can we get this merged today? The corresponding ansible PR is approved for merging...

you went with option 3, so have no downtime?

**Comment by DirectXMan12** [comment]
> you went with option 3, so have no downtime?

No.  We couldn't install metrics-server in 3.10 because the image didn't get built in time for feature freeze.  Doing option 3 would push this off another release, with I don't think is acceptable.

That leaves options 1 and 2.  By default, we take option 1.  While that's sub-optimal, I think it was decided that having special pre-upgrade logic was problematic for some reason (@frobware do you remember why we didn't do that?).  However, now that the playbooks are runnable independently of each other, it should be possible to just run the metrics playbook pre-control-plane-upgrade, for users who are concerned about the outage.

**Comment by smarterclayton** [comment]
You cannot cause an outage during an upgrade unless you're major special.  This doesn't really qualify.  You must be N-1 on the control plane always.

**Comment by smarterclayton** [comment]
Doing the metrics server install at the beginning of the upgrade is possible, but you'll need to test heavily.  We can change certain orders (as long as 3.11 metrics server is decoupled from core apis, which it should be).

**Comment by DirectXMan12** [comment]
> We can change certain orders (as long as 3.11 metrics server is decoupled from core apis, which it should be).

It should not be problematic from a metrics-server perspective to just install it pre-upgrade.  I seem to recall any issues with running pre-upgrade were installer wrinkles, but I don't recall what they were.  @frobware can you take a look at that since you wrote the current ansible PR?

**Comment by deads2k** [comment]
> That leaves options 1 and 2. By default, we take option 1. While that's sub-optimal, I think it was decided that having special pre-upgrade logic was problematic for some reason (@frobware do you remember why we didn't do that?). However, now that the playbooks are runnable independently of each other, it should be possible to just run the metrics playbook pre-control-plane-upgrade, for users who are concerned about the outage.

@liggitt made the point that we don't really know how long they'll be rippling.  Install in 3.11 and update in the next.

/hold

**Comment by DirectXMan12** [comment]
> @liggitt made the point that we don't really know how long they'll be rippling. Install in 3.11 and update in the next.

If we take option 2 (pre-upgrade) that should be moot.  I'll figure out how to get the pre-upgrade path working

**Comment by DirectXMan12** [comment]
@frobware can you take a look at https://github.com/openshift/openshift-ansible/pull/9104?

**Comment by DirectXMan12** [comment]
ansible PR merged.  Can we get this unheld?

**Comment by DirectXMan12** [comment]
@deads2k @smarterclayton ping, can we unhold this?

**Comment by deads2k** [comment]
> ansible PR merged for doing pre-upgrade install. Can we get this unheld?

yay!

/hold cancel

**Comment by DirectXMan12** [comment]
@deads2k can you also approve and/or lgtm?

**Comment by deads2k** [comment]
this removes the special HPA case.  @DirectXMan12 owns making sure we get testing on the functionality of hpa overall

/lgtm

**Pull request merged**
