### PR TITLE
Updated allowed levels of `glog` info levels in CLI doc

### LINKED ISSUE #9052: --loglevel documented as max 5 it's really max 10 (replacing --v=10)
--v=10 has changed into --loglevel=10, but the command is wrongly documented.

# oc options
````
The following options can be passed to any command:
      ....
      --loglevel=0: Set the level of log output (0-5)
      ....
````

It clearly says max is 5.

With loglevel=5 (max documented) I get:
````
[root@origin ~]# oc get pods --loglevel=5
I0526 18:15:07.638648   18348 meta.go:46] Calling Accessor on non-internal object: *api.PodList
NAME              READY     STATUS    RESTARTS   AGE
jenkins-1-80a94   1/1       Running   0          2h
````

But knowing what you said, I used 10, and voila:
````
[root@origin ~]# oc get pods --loglevel=10
I0526 18:15:11.055285   18433 loader.go:242] Config loaded from file /var/lib/origin/openshift.local.config/master/admin.kubeconfig
I0526 18:15:11.057289   18433 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0 (linux/amd64) openshift/6e83535" https://10.2.2.2:8443/oapi
I0526 18:15:11.084679   18433 round_trippers.go:318] GET https://10.2.2.2:8443/oapi 200 OK in 27 milliseconds
I0526 18:15:11.084704   18433 round_trippers.go:324] Response Headers:
I0526 18:15:11.084708   18433 round_trippers.go:327]     Cache-Control: no-store
I0526 18:15:11.084712   18433 round_trippers.go:327]     Content-Type: application/json
I0526 18:15:11.084715   18433 round_trippers.go:327]     Date: Thu, 26 May 2016 22:15:11 GMT
I0526 18:15:11.084719   18433 round_trippers.go:327]     Content-Length: 93
I0526 18:15:11.084770   18433 request.go:870] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1"],"serverAddressByClientCIDRs":null}
I0526 18:15:11.085262   18433 cached_discovery.go:80] returning cached discovery info from /root/.kube/10.2.2.2_8443/servergroups.json
I0526 18:15:11.085323   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/autoscaling/v1/serverresources.json
I0526 18:15:11.085372   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/batch/v1/serverresources.json
I0526 18:15:11.085448   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/extensions/v1beta1/serverresources.json
I0526 18:15:11.085672   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/v1/serverresources.json
I0526 18:15:11.085839   18433 cached_discovery.go:80] returning cached discovery info from /root/.kube/10.2.2.2_8443/servergroups.json
I0526 18:15:11.085884   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/autoscaling/v1/serverresources.json
I0526 18:15:11.085928   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/batch/v1/serverresources.json
I0526 18:15:11.086021   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/extensions/v1beta1/serverresources.json
I0526 18:15:11.086324   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/v1/serverresources.json
I0526 18:15:11.086959   18433 cached_discovery.go:80] returning cached discovery info from /root/.kube/10.2.2.2_8443/servergroups.json
I0526 18:15:11.087002   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/autoscaling/v1/serverresources.json
I0526 18:15:11.087042   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/batch/v1/serverresources.json
I0526 18:15:11.087121   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/extensions/v1beta1/serverresources.json
I0526 18:15:11.087439   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/v1/serverresources.json
I0526 18:15:11.088064   18433 cached_discovery.go:80] returning cached discovery info from /root/.kube/10.2.2.2_8443/servergroups.json
I0526 18:15:11.088100   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/autoscaling/v1/serverresources.json
I0526 18:15:11.088194   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/batch/v1/serverresources.json
I0526 18:15:11.088282   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/extensions/v1beta1/serverresources.json
I0526 18:15:11.088593   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/v1/serverresources.json
I0526 18:15:11.094697   18433 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0 (linux/amd64) kubernetes/6e83535" https://10.2.2.2:8443/api
I0526 18:15:11.096413   18433 round_trippers.go:318] GET https://10.2.2.2:8443/api 200 OK in 1 milliseconds
I0526 18:15:11.096430   18433 round_trippers.go:324] Response Headers:
I0526 18:15:11.096434   18433 round_trippers.go:327]     Cache-Control: no-store
I0526 18:15:11.096438   18433 round_trippers.go:327]     Content-Type: application/json
I0526 18:15:11.096441   18433 round_trippers.go:327]     Date: Thu, 26 May 2016 22:15:11 GMT
I0526 18:15:11.096444   18433 round_trippers.go:327]     Content-Length: 130
I0526 18:15:11.096471   18433 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.2.2.2:443"}]}
I0526 18:15:11.096676   18433 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0 (linux/amd64) kubernetes/6e83535" https://10.2.2.2:8443/apis
I0526 18:15:11.097543   18433 round_trippers.go:318] GET https://10.2.2.2:8443/apis 200 OK in 0 milliseconds
I0526 18:15:11.097566   18433 round_trippers.go:324] Response Headers:
I0526 18:15:11.097569   18433 round_trippers.go:327]     Content-Length: 760
I0526 18:15:11.097573   18433 round_trippers.go:327]     Cache-Control: no-store
I0526 18:15:11.097576   18433 round_trippers.go:327]     Content-Type: application/json
I0526 18:15:11.097579   18433 round_trippers.go:327]     Date: Thu, 26 May 2016 22:15:11 GMT
I0526 18:15:11.097603   18433 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.2.2.2:443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.2.2.2:443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.2.2.2:443"}]}]}
I0526 18:15:11.098361   18433 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0 (linux/amd64) kubernetes/6e83535" https://10.2.2.2:8443/api/v1/namespaces/ci/pods
I0526 18:15:11.100156   18433 round_trippers.go:318] GET https://10.2.2.2:8443/api/v1/namespaces/ci/pods 200 OK in 1 milliseconds
I0526 18:15:11.100181   18433 round_trippers.go:324] Response Headers:
I0526 18:15:11.100185   18433 round_trippers.go:327]     Cache-Control: no-store
I0526 18:15:11.100188   18433 round_trippers.go:327]     Content-Type: application/json
I0526 18:15:11.100191   18433 round_trippers.go:327]     Date: Thu, 26 May 2016 22:15:11 GMT
I0526 18:15:11.100229   18433 request.go:870] Response Body: {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/ci/pods","resourceVersion":"3283"},"items":[{"metadata":{"name":"jenkins-1-80a94","generateName":"jenkins-1-","namespace":"ci","selfLink":"/api/v1/namespaces/ci/pods/jenkins-1-80a94","uid":"6ce9b72d-237b-11e6-aed0-525400b263eb","resourceVersion":"3177","creationTimestamp":"2016-05-26T19:52:49Z","labels":{"deployment":"jenkins-1","deploymentconfig":"jenkins","name":"jenkins"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"ci\",\"name\":\"jenkins-1\",\"uid\":\"6afcb551-237b-11e6-aed0-525400b263eb\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1190\"}}\n","openshift.io/deployment-config.latest-version":"1","openshift.io/deployment-config.name":"jenkins","openshift.io/deployment.name":"jenkins-1","openshift.io/scc":"anyuid"}},"spec":{"volumes":[{"name":"jenkins-data","persistentVolumeClaim":{"claimName":"jenkins"}},{"name":"default-token-nefz2","secret":{"secretName":"default-token-nefz2"}}],"containers":[{"name":"jenkins","image":"openshift/jenkins-1-centos7@sha256:9ccb680436a4216c560101b6e39add505e13c72bd098c4c3b71191d19b9ca3b9","env":[{"name":"JENKINS_PASSWORD","value":"password"}],"resources":{"limits":{"memory":"1Gi"},"requests":{"memory":"1Gi"}},"volumeMounts":[{"name":"jenkins-data","mountPath":"/var/lib/jenkins"},{"name":"default-token-nefz2","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"livenessProbe":{"httpGet":{"path":"/login","port":8080,"scheme":"HTTP"},"initialDelaySeconds":60,"timeoutSeconds":3,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/login","port":8080,"scheme":"HTTP"},"initialDelaySeconds":3,"timeoutSeconds":3,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["MKNOD","SYS_CHROOT"]},"privileged":false,"seLinuxOptions":{"level":"s0:c6,c5"}}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","host":"origin","serviceAccountName":"default","serviceAccount":"default","nodeName":"origin","securityContext":{"seLinuxOptions":{"level":"s0:c6,c5"}},"imagePullSecrets":[{"name":"default-dockercfg-uk5hi"}]},"status":{"phase":"Running","conditions":[{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2016-05-26T21:58:49Z"}],"hostIP":"10.0.2.15","podIP":"172.17.0.6","startTime":"2016-05-26T19:52:49Z","containerStatuses":[{"name":"jenkins","state":{"running":{"startedAt":"2016-05-26T19:53:16Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"openshift/jenkins-1-centos7@sha256:9ccb680436a4216c560101b6e39add505e13c72bd098c4c3b71191d19b9ca3b9","imageID":"docker://be39895d3238450415a4c5acf2df4add4c39412f08df6bb9ae2c2ef6cec06729","containerID":"docker://217d682a01ea370174134c6a5482291c88bfca59675d6a186b8a0e2e5ddb7950"}]}}]}
I0526 18:15:11.101289   18433 meta.go:46] Calling Accessor on non-internal object: *api.PodList
I0526 18:15:11.101419   18433 cached_discovery.go:80] returning cached discovery info from /root/.kube/10.2.2.2_8443/servergroups.json
I0526 18:15:11.101464   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/autoscaling/v1/serverresources.json
I0526 18:15:11.101512   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/batch/v1/serverresources.json
I0526 18:15:11.101634   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/extensions/v1beta1/serverresources.json
I0526 18:15:11.101983   18433 cached_discovery.go:38] returning cached discovery info from /root/.kube/10.2.2.2_8443/v1/serverresources.json
NAME              READY     STATUS    RESTARTS   AGE
jenkins-1-80a94   1/1       Running   0          2h
````

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton PTAL

/cc @jorgemoralespou 

fixes #9052

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster

**Comment by stevekuznetsov** [comment]
Didn't we "fix" that with the RAMdisk?

**Comment by smarterclayton** [comment]
This is the race.  Someone needs to be waiting for the cache probably.

On May 28, 2016, at 9:30 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Didn't we "fix" that with the RAMdisk?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9056#issuecomment-222308706>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p0F2kGZr0NZ6zGKe4A2YeX04hs47ks5qGEN-gaJpZM4Ioeta>
.

**Comment by fabianofranz** [comment]
re[merge]

**Comment by stevekuznetsov** [comment]
@smarterclayton honestly we could just force-merge this since it's a tiny change and we're just wasting our time and AWS money running tests on it

**Comment by smarterclayton** [comment]
These are new flakes, are there issues opened?

[merge]

**Pull request merged**
