### PR TITLE
Injecting new required vars into origin.spec file

### PR DESCRIPTION
**Pull request by DanyC97**
Cherry pick of https://github.com/openshift/origin/pull/20503 from 3.10 branch

### CODE REVIEW

**Comment by DanyC97** [comment]
@sdodson pls help review, just getting the PR you pushed to 3.10 to master too so we don't bump into this issue when will build 3.11

**Comment by DanyC97** [comment]
@jupierce @adammhaile fyi too

**Comment by sdodson** [comment]
I hadn't realized this wasn't on master branch before opening it on release-3.10.

**Comment by DanyC97** [comment]
is anything needed @sdodson to get this merged ?

**Comment by sdodson** [comment]
/assign @tbielawa 
do you mind approving this? You're probably the person closest to this topic area in the OWNERS file.

**Comment by DanyC97** [comment]
thank you all for staying on top on this PR

**Pull request merged**
