### PR TITLE
Push origin-cluster-capacity image to docker hub.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@stevekuznetsov  @derekwaynecarr @eparis @jpeeler

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by aveshagarwal** [comment]
[test]

**Comment by aveshagarwal** [comment]
who can help here? @stevekuznetsov @eparis

**Comment by eparis** [comment]
[test]

**Comment by aveshagarwal** [comment]
Do we need to apply merge tag again?

**Comment by eparis** [comment]
@aveshagarwal https://github.com/openshift/origin/pull/14501#issuecomment-306617334

**Comment by aveshagarwal** [comment]
@eparis yeah I knew, I was not sure that if we need to do it again or not. As its been some time after tests passed and nothing seemed to move. thanks.

**Comment by smarterclayton** [comment]
I had to push it anyway for the release.

**Comment by aveshagarwal** [comment]
https://hub.docker.com/u/openshift/origin-cluster-capacity/ is still returning 404.

**Comment by aveshagarwal** [comment]
nvm, the image is available now https://hub.docker.com/r/openshift/origin-cluster-capacity/.

**Pull request merged**
