### PR TITLE
[release-4.2] Bug 1762658: UPSTREAM: 83747: Improve efficiency of csiMountMgr.GetAttributes

### PR DESCRIPTION
**Pull request by bertinatto**
This backport was requested by @JohnStrunk:

https://bugzilla.redhat.com/show_bug.cgi?id=1745773

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
CC @openshift/storage @JohnStrunk 

Please note that this patch is based on a bit different from the [upstream one](https://github.com/kubernetes/kubernetes/pull/83747/files). Backporting the upstream patch as is would mean backporting many other PRs, among them: https://github.com/kubernetes/kubernetes/pull/68513 and https://github.com/kubernetes/kubernetes/pull/76456/

**Comment by bertinatto** [comment]
/assign @knobunc 
PTAL

**Comment by knobunc** [comment]
@eparis can you approve this please?

**Comment by JohnStrunk** [comment]
Checking back on this... Can we get this merged, please?
... or has the backport been denied?
@knobunc @eparis

**Comment by bertinatto** [comment]
/assign @mfojtik 
Could you take a look at this, please?

**Pull request merged**
