### PR TITLE
Temporarily mark the router prometheus metrics test as flaky

### PR DESCRIPTION
**Pull request by ironcladlou**
A fix will be forthcoming.

/cc @openshift/sig-network-edge @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
/retest

Will force merge if it doesn’t pass

**Comment by deads2k** [comment]
merging to help unstick our queue.

**Comment by ironcladlou** [comment]
Monday I'll get these flaky tags moved out to `test.go` and associate them with BZs to make sure we don't lose track

**Pull request merged**
