### PR TITLE
Cleanup the STI and Docker build output

### PR DESCRIPTION
**Pull request by mfojtik**
* Added 'Successfully pushed' message
* Move some Secrets messages to V(3)

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh @bparees just minor fixes to make the build output look more compact. The main issue this PR is fixing is that at this moment you don't know (from the build log output) that the push finished, which looks like a bug from the user side.

**Comment by mfojtik** [comment]
@jhadvig PTAL

**Comment by mfojtik** [comment]
(hold on, i'll push more ;-)

**Comment by jhadvig** [comment]
@mfojtik LGTM
Thanks for the refactoring, looks better now :+1:

**Comment by mfojtik** [comment]
[merge]

**Comment by bparees** [comment]
lgtm but jenkins disagrees.

**Comment by mfojtik** [comment]
[merge] again?

**Pull request merged**
