### PR TITLE
s2i bump

### PR DESCRIPTION
**Pull request by soltysh**
Do not merge until I have the link with latest sti release confirmed. @bparees ptal

### CODE REVIEW

**Comment by soltysh** [comment]
[test] in the mean time.

**Comment by soltysh** [comment]
The release was fixed for s2i, which is the reason the tests failed previously.
Now re-[test].

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by soltysh** [comment]
The failure doesn't look related to the changes I've made in this PR.
re-[merge]

**Comment by soltysh** [comment]
Again experienced failure mentioned in #3624.
re-[merge]

**Pull request merged**
