### PR TITLE
NO-JIRA: Add test case for namespaced filename in oc process

### PR DESCRIPTION
**Pull request by ardaguclu**
There is no test in cli template tests to assure that namespace
is handled correctly, when the template contains a different namespace
in `oc process -f` command.

This PR adds this.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve
/hold
for https://github.com/openshift/oc/pull/1612, and to see failure first

**Comment by ardaguclu** [comment]
`[sig-cli] templates process [apigroup:apps.openshift.io][apigroup:template.openshift.io][Skipped:Disconnected] [Suite:openshift/conformance/parallel] ` test failed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28440/pull-ci-openshift-origin-master-e2e-aws-ovn-fips/1731993253609213952 as expected.

**Comment by ardaguclu** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28440/pull-ci-openshift-origin-master-e2e-aws-ovn-fips/1732263743598891008 passed and the failing jobs seem unrelated;

/hold cancel
@ingvagabund could you please take a look at, when you have a chance?. Thanks.

**Pull request merged**
