### PR TITLE
Revert "skip tsb tests on GCE until new images are published"

### PR DESCRIPTION
**Pull request by deads2k**
This reverts commit 3e9c66cc1449f691751bd9cb20b1e7a0e7b0a028.

### CODE REVIEW

**Comment by bparees** [comment]
now aren't you glad you made this a separate commit? :)

/lgtm

**Comment by deads2k** [comment]
@smarterclayton can I get a new tagged level for GCE?

**Comment by smarterclayton** [comment]
Yeah, probably not until tomorrow or Friday.

**Pull request closed without merging**
