### PR TITLE
[3.6] Fix issues related to the migration to RBAC and the Kubernetes authorizer

### PR DESCRIPTION
**Pull request by enj**
Cherry-pick of #15342 into release-3.6

@liggitt PTAL

[test]

### CODE REVIEW

**Comment by liggitt** [comment]
[merge][severity:blocker]

**Comment by enj** [comment]
```
298352003e9e: Download complete
298352003e9e: Pull complete
e5186cffb433: Pull complete
0d1b21a54419: Pull complete
Digest: sha256:7685193b578d85619f3985425fad8b30f050a5318cb8687189e402afabf10470
+ ../../bin/local.sh ansible-playbook -e provision_gce_docker_storage_driver=overlay2 -e openshift_test_repo=https://storage.googleapis.com/origin-ci-test/pr-logs/pull/15348/test_pull_request_origin_extended_conformance_gce/4477/artifacts/rpms playbooks/launch.yaml
Activated service account credentials for: [jenkins-ci-provisioner@openshift-gce-devel.iam.gserviceaccount.com]
ERROR! Attempted to execute "/usr/share/ansible/openshift-ansible-gce/inventory.sh" as inventory script: Inventory script (/usr/share/ansible/openshift-ansible-gce/inventory.sh) had an execution error: Traceback (most recent call last):
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 400, in <module>
    GceInventory()
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 132, in __init__
    print(self.json_format_dict(self.group_instances(zones),
  File "/usr/share/ansible/openshift-ansible-gce/inventory/gce/hosts/gce.py", line 320, in group_instances
    nodes = self.driver.list_nodes()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2419, in list_nodes
    use_disk_cache=ex_use_disk_cache)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 8366, in _to_node
    bd['name'], bd['zone'], use_cache=use_disk_cache)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7109, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7405, in _ex_lookup_volume
    self._ex_populate_dict()
AttributeError: 'GCENodeDriver' object has no attribute '_ex_populate_dict'
 
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: PROVISION TEST CLUSTER [00h 00m 35s] ##########
```

@stevekuznetsov @sdodson @jupierce wat?

**Comment by stevekuznetsov** [comment]
@enj this is our catchall for that I believe

https://github.com/openshift/origin/issues/14575

**Comment by enj** [comment]
re[merge] flake #14575

**Comment by liggitt** [comment]
[test]

**Comment by enj** [comment]
@derekwaynecarr @smarterclayton @liggitt this seems to be broken on #15252

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/15252 was to reenable tests disabled as part of the rebase. IIRC, those two had just been enabled a couple weeks earlier after having been disabled for being flaky. 

Since this is against release-3.6, it's clearly unaffected by the rebase. Were we wrong to enable those tests for 3.6?

**Comment by liggitt** [comment]
[merge][test] GCE PV fix was merged for ansible

**Comment by enj** [comment]
Still broken on `StatefulSet` issues...

**Comment by liggitt** [comment]
required an image rebuild/repush, got updated around 5:30pm. [test][merge]

**Comment by enj** [comment]
xref openshift/openshift-ansible/pull/4841

**Pull request merged**
