### PR TITLE
OCPBUGS-8092: Fix mounted volume expansion tests

### PR DESCRIPTION
**Pull request by bertinatto**
- Bump (openshift/kubernetes): to get openshift/kubernetes#1498. Generated with: `hack/update-kube-vendor.sh 7d98b1aa513462643491f4ddc6607d523a896788`
- Revert b3a00d8

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
> /override ci/prow/e2e-aws-ovn-serial /override ci/prow/e2e-aws-ovn-fips
> 
> These are known broken right now.

Re-doing this, they back running again.

/override ci/prow/e2e-aws-ovn-serial
/override ci/prow/e2e-aws-ovn-fips

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips 
this will help unblock the queue and fips failures are known, I don't have issue though :disappointed:

**Pull request merged**
