### PR TITLE
bump(github.com/fsouza/go-dockerclient) 1399676f53e6ccf46e0bf00751b21bed329bc60e

### PR DESCRIPTION
**Pull request by pmorie**
Temporary carry PR for kubernetes/kubernetes#15127

@swagiaal @pweil-

### CODE REVIEW

**Comment by liggitt** [comment]
is this paired with a bump in k8s?

**Comment by pmorie** [comment]
@liggitt It is, and that bump will come in with the next rebase.

**Comment by liggitt** [comment]
not sure what to name the commit for this... `bump(...): ...`?

**Comment by pmorie** [comment]
@deads2k ^^ tell us your innermost desires (pertaining to commit names for this PR)

**Comment by deads2k** [comment]
See the format here: https://github.com/openshift/origin/pull/5143/commits.  Just call it a bump

**Comment by pmorie** [comment]
Reformatted.

**Comment by pmorie** [comment]
@deads2k @liggitt

**Comment by deads2k** [comment]
Picked up in rebase here: https://github.com/openshift/origin/commit/05a334f83f8896fee09efc6f0357d52389a13195

**Pull request closed without merging**
