### PR TITLE
Removing utf-8 file in extended build test

### PR DESCRIPTION
**Pull request by adambkaplan**
Non-ascii characters break tito.

/assign @sosiouxme

### CODE REVIEW

**Comment by adambkaplan** [comment]
See https://github.com/openshift/origin/pull/22388#discussion_r269767940

**Comment by adambkaplan** [comment]
/cc @gabemontero 
fyi @openshift/sig-developer-experience

**Comment by sosiouxme** [comment]
/lgtm
much appreciated

**Comment by gabemontero** [comment]
@adambkaplan - so unless  the `tito` dependency @sosiouxme mentioned resolves anytime soon, does it make sense to try the https://github.com/openshift/origin/blob/master/test/cmd/builds.sh approach I mentioned in the original PR ?

**Comment by adambkaplan** [comment]
@gabemontero I think we'll run into the same issue with tito - that approach will also need a file with UTF-8 names.

My plan B is to do a white-box test that verifies the default build pod has the LANG env var set to something that has "utf8" in it.

**Comment by sosiouxme** [comment]
For background (and to watch for when tito gets a fix): https://github.com/dgoodwin/tito/issues/335

**Comment by sosiouxme** [comment]
/retest
Please keep an eye on this and keep pushing it... I hacked around this for our build today but it will be a pain to keep doing that.

**Pull request merged**
