### PR TITLE
declared variables better for RHEL

### PR DESCRIPTION
**Pull request by stevekuznetsov**
fixes https://github.com/openshift/origin/issues/6456

@liggitt PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
flake on `TestAuthorizationSubjectAccessReview` [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8083/console):
```
I1222 14:00:15.624786   19202 etcd.go:37] Deleting &etcd.Node{Key:"/kubernetes.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x33b, CreatedIndex:0x33b} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc208899620), (*etcd.Node)(0xc208899680)}, ModifiedIndex:0x0, CreatedIndex:0x0})
I1222 14:00:19.803916   19202 etcd.go:37] Deleting &etcd.Node{Key:"/openshift.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x342, CreatedIndex:0x342} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc208899620), (*etcd.Node)(0xc208899680)}, ModifiedIndex:0x0, CreatedIndex:0x0})
F1222 14:00:28.986945   19202 etcd.go:39] Unable to delete key: 100: Key not found (/openshift.io) [1111]
```

https://github.com/openshift/origin/issues/6065

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
e2e flake [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8090/console):
```
Error from server: 501: All the given peers are not reachable (failed to propose on members [https://172.18.7.236:4001] twice [last error: Unexpected HTTP status code]) [0]
!!! Error in hack/../test/end-to-end/core.sh:160
	'oc delete pod cli-with-token' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:160 main(...)
Exiting with status 1
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
```

#6447

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
Either https://github.com/openshift/origin/issues/6149 or https://github.com/openshift/origin/issues/6447 [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8095/), unclear

re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
@liggitt Is there anything else this needs?

**Comment by stevekuznetsov** [comment]
@liggitt bump

**Comment by liggitt** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@liggitt  please re-tag

**Pull request merged**
