### PR TITLE
[release-4.8] Bug 1989402: Add tests required internet into Skipped:Disconnected list

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR adds tests, required internet access and fails in disconnected environment, into the [Skipped:Disconnected] list.

This PR is backport of https://github.com/openshift/origin/pull/26051

### CODE REVIEW

**Comment by ardaguclu** [comment]
/assign @knobunc 
Could you please take a look at this backport?. Thanks.

**Comment by ingvagabund** [comment]
lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

adding cherry-pick approved

**Pull request merged**
