### PR TITLE
UPSTREAM Decrease columns and refactor get pods layout

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Upstream:
https://github.com/GoogleCloudPlatform/kubernetes/pull/9032

This is now much easier to read:

```shell
# openshift cli get pods
NAME                      READY     REASON    RESTARTS   AGE
docker-registry-1-r4gw5   1/1       Running   0          5h
```

I had to modify the upstream slightly since we do not have the internal rename of Container.State.Termination -> Container.State.Terminated.

@smarterclayton please review.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Comment by ncdc** [comment]
@smarterclayton @derekwaynecarr need to fix how we get the name of the registry pod https://github.com/openshift/origin/blob/master/hack/test-end-to-end.sh#L375 now that the labels aren't shown any more.

**Comment by derekwaynecarr** [comment]
@ncdc - ahh, our tests need to use Go templates... I just harassed @deads2k on a similar issue.

**Comment by ncdc** [comment]
@derekwaynecarr agreed, although in this case because the registry pod is from an RC, the name isn't consistent so a grep was a quick and easy win

**Comment by derekwaynecarr** [comment]
@ncdc - I will buy you a GitHub beer if you can give me the corresponding Go template, or grep command I can use against yaml output ;-)

**Comment by ncdc** [comment]
@derekwaynecarr maybe use

```
oc get pod -l deploymentconfig=docker-registry -t '{{(index .items 0).metadata.name}}'
```

(I had forgotten about label selectors!)

**Comment by derekwaynecarr** [comment]
@ncdc :beers: 

re [merge]

**Pull request merged**
