### PR TITLE
test/upgrade: Validate that we have exactly 3 boots

### PR DESCRIPTION
**Pull request by cgwalters**
Part of validating
https://github.com/openshift/machine-config-operator/pull/2112

We discovered a somewhat rare race condition where the MCO
can cause at least one control plane node to update more than once during
an upgrade.

This is obviously a fairly hardcoded test...if we e.g. ever
rework how the initial pivot works this will need more
thought, but for now I think this should work.

### CODE REVIEW

**Comment by cgwalters** [comment]
Honestly I am not very familiar with the test suite frameworks here; it looks like there's some sort of conflict with using `exutil`...ah, wait maybe it can only be instantiated once?  The `README.md` sort of implies this, let me try that...

**Comment by cgwalters** [comment]
Maybe something like this?
```
diff --git a/test/e2e/upgrade/upgrade.go b/test/e2e/upgrade/upgrade.go
index 61ab9b4273..5e7366659c 100644
--- a/test/e2e/upgrade/upgrade.go
+++ b/test/e2e/upgrade/upgrade.go
@@ -124,6 +124,7 @@ var _ = g.Describe("[sig-arch][Feature:ClusterUpgrade]", func() {
 		framework.ExpectNoError(err)
 		client := configv1client.NewForConfigOrDie(config)
 		dynamicClient := dynamic.NewForConfigOrDie(config)
+		oc := exutil.NewCLI("upgrade")
 
 		upgCtx, err := getUpgradeContext(client, upgradeToImage)
 		framework.ExpectNoError(err, "determining what to upgrade to version=%s image=%s", "", upgradeToImage)
@@ -136,7 +137,7 @@ var _ = g.Describe("[sig-arch][Feature:ClusterUpgrade]", func() {
 			upgradeTests,
 			func() {
 				for i := 1; i < len(upgCtx.Versions); i++ {
-					framework.ExpectNoError(clusterUpgrade(f, client, dynamicClient, config, upgCtx.Versions[i]), fmt.Sprintf("during upgrade to %s", upgCtx.Versions[i].NodeImage))
+					framework.ExpectNoError(clusterUpgrade(f, client, dynamicClient, oc, config, upgCtx.Versions[i]), fmt.Sprintf("during upgrade to %s", upgCtx.Versions[i].NodeImage))
 				}
 			},
 		)
@@ -237,7 +238,7 @@ func getUpgradeContext(c configv1client.Interface, upgradeImage string) (*upgrad
 
 var errControlledAbort = fmt.Errorf("beginning abort")
 
-func clusterUpgrade(f *framework.Framework, c configv1client.Interface, dc dynamic.Interface, config *rest.Config, version upgrades.VersionContext) error {
+func clusterUpgrade(f *framework.Framework, c configv1client.Interface, dc dynamic.Interface, oc *exutil.CLI, config *rest.Config, version upgrades.VersionContext) error {
 	fmt.Fprintf(os.Stderr, "\n\n\n")
 	defer func() { fmt.Fprintf(os.Stderr, "\n\n\n") }()
 
@@ -251,8 +252,6 @@ func clusterUpgrade(f *framework.Framework, c configv1client.Interface, dc dynam
 	}
 
 	kubeClient := kubernetes.NewForConfigOrDie(config)
-	oc := exutil.NewCLI("upgrade")
-	defer g.GinkgoRecover()
 
 	// this is very long.  We should update the clusteroperator junit to give us a duration.
 	maximumDuration := 150 * time.Minute
```

**Comment by cgwalters** [comment]
The error says `fail [github.com/openshift/origin/test/extended/util/client.go:133]: You may only call AfterEach from within a Describe, Context or When` but the toplevel seems like it's inside a `var _ = g.Describe("[sig-arch][Feature:ClusterUpgrade]", func() `.  But maybe some level of indirection here is losing that?

**Comment by cgwalters** [comment]
That time the SDN fell over looks like
/test e2e-gcp-upgrade

**Comment by deads2k** [comment]
/test all

this seems like a good test to have.

**Comment by cgwalters** [comment]
/hold 
this code is broken and I haven't debugged why yet

**Pull request closed without merging**
