### PR TITLE
e2e: Add a test to verify no crashlooping pods

### PR DESCRIPTION
**Pull request by smarterclayton**
During the e2e runs, no pods in kube-* or openshift-* should be unhealthy
or be failing.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@derekwaynecarr @wking @crawford this will prevent crash loop regressions (mostly) in the e2e-aws jobs across clusters.

Telemeter is currently broken - @s-urbaniak / @squat how do you want to handle telemetry crash looping?  An exception for now that we remove when CI handles it?  Skip creating the telemetry client if no token exists?

**Comment by squat** [comment]
@smarterclayton id prefer not to go down the route of creating exceptions and risk encouraging that. Telemeter is never supposed to work without a token so let’s be explicit and not deploy telemeter if no token exists.

**Comment by s-urbaniak** [comment]
@smarterclayton agreed to what @squat said :+1:

**Comment by smarterclayton** [comment]
Telemetry team is going to diagnose and fix (outside discussions)

**Comment by smarterclayton** [comment]
Actually, this test won't pass on the old installer if we don't fix both directions (don't deploy if no pull secret AND correct whatever error is preventing us from deploying when we do a have a pull secret)

**Comment by s-urbaniak** [comment]
xref: https://github.com/openshift/cluster-monitoring-operator/pull/157

**Comment by s-urbaniak** [comment]
@smarterclayton not sure why this still fails here, but https://github.com/openshift/cluster-monitoring-operator/pull/157 landed and we check the config now explicitly to skip creating the telemeter client if no token (and cluster ID) is being configured.

**Comment by smarterclayton** [comment]
I'll bring up a cluster but I was seeing this even today.

**Comment by smarterclayton** [comment]
well, telemetry is fixed but now 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21496/pull-ci-openshift-origin-master-e2e-aws/930#openshift-tests-featureplatformsuiteopenshiftsmoke-4-managed-cluster-should-have-no-crashlooping-pods-in-core-namespaces-over-two-minutes-suiteopenshiftconformanceparallel cluster autoscaler is broken @openshift/sig-cloud

**Pull request merged**
