### PR TITLE
Deprecated evacuate in favor of drain node

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/11310

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis @smarterclayton PTAL

**Comment by soltysh** [comment]
LGTM

**Comment by kargakis** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
@sdodson dunno if ansible use evacuate, but you might consider switching it.

**Comment by sdodson** [comment]
> @sdodson dunno if ansible use evacuate, but you might consider switching it.

we do, thanks. Just to be clear this is deprecated in 1.4 and removed in 1.5?

**Comment by smarterclayton** [comment]
Does drain do everything that evacuate does?  If there are gaps, we can't
remove until the gaps are closed.

On Nov 7, 2016, at 6:36 AM, Scott Dodson <notifications@github.com> wrote:

@sdodson <https://github.com/sdodson> dunno if ansible use evacuate, but
you might consider switching it.

we do, thanks. Just to be clear this is deprecated in 1.4 and removed in
1.5?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/11803#issuecomment-258851520>,
or mute
the thread

**Pull request merged**
