### PR TITLE
hash access and authorize tokens

### PR DESCRIPTION
**Pull request by liggitt**
**Goals**

1. Allow storing hashes of authorization and access tokens, rather than token values
2. Allow sharding tokens by user to pave the way for user-management of their own API tokens

**API changes**
Three new fields are added to OAuthAccessToken and OAuthAuthorizeToken objects:

1. `token`: populated with the secret bearer token or authorization code only when returning the object from the initial create API call. This field is never persisted.
2. `salt`: populated by the server with random data when creating a hashed token
3. `saltedHash`: populated by the server with `hash(salt+secret)` when creating a hashed token

To create a hashed token, submit an API creation request with no metadata.name set.

**Server-side procedure for creating a hashed token**

1. Make a secret and secret hash:

    ```
    secret = base64(32 random bytes))
    secretHash = sha256(s)
    ```

2. Make a user hash:

    ```
    userHash = sha256(token.userName)
    ````

3. Make a salted hash:

    ```
    salt = base64(32 random bytes))
    saltedHash = sha256(salt+secret)
    ```

4. Make the name of the token object an unsigned JWT containing claims holding the `secretHash` and `userHash` values. This allows the storage layer to shard by user without exposing the user name or making the name of the token a secret.

    ```
    tokenName = jwt({sh:secretHash, uh:userHash})
    ```

5. Make the bearer token an unsigned JWT containing claims holding the `secret` and `userHash` values. This allows extracting these values, deriving `secretHash` to look up the token object, and once the token object is retrieved, deriving `saltedHash` to verify the passed `secret`.

    ```
    bearerToken = jwt({s:secret, uh:userHash})
    ```

6. Return the token:

    ```yaml
      metadata:
        name: <tokenName>
      token: <bearerToken> (unpersisted)
      salt: <salt>
      saltedHash: <saltedHash>
    ```

7. The client creating the object uses the value in the `token` field as the bearer token. Because that value is not persisted, it cannot be accessed again.

**Storage changes**

Legacy tokens are stored in etcd under `<prefix>/<metadata.name>`

New tokens are stored in etcd under `<prefix>/<userHash>/<secretHash>`

The storage keyFunction attempts to parse the token name as a JWT and extract values for the `userHash` (`uh` claim), `secret` (`s` claim), and `secretHash` (`sh` claim) from the JWT.

If the secret is specified and the secretHash is not, the secretHash is derived from the secret. This allows the token object to be looked up using the bearerToken.

If the token name cannot be parsed as a JWT or the userHash and secretHash cannot be determined from the claims, the legacy key path is used.

**Authentication**

1. The token object is retrieved from storage, using the presented bearer token as a name (see *Storage changes* section for explanation of why this works for both legacy and new tokens).
2. If the token is not found, authentication fails.
3. If the token is found, and the token object's `salt` and `saltedHash` fields are empty, authentication succeeds.
4. If the `salt` or `saltedHash` fields are non-empty, the `secret` claim is extracted from the presented bearer token. If the bearer token fails to parse as a JWT or does not contain a secret claim, authentication fails.
5. The `saltedHash` is verified by comparing against `hash(token.salt + secret claim)`. If identical, authentication succeeds. Otherwise, authentication fails.

**Creation**

To create a hashed token, create a token API object without specifying a name.

The returned token object will have its metadata.name set to a value that cannot be used as a bearer token, and a token field containing a value which can.

The token field is only returned from the create API request and is not persisted.

**Hash algorithms**

- The only algorithm initially is `sha256`. The algorithm used for the hashes in the token name and bearer token JWT claims (and therefore the storage path) are not intended to be changeable. The algorithm used for the saltedHash could be modified later with the addition of a `saltedHashAlgorithm` field in the token object.

**Compatibility**

- The token authenticator falls back to looking for unhashed token objects if a hashed lookup fails. This means old tokens can be used against new masters.

- Token objects can be deleted by their name or by their bearer token value

- Old masters will not be able to validate tokens stored in hashed objects, since they do not know how to look up a token object with a hashed name. Options:
  - No mitigation. Tokens obtained from a new master during a rolling upgrade will not work against an old master still in rotation.
  - Default hashing off, require explicit enablement. Would require a second round of config changes/restarts after a rolling upgrade.
  - ...

TODO:

Should we allow logging out by deleting a hashed token name? Currently, logging out by deleting the token is allowed because knowledge of the name means you hold the bearer token. That is no longer the case when the name is a hash and is not considered a credential any more

- [ ] test watch with this alternate storage path
- [ ] refactor the `none` jwt algorithm and claim parsing
- [ ] unit tests
- [ ] resolve issue with short reads from rand.Reader

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by liggitt** [comment]
flaked on https://github.com/openshift/origin/issues/10173, re[test]

**Comment by liggitt** [comment]
[test]

**Comment by enj** [comment]
cc @npmccallum b/c you asked 😄

**Pull request closed without merging**
