### PR TITLE
Revert parallel Docker builds

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This reverts https://github.com/openshift/origin/pull/12218 and https://github.com/openshift/origin/pull/12229 to address https://github.com/openshift/origin/issues/12236. 

@deads2k PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton @bparees the linked issue suggests reversion.  I don't see a followup that fixes the problem.  Any reason not to merge this?

[test]

**Comment by stevekuznetsov** [comment]
Generated with:
```
$ git revert f8b5dd6fe2b1e1e584e1f790435bcf9a98bf3eb3 -m 1
$ git revert b61cf87413a73268ff35fdeec0bade6b2e6eb61e -m 1
```

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@smarterclayton @bparees tagged for merge.  If there's another fix, please link it when you remove the tag.

**Comment by smarterclayton** [comment]
I merged yesterday.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/12229 was the revert of parallelism

**Comment by stevekuznetsov** [comment]
Wow that's incredibly difficult to determine. Cool.

**Comment by stevekuznetsov** [comment]
@smarterclayton we're seeing router-related issues like: https://github.com/openshift/origin/pull/11644#issuecomment-266780360

 What's going on?

**Comment by smarterclayton** [comment]
Probably unrelated, positive it's not related to that PR?

On Dec 13, 2016, at 1:00 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> we're seeing
router-related issues like: #11644 (comment)
<https://github.com/openshift/origin/pull/11644#issuecomment-266780360>

What's going on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12246#issuecomment-266813068>,
or mute
the thread

**Comment by stevekuznetsov** [comment]
Not entirely sure, I had some people ask me about the router flake this morning but it _looks_ like they all happened late yesterday. If only we had some metrics ...

**Pull request closed without merging**
