### PR TITLE
Add upgrade-aware HTTP proxy

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton I added a 2nd commit with some refactoring to break up the big methods into smaller ones that hopefully will be more easily testable. Please let me know what you think. I'll squash if you like it better.

**Comment by smarterclayton** [comment]
Looks fine, have you tested?

**Comment by ncdc** [comment]
Squashed & updated. Yes, it works :-)

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
