### PR TITLE
add debugging that will list the different items in a watch

### PR DESCRIPTION
**Pull request by deads2k**
@openshift/sig-network-edge @eparis I haven't tried this, but I think that it wires glog up to your informers to get definitive proof about missing notifications.

### CODE REVIEW

**Comment by deads2k** [comment]
@openshift/sig-networking wrong networknig team

**Comment by danwinship** [comment]
/lgtm
(so the bot will keep re-running tests if they fail)

/hold

**Comment by danwinship** [comment]
The bug that this was supposed to help debug seems to have been fixed somehow?

In case the bug comes back, https://gist.github.com/danwinship/3fafddfeb87371f1636c33357bf63195 will check the SDN pod logs from this PR for "errors". (The expected output is nothing; it only prints something if it finds something wrong in the logs.)

**Pull request closed without merging**
