### PR TITLE
[3.10] ImageGC fixes

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/70647
https://github.com/kubernetes/kubernetes/pull/75367

3.11 PRs:
https://github.com/openshift/origin/pull/22154
https://github.com/openshift/origin/pull/22629

@sferich888 @soukron @derekwaynecarr 

supercedes https://github.com/openshift/origin/pull/22500 that doesn't include https://github.com/kubernetes/kubernetes/pull/75367

### CODE REVIEW

**Comment by sjenning** [comment]
unit test flake https://github.com/openshift/origin/issues/20295
/retest

**Comment by sjenning** [comment]
`TestRegistryClient` flakes
/test integration

**Comment by sjenning** [comment]
TestRegistryClient failure again

**Comment by soukron** [comment]
@sjenning the tests fail even with a change in the README. I already reported in a different issue. Not pull requests will be validated until https://github.com/openshift/origin/issues/22639 is fixed.

**Pull request merged**
