### PR TITLE
 UPSTREAM: 58089: Create proper volumeSpec during ConstructVolumeSpec

### PR DESCRIPTION
**Pull request by jsafrane**
https://bugzilla.redhat.com/show_bug.cgi?id=1612783
https://github.com/kubernetes/kubernetes/pull/58089

@openshift/sig-storage

### CODE REVIEW

**Comment by bertinatto** [comment]
The failing test seems to be a problem in the installer. It's trying to create a tar of OpenShift examples from a non-existent directory:

```
TASK [openshift_examples : Create tar of OpenShift examples] *******************
Thursday 30 August 2018  15:49:47 +0000 (0:00:01.821)       0:16:14.925 ******* 
fatal: [prtest-20891fe-333-ig-m-g0j7 -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-QcozMSj/openshift-examples.tar", "."], "delta": "0:00:00.612828", "end": "2018-08-30 15:49:48.516940", "msg": "non-zero return code", "rc": 2, "start": "2018-08-30 15:49:47.904112", "stderr": "tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}
```

**Comment by bertinatto** [comment]
@childsb, whom should we talk to regarding this [1]?

I know Jan filled a ticket about this error, but I don't know where.

[1] https://github.com/openshift/origin/pull/20768#issuecomment-417391820

**Comment by wongma7** [comment]
TASK [openshift_examples : Create tar of OpenShift examples] *******************
Thursday 13 September 2018  21:54:20 +0000 (0:00:00.847)       0:16:50.559 **** 
fatal: [prtest-20891fe-564-ig-m-fn5s -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-RKtfBj8/openshift-examples.tar", "."], "delta": "0:00:00.620208", "end": "2018-09-13 21:54:21.239608", "msg": "non-zero return code", "rc": 2, "start": "2018-09-13 21:54:20.619400", "stderr": "tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}

**Comment by jsafrane** [comment]
/close
will reopen in ose

**Pull request closed without merging**
