### PR TITLE
[RPMs] Add socat and util-linux dependencies for node

### PR DESCRIPTION
**Pull request by sdodson**
Resolves RHBZ 1213282

### CODE REVIEW

**Comment by sdodson** [comment]
@ncdc PTAL

**Comment by ncdc** [comment]
LGTM but I'd change the comment as I'm not yet 100% certain that the root cause of the bz is missing RPMs.

**Comment by sdodson** [comment]
I'll test and report back.

**Comment by sdodson** [comment]
Confirmed, lets merge. (I cannot)

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
