### PR TITLE
Fix apply for lists

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton PTAL

[test]

### CODE REVIEW

**Comment by deads2k** [comment]
Already merged upstream.

I think its too early for @liggitt  to shut down upstream picks, but just so he's aware: [merge]

**Comment by deads2k** [comment]
@kargakis one was already flagged as a flake, please check the other: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12122/consoleFull#71199567256c25df4e4b05b79524e5d52

**Comment by kargakis** [comment]
Haven't seen that one before and it doesn't seem related to this PR. Opened https://github.com/openshift/origin/issues/7738

[merge]

**Comment by smarterclayton** [comment]
This broke Macs - because `--suffix` is not supported on Mac bash.  Please fix without using --suffix

**Comment by smarterclayton** [comment]
`+workingdir=$(mktemp -d --suffix=registry)`

**Comment by kargakis** [comment]
@smarterclayton we are using --suffix [elsewhere](https://github.com/openshift/origin/blob/5bed7a306b01d3ce6cc9b07e71186eba7dd12fe2/test/cmd/policy.sh#L40) for quite some time, why did it break now?

**Comment by liggitt** [comment]
that merged 6 days ago... I don't think it has been used for long anywhere

**Comment by smarterclayton** [comment]
That other things is broken too.

**Comment by kargakis** [comment]
git blame fools people

**Pull request merged**
