### PR TITLE
Fix template use to generate javaconsole link in a pod template

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes issue #7948

@spadgett @jwforres @sg00dwin 

screen shot 2016-03-14 at 10 20 42 am

### CODE REVIEW

**Comment by spadgett** [comment]
Unsure about the external link icon. We want the Java console to feel integrated with OpenShift rather than something separate. Also it makes it look like it opens in a new window.

**Comment by spadgett** [comment]
@gashcrumb Which pod are you connecting to if there are multiple?

**Comment by gashcrumb** [comment]
@spadgett it should be grouped with the container

Agree about the icon, it does look like it's going to open a new window.

**Comment by spadgett** [comment]
> it should be grouped with the container

I guess I'm confused. If there is more than one pod in the deployment, each with a container, I'm not sure which I'm connecting to. Is there a way to select from multiple pods in the Java console?

**Comment by gashcrumb** [comment]
The link is per container, not pod...  So if you have a pod that consists of more than one container, you'd need a link for each one.

**Comment by benjaminapetersen** [comment]
- [ ] `fa-share` icon instead works for me.

Per the pod/container discussion, i was initially just planning on fixing the layout here, did we uncover something more significant?

**Comment by spadgett** [comment]
> The link is per container, not pod... So if you have a pod that consists of more than one container, you'd need a link for each one.

Right, I understand that. But if I have two pods, there are also two replicas of the _same_ container running, one for each pod. Which one I am connecting to?

**Comment by gashcrumb** [comment]
Ah, I see, didn't see that's the 'deployment' page.  The link originally was on the pod detail page, where you'd be looking at an individual pod and then can connect to a container.

**Comment by spadgett** [comment]
> Ah, I see, didn't see that's the 'deployment' page.

@gashcrumb Yeah, we need to make this more obvious in the UI. It's a usability problem. Worse now that we hide the secondary nav.

@benjaminapetersen Can you try with this and see where the link appears? I'd expect it to be on the browse pod page, not browse deployment.

> oc process -f http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-java-camel-spring/2.2.9.1/quickstart-java-camel-spring-2.2.9.1-kubernetes.json | oc create -f -

**Comment by benjaminapetersen** [comment]
@spadgett  can do,  `oc create -f` needs an arg, no?

**Comment by spadgett** [comment]
@benjaminapetersen It's piped from oc process.

**Comment by sg00dwin** [comment]
One related item, once this is changed in the ui, the screenshot in openshift docs should be updated.
https://docs.openshift.com/enterprise/3.1/architecture/infrastructure_components/web_console.html#jvm-console

**Comment by benjaminapetersen** [comment]
@spadgett ah, the trailling `-` indicates. thought that was a typo, ran it, and it complained.  Got it.

**Comment by jwforres** [comment]
squash and generate bindata, otherwise LGTM

**Comment by benjaminapetersen** [comment]
Updated icon:

screen shot 2016-03-15 at 11 28 48 am

**Comment by gashcrumb** [comment]
Looks great!

**Comment by benjaminapetersen** [comment]
Squashed & rebased.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
