### PR TITLE
switch to unprivileged pods for builds

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/cc @adambkaplan 

@nalind are you aware of any reason we would still need to be running the builder image as a privileged pod?  (I haven't tested this locally so we'll see what the PR test results are)

**Comment by nalind** [comment]
> @nalind are you aware of any reason we would still need to be running the builder image as a privileged pod? (I haven't tested this locally so we'll see what the PR test results are)

I think our main stumbling block has been around wanting to be able to mount overlay filesystems while inside of the build container to get speedier builds than we would with the vfs driver.

**Comment by rhatdan** [comment]
@nalind Can we experiment with the fuse-overlay to get the best of both worlds?

**Comment by nalind** [comment]
Can we use it inside of unprivileged containers on EL7-based nodes?

**Pull request closed without merging**
