### PR TITLE
Add goreportcard badge in README

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @danmcp

### CODE REVIEW

**Comment by smarterclayton** [comment]
Lgtm [merge] but only because we have an A+

**Comment by deads2k** [comment]
Not sure how I feel about being the first two hits for the cyclomatic complexity test.

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
extended failure was https://github.com/openshift/origin/issues/9076

[merge]

**Pull request merged**
