### PR TITLE
Remove v1beta1 annotation/label mapping

### PR DESCRIPTION
**Pull request by ironcladlou**
Remove unnecessary v1beta1 annotation/label mapping from the deployment
utility. It introduces at least 1 bug where a beta1 key is written and then
read as a beta3/v1 key, preventing the deployment controller from correctly
interpreting deployment status. The beta1 mapping is no longer needed.

Closes #3483

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by liggitt** [comment]
curious where the beta1 key was being written... would like to track that down first

**Comment by ironcladlou** [comment]
I'm still not entirely convinced we have a complete handle on how that key got persisted, but @deads2k had some logs showing it to be true, and we can see how if that key ends up present, we'll continue to read it while writing to the new key (which we'll never read due to the presence of the old key).

We can spend more time trying to figure that out, but the reality is we shouldn't be using those old annotations anywhere in the codebase. I've already found places in the test fixtures where we're using the old ones, which I've added to this PR.

**Comment by ironcladlou** [comment]
We should audit to make sure those old keys aren't used *anywhere*, and have a solid conversion strategy before trying to do this sort of compatibility stuff in the future.

**Comment by deads2k** [comment]
> curious where the beta1 key was being written... would like to track that down first

Looks like one the test fixtures fixed here.

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
also, will this actually close my pull?

**Comment by liggitt** [comment]
@ironcladlou were there other fixtures using the old annotations, or was status the only one you cared about?

**Comment by ironcladlou** [comment]
@deads2k 
>also, will this actually close my pull?

test-cmd.sh passes and none of the errors you cited appear in the logs. I inspected the etcd data store that remains from the test run, and looked at some ReplicationControllers, which have the correct annotation. Grepping the json of all RCs for 'deploymentStatus' turned up nothing.

**Comment by ironcladlou** [comment]
@liggitt 
>@ironcladlou were there other fixtures using the old annotations, or was status the only one you cared about?

In the fixture I changed, not only was the old status annotation used, but also the version key and some correlation keys. I certainly could have missed other things with my grepping. I didn't even know these fixtures existed until now. Storing static JSON representations of the API objects for tests scares me. Would we be able to serialize objects at runtime instead?

**Comment by liggitt** [comment]
> Storing static JSON representations of the API objects for tests scares me. Would we be able to serialize objects at runtime instead? 

Now that we've shipped an API version, static versions should be able to be loaded and be forward compatible. These are super-useful for things like testing UI behavior of scenarios that are complex to create in real-life

**Pull request merged**
