### PR TITLE
Adding rhel7 based origin-base Dockerfile

### PR DESCRIPTION
**Pull request by jhadvig**
@smarterclayton PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Actually, can you change the standard name in the comment to match the enterprise naming scheme?

**Comment by jhadvig** [comment]
@smarterclayton updated to `openshift/ose-base` as suggested.

**Comment by smarterclayton** [comment]
[test]

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
