### PR TITLE
disable hpa tests

### PR DESCRIPTION
**Pull request by dgoodwin**
- **quota.sh: OCP 4.16 no longer creates legacy API tokens**
- **[ETCD-578](https://issues.redhat.com//browse/ETCD-578): remove Tech Preview check from etcd profiles e2e test**
- **[ETCD-565](https://issues.redhat.com//browse/ETCD-565): add manual etcd signer cert rotation e2e test**
- **bump(k8s.io)**
- **React to library-go changes**
- **make update**
- **Add a "limit" exception for iptables-alerter**
- **[trt-1689](https://issues.redhat.com//browse/trt-1689): Filter must-gather and truncate system node users**
- **[trt-1689](https://issues.redhat.com//browse/trt-1689): Filter must-gather and normalize system node users**
- **[trt-1689](https://issues.redhat.com//browse/trt-1689): Change system:node pattern to assist in query filtering**
- **[trt-1689](https://issues.redhat.com//browse/trt-1689): Preserve unmodified_user and filter prior to checking monitored users**
- **[ETCD-578](https://issues.redhat.com//browse/ETCD-578): Fix etcd profiles e2e test to check returned status for updated value**
- **bump 4.16 to latest o/k 4.16 release branch**
- **Router: add Proxy config**
- **Add new intervals for kubelet metrics endpoints down**
- **Improve test name**
- **Skip the horizontal pod autoscaling tests for test purposes**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn

/hold

Purely a test to see if this resolves the metrics outage in the kubelet. Do not merge.

**Comment by rphillips** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn

**Comment by rphillips** [comment]
The jobs above all have the same UUID for some reason.

**Pull request closed without merging**
