### PR TITLE
Add badges for Go Report Card and License

### PR DESCRIPTION
**Pull request by jawnsy**
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by jawnsy** [comment]
@smarterclayton Pretty simple doc-only change, can you please take a look?

**Comment by liggitt** [comment]
Not sure I'd want to give goreportcard.com a chance to track all visitors to the origin repo. Does that really add value?

**Comment by jawnsy** [comment]
@liggitt Thanks for taking a look. I dunno, I saw that the Kubernetes project uses it and it seems to provide some useful-looking static code analysis reports, so the badge provides a convenient way to look at them. And it also looks nice for us since, hey, an "A" grade isn't too shabby.

There's a similar concern about the license badge that I added, but I figure it's useful for people looking at our project to quickly tell that is licensed suitably for their organization.

If you're against this change, I'm happy to just close without merging. Not a big deal to me, just thought it'd be nice.

**Comment by liggitt** [comment]
Yeah, I don't think that's that important either. The license is easy to find for those who care

**Comment by jawnsy** [comment]
@liggitt It turns out that GitHub re-hosts all images embedded in the README. You can see this if you use the Inspector in your browser; for example, the Jenkins badge has this HTML:

```html
<a href="https://ci.openshift.redhat.com/jenkins/job/devenv_ami/">
<img src="https://camo.githubusercontent.com/4c76fa6ed7dd8029b441216cb40235eea3e5e16f/..."
alt="Jenkins"
data-canonical-src="https://ci.openshift.redhat.com/jenkins/buildStatus/icon?job=devenv_ami" 
style="max-width:100%;"></a>
```

So there should not be any privacy/tracking issue here, though certainly the value of both is still an open question. Go Report Card runs tools like `golint`, which look to have a few useful suggestions in there. Personally I think they are useful, and that the cost of adding them is pretty low. I don't feel that strongly about it, so if you still disagree I'll acquiesce and close this PR.

**Comment by liggitt** [comment]
Report card, I'm ambivalent.
License badge is noise, imo

**Comment by jawnsy** [comment]
Thanks Jordan.

**Pull request closed without merging**
