### PR TITLE
Use a different donut color for pods not ready

### LINKED ISSUE #5793: Use a different color in the overview donut for pods that are running, but not ready
There's currently no way to tell if a pod is running, but not ready on the overview.

/cc @smarterclayton @jwforres

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #5793. Thoughts on the color?

screen_shot_2015-11-11_at_9_44_55_am

Hovering shows a tooltip like for other phases.

screen_shot_2015-11-11_at_9_27_29_am

Here is one pod pending (gray) and two not ready.

screen_shot_2015-11-11_at_10_07_14_am

Patternfly color palette: https://www.patternfly.org/styles/color-palette/

/cc @jwforres @liggitt @smarterclayton

### CODE REVIEW

**Comment by jwforres** [comment]
does the order of the categories matter?  like if i have one pending, one
not ready, and one ready then i would want to see gray -> light blue -> blue

**Comment by spadgett** [comment]
I like how it fills clockwise as things start running. It's a weird animation if gray is first.

**Comment by spadgett** [comment]
Actually I changed the order form when I took the screenshot. The light blue appears before gray now.

**Comment by jwforres** [comment]
blue -> light blue -> gray is fine too, i just meant i didnt want to see
gray in between the two blues

**Comment by spadgett** [comment]
> blue -> light blue -> gray is fine too, i just meant i didnt want to see gray in between the two blues

Right that's how it works. I'll update the screenshot.

**Comment by jwforres** [comment]
LGTM

**Comment by smarterclayton** [comment]
Looks excellent thanks

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
