### PR TITLE
OCPBUGS-18865: Reapply "Merge pull request #28277 from vrutkovs/in-cluster-fixes-v3"

### PR DESCRIPTION
**Pull request by vrutkovs**
This reverts commit 4d66ac7.

* apiserver disruption tests no longer race with network disruption tests (they used the same label for the namespaces so apiserver disruption tests may have mistakenly assumed it was already running)
* added permissions to watch stop-configmap
* improved logging

### CODE REVIEW

**Comment by vrutkovs** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/test unit verify e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 5

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 5

**Comment by vrutkovs** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 5

**Comment by sdodson** [comment]
/cc @dgoodwin
seems you have some context on this

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 6

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 6

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 6

**Comment by dgoodwin** [comment]
/lgtm

Good find.

**Pull request merged**
