### PR TITLE
Release should pass OS_GIT_COMMIT as a commit, not a tag

### PR DESCRIPTION
**Pull request by smarterclayton**
Also elide the extra git commit value in a release archive name if it exactly matches.

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
[test

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
