### PR TITLE
Roll back fix for 1405440

### PR DESCRIPTION
**Pull request by pecameron**
The fix to use a TCP connection check to check whether the HAProxy
process is alive or not doesn't work without a iptables rule for port
1936. The original test using HTTPGet works because HTTPGet supports
a Host field that can be set with "localhost" when host networking is
used. The TCPSocketAction does not support a Host field.

Rolling back the fix until a new fix is developed.

bug 1430729

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc @danwinship @dcbw Rolled back the fix for 1405440. PTAL

**Comment by danwinship** [comment]
standard git way to do this would be "git revert 5b708a5", which then makes it completely clear that this is just reverting an earlier commit

**Comment by pecameron** [comment]
@danwinship Did I get this right? PTAL

**Comment by danwinship** [comment]
yeah, looks right

**Comment by pecameron** [comment]
@danwinship @dcbw @eparis Is this ready to merge? If so will one of you merge it?

**Comment by louyihua** [comment]
This is a weird bug...
The health check should be executed on local node, so there should be no way for the iptables to prevent such access...

**Comment by louyihua** [comment]
Maybe expose the port 1936 in router image's dockerfile can resolve this issue.
And I'll try to submit an issue or PR on kubernetes so that the TCPSocketAction can have an option to use loopback address for probe.

**Comment by imcsk8** [comment]
It sounds like a good option

**Comment by pecameron** [comment]
@louyihua The HTTPGet handler also had problems (see comment pkg/cmd/admin/router/router.go line 423) so adding Host to the TCPSocketAction may be all that is needed.

**Comment by louyihua** [comment]
@pecameron
Yes, this is the best way to solve this problem, and I've prepared a preliminary PR submitted to kubernetes (https://github.com/kubernetes/kubernetes/pull/42902) .

**Comment by eparis** [comment]
[merge] to fix broken, we can try again once everyone agrees on the next path.

**Comment by eparis** [comment]
[merge] but https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/45/testReport/junit/(root)/Extended/_Conformance__networking__router__openshift_routers_The_HAProxy_router_should_serve_the_correct_routes_when_scoped_to_a_single_namespace_and_label_set/ is a bit worrying that maybe it isn't a flake...

**Comment by eparis** [comment]
guess it was a flake [merge] because last time it was https://github.com/openshift/origin/issues/11114

**Pull request merged**
