### PR TITLE
UPSTREAM: 71713: Plumb token and token file through rest.Config

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
@soltysh it is reverted here. Should I add some commit with a "magic" first line?

**Comment by soltysh** [comment]
> @soltysh it is reverted here. Should I add some commit with a "magic" first line?

Yes, we need to be clear that it was reverted for @deads2k to know it can safely drop that PR, the magic incantation is `UPSTREAM: revert: 69272: Fix bug with InClusterConfig requiring bearer token`

**Pull request merged**
