### PR TITLE
Fix flakiness in builds extended tests

### PR DESCRIPTION
**Pull request by csrwng**
Uses a pod with a readiness probe and a service to determine when the pod is serving content. The service endpoint will be added only when the pod is ready to serve content as determined by the readiness probe.

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
[testonlyextended][extended:core(s2i)]

**Comment by bparees** [comment]
[merge]

**Comment by csrwng** [comment]
@bparees looks like test-cmd is having trouble with the wildfly image
```
FAILURE after 60.283s: test/cmd/images.sh:49: executing 'oc get imagestreamtags wildfly:latest' expecting success; re-trying every 0.2s until completion or 60.000s: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: imageStreamTag "wildfly:latest" not found
```
Is it a known issue?

**Comment by bparees** [comment]
nope, not one i've seen before.  I just created the wildfly imagestream myself (from the image-streams-centos7.json file, which i believe is what this test also sets up) and it seems fine.

and line 44 confirms the imagestream is defined, so was this just a hiccup with imagestream import not succeeding or a dockerhub flake?

**Comment by csrwng** [comment]
My guess would be a dockerhub flake

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
The last merge flake was:

```console
--- FAIL: TestAuthorizationSubjectAccessReview-4 (15.83s)
	authorization_test.go:493: unexpected error: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
FAIL
```

**Pull request merged**
