### PR TITLE
Add an ENV to control ipv6 behavior in the router

### PR DESCRIPTION
**Pull request by knobunc**
This patch adds an environent variable called ROUTER_IP_V4_V6_MODE
which must be set to "v4" (the default), "v6", or "v4v6" to control
whether the router to binds to IPv4, IPv6, or both.

Note that when set to 'v6' or 'v4v6', the X-Forwarded-For and
Forwarded http headers will be in IPv6 form (even when the connection
was an IPv4 one, if set to 'v4v6').

Back-port of https://github.com/openshift/origin/pull/15229

Fixes bug 1472976 (https://bugzilla.redhat.com/show_bug.cgi?id=1472976)

### CODE REVIEW

**Comment by knobunc** [comment]
[test][testextended][extended: networking]

**Comment by knobunc** [comment]
[test] last flaked on https://github.com/openshift/origin/issues/15337
[testextended][extended: networking]

**Comment by knobunc** [comment]
[merge][severity: blocker]

**Comment by knobunc** [comment]
[test] flaked on https://github.com/openshift/origin/pull/15351
[testextended][extended: networking]

**Comment by knobunc** [comment]
[test] flaked on docker pull with `error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error`

**Comment by liggitt** [comment]
sdnnamespace flake fix merged, [test]

**Comment by knobunc** [comment]
[test] flaked on https://github.com/openshift/origin/issues/15401

**Pull request merged**
