### PR TITLE
Namespace all build secrets

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: #2923

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees @liggitt @soltysh PTAL

**Comment by soltysh** [comment]
LGTM

**Comment by mfojtik** [comment]
@smarterclayton merge?

**Comment by liggitt** [comment]
hold off... this will require a rebuild of the builder images to pick up the new constants

**Comment by liggitt** [comment]
and re-tag

**Comment by mfojtik** [comment]
@liggitt it is in @smarterclayton hands now :-)

**Comment by liggitt** [comment]
actually, nm, looks like we used PUSH_DOCKERCFG_PATH/PULL_DOCKERCFG_PATH for the builder to get the paths

**Comment by mfojtik** [comment]
@liggitt right, they should both pickup the updated path automagically

**Comment by liggitt** [comment]
LGTM, then

**Comment by smarterclayton** [comment]
Approved [merge]

**Comment by liggitt** [comment]
Fix message:
```
if [ -z "${SECRET_PATH}" ]; then
  echo "The dockercfg not found in /var/run/secrets/push"
  exit 1
fi
```

**Comment by mfojtik** [comment]
@liggitt this is already tagged... if you refer to extended tests fixture, I will fix that in follow up PR

**Comment by smarterclayton** [comment]
You still have about 3 hours to fix this.

**Comment by smarterclayton** [comment]
Just make the change here.

**Comment by mfojtik** [comment]
@smarterclayton commit added

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
