### PR TITLE
Add unit tests for PushSecretName

### PR DESCRIPTION
**Pull request by mfojtik**
Simple unit tests to verify that the Volume has been added to Build Pod. Sorry for not doing this in the main PR :-(

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh @bparees PTAL

**Comment by soltysh** [comment]
What about custom test?

**Comment by mfojtik** [comment]
@soltysh fixed

**Comment by soltysh** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
