### PR TITLE
UPSTREAM: 47919: Cherry: Use %q formatter for error messages from the AWS SDK

### PR DESCRIPTION
**Pull request by jpeeler**
upstream pick for https://bugzilla.redhat.com/show_bug.cgi?id=1462445

### CODE REVIEW

**Comment by jpeeler** [comment]
upstream PR is lgm/approved [test]

**Comment by eparis** [comment]
[test] doesn't seem likely to have broken testRouterStatsPort

**Comment by derekwaynecarr** [comment]
re [test]

**Comment by eparis** [comment]
[merge]

**Comment by eparis** [comment]
this is some message printing. going by hand baby!

**Pull request merged**
