### PR TITLE
UPSTREAM: 47078: HPA: only send updates when the status has changed

### PR DESCRIPTION
**Pull request by DirectXMan12**
This commit only sends updates if the status has actually changed.
Since the HPA runs at a regular interval, this should reduce the volume
of writes, especially on short HPA intervals with relatively constant
metrics.

bug 1467022

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
[test]

**Comment by DirectXMan12** [comment]
at a glance, these seem to all be flakes.

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]

**Comment by derekwaynecarr** [comment]
re [test]

**Comment by DirectXMan12** [comment]
re [test]

**Comment by DirectXMan12** [comment]
whoops, looks like there's a newly detected race in horizontal_test.go that wasn't showing up before.  It was buried in the middle of the unit test results, as it doesn't actually cause the unit tests to fail :-/.

**Comment by DirectXMan12** [comment]
ok, that should fix it.

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]

**Comment by eparis** [comment]
[merge] because i don't see events anywhere in the timeout...

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker] as last failure was due to timeout provisioning cluster.

**Pull request merged**
