### PR TITLE
Run separate informers for api and controllers

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1470009

### CODE REVIEW

**Comment by liggitt** [comment]
[severity:blocker]

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by smarterclayton** [comment]
We have customers running very large all-in-one setups.  Is this going to double memory use?

**Comment by liggitt** [comment]
known flake on "oc rollout status dc/ipfailover" - https://github.com/openshift/origin/issues/14403
[test]

**Comment by liggitt** [comment]
> Is this going to double memory use?

Not double, the api server doesn't watch all resources.

**Comment by smarterclayton** [comment]
Will run some tests to get numbers.

On Jul 14, 2017, at 11:07 PM, OpenShift Bot <notifications@github.com>
wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3173/)
(Base Commit: bca9c79
<https://github.com/openshift/origin/commit/bca9c798bb4c1feb15851083ccf043d964297b35>)
(PR Branch Commit: 6d86bbb
<https://github.com/openshift/origin/commit/6d86bbb787f3a49d60da04978ac4a5539cdd64e7>
)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/15217#issuecomment-315505198>,
or mute
the thread

**Comment by liggitt** [comment]
Integration setup flake, [test]

**Comment by deads2k** [comment]
lgtm, this was on my list and makes logical sense since controllers are late initializing

**Comment by smarterclayton** [comment]
Ship it, it makes performance worse, but it's only 10-ish unshared informers anyway.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
