### PR TITLE
change balance to source

### PR DESCRIPTION
**Pull request by pweil-**
Change balance from leastconn to source which will provide basic stickiness for http and tcp connections based on the source ip.  

http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-balance

@rajatchopra @ramr PTAL

/cc @bparees

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by rajatchopra** [comment]
LGTM.
We should eventually utilize stick-tables +cookies wherever applicable. Especially with peers, and use 'stick on src'. And mention leastconn as the default balancing algo, then.

**Comment by pweil-** [comment]
@rajatchopra I think that's the preferred implementation.  This will get us OOTB basic stickiness that some folks have been asking for and I'll need to update the docs with some common changes that people will probably want to make to routers for a more robust implementation.

**Comment by smarterclayton** [comment]
With peers we'll need to be able to find the other master endpoints - we may want to switch the router to being a headless service so that DNS will resolve the endpoints, at which point the peers are just a `dig A +search router` away (although knowing what service you want to look for is harder).

**Comment by pweil-** [comment]
If I'm going to have to implement stick-tables in the near future (which it sounds like based on the email conversations we've had) we can probably close this PR.  Agree or is this still worth having around in the short term?

**Comment by bparees** [comment]
i think the real preference is cookies for http traffic and stick-tables for everything else, but either way i think we can abandon the "source" approach this issue proposes.

**Comment by pweil-** [comment]
Seconded...closing

**Pull request closed without merging**
