### PR TITLE
Drop --config support from openshift-sdn

### PR DESCRIPTION
**Pull request by danwinship**
Last one! (For now...) This drops support for reading `node-config.yaml`; the node config now comes from the `ClusterNetwork` object, and the proxy config from the `kube-proxy-config.yaml`.

/cc @squeed

### CODE REVIEW

**Comment by squeed** [comment]
Looks like the CI run hadn't picked up the CNO changes.
/retest

**Comment by squeed** [comment]
Ah, looks like https://github.com/openshift/cluster-network-operator/pull/195 fails to actually pass the kube-proxy config.

**Comment by danwinship** [comment]
Doh.
/hold

**Comment by squeed** [comment]
/hold cancel
I think we can revive this.

**Pull request merged**
