### PR TITLE
No one needs this log output

### PR DESCRIPTION
**Pull request by smarterclayton**
If you care, you'll find out.  If you don't care, you don't need to
ignore it while looking at logs anymore

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Exactly where I was going with `os::log::debug` +1000

(maybe we should have `os::log::debug` always write to a file and only display to the screen with `OS_DEBUG` ... this would allow for us to have it on in Jenkins and not annoy people looking at logs?)

**Comment by smarterclayton** [comment]
I actually was turning this off on for Jenkins because it provides no
useful info in the log output (and the files either get grabbed in
artifacts or not, which is something only you and I need to know is broken)

**Comment by stevekuznetsov** [comment]
Ack.

This LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
