### PR TITLE
test: retry rollout latest on update conflicts

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/11477

[test]

### CODE REVIEW

**Comment by kargakis** [comment]
@mfojtik

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11094 [test]

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
cc: @legionus ^

**Comment by mfojtik** [comment]
[test]

**Comment by kargakis** [comment]
@mfojtik mind tagging?

**Comment by mfojtik** [comment]
@kargakis why are we not protecting from the conflicts in `oc rollout latest` code? as an end-user I want to rollout and don't want to retry because something updated my config.

**Comment by kargakis** [comment]
Not always true. Most update conflicts happen due to the dc controller
updating the status of the deployment config. So someone could argue that
they would want to retry in such a case.

**Comment by mfojtik** [comment]
@kargakis is there a case when they don't want to retry?  end users don't know about controller updating the status and I can argue that don't care when they just created the DC.

**Comment by kargakis** [comment]
> @kargakis is there a case when they don't want to retry? end users don't know about controller updating the status and I can argue that don't care when they just created the DC.

I can't think of any.

**Comment by mfojtik** [comment]
@kargakis i'm ok with this to fix flaky tests for now but we should add TODO and create issue to add retrying into `rollout latest` (in upstream). WDYT?

**Comment by kargakis** [comment]
@mfojtik there is no `rollout latest` upstream. I have proposed somewhere to use GuaranteedUpdate in instantiate (similar to how the upstream rollback REST uses GuaranteedUpdate for rollbacks) but we really need to think if it's 100% correct to do so.

**Comment by kargakis** [comment]
@mfojtik merge this?

**Comment by mfojtik** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/12155 [merge]

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/11004

[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11004 and https://github.com/openshift/origin/issues/12072 [merge]

**Comment by kargakis** [comment]
flake is https://github.com/openshift/origin/issues/12157

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/8571 [merge]

**Pull request merged**
