### PR TITLE
UPSTREAM: 13322: Various exec fixes

### LINKED ISSUE #4239: Flake in travis on upstream test TestRequestExecuteRemoteCommand/TestRequestAttachRemoteCommand
https://travis-ci.org/openshift/origin/jobs/75076860#L1453

### LINKED ISSUE #4445: oc exec / rsh hangs for a long time on exit
After exiting an interactive shell session in a pod, the terminal hangs for several seconds before I can type anything back in the host.

```
[vagrant@openshiftdev origin]$ oc get pods
NAME            READY     STATUS    RESTARTS   AGE
mysql-3-9zgou   1/1       Running   0          3m
[vagrant@openshiftdev origin]$ time oc rsh mysql-3-9zgou
bash-4.2$ exit
real    0m29.163s
user    0m0.431s
sys     0m0.110s
```

Same for other pods, e.g., `docker-registry`.

(@mfojtik FYI)

### PR DESCRIPTION
**Pull request by liggitt**
Upstream PR: https://github.com/kubernetes/kubernetes/pull/13322

Includes dockerclient fixes from https://github.com/openshift/origin/pull/4467 (cc @csrwng)

Fixes BZ 1255502
Fixes #4239
Fixes #4445

### CODE REVIEW

**Comment by liggitt** [comment]
[test] [extended:all]

**Comment by liggitt** [comment]
transitive LGTM from @smarterclayton upstream

**Comment by deads2k** [comment]
Extended is currently borked.  Care to merge instead?

**Comment by liggitt** [comment]
yeah, [merge]

**Comment by smarterclayton** [comment]
I can still trigger a hang even with this PR.  This is without a TTY stdin.

```
goroutine 10 [syscall]:
runtime.notetsleepg(0x1ea54f8, 0x253fc1ca0, 0x1)
	/usr/lib/golang/src/runtime/lock_futex.go:201 +0x52 fp=0xc20801af68 sp=0xc20801af40
runtime.timerproc()
	/usr/lib/golang/src/runtime/time.go:207 +0xfa fp=0xc20801afe0 sp=0xc20801af68
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
created by runtime.addtimerLocked
	/usr/lib/golang/src/runtime/time.go:113 +0x1ba

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc20832e060)
	/usr/lib/golang/src/sync/waitgroup.go:132 +0x169
k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream(0xc208234a10, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:261 +0xa00
k8s.io/kubernetes/pkg/client/remotecommand.(*Executor).Execute(0xc208234a10, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:129 +0x193
k8s.io/kubernetes/pkg/kubectl/cmd.(*DefaultRemoteExecutor).Execute(0x1eb3920, 0xc20814eb40, 0xc208190640, 0xc20828e010, 0x5, 0x6, 0x7ff1bc3e9160, 0xc20802e000, 0x7ff1bc3e90b0, 0xc20802e008, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/exec.go:85 +0x220
k8s.io/kubernetes/pkg/kubectl/cmd.(*ExecOptions).Run(0xc208218820, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/exec.go:225 +0x991
github.com/openshift/origin/pkg/cmd/cli/cmd.RunRsh(0xc208218820, 0xc2081fea00, 0xc2082651e0, 0xc20828e010, 0x5, 0x6, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/rsh.go:112 +0x1cb
github.com/openshift/origin/pkg/cmd/cli/cmd.func·021(0xc2082651e0, 0xc20828e010, 0x5, 0x6)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/rsh.go:78 +0x25d
github.com/spf13/cobra.(*Command).execute(0xc2082651e0, 0xc208235f80, 0x7, 0x7, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:477 +0x3d4
github.com/spf13/cobra.(*Command).Execute(0xc2081cc340, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:551 +0x414
main.main()
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:22 +0x175

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1ea5a60)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 22 [IO wait]:
net.(*pollDesc).Wait(0xc20828e0d0, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20828e0d0, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20828e070, 0xc208296000, 0x1000, 0x1000, 0x0, 0x7ff1bc3e91b0, 0xc208125ed8)
	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2083e4000, 0xc208296000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2082080c0, 0x7ff1bc3fb368, 0xc2083e4000, 0x5, 0x0, 0x0)
Quit (core dumped)
[vagrant@openshiftdev origin]$ 	/usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208150580, 0x17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208150580, 0xc20816b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7ff1bc3fb850, 0xc208150580, 0xc208084058, 0xc20816b000, 0x1000, 0x1000, 0x1101500, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2083f3260, 0xc20816b000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208241ce0)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208241ce0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208084000)
	/usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 24 [chan receive]:
github.com/docker/spdystream.func·003(0xc2082a4240)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:272 +0x43
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:274 +0x175

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc208084000)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 35 [select]:
github.com/docker/spdystream.(*idleAwareFramer).monitor(0xc208261ec0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:57 +0x551
created by github.com/docker/spdystream.NewConnection
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:223 +0x598

goroutine 36 [IO wait]:
net.(*pollDesc).Wait(0xc20828f5d0, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20828f5d0, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20828f570, 0xc208263000, 0x400, 0x400, 0x0, 0x7ff1bc3e91b0, 0xc2081f98d0)
	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e118, 0xc208263000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208288ff0, 0x7ff1bc3fb368, 0xc20802e118, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208150b00, 0x17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208150b00, 0xc2081f98c8, 0x4, 0x8, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
io.ReadAtLeast(0x7ff1bc3fb850, 0xc208150b00, 0xc2081f98c8, 0x4, 0x8, 0x4, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff1bc3fb850, 0xc208150b00, 0xc2081f98c8, 0x4, 0x8, 0xc200000000, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:316 +0x6d
encoding/binary.Read(0x7ff1bc3fb850, 0xc208150b00, 0x7ff1bc3fca70, 0x1eb3920, 0xf99f20, 0xc2081f98c0, 0x0, 0x0)
	/usr/lib/golang/src/encoding/binary/binary.go:148 +0x12d
github.com/docker/spdystream/spdy.(*Framer).ReadFrame(0xc208240060, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/spdy/read.go:148 +0xff
github.com/docker/spdystream.(*idleAwareFramer).ReadFrame(0xc208261ec0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:137 +0x4f
github.com/docker/spdystream.(*Connection).Serve(0xc2082180a0, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:281 +0x206
created by k8s.io/kubernetes/pkg/util/httpstream/spdy.newConnection
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/connection.go:68 +0x113

goroutine 25 [semacquire]:
sync.(*Cond).Wait(0xc2083c6300)
	/usr/lib/golang/src/sync/cond.go:62 +0x9e
github.com/docker/spdystream.(*PriorityFrameQueue).Pop(0xc2082a4240, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/priority.go:86 +0x11c
github.com/docker/spdystream.(*Connection).frameHandler(0xc2082180a0, 0xc2082a4240, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:345 +0x33
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:276 +0x1cc

goroutine 26 [chan receive]:
github.com/docker/spdystream.func·003(0xc2082a4270)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:272 +0x43
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:274 +0x175

goroutine 27 [semacquire]:
sync.(*Cond).Wait(0xc2083c6340)
	/usr/lib/golang/src/sync/cond.go:62 +0x9e
github.com/docker/spdystream.(*PriorityFrameQueue).Pop(0xc2082a4270, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/priority.go:86 +0x11c
github.com/docker/spdystream.(*Connection).frameHandler(0xc2082180a0, 0xc2082a4270, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:345 +0x33
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:276 +0x1cc

goroutine 28 [chan receive]:
github.com/docker/spdystream.func·003(0xc2082a42a0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:272 +0x43
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:274 +0x175

goroutine 29 [semacquire]:
sync.(*Cond).Wait(0xc2083c6380)
	/usr/lib/golang/src/sync/cond.go:62 +0x9e
github.com/docker/spdystream.(*PriorityFrameQueue).Pop(0xc2082a42a0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/priority.go:86 +0x11c
github.com/docker/spdystream.(*Connection).frameHandler(0xc2082180a0, 0xc2082a42a0, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:345 +0x33
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:276 +0x1cc

goroutine 30 [chan receive]:
github.com/docker/spdystream.func·003(0xc2082a42d0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:272 +0x43
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:274 +0x175

goroutine 31 [semacquire]:
sync.(*Cond).Wait(0xc2083c63c0)
	/usr/lib/golang/src/sync/cond.go:62 +0x9e
github.com/docker/spdystream.(*PriorityFrameQueue).Pop(0xc2082a42d0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/priority.go:86 +0x11c
github.com/docker/spdystream.(*Connection).frameHandler(0xc2082180a0, 0xc2082a42d0, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:345 +0x33
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:276 +0x1cc

goroutine 32 [chan receive]:
github.com/docker/spdystream.func·003(0xc2082a4300)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:272 +0x43
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:274 +0x175

goroutine 33 [semacquire]:
sync.(*Cond).Wait(0xc2083c6400)
	/usr/lib/golang/src/sync/cond.go:62 +0x9e
github.com/docker/spdystream.(*PriorityFrameQueue).Pop(0xc2082a4300, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/priority.go:86 +0x11c
github.com/docker/spdystream.(*Connection).frameHandler(0xc2082180a0, 0xc2082a4300, 0xc2081c80c0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:345 +0x33
created by github.com/docker/spdystream.(*Connection).Serve
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:276 +0x1cc

goroutine 37 [select]:
github.com/docker/spdystream.(*Stream).Read(0xc208218140, 0xc20821a000, 0x200, 0x200, 0x7ff1bc3ddf88, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:80 +0x347
bytes.(*Buffer).ReadFrom(0xc2081fa1c0, 0x7ff1bc3fce90, 0xc208218140, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bytes/buffer.go:169 +0x25a
io/ioutil.readAll(0x7ff1bc3fce90, 0xc208218140, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/ioutil/ioutil.go:33 +0x1b0
io/ioutil.ReadAll(0x7ff1bc3fce90, 0xc208218140, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/ioutil/ioutil.go:42 +0x68
k8s.io/kubernetes/pkg/client/remotecommand.func·001()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:170 +0x63
created by k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:180 +0x3c3

goroutine 38 [runnable]:
syscall.Syscall(0x1, 0x5, 0xc208262c00, 0x21, 0x21, 0x21, 0x0)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.write(0x5, 0xc208262c00, 0x21, 0x400, 0x77, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:1263 +0x6e
syscall.Write(0x5, 0xc208262c00, 0x21, 0x400, 0x21, 0x0, 0x0)
	/usr/lib/golang/src/syscall/syscall_unix.go:152 +0x58
net.(*netFD).Write(0xc20828f570, 0xc208262c00, 0x21, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_unix.go:327 +0x34c
net.(*conn).Write(0xc20802e118, 0xc208262c00, 0x21, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:129 +0xdc
crypto/tls.(*Conn).writeRecord(0xc208150b00, 0x17, 0xc2081f9914, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:748 +0x4f3
crypto/tls.(*Conn).Write(0xc208150b00, 0xc2081f9914, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:880 +0x411
encoding/binary.Write(0x7ff1bc3fb8a0, 0xc208150b00, 0x7ff1bc3fca70, 0x1eb3920, 0xfd50e0, 0xc2081f9910, 0x0, 0x0)
	/usr/lib/golang/src/encoding/binary/binary.go:333 +0x1afe
github.com/docker/spdystream/spdy.(*Framer).writeDataFrame(0xc208240060, 0xc20837cd60, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/spdy/write.go:311 +0x2a6
github.com/docker/spdystream/spdy.(*DataFrame).write(0xc20837cd60, 0xc208240060, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/spdy/write.go:133 +0x44
github.com/docker/spdystream/spdy.(*Framer).WriteFrame(0xc208240060, 0x7ff1bc3fd008, 0xc20837cd60, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/spdy/write.go:138 +0x4a
github.com/docker/spdystream.(*idleAwareFramer).WriteFrame(0xc208261ec0, 0x7ff1bc3fd008, 0xc20837cd60, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:126 +0xd0
github.com/docker/spdystream.(*Stream).WriteData(0xc208154820, 0x1eb3920, 0x0, 0x0, 0x413f01, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:63 +0x2c0
github.com/docker/spdystream.(*Stream).Close(0xc208154820, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:163 +0xcb
k8s.io/kubernetes/pkg/client/remotecommand.func·002()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:198 +0x39
sync.(*Once).Do(0xc2081cb3e0, 0xc20836bfc8)
	/usr/lib/golang/src/sync/once.go:44 +0xd4
k8s.io/kubernetes/pkg/client/remotecommand.func·003()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:203 +0x123
created by k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:203 +0x5b6

goroutine 39 [select]:
github.com/docker/spdystream.(*Stream).Read(0xc208154820, 0xc208372000, 0x2000, 0x2000, 0x1b, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:80 +0x347
io/ioutil.devNull.ReadFrom(0x0, 0x7ff1bc3fce90, 0xc208154820, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/ioutil/ioutil.go:151 +0xb1
io/ioutil.(*devNull).ReadFrom(0xc20802a2a0, 0x7ff1bc3fce90, 0xc208154820, 0x7ff1bc3fbb18, 0x0, 0x0)
	<autogenerated>:9 +0xbb
io.Copy(0x7ff1bc3e90d8, 0xc20802a2a0, 0x7ff1bc3fce90, 0xc208154820, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:358 +0x13d
k8s.io/kubernetes/pkg/client/remotecommand.func·005()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:220 +0xee
created by k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:223 +0x637

goroutine 50 [select]:
github.com/docker/spdystream.(*Stream).Read(0xc208154e60, 0xc2083e6000, 0x8000, 0x8000, 0x9a, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:80 +0x347
io.Copy(0x7ff1bc3e90b0, 0xc20802e008, 0x7ff1bc3fce90, 0xc208154e60, 0x30e, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:362 +0x1f6
k8s.io/kubernetes/pkg/client/remotecommand.func·006()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:237 +0xa2
created by k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:240 +0x807

goroutine 40 [select]:
github.com/docker/spdystream.(*Stream).Read(0xc208218320, 0xc2083b2000, 0x8000, 0x8000, 0x35, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:80 +0x347
io.Copy(0x7ff1bc3e90b0, 0xc20802e010, 0x7ff1bc3fce90, 0xc208218320, 0x35, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:362 +0x1f6
k8s.io/kubernetes/pkg/client/remotecommand.func·007()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:254 +0xa2
created by k8s.io/kubernetes/pkg/client/remotecommand.(*Streamer).doStream
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/remotecommand/remotecommand.go:257 +0x9f0
```

**Comment by liggitt** [comment]
What's the exact command and sequence of operations?

**Comment by smarterclayton** [comment]
My branch, rsync -avvv -e "oc rsh" file pod:/dir

On Sep 5, 2015, at 1:43 PM, Jordan Liggitt <notifications@github.com> wrote:

What's the exact command and sequence of operations?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4535#issuecomment-137980847>.

**Pull request merged**
