### PR TITLE
DRY out script cleanup code

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Disable swap in Go build

We have migrated to Go 1.7+ and as such we no longer need to be enabling
swap space for our builds.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Automatically determine which type of jUnit report to generate

We can tell from the raw test output file which type of test was used to
create the output, so we do not need users to have to specify which type
of parsing and report they would like.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

DRY out script cleanup code

Almost every single cleanup function trapped on exit for our scripts was
taking the same actions in the same order. We can break that out into a
standalone function under `hack/lib` that contains a superset of all the
cleanup steps used, provided that we make sure each individual clean up
step can gracefully handle the case where it is not needed or does not
have any work to do.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

/cc @smarterclayton PTAL

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Lgtm merge at will

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
[test][merge]

**Comment by smarterclayton** [comment]
This kills my docker containers when i run `hack/update-generated-swagger-spec.sh`, which is annoying:

```
SUCCESS after 2.964s: hack/lib/start.sh:298: executing 'oc get --raw /healthz --config='/var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T//openshift/update-generated-swagger-spec/openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s
SUCCESS after 0.240s: hack/lib/start.sh:299: executing 'oc get --raw /healthz/ready --config='/var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T//openshift/update-generated-swagger-spec/openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s
SUCCESS after 0.248s: hack/lib/start.sh:300: executing 'oc get service kubernetes --namespace default --config='/var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T//openshift/update-generated-swagger-spec/openshift.local.config/master/admin.kubeconfig'' expecting success; re-trying every 0.25s until completion or 160.000s
[INFO] Updating /Volumes/development/projects/origin/src/github.com/openshift/origin//api/swagger-spec:
[INFO] Updating /api/swagger-spec/oapi-v1.json from /swaggerapi/oapi/v1...
[INFO] Updating /api/swagger-spec/api-v1.json from /swaggerapi/api/v1...
[INFO] [CLEANUP] Beginning cleanup routines...
[INFO] [CLEANUP] Dumping cluster events to _output/scripts/update-generated-swagger-spec/artifacts/events.txt
[INFO] [CLEANUP] Dumping etcd contents to _output/scripts/update-generated-swagger-spec/artifacts/etcd
2017-05-21 23:32:40.029884 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
[INFO] [CLEANUP] Dumping container logs to _output/scripts/update-generated-swagger-spec/logs/containers
[INFO] [CLEANUP] `pprof` output logged to _output/scripts/update-generated-swagger-spec/logs/pprof.out
[INFO] [CLEANUP] Truncating log files over 100M
[INFO] [CLEANUP] Stopping docker containers
[INFO] [CLEANUP] Removing docker containers
[INFO] [CLEANUP] Killing child processes
[INFO] [CLEANUP] Pruning etcd data directory
[INFO] hack/update-generated-swagger-spec.sh exited with code 0 after 00h 00m 15s
```

update-generated-swagger-spec has nothing to do with docker containers or etcd data directory.

**Comment by stevekuznetsov** [comment]
Since we start a server for Swagger anyway I'm pretty sure container cleanup was pre-existing. We haven't changed the logic for which containers we target for cleanup. Which ones are you seeing killed?

**Pull request merged**
