### PR TITLE
move images extended tests to new tag and directory

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
LGTM

**Comment by gabemontero** [comment]
(pending successful test completion of course)

**Comment by bparees** [comment]
[merge]

**Comment by php-coder** [comment]
Why it's not merged yet? I see a merge command and "All checks have passed" message but PR still unmerged.

**Comment by bparees** [comment]
@php-coder it's #6 in the queue currently: https://github.com/openshift/origin/pull/11322#issuecomment-253057883

**Pull request merged**
