### PR TITLE
re-enable newapp conformance test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik was the double deployment issue ever solved?  i can re-enable the test because we made the checking more permissive, but it would be good to make the checking less permissive again, too.

**Comment by bparees** [comment]
[testextended][extended:core(oc new-app)]

**Comment by mfojtik** [comment]
@bparees this was the registry DNS thing, the ansible playbooks has to be updated ( @sdodson ?) and the new docker-registry image has to be uploaded to docker hub.

lets keep this PR open and tagged for test few times

**Comment by sdodson** [comment]
Ansible side should all be done.

**Comment by bparees** [comment]
@mfojtik this PR shouldn't fail because we loosened the deployment checking logic to tolerate multiple deployments.  

You own adding a new deployment test that ensures we don't get double deployments(I do not want this test to be responsible for that), and re-tightening the existing deployment checking logic:  https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L741-L747

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Pull request merged**
