### PR TITLE
wait longer for db availability

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by gabemontero** [comment]
labels are already there but /approve all the same

**Comment by bparees** [comment]
@gabemontero /lgtm is the command you're looking for.

**Comment by gabemontero** [comment]
hmm ... I see `/approve` in the list of commands at https://github.com/kubernetes/test-infra/blob/master/commands.md .... should I not assume it maps to the "approve" label? and for someone who does not have merging power, why would I bother with the lgtm command ?

**Comment by bparees** [comment]
@gabemontero i agree the terminology is confusing especially when transitioning from our old mechanism, but "approve" is the more constrained power that only people with merge access have.

"/lgtm" means "i am an expert in this code space and i have reviewed this code and believe it is correct"

"/approve" means "i am signing off on this code being merged into the repository, using my authority as someone with merge rights.  I may be doing that based on my trust of someone else's /lgtm or my own review"

**Comment by bparees** [comment]
(and both the lgtm and approved labels are necessary for a PR to merge)

**Comment by gabemontero** [comment]
i see ... thx for clarification

/lgtm :-)

**Comment by kargakis** [comment]
What high priority issue was this PR fixing that it warranted a manual merge? The latest batch job failed on a single job (install_update) but had it succeeded it would break because of this merge. 
```yaml
    refs:
      base_ref: master
      base_sha: a1d69a1f8ead02e43361b27d25a5c67f957e73a6
      org: openshift
      pulls:
      - number: 16311
        sha: bd775a4d9b4f16932dd68cc4e4b9963c52561ef6
      - number: 16204
        sha: b81f5a5f248b7bc9e7ec3f5af1ff66ee6669ca64
      - number: 16328
        sha: 2722efafe83987f03189b931d3c2e73fd3a43c85
      - number: 16348
        sha: e8eeca9f6881035a46c3cb24780b156774b5e2bd
      - number: 16250
        sha: 0c5698a19c53929bcd98d7999dba7bbd8283c994
      repo: origin
    type: batch
```
cc: @stevekuznetsov

**Comment by bparees** [comment]
> What high priority issue was this PR fixing that it warranted a manual merge? The latest batch job failed on a single job (install_update) but had it succeeded it would break because of this merge.

nothing. sorry.

**Pull request merged**
