### PR TITLE
Fix path to fixture for build secret extended test

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: #7911

### CODE REVIEW

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(build with secrets)]

**Comment by mfojtik** [comment]
@csrwng @php-coder PTAL

**Comment by php-coder** [comment]
LGTM

**Comment by csrwng** [comment]
why not change the file name :-)

**Comment by mfojtik** [comment]
@csrwng don't want to break something that potentially use it :-)

**Comment by csrwng** [comment]
Nothing a quick grep can't find :-) IMHO its better to have consistent naming. In the directory just above the secrets-build fixture we have one file named with s2i. Plus I thought we were going to try to replace sti with s2i wherever possible.

**Comment by mfojtik** [comment]
@csrwng ok :-) will rename

**Comment by mfojtik** [comment]
seems like this is already fixed ;-)

**Pull request closed without merging**
