### PR TITLE
[DO_NOT_MERGE] test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@PI-Victor let's see what happens here.

**Comment by PI-Victor** [comment]
aaaa...
Travis reports that this didn't fail, when in fact, it did.

```
FAILURE: Generated bootstrap bindata out of date. Please run hack/update-generated-bootstrap-bindata.sh

===== Verifying Generated Deep Copies =====

===== Verifying Generated Conversions =====

===== Verifying Generated Client sets =====
```

```
/home/travis/gopath/src/github.com/openshift/origin/hack/build-go.sh took 2 seconds

===== Verifying UPSTREAM Commits =====

SUCCESS: All commits are valid.

The command "make verify-commits" exited with 0.

Done. Your build exited with 0.
```

**Comment by PI-Victor** [comment]
also, you need to run update-generated-bootstrap-bindata.sh to make it pass.
still funny travis reports 0 exit code

**Comment by bparees** [comment]
well of course i actually did forget to update that file, too....  but it's bad that travis is lying to us.

**Comment by bparees** [comment]
@stevekuznetsov @csrwng see above re: travis reporting success when it should report failure.

**Comment by PI-Victor** [comment]
what's even more intriguing is that it doesn't fail in travis, but fails in jenkins so i'm assuming it's down to environment.

**Comment by bparees** [comment]
@PI-Victor looks to me like this passed verification (failed for other reasons, not surprisingly given how i hacked the change...)

**Comment by stevekuznetsov** [comment]
@bparees probably related to https://github.com/openshift/origin/commit/4851ce52a4e53b4c542e9977b3ba2ae2c72204da /cc @smarterclayton

**Pull request closed without merging**
