### PR TITLE
Mark package level flags as hidden for completions

### PR DESCRIPTION
**Pull request by smarterclayton**
This reserves completions only for those flags that are explictly added
into a cobra command. A reasonable tradeoff to make sure that flags are
consistent across platforms.

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'm going to stab completions and a jury will acquit me for
justifiable code-slaughter.

**Comment by juanvallejo** [comment]
@fabianofranz this lgtm

**Comment by fabianofranz** [comment]
/acquit
I mean
/lgtm

**Pull request merged**
