### PR TITLE
Revert "test/extended: Add MultiNetworkPolicy IPv4/IPv6 test cases"

### PR DESCRIPTION
**Pull request by deepsm007**
Reverts openshift/origin#27795

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

This change is breaking ci 4.14 or nightly 4.14 payloads:
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-05-17-212447
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-serial/1659065324743430144
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-05-18-040905
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-serial/1659088328617627648

https://sippy.dptools.openshift.org/sippy-ng/tests/4.14?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522current_runs%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25227%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257D%252C%257B%2522id%2522%253A99%252C%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522%255Bsig-network%255D%255BFeature%253AMultiNetworkPolicy%255D%255BSerial%255D%2520should%2520enforce%2520a%2520network%2520policies%2520on%2520secondary%2520network%2520IPv6%2520%255BSuite%253Aopenshift%252Fconformance%252Fserial%255D%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage

This test breaks some functionality or is a regression
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:

/payload-aggregate periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-serial 5

/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-serial 5

CC: @zeeke  , @s1061123 , https://github.com/orgs/openshift/teams/team-multus-cni-maintainers

### CODE REVIEW

**Comment by stbenjam** [comment]
/skip
/override ci/prow/e2e-aws-ovn-fips 
/override ci/prow/e2e-aws-ovn-serial
/override ci/prow/e2e-gcp-ovn 
/override ci/prow/e2e-gcp-ovn-upgrade 

Revert is clean, we need to return to green payloads as it's blocking some high-priority things like the kube rebase.

**Comment by deepsm007** [comment]
https://issues.redhat.com/browse/OCPBUGS-13788

**Pull request merged**
