### PR TITLE
Bug 1758158: aws: sort addresses of multiple interfaces correctly [4.2]

### PR DESCRIPTION
**Pull request by danwinship**
Backport of #23870 to 4.2

### CODE REVIEW

**Comment by eparis** [comment]
needs review and lgtm/approval

**Comment by danwinship** [comment]
/assign @p0lyn0mial @mfojtik 
who reviewed the PR on master (#23870 )

**Comment by jottofar** [comment]
can someone apply correct labels so this merges and can get into next 4.2 release

**Pull request merged**
