### PR TITLE
The func 'RequestForConfig' isn't used in the project

### PR DESCRIPTION
**Pull request by miaoyq**

### CODE REVIEW

**Comment by kargakis** [comment]
LGTM [merge]

**Comment by miaoyq** [comment]
@kargakis  This PR still be not merged,  could you please trigger another test and merge process?  
Thanks a lot!

**Comment by kargakis** [comment]
*continuous-integration/openshift-jenkins/merge Waiting: You are in the build queue at position: 13*

**Comment by miaoyq** [comment]
@kargakis  Is this PR still in the build queue?  Thanks!

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
