### PR TITLE
Bug 1697644: test/extended: update test to use openshift-config pull-secret

### PR DESCRIPTION
**Pull request by abhinavdahiya**
requires: https://github.com/openshift/installer/pull/1554

/cc @smarterclayton

### CODE REVIEW

**Comment by wking** [comment]
Looks like [verify failed][1] on the Go 1.11 bump (openshift/release#3394).  Maybe that's what's going on with the unit tests too?

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-unit/4939/artifacts/unit/unit.log.gz | gunzip | grep GetNameFromCallsite/ignore-package
{"Time":"2019-04-09T23:43:06.158172797Z","Action":"run","Package":"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/naming","Test":"TestGetNameFromCallsite/ignore-package"}
{"Time":"2019-04-09T23:43:06.158193705Z","Action":"output","Package":"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/naming","Test":"TestGetNameFromCallsite/ignore-package","Output":"=== RUN   TestGetNameFromCallsite/ignore-package\n"}
{"Time":"2019-04-09T23:43:06.159995273Z","Action":"output","Package":"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/naming","Test":"TestGetNameFromCallsite/ignore-package","Output":"    --- FAIL: TestGetNameFromCallsite/ignore-package (0.00s)\n"}
{"Time":"2019-04-09T23:43:06.160000271Z","Action":"output","Package":"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/naming","Test":"TestGetNameFromCallsite/ignore-package","Output":"        from_stack_test.go:52: expected \"testing/testing.go:777\", got \"testing/testing.go:827\"\n"}
{"Time":"2019-04-09T23:43:06.160009673Z","Action":"fail","Package":"github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/naming","Test":"TestGetNameFromCallsite/ignore-package","Elapsed":0}
```

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-verify/4321/build-log.txt

**Comment by soltysh** [comment]
> Looks like [verify failed](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-verify/4321/build-log.txt) on the Go 1.11 bump ([openshift/release#3394](https://github.com/openshift/release/pull/3394)). Maybe that's what's going on with the unit tests too?

Should be fixed by now. @wking ping me if there are some problems still.

**Comment by wking** [comment]
[images][1]:

```
could not wait for RPM repo server to deploy: could not wait for deployment: the deployment config ci-op-5t6fl9c5/rpm-repo failed with status "ProgressDeadlineExceeded"
```

Hunting...

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-images/4679

**Comment by wking** [comment]
[Build history][1] has this as a one-off failure, so kicking again in case it was just a fluke.

/retest

[1]: https://openshift-gce-devel.appspot.com/pr/22508

**Comment by wking** [comment]
[images][1]:

```
could not wait for build: the build node failed after 15m4s with reason BuildPodDeleted: The pod for this build was deleted before the build completed
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-images/4707

**Comment by wking** [comment]
[unit][1]:

```
FAIL: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/podautoscaler TestEventNotCreated 3m0.261s
```

/test unit

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22508/pull-ci-openshift-origin-master-unit/5244/build-log.txt

**Pull request merged**
