### PR TITLE
[DO NOT MERGE] Fix alignment for 32-bit compilers

### PR DESCRIPTION
**Pull request by kargakis**
@mmilata re #1666: can you please run this fix and verify that the issue is resolved?

Respective etcd PR https://github.com/coreos/etcd/pull/2511 though it seems stalled

### CODE REVIEW

**Comment by kargakis** [comment]
Relevant read: http://www.catb.org/esr/structure-packing/

**Comment by mmilata** [comment]
Sorry, I missed the notification. I'll test it soon.

**Comment by mmilata** [comment]
I tested the branch and it still fails as described in #1666 :(

**Comment by kargakis** [comment]
I tested it as well today and it doesn't work. In order to use the upstream patch we have to rebase etcd.

**Pull request closed without merging**
