### PR TITLE
Add clientauth flag for create-server-cert

### PR DESCRIPTION
**Pull request by sdodson**
This is primarily motivated by a need to create etcd peering certificates which requires that the cert is valid for both x509.ExtKeyUsageServerAuth x509.ExtKeyUsageClientAuth. I'd rather not create them manually if the only gap is adding an ExtKeyUsage value. It's fairly repetitious and could probably be refactored if need be.

### CODE REVIEW

**Comment by sdodson** [comment]
@liggitt ptal if you have the time

**Comment by liggitt** [comment]
just one more cert option... and before you know it, we're a pki wrapper :)

**Comment by sdodson** [comment]
It felt like we were already there so I was hoping you'd let it slide.

**Comment by liggitt** [comment]
I have to draw the line at an option to create client certs using create-server-cert...

**Comment by liggitt** [comment]
they really don't let you set different certs for serving and peering?

**Comment by sdodson** [comment]
They do, it's just that for peering they expect that the certs are valid for both server and client uses. The peering connectivity can use an entirely different CA if we need to, but that's another thing I'd have to have ansible set up.

See lines 37-46
https://github.com/openshift/openshift-ansible/pull/244/files#diff-fe48981231840fe56e7e955b33a4fe43R37

**Comment by sdodson** [comment]
We're going to have ansible build a CA specifically for etcd peering rather than adding this functionality to `openshift admin`

**Comment by sdodson** [comment]
Now we'd like to converge the etcd and openshift CAs so we're again interested in being able to use the openshift certificate tooling to sign certs for etcd peering.

**Pull request closed without merging**
