### PR TITLE
Change all aarch64 references to arm64

### PR DESCRIPTION
**Pull request by tdawson**
When I changed linux-aarch64 to linux-arm64, I only changed it in one place.
This patch changes it in all the scripts.

### CODE REVIEW

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
I have manually tested that this works on an arm64 build

**Comment by stevekuznetsov** [comment]
Matches the `os::build::host_platform_friendly` mapping, LGTM

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by smarterclayton** [comment]
Flaked due to openshift/origin-gce#14 which we can't debug until the new packages required for Ansible land and we can rebuild the image.

**Comment by tdawson** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
