### PR TITLE
UPSTREAM: 34721: Remove unnecessary cloud provider calls from service controller

### PR DESCRIPTION
**Pull request by pmorie**
Addresses bug https://bugzilla.redhat.com/show_bug.cgi?id=1367229

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by derekwaynecarr** [comment]
@liggitt -- @pmorie needs more time to make sure the fix on the 1.4.x stream is right, we fixed the issue on the 1.3.x stream separately (there has been a big refactor across releases)

**Comment by liggitt** [comment]
is this needed for 1.4? is the fix ready?

**Comment by liggitt** [comment]
is this still in progress or should we close it?

**Comment by derekwaynecarr** [comment]
@liggitt @pmorie -- i think we may be forced to resurrect this as we have a new bz in this impacted area:
https://bugzilla.redhat.com/show_bug.cgi?id=1413650

**Pull request closed without merging**
