### PR TITLE
image: match the integrated registry when using image name in image policy

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/15475

### CODE REVIEW

**Comment by mfojtik** [comment]
@openshift/sig-security for double check as this is touching admission controller

@pweil- FYI

**Comment by mfojtik** [comment]
@smarterclayton @miminar suggested that we should refactor the admission to use the managed image annotation instead of checking for the integrated registry.,

**Comment by smarterclayton** [comment]
The annotation is somewhat worrying.  It's not accurate 100% of the time anymore.

This change looks correct, are there any other attributes that are also affected by the caching?

**Comment by mfojtik** [comment]
@smarterclayton `LocalRewrite` looks suspicious but lacks docs ;-)

**Comment by smarterclayton** [comment]
LocalRewrite should be an output var.  i think it's ok.

**Comment by mfojtik** [comment]
@smarterclayton let's ship it :)

**Pull request merged**
