### PR TITLE
[release-3.11] Bug 1870540: UPSTREAM: 94112: Improve diff check in endpoints controller syncService

### PR DESCRIPTION
**Pull request by soltysh**
Updated version of https://github.com/openshift/origin/pull/25424 with additional fixes that improve networking performance in endpoints controller

### CODE REVIEW

**Comment by damemi** [comment]
/retitle [release-3.11] Bug 1854434: UPSTREAM: 94112: Improve diff check in endpoints controller syncService

**Comment by damemi** [comment]
@soltysh we've pushed some more changes to the upstream PR based on feedback https://github.com/kubernetes/kubernetes/pull/94112 do you want to update this PR with them?

**Comment by soltysh** [comment]
/hold cancel
upstream PR is already approved

**Review by damemi — APPROVED** [review]
/lgtm
/kind bug
/priority critical-urgent

**Review by damemi — APPROVED** [review]
/lgtm

**Pull request merged**
