### PR TITLE
Bug 1220678: Fix web console generic webhook URL

### PR DESCRIPTION
**Pull request by csrwng**
https://bugzilla.redhat.com/show_bug.cgi?id=1220678

### CODE REVIEW

**Comment by csrwng** [comment]
@spadgett ptal

**Comment by liggitt** [comment]
Bindata needs building

**Comment by spadgett** [comment]
LGTM (other than bindata)

**Comment by csrwng** [comment]
bindata updated ... forget to update it every time

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
