### PR TITLE
oc debug: fix crash on attach

### PR DESCRIPTION
**Pull request by rphillips**
o.AttachFunc is nil since we use our own custom `oc debug` command.
Attaching the defaultAttachFunc if nil fixes the crash and gives a
prompt.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618522

### CODE REVIEW

**Comment by sjenning** [comment]
Upstream pick that introduced this https://github.com/openshift/origin/commit/c7e00d1755ffab40b241de9f8c89c6508e92ac79

`oc debug` calls directly into the `AttachOptions.Run()` and does not call `Complete()` which is what initializes `o.AttachFunc` to `defaultAttachFunc` in `kubectl attach` upstream.  Thus upstream does not suffer this with `kubectl attach` but we do with `oc debug`.

LGTM but want CLI to look at this
/cc @sttts @juanvallejo

**Comment by rphillips** [comment]
We could improve the upstream code to avoid the carry patch, but exporting the defaultAttachFunc. The initialization of AttachFunc is odd as well. By instantiating the upstream AttachFunc in the New... constructors the code would be setup from the initial construction to be overridden by our debug implementation.

**Comment by rphillips** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/67615

**Comment by sjenning** [comment]
/hold
on different route proposed upstream

**Comment by juanvallejo** [comment]
lgtm provided upstream PR is approved

**Comment by juanvallejo** [comment]
Also, please split your commit into two. First one should be "UPSTREAM: 67615: attach: Move the AttachFunc default function to the initializer", second one should contain Origin changes

**Comment by rphillips** [comment]
@soltysh rebased and refactored... good to go for another review.

**Comment by soltysh** [comment]
Upstream merged, this is properly updated, approving.

**Pull request merged**
