### PR TITLE
Added unit testing for handler chain

### PR DESCRIPTION
**Pull request by stevekuznetsov**
In order to enable a soon-to-be PR for refactoring the flow of `Run()` in `master.go`, I am implementing unit testing for the order of handler chaining for the API server as we discussed.

This change should ideally be testing the code already in `master.go` to ensure it passes with no other changes. However, that's not possible, so I broke this up into atomic commits to better document what changes I made to the codebase in order to implement the test so that we can convince ourselves nothing about the flow of `master.go` changed and the test *is* testing the existing code.
@deads2k  @liggitt  PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@liggitt I would like suggestions on how to handle argument errors in the handler append functions. Currently the naive implementation was to ignore the handler that was supposed to be added.

**Comment by stevekuznetsov** [comment]
@deads2k Made requested changes, PTAL

**Comment by stevekuznetsov** [comment]
@deads2k  Changed abstractions from functions to interfaces to make their definitions stricter.

**Comment by deads2k** [comment]
Move the test into the first commit and remove your changes for `installSafe`.  I'd like to to see just the current chain that we have.  

This is much closer to what I expected.  It feels like something is missing in the chain, but I'll look for that tomorrow after you pull out your other changes.

**Comment by stevekuznetsov** [comment]
Not sure why GitHub is not honoring the re-ordering of commits I did locally, but `Added testing` should be last. The *only* change to `master.go` that is *not* simply copy-paste is [`Grouped Handler prepending together`](https://github.com/stevekuznetsov/origin/commit/95c368ee83abbcf26e80ba1e20120ec278672ab4). If this change is allowable, this testing is reasonable. If this change is not allowable, then testing must happen on the broken-out `CreateServer` function from the first commit, andthen entirety of the `MasterConfig` has to be mocked out so that methods like [`GetRestStorage`](https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go#L293-458) can function.

**Comment by stevekuznetsov** [comment]
@deads2k PTAL

**Comment by stevekuznetsov** [comment]
[test]

**Comment by smarterclayton** [comment]
I'm ok with some of the changes here (the grouping and ordering are much cleaner) but not the handler prepender abstraction.

**Comment by deads2k** [comment]
> I'm ok with some of the changes here (the grouping and ordering are much cleaner) but not the handler prepender abstraction.

The prepender abstraction exists so that we have a way to verify that our chain gets built in the expected order.  Using that abstraction, we can create a unit test that can definitively determine the handler chain order and with some more swizzling can confirm that the correct filters are applied to traffic based on endpoint.  That makes refactoring and additions safer to perform.

**Comment by smarterclayton** [comment]
Why do we need a test to verify that when we can verify it by observation?
This is defined in one place, in order, and I'm not sure why that requires
some sort of abstraction to test.

On Thu, Jul 2, 2015 at 3:33 PM, David Eads <notifications@github.com> wrote:

> I'm ok with some of the changes here (the grouping and ordering are much
> cleaner) but not the handler prepender abstraction.
>
> The prepender abstraction exists so that we have a way to verify that our
> chain gets built in the expected order. Using that abstraction, we can
> create a unit test that can definitively determine the handler chain order
> and with some more swizzling can confirm that the correct filters are
> applied to traffic based on endpoint. That makes refactoring and additions
> safer to perform.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3500#issuecomment-118141750>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
You can test the combined order by having a function that generates the
wrapped handler from an input handler - you don't need to use a prepender
pattern for that.

On Thu, Jul 2, 2015 at 3:48 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

> Why do we need a test to verify that when we can verify it by
> observation?  This is defined in one place, in order, and I'm not sure why
> that requires some sort of abstraction to test.
>
> On Thu, Jul 2, 2015 at 3:33 PM, David Eads <notifications@github.com>
> wrote:
>
>> I'm ok with some of the changes here (the grouping and ordering are much
>> cleaner) but not the handler prepender abstraction.
>>
>> The prepender abstraction exists so that we have a way to verify that our
>> chain gets built in the expected order. Using that abstraction, we can
>> create a unit test that can definitively determine the handler chain order
>> and with some more swizzling can confirm that the correct filters are
>> applied to traffic based on endpoint. That makes refactoring and additions
>> safer to perform.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3500#issuecomment-118141750>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> Why do we need a test to verify that when we can verify it by observation?
> This is defined in one place, in order, and I'm not sure why that requires
> some sort of abstraction to test.

One refactor was attempted before and I couldn't reason about it.  Pretty sure @liggitt had trouble too.

**Comment by smarterclayton** [comment]
```
handler = methodCall1(handler, <arguments>)
handler = methodCall2(handler, <arguments>)
handler = methodCall3(handler, <arguments>)
```

Is pretty much what the prepend handler is doing.  I'm not specifically about prepend makes the refactor easier?

**Comment by stevekuznetsov** [comment]
@smarterclayton  That was the previous implementation, yes. It was not possible to look at the resulting `http.Handler` and determine that it had been chained correctly from that implementation.

**Comment by smarterclayton** [comment]
"Hates closures" is not a sufficient justification to refactor the structure, because that's idiomatic.

**Comment by stevekuznetsov** [comment]
@deads2k On the upside if the tests don't make it, at least now I know the ins and outs of the chain so I won't break it :)

**Pull request closed without merging**
