### PR TITLE
Add prometheus annotations to webconsole service

### PR DESCRIPTION
**Pull request by spadgett**
/assign @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
AFAIK this is right, would be good to get another set of eyes that can confirm.  Maybe @deads2k or @liggitt or @smarterclayton ?

**Comment by deads2k** [comment]
I don't know how this works.  @smarterclayton are you resolving the endpoints for the service or something to gather them all?  I guess that actually makes sense, but you'd have to twiddle the transport to get the TLS right wouldn't you?

**Comment by spadgett** [comment]
devmapper flake

/retest

**Comment by spadgett** [comment]
I'm able to see uptime for the console testing locally:

prometheus time series collection and processing server 2018-01-26 14-26-16

**Comment by spadgett** [comment]
flake  #17330

/retest

**Comment by spadgett** [comment]
Opened flake #18315

/retest

**Pull request merged**
