### PR TITLE
Update topology graph to next version

### LINKED ISSUE #6491: Incorrect replication controller icon in topology view?
@jwforres @stefwalter I'm guessing this icon is wrong?

openshift_web_console

### PR DESCRIPTION
**Pull request by stefwalter**
Fixes #6491

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2016-01-05 15-41-31

**Comment by stefwalter** [comment]
Dup of #6537

**Comment by spadgett** [comment]
@stefwalter oops, my fault. didn't see your pull.

**Comment by stefwalter** [comment]
@spadgett No worries.

**Pull request closed without merging**
