### PR TITLE
Fix ugorji empty list decoding

### LINKED ISSUE #6936: rebase changed serialization of empty yaml arrays
Previously, empty list of users on a group in the LDAP group sync extended test would be reported as :
```yaml
apiVersion: v1
kind: Group
metadata:
  name: group1
users: []
```

Now it is serialized to:
```yaml
apiVersion: v1
kind: Group
metadata:
  name: group1
users: null
```

@liggitt @deads2k

### PR DESCRIPTION
**Pull request by liggitt**
fixes #6936
WIll open upstream issue to bump ugorji, but that would make us out of sync with etcd again.
Upstream might not see this if they are using fully generated codecs.

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
Made it to the UI tests and timed out on protractor [test]

**Pull request merged**
