### PR TITLE
Clean up bad OVS ports

### PR DESCRIPTION
**Pull request by danwinship**
Apparently just because `ovs-vsctl add-port` returns an error doesn't mean that it didn't do anything, and this isn't considered a bug:

> See this example:
> 
>     [root@plex ~]# ovs-vsctl add-port ovsbr0 foo 
>     ovs-vsctl: Error detected while setting up 'foo': could not open network device foo (No such device).  See ovs-vswitchd log for details.
>     ovs-vsctl: The default log directory is "/var/log/openvswitch".
>     
>     [root@plex ~]# ovs-vsctl show 
>     36a1b8c2-9512-4f38-a9b1-2328ea8832e2
>         Bridge "ovsbr0"
>             Port foo
>                 Interface foo
>                     error: "could not open network device foo (No such device)"
>             Port "ovsbr0"
>                 Interface "ovsbr0"
>                     type: internal
>     
>     [root@plex ~]# ip link add foo type veth peer name veth10
>     
>     [root@plex ~]# ovs-vsctl show 
>     36a1b8c2-9512-4f38-a9b1-2328ea8832e2
>         Bridge "ovsbr0"
>             Port foo
>                 Interface foo
>             Port "ovsbr0"
>                 Interface "ovsbr0"
>                     type: internal

This can cause problems when a pod is deleted while it's still being created, in which case we may delete its veth from one thread while trying to add it to br0 in another.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1595092

### CODE REVIEW

**Comment by dcbw** [comment]
So theoretically kubelet shouldn't be calling both ADD and DEL for a given pod at the same time.  I added locking in kubelet a long time ago specifically for that in https://github.com/kubernetes/kubernetes/pull/37036. Is that somehow broken?

**Comment by danwinship** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1595092#c11

It looks like the problem is one level up: dockershim.StopPodSandbox() is called while dockershim.RunPodSandbox() is still running, but before it finishes SetUpPod(), so it decides that the pod doesn't have networking, and so it doesn't need to call TearDownPod(), so it can proceed directly to StopContainer(), which then destroys the veth out from under the SetUpPod() thread.

**Comment by danwinship** [comment]
(FWIW, the fix to ovscontroller is correct regardless of whether there is also a locking/racing problem in kubelet.)

**Comment by dcbw** [comment]
> It looks like the problem is one level up: dockershim.StopPodSandbox() is called while dockershim.RunPodSandbox() is still running, but before it finishes SetUpPod(), so StopPodSandbox() decides that the pod doesn't have networking, and so it doesn't need to call TearDownPod(), so it can proceed directly to StopContainer(), which then destroys the veth out from under the SetUpPod() thread.

Haha, and that's my fault too because of https://github.com/kubernetes/kubernetes/pull/62874

**Comment by dcbw** [comment]
> It looks like the problem is one level up: dockershim.StopPodSandbox() is called while dockershim.RunPodSandbox() is still running, but before it finishes SetUpPod(), so StopPodSandbox() decides that the pod doesn't have networking, and so it doesn't need to call TearDownPod(), so it can proceed directly to StopContainer(), which then destroys the veth out from under the SetUpPod() thread.

@danwinship oh hah, ok.  IMHO the runtimes should really, really synchronize their pod operations too so that this doesn't happen.  But your explanation makes sense.

**Pull request merged**
