### PR TITLE
don't read buildenv from stdin twice

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1436552

### CODE REVIEW

**Comment by bparees** [comment]
@coreydaley fyi
@openshift/devex ptal

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13758
[merge]

**Comment by bparees** [comment]
@coreydaley the test on line 132 covers stdin for --env-file correctly.  not sure what happened when you copied it for your --build-env-file from stdin test.

**Comment by coreydaley** [comment]
@bparees doh, maybe it failed so I "fixed" it ...

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13650
[merge]

**Pull request merged**
