### PR TITLE
dind: update for latest ovn-kubernetes config changes

### PR DESCRIPTION
**Pull request by dcbw**
Update CLI options and config file format for
https://github.com/openvswitch/ovn-kubernetes/pull/228

@pecameron @rajatchopra @openshift/networking

### CODE REVIEW

**Comment by danwinship** [comment]
should there be some sort of required version bump somewhere?

**Comment by dcbw** [comment]
> should there be some sort of required version bump somewhere?

@danwinship can you expand on that?  not quite sure what you mean...

**Comment by danwinship** [comment]
Like, presumably this change only works with ovn-kubernetes >= version X.Y.Z, but there doesn't seem to be anything enforcing that anywhere. Or is it just assumed that anyone using dind+ovn is building ovn-kubernetes from git master?

**Comment by dcbw** [comment]
> is building ovn-kubernetes from git master?

@danwinship yes.

**Comment by imcsk8** [comment]
LGTM

**Pull request merged**
