### PR TITLE
Make github hide generated files in diffs

### PR DESCRIPTION
**Pull request by soltysh**
This is taken from https://github.com/kubernetes/kubernetes/pull/54766 with some additional changes for origin.

@liggitt ptal

### CODE REVIEW

**Comment by liggitt** [comment]
Hmm, I frequently have to fiddle with this upstream in order to acually see/verify the generated changes are correct. 

Can we do the linguist change to collapse in github only?

**Comment by soltysh** [comment]
> Can we do the linguist change to collapse in github only?

I'll check, but that's reasonable.

**Comment by soltysh** [comment]
@liggitt hiding only on gh, but works fine locally, just like you wanted it, ptal

**Pull request merged**
