### PR TITLE
WIP: Fix the mysql replica extended test

### PR DESCRIPTION
**Pull request by mfojtik**
This is just a canary to fix the mysql replication extended tests

### CODE REVIEW

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(MySQL replication]

**Comment by bparees** [comment]
lgtm, feel free to merge if the test passes.

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(MySQL replication]

**Comment by mfojtik** [comment]
[merge]

@mnagy FYI

**Pull request merged**
