### PR TITLE
Ignore kubelet proxy settings in http probe

### PR DESCRIPTION
**Pull request by juanvallejo**
Picks: https://github.com/kubernetes/kubernetes/pull/68663
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639137

cc @praveenkumar @smarterclayton @soltysh

### CODE REVIEW

**Comment by praveenkumar** [comment]
@juanvallejo I tried it locally and it does work now with proxy env. :+1: 

LGTM

**Comment by soltysh** [comment]
@juanvallejo open a master PR with this cherry-pick, but we'll land it after the rebase.

**Comment by juanvallejo** [comment]
@soltysh 
> open a master PR with this cherry-pick, but we'll land it after the rebase.

https://github.com/openshift/origin/pull/21608

**Pull request merged**
