### PR TITLE
Expose Watch in the Users client API

### PR DESCRIPTION
**Pull request by vbehar**

### CODE REVIEW

**Comment by kargakis** [comment]
@deads2k

**Comment by deads2k** [comment]
@vbehar I'm fine with this and #8447, but unless this is blocking something else I'd like to wait until after 1.2.

**Comment by vbehar** [comment]
ok thanks, it's good for me (I "hacked" my godeps in the mean time)

**Comment by smarterclayton** [comment]
Did you not have to regenerate swagger?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Nm, client only [merge]

**Pull request merged**
