### PR TITLE
UPSTREAM: 66835: cloudprovider: aws: return true on existence check for stopped instances

### LINKED ISSUE #19899: Node labels are lost after Deregister/Register Node events
After stopping/starting a Node (AWS EC2 instance) node labels:
logging-infra-fluentd=true,node-role.kubernetes.io/compute=true
Are missing after the node registers and becomes READY

##### Version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. oc get node ip-177-77-77-100.ec2.internal --show-labels
NAME                            STATUS    ROLES     AGE       VERSION             LABELS
ip-177-77-77-100.ec2.internal   Ready     compute   6d        v1.9.1+a0ce1bc657   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=ip-177-77-77-100.ec2.internal,**logging-infra-fluentd=true,node-role.kubernetes.io/compute=true**,region=primary,zone=default
2. Shut down EC2 Instance 
3. Start up EC2 Instance
4. Run oc get node ip-177-77-77-100.ec2.internal --show-labels

##### Current Result
oc get node ip-177-77-77-100.ec2.internal --show-labels
NAME                            STATUS    ROLES     AGE       VERSION             LABELS
ip-177-77-77-100.ec2.internal   Ready     <none>    1m        v1.9.1+a0ce1bc657   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=ip-177-77-77-100.ec2.internal,region=primary,zone=default
##### Expected Result
We expect to still have the labels **logging-infra-fluentd=true,node-role.kubernetes.io/compute=true** after reboot.

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/66835

xref https://bugzilla.redhat.com/show_bug.cgi?id=1559271

fixes #19899

@derekwaynecarr @jsafrane @liggitt

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
upstream directional change is blessed, but we can carry this in the interim pending it merge upstream.

/approve
/lgtm

**Comment by gnufied** [comment]
There are couple of this that needs this verified. Please do not merge this without approval from @openshift/sig-storage 

/hold

**Comment by gnufied** [comment]
Things that needs to be verified before we merge this:

a. We need to make sure that, nodes that are shutdown can have its pod migrated without attach/detach issues when node object is still around.
b. We need to make sure that - volumes get detached from static pods(not backed by rc/rs) when a node is down for long period of time.
c. We need to make sure that - there are no race conditions for AWS as mentioned in https://github.com/kubernetes/kubernetes/issues/52735 wrt to attach/detach controller attempting to reattach volumes to terminated nodes because on terminate AWS detaches all volumes from node but this PR will keep the node object still around and hence attach/detach controller will consider this as error state and try to "fix" it.

**Comment by sjenning** [comment]
@gnufied re: our discussions on IRC, I think you ok with this now right?  If so, please comment confirming and re-add lgtm.  @derekwaynecarr  already approved.  Thanks!

**Comment by gnufied** [comment]
Yeah I think I am okay with merging this with master.  storage team will backport the other fix for detaching volume from shutdown node. 

/hold cancel

**Comment by gnufied** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1622175 for tracking the storage bug of volumes not getting detached from stopped AWS nodes.

**Pull request merged**
