### PR TITLE
Bug 1973667: undisable NetworkPolicy tests [4.8]

### PR DESCRIPTION
**Pull request by danwinship**
backport of #26231 
/assign @knobunc

### CODE REVIEW

**Comment by danwinship** [comment]
/test e2e-metal-ipi
/test e2e-metal-ipi-ovn-ipv6
(failed due to packet.net issues before)

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-proxy
/override ci/prow/e2e-metal-ipi-ovn-dualstack

(Permafailing on unrelated tests, will investigate that separately)

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-upgrade
/override ci/prow/e2e-metal-ipi-virtualmedia 

This has had a clean test run for both of these and is just flaking at this point on unrelated tests.

**Comment by knobunc** [comment]
/override ci/prow/e2e-gcp-builds

This is not required

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-upgrade

This has passed, but is intermittently flaking on unrelated stuff.  Will chase later.

**Comment by bparees** [comment]
> /override ci/prow/e2e-aws-proxy
> /override ci/prow/e2e-metal-ipi-ovn-dualstack
> (Permafailing on unrelated tests, will investigate that separately)****

@knobunc did you get a chance to look into this?  @gabemontero is now hitting failures in the same jobs in https://github.com/openshift/origin/pull/26275

we need to get bugs open so we can get the required jobs on the origin repo back to green

**Pull request merged**
