### PR TITLE
UPSTREAM: <carry>: add templates to valid_resources list

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/8640

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k ptal

**Comment by deads2k** [comment]
Um, you've done something squirrelly with the whitespace.

**Comment by deads2k** [comment]
@bparees in an ideal world, you wire this up to a reflective test in origin and parses the lines and diffs against our registered RESTStorage resources.  What are my chances of convincing you to do that?

**Comment by bparees** [comment]
blech. converted tabs to spaces, as mother nature intended!  will fix.

**Comment by bparees** [comment]
> @bparees in an ideal world, you wire this up to a reflective test in origin and parses the lines and diffs against our registered RESTStorage resources. What are my chances of convincing you to do that?

low.  i'd accept it as an issue opened for follow up, but for now i'd like to just get this fixed :)

**Comment by bparees** [comment]
(tabs resurrected)

**Comment by deads2k** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
