### PR TITLE
Rebase Kube to v0.16.2

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k see d5c298c6bec01e956bf36edfb1040dad64ad414c I simplified AttributeRestrictions.  I would recommend avoiding runtime.EmbeddedObject for now (it was choking the gob.Encoder) because no one else is using it and until the conversion stuff cleans up upstream we don't know for sure how long that will last.

**Comment by smarterclayton** [comment]
@derekwaynecarr 

```
projects/recreated-project
E0504 22:41:22.746289   20421 cache.go:209] error synchronizing: ResourceAccessReview "" is forbidden: Namespace recreated-project is terminating
E0504 22:41:23.748323   20421 errors.go:66] apiserver received an error that is not an api.Status: Namespace recreated-project termination is in progress, waiting for [kubernetes]
Error from server: Namespace recreated-project termination is in progress, waiting for [kubernetes]
!!! Error in hack/test-cmd.sh:470
```

What is missing here?  Unapplied UPSTREAM?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@ncdc exec is failing with 

```
[INFO] Validating exec
env: registry: No such file or directory
Error: Error executing remote command: Error executing command in container: exit status 127
```

thoughts?

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[vipmerge]

**Comment by deads2k** [comment]
is that a thing!?

**Pull request merged**
