### PR TITLE
revert remove "openshift.io/container.%s.image.entrypoint annotation …

### PR DESCRIPTION
**Pull request by jim-minter**
…and clarify new-app maximum name length"

### CODE REVIEW

**Comment by jim-minter** [comment]
[test]

**Comment by jim-minter** [comment]
flaked, otherwise I believe this is good - please merge.

**Comment by bparees** [comment]
i'm not convinced we need to revert this.

**Comment by bparees** [comment]
[merge]

**Comment by jim-minter** [comment]
flake #12322

**Comment by jim-minter** [comment]
@bparees hold off on merge this for now please

**Pull request closed without merging**
