### PR TITLE
Use less precise branding on OAuth page templates

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Using less precise branding on the OAuth page templates allows for no
diff to be necessary between the Origin and OCP distributions of these
pages.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@liggitt @jwforres @smarterclayton FYI

[merge]

**Comment by liggitt** [comment]
removed merge. background images were also different

**Comment by stevekuznetsov** [comment]
The diff on the image lines is from the alt-text at the end. Diff was generated with:

```
$ sed -i 's/OpenShift Origin/OpenShift/g' pkg/auth/server/{login,errorpage,selectprovider}/templates.go
```

I was making this change per @smarterclayton's request -- assumed we had sign-off from branding for it. Who should I tag in for that?

**Comment by jwforres** [comment]
this is the first I am hearing of this, please hold until I can talk to
some people

**Comment by stevekuznetsov** [comment]
> this is the first I am hearing of this, please hold until I can talk to some people

Will do

**Comment by smarterclayton** [comment]
Steve, in the short term you can use a build tag for these and split them.

**Comment by smarterclayton** [comment]
Both would be checked in to tree and we'll do an extra build tag from the spec file.

**Comment by stevekuznetsov** [comment]
Sure, I'll bring back the platform name `ldflag`

**Comment by smarterclayton** [comment]
Was actually thinking of something else.  The entire file will change if logos are different

**Comment by smarterclayton** [comment]
We'd just add a build tag "// +build ocp" or something and differentiate at product time.  Default would be Origin, then all dev happens in Origin for these

**Pull request closed without merging**
