### PR TITLE
default the imagestream status.dockerImageRepository

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton this is my proposed solution to the email discussion we've been having about the imagechange controller and its interaction with the imagestream decorator.

I suspect you won't like it, but consider it a starting point for discussion.  I consider it a reasonable assumption for 4.0 because we know the registry operator will always be present and will always install the registry with this service name, so even if the value isn't valid initially, it will be eventually.  (and to the extent that it's not valid initially, i don't think you can do anything useful until the registry exists anyway).

For existing clusters that already have a registry in docker-registry.default.svc, the assumption is they have explicitly configured the internalRegistryHostname, so this defaulting won't matter to them.


/cc @dmage @legionus

**Comment by bparees** [comment]
@jwforres I believe this would address the "pushing to ip address" issue for now, by ensuring imagestreams always use some sort of default internal registry hostname.  ptal.

**Comment by dmage** [comment]
@bparees if we want to avoid IPs, we may want to change this:

https://github.com/openshift/origin/blob/24f5d4259b4181b6f77903b7aa634f795d5d1f53/pkg/image/apiserver/registryhostname/retriever.go#L38

**Comment by bparees** [comment]
> @bparees if we want to avoid IPs, we may want to change this:

yeah, I didn't want to go so far as changing that, I was trying to inject the change at the lowest/least impactful place possible, but I definitely considered just setting it there too.

**Comment by bparees** [comment]
Since the imagechangecontroller will now get bounced by the controller operator when the internalRegistryHostname changes (at least it will when i'm done with it), this is no longer strictly necessary.

we are also going to have the samples operator not install the imagestreams until the internalRegistryHostname is set which will also prevent the caching of invalid values by the imagechangecontroller.

**Pull request closed without merging**
