### PR TITLE
Missing mobile hamburger dropdown on chromeless log pages

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/6957

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
LGTM, but will conflict with #6965

**Comment by jwforres** [comment]
@benjaminapetersen do you want to just roll this into yours?

**Comment by benjaminapetersen** [comment]
@jwforres, sure, I can copy this over into mine since its just a few lines in the same 3 files.

**Comment by jwforres** [comment]
ok closing this PR then

**Pull request closed without merging**
