### PR TITLE
NO-ISSUE: Add Capability and FeatureGate checks to OLMv1 tests

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Comment by tmshort** [comment]
Alternative to #29283
This one doesn't update openshift/api

**Comment by tmshort** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by wking** [comment]
[The tech-preview payload run][1] failed on `KubeAPIErrorBudgetBurn`.  It skipped the OLM tests:

```console
$ curl -s https://storage.googleapis.com/test-platform-results/logs/openshift-origin-29290-ci-4.18-e2e-aws-ovn-techpreview/1856776673144344576/build-log.txt | grep OCPFeatureGate:NewOLM
started: 0/281/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
skipped: (2.4s) 2024-11-13T21:04:00 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
started: 0/291/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
skipped: (3.1s) 2024-11-13T21:04:08 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
started: 0/354/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
skipped: (2.7s) 2024-11-13T21:04:46 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
```

because it was run early enough that openshift/cluster-version-operator#1108 wasn't in 4.18 CI builds yet.  Launching a fresh tech-preview job:

/test e2e-gcp-ovn-techpreview

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-29290-ci-4.18-e2e-aws-ovn-techpreview/1856776673144344576

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by neisw** [comment]
/approve
/hold

Looked like `e2e-gcp-ovn-techpreview ` had the same skip.  Feel free to remove the hold when you are ready.

**Comment by wking** [comment]
[e2e-gcp-ovn-techpreview][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144/artifacts/e2e-gcp-ovn-techpreview/openshift-e2e-test/build-log.txt | grep OCPFeatureGate:NewOLM
started: 0/27/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
skipped: (6.3s) 2024-11-14T00:06:50 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
started: 0/118/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
skipped: (6.3s) 2024-11-14T00:08:06 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
started: 5/489/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
skipped: (4.2s) 2024-11-14T00:16:50 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144/artifacts/e2e-gcp-ovn-techpreview/openshift-e2e-test/build-log.txt | grep -B3 OCPFeatureGate:NewOLM | tail -n4
skip [github.com/openshift/origin/test/extended/olm/olmv1.go:168]: Test only runs with OLMv1 capability
Ginkgo exit error 3: exit with code 3

skipped: (4.2s) 2024-11-14T00:16:50 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
```

Hmm, that's surprising.

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144/artifacts/e2e-gcp-ovn-techpreview/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.capabilities.knownCapabilities[]' | grep O
OperatorLifecycleManager
```

So still no sign of `OperatorLifecycleManagerV1`.

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144/artifacts/e2e-gcp-ovn-techpreview/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-769cf984fc-p7xr7_cluster-version-operator.log | head -n1
I1113 23:02:05.498754       1 start.go:23] ClusterVersionOperator v1.0.0-1268-g2e594cdd-dirty
```

In a CVO checkout:

```console
cluster-version-operator$ git --no-pager log --first-parent --format='%ad %h %s' -2
Wed Nov 13 18:45:27 2024 +0000 b0eddfee Merge pull request #1108 from LalatenduMohanty/add_olmv1_capability_api
Mon Nov 11 15:57:13 2024 +0000 2e594cdd Merge pull request #1091 from petr-muller/scaffold-update-status-operator
```

so this cluster is still not using the new CVO commit?  Back to [the job run][2]

```
INFO[2024-11-13T22:21:20Z] Building release initial from a snapshot of ocp/4.18 
INFO[2024-11-13T22:21:20Z] Building release latest from a snapshot of ocp/4.18
```

Checking `app.ci`:

```console
$ oc whoami -c
default/api-ci-l2s4-p1-openshiftapps-com:6443/wking
$ oc -n ocp get -o json imagestream 4.18 | jq -c '.status.tags[] | select(.tag == "cluster-version-operator").items[] | {created, image}'
{"created":"2024-11-13T19:20:49Z","image":"sha256:91dda68f5256eeae7c934e677e7a8b36add124faad0c4124e44063af2c008efa"}
{"created":"2024-11-11T16:23:01Z","image":"sha256:762a726e9118e1879691044d61c9cd6e388c2add8e6da920b74ba455c8975a55"}
{"created":"2024-11-11T12:47:21Z","image":"sha256:bef79b6f45e551a34e3d22877721cf8f4937b80f0b233d34fdeb259181313c48"}
$ oc image info registry.ci.openshift.org/ocp/4.18@sha256:91dda68f5256eeae7c934e677e7a8b36add124faad0c4124e44063af2c008efa | grep 'Created\|vcs-ref'
Created:       9h ago
               vcs-ref=b0eddfee2890ed868cbecc36594490e9afa6c9f1
```

Hmm, certainly looks like pulling `ocp/4.18` at 22:21 UTC should have picked up that most-recent commit pushed 19:20 UTC?  Not sure why the running CVO in this cluster is claiming to be from the older commit.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144
[2]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144#1:build-log.txt%3A7

**Comment by wking** [comment]
More poking at that run:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856824118029062144/artifacts/build-resources/imagestreams.json | jq -c '.items[] | .metadata.name as $n | .status.tags[] | select(.tag == "cluster-version-operator").items[] | {created, image, imageStream: $n}'
{"created":"2024-11-13T19:14:55Z","image":"sha256:762a726e9118e1879691044d61c9cd6e388c2add8e6da920b74ba455c8975a55","imageStream":"stable"}
{"created":"2024-11-13T19:14:59Z","image":"sha256:762a726e9118e1879691044d61c9cd6e388c2add8e6da920b74ba455c8975a55","imageStream":"stable-initial"}
```

So that's picking up the older hash.  But I'm not clear on why, since it seems like it had been rotated out of the source ImageStream by that point.  Maybe syncing between `app.ci` and the build clusters is slow?  Testing again:

/test e2e-gcp-ovn-techpreview

**Comment by wking** [comment]
No new TechPreview jobs on the recent commits, but checking [the one I'd launched last night][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856932509166604288/artifacts/e2e-gcp-ovn-techpreview/openshift-e2e-test/build-log.txt | grep NewOLM
started: 2/169/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
passed: (5s) 2024-11-14T07:23:01 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed [Suite:openshift/conformance/parallel]"
started: 2/274/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
passed: (13.3s) 2024-11-14T07:25:02 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 operator installation should install a cluster extension [Suite:openshift/conformance/parallel]"
started: 3/403/508 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
passed: (5.7s) 2024-11-14T07:28:12 "[sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 Catalogs should be installed [Suite:openshift/conformance/parallel]"
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856932509166604288/artifacts/e2e-gcp-ovn-techpreview/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.capabilities.enabledCapabilities[]' | grep O
OperatorLifecycleManager
OperatorLifecycleManagerV1
```

So the CVO / ClusterVersion bump finally came through, the `OperatorLifecycleManagerV1` capability is enabled, the tech-preview suite is running the tests on the capability, and the tests are passing :+1:
[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29290/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1856932509166604288

**Comment by tmshort** [comment]
This PR was updated to the point it will no longer pass, because it's expecting v1 APIs now, but it's good to know that the code that deals with capabilities, etc, passes.

**Comment by joelanford** [comment]
The 4.18 CI builds seem to be failing to even create payload images since our sync changes merged. As I understand it, nothing here will pass until we have a CI image that picks up the changes we merged last night.

**Comment by tmshort** [comment]
/retitle OPRUN-3594: Add Capability and FeatureGate checks to OLMv1 tests

**Pull request merged**
