### PR TITLE
UPSTREAM 35285: Remove stale volumes if endpoint/svc creation fails.

### PR DESCRIPTION
**Pull request by humblec**
Bug# https://bugzilla.redhat.com/show_bug.cgi?id=1388868
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs @jsafrane PTAL.

**Comment by pweil-** [comment]
@childsb @eparis please add sign off/justification before merge as this is not in the upstream 1.4 branch.  Thanks

(cc @ncdc @soltysh)

**Comment by soltysh** [comment]
If this isn't fixing a blocker bug and it didn't land in 1.4 I'm against it.

**Comment by humblec** [comment]
@soltysh this is a blocker bug fix. Without this fix, the underlying storage will run out of space if there is an error in endpoint/svc creation . Also its very difficult to track the culprit from admin point of view.

**Comment by ncdc** [comment]
Please provide a link to the bz in the PR description if you can

**Comment by humblec** [comment]
@ncdc Done. Please let me know if you need more details on this. Thanks!

**Comment by childsb** [comment]
https://github.com/kubernetes/kubernetes/pull/35285

**Comment by childsb** [comment]
This is merged upstream.
[test]

**Comment by childsb** [comment]
[test]

**Comment by soltysh** [comment]
> @soltysh this is a blocker bug fix

:+1: for merge

**Comment by childsb** [comment]
[merge]

**Pull request merged**
