### PR TITLE
Reimplemented the Bash preamble init script

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/cc @smarterclayton @marun

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test][extended]

**Comment by stevekuznetsov** [comment]
Jenkins dead? @danmcp

**Comment by danmcp** [comment]
@stevekuznetsov It's being updated.  Started about 2 mins ago and will be back in a couple.

**Comment by smarterclayton** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Conformance flake on the k8s logs test

Re[test]

**Comment by stevekuznetsov** [comment]
Same flake again, re[test]

**Comment by stevekuznetsov** [comment]
For a moment I'm wondering if it's possible I am to blame for the `kubectl logs` test failing... it's now three times in a row it's failed. Is that possible @smarterclayton with these changes? I can't see how, those are `ginkgo` tests ... 

re[test]

**Comment by smarterclayton** [comment]
No, it's an upstream issue.

On May 13, 2016, at 8:39 AM, Steve Kuznetsov <notifications@github.com>
wrote:

For a moment I'm wondering if it's possible I am to blame for the kubectl
logs test failing... it's now three times in a row it's failed. Is that
possible @smarterclayton <https://github.com/smarterclayton> with these
changes? I can't see how, those are ginkgo tests ...

re[test]

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/8853#issuecomment-219031498>

**Comment by smarterclayton** [comment]
[test] now that conformance is fixed.

On May 13, 2016, at 10:35 AM, OpenShift Bot <notifications@github.com>
wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/3805/)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/8853#issuecomment-219061157>

**Comment by stevekuznetsov** [comment]
Conformance is taking 3h to run ... @smarterclayton is this expected?

**Comment by stevekuznetsov** [comment]
Lots of waiting around on pods:
```
May 13 12:46:51.671: INFO: Waiting for pod server in namespace 'e2e-tests-prestop-srdku' status to be 'running'(found phase: "Pending", readiness: false) (2m16.478716884s elapsed)
```

**Comment by smarterclayton** [comment]
Cancel the job and restart - if it happens again we'll raise the red flags.

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
Flake on `test-cmd` that seems related ...
```
/data/src/github.com/openshift/origin/test/cmd/../../hack/cmd_util.sh: line 206: os::text::clear_last_line: command not found
``` 

Unclear how that could flake without 100% probability, I'll look into it.

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
logs 404ed ... re[test]

**Comment by stevekuznetsov** [comment]
Some weird networking flakes [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/1160/consoleFull):
```
/data/src/github.com/openshift/origin/hack/lib/init.sh: line 13: find: command not found
[INFO] Saving cluster configuration
cp: cannot stat ‘/tmp/openshift/test-extended/networking/subnet/openshift.local.config/*’: No such file or directory
[ERROR] Failed to deploy cluster for plugin: {subnet}
```
@marun could you help me parse out the failures there?

Weird failures without stacktrace in test-cmd...
```
Now using project "cmd-authentication" on server "https://127.0.0.1:28443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
Running test/cmd/authentication.sh:17: executing 'oadm policy add-role-to-user admin scoped-user' expecting success...
[INFO] Stacked plot for log subset "iops" written to /tmp/openshift/test-cmd//logs/iops.pdf
[INFO] Stacked plot for log subset "paging" written to /tmp/openshift/test-cmd//logs/paging.pdf
[INFO] Stacked plot for log subset "cpu" written to /tmp/openshift/test-cmd//logs/cpu.pdf
[INFO] Stacked plot for log subset "queue" written to /tmp/openshift/test-cmd//logs/queue.pdf
[INFO] Stacked plot for log subset "memory" written to /tmp/openshift/test-cmd//logs/memory.pdf
[INFO] Dumping etcd contents to /tmp/openshift/test-cmd//artifacts/etcd_dump.json

[FAIL] !!!!! Test Failed !!!!

-------------------------------------

++ Building go targets for linux/amd64: tools/junitreport
++ Placing binaries
/data/src/github.com/openshift/origin/hack/build-go.sh took 4 seconds
Of 309 tests executed in 148.807s, 308 succeeded, 1 failed, and 0 were skipped.

In suite "github.com/openshift/origin/test/cmd/authentication/scopedtokens", test case "" failed:
=== BEGIN TEST CASE ===
=== END TEST CASE ===

hack/test-cmd.sh took 279 seconds
```
The log doesn't look good:
```
=== BEGIN TEST SUITE github.com/openshift/origin/test/cmd/authentication ===
=== BEGIN TEST SUITE github.com/openshift/origin/test/cmd/authentication/scopedtokens ===
=== BEGIN TEST CASE ===
=== END TEST CASE ===
=== END TEST SUITE ===
```

We don't seem to be closing the suite contexts correctly.

re[test]

**Comment by marun** [comment]
@stevekuznetsov dind provisioning is failing due to findutils not being installed in the dind image.  findutils might be installed by default on a fedora/centos/rhel vm or baremetal install, but dind is based on the f23 docker image and findutils needs to be explicitly installed here:

https://github.com/openshift/origin/blob/master/images/dind/Dockerfile#L23

**Comment by stevekuznetsov** [comment]
Another flake on the first line in `authentication.sh` -- will look into it

**Comment by marun** [comment]
@stevekuznetsov This PR needs to update the dind dockerfile to install findutils on the dind image so that your update to the dind provisioning will work.  Is there a reason to track that oversight as #9303?

**Comment by stevekuznetsov** [comment]
Ah sorry, misunderstood you. Didn't realize this was caused by me.

**Comment by stevekuznetsov** [comment]
integration flaked with https://github.com/openshift/vagrant-openshift/issues/460

**Comment by stevekuznetsov** [comment]
@smarterclayton I think this is ready

**Comment by smarterclayton** [comment]
LGTM as well [merge]

**Comment by stevekuznetsov** [comment]
:confetti_ball: :tada: :confetti_ball: :tada: :confetti_ball: :tada: :confetti_ball: :tada:

**Pull request merged**
