### PR TITLE
Add python 3.6 S2I image to examples

### PR DESCRIPTION
**Pull request by alexcern**
Python 3.6 S2I image was added by sclorg/s2i-python-container#215

### CODE REVIEW

**Comment by bparees** [comment]
thanks @alexcern 

you're going to need to run hack/update-generated-bindata.sh too.

/approve
/ok-to-test

**Comment by alexcern** [comment]
Thanks @bparees
I ran hack/update-generated-bindata.sh and rebased but some tests still fail. I'm not sure what to do next as no failure seems related to the change.

**Comment by bparees** [comment]
yeah i don't think the failures are related to your change.
/retest

**Pull request merged**
