### PR TITLE
Bug 2045590: Alibaba: enable init for alibabacloud provider

### PR DESCRIPTION
**Pull request by kwoodson**
In an attempt to fix the e2e-alibaba tests, I have modified the import statement to call the init.

### CODE REVIEW

**Comment by kwoodson** [comment]
@petr-muller The results from your link https://prow.ci.openshift.org/log?container=test&id=1489377614979141632&job=origin-26818--e2e-alibaba

```
Writing JUnit report to /logs/artifacts/junit/junit_e2e_20220204-004754.xml

error: 18 fail, 1164 pass, 1695 skip (41m59s)
```

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
