### PR TITLE
commit checker log

### PR DESCRIPTION
**Pull request by deads2k**
Adds logging to the commit checker so we can look at it in CI.

@stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
+ make verify-commits -j
hack/verify-upstream-commits.sh
[INFO] [17:33:01+0000] hack/verify-upstream-commits.sh exited with code 0 after 00h 00m 02s
```

Seems like we have no `.git`

**Comment by deads2k** [comment]
@stevekuznetsov is this fixed?  We're at risk for broken deps without verify scripts working.

**Comment by stevekuznetsov** [comment]
Sorry, I've been on PTO -- @smarterclayton do you want to just add the `.git` to our sync into `openshift/origin-release` container? or fix this another way?

**Comment by smarterclayton** [comment]
Oh, I was going to move this to a job in ci-operator that had git.

**Comment by deads2k** [comment]
> Oh, I was going to move this to a job in ci-operator that had git.

Still planning to do that?  Now that we rely on glide update, it's a risk.

**Comment by deads2k** [comment]
tide obeys travis

**Pull request closed without merging**
