### PR TITLE
Remove retry logic when waiting for haproxy listening on ports

### PR DESCRIPTION
**Pull request by ramr**
As discussed, removed the max retry logic - the {readi,live}ness probes will ensure container is restarted past the "deadline" + add an lsof image sanity check.

@smarterclayton  PTAL thx

### CODE REVIEW

**Comment by smarterclayton** [comment]
Wouldn't this not fail liveness checks or readiness since the old process could still be listening on 1936?

**Comment by ramr** [comment]
Good point, didn't think about that - yeah its possible it would never fail and this would keep looping. The retry seems the lesser of the 2 evils. Closing this out - let me mull on it a bit more.

**Comment by smarterclayton** [comment]
We may just need to have a parameter which is total time, and we loop until
we cross that threshold, then we fail and bubble it up.  Admins set it
based on how long they expect haproxy to load, but our default is 60
seconds or something.

**Comment by ramr** [comment]
Ok - will add something for that.

**Pull request closed without merging**
