### PR TITLE
Revert "Revert "Add vlan/macvlan/ipvlan incontainer master tests""

### PR DESCRIPTION
**Pull request by mlguerrero12**
Reverts #27766

### CODE REVIEW

**Comment by mlguerrero12** [comment]
Hi @dgoodwin @bparees, I fixed the issue of the original PR. Please review this one.

**Comment by bparees** [comment]
> Hi @dgoodwin @bparees, I fixed the issue of the original PR. Please review this one.

networking team should have all the OWNER permissions needed to approve this(once TRT agrees it is good to go back in).  cc @trozet

**Comment by mlguerrero12** [comment]
@cgoncalves, please review this PR. Made some changes to fix the issue present in #27700

**Comment by dgoodwin** [comment]
Based on the payload results and the fact this test is not failing in your presubmits, it looks like it's ok to me.
/approve

**Pull request merged**
