### PR TITLE
Upstream 1.2.2 picks

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
test flaked with https://github.com/openshift/origin/issues/8399
[test]

**Comment by liggitt** [comment]
@ncdc PTAL

**Comment by ncdc** [comment]
LGTM

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/2961/ had a clean conformance test, [merge]

**Pull request merged**
