### PR TITLE
Make sure extended networking isolation test doesn't run for subnet plugin

### PR DESCRIPTION
**Pull request by dcbw**
Only multitenant supports isolation.

Fixes: 2cb2a753beb0de6830d93d4c179a82125288e5a9

### CODE REVIEW

**Comment by dcbw** [comment]
[test][extended:networking]

**Comment by marun** [comment]
lgtm

**Comment by dcbw** [comment]
@marun are the NodePort tests extended tests expected to fail?  So far the extended failures are:

should be able to create a functioning NodePort service
should release NodePorts on delete

**Comment by dcbw** [comment]
[test]

**Comment by marun** [comment]
@dcbw No, the NodePort tests are not expected to fail.

**Comment by marun** [comment]
@dcbw I wasn't able to replicate the NodePort failures earlier today but I am seeing them now against this PR.  Will bisect to figure out the cause.

**Comment by liggitt** [comment]
If it's the proxy config PR that merged, we need to know asap

**Comment by marun** [comment]
@liggitt The failure is a couple of weeks old, so no need to revert.

**Comment by marun** [comment]
@dcbw I think I've traced the problem to the NodePort tests switching from ssh to a HostExec pod to verify that a port allocated for a NodePort service is allocated on the host [1].  I tried debugging the test with delve but it hangs for some reason.  May want to update this PR to skip the affected services tests to get the job passing again since it may take a bit longer to resolve.

1:  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L407

**Comment by marun** [comment]
@dcbw Please close in favor of #7244, which includes your commit as well as a couple more.

**Comment by dcbw** [comment]
@marun ok, works for me.  Closed in favor of https://github.com/openshift/origin/pull/7244

**Pull request closed without merging**
