### PR TITLE
WIP - Experiment with glide

### PR DESCRIPTION
**Pull request by smarterclayton**
Now that they've fixed the importing issues.

Todo:

* [ ] No more carried patches - fork repos
* [ ] Need to try update and see how ugly it is
* [ ] Does this complicate our diff detection
* [ ] Seems to be importing .git dirs

### CODE REVIEW

**Comment by jimmidyson** [comment]
.git & .hg dirs can be deleted from vendor dir safely & vendor committed. You can then use the `--update-vendored` flag to add/update dependencies & the .git/.hg will be removed after add/update - works nicely

**Comment by smarterclayton** [comment]
Is there a way to make GOVENDOREXPERIMENT work in 1.4?

**Comment by jimmidyson** [comment]
Not that I know of. Annoyingly the vendor dir doesn't have a GOPATH style src dir. I think you'd need to script up creating a temp GOPATH with vendor dir stuff in & prepend that to existing GOPATH.

**Comment by smarterclayton** [comment]
Which technically we do anyway, but I don't know if it would break things
like vscode or other editor integrations.  That's my big hesitation here -
we're not ready to move off go 1.4 yet.  We could theoretically symlink
Godeps/_workspace/src to vendor/

**Comment by jimmidyson** [comment]
Aren't symlinks notoriously bad when working with go? If you're not ready to move off of 1.4 then I probably wouldn't migrate to a vendor dir until you are.

**Comment by smarterclayton** [comment]
We use symlinks in some places.  It has issues with clean builds in some
cases, but not the end of the world.

**Comment by mattfarina** [comment]
Hi folks. On the Glide tip of master there is now a flag for update and install of `--strip-vcs` that may help. It tells Glide to remove the VCS directories. It will be in the 0.10 release later this month. There is a plugin project someone is working on reducing `vendor/` directory files if you're going to check it into your VCS called [`glide-vc`](https://github.com/sgotti/glide-vc).

I'm curious how this experiment will go. Best of luck.

**Comment by smarterclayton** [comment]
Thanks - hoping Glide will simplify some of the pain that comes with rebasing 1 million+ lines of go code.  Will definitely have feedback as we fine tune the process.

**Comment by mfojtik** [comment]
@smarterclayton why is this closed? do we want to keep up experimenting with glide?

**Comment by smarterclayton** [comment]
Not a priority right now.

**Pull request closed without merging**
