### PR TITLE
Drop Go 1.4 conditions, switch to 1.6 by default

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@csrwng can you fix these govet errors so I can kick this over?

**Comment by smarterclayton** [comment]
@sdodson @brenton FYI I'm preparing to drop Go 1.4.2 support from Origin, so the next master branch pick up for OSE will probably need to switch as well.

**Comment by csrwng** [comment]
Submitted https://github.com/openshift/origin/pull/8984

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by csrwng** [comment]
Hitting https://github.com/openshift/origin/issues/8946
and extended test failure on readiness probe.

[test]

**Comment by sdodson** [comment]
It'd be nice if we handled rpm builds in this same pr. https://github.com/smarterclayton/origin/pull/19 will take care of that

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
