### PR TITLE
WIP - [release-4.5] Bug 1939550: Update tests to use Ruby 2.6

### PR DESCRIPTION
**Pull request by adambkaplan**
Update orign tests to use Ruby 2.6 instead of Ruby 2.5.
github.com/openshift/ruby-hello-world was updated to use Ruby 2.7,
which breaks many tests that were based on Ruby 2.5.

Tests which relied on the Dockerfile in ruby-hello-world are disabled
because it explicitly uses the ruby 2.7 imagestream, which is not
available on OCP 4.5.

Other changes:

- Fix check on build args warning
- Test that checks if we infer the origin imagestream tag was switched
from a centos image to the ruby imagestream.

### CODE REVIEW

**Comment by gabemontero** [comment]
preliminary

/lgtm

can readd of something 4.5 specific crops up in the e2e results

**Comment by adambkaplan** [comment]
/hold

Is ruby 2.7 not in 4.5?

**Comment by xiuwang** [comment]
> Is ruby 2.7 not in 4.5?
Yes, on 4.5, latest tag is pointing to ruby:2.6 istag

**Comment by gabemontero** [comment]
update the PR title and and description @adambkaplan and I'll apply the lgtm

**Comment by adambkaplan** [comment]
/hold cancel

Updated to use Ruby 2.6.
Keeping the WIP until I see green runs, or failures that are unrelated to this PR.

**Comment by adambkaplan** [comment]
/close

Adding this to the list of "test fixes ignored because 4.5 is almost EOL."
Needs https://github.com/openshift/origin/pull/25831 to be cherry picked here as well to fix the perm-fail in e2e-agnostic-cmd.

**Pull request closed without merging**
