### PR TITLE
Reduce local-up-master to a single script file with associated yaml

### PR DESCRIPTION
**Pull request by smarterclayton**
Integration tests need to be able to reference use this script without
grabbing all of origin, so for the short term I'm going to run it from
a configmap in the template, and then eventually it will be added to
one of the images.

Collapse the various libraries into one script, use the same namespace,
cut anything that isn't related to start, and rename the yaml files
so they live in the same dir. Have test-cmd reference it.

Fix two bugs in test/cmd that no longer worked on Mac.

This code would be a lot more succint and reliable if written in Go.
I am displeased.

### CODE REVIEW

**Comment by soltysh** [comment]
> This code would be a lot more succint and reliable if written in Go.
> I am displeased.

Why not doing this right away instead of moving files back and forth? @juanvallejo will you be able to find the time, if not I can easily take a stab at it b/c we'll need to cleanup integration tests, so both could share some code hopefully. We still need to get rid of the old config handling in integration. @smarterclayton wdyt?

**Comment by juanvallejo** [comment]
@soltysh 
>  will you be able to find the time, if not I can easily take a stab at it b/c we'll need to cleanup integration tests, so both could share some code hopefully. We still need to get rid of the old config handling in integration.

Sure, I'd be fine with either you or I opening a starting PR, and beginning to work on this through that

**Comment by smarterclayton** [comment]
I would like hypershift to have a private, hidden command option that does:

1. takes a root directory argument and creates the same stuff that the
script does
2. uses the go libraries we have for certs to mint certs in directory
instead of cfssl
3. calculates the public IP address the same way `--print-ip` did
4. launches the children using `os/exec` and is able to clean up the
children on exit (should happen already)
5. takes zero arguments beyond that
6. It would expect etcd and hyperkube binaries to be on the path, and exit
if it can't find them

That effectively replaces unreliable bash with reliable go code that I can
review.

**Comment by smarterclayton** [comment]
not supported for anyone except integration tests or someone running hack
local up.

**Comment by soltysh** [comment]
> That effectively replaces unreliable bash with reliable go code that I can review.

SGTM, I'll work on that through the rest of the week.

**Comment by soltysh** [comment]
See https://jira.coreos.com/browse/MSTR-382 for the direction this is going in.
/close

**Pull request closed without merging**
