### PR TITLE
Fix field selectors for origin types

### PR DESCRIPTION
**Pull request by liggitt**
* Moved `*ToSelectableFields` functions to api packages
* Added helper to make field label conversion functions
* Added tests to make sure current selectable fields have conversions, and all legacy selectable fields have conversions
* Added field selection filtering to project, template, sdn objects
* Fixed several uses of "name" field label selectors to use "metadata.name"
* Preserved "name"->"metadata.name" conversions for:
  * Build
  * BuildConfig
  * ImageStream

Previously, the only registered and usable field labels for origin types were:
```
err = kapi.Scheme.AddFieldLabelConversionFunc("v1", "Build",
		case "name":			return "metadata.name", value, nil
		case "status", "podName": return label, value, nil

err = kapi.Scheme.AddFieldLabelConversionFunc("v1", "BuildConfig",
		case "name":			return "metadata.name", value, nil

err = kapi.Scheme.AddFieldLabelConversionFunc("v1", "ImageStream",
		case "name":			return "metadata.name", value, nil
		case "metadata.name", "spec.dockerImageRepository", "status.dockerImageRepository":			return label, value, nil

err := api.Scheme.AddFieldLabelConversionFunc("v1", "Route",
		case "metadata.name", "spec.host", "spec.path", "spec.to.name": return label, value, nil
```

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1269256

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton @deads2k PTAL

**Comment by smarterclayton** [comment]
[test]

On Oct 31, 2015, at 1:08 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6546/)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5516#issuecomment-152751161>.

**Comment by liggitt** [comment]
clean test runs

**Comment by smarterclayton** [comment]
LGTM [merge] although is still don't like the overhead of this approach.

**Comment by liggitt** [comment]
I don't either, will add a TODO to look to improve that upstream

**Comment by liggitt** [comment]
Flake
```
Error from server: imageStream "newrepo" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in test/cmd/images.sh:115
	'oc tag mysql:5.5 newrepo:latest' exited with status 1
Call stack:
	1: test/cmd/images.sh:115 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:276
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:276 main(...)
```

**Comment by liggitt** [comment]
flake:
```

[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i complete'...
ruby-sample-build-1   Source    Git       Failed    About a minute ago   1m57s
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i complete'

[FAIL] !!!!! Test Failed !!!!
```
[merge]

**Pull request merged**
