### PR TITLE
Bug 1207952: Update vagrant cluster commands

### PR DESCRIPTION
**Pull request by liggitt**
@deads2k review

### CODE REVIEW

**Comment by liggitt** [comment]
Was able to successfully create the vagrant cluster with these changes. Node spinup failed because the node config was a json file, not a yaml file, but that should be fixed in the other PR

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
Side note.  Can we add vagrant set up to our extended test runs?

@derekwaynecarr @mfojtik

**Comment by liggitt** [comment]
flaky test, re[merge]

**Comment by liggitt** [comment]
re[merge]

**Comment by liggitt** [comment]
re[merge]

**Comment by liggitt** [comment]
re[merge]

**Comment by liggitt** [comment]
re[merge]

**Comment by liggitt** [comment]
[test]

**Pull request merged**
