### PR TITLE
Make edit work with lists again

### PR DESCRIPTION
**Pull request by kargakis**
Help yourselves: https://github.com/openshift/origin/pull/11704/files?w=1

Upstream issue is https://github.com/kubernetes/kubernetes/issues/20519, if it's not fixed until the next rebase, we need to continue carrying the drop commit (will need some changes @soltysh I can help with that). A test is added on our side to prevent future regressions.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389681

@openshift/cli-review

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/11704/files?diff=split&w=1

**Comment by liggitt** [comment]
what was the upstream change to use `Visit` fixing? can we edit a list now?

**Comment by liggitt** [comment]
also, why `<drop>` instead of referencing the upstream PR that fixed it?

**Comment by kargakis** [comment]
> what was the upstream change to use Visit fixing? can we edit a list now?

https://github.com/kubernetes/kubernetes/pull/20918 was fixing this in OCP 1.3, https://github.com/kubernetes/kubernetes/pull/25085 broke it again in OCP 1.4. The present PR fixed the regression (again) but it also adds a test.

> also, why <drop> instead of referencing the upstream PR that fixed it?

This is yet to be fixed upstream and `edit` has diverged quite a bit between Kube and Origin.

**Comment by liggitt** [comment]
comment upstream sounds like removing Visit breaks the recursive function

**Comment by kargakis** [comment]
@stevekuznetsov @smarterclayton shouldn't we run upstream test-cmd in parallel with the upstream unit tests or is that an overkill?

**Comment by soltysh** [comment]
I don't see that being a big overkill, they take ~5mins. The problem is that `hack/make-rules/test-cmd.sh` contains also code responsible for starting all of k8s elements. We'd have to split the code responsible for actual tests and only then run it against openshift.

**Comment by stevekuznetsov** [comment]
Five minutes sounds fine, but maintaining their Bash that they use to run them .... not so much

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10988 [test]

**Comment by kargakis** [comment]
#10988 [test]

**Comment by soltysh** [comment]
Upstream merged, tests green, @mfojtik ship it!

**Comment by mfojtik** [comment]
[merge]

@kargakis can you address @liggitt https://github.com/openshift/origin/pull/11704#issuecomment-257661122 comment?

**Comment by kargakis** [comment]
> @kargakis can you address @liggitt #11704 (comment) comment?

https://github.com/kubernetes/kubernetes/issues/20519#issuecomment-258112716

**Pull request merged**
