### PR TITLE
UPSTREAM: 36541: Remove duplicate describer errs

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/36541

Fixes https://github.com/openshift/origin/issues/11846

The `describe` command iterates through a list of infos received from
the server and aggregates a list of errors while attempting to call each
resource's respective describer. When a resource exists, but does not
have a describer set, such as `Event`, the `describe` command outputs
the same error `error: no description has been implemented for "Event"`
for each info.

```
$ oc describe events
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
no description has been implemented for "Event"
```

@openshift/cli-review

### CODE REVIEW

**Comment by fabianofranz** [comment]
LGTM, needs upstream and maybe a test.

**Comment by juanvallejo** [comment]
@fabianofranz 
> LGTM, needs upstream and maybe a test.

Done!

**Comment by juanvallejo** [comment]
[test]

**Comment by fabianofranz** [comment]
LGTM. [merge] and we'll keep tracking upstream.

**Pull request merged**
