### PR TITLE
rework GitHubWebhookCause/GenericWebhookCause to leverage CommonWebHo…

### PR DESCRIPTION
**Pull request by gabemontero**
…okCause

(possibly) Fixes https://github.com/openshift/origin/issues/13620

Also addresses an issue Ben found with what we recently merged for GitLab and Bitbucket

@bparees @smarterclayton @liggitt PTAL ... thanks

### CODE REVIEW

**Comment by gabemontero** [comment]
Note, Ben and I wrestled off line about adding the protobuf:"bytes,1,opt,name=commonWebHookCause" portion of the annotation to CommonWebHookCause for GitHub and  Generic .... I originally did not add it, but when I ran `make update` and `make update-api` those generators in fact added it.

**Comment by bparees** [comment]
so my understanding is that this change will not affect json/yaml serialization (internal or external) since we've just inlined the same fields that were already in the struct.  Thus it's a compatible change.

The question is whether the fact that it's going to change the protobuf serialization is a problem or not and again my thinking is it's not a problem because we don't store protobuf and external clients don't use protobuf, so we'll can't have two different levels of code talking to each other over protobuf and having a compatibility problem.

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by bparees** [comment]
ok i I talked to @smarterclayton and the conclusion is we cannot make changes like this because it will change the protobuf serialization (he originally thought it would not, but the protobuf serialization actually exposes the embedded field, not just the fields within the embedded struct).

And changing the protobuf serialization is not acceptable because even though it's only used by internal components, we have no guarantee all those internal components are at the same level (e.g. during an upgrade process they could be out of sync).

@liggitt fyi since it sounded like you were making protobuf changes somewhere else.

**Pull request closed without merging**
