### PR TITLE
Protect against nil panic in apply

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/15017
Cherry-picks https://github.com/kubernetes/kubernetes/pull/48481

@liggitt PTAL

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM although weird that helper and clientFunc initialized in two different places with two different clients

**Comment by fabianofranz** [comment]
Ok, I'll [ḿerge] since it's related to a blocker and improve the upstream PR, so when we rebase we get it improved.

**Comment by fabianofranz** [comment]
Actually
[merge][severity: blocker]

**Pull request merged**
