### PR TITLE
Fix 'pods "hello-openshift" cannot be updated' flake

### LINKED ISSUE #4262: test-cmd flake "pods "hello-openshift" cannot be updated: the object has been modified"
```
Error from server: pods "hello-openshift" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in hack/test-cmd.sh:269
  '${test}' exited with status 1
Call stack:
  1: hack/test-cmd.sh:269 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4266/

@liggitt do we have a "flake" tag?

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #4262

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton review

**Comment by liggitt** [comment]
I'm not sure whether we should retry internally in the annotate/label/volume commands or not... having to wrap retry logic written in bash around our command invocations to script them with confidence makes me think we're doing something wrong

**Comment by bparees** [comment]
lgtm [merge]

**Comment by smarterclayton** [comment]
We need to eventually use "patch" in the commands.  I think the answer to
your question is "commands should not fail when status on the server
changes, only when spec changes".  That's either patch, better merge on the
server, etc.  We have the generation in the object on the server, so we
should be using that when clients submit changes to delta diffs.

On Mon, Aug 24, 2015 at 11:51 PM, Jordan Liggitt <notifications@github.com>
wrote:

> I'm not sure whether we should retry internally in the
> annotate/label/volume commands or not... having to wrap retry logic written
> in bash around our command invocations to script them with confidence makes
> me think we're doing something wrong
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4352#issuecomment-134458418>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request merged**
