### PR TITLE
Support reconcile option for registry and router

### PR DESCRIPTION
**Pull request by nak3**
As an OpenShift admin, when we deleted serviceaccounts for registry or
router by accident, it is difficult to fix it as it was automaticaly
added during the creation. Also, when serviceaccounts or
clusterrolebindings name were changed during the update, it happened as
well.

This patch adds reconcile option for oc adm registry and router to
solve the issue.

### CODE REVIEW

**Comment by enj** [comment]
/hold

/assign @smarterclayton @knobunc @bparees @mfojtik 

I believe one or more of you guys own these components so I will defer to you to determine if such a flag makes sense.

**Comment by smarterclayton** [comment]
Why do we need this?

I would expect you to do:

```
oc adm registry --dry-run -o yaml | oc apply -f -
```

We don't need reconcile because apply already does it.

**Comment by bparees** [comment]
I wonder if a better implementation would recreate anything that's missing/skip over things that already exist.

I can see someone needing to recreate just the binding or just the service account in the future, or some other combination of pieces that get deleted.  I wouldn't want to limit this to one specific scenario, if we're going to do it.

**Comment by smarterclayton** [comment]
Piping to create and to replace can also do that.   I think we should not
attempt to do this within these commands, because we already have
reconciliation at a higher level via piping and apply.

**Comment by bparees** [comment]
> Piping to create and to replace can also do that. I think we should not attempt to do this within these commands, because we already have reconciliation at a higher level via piping and apply.

no disagreement here, wasn't aware of the pipe to apply solution.

**Comment by nak3** [comment]
@smarterclayton @bparees 

I am not positive for the piple (`oc adm registry --dry-run -o yaml | oc apply -f -`) solution. This command will reset users' manual changes in their deploymentConfig of router or registry.

**Comment by smarterclayton** [comment]
The whole point of apply is that it does not do that.

On Mar 26, 2018, at 8:34 PM, Kenjiro Nakayama <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> @bparees
<https://github.com/bparees>

I am not positive for the piple (oc adm registry --dry-run -o yaml | oc
apply -f -) solution. This command will reset users' manual changes in
their deploymentConfig of router or registry.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/19095#issuecomment-376356452>,
or mute
the thread

**Comment by nak3** [comment]
I meant that I sent this PR to support reconcile option for `serviceaccounts` and `clusterrolebindings` only. I did not expect reconcile all resources such as deploymentconfig. (I'm sorry, `--reconcile` may sound like reconcile everything.)

I am concerned follwoing scenario.

0. edit deploymentconfig beforehand - e.g `initialDelaySeconds: 10` -> `30`
1. delete serviceaccounts by accident - e.g `$ oc delete sa --all`
2. to fix serviceaccounts, run oc apply - e.g `$ oc adm registry --dry-run -o yaml | oc apply -f `

After this scenario, serviceaccounts will reconcile successfully, but `initialDelaySeconds` will be reset to `10` unexpectedly.

**Comment by nak3** [comment]
> The whole point of apply is that it does not do that.

@smarterclayton Hmm... Below is my test and `initialDelaySeconds` was reset to default. Did I make something wrong?

~~~
$ oc adm registry
--> Creating registry registry ...
    serviceaccount "registry" created
    clusterrolebinding "registry-registry-role" created
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Success

// Modify initialDelaySeconds from default value
$ oc edit dc docker-registry
deploymentconfig "docker-registry" edited

$ oc get dc docker-registry -o yaml |grep init
          initialDelaySeconds: 30

$ oc delete sa registry
serviceaccount "registry" deleted

$ oc adm registry --dry-run -o yaml | oc apply -f -
serviceaccount "registry" created

$ oc get dc docker-registry -o yaml |grep init
      {"apiVersion":"v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"docker-registry":"default"},"name":"docker-registry","namespace":"default"},"spec":{"replicas":1,"selector":{"docker-registry":"default"},"strategy":{"resources":{}},"template":{"metadata":{"creationTimestamp":null,"labels":{"docker-registry":"default"}},"spec":{"containers":[{"env":[{"name":"REGISTRY_HTTP_ADDR","value":":5000"},{"name":"REGISTRY_HTTP_NET","value":"tcp"},{"name":"REGISTRY_HTTP_SECRET","value":"RPuOBoAaiMU0Fc1uFhY3TwCedy3nsg2/brz29af5v1M="},{"name":"REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA","value":"false"}],"image":"openshift/origin-docker-registry:v3.10.0-alpha.0","livenessProbe":{"httpGet":{"path":"/healthz","port":5000},"initialDelaySeconds":10,"timeoutSeconds":5},"name":"registry","ports":[{"containerPort":5000}],"readinessProbe":{"httpGet":{"path":"/healthz","port":5000},"timeoutSeconds":5},"resources":{"requests":{"cpu":"100m","memory":"256Mi"}},"securityContext":{"privileged":false},"volumeMounts":[{"mountPath":"/registry","name":"registry-storage"}]}],"securityContext":{},"serviceAccount":"registry","serviceAccountName":"registry","volumes":[{"emptyDir":{},"name":"registry-storage"}]}},"test":false,"triggers":[{"type":"ConfigChange"}]},"status":{"availableReplicas":0,"latestVersion":0,"observedGeneration":0,"replicas":0,"unavailableReplicas":0,"updatedReplicas":0}}
          initialDelaySeconds: 10
~~~

**Comment by enj** [comment]
I believe you cannot use edit, so the change to `dc docker-registry` must be done via an apply (which is what a script would use).

**Comment by nak3** [comment]
> I believe you cannot use edit, so the change to dc docker-registry must be done via an apply (which is what a script would use).

So, to create registry's or router's `serivceaccounts` or `clusterrolebindings` by `oc apply`, we have to assume that users have never updated their DC by `oc edit`? I think it is possible that my test scenario happens.

**Comment by nak3** [comment]
So, if users modified or removed some parameters, `oc apply` resets the object. Below c) and d) are problematic when reconcile router's/registry's serviceaccounts and clusterrolebindings.

~~~
a)  X + a --> apply (X) --> X + a
b)        --> apply (X) --> X
c)  X - a --> apply (X) --> X
d)  X'    --> apply (X) --> X

X... object, X'... modified object, a... parameter
~~~

If `oc adm registry --dry-run -o yaml | oc apply -f -` should be used for reconcile, one of the solutions could be that changing `--dry-run -o yaml` to output only particular objects when the objects are already deployed.
If so, https://github.com/openshift/origin/pull/19096 should be updated.

**Comment by bparees** [comment]
with the 4.0 move to operators for the registry and router this is all going to change anyway so i am going to close this.
/close

**Pull request closed without merging**
