### PR TITLE
delete non-junit file before junit merge

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov fyi

**Comment by bparees** [comment]
(the right fix for this is https://github.com/openshift/origin/pull/16068 but that is on hold pending @smarterclayton's confirmation that we don't need junit merge for anything else)

**Comment by stevekuznetsov** [comment]
@bparees the 10x simpler solutions is to pass in TEST_REPORT_DIR that is not OUTPUT_DIR or ARTIFACT_DIR but some subdir. Why not do that?

**Comment by bparees** [comment]
> @bparees the 10x simpler solutions is to pass in TEST_REPORT_DIR that is not OUTPUT_DIR or ARTIFACT_DIR but some subdir. Why not do that?

because i don't know what the subdir is supposed to be.  and i'd have to change everywhere it's being set.  and this function is going away.

**Comment by stevekuznetsov** [comment]
TEST_REPORT_DIR is declarative -- you pass it in to set it. But yes, let's just delete the `junitmerge` functionality instead.

/close

**Comment by bparees** [comment]
@stevekuznetsov i need a solution to junit merge today.  since @smarterclayton is blocking the other PR, this is the expedient solution in the meantime.

**Comment by stevekuznetsov** [comment]
>  since @smarterclayton is blocking the other PR

His worry about Gubernator is unfounded. That PR should be unblocked.

**Comment by stevekuznetsov** [comment]
Please set `$TEST_REPORT_DIR` to some subdir of artifacts and `mkdir` it:

```
test/extended/networking.sh:373:    export TEST_REPORT_DIR="${ARTIFACT_DIR}"
test/extended/setup.sh:53:              export TEST_REPORT_DIR="${ARTIFACT_DIR}"
```

**Comment by bparees** [comment]
@stevekuznetsov has convinced me this probably won't work.

**Comment by stevekuznetsov** [comment]
@openshift-ci-robot stop, it's already dead

**Pull request closed without merging**
