### PR TITLE
Move project-related commands to external client

### PR DESCRIPTION
**Pull request by soltysh**
Also fixes https://github.com/openshift/origin/issues/20487.

/assign @juanvallejo

### CODE REVIEW

**Comment by juanvallejo** [comment]
Need to update integration tests

**Comment by soltysh** [comment]
Re-applying labels based on previous review.

**Comment by juanvallejo** [comment]
@soltysh you have a test-cmd failure - apparently `oc projects` is no longer failing when any args are passed to it

**Pull request merged**
