### PR TITLE
UPSTREAM: 46614: Add `auto_unmount` mount option for glusterfs fuse mount

### PR DESCRIPTION
**Pull request by gnufied**
This commit also picked pv annotation set for `auto_unmount` mount option
from upstream commit #45995.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by gnufied** [comment]
[test]

**Comment by gnufied** [comment]
This is a fixed version of https://github.com/openshift/origin/pull/14431 .

cc @rootfs @childsb @jsafrane @humblec

**Comment by gnufied** [comment]
Reruning the test. failure seems to be related to docker registry problems.

**Comment by gnufied** [comment]
[test]

**Comment by jsafrane** [comment]
[test]
flake: #13943

**Comment by jsafrane** [comment]
[merge][severity:blocker]

**Pull request merged**
