### PR TITLE
Customize messenger styling

### PR DESCRIPTION
**Pull request by sg00dwin**
fix bug Bug 1203949 to correct sidebar display in ie
and resized logo to fix ie issue

### CODE REVIEW

**Comment by sg00dwin** [comment]
Screenshot of messenger notifications
notifications

**Comment by sg00dwin** [comment]
@jwforres ready for review/merge

**Comment by sg00dwin** [comment]
@jwforres I updated notifications with icons. see screenshot
and regenerated a new bindata.go so it's ready for merge

**Comment by jwforres** [comment]
@sg00dwin i am guessing the data-icon numbers for warning/error/etc could potentially change if we updated patternfly versions?  Just something to keep in mind if/when we update.

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
@jwforres Is this still in the queue to be merged?

**Comment by jwforres** [comment]
unrelated failure [merge]

**Pull request merged**
