### PR TITLE
TRT-1476: Re-introduce the GCP liveness endpoint test

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/origin#28603

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold 

Until we see the right jobs pass.

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm

We'll also want to make sure ci/prow/e2e-metal-ipi-sdn as I think that was the one failing originally.

**Comment by DennisPeriquet** [comment]
regarding that first commit, this one is probably wrong too:

https://github.com/openshift/origin/blob/02fe966e66ed9817d89f9788821aaef0d644f13f/pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go#L31-L39

`NewRecordAvailabilityOnly` is never called ; `NewAvailabilityInvariant` is called but doesn't suppress junit. 

But we can leave that one alone for now.

**Comment by dgoodwin** [comment]
The issue is not fixed: 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/28608/pull-ci-openshift-origin-master-e2e-metal-ipi-sdn/1760328457264304128/artifacts/e2e-metal-ipi-sdn/baremetalds-e2e-test/artifacts/junit/backend-disruption_20240221-171717.json

Ran gcp-network-liveness and failed the whole way. re-checking logic.

**Comment by dgoodwin** [comment]
Trying again with a method for detecting proxy I found in the code where there's evidence this one DID correctly pick up that we're behind a proxy.

**Comment by DennisPeriquet** [comment]
the two BM ci tests look good. no gcp-network-liveness test in the backend-disruptions.json
I checked two non-BM tests and they do contain gcp-network-liveness.

**Pull request merged**
