### PR TITLE
add nodejs 4 imagestream and bump templates to use latest imagestreams

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@dinhxuanvu ptal

**Comment by bparees** [comment]
[test]

**Comment by dinhxuanvu** [comment]
LGTM

**Comment by bparees** [comment]
[testextended][extended:core(openshift sample application repositories)]

**Comment by bparees** [comment]
https://github.com/openshift/origin/issues/9825
[merge]

**Comment by bparees** [comment]
something is badly broken in deployments but it's not caused by this near as i can tell.
[merge]

**Pull request merged**
