### PR TITLE
make oc status build output consistent with deployments

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/4193

```
[deads@deads-dev-01 origin]$ oc status
In project foo

service/ruby-hello-world - 172.30.120.49:8080
  dc/ruby-hello-world deploys istag/ruby-hello-world:latest <-
    docker build of https://github.com/openshift/ruby-hello-world through bc/ruby-hello-world 
      #1 build new for 5 minutes (can't push to image)
    #1 deployment waiting on image or update

Warnings:
  bc/ruby-hello-world is pushing to imagestreamtag/ruby-hello-world:latest that is using is/ruby-hello-world, but the administrator has not configured the integrated Docker registry.  (oadm registry)

To see more, use 'oc describe <resource>/<name>'.
You can use 'oc get all' to see a list of other objects.
```

@fabianofranz ptal

### CODE REVIEW

**Comment by fabianofranz** [comment]
> The problem is exacerbated by the fact that build commands operate on build names (not displayed for the ultimate in frustration)

Doesn't address this, correct? Any chance this could be something like

```
#1 build (build/ruby-sample-build-1) new for 5 minutes (can't push to image)
```

**Comment by deads2k** [comment]
> Doesn't address this, correct? Any chance this could be something like

I'd like tackle that problem by fixing the build-logs to work like we're making deployment logs: accept a bc/name and an optional build number.  I don't think we should get into the habit of making builds named entities that you deal with.

**Comment by fabianofranz** [comment]
@deads2k I was actually thinking about `oc describe`, but your argument makes sense. Other than that LGTM.

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
ui re[merge]

**Comment by liggitt** [comment]
Um, merged?

**Comment by liggitt** [comment]
Also, chrome is now active. Hopefully "browser died" flakes will die

**Pull request merged**
