### PR TITLE
UPSTREAM: 78991: log stale cache Info not Warning Bug 1573460

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Comment by jottofar** [comment]
This is corrected PR against origin to replace https://github.com/openshift/ose/pull/1527 which was incorrectly put against ose.

**Comment by jottofar** [comment]
/assign @mfojtik
Can you help me on this one too please. Thanks.

**Comment by soltysh** [comment]
/title Bug 1573460 - UPSTREAM: 78991: log stale cache Info not Warning

**Pull request merged**
