### PR TITLE
respect system:masters like upstream

### PR DESCRIPTION
**Pull request by deads2k**
Prior to the rebase, I put in a hack to make post-starthooks work.  Now we have the privileged authorizer available.  This wires it together and removes the hack.

[test]

### CODE REVIEW

**Comment by deads2k** [comment]
@ncdc

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
yum flake [test]

**Comment by deads2k** [comment]
"Stage PROVISION TEST CLUSTER failed."  Not sure what do about that.

re[merge]

**Pull request merged**
