### PR TITLE
Bug 1718541: Fix egress monitoring for some rare corner cases [4.1]

### PR DESCRIPTION
**Pull request by danwinship**
Backport of #23089

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
i see that this change has merged into 3.11, but its not clear it has actually been verified there.
the change in master has not been verified according to the bz.
i would prefer to hold this change from the 4.1.z support stream until it has actually been verified in master or i can confirm it was actually verified in 3.11.

**Comment by danwinship** [comment]
I am not sure why the master bug is not yet qe-verified. However, the code hasn't changed at all since 3.11. The 3.11 bug is definitely verified. Note that the patch that was committed to 3.11 came from the customer and had already been confirmed to fix the bug by them before we ever saw it.

That said, the customer doesn't care about 4.x yet and no one else needs the fix so it doesn't really matter much if this doesn't make 4.1.2.

**Comment by eparis** [comment]
Still not VERIFIED in master, but since it was in 3.11 I'm going to allow it. Next time, Dan, bother them in #forum-art to get the master BZ ON_QA sooner.

**Pull request merged**
