### PR TITLE
add db name to the provided secret

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1479660

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal

**Comment by jim-minter** [comment]
Think it's advisable to change
```
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
```
to
```
                  {
                    "name": "MYSQL_DATABASE",
                    "valueFrom": {
                      "secretKeyRef" : {
                        "name" : "${DATABASE_SERVICE_NAME}",
                        "key" : "database-name"
                      }
                    }
                  }
```
(or whatever the equivalents are) across the board otherwise we'll tie ourselves in knots.

**Comment by bparees** [comment]
@jim-minter updated

**Comment by bparees** [comment]
failing image_eco test is unrelated. proceeding w/ merge.

**Pull request merged**
