### PR TITLE
improving probe defaults in the NodeJS+MongoDB example #19379

### PR DESCRIPTION
**Pull request by ryanj**
Allow for user customization of the SOURCE_REPOSITORY_URL input (without breaking the existing example)

### CODE REVIEW

**Comment by ryanj** [comment]
/assign @mfojtik

cc: @bparees

**Comment by bparees** [comment]
/unassign @mfojtik 
/assign

@ryanj this file lives upstream here now: https://github.com/sclorg/nodejs-ex/blob/master/openshift/templates/nodejs-mongodb.json so it needs to be changed there and it will work its way down to origin.

that said, what is really needed is a health check endpoint that does not touch the pagecount.

**Comment by bparees** [comment]
(we switched this to /pagecount because we didn't want the pagecount to increment due to probe accesses)

**Comment by bparees** [comment]
So I do not think we want to make this change in any case.

**Comment by bparees** [comment]
(also not clear what your PR summary comment is referring to?)

**Comment by bparees** [comment]
we've updated the nodejs templates upstream and i'm pulling them (along w/ other changes) into origin here: 
https://github.com/openshift/origin/pull/19653

**Pull request closed without merging**
