### PR TITLE
Don't use version name in external clientsets

### PR DESCRIPTION
**Pull request by ncdc**
@mfojtik @soltysh @pweil- @smarterclayton @deads2k @liggitt @sttts @pmorie

### CODE REVIEW

**Comment by ncdc** [comment]
If you don't like e.g. pkg/user/clientset/clientset, we could switch to pkg/user/clientset_generated/{internalclientset, clientset}.

**Comment by deads2k** [comment]
@ncdc `pkg/user/generated/{internalclientset, clientset, listers, informers}`?

**Comment by ncdc** [comment]
Yeah

**Comment by smarterclayton** [comment]
I like that as well.

**Comment by ncdc** [comment]
I'll get to work on this. I may put everything in 1 pull, as the informers won't compile without proper listers, etc.

**Comment by ncdc** [comment]
Replaced by #13982

**Pull request closed without merging**
