### PR TITLE
The first letter should be small in error of token.go

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: YuPengZTE yu.peng36@zte.com.cn

### CODE REVIEW

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by YuPengZTE** [comment]
@smarterclayton PTAL, thanks.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Flake:

```
I1118 13:02:05.109546    6126 router_http_server.go:208] Stopping listener at 172.18.15.140:8080
I1118 13:02:05.109578    6126 router_http_server.go:208] Stopping listener at 172.18.15.140:8888
I1118 13:02:05.109586    6126 router_http_server.go:208] Stopping listener at 172.18.15.140:8889
I1118 13:02:05.109594    6126 router_http_server.go:208] Stopping listener at 172.18.15.140:8443
--- FAIL: TestRouter (7.65s)
	router_test.go:330: TC non-secure: url 0.0.0.0 alias www.example-unsecure.com protocol http
	router_test.go:330: TC non-secure-path: url 0.0.0.0/test alias www.example-unsecure.com protocol http
	router_test.go:330: TC preferred-port: url 0.0.0.0 alias www.example-unsecure.com protocol http
	router_test.go:330: TC edge termination: url 0.0.0.0 alias www.example.com protocol https
	router_test.go:330: TC edge termination path: url 0.0.0.0/test alias www.example.com protocol https
	router_test.go:330: TC reencrypt: url 0.0.0.0 alias www.example.com protocol https
	router_test.go:330: TC reencrypt-destcacert: url 0.0.0.0 alias www.example.com protocol https
	router_test.go:330: TC reencrypt path: url 0.0.0.0/test alias www.example.com protocol https
	router_test.go:330: TC passthrough termination: url 0.0.0.0 alias www.example-passthrough.com protocol https
	router_test.go:332: TC passthrough termination failed: Get https://0.0.0.0: dial tcp 0.0.0.0:443: getsockopt: connection reset by peer
	router_test.go:330: TC websocket unsecure: url 0.0.0.0 alias www.example.com protocol ws
	router_test.go:330: TC ws edge termination: url 0.0.0.0 alias www.example.com protocol wss
	router_test.go:330: TC ws passthrough termination: url 0.0.0.0 alias www.example.com protocol was
FAIL
```

@ramr @marun known?

[merge]

**Comment by smarterclayton** [comment]
That's weird ^ @stevekuznetsov is the bot angry?

**Comment by marun** [comment]
Not known to me.  Where'd the link to the failing job go?

**Comment by php-coder** [comment]
@smarterclayton Could you try to merge it 4th time? :)

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
