### PR TITLE
Bug 1748150: Modify scheduler preemption tests (fixup #23645)

### PR DESCRIPTION
**Pull request by damemi**
This fixes a bug introduced in https://github.com/openshift/origin/pull/23645 by initializing the pod array with a length of 0 and a capacity of 4, due to the fact that some nodes may be unschedulable and thus we can't assume that `len(pods)` will always have 4 pods

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
it looks like there's a another problem, in line 336 of this file, see:
```
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduling.glob..func4.5()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:336 +0x15f2
```

**Comment by soltysh** [comment]
@damemi stupid me, when you create a slice like this `make([]*v1.Pod, 0, numPods)` you're actually creating an empty slice with given capacity, this means you need to use `append` to add pods into it.

**Comment by damemi** [comment]
@soltysh good catch, could you /lgtm this again?

**Pull request merged**
