### PR TITLE
fix casting errors in case of obj nil

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by liggitt** [comment]
this shouldn't be needed... nil can be cast to objects without errors... are you seeing problems, or is this preventative?

**Comment by liggitt** [comment]
hmm, maybe I was thinking of nil interface pointers... see http://play.golang.org/p/YDwOziIBiF

**Comment by liggitt** [comment]
though if we're not hitting the cast error, I'm not sure I care about fixing the fake client at this point

**Comment by kargakis** [comment]
The commit name needs to be `UPSTREAM: <carry>: fix casting errors in case of obj nil`

And @liggitt is mad about UPSTREAM commits because @liggitt is the next rebaser:)

**Comment by jkhelil** [comment]
I saw the casting error at runtime when getting the restricted scc for exemple without the test
typically the error is 
I0305 14:25:15.207143    5003 testscc.go:151] KClient in updateSecurityContextConstraint: &{{{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} [] [%!s(*client.ObjectPool=&{map[] 0xc820100830})] [] []}
--- FAIL: TestHttpCreate (0.00s)
panic: interface conversion: runtime.Object is nil, not *api.SecurityContextConstraints [recovered]
	panic: interface conversion: runtime.Object is nil, not *api.SecurityContextConstraints

If you see the other fake client, they all have the test, fake_services.go for exemple

**Comment by liggitt** [comment]
Ah, ok. Fix the commit title to start with `UPSTREAM: <carry>: ...`, then LGTM

**Comment by jkhelil** [comment]
Commit message amended with UPSTREAM: <carry>: fix casting errors in case of obj nil

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
