### PR TITLE
apps: do not inject oversized env vars into deployer pod

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535375

@deads2k @smarterclayton this will allow injecting reasonable sized vars into deployer, we can start deprecation process for `OPENSHIFT_CA_DATA` in 3.10?

### CODE REVIEW

**Comment by soltysh** [comment]
> but please create an issue for us to delete this hack in 3.10

I'd suggest fixing upstream validation right away so that we pick it up with the 1.10 rebase.

**Comment by mfojtik** [comment]
> I'd suggest fixing upstream validation right away so that we pick it up with the 1.10 rebase.

This might be controversial upstream as you can use the vars not just for injection but also for downward api and I guess the limitation also apply differently for various container runtimes.

I will start the issue, but I don't have hopes high this will make it for 1.10

**Comment by tnozicka** [comment]
yeah, we talked this on IRC. not easy to fix in general, that's why this hotfix. the limits differ by system, but in general there are other system calls that will allow you to avoid this limitation. So it 'll bounce back upstream between validation and fixing runtime I guess.

**Comment by tnozicka** [comment]
and as @mfojtik says downward API can't be really validated in admission as that get's injected and calculated when kubelet runs it. Other issue might be that since it varies by kernel it's really a runtime property which can differ across nodes in cluster.

It'll be tricky :)

**Comment by mfojtik** [comment]
Also note this is not intended to fix the env var size problem, just unblock running deployer pod when you have these env vars populated with a lot of data (CA bundles). Eventually we want to remove that env vars, but making sure deployer runs even of you try to break it hard seems reasonable to me.

**Pull request merged**
