### PR TITLE
Note that new-app --env flag doesn't apply to templates

### LINKED ISSUE #9508: Environment variables passed to oc new-app are ignored by template
`oc new-app` has a flag `--env` that is documented as:

```
  -e, --env=[]: Specify key value pairs of environment variables to set into each container.
```

And one of the multiple uses of `new-app` is to instantiate a template with `-f`:

```
  -f, --file=[]: Path to a template file to use for the app.
```

One could then assume that both options would work together:

```
oc new-app -f template.json --env FOO=BAR
```

However the environment variables are effectively ignored.

##### Version

```
$ oc version
oc v1.3.0-alpha.1-379-g662753c-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
1. `oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json -e NEWAPP=ok`
2. `oc env dc/frontend --list`

##### Current Result

```
$ oc env dc/frontend --list
# deploymentconfigs frontend, container ruby-helloworld
ADMIN_USERNAME=admin67Q
ADMIN_PASSWORD=DjEGRibg
MYSQL_USER=userBFI
MYSQL_PASSWORD=KIiNJnft
MYSQL_DATABASE=root
```

##### Expected Result

Should include the NEWAPP=ok variable, or it should be documented that both `-f` and `-e` don't work together, or a warning/error message.

```
$ oc env dc/frontend --list
# deploymentconfigs frontend, container ruby-helloworld
ADMIN_USERNAME=admin67Q
ADMIN_PASSWORD=DjEGRibg
MYSQL_USER=userBFI
MYSQL_PASSWORD=KIiNJnft
MYSQL_DATABASE=root
NEWAPP=ok
```

##### Additional Information

Pointing `new-app` to a Git repository and setting envs work as expected:

```
$ oc new-app https://github.com/openshift/ruby-hello-world -e NEWAPP=ok
--> Found Docker image 09345a0 (41 hours old) from Docker Hub for "centos/ruby-22-centos7"
...
--> Creating resources with label app=ruby-hello-world ...
    imagestream "ruby-22-centos7" created
    imagestream "ruby-hello-world" created
    buildconfig "ruby-hello-world" created
    deploymentconfig "ruby-hello-world" created
    service "ruby-hello-world" created
--> Success
    Build scheduled, use 'oc logs -f bc/ruby-hello-world' to track its progress.
    Run 'oc status' to view your app.
$ oc env dc/ruby-hello-world --list
# deploymentconfigs ruby-hello-world, container ruby-hello-world
NEWAPP=ok
```

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixes #9508.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
[test] @bparees PTAL

**Comment by bparees** [comment]
lgtm, thanks @rhcarvalho!
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Comment by bparees** [comment]
networking test is disabled.
[merge]

**Comment by bparees** [comment]
@rhcarvalho needs a rebase

**Comment by rhcarvalho** [comment]
Strangely, rebased and there were no conflicts...

**Comment by bparees** [comment]
might have been auto-resolved, that has happened to me.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
(flake https://github.com/openshift/origin/issues/9670 opened)

**Comment by bparees** [comment]
delightful.. a new flake.
`ERROR: gave up waiting for https://127.0.0.1:38443/healthz`

[merge]

**Pull request merged**
