### PR TITLE
Updates template and image stream metadata

### PR DESCRIPTION
**Pull request by luciddreamz**
Adds display name, service grouping, post-deployment message, and
updated descriptions for all templates and image streams

### CODE REVIEW

**Comment by luciddreamz** [comment]
@bparees Please review and merge

**Comment by bparees** [comment]
needs hack/update-generated-bootstrap.sh, otherwise lgtm

**Comment by luciddreamz** [comment]
@bparees Updated

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11560
[merge]

**Pull request merged**
