### PR TITLE
Add error clause to service/project.js

### LINKED ISSUE #5031: Runtime error refreshing pod page when server down
Data service still shows an error message, but we also have a cannot read property of undefined error in the controller (`resp` is undefined). I suspect this happens everywhere we use the new project service.

screen shot 2015-10-09 at 7 39 24 am

/cc @jwforres

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes #5031 by directing user to error page.

@spadgett @jwforres for review

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Borrowed most of this from the old project controller.  The `e.data` could be used for more information if we wanted to pass that to view as well.

**Comment by jwforres** [comment]
LGTM

@openshift/team-project-committers

**Comment by jwforres** [comment]
wait a sec, missing bindata.go

**Comment by smarterclayton** [comment]
On Jessica's recognizance this is approved :)

**Comment by benjaminapetersen** [comment]
@jwforres updated, thanks!

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
[test] pleeeease?

**Comment by jwforres** [comment]
[test]

**Pull request merged**
