### PR TITLE
create template file for image repos

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton i think is the image repo list you wanted me to create...  not sure exactly where you wanted it placed or what sort of doc you want around it though.

**Comment by bparees** [comment]
(also this file is setup to pull from dockerhub, not the internal docker-registry.  not sure which you wanted but this is more usable out of the box)

**Comment by smarterclayton** [comment]
This way is better for now

**Comment by smarterclayton** [comment]
LGTM - we should be able to `osc create -f <url_to_this>` and get it booted into that namespace.  Can you add this to hack/test-cmd.sh during run (to ensure it validates) and to test-end-to-end and verify that it gets a status url?

**Comment by bparees** [comment]
@smarterclayton added to test-cmd, which includes validation that Status gets populated, is that sufficient or is there still something you want to see in e2e?

**Comment by smarterclayton** [comment]
It's fine for now.  e2e I think we should maybe get to the point where we can do new-app off it (once new-app works).

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
