### PR TITLE
add debug statements for test-go

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k FYI
@smarterclayton PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is this for me to use on my pr that is failing?

**Comment by stevekuznetsov** [comment]
And for David as well, if I'd like it in master so we have more information when we see it in Jenkins. David's failures seem intermittent.

**Comment by smarterclayton** [comment]
[merge]

**Comment by deads2k** [comment]
I'm betting its because the scanner or junit summary or something isn't properly handling when a unit test fails to compile

**Comment by stevekuznetsov** [comment]
If the scanner failed we wouldn't see XML output and without fully formed XML we wouldn't see the summary as the summarizer reads in the file at once and creates structs immediately instead of streaming it ... but I like the idea.

**Comment by stevekuznetsov** [comment]
@deads2k can you please use `reflog` to push a branch on your fork where the Jenkins job failed? I'll use that to try to replicate this.

**Pull request merged**
