### PR TITLE
Don't trigger a build if the namespaces differ

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
@bparees @smarterclayton PTAL

**Comment by ncdc** [comment]
[test]

**Comment by bparees** [comment]
is repo.Namespace always populated?

**Comment by ncdc** [comment]
It comes from etcd. Shouldn't it be?

**Comment by bparees** [comment]
i don't know enough about the k8s/etcd interface to know.  i wouldn't have guessed that.

**Comment by smarterclayton** [comment]
The namespace of an existing object is always set.

**Comment by ncdc** [comment]
Now complete with shiny unit test!

**Comment by ncdc** [comment]
Anyone care to m-e-r-g-e? :smile:

**Comment by bparees** [comment]
lgtm. [merge]

**Pull request merged**
