### PR TITLE
Add VARS ROUTER_SERVICE_HTTP(S)_IP

### PR DESCRIPTION
**Pull request by git001**
To be able to run HAProxy on a multi-homed machine you can add the IP to which HAProxy should bind.
Doc for the bind parameter is at http://cbonte.github.io/haproxy-dconv/1.5/configuration.html#4-bind

### CODE REVIEW

**Comment by ramr** [comment]
@git001  by default it does bind to all the IP addresses on the node. And you can add iptables rules if you don't want to not accept connections on other IPs - e.g. 80 on one of them and 443 on the other. But that said ...
 
Any reason you want to restrict that to just one IP? 
Am okay with doing that but this change assumes you'd _only_ want to use one of those IP addresses. Maybe operating off a list may be better - a list of size 1 is your use case/fix.

And just for completeness, another alternative if you have a need for just a single IP,  could be to use a custom template. See: https://docs.openshift.com/container-platform/3.3/install_config/router/customized_haproxy_router.html

**Comment by git001** [comment]
@ramr This is useful when you run the router on a multi homed node you need to bind haproxy on a dedicated ip/interface.

It would be nice that openshift support this out of the box.

**Comment by ramr** [comment]
@git001  fair enough. If you could do it for a list of addresses, then this works. 

Something like:
```
  {{ with $values := split (env "ROUTER_SERVICE_HTTP_IP_ADDRESSES" "")  "," }}
    {{ range $idx, $ipaddr := $values }}
        bind {{ $ipaddr }}:{{env "ROUTER_SERVICE_HTTP_PORT" "80"}}
    {{ end }}{{/* end range IP addresses. */}}
  {{ else }}
    bind :{{env "ROUTER_SERVICE_HTTP_PORT" "80"}}
  {{ end }}
```
and repeat for 443 (public_ssl).  You will need to add a helper method named `split` to `pkg/router/template/plugin.go` - same as the `env` + `matchPattern`. Just alias it to `strings.Split`.  Thx

**Comment by oprudkyi** [comment]
just a note, it seems 'oc cluster up' validates ports as well (```-- Checking for available ports```), so , if your unlisted interface/IP has port 80 used by some other process - it will fail

**Pull request closed without merging**
