### PR TITLE
UPSTREAM: 13317: Recover panics in finishRequest goroutine

### LINKED ISSUE #4374: Can kill OpenShift process with go panic by invalid json file
Env
---
~~~
# openshift version
openshift v1.0.5-27-g2cc96dc
kubernetes v1.1.0-alpha.0-1605-g44c91b1

# go version
go version go1.4.2 linux/amd64
~~~

**NOTE:** I couldn't reproduce this issue with OSE v3.0.1.0 due to another error.

Issue:
---
- We can kill OpenShift process by sending request with invalid json file.
- Please see following steps.

Reproduce steps
---

step-1. Start openshift origin with standalone mode, and create route and docker-registry. (Followed with [here](https://github.com/nak3/openshift-local-setup))

step-2. Send invalid json file by my [origin-killer.json](https://gist.githubusercontent.com/nak3/23de3850fd3abf5ed038/raw/eba398a3e778459ca21ff8f60371e708566f7950/origin-killer.json
)
~~~
[root@localhost ~]# oc create -f https://gist.githubusercontent.com/nak3/23de3850fd3abf5ed038/raw/eba398a3e778459ca21ff8f60371e708566f7950/origin-killer.json
imagestream "sti-python" created
Unable to connect to the server: EOF
The connection to the server 192.168.122.27:8443 was refused - did you specify the right host or port?
The connection to the server 192.168.122.27:8443 was refused - did you specify the right host or port?
~~~

step-3. You can see go panic and stop the OpenShift process

The log is here: https://kenjiro.fedorapeople.org/misc/logs/origin.log (Too long, please check from the bottom.)

### PR DESCRIPTION
**Pull request by liggitt**
Upstream PR: https://github.com/kubernetes/kubernetes/pull/13317

Fixes #4374

### CODE REVIEW

**Comment by liggitt** [comment]
Catches, logs and propagates panic in `finishRequest`. Before the bug causing the panic was fixed in this PR, submitting the fatal JSON resulted in this being logged, but not killing the server:

```
E0828 13:23:01.731651   25159 util.go:72] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:66
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:54
    /home/jliggitt/.go142/src/runtime/asm_amd64.s:402
    /home/jliggitt/.go142/src/runtime/panic.go:387
    /home/jliggitt/.go142/src/runtime/panic.go:42
    /home/jliggitt/.go142/src/runtime/sigpanic_unix.go:26
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/util/util.go:37
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/api/validation/validation.go:67
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfig/strategy.go:51
    <autogenerated>:32
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/rest/create.go:66
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:205
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:358
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:323
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:630
    /home/jliggitt/.go142/src/runtime/asm_amd64.s:2232
E0828 13:23:01.731921   25159 master.go:430] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /home/jliggitt/.go142/src/runtime/asm_amd64.s:401
    /home/jliggitt/.go142/src/runtime/panic.go:387
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:646
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:328
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:220
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:59
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:222
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:91
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/.go142/src/net/http/server.go:1541
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:240
    <autogenerated>:23
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:89
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/auth.go:618
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:173
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:139
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:56
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/.go142/src/net/http/server.go:1541
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:240
    <autogenerated>:23
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:338
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:191
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:91
    /home/jliggitt/.go142/src/net/http/server.go:1265
    /home/jliggitt/.go142/src/net/http/server.go:1703
    /home/jliggitt/.go142/src/net/http/server.go:1204
    /home/jliggitt/.go142/src/runtime/asm_amd64.s:2232
```

**Comment by liggitt** [comment]
After fixing the nil check in util.go:
```
$ oc create -f panic.json 
The BuildConfig "sti-python" is invalid.
spec.strategy.stiStrategy: required value
```

**Comment by liggitt** [comment]
@smarterclayton got LGTM upstream, review?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
@brenton we probably need to backport this

**Comment by nak3** [comment]
@liggitt "return nil" is the best that we can handle the invalid JSON? 

https://github.com/openshift/origin/blob/f8337f75bbf983e35e812ba99f50ba1cc3f6c0e2/pkg/build/util/util.go#L38
https://github.com/openshift/origin/blob/f8337f75bbf983e35e812ba99f50ba1cc3f6c0e2/pkg/build/util/util.go#L43
https://github.com/openshift/origin/blob/f8337f75bbf983e35e812ba99f50ba1cc3f6c0e2/pkg/build/util/util.go#L48

I can easily create the request to make panic. (Of course, it will not kill the server in this server, though)

eg. [kill.yaml](https://gist.githubusercontent.com/nak3/6387633d1e833929cc2d/raw/3ac14d7f4a9569fba7c3ee01daa8ba3d823712e5/killer.yaml)
~~~
oc create -f https://gist.githubusercontent.com/nak3/6387633d1e833929cc2d/raw/3ac14d7f4a9569fba7c3ee01daa8ba3d823712e5/killer.yaml
~~~

- origin.log
~~~
I0901 19:44:25.260717    7279 config_controller.go:38] Running build for BuildConfig default/hello-c
I0901 19:44:25.269988    7279 generator.go:167] Generating Build from BuildConfig: default/hello-c, LastVersion: 0
E0901 19:44:25.271091    7279 util.go:72] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:66
/tmp/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:54
/usr/lib/golang/src/runtime/asm_amd64.s:402
/usr/lib/golang/src/runtime/panic.go:387
/usr/lib/golang/src/runtime/panic.go:42
/usr/lib/golang/src/runtime/sigpanic_unix.go:26
/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/generator/generator.go:237
/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/generator/generator.go:177
/tmp/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/instantiate/generator/generator.go:35
~~~

**Comment by pweil-** [comment]
I'm for putting in the nil checks and new handling code there but should we also prevent this from even getting that var by moving the spec validation for the build config up in the method and returning?

https://github.com/pweil-/origin/blob/3dbf26a785e613ed5b3ec6f30953204b6c296ca0/pkg/build/api/validation/validation.go#L77-77

**Comment by liggitt** [comment]
they're both spec validation, and we want to include all errors... all parts of the validate should be guarded appropriately, will open another pull to add more nil checks

**Pull request merged**
