### PR TITLE
Log failures when retrying

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
LGTM

**Comment by jwforres** [comment]
although a "retrying" message would be nice

**Comment by jwforres** [comment]
meh, you'd have to check if tries = 0 after the tries -- to know if it was going to retry, not worth it right now

**Comment by jwforres** [comment]
Well it conveniently failed and proved your change did what you intended :-)

But its our first definite triple failure.

**Pull request closed without merging**
