### PR TITLE
extended: Allow to focus on particular tests

### PR DESCRIPTION
**Pull request by miminar**
Focus usually involves string with spaces such as:

    ./test/extended/core.sh --ginkgo.focus='quota admission' --ginkgo.failFast

### CODE REVIEW

**Comment by miminar** [comment]
[test][extended:core(image should have proper)]

**Comment by stevekuznetsov** [comment]
Since `test::extended::focus` consumes args using `$@` it's not necessary to pass everything in as one argument, and perhaps we actually don't want to. If we pass in using `$*` we will break on spaces, causing separate args to `test::extended::focus`. Inside `test::extended::focus` I would have actually expected line 14 to *require* separate arguments for all of the args passed in, whereas now it uses `"$@"` and passes all arguments as one. Maybe `ginkgo` does word splitting itself? @Miciah thoughts?

**Comment by miminar** [comment]
Closing this in favor of #8438.

**Pull request closed without merging**
