### PR TITLE
Add instructions to ignore vboxnet interfaces on the host.

### LINKED ISSUE #711: Unable to connection from a 'master' to minions when using OPENSHIFT_DEV_CLUSTER
How to reproduce:

1. export OPENSHIFT_DEV_CLUSTER=1
2. vagrant up
3. vagrant ssh master
4. ping openshift-minion-1
....
4 packets transmitted, 0 received, 100% packet loss, time 3000ms

This is the same for openshift-minion-2. This seems to be random (after several vagrant halt/up, it sometimes works...)

We tracked it down into host NetworkManager, where the NetworkManager sees the VirtualBox devices and tries to manage them. If I add following into /etc/NetworkManager/NetworkManager.conf:

```
[keyfile]
unmanaged-devices=mac:0a:00:27:00:00:00;mac:0a:00:27:00:00:01;mac:0a:00:27:00:00:02;mac:0a:00:27:00:00:03;mac:0a:00:27:00:00:04
```

where the MAC addresses are addresses of vboxnet# interfaces and I systemctl restart NetworkManager then the problem seems to go away and I can connect between minions and also from master to minions.

After running `nmcli d` I see all vboxnet# devices as 'unmanaged'.

We should either update our Vagrant instructions to include this or fix the VirtualBox RPM to automatically update/install the config file with unmanaged-devices list.

@rajatchopra @mrunalp ^^

### PR DESCRIPTION
**Pull request by mrunalp**
Update CONTRIBUTING.adoc

Closes #711

### CODE REVIEW

**Comment by mfojtik** [comment]
lgtm

fyi this is now being fixed in NM.

**Comment by mrunalp** [comment]
@mfojtik Thanks for the review. We can take this out once it is fixed in NM.

**Comment by mrunalp** [comment]
[merge]

**Comment by mrunalp** [comment]
[merge]

**Pull request merged**
