### PR TITLE
Bump fontawesome to 4.6.1

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Approved [merge]

**Comment by jwforres** [comment]
@spadgett bit us again, gotta figure out how to stop this

**Comment by jwforres** [comment]
Flake [merge]

**Comment by liggitt** [comment]
test-assets.sh passed in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/13/consoleFull

**Comment by smarterclayton** [comment]
Just failed again

**Comment by liggitt** [comment]
merging to unblock the queue. @spadgett is fixing the dependency declaration to prevent future breaks.

**Pull request merged**
