### PR TITLE
Bug 1907373: Tests for kube rebase to 1.20.0

### PR DESCRIPTION
**Pull request by soltysh**
This is #25764 with fixed deps.
/assign @tnozicka @marun

### CODE REVIEW

**Comment by marun** [comment]
/lgtm

Let the retesting commence!

**Comment by wking** [comment]
Required [e2e-aws-serial][1]:

```
could not run steps: step e2e-aws-serial failed: "e2e-aws-serial" test steps failed: "e2e-aws-serial" pod "e2e-aws-serial-openshift-e2e-test" exceeded the configured timeout activeDeadlineSeconds=7200: the pod ci-op-40m9g1pk/e2e-aws-serial-openshift-e2e-test failed after 2h0m1s (failed containers: ): DeadlineExceeded Pod was active on the node longer than the specified deadline
```

But looks like [no `test` container logs from that step][2].  I'll check with the test-platform folks to see if they can get us those in the future...

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25765/pull-ci-openshift-origin-master-e2e-aws-serial/1338583938079133696#1:build-log.txt%3A157
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/25765/pull-ci-openshift-origin-master-e2e-aws-serial/1338583938079133696/artifacts/e2e-aws-serial/openshift-e2e-test/container-logs/

**Comment by soltysh** [comment]
Closing in favor of https://github.com/openshift/origin/pull/25764
/close

**Pull request closed without merging**
