### PR TITLE
Remove unused function in CatalogImagesController

### LINKED ISSUE #2225: CatalogImagesController.templatesByTag is never called
The `templatesByTag` function in `CatalogImagesController` never appears to be used.

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #2225

### CODE REVIEW

**Comment by spadgett** [comment]
No bindata changes when building assets.

**Comment by liggitt** [comment]
[merge]

**Comment by spadgett** [comment]
```
--- FAIL: TestImage (0.69s)
	client_test.go:110: tag "latest" has not been set on repository "openshift/origin"
FAIL
coverage: 78.3% of statements
FAIL	github.com/openshift/origin/pkg/dockerregistry	2.897s
```

**Comment by liggitt** [comment]
@ncdc ^ that a normal thing for dockerhub to do?

**Comment by ncdc** [comment]
@liggitt no, I haven't seen that particular failure before. I've seen tests fail in this package when the Hub is having a brief outage, but not like this.

**Comment by liggitt** [comment]
```
--- FAIL: TestRunBuild (3.87s)
	newapp_test.go:835: successful ruby app generation: Error mismatch! Expected <nil>, got no image or template matched "openshift/ruby-20-centos7": can't connect to "": error retrieving image https://registry-1.docker.io/v1/images/d5de68d8a25674ccfedfb7415b214f73c0de526d15ab08a5b4d43c1e5e96a1cd/json: server returned 401
W0708 04:33:02.479744   12150 newapp.go:510] Could not find an image match for "mysql". Make sure that a Docker image with that tag is available on the OpenShift node for the build to succeed.
FAIL
```

**Pull request merged**
