### PR TITLE
Updating GITHUB_WEBHOOK_SECRET description

### PR DESCRIPTION
**Pull request by coreydaley**
https://bugzilla.redhat.com/show_bug.cgi?id=1365656

@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
probably needs bindata regen'd?

**Comment by coreydaley** [comment]
updated

**Comment by bparees** [comment]
[merge][severity:lowrisk]

**Comment by bparees** [comment]
[merge][severity:lowrisk]

**Comment by deads2k** [comment]
re[test]

**Pull request merged**
