### PR TITLE
Fix hot deploy test for CakePHP upgrade PR

### PR DESCRIPTION
**Pull request by cuppett**
This test fix is needed after https://github.com/sclorg/cakephp-ex/pull/93 is merged.

### CODE REVIEW

**Comment by cuppett** [comment]
https://github.com/sclorg/cakephp-ex/pull/93 is merged. This should be merged now.

**Comment by bparees** [comment]
@cuppett we're picking this here: https://github.com/openshift/origin/pull/19541 because we need a single PR that will pass the image eco test and get merged.

/close

**Pull request closed without merging**
