### PR TITLE
OCPBUGS-32320: revert: removing static pod skip for crio check

### PR DESCRIPTION
**Pull request by eggfoobar**
Reverting OCPBUGS-31074, the error that caused this was resolved.

### CODE REVIEW

**Comment by eggfoobar** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-gcp-ovn-rt-upgrade

**Comment by eggfoobar** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-gcp-ovn-rt-upgrade

**Comment by eggfoobar** [comment]
/hold
/cc @xueqzhan 

Wait for another payload run to pass

**Comment by xueqzhan** [comment]
/lgtm

Feel free to cancel hold after payload run.

**Comment by eggfoobar** [comment]
/unhold

Same payload jobs that triggered #28662 are succeeding now with that skip removed. Un-holding and merging back the existing logic.

**Pull request merged**
