### PR TITLE
UPSTREAM: 60457: tests: e2e: empty msg from channel other than stdout should be non-fatal

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/60457

fixes https://github.com/openshift/origin/issues/18726

@smarterclayton @liggitt @derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
/approve
/lgtm

@stevekuznetsov @runcom - after this merges, i think we can retry the bump to docker 1.13.

**Comment by sjenning** [comment]
blocked by flake https://github.com/openshift/origin/issues/18762

**Comment by smarterclayton** [comment]
I'm going to manually merge, not conflicting with the queue and this has gone green on others.  I want this pre-branch.

**Pull request merged**
