### PR TITLE
Ensure that StepExecPostCommit is not recorded if no PostCommit exists

### LINKED ISSUE #16119: Build status should not record a PostCommit step if none was specified
Had a build report a stage and step for PostCommit, which was not actually specified.  Build shouldn't include steps that aren't run.

```
  - name: PostCommit
    startTime: 2017-09-03T20:42:07Z
    steps:
    - name: RunPostCommitHook
      startTime: 2017-09-03T20:42:07Z
```

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes #16119

### CODE REVIEW

**Comment by coreydaley** [comment]
@smarterclayton ptal

**Comment by csrwng** [comment]
dockerRun seems like a generic utility function that should have no knowledge about recording a step for postcommit. If only dockerRun can make the determination whether the step can be recorded, then maybe passing a closure to run when successful seems better or if you can make the determination on the calling function, I would do it there.

**Comment by coreydaley** [comment]
@csrwng Updated per your suggestion.

**Comment by coreydaley** [comment]
@bparees This test isn't going to pass unless the new images are being built.

**Comment by bparees** [comment]
@coreydaley new images are being built.  The only env that doesn't build new images is the conformance_gce test, and what's failing isn't a conformance test.

**Comment by bparees** [comment]
@coreydaley one of these failures is due to the build-args issue you fixed in the other PR, so once that PR merges, that test will pass here.

the other failure is, i think, a flake due to a k8s issue.  (no logsnippet value present in the build which likely means it there wasn't a failure log entry present in the build pod)

/retest

(but the build-args test is still going to fail)

**Comment by coreydaley** [comment]
@bparees ptal, all tests passing

**Pull request merged**
