### PR TITLE
Fixes attach broken during the refactor

### PR DESCRIPTION
**Pull request by fabianofranz**
Cherry-picking https://github.com/kubernetes/kubernetes/commit/7f6f85bd7b47db239868bcd868ae3472373a4f05.

PTAL @smarterclayton @liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by fabianofranz** [comment]
re[merge]

**Comment by liggitt** [comment]
test failed, not merge

**Comment by liggitt** [comment]
re[test]

**Pull request merged**
