### PR TITLE
Revert "3.11 - Move binaries into cmd/ where they belong"

### PR DESCRIPTION
**Pull request by pravisankar**
Reverts openshift/origin#19989

openshift/origin#19989 got merged before I added the /hold. I should have tagged /hold before /lgtm :(

### CODE REVIEW

**Comment by pravisankar** [comment]
@smarterclayton sorry for the inconvenience

**Comment by liggitt** [comment]
@smarterclayton this ready?

**Comment by smarterclayton** [comment]
It's a pure revert

/lgtm
/approve

**Pull request merged**
