### PR TITLE
Bug 1845780: [release-4.4] kubelet: block non-forwarded packets from crossing the localhost boundary

### PR DESCRIPTION
**Pull request by joelsmith**
This is a release-4.4 cherry-pick of https://github.com/openshift/origin/pull/25141

### CODE REVIEW

**Comment by joelsmith** [comment]
@bparees This one is ready for cherry-pick-approved review. Thanks!

**Comment by bparees** [comment]
@joelsmith the scheduled patch manager should review this for approval on wednesday

**Pull request merged**
