### PR TITLE
Upgrade to etcd v2.1.2

### PR DESCRIPTION
**Pull request by smarterclayton**
@ncdc @liggitt

Lots of dependency updates, but...

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
didn't dig into godeps too much... etcd init changes look ok... do you know if we have clustered etcd test coverage anywhere? might want to spawn a BZ for QE to hit those test cases

only question is the addition of golang.org/x/crypto/bcrypt... that would be the first crypto library we were vendoring that I'm aware of... don't know if that needs approval or not

**Comment by smarterclayton** [comment]
We don't run clustered from our code - but QE should test clustering, yes.
We already vendor crypto/ssh and a few others.

On Wed, Sep 2, 2015 at 1:37 PM, Jordan Liggitt <notifications@github.com>
wrote:

> didn't dig into godeps too much... etcd init changes look ok... do you
> know if we have clustered etcd test coverage anywhere? might want to spawn
> a BZ for QE to hit those test cases
>
> only question is the addition of golang.org/x/crypto/bcrypt... that would
> be the first crypto library we were vendoring that I'm aware of... don't
> know if that needs approval or not
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4460#issuecomment-137182466>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
I won't be able to review this until tomorrow at the earliest

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
This should remove [gogoprotobuf/proto](https://github.com/openshift/origin/blob/1e58d081b2bf79e45511166fa43bdd5d121cd0fd/Godeps/Godeps.json#L23). Will handle in https://github.com/openshift/origin/issues/4434

**Pull request merged**
