### PR TITLE
OCPBUGS-36672: Shorten stabilization time for etcd profiles test

### PR DESCRIPTION
**Pull request by dusk125**
Shorten stabilization time from 5 minutes to 2 minutes

### CODE REVIEW

**Comment by dusk125** [comment]
@derekhiggins 1 minute didn't work, trying 2

**Comment by dusk125** [comment]
@derekhiggins can I get a lgtm if you're satisfied with the results?

**Comment by derekhiggins** [comment]
/lgtm
looks like it has taken about 16 minutes+ from the runtime

> passed: (4m12s) 2024-07-10T12:22:55 "[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to set the hardware speed to Standard [Timeout:30m][apigroup:machine.openshift.io] [Suite:openshift/conformance/serial]"
> passed: (15m27s) 2024-07-10T12:38:31 "[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to set the hardware speed to Slower [Timeout:30m][apigroup:machine.openshift.io] [Suite:openshift/conformance/serial]"
> passed: (4m12s) 2024-07-10T13:16:51 "[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to set the hardware speed to \"\" [Timeout:30m][apigroup:machine.openshift.io] [Suite:openshift/conformance/serial]"
>

**Pull request merged**
