### PR TITLE
WIP - debug: WaitForABuild

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by gabemontero** [comment]
image-eco tests actually completed successfully in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24604/pull-ci-openshift-origin-master-e2e-gcp-image-ecosystem/103 @adambkaplan but then some post test container activity failed

**Comment by adambkaplan** [comment]
/retest

looks like the image eco tests didn't even run (failed to get lease from boskos)

**Comment by adambkaplan** [comment]
/close

I think we can conclude that changes to ocm didn't impact how builds and image-eco operates

**Pull request closed without merging**
