### PR TITLE
Fix type %s to %d for int type parameter

### PR DESCRIPTION
**Pull request by yu-song**
Fix type %s to %d for int type parameter

### CODE REVIEW

**Comment by pweil-** [comment]
LGTM [merge]

**Comment by yu-song** [comment]
@pweil-  @jcantrill 
Excuse me,  I do not know what I should do now for the PR, can you give me some suggestions?
Thanks very much.

**Comment by pweil-** [comment]
[merge]

**Comment by yu-song** [comment]
@pweil- 
Thank you for advice.

**Comment by pweil-** [comment]
LGTM re[merge]

**Pull request merged**
