### PR TITLE
UPSTREAM: 64675 : Fixes data races for pkg/kubelet/config/file_linux_test.go

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Pick of https://github.com/kubernetes/kubernetes/pull/64675/files

/cc @sjenning @smarterclayton

### CODE REVIEW

**Comment by sjenning** [comment]
that image pruning failure again :-/  even still
/lgtm

**Comment by sjenning** [comment]
/test e2e-gcp-crio
still a massive number of failing tests in e2e-aws so not trying that one again until issues are adressed elsewhere

**Comment by ravisantoshgudimetla** [comment]
/close

Waiting for the rebase to land which includes this change.

**Comment by smarterclayton** [comment]
/hold

@solytsh this is flaking 1/5.  We can wait if it impacts you

**Pull request closed without merging**
