### PR TITLE
Router: factor RouteValidator out of UniqueHost

### PR DESCRIPTION
**Pull request by Miciah**
Currently, the UniqueHost router plugin wrapper performs several functions:

• Filter route and endpoint updates per `--namespace-labels`/`NAMESPACE_LABELS`.

• Ensure that the route has a non-empty host.

• Ensure that a new route does not claim a host held by an existing route.

Additionally, the core router code performs the following function:

• Override the route's host using the template specified with `--subdomain`/`ROUTER_SUBDOMAIN` if the host is blank or if `--force-subdomain`/`ROUTER_OVERRIDE_HOSTNAME` is specified.

This PR defines a new plugin wrapper, RouterValidator, to perform the first, second, and fourth of these functions, leaving UniqueHost to do exactly what its name implies and reducing the amount of ancillary login in the core router code.  This PR also adds some tests for RouteValidator.

These changes were previously included in https://github.com/openshift/origin/pull/9043 but are being introduced independently in this PR while we argue over the remaining changes in https://github.com/openshift/origin/pull/9043.
## 
#### router: Move `RejectionRecorder` to its own file

Move the `RejectionRecorder` interface and default implementation from `unique_host.go` into its own file, `rejection_recorder.go`.
#### router: Factor `RouteValidator` out of `UniqueHost`

Define a new plugin wrapper, `RouteValidator`.  Move existing validation from `UniqueHost` into `RouteValidator`:

• Reject the route if it is not from an allowed namespace.

• Override the hostname using the defined template if it is blank or if the plugin wrapper is configured to override hostnames.

Move `allowedNamespaces` and `hostForRoute` from `UniqueHost` to `RouteValidator`.

Move `RouteSelectionFunc` from `pkg/cmd/infra/router/router.go` to `pkg/router/controller/route_validator.go`, and modify it to take the hostname template and hostname-override flag as parameters instead of taking `RouterSelection` as a receiver and reading the parameters from there.

Call `RouteSelectionFunc` from `NewRouteValidator`, which now sets the `hostForRoute` callback, instead of calling `RouteSelectionFunc` in `NewUniqueHost`'s caller.

Move namespace validation, host validation, and host template expansion from `UniqueHost`'s `HandleEndpoints`, `HandleRoute`, and `HandleNamespace` callbacks to `RouteValidator`'s.

Update callers of `NewUniqueHost` to drop the `hostToRoute` argument if they do not need route validation or to use `NewRouteValidator` to create a `RouteValidator` that wraps a `UniqueHost` if they do need route validation.
#### router: Add tests for `RouteValidator`

Add tests for `RouteValidator`.
## 

openshift-bot, please [test]!

### CODE REVIEW

**Comment by Miciah** [comment]
EC2 provisioning failed.  openshift-bot, please [test] again!

**Comment by Miciah** [comment]
@knobunc, this PR is just the cleanups and tests from #9043; do they look reasonable to merge?

Cc @smarterclayton and @abhgupta.

**Comment by liggitt** [comment]
Post 1.3, right?

**Comment by abhgupta** [comment]
This is aimed at 3.4 - we need to hold off on this PR till after code freeze on 3.3 and when master is open for 3.4

**Comment by Miciah** [comment]
It's been a while, so please [test] [extended:networking] in case of bitrot!

**Comment by Miciah** [comment]
@knobunc, this PR just makes some cleanups and adds a few unit tests.  It came out of some work I did for Online, but we do not need it for Online, so while I would be gratified by a merge, we can drop it if you do not see a benefit.

In case you are curious, the coverage goes from the following:
```
ok    github.com/openshift/origin/pkg/router/controller 1.266s  coverage: 49.1% of statements
```
to the following:
```
ok  github.com/openshift/origin/pkg/router/controller1.323s coverage: 52.1% of statements
```

**Comment by knobunc** [comment]
@Miciah sorry, I missed this in the shuffle.  I definitely want it, but post 1.4 at this point.  Sorry :-(  Please rebase and we'll get it reviewed and in.  Please bug me if you don't get a review soon after 1.4 branches.

**Pull request closed without merging**
