### PR TITLE
IR-471: Updating the test with skipper function

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @flavianmissi

### CODE REVIEW

**Comment by deepsm007** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-gcp-ovn-serial

**Comment by flavianmissi** [comment]
LGTM. The test failures are unrelated right?

**Comment by deepsm007** [comment]
I didn't see the new tests in any of the above serial jobs. (not even in the skip tests)

**Comment by deepsm007** [comment]
local run using cluster bot for serial test looks good and also individual test runs

**Comment by deepsm007** [comment]
/assign @stbenjam 
Any particular job we need to trigger?

**Comment by neisw** [comment]
Seems like we would expect it to run for `periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial` and skip for `periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-techpreview-serial `, sound right?

**Comment by deepsm007** [comment]
> Seems like we would expect it to run for `periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial` and skip for `periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-techpreview-serial `, sound right?

Yes, that is correct. Skip for any other provider if storage is not S3

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-techpreview-serial

**Comment by deepsm007** [comment]
Looks like the test is working 


From GCP
> started: 0/11/62 "[sig-imageregistry][OCPFeatureGate:ChunkSizeMiB][Serial][apigroup:imageregistry.operator.openshift.io] Image Registry Config ChunkSizeMiB should set maximum valid ChunkSizeMiB value [Suite:openshift/conformance/serial]"
> skip [github.com/openshift/origin/test/extended/storage/helpers.go:58]: No S3 storage detected
> Ginkgo exit error 3: exit with code 3
> skipped: (3.8s) 2024-07-24T19:30:26 "[sig-imageregistry][OCPFeatureGate:ChunkSizeMiB][Serial][apigroup:imageregistry.operator.openshift.io] Image Registry Config ChunkSizeMiB should set maximum valid ChunkSizeMiB value [Suite:openshift/conformance/serial]"
>

From AWS
> started: 0/4/62 "[sig-imageregistry][OCPFeatureGate:ChunkSizeMiB][Serial][apigroup:imageregistry.operator.openshift.io] Image Registry Config ChunkSizeMiB should set maximum valid ChunkSizeMiB value [Suite:openshift/conformance/serial]"
> passed: (1.5s) 2024-07-24T18:56:23 "[sig-imageregistry][OCPFeatureGate:ChunkSizeMiB][Serial][apigroup:imageregistry.operator.openshift.io] Image Registry Config ChunkSizeMiB should set maximum valid ChunkSizeMiB value [Suite:openshift/conformance/serial]"
>

**Comment by neisw** [comment]
/override ci/prow/e2e-aws-ovn-edge-zones
/override ci/prow/e2e-aws-ovn-fips
/override ci/prow/e2e-aws-ovn-serial
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-gcp-ovn-builds 
/override ci/prow/e2e-gcp-ovn-upgrade
/override ci/prow/e2e-metal-ipi-ovn-ipv6

overriding jobs that have passed previously

**Pull request merged**
