### PR TITLE
restrict osc loading chain to openshift files

### PR DESCRIPTION
**Pull request by deads2k**
I had been resisting this to avoid changing the chain twice, but getting any further changes into upstream is starting to get slow.

This changes the osc chain to be:
 1. `--config`
 1. `$OPENSHIFTCONFIG`
 1. `./.openshiftconfig`
 1. `~/.config/openshift/.config`

@fabianofranz can you review?

### CODE REVIEW

**Comment by deads2k** [comment]
Basically this just cuts out the kubernetes files to make it easier to describe to users where the values come from.

Code-wise, this is collapses the file modification logic down onto the rules used by `kubectl config` to make it more predicatable.

**Comment by deads2k** [comment]
@brenton You may be interested in this.  You asked about the chain today.

**Comment by deads2k** [comment]
[test]

**Comment by fabianofranz** [comment]
One comment, otherwise LGTM.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
