### PR TITLE
bump(github.com/openshift/source-to-image): 78f4e4fe283bd9619804da9e929c61f655df6d06

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
blocked on https://github.com/openshift/origin/pull/6795

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@mfojtik ptal.

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
