### PR TITLE
[release-3.11] Bug 1772594: Make DNS querying more efficient by querying once per dns name

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Refactor the datastructures to query DNS names more efficiently as
the same DNS name may appear across multiple policies.

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
/retitle  Bug 1772594: Make DNS querying more efficient by querying once per dns name

**Comment by danwinship** [comment]
was this basically a trivial backport or did you have to fix any conflicts?

**Comment by juanluisvaladas** [comment]
A lot of conflicts, I need to review this, at least the verify and the unit are legit failures

**Comment by sdodson** [comment]
@juanluisvaladas Is this still WIP?

**Comment by juanluisvaladas** [comment]
@sdodson I'm waiting to see what happens with the 4.1 https://github.com/openshift/origin/pull/24515 before fixing the issues on this one.

**Comment by sdodson** [comment]
> @sdodson I'm waiting to see what happens with the 4.1 #24515 before fixing the issues on this one.

This doesn't meet the requirements for 4.1 given its current lifecycle, however this is valid for 3.11.

**Comment by juanluisvaladas** [comment]
OK, I have some other stuff to deal with before this, and next week I'll be on PTO, but most certainly I'll have this done by the 27th.

**Comment by juanluisvaladas** [comment]
@knobunc I thnk this will also need lgtm and cherry-pick-approval

**Comment by juanluisvaladas** [comment]
Let's see if I can do this
/lgtm

**Comment by sdodson** [comment]
/hold
Clear this once the tests have been fixed.

**Comment by sdodson** [comment]
/hold cancel
/override ci/prow/e2e-gcp
e2e-gcp job is currently broken but the team that can fix it is unable to work on it right now

**Pull request merged**
