### PR TITLE
oc help output improvements

### PR DESCRIPTION
**Pull request by juanvallejo**
Related bugzilla (pkg/cmd/cli/cmd/wrappers.go): https://bugzilla.redhat.com/show_bug.cgi?id=1415969
Related bugzilla (pkg/cmd/cli/cmd/process.go): https://bugzilla.redhat.com/show_bug.cgi?id=1416936
Related bugzilla (pkg/generate/app/cmd/template.go) and (pkg/cmd/cli/describe/helpers.go) https://bugzilla.redhat.com/show_bug.cgi?id=1370104

cc @openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by fabianofranz** [comment]
LGTM, but needs to update the generated stuff.  ;)

**Comment by fabianofranz** [comment]
[merge]

**Comment by juanvallejo** [comment]
conformance_future flaked on https://github.com/openshift/origin/issues/12960 re[test]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/12960 re[merge]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/12960 re[merge]

**Pull request merged**
