### PR TITLE
Deprecate apply cmd

### PR DESCRIPTION
**Pull request by juanvallejo**
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1332498

#### Why deprecate?
1. Compare the help info of `oc apply -h` VS `oc create -h`

##### Take an example of `oc apply`:
\2. `$ cat svc_test.yaml`

2.1
```
apiVersion: v1
kind: Service
metadata:
  name: svc-test
spec:
  ports:
  - targetPort: 8080
    port: 8080
    name: web1
    protocol: TCP
  selector:
    name: database
```

2.2 `$ oc apply -f svc_test.yaml`

\3. Check oc apply's result
3.1 `$oc get svc svc-test -o yaml`

3.2 From the output, compare the content in kubectl.kubernetes.io/last-applied-configuration and the content of the resource

\4. oc edit resource then check again 
4.1 oc edit svc svc-test # e.g. change targetPort: 8080 to targetPort: 8081
4.2 oc get svc svc-test -o yaml
4.3 From the output, compare the content like step 3.2 again.

##### results:
3.
3.2 What `oc apply` does is just to add one new annotation: kubectl.kubernetes.io/last-applied-configuration, the content of which is just as same as the content of the resource. So, the annotation provides nothing useful at all. It just makes the resource content bulky

4.
4.3 The contents are sync'ed same after any edit, again proving the annotation provides nothing useful at all

What `oc apply` does is just to add one new annotation: kubectl.kubernetes.io/last-applied-configuration, the content of which is just as same as the content of the resource. So, the annotation provides nothing useful at all. It just makes the resource content bulky

### CODE REVIEW

**Comment by smarterclayton** [comment]
We aren't deprecating apply.

**Comment by juanvallejo** [comment]
@smarterclayton Ok, will close bug on BZ.

**Comment by liggitt** [comment]
> Don't ever take a fence down until you know the reason it was put up.”
>
> ― G.K. Chesterton

The intent of `apply` is to take user input and "make it so" on a given object. it is supposed to create the object if needed, or update the object if it already exists. It stores the annotation so that future calls to `apply` can intelligently diff between previously "applied" configurations, and avoid stomping defaulting or changes made by the server. It doesn't work well, but the intent is nice.

**Comment by rkhshan** [comment]
I know this is an old subject but isn't <oc apply> does update your current pod/project ? If you have a template config file that points to a Docker image, Description, Release, etc. and  you changed the application build release and wanted to redeploy the new tagged image with that change, what is better than <oc apply> to be used ?

I Currently do use 
$ oc process -f template.json release=$releasenumber | oc apply -f -

Please advise.

Thanks,
Rami

**Comment by aijanai** [comment]
apply is for idempotent calls even when the object doesn't exist yet

**Pull request closed without merging**
