### PR TITLE
sync godeps

### PR DESCRIPTION
**Pull request by sjenning**
Removes unused/nonexistent deps
Adds entries for deps that are in the tree but not in Godeps.json

@eparis @ncdc @mfojtik

### CODE REVIEW

**Comment by liggitt** [comment]
why do we keep adding and removing the `golang.org/x/sys/windows` files? @smarterclayton, you just had to fix adding those back in

**Comment by ncdc** [comment]
goproxy is used by kube upstream as part of an e2e test, which is why upstream kube has it in its Godeps.json. Do we have some custom script that keeps stuff like that in our tree that a normal `godep restore/godep save` won't catch?

**Comment by sjenning** [comment]
@ncdc @eparis had started on a script for wrapping ```godep restore/save```.  Are you saying that goproxy _is_ something we should have in the dep tree for origin?  IMHO, it would be better if we could find some way to trick ```godep save``` into including the dep rather than have a godep wrapper script.  Not sure how to do that though.

**Comment by ncdc** [comment]
Yes, we need goproxy. See https://github.com/openshift/origin/blob/0ee4496c4f9a1a5cdc20eb795a602cc24b0cb781/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/roundtripper_test.go#L29

**Comment by ncdc** [comment]
Try passing the `-t` flag to `godep save`

**Comment by ncdc** [comment]
Or maybe not, that appears just to save _test.go and testdata stuff.

**Comment by eparis** [comment]
You definitely need -t in this repo (though I don't love it)

Also upstream we use:
https://github.com/kubernetes/kubernetes/blob/master/hack/godep-save.sh
to do saves, because there are some things (codecgen and ginkgo) which we need the binaries but which are not code dependencies

@sjenning will you create a hack/godep-restore.sh and a hack/godep-save.sh which when run in a clean GOPATH will work?

**Comment by sjenning** [comment]
got clicky and blew away the github branch.  restored and reopened.

**Pull request closed without merging**
