### PR TITLE
NO-JIRA: watchpods: fix the collection logic for pending pods

### PR DESCRIPTION
**Pull request by rphillips**
[periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le/1749182126944686080) is exhibiting a flake with pods transitioning to Pending state. I reviewed the kubelet, scheduler, and test logs, and everything seems to make sense.

The test itself though does not check to see if the 'Old' pod was in Pending state to check for the invalid state transition. The PR changes the test so an Old Pod Phase of `Pending` and a New Pod Phase of `Pending` are not considered bad transitions.

### CODE REVIEW

**Comment by harche** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by rphillips** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by rphillips** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by rphillips** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le

**Pull request closed without merging**
