### PR TITLE
UPSTREAM: 71573  Correctly Clear conntrack entry on endpoint changes when using nodeport

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
https://github.com/kubernetes/kubernetes/pull/71573

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1537780

### CODE REVIEW

**Comment by knobunc** [comment]
/approve

@smarterclayton can you approve this backport please?

**Comment by dcbw** [comment]
@soltysh could you sign off on this one, or affirm that it'll be picked up in the rebase?

**Comment by JacobTanenbaum** [comment]
@soltysh PTAL this change is already been merged in 3.10 and 3.11

**Comment by knobunc** [comment]
@mfojtik Do you know if @soltysh is around at the moment?  It seems not to have been picked up by the rebase, and since it's on our older branches and upstream it would be nice to get this in to 4.0 soon.

**Comment by soltysh** [comment]
This is targetted at master branch which is currently frozen until we land the rebase. Only upstream PRs that are helping us towards landing the rebase are being merged. All the rest MUST wait after the rebase lands. Is there any immediate need for that, as in it fixes e2e flakes or something similar?

**Comment by soltysh** [comment]
Also, from what I see this fix was not picked as part of 1.12 rebase, so it has to wait.

**Comment by soltysh** [comment]
/hold cancel
although it looks you need to rebase it

**Comment by JacobTanenbaum** [comment]
@deads2k @derekwaynecarr PTAL, the tests have gone all green

**Pull request merged**
