### PR TITLE
Cluster capacity rebase to kubernetes 1.9

### PR DESCRIPTION
**Pull request by aveshagarwal**
Still doing some testing.

@sjenning FYI

### CODE REVIEW

**Comment by ingvagabund** [comment]
Nice kitty: https://github.com/openshift/origin/pull/18088/files#diff-12ec0e09fe110f50616e20d165cfb06d

**Comment by sjenning** [comment]
> Nice kitty: https://github.com/openshift/origin/pull/18088/files#diff-12ec0e09fe110f50616e20d165cfb06d

what the?!

**Comment by aveshagarwal** [comment]
I looked into test failures and I dont think any test failure is related to cluster capacity update.

**Comment by aveshagarwal** [comment]
@sjenning it passed all tests now. who can tag lgtm?

**Pull request merged**
