### PR TITLE
Bug 1802996: [4.1] Fix reinitialization of deny-all NetworkPolicy state on restart

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Backport of: https://github.com/openshift/sdn/pull/96 https://github.com/openshift/sdn/pull/103
These are just 2 cherry-picks without conflicts.

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
@danwinship should we close this instead?
Although it's ready to merge, it's 4.1 as far as we know it's not affecting any customer.

**Comment by danwinship** [comment]
yeah, I guess so...
/close

**Pull request closed without merging**
