### PR TITLE
Remove dockerregistry Dockerfile and build

### PR DESCRIPTION
**Pull request by liggitt**
The docker registry is built by the `make images` step of the image-registry repo, remove it from being rebuilt as part of the origin build.

e2e should (*should*) pick up the already built image because it gets cross-tagged.

When we branch 3.8, we'll need to ensure the 3.8 branch of the image registry is tested with with 3.8 branch of origin

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Investigating e2e job

**Comment by liggitt** [comment]
it's not clear what image `cluster up` was trying to pull for the registry

**Comment by stevekuznetsov** [comment]
We were trying to pull the right one:

```
[INFO] Using images:							openshift/origin-${component}:b5b4d46
```

We just aren't building it in that job. Will fix

**Pull request merged**
