### PR TITLE
Retry build instantiation on conflict in rest api

### LINKED ISSUE #13220: Extended.[builds][Slow] openshift pipeline build Blue-green pipeline Blue-green pipeline should build and complete successfully
```
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs "bluegreen-pipeline": the object has been modified; please apply your changes to the latest version and try again
```
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/1152/testReport/junit/(root)/Extended/_builds__Slow__openshift_pipeline_build_Blue_green_pipeline_Blue_green_pipeline_should_build_and_complete_successfully/

### LINKED ISSUE #13694: build flake: Update conflict in blue-green pipeline job starting build prevents build from running
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/137/testReport/junit/(root)/Extended/_builds__Slow__openshift_pipeline_build_Blue_green_pipeline_Blue_green_pipeline_should_build_and_complete_successfully/

Generic trigger controller runs faster, this may be the root cause of this.  Conflict on server should be retried in most cases.

```
Apr  8 18:38:42.515: INFO: Running 'oc start-build --config=/tmp/extended-test-jenkins-pipeline-1x9fj-8wn49-user.kubeconfig --namespace=extended-test-jenkins-pipeline-1x9fj-8wn49 bluegreen-pipeline -o=name'
Apr  8 18:38:42.902: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc start-build --config=/tmp/extended-test-jenkins-pipeline-1x9fj-8wn49-user.kubeconfig --namespace=extended-test-jenkins-pipeline-1x9fj-8wn49 bluegreen-pipeline -o=name] []    Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "bluegreen-pipeline": the object has been modified; please apply your changes to the latest version and try again
 [] <nil> 0xc421654990 exit status 1 <nil> <nil> true [0xc42002db20 0xc42002db50 0xc42002db60] [0xc42002db20 0xc42002db50 0xc42002db60] [0xc42002db28 0xc42002db48 0xc42002db58] [0x9b7d50 0x9b7e50 0x9b7e50] 0xc4212cac60 <nil>}:
StdOut>

StdErr>
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "bluegreen-pipeline": the object has been modified; please apply your changes to the latest version and try again



start-build output with args [bluegreen-pipeline -o=name]:
Error>exit status 1
StdOut>

StdErr>
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "bluegreen-pipeline": the object has been modified; please apply your changes to the latest version and try again

[AfterEach] Blue-green pipeline
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:271
```

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #13694 
fixes #13220

### CODE REVIEW

**Comment by jim-minter** [comment]
@csrwng @bparees at the moment I'm just putting this out here for discussion ;)

Is retry-N-times a preferred strategy to retry-forever?

Separately, actually there are quite a few calls to Instantiate() in our codebase.  Some specifically catch a Conflict response and *don't* retry (um?).  Others don't catch it.

I'm wondering whether a better plan is to refactor Instantiate() to retry itself (according to the retry strategy you prefer) and clear up the conflict paths where they exist in callers?

@openshift/devex

**Comment by gabemontero** [comment]
retry forever generically scares me, but I admittedly don't have the requisite experience with the build instantiate/create path to say it does not fit into some special case category.

I like the latter idea, assuming the implementation cost/risks are tolerable.

my 2 cents in any event

**Comment by csrwng** [comment]
> Is retry-N-times a preferred strategy to retry-forever?

I vote for retry-N-times



> I'm wondering whether a better plan is to refactor Instantiate() to retry itself (according to the retry strategy you prefer) and clear up the conflict paths where they exist in callers?

Seems reasonable

**Comment by bparees** [comment]
Near as i can tell, the only place we update the buildconfig is within instantiate() and clone().  So again i'm not clear how we're hitting this failure unless someone else is also starting a build at the same time and we're in a race.

anyway I vote for N retries and moving the retry logic into the instantiate/clone methods, but i'm still concerned we don't really understand why the conflict is happening.

**Comment by jim-minter** [comment]
@bparees hmm, then could it be the jenkins plugin that's updating the buildconfig under our feet?  I still need to go through the logs in more detail.

**Comment by bparees** [comment]
@jim-minter w/o looking at the test/pipeline definition etc myself, all i can say is "anything's possible" :)

**Comment by gabemontero** [comment]
It could be the plugin.  After initiating the build request, once we have the build object, we annotate the build with the job url.  See https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftBuilder.java#L251-L258

When we implemented that job annotation pieced, I had to add some retry there because I was getting update conflicts.  See https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftPlugin.java#L612-L614

**Comment by gabemontero** [comment]
Also, that blue-green job has some multithreaded-ness, including accessing the build with background threads .... i would hope that etcd manages the RO vs RW type of locking as one would expect, but I only have a high level understanding of etcd

**Comment by bparees** [comment]
> It could be the plugin. After initiating the build request, once we have the build object, we annotate the build with the job url

we're getting the conflict on the update to the buildconfig, not the build, though.

**Comment by gabemontero** [comment]
On Thu, Apr 27, 2017 at 2:39 PM, Ben Parees <notifications@github.com>
wrote:

> It could be the plugin. After initiating the build request, once we have
> the build object, we annotate the build with the job url
>
> we're getting the conflict on the update to the buildconfig, not the
> build, though.
>
Ah ... then yeah, don't see after my review the jenkins plugin contributing
to the race/conflict

**Comment by jim-minter** [comment]
The source of the conflict is definitely Java (okhttp user agent):
```
I0426 12:55:04.100810    2597 panics.go:76] GET /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline: (5.846ms) 200 [[okhttp/3.4.2] 172.17.0.4:58212]
I0426 12:55:04.124480    2597 panics.go:76] GET /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline: (7.214965ms) 200 [[okhttp/3.4.2] 172.17.0.4:58212]
I0426 12:55:04.282048    2597 panics.go:76] GET /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline: (3.17854ms) 200 [[openshift/v3.6.0 (linux/amd64) openshift/b4cdb81] 172.18.15.5:34530]
I0426 12:55:04.320678    2597 panics.go:76] PUT /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline: (7.782331ms) 200 [[okhttp/3.4.2] 172.17.0.4:58212]
I0426 12:55:04.339865    2597 panics.go:76] POST /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline/instantiate: (64.612288ms) 409 [[oc/v3.6.0 (linux/amd64) openshift/b4cdb81] 172.18.15.5:47686]
I0426 12:55:04.919017    2597 panics.go:76] DELETE /oapi/v1/namespaces/extended-test-jenkins-pipeline-1n0dc-8cr85/buildconfigs/bluegreen-pipeline: (12.213644ms) 200 [[openshift/v3.6.0 (linux/amd64) openshift/b4cdb81] 172.18.15.5:34530]
```

I think that the issue is probably PipelineJobListener.java in openshift-sync-plugin firing in response to the pipeline being created initially and sending a needless buildconfig update back to OpenShift.  @gabemontero would you be able to help me fix this?

Regardless, I think the origin server code should be hardened up: will update this PR to do so.

**Comment by jim-minter** [comment]
[test]

**Comment by gabemontero** [comment]
| @gabemontero would you be able to help me fix this?

I should be able to look into the sync plugin item soon @jim-minter

**Comment by jim-minter** [comment]
flake #14109
flake #14110
[test]
@bparees, @csrwng ptal

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/10773
[test]

**Comment by bparees** [comment]
@jim-minter i'm ok w/ merging this if you're happy, just take the WIP off the description.

**Comment by jim-minter** [comment]
@bparees done - please merge

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
something appears to have hung in the networking tests
[merge]

**Pull request merged**
