### PR TITLE
allow for bypass of not proceeding deployment check jenkins extended tests given update center sync delay is now on startup

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

see discussion in https://github.com/openshift/jenkins/pull/544 and failure in https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/417/consoleFull#-153881154656cbb9a5e4b02b88ae8c2f77

### CODE REVIEW

**Comment by bparees** [comment]
hm.  this is going to make these tests always wait 3 minutes before they have any hope of progressing.

should we be changing the waitfordeploymentconfig logic?  is it just flat out wrong that it currently aborts when progressing is false, based on your deployment api investigation?

I think this is worth a discussion with @mfojtik and team.

**Comment by gabemontero** [comment]
On Fri, Mar 16, 2018 at 3:17 PM, Ben Parees <notifications@github.com>
wrote:

> hm. this is going to make these tests always wait 3 minutes before they
> have any hope of progressing.
>
> should we be changing the waitfordeploymentconfig logic? is it just flat
> out wrong that it currently aborts when progressing is false, based on your
> deployment api investigation?
>
I debated with myself more invasive changes and then opted for this.  In my
testing at least, jenkins startup now is at least 2 to 3 minutes anyway
doing the update center stuff
on startup.  So I used that in my decision making process.

> I think this is worth a discussion with @mfojtik
> <https://github.com/mfojtik> and team.
>
Sure thing

**Comment by gabemontero** [comment]
Well we got not progressing errors even with this change:

```
[image_ecosystem][jenkins][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test multitag DSL [Suite:openshift] 12m25s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[image\_ecosystem\]\[jenkins\]\[Slow\]\sopenshift\spipeline\splugin\s\sjenkins\-plugin\stest\scontext\s\s\sjenkins\-plugin\stest\smultitag\sDSL\s\[Suite\:openshift\]$'

/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:154
Expected error:
    <*errors.errorString | 0xc420b58590>: {s: "not progressing"}
    not progressing
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:206
				
				Click to see stdout/stderrfrom focus_parallel_03.xml

Filter through log files
[image_ecosystem][jenkins][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test trigger build with slave [Suite:openshift] 12m23s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[image\_ecosystem\]\[jenkins\]\[Slow\]\sopenshift\spipeline\splugin\s\sjenkins\-plugin\stest\scontext\s\s\sjenkins\-plugin\stest\strigger\sbuild\swith\sslave\s\[Suite\:openshift\]$'

/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:154
Expected error:
    <*errors.errorString | 0xc4201b85d0>: {s: "not progressing"}
    not progressing
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:206
				
				Click to see stdout/stderrfrom focus_parallel_02.xml

Filter through log files

```

Will get more aggressive in allowing for adjustments of existing logic

**Comment by gabemontero** [comment]
new version pushed that allows for not proceeding check to be optional

**Comment by gabemontero** [comment]
The bump of the jenkins LTS seems to have caused another problem (at least that is the most likely explanation for this exception, since we have not changed the login plugin lately):

```
java.io.IOException: java.lang.RuntimeException: Failed to serialize jenkins.model.Jenkins#securityRealm for class hudson.model.Hudson
	at hudson.XmlFile.write(XmlFile.java:200)
	at jenkins.model.Jenkins.save(Jenkins.java:3168)
	at jenkins.model.Jenkins.saveQuietly(Jenkins.java:3174)
	at jenkins.model.Jenkins.setAuthorizationStrategy(Jenkins.java:2544)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.updateAuthorizationStrategy(OpenShiftOAuth2SecurityRealm.java:859)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftPermissionFilter.doFilter(OpenShiftPermissionFilter.java:210)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to serialize jenkins.model.Jenkins#securityRealm for class hudson.model.Hudson
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:193)
	... 70 more
Caused by: java.lang.RuntimeException: Failed to serialize org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm#transport for class org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 83 more
Caused by: java.lang.UnsupportedOperationException: Refusing to marshal com.google.api.client.http.javanet.NetHttpTransport for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:543)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 92 more

```

Don't know yet why this did not show up in the image tests or my manual starting of the image at 2.101.

Will study a little be more, and there may be a change in the login plugin to avoid this, but the quick fix is probably to revert the lts bump, then try to sort this out.

**Comment by gabemontero** [comment]
Marking this field transient might be the longer term solution:

```
Caused by: java.lang.RuntimeException: Failed to serialize org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm#transport for class org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm
```

**Comment by gabemontero** [comment]
Duh ... bringing up the image outside a pod means the login plugin does not insert itself as the sec realm

**Comment by gabemontero** [comment]
ok let's retest after https://ci.openshift.redhat.com/jenkins/view/All/job/push_jenkins_images/169/ completes

**Comment by gabemontero** [comment]
last run looked better (no exceptions saving the oauth sec realm where we are back to 2.89.4 for now)

the image_eco/jenkins-plugin.go runs still seem more prone to the deploy to's ... but they still run at 512Mit vs. our build/pipeline.go runs.  Bumped image_eco/jenkins-plugin.go to more mem, and added pod log dump on jenkins deploy failure

In parallel, i'm testing locally:
a) i believe i have a login plugin change that will allow moving back to jenkins v2.107
b) but i'm still seeing some deploy timeouts in my local runs - seems more constrained than the ci/aws runs... going to look into
     i) moving the image's groovy init onto a separate path, to perhaps that allows jenkins startup to proceed faster
     ii) if that doesn't do it, figure our right deployment setting, modify jenkins template some more / reach out to master team as needed
     iii) or give up once again on incurring the updater center churn on startup vs. first login

**Comment by gabemontero** [comment]
OK, look better wrt the update center / GC stuff.

The image eco failure was in a jenkins test, but the problem was unrelated to the JVM.  There was a timeout adding the edit role to the service account:

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:154
Expected error:
    <*util.ExitError | 0xc42195e150>: {
        Cmd: "oc policy --config=/tmp/extended-test-jenkins-plugin-t9f42-lnzpd-user.kubeconfig --namespace=extended-test-jenkins-plugin-t9f42-lnzpd add-role-to-user edit system:serviceaccount:extended-test-jenkins-plugin-t9f42-lnzpd-jenkins:jenkins",
        StdErr: "Error from server: timeout",
        ExitError: {
            ProcessState: {
                pid: 109903,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 310356},
                    Stime: {Sec: 0, Usec: 60405},
                    Maxrss: 62672,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 14998,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 985,
                    Nivcsw: 1012,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:246
```

**Comment by gabemontero** [comment]
the extended builds were 2 more instances of the service not being considered ready in 600 seconds

going to get another sample while I try the other alternatives noted in https://github.com/openshift/origin/pull/19008#issuecomment-373917445

**Comment by gabemontero** [comment]
So, with have the login plugin update and jenkins v2.107 working with the ext tests.

Also, I got the update center init groovy working on a separate thread, running with PARALLEL_NODES=1 on my lap top, monitoring CPU, the jenkins container log, and the deployment.  I can see the readiness checks come in via the jenkins log (since they act like login reqs).  Even with the jenkins is up and running message already made, the readiness check does not always pass before the update center download finishes.  So it truly becomes a race with these factors:
a) available cpu on the node
b) and related to that, GC pressure
c) how responsive the jenkins update center is during a given run
d) how long the deployment controller waits

So, knobs we can/cannot tune (with some pros/cons)
a) I do not think "ramping up" cpu reqs/limits from the defaults is a viable option ... how do we pick a consistent value that works across potentially varying envs
b) is running the jenkins test in serial mode an option?  ... that might help with c)
c) to help with GC, we can further increase the heap allocated .... but with running tests in parallel, are we going to hit pain points where we exhaust node memory?
d) update the templates to make the deployment to configurable ... perhaps stay with the 600 second default, but then try to provide even more time in our extended tests ... slower tests for sure
e) revert the init groovy change ... live with the delay during initial login

@bparees thoughts?

in the interim, I'll get some more sample runs with this PR.  I may temporarily bump the heap, enable mem monitoring, got get more data.

**Comment by gabemontero** [comment]
image eco clean (no oc policy add role failure this time)

build a couple of jenkins took to long to be ready

about to push a temp change to force mem/gc/cp monitor

then will try a run with more heap for pipeline.go

**Comment by gabemontero** [comment]
the build origin stage failed everywhere this time

/retest

**Comment by gabemontero** [comment]
another option occurred to me:

my original change of disabling the comm with update center to see if there are advisories/updates ... I could make the disabling of those two things configurable via envvar/template param.  It could be on by default, but we explicitly disable it in the extended tests (and maybe online as well).  The groovy init stuff could be part of this decision point as well.

**Comment by bparees** [comment]
>  Even with the jenkins is up and running message already made, the readiness check does not always pass before the update center download finishes. So it truly becomes a race with these factors:
a) available cpu on the node
b) and related to that, GC pressure
c) how responsive the jenkins update center is during a given run
d) how long the deployment controller waits

to make sure I understand, the ultimate failure point is that the readiness check doesn't pass before the deployment times out?  And the readiness check passing is predicated on the update center processing completing, so that the login url responds successfully?


> So, knobs we can/cannot tune (with some pros/cons)
> a) I do not think "ramping up" cpu reqs/limits from the defaults is a viable option ... how do we pick a consistent value that works across potentially varying envs

Agree.

> b) is running the jenkins test in serial mode an option? ... that might help with c)

In general we've been pushed to remove serial tests, so if we did it, it would just become tech debt we'd be asked to resolve as soon as we did it.  i.e. might get us out of a hole now, but just signing up for more work later.

> c) to help with GC, we can further increase the heap allocated .... but with running tests in parallel, are we going to hit pain points where we exhaust node memory?

Possibly, but it seems worth a try.  I think we run a parallelism of 5 and we run on m4.xlarge instances (at least for the ec2 tests) which have 32gigs of memory.  I'm guessing we could afford to ramp it up, at least to 1gig, probably even 2.

(it looks like on ec2 we run parallelism of 5, on gce it's 25.  I'm going to assume the gce nodes have more memory but it's probably a conversation to have w/ steve. Note that today only conformance tests run on gce, and as i recall these are not in the conformance bucket)

> d) update the templates to make the deployment to configurable ... perhaps stay with the 600 second default, but then try to provide even more time in our extended tests ... slower tests for sure

I'm really surprised we're hitting a 10 min deployment timeout, given your other testing has shown at most maybe a 3-4 minute delay before login works (plus the initial jenkins startup time of course)  See my initial questions in this comment about what exactly is failing. But sure, this would be an ok path in my mind, though I agree slower tests are undesirable.

> e) revert the init groovy change ... live with the delay during initial login

So today (w/o the init changes) the login url "works" from a readiness check perspective (I guess the login screen comes up, but the update center logic doesn't get run until the user actually performs a login?)

> my original change of disabling the comm with update center to see if there are advisories/updates ... I could make the disabling of those two things configurable via envvar/template param. It could be on by default, but we explicitly disable it in the extended tests (and maybe online as well). The groovy init stuff could be part of this decision point as well.

It's an interesting thought, though we'd want to make sure we have at least one test that brings jenkins up w/ the update center installed to ensure we don't break something there, so not sure it totally solves our problem.  Also while we'd want the template to default disable it in starter, that's likely *not* how we'd want to ship the template in pro and OCP, which then becomes tricky to manage.

**Comment by gabemontero** [comment]
`to make sure I understand, the ultimate failure point is that the readiness check doesn't pass before the deployment times out? And the readiness check passing is predicated on the update center processing completing, so that the login url responds successfully?`

Yes and yes.

`I'm really surprised we're hitting a 10 min deployment timeout, given your other testing has shown at most maybe a 3-4 minute delay before login works (plus the initial jenkins startup time of course)`

It was for me too initially, but I was always running single pod deployment tests.  Once this started happening, I ran the extended tests on my laptop, where several pods ran at once, and started seeing the same deployment timeout all over the place.  Monitoring cpu on my laptop, it was pegged at 100% cpu for long periods, thrashing on GC.  As I reduced the parallel nodes setting systematically from 5 to 1, the situation improved.

Part of this PRs current temp debug is to monitor some gc/cpu in real time, see what occurs.  And that said, there is an intermittent aspect to this ... I've seen some of both build and image ecosystem ext tests pass on occasion both in the overnight and PR tests since adding the init groovy stuff back in.

```
It's an interesting thought, though we'd want to make sure we have at least one test that brings jenkins up w/ the update center installed to ensure we don't break something there, so not sure it totally solves our problem. Also while we'd want the template to default disable it in starter, that's likely not how we'd want to ship the template in pro and OCP, which then becomes tricky to manage.
```

+1 on all that / yep stuff that occurred to me as well ... feeling like the least of the evils, assuming we keep the jenkins stuff as an option on starter (yes, I didn't forget our prior conversations here, but I don't think we've reached the apex of our pain here yet.

**Comment by gabemontero** [comment]
ahh ... getting a compile error in pipeline.go I'm not seeing locally as part of the debug .... investigating

**Comment by gabemontero** [comment]
ok compile weirdness appears sorted out

**Comment by gabemontero** [comment]
well, builds passed, image_eco only had one failure, but the memory debug didn't show up

i'll see if i can sort that out locally, try again

**Comment by gabemontero** [comment]
ok ... more realizations ... we use `oc rsh` for our current mem debug; that depends on the fact that the pod at least comes up and is marked ready

i could see about monitoring whatever ec2 node the tests is on *while* the test is running and the problem occurs ... that is going to be hard ... more inclined to go off my local testing observations

we can talk more on Monday, but I'm leaning toward the configurable disabling of admin monitor, at least for extended tests, if not online as well, or backing of the start up path call to the update center

**Comment by gabemontero** [comment]
ok, we actually got clean build/image_eco system runs this time, even without the upcoming jenkins image changes

given the latest build/image_ecosystem overnight runs both had a couple of intermittent not progressing errors, shall we merge this in the interim @bparees ?

I removed the debug stuff already

**Comment by gabemontero** [comment]
fyi, none of the last few failures have been with the jenkins tests

**Comment by gabemontero** [comment]
the last conformance install failure was flake https://github.com/openshift/origin/issues/17883

**Comment by gabemontero** [comment]
various `Stage PROVISION CLOUD RESOURCES [00h 10m 24s] failed.` failures 

/retest

**Comment by gabemontero** [comment]
more provision cloud failures ... will wait a bit, see if clouds heal

**Comment by gabemontero** [comment]
provision test cluster problem

/test gcp

**Comment by gabemontero** [comment]
ok tests pass again ... let's see if we get lucky and they do so again now that we are back on the merge queue

**Pull request merged**
