### PR TITLE
Rename all controller.go to be easily distinguishable in logs

### PR DESCRIPTION
**Pull request by soltysh**
We need this for ease of debugging, and it should be merged for 3.6, still. 

Since I don't want to mess people yet, I'll wait for at least the rebase to land. @csrwng I've heard you're re-factoring build controllers so if you could pick the build part that will be also great and won't interfere with your changes @bparees mentioned. 

@sttts @ncdc @smarterclayton @liggitt @deads2k @mfojtik @knobunc @danwinship fyi

Currently blocked by https://github.com/openshift/origin/pull/13653

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by deads2k** [comment]
I like the idea of renaming them.

**Comment by bparees** [comment]
+1 on renaming them and +1 on letting us rename our own controllers :)

**Comment by deads2k** [comment]
> +1 on renaming them and +1 on letting us rename our own controllers :)

Didn't someone (who can remain nameless), force us to make all the filenames the same?  Something about go-like instead of java-like maybe?

**Comment by soltysh** [comment]
> Didn't someone (who can remain nameless), force us to make all the filenames the same? Something about go-like instead of java-like maybe?

That makes debugging any remote issue with controllers almost impossible. That's because with the glog limitation we only see the go filename, but no path to it. K8S already did that change, if we need another argument of this sort ;)

**Comment by soltysh** [comment]
Since the rebase landed, I'd like to push this forward as well. Any objections? @bparees since you complained a bit 😉

**Comment by bparees** [comment]
It's going to merge conflict some people but it shouldn't be too bad. Go for it. I'm certainly in favor of the rename in general.

**Comment by deads2k** [comment]
[merge]

**Comment by soltysh** [comment]
Flakes https://github.com/openshift/origin/issues/12072 and https://github.com/openshift/origin/issues/13985

**Comment by soltysh** [comment]
> It's going to merge conflict some people but it shouldn't be too bad. Go for it. I'm certainly in favor of the rename in general.

I know, myself included, since I'm modifying the image controller, switching to shared informers.

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
