### PR TITLE
UPSTREAM: 52221: Always populate volume status from node

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1481729

Actual Upstream PR - kubernetes/kubernetes#52221

But we think, we won't be able to get this in 1.8

### CODE REVIEW

**Comment by gnufied** [comment]
The failure is:

```
/go/src/github.com/openshift/origin/test/extended/router/metrics.go:173
Expected error:
    <*errors.errorString | 0xc4203d80b0>: {
        s: "last response from server was not 403: 401",
    }
    last response from server was not 403: 401
not to have occurred
/go/src/github.com/openshift/origin/test/extended/router/metrics.go:99			
```

It definitely looks like unrelated to this change.

**Comment by eparis** [comment]
https://github.com/openshift/origin/pull/16542 hopefully fixed stage so this can pass CI

**Pull request merged**
