### PR TITLE
Backport: Availability Zone is Ignored by Cinder API

### PR DESCRIPTION
**Pull request by pospispa**
This is "backport" of Kubernetes PR #44082 (https://github.com/kubernetes/kubernetes/pull/44082).
Actually, the github.com/gophercloud/gophercloud library version is bumped up to a version that contains the availability zone fix.

The problem is described in Bugzilla #1444828 (https://bugzilla.redhat.com/show_bug.cgi?id=1444828).

The problem was introduced into Kubernetes 1.6 and fixed in Kubernetes 1.7.
That's why the fix is "backported" into OpenShift 3.6.

### CODE REVIEW

**Comment by pospispa** [comment]
@rootfs @childsb @eparis PTAL

**Comment by soltysh** [comment]
LGTM

**Comment by pospispa** [comment]
@childsb @eparis I believe this PR can be merges, couldn't it?

**Comment by pospispa** [comment]
The https://github.com/openshift/origin/pull/14005 is a superset of this PR.
The https://github.com/openshift/origin/pull/14005 contains all fixes that are in this PR.
The https://github.com/openshift/origin/pull/14005 contains (a fix)[https://github.com/openshift/origin/pull/14005/commits/8107b3191078106f5651d59fea0eaa543577c7b1] that was done before the fix in this PR. That's why the https://github.com/openshift/origin/pull/14005 shall be merged before this PR and because it is also a superset of this PR I'm closing this PR without merge.

**Pull request closed without merging**
