### PR TITLE
UPSTREAM: 80004: Prefer to delete doubled-up pods of a ReplicaSet

### PR DESCRIPTION
**Pull request by p0lyn0mial**
brings back https://github.com/openshift/origin/pull/23806

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

not clear if we want to merge it again - https://github.com/openshift/origin/pull/23806#issuecomment-547403020

**Comment by tnozicka** [comment]
/hold
the PR "conveniently" nuked by rebase broke https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/release-openshift-openshift-ansible-e2e-aws-scaleup-rhel7-4.3 - we shouldn't merge it before the author (@Miciah) fixes the CI flake which seemed permanent on that periodic

**Comment by tnozicka** [comment]
ref BZ is here https://bugzilla.redhat.com/show_bug.cgi?id=1765756

**Comment by p0lyn0mial** [comment]
> I created #24057, which supersedes this PR 

okay, so I am closing this PR then, thx.

**Pull request closed without merging**
