### PR TITLE
UPSTREAM: 49724: skip WaitForAttachAndMount for terminated pods in syncPod

### PR DESCRIPTION
**Pull request by sjenning**
master PR https://github.com/openshift/origin/pull/15533

This can wait for 3.6.1

@derekwaynecarr

### CODE REVIEW

**Comment by sjenning** [comment]
@stevekuznetsov I hit
```
+ hack/env make build-router-e2e-test
[INFO] Pulling the openshift/origin-release:golang-1.7 image to update it...
Trying to pull repository registry.access.redhat.com/openshift/origin-release ... 
Trying to pull repository docker.io/openshift/origin-release ... 
golang-1.7: Pulling from docker.io/openshift/origin-release
Digest: sha256:9dbd5afabca198001e9cae62eaca8646248770fe5a9e10f67baab034ab44309b
make: *** No rule to make target `build-router-e2e-test'.  Stop.
```
Doesn't seem like that would be a flake but I'll do a retest in case it was or has been fixed in the meantime.

/test end_to_end

**Comment by stevekuznetsov** [comment]
Ah, crap. This branch needs get the changes backported @dea

**Comment by sjenning** [comment]
flake https://github.com/openshift/origin/issues/15941

**Pull request merged**
