### PR TITLE
add missed dashboard_file variable

### PR DESCRIPTION
**Pull request by cyron**
the dashboard_file variable is missing, when deploymented with this script,
and access the node-exporter dashboard, error message "Datasource named ${DS_PR} was not found" will appear.

### CODE REVIEW

**Comment by jwforres** [comment]
@openshift/sig-monitoring 

looks like the old grafana examples, do we even still want to have this example here versus having people deploying the grafana that is a part of cluster monitoring

/assign @brancz

**Comment by pgier** [comment]
@brancz Yes, I agree we should remove the older grafana example and point people to the newer monitoring setup instead.

**Comment by cyron** [comment]
hi, could anyone kindly point me where to find the newer monitoring setup?

**Pull request closed without merging**
