### PR TITLE
UPSTREAM: 24208: Honor starting resourceVersion in watch cache

### PR DESCRIPTION
**Pull request by ncdc**
@liggitt @smarterclayton

### CODE REVIEW

**Comment by ncdc** [comment]
This wasn't a clean cherry-pick. Please review carefully.

I assume we'll want to wait for this to merge upstream

**Comment by deads2k** [comment]
The only "sane" way I could see to do this would be to explicitly depend on the comparability of resourceVersions when used by etcd.  I didn't know that was a restriction for this.  Is it?  Is that limitation well known?

**Comment by ncdc** [comment]
@deads2k I'm not sure what you're asking

**Comment by ncdc** [comment]
But better to comment on the upstream PR, right?

**Comment by liggitt** [comment]
yes, the assumption of resourceVersion comparability runs throughout the watch cache

**Comment by liggitt** [comment]
LGTM

**Comment by ncdc** [comment]
Upstream PR just merged

**Comment by liggitt** [comment]
[merge]

**Comment by ncdc** [comment]
```
Running test/end-to-end/core.sh:130: executing 'docker pull 172.30.168.192:5000/cache/mysql:pullthrough' expecting success...
FAILURE after 17.798s: test/end-to-end/core.sh:130: executing 'docker pull 172.30.168.192:5000/cache/mysql:pullthrough' expecting success: the command returned the wrong error code
Standard output from the command:
Trying to pull repository 172.30.168.192:5000/cache/mysql ... pullthrough: Pulling from cache/mysql
70e9a6907f10: Pulling fs layer
32f2a4cccab8: Pulling fs layer
941b42725941: Pulling fs layer
9d1d3901c20a: Pulling fs layer
7c88fa8d073b: Pulling fs layer
7148ec0a1b6a: Pulling fs layer
6d4e5d65fa7a: Pulling fs layer
5c38331b8ed5: Pulling fs layer
354d042e3175: Pulling fs layer
5c4d4e18341e: Pulling fs layer
d384b7b60269: Pulling fs layer
d8cf53addf9e: Pulling fs layer
bb932e31780f: Pulling fs layer
9ea1fef42552: Pulling fs layer
cc5bed84d505: Pulling fs layer
e2fd05a2f2e8: Pulling fs layer
c607d9b50dfa: Pulling fs layer
c607d9b50dfa: Verifying Checksum
c607d9b50dfa: Download complete
6d4e5d65fa7a: Verifying Checksum
6d4e5d65fa7a: Download complete
e2fd05a2f2e8: Verifying Checksum
e2fd05a2f2e8: Download complete
9ea1fef42552: Verifying Checksum
9ea1fef42552: Download complete
32f2a4cccab8: Verifying Checksum
32f2a4cccab8: Download complete
bb932e31780f: Verifying Checksum
bb932e31780f: Download complete
cc5bed84d505: Verifying Checksum
cc5bed84d505: Download complete
d384b7b60269: Verifying Checksum
d384b7b60269: Download complete
7148ec0a1b6a: Verifying Checksum
7148ec0a1b6a: Download complete
354d042e3175: Verifying Checksum
354d042e3175: Download complete
9d1d3901c20a: Verifying Checksum
9d1d3901c20a: Download complete
5c38331b8ed5: Verifying Checksum
5c38331b8ed5: Download complete
d8cf53addf9e: Verifying Checksum
d8cf53addf9e: Download complete
941b42725941: Verifying Checksum
941b42725941: Download complete
7c88fa8d073b: Verifying Checksum
7c88fa8d073b: Download complete
5c4d4e18341e: Verifying Checksum
70e9a6907f10: Verifying Checksum
70e9a6907f10: Download complete
70e9a6907f10: Pull complete
32f2a4cccab8: Pull complete
941b42725941: Pull complete
9d1d3901c20a: Pull complete
7c88fa8d073b: Pull complete
7148ec0a1b6a: Pull complete
6d4e5d65fa7a: Pull complete
5c38331b8ed5: Pull complete
354d042e3175: Pull complete
not found
Standard error from the command:
Error: image cache/mysql:pullthrough not found
```

[merge]

**Comment by ncdc** [comment]
@miminar @smarterclayton does the flake above look familiar?

**Comment by liggitt** [comment]
yeah, https://github.com/openshift/origin/issues/8399
[merge]

**Pull request merged**
