### PR TITLE
delete the redundant loop that save slice to map

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/10487
[test]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/10487
[test]

**Comment by guangxuli** [comment]
@bparees ptal,thanks.

**Comment by bparees** [comment]
marked for post 3.3.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
