### PR TITLE
fix broken "failing postCommit default entrypoint" test and reformat for clarity

### PR DESCRIPTION
**Pull request by jim-minter**
reformatting + a missing 'sh -c' in the last test which meant that it wasn't working

@jupierce as discussed (ages ago)

### CODE REVIEW

**Comment by jim-minter** [comment]
[testextended][extended:core(testing build configuration hooks)]

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/12540
https://github.com/openshift/origin/issues/11004
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/12540
flake https://github.com/openshift/origin/issues/10773
[merge]

**Comment by stevekuznetsov** [comment]
@bparees as you did not link to the job logs when you mentioned the flake ... I cannot look to see the context for the failures.

**Comment by bparees** [comment]
@stevekuznetsov i didn't link it because the issue already existed and had a link to a failing job.  do you need more examples?

**Pull request merged**
