### PR TITLE
UPSTREAM: 31607: Add kubectl describe storageclass

### PR DESCRIPTION
**Pull request by jsafrane**

### CODE REVIEW

**Comment by jsafrane** [comment]
[test]

**Comment by jsafrane** [comment]
flakes:

```
--- FAIL: TestCheckRemoteGit (20.38s)
	source_test.go:37: unexpected error "fatal: unable to access 'https://github.com/openshift/origin/': Could not resolve host: github.com; Name or service not known"
```

**Comment by jsafrane** [comment]
[test]

**Comment by eparis** [comment]
I haven't looked yet between https://github.com/openshift/origin/pull/11475 and this.

**Comment by jsafrane** [comment]
@eparis, #11475 already includes code from this PR, i.e. this one could be closed if we want #11475

**Comment by eparis** [comment]
you willing to review over there?

**Comment by jsafrane** [comment]
Updated with Scott's changes, now contains all code that is in #11475 + it *should* pass tests

**Comment by jsafrane** [comment]
[test]

**Comment by eparis** [comment]
because it's going to take all day anyway [merge]

**Comment by screeley44** [comment]
@jsafrane - THANKS!  It would have taken me some time to figure out the bash stuff, so this def should speed things up

**Pull request merged**
