### PR TITLE
prometheus annotations dropped from router service

### PR DESCRIPTION
**Pull request by pecameron**
oc adm router
creates the router service without the prometheus annotations when
the default cert is not supplied. This is a regression introduced
by PR 10345 (fix for bug 1349144)

Fixes bug 1491430

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc PTAL

**Comment by imcsk8** [comment]
Code looks ok, LGTM

**Comment by pecameron** [comment]
@fabianofranz could you approve this?
@knobunc Should you or some team members be on the approve list?

**Comment by knobunc** [comment]
@pecameron Already posted the PR to add people to the OWNERS -- https://github.com/openshift/origin/pull/16375

**Comment by knobunc** [comment]
@rajatchopra Unless I'm being particularly dense today, the code at https://github.com/openshift/origin/pull/16334/files#diff-336f4b17c5000b42d210b83916ebddd1R795 guarantees the object is not nil.

**Comment by rajatchopra** [comment]
I meant if the t.Annotations object is nil or not. Let me get to a real computer and check the code. The phone doesn't cut it :).

**Pull request merged**
