### PR TITLE
cross-build (Windows) fix

### LINKED ISSUE #12077: Windows Client Fails to Compile
As seen in the [`devenv_ami` jobs](https://ci.openshift.redhat.com/jenkins/job/devenv_ami/5444/consoleFull)

```
+ vagrant ssh -c 'cd /data/src/github.com/openshift/origin && make build-cross'
rm -rf _output
hack/build-cross.sh
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Building go targets for darwin/amd64: cmd/openshift cmd/oc
++ Building go targets for windows/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/vendor/github.com/docker/docker/pkg/term/windows
vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:186: cannot use keyEvent.VirtualKeyCode (type winterm.WORD) as type uint16 in argument to formatVirtualKey
vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:186: cannot use keyEvent.ControlKeyState (type winterm.DWORD) as type uint32 in argument to formatVirtualKey
vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:189: cannot use keyEvent.ControlKeyState (type winterm.DWORD) as type uint32 in argument to getControlKeys
# github.com/openshift/origin/vendor/github.com/Microsoft/go-winio
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:15: undefined: "github.com/openshift/origin/vendor/golang.org/x/sys/windows".NewLazySystemDLL
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:16: undefined: "github.com/openshift/origin/vendor/golang.org/x/sys/windows".NewLazySystemDLL
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:17: undefined: "github.com/openshift/origin/vendor/golang.org/x/sys/windows".NewLazySystemDLL
[ERROR] PID 2551: hack/common.sh:257: `local -a binaries=("$@")` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:257: `local -a binaries=("$@")`
[INFO] 		  2: hack/build-cross.sh:24: os::build::build_binaries
[INFO]   Exiting with code 1.
make: *** [build-cross] Error 1
Build step 'Execute shell' marked build as failure
```

@smarterclayton @csrwng

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #12077

### CODE REVIEW

**Comment by ncdc** [comment]
I think we still need ansi_reader.go with the WORD -> uint16 change (it came from https://github.com/openshift/origin/commit/734a79b). Right @smarterclayton ?

**Comment by smarterclayton** [comment]
Yes, I believe that's still necessary (I don't remember when docker bumped
or if they had)

On Nov 30, 2016, at 2:22 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test Running (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/11827/) (Base
Commit: b32bbcf
<https://github.com/openshift/origin/commit/b32bbcfb1591a4c09c885bf8bf5711b1f9cc6e60>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12078#issuecomment-263968328>,
or mute
the thread

**Comment by ncdc** [comment]
Chatting with @jim-minter on irc; he's bumping golang.org/x/sys and thinks the WORD change is no longer necessary. We'll see...

**Comment by jim-minter** [comment]
[test]

**Comment by jim-minter** [comment]
flake #11024
flake #8571

**Comment by jim-minter** [comment]
[test]

**Comment by soltysh** [comment]
Merging as is, will look into godeps when this is in.

[merge]

**Pull request merged**
