### PR TITLE
Bug 1867800: Make EBS attachDisk idempotent

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1867800

@openshift/sig-storage

### CODE REVIEW

**Comment by ashcrow** [comment]
@gnufied I don't see a PR in the main branch for this. Is it safe to say that the change will still be applied but via kubernetes rebases?

**Comment by gnufied** [comment]
@ashcrow yes the change to master was brought via k/k rebase of 1.19.

**Comment by ashcrow** [comment]
Note to next patch manager: Label removed due to missing approved.

**Pull request merged**
