### PR TITLE
Use ruby 2.5 image in extended tests

### PR DESCRIPTION
**Pull request by adambkaplan**
Attempt to address build test errors from Gemfile dependency failure:

```
2019-01-16T08:28:42.127100663Z Gem::InstallError: i18n requires Ruby version >= 2.3.0.
```

### CODE REVIEW

**Comment by bparees** [comment]
did you check for references to the ruby:2.2 imagestream from buildconfigs?  i guess if it's an issue you'll see it in the test runs for this PR.

**Comment by adambkaplan** [comment]
we have two spots where we are using that ImageStream. Those seem to be passing, and one relies on mounting a path specific to the 2.2 image.

**Comment by adambkaplan** [comment]
/hold

Finally have real failures on build tests due to version bump

**Comment by bparees** [comment]
no longer needed since we fixed the hello-world repo to work with ruby 2.2 again but would still be nice to get to 2.5 if you have time to finish the updates needed here.

**Comment by adambkaplan** [comment]
/close

Already implemented in master

**Pull request closed without merging**
