### PR TITLE
Replace the tab with 4 spaces

### PR DESCRIPTION
**Pull request by YuPengZTE**
Spaces, it is aligned to view code with any editor, including the web
page view (such as in the GitHub code). When use tabs, the view on the
page is chaos, and it is terrible to mix tabs and spaces.

### CODE REVIEW

**Comment by mfojtik** [comment]
@YuPengZTE guess you can close this in favor of https://github.com/openshift/origin/pull/10178 ?

**Comment by YuPengZTE** [comment]
@mfojtik Sorry, #10178 is a wrong operation, now, it is closed.

**Comment by mfojtik** [comment]
@YuPengZTE also please squash this into one commit when you will be done :-)

**Comment by YuPengZTE** [comment]
@mfojtik Thanks, this PR is closed, and the changes are in #10200 .

**Pull request closed without merging**
