### PR TITLE
Bug 1960171: Enable SNO check for image registry

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
cc @xiuwang @wzheng1 - fyi, we (will) have an automated check for number of replicas on AWS, https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-single-node

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Comment by dmage** [comment]
/retitle Bug 1960171: Enable SNO check for image registry

**Pull request merged**
