### PR TITLE
Ocp 21041

### PR DESCRIPTION
**Pull request by wmuha**
fyi: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21041

### CODE REVIEW

**Comment by s-urbaniak** [comment]
as @brancz mentioned in https://github.com/openshift/origin/pull/23570#issuecomment-519421281, the right place for unit tests like these is in https://github.com/openshift/cluster-monitoring-operator/blob/master/pkg/manifests/manifests_test.go. I agree here is not the best place for these.

**Comment by wmuha** [comment]
Thank you @s-urbaniak and @brancz for your comments! will move test there

**Comment by stlaz** [comment]
/close
Please use a better name for the PR next, although this certainly catches one's eye

**Pull request closed without merging**
