### PR TITLE
Job cherry-picks

### PR DESCRIPTION
**Pull request by soltysh**
@pweil- @smarterclayton ptal
Currently only the last one (https://github.com/kubernetes/kubernetes/pull/16494) is not merged yet, so it may change, I'd suggest waiting until it lands and merge only afterwards.

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by davidopp** [comment]
FYI we will cherrypick #16494 into 1.1

**Comment by pweil-** [comment]
Looks like 16494 is now merged as well.  :+1:

**Comment by soltysh** [comment]
@pweil- yup, but it changed, updating that.

**Comment by soltysh** [comment]
Ready to rock'n'roll :guitar: !!!

**Comment by soltysh** [comment]
re-[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
