### PR TITLE
FIx CI for 3.11

### PR DESCRIPTION
**Pull request by soltysh**
/hold

### CODE REVIEW

**Comment by sdodson** [comment]
Hmm, nevermind, I went looking for 3.11 PRs failing on e2e-gcp to test the fix in https://github.com/openshift/openshift-ansible/pull/12203
But this is not a good PR to test since this actually attempts to change things such that the test works.

**Comment by soltysh** [comment]
Yeah, I used it to proof the initial problem @sdodson. Let's see if this now works w/o the hacks.

**Comment by soltysh** [comment]
It looks like the only failure in this PR was caused by HAProxy test, which was fixed in https://github.com/openshift/origin/pull/25045 I've picked that here and let's see where we get with it.
/cc @frobware 
since you authored the original PR

**Comment by frobware** [comment]
> It looks like the only failure in this PR was caused by HAProxy test, which was fixed in #25045 I've picked that here and let's see where we get with it.
> /cc @frobware
> since you authored the original PR

LGTM, though not sure I should be approving my commits...

**Comment by soltysh** [comment]
Yeah, that particular unit flaked a lot and was fixed in https://github.com/openshift/origin/pull/21957 so I'm picking that one too here.

**Pull request merged**
