### PR TITLE
NetworkPolicy tests

### PR DESCRIPTION
**Pull request by danwinship**
This pulls in the NetworkPolicy tests from https://github.com/kubernetes/kubernetes/pull/35660, and then makes a few changes to get it to work with our extended networking test, and to get it to actually pass given the current state of our NetworkPolicy support; hopefully the last commit will be able to be reverted at some point.

### CODE REVIEW

**Comment by danwinship** [comment]
[testextended][extended:networking]

**Comment by danwinship** [comment]
node startup is failing for networkpolicy:

    Feb 16 15:50:08 nettest-node-1 openshift[359]: I0216 15:50:08.281390     359 ovs.go:62] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=21, priority=100, ip, actions=ct(commit,table=30)
    Feb 16 15:50:08 nettest-node-1 openshift[359]: I0216 15:50:08.285473     359 ovs.go:66] Error executing ovs-ofctl: OFPT_ERROR (OF1.3) (xid=0x2): OFPBAC_BAD_TYPE

It works fine for me locally, and this is inside the dind image, so it ought to be exactly the same software...

**Comment by danwinship** [comment]
Oh, right, the OVS userland is in dind and so is 2.5, but the kernel side of it is in the host and so is still 2.4 here.

**Comment by danwinship** [comment]
@openshift/networking PTAL
The tests won't actually pass until both #14466 and #14498 have merged. Or, well, actually they *will* pass here, because jenkins is still using RHEL 7.2 and so the "is your kernel new enough" check will fail and the networkpolicy tests will be skipped. But they'd fail if you ran them locally.

**Comment by danwinship** [comment]
> the "is your kernel new enough" check

Oh, right. So, this adds a check to the extended networking test setup script that makes it skip the networkpolicy tests if your kernel is too old (which basically means "RHEL < 7.3" since any non-enterprise distro with a kernel too old to support OVS conntrack would presumably also have ancient golang and docker). This lets us commit the tests before jenkins gets updated (#13049).

**Comment by knobunc** [comment]
Since https://github.com/openshift/origin/pull/12972 merged, can we revisit this?

**Comment by danwinship** [comment]
as per the comment above, this is currently waiting on #14466 and #14498

**Comment by danwinship** [comment]
rebased on top of #14466. we want to get this in, although 14466 should merge first. (Note that this only affects the full extended networking test, so even in the worst case it's not going to create more flakes for everyone else)

**Comment by danwinship** [comment]
@stevekuznetsov how do I run the full extended networking test rather than just extended_networking_minimal?

**Comment by stevekuznetsov** [comment]
Should be possible now

**Comment by rajatchopra** [comment]
Looks great to me. How can we get this merged?

**Comment by stevekuznetsov** [comment]
There is one last step:

>  Submit Queue — PR does not have lgtm label. 

The reviewer ( @dcbw  ) needs to add their `/lgtm` tag to this by commenting in the thread.

**Pull request merged**
