### PR TITLE
expose: Bump validation and default flag message to routes

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton ptal

I am not sure if we want to do the flag validation part. 

ps. Note that I have left out `--protocol` since it has a default value set so we cannot know if the user runs it or not.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Test case

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@smarterclayton this is ready

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
