### PR TITLE
Switch empty extension files to return 200 with Content-Length zero

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by spadgett** [comment]
What cache headers are generated now when there is no content?

**Comment by jwforres** [comment]
All the headers:

```
cache-control:public, max-age=0, must-revalidate
content-encoding:gzip
content-length:23
content-type:application/javascript; charset=utf-8
date:Tue, 24 Jan 2017 14:12:54 GMT
etag:W/"d41d8cd98f00b204e9800998ecf8427e_677a6970"
status:200
vary:Accept-Encoding
x-content-type-options:nosniff
x-frame-options:DENY
x-xss-protection:1; mode=block
```

**Comment by spadgett** [comment]
Does that response have content? Otherwise I'd expect `Content-Length: 0`

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
