### PR TITLE
start-build: remove false alarm warning for repo binary input

### PR DESCRIPTION
**Pull request by wozniakjan**
I was able to create a zip archive that was as little as 183 bytes with valid but very short Dockerfile as the only file, so the peek was too large even for an archive created differently than from git repo and should probably not warn a false alarm

ptal @openshift/sig-developer-experience 
including the conversation for reference https://github.com/openshift/origin/pull/20090

also, I think the magic number for .gz was not completely correct, it had an extra byte (which is used to signal "deflate" compression algorithm but the byte can have different values as well and still denote .gz archive)
RFC for reference: https://tools.ietf.org/html/rfc1952

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/hold
(touches oc so needs to wait for the rebase)

**Comment by wozniakjan** [comment]
/retest

flake https://github.com/openshift/origin/issues/20101

**Comment by wozniakjan** [comment]
/retest

flakes - gcp timing out here as well @stevekuznetsov 
```
extended_builds - Failed, no cause. Check <a href="https://github.com/openshift/origin/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Ftest-flake">the flake issues</a> and add a cause if necessary
extended_conformance_install -  FORWARD PARAMETERS TO THE REMOTE HOST
gcp - {"component":"entrypoint","level":"error","msg":"Process gracefully exited before 15s grace period","time":"2018-06-27T19:41:29Z"}
```

**Pull request merged**
