### PR TITLE
fix kubernetes scheduler long description

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Thanks, [test]

**Comment by guangxuli** [comment]
@smarterclayton  PTAL, the test failure seems another flake.
```

01:24:00 [k8s.io] Service endpoints latency
01:24:00 /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:826
01:24:00   should not be very high [Conformance]
01:24:00   /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/service_latency.go:116
01:24:00 ------------------------------
01:24:00 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
01:24:00 Ran 22 of 702 Specs in 672.804 seconds
01:24:00 SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 680 Skipped Mar 12 01:24:00.874: INFO: Error running cluster/log-dump.sh: fork/exec /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/cluster/log-dump.sh: no such file or directory
01:24:00 PASS
01:24:00 
01:24:00 Ginkgo ran 1 suite in 11m13.450636572s
01:24:00 Test Suite Passed
01:24:00 grep: /tmp/openshift/test-extended/core/logs/openshift.log: No such file or directory
01:24:00 [INFO] Dumping etcd contents to /tmp/openshift/test-extended/core/artifacts/etcd_dump.json
01:24:00 [INFO] Dumping container logs to /tmp/openshift/test-extended/core/logs/containers
01:24:01 grep: /tmp/openshift/test-extended/core/logs/openshift.log: No such file or directory
01:24:01 [INFO] Cleanup complete
01:24:01 [INFO] Exiting
01:24:01 
[ERROR] PID 24674: test/extended/conformance.sh:56: `return $out` exited with status 1.
01:24:01 [INFO] 		Stack Trace: 
01:24:01 [INFO] 		  1: test/extended/conformance.sh:56: `return $out`
01:24:01 [INFO]   Exiting with code 1.
01:24:01 make: *** [test-extended] Error 1
01:24:01 ++ export status=FAILURE
01:24:01 ++ status=FAILURE
01:24:01 + set +o xtrace
01:24:01 
########## FINISHED STAGE: FAILURE: RUN EXTENDED TESTS ##########
01:24:01 Build step 'Execute shell' marked build as failure
01:24:01 [PostBuildScript] - Execution post build scripts.
01:24:01 [workspace@2] $ /bin/bash /tmp/hudson4934852445323633573.sh
01:24:01 ########## STARTING STAGE: DOWNLOAD ARTIFACTS FROM THE REMOTE HOST ##########
01:24:01 + [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install
```

**Comment by pweil-** [comment]
re[test]

**Comment by guangxuli** [comment]
@pweil- test over.

**Comment by pweil-** [comment]
[merge]

**Pull request merged**
