### PR TITLE
update github.com/cockroachdb/cmux for bz1532060

### PR DESCRIPTION
**Pull request by rajatchopra**
For https://bugzilla.redhat.com/show_bug.cgi?id=1532060, github.com/cockroachdb/cmux needs to be updated. Automatic glide update (using hack/update-deps.sh, after editing glide.yaml) checks all dependencies, so one gets to see other parts of vendor directory updated too.

@deads2k Review please.

Thanks.

### CODE REVIEW

**Comment by knobunc** [comment]
@deads: Did we do this correctly?  Do we really want to pull in the changes to other deps just to get this change?

**Comment by deads2k** [comment]
> @deads: Did we do this correctly? Do we really want to pull in the changes to other deps just to get this change?

Yes.  `glide` works by traversing package dependencies to choose repo dependency versions.  Because one dependency change can change the selection criteria for determining all repo dependency levels, you cannot bump a single package.

However, this particular change probably wanted the cleanup from https://github.com/openshift/origin/pull/18419 and without @mfojtik's sync bot running, we have to keep the k8s.io/kubernetes forks up to date

**Comment by rajatchopra** [comment]
Rebased post-  #18419 
Also includes #18463

@deads2k not sure what to do with hack/verify-upstream-commit.sh, help!

**Comment by deads2k** [comment]
make your glide.yaml change in one commit, and the rest of hack/update-deps.sh in a commit called "bump(*)" and you should pass that.

when you see your commit changing files under k8s.io/*, it means we're out of sync.  @mfojtik we needs the bot!

**Comment by deads2k** [comment]
> when you see your commit changing files under k8s.io/*, it means we're out of sync. @mfojtik we needs the bot!

I just manually sync'ed for you.  You can try again.

**Pull request merged**
