### PR TITLE
Bug 1871080: IR-21: Adding tests for image stream imports on blocked/insecure registries

### PR DESCRIPTION
**Pull request by ricardomaraschini**
Adding tests for apiserver image stream import feature. These new tests validate if apiserver behavior is correct when importing from "insecure" and "blocked" registries.

Please don't merge this before merging https://github.com/openshift/openshift-apiserver/pull/111.

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
/hold 

we need to merge https://github.com/openshift/openshift-apiserver/pull/111 prior to this

**Comment by sttts** [comment]
Waiting for a review and lgtm from the team first.

**Comment by ricardomaraschini** [comment]
@dmage green light.

**Comment by ricardomaraschini** [comment]
@dmage This PR was based on a Jira Card, to have a BZ would be strange. Is it possible to bypass this or I need to create a BZ?

**Pull request merged**
