### PR TITLE
Fixes for CRI-O 

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom I have picked your commit from #20325 and added one more fix for image sublayer test.

### CODE REVIEW

**Comment by runcom** [comment]
deployment test is now racing in another path (here: https://github.com/openshift/origin/pull/20359/files#diff-f2c8446f523f5b04af6def6670658089R366). Looks like `oc logs` is too fast to query for logs where (maybe) deployment isn't even started/running. I'll look into this.

**Comment by mrunalp** [comment]
The last run succeeded. Will try again a few times.

**Comment by mrunalp** [comment]
Again succeeded. Kicking off another one.

**Comment by mrunalp** [comment]
Succeeded again.

**Comment by mrunalp** [comment]
Last failure was from termination before it got to the tests.

**Comment by mrunalp** [comment]
Last one succeeded.

**Comment by mrunalp** [comment]
@smarterclayton @runcom This PR carries the commit from #20325 and has been mostly passing when the tests run.

**Comment by smarterclayton** [comment]
Found a bug in ci-operator that was causing failures before

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20359/pull-ci-origin-e2e-gcp-crio/74/

Had one failure

/test gcp-crio

**Comment by mrunalp** [comment]
Last two succeeded. Trying one more.

**Comment by mrunalp** [comment]
Replaced by #20472

**Pull request closed without merging**
