### PR TITLE
Allow userspace or iptables proxy

### PR DESCRIPTION
**Pull request by liggitt**
Related to https://github.com/openshift/origin/issues/6908
Supercedes https://github.com/openshift/origin/pull/6967

### CODE REVIEW

**Comment by liggitt** [comment]
@danwinship rebased, updated upstream code to honor an existing value for the proxy mode
PTAL

**Comment by liggitt** [comment]
[test]

**Comment by dcbw** [comment]
LGTM, though this does change the proxy's ConfigSyncPeriod from 10 minutes -> 15 minutes.  I don't know if we care or not (probably not?)

**Comment by liggitt** [comment]
yeah, I'd rather stay in sync with upstream for default proxy values

**Comment by liggitt** [comment]
I think this is ready, will let the extended networking test run first, though

**Comment by liggitt** [comment]
@dcbw and @marun looked at the extended failures and they match failures in master. [merge]

**Pull request merged**
