### PR TITLE
oc process: show multiple parameter errors where present

### LINKED ISSUE #16496: process should display better structured errors, especially around parameters
```
$ oc process -f /tmp/source BUILD_NAME=test
error: error processing the template "": Template.template.openshift.io "" is invalid: template.parameters[4]: Required value: template.parameters[4]: parameter RPM_REPO_URL is required and must be specified
```

Is terrible.  We should be displaying a better error:

```
error: Unable to process template: parameter RPM_REPO_URL is required and must be specified
```

and we should be displaying all the required values, not just the first one:

```
error: Unable to process template
* parameter BUILD_NAME is required and must be specified
* parameter RPM_REPO_URL is required and must be specified
```

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #16496

### CODE REVIEW

**Comment by jim-minter** [comment]
Sample output:

```
error: unable to process template
  Required value: template.parameters[0]: parameter FOO is required and must be specified
  Required value: template.parameters[1]: parameter BAR is required and must be specified
```

**Comment by jim-minter** [comment]
@smarterclayton this is as far as I think is obviously reasonable to take this - please shout if you think it's not far enough
@bparees fyi (still expecting to have to deal with broken tests)

**Comment by bparees** [comment]
(we'll see if you get lucky but yeah, we probably (hopefully) have cli tests checking for that output)

**Comment by jim-minter** [comment]
@bparees please can you re-lgtm if you're happy with this?

**Pull request merged**
