### PR TITLE
UPSTREAM: 14347: Bump cadvisor godep

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes network stats in Docker >= 1.7
Prometheus metrics improvements

### CODE REVIEW

**Comment by liggitt** [comment]
@kargakis is cadvisor getting bumped with the rebase? @jimmidyson does the version in use by kubernetes have the fix? We want to keep shared godeps in sync with upstream as much as possible

**Comment by kargakis** [comment]
> @kargakis is cadvisor getting bumped with the rebase? @jimmidyson does the version in use by kubernetes have the fix? We want to keep shared godeps in sync with upstream as much as possible

Yes, it does.

**Comment by kargakis** [comment]
https://github.com/kargakis/origin/commit/ee585eaa6f49f632f614a83de54641e7c093f2fc

**Comment by liggitt** [comment]
Never mind, I missed the fact that this was an upstream pull as well. Not sure whether we want the "Upstream" or "bump(dep): ver" type of commit message for this

**Comment by kargakis** [comment]
> Never mind, I missed the fact that this was an upstream pull as well. Not sure whether we want the "Upstream" or "bump(dep): ver" type of commit message for this

I am going to squash the bump commit into the Kube bump commit, keeping it separated now for easier reviewing.

**Comment by liggitt** [comment]
@jimmidyson does the version in use upstream fix the issue, or were there other things added that made you want to bump to HEAD upstream?

**Comment by jimmidyson** [comment]
@liggitt There are a couple of extra bits I personally want, exposing machine & container specs, which are in the new bump. Minor, but useful.

**Comment by liggitt** [comment]
@kargakis what's the timeframe on the rebase? Should we hold all non-critical upstream PRs until it lands?

**Comment by kargakis** [comment]
> @kargakis what's the timeframe on the rebase? Should we hold all non-critical upstream PRs until it lands?

I still have to figure out one or two things so I am not sure. Merging upstream PRs in the meantime is not a problem.

**Comment by kargakis** [comment]
@jimmidyson after the rebase goes in (most probably today), you'll want to rebump cadvisor.

**Comment by jimmidyson** [comment]
@kargakis OK thanks!

**Comment by jimmidyson** [comment]
Closing in preference to another cadvisor bump upstream.

**Pull request closed without merging**
