### PR TITLE
OCPBUGS-39004: Revendor openshift/kubernetes v0.0.0-20240912105924-ce117ff87249

### PR DESCRIPTION
**Pull request by dgoodwin**
From: hack/update-kube-vendor.sh ce117ff87249deb45bf9564d976255645e530105

The latest commit in openshift/kubernetes today.

Doing this to pick up two fixes for https://issues.redhat.com/browse/OCPBUGS-39004 which run from this repo in the case of metal ipv6.

### CODE REVIEW

**Comment by deads2k** [comment]
We need fixes for VAP e2e testing 

/lgtm
/approve

**Comment by dgoodwin** [comment]
/override ci/prow/e2e-gcp-ovn-builds

Couldn't schedule and has passed previously

**Comment by dgoodwin** [comment]
/retest

Unreal...

**Comment by dgoodwin** [comment]
/override ci/prow/e2e-gcp-ovn-builds

Known broken outside this PR

**Comment by dgoodwin** [comment]
/override ci/prow/e2e-gcp-ovn-builds

Known broken outside this PR

**Pull request merged**
