### PR TITLE
Add Monitored Jenkins Templates

### PR DESCRIPTION
**Pull request by waveywaves**
Add Jenkins Templates with ServiceMonitor for App Monitoring enabled
cc @s-urbaniak @akram @gabemontero

### CODE REVIEW

**Comment by adambkaplan** [comment]
@waveywaves if the intent is for this template to be shipped via the samples operator, it should go in https://github.com/openshift/jenkins/tree/master/openshift/templates

**Comment by gabemontero** [comment]
> @waveywaves if the intent is for this template to be shipped via the samples operator, it should go in https://github.com/openshift/jenkins/tree/master/openshift/templates

and subsequently the jenkins entries in https://github.com/openshift/library should be updated to reference this new template

**Comment by akram** [comment]
@adambkaplan and @gabemontero : is it the new default location for the templates/examples ?

about: https://github.com/openshift/library , all the commits seems to be automated and done by a bot. How to commit there? or it is based on what is committed in:  https://github.com/openshift/jenkins/tree/master/openshift/templates ?

**Comment by gabemontero** [comment]
> @adambkaplan and @gabemontero : is it the new default location for the templates/examples ?
> 
> about: https://github.com/openshift/library , all the commits seems to be automated and done by a bot. How to commit there? or it is based on what is committed in: https://github.com/openshift/jenkins/tree/master/openshift/templates ?

I think you sorted it out in your openshift/jenkins PR @akram but just in case I'll elaborate here
- prior to openshift/library, we used to store samples in openshift/origin
- but that got to unwieldy .... and as you may have noticed, there has been a ton or work breaking code out of openshift/origin .... samples are one of those, though some of the old samples had to be left there to facilitate CI .. also, they still serve more than hamper providing users with "doc"
- openshift/library is wired to pull content from all the "samples supplier" repositories ... openshift/jenkins is one of those ... and yes, pull from the branch you mentioned
- products running on top of openshift like scl, eap, etc. contribute to it
- a bot does that periodic reconciliation
- it distinguishes on okd/ocp boundaries, and is set up to deal with HW architectures as well
- the samples operator then periodically pulls in the content from openshift/library, that was in turn pulled from all those other repos by the bot
-

**Comment by akram** [comment]
we can close this PR is favour of https://github.com/openshift/library/pull/191 , right?

**Comment by gabemontero** [comment]
yes

/close

**Pull request closed without merging**
