### PR TITLE
cli: add statefulsets to PodForResource

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/16650

@smarterclayton PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
Lacks a test.

**Comment by mfojtik** [comment]
@kargakis do we have any tests for PodForResource?

**Comment by kargakis** [comment]
This needs a test in ent-to-end since it's fixing cli functionality. Pretty sure we are testing `rsh` and `logs` there.

**Comment by mfojtik** [comment]
@kargakis test added

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/16654

/retest

**Comment by kargakis** [comment]
Awesome, thanks!

/lgtm
/approve

**Comment by smarterclayton** [comment]
Thanks

**Pull request merged**
