### PR TITLE
disallow GC on non-gc-able resources

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/14976

Openshift has many resources which are not handled by GC, this updates their strategies to make sure they don't end up in limbo.

[test]

### CODE REVIEW

**Comment by deads2k** [comment]
opened https://github.com/openshift/origin/issues/14989 to hopefully start proactively finding these.

**Comment by deads2k** [comment]
[severity:blocker]

**Comment by sttts** [comment]
lgtm

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
