### PR TITLE
Bug 1324437: show cancel as subordinate to non-terminating phases

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1324437

@ironcladlou PTAL

### CODE REVIEW

**Comment by ironcladlou** [comment]
LGTM

**Comment by kargakis** [comment]
@pweil- fyi

**Comment by pweil-** [comment]
@kargakis @ironcladlou is this always going to work as expected?  Ie. the case for cancellation is above the case for running so a deployment may still be running but marked as cancelled and will show as cancelled in the describer.  Not sure if that is the desired state or if there is a better display of "running but marked for cancellation" that is more accurate AND a state of "cancelled (not running)".

**Comment by kargakis** [comment]
> @kargakis @ironcladlou is this always going to work as expected? Ie. the case for cancellation is above the case for running so a deployment may still be running but marked as cancelled and will show as cancelled in the describer. Not sure if that is the desired state or if there is a better display of "running but marked for cancellation" that is more accurate AND a state of "cancelled (not running)".

Eventually, a deployment marked as cancelled should transition to failed. By the time it is marked as cancelled, we want it to show up as cancelled even though the underlying phase is "Running".

**Comment by ironcladlou** [comment]
There's a bit of a disconnect here since it sort of conflates phase with "cancelled" (not a phase). Cancelled seems to imply a terminal state, but really cancelled is a condition which may ultimately persist through the terminal phase "Failed" or may be cleared if the terminal phase "Completed" is entered...

**Comment by pweil-** [comment]
@smarterclayton thoughts on the presentation of this before giving approval?  It does seem like this can cause some confusion.  I think there are two options:

1.  present cancelled (or cancelling) as a psuedo-phase that will transition to Cancelled (with the real underlying phase of Failed) or Completed (if best effort cancel fails)
2.  present the real phase with a snippet that cancellation is being attempted (ie. Running (Cancelling))

In both cases the web ui definitely needs to match the cli.

**Comment by ironcladlou** [comment]
To clarify what I think makes logical sense given the use of phase today, I think these are the three possible states that are consistent and users could see:

Cancelling (condition) + Running (phase)
Cancelled (condition) + Failed (phase)
Completed (phase)

**Comment by smarterclayton** [comment]
Since user's can't un-cancel, cancellation is a modifier to a phase (a condition as Dan notes).  The phase is most important, the cancellation should be presented subordinate to it.

**Comment by kargakis** [comment]
Updated to:
```
$ oc deploy database --latest; oc deploy database --cancel; oc deploy database
Started deployment #2
Cancelled deployment #2
database deployment #2 pending (cancelling) 1 seconds ago
database deployment #1 deployed 22 minutes ago - 1 pod
```
Also updated the changes from https://github.com/openshift/origin/pull/8357 to:
```
$ oc deploy database --latest; oc deploy database --cancel; oc deploy database --cancel
Started deployment #3
Cancelled deployment #3
No deployments are in progress (latest deployment #3 pending (cancelling) less than a second ago)
```

**Comment by pweil-** [comment]
new messages LGTM.  Approving for 1.2 blocker bug 1324437 - resolves CLI and web UI message inconsistency.

**Comment by pweil-** [comment]
[test]

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
