### PR TITLE
test/extended: Remove the failure allowed logic in the cluster topology SNO test

### PR DESCRIPTION
**Pull request by timflannagan**
Update the test/extended/single_node/topology.go single-node validation
logic that allows the PackageServer Deployment resource to be more than
one replica when running tests.

OLM will be moving that component from the CVO payload to a second-level
Operator that reads the Infrastructure cluster singleton resource and
propagates the HA/non-HA expectations to the PackageServer CSV resource.

### CODE REVIEW

**Comment by timflannagan** [comment]
Blocked until https://github.com/openshift/operator-framework-olm#99 merges.

/hold

**Comment by timflannagan** [comment]
The linked PR has merged - removing the hold.

/test all
/hold cancel

**Comment by bparees** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

one of these times it'll make it....

**Pull request merged**
