### PR TITLE
Support oc tag to add alias of ImageStreamTag in the same ImageStream

### PR DESCRIPTION
**Pull request by nak3**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1514907

oc tag: Support oc tag to add alias of ImageStreamTag

Current `oc tag` command allows only `<name>:<tag>` format to add tag
from ImageStreamTag source. Due to this, if users want to create an
alias of ImageStreamTag in same ImageStream by `oc tag <tag> --alias` 
after omitting the name,  they encounter following validation error:

```
# oc tag registry.access.redhat.com/rhscl/perl-520-rhel7:latest perl:latest --source=docker
# oc tag perl:latest perl:5.20 --source=istag 
# oc tag 5.20 perl:latest --source=istag --alias
error: --source=ImageStreamTag requires a valid <name>:<tag> in SOURCE
```
Note, these command could create this
[ImageStream](https://gist.githubusercontent.com/nak3/223bf3bd7d59bfcc6eb63fa981a691ba/raw/c4705d82157c72caf13f91c4540bd504c965b47c/perl_imagestream.yaml)
and we know that it is possible to create this ImageStream(Tags) by
`oc create -f`.

This patch removes the validation check of <name>:<tag> only when
`--alias` specified and allow users to create ImageStreamTag alias in
the same ImageStream by `oc tag`.

### CODE REVIEW

**Comment by nak3** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1514907

**Comment by juanvallejo** [comment]
@nak3 Thanks for the PR! Could you add a small test if possible please?

**Comment by nak3** [comment]
@juanvallejo Sure, I have added it.

**Comment by fabianofranz** [comment]
/approve
@bparees PTAL

**Comment by bparees** [comment]
@nak3 I don't understand why running `oc tag perl:5.20 perl:latest --source=istag --alias` isn't the correct solution to this problem?

the source for an "oc tag" operation is an imagestreamtag, not just a "tag".

/hold

**Comment by bparees** [comment]
(and if we were going to do anything here, which i'm not in support of, i would expect the new behavior to be `oc tag existing:tag newtag --alias`, that is you would fully qualify the name of the source imagestreamtag, and then only provide the new tag name as the destination, not the other way around).

**Comment by nak3** [comment]
Unfortunately, `oc tag perl:5.20 perl:latest --source=istag --alias` is not what I expected. I would like to make a ImageStream(Tags) like [0] and displays the tag as `5.20 (latest)`. It is same way of making the tag in default `openshift` namespace and this [ImageStream](https://gist.githubusercontent.com/nak3/223bf3bd7d59bfcc6eb63fa981a691ba/raw/c4705d82157c72caf13f91c4540bd504c965b47c/perl_imagestream.yaml)

[0]
~~~
$ oc describe is perl -n openshift
Name:			perl
Namespace:		openshift
Created:		6 weeks ago
Labels:			<none>
Annotations:		openshift.io/display-name=Perl
			openshift.io/image.dockerRepositoryCheck=2017-10-16T06:42:04Z
Docker Pull Spec:	172.30.106.110:5000/openshift/perl
Unique Images:		2
Tags:			3

5.20 (latest)
  tagged from registry.access.redhat.com/rhscl/perl-520-rhel7:latest

  Build and run Perl 5.20 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-perl-container/blob/master/5.20/README.md.
  Tags: builder, perl
  Supports: perl:5.20, perl
  Example Repo: https://github.com/openshift/dancer-ex.git

  * registry.access.redhat.com/rhscl/perl-520-rhel7@sha256:91ff6c9dd3f7701cb4dce9bf857f81ab3f2d5950dbe77008ce9ee62dc9e6005c
      6 weeks ago
~~~

Please also note that the command you suggested will display the ImageStream on webconsole as:

wrong

Expected display is this:

correct

Is there a way to make ImageStream like this, without `# oc tag 5.20 perl:latest --source=istag --alias`?

**Comment by bparees** [comment]
@nak3 
what is `oc tag perl:5.20 perl:latest --source=istag --alias` giving you?

**Comment by nak3** [comment]
Here is the output:

~~~
$ oc tag registry.access.redhat.com/rhscl/perl-520-rhel7:latest perl:latest --source=docker
$ oc tag perl:latest perl:5.20 --source=istag --alias
~~~

result: https://paste.fedoraproject.org/paste/lgD2oYvefRKWNLjQZhuBhQ/raw

~~~
$ oc tag registry.access.redhat.com/rhscl/perl-520-rhel7:latest perl:latest --source=docker
$ oc tag perl:5.20 perl:latest --source=istag --alias
~~~

result: https://paste.fedoraproject.org/paste/qLh7gDKMjXXAef3wGhjCJw/raw

**Comment by bparees** [comment]
i think --reference might be what you want (instead of --alias).  can you try that?

**Comment by bparees** [comment]
ignore my previous (deleted) comment.

**Comment by bparees** [comment]
```
oc tag registry.access.redhat.com/rhscl/perl-520-rhel7:latest perl:5.20 --source=docker
oc tag perl:5.20 perl:latest --source=istag --alias
```

should get you the equivalent to:
https://gist.githubusercontent.com/nak3/223bf3bd7d59bfcc6eb63fa981a691ba/raw/c4705d82157c72caf13f91c4540bd504c965b47c/perl_imagestream.yaml
```
spec:
  tags:
  - annotations:
      version: "5.20"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/perl-520-rhel7:latest
    generation: 2
    importPolicy: {}
    name: "5.20"
  - annotations:
      version: "latest"
    from:
      kind: ImageStreamTag
      name: "5.20"
    generation: 1
    importPolicy: {}
    name: latest
```


you can see that your existing paste is pretty much the same except you inverted which is the "real" tag and which is the "alias" tag:
https://paste.fedoraproject.org/paste/lgD2oYvefRKWNLjQZhuBhQ/raw
```
spec:
  tags:
  - annotations: null
    from:
      kind: ImageStreamTag
      name: perl:latest
    generation: 3
    importPolicy: {}
    name: "5.20"
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/perl-520-rhel7:latest
    generation: 2
    importPolicy: {}
    name: latest
```

**Comment by nak3** [comment]
This commands:

~~~
oc tag registry.access.redhat.com/rhscl/perl-520-rhel7:latest perl:5.20 --source=docker
oc tag perl:5.20 perl:latest --source=istag --alias
~~~

will never display as `5.20 (latest)` by `oc describe is perl`, because it has the from.kind: ImageStreamTag as `perl:5.20` not `5.20`

~~~
  - annotations: null
    from:
      kind: ImageStreamTag
      name: perl:5.20
~~~

I'm sorry for my repeat, but let me summarize the points:

- [0] is the expectation, currently just [1] is possible. (Please see`5.20 (latest)`).
- `openshift` namespace creates the imagestream as expected display like [0] by default.
- It is possible to create by `oc create -f ` with this [ImageStream](https://gist.githubusercontent.com/nak3/223bf3bd7d59bfcc6eb63fa981a691ba/raw/c4705d82157c72caf13f91c4540bd504c965b47c/perl_imagestream.yaml), but only `oc tag` cannot.

[0] expected
~~~
$ oc describe is perl -n openshift
Name:			perl
Namespace:		openshift
Created:		6 weeks ago
Labels:			<none>
Annotations:		openshift.io/display-name=Perl
			openshift.io/image.dockerRepositoryCheck=2017-10-16T06:42:04Z
Docker Pull Spec:	172.30.106.110:5000/openshift/perl
Unique Images:		2
Tags:			3

5.20 (latest)
  tagged from registry.access.redhat.com/rhscl/perl-520-rhel7:latest

  Build and run Perl 5.20 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-perl-container/blob/master/5.20/README.md.
  Tags: builder, perl
  Supports: perl:5.20, perl
  Example Repo: https://github.com/openshift/dancer-ex.git

  * registry.access.redhat.com/rhscl/perl-520-rhel7@sha256:91ff6c9dd3f7701cb4dce9bf857f81ab3f2d5950dbe77008ce9ee62dc9e6005c
      6 weeks ago
~~~

[1] `oc tag perl:5.20 perl:latest --source=istag --alias`
~~~
# oc describe is perl
Name:			perl
Namespace:		demo
Created:		36 seconds ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2017-11-29T03:00:40Z
Docker Pull Spec:	172.30.106.110:5000/demo/perl
Unique Images:		1
Tags:			2

latest
  tagged from perl:5.20

  ~ importing latest image ...
  * registry.access.redhat.com/rhscl/perl-520-rhel7@sha256:d0b7011aa1a7e961d96388ec062a0b3a03ff8e0e3225f7290f36ab8316724420
      28 seconds ago

5.20
  tagged from registry.access.redhat.com/rhscl/perl-520-rhel7:latest

  * registry.access.redhat.com/rhscl/perl-520-rhel7@sha256:d0b7011aa1a7e961d96388ec062a0b3a03ff8e0e3225f7290f36ab8316724420
      28 seconds ago
~~~

**Comment by nak3** [comment]
(I updated previous comment, but it is not different just add `cf. exepected` to make it more clear.)

**Comment by bparees** [comment]
@nak3 that sounds like something that should be fixed in the describer (it should recognize the from imagestream is itself).

**Comment by nak3** [comment]
@bparees

I thought so once. However, [the expected ImageStream](https://gist.githubusercontent.com/nak3/223bf3bd7d59bfcc6eb63fa981a691ba/raw/c4705d82157c72caf13f91c4540bd504c965b47c/perl_imagestream.yaml) is possible to create by `oc create`, but only `oc tag` fails due to its validation check. Can you address this?

**Comment by bparees** [comment]
that doesn't make oc tag's behavior wrong.  there are plenty of things you can do via oc create that you can't do via specialized oc commands.

there is no functional difference between a tag with a fully qualified reference and one without, the only difference is in how oc describe is displaying them.  thus the simplest effective change is to oc describe, not oc tag.

**Comment by nak3** [comment]
Thank you. I understand. Closing this PR as webconsole will fix the issue https://github.com/openshift/origin-web-catalog/pull/574

**Pull request closed without merging**
