### PR TITLE
[DO NOT MERGE] UPSTREAM: 34028: add `--dry-run` flag to `oc apply`

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/34028

Fixes: #11152
Related StackOverflow:
http://stackoverflow.com/questions/38824409/validate-openshift-objects-defined-in-yaml-before-actually-applying-or-executing

This patch adds a `--dry-run` flag to the `apply` command in order to
allow validation of objects, without actually creating them. If a
`--dry-run` flag is present and no validation errors are found, the
command will exit before sending the objects to the server.

cc @openshift/cli-review @soltysh

### CODE REVIEW

**Comment by ncdc** [comment]
Is there an upstream kube PR for this?

**Comment by ncdc** [comment]
Retitling [DO NOT MERGE] for now

**Comment by ncdc** [comment]
Is there a Trello card for this? This seems like something we'd pick up in a rebase, not something we'd backport.

**Comment by soltysh** [comment]
I agree with Andy here, it's not something super important to have asap, it's rather a nice to have feature, but we're ok to pick it up during next rebase to k8s.

**Comment by juanvallejo** [comment]
@ncdc @soltysh Thanks for the feedback, I'll go ahead and close this PR. [Do you have any more thoughts on the upstream PR](https://github.com/kubernetes/kubernetes/pull/34028)?

**Pull request closed without merging**
