### PR TITLE
Bug 1700279: UPSTREAM: 92442 Respect grace period when removing mirror pod

### PR DESCRIPTION
**Pull request by tedyu**
This PR is based on #92442 upstream.

I have tested this PR on patched 4.5 cluster.

This PR also contains Sam's e2e DR test. I use the combination to verify etcd DR behavior.

### CODE REVIEW

**Comment by hexfusion** [comment]
> fail [github.com/openshift/origin/test/extended/dr/quorum_restore.go:167]: Unexpected error:

This would be where I would expect the failure to show itself.

**Comment by tedyu** [comment]
Looking at masters-journal, the grace period for etcd pod was fulfilled:
```
Jun 23 03:42:08.734274 ip-10-0-128-70 hyperkube[1341]: I0623 03:42:08.733618    1341 pod_manager.go:267] terminating pod with grace period 30 for "etcd-ip-10-0-128-70.us-east-2.compute.internal_openshift-etcd" : expires at 2020-06-23 03:42:38.733613966 +0000 UTC m=+2178.196492866
...
Jun 23 03:43:04.512759 ip-10-0-128-70 hyperkube[1341]: I0623 03:43:04.512539    1341 kubelet_pods.go:1059] "etcd-ip-10-0-128-70.us-east-2.compute.internal_openshift-etcd" has passed the grace period 2020-06-23 03:42:38.733613966 +0000 UTC m=+2178.196492866
Jun 23 03:43:04.512759 ip-10-0-128-70 hyperkube[1341]: I0623 03:43:04.512565    1341 mirror_client.go:124] Deleting a mirror pod "etcd-ip-10-0-128-70.us-east-2.compute.internal_openshift-etcd" (uid (*types.UID)(nil))
```

**Comment by sjenning** [comment]
need a colon after the PR number

**Comment by tedyu** [comment]
@sjenning 
commit message has been corrected.

**Comment by rphillips** [comment]
/lgtm
/hold

Just holding for the upstream PR to merge

**Pull request closed without merging**
