### PR TITLE
Fix the Vagrant network setup

### PR DESCRIPTION
**Pull request by lhuard1A**
The Vagrantfile configures the machines with:

    master_ip = "10.245.1.2"
    minion_ip_base = "10.245.2."

The issue is that, by default, Vagrant uses a netmask of 255.255.255.0.
With that netmask, Vagrant considers that the master and the minions are on
two distinct subnets and so, creates two distinct private networks.
This prevents the master and the minions from communicating between each other.

By explicitly forcing the netmask to be 255.255.0.0, Vagrant will create a
single private network for the master and the minions which will be able
to communicate.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@rajatchopra please review

**Comment by rajatchopra** [comment]
The other option is to bring the master ip within the /24 mask.
Its probably better to have the master setup as 10.245.2.1 than expand the netmask.

@lhuard1A Do you see any issues with the above option?

**Comment by derekwaynecarr** [comment]
I would love to see an e2e test that validates this stuff works, and that the e2e test adds a scenario to ensure that a container in a pod can hit the public internet.

**Comment by derekwaynecarr** [comment]
But we can do that in a later PR.

**Comment by lhuard1A** [comment]
@rajatchopra : Vagrant complains when trying to use 10.245.2.1 for the master:
==> master: You assigned a static IP ending in ".1" to this machine.
==> master: This is very often used by the router and can cause the
==> master: network to not work properly. If the network doesn't work
==> master: properly, try changing this IP.

So, I used 10.245.2.2 for the master and 10.245.2.3 and onwards for the minions. Things are now working with the default /24 netmask.

**Comment by rajatchopra** [comment]
LGTM
Thanks Lenaic.
[merge]

**Pull request merged**
