### PR TITLE
Update to etcd v2.2.2

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
Clean test run:
continuous-integration/openshift-jenkins/test SUCCESS (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8026/)
Hijacking to see if this cleans up our etcd retry flakes... [test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge], but Im' going to update to v2.2.4 after this

**Comment by liggitt** [comment]
> I'm going to update to v2.2.4 after this

can you pair that with an upstream PR to bump them to 2.2.4 for the packages they import?

**Comment by smarterclayton** [comment]
Yeah, once i sort out the transitivee dependency mess.

**Pull request merged**
