### PR TITLE
Allow patching events

### LINKED ISSUE #5315: Server rejected node event displayed during test execution
Not sure why this is being logged.  Triggered by running

    TEST_ONLY=1 test/extended/core.sh -focus='create a functioning NodePort service' -v -trace

```
E1022 04:48:55.595128    4937 event.go:198] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"webserver-omc9n.140f68dfbd41a22b", GenerateName:"", Namespace:"e2e-tests-services-oo1a1", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-services-oo1a1", Name:"webserver-omc9n", UID:"213a862a-7878-11e5-8630-080027c5bfa9", APIVersion:"v1", ResourceVersion:"280", FieldPath:"spec.containers{webserver}"}, Reason:"Pulled", Message:"Container image \"gcr.io/google_containers/test-webserver\" already present on machine", Source:api.EventSource{Component:"kubelet", Host:"openshiftdev.local"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581086135, nsec:592330427, loc:(*time.Location)(0x4a07d00)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581086135, nsec:592330427, loc:(*time.Location)(0x4a07d00)}}, Count:2}': 'User "system:node:openshiftdev.local" cannot "patch" "events" with name "webserver-omc9n.140f68dfbd41a22b" in project "e2e-tests-services-oo1a1"' (will not retry!)
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5315

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k

**Comment by deads2k** [comment]
Why would I ever want to update or patch an event?  I would expect those to be immutable.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/15268/files

**Comment by deads2k** [comment]
I still think its weird, but that's the right permission.  [merge]

**Pull request merged**
