### PR TITLE
fix swapped format args and fix ruby version checking

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/19241

### CODE REVIEW

**Comment by wozniakjan** [comment]
/lgtm

@bparees the args to `Logf` were definitely in a wrong order, but when I look at the test logs, it does look like it failed in the next code block timeouting getting the logs, doesn't it?

**Comment by bparees** [comment]
I've realized the code actually was already checking if the err was PodCompleted.

**Pull request merged**
