### PR TITLE
UPSTREAM: 50934: Skip non-update endpoint updates

### PR DESCRIPTION
**Pull request by sjenning**
xref https://github.com/kubernetes/kubernetes/pull/50934 and https://github.com/kubernetes/kubernetes/pull/51144
master PR:
https://github.com/openshift/origin/pull/15888

xref https://bugzilla.redhat.com/show_bug.cgi?id=1481603

@joelsmith @derekwaynecarr @eparis @smarterclayton

### CODE REVIEW

**Comment by joelsmith** [comment]
I'll look in the morning to see if the failure is a flake or legitimate. But in case it's a flake, I'm running it again.
/test extended_conformance_gce

**Comment by sjenning** [comment]
Flake https://github.com/openshift/origin/issues/15941

**Comment by sjenning** [comment]
/retest

also @derekwaynecarr misspelled "lgtm" in the bot message :stuck_out_tongue:

**Comment by joelsmith** [comment]
Did we decide to leave this unmerged for now? I thought that maybe we had decided to keep it off of the 3.6 branch until it had more soak time upstream and in master, so maybe it's good that he misspelled "lgtm". That being said, I am interested in seeing what impact this has on https://bugzilla.redhat.com/show_bug.cgi?id=1481603 and we won't really know until the OpenShift Online free tier gets a 3.6 update with this in it (or when they go to 3.7).

**Comment by sjenning** [comment]
@joelsmith ah indeed. So many of these 3.6 PRs; got a little punchy :smile:

Wonder if bot understands
/do-not-merge

Waiting on master and upstream kube soak before including in 3.6

@derekwaynecarr @smarterclayton how long we want to let this soak?  Are we pushing this to 3.6.2+?

**Comment by sjenning** [comment]
integration test seems to be doing better now.  still flaking but not every time now.
/retest

**Comment by sjenning** [comment]
waiting for https://github.com/openshift/origin/pull/16336 to fix integration test

**Comment by joelsmith** [comment]
hopefully now that #16336 is merged, the test will pass.
/retest

**Pull request merged**
