### PR TITLE
Delete registry interfaces for clusternetwork/hostsubnet/netnamespace resources

### PR DESCRIPTION
**Pull request by pravisankar**
We do not use registry interfaces for these resources.

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by knobunc** [comment]
LGTM.  Thanks Ravi.

**Comment by pravisankar** [comment]
re[test]

**Comment by danwinship** [comment]
tests are broken right now, but not related to this change
[merge]

**Pull request merged**
