### PR TITLE
Fix prioritizing of semver equal tags

### LINKED ISSUE #14080: "Unable to resolve" imagestreams when using specific semantic versioning format
This took a while to figure out but I'm not sure if this goes against Docker tag naming conventions or if this is an issue with OpenShift. 

##### Version
OpenShift Master:
v1.5.0+031cbe4
Kubernetes Master:
v1.5.2+43a9be4

##### Steps To Reproduce
1. Run the following commands:
`oc tag --source=docker docker.io/php:7.1 openshift/phptest:7.1`
`oc tag --source=docker docker.io/php:7.1.0 openshift/phptest:7.1.0`
2. Visit `/console/project/openshift/browse/images/phptest`

##### Current Result
Lots of errors - "Unable to resolve" and the imagestream doesn't work.

There is also a frequent re-sorting of the list via javascript.

##### Expected Result
Both imagestream tags work as expected

##### Additional Information
It seems that OpenShift, for some reason, is having trouble differentiating "7.1" from "7.1.0" and bad things happen. If you were to replace "7.1.0" with "7.1.4" above, there isn't an issue.

My specific example is that we have a "2.3" image, which means it will be tagged with the latest 2.3 patch version. Then we also have a "2.3.0" image which means it will be tagged with the initial release of 2.3.

I thought Docker tags were arbitrary and didn't have any rules based on versioning so maybe this is a bug.

### PR DESCRIPTION
**Pull request by dmage**
Fixes #14080

### CODE REVIEW

**Comment by dmage** [comment]
[test]

**Comment by dmage** [comment]
Flake #14236, re[test].

**Comment by soltysh** [comment]
LGTM
[merge]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/13943
[merge[

**Comment by legionus** [comment]
@soltysh typo :)
[merge]

**Pull request merged**
