### PR TITLE
Update travis to go 1.5.1

### PR DESCRIPTION
**Pull request by mfojtik**
See:

https://github.com/kubernetes/kubernetes/pull/12967#issuecomment-143511934

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by kargakis** [comment]
LGTM

**Comment by mfojtik** [comment]
want to see travis pass :)

**Comment by mfojtik** [comment]
@smarterclayton shouldn't we use "release" travis target for Go instead of "1.5.1" ? So we know if we are broken on the latest released Go.

**Comment by smarterclayton** [comment]
The problem is that broke all the time.  We should matrix our build test
onto 1.5.x latest for sure, but tip isn't stable.

**Comment by mfojtik** [comment]
@smarterclayton OK, then I think this PR is correct. I'll merge this and wait for //github.com/openshift/origin/pull/4889/files#diff-4fec64726d924692feaa6853d4609b5dR22 to fix the policy cache race.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
