### PR TITLE
UPSTREAM: 31881: 36140 update kubernetes public function to get docker auth

### PR DESCRIPTION
**Pull request by guangxuli**
**what this PR does:**

https://github.com/kubernetes/kubernetes/pull/36140
https://github.com/kubernetes/kubernetes/pull/31881

Through using two PR's public invocation of kubernetes, I can fix the PR https://github.com/openshift/origin/pull/10608 which have blocked so long time, and now I have completed the code in my local by using newest public invocation.  After merge this PR I will push my new modification for PR https://github.com/openshift/origin/pull/10608. 

@liggitt @bparees

### CODE REVIEW

**Comment by pweil-** [comment]
should hold for the in-progress rebase

**Comment by bparees** [comment]
@pweil- who's doing the rebase?  can we assign this to them?  (and if these changes are already in the rebase, close this.. though they probably aren't since i think these changes just merged upstream)

**Comment by pweil-** [comment]
> who's doing the rebase? can we assign this to them?

@ncdc and yes.  Current PR is https://github.com/openshift/origin/pull/12143 and was started 3 days ago so this wouldn't be included

**Comment by liggitt** [comment]
The use is low priority enough that we should wait to pick the upstream function up in 1.6

**Pull request closed without merging**
