### PR TITLE
bump(github.com/openshift/source-to-image): 5741384e376d9c61b5b361560…

### PR DESCRIPTION
**Pull request by PI-Victor**
this is the bump to fix the engine-api dependency problem that we currently have.
[test]

@bparees

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
@jim-minter @PI-Victor looks like there's an additional godep dependency being introduced here that origin doesn't meet?

```
++ Building go targets for linux/amd64: cmd/openshift cmd/oc pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
vendor/github.com/openshift/source-to-image/pkg/docker/util.go:16:2: cannot find package "github.com/docker/docker/cliconfig" in any of:
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/docker/cliconfig (vendor tree)
	/usr/lib/golang/src/github.com/docker/docker/cliconfig (from $GOROOT)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/docker/docker/cliconfig (from $GOPATH)
```

**Comment by jim-minter** [comment]
Correct, @PI-Victor you'll need to include github.com/docker/docker/cliconfig - but the good news is that it's at the same git checkout version as the other stuff in github.com/docker/docker.

**Comment by PI-Victor** [comment]
@bparees @jim-minter 
i did this manually and i hope i got it right. went to docker at head b9f10c951893f9a00865890a5232e85d770c1087 copied the cliconfig dir and the homedir dir over to the vendor folder in origin. 
split it into two commits and also added the s2i bump, which wants the vendor cliconfig and homedir at the same HEAD as mentioned above. seems to be working but i'm afraid i missed something, can you please double check?

**Comment by PI-Victor** [comment]
on second thought, since homedir is a dep for cliconfig, should it be in a separate commit bump, after all?

**Comment by jim-minter** [comment]
Hi @PI-Victor, there should be no need to include vendor/github.com/docker/docker/cliconfig/credentials/..., this is a separate package.  Please could you remove those files from your commit?

**Comment by PI-Victor** [comment]
@jim-minter removed, thanks!

**Comment by bparees** [comment]
running image ecosystem only to see if the ruby tests still fail, only remaining failures from last run were:
```
    Extended.[image_ecosystem][Slow] openshift sample application repositories [image_ecosystem][ruby] test ruby images with rails-ex db repo Building rails-postgresql app from new-app should build a rails-postgresql image and run it in a pod
    Extended.[image_ecosystem][ruby][Slow] hot deploy for openshift ruby image Rails example should work with hot deploy
```
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
going to assume the remaining failures are due to rails5 changes.  @coreydaley can you look into them? (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/763/#showFailuresLink)

[merge]

**Comment by coreydaley** [comment]
@bparees looking

**Comment by coreydaley** [comment]
@bparees opened pull request https://github.com/openshift/rails-ex/pull/67 which will fix this issue

**Comment by PI-Victor** [comment]
awesome, thanks for the help!

**Pull request merged**
