### PR TITLE
Bug 1190577 - Failed to parse port when generate an application list code with a dockerfile which expose multiple ports

### PR DESCRIPTION
**Pull request by csrwng**
Generate: handle image with multiple ports in EXPOSE statement

### CODE REVIEW

**Comment by smarterclayton** [comment]
Test case

**Comment by csrwng** [comment]
test case provided

**Comment by smarterclayton** [comment]
gofmt flagged you

**Comment by csrwng** [comment]
Fixed gofmt

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
