### PR TITLE
Bug 1899721: HPA: Ignore deleted pods.

### PR DESCRIPTION
**Pull request by joelsmith**
xref kubernetes#95560

### CODE REVIEW

**Comment by rphillips** [comment]
/hold

we need to get this into master and 4.6 first.

**Comment by rphillips** [comment]
/hold cancel

we did :)

**Comment by joelsmith** [comment]
Here are the master and 4.6 PRs: 
https://github.com/openshift/kubernetes/pull/462
https://github.com/openshift/kubernetes/pull/465

**Pull request merged**
