### PR TITLE
remove dead handlers and move specific handlers to point of use

### PR DESCRIPTION
**Pull request by deads2k**
This moves code to its point of use and removes handlers we no longer use.  We're starting to look pretty tidy.

### CODE REVIEW

**Comment by deads2k** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18273/test_pull_request_origin_extended_conformance_install/6335/

```
              Some dependencies are required in order to check Docker image availability.
               Unable to install required packages on this host:
                   python-docker-py,
                   skopeo
               Error: Package: 1:skopeo-0.1.26-2.dev.git2e8377a.el7.x86_64 (oso-rhui-rhel-server-extras)
                          Requires: skopeo-containers = 1:0.1.26-2.dev.git2e8377a.el7
```

@sdodson @stevekuznetsov known problem?

**Comment by stevekuznetsov** [comment]
Fixed now

**Pull request merged**
