### PR TITLE
Add server-side column printer support for openshift objects

### PR DESCRIPTION
**Pull request by liggitt**
We never hooked up openshift storage to act as table printers to support server-side printing in 3.10

If we want to drop client-side printing in 3.11, this is required.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @spadgett @soltysh @smarterclayton

**Comment by liggitt** [comment]
@openshift/sig-master

**Comment by soltysh** [comment]
> If we want to drop client-side printing in 3.11, this is required.

We're not dropping it, we're just enabling it by default in 3.11, but still leave the functionality in place.

**Pull request merged**
