### PR TITLE
Bug 1248463 - fixes exec help

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[merge]

**Comment by deads2k** [comment]
@fabianofranz is this a case of drift?  If so, can we build a unit test to catch drift on these?

**Comment by rhcarvalho** [comment]
Hi @fabianofranz! Are these JSON files added here needed?

**Comment by fabianofranz** [comment]
@rhcarvalho yikes no.

**Pull request merged**
