### PR TITLE
upstream machinery picks

### PR DESCRIPTION
**Pull request by deads2k**
1. track schemes by name so we know which scheme is failing
2. only ignore events for GC and quota

both are lgtm'd upstream

### CODE REVIEW

**Comment by liggitt** [comment]
do we need both of these ahead of 1.11.1?

**Comment by deads2k** [comment]
> do we need both of these ahead of 1.11.1?

I could pull the second one if you wanted.  I really need that scheme naming to move the separate scheme stuff ahead.  Now that both work, why not?

**Comment by liggitt** [comment]
ok

/lgtm

**Pull request merged**
