### PR TITLE
expose: Allow specifying a hostname when generating routes

### LINKED ISSUE #2670: osc expose needs to add host option and the doc needs fixing
the osc expose command should allow me to add the host in the command. For example:
osc expose apache -h www.example.com 

should add the following metadata to the route

"spec": {
                "host": "www.example.com",
                "to": {
                    "kind": "Service",
                    "name": "apache"
                },

There is also some issues with the current doc. 

The doc says port is required 
"      --port=-1: The port that the service should serve on. Required."

but in the two examples you give there are no ports listed

"Examples:
// Create a route based on service nginx. The new route will re-use nginx's labels.
$ osc expose service nginx

// Create a route and specify your own label.
$ osc expose service nginx --labels name=myroute
"

Does the "port the service should serve on" have to match the port exposed by the service, or will the route take something coming in on a different port and then send it to the listening port for a service?

Should this say route rather than service?
" --name='': The name for the newly created service."

These two are not clear just from reading the help but I think that is because I need to read more in depth documentation about Load Balancers and routes. Does documentation exist for the concepts discussed here?
"--create-external-load-balancer=false: If true, create an external load balancer for this service (trumped by --type). Implementation is cloud provider dependent. Default is 'false'.
"
 "--type='': Type for this service: ClusterIP, NodePort, or LoadBalancer. Default is 'ClusterIP' unless --create-external-load-balancer is specified."

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #2670 

@smarterclayton @pweil- PTAL

@thesteve0 @sosiouxme fyi

### CODE REVIEW

**Comment by kargakis** [comment]
Unfortunately I was getting a weird shorthand collision with the shorthand -h flag so only --hostname for now.

**Comment by sosiouxme** [comment]
Should there be at least some validation that the string given could be a hostname? So people find out early on that 'https://foo.example.com:8443' isn't a valid hostname.

Otherwise, w00t, thanks!

**Comment by liggitt** [comment]
doesn't API validation catch the error and prevent the route creation?

**Comment by pweil-** [comment]
if the host name is set it will use the IsDNS1123Subdomain check

**Comment by liggitt** [comment]
Are there any other consequences to route creation failing on API validation, like prior objects getting created and needing to be cleaned up? I'd rather defer to API validation in almost every case

**Comment by smarterclayton** [comment]
Clients should not be validating, the API should be.

----- Original Message -----

**Comment by kargakis** [comment]
> Unfortunately I was getting a weird shorthand collision with the shorthand -h flag so only --hostname for now.

Ok, it's not that weird, -h is used for help.

**Comment by kargakis** [comment]
@bparees fyi

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
