### PR TITLE
Remove npm shrinkwrap by bumping html-min deps

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
tests passed, merging to unblock queue

**Comment by spadgett** [comment]
@jwforres seeing a bindata diff when I build assets on master now.

```diff
diff --git a/pkg/assets/bindata.go b/pkg/assets/bindata.go
index a0897aa..4ca428c 100644
--- a/pkg/assets/bindata.go
+++ b/pkg/assets/bindata.go
@@ -5766,7 +5766,7 @@ a.$apply(function() {
 b.url(d);
 });
 }), a.$on("project.settings.update", function(a, b) {
-h[b.metadata.name] = b, k();
+f[b.metadata.name] = b, k();
 });
 }
 };
```

Looks like #7571 might have merged just before this PR.

**Comment by jwforres** [comment]
Jenkins had a number of passes after that, are you seeing it in Jenkins or
locally? If it's local maybe try updating your npm to 3.7.3?

**Comment by jwforres** [comment]
Ah just saw failure in merge queue, ok

**Comment by spadgett** [comment]
Hm, I noticed it was the same diff that caused #7475 to fail.

I am using npm 3.7.5.

**Comment by jwforres** [comment]
Ahh yep I see what happened, Ben's PR's merge test was launched from the
ami before the npm version was updated so it passed and finished after I
started the test of this one.

**Pull request merged**
