### PR TITLE
allow build request override of pipeline strategy envs

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/devex fyi

### CODE REVIEW

**Comment by bparees** [comment]
we should probably have a test that covers this.  (I suspect we do have ones that cover the other strategies already).

**Comment by gabemontero** [comment]
On Tue, Feb 28, 2017 at 5:58 PM Ben Parees <notifications@github.com> wrote:

> we should probably have a test that covers this. (I suspect we do have
> ones that cover the other strategies already).
>
my initial scan for existing tests for the other strategies came up empty;
i will make another attempt tomorrow

**Comment by bparees** [comment]
yeah it looks like this might be the only only: https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L54

i had expected to see some more tests here:
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator_test.go

i think that would be the right place to add new ones.

**Comment by gabemontero** [comment]
generator_test.go unit tests for envs pushed

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by gabemontero** [comment]
flake https://github.com/openshift/origin/issues/12923

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
there was a devicemapper flake note, but also a go vet issue from my change:

pkg/build/generator/generator_test.go:552: wrong number of args for format in Errorf call: 2 needed but 3 args

will submit change shortly

**Comment by gabemontero** [comment]
make verify go-vet check passing locally for me .. pushed update

**Comment by bparees** [comment]
[merge]

**Pull request merged**
