### PR TITLE
UPSTREAM: <carry>: Back n forth downward/metadata conversions

### PR DESCRIPTION
**Pull request by soltysh**
@deads2k that's the missing part from the carry patch from the title. Thankfully it applied pretty cleanly.

### CODE REVIEW

**Comment by deads2k** [comment]
@kargakis Pretty sure you wrote the original

**Comment by kargakis** [comment]
Why are we doing this?

**Comment by soltysh** [comment]
It was wrongly applied during rebase. It was applied to
apis/experimental/v1 instead of api/extensions/v1beta1.

**Comment by kargakis** [comment]
I see... We need volume source conversion because of a bunch of resources using pod templates right?

**Comment by kargakis** [comment]
LGTM [merge]

**Pull request merged**
