### PR TITLE
UPSTREAM: drop: Fix kube e2e tests in origin. 

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ncdc

**Comment by ncdc** [comment]
@aveshagarwal a few things:

1. this was actually fixed by upstream PR 16084 (which was reverted, then restored)
1. kube upstream master has this fix, which means our Godep'd version of kube is just a bit too old to have it yet
1. we'll eventually pick this up in a rebase
1. if you do want to pull this in to origin now, your commit must follow the Godep patch message conventions (see https://github.com/openshift/origin/blob/master/HACKING.md#cherry-picking-an-upstream-commit-into-origin for all the details).
  1. in short, it needs to be `UPSTREAM: drop: <your description here>`. Note that it needs to say "drop" because that means we'll pick it up in the next rebase

cc @deads2k to sanity check what I just wrote :smile:

**Comment by aveshagarwal** [comment]
@ncdc yes I know, I investigated that history and spent considerable time understanding what happened.

**Comment by aveshagarwal** [comment]
@ncdc regarding your 4 point, it depends whether we want to fix it now or want to wait for rebase. I am fine with anything.

**Comment by ncdc** [comment]
cc @smarterclayton @liggitt - do you guys want us to cherry pick in fixes to make kube e2es green?

**Comment by deads2k** [comment]
> UPSTREAM: drop: <your description here>

If it differs from the actual kube pull, then yes.  Otherwise, it should be `UPSTREAM: <upstream pull number>: <upstream pull description>`.

**Comment by ncdc** [comment]
@deads2k true. @aveshagarwal can we cherry pick the whole PR?

**Comment by aveshagarwal** [comment]
@ncdc part of the PR is already in origin, but some pieces are missing. So it will not be exactly like the whole PR. Also, there is another PR that has one line change on top of this PR, dont have that PR link now.

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes/kubernetes/pull/16360 has one line change to fix the issue that caused revert in the first place. But I have to check whether this is already is origin or not.

**Comment by aveshagarwal** [comment]
Since the PR patch does not apply due to some parts already present in origin, I am going through the changes manually and picking those not present in origin.

**Comment by aveshagarwal** [comment]
I have manually picked changes from https://github.com/kubernetes/kubernetes/pull/16360 and updated this PR.

**Comment by ncdc** [comment]
[test][extended:core]

**Comment by aveshagarwal** [comment]
I found an issue with the patch and pushed an updated one now.

**Comment by aveshagarwal** [comment]
[test][extended:core]

**Comment by aveshagarwal** [comment]
Changes in Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/density.go and Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/load.go:62 are dependent on another PR https://github.com/kubernetes/kubernetes/pull/15843 . I am wondering whether to back out changes in these files or bring that PR also in (although not sure if it will cause any chain reaction further).

**Comment by aveshagarwal** [comment]
[test][extended:core]

**Comment by aveshagarwal** [comment]
I just ran "Probing container" kube e2e tests and they passed. I am now running all kube e2e tests in origin with this PR and my hope is that as far as less number of tests fail or IOW more passes (ofcourse I am hoping that this does not cause more failures),  this should be good to go if we want to reduce kube e2e failures before next rebase.

**Comment by deads2k** [comment]
Changes are contained and temporary, I'm ok with them going in, but the test are still red.  Did they fix what they were supposed to fix?

**Comment by ncdc** [comment]
These will come in by default in the next rebase. This PR does fix the failing container probe tests. As discussed on irc, we can look into splitting the kube tests into a separate test script, and if we do that, we'll presumably want a new jenkins job to run them.

**Comment by deads2k** [comment]
> These will come in by default in the next rebase. This PR does fix the failing container probe tests. As discussed on irc, we can look into splitting the kube tests into a separate test script, and if we do that, we'll presumably want a new jenkins job to run them.

Alright.  [merge]

**Comment by ncdc** [comment]
Test flake, related to https://github.com/openshift/origin/issues/6065#issuecomment-161852766 and https://github.com/openshift/origin/issues/5679#issuecomment-161852797.

[merge]

**Pull request merged**
