### PR TITLE
Slightly new format string for default release command

### PR DESCRIPTION
**Pull request by smarterclayton**
[DATE]-[TIME] instead of [DATE]T[TIME]Z

### CODE REVIEW

**Comment by wking** [comment]
Can we use an [RFC 3339][1] `2006-01-02T15:04:05Z`?  I'd rather stick with a standard time format if possible.

[1]: https://tools.ietf.org/html/rfc3339#section-5.8

**Comment by wking** [comment]
Ah, maybe this is being used for the tag?  And colons are [not valid tag characters][1].  In that case, I prefer the format you're dropping (RFC 3339 with the colons removed) to the one you're changing to ;).  But folks will probably be able to figure it out either way.

[1]: https://docs.docker.com/engine/reference/commandline/tag/

**Comment by smarterclayton** [comment]
Key thing is readability - the new format is more scannable, and I kept not being able to see what day a build was from in the logs.  The Z doesn't add anything, nor did the T.

**Pull request merged**
