### PR TITLE
Add mirror.centos.org repository to get the latest haproxy version

### PR DESCRIPTION
**Pull request by jkroepke**
See: #24825 

gpg key and .repo file are from https://github.com/openshift/openshift-ansible/tree/release-3.11/roles/openshift_repos

### CODE REVIEW

**Comment by Boran** [comment]
Should there not be a 
includepkgs = haproxy18*

and in images/base/cbs-paas7-openshift-multiarch-el7-build.repo, remove 
includepkgs = haproxy

**Comment by jkroepke** [comment]
@pecameron Any tasks for me? Or just to info the next?

**Comment by jkroepke** [comment]
Looking at @knobunc profile, it doesn't looks active...

/assign @bparees

**Comment by bparees** [comment]
/unassign @bparees 

i am not a member of the routing team, the routing team should be reviewing/approving this.

**Comment by jkroepke** [comment]
@bparees Sorry. I grab the info from here: https://github.com/openshift/origin/pull/24957

**Comment by frobware** [comment]
@jkroepke taking a look but I'm not so familiar with what was done in 3.x for the router image.

**Comment by frobware** [comment]
So I can see that http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/Packages/h/haproxy18-1.8.23-3.el7.x86_64.rpm is the RPM with the CVE fix. And that repo is available based on the changes in this PR. What's not clear to me is whether this change should land in openshift/release-3.11. Will this not be reflected for all OSE builds? /cc @knobunc @Miciah who will have more context here.

**Comment by jkroepke** [comment]
@frobware

Please recheck the changed files. Only the Docker Image inside router is change. The base image is not affected.

You might be get more context by reading the last comments at #24825

**Comment by spakal1** [comment]
assign @frobware

**Comment by frobware** [comment]
> /assign @frobware

I don't have enough context w.r.t how 3.11 is built to know whether this change is OK even though it appears to touch only the dockerfile for the route image. 

/assign @knobunc 

Ben: Any concerns with this change?

**Comment by jkroepke** [comment]
@frobware 

Few days ago @knobunc doesn't respond for 2 weeks. 

> I don't have enough context w.r.t how 3.11 is built

3.11 OKD images are build by CentOS PAAS and not inside the project. See: https://github.com/openshift/origin/issues/24825#issuecomment-622925150

I think there is no CI which covers the change.

**Comment by frobware** [comment]
> I think there is no CI which covers the change.

This strikes to the heart of my concern.

**Comment by jkroepke** [comment]
Sorry!

I read the logs (https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24958/test_pull_request_origin_end_to_end_311/1142/build-log.txt) and it looks like that new haproxy version is used:

```
[openshift/origin-haproxy-router] Dependencies Resolved
[openshift/origin-haproxy-router] ================================================================================
[openshift/origin-haproxy-router]  Package         Arch       Version           Repository                   Size
[openshift/origin-haproxy-router] ================================================================================
[openshift/origin-haproxy-router] Installing:
[openshift/origin-haproxy-router]  haproxy18       x86_64     1.8.23-3.el7      centos-openshift-origin     1.2 M
[openshift/origin-haproxy-router]  rsyslog         x86_64     8.24.0-52.el7     base                        620 k
[openshift/origin-haproxy-router] Installing for dependencies:
[openshift/origin-haproxy-router]  libestr         x86_64     0.1.9-2.el7       base                         20 k
[openshift/origin-haproxy-router]  libfastjson     x86_64     0.99.4-3.el7      base                         27 k
[openshift/origin-haproxy-router]  logrotate       x86_64     3.8.6-19.el7      base                         70 k
[openshift/origin-haproxy-router] Transaction Summary
[openshift/origin-haproxy-router] ================================================================================
[openshift/origin-haproxy-router] Install  2 Packages (+3 Dependent packages)
[openshift/origin-haproxy-router] Total download size: 2.0 M
[openshift/origin-haproxy-router] Installed size: 6.0 M
[openshift/origin-haproxy-router] Downloading packages:
[openshift/origin-haproxy-router] warning: /var/cache/yum/x86_64/7/centos-openshift-origin/packages/haproxy18-1.8.23-3.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 2f297ecc: NOKEY
[openshift/origin-haproxy-router] Public key for haproxy18-1.8.23-3.el7.x86_64.rpm is not installed
```

The end-to-end test is green. So the change is covered by CI (end-to-end) which is green!

I'll also expect no new site effects with the haproxy 1.8.23-3.el7 version, because this version is used in the enterprise router image.

**Comment by vrutkovs** [comment]
>Will this not be reflected for all OSE builds?

OSE builds are using a private fork to build images afaik, so router team should ensure this commit doesn't get cherry-picked there.

>I think there is no CI which covers the change.

e2e-gcp covers that.
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24958/pull-ci-openshift-origin-release-3.11-e2e-gcp/1078/artifacts/build-logs/haproxy-router.log builds a new image and https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24958/pull-ci-openshift-origin-release-3.11-e2e-gcp/1078/artifacts/e2e-gcp/container-logs/setup.log uses it:

```
TASK [openshift_hosted : Create OpenShift router] ******************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:86
Sunday 10 May 2020  16:38:57 +0000 (0:00:00.892)       0:22:53.543 ************ 
changed: [ci-op-pbz62lci-7a04a-ig-m-ng7m] => (item={... u'images': u'registry.svc.ci.openshift.org/ci-op-pbz62lci/stable:${component}', ...
```

Router didn't get deployed though, hopefully its a flake

/retest

**Comment by jkroepke** [comment]
Whats the error? Are the router logs available?

**Comment by vrutkovs** [comment]
`"0/4 nodes are available: 4 node(s) didn't match node selector."`
Seems to be a CI issue - all nodes have `node-role.kubernetes.io/master=true` label

**Comment by jkroepke** [comment]
Hm. I rebased the branch.

**Comment by jkroepke** [comment]
CI seems completely broken.

Other PRs for `release-3.11` just skip the ci/prow/e2e-gcp result by the override command.

So I would prefer to merge and good luck.

**Comment by jkroepke** [comment]
@frobware Any news? Your are the only one. Maybe @vrutkovs or I can give you the required contest to merge this.

Other members are still not responsible for weeks.

**Comment by frobware** [comment]
> @frobware Any news? Your are the only one. Maybe @vrutkovs or I can give you the required contest to merge this.

Sorry - I have been distracted by other things. 

I will ask the team again for their context.

**Comment by jkroepke** [comment]
Looking at [OWNERS](https://github.com/openshift/origin/blob/release-3.11/images/router/OWNERS).

Could some one look into it?

- @JacobTanenbaum
- @smarterclayton
- @pweil-
- @knobunc
- @ironcladlou
- @pecameron
- @rajatchopra

**Comment by jkroepke** [comment]
@frobware 

> I will ask the team again for their context.


Do you receive an answer?

**Comment by Boran** [comment]
Thanks jkroepke for your perseverance with this security bug, have any of the "owners" your referenced above reacted to you directly to help move this issue forward? Are we in a stalemate?

**Comment by frobware** [comment]
> Thanks jkroepke for your perseverance with this security bug, have any of the "owners" your referenced above reacted to you directly to help move this issue forward? Are we in a stalemate?

This had completely fallen off my radar. I will ask internally again about the change.

/assign @frobware

**Comment by frobware** [comment]
Post a discussion with the network edge team...

/lgtm

@jkroepke A sincere "thank you!" for your patience.

**Comment by jkroepke** [comment]
@frobware Thanks alot.

What are the next steps? The merge bot still wants a approve.

**Comment by frobware** [comment]
> @frobware Thanks alot.
> 
> What are the next steps? The merge bot still wants a approve.

@knobunc can you approve here?

/assign @knobunc

**Comment by jkroepke** [comment]
@frobware @knobunc got the PR multiple times, he is still unresponsible for almost 4 months now. Just look at the first posts here.

It would be great if you could ping him internally.

**Comment by frobware** [comment]
> It would be great if you could ping him internally.

Done.

**Comment by jkroepke** [comment]
@frobware @knobunc Any news?

**Comment by sgreene570** [comment]
The `unit` test job is (somewhat) broken at the moment iirc, might need an override if it doesn't pass through CI.

**Comment by frobware** [comment]
> The `unit` test job is (somewhat) broken at the moment iirc, might need an override if it doesn't pass through CI.

Which (I believe) is this issue: https://github.com/openshift/origin/issues/24874

**Comment by jkroepke** [comment]
@sgreene570 @frobware 

How to move forward?

Is there a circuit breaker for the two bots?

**Comment by frobware** [comment]
> @sgreene570 @frobware
> 
> How to move forward?
> 
> Is there a circuit breaker for the two bots?

https://github.com/openshift/origin/pull/25616 should fix the unit test failures.

**Comment by miheer** [comment]
Hi @jkroepke ! We need an updated haproxy rpm i.e version 1.8.26  but the mirror has 1.8.23  http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/Packages/h/haproxy18-1.8.23-3.el7.x86_64.rpm  I want to understand what is the correct process to update the haproxy rpm as I need haproxy attr feature for Samesite I wrote which is available in 1.8.26 and this is serious blocker for some important users. Please do let me know on this at your earliest.

**Comment by jkroepke** [comment]
@miheer 
CentOS PASS SIG would provide haproxy updates based on the official haproxy images for openshift. In best case, the haproxy version should match the version from the Openshift Enterprise version.

Looking here: https://ftp.redhat.com/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/ 1.8.23 is the latest available version from 1.8.x branch.

See: https://github.com/openshift/origin/issues/24825#issuecomment-613874198

> I want to understand what is the correct process

Normally:
* A enterprise user must raise an issue at RedHat Support portal (github issues for opensource are ignored)
* RedHat will provide a fix and would update the haproxy rpm for enterprise customers.
* Wait until the SPRM for the enterprise version is published -> https://ftp.redhat.com/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/
* Someone should drop a mail at the [CentOS PASS SIG](https://wiki.centos.org/SpecialInterestGroup/PaaS) group if someone could start to rebuilt the rpm and publish to the mirror.centos.org repository.
* Done.

But in this case (samesite issue) there is already a issue + PR provided by RedHat: https://github.com/openshift/origin/pull/25542

As non enterprise user, you have 
* to wait or
* start to build your own router images.

2 Examples how to build a own router images:
* https://github.com/adorsys-containers/openshift-components/blob/master/origin-haproxy-router/adorsys/Dockerfile 
* https://gitlab.com/aleks001/okd-router-hap21/-/blob/master/Dockerfile

I'm maintain the first and use the images in production. But it's patched, e.g. using a newer openssl version + haproxy version (2.2.4) + [patched haproxy-router.templates](https://github.com/adorsys-containers/openshift-components/tree/master/origin-haproxy-router/adorsys/patches)

**Comment by miheer** [comment]
@jkroepke  thanks for the quick response! Yes I already created and pushed the rpm to rhaos-3.11-rhel-7 
  branch using rhpkg push https://pkgs.devel.redhat.com/cgit/rpms/haproxy/log/?h=rhaos-3.11-rhel-7)  but not sure why it is not reflected in https://ftp.redhat.com/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/  . But using your Dockerfile I think I get your point as it seems to be a different approach. So it looks like I will have to check with the RHEL engineering about the package upgrade so that this package becomes available in centos repo after I drop them an email to CentOS PASS SIG right?

**Comment by jkroepke** [comment]
> Yes I already created and pushed the rpm to rhaos-3.11-rhel-7

But it's not public or reachable from external. I don't know if SIG members RH employees.

> So it looks like I will have to check with the RHEL engineering about the package upgrade so that this package becomes available in centos repo after I drop them an email to CentOS PASS SIG right?

Thats how we got the [1.8.23 haproxy package](https://cbs.centos.org/koji/buildinfo?buildID=29635) inside the OKD repository. For the whole story take a look at https://github.com/openshift/origin/issues/24825

**Comment by miheer** [comment]
@jkroepke thanks a lot!

**Pull request merged**
