### PR TITLE
Move hack/test-cmd_util.sh to test-util.sh, messing with script-fu

### PR DESCRIPTION
**Pull request by smarterclayton**
[merge]

### CODE REVIEW

**Comment by deads2k** [comment]
Did you just move a file so your tab completion was prettier.....?

**Comment by liggitt** [comment]
Yes. I'll admit the naming of the files upstream messing up tab completing test-go.sh bothers me

**Comment by smarterclayton** [comment]
Absolutely, according to https://xkcd.com/1205/ where it saves 5 seconds
and I do it 50/day.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Flake, https://github.com/openshift/origin/issues/8027

[merge]

**Pull request merged**
