### PR TITLE
Reduce delete check flakiness

### PR DESCRIPTION
**Pull request by ironcladlou**
Wait for delete post-conditions to be true rather than giving up
immediately.

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
cc @ncdc @kargakis

**Comment by ncdc** [comment]
:+1:

**Comment by ironcladlou** [comment]
[merge]

**Comment by kargakis** [comment]
:+1:

**Comment by smarterclayton** [comment]
Negative on merge - this needs to be fixed asap.  Delete being broken is unacceptable

**Comment by ironcladlou** [comment]
The problem wasn't the delete. The problem is that the delete happened, and then the script tried to assert the items were deleted immediately, once, with no retries. Which sometimes works, obviously.

**Comment by ironcladlou** [comment]
Of course, now there appears to be some other flaky behavior during the test for this one...

**Comment by ncdc** [comment]
With `osc stop`, isn't the deletion of the RCs async?

**Comment by liggitt** [comment]
I thought the cascading delete was supposed to happen prior to the command returning

**Comment by ncdc** [comment]
If it's supposed to happen prior to the command returning, then yes, we have a problem somewhere.

**Comment by smarterclayton** [comment]
It is, and we have a serious problem.  That's why https://github.com/openshift/origin/issues/2721 is p0

----- Original Message -----

**Comment by ironcladlou** [comment]
Yep, now I see. Sorry, folks!

**Comment by kargakis** [comment]
Note that we are doing the [exact](https://github.com/openshift/origin/blob/21b24f810ccf3cb34e9031bc57d8306e86e42db9/hack/test-cmd.sh#L344) same thing for `rc/docker-registry-1`, it's just not a deletion but a get. I am inclined to believe this is not specific to delete or the dc reaper, but a problem deeper in the rc controller.

**Comment by smarterclayton** [comment]
It could be a race in the order of deletion of the dc's replication controllers.  If you aren't disabling the config change trigger, the deployment controller will try to create a new rc right away.  Or, the deployment controller is creating a deployment when you disable the config change trigger (also a bug).  I tend to doubt that you read a rc after a delete was successful (since that would be a pretty serious etcd bug).

----- Original Message -----

**Comment by ncdc** [comment]
@kargakis I don't think that's the issue. We've diagnosed it down to the fact that after `osc stop`, sometimes we still see the rc (presumably a new one, as @smarterclayton is suggesting).

**Comment by kargakis** [comment]
@smarterclayton we are disabling all dc triggers before removing anything (rcs, dc in that order)

**Comment by kargakis** [comment]
Actually on master we just remove the latest rc, https://github.com/openshift/origin/pull/2692 removes all of them.

**Comment by smarterclayton** [comment]
It's possible that the deployment controller is incorrectly triggering a new deployment in that case then.

----- Original Message -----

**Comment by kargakis** [comment]
> It's possible that the deployment controller is incorrectly triggering a new deployment in that case then.

That's what I thought too, though it seems more of a rc problem (get rc/docker-registry-1 a while after bringing it up was flaking too). Try to replace the dc [here](https://github.com/openshift/origin/blob/21b24f810ccf3cb34e9031bc57d8306e86e42db9/hack/test-cmd.sh#L466) with its rc and see if we get the same flake. If so, then it certainly is an rc thing. Cannot run anything now, will test this tomorrow.

**Pull request closed without merging**
