### PR TITLE
OCPBUGS-34289: Revert "[release-4.14] OCPBUGS-33417: Provide SCC access via RBAC"

### PR DESCRIPTION
**Pull request by dtantsur**
All metal jobs on 4.14 are failing with something along the lines of

```
Back-off pulling image "virthost.ostest.test.metalkube.org:5000/localimages/local-test-image:e2e-28-registry-k8s-io-pause-3-9-p9APyPDU5GsW02Rk"
```

The failures started around the time the PR was merged. Testing a revert.

Reverts openshift/origin#28806

### CODE REVIEW

**Comment by soltysh** [comment]
@dtantsur has anyone looked into why that pause:3.9 image isn't mirrored? It was added long time ago here: https://github.com/openshift/release/blob/c1168de592b4836d17f438114408a6fd93f836e2/ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh#L23-L26 so I'd look there why it's not happening in 4.14?

**Comment by dtantsur** [comment]
Trying to. The difference I can spot is that there we're mirroring into `e2e-27-registry-k8s-io-pause-3-9-p9APyPDU5GsW02Rk`, while here we're looking for `e2e-28-registry-k8s-io-pause-3-9-p9APyPDU5GsW02Rk` (27 vs 28). I don't know what that means.

**Comment by soltysh** [comment]
> Trying to. The difference I can spot is that there we're mirroring into `e2e-27-registry-k8s-io-pause-3-9-p9APyPDU5GsW02Rk`, while here we're looking for `e2e-28-registry-k8s-io-pause-3-9-p9APyPDU5GsW02Rk` (27 vs 28). I don't know what that means.

Update scripts adding the new numbers, that should help.

**Comment by soltysh** [comment]
Proper fix in https://github.com/openshift/release/pull/52432

**Pull request closed without merging**
