### PR TITLE
add image policy admission to the openshift chain and default on

### PR DESCRIPTION
**Pull request by deads2k**
@bparees I think this is where you need to twiddle it.  This also defaults it to on.  Is that correct?

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
> @bparees I think this is where you need to twiddle it. This also defaults it to on. Is that correct?

yeah, but let me include this in the PR i'm already working on to properly default the config as well.

/hold

**Comment by bparees** [comment]
@deads2k this lgtm, can you rebase it and we'll merge?  That will at least get the imagepolicy admission plugin enabled again.  Still need to sort out removing the internal api and a few other things, but that can be done after, i believe.

**Comment by deads2k** [comment]
Added unit tests for registration, comments indicating names that were registered, ordered a couple lists to make them easier to read, removed duplicate enablement/removal options.

**Pull request closed without merging**
