### PR TITLE
UPSTREAM: 44295: Azure disk: dealing with missing disk probe

### PR DESCRIPTION
**Pull request by rootfs**
@childsb @eparis

### CODE REVIEW

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
@childsb @eparis can you merge? thanks

**Comment by rootfs** [comment]
fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1451039

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by rootfs** [comment]
Test failed 

```
Ginkgo ran 1 suite in 18m46.316933666s
Test Suite Passed
[INFO] [CLEANUP] Beginning cleanup routines...
[INFO] [CLEANUP] Dumping cluster events to _output/scripts/conformance/artifacts/events.txt
[INFO] [CLEANUP] Dumping container logs to _output/scripts/conformance/logs/containers
[INFO] [CLEANUP] Truncating log files over 200M
[INFO] [CLEANUP] Stopping docker containers
[INFO] [CLEANUP] Removing docker containers
[INFO] [CLEANUP] Killing child processes
[INFO] [CLEANUP] Pruning etcd data directory
rm: cannot remove ‘/tmp/etcd’: Operation not permitted
[ERROR] test/extended/conformance.sh exited with code 1 after 00h 27m 21s
make: *** [test-extended] Error 1
+ gather
+ set +e
+ hack/build-go.sh cmd/oc
++ Building go targets for linux/amd64: cmd/oc
hack/build-go.sh took 225 seconds
++ pwd
+ export PATH=/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/origin/.local/bin:/home/origin/bin
+ PATH=/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/origin/.local/bin:/home/origin/bin
+ oc get nodes --template '{{ range .items }}{{ .metadata.name }}{{ "\n" }}{{ end }}'
+ xargs -L 1 -I X bash -c 'oc get --raw /api/v1/nodes/X/proxy/metrics > /tmp/artifacts/X.metrics' ''
+ oc get --raw /metrics
+ set -e
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: RUN EXTENDED TESTS [00h 31m 10s] ##########
```

**Comment by childsb** [comment]
[merge][severity:blocker]

**Pull request merged**
