### PR TITLE
[1.4] Fix image pruning with both strong & weak refs

### PR DESCRIPTION
**Pull request by soltysh**
Fix a logic error where an image could incorrectly be considered
prunable if there were both strong and weak references from an image
stream to the image.

1.4 cherrypick of #13671

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
re[test]

**Comment by pweil-** [comment]
flake https://github.com/openshift/origin/issues/12007 re[test]

**Comment by pweil-** [comment]
[test]

**Comment by eparis** [comment]
[merge] just to get it in the queue somewhere?

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/13271
[test]

**Comment by pweil-** [comment]
Seems to be having issues with:
```
++ export PATH
+ os::build::rpm::get_nvra_vars
bash: line 5: os::build::rpm::get_nvra_vars: command not found
++ os::util::trap::err_handler
++ local -r return_code=127
++ local -r last_command=os::build::rpm::get_nvra_vars
```

@mfojtik the only place I can find that is: https://github.com/openshift/origin/commit/b95268c2cad60631429804413faa375b84dcd6f4#diff-c678ee0710aaec9235e19633904cef51 and doesn't exist in the 1.4 branch.  Ideas?

In any case the test_pull_request_origin_integration, test_pull_request_origin_check, and test_pull_request_origin_extended_networking_minimal passed..

**Comment by stevekuznetsov** [comment]
Historically we have never versioned the jobs that run our CI. As of late there has been more churn than usual on the support code and 1.4 branch is ~150 commits behind 1.5 ... unclear if the backport is a reasonable thing to do or not, but these errors are expected.

**Comment by stevekuznetsov** [comment]
If you want to run conformance tests without the Ansible installation, use https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance/ manually.

**Pull request merged**
