### PR TITLE
Work around docker race condition when running build post commit hooks.

### PR DESCRIPTION
**Pull request by jim-minter**
https://bugzilla.redhat.com/show_bug.cgi?id=1425824

### CODE REVIEW

**Comment by csrwng** [comment]
👍  I didn't realize we were doing a logs call instead of attach. Makes sense.

**Comment by jim-minter** [comment]
Tested with fork AMI and seems to solve the problem.

**Comment by jim-minter** [comment]
@bparees this should go into release-1.5 as well - does that require a second PR?  Once this has merged or concurrently?

**Comment by bparees** [comment]
> @bparees this should go into release-1.5 as well - does that require a second PR? Once this has merged or concurrently?

yes it needs a second pr against the release-1.5 branch, concurrent is fine.

[merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@jim-minter failure looks legitimate.

**Comment by bparees** [comment]
merge tag removed, this breaks an extended test.

**Comment by jim-minter** [comment]
Yes, sorry, repushed and hopefully fixed. Let's see the test results.  Ditto on #13196.

**Comment by bparees** [comment]
@jim-minter I think the extended tests are still going to fail.

**Comment by jim-minter** [comment]
flake #13068

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13234
[merge]

**Pull request merged**
