### PR TITLE
don't update the build phase once it reaches a terminal state

### PR DESCRIPTION
**Pull request by bparees**
fix for bug https://bugzilla.redhat.com/show_bug.cgi?id=1279312

### CODE REVIEW

**Comment by deads2k** [comment]
Should validation be preventing transitions out of terminal states?

**Comment by bparees** [comment]
@deads2k which validation?

**Comment by deads2k** [comment]
> @deads2k which validation?

https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L28  That validation method has sufficient information to enforce proper flow through any state machine.  As a starting point, it should be able to enforce terminal state logic.

I was actually thinking about this problem for our controller state machines in general while reviewing the PVC controller.

**Comment by bparees** [comment]
@deads2k hm.  yeah maybe we should add it there too.  i'll put it in my PR.

**Comment by kargakis** [comment]
We hit it in the deployerpod controller too a couple of weeks ago: https://github.com/openshift/origin/pull/4963

+1 for bumping the validation to check for it too

**Comment by bparees** [comment]
validation + tests added.

**Comment by deads2k** [comment]
lgtm

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[test]

**Pull request merged**
