### PR TITLE
Prefer secure connection during image pruning

### PR DESCRIPTION
**Pull request by miminar**
The default stays the same. When a CA bundle or a registry url is specified, require secure connection with certificate verification. Allow the user to force insecure connection using --force-insecure if he has to.

### CODE REVIEW

**Comment by miminar** [comment]
[test][testextended:core(prune\ images)]

**Comment by miminar** [comment]
Regenerated completions.

**Comment by miminar** [comment]
Flake #14122

**Comment by miminar** [comment]
Flake #12927

**Comment by miminar** [comment]
[test]

**Comment by miminar** [comment]
Flakse #14140. re-[test]

**Comment by soltysh** [comment]
@miminar can you confirm if this PR will solve the problem from https://bugzilla.redhat.com/show_bug.cgi?id=1448595 ?

**Comment by miminar** [comment]
Flake #13426 in job https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1349/. re-[test]

**Comment by miminar** [comment]
> @miminar can you confirm if this PR will solve the problem from https://bugzilla.redhat.com/show_bug.cgi?id=1448595 ?

If they keep using wrong certificate authority, this PR will at least allow them to force insecure connection.

**Comment by miminar** [comment]
Flake #12251. re-[test]

**Comment by miminar** [comment]
Test flake #14214. @soltysh all the sub tests passed individually in various runs. There was just  not a single run where they passed all at once. May I request your merge powers?

**Comment by soltysh** [comment]
[merge]

**Comment by miminar** [comment]
Flake #14228.

**Comment by miminar** [comment]
Do not merge. I've just found another shortcoming.

**Comment by miminar** [comment]
Fixed. The code now takes into account an insecure flag in user's kubeconfig - just like before. Also the registry pinger now generates more readable errors. It won't attempt HTTP ping if a secure transport is requested.

**Comment by miminar** [comment]
@soltysh may I request one more look of yours?

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
flake https://github.com/openshift/origin/issues/8571
[test]

**Comment by miminar** [comment]
The extended tests may need some changes. I'll investigate on Monday.

**Comment by miminar** [comment]
The pruner now allows insecure connections for private addresses.

**Comment by miminar** [comment]
Here's a documentation: openshift/openshift-docs#4471

@dmage could you please help review this? I'd like to get it in before the pruning changes for the read-only mode.

**Comment by miminar** [comment]
[testextended][extended:core(prune images)]

**Comment by miminar** [comment]
No change, just re-signed the last commit to trigger new test runs.

**Comment by miminar** [comment]
Oh the extended test has been renamed. One more try:
[testextended][extended:core(ImagePrune)]

**Comment by miminar** [comment]
@mfojtik merge?

**Comment by mfojtik** [comment]
[merge][severity:blocker]

blocker bug: https://bugzilla.redhat.com/show_bug.cgi?id=1448595

**Comment by miminar** [comment]
Flake #12072

**Comment by mfojtik** [comment]
[merge][severity:blocker]

**Pull request merged**
