### PR TITLE
Updating images to build containers on pipeline.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
- Deleted node Dockerfile.centos7 as it was an exact replica of Dockerfile.
- Deleted origin Dockerfile.centos7 as it was exact replica of Dockerfile.
- Added cccp.yml files to observe and source to build on pipeline.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
ping @stevekuznetsov @tdawson @smarterclayton 
Also i had a couple of doubts related to dind containers, for which reason, i have not added cccp.yml files here

**Comment by stevekuznetsov** [comment]
Yeah, DIND is for testing and should not be downstream.

/lgtm
/approve
/ok-to-test

**Comment by stevekuznetsov** [comment]
/lgtm cancel

Too many failures -- @mohammedzee1000 please take a look at them and determine why the tests are failing.

**Comment by mohammedzee1000** [comment]
@stevekuznetsov Cant able to make out what happened here. Is it because of the removal of the Dockerfile.centos7?

**Comment by mohammedzee1000** [comment]
I had some doubts about the following containers and their names.
federation, observe, openldap, simple-authenticated-registry.

Also i have resubmitted the PR after a rebase. So hopefully can get it to pass.

**Comment by sdodson** [comment]
I don't see any obvious problems with this but that assumes that the .centos7 files aren't in use by any of our CI/CD processes which I'm not sure of.

**Pull request closed without merging**
