### PR TITLE
UPSTREAM: 23894: OOM errors when processes exit rapidly

### PR DESCRIPTION
**Pull request by smarterclayton**
This is on the bubble for 1.2 but I wanted to see if it helps clear up our failures

@ncdc @derekwaynecarr @liggitt [test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by ncdc** [comment]
@smarterclayton upstream PR was updated and hopefully will fix the type issues in all the right places (by removing the type assertions).

**Comment by smarterclayton** [comment]
Updated against upstream

**Comment by ncdc** [comment]
Conformance tests failed, again with the update-demo scaling an RC test. But it doesn't appear to be the same failure text. Still tracking it down. But I did notice that the docker.log that's captured in the jenkins artifacts isn't complete. For example, the failing test created its first container that had an issue at 12:04, but the contents of docker.log starts at 12:08 :cry:

**Comment by smarterclayton** [comment]
#8441 is the other failure.

**Comment by smarterclayton** [comment]
You can extend the docker log time.  Going up to 30m is probably fine.

**Comment by ncdc** [comment]
How do we do that?

I'll spin up a rhel7 vm in ec2 to try to repro manually.

**Comment by smarterclayton** [comment]
It's in the test failure trap where we shut down the server - we grab the docker logs from the journal in hack/test-end-to-end-docker.sh

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Updated

**Comment by ncdc** [comment]
Because we run tests in parallel, each test's namespace needs to be added to the various SCCs to ensure upstream e2es can pass against OpenShift's security model. It looks like that code was resulting in each namespace stomping on the other namespaces such that only a single e2e namespace at a time was ever a member of the various SCCs.

#8465 should fix this issue.

**Comment by smarterclayton** [comment]
@jwforres @spadgett Bindata failure

**Comment by spadgett** [comment]
@smarterclayton looking at it

**Comment by spadgett** [comment]
@jwforres new font-awesome update today is breaking us

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Flaked https://github.com/openshift/origin/issues/8399 [test]

**Comment by deads2k** [comment]
> I think that flake is an extended flake w.r.t. the policy cache falling behind. Not sure though - @deads2k?

It's likely.  We have a method `WaitForPolicyUpdate` to avoid that problem during our integration tests.

**Comment by pecameron** [comment]
[TEST]

**Comment by ncdc** [comment]
@pecameron this already merged. No need to re-test.

**Comment by deads2k** [comment]
> @pecameron this already merged. No need to re-test.

Man, he meant it too. :)

**Pull request merged**
