### PR TITLE
Restore contrib/vagrant/provision-minimal.sh

### PR DESCRIPTION
**Pull request by adambkaplan**
Restores CI for source-to-image until we switch to ci-operator.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 

Note that this may not fix everything (just will fix the current known breakage).

**Comment by bparees** [comment]
@adambkaplan can you tag whoever removed this so they are aware?

also put a comment in the file about why it's here so it hopefully doesn't get removed again until it's not needed.

alternatively, can we just create this in the s2i repo and update the jenkins job to not use origin?  (not sure why the jenkins job should require origin in general....)

**Comment by adambkaplan** [comment]
fyi @soltysh - think this was removed when we dropped openshift start. Previous sha was 4fe1c7912a41200f89272aa32a2942647e4726a1

**Comment by adambkaplan** [comment]
@bparees the s2i jenkins job runs a whole bunch of vagrant commands in the setup phase, one of which is `vagrant up` using the origin `Vagrantfile`.

**Comment by bparees** [comment]
we could move the vagrantfile too :)

but this is fine for now and since the long term goal is to move off vagrant, i guess we just let it go.

That said, i wouldn't be surprised if someone removes the Vagrant file from origin at some point too because I suspect it's not used any more either.

**Pull request merged**
