### PR TITLE
UID repair should not fail when out of range allocation

### LINKED ISSUE #5316: Setting a UID block outside the range prevents server startup
```
F1022 04:58:33.519655    6107 run_components.go:390] Unable to initialize namespaces: unable to allocate UID block 0/10000 for namespace default due to an unknown error, exiting: provided UID range is not in the valid range
```

because default is set.  Should not happen.  UIDs outside range can be safely ignored.

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #5316

@pweil-

### CODE REVIEW

**Comment by pweil-** [comment]
LGTM.  Do we need to account for the case of an annotation that partially collides with the allocator range?  At first glance I'd say no, that the admin is probably making the choice to have overlap and the block is still available for allocation.

**Comment by liggitt** [comment]
> the block is still available for allocation

I wouldn't expect the allocator to give anything that is already allocated to a new namespace

**Comment by pweil-** [comment]
Let's say:

1.  you have an allocator block of 1-20/5
2.  1-5 is allocated to ns A
3.  the admin changes ns A to have 1-7
4.  repair runs

would you expect the allocator to throw out the 6-10 block because of the collision?  If the allocator accounts for this use case that's what I'd expect.

**Comment by pweil-** [comment]
though that means that repair (or something) would need to run when this annotation changed to make it consistent so I could see the argument of letting the admin do what they want with full knowledge that they're crossing streams

**Comment by smarterclayton** [comment]
Admin can set any annotation they want.  Allocator needs to ensure that it
doesn't hand out the same allocations twice.  An admin who assigns a block
that the allocator expects to see has done so deliberately, and the
allocator can assume it's taken.  Any other case, the allocator should
ignore it.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
