### PR TITLE
 remove openshift cli and friends

### PR DESCRIPTION
**Pull request by deads2k**
removes
 1. `openshift cli`
 2. `openshift admin`
 3. `osc`
 4. `oadm`
 5. `osadm`

### CODE REVIEW

**Comment by sdodson** [comment]
@deads2k which package provides the client binaries now?

**Comment by wanghaoran1988** [comment]
@deads2k @mfojtik @soltysh  Why we remove oadm command? as currently a lot tools that use the oadm, not only the automation framework qe used, but also the installer, and I think a lot customer also are using this.

**Comment by sdodson** [comment]
The installer was fixed yesterday FWIW.

**Comment by aditya-konarde** [comment]
@wanghaoran1988 +1. 

Can we please get to know what's the context for this? Are these tools being packaged somewhere else? Is there a GitHub issue I can look at to get more clarity on this? 

I'm just curious, as I've used these commands while I was learning OpenShift. :)

**Comment by vikram-redhat** [comment]
@sdodson - is this for 3.9 or future? This will have a major impact on the docs.

FYI: @adellape @aheslin

**Comment by wanghaoran1988** [comment]
@vikram-redhat This already happening in the 3.8

**Pull request merged**
