### PR TITLE
[DO NOT MERGE] Test Commit

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[test_future]

**Comment by smarterclayton** [comment]
GCE flaked on registry

**Comment by stevekuznetsov** [comment]
[test_future]

**Comment by smarterclayton** [comment]
Flake https://github.com/openshift/origin-gce/issues/14

**Pull request closed without merging**
