### PR TITLE
Issue 4855 - warning flickers about build config and deployment config not existing

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/4855

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett

**Comment by jwforres** [comment]
fyi deployments controller was already setting deploymentConfigs to undefined

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
