### PR TITLE
Enable upstream e2e statefulset tests

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by deads2k** [comment]
No preference.  If they break in the rebase, I expect @mfojtik will re-disable them.

**Comment by kargakis** [comment]
Why would they break? They seem pretty happy upstream (no failure in the past 16 days).

https://k8s-testgrid.appspot.com/sig-apps#gce&width=5

**Comment by kargakis** [comment]
@deads2k @mfojtik tests are green here

**Pull request merged**
