### PR TITLE
Authorize Git against the master

### PR DESCRIPTION
**Pull request by smarterclayton**
@ncdc this includes changes to use one client for multiple tokens,
although there was the change upstream as well.

### CODE REVIEW

**Comment by ncdc** [comment]
SAR changes LGTM. Not sure about the rest.

**Comment by smarterclayton** [comment]
They were more of an example based on what I described - don't worry about
the rest.  We need something slightly cleaner but I'd prefer to solve the
proxy SAR issue now

On Jul 7, 2015, at 12:23 PM, Andy Goldstein <notifications@github.com>
wrote:

SAR changes LGTM. Not sure about the rest.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3600#issuecomment-119259780>.

**Comment by smarterclayton** [comment]
[merge] since this is an example only still.

**Comment by ncdc** [comment]
I think @liggitt had some reservations about the token impersonation...

**Comment by smarterclayton** [comment]
There's not really an alternative.  In this case you're trusting the
gitserver with your SSO token.  Other options have other problems - SSO
token (complexity), oauth authorization (complexity), single shared
password (moves authorization outside).

In general, a user here is going to want to generate a long lived token
that can be reused, so that's probably a SA token, but the user has to find
that token somehow and you probably want one per user.  If we had a some
form of scoping with macaroons that might be an option.  The only other
option is OAuth, and I blanche at the cost of that.

On Mon, Aug 10, 2015 at 8:45 AM, Andy Goldstein <notifications@github.com>
wrote:

> I think @liggitt <https://github.com/liggitt> had some reservations about
> the token impersonation...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3600#issuecomment-129429476>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request merged**
