### PR TITLE
Replace default ginkgo reporter with SimpleReporter

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test][extended:core(images)]

**Comment by mfojtik** [comment]
@smarterclayton :christmas_tree: (still WIP, any suggestions about how to make the output better are welcome ;-)

**Comment by mfojtik** [comment]
[test][extended:core(images)]

**Comment by mfojtik** [comment]
[test]

**Comment by deads2k** [comment]
@deads2k mail filter check.

**Comment by liggitt** [comment]
cc @deads2k

**Comment by mfojtik** [comment]
@smarterclayton it seems like there is no good way to completely silence the ginkgo tests (it still prints the `[BeforeEach]` and `STEP:` parts... I can try to capture the stdout/err as well but dunno if that would be ok :-)

**Comment by mfojtik** [comment]
[extended:core(s2i)]

**Comment by danmcp** [comment]
[testonlyextended]

**Comment by smarterclayton** [comment]
Is before each and step because we have verbose?

**Comment by mfojtik** [comment]
@smarterclayton I removed verbose, they are still there :/

**Comment by smarterclayton** [comment]
Can we fix ginkgo?

**Comment by mfojtik** [comment]
[extended:core(start-build)]

**Comment by mfojtik** [comment]
@smarterclayton I found it... we were hardcoding the Verbose in code and also on command line, see: https://github.com/openshift/origin/commit/767e9ff635e8c9be06048c0d6980837f8f1e6dbc

PTAL the Jenkins output (if the jenkins pass ;-) and tell me if it looks better... It definitely does for me ;-)

**Comment by smarterclayton** [comment]
Looks ok.  Let's try to get this in Kube though (we can keep this as an
upstream if they want it)

On Oct 8, 2015, at 7:12 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I found it... we were
hardcoding the Verbose in code and also on command line, see: 767e9ff
<https://github.com/openshift/origin/commit/767e9ff635e8c9be06048c0d6980837f8f1e6dbc>

PTAL the Jenkins output (if the jenkins pass ;-) and tell me if it looks
better... It definitely does for me ;-)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4984#issuecomment-146506684>.

**Comment by mfojtik** [comment]
@smarterclayton I will merge this here (it contains more fixes to make the test output more readable and one fix for start-build extended test) AND opening PR in upstream. If they will be happy with this, we just import the reporter and remove it from our code base.

[merge]

**Comment by mfojtik** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/15360

**Pull request merged**
