### PR TITLE
UPSTREAM: 58345: azure disk: if the disk is not found, immediately detach it. This prevents azure keeps the bad request and stops issuing new request

### PR DESCRIPTION
**Pull request by rootfs**
fix https://bugzilla.redhat.com/show_bug.cgi?id=1440892

### CODE REVIEW

**Comment by rootfs** [comment]
ping @childsb

**Comment by childsb** [comment]
/assign @smarterclayton

to appease the approval bots

**Comment by liggitt** [comment]
is this a release blocker?

**Comment by liggitt** [comment]
the linked BZ is closed as verified...

**Pull request closed without merging**
