### PR TITLE
miekg/dns: bump to latest version

### PR DESCRIPTION
**Pull request by sosiouxme**
I believe there's a bug in this lib that's causing https://bugzilla.redhat.com/show_bug.cgi?id=1330486 and I wanted to try updating it before bugging the author to look at it (our Godep is 7 months old).

### CODE REVIEW

**Comment by sosiouxme** [comment]
[test][extended:networking]

**Comment by ncdc** [comment]
@sosiouxme Kube vendors this too - ideally we would have the same git commit as they do so you may want to do a bump PR there too.

cc @smarterclayton

**Comment by knobunc** [comment]
I have no objection, but @ncdc's comment is wise.

**Comment by eparis** [comment]
agreed, upstream first.

**Comment by sosiouxme** [comment]
Seems like it would be harder to make the case upstream, but I see the wisdom in not diverging.

**Comment by smarterclayton** [comment]
We've always diverged a little bit from upstream on this package (typically we are newer).

**Comment by smarterclayton** [comment]
@deads2k we're supposed to ping you...

**Comment by deads2k** [comment]
@mfojtik I don't think the rebase is close enough to block this, but if you disagree now's the time.

**Comment by deads2k** [comment]
wait @mfojtik you bumped skydns in the rebase, but didn't bump this along with it?  how did that happen?

**Comment by mfojtik** [comment]
@deads2k no idea, I guess that dep did not showed up after restore or the skydns bump was not that major. but I think this bump will fix it if I accidentialy missed it.

**Comment by sosiouxme** [comment]
So does that mean we do or don't want to wait on a kubernetes bump for this lib?

Jenkins tests passed the first time, guessing https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/952/ is a flake

**Comment by deads2k** [comment]
> Jenkins tests passed the first time, guessing https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/952/ is a flake

Yeah, its a flake.  The status on the job actually links to the current flake issue and requests that you ping me if its a merge job so I'll know its not contending with test-cmd.

**Comment by deads2k** [comment]
> So does that mean we do or don't want to wait on a kubernetes bump for this lib?

No need to wait, but an upstream bump is worthwhile.  Skewed godeps are painful for us to rebase.

**Comment by smarterclayton** [comment]
Reopen if necessary, we updated for 1.4 and it probably got this

**Pull request closed without merging**
