### PR TITLE
move pkg/cmd/util/clientcmd -> pkg/oc/cli/util/clientcmd

### PR DESCRIPTION
**Pull request by juanvallejo**
This patch *partially* solves a few of the items (currently checked) from #17309 
Now that `clientcmd` (which includes printer factory methods) is moved into `pkg/oc`,
the following files outside of `pkg/oc` need to have their dependency on `clientcmd` broken (this will be done in a separate PR):

- [x] pkg/cmd/server/origin/controller/config.go (https://github.com/openshift/origin/pull/17357)
- [x] pkg/cmd/server/admin/create_error_template.go   (https://github.com/openshift/origin/pull/17357)
- [x] pkg/cmd/server/admin/create_bootstrap_project_template.go (https://github.com/openshift/origin/pull/17357)
- [x] pkg/cmd/server/admin/overwrite_bootstrappolicy.go (*this file has been removed by* https://github.com/openshift/origin/pull/17336)
- [x] pkg/cmd/server/admin/create_login_template.go (https://github.com/openshift/origin/pull/17357)
- [x] pkg/cmd/server/admin/create_provider_selection_template.go (https://github.com/openshift/origin/pull/17357)
- [x] **pkg/cmd/infra/router/template.go** (Wanted by: `pkg/cmd/openshift/openshift.go` (no other dependents)) (https://github.com/openshift/origin/pull/17357)
- [x] **pkg/cmd/infra/router/f5.go** (Wanted by: `pkg/cmd/openshift/openshift.go` (no other dependents)) (https://github.com/openshift/origin/pull/17357)
- [x] pkg/cmd/openshift/openshift.go (https://github.com/openshift/origin/pull/17486 and https://github.com/openshift/origin/pull/17482)
- [x] pkg/cmd/dockerregistry/dockerregistry.go (Wanted by: `cmd/dockerregistry/main.go` (depends on `clientcmd.Config`)) (https://github.com/openshift/origin/pull/17357)
- [x] *pkg/diagnostics/networkpod/util/util.go* (Can  be addressed by moving `pkg/diagnostics` inside existing `pkg/oc/admin/diagnostics`) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/client/config_contexts.go* (Can  be addressed by moving `pkg/diagnostics` inside existing `pkg/oc/admin/diagnostics`) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/client/run_diagnostics_pod.go* (Can  be addressed by moving `pkg/diagnostics` inside existing `pkg/oc/admin/diagnostics`) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/pod/auth.go* (Can  be addressed by moving `pkg/diagnostics` inside existing `pkg/oc/admin/diagnostics`) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/network/run_pod.go* (Can be addressed by moving `pkg/diagnostics` inside existing `pkg/oc/admin/diagnostics`) https://github.com/openshift/origin/pull/17393
- [x] pkg/ipfailover/keepalived/plugin.go (moved to `pkg/oc/experimental`) (https://github.com/openshift/origin/pull/17357)
- [x] pkg/federation/kubefed/kubefed.go (https://github.com/openshift/origin/pull/17357)
- [x] pkg/dockerregistry/server/client/client.go (https://github.com/openshift/origin/pull/17357)
- [x] pkg/dockerregistry/server/auth_test.go (https://github.com/openshift/origin/pull/17357)

**bold** = depends on `clientcmd.Config` (not sure what to do about this) AND only dependent is `pkg/cmd/openshift/openshift.go`

cc @deads2k @openshift/cli-review @liggitt

### CODE REVIEW

**Comment by deads2k** [comment]
Check for conflicts with the rebase and get it green.  This is an ok way to break the dependency.  A little messy in the interm, but acceptable since we know you won't stop part way.

/approve no-issue

**Comment by deads2k** [comment]
let's crack some eggs.

/lgtm

**Comment by deads2k** [comment]
@juanvallejo this pull still valid/needed?

**Comment by juanvallejo** [comment]
@deads2k 
>  this pull still valid/needed?

yes, this pull is a counterpart to https://github.com/openshift/origin/pull/17357. This one moves `clientcmd` into `pkg/oc`, and pull/17357 breaks any package dependencies on it outside of `pkg/oc`

**Pull request merged**
