### PR TITLE
UPSTREAM: google/cadvisor: 1639: Reduce cAdvisor log spam

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/openshift/origin/issues/13719

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
cc @ncdc @eparis

**Comment by derekwaynecarr** [comment]
FYI - the upstream merged

**Comment by derekwaynecarr** [comment]
see https://github.com/google/cadvisor/pull/1639

**Comment by ncdc** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Pull request merged**
