### PR TITLE
Test build-chain in hack/test-cmd

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by kargakis** [comment]
re[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by soltysh** [comment]
re-[test]

**Comment by soltysh** [comment]
re-[test] again

**Comment by soltysh** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
