### PR TITLE
OPRUN-3579: Add happy-path operator-contoller test

### PR DESCRIPTION
**Pull request by tmshort**
Install an operator from quay.io

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by tmshort** [comment]
Ping @bertinatto ?

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview-serial

**Pull request merged**
