### PR TITLE
Bug 2089966: use multi-arch ldap and multicast test images

### PR DESCRIPTION
**Pull request by yselkowitz**
The ldap and multicast images used in origin e2e are unmaintained and were only built for x86.  In order to avoid the need for multi-arch overrides of these e2e test images, they need to be replaced by functionally equivalent multi-arch images.  These images are built and managed by QE and support multi-arch.

fyi auth team wrt ldap:
/cc @ibihim @s-urbaniak @slaskawi @stlaz 

fyi SDN team wrt multicast:
/cc @jluhrsen @astoycos 

To mirror images (required for testing):
/cc @soltysh @sttts

### CODE REVIEW

**Comment by yselkowitz** [comment]
found an issue with the new ldap image
/hold

**Comment by yselkowitz** [comment]
Issue was due to a strictness check introduced in the newer openldap version used by the newer image; added fix.
Leaving hold in place pending image mirroring which blocks CI testing.

**Comment by yselkowitz** [comment]
please mirror e2e images to allow CI testing to proceed
/assign @soltysh

**Comment by ibihim** [comment]
Does it use the [openshift/openldap](https://github.com/openshift/openldap/)? How do we manage version bumps to openldap?

**Review by soltysh — APPROVED** [review]
Mirroring completed
/lgtm
/approve

**Comment by yselkowitz** [comment]
@ibihim the `[sig-auth][Feature:LDAP][Serial] ldap group sync can sync groups from ldap [Suite:openshift/conformance/serial]` test is failing with a newer (F34-based) openldap.  Any ideas how to address the following error?

```
Jun 14 14:12:24.732: INFO: Error running /usr/bin/oc --namespace=e2e-test-ldap-group-sync-qvfng --kubeconfig=/path/to/auth/kubeconfig adm groups sync --sync-config=/tmp/staging1791230506/rfc2307/sync-config.yaml --confirm:
StdOut>
could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF
error: could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF
StdErr>
could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF
error: could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF

could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF
error: could not connect to the LDAP server: unable to read LDAP response packet: unexpected EOF
```

**Comment by yselkowitz** [comment]
aws-single-node failures were remnants from the worked-around RHCC v2s1 deprecation issue
/retest

**Comment by yselkowitz** [comment]
Parallel and serial suites have both passed.  Once this lands, we can rehearse removing `--from-repository` flags in 4.12 multi-arch jobs.
/cc @deepsm007 @aleskandro

**Comment by yselkowitz** [comment]
single-node tests require a separate workaround for the RHCC v2s1 decommissioning: https://github.com/openshift/release/pull/30412.  But the other tests which have passed already cover all the affected suites.

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
