### PR TITLE
Use tags consistently in top-level extended tests descriptions

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/4961

### CODE REVIEW

**Comment by soltysh** [comment]
Rename job subdirectory to jobs and LGTM.

**Comment by mfojtik** [comment]
@smarterclayton @stevekuznetsov PTAL

**Comment by smarterclayton** [comment]
Beyond Maciej's comment looks good to me

**Comment by stevekuznetsov** [comment]
LGTM.

**Comment by stevekuznetsov** [comment]
Do we have a doc about how to correctly summon the bot?

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
@stevekuznetsov I don't think so but I plan to write the commands into HACKING.md

**Pull request merged**
