### PR TITLE
no need to build networking pkg in build-tests session

### PR DESCRIPTION
**Pull request by guangxuli**
I don't  think we  need a separate building this module for testing，there is no *_test.go file in networking directory.

### CODE REVIEW

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/blob/master/test/extended/networking/services.go is a test file.

**Comment by smarterclayton** [comment]
We do the build here to ensure there are no coding errors in infrequently run packages (so someone calling `make verify` can ensure their code compiles).

**Comment by guangxuli** [comment]
When run hack/build-go.sh test/extended/extended.test,  I think netwoking dir has been built. no need build again.

**Comment by smarterclayton** [comment]
Yeah, looks like that was changed.  Thanks!

LGTM [merge]

**Pull request merged**
