### PR TITLE
tolerate already exists for imagestream update test prep

### PR DESCRIPTION
**Pull request by deads2k**
May fix https://bugzilla.redhat.com/show_bug.cgi?id=1732622

/assign @adambkaplan

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why is this appropriate?

**Comment by deads2k** [comment]
serial flake on a different test

/retest

**Comment by bparees** [comment]
@dmage fyi.  this appears to be an attempt to fix https://bugzilla.redhat.com/show_bug.cgi?id=1731254

**Comment by bparees** [comment]
this change is low risk, only touches test code, and the test in question passed the CI job already.  Manually merging because this is a frequent flake impacting our merge queue.

**Pull request merged**
