### PR TITLE
UPSTREAM: 46112: apimachinery: move unversioned registration to metav1

### LINKED ISSUE #14574: Origin generated clients can't decode a valid server v1.Status
`v1.Status` is not registered in the `pkg/image/clientset/scheme` because Status isn't an unversioned resource.  This is with the versioned generated image stream client in Origin master.  The server is allowed to return `v1.Status`, so this is either a bug in the generation code or the registration.

```
oc push binary /tmp/file --to=test:bar --loglevel=8
I0611 14:12:57.408057    6177 loader.go:354] Config loaded from file /Users/clayton/projects/origin/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0611 14:12:57.409747    6177 cached_discovery.go:118] returning cached discovery info from /Users/clayton/.kube/192.168.1.105_8443/servergroups.json
I0611 14:12:57.410018    6177 request.go:991] Request Body: {"kind":"ImageStreamTagClone","apiVersion":"image.openshift.io/v1","metadata":{"name":"test:bar","namespace":"default","creationTimestamp":null},"addLayer":true}
I0611 14:12:57.410070    6177 round_trippers.go:383] POST https://192.168.1.105:8443/apis/image.openshift.io/v1/namespaces/default/imagestreamtags/test:bar/clone
I0611 14:12:57.410075    6177 round_trippers.go:390] Request Headers:
I0611 14:12:57.410079    6177 round_trippers.go:393]     User-Agent: oc/v1.6.1+5115d708d7 (darwin/amd64) kubernetes/010d313
I0611 14:12:57.410083    6177 round_trippers.go:393]     Accept: application/json, */*
I0611 14:12:57.410086    6177 round_trippers.go:393]     Content-Type: application/json
I0611 14:12:57.435613    6177 round_trippers.go:408] Response Status: 409 Conflict in 25 milliseconds
I0611 14:12:57.435624    6177 round_trippers.go:411] Response Headers:
I0611 14:12:57.435627    6177 round_trippers.go:414]     Cache-Control: no-store
I0611 14:12:57.435630    6177 round_trippers.go:414]     Content-Type: application/json
I0611 14:12:57.435632    6177 round_trippers.go:414]     Content-Length: 264
I0611 14:12:57.435635    6177 round_trippers.go:414]     Date: Sun, 11 Jun 2017 18:12:57 GMT
I0611 14:12:57.435657    6177 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"imagestreamtags.image.openshift.io \"test:bar\" already exists","reason":"AlreadyExists","details":{"name":"test:bar","group":"image.openshift.io","kind":"imagestreamtags"},"code":409}
I0611 14:12:57.435708    6177 request.go:1190] body was not decodable (unable to check for Status): no kind "Status" is registered for version "v1"
F0611 14:12:57.435735    6177 helpers.go:119] error: unable to clone the image: the server reported a conflict (post imageStreamTags.image.openshift.io test:bar)
```

Code looks the same in upstream kube.

@sttts @deads2k

### PR DESCRIPTION
**Pull request by sttts**
Fixes #14574

### CODE REVIEW

**Comment by sttts** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by sttts** [comment]
Tito flake https://github.com/openshift/origin/issues/14122

**Comment by sttts** [comment]
re[test]
re[merge]

**Pull request merged**
