### PR TITLE
Bug 1806407: Improve upgrade availability tests and add sequential upgrade input

### PR DESCRIPTION
**Pull request by smarterclayton**
See commits for details, backporting to allow testing of our backports for upgrade
availability.

### CODE REVIEW

**Comment by smarterclayton** [comment]
4.3 will be bug 1806408

**Comment by smarterclayton** [comment]
/hold

Until I get a passing 4.1 to 4.2 to 4.3 to 4.5 run in master (at which point I will backport all related changes)

**Comment by smarterclayton** [comment]
/hold cancel

Should be ready for merge, has all of the key fixes.

**Comment by smarterclayton** [comment]
(the tests are now going green in master as we land the most recent set of downtime mitigations)

**Comment by smarterclayton** [comment]
Merging to unblock 4.1 to 4.2 to 4.3 to 4.4 testing

**Comment by danehans** [comment]
https://github.com/openshift/origin/pull/24726 backports this PR to 4.3 due to the [merge conflict](https://github.com/openshift/origin/pull/24589#issuecomment-595433938).

**Pull request merged**
