### PR TITLE
UPSTREAM: 43396: iSCSI CHAP support

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by rootfs** [comment]
@sttts can you take a look? thanks!

**Comment by rootfs** [comment]
[test]

**Comment by sttts** [comment]
@rootfs as far as I can judge (am not in the storage code very much) this looks good

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
thanks @sttts !

**Comment by childsb** [comment]
[merge]

**Comment by rootfs** [comment]
FLAKE https://github.com/openshift/origin/issues/14172

**Comment by rootfs** [comment]
FLAKE #https://github.com/openshift/origin/issues/14161

**Comment by liggitt** [comment]
this picked API changes and did not update generated deep copies, defaulting, or conversions. that means the API changes picked in are non-functional. We have to include tests that exercise picked function to ensure that it behaves as expected.

**Pull request merged**
