### PR TITLE
use replicated zookeeper template

### PR DESCRIPTION
**Pull request by ibotty**

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM, thanks @ibotty !

**Comment by danmcp** [comment]
@ibotty Can you please squash your commits.

**Comment by smarterclayton** [comment]
Squash if you can and then I'll merge

**Comment by ibotty** [comment]
Sorry for not getting back to it. I missed @danmcp's message.

What do you think about abusing hostPorts for ensuring that only on pod is run per node? Nodes will most likely be firewalled but it's one external port to worry about. It might be better to use the scheduler policy for that kind of thing.

**Comment by smarterclayton** [comment]
Eventually we'll have pod exclusion constraints, so not terribly worried.
Is there a particular reason that you have to enforce one per node?
Regular scheduler policy will usually do that anyway.

**Comment by ibotty** [comment]
As is, the example does not use persistent storage. If two zookeeper
instances are on the same (openshift) node and the node goes down, two
of the three zookeeper instances get restarted with empty state. They
will have a quorum, that state is empty and hilarity ensues.

**Comment by smarterclayton** [comment]
Ok, I think we can live with that for right now.

**Comment by ibotty** [comment]
I will update the Readme to mention that and the "scaling" story (create
zookeeper-N services) later today

**Comment by ibotty** [comment]
Just checking in, what the status is?

**Pull request closed without merging**
