### PR TITLE
Bugzilla 1693023: Add CSRF to token request endpoint [3.9] 

### PR DESCRIPTION
**Pull request by stlaz**
This is a 3.9 backport of #22767 which adds CSRF validation to OAuth server token requests created from its web console.

cc @enj

csrf check tested with openshift start master
contains only necessary changes to wrap the token request with csrf and set the standard security headers

### CODE REVIEW

**Comment by stlaz** [comment]
Test failures:
- `gcp`:
```
TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ***
Thursday 13 June 2019  15:13:46 +0000 (0:00:00.446)       0:16:49.288 ********* 
fatal: [prtest-20891fe-1226-ig-m-m5bk]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.11"}
```
^--- test misconfiguration? How else could 3.11 pop in there...
- Travis - Unbound variable in `hack/lib/constants.sh` -> looks like Travis builds are broken

**Comment by stlaz** [comment]
/test gcp
Lets' see whether the gcp failure is consistent

**Comment by p0lyn0mial** [comment]
@stlaz I fixed ` Unbound variable in hack/lib/constants.sh` in https://github.com/openshift/origin/pull/23485/commits/ee6e7e8d9ee9cfc0b078ffe41c8bfa95a2ff35cc

**Comment by p0lyn0mial** [comment]
@stlaz `ci/openshift-jenkins/gcp ` seems to be failing due to `An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.11`. 

I think it never worked, see: https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_extended_conformance_gce_39

I run into the same issues in my pull https://github.com/openshift/origin/pull/23485

**Pull request closed without merging**
