### PR TITLE
Rebase to latest Kubernetes

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@ironcladlou please review the event store changes as well as the upstream issue I created to add GetByKey.

**Comment by ironcladlou** [comment]
@smarterclayton 
>@ironcladlou please review the event store changes as well as the upstream issue I created to add GetByKey.

That looks cool. I agree that the change is a good idea to provide the most flexibility.

**Pull request merged**
