### PR TITLE
Fix cookie generation scheme. Use hex encoding instead of md5

### PR DESCRIPTION
**Pull request by rajatchopra**
https://github.com/openshift/openshift-sdn/issues/88

### CODE REVIEW

**Comment by liggitt** [comment]
Is this a commit from the upstream repo? If so, rename the commit to "bump(commit id) dependency"

If not, don't update godeps.json

**Comment by rajatchopra** [comment]
@smarterclayton Approval please. Needed for 3.0 release.

**Comment by smarterclayton** [comment]
This needs to be UPSTREAM unless it changes godeps.

**Comment by liggitt** [comment]
UPSTREAM == patch which still needs to go upstream, should not update godeps.json

bump == update to commit in upstream repo, should update godeps.json

**Comment by rajatchopra** [comment]
Godep.json is part of this PR.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
