### PR TITLE
Backport logs with attach

### PR DESCRIPTION
**Pull request by ncdc**
@smarterclayton @mfojtik @soltysh @liggitt xref #11240 #12558

### CODE REVIEW

**Comment by ncdc** [comment]
I haven't touched any tests yet. Let me know what needs changing since things have evolved since I was last in there.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
I believe @soltysh added set +e around the failing tests

**Comment by smarterclayton** [comment]
in test/end-to-end/core.sh

**Comment by smarterclayton** [comment]
I think just revert 5696d6d9de6faf986beb6ba30d70dbd4d92048f6

**Comment by soltysh** [comment]
If the problem persists, and from what I've seen it's still there I'll look into that bug more. Otherwise this LGTM, except for that change Clayton asked for.

**Comment by ncdc** [comment]
Talked to @soltysh on irc. We're going to merge this as-is, but keep the changes to the tests that allow the in-cluster configuration tests to fail without erroring. We'll let jenkins run tests for a few days and then check to see if this PR has resolved the issue or if it's still happening.

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
