### PR TITLE
use env var for registry config arg value

### PR DESCRIPTION
**Pull request by pweil-**
Fixes https://github.com/openshift/origin/issues/3686

Allow the ability to easily override the config file location in the deployment config.  Changes the main path to only use an argument and changes the dockerfile entrypoint to take that argument from an environment variable.

@ncdc @liggitt - what do you think of this approach?

```
oadm registry --credentials="$KUBECONFIG" --create --images=openshift/origin-docker-registry

[vagrant@openshiftdev origin]$ oc edit dc/docker-registry
deploymentconfigs/docker-registry

{
   "name": "REGISTRY_CONFIGURATION_PATH",
   "value": "/tmp/badfile.yaml"
}



[vagrant@openshiftdev origin]$ docker logs 8661
time="2015-07-22T14:24:48Z" level=fatal msg="Unable to open configuration file: open /tmp/badfile.yaml: no such file or directory"
```

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by ncdc** [comment]
Interesting... :smile:

**Comment by ncdc** [comment]
LGTM. This retains support for specifying the config file as a command line arg, and fixes the env var issue.

**Comment by smarterclayton** [comment]
Agree it looks a little weird but [merge]

**Pull request merged**
