### PR TITLE
Align with other cli descriptions

### PR DESCRIPTION
**Pull request by YuPengZTE**
image

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by YuPengZTE** [comment]
./hack/update-generated-docs.sh has run

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/10773 re[test]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
