### PR TITLE
Clean up sysconfig files and service units

### PR DESCRIPTION
**Pull request by sdodson**
All config values have been moved to configuration files so we're paring these files down considerably.

### CODE REVIEW

**Comment by sdodson** [comment]
@liggitt pulled that one commit we'd discussed into PR and cleaned up other items.
@detiber PTAL

Setting CONFIG_FILE in /etc/sysconfig/openshift-node will override the default that's set in the service. I think this mostly gets us to a place where an all in one install requires no modification but will allow us to place config files wherever we please.

I'd like to test this after #1611 lands

**Comment by sdodson** [comment]
I'm also fine with getting rid of the /etc/sysconfig/* files and simply pointing the services at /etc/openshift/{master,node-config.yaml} respectively but I don't think the config files would support that in their current form.

**Comment by detiber** [comment]
@sdodson lgtm

I like the idea of keeping /etc/sysconfig/openshift-{node,master} around, it allows us to be more flexible in where the config files are located.

**Comment by sdodson** [comment]
Hmm, I just noticed that we're getting away from a situation where you can install the two rpms, start both services, and expect things to work. I think that, along with easily generating custom configuration files and substituting them, should be our primary goal for the RPM packaging.

**Comment by detiber** [comment]
@sdodson, what if we generated a failure message if the config file is not present, giving the user some info on how to generate it (or where to look to find out how to generate it)?

Better to not start and tell the user how to get going rather than them getting a config that appears to work, but will cause them issues when they try to reconfigure it (Thinking mostly along the lines of things that could be stored in etcd, especially node config info)

**Comment by sdodson** [comment]
The node will fail to start with this error message so it's clear what's happened, though it doesn't provide any remedy, I think this is probably good to go, we can improve the error messaging in the future.

```
Apr 08 10:25:02 ose3.os1.phx2.redhat.com openshift[17487]: F0408 10:25:02.734561   17487 start_node.go:77] open /var/lib/openshift/openshift.local.certificates/node-ose3.os1.phx2.redhat.com/node-config.yaml: no such file or directory
```

**Comment by sdodson** [comment]
@sosiouxme This moves all configuration to node and master configuration files. Paths to those config files can be updated in /etc/sysconfig/openshift-{master,node}

Mind sanity checking and merging?

**Comment by sosiouxme** [comment]
Looks fine to me, recommend for [merge].

I'm not super fond of having the location of the file depend on the host/node name (which as we've seen can be fickle). I would prefer at some point that the installer create a symlink e.g. /var/lib/openshift/openshift.local.certificates/node/ or /etc/openshift/node points to /var/lib/openshift/openshift.local.certificates/node-${node-fqdn} and just use a static default.

**Comment by sdodson** [comment]
I was going to make it point to /etc/openshift/node-config.yaml and leave creating that up to someone else, but I believe as of right now the config file uses relative paths.

**Comment by liggitt** [comment]
the path to the config file (`--config=foo.yaml`) can be relative or absolute (relative paths are resolve relative to the working directory)

file references inside the config file can be relative or absolute (relative paths are resolved relative to the location of the config file)

**Comment by liggitt** [comment]
I think `/etc/openshift/node-config.yaml` is a reasonable default. If someone runs `create-node-config` and copies the resulting directory to `/etc/openshift/` on the node, that should work fine

**Comment by sdodson** [comment]
@liggitt I think we found that not to be the case, but we'll check again and let you know.

**Comment by liggitt** [comment]
@sdodson please do... the intent of create-node-config was to create a portable config folder

**Comment by sdodson** [comment]
@liggitt looks like copying the node directory to /etc/openshift/node and pointing the node to /etc/openshift/node/node-config.yaml works just fine, thanks for clarifying.

**Comment by sosiouxme** [comment]
Yeah, you can't just copy the file as the relative refs won't work. copy/symlink the whole directory, or make the references absolute (but best not to tinker with the file so whole directory is best).

**Comment by smarterclayton** [comment]
Reopen if you plan on fixing this still.

**Pull request closed without merging**
