### PR TITLE
[release-4.1] WIP: Bug 1769951: Get 4.1.z tests working again

### PR DESCRIPTION
**Pull request by adambkaplan**
Update to use centos/ruby-25-centos7 image

### CODE REVIEW

**Comment by bparees** [comment]
/hold

this has never passed, please investigate the failure before unholding.

**Comment by stlaz** [comment]
@adambkaplan since you're fixing tests in this PR, please also include the unittest fixes from https://github.com/openshift/origin/pull/24124 - Golang 1.11 fixed a vulnerability which requires ports to be a valid integer.

It's yet to be found what's wrong with the cmd tests, or I am not aware of any PR fixing them yet

**Comment by adambkaplan** [comment]
@soltysh `test-cmd` is still very broken, and it's failing on tests that frankly don't feel relevant. Do we just drop those?

**Comment by eparis** [comment]
this should be closed after #24176 merged, right?

**Comment by adambkaplan** [comment]
/close

Replaced by #24176

**Pull request closed without merging**
