### PR TITLE
Add ethtool to our deps

### PR DESCRIPTION
**Pull request by kargakis**
@ncdc @sdodson @smarterclayton 

Closes https://github.com/openshift/origin/issues/4843

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [test]

**Comment by sdodson** [comment]
LGTM

**Comment by kargakis** [comment]
re[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Also add to the base AMI in vagrant-openshift as a separate issue

**Pull request merged**
