### PR TITLE
Change how the router was logging

### PR DESCRIPTION
**Pull request by smarterclayton**
[merge]

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton this looks out of place... can the filesystem flake out?

```
00:38:08.761 TASK [openshift-volume-quota : Create filesystem for /var/lib/origin/openshift.local.volumes] ***
00:38:08.761 Sunday 12 February 2017  01:59:46 +0000 (0:00:00.261)       0:04:44.738 ******* 
00:38:09.155 fatal: [ci-prtest519-ig-n-76kj]: FAILED! => {"changed": false, "failed": true, "msg": "Device /dev/sdc not found."}
```

**Comment by smarterclayton** [comment]
There's an issue open, it's not clear whether this is a RHEL issue or a gce
setup wait issue

On Feb 12, 2017, at 11:21 AM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> this looks out of
place... can the filesystem flake out?

00:38:08.761 TASK [openshift-volume-quota : Create filesystem for
/var/lib/origin/openshift.local.volumes] ***
00:38:08.761 Sunday 12 February 2017  01:59:46 +0000 (0:00:00.261)
  0:04:44.738 *******
00:38:09.155 fatal: [ci-prtest519-ig-n-76kj]: FAILED! => {"changed":
false, "failed": true, "msg": "Device /dev/sdc not found."}

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12921#issuecomment-279229248>,
or mute
the thread

**Comment by smarterclayton** [comment]
openshift/origin-gce#14

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
