### PR TITLE
Release tar should contain smaller oc

### LINKED ISSUE #3823: `oc` binary not in release output zip

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #3823

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton yeah, I tried the same and it seems to fix the issue. Just have to make sure it's in the origin-release image when building the release.

**Comment by fabianofranz** [comment]
LGTM

**Comment by smarterclayton** [comment]
It was

On Fri, Jul 24, 2015 at 1:00 PM, Fabiano Franz <notifications@github.com>
wrote:

> LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3900#issuecomment-124579230>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
[merge]

On Fri, Jul 24, 2015 at 1:04 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> It was
>
> On Fri, Jul 24, 2015 at 1:00 PM, Fabiano Franz <notifications@github.com>
> wrote:
>
>> LGTM
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3900#issuecomment-124579230>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by akostadinov** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1244169 , current linux download is far from ideal at least on a linux system. I know that windows also supports symlinks btw (but I don't know if any archive tool supports these). Perhaps for windows an installer can provide best result where it could install only selected tools and link `oc` and/or `oadm` to `openshift` when appropriate.

**Pull request merged**
