### PR TITLE
Rebase Kube to v1.0.0

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Drops v1beta3 upstream

**Comment by smarterclayton** [comment]
Nevermind, it does not.

**Comment by liggitt** [comment]
I was going to say… I got scared by the upstream PR until I realized it just got disabled by default

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Hrm, serial cert error...

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
