### PR TITLE
bump(github.com/openshift/source-to-image) cfd95f2873bf687fbd2a4f32721462200d1b704a

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[merge] 
(got a lgtm from @csrwng elsewhere)

**Comment by bparees** [comment]
[merge]

**Comment by csrwng** [comment]
@bparees seems you missed a package from STI

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@csrwng yeah, i thought this was supposed to add all the new packages?
godep update github.com/openshift/source-to-image/pkg/...

but i ended up having to add the new package to Godeps.json manually...  what am i missing?

**Comment by bparees** [comment]
@csrwng maybe i needed to use godep save since there was a new package

**Comment by csrwng** [comment]
I would think so too, but it seems like it's only updating packages that
are already in Godeps, that's not cool because a 'Godep save' won't do the
trick either unless we manually re-apply the kube patches.

**Pull request merged**
