### PR TITLE
sync openshift-sdn for code reorg

### PR DESCRIPTION
**Pull request by danwinship**
The origin side of https://github.com/openshift/openshift-sdn/pull/305

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by danwinship** [comment]
[test]

**Comment by pravisankar** [comment]
Origin changes LGTM

**Comment by dcbw** [comment]
LGTM [merge]

**Comment by pravisankar** [comment]
re[merge]

**Comment by danwinship** [comment]
try this again... [merge]

**Comment by dcbw** [comment]
• [SLOW TEST:42.134 seconds]
[networking] services
/data/src/github.com/openshift/origin/test/extended/networking/services.go:68
  when using a multi-tenant plugin
  /data/src/github.com/openshift/origin/test/extended/networking/util.go:193
    should prevent connections to pods in different namespaces on the same node via service IPs
    /data/src/github.com/openshift/origin/test/extended/networking/services.go:44
------------------------------
E0624 20:26:12.523859   29644 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0624 20:31:12.539255   29644 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0624 20:36:12.554605   29644 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by danwinship** [comment]
Yeah, but the test is *supposed* to time out (because the packets get dropped by the isolation rules). And anyway, the test passed as part of [test], so it looks like the merge failure was a flake.

Let's try rebasing and retrying...

**Comment by danwinship** [comment]
extended networking tests currently failing for everyone... (#9599)

**Comment by danwinship** [comment]
networking integration tests pass locally, and have been disabled in jenkins for now, so...
[merge]

**Comment by danwinship** [comment]
[test]

**Comment by danwinship** [comment]
[merge]

**Comment by knobunc** [comment]
[merge]

**Comment by danwinship** [comment]
hey! @openshift-bot! [merge]

**Pull request merged**
