### PR TITLE
Remove experimental `oc import docker-compose`

### PR DESCRIPTION
**Pull request by smarterclayton**
Please use Kompose instead

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by bparees** [comment]
can pkg/generate/dockercompose/generate.go not also go away?

**Comment by bparees** [comment]
nm, cntrl-f is lying to me.

**Comment by bparees** [comment]
lgtm

**Comment by mfojtik** [comment]
LGTM

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] some old flakes

**Pull request merged**
