### PR TITLE
prevent privilege escalation

### PR DESCRIPTION
**Pull request by deads2k**
Prevent a user who has rights to modify role bindings from binding a user to a role that has more power than the granting user has.

/cc @liggitt

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton comments up to "prevent escalation" addressed.

**Comment by deads2k** [comment]
@smarterclayton created a rolebinding.Registry to abstract out the ugly from rolebinding/rest.go.  It felt more registry-like.  If you agree with the approach, I'll fill in unit tests.

**Comment by deads2k** [comment]
Plumbed kapi.Context through the authorizer.  I think it really hurts readability, especially in places where there is logically more than one context in play and in places where only part of the context is used.  It ends up reading like a magic container.

@liggitt Your thoughts on the "plumb context through authorizer" commit?

**Comment by deads2k** [comment]
@smarterclayton I think I made it through all the comments.  The only one I don't feel good about is plumbing context through the authorizer.  It feels like I've gone from a way of passing arguments that allows the compiler to ensure that I'm passing the correct data where its required and I've replaced with with a way of passing through a data object that is mostly blackblox, that sometimes needs certain fields and sometimes needs others, and destroys the compiler's ability to help me write valid code without having runtime failures.

**Comment by deads2k** [comment]
[test]

**Comment by smarterclayton** [comment]
If the authorizer is making nested calls it needs to be using the context of the person who called it.  A context is the thread that ties an incoming request from the client across all the backend systems that fulfill it.  See https://godoc.org/golang.org/x/net/context and http://research.google.com/pubs/pub36356.html for why we use contexts.

----- Original Message -----

**Comment by smarterclayton** [comment]
You can hide the context underneath your getters if necessary - it doesn't have to be a field on the object.  It just has to be preserved.

----- Original Message -----

**Comment by deads2k** [comment]
jenkins failed in test-integration on `TestSimpleImageChangeBuildTrigger`.  re[test]?

**Comment by smarterclayton** [comment]
Squash and you'll get a merge.

**Comment by deads2k** [comment]
squashed.

**Comment by smarterclayton** [comment]
Hope I don't regret this... LGTM [merge]

**Pull request merged**
