### PR TITLE
Move env and volume to a new 'oc set' subcommand

### PR DESCRIPTION
**Pull request by smarterclayton**
Leave aliases at the old commands. Ensure policy and set have
good descriptions for their commands.  Removes `stop`, enables `apply`.

@kargakis if you can review

### CODE REVIEW

**Comment by smarterclayton** [comment]
Sets the stage for things like `oc set deployment-hooks` and `oc set build-hooks`.

**Comment by smarterclayton** [comment]
Also finally nuked "stop".

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge] post review please (since this is just a refactor), will deal with anything in follow up

**Comment by kargakis** [comment]
LGTM

**Comment by smarterclayton** [comment]
[test]

**Comment by kargakis** [comment]
@fabianofranz @smarterclayton we should upstream these commands, they will be added anyway

https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deploy.md#kubectl-set

**Comment by smarterclayton** [comment]
Yes, I'm the one who is going to probably upstream them.

**Pull request merged**
