### PR TITLE
DO NOT MERGE - Test PR only

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@bparees i think image_ecosystem is permabroken in 3.10 somehow.

**Comment by smarterclayton** [comment]
Did we fix something in master that isn’t in Ansible 3.10 branch?  I’m seeing master passes.

**Comment by bparees** [comment]
>  @bparees i think image_ecosystem is permabroken in 3.10 somehow.

need to cherry pick https://github.com/openshift/origin/pull/20021.  Working on it.

**Pull request closed without merging**
