### PR TITLE
Fix for nav bar issues on resize.

### PR DESCRIPTION
**Pull request by sg00dwin**
https://github.com/openshift/origin/issues/4404

- Styling details of filter, add to project, and toggle menu
- Use of flex for positioning

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres mobile nav fixes

**Comment by jwforres** [comment]
LGTM but needs bindata

**Comment by sg00dwin** [comment]
@jwforres bindata added

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
