### PR TITLE
Added a mention of TEST_ONLY to extended test doc

### PR DESCRIPTION
**Pull request by oatmealraisin**
@stevekuznetsov ptal?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
LGTM. can merge after code freeze

**Comment by oatmealraisin** [comment]
@stevekuznetsov Do you have merge rights?

**Comment by stevekuznetsov** [comment]
Freeze is not yet over

**Comment by oatmealraisin** [comment]
@stevekuznetsov merge?

**Comment by stevekuznetsov** [comment]
[merge]

**Pull request merged**
