### PR TITLE
Fix variable name for virtualbox Vagrant

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
This fixes following error:

```
→ vagrant up
Bringing machine 'openshiftdev' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```

**Comment by mfojtik** [comment]
@rajatchopra PTAL

**Comment by pweil-** [comment]
@rajatchopra I'm curious to why the base box was changed.  Probably to support some of the networking pieces?  IIRC, there were some optimizations made by @ironcladlou to the file system in the old box to help speed things up a bit.  We probably want to integrate your changes into his box or the other way around.

Also, it seems that in the single machine environment that the new base box isn't provisioned the same as the old base box.  Building wasn't working because golang wasn't available.

**Comment by mfojtik** [comment]
@pweil- yeah you have to run `sh hack/provision-full.sh` in order to get all required rpms... That used to ran after the vagrant up as a provisioner shell, dunno what happened there.

**Comment by rajatchopra** [comment]
@pweil- Correct, a newer box was needed for the networking pieces. On my TODO to sync with storage optimzations by @ironcladlou. 
@mrunalp FYI

**Comment by mfojtik** [comment]
@rajatchopra is this a legit fix? so it could be merged?

**Comment by pmorie** [comment]
@mfojtik I would prefer to use either `name` or `box_name` throughout, not mix them.

**Comment by smarterclayton** [comment]
I bought Paul's argument this time.

**Comment by mfojtik** [comment]
@pmorie +1

**Comment by smarterclayton** [comment]
Thanks for everyone jumping on this - next time vote and elect a victor to get into master :)

**Pull request closed without merging**
