### PR TITLE
Tag origin to 3.7

### PR DESCRIPTION
**Pull request by smarterclayton**
This commit was necessary for builds and contains the origin 3.7 tag.

### CODE REVIEW

**Comment by smarterclayton** [comment]
/retest

origin-gce image has been updated

**Comment by smarterclayton** [comment]
Wtf

```

     Play:     Determine openshift_version to configure on first master
     Task:     openshift_version : Get available origin version
     Message:  {u'package_found': False, u'returncode': 1, u'stdout':
u'Could not parse metalink
https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64
error was \nNo timestamp for file\n', u'cmd': u'/usr/bin/repoquery
--plugins --quiet --pkgnarrow=repos
--queryformat=%{version}|%{release}|%{arch}|%{repo}|%{version}-%{release}
--config=/tmp/tmpj_utiR origin', u'results': {}, u'stderr': u'File
/var/cache/yum/x86_64/7/epel/metalink.xml does not exist\n'}
++ export status=FAILURE
++ status=FAILURE

```

**Comment by smarterclayton** [comment]
Wtf

```
     Play:     Determine openshift_version to configure on first master
     Task:     openshift_version : Get available origin version
     Message:  {u'package_found': False, u'returncode': 1, u'stdout':
u'Could not parse metalink
https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64
error was \nNo timestamp for file\n', u'cmd': u'/usr/bin/repoquery
--plugins --quiet --pkgnarrow=repos
--queryformat=%{version}|%{release}|%{arch}|%{repo}|%{version}-%{release}
--config=/tmp/tmpj_utiR origin', u'results': {}, u'stderr': u'File
/var/cache/yum/x86_64/7/epel/metalink.xml does not exist\n'}
++ export status=FAILURE
++ status=FAILURE
```

**Comment by smarterclayton** [comment]
install_update is now failing due to:

```
########## STARTING STAGE: INSTALL ORIGIN ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@3/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@3/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/43507a98bd8a594572430310e0d37d1b64453113
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/43507a98bd8a594572430310e0d37d1b64453113
++ export PATH=/var/lib/jenkins/origin-ci-tool/43507a98bd8a594572430310e0d37d1b64453113/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/43507a98bd8a594572430310e0d37d1b64453113/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@3/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@3/.config
++ mktemp
+ script=/tmp/tmp.7wPXyjTbIs
+ cat
+ chmod +x /tmp/tmp.7wPXyjTbIs
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.7wPXyjTbIs openshiftdevel:/tmp/tmp.7wPXyjTbIs
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "timeout 1800 /tmp/tmp.7wPXyjTbIs"'
+ cd /data/src/github.com/openshift/aos-cd-jobs
+ sudo rm -f /etc/yum.repos.d/origin_ci_tool_tmp.repo
+ [[ -s /etc/yum.repos.d/centos-paas-sig-openshift-origin36-rpms.repo ]]
+ echo 'exclude=origin*'
+ sudo tee -a /etc/yum.repos.d/centos-paas-sig-openshift-origin36-rpms.repo
exclude=origin*
++ cat ./PKG_NAME
+ pkg_name=origin
+ [[ origin == \o\r\i\g\i\n ]]
+ deployment_type=origin
+ echo origin
++ cat ORIGIN_BUILT_VERSION
+ sudo python sjb/hack/determine_install_upgrade_version.py origin-3.7.0-0.alpha.0.117.7760ee3.x86_64 --dependency_branch master
[ERROR] Can not determine install and upgrade version for the `origin` package
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ORIGIN [00h 00m 03s] ##########
```

**Comment by smarterclayton** [comment]
Templates is failing with 

```
An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7
```

**Comment by smarterclayton** [comment]
The retest bot has gone insane, it should not be rate limited on retries
here.

**Comment by smarterclayton** [comment]
Now egress router build is broken.

**Comment by smarterclayton** [comment]
/retest

Have all of the latest changes

**Comment by smarterclayton** [comment]
@stevekuznetsov

**Comment by smarterclayton** [comment]
Failed on the same thing I thought we fixed yesterday.

**Comment by stevekuznetsov** [comment]
Ah, hoisted by my own petard. I had a failsafe in there. Updated.

/retest

**Comment by stevekuznetsov** [comment]
@smarterclayton maybe I'm missing something but `yum` is not picking up the repo update ... the AMI now ships with the exclusion in the repofile, so we do:

```
+ sudo sed -i '/exclude=origin*/d' /etc/yum.repos.d/centos-paas-sig-openshift-origin36-rpms.repo
+ sudo yum clean all
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Cleaning repos: centos-paas-sig-openshift-origin13-rpms
              : centos-paas-sig-openshift-origin14-rpms
              : centos-paas-sig-openshift-origin15-rpms
              : centos-paas-sig-openshift-origin36-rpms epel li li-rhscl
              : openshift-ansible-local-release ops-rpm origin-deps-rhel7
              : origin-local-release oso-rhui-rhel-server-extras
              : oso-rhui-rhel-server-releases
              : oso-rhui-rhel-server-releases-optional
              : oso-rhui-rhel-server-rhscl rhel-7-server-ose-3.1-rpms
              : rhel-7-server-ose-3.2-rpms rhel-7-server-ose-3.3-rpms
              : rhel-7-server-ose-3.4-rpms rhel-7-server-ose-3.5-rpms
              : rhel-7-server-ose-3.6-rpms rhui-REGION-client-config-server-7
              : rhui-REGION-rhel-server-releases
              : rhui-REGION-rhel-server-rh-common
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
+ sudo yum makecache
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Metadata Cache Created
+ sudo yum list --showduplicates origin
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Available Packages
origin.x86_64 1.3.3-1.el7                 centos-paas-sig-openshift-origin13-rpms
origin.x86_64 1.4.1-1.el7                 centos-paas-sig-openshift-origin14-rpms
origin.x86_64 1.5.0-0.6                   centos-paas-sig-openshift-origin15-rpms
origin.x86_64 1.5.0-0.7.rc1               centos-paas-sig-openshift-origin15-rpms
origin.x86_64 1.5.0-1.el7                 centos-paas-sig-openshift-origin15-rpms
origin.x86_64 1.5.0-1.1.el7               centos-paas-sig-openshift-origin15-rpms
origin.x86_64 1.5.1-1.el7                 centos-paas-sig-openshift-origin15-rpms
origin.x86_64 3.7.0-0.alpha.0.199.86c0719 origin-local-release      
```

**Comment by stevekuznetsov** [comment]
for crying out loud, not right now EPEL

/retest

**Comment by stevekuznetsov** [comment]
@smarterclayton @sdodson that one installed and upgraded successfully. Lots of HAProxy issues though. You should take a look

**Comment by smarterclayton** [comment]
There's a router pod that hasn't pulled an image:

```
Aug 11 12:54:06.791: INFO: router-2-3mj64                                            ip-172-18-14-137.ec2.internal  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-08-11 12:37:26 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-08-11 12:37:26 -0400 EDT ContainersNotReady containers with unready status: [router]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-08-11 12:37:26 -0400 EDT  }]
```

/retest

Could be a bad image.

**Comment by smarterclayton** [comment]
verify check in openshift-ansible failed because of epel

/retest

**Comment by sdodson** [comment]
epel

/retest

**Comment by stevekuznetsov** [comment]
OH GOODNESS @smarterclayton @sdodson WE'RE DOING IT

**Pull request merged**
