### PR TITLE
Bug 1454550 - Do not double count the image* quota resources

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1454550

### CODE REVIEW

**Comment by mfojtik** [comment]
@derekwaynecarr i tested this locally, we store everything as legacy now so even if you create the image stream using YAML with APIVersion: image.openshift.io/v1 the quota will capture it and bump the counter.

Without this patch the counts will be doubled.

[test]

**Comment by deads2k** [comment]
We fixed this during the rebase https://github.com/sttts/origin/pull/94 and had trouble skipping the count by accident for /oapi.  How about an integration test?

**Comment by deads2k** [comment]
the fix lgtm, but @mfojtik should probably review since its my commit.

**Comment by mfojtik** [comment]
[merge][severity:bug]

will create follow up for integration test... tested this manually for now. (i'm merging @deads2k fix in case somebody wonder ;-)

**Comment by deads2k** [comment]
@sttts (when you get back) this got lost in the rebase somewhere.  Did we lose the test it was testing?

**Comment by mfojtik** [comment]
[merge][severity:bug]

fixed unit test.

**Comment by mfojtik** [comment]
[test]

**Pull request merged**
