### PR TITLE
SO-126: Sync the list of tests for s2i images with the image versions available in the library

### PR DESCRIPTION
**Pull request by metlos**
Syncing the list of the image stream tests with the actual imagestreams defined in the library. This is in preparation for the release of Samples Operator for OCP 4.17.

Release JIRA: https://issues.redhat.com/projects/SO/issues/SO-123
JIRA for this task: https://issues.redhat.com/projects/SO/issues/SO-126

### CODE REVIEW

**Comment by metlos** [comment]
@soltysh, can I ask for a review and eventual merge of this?

**Review by soltysh — APPROVED** [review]
/approve
/label tide/merge-method-squash

@metlos get someone from your team to lgtm the PR

**Pull request merged**
