### PR TITLE
New app envs

### PR DESCRIPTION
**Pull request by jhadvig**
Adding two new flags to the `new-app` command:
- `--bc-env` which adds desired environment variables to all generated buildConfigs
- `--dc-env` which adds desired environment variables to all generated deploymentConfigs

@csrwng PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why are we doing this?

**Comment by jhadvig** [comment]
@smarterclayton we have an issue for that https://github.com/openshift/origin/issues/4123

**Comment by smarterclayton** [comment]
See my comments in the issue - I don't think this is within the design intent of new-app

**Comment by jhadvig** [comment]
Closing this one in favor of https://github.com/openshift/origin/pull/4463

**Pull request closed without merging**
