### PR TITLE
Speed up extended network tests a bit by skipping sooner

### PR DESCRIPTION
**Pull request by danwinship**
We spend too much time doing setup on tests that we're going to skip... This cuts the time for a dind-cluster extended-networking check from 27m to 22m for me.

@marun?

### CODE REVIEW

**Comment by marun** [comment]
[test]

**Comment by marun** [comment]
@danwinship Nice work, lgtm!

**Comment by danwinship** [comment]
looks flaky to me.
[test] again!

**Comment by danwinship** [comment]
ok, looks like the conformance test is failing for everyone right now...

**Comment by pravisankar** [comment]
LGTM

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
