### PR TITLE
Dump router logs for debugging purposes in the scoped and weighted extended tests

### PR DESCRIPTION
**Pull request by ramr**
Debug logs for #12784

### CODE REVIEW

**Comment by ramr** [comment]
[test]

**Comment by ramr** [comment]
fix failures. [test]

**Comment by ramr** [comment]
[testextended]

**Comment by ramr** [comment]
ok now the router logs are always dumped. cleaned up the message logged. [test]
@knobunc  @smarterclayton  PTAL

**Comment by knobunc** [comment]
[merge]

**Comment by smarterclayton** [comment]
Force merge because we need to figure out what the cause is

**Pull request merged**
