### PR TITLE
make the api server start faster for integration tests

### PR DESCRIPTION
**Pull request by deads2k**
Starting the openapi endpoint even once takes about 6 seconds on my machine.  This fixes some noisy startup messages in an all-in-one and disables the openapi endpoint in integration tests only.

The config change is never serialized out, so we can remove it any time we wish.

### CODE REVIEW

**Comment by deads2k** [comment]
This took test-integration to 90 minutes

**Comment by liggitt** [comment]
this looks fine to me, short-term. @smarterclayton, how close are your openapi perf improvements (in terms of matching this speedup, and in terms of being mergeable)?

**Comment by smarterclayton** [comment]
This is fine for now, we can reeenable and retest once some of the other changes go through.  Using etcd2 is the next worst problem in terms of CPU used, and I'm going to be distracted this week.

**Comment by deads2k** [comment]
@stevekuznetsov  status reporting looks broken.  it tested green.

**Comment by kargakis** [comment]
Seeing some 405s in the plank log and to me Github seems to be the culprit (getting those unicorns regurarly today).  We need informers in the plank controller so we can get a sane retry mechanism. Do you have an example for generating them for a TPR?

**Comment by kargakis** [comment]
Or we can retry just the github call for now.

**Comment by kargakis** [comment]
You got lucky by getting merged by a batch job.

**Comment by smarterclayton** [comment]
So at some point today we went from taking 90m in integration.... back to 120+m.  It happened around 2pm today.

**Comment by smarterclayton** [comment]
Which is right about when this merged.

**Comment by stevekuznetsov** [comment]
"faster"

**Comment by deads2k** [comment]
> Which is right about when this merged.



> "faster"

I'm seeing most around 90 minutes still: https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_integration&state=success

**Comment by smarterclayton** [comment]
There was a peak starting at this merge and then lasting all night.  It
could be related to something in the AWS environment, but it was a very
noticeable spike.

**Pull request merged**
