### PR TITLE
Set layer size whether it found in cache or not

### PR DESCRIPTION
**Pull request by dmage**
[BZ 1442855](https://bugzilla.redhat.com/show_bug.cgi?id=1442855)

### CODE REVIEW

**Comment by dmage** [comment]
[test]

**Comment by dmage** [comment]
[test]

**Comment by dmage** [comment]
Flake #14187, re[test].

**Comment by dmage** [comment]
Flake #14041, re[test].

**Comment by dmage** [comment]
Flake #13945, re[test].

**Comment by dmage** [comment]
Flake #13966, re[test].

**Comment by dmage** [comment]
Flake #13943, re[test].

**Comment by legionus** [comment]
[merge]

**Comment by legionus** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge][severity: blocker]

https://bugzilla.redhat.com/show_bug.cgi?id=1442855

**Pull request merged**
