### PR TITLE
properly check for nil docker client value

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1309805

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng @smarterclayton ptal.  we were checking an interface for nil :(

i've removed the interface entirely since it didn't seem to be adding any value (there's only one implementation of it).

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
specifically the bug crops up because this if-check was never true before:
https://github.com/openshift/origin/pull/7433/files#diff-b57f71d63cf4027ff3a7c7ab58ea6a87R76

**Comment by csrwng** [comment]
LGTM

**Comment by smarterclayton** [comment]
Please leave the interface...

**Comment by smarterclayton** [comment]
You can check interfaces for nil.  You just have to check for the correct nil type.

**Comment by bparees** [comment]
> You can check interfaces for nil. You just have to check for the correct nil type.

yeah i know, but that means assuming there will only ever be that single implementation of the interface, so what purpose does it serve if you have to be able to cast it anyway?

**Comment by bparees** [comment]
updated.
@csrwng says this is the right way to check for nil interfaces.

**Comment by smarterclayton** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Pull request merged**
