### PR TITLE
build hello-pod statically

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton this fixes https://github.com/openshift/origin/issues/2579 in a secure way. ptal.

**Comment by bparees** [comment]
[test]

**Comment by liggitt** [comment]
You win the Internet today

**Comment by bparees** [comment]
woot.  all the cat videos i can watch!  for a whole day!

**Comment by smarterclayton** [comment]
The Travis break is not your fault

**Comment by smarterclayton** [comment]
LGTM [merge] thanks for the kittens

**Comment by bparees** [comment]
ok @smarterclayton why didn't this close the issue i tagged above when it merged?

**Comment by liggitt** [comment]
fixed ### has to be in the description of the PR, not a comment

**Comment by bparees** [comment]
[sigh]

**Comment by smarterclayton** [comment]
That is not a recognized command.  Please contact #openshift-dev to get access to run that command.

**Comment by bparees** [comment]
I think we should update rosie to say something sympathetic for that command.

**Comment by smarterclayton** [comment]
And [face] will be Jordan looking at you

**Pull request merged**
