### PR TITLE
Remove Service Catalog Controller Manager service & fix port

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by jboyd01** [comment]
@luksa  pkg/oc/bootstrap/bindata.go is generated by the hack/update-generated-bindata.sh  script and should not be modified by hand.  You need to make changes to examples/service-catalog/service-catalog.yaml and then run the update-generated-bindata.sh and check in the yaml and updated bindata.go.

**Comment by luksa** [comment]
@jboyd01 Thanks. Fixed.

**Comment by jboyd01** [comment]
awesome!  LGTM

**Comment by pmorie** [comment]
/lgtm

Do we need to make any installer changes for this?

**Comment by jboyd01** [comment]
@pmorie  regarding https://github.com/openshift/origin/pull/18612#issuecomment-366816912  Yes, it looks to me like we are missing the --port in the ansible installer.    I believe the port should be in openshift-ansible/roles/openshift_service_catalog/templates/controller_manager.j2    I don't think Ansible is configured to create a controller service though.  @jpeeler  could you confirm?

**Comment by luksa** [comment]
I've closed this because equivalent changes were already merged in a different PR.

**Pull request closed without merging**
