### PR TITLE
don't output empty strings in logs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
avoid log output like:
```
I1217 02:55:06.996977       1 source.go:103] 
I1217 02:55:06.997002       1 source.go:104] 
```

@csrwng ptal.

**Comment by csrwng** [comment]
thx, LGTM [merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/6173
[merge]

**Comment by mfojtik** [comment]
@bparees do we want to do something similar for s2i?

**Comment by bparees** [comment]
If it has similar issues, sure.

Ben Parees | OpenShift

**Comment by mfojtik** [comment]
@bparees well the s2i emits these log messages when the assemble script emits a new line... if we fix this in s2i, then we don't get empty lines in origin. The only problem is that it might sometimes make the log less readable, especially when you have long lines or something important you want to show and add extra new lines on top and bottom.

**Comment by bparees** [comment]
If it's coming from assemble I don't think we should strip it.

Ben Parees | OpenShift

**Pull request merged**
