### PR TITLE
Cherrypick should force delete branch

### PR DESCRIPTION
**Pull request by smarterclayton**
[merge]

### CODE REVIEW

**Comment by deads2k** [comment]
This won't scare @liggitt  at all :)

**Comment by liggitt** [comment]
good grief...

**Comment by smarterclayton** [comment]
We won't go into that unless the branch didn't exist.  You can't delete
something that previously existed, only things that we created.

**Comment by smarterclayton** [comment]
```
E0209 12:15:24.742078   21565 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
I0209 12:15:24.742155   21565 trace.go:57] Trace "Create /oapi/v1/oauthclients" (started 2016-02-09 12:15:17.741007461 -0500 EST):
[15.431µs] [15.431µs] About to convert to expected version
[64.034µs] [48.603µs] Conversion done
[68.165µs] [4.131µs] About to store object in database
[7.001128254s] [7.001060089s] END
--- FAIL: TestAuthProxyOnAuthorize-2 (12.08s)
	auth_proxy_test.go:52: proxy server is on http://127.0.0.1:40471
	buildcontroller_test.go:326: unexpected error: client: etcd cluster is unavailable or misconfigured
FAIL
[INFO] Dumping etcd contents to /tmp/openshift/test-integration//artifacts/TestAuthProxyOnAuthorize-etcd_dump.json
```

from https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/10503/console

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
