### PR TITLE
moves the TSB into its own package

### PR DESCRIPTION
**Pull request by deads2k**
This moves all TSB code into its own package.  The only references we have to this code are here:

```
./pkg/cmd/server/start/start_allinone.go
./pkg/cmd/server/origin/master.go
./test/extended/templates/templateservicebroker_security.go
./test/extended/templates/templateservicebroker_e2e.go
```

We're going to remove the `master.go` reference in https://github.com/openshift/origin/pull/15684, leaving a dependency on building the command and in the e2e tests.

@smarterclayton @sttts Are we ready to jump off the cliff and move to staging repos?  We'd end up with cyclical imports until we sort out https://github.com/openshift/client-go/pull/2, but that looks tractable for an internal solution in 3.7 so we can learn how we want to shape it....

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal.  the idea here is someday the openservicebroker package becomes a thing that's vendored in (perhaps from the brokersdk).

**Comment by deads2k** [comment]
@gabemontero can you attempt a rebase on this to see if and how badly you conflict on it?

**Comment by gabemontero** [comment]
I'm in the middle of a rebase (3rd in last day and half :-) for my PR for something that just got merged @deads2k , but I can take a look afterward.  Hopefully later this evening.

**Comment by gabemontero** [comment]
@deads2k - checked both our prs to a temp dir, then did the reabse .... the output (prior to attempting to run `git mergetool`):

```
gmontero ~/rebase-test/origin  (gabemontero-tsb-userinfo-groups)$ git rebase deads2k-tsb-16-move
First, rewinding head to replay your work on top of it...
Applying: Use groups/extra information for authorization in template service broker
Using index info to reconstruct a base tree...
A	pkg/openservicebroker/api/types.go
A	pkg/openservicebroker/client/client.go
A	pkg/openservicebroker/server/route.go
A	pkg/openservicebroker/server/route_test.go
A	pkg/template/servicebroker/bind.go
A	pkg/template/servicebroker/catalog.go
A	pkg/template/servicebroker/catalog_test.go
A	pkg/template/servicebroker/deprovision.go
A	pkg/template/servicebroker/lastoperation.go
A	pkg/template/servicebroker/provision.go
A	pkg/template/servicebroker/unbind.go
A	pkg/template/servicebroker/validation.go
A	pkg/template/servicebroker/validation_test.go
Falling back to patching base and 3-way merge...
Auto-merging pkg/templateservicebroker/servicebroker/validation_test.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/validation_test.go
Auto-merging pkg/templateservicebroker/servicebroker/validation.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/validation.go
Auto-merging pkg/templateservicebroker/servicebroker/unbind.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/unbind.go
Auto-merging pkg/templateservicebroker/servicebroker/provision.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/provision.go
Auto-merging pkg/templateservicebroker/servicebroker/lastoperation.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/lastoperation.go
Auto-merging pkg/templateservicebroker/servicebroker/deprovision.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/deprovision.go
Auto-merging pkg/templateservicebroker/servicebroker/catalog_test.go
Auto-merging pkg/templateservicebroker/servicebroker/catalog.go
Auto-merging pkg/templateservicebroker/servicebroker/bind.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/servicebroker/bind.go
Auto-merging pkg/templateservicebroker/openservicebroker/server/route_test.go
CONFLICT (content): Merge conflict in pkg/templateservicebroker/openservicebroker/server/route_test.go
Auto-merging pkg/templateservicebroker/openservicebroker/server/route.go
Auto-merging pkg/templateservicebroker/openservicebroker/client/client.go
Auto-merging pkg/templateservicebroker/openservicebroker/api/types.go
error: Failed to merge in the changes.
Patch failed at 0001 Use groups/extra information for authorization in template service broker
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

gmontero ~/rebase-test/origin  (gabemontero-tsb-userinfo-groups|REBASE 1/12)$ 
```

**Comment by gabemontero** [comment]
And didn't go through all 12 re-bases .... I squashed my commits and then rebased and got:

```
gmontero ~/rebase-test/origin  (gabemontero-tsb-userinfo-groups)$ git rebase deads2k-tsb-16-move
First, rewinding head to replay your work on top of it...
Applying: Use groups/extra information for authorization in template service broker
Using index info to reconstruct a base tree...
A	pkg/openservicebroker/api/helpers.go
A	pkg/openservicebroker/api/types.go
A	pkg/openservicebroker/client/client.go
A	pkg/openservicebroker/server/route.go
A	pkg/openservicebroker/server/route_test.go
A	pkg/template/servicebroker/bind.go
A	pkg/template/servicebroker/catalog.go
A	pkg/template/servicebroker/catalog_test.go
A	pkg/template/servicebroker/deprovision.go
A	pkg/template/servicebroker/lastoperation.go
A	pkg/template/servicebroker/provision.go
A	pkg/template/servicebroker/test-scripts/bind.sh
A	pkg/template/servicebroker/test-scripts/deprovision.sh
A	pkg/template/servicebroker/test-scripts/lastoperation-provision.sh
A	pkg/template/servicebroker/test-scripts/provision.sh
A	pkg/template/servicebroker/test-scripts/shared.sh
A	pkg/template/servicebroker/test-scripts/unbind.sh
A	pkg/template/servicebroker/unbind.go
A	pkg/template/servicebroker/validation.go
A	pkg/template/servicebroker/validation_test.go
M	test/extended/templates/templateservicebroker_e2e.go
M	test/extended/templates/templateservicebroker_security.go
Falling back to patching base and 3-way merge...
Auto-merging test/extended/templates/templateservicebroker_security.go
Auto-merging test/extended/templates/templateservicebroker_e2e.go
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/unbind.sh
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/shared.sh
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/provision.sh
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/lastoperation-provision.sh
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/deprovision.sh
Auto-merging pkg/templateservicebroker/servicebroker/test-scripts/bind.sh
Auto-merging pkg/templateservicebroker/openservicebroker/api/types.go
Auto-merging pkg/templateservicebroker/openservicebroker/api/helpers.go
CONFLICT (modify/delete): pkg/template/servicebroker/validation_test.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/validation_test.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/validation.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/validation.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/unbind.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/unbind.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/provision.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/provision.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/lastoperation.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/lastoperation.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/deprovision.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/deprovision.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/catalog_test.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/catalog_test.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/catalog.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/catalog.go left in tree.
CONFLICT (modify/delete): pkg/template/servicebroker/bind.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/template/servicebroker/bind.go left in tree.
CONFLICT (modify/delete): pkg/openservicebroker/server/route_test.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/openservicebroker/server/route_test.go left in tree.
CONFLICT (modify/delete): pkg/openservicebroker/server/route.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/openservicebroker/server/route.go left in tree.
CONFLICT (modify/delete): pkg/openservicebroker/client/client.go deleted in acd2c809c201a55a516c2feb914055819b3e2a95 and modified in Use groups/extra information for authorization in template service broker. Version Use groups/extra information for authorization in template service broker of pkg/openservicebroker/client/client.go left in tree.
warning: inexact rename detection was skipped due to too many files.
error: Failed to merge in the changes.
Patch failed at 0001 Use groups/extra information for authorization in template service broker
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

gmontero ~/rebase-test/origin  (gabemontero-tsb-userinfo-groups|REBASE 1/1)$ 
```

**Comment by deads2k** [comment]
@bparees was ok with it in concept.  I've rebased on top of gabe's pull.  Tagging.

**Pull request merged**
