### PR TITLE
use local dockerconfig for auth when pulling images

### PR DESCRIPTION
**Pull request by bparees**
bug https://bugzilla.redhat.com/show_bug.cgi?id=1615762

### CODE REVIEW

**Comment by deads2k** [comment]
/assign @mfojtik 

this seems fairly reasonable to me.  The dep may eventually cause us a problem, but hopefully we'll be out of the installer business by then.

**Comment by bparees** [comment]
@mfojtik bump.. this fixes a test-blocker for v3.11 QE.

**Comment by bparees** [comment]
@deads2k @mfojtik has not reviewed this in 2 days.  CAn you please bug him or pick someone else? it's blocking QE test cases for 3.11.

**Comment by mfojtik** [comment]
/lgtm

@deads2k since that code is shared between builds and cluster up, maybe a good candidate to library-go ?

**Comment by bparees** [comment]
> @deads2k since that code is shared between builds and cluster up, maybe a good candidate to library-go ?

semi-shared anyway, i think i tweaked it a little for this usage.

**Pull request merged**
