### PR TITLE
Bug 2098095: EgressIP tests: Use OpenShift API to retrieve CloudPrivateIPConfigs and EgressIPs

### PR DESCRIPTION
**Pull request by andreaskaris**
Instead of using the oc CLI, use the OpenShift API and the CloudV1()
resource group to retrieve objects of the CloudPrivateIPConfigs
resource.

In order to avoid using oc, read EgressIPs now with the dynamic
client-go client.

Tested on AWS OVNKubernetes (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] only pods matched by the pod selector should have the EgressIPs [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be updated [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
~~~

Tested: AWS with SDN (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
echo ================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] EgressIPs can be assigned automatically [Skipped:Network/OVNKubernetes] [Serial] [Suite:openshift/conformance/serial]"
~~~

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

### CODE REVIEW

**Comment by andreaskaris** [comment]
retest

**Comment by jluhrsen** [comment]
guessing it's more reliable this way?
/lgtm

**Pull request merged**
