### PR TITLE
Bug 2058086: Add item length check in legacyPrinterToTable

### PR DESCRIPTION
**Pull request by ardaguclu**
Item length should be always equal to data buffer
size. But if resource contains invalid data, api server
panicks with index out of range error.

Instead panicking, this PR adds equality check.

In addition to that, this PR fixes integration and e2e-gcp test failures
due to `git://` deprecation.

### CODE REVIEW

**Comment by ardaguclu** [comment]
openshift-jenkins/extended_clusterup is failing because of docker rate limit error and not related to this PR.

**Comment by ardaguclu** [comment]
[openshift-jenkins/cmd](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26922/test_pull_request_origin_cmd/25250/) and [openshift-jenkins/extended_clusterup](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26922/test_pull_request_origin_extended_clusterup-release-3.11/2443/) jobs are failing because of docker rate limit error and not related to this PR.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
