### PR TITLE
[release-4.17] OCPBUGS-42814: ruby:3.0-ubi8 => ruby:3.1-ubi8

### PR DESCRIPTION
**Pull request by sanchezl**

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

/label cherrypick-approved

/label backport-risk-assessed

**Comment by ardaguclu** [comment]
Are we sure that this image works in aws-ovn-builds. This job https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oc/1910/pull-ci-openshift-oc-master-e2e-aws-ovn-builds/1856029543182110720 failed by getting;

```
  You might consider adding 'puma' into your Gemfile.
  /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/lib/rackup/handler.rb:81:in `pick': Couldn't find handler for: puma, falcon, webrick. (LoadError)
  	from /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/lib/rackup/handler.rb:91:in `default'
  	from /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/lib/rackup/server.rb:345:in `server'
  	from /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/lib/rackup/server.rb:341:in `start'
  	from /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/lib/rackup/server.rb:182:in `start'
  	from /opt/app-root/src/bundle/ruby/3.1.0/gems/rackup-2.2.0/bin/rackup:5:in `<top (required)>'
  	from /opt/app-root/src/bundle/ruby/3.1.0/bin/rackup:25:in `load'
  	from /opt/app-root/src/bundle/ruby/3.1.0/bin/rackup:25:in `<main>'
  <----end of log for "build-test-pod"/"test"
```

**Comment by ardaguclu** [comment]
Currently e2e-aws-ovn-builds job is permafailing due to this error.

**Pull request merged**
