### PR TITLE
Temporarily accept 'Forbidden' and 'forbidden' responses

### LINKED ISSUE #5602: '[ "$(oc rsh ${BUILD_ID}-build 2>&1 | grep 'forbidden')" ]' exited with status 1
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6591/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6593/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6594/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6595/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6596/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6597/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6599/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6602/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6603/console

```
!!! Error in hack/../test/end-to-end/core.sh:156
	'[ "$(oc rsh ${BUILD_ID}-build 2>&1 | grep 'forbidden')" ]' exited with status 1
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5602

### CODE REVIEW

**Comment by liggitt** [comment]
#5525 prevents the details of server errors establishing exec sessions from being displayed, and instead displays the generic http text. This accepts the generic text ("Forbidden") until we can restore the behavior of displaying the detailed server message

**Comment by liggitt** [comment]
@ncdc @smarterclayton PTAL

**Comment by liggitt** [comment]
tested locally, merging to unblock the queue

**Comment by smarterclayton** [comment]
LGTM

**Comment by deads2k** [comment]
> #5525 prevents the details of server errors establishing exec sessions from being displayed, and instead displays the generic http text. This accepts the generic text ("Forbidden") until we can restore the behavior of displaying the detailed server message

#5525 merged through the regular queue.  Any idea how it sometimes returns different forbiddens?  I would really hope for consistent behavior on that kind of an error.

**Comment by liggitt** [comment]
> #5525 merged through the regular queue. Any idea how it sometimes returns different forbiddens?

Absolutely no idea. The logs showed admission getting hit for the rsh e2e-user case, and server-side had the correct forbidden error... I don't see how `oc` output anything but `Forbidden` in that case with that PR

**Pull request merged**
