### PR TITLE
Bug 1949050: Fix oauthaccesstoken test to use the new required name

### PR DESCRIPTION
**Pull request by soltysh**
Followup to https://github.com/openshift/origin/pull/26009
/assign @sttts

### CODE REVIEW

**Comment by soltysh** [comment]
This is not touching aws-serial, and is unblocking oc merges since this is currently broken. aws-serial is being actively investigated. 
/override ci/prow/e2e-aws-serial

**Comment by smarterclayton** [comment]
Force merging to green up tests

**Pull request merged**
