### PR TITLE
Trigger SDN node event; bump openshift-sdn/ovssubnet(d534b3b254fe2a41b77260dcc5f6061b04f633b8)

### PR DESCRIPTION
**Pull request by pravisankar**
Trigger SDN node event when node ip changes 
Replace 'minion' with 'node' or 'nodeIP' based on the context

### CODE REVIEW

**Comment by pravisankar** [comment]
Depends on https://github.com/openshift/openshift-sdn/pull/119

**Comment by pravisankar** [comment]
@rajatchopra PTAL

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[test]

**Comment by rajatchopra** [comment]
Looks good.
[merge]

**Comment by bmeng** [comment]
@pravisankar Do we have a trello card to follow this?

I tried with the latest code, and get the following result. http://fpaste.org/254631/39453036/
I am not sure if it is correct, can you please take a look?

**Pull request merged**
