### PR TITLE
move build testdata files into builds subdirs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/unassign @kargakis @dcbw 
/assign @coreydaley 

@openshift/devex fyi.  just a basic relocation for now, i have not sifted through consolidating these or renaming them (though i did find a couple that weren't being used at all, so i've removed those).

**Comment by bparees** [comment]
@coreydaley bump

**Comment by coreydaley** [comment]
/lgtm
I can't think of any reason this would break anything un-related to the tests.

**Pull request merged**
