### PR TITLE
Add summary status message to network test runner

### PR DESCRIPTION
**Pull request by marun**
cc: @danwinship

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by danwinship** [comment]
yay!

**Comment by marun** [comment]
re-[testonlyextended]

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by dcbw** [comment]
LGTM

**Comment by pravisankar** [comment]
LGTM

**Comment by pravisankar** [comment]
[merge]

**Comment by marun** [comment]
@pravisankar Thank you for your attention!  I only hope you have the stomach for the endless stream of re-merges that will no doubt be required!

**Comment by eparis** [comment]
ravi got it to merge in one try.  WTH! So Impressed!

**Comment by danwinship** [comment]
it's all in the wrist

**Pull request merged**
