### PR TITLE
More UI integration test fixes

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]
WIP FYI @jwforres @liggitt

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
green, [test] again

**Comment by fabianofranz** [comment]
[test] again

**Comment by fabianofranz** [comment]
re[test]

**Comment by fabianofranz** [comment]
3 green, [test] again

**Comment by fabianofranz** [comment]
4 green, [test] again

**Comment by fabianofranz** [comment]
5 green

**Comment by liggitt** [comment]
5 clean test runs in a row, merging to unblock the merge queue

**Pull request merged**
