### PR TITLE
[release-3.6] host diagnostics: update master unit names

### PR DESCRIPTION
**Pull request by sosiouxme**
backport #18542 for https://bugzilla.redhat.com/show_bug.cgi?id=1378883

### CODE REVIEW

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18557/test_pull_request_origin_extended_conformance_install/7433/ seems to have failed because 3.7 packages were available and we're supposed to be testing 3.6. @stevekuznetsov @jupierce any comment?

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18557/test_pull_request_origin_extended_conformance_gce/16208/ flaked widely in a way that makes me think there's some unreported base cause underneath all the failures. I'm not even sure how to report that.

**Comment by stevekuznetsov** [comment]
CI is not supported in Origin repo for branches this old. Suggest you do an OSE backport instead. Origin 3.6 is not getting an OSS re-release at this point as far as I understand it, anyway.

**Comment by sosiouxme** [comment]
Ah, I have become lazy with the comparatively simple process of origin-ansible backports. Right-o.

**Pull request closed without merging**
