### PR TITLE
Updated sample-app output to match current state of work

### PR DESCRIPTION
**Pull request by soltysh**
@bparees PTAL
There's one small problem with my modifications (specifically after adding `osc login`), though. I can't see build-logs:
```
[vagrant@openshiftdev origin]$ osc build-logs ruby-sample-build-1 -n test
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "\"/osapi/v1beta1/proxy/buildLogs/ruby-sample-build-1?namespace=test\" is forbidden because test-admin cannot proxy on buildLogs with name \"ruby-sample-build-1\" in test",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

@deads2k could you tell me what role should I assign to test-admin so that he has access to it?

### CODE REVIEW

**Comment by bparees** [comment]
@soltysh this is handled in e2e via: 
openshift ex new-project test --description="This is an example project to demonstrate OpenShift v3" --admin="anypassword:e2e-user"

you'd want to do something similar here.  

also e2e should be updated to do an osc login if it is not currently doing so.

**Comment by deads2k** [comment]
Only cluster admins are allowed to proxy, so only cluster admins can see the build logs.

@liggitt  this was a side effect of securing the node, correct?

**Comment by liggitt** [comment]
@deads2k correct

**Comment by liggitt** [comment]
once build logs move under namespaces/[ns]/builds/[build]/logs, we can grant access to project admins

**Comment by bparees** [comment]
thought we were still doing redirect to the kubelet for logs, did that change?

**Comment by liggitt** [comment]
changed when the node got secured

**Comment by bparees** [comment]
ok, so we can't add osc login to the steps for now (since it prevents build-logs)

**Comment by bparees** [comment]
(oops, didn't mean to close, some of the other edits in here are useful)

**Comment by soltysh** [comment]
@bparees removed the `osc login` step, all the rest is as it was.

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by soltysh** [comment]
re-[merge]

**Pull request merged**
