### PR TITLE
bump(github.com/openshift/openshift-sdn): 9f1f60258fcef6f0ef647a75a87

### PR DESCRIPTION
**Pull request by pravisankar**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1320430  : https://github.com/openshift/openshift-sdn/pull/272
Debug improvements: https://github.com/openshift/openshift-sdn/pull/273 , https://github.com/openshift/openshift-sdn/pull/276 , https://github.com/openshift/openshift-sdn/pull/283 , https://github.com/openshift/openshift-sdn/pull/284 , https://github.com/openshift/openshift-sdn/pull/286
Plugin refactor/cleanup: https://github.com/openshift/openshift-sdn/pull/270 , https://github.com/openshift/openshift-sdn/pull/278
Add macvlan interface to pod (for egress-router): https://github.com/openshift/openshift-sdn/pull/271
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1322077 : https://github.com/openshift/openshift-sdn/pull/277
Don't perform AddServiceRules with global/zero vnid when the vnid is not found: https://github.com/openshift/openshift-sdn/pull/279
Do not throw spurious error msgs in SDN: https://github.com/openshift/openshift-sdn/pull/280
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=132294 : https://github.com/openshift/openshift-sdn/pull/285
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1275904 : https://github.com/openshift/openshift-sdn/pull/241

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
[test][extended:networking]

**Comment by pravisankar** [comment]
OOM Flake in Kubelet, Networking extended tests passed

**Comment by pravisankar** [comment]
@eparis @knobunc can we get these fixes into origin?
We can bundle rest of the fixes in subsequent pr (sometime tomorrow or Thursday)

**Comment by eparis** [comment]
@danwinship @dcbw get a couple of reviews and I will merge.

**Comment by knobunc** [comment]
The changes you pulled for issue 285 and issue 277 look good to me.  The other changes I spot checked looked complete too... so yeah.  LGTM

**Comment by danwinship** [comment]
I thought we already agreed we weren't doing a full resync for 3.2? (#8333)

**Comment by eparis** [comment]
I think ravi is trying to argue that the number of bug fixes is so large and the non-required fixes so small/risk free....

But I'll let you tell me.

**Comment by pravisankar** [comment]
If we plan to skip/cherry-pick commits, patches won't apply smoothly due to some refactors and also we need to maintain what is synced and what is not synced to origin.
At least I feel except openshift/openshift-sdn#271 all the commits either fixes some existing issue or helps in debugging our code.

**Comment by danwinship** [comment]
> At least I feel except openshift/openshift-sdn#271 all the commits either fixes some existing issue or helps in debugging our code.

agreed (although note that the debugging fixes are not actually part of this PR: debug.sh isn't synced to origin)

We probably should wait to get https://github.com/openshift/openshift-sdn/pull/292 in too?

**Comment by pravisankar** [comment]
On Tue, Apr 12, 2016 at 2:01 PM, Dan Winship <notifications@github.com>
wrote:

> At least I feel except openshift/openshift-sdn#271
> <https://github.com/openshift/openshift-sdn/pull/271> all the commits
> either fixes some existing issue or helps in debugging our code.
>
> agreed (although note that the debugging fixes are not actually part of
> this PR: debug.sh isn't synced to origin)
>
> We probably should wait to get openshift/openshift-sdn#292
> <https://github.com/openshift/openshift-sdn/pull/292> in too?
>
We got some more pending fixes, we can bundle them in a separate pr

**Comment by danwinship** [comment]
LGTM

**Comment by eparis** [comment]
approved and [merge]

**Comment by dragon9783** [comment]
LGTM

**Pull request merged**
