### PR TITLE
Disable settings.k8s.io/v1alpha1 API

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

@deads2k FYI

**Comment by deads2k** [comment]
@mfojtik I may have guided you astray.  I didn't realize we only had a blacklist, not a whitelist.  I'm still pulling at the thread, but we have to have a way to optionally enable this :(

**Comment by mfojtik** [comment]
@deads2k we can use extended args to enable?

**Comment by deads2k** [comment]
Can you test to make sure?  If so, then we can pursue this path, which is
easier than other options I can think of.

**Pull request closed without merging**
