### PR TITLE
OCPBUGS-34666: Update etcd test data for 1.30 release

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Add these resources to etcd test data:

resource.k8s.io/v1alpha2, Resource=resourceslices
resource.k8s.io/v1alpha2, Resource=resourceclassparameters 
resource.k8s.io/v1alpha2, Resource=resourceclaimparameters

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

While we figure out which of these goes in.
/payload 4.17 nightly informing

**Comment by dinhxuanvu** [comment]
@Elbehery @dgoodwin Would you mind re-lgtming the PR? I force-pushed to fix a typo (singular vs plural on resource name).
The test passed on the payload so we can merge this PR and will no longer need the revert one.

**Comment by dinhxuanvu** [comment]
@ardaguclu Thanks!
@dgoodwin You can unhold this PR whenever you are ready.

**Comment by dgoodwin** [comment]
From your last set of job runs:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-28843-ci-4.17-e2e-gcp-ovn-techpreview-serial/1796288399989018624
```
[sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial] expand_less 	25s
{  fail [github.com/openshift/origin/test/extended/etcd/etcd_storage_path.go:546]: test failed:
no test data for resource.k8s.io/v1alpha2, Kind=ResourceSlice.  Please add a test for your new type to etcdStorageData.
etcd data does not match the types we saw:
seen but not in etcd data:
[
	resource.k8s.io/v1alpha2, Resource=resourceslices]
Ginkgo exit error 1: exit with code 1}
```

What's going on there?


For next round of testing we can save some money with just the techpreview-serial jobs that are failing, I'll omit the leading / to prevent them from running now.

payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial
payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-techpreview-serial
payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-techpreview-serial

**Comment by dinhxuanvu** [comment]
> From your last set of job runs: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-28843-ci-4.17-e2e-gcp-ovn-techpreview-serial/1796288399989018624
> 
> ```
> [sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial] expand_less 	25s
> {  fail [github.com/openshift/origin/test/extended/etcd/etcd_storage_path.go:546]: test failed:
> no test data for resource.k8s.io/v1alpha2, Kind=ResourceSlice.  Please add a test for your new type to etcdStorageData.
> etcd data does not match the types we saw:
> seen but not in etcd data:
> [
> 	resource.k8s.io/v1alpha2, Resource=resourceslices]
> Ginkgo exit error 1: exit with code 1}
> ```
> 
> What's going on there?
> 
> For next round of testing we can save some money with just the techpreview-serial jobs that are failing, I'll omit the leading / to prevent them from running now.
> 
> payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-techpreview-serial payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-techpreview-serial

That was the typo that I mentioned in one of the comments. The resource name was supposed to be `resourceslices` but I typed only `resourceslice`. So it errored out hence the force=push to correct it. It passed the test after that. It was an accident but funny enough it confirmed that the test did get run properly.

**Comment by dgoodwin** [comment]
Ah I see I got the wrong comment I guess. Thanks!

/hold cancel

**Pull request merged**
