### PR TITLE
Make activeDeadlineSeconds configurable for deployer pods 	

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/11351

@mfojtik @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@openshift/api-review

**Comment by smarterclayton** [comment]
API approved.

**Comment by kargakis** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
[test]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11775 [merge]

**Pull request merged**
