### PR TITLE
Update oc scale help  to display duration "units" in --timeout usage

### PR DESCRIPTION
**Pull request by juanvallejo**
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1277070

`oc scale` has `--timeout` option, but the help info does not give accepted time units. 

The help info gives default value `0` without a unit, potentially misleading a user into thinking they need to pass the numbered time only.

### CODE REVIEW

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by juanvallejo** [comment]
re[test]

**Comment by juanvallejo** [comment]
re[test]

**Comment by fabianofranz** [comment]
re[merge]

**Comment by smarterclayton** [comment]
What upstream PR contains 0ddea3e76619b874f812b64c860aa4bc429974cf (since you didn't fill out the commit title)?

**Comment by juanvallejo** [comment]
@smarterclayton Ah, sorry about this, I had forgotten to create one: https://github.com/kubernetes/kubernetes/pull/30022

**Pull request merged**
