### PR TITLE
UPSTREAM: 34298: Fix potential panic in namespace controller

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1379316

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM, [test]

**Comment by derekwaynecarr** [comment]
re[test]

**Comment by derekwaynecarr** [comment]
flake, test on [merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by derekwaynecarr** [comment]
re [merge] down to one flake.

**Pull request merged**
