### PR TITLE
UPSTREAM: 47274: Don't provision for PVCs with AccessModes unsupported by plugin

### PR DESCRIPTION
**Pull request by wongma7**
https://github.com/kubernetes/kubernetes/pull/47274

I will create BZ

### CODE REVIEW

**Comment by wongma7** [comment]
the difference between this patch and upstream is storageos and azurefile

**Comment by wongma7** [comment]
[test]

**Comment by wongma7** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1462275

**Comment by wongma7** [comment]
```
    Test Panicked
    runtime error: invalid memory address or nil pointer dereference
    /usr/local/go/src/runtime/panic.go:458

    Full Stack Trace
    	/usr/local/go/src/runtime/panic.go:458 +0x243
    github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework.(*StatefulSetTester).WaitForStatus.func1(0xc42177f0b0, 0xde43ad, 0x349bde0)
    	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:371 +0x113
    github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc421521740, 0xc421cca480, 0xc421521740, 0xc421cca480)
    	/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:205 +0x2b
    github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x2540be400, 0x8bb2c97000, 0xc421cca480, 0x1, 0x1)
    	/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:201 +0x4d
    github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework.(*StatefulSetTester).WaitForStatus(0xc421e6eb80, 0xc4212b6700, 0xc400000000)
    	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:379 +0x1bd
    github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e.glob..func86.2.8()
    	/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/statefulset.go:374 +0x820
    github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc42138d2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/go/src/github.com/openshift/origin/test/extended/util/test.go:119 +0x3cf
    github.com/openshift/origin/test/extended.TestExtended(0xc4214c66c0)
    	/go/src/github.com/openshift/origin/test/extended/extended_test.go:33 +0x40
    testing.tRunner(0xc4214c66c0, 0x3b155a0)
    	/usr/local/go/src/testing/testing.go:610 +0x81
    created by testing.(*T).Run
    	/usr/local/go/src/testing/testing.go:646 +0x2ec
```

**Comment by wongma7** [comment]
[test]

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by smarterclayton** [comment]
[test] this was a failure in the job to update the cluster

**Comment by eparis** [comment]
[merge][severity: blocker]

**Comment by eparis** [comment]
[merge]
Last try was: https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1042/

**Comment by wongma7** [comment]
• Failure in Spec Setup (JustBeforeEach) [50.821 seconds]
[builds][Conformance][valueFrom] process valueFrom in build strategy environment variables
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originGVPA4d/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:129
  should successfully resolve valueFrom in docker build environment variables [JustBeforeEach]
  /openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originGVPA4d/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:94

  Expected error:
      <*errors.errorString | 0xc4211b18d0>: {
          s: "Failed to import expected imagestreams",
      }
      Failed to import expected imagestreams
  not to have occurred

**Comment by smarterclayton** [comment]
@bparees @coreydaley

On Jun 19, 2017, at 10:27 AM, Matthew Wong <notifications@github.com> wrote:

• Failure in Spec Setup (JustBeforeEach) [50.821 seconds]
[builds][Conformance][valueFrom] process valueFrom in build strategy
environment variables
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originGVPA4d/BUILD/origin-3.6.0/_output/local/go/src/
github.com/openshift/origin/test/extended/builds/valuefrom.go:129
should successfully resolve valueFrom in docker build environment variables
[JustBeforeEach]
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originGVPA4d/BUILD/origin-3.6.0/_output/local/go/src/
github.com/openshift/origin/test/extended/builds/valuefrom.go:94

Expected error:
<*errors.errorString | 0xc4211b18d0>: {
s: "Failed to import expected imagestreams",
}
Failed to import expected imagestreams
not to have occurred

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14705#issuecomment-309456403>,
or mute
the thread

**Comment by smarterclayton** [comment]
Green except for the one failure, force merging.

**Comment by coreydaley** [comment]
@bparees we may need to go ahead and merge in #14721, which would fix this issue with the valueFrom tests on gce

**Comment by bparees** [comment]
@coreydaley @smarterclayton the failure doesn't look at all related to the envvar changes or anything specific about that test:

```
Expected error:
<*errors.errorString | 0xc4211b18d0>: {
s: "Failed to import expected imagestreams",
}
Failed to import expected imagestreams
not to have occurred
```

just happened to be in that test (something went wrong w/ the network?)

https://github.com/openshift/origin/blob/master/test/extended/builds/valuefrom.go#L34
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L52-L81

(the failed job is here: https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1042/)

**Pull request merged**
