### PR TITLE
[release-3.10] Bug 1775782: React to openshift/ruby-hello-world changes

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by bparees** [comment]
/hold

This is spinning, needs investigation


Ben Parees | OpenShift

**Comment by adambkaplan** [comment]
@bparees think I ironed out the failures (had green runs prior to my squash)

**Comment by bparees** [comment]
@adambkaplan feel free to remove the hold if you're satisfied it's passing

**Comment by adambkaplan** [comment]
@bparees @akram @openshift/openshift-team-developer-experience ptal at the tests I disabled.

**Comment by bparees** [comment]
at this point for 3.10 only i'm ok w/ disabling these tests.

**Comment by gabemontero** [comment]
yeah we've disabled those gradle items in later releases

/lgtm

**Pull request merged**
