### PR TITLE
WIP Bug 1977383: [release-4.7] Update resource quota test for compatibility with service ca configmap publishing

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by marun** [comment]
/retest

serial job is failing on aws infra issue unrelated to this PR.

**Comment by marun** [comment]
Marking WIP until https://github.com/openshift/kubernetes/pull/843 merges and this PR is updated to incorporate it. The quota and watch fixes are both required to merge to origin@release-4.7 before https://github.com/openshift/kubernetes/pull/834 can safely merge.

**Comment by s-urbaniak** [comment]
/close
exactly this bump just merged as part of https://github.com/openshift/origin/pull/26259

**Pull request closed without merging**
