### PR TITLE
UPSTREAM: google.golang.org/grpc: 1005: fix logical race in flow control

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by enj** [comment]
@mfojtik you have an extra zero in the PR number: https://github.com/grpc/grpc-go/pull/1005

**Comment by mfojtik** [comment]
@enj thanks, fixed.

**Comment by mfojtik** [comment]
/cherrypick release-3.8

@kargakis does the bot don't recognize multiple cherrypick comments?

**Comment by mfojtik** [comment]
@smarterclayton do we need/want this?

**Comment by smarterclayton** [comment]
Yes, I expect us to deliver this to 3.7.  Have we had reproducer yet?  It’s still happening on west-1

**Comment by soltysh** [comment]
> Yes, I expect us to deliver this to 3.7. Have we had reproducer yet? It’s still happening on west-1

No luck on the reproducer, I've tried several different approaches with [this](https://github.com/soltysh/origin-tester/blob/master/cmd/tester/main.go) tweaking numbers in many different directions and was never able to reproduce it :/

**Comment by smarterclayton** [comment]
One way may be to add a print statement to the connect function that shows
the current quota number and verify if your test suite can cause the race
to happen.  Also run with stress -c 8 or whatever in the background.

us-west-1 is still hitting this.  This is p0

**Comment by mfojtik** [comment]
/retest

@smarterclayton if we can't reliably reproduce this in isolated environment, can we ship this and see if it helps? I'm 85% sure the queue is causing the API server being stuck and the tests in CI for this PR did not revealed any regression AFAIK.

**Comment by mfojtik** [comment]
@smarterclayton @derekwaynecarr merge?

**Comment by mfojtik** [comment]
@smarterclayton this should be automatically cherry-picked for 3.8... if not, it means we already have this fix and the grpc bumped.

**Comment by soltysh** [comment]
Or the alternative https://github.com/openshift/origin/pull/18071?

**Comment by soltysh** [comment]
Discussed this with @mfojtik and @smarterclayton we're going with this
/lgtm

**Pull request merged**
