### PR TITLE
[RPMS] Switch atomic-openshift services to /usr/bin/openshift

### PR DESCRIPTION
**Pull request by sdodson**
Also fix an existing build issue.

### CODE REVIEW

**Comment by sdodson** [comment]
@brenton PTAL this should be the last of the packaging refactor work for 3.1

The rpm build fix was in #4850 but I've moved it here as that pull request is more invasive and I'd like Clayton to review it.

**Comment by brenton** [comment]
Looks like this needs a rebase.  Other than that I think it's ready to merge.

**Comment by danmcp** [comment]
@sdodson Bump

**Comment by sdodson** [comment]
@brenton ready to merge

**Comment by brenton** [comment]
[merge]

**Pull request merged**
