### PR TITLE
UPSTREAM: 30796: Quota usage checking ignores unrelated resources

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1367733

xref https://github.com/kubernetes/kubernetes/pull/30796

/cc @ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
```
+ vagrant origin-local-checkout --replace --branch master
You don't seem to have the GOPATH environment variable set on your system.
See: 'go help gopath' for more details about GOPATH.
Waiting for the cloning process to finish
Replacing: /var/lib/jenkins/jobs/test_pull_requests_origin_integration/workspace/origin
~/jobs/test_pull_requests_origin_integration/workspace/origin ~/jobs/test_pull_requests_origin_integration/workspace
error: you need to resolve your current index first
images/router/haproxy/conf/haproxy-config.template: needs merge
Origin repositories cloned into /var/lib/jenkins/jobs/test_pull_requests_origin_integration/workspace
```

[test]

**Comment by ncdc** [comment]
This is currently 16th in the Kube submit queue

**Comment by stevekuznetsov** [comment]
@ncdc known issue, thanks for the mention. should be fixed now

**Comment by ncdc** [comment]
@stevekuznetsov yeah, Dan helped me out, thanks

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
