### PR TITLE
Bug 1316749: prompt warning when scaling test deployments

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton PTAL

I am going to follow-up with an oc status warning for autoscalers on test deployments.

### CODE REVIEW

**Comment by kargakis** [comment]
Or we could allow scaling since we may want to test different sizes of deployments but print a message that no actual pods will be scaled up.

**Comment by smarterclayton** [comment]
We want to allow scaling of test deployments.  We should warn that the scale setting will only apply when the test deployment is running.  We want to allow autoscaling of test deployments -y ou might be testing autoscaling.

**Comment by kargakis** [comment]
> We want to allow autoscaling of test deployments -y ou might be testing autoscaling.

How a test deployment is supposed to autoscale when there is no cpu utilization for the hpa to make decisions?

**Comment by smarterclayton** [comment]
Because they start up and run for an indefinite amount of time, and
can be autoscaled while they are running.  When they finish, they will
be reset to min scale (or should).

I don't think this is even a warning.  At best it's informational and
we should show related HPA on describe page.

**Comment by kargakis** [comment]
> t best it's informational and we should show related HPA on describe page.

This is an interesting proposition. How can we make this happen w/o a link from the dc to its hpa?

**Comment by kargakis** [comment]
@smarterclayton updated to just warn, ptal

**Comment by kargakis** [comment]
> This is an interesting proposition. How can we make this happen w/o a link from the dc to its hpa?

I see that clients are passed around. Will submit a PR shortly that adds this info.

**Comment by smarterclayton** [comment]
Same way we do for pods and the services / rcs that cover them - make a
query for HPAs in the project and show any that are targeting the described
DC.

**Comment by kargakis** [comment]
> Same way we do for pods and the services / rcs that cover them - make a query for HPAs in the project and show any that are targeting the described DC.

Opened https://github.com/openshift/origin/pull/7995, are you ok with merging the present PR?

**Comment by smarterclayton** [comment]
I'm fine with this change

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
