### PR TITLE
Use correct client config to run token cmd

### PR DESCRIPTION
**Pull request by liggitt**
Fixed an error running integration tests with $KUBERNETES_MASTER set (which we do in the vagrant images). The test correctly sets --master to point at the test server, but the client config was getting $KUBERNETES_MASTER from the environment

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k review

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge]

**Comment by deads2k** [comment]
egads, I take it back.  It works, but Names need updating.

**Comment by deads2k** [comment]
oh well, follow up

**Comment by deads2k** [comment]
Once the variable is renamed, it'll be fine.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
