### PR TITLE
skip tests for etcd leaders when etcd revisions change a lot

### PR DESCRIPTION
**Pull request by p0lyn0mial**
based on https://github.com/openshift/origin/pull/26965/files and https://github.com/openshift/origin/pull/26917

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
the e2e-gcp failure was fixed in https://github.com/openshift/origin/pull/27002

**Comment by EmilienM** [comment]
@p0lyn0mial thanks for your PR. Are you going ot backport it to stable releases?

**Pull request merged**
