### PR TITLE
Add progress to rsync

### PR DESCRIPTION
**Pull request by wanghaoran1988**
When a file is abit large , progress info of a file is usefull for users to know the status of oc rsync.

### CODE REVIEW

**Comment by smarterclayton** [comment]
For tar, do we need a different flag?

**Comment by wanghaoran1988** [comment]
@smarterclayton For tar strategy will not support this, a little difficult , only works for rsync strategy is enough I think.

**Comment by csrwng** [comment]
@wanghaoran1988 so far we've only exposed flags that apply to all strategies, but ideally would like to expose more of the rsync flags when rsync is used... one idea would be to have an --rsync-args flag to allow pass-through of arbitrary flags to the rsync invocation. @smarterclayton what do you think?

**Comment by liggitt** [comment]
it feels silly to have `--rsync-args` for an `rsync` command...

**Comment by csrwng** [comment]
@liggitt or we can just pass through any args that we can't recognize. Would that work better?

**Comment by smarterclayton** [comment]
I certainly don't want to create an API translation layer to rsync.
However, we already have that for the tar path, so we should be very
careful not to clone those flags into new flags.

**Comment by csrwng** [comment]
@smarterclayton so... should we go with the approach of just passing flags through?

**Comment by smarterclayton** [comment]
That also can lead to problems (if people use them, then we introduce our
on flag in the future).  I think we may have to do the --rsync-args
argument, as ugly as it is.  We would selectively add flags that we support.

**Comment by smarterclayton** [comment]
Passing progress through is ok, we just have to identify when the flags can be transformed or safely ignored.

**Comment by wanghaoran1988** [comment]
I am prefer add the rsync-args solution , as a user , I want to use the maybe more other rsync options .and we should mentions that what works for rsync and what works for tar  in our doc.

**Pull request closed without merging**
