### PR TITLE
add negative checking for new-app

### PR DESCRIPTION
**Pull request by SSshahan**
Add negative checking for new-app unit-test, please have a review, thanks！
@mfojtik  @coreydaley  could you have a  look?

### CODE REVIEW

**Comment by SSshahan** [comment]
@deads2k  This pr looks like being left out, could you take a look at this pr? Thanks!

**Comment by juanvallejo** [comment]
@SSshahan You'll need to run gofmt on `newapp_test.go`

**Comment by SSshahan** [comment]
@juanvallejo  Thanks!

**Comment by soltysh** [comment]
@SSshahan looks like your test is actually failing.

**Pull request merged**
