### PR TITLE
kube rebase

### PR DESCRIPTION
**Pull request by deads2k**
TODOs
- [x] fix unit tests
- [x] repick 9009
- [x] collapse the purely transitive bumps
- [x] cherry-pick misses from 4003
- [x] Ensure kubeAddress is an IP (https://github.com/deads2k/origin/commit/f802ef02269c5fbb8e3a5b28617383df0bbf6527#commitcomment-12675432)

- [x] add back "omitempty" to `Metadata *MetadataVolumeSource json:"metadata"`

Followups
- [ ] unbreak multi-tenant plugin (https://github.com/deads2k/origin/commit/7d861789ffee2b49ef8158973276c8f93278e064#diff-b49718624992033acb44cece8be1f7dfR68) https://github.com/deads2k/origin/commit/7d861789ffee2b49ef8158973276c8f93278e064#commitcomment-12689648
- [ ] rebase 5093
- [ ] upstream controller packages don't match the folder names
- [ ] upstream flag types were removed.  We currently have a patch.
- [ ] fix upstream flag binding methods to bind variable, not rely on flagset lookups
- [ ] repick 9870
- [ ]  make the rate limiter configurable (https://github.com/deads2k/origin/commit/f802ef02269c5fbb8e3a5b28617383df0bbf6527#diff-62e1d6e1ea7f763bd41c44733aa2fba2R163)
- [ ] decide if we care about the API enforcing apiVersion matching now

`git log -E --grep="^UPSTREAM:|^bump" --oneline`
- [x] dropped 1c00a58 UPSTREAM: <drop>: handle kube package refactor
- [x] added bf1afb1 UPSTREAM: 12498: Re-add timeouts for kubelet which is not in the upstream PR.
- [x] added f6ebdae UPSTREAM: search for mount binary in hostfs
- [x] added 2cd5ca4 UPSTREAM:<carry>:kube dep for tests
- [x] added eb7992a UPSTREAM:<carry>:reallow the ability to post across namespaces in api installer
- [x] merged 4e09a2c UPSTREAM:12271:expose codec in storage
- [x] merged 659eae0 UPSTREAM: 10636: Split kubelet server initialization for easier reuse
- [x] added 6fb0cb8 UPSTREAM: 9844: EmptyDir volume SELinux support
- [x] added 668ce2d UPSTREAM: carry: support pointing oc exec to old openshift server
- [x] added b28bbe1 UPSTREAM: <carry>: Add deprecated fields to migrate 1.0.0 k8s v1 data
- [x] added cd08aab UPSTREAM: 9009: Retry service account update when adding token reference
- [x] added d3ff541 UPSTREAM: 5093: adding downward api volume plugin
- [x] added 1f56b02 UPSTREAM: 8890: Allowing ActiveDeadlineSeconds to be updated for a pod
- [x] added ae89055 UPSTREAM: 6649: Add CephFS volume plugin
- [x] added 2aabce0 UPSTREAM: <carry>: Enable LimitSecretReferences in service account admission
- [x] added 018815a UPSTREAM: <none>: Suppress aggressive output of warning
- [x] added 8ab273d UPSTREAM: <none>: Hack date-time format on *util.Time
- [x] added 8f2950b UPSTREAM: <carry>: Disable UIs for Kubernetes and etcd
- [x] added 66117ce UPSTREAM: 9321: update describer for dockercfg secrets
- [x] added bf9197c UPSTREAM: <carry>: Allow pod start to be delayed in Kubelet
- [x] added 1f84352 UPSTREAM: 9870: Allow Recyclers to be configurable
- [x] added 3c630c4 UPSTREAM: 7893: scc allocation interface methods
- [x] added 3f8ec4c UPSTREAM: <carry>: implement a generic webhook storage
- [x] merged 367b4b3 UPSTREAM: 8607: service account groups
- [x] merged 2976e74 UPSTREAM: 9472: expose name validation method
- [x] added 18fc2e3 UPSTREAM:<carry>: v1beta3
- [x] added 87b4b4a UPSTREAM:7893: scc

@pweil- Your turn to review

### CODE REVIEW

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/4098 in case we want to pick it just to be cautious - @deads2k, @liggitt

**Comment by pweil-** [comment]
Missing https://github.com/openshift/origin/pull/4093 unless it was wrapped in to another commit somehow.  If it is already in I can close that PR, if not I can rebase it so it can be picked.

**Comment by liggitt** [comment]
@pweil-  nope, #4093 still needs to be picked, please rebase

**Comment by pweil-** [comment]
rebased and bumped for a review

**Comment by deads2k** [comment]
fighting two integration test failures, but this is ready for review.

**Comment by liggitt** [comment]
should have omitempty:
```
Metadata *MetadataVolumeSource `json:"metadata"`
```

**Comment by deads2k** [comment]
[test]

**Comment by liggitt** [comment]
I can't tell what `UPSTREAM: <carry>: kube dep for tests` is supposed to be... it looks like a straight copy of a ton of additional upstream things... is it really a carry patch?

**Comment by liggitt** [comment]
review complete, added a few things to the TODO list. multi-tenant plugin might be able to be a follow up

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
> I can't tell what UPSTREAM: <carry>: kube dep for tests is supposed to be... it looks like a straight copy of a ton of additional upstream things... is it really a carry patch?

Wasn't sure how to call it out.  It won't come in with `godep save` because its a test only package dependency without any go files in it.  pmorie and pweil both chose this as well.  It at least points out that you'll need it and gives you a starting point for pulling the correct files.

**Comment by deads2k** [comment]
> add back "omitempty" to Metadata *MetadataVolumeSource json:"metadata"

I only saw this on the internal version that's never used, the serialized types were ok, correct?

**Comment by deads2k** [comment]
> unbreak multi-tenant plugin (deads2k@7d86178#diff-b49718624992033acb44cece8be1f7dfR68)

I've tagged the commit a couple times (it keep changing).  I really want to break it since the rest works.

**Comment by liggitt** [comment]
> I only saw this on the internal version that's never used, the serialized types were ok, correct?

Looks fine now... I only saw it missing in a diff, don't remember which file it was in

**Comment by liggitt** [comment]
> Wasn't sure how to call it out. It won't come in with godep save because its a test only package dependency without any go files in it. pmorie and pweil both chose this as well. It at least points out that you'll need it and gives you a starting point for pulling the correct files.

How did you grab those files? Is it that the result of running `hack/copy-kube-artifacts.sh`? Probably fine, I just didn't know how to review it

**Comment by deads2k** [comment]
> How did you grab those files? Is it that the result of running hack/copy-kube-artifacts.sh? Probably fine, I just didn't know how to review it

Yes, and I updated that script to handle the current state of kube.

**Comment by liggitt** [comment]
ok, LGTM

**Comment by liggitt** [comment]
need to update completions, per latest jenkins test run

**Comment by deads2k** [comment]
> need to update completions, per latest jenkins test run

just did

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@smarterclayton I just realized that you might want to tag something before this drops.  It's close to the previous rebase in time, but not in terms of changes.

**Comment by liggitt** [comment]
I'm not sure we had something stable we want to tag since the last rebase

**Comment by deads2k** [comment]
Looks like dockerhub failure.  re[test]

```
--- FAIL: TestImage (30.37s)
	client_test.go:110: error getting X-Docker-Token from openshift/origin: Get https://index.docker.io/v1/repositories/openshift/origin/images: dial tcp 54.208.130.47:443: i/o timeout
2015/08/13 14:34:37 http: multiple response.WriteHeader calls
2015/08/13 14:34:37 http: multiple response.WriteHeader calls
FAIL
coverage: 77.8% of statements
FAIL	github.com/openshift/origin/pkg/dockerregistry	32.021s
```

**Comment by deads2k** [comment]
[test]

**Comment by liggitt** [comment]
```
/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Error communicating with the remote browser. It may have died.
```

**Comment by deads2k** [comment]
Just a UI flake, right?

**Comment by liggitt** [comment]
yeah, kicked jenkins test while we continue to wait for the merge queue

**Comment by deads2k** [comment]
> yeah, kicked jenkins test while we continue to wait for the merge queue

I prefer to think of it as everything else worked

**Comment by liggitt** [comment]
```
remote: error: failed to lock refs/heads/master
To verifier:/data/src/github.com/openshift/origin-bare
 ! [remote rejected] master -> master (failed to lock)
```

**Comment by deads2k** [comment]
test-cmd.sh passed in one Travis, so I'm hopeful.

**Comment by deads2k** [comment]
re[merge]

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/2960

UI
```
WARNING - more than one element found for locator by.cssContainingText("h3 > a", "ruby") - the first result will be used
**************************************************
*                    Failures                    *
**************************************************

1)  authenticated e2e-user with test project when adding to project should create from source
  - Error: Wait timed out after 5085ms
      at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ 
```

**Comment by deads2k** [comment]
Non-conflicting merge conflict. Not meant to be today.

**Comment by deads2k** [comment]
@liggitt can you help diagnose this failure from UI?  I've gotten it twice now: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4118

```
1)  authenticated e2e-user when creating a new project should successfully create a new project
  - Expected 'https://localhost:9000/createProject' to contain '/project/e2e-test-project/overview'.
      at /data/src/github.com/openshift/origin/assets/test/e2e/test.js:298:43
    at /data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/element.js:770:12
```

`oc new-project` works, at least in `hack/test-cmd.sh`

**Comment by liggitt** [comment]
@fabianofranz ^ if I don't get to it first

**Comment by deads2k** [comment]
maybe just a bad flake?  really hoping re[merge]

**Comment by liggitt** [comment]
Looks like a create/auth failure, which is weird... https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4118/artifact/origin/artifacts/screenshots/00450064-007b-007e-003a-005000040049.png

**Comment by fabianofranz** [comment]
@liggitt This is new. We disabled app creation yesterday, should we just disable project creation too?

**Comment by deads2k** [comment]
> @liggitt This is new. We disabled app creation yesterday, should we just disable project creation too?

This seems to happening pretty consistently.  The cli seems to be working fine with new-project.  How can I trigger this test manually to compare?

**Comment by fabianofranz** [comment]
@deads2k https://github.com/openshift/origin/pull/4167 just disabled it.

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
I wonder how @liggitt broke that. re[merge]

**Pull request merged**
