### PR TITLE
reaper: Use NOHANG pattern instead of waiting for all children.

### LINKED ISSUE #1434: Router doesn't start if there are no child processes for Wait
@mrunalp @thoraxe 

```
E0324 14:45:52.998462       1 router.go:126] Error reloading router: wait: no child processes
 Reload output: + config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ path_map_file=/var/lib/haproxy/conf/os_http_be.map
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=16
+ '[' -n 16 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 16
[WARNING] 082/144552 (21) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
E0324 14:45:53.013026       1 router.go:126] Error reloading router: wait: no child processes
 Reload output: + config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ path_map_file=/var/lib/haproxy/conf/os_http_be.map
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=22
+ '[' -n 22 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 22
[WARNING] 082/144553 (26) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
E0324 14:45:53.042369       1 router.go:126] Error reloading router: wait: no child processes
 Reload output: + config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ path_map_file=/var/lib/haproxy/conf/os_http_be.map
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=27
+ '[' -n 27 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 27
[WARNING] 082/144553 (31) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
```

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #1434 

@pweil- ping

### CODE REVIEW

**Comment by mrunalp** [comment]
@ramr PTAL. This is cleaner as it breaks out when there are no more children.

**Comment by pweil-** [comment]
This LGTM.

Not a part of this PR but to make sure I understand a corner case:

If there is a bad config and haproxy doesn't start then there would be no child processes of the plugin and the reaper would stop.  Then, corrected data comes through and the haproxy config is valid again.  Are we stuck with no reaper?

We need to take a closer look at error conditions in the plugin anyway - a hosed config needs to revert to a good backup but I want to make sure I'm clear on the above scenario.

**Comment by mrunalp** [comment]
With these changes, whenever a child process or more of them terminate, then we get a minimum of one SIGCHLD. We loop on wait4 with WNOHANG to reap all the children and then the reaper breaks out to wait for the next SIGCHLD. It should handle the scenario you describe. Previously we are were waiting longer in the reap loop, but now because of NOHANG, we break out of it much quicker.

**Comment by pweil-** [comment]
reading comprehension failure on my part.  I completely missed the outer loop.  Thanks @mrunalp  :+1:

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by ramr** [comment]
looks like this got merged already. But in any case, LGTM
Minor typo in message - ```No more process to reap```. Don't worry about that for now.

**Comment by smarterclayton** [comment]
FIX TYPOS :)

----- Original Message -----

**Comment by mrunalp** [comment]
I did realize it after merge process had started. Didn't want to stop that ;)

**Pull request merged**
