### PR TITLE
update cmdconfig.MergeConfig; use --context option in `oc login` if one is provided

### PR DESCRIPTION
**Pull request by juanvallejo**
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1471160

Right now, `oc login` does not acknowledge a `--context` value passed by a user.
Reading the value of this flag would allow users to edit their `kubeconfig` file with a custom name for a current context, and re-use that edited context in future login attempts.

This patch also updates the `MergeConfig` helper, which now looks at existing contexts to see if any contain a matching `authInfo` and `cluster` (regardless of names) before creating a new one.

**Before**
```
$ oc login -u dev -p test --context friendlycontextname
# this would try to use the default context "/hostname:port/dev", despite the user providing a context name to use
Server [https://hostname:port]:
```

**After**
```
$ oc login -u dev -p test --context friendlycontextname
Login successful.
...
```

cc @openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
@akostadinov I attempt to address https://bugzilla.redhat.com/show_bug.cgi?id=1471160#c2 in the latest commit (https://github.com/openshift/origin/pull/16161/commits/474c85fa4c35e23796c5840e8fd07c62394c7d7a).

Given the following context stanzas in a kubeconfig file, and a `current-context` field:

```yaml
contexts:
- context:
    cluster: 10-13-137-206:8443
    user: test/10-13-137-206:8443
  name: foo
current-context: foo
```

Performing `oc login` as user `test` on the same cluster would re-use context `foo` without creating a new one or changing the `current-context` name (`oc login -u test -p test`).

**Comment by akostadinov** [comment]
Is there a nightly build I can try?

**Comment by juanvallejo** [comment]
@akostadinov 
> Is there a nightly build I can try?

No nightly build, but you could fetch and build this PR: `git fetch origin pull/16161/head:pr16161/oc-login-merge-config-pr`

**Comment by juanvallejo** [comment]
@akostadinov A side-effect of this PR would be that, since we are only creating a new context stanza when the server or username changes, creating a new project or even switching to an existing project will just cause the `namespace` field to be updated in an existing stanza (if one already exists with the current cluster and username). This means that if a context has not been renamed to a friendly name, but rather left with its generated name of `<namespace>/server-ip:port/username`, the "namespace" portion of the name will eventually drift as the user changes and creates new projects; so a context named `default/127-0-0-1:8443/username` will not necessarily have its namespace field set to `default`.

This could be mitigated if we allow new contexts to be created any time the namespace changes as well. WDYT?

cc @fabianofranz

**Comment by akostadinov** [comment]
In my view, having `project/namespace` to be part of the context name is useless. It actually is duplicating functionality of  `-n` or `use-project`. The latter make more sense to me and are clearer to the user.

I find it hard to believe somebody is relying on contexts to switch between projects in their current implementation but that is definitely a significant change in behaviour. So may require someone with more data to chime in.

When I login to an environment for the first time I see context generated `name: /api-online-stg-openshift-com:443/username`. It makes sense to me to reuse that context for whatever project I create or use.

In recap, what you describe above - reusing the context, sounds great to me and I find it superior to creating a new context for new projects. Still either approach will be an improvement over old implementation.

HTH, thank you for trying to fix this. I hope to test this on Monday.

**Comment by juanvallejo** [comment]
cc @deads2k @smarterclayton @liggitt

**Comment by liggitt** [comment]
Contexts generated by login are not intended to be user managed, but interacted with via the project command. Stomping a single context in login is not desired

**Comment by akostadinov** [comment]
@liggitt , I can't understand well your post. Would you list the expected use cases? Do we have any UX design around how contexts?
So far I find using different contexts frustrating as I have to always check the file for the context name and over time, using different clusters, the list becomes longer to unmanageable state.

**Comment by liggitt** [comment]
a user using `oc login` and `oc project` is not expected to manage contexts themselves

**Comment by akostadinov** [comment]
Is there a good reason we shouldn't implement it in a way that makes it possible to manage by user and allow easy switching between clusters? Provided users were not supposed to manage contexts in the past then we shouldn't have much compatibility concerns. And I don't see any breaking difference with the above proposed change for the existing use case where user doesn't manage contexts manually.

**Comment by juanvallejo** [comment]
@liggitt @akostadinov closing this PR, since it looks like we will not be allowing users to manage contexts through `oc login`

**Comment by akostadinov** [comment]
I am disappointed that a valid feature request and associated patch is rejected without any logical explanation against it. What is the point then in keeping all this data in the config file if it is not supposed to be useful for the users? It's a PITA to work with multiple environments at the moment.

**Comment by jorgemoralespou** [comment]
Haven't looked into the PR but I totally agree that this behavior and response is not really correct. It's not difficult to fix the behavior to have a proper user UX. Why do we oppose to the improvements?

**Comment by vmtyler** [comment]
Agree with @jorgemoralespou. The idea that a user of oc wouldn't manage their kube contexts only makes sense in the context of that user only ever interacting with OpenShift. If they use *any* other kube instance too they need to manage their contexts, and this approach currently makes a mess of it.

**Pull request closed without merging**
