### PR TITLE
Unidling Controller: Deal with tombstones in cache

### PR DESCRIPTION
**Pull request by DirectXMan12**
The delete handler in the unidling code assumed that the object passed
to the delete EventHandlerFunc would be a `*kapi.Event`.  However, it
can also be a `cache.DeletedFinalStateUnknown`, which previously caused a
panic in the controller.

Fixes bug 1370137

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @ncdc @bmeng

**Comment by DirectXMan12** [comment]
[test]

**Comment by ncdc** [comment]
LGTM. cc @smarterclayton @deads2k @liggitt

**Comment by deads2k** [comment]
lgtm

**Comment by DirectXMan12** [comment]
flaked on #7706, plus AWS ran out of space in the AZ

[test]

**Comment by smarterclayton** [comment]
[test] failure to import

**Comment by ncdc** [comment]
[merge]

**Comment by DirectXMan12** [comment]
[test] flaked on #10663 + and unknown error actually calling out to the scale (I added a commit to this PR which will make sure we can see the error, should it occur again)

**Comment by ncdc** [comment]
[test] #10663

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
