### PR TITLE
Tests for template completion detection

### PR DESCRIPTION
**Pull request by coreydaley**
Dependent on #15402 
Link to my commit: https://github.com/openshift/origin/pull/15776/commits/2d4881cf2cab7e00f9bbb3856a951a6baaa9b70d

### CODE REVIEW

**Comment by coreydaley** [comment]
@jim-minter @bparees ptal

**Comment by jim-minter** [comment]
thanks @coreydaley I've fetched this locally and will push to #15402 shortly.

**Comment by bparees** [comment]
part of https://github.com/openshift/origin/pull/15402

**Pull request closed without merging**
