### PR TITLE
bundle-secret updates

### PR DESCRIPTION
**Pull request by liggitt**
- [x] Updates bundle-secret args to `bundle-secret NAME [SOURCE...]` This lets us use shell expansion to specify source files (e.g. `bundle-secret mysecret *.*`), in addition to `-f file`
- [x] Outputs warnings when skipping directories
- [x] Errors if there are duplicate files specified
- [x] Errors if there are source files, but ultimately no files selected (e.g. `bundle-secret mysecret emptydir`)

### CODE REVIEW

**Comment by liggitt** [comment]
@derekwaynecarr PTAL

**Comment by derekwaynecarr** [comment]
I still feel like we should preserve support for -f as an input argument for sources to be consistent with create command.  Add that back, and then LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
LGTM - github was slow to load for me and got sidetracked before I looked to merge for you.

**Pull request merged**
