### PR TITLE
Update hawtio-core-navigation to 2.0.48

### PR DESCRIPTION
**Pull request by spadgett**
This version fixes a memory leak. See #1921.

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by spadgett** [comment]
@liggitt looks spurious

```
!!! Error in hack/test-cmd.sh:348
  '[ ! "$(osc get rc docker-registry-1)" ]' exited with status 1
Call stack:
  1: hack/test-cmd.sh:348 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
