### PR TITLE
Sanitize S2I Builder tests

### PR DESCRIPTION
**Pull request by rhcarvalho**
Came across duplication and test names that say one thing and test another while working on #6715.

If all changes proposed here are fine I can squash into a single commit.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by mfojtik** [comment]
[test]

**Comment by rhcarvalho** [comment]
[test] again

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by mfojtik** [comment]
LGTM

**Comment by rhcarvalho** [comment]
@bparees PTAL

**Comment by bparees** [comment]
lgtm, need squashing.

**Comment by rhcarvalho** [comment]
@bparees done

**Comment by bparees** [comment]
[merge]

**Pull request merged**
