### PR TITLE
Output logs on network e2e deployment failure

### PR DESCRIPTION
**Pull request by marun**
Jenkins relies on the build log to detect failure cause, but the
networking test runner was previously not outputting dind container
logs.  This change ensures that container logs are output to stdout when
deployment failures occur to maximize the chances of jenkins being able
to detect deployment-related flakes.

cc: @openshift/networking

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by marun** [comment]
@eparis @pravisankar @rajatchopra @dcbw @danwinship: Please merge asap

This will allow detection of failures like #7610 via the following Jenkins failure cause matcher:

https://ci.openshift.redhat.com/jenkins/failure-cause-management/571d3cbbe4b04eba47d90986/

**Comment by danwinship** [comment]
@marun I don't really understand this stuff... maybe get someone who understands the test infrastructure / failure cause matchers / whatever to review/merge it?

**Comment by eparis** [comment]
[merge]

**Pull request merged**
