### PR TITLE
[release-3.11] Bug 1794768: update github.com/openshift/imagebuilder

### PR DESCRIPTION
**Pull request by nalind**
Update imagebuilder to the now-updated tip of its openshift-3.11 branch.  This pulls in changes from 
https://github.com/openshift/imagebuilder/pull/147, https://github.com/openshift/imagebuilder/pull/148, https://github.com/openshift/imagebuilder/pull/152, and https://github.com/openshift/imagebuilder/pull/153.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@nalind, any progress on this?

**Comment by nalind** [comment]
Hmm, I thought the timeouts were transient problems.

/retest

**Comment by nalind** [comment]
Huh, looks like the change I was trying to make here was merged as part of #25416, so I guess we don't need this one any more.

**Pull request closed without merging**
