### PR TITLE
use unique filenames for junit output

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/test extended_builds
/test extended_image_ecosystem

@stevekuznetsov fyi

**Comment by bparees** [comment]
/retest

@stevekuznetsov junit.xml looks healthier anyway, i'd still like to know why we had to turn off junit parsing in jenkins though, it was really handy.  (our nightly extended test jobs don't run through gubernator)

**Comment by stevekuznetsov** [comment]
There were about 50 jobs we turned it off for -- if we inadvertently turned it off for a job not displayed in Gubernator, it can be turned back on. We turned it off because jUnit plugin for Jenkins uses so many resources it was causing the master to crash every other week with the higher volume of jobs.

**Pull request merged**
