### PR TITLE
UPSTREAM: 55631: Parse and return the last line in the log even if it is partial

### PR DESCRIPTION
**Pull request by runcom**
Upstream issue: https://github.com/kubernetes/kubernetes/issues/44976
Needed by CRI-O, @mrunalp PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@smarterclayton @mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM. This is needed to work around upstream CRI log parsing issue where it doesn't return the last line if it doesn't have a newline.

**Comment by ashcrow** [comment]
(Unrelated) Failed for extended_conformance_install_update:

```
INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS
```

**Comment by derekwaynecarr** [comment]
@runcom the referenced upstream is related to DCOS getting started guide.

see: https://github.com/kubernetes/kubernetes/pull/17198

what upstream are you actually intending to carry?

**Comment by runcom** [comment]
> @runcom the referenced upstream is related to DCOS getting started guide.
> 
> see: kubernetes/kubernetes#17198
> 
> what upstream are you actually intending to carry?

yeah, sorry ,that's actually an issue in kube. There's no PR upstream for this patch /cc @mrunalp 
This PR is actually breaking something in tests and @mrunalp is looking at it.

**Comment by liggitt** [comment]
> There's no PR upstream for this patch

why not?

**Comment by mrunalp** [comment]
I created https://github.com/kubernetes/kubernetes/pull/55631 to fix this upstream.

**Comment by derekwaynecarr** [comment]
I want to hold this PR merging in any branch until the corresponding upstream merges.

**Comment by mrunalp** [comment]
upstream for this has merged.

**Comment by mrunalp** [comment]
@smarterclayton @stevekuznetsov We need this to fix the last crio test and start gating on crio in origin.

**Comment by runcom** [comment]
```
Submit Queue — PR does not have lgtm label.
```

@derekwaynecarr you need to re-post your /lgtm I guess

**Comment by runcom** [comment]
Cri-o test is hitting some weird failure on an unrelated test, this PR is fixing the issue so please merge it guys

**Comment by runcom** [comment]
@stevekuznetsov ^^

**Comment by stevekuznetsov** [comment]
This one is currently in the queue, will merge in due time

**Comment by runcom** [comment]
First CRI-O job fully green :tada:

**Comment by stevekuznetsov** [comment]
PARTY

**Pull request merged**
