### PR TITLE
When using 'make run' enable broad cross origin resource sharing

### PR DESCRIPTION
**Pull request by stefwalter**
This is development mode, and enables simple usage with
hack/serve-local-assets.sh

### CODE REVIEW

**Comment by liggitt** [comment]
we already include localhost:9000 by default in dev mode, was there something else this was enabling?

**Comment by stefwalter** [comment]
Hmmm, I'm having a hard time duplicating the problem after rebasing yesterday.

But the problem was that openshift tried to redirect to a local ip address, and CORS would step in due to the difference of origin between localhost and the local ip (192.168.11.5 in my case).

**Comment by liggitt** [comment]
When using `hack/serve-local-assets.sh`, just use localhost and you shouldn't have any issues. `make run` probably shouldn't do anything different than `openshift start`

**Comment by stefwalter** [comment]
Thanks. I'll close this. Things seem to be working well without this patch.

**Pull request closed without merging**
