### PR TITLE
Add rsyslog example config

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@sdodson obviously it needs some comments in the config to describe what it's doing, but what are your initial thoughts of shipping this example?

**Comment by sdodson** [comment]
@detiber :+1 I'd have to re-familiarize myself with rsyslog to follow exactly what you're doing there but at first glance it looks good and I think we should definitely include it.

**Comment by detiber** [comment]
@sdodson the template basically just uses the 'program name' to put the logs in either /var/log/origin or /var/log/atomic-enterprise and puts each unit in it's own file within that directory (without including origin- or atomic-enterprise- in the name).

**Comment by danmcp** [comment]
@detiber Bump.  Still valid?

**Comment by detiber** [comment]
@danmcp I doubt I will get back to this in a reasonable amount of time, closing for the time being.

**Pull request closed without merging**
