### PR TITLE
UPSTREAM: 65549: Fix flexvolume in containerized kubelets

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1602963

/sig storage

### CODE REVIEW

**Comment by liggitt** [comment]
/hold 
for 1.11.1 rebase

**Comment by gnufied** [comment]
@liggitt does the hold still applies?

**Comment by fabianvf** [comment]
@jsafrane looks like it needs the approved label as well, I think /approve does it

**Comment by fabianvf** [comment]
also, can this be backported to origin 3.10?

**Comment by gnufied** [comment]
The failure looks unrelated.

/test gcp

**Pull request merged**
