### PR TITLE
Remove cluster capacity from origin repo

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@derekwaynecarr for when @aveshagarwal's changes merge

**Comment by ingvagabund** [comment]
```
$ grep -rn "cluster-capacity"
hack/lib/constants.sh:179:# cmd/cluster-capacity and doc.go useful for tools that
hack/lib/constants.sh:219:              -o -path '*cmd/cluster-capacity' \
tools/depcheck/examples/origin_excludes.json:4:	"github.com/openshift/origin/cmd/cluster-capacity"
tools/depcheck/pkg/graph/openshift.go:17:		"github.com/openshift/origin/cmd/cluster-capacity",
Binary file .git/objects/pack/pack-c045fc05a193d95e85321a3feb1411a44ae2fc96.pack matches
glide.yaml:3:- cmd/cluster-capacity
```

> hack/lib/constants.sh:179:# cmd/cluster-capacity and doc.go useful for tools that

Just comment
> hack/lib/constants.sh:219:              -o -path '*cmd/cluster-capacity' \

Has no effect
> tools/depcheck/examples/origin_excludes.json:4:	"github.com/openshift/origin/cmd/cluster-capacity"

This should be removed
> tools/depcheck/pkg/graph/openshift.go:17:		"github.com/openshift/origin/cmd/cluster-capacity",

Had no effect
> Binary file .git/objects/pack/pack-c045fc05a193d95e85321a3feb1411a44ae2fc96.pack matches
> glide.yaml:3:- cmd/cluster-capacity

part of the excludeDirs clause
> 

Given the cluster-capacity is about to be removed completely, we can remove all references of the project so noone is surprised when he/she sees the `cluster-capacity` keyword.

It's not a blocker for the PR but it could lead to a confusion in the future.

**Comment by smarterclayton** [comment]
I might have snipped those in the follow up but not in here.  Will look.

**Comment by ingvagabund** [comment]
@aveshagarwal feel free to give lgtm

**Pull request merged**
