### PR TITLE
Rename BaseImage -> Image for DockerBuildStrategy to be consistent with STIBuilderStrategy about field naming

### PR DESCRIPTION
**Pull request by soltysh**
@bparees here you have it :smile:

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by bparees** [comment]
lgtm.

**Comment by mfojtik** [comment]
lgtm

**Comment by bparees** [comment]
lbtj (looks bad to jenkins)

**Comment by soltysh** [comment]
Should be fixed, waiting for tests results.

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
