### PR TITLE
Fix godoc comments and typo in command description

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by php-coder** [comment]
Kubernetes test flake: https://github.com/kubernetes/kubernetes/issues/28569

[test]

**Comment by php-coder** [comment]
The same flake again, please, [test]

**Comment by php-coder** [comment]
@mfojtik ready to merge

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
