### PR TITLE
UPSTREAM: google/cadvisor: 1411: Ensure minimum kernel version for thin_ls

### PR DESCRIPTION
**Pull request by ncdc**
@eparis

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@timothysc this should fix your thin pool woes

**Comment by eparis** [comment]
this will need a re-work once we know the z-stream kernel version...  but LGTM for what we know now.

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
@smarterclayton PetSet related?

```
Running test/cmd/admin.sh:351: executing 'oc create -f test/testdata/app-scenarios' expecting success...
FAILURE after 2.977s: test/cmd/admin.sh:351: executing 'oc create -f test/testdata/app-scenarios' expecting success: the command returned the wrong error code
Standard output from the command:
pod "lonely-pod" created
replicationcontroller "database-app-1" created
replicationcontroller "frontend-app-1" created
service "database-app" created
service "frontend-app" created
service "hello-openshift" created
pod "hello-openshift" created
service "empty-service" created
replicationcontroller "database-rc-1" created
replicationcontroller "frontend-rc-1" created
service "database-rc" created
buildconfig "ruby-sample-build" created
build "ruby-sample-build-1" created
replicationcontroller "database-2" created
replicationcontroller "database-1" created
deploymentconfig "database" created
replicationcontroller "frontend-2" created
replicationcontroller "frontend-1" created
deploymentconfig "frontend" created
service "database" created
service "database-external" created
service "frontend" created
route "frontend" created
route "other" created
buildconfig "sinatra-example-2" created
deploymentconfig "sinatra-example-2" created
imagestream "sinatra-example-2" created
service "sinatra-example-2" created
buildconfig "sinatra-example-1" created
imagestream "sinatra-example-1" created
build "sinatra-example-1-1" created
deploymentconfig "sinatra-example-1" created
service "sinatra-example-1" created
buildconfig "sinatra-app-example" created
imagestream "sinatra-app-example" created
build "sinatra-app-example-1" created
deploymentconfig "sinatra-app-example-a" created
deploymentconfig "sinatra-app-example-b" created
service "sinatra-app-example" created
petset "mysql" created
service "galera" created
pod "mysql-1" created
pod "mysql-2" created

Standard error from the command:
Error from server: The POST operation against Pod could not be completed at this time, please try again.
```

[merge]

**Comment by stevekuznetsov** [comment]
issue xref: #10008

**Pull request merged**
