### PR TITLE
Update to Go 1.7 in the build tools

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Let's sync on your target date for this so I can update the AMIs. This will be weird, since that process can take a day and I'm not sure we can ensure the versions are in sync.

**Comment by smarterclayton** [comment]
There are no changes required for to the AMI for this to land, since all
binaries will be built inside of release images.  It would only impact
things running outside of that flow.

**Comment by stevekuznetsov** [comment]
Right, and as I'm not 100% certain all flows use the container to build everything, the AMI _does_ need to be updated, and I'm not certain there will be no use-case where someone is impacted by the switch. I'm happy to break whoever is using non-standard flows for builds, but we should let them know this is going to happen. Additionally, perhaps we need to find a better way to signal which release image to use for builds in jobs, etc -- I think the current `export` statements in Jenkins job configurations are fragile, and would like to see the default enforced in the scripting surrounding `hack/env` so it's versioned with the code.

**Comment by smarterclayton** [comment]
The release image to use is input to a build, because we need to be able to
run PRs against the latest version of them.  Versioning it as code is
exactly the wrong thing to do, because inputs coming from outside the core
build process would then be locked incorrectly.

I'm also happy to break people who are using non-standard flows - generally
an email is sufficient.  I'm not against updating the AMIs, but the point
of this change is that we are now no longer tied to the version of Go in
the AMI.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by stevekuznetsov** [comment]
> Versioning it as code is exactly the wrong thing to do, because inputs coming from outside the core build process would then be locked incorrectly.

I'm arguing for versioning a default, of course someone can ask for another if they want.

> but the point of this change is that we are now no longer tied to the version of Go in the AMI

We're in a weird transitional state right now where I'm not sure this is 100% done, hence the parallel changes. (see also: deps updated in v-o and the image...)

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge] now that images are updated

**Pull request merged**
