### PR TITLE
Replace /bin/bash in oc rsh with /bin/sh -i

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/7514

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees PTAL

**Comment by mfojtik** [comment]
@bparees @smarterclayton fyi, the web console already use interactive (-i) because the SCL is enabled there but the prompt says "sh" ;-)

**Comment by mfojtik** [comment]
and surprisingly, the `oc rsh foo` enters the interactive shell even if the `-i` is not specified.

**Comment by smarterclayton** [comment]
I think it's because it has a tty

**Comment by mfojtik** [comment]
@smarterclayton which leaves us broken with SCL only when you invoke `oc exec foo /bin/sh -c "ruby"` and we can 'workaround' this by having `tty: true` by default there (it is false now).

**Comment by smarterclayton** [comment]
We can't make exec default to tty, that isn't backwards compatible.
Is the path variable not defined in the container (assuming that has
an effect)?

**Comment by mfojtik** [comment]
@smarterclayton I assume SCL is not just about the PATH, there is more magic done depending on collection :-(

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by smarterclayton** [comment]
Release note this and also send something to users list

**Pull request merged**
