### PR TITLE
UPSTREAM: <carry>: Change docker security opt separator to be compatible with 1.11+

### PR DESCRIPTION
**Pull request by pmorie**
Closes bug 1413100

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by pmorie** [comment]
@stevekuznetsov what is the deal with the build here

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/13671/) failed from the following flakes:
 - [networking](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3980/) failed on: https://github.com/openshift/origin/issues/12865

re[merge]

**Comment by derekwaynecarr** [comment]
@openshift-bot, the last build failed from the following flakes:

    networking failed on: #12865

re[merge]

**Comment by stevekuznetsov** [comment]
If that repeats there is some chance it's due to this PR?

**Comment by smarterclayton** [comment]
Flaked on https://github.com/openshift/origin-gce/pull/12

**Comment by pmorie** [comment]
@openshift-bot, the last build failed from the following flakes:

    networking failed on: #12865

re[merge]

**Comment by pmorie** [comment]
🎲 🎲

**Comment by stevekuznetsov** [comment]
@pmorie sorry had to abort job, some technical issues. you're still in the queue

**Comment by smarterclayton** [comment]
Queue went boom, try again

[merge]

**Comment by smarterclayton** [comment]
Networking hung

**Comment by derekwaynecarr** [comment]
re [merge] again

**Comment by smarterclayton** [comment]
This PR is cursed

On Feb 9, 2017, at 10:37 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/merge FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/63/)
(Base Commit: 898266a
<https://github.com/openshift/origin/commit/898266a23a67f441406a0837a0a1736a44de80aa>
)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12831#issuecomment-278849357>,
or mute
the thread

**Comment by eparis** [comment]
oh my god is anything [merge] ing today?

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/127/) failed from the following flakes:
 - [networking](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking_future/126/consoleFull#2052316086580978c8e4b0742a3aefe9b5) failed on: #11452 

re[merge]

**Comment by stevekuznetsov** [comment]
@pmorie this really does look like your PR is making networking consistently hang.

**Comment by smarterclayton** [comment]
Yeah, removing tag this is suspicious

**Comment by smarterclayton** [comment]
There are lots of things merging and my spider senses are tingling

**Comment by smarterclayton** [comment]
I wish we had test grid history.

**Comment by stevekuznetsov** [comment]
@smarterclayton I've been baby-sitting for the queue today and everything else seems legit.

**Comment by pmorie** [comment]
[testextended][extended:networking-minimal]

Going to try to isolate the networking failure we were seeing.

**Comment by pmorie** [comment]
Next step for me is to debug the test in question - but from looking at the test code, there should be no deps on this change for that particular test to work/break that wouldn't have broken a ton of other tests.  Nonetheless, it does seem that this PR is indicating there's some kind of breakage.  So, time to debug.

**Comment by pmorie** [comment]
I was able to run the failing tests correctly locally, so will need to debug in more detail on the CI environment.

**Comment by pmorie** [comment]
@stevekuznetsov and I have tracked down the issue here:

1.  Docker 1.12 ignores old-format separators
2.  Kubernetes 1.5 uses the behaviors of the docker daemon to DTRT wrt SELinux when no SELinux context is provided for the pod, which is the behavior that the origin CI fell into when it was sending the old separator.  This is why the jobs ran correctly with SELinux enforcing, even though our separators were being ignored.
3.  The networking tests use a DIND setup in order to simulate multiple hosts on a single machine; the DIND version is 1.10, which will fail to start containers if the new-style separator is passed.

@marun is going to submit a change to move the DIND version in the networking tests up to 1.12 today.

**Comment by stevekuznetsov** [comment]
@marun can we tentatively create a card to move the dind image building to rely on RHEL and pull in the same Docker we use for the AMIs so that there is no drift? Is Fedora a necessary target for those jobs?

**Comment by stevekuznetsov** [comment]
Prerequisite https://github.com/openshift/origin/pull/12965 has merged -- thanks @marun 
let's re[test] this now

**Comment by stevekuznetsov** [comment]
Newer DIND images are pulling in `docker-2:1.12.6-6.gitae7d637.fc25`, tests look fine, [merge]

**Comment by jim-minter** [comment]
I'm using `docker-1.10.3-45.gite03ddb8.fc23.x86_64`, and this change means I can't run pods any more:

`Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: Invalid --security-opt: \"label=level:s0:c8,c2\""`

Is this intended?

**Comment by stevekuznetsov** [comment]
Yes. Docker 1.10 is not supported for the current release of Origin.

**Comment by jim-minter** [comment]
What is the minimum version of Docker now required? 1.12? Where is it documented?

**Comment by stevekuznetsov** [comment]
The Origin [installation documentation](https://docs.openshift.org/latest/install_config/install/host_preparation.html#installing-docker) lists 1.12 as the minimum version for 1.5

**Comment by pweil-** [comment]
@pmorie @derekwaynecarr we also required 1.12 for 3.4, this likely needs backported (didn't see another PR from a quick search)

**Pull request merged**
