### PR TITLE
bump(github.com/openshift/source-to-image):358cdb59db90b920e90a5f9a95…

### PR DESCRIPTION
**Pull request by bparees**
…2ef7a3e11df3ad

### CODE REVIEW

**Comment by bparees** [comment]
@soltysh @mfojtik ptal.

**Comment by mfojtik** [comment]
@bparees LGTM

**Comment by soltysh** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
seems like a docker registry failed to start... re-[merge]

**Comment by bparees** [comment]
yum issues.  [merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
