### PR TITLE
Remember token ttl, stop retrieving user/token from localStorage after expiration

### LINKED ISSUE #2282: The UI should discard user/token info after the token expiration time
Currently, the UI stores the info, and only removes it when explicitly logging out or when completing a login flow for another user.

When the token is granted, the UI should remember the expiration time of the token and discard user/token info after that point.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #2282

### CODE REVIEW

**Comment by liggitt** [comment]
@spadgett review

**Comment by liggitt** [comment]
Actually, I want to tweak this to store the TTL separately from the stored objects to avoid polluting the returned data

**Comment by spadgett** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
