### PR TITLE
bump(k8s.io/kubernetes): fix kubernetes revisions

### PR DESCRIPTION
**Pull request by soltysh**
Followup to #21887. 

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
@soltysh glide.lock change w/ no actual file changes?   Seems odd, especially since I see a bunch of commits between the old ref and the new one:

https://github.com/openshift/kubernetes/commits/origin-3.11-kubernetes-1.11.1

what's going on?

**Comment by soltysh** [comment]
> what's going on?

That means we're in sync with our fork, since we sync from here to our fork. This only bumps the levels so they are correct.

**Comment by bparees** [comment]
> That means we're in sync with our fork, since we sync from here to our fork. 

So when I did my bump it had picked up the newest code, but for some reason the glide.lock didn't reflect the actual commit of the code it picked up?

/lgtm

**Pull request merged**
