### PR TITLE
Router has an expired certificate by default

### PR DESCRIPTION
**Pull request by pecameron**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1349144

The haproxy router has a default certificate that has expired.
The certificate is used in reporting errors. The admin is
encouraged to supply a certificate as part setting up the router.
When that is not done this certificate used.

New Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 13346332625879039973 (0xb937b2cfb3b9ffe5)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=--, ST=SomeState, L=SomeCity, O=SomeCompany,
        OU=SomeOrganization,
        CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Jun 30 13:24:25 2016 GMT
            Not After : Jun 30 13:24:25 2026 GMT

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc  @ramr @marun  PTAL
This is a new default certificate with a 10 year expiration.

**Comment by knobunc** [comment]
Here's the new cert details:
```
 $ openssl x509 -in /tmp/foo -noout -text
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            b9:37:b2:cf:b3:b9:ff:e5
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=--, ST=SomeState, L=SomeCity, O=SomeCompany, OU=SomeOrganization, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Jun 30 13:24:25 2016 GMT
            Not After : Jun 30 13:24:25 2026 GMT
        Subject: C=--, ST=SomeState, L=SomeCity, O=SomeCompany, OU=SomeOrganization, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d7:51:5b:22:73:22:ff:e3:1e:76:0f:f2:11:9a:
                    a8:18:08:25:60:ea:75:58:21:d1:21:ac:5f:ca:56:
                    af:cc:eb:66:f3:84:ab:ab:f9:90:99:6a:e9:26:c9:
                    94:be:1f:fa:b0:1b:c7:f8:7a:d4:20:4f:e8:cd:ec:
                    2d:44:90:d5:d4:db:09:ff:5e:63:ec:20:cc:7b:c3:
                    a4:0f:4a:06:ea:8a:08:d6:02:4b:6f:4c:9e:17:f7:
                    0c:0b:54:a6:61:94:46:a7:d8:9f:74:22:84:3e:c6:
                    25:41:5e:77:42:e0:e9:84:c0:70:1d:3b:2c:7b:e0:
                    39:5e:27:07:44:40:56:9b:99:c0:ef:b5:b7:3b:c4:
                    1b:4c:73:cc:8d:3b:fd:67:41:63:4c:ff:6a:3d:a4:
                    ba:ac:0f:8a:c7:c0:24:9d:d9:1a:fd:71:c8:82:91:
                    96:b0:4b:7a:dd:07:59:6e:fd:c7:bd:d7:31:74:d9:
                    ee:a8:20:45:1a:9e:40:38:85:7b:f3:d1:f0:5d:39:
                    cd:15:a6:c6:d3:a8:0b:a8:64:47:43:3a:f3:7a:ee:
                    e4:15:cb:72:de:8b:5f:2c:7e:11:c7:71:01:2e:f4:
                    37:64:ec:15:cc:f3:92:40:b1:9f:9c:a4:e1:c1:bd:
                    88:18:54:38:da:45:54:fc:5e:3b:d6:62:7e:39:0f:
                    ea:55
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha1WithRSAEncryption
         31:8a:1f:5a:d7:86:3e:d6:0f:b4:a0:f1:e0:2e:03:4c:ba:4d:
         19:c3:50:ce:57:77:fc:17:5a:fc:ba:87:e6:95:ff:42:b2:f4:
         e2:be:85:eb:53:65:3e:40:d7:3b:25:f2:43:88:95:0a:e3:8b:
         36:d9:4c:89:67:44:16:cd:fe:42:2e:d7:9b:a3:fb:ba:cc:46:
         10:f8:15:0e:f4:87:3f:e1:49:f9:cc:7a:10:dc:95:be:e9:57:
         c5:ec:bb:c4:4f:1d:fe:f1:93:c1:38:19:d8:39:5b:9e:10:28:
         e9:3e:72:62:60:4e:9e:27:14:e7:39:28:1f:48:8f:0a:eb:ac:
         f9:d8:0a:80:61:76:19:73:a1:f4:95:fe:ae:85:54:a9:cb:02:
         ae:86:e1:0c:d1:3e:bd:7a:3a:3b:18:43:6b:de:c3:07:b3:39:
         de:ee:b1:32:c4:25:d9:33:59:4c:2a:bf:bf:2b:46:da:e1:78:
         3a:97:21:e3:e1:b6:ad:58:29:ef:c3:99:5d:22:94:8f:91:8b:
         8e:99:9f:f7:7d:d5:62:7d:6e:0e:66:17:ff:1f:48:4b:be:64:
         1d:3e:91:75:b1:d5:3b:73:6e:89:fb:5b:21:00:2f:37:16:2b:
         13:c6:ee:37:37:0e:7e:92:45:ac:fe:b9:3c:0b:d8:32:0a:f8:
         6a:34:eb:27
```

And the old cert:
```
 $ openssl x509 -in *pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 30676 (0x77d4)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=--, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationalUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Feb 24 05:56:46 2014 GMT
            Not After : Feb 24 05:56:46 2015 GMT
        Subject: C=--, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationalUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:ab:28:42:50:73:91:f8:be:3c:a8:ce:23:68:3d:
                    d6:1c:cf:53:05:e3:0c:5d:a5:38:8c:03:3f:22:f5:
                    8e:9c:3b:3e:9f:79:de:e0:29:e0:28:e9:ed:b6:ee:
                    f9:d0:2c:8b:51:b4:87:9d:cb:0f:e8:c8:ae:25:65:
                    ae:c3:a3:cf:ea:f0:3d:70:47:27:d7:62:37:0f:b0:
                    f6:de:83:89:68:28:56:3a:a3:57:1c:ee:4c:63:e1:
                    59:8c:d2:10:20:d3:93:dd:6d:8f:9b:20:8f:26:33:
                    f6:d8:84:8c:54:89:de:64:ed:33:94:3b:05:d3:f3:
                    20:fd:29:96:b9:02:f1:b7:25
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                3C:A8:B2:0A:3E:3C:86:5C:A5:92:86:63:53:09:D1:28:11:5C:6A:6C
            X509v3 Authority Key Identifier: 
                keyid:3C:A8:B2:0A:3E:3C:86:5C:A5:92:86:63:53:09:D1:28:11:5C:6A:6C

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha1WithRSAEncryption
         8e:f2:18:bd:32:43:95:3b:49:60:b0:6e:c0:5d:b7:57:fe:df:
         c0:4d:05:cb:ac:c9:3b:e8:4c:07:e7:b2:c3:8f:3c:09:77:ce:
         f6:4f:28:cf:f7:2c:d7:1e:ec:1e:7e:dc:55:2e:ea:9b:89:cf:
         35:e1:bf:e4:9d:1f:8e:69:78:52:73:69:91:f7:a6:69:5c:de:
         1b:ac:2c:41:c7:8d:5a:a3:12:16:95:75:d7:47:12:89:5b:a3:
         91:08:97:a3:45:ab:04:26:df:d7:3d:88:eb:6d:09:e1:96:63:
         5d:8e:2e:11:de:20:dc:69:86:6a:fd:4c:1e:12:03:aa:56:17:
         4e:9a
```

**Comment by knobunc** [comment]
I wonder if we should be keeping the serial number the same and bumping the version to 4?

**Comment by knobunc** [comment]
[test]

**Comment by liggitt** [comment]
serialnumber+issuer should be universally unique

**Comment by knobunc** [comment]
@liggitt: sorry, yes.  I meat version number... edited my comment :-(

**Comment by knobunc** [comment]
[test]

**Comment by pecameron** [comment]
@knobunc PTAL

Made a x509v3 certificate.

$ openssl x509 -in cert.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 14036440248487208697 (0xc2cb7409aa1366f9)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=--, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationalUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Jun 30 19:35:28 2016 GMT
            Not After : Jun 30 19:35:28 2026 GMT
        Subject: C=--, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationalUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d3:77:2a:fe:f7:68:19:e8:1c:e1:16:af:d7:06:
                    c7:2b:80:89:82:31:23:18:00:f1:a0:34:97:a2:71:
                    94:4b:47:a9:f0:72:a9:66:07:d7:61:f9:0f:ee:6e:
                    0b:a5:76:98:e9:4d:20:51:48:88:2c:07:c5:a1:1a:
                    7b:61:99:98:ee:d4:7a:81:6f:8a:10:76:45:63:3c:
                    7c:fb:c2:ad:ae:a3:ee:c3:c2:87:ba:d1:4b:ef:7a:
                    3f:8d:f1:75:66:f9:4a:ba:a7:43:e4:fb:9f:63:cd:
                    bf:05:cc:c0:73:70:62:69:7b:29:52:46:5a:7d:e1:
                    6c:ce:63:70:32:24:a3:5a:fd:49:6c:4c:b3:4c:c5:
                    4d:e4:42:68:c2:63:eb:fd:3a:b4:d5:0b:3a:1a:00:
                    82:58:02:71:f4:3e:67:0f:a5:cd:0e:32:8c:eb:81:
                    8a:c7:6f:f0:51:eb:b9:a3:80:73:76:46:de:78:ba:
                    7e:1e:55:8e:0f:0d:a3:f0:9d:30:6c:03:0b:6b:d8:
                    aa:1e:82:f4:28:49:55:32:3d:1c:a6:05:54:76:97:
                    ca:a5:e7:87:47:46:43:f4:f9:2d:b0:d1:f7:63:03:
                    7e:e5:62:b1:b7:6c:95:df:9d:37:dd:6f:53:08:1b:
                    ed:15:ae:f1:76:ad:48:ea:cb:9d:e1:ff:d7:59:6c:
                    dc:f3
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                DirName:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
                serial:C2:CB:74:09:AA:13:66:F9

            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment
    Signature Algorithm: sha256WithRSAEncryption
         83:ee:d6:9c:6c:b8:50:08:c0:eb:16:1a:b7:54:43:41:5f:0f:
         5e:14:95:a2:b9:cf:94:c2:02:dd:b5:d0:2f:c8:d9:3b:3b:ec:
         91:26:17:94:3e:e9:d2:a8:5e:e9:07:d2:4b:fe:b8:68:f4:9f:
         78:43:02:bd:01:2c:20:e0:33:ca:2a:53:2c:81:8c:74:21:a5:
         b3:d9:e7:f8:fb:6b:00:ae:55:e5:55:2f:bd:50:40:d2:a1:40:
         ae:45:3c:e3:ce:9f:d7:5a:48:5d:1c:61:3e:cc:af:8f:ad:86:
         e2:5e:a3:70:af:c0:02:d0:ff:27:64:b3:1f:84:47:b4:ca:66:
         9e:c2:fb:cb:f2:8c:4b:65:e8:94:83:16:55:fe:f7:a7:dc:45:
         ff:08:17:a2:f9:5e:c8:7b:63:67:73:4c:ec:de:d1:52:b3:74:
         ec:ec:b6:ce:d0:a7:63:4b:92:57:cb:46:64:fe:f5:72:23:1c:
         dc:da:9a:10:16:fc:8f:d9:d8:4c:e6:92:3d:fd:fa:41:27:b2:
         93:69:d5:53:e4:d0:16:24:03:61:be:78:44:de:73:ed:67:1d:
         68:52:15:9a:aa:df:ff:bb:08:2d:6e:e5:ff:19:c7:27:2b:c9:
         82:e4:1c:3a:cd:a9:ce:d5:b0:d8:46:45:3d:3e:e5:91:be:f1:
         8d:11:16:20

**Comment by pecameron** [comment]
@knobunc more changes -- PTAL
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 15068095030625975298 (0xd11ca0989e4a3c02)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=XX, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Jul  6 14:10:12 2016 GMT
            Not After : Jul  6 14:10:12 2026 GMT
        Subject: C=XX, ST=SomeState, L=SomeCity, O=SomeOrganization, OU=SomeOrganizationUnit, CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:bf:57:65:8d:56:23:93:df:29:4e:6d:89:88:98:
                    4e:66:c9:1c:40:4a:06:38:77:4a:3c:a8:9a:71:b8:
                    f3:0e:1b:ac:e1:c5:26:f4:c2:33:13:d6:14:0f:22:
                    ac:35:9e:8b:f8:8f:d8:cc:ad:c8:0c:b9:7a:14:64:
                    08:cf:50:d3:ce:29:67:07:d4:82:bf:60:85:76:48:
                    a8:65:e3:3a:28:50:87:1a:1a:8a:a8:01:33:89:21:
                    05:6b:11:1f:13:83:90:66:7a:11:88:22:12:13:fc:
                    df:a6:34:44:1d:08:3e:60:0b:fa:8c:25:30:69:4d:
                    93:ce:8f:f2:1b:48:6b:a3:94:ef:24:41:b6:6e:09:
                    ec:0c:07:c4:8d:67:1a:52:6c:42:d8:3b:df:bc:19:
                    df:ed:ba:71:23:94:70:8d:88:02:39:91:4c:30:26:
                    8b:07:76:1d:7a:ac:4d:5a:58:c2:3f:ae:f5:21:46:
                    94:88:89:aa:6c:9f:d6:0a:8d:04:6c:07:a2:1e:26:
                    d6:49:21:4b:95:e0:ac:05:5c:80:e8:70:68:6f:6d:
                    a3:b8:e4:1b:3e:bd:1f:27:cb:bb:48:35:3d:f8:59:
                    22:51:94:55:d0:2c:f6:3d:c7:94:3d:fb:fc:e1:24:
                    74:39:f9:85:74:8d:62:25:07:81:54:75:59:e0:6e:
                    72:e5
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                DirName:/C=XX/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationUnit/CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
                serial:D1:1C:A0:98:9E:4A:3C:02

            X509v3 Subject Key Identifier: 
                98:C9:38:24:CF:B5:7A:51:D8:EE:62:7A:A1:C2:40:AB:8A:80:BE:47
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
    Signature Algorithm: sha256WithRSAEncryption
         bb:46:ba:5f:3c:b9:c7:e0:25:b2:e4:b1:33:c8:52:18:58:50:
         26:5c:15:46:df:34:55:42:20:df:77:4f:11:a3:ad:c0:49:e3:
         68:7b:ed:8b:f6:ed:54:58:10:76:1e:df:e5:fc:fa:91:03:af:
         5d:6a:18:4e:35:b6:3e:6b:5b:3a:d4:cd:58:ea:14:0a:8d:0b:
         50:20:07:a7:34:42:93:96:23:bb:16:ff:2b:64:fa:02:b5:7e:
         ec:b1:06:b8:d7:1a:d3:6e:bd:ac:58:4e:11:e1:1b:06:d5:18:
         2a:d4:5e:8f:38:e6:b8:de:7d:32:f2:93:81:19:7b:2d:ff:fd:
         18:08:5a:fa:80:e5:a9:de:da:b2:2c:11:8c:59:4f:e6:af:f9:
         cf:ae:6a:b4:34:85:2a:e5:fb:4b:ce:bc:80:ad:9c:0f:60:f8:
         f8:65:cb:21:e7:84:48:95:d8:05:73:a4:27:03:65:90:de:ff:
         16:64:95:95:30:42:59:21:4d:83:92:54:59:ff:33:4e:38:2c:
         34:05:20:f5:e8:62:49:7e:26:79:3a:d9:7d:2b:4b:f3:3b:63:
         47:fe:25:14:c8:8d:ff:d6:27:a5:b0:1f:44:6c:55:fb:6d:10:
         53:93:26:42:4b:c1:62:58:0f:13:a4:d2:43:3e:10:a2:29:d8:
         40:0e:da:0b

**Comment by knobunc** [comment]
Closing in preference to https://github.com/openshift/origin/pull/9719

**Pull request closed without merging**
