### PR TITLE
Bash is the worst programming language ever invented

### PR DESCRIPTION
**Pull request by smarterclayton**
And process management is a disaster of epic proportions.

[test]

### CODE REVIEW

**Comment by sosiouxme** [comment]
come on, worse than cobol and fortran?

**Comment by smarterclayton** [comment]
Qualified: It's the worst programming language you're forced to deal with every day.

**Comment by deads2k** [comment]
Doesn't look like it works.


openshift-router remains
```
[deads@deads-dev-01 origin]$ ps ax | grep opens
13797 ?        Ssl    0:00 /usr/bin/openshift-router --template=/var/lib/haproxy/conf/haproxy-config.template --reload=/var/lib/haproxy/reload-haproxy --loglevel=4
```

docker containers are still running
```
[deads@deads-dev-01 origin]$ docker ps
CONTAINER ID        IMAGE                                                                                                         COMMAND                CREATED              STATUS              PORTS                                      NAMES
96d1c4a55295        openshift/origin-haproxy-router:latest                                                                        "/usr/bin/openshift-   About a minute ago   Up About a minute                                              k8s_origin-haproxy-router-router1.d89546bb_router1.default.api_7aac5984-ac6d-11e4-b0b1-28d2447dc82b_01200157                        
5f968b230eaf        openshift/origin-pod:latest                                                                                   "/pod"                 About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   k8s_POD.86bcfaa0_router1.default.api_7aac5984-ac6d-11e4-b0b1-28d2447dc82b_75996da4                                                  
1f66aaf425ba        172.30.17.228:5001/test/origin-ruby-sample:f01fed3e8d4f1c3c11129ea07ba240f98ff809cbc640e6f01365baa3b780d627   "/tmp/scripts/run"     About a minute ago   Up About a minute                                              k8s_ruby-helloworld.a1b03e81_72e06da9-ac6d-11e4-b0b1-28d2447dc82b.test.api_72e06da9-ac6d-11e4-b0b1-28d2447dc82b_f49ad967            
f796f18137f5        openshift/origin-pod:latest                                                                                   "/pod"                 About a minute ago   Up About a minute                                              k8s_POD.201bd851_72e06da9-ac6d-11e4-b0b1-28d2447dc82b.test.api_72e06da9-ac6d-11e4-b0b1-28d2447dc82b_577237e4                        
d4fa912ec10d        mysql:latest                                                                                                  "/entrypoint.sh mysq   2 minutes ago        Up 2 minutes                                                   k8s_ruby-helloworld-database.fe1001f0_425e1076-ac6d-11e4-b0b1-28d2447dc82b.test.api_425e1076-ac6d-11e4-b0b1-28d2447dc82b_9b5c31dd   
cf528999a4a4        openshift/origin-pod:latest                                                                                   "/pod"                 2 minutes ago        Up 2 minutes                                                   k8s_POD.199ad84d_425e1076-ac6d-11e4-b0b1-28d2447dc82b.test.api_425e1076-ac6d-11e4-b0b1-28d2447dc82b_658ccb7c                        
206165caa2be        openshift/origin-pod:latest                                                                                   "/pod"                 2 minutes ago        Up 2 minutes                                                   k8s_POD.7a99b72d_build-3df22c0f-ac6d-11e4-b0b1-28d2447dc82b.test.api_3e179bca-ac6d-11e4-b0b1-28d2447dc82b_fc0cdda1                  
1b734618e5d6        openshift/docker-registry:latest                                                                              "\"sh -c 'echo \"$OP   3 minutes ago        Up 3 minutes                                                   k8s_registry-container.92e98182_257b9d1f-ac6d-11e4-b0b1-28d2447dc82b.default.api_257b9d1f-ac6d-11e4-b0b1-28d2447dc82b_d3d16c2d      
69d63edb569b        openshift/origin-pod:latest                                                                                   "/pod"                 3 minutes ago        Up 3 minutes                                                   k8s_POD.e56d846_257b9d1f-ac6d-11e4-b0b1-28d2447dc82b.default.api_257b9d1f-ac6d-11e4-b0b1-28d2447dc82b_1cfd57ea                      
```

**Comment by jhadvig** [comment]
Agreeing with title :+1:

**Comment by smarterclayton** [comment]
Something about how it's working on fed20 and OS X vs other systems is messing with this.  It could be about whether you're running test end to end as root?

**Comment by smarterclayton** [comment]
I think this *actually* fixes it.  But I thought it before.  Won't kill misbehaving children, but eh.

**Comment by deads2k** [comment]
There is some loss of confidence,  hack/test-end-to-end.sh runs with root permissions, does he know enough to not accidentally hose my system....

**Comment by deads2k** [comment]
works for me.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
