### PR TITLE
Fix sr-only text for pod status chart

### PR DESCRIPTION
**Pull request by spadgett**
See #5988

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
Spurious, [test]

```
!!! Error in hack/../test/end-to-end/core.sh:160
	'oc delete pod cli-with-token' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:160 main(...)
Exiting with status 1
```

**Comment by spadgett** [comment]
re[merge]

```
Error from server: Timeout: timed out waiting for deployment test/failing-dc-1 to start after 10s
!!! Error in hack/../test/end-to-end/core.sh:173
	'oc logs -f dc/failing-dc' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:173 main(...)
Exiting with status 1
```

**Pull request merged**
