### PR TITLE
Fix errors creating from source in UI

### PR DESCRIPTION
**Pull request by spadgett**
- Remove generated port name
- Update build config `spec.output.to` to `kind: ImageStreamTag`

https://bugzilla.redhat.com/show_bug.cgi?id=1241392

### CODE REVIEW

**Comment by liggitt** [comment]
Remove generated container port name... that's not useful

**Comment by liggitt** [comment]
Fix application generator spec

**Comment by spadgett** [comment]
@liggitt updated

**Comment by liggitt** [comment]
lgtm, [merge]

**Pull request merged**
