### PR TITLE
pkg/quota/controller: Fix typo in file name

### PR DESCRIPTION
**Pull request by rhcarvalho**

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm, but I doubt it makes the cut.

**Comment by deads2k** [comment]
@mfojtik to decide if it makes the 1.4 cut.

**Comment by mfojtik** [comment]
[test]

**Comment by rhcarvalho** [comment]
@mfojtik are we in a good time to merge this?

**Comment by mfojtik** [comment]
yes, sorry!

[merge]

**Pull request merged**
