### PR TITLE
Tracking PR for 1.3 console changes

### PR DESCRIPTION
**Pull request by jwforres**
Includes changes from original PRs:
https://github.com/openshift/origin/pull/8186
https://github.com/openshift/origin/pull/7929
https://github.com/openshift/origin/pull/7994
https://github.com/openshift/origin/pull/8157

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett @fabianofranz @jhadvig @benjaminapetersen @sg00dwin @rhamilto

**Comment by jwforres** [comment]
1.3 branch has been rebased, bindata is built, lets start with a [test]

**Comment by smarterclayton** [comment]
You going to merge this bad boy tomorrow?

**Comment by jwforres** [comment]
@smarterclayton thats the plan

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
@spadgett looks like the e2e test that does project delete failed because of the new type the name confirmation stuff, should just need to add a line to find the input and send the keys for the name

**Comment by spadgett** [comment]
@jwforres yeah, i saw this morning. i'll fix

**Comment by spadgett** [comment]
@jwforres https://github.com/jwforres/origin/pull/69/files

**Comment by jwforres** [comment]
[test]

**Comment by fabianofranz** [comment]
\o/

**Comment by jwforres** [comment]
ok, here it goes...  [merge]

**Comment by smarterclayton** [comment]
\m/

**Comment by smarterclayton** [comment]
OH NOES STOOOOOOOPPPPPPPPP

**Comment by jwforres** [comment]
Can't stop this train

**Comment by spadgett** [comment]
unstoppable train game

**Comment by benjaminapetersen** [comment]
😯 ... 😳 ... 😰 ... 😱

**Comment by fabianofranz** [comment]
https://www.youtube.com/watch?v=aiMECPUxjIU

**Comment by jhadvig** [comment]
e2161543fb07fbef4f3b8748567fdbb1

**Pull request merged**
