### PR TITLE
UPSTREAM: 89592: log previous pod logs if pod was removed

### PR DESCRIPTION
**Pull request by dcbw**
`Apr  2 20:19:21.689: INFO: unable to fetch logs for pods: paused-1-lzxdz[e2e-test-cli-deployment-79fhw].container[myapp].error=the server could not find the requested resource (get pods paused-1-lzxdz)`

Companion to https://github.com/openshift/origin/pull/24799 except this part of the code is not upstream so must be carried.

@danwinship @knobunc

### CODE REVIEW

**Comment by sjenning** [comment]
@dcbw is there any reason this could not be accepted upstream as well so we don't have to carry?

**Comment by dcbw** [comment]
> @dcbw is there any reason this could not be accepted upstream as well so we don't have to carry?

@sjenning also the code I'm touching here isn't upstream anyway; it's already <carry> code.

**Comment by dcbw** [comment]
@danwinship @sjenning PTAL thanks!

**Comment by danwinship** [comment]
/lgtm
but honestly we should just rip out that code. I asked about this upstream and you claimed you really did care about the pod logs, but now that I have more context, I realize you don't, you just want the test to fail with the right error message instead of the wrong one

**Pull request closed without merging**
