### PR TITLE
Bug 1755936: e2e: fix ingress metrics parallelism flake

### PR DESCRIPTION
**Pull request by ironcladlou**
This ingress metrics test manages an ingresscontroller that is not unique,
violating parallel test invariants. Because parallel tests try to own the same
ingresscontroller and tend to overlap, one test deletes the resource of the
other, causing assertion failures.

Use a unique name for newly created ingresscontrollers to ensure the tests can
safely execute in parallel.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@smarterclayton this should fix the ingress metrics flake.

**Comment by ironcladlou** [comment]
@smarterclayton @wking — I'm afraid I'm chasing a red herring with the parallel angle.

Something I think I was confused about: I think the parallel suite just queues up tests to run them in parallel, and so that means there wouldn't be concurrent executions of this test logic. Correct? If so this PR doesn't fix anything.

I now notice the test was marked flaky — does that mean it was retried serially (in relation to the first run) and passed? I have evidence that the test logic repeated (operator logs and such), but no evidence from the test log that the test actually ran twice. Just the failure output and no corresponding output from a retry. Maybe I'm missing it.

During the course of investigating this I've found some weird data in prometheus which _seems_ to indicate missing and incorrect job labels _sometimes_ applied to prometheus targets for new ingresscontroller services.

I'm going to continue chasing those discrepancies down until I can understand them.

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-gcp-4.2/409

For example, if you set up the same prometheus ingresscontroller from the test on an AWS cluster and compare the resulting prometheus targets with those from the CI run, the CI run actually shows some job definitions associated with the test ingress controller's service, but the scrape labels are missing and the job name is the same as the default ingresscontroller job name, which is just wrong.

Gathered from https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/targets (which btw returns like 2mb of data in these clusters which is dumped into the e2e logs!)

```diff
3c3
<     "__address__": "10.128.2.15:1936",
---
>     "__address__": "10.128.3.9:1936",
5,6c5,6
<     "__meta_kubernetes_endpoint_address_target_name": "router-prometheus-b69fb8455-88tjx",
<     "__meta_kubernetes_endpoint_node_name": "ip-10-0-172-14.us-east-2.compute.internal",
---
>     "__meta_kubernetes_endpoint_address_target_name": "router-prometheus-5c688d88d7-qp8ts",
>     "__meta_kubernetes_endpoint_node_name": "ci-op--4pzgd-w-b-9scz9.c.openshift-gce-devel-ci.internal",
12c12
<     "__meta_kubernetes_pod_annotation_k8s_v1_cni_cncf_io_networks_status": "[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.2.15\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]",
---
>     "__meta_kubernetes_pod_annotation_k8s_v1_cni_cncf_io_networks_status": "[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.3.9\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]",
21,23c21,23
<     "__meta_kubernetes_pod_controller_name": "router-prometheus-b69fb8455",
<     "__meta_kubernetes_pod_host_ip": "10.0.172.14",
<     "__meta_kubernetes_pod_ip": "10.128.2.15",
---
>     "__meta_kubernetes_pod_controller_name": "router-prometheus-5c688d88d7",
>     "__meta_kubernetes_pod_host_ip": "10.0.32.2",
>     "__meta_kubernetes_pod_ip": "10.128.3.9",
25c25
<     "__meta_kubernetes_pod_label_pod_template_hash": "b69fb8455",
---
>     "__meta_kubernetes_pod_label_pod_template_hash": "5c688d88d7",
28,29c28,29
<     "__meta_kubernetes_pod_name": "router-prometheus-b69fb8455-88tjx",
<     "__meta_kubernetes_pod_node_name": "ip-10-0-172-14.us-east-2.compute.internal",
---
>     "__meta_kubernetes_pod_name": "router-prometheus-5c688d88d7-qp8ts",
>     "__meta_kubernetes_pod_node_name": "ci-op--4pzgd-w-b-9scz9.c.openshift-gce-devel-ci.internal",
32c32
<     "__meta_kubernetes_pod_uid": "2a57946d-e0c0-11e9-993b-0acb394f1cd6",
---
>     "__meta_kubernetes_pod_uid": "88324571-e059-11e9-91d0-42010a000003",
34,35c34,35
<     "__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_signed_by": "openshift-service-serving-signer@1569509594",
<     "__meta_kubernetes_service_annotation_service_beta_openshift_io_serving_cert_signed_by": "openshift-service-serving-signer@1569509594",
---
>     "__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_signed_by": "openshift-service-serving-signer@1569499133",
>     "__meta_kubernetes_service_annotation_service_beta_openshift_io_serving_cert_signed_by": "openshift-service-serving-signer@1569499133",
44,57c44,45
<     "job": "openshift-ingress/router-prometheus/0"
<   },
<   "labels": {
<     "endpoint": "metrics",
<     "instance": "10.128.2.15:1936",
<     "job": "router-internal-prometheus",
<     "namespace": "openshift-ingress",
<     "pod": "router-prometheus-b69fb8455-88tjx",
<     "service": "router-internal-prometheus"
<   },
<   "scrapeUrl": "https://10.128.2.15:1936/metrics",
<   "lastError": "",
<   "lastScrape": "2019-09-27T00:52:47.170552639Z",
<   "health": "up"
---
>     "job": "openshift-ingress/router-default/0"
>   }
```

I'm still digging through prometheus source to understand more clearly how the job label is constructed, and will re-open https://github.com/openshift/origin/pull/23876 to collect data which will more clearly show the input state to prometheus in the failure scenario.

cc @brancz 

/hold

**Comment by wking** [comment]
> I now notice the test was marked flaky — does that mean it was retried serially (in relation to the first run) and passed?

Yup.

**Comment by smarterclayton** [comment]
Retries are serial at the very end (nothing runs in parallel when retried).

Parallel will run any test in parallel, but remember if you have two tests
in a suite using a shared namespace / variable / object you *can* race
against yourself.



On Sep 27, 2019, at 7:03 PM, Dan Mace <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> @wking
<https://github.com/wking> — I'm afraid I'm chasing a red herring with the
parallel angle.

Something I think I was confused about: I think the parallel suite just
queues up tests to run them in parallel, and so that means there wouldn't
be concurrent executions of this test logic. Correct? If so this PR doesn't
fix anything.

I now notice the test was marked flaky — does that mean it was retried
serially (in relation to the first run) and passed? I have evidence that
the test logic repeated (operator logs and such), but no evidence from the
test log that the test actually ran twice. Just the failure output and no
corresponding output from a retry. Maybe I'm missing it.

During the course of investigating this I've found some weird data in
prometheus which *seems* to indicate missing and incorrect job labels
*sometimes* applied to prometheus targets for new ingresscontroller
services.

I'm going to continue chasing those discrepancies down until I can
understand them.

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-gcp-4.2/409

For example, if you set up the same prometheus ingresscontroller from the
test on an AWS cluster and compare the resulting prometheus targets with
those from the CI run, the CI run actually shows some job definitions
associated with the test ingress controller's service, but the scrape
labels are missing and the job name is the same as the default
ingresscontroller job name, which is just wrong.

Gathered from
https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/targets (which
btw returns like 2mb of data in these clusters which is dumped into the e2e
logs!)

3c3<     "__address__": "10.128.2.15:1936",--->     "__address__":
"10.128.3.9:1936",5,6c5,6<
"__meta_kubernetes_endpoint_address_target_name":
"router-prometheus-b69fb8455-88tjx",<
"__meta_kubernetes_endpoint_node_name":
"ip-10-0-172-14.us-east-2.compute.internal",--->
"__meta_kubernetes_endpoint_address_target_name":
"router-prometheus-5c688d88d7-qp8ts",>
"__meta_kubernetes_endpoint_node_name":
"ci-op--4pzgd-w-b-9scz9.c.openshift-gce-devel-ci.internal",12c12<
"__meta_kubernetes_pod_annotation_k8s_v1_cni_cncf_io_networks_status":
"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n
  \"ips\": [\n        \"10.128.2.15\"\n    ],\n    \"default\":
true,\n    \"dns\": {}\n}]",--->
"__meta_kubernetes_pod_annotation_k8s_v1_cni_cncf_io_networks_status":
"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n
  \"ips\": [\n        \"10.128.3.9\"\n    ],\n    \"default\": true,\n
   \"dns\": {}\n}]",21,23c21,23<
"__meta_kubernetes_pod_controller_name":
"router-prometheus-b69fb8455",<     "__meta_kubernetes_pod_host_ip":
"10.0.172.14",<     "__meta_kubernetes_pod_ip": "10.128.2.15",--->
"__meta_kubernetes_pod_controller_name":
"router-prometheus-5c688d88d7",>     "__meta_kubernetes_pod_host_ip":
"10.0.32.2",>     "__meta_kubernetes_pod_ip": "10.128.3.9",25c25<
"__meta_kubernetes_pod_label_pod_template_hash": "b69fb8455",--->
"__meta_kubernetes_pod_label_pod_template_hash":
"5c688d88d7",28,29c28,29<     "__meta_kubernetes_pod_name":
"router-prometheus-b69fb8455-88tjx",<
"__meta_kubernetes_pod_node_name":
"ip-10-0-172-14.us-east-2.compute.internal",--->
"__meta_kubernetes_pod_name": "router-prometheus-5c688d88d7-qp8ts",>
  "__meta_kubernetes_pod_node_name":
"ci-op--4pzgd-w-b-9scz9.c.openshift-gce-devel-ci.internal",32c32<
"__meta_kubernetes_pod_uid":
"2a57946d-e0c0-11e9-993b-0acb394f1cd6",--->
"__meta_kubernetes_pod_uid":
"88324571-e059-11e9-91d0-42010a000003",34,35c34,35<
"__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_signed_by":
"openshift-service-serving-signer@1569509594",<
"__meta_kubernetes_service_annotation_service_beta_openshift_io_serving_cert_signed_by":
"openshift-service-serving-signer@1569509594",--->
"__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_signed_by":
"openshift-service-serving-signer@1569499133",>
"__meta_kubernetes_service_annotation_service_beta_openshift_io_serving_cert_signed_by":
"openshift-service-serving-signer@1569499133",44,57c44,45<     "job":
"openshift-ingress/router-prometheus/0"<   },<   "labels": {<
"endpoint": "metrics",<     "instance": "10.128.2.15:1936",<
"job": "router-internal-prometheus",<     "namespace":
"openshift-ingress",<     "pod": "router-prometheus-b69fb8455-88tjx",<
    "service": "router-internal-prometheus"<   },<   "scrapeUrl":
"https://10.128.2.15:1936/metrics",<   "lastError": "",<
"lastScrape": "2019-09-27T00:52:47.170552639Z",<   "health": "up"--->
   "job": "openshift-ingress/router-default/0">   }

I'm still digging through prometheus source to understand more clearly how
the job label is constructed, and will re-open #23876
<https://github.com/openshift/origin/pull/23876> to collect data which will
more clearly show the input state to prometheus in the failure scenario.

cc @brancz <https://github.com/brancz>

/hold

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/23879?email_source=notifications&email_token=AAI37J2ONOXIC6KPMXE2VWLQL2NL7A5CNFSM4I3LXZW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72LMUI#issuecomment-536131153>,
or mute the thread

**Comment by brancz** [comment]
Prometheus is totally agnostic to the way people set the job label. The prometheus operator is what sets defaults for this. By default the job label defaults to some configurations in your service monitor, generally that means: `<service-monitor-namespace>/<service-monitor-name>/<position-of-endpoint-in-service-monitor>`. If you specify a `jobLabel` however, then if that label exists on your Service picked up through the ServiceMonitor then the value of that label will be your job label.

**Comment by ironcladlou** [comment]
I have evidence now that prometheus simply didn't scrape (or didn't report scraping) the target after 4 minutes. I still have other suspicious prometheus data I can't explain due to lack of additional dumps from openshift-ingress, but if they happen again I can look into it.

**Pull request closed without merging**
