### PR TITLE
add DOCKER_REGISTRY_SERVICE_HOST env var to AR install

### LINKED ISSUE #11670: atomic registry missing DOCKER_REGISTRY_SERVICE_HOST env var
https://github.com/openshift/origin/blob/master/examples/atomic-registry/systemd/install.sh#L71

Without this env var, docker push to registry gives errors like this (note the invalid value message):
```
Oct 31 12:47:46 registry.example.com atomic-registry[14455]: time="2016-10-31T16:47:46.452183896Z" level=error 
msg="error creating ImageStreamMapping: ImageStreamMapping \"test-for-echo\" is invalid: image.dockerImageReference: Invalid value: \":5001/thomasmckay/test-for-echo@sha256:bb6345201244ea4f80457b9df0d83d9fcb4c8fda1cf03ada48966c427f40bfc0\": invalid reference format" 
go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host="registry.example.com:5001" 
http.request.id=ab781300-c194-4fed-aaa9-5db01ae1db6f http.request.method=PUT http.request.remoteaddr="127.0.0.1:57222" 
http.request.uri="/v2/thomasmckay/test-for-echo/manifests/v1" 
http.request.useragent="docker/1.10.3 go/go1.6.3 git-commit/cb079f6-unsupported kernel/3.10.0-229.4.2.el7.x86_64 os/linux arch/amd64" i
nstance.id=9eccbea1-88e0-4d57-abcf-91d5fea669c4 vars.name="thomasmckay/test-for-echo" vars.reference=v1
```

### PR DESCRIPTION
**Pull request by aweiteka**
resolves #11670

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

@sdodson PTAL

**Comment by yangjunsss** [comment]
LGTM

**Comment by aweiteka** [comment]
This fix was added to the [upstream image](https://hub.docker.com/r/projectatomic/atomic-registry-install/) build.

@mfojtik please merge.

**Comment by mfojtik** [comment]
[merge]

**Comment by admiyo** [comment]
please recheck

**Pull request closed without merging**
