### PR TITLE
unit: increase timeout for getting master version

### LINKED ISSUE #17223: TestImagePruneErrOnBadReference flake
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17215/test_pull_request_origin_unit/5323/

```
github.com/openshift/origin/pkg/oc/admin/prune TestImagePruneErrOnBadReference 0.02s

images_test.go:142: pruner error: failed to build graph - no changes made
images_test.go:107: pruner error output: Failed to build graph!

The following objects have invalid references:

Pod[foo/pod1]: invalid docker image reference "invalid image reference": invalid reference format
BuildConfig[foo/bc1]: invalid ImageStreamImage reference "bar:invalid-digest": expected exactly one @ in the isimage name "bar:invalid-digest"
Deployment[foo/dep1]: invalid docker image reference "do not blame me": invalid reference format

Either fix the references or delete the objects to make the pruner proceed.

images_test.go:145: bump master version and try again
images_test.go:153: pruner error: failed to build graph - no changes made
images_test.go:107: pruner error output: Failed to build graph!
Failed to get master API version: error: server took too long to respond with version information.

The following objects have invalid references:

Pod[foo/pod1]: invalid docker image reference "invalid image reference": invalid reference format
BuildConfig[foo/bc1]: invalid ImageStreamImage reference "bar:invalid-digest": expected exactly one @ in the isimage name "bar:invalid-digest"
Deployment[foo/dep1]: invalid docker image reference "do not blame me": invalid reference format

Either fix the references or delete the objects to make the pruner proceed.

images_test.go:126: expected message "client version" is not contained in the output
```

### PR DESCRIPTION
**Pull request by miminar**
Resolves #17223

Signed-off-by: Michal Minář <miminar@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
@miminar was this still flaking?

**Comment by miminar** [comment]
> @miminar was this still flaking?

@bparees yes, according to #17223

**Pull request merged**
