### PR TITLE
SDN-4930: Don't modify pod routes in tests

### PR DESCRIPTION
**Pull request by kyrtapz**
port of https://github.com/ovn-org/ovn-kubernetes/pull/4809/commits/f02a9d141214e3f64157fbc7b9cca52572fcfa23
cc @trozet

### CODE REVIEW

**Comment by tssurya** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn

**Comment by trozet** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview

**Pull request merged**
