### PR TITLE
Improve provider selection page

### PR DESCRIPTION
**Pull request by liggitt**
@jwforres @spadgett PTAL

### CODE REVIEW

**Comment by liggitt** [comment]
before:
screen shot 2016-03-29 at 10 46 42 pm

after:
screen shot 2016-03-29 at 10 44 38 pm

also, this changes the background to be darker on hover, which makes the darker hover link more readable

**Comment by liggitt** [comment]
[test]

**Comment by spadgett** [comment]
Code changes LGTM, definitely an improvement.

Just a small note that Patternfly styles say to use square borders instead of rounded.

**Comment by liggitt** [comment]
squared border, [merge]

**Comment by liggitt** [comment]
flake on https://github.com/openshift/origin/issues/8303, re[test]

**Pull request merged**
