### PR TITLE
Bug 1892775: disabling cakephp until upstream problem addressed: bugzilla 1891989

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan

### CODE REVIEW

**Comment by gabemontero** [comment]
Ah @adambkaplan you are not in the 3.11 OWNERS file we need

lgtm it at least and then I'll assign someone else for approval (with Ben on PTO, I'll pick someone outside "devexp")

**Review by adambkaplan — APPROVED** [review]
/lgtm

Filed https://bugzilla.redhat.com/show_bug.cgi?id=1892845 to move these tests to NodeJS. This unblocks 3.11 PRs in the interim.

**Comment by frobware** [comment]
/assign @mfojtik

Please can you approve this PR as this is gating https://github.com/openshift/origin/pull/25542

**Comment by gabemontero** [comment]
/assign @bparees 

in case you see this before @mfojtik  .... and as a fyi @cuppett mentioned this to me off line ... in addition to his recently merged https://github.com/sclorg/cakephp-ex PR, 3.11 will need some additional bumps cause the older 7.1 versions of PHP just don't work no more essentially, even outside of OCP

To quote him:

```
3.11 with PHP 7.1 is dead.

On 3.11, they'll need to load the new image streams and then still need my merge.
```

So I believe that would entail adding php-72 after php-71 in https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_examples/files/examples/x86_64/image-streams/image-streams-rhel7.json#L843-L861

But let's have the 3 of us discuss either here on on slack next week

**Comment by frobware** [comment]
Created https://bugzilla.redhat.com/show_bug.cgi?id=1893657 to cover the persist CI failure: 

```
[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 
```

**Comment by gabemontero** [comment]
The build pruning test is also cakephp related:

```
2020-11-02T12:54:42.225219368Z   - Installing cakephp/plugin-installer (1.3.0): Extracting archive
2020-11-02T12:54:42.262160808Z 
2020-11-02T12:54:42.262196006Z Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /opt/app-root/src/vendor/cakephp/plugin-installer/src/Plugin.php on line 157
2020-11-02T12:54:42.262203906Z PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /opt/app-root/src/vendor/cakephp/plugin-installer/src/Plugin.php on line 157
2020-11-02T12:54:42.700447701Z error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/php@sha256:e8b78ce0bc74a96bef4676126522717f3612e715d18888b1c8c9dbbfb9fa89c8
```

curious that we go green tests at all last week ... perhaps another upstream change (i.e. in PHP proper, not scl) has impacted us.

will handle in this PR

closing the new https://bugzilla.redhat.com/show_bug.cgi?id=1893657 as a dupe

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
the extended_builds failure looks to be a true flake, a timeout trying to pull the nodejs image from the image registry:

```
pulling image error : error pulling image configuration: Get https://docker-registry.default.svc:5000/v2/openshift/nodejs/blobs/sha256:0e060abe07af3e3a4a8829379a287db2c7ec758baca213758312772d001c23a2: dial tcp 172.30.226.132:5000: i/o timeout
error: build error: unable to get docker-registry.default.svc:5000/openshift/nodejs@sha256:3dfd54c57b791d0b8fc4b4670144920e7ad0c1b0bd7a501375af8421d19df90c
```

it is retrying now

**Pull request merged**
