### PR TITLE
test: Fix a few remaining issues from the test renaming

### PR DESCRIPTION
**Pull request by smarterclayton**
Fix excludes on sig-scalability and sig-cluster-lifecycle. Remove
use of [Conformance] in openshift tests. Rename [local] to [Local].

### CODE REVIEW

**Comment by bparees** [comment]
this is gonna merge conflict with https://github.com/openshift/origin/pull/24687

can you cherrypick my changes into this PR?

**Comment by smarterclayton** [comment]
```
[sig-imageregistry][Feature:ImageTriggers][Serial] ImageStream API [Top Level] [sig-imageregistry][Feature:ImageTriggers][Serial] ImageStream API TestImageStreamMappingCreate [Suite:openshift/conformance/serial] expand_less	4s
fail [github.com/openshift/origin/test/extended/images/imagestream.go:85]: Unexpected error:
    <*errors.StatusError | 0xc00214a280>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "images.image.openshift.io \"image2\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "image2",
                Group: "image.openshift.io",
                Kind: "images",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    images.image.openshift.io "image2" already exists
```

Looks broken, may have been taken off the skip list by my recent changes (but not in this PR)

**Comment by bparees** [comment]
as 3/10 the job was only running 35 tests:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24574/pull-ci-openshift-origin-master-e2e-aws-image-registry/1089

and that wasn't one of them.

Now it's running 57:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24692/pull-ci-openshift-origin-master-e2e-aws-image-registry/1112

so yeah, something about the recent change affected what's being picked up.

But we should also check with @dmage about why so many tests are disabled...  I suspect it's integration tests that we haven't gotten re-enabled yet after the conversion to e2e, but we should confirm they're being tracked for re-enablement.

**Comment by smarterclayton** [comment]
Most of the new tests are things like the image cli tests.  They belong to sig-image registry, but they are run in the CLI suite.  We may just want to make the image registry suite be based on a set of "[Feature:Image...]" tags rather than on [sig-image-registry].

**Comment by smarterclayton** [comment]
The test is wrong, it assumes no retries or other executions.  I need to fix it.

**Comment by smarterclayton** [comment]
I pushed a fix, hopefully should clear it.  Whichever of us wins will have to rebase.

**Comment by bparees** [comment]
> I pushed a fix, hopefully should clear it. Whichever of us wins will have to rebase.

loses.

**Pull request merged**
