### PR TITLE
web console: defensive blocks in valuesIn and valuesNotIn filters

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Originally in [this PR](https://github.com/jwforres/origin/pull/44/files) from @spadgett, will affect @rhamilto's work on the osc-key-values directive for env vars.
@jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
LGTM, but missing bindata

**Comment by benjaminapetersen** [comment]
ah, habit, will add the bindata

**Comment by benjaminapetersen** [comment]
ok bindata :)

[TEST]

**Comment by spadgett** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Hmm. webdriver server error (timeout)

**Comment by jhadvig** [comment]
:+1: :)

**Pull request merged**
