### PR TITLE
Bug 1794885: UPSTREAM: <carry>: bootstrap user - make tokens have implicit audiences

### PR DESCRIPTION
**Pull request by stlaz**
cc @sttts @marun

### CODE REVIEW

**Comment by marun** [comment]
@stlaz @sttts Why does this code need to be duplicated from https://github.com/openshift/origin/pull/24461 ? Seems like an opportunity to factor out the common code to avoid this class of error in the future.

**Comment by sttts** [comment]
It's actually copied from upstream (service account authn). If we want to factor it out, then in upstream.

**Comment by marun** [comment]
> It's actually copied from upstream (service account authn). If we want to factor it out, then in upstream.

In an ideal world, yes, the openshift patches for tokenauthenticator and bootstrapauthenticator would derive from better-factored upstream code. I'm not sure why it would be necessary to wait for that, though, to remove the potential source of errors represented by tokenauthenticator and bootstrapauthenticator being independently implemented given that their functionality is largely common.

**Comment by stlaz** [comment]
/retest
looks like KAS couldn't reach etcd in the upgrade job, not good

**Pull request merged**
