### PR TITLE
stop calling junit merge.

### PR DESCRIPTION
**Pull request by bparees**
since https://github.com/jenkinsci/junit-plugin/pull/54 was merged,
it should not be needed anymore.

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov ptal

**Comment by jim-minter** [comment]
lgtm but leaving it to @stevekuznetsov

**Comment by smarterclayton** [comment]
It's required for other tools.

**Comment by bparees** [comment]
> It's required for other tools.

are you saying  we need to leave the junitmerge tool here, or are you saying we can't stop calling junit merge at all?

**Comment by smarterclayton** [comment]
I'm still investigating whether we need it for gubernator, so it's not
appropriate to remove it yet.

**Comment by stevekuznetsov** [comment]
I confirmed we're fine for Gubernator -- it expects many jUnit files

**Comment by bparees** [comment]
I need a decision on whether this PR can move forward, it's screwing up our extended test runs.

**Comment by stevekuznetsov** [comment]
In my opinion it should be good

**Comment by bparees** [comment]
@stevekuznetsov @smarterclayton bump.

**Comment by stevekuznetsov** [comment]
So we do NOT need this for Gubernator ... @smarterclayton any objections?

**Comment by bparees** [comment]
(i heard no objections).

**Pull request merged**
