### PR TITLE
WIP: Remove jenkins from payload

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by yselkowitz** [comment]
@akram you need to run `make update` and add the resulting diff to this PR.

**Comment by yselkowitz** [comment]
Also, before the make update, is there any testdata which is used exclusively by these tests that can also be removed?

**Review by adambkaplan — COMMENTED** [review]
/hold

This should be retitled, as "removing from payload" is misleading. We won't remove Jenkins from the payload until we get Jenkins out of the ART pipeline and into its own CPaaS build pipeline.

This removes Jenkins from origin tests and examples. This PR should be held until equivalent tests are set up in the openshift/jenkins repo.

**Pull request closed without merging**
