### PR TITLE
Bug 1758159: aws: sort addresses of multiple interfaces correctly [4.1]

### PR DESCRIPTION
**Pull request by danwinship**
Backport of #23870 to 4.1

### CODE REVIEW

**Comment by eparis** [comment]
this needs review/lgtm/approval

**Comment by danwinship** [comment]
/assign @p0lyn0mial @mfojtik 
who reviewed the PR on master (#23870 )

**Comment by ashcrow** [comment]
Waiting for QE review.

**Comment by danwinship** [comment]
/hold
4.1 CI is apparently busted

**Comment by ashcrow** [comment]
Removing `cherry-pick-approved` for now. The next patch manager should re-review.

**Pull request merged**
