### PR TITLE
Tag and run qualified image names for gssapi tests

### LINKED ISSUE #17481: GSSAPI test failure due to run command error: watch closed before Until timeout
This is possibly related to https://github.com/kubernetes/kubernetes/pull/50102

From https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_gssapi/272/

```
Some command failed in a script: test/extended/gssapi.sh:109: `oc run "${image_name}" --image="${project_name}/${image_name}" --generator=run-pod/v1 --restart=Never --attach --env=SERVER="${server_config}" > "${pod_log_location}" 2>> "${junit_gssapi_output}"` exited with status 1.
```

The `oc run` command failed due to:

```
error: watch closed before Until timeout
```

@openshift/sig-master @openshift/sig-security @openshift/cli-review

### PR DESCRIPTION
**Pull request by liggitt**
caused by mismatch in local docker builds and fully-qualified pull expectations

fixes #17481

### CODE REVIEW

**Comment by enj** [comment]
@liggitt nice!  I should have looked at registry logs before assuming it was a watch error.

**Comment by enj** [comment]
@liggitt looks like GSSAPI is broken differently...

**Comment by liggitt** [comment]
looks like the  openshift/origin-docker-registry isn't getting built for this job... opening https://github.com/openshift/aos-cd-jobs/pull/942 to try to fix that

**Pull request merged**
