### PR TITLE
Use p12-encoded certs on OS X

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton review, weep, and try on your machine

**Comment by liggitt** [comment]
resolves #1011

**Comment by liggitt** [comment]
hmm... not quite right... the files may not exist when we get into the wait_for_url loop, and we have to wait until they do to convert them to p12

**Comment by liggitt** [comment]
awesome, wait_for_file... just what I wanted to add

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
