### PR TITLE
expose project creation failures

### PR DESCRIPTION
**Pull request by deads2k**
Necessary, but not sufficient for https://github.com/openshift/origin/issues/4473.

I suspect that project creation failed (possibly due to weird etcd problems), but the project create failure was suppressed.  This exposes it so we'll be able to see what's broken next time.

@liggitt  or @sosiouxme

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm, [merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by deads2k** [comment]
Note for me to look at friday: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3208/

```
You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

!!! Error in hack/test-cmd.sh:223
  '[ "$(oc login --token=${temp_token} 2>&1 | grep 'using the token provided')" ]' exited with status 1
Call stack:
  1: hack/test-cmd.sh:223 main(...)
Exiting with status 1
```

**Comment by deads2k** [comment]
@smarterclayton How do you feel about killing the server and restarting between test-cmd scripts to see if it increases stability?

**Comment by smarterclayton** [comment]
Yuck.  Why do we suddenly have test cmd stability problems?  Racing against
controllers is only reason?

On Sep 2, 2015, at 7:11 PM, David Eads <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> How do you feel about
killing the server and restarting between test-cmd scripts to see if it
increases stability?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4475#issuecomment-137270663>.

**Pull request merged**
