### PR TITLE
Copy ImageRepository annotations to image

### PR DESCRIPTION
**Pull request by ncdc**
When an Image is added to an ImageRepository via ImageRepositoryMapping,
copy all annotations from the ImageRepository of the form <tag>.<...> to
the Image.

### CODE REVIEW

**Comment by ncdc** [comment]
@jwforres @smarterclayton @jcantrill PTAL

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
Also @bparees

**Comment by bparees** [comment]
lgtm.

**Comment by mfojtik** [comment]
LGTM

**Comment by ncdc** [comment]
@smarterclayton merge?

**Comment by smarterclayton** [comment]
y'all got the powa [merge]

**Pull request merged**
