### PR TITLE
Revising sidebar to better align with PatternFly standard

### PR DESCRIPTION
**Pull request by rhamilto**
@spadgett, review and merge, please?  cc: @sg00dwin, @jwforres, @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
I like the dropdown bg color change & softer break. Looks good.

screen shot 2016-02-05 at 3 36 54 pm

**Comment by rhamilto** [comment]
Screenshot is a great addition, @benjaminapetersen.  Thanks!  

However, that vertical line yours is rendering a bit differently than mine (see attachment)
screen shot 2016-02-05 at 3 49 56 pm

**Comment by spadgett** [comment]
I like it better. My only hesitation is now the project dropdown and the sidebar have different hover effect when they used to be the same.

@jwforres opinions?

**Comment by rhamilto** [comment]
Oh.  That's a bug!  Hold, please.

**Comment by spadgett** [comment]
@rhamilto Mine looks like as @benjaminapetersen (in chrome at least)

**Comment by benjaminapetersen** [comment]
While we are discussing it... does anyone else ever click the sidebar & close the menu?  For some reason my instinct is to click browse even though it is hover activated.  :grimacing:

**Comment by rhamilto** [comment]
Ok.  The bug is fixed. Since there are different colors for hover and active, the filler strip we're putting in to bridge the gap between the sidebar and the dropdown needed to change based on whether or not the item is active.

screen shot 2016-02-06 at 10 12 03 am
screen shot 2016-02-06 at 10 11 56 am

I agree about the behavior, @benjaminapetersen.  And PatternFly's recommendation will be on click (spoiler alert!).  What do the rest of you think?

**Comment by spadgett** [comment]
I prefer click to hover, but it would be a change in behavior. @jwforres?

**Comment by spadgett** [comment]
I like the new menu style, except I don't like the hover effect as well. Is the underline in place of a background color change part of the Patternfly standard?

**Comment by rhamilto** [comment]
> I like the new menu style, except I don't like the hover effect as well. Is the underline in place of a background color change part of the Patternfly standard?

It is, @spadgett.  I think it's safe to deviate from it if we come up with an option we think is better...

screen shot 2016-02-08 at 9 19 35 am

**Comment by jwforres** [comment]
are you proposing only click to open?  i like having it open on hover, but i think we should fix the behavior that if the hover has already opened it that the click closes it, ideally "click" should only close if a click opened it (for keyboard use).

**Comment by rhamilto** [comment]
After discussion with @jwforres and @spadgett, we're going to leave the behavior alone for this PR and revert the tertiary hover style back to what it was.  I will add a second PR to address the behavior.

**Comment by rhamilto** [comment]
Ok.  Let's give this a go, @spadgett, @jwforres, @benjaminapetersen, @sg00dwin.  This combines PatternFly's approach for active state (minus the blue highlight along the left edge) but maintains the old hover state .  Thoughts?

screen-shot-2016-02-08-at-4 37 25-pm
screen-shot-2016-02-08-at-4 37 36-pm

**Comment by benjaminapetersen** [comment]
I'm good with the way it looks.  Curious if you have it on a delay before closes?

**Comment by rhamilto** [comment]
@benjaminapetersen, there should be no change to the behavior of the menu (in other words, I didn't add a delay).

**Comment by sg00dwin** [comment]
I think the hover and active bg color states look good. 
Since the browse tab doesn't actually link, seems it should be set to cursor:default. And as Jessica mentioned, have the hover nav not close if browse is clicked.

**Comment by jwforres** [comment]
yeah definitely prefer this hover state

**Comment by rhamilto** [comment]
Closing in favor of #7152

**Pull request closed without merging**
