### PR TITLE
generate more image clients and fix users clientset

### PR DESCRIPTION
**Pull request by mfojtik**
Add clients for ImageStreamImage, ImageSignatures and ImageStreamMappings.
Fixes Users() to be non-namespaced.

### CODE REVIEW

**Comment by mfojtik** [comment]
FYI @deads2k forgot to regenerate listers and informers...

**Comment by mfojtik** [comment]
@deads2k removing lgtm as something is broken in the generator... seems like we generate informers for resources we should not generate informers (those who does not have .List())... I need to look closer on the generator pieces, but I guess this is also broken upstream (luckily we don't use onlyVerbs in upstream yet).

**Comment by mfojtik** [comment]
@deads2k or @soltysh ship me pls :)

**Comment by deads2k** [comment]
@mfojtik I did once here: https://github.com/openshift/origin/pull/15625#issuecomment-319970934  Feel free to re-apply if you're not changing anything significant

/lgtm

**Comment by mfojtik** [comment]
@deads2k no, just rebased

**Pull request merged**
