### PR TITLE
pkg/cmd/server/api/validation/master.go: fix typo in warning message

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @soltysh @mfojtik

### CODE REVIEW

**Comment by imcsk8** [comment]
LGTM

**Comment by mfojtik** [comment]
LGTM [merge][severity:bug]

**Comment by php-coder** [comment]
test flake #14485

**Comment by mfojtik** [comment]
[merge]

**Comment by php-coder** [comment]
> continuous-integration/openshift-jenkins/merge Running (https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/905/) (Base Commit: 943154e) (Extended Tests: bug)

^^^ @stevekuznetsov this looks like a bug: it tries to run `Extended Tests: bug` for the comment `[merge][severity:bug]`.

**Comment by php-coder** [comment]
test flake #14489

**Comment by stevekuznetsov** [comment]
@php-coder we are piggy-backing off of the extended test configuration to run the merge severity stuff, so it's just a "typo" -- nothing is wrong underneath. Thanks for pointing it out, though.

**Pull request merged**
