### PR TITLE
Add test for validating related object references.

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold 

Need https://github.com/openshift/cluster-ingress-operator/pull/725 to merge before this can go in.

**Comment by dgoodwin** [comment]
Correction holding on https://github.com/openshift/cluster-ingress-operator/pull/721

**Comment by deads2k** [comment]
once this merges, an effort to reduce the items in `whitelistNoOperatorConfig` would be good.

**Comment by dgoodwin** [comment]
Something new showing up: 

```
{  fail [github.com/openshift/origin/test/extended/operators/clusteroperators.go:109]: Unexpected error:
    <*meta.NoResourceMatchError | 0xc001f97350>: {
        PartialResource: {
            Group: "sharedresource.openshift.io",
            Version: "",
            Resource: "sharedconfigmaps",
        },
    }
    no matches for sharedresource.openshift.io/, Resource=sharedconfigmaps
occurred}
```

**Comment by dgoodwin** [comment]
Spoke with storage team, known issue as this resource only is created if TechPreviewNoUpgrade is enabled. Bug filed: https://bugzilla.redhat.com/show_bug.cgi?id=2069653, for now we'll skip this specific resource in the test so we can land it.

**Comment by dgoodwin** [comment]
Looks like test is now passing.

**Pull request merged**
