### PR TITLE
Bump Cobra with suggestions on 'unknown command' errors

### PR DESCRIPTION
**Pull request by fabianofranz**
The latest version of Cobra [adds suggestions](https://github.com/spf13/cobra/pull/149) when "unknown command" errors happen, like

```
$ oc volumes
Error: unknown command "volumes" for "oc"

Did you mean this?
    volume

Run 'oc --help' for usage.
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@smarterclayton @liggitt automatic suggestions in 'unknown command' errors was accepted in Cobra, bumping to support that.

**Comment by kargakis** [comment]
@fabianofranz do you need the last [commit](https://github.com/spf13/pflag/commit/574bc4cfb94effb3e1bb934f1512c1f1a558000f) in pflag? If not, can you please bump until the previous commit (https://github.com/spf13/pflag/commit/8e7dc108ab3a1ab6ce6d922bbaff5657b88e8e49)? Kubernetes have  bumped their [pflag dep](https://github.com/kubernetes/kubernetes/blob/c9570e34d03c6700d83f796c0125d17c5064e57d/Godeps/Godeps.json#L519) until that commit and it would be convenient to be on par (also convenient for my rebase:) )

**Comment by fabianofranz** [comment]
@kargakis I don't think I need it, let me rebase.

**Comment by kargakis** [comment]
@fabianofranz thanks!

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
