### PR TITLE
Bug 1325069 - Sort status tags according to semver

### PR DESCRIPTION
**Pull request by soltysh**
Fixes [bug1325069](https://bugzilla.redhat.com/show_bug.cgi?id=1325069)
@smarterclayton ptal

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by soltysh** [comment]
@smarterclayton bump

**Comment by mfojtik** [comment]
[merge]

**Comment by soltysh** [comment]
Flake #10107.

re-[merge]

**Comment by soltysh** [comment]
Flakes https://github.com/openshift/origin/issues/9548 and #9775

re-[merge]

**Comment by soltysh** [comment]
#9775 again... 

re-[merge]

**Comment by soltysh** [comment]
#9775 again and vagrant failure

re-[merge]

**Comment by soltysh** [comment]
Rebased, maybe that should help bypassing the flake.

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by soltysh** [comment]
#9775 again...

re-[merge]

**Pull request merged**
