### PR TITLE
Bug 1726326 - Temporarily skip Jenkins template tests

### PR DESCRIPTION
**Pull request by adambkaplan**
Temporary until underlying issue with Jenkins is addressed.

/assign @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
this unsticks multiple PRs

/lgtm

**Comment by adambkaplan** [comment]
odd...ephemeral test was not skipped :slightly_frowning_face:

**Comment by jsafrane** [comment]
@adambkaplan, IMO you want to skip test in pipeline_origin_bld.go:

https://github.com/openshift/origin/blob/f1d0a259b1bff4d8da6820ffebed9e4a426bd26a/test/extended/builds/pipeline_origin_bld.go#L211-L213

(and not pipeline_jenkins_e2e.go)

**Comment by adambkaplan** [comment]
/hold

Not skipping...

**Pull request merged**
