### PR TITLE
Fix vagrant single vm environment

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by pmorie** [comment]
@smarterclayton @bparees @ironcladlou ptal

**Comment by bparees** [comment]
@mfojtik fyi.

**Comment by mfojtik** [comment]
@pmorie #742 too late Paul :-(

**Comment by pmorie** [comment]
@mfojtik What does this say about the two of us, find the same problem and solve it in the opposite ways

**Comment by pweil-** [comment]
@pmorie more importantly, what does it say that the Pauls fixed it in the same way but @mfojtik still beat us to the punch?  https://github.com/openshift/origin/pull/743/files

**Comment by smarterclayton** [comment]
Merging this change because I buy Paul's comment

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
