### PR TITLE
Enable the gcs, oss, and inmemory storage drivers in registry

### PR DESCRIPTION
**Pull request by smarterclayton**
Also enable the proxy code.

@liggitt @pweil- review please

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
well... the underscore is wafer-thin...

**Comment by pweil-** [comment]
LGTM

/cc @miminar 

> well... the underscore is wafer-thin...

never satisfied

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
