### PR TITLE
bump(github.com/openshift/source-to-image): ec23cd36484d1c32d3cfdbbc1…

### LINKED ISSUE #9645: logging data race
```
WARNING: DATA RACE
Read by goroutine 9:
  bufio.(*Writer).WriteString()
      /usr/lib/golang/src/bufio/bufio.go:660 +0x83
  github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).writeln()
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:120 +0x2ac
  github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).outputf()
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:129 +0x91
  github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).Errorf()
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:158 +0x68
  github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging.func1()
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:228 +0x9a4
  path/filepath.walk()
      /usr/lib/golang/src/path/filepath/path.go:349 +0xa3
  path/filepath.walk()
      /usr/lib/golang/src/path/filepath/path.go:374 +0x619
  path/filepath.Walk()
      /usr/lib/golang/src/path/filepath/path.go:396 +0x106
  github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStreamWithLogging()
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go:237 +0x404
  github.com/openshift/source-to-image/pkg/tar.(*stiTar).CreateTarStream()
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2669/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2669/artifact/origin/artifacts/test-go/logs/test-go.log

Need to fix the race in s2i and bump the fix to origin.

### PR DESCRIPTION
**Pull request by jupierce**
…60d30d06bac9db4

fixes #9645

### CODE REVIEW

**Comment by jupierce** [comment]
[testextended][extended:core(builds)]

**Comment by jupierce** [comment]
@bparees

**Comment by jupierce** [comment]
[testextended][extended:core(images)]

**Comment by jupierce** [comment]
[test]

**Comment by bparees** [comment]
one known issue
[merge]

**Pull request merged**
