### PR TITLE
UPSTREAM: <carry>: StatefulSets require privileged for host access

### LINKED ISSUE #12500: Dynamic PV's not being attached to nodes on GCE
I'm seeing following StatefulSet extended failures (usually due to timeouts) both in master and my rebase PR (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/984/consoleFull).

```
[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should allow template updates 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923

[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should provide basic identity 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923

[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should handle healthy pet restarts during scale 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923
```

@smarterclayton fyi

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #12500

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Testing in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/202/

**Comment by soltysh** [comment]
You are aware that setting that privileged isn't sufficient. Besides that's already handled in [here](https://github.com/openshift/origin/blob/d7763282cf9ac0cf056c506e91e97c8b8a9a4f29/test/extended/util/test.go#L177). The 2nd part of the commit of mine actually turns options responsible for allowing to actually create hostMounts, that's [here](https://github.com/openshift/origin/blob/d7763282cf9ac0cf056c506e91e97c8b8a9a4f29/test/extended/setup.sh#L143), in turn. Scroll to `enable-hostpath-provisioner` option. I don't see your PR adding something new here, unless the e2e tests on GCE are run differently. I'd rather address this at our test level.

**Comment by smarterclayton** [comment]
We don't want host path provisioner on a real cluster.

**Comment by smarterclayton** [comment]
That allows privileged, it does not actually set it.

**Pull request closed without merging**
