### PR TITLE
Cherry pick into 1.5 of "Stop generating manuals by default"

### PR DESCRIPTION
**Pull request by kargakis**
@stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
LGTM on green [tests]

**Comment by kargakis** [comment]
Seems like this has picked a command that is currently merging in the release-1.5 branch. Probably an artifact from me switching this from master.. Will need a rebase once https://github.com/openshift/origin/pull/13045 merges.

**Comment by stevekuznetsov** [comment]
@kargakis can you explain more? What has happened? Is it a CI thing you think?

**Comment by kargakis** [comment]
> @kargakis can you explain more? What has happened? Is it a CI thing you think?

Not at all a CI thing. Just me fighting with git. I had to pick three out of four commits and regenerate the fourth on top of the release-1.5 branch. The master branch has the extra command docs/mans that were missing from release-1.5 so during checkout I moved those in this PR too.

**Comment by kargakis** [comment]
> Not at all a CI thing. Just me fighting with git. I had to pick three out of four commits and regenerate the fourth on top of the release-1.5 branch. The master branch has the extra command docs/mans that were missing from release-1.5 so during checkout I moved those in this PR too.

Of course, I knew the job would fail and aborted it. But it can rerun now [test]

**Comment by kargakis** [comment]
aws failure [merge]

**Pull request merged**
