### PR TITLE
Enable oss storage driver

### LINKED ISSUE #11995: Aliyun oss storage driver for Docker registry
It looks like https://github.com/openshift/origin/pull/8692 added support for the [Docker registry oss storage driver](https://docs.docker.com/registry/storage-drivers/oss/), however, this was removed by [this PR](https://github.com/openshift/origin/commit/ad2e16428e0930d1fb36a7dd311b697457b45847#diff-50cb1f18216798dfbbed586e322c3edfL35
). The OpenShift [docs](https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-storage) don't mention support for oss; I was just wondering if there's a way to add support for it? We have an account if that helps with initial testing.

Adding an oss storage section in the registry config yaml results in the following errors (expected given that it's not supported):
```
panic: StorageDriver not registered: oss

goroutine 1 [running]:
panic(0x1b54a20, 0xc8204967d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x7f71c419dac8, 0x2c02f00, 0xc820325080, 0x7f71c419dac8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/handlers/app.go:121 +0x619
github.com/openshift/origin/pkg/cmd/dockerregistry.Execute(0x7f71c4189270, 0xc8202d6380)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/dockerregistry/dockerregistry.go:60 +0x4e4
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/dockerregistry/main.go:51 +0x47d
```

##### Version
```
# oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dashboard.abarcloud.internal:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4
```

### PR DESCRIPTION
**Pull request by legionus**
Fix #11995 

@mfojtik @pweil-  please review

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@legionus we will have to  make a second PR for 1.4 branch IMHO

**Comment by legionus** [comment]
@mfojtik Let's merge this PR first.

**Comment by mfojtik** [comment]
@legionus I think you have change the commit message and split this to changing vendored dir commit and second that change the origin file. (to pass the commit checker)

**Comment by legionus** [comment]
[test]

**Comment by pweil-** [comment]
re[test]

**Comment by mfojtik** [comment]
@legionus 
```
vendor/github.com/docker/distribution/registry/storage/driver/oss/oss.go:28:2: cannot find package "github.com/denverdino/aliyungo/oss" in any of:
```

**Comment by legionus** [comment]
@mfojtik Damn. That's what happens when trying to do two PRs in same time.

**Comment by mfojtik** [comment]
@legionus are you working on this or should I go try to resolve the godep?

**Comment by legionus** [comment]
@mfojtik I've fixed it already.

**Comment by mfojtik** [comment]
thx. lets make the test pass and open 1.4 branch pr

**Comment by legionus** [comment]
[test]

**Comment by soltysh** [comment]
@ncdc heads up for Godeps changes

**Comment by soltysh** [comment]
LGTM, including godep change

**Comment by mfojtik** [comment]
[merge]

flake: https://github.com/openshift/origin/issues/12072

**Comment by pweil-** [comment]
@legionus @mfojtik do you have 1.4 branch patch for this?

**Comment by soltysh** [comment]
Flake #11004
[merge]

**Comment by soltysh** [comment]
Flake: https://github.com/openshift/origin/issues/10988, https://github.com/openshift/origin/issues/11016

re-[merge]

**Comment by mfojtik** [comment]
yum repo flake [merge]

**Pull request merged**
