### PR TITLE
namespace scope all our new admission plugins

### PR DESCRIPTION
**Pull request by deads2k**
We need to namespace our admission plugins.  We almost ended up with our ImagePolicy and upstream ImagePolicy.  I chose `openshift.io/Name` to ensure that it never parsed as a GroupResource or GroupKind (the two most likely to be confused).  It does parse as a `GroupVersion`, so we could consider other delimiters, but we must do something.

@openshift/api-review

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

I could write an inspection test to watch these, but it would require the rebaser to keep the list up to date.  I guess I'll do that, because the rebase is already so painful, what's a few more.

**Comment by liggitt** [comment]
should we double register all of our existing plugins with namespaced forms and switch our defaults to using the namespaced names?

**Comment by deads2k** [comment]
> should we double register all of our existing plugins with namespaced forms and switch our defaults to using the namespaced names?

Yeah... So you know I thought of that I decided that was so ugly it made me want to go home, right?

**Comment by smarterclayton** [comment]
You're right, that **is** ugly.

**Comment by deads2k** [comment]
api agreed on in IRC.

[merge]

**Comment by deads2k** [comment]
> should we double register all of our existing plugins with namespaced forms and switch our defaults to using the namespaced names?

Admission plugins are side-effecty.  You can't simply double everything in the list (think quota) and you can't simply cut over because of existing config.  We could write some sort of fallback logic, but that's more than I want to do in 1.3.

**Comment by liggitt** [comment]
> You can't simply double everything in the list

I meant double register, not double activate

**Comment by deads2k** [comment]
> I meant double register, not double activate

Yeah, see the rest of the comment.  I don't want to do the fallback logic in the chain for 1.3.

**Pull request merged**
