### PR TITLE
Removing the transition on .sidebar-left for cleaner rendering on resize

### PR DESCRIPTION
**Pull request by rhamilto**
@spadgett, review and merge, please?  cc: @sg00dwin

### CODE REVIEW

**Comment by jwforres** [comment]
@rhamilto you need to run hack/build-assets.sh

also if you get a diff for /java/bindata.go ignore that one its acting wonky this week with diffs, just check in regular bindata.go

**Comment by spadgett** [comment]
Is this like #6971 where we have two different animations to the same element?

**Comment by sg00dwin** [comment]
@spadgett this transition should have been removed with the other in #6971

**Comment by spadgett** [comment]
LGTM

@rhamilto check in bindata.go after you run hack/build-assets.sh, thanks!

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
