### PR TITLE
RFC: refactor persistent storage example and add Cinder documentation

### PR DESCRIPTION
**Pull request by jsafrane**
These two patches modify the Wordpress example to include documentation of Cinder persistent volumes. Additional storage plugins can be added easily later. Is this something that you would be interested in? Is the structure fine?

~~Cinder support is heading to upstream Kubernetes in [PR #6689] https://github.com/kubernetes/kubernetes/pull/6689/).~~ Kubernetes changes have been merged in openshift/origin commit 2009660eb84e1a56df68db8e1077e2b0bd136d3f

### CODE REVIEW

**Comment by markturansky** [comment]
At first glance, this looks like a great addition to the wordpress example that shows how to change out the PV part in the backend.  I'll take a more careful/thorough look later.

**Comment by jsafrane** [comment]
Note that I had to disable SELinux to make it working - newly created ext3 filesystems are not labelled (system_u:object_r:unlabeled_t) and SELinux denies containers (svirt_lxc_net_t) to write to them. This is not Cinder related, it provides block device, not the filesystem. All other block-device-like volumes (iSCSI, RBD, ...) will have the same problem. Is the user supposed to label the filesystems inside the volumes?

**Comment by danmcp** [comment]
@markturansky @childsb Review please.

**Comment by childsb** [comment]
LGTM

**Comment by jsafrane** [comment]
Rebased. Also, Kubernetes PR for OpenStack/Cinder was merged and it will land in OpenShift with next Kubernetes rebase.

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
