### PR TITLE
Run HPA e2e tests

### PR DESCRIPTION
**Pull request by DirectXMan12**
This runs the "fast" ("ReplicationController light") HPA tests.
The rest would be nice to have, since they test other resources,
but they take forever to complete (20 minutes+).

As part of this, we now launch metrics-server in the extended tests.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Depends on #19115 merging first (it's in merge queue right now).

@deads2k as promised :-)

**Comment by DirectXMan12** [comment]
/retest

I don't think those failures are my fault, but let's see.

**Comment by deads2k** [comment]
hpa tests appear to be failing in e2e.

**Comment by DirectXMan12** [comment]
hmm... both of those ran fine locally with `test/extended/core.sh` with the appropriate focus.  Let me see if I can figure out what's going on.

**Comment by DirectXMan12** [comment]
actually @deads2k @stevekuznetsov how are the clusters that the e2e tests are run against set up?  I don't see any of the log lines in the build log from test/extended/setup.sh...

If it's being set up a different way, and metrics-server isn't being installed, then the tests are going to fail 100% of the time.

**Pull request closed without merging**
