### PR TITLE
Support create-master-config option by oadm

### PR DESCRIPTION
**Pull request by nak3**
Refer to https://github.com/openshift/origin/issues/4733

### CODE REVIEW

**Comment by liggitt** [comment]
not sure how I feel about this... feels like an additional command to keep in sync without a lot of benefit

cc @deads2k

**Comment by nak3** [comment]
Actually, I didn't like to move the codes for sync. However, if oadm will support `--create-master-config`, it is the best way, I think.
And I hope oadm has `create-master-config` option for manual installation and to scale up master.

**Comment by danmcp** [comment]
@nak3 Needs rebase

@deads2k Bump.

**Comment by danmcp** [comment]
@nak3 Needs rebase

@deads2k Bump

**Comment by deads2k** [comment]
> @deads2k Bump

I don't feel strongly about having this and @liggitt isn't really for it.  Even if he's willing to have it, the pull still needs refactoring to use a command delegation implementation to avoid having to repeat ourselves for the flag bindings.

**Comment by nak3** [comment]
OK, I understand. Please feel to close this PR.
(But before closing this PR, if you have any idea to create `master-config.yaml manually`, please let me know. There is no way except for starting standalone or stealing from ansible-installer?)

**Comment by liggitt** [comment]
Pass the `--write-config` option to `openshift start` to create a config file. All passed command-line options are used to build the resulting config directory.

For example:
```
openshift start master --public-master=https://mydomain.com:8443 --write-config=<output-dir>
```

**Comment by nak3** [comment]
OK, thank you for your explanation @liggitt 
I will write KCS

**Pull request closed without merging**
