### PR TITLE
Bug 1846428: UPSTREAM: 90419: Update strategy used to reuse CPUs from init containers in CPUManager

### PR DESCRIPTION
**Pull request by cynepco3hahue**
ref: kubernetes/kubernetes#90419

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@vpickard Can you please provide the relevant Bugzilla?

**Comment by rphillips** [comment]
I'm a bit confused. This PR does not patch the 90419 upstream PR here: https://github.com/kubernetes/kubernetes/pull/90419/files

Do we need additional patches from upstream for this functionality?

**Comment by cynepco3hahue** [comment]
@sjenning @rphillips The PR is ready for review, can you please take a look?

**Comment by cynepco3hahue** [comment]
The fix will be available for free after the rebase on top of 1.19.

**Pull request closed without merging**
