### PR TITLE
re-enable jenkins autoprovisioning

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton do we really want to do this before oauth is enabled?  it means we need to update a bunch of doc(this tutorial, official docs) telling people how to find out their jenkins password when the jenkins server gets provisioned for them.

@gabemontero

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
I guess not - since we're getting close to oauth and routes.

**Comment by bparees** [comment]
I will hold this until the oauth stuff goes in and then revisit this PR.

**Comment by bparees** [comment]
oauth has landed in the jenkins centos image and should be in the rhel image we publish for 3.4.
[merge]

**Comment by bparees** [comment]
swagger regen'd
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11114
[merge]

**Comment by smarterclayton** [comment]
Update swagger

On Oct 22, 2016, at 12:45 AM, OpenShift Bot <notifications@github.com>
wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/10458/) (Base
Commit: b5156c2
<https://github.com/openshift/origin/commit/b5156c2965f0b48135d3b2d798ab6ea4c62cd66a>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/11065#issuecomment-255507317>,
or mute
the thread

**Comment by bparees** [comment]
@smarterclayton did you mean to comment on this PR? it's already merged.

**Comment by bparees** [comment]
(and yes, swagger was updated as part of it)

**Pull request merged**
