### PR TITLE
bump(github.com/docker/docker):7d2188f9955d3f2002ff8c2e566ef84121de5217

### PR DESCRIPTION
**Pull request by kargakis**
Bumping Docker to the commit I had bumped my changes in a previous pull request. @smarterclayton ptal so I can then submit the Docker parsing stuff as a separate pr

### CODE REVIEW

**Comment by kargakis** [comment]
How are we supposed to address an autogenerated file here? See [this](https://github.com/docker/docker/commit/6871b9b16afe46e7566ac2937246b4a64be97269)

(cc: @bparees @smarterclayton )

**Comment by bparees** [comment]
@kargakis good question.  i'm guessing the actual content doesn't matter because we're probably never invoking anything that uses it (in fact i'm surprised we're pulling in this much of the docker project in the first place), so maybe we can just check in a dummy one with a version value that makes it clear it's our dummy version.  @smarterclayton  ?

**Comment by smarterclayton** [comment]
Yeah, check in a dummy version.  Unfortunate - this is why I hate static vars creeping in (we have this problem as well with version).

**Comment by kargakis** [comment]
I have added the dummy `dockerversion` file under `autogen/` where it's now generated in Docker. One thing to note is all of the uninitialized (by us) constants are actually used in a package we already import ([here](https://github.com/kargakis/origin/blob/bfe912f760d7429b4c908a2778684388fb5c23fa/Godeps/_workspace/src/github.com/docker/docker/utils/utils.go#L97), [here](https://github.com/kargakis/origin/blob/bfe912f760d7429b4c908a2778684388fb5c23fa/Godeps/_workspace/src/github.com/docker/docker/utils/utils.go#L114) and [here](https://github.com/kargakis/origin/blob/bfe912f760d7429b4c908a2778684388fb5c23fa/Godeps/_workspace/src/github.com/docker/docker/utils/utils.go#L126)). We don't actually use the function that exports them though.

> in fact i'm surprised we're pulling in this much of the docker project in the first place

@bparees we import the whole [docker/utils](https://github.com/docker/docker/tree/master/utils) package just to check for [one](https://github.com/openshift/origin/blob/7c8835293ab72a1d9fd21e3d0e81583fc1c5fed4/pkg/dockerregistry/client.go#L175) error is probably one example for that

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
