### PR TITLE
eliminate fallback to root command when another command is explicitly re...

### LINKED ISSUE #1249: "openshift ex login" fails with "unknown flag: --certificate-authority"
We need this for beta2 and @sdodson noticed it's failing.  I just built the lasted origin and I see the same problem.

~~~
# openshift ex login --certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/root.crt --server=https://localhost:8443 --namespace=demo --name=demo
unknown flag: --certificate-authority
~~~

### PR DESCRIPTION
**Pull request by deads2k**
...quested

Fixes #1249 

Previously, when you explicitly call a subcommand, if that subcommand fails then cobra attempts to run the root command.  That causes flags to be reparsed with different rules, resulting in a bizarre error message.  I don't see why anyone would ever want that sort of fallback behavior.

@fabianofranz Can you review?

### CODE REVIEW

**Comment by ncdc** [comment]
If I had to guess, I'd say the fallback is in the event it couldn't find a subcommand. Unfortunately, since it only returns a single error from `findAndExecute`, it's not possible to tell if the error means "error running subcommand, therefore stop," or "unable to find subcommand, try the root".

**Comment by fabianofranz** [comment]
@deads2k The fix LGTM, but are we going to propose this upstream (both Cobra and Kube) or are we officially forking Cobra?

**Comment by fabianofranz** [comment]
Or just UPSTREAM for now?

**Comment by soltysh** [comment]
+1 on pushing it in both (iow. Cobra and Kube) place.

**Comment by smarterclayton** [comment]
Please open and link a pull to upstream before we merge this.

**Comment by deads2k** [comment]
upstream pull is here: https://github.com/spf13/cobra/pull/79

**Comment by deads2k** [comment]
@fabianofranz the fix looks a little different to handle some edge case behavior in cobra command.  Can you re-review?

**Comment by deads2k** [comment]
@liggitt This causing us pain

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
