### PR TITLE
Fix for bugz 1392862 - don't allow wildcard policy if host is not specified.

### PR DESCRIPTION
**Pull request by ramr**
Fixes bugz https://bugzilla.redhat.com/show_bug.cgi?id=1392862

@knobunc  @liggit PTAL thx

### CODE REVIEW

**Comment by ramr** [comment]
[test]

**Comment by pravisankar** [comment]
re[test] flaked on https://github.com/openshift/origin/issues/11777

**Comment by knobunc** [comment]
To make the bot happy:
Fixes bug 1392862

**Comment by knobunc** [comment]
[test] flaked on https://github.com/openshift/origin/issues/10988

**Comment by knobunc** [comment]
[merge]

**Comment by dcbw** [comment]
LGTM from 10,000ft

**Comment by knobunc** [comment]
Test flake was https://github.com/openshift/origin/issues/10773

**Pull request merged**
