### PR TITLE
UPSTREAM: 28500: don't migrate files you can't access

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/9581

@fabianofranz hold for rebase.

### CODE REVIEW

**Comment by fabianofranz** [comment]
LGTM, holding for rebase.

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
looks a lot like  https://github.com/openshift/origin/issues/9195, re[merge] re[test]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/9548 re[test]

**Pull request merged**
