### PR TITLE
[release 4.2] Bug 1801742: Multiple iptables improvements for kubelet and kube-proxy

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Several performance improvements from upstream
UPSTREAM 80368
UPSTREAM 82602
UPSTREAM 78547
UPSTREAM 81517
UPSTREAM 83402

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
/retitle [release 4.2] Bug 1801742: Multiple iptables improvements for kubelet and kube-proxy

**Comment by juanluisvaladas** [comment]
@danwinship can you please review?

**Comment by danwinship** [comment]
Drop 78547; the patchset is big enough without pulling in unrelated fixes.
Also, you need to add back the e2e test from 81517.

**Comment by juanluisvaladas** [comment]
1- Removed upstream 78547.
2- Added the e2e test from upstream 81517.
3- Added github.com/openshift/sdn#126

**Comment by danwinship** [comment]
@juanluisvaladas can you squash https://github.com/danwinship/origin/commit/c50267cf ?

**Comment by juanluisvaladas** [comment]
@danwinship done, looks like that fixed it

**Comment by danwinship** [comment]
can you squash my commit into yours?

**Comment by juanluisvaladas** [comment]
> can you squash my commit into yours?

Do you mean instead of having https://github.com/openshift/origin/pull/24685/commits/196de22ad3e225dcefb4553c44bd8a51c12a65fa and https://github.com/openshift/origin/pull/24685/commits/4e65a7a99e27b36a92116925e3b3d797f8d4ef3c having just one commit for both?

**Comment by danwinship** [comment]
yes. in particular if you do `git rebase --autosquash -i release-4.2` and then just immediately close the rebase editor, it should do the right thing

**Comment by juanluisvaladas** [comment]
Very cool! wasn't aware of this fixup thing. Will do the same for the other one.

**Comment by danwinship** [comment]
sorry, can you re-push without the last commit ("`Bug 1820778: fix health check in standalone kube-proxy`")? We don't build kube-proxy from the origin code in 4.2 (or later) so it's weird to have a kube-proxy-specific fix here (especially when we don't have _all_ of the kube-proxy-specific fixes)

otherwise I think this is ready

**Comment by danwinship** [comment]
er, no, as with the other PR, this is missing "`UPSTREAM: 83402: iptables.Monitor: don't be fooled by "could not get lock" errors`"

**Comment by juanluisvaladas** [comment]
@JacobTanenbaum  @danwinship sorry for the delay. All issues addressed

**Comment by juanluisvaladas** [comment]
/close
We decided not to backport this to 4.2

**Pull request closed without merging**
