### PR TITLE
Node was blocking rather than running in goroutine

### LINKED ISSUE #2996: start node never reaches SdNotify("READY=1")
Something has changed between v0.5.2 and origin/master preventing the notification from being sent to systemd which means that systemd kills the process after 90 second timeout

### PR DESCRIPTION
**Pull request by smarterclayton**
Ensures that the systemd ready call gets made

Fixes #2996

### CODE REVIEW

**Comment by smarterclayton** [comment]
[merge]

**Comment by sdodson** [comment]
Confirmed that this fixed the issue.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
