### PR TITLE
no commit id in img name and add openshift org to image name for open…

### PR DESCRIPTION
**Pull request by gabemontero**
…shift-pipeline plugin extended test

@bparees PTAL - these are the additional changes we've emailed about to support the test-openshift-pipeline-plugin job at ci.openshift

### CODE REVIEW

**Comment by gabemontero** [comment]
[testonlyextended][extended:core(openshift pipeline plugin)]

**Comment by bparees** [comment]
lgtm pending extended test pass

**Comment by gabemontero** [comment]
ok cool ... the first of the 2 runs failed during the build of the openshift/node image, unable to access a mirror, etc etc.

The second was able to successfully build and the extended test is running now ...

**Comment by gabemontero** [comment]
... and it passed successfully.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Pull request merged**
