### PR TITLE
Removing unnecessary namespace prefix for deployment/deploymentConfig/Repo

### PR DESCRIPTION
**Pull request by jhadvig**
Noticed that the:
- LabelForDeploymentConfig
- LabelForDeployment
- labelForRepo

functions already contain namespace prefix, so removing it.
@ironcladlou fyi

### CODE REVIEW

**Comment by jhadvig** [comment]
@kargakis @soltysh PTAL

**Comment by kargakis** [comment]
LGTM

**Comment by soltysh** [comment]
LGTM [merge]

@jhadvig as a side not, maybe we should "steal" that idea of LabelForXYZ and apply this to every object, not now but soon :wink:

**Comment by jhadvig** [comment]
@soltysh thats a good idea and we definitely should have done it that way(maybe create a card for that???)

**Comment by ironcladlou** [comment]
Thanks for fixing this!

**Pull request merged**
