### PR TITLE
[3.11] Increase limit for signatures

### PR DESCRIPTION
**Pull request by dmage**
https://bugzilla.redhat.com/show_bug.cgi?id=1705984

### CODE REVIEW

**Comment by adambkaplan** [comment]
/approve

/cc @bparees @smarterclayton 
Per discussion with Oleg there were outstanding concerns over etcd performance storing so many signatures.

**Comment by bparees** [comment]
@dmage there were a couple other concerns about the behavior raised in that BZ, are you intending to address them elsewhere?

Just increasing the limit doesn't do much to address most of the problems in that BZ.

https://bugzilla.redhat.com/show_bug.cgi?id=1705984#c38
https://bugzilla.redhat.com/show_bug.cgi?id=1705984#c39
https://bugzilla.redhat.com/show_bug.cgi?id=1705984#c40

**Comment by dmage** [comment]
@bparees maybe one day I'll address them. Not this sprint.

**Comment by bparees** [comment]
> @bparees maybe one day I'll address them. Not this sprint.

that's fine, i just wanted to clarify whether you were intending to close out the BZ based on this PR.  If you're going to leave the BZ open when this merges, that's fine.

**Comment by adambkaplan** [comment]
@bparees per discussion it made sense to split the fixes into multiple PRs. There are other changes that need to occur upstream as well (ex - one component is using the deprecated `/oapi` endpoint)

**Comment by bparees** [comment]
@dmage @adambkaplan we also need to clone https://bugzilla.redhat.com/show_bug.cgi?id=1705984 to 4.1.z and 4.2.0 (and deliver this and the other fixes to those branches) to ensure we don't regress customers when they upgrade from 3.11.

**Comment by bparees** [comment]
@dmage @adambkaplan also since this is 3.11 i think you may need to explicitly ask ART to do a 3.11.z errata to pick this up, once it is merged.

**Comment by bparees** [comment]
actually @derekwaynecarr does this need cherry-pick approval? i would assume so.....

**Comment by bparees** [comment]
(and cherry-pick approval won't be granted until this is in 4.2 first)

**Comment by derekwaynecarr** [comment]
there should be a clone of a bz for each release that is getting a fix.

**Pull request merged**
