### PR TITLE
UPSTREAM: 34831: cloudprovider/gce: canonicalize instance name when returning instance array

### PR DESCRIPTION
**Pull request by dcbw**
@knobunc @liggitt @soltysh

### CODE REVIEW

**Comment by soltysh** [comment]
@dcbw can you include justification why we want to have this cherry-pick bugzilla no, for example? Unless this is on our blocker bug list it might not be considered for 1.4.

// cc @ncdc

**Comment by dcbw** [comment]
> @dcbw can you include justification why we want to have this cherry-pick bugzilla no, for example? Unless this is on our blocker bug list it might not be considered for 1.4.

@soltysh OpenShift doesn't work on multi-zone GCE without this patch.  See the threads on aos-devel list with the title "Can't deploy OCP 3.3 on multizone GCE".  I'll leave it up to somebody else whether multizone GCE is something we care about for 3.4 or not.

**Comment by soltysh** [comment]
@ncdc I'll leave the decision to either you or @smarterclayton about whether we need it for 1.4

**Comment by ncdc** [comment]
cc @danmcp

**Comment by danmcp** [comment]
If the risk is low, we certainly want the feature for 3.4.

**Comment by ncdc** [comment]
It's low risk. I'm fine merging it.

**Comment by ncdc** [comment]
[merge]

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/11685 [merge]

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/10773 [merge]

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
