### PR TITLE
Rename project service to ProjectsService, update existing uses

### PR DESCRIPTION
**Pull request by benjaminapetersen**
@jwforres @spadgett this is pt3 of [breaking down this PR](https://github.com/openshift/origin/pull/5953).  In this one I'm renaming project to ProjectsService & updating all the controllers using it already.  I'm creating one more PR that updates all of the controllers where ProjectsService will be newly introduced.

### CODE REVIEW

**Comment by jwforres** [comment]
this PR is picking up one of david's commits, maybe try rebasing?

**Comment by jwforres** [comment]
hmmm, it also looks like you didnt intend to include everything thats in that last commit either, assuming befc2ce is what you wanted?

**Comment by benjaminapetersen** [comment]
Erm. Yeah.  Fixing this.  :confused:

**Comment by benjaminapetersen** [comment]
Also, leaving the `BuildsService` and `DeploymentsService` taking both `$scope, context` until another PR where I'll update those, per discussion.

**Comment by benjaminapetersen** [comment]
@jwforres fixed the weird stuff.  Even with the `?w=1` trick this is still a bit tricky to review, sorry.

**Comment by jwforres** [comment]
looks good, fork_ami

**Comment by benjaminapetersen** [comment]
Latest update/rebase includes a tweak to deleteButton.js.

**Comment by benjaminapetersen** [comment]
[TEST]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
@jwforres don't merge #5997 until I rebase on this change

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
