### PR TITLE
[release-4.12] OCPBUGS-8705: Bump(openshift/kubernetes): to get fix for resizing flake

### PR DESCRIPTION
**Pull request by bertinatto**
Changes generated with:

`./hack/update-kube-vendor.sh eab9cc98fe4c002916621ace6cdd623afa519203`

/assign @soltysh @dgoodwin @stbenjam @gnufied @dhellmann @joep

CC @openshift/storage

### CODE REVIEW

**Comment by stbenjam** [comment]
/label cherry-pick-approved
/label backport-risk-assessed

The jira bug needs some tweaking to make the automations happy

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
