### PR TITLE
Add openssh-clients package to f5-router

### PR DESCRIPTION
**Pull request by pecameron**
bug: 1645755
https://bugzilla.redhat.com/show_bug.cgi?id=1645755

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@smarterclayton @pweil- Do we still want to do this? If so PTAL and help this get through the test problems. This change should not trigger a test failure.

**Comment by dcbw** [comment]
/lgtm
@knobunc can you take a look and approve?

**Pull request merged**
