### PR TITLE
Bug 1684397: Remove custom build template

### PR DESCRIPTION
**Pull request by adambkaplan**
Per [BZ 1684397](https://bugzilla.redhat.com/show_bug.cgi?id=1684397), removing this template in favor of openshift-docs tutorial.

### CODE REVIEW

**Comment by bparees** [comment]
looks like you need to update bindata.

also it looks like this template is used in a few e2e/cli tests..so at a minimum it needs to be moved into the test folder so they can continue using it.  (i'm not sure what those tests are doing with it..not much presumably since they aren't failng)

**Comment by adambkaplan** [comment]
@bparees moved the custom strategy example to `test/extended/testdata/builds`.

**Pull request merged**
