### PR TITLE
Web Console: Hide images section when no images detected in template creation

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by mfojtik** [comment]
@csrwng if you do this, does the 'create' works?

**Comment by mfojtik** [comment]
@csrwng maybe a suggestion for this screen... can we detect Services and show them? So users can see what services this Template provides (ports?)

**Comment by csrwng** [comment]
@mfojtik create works regardless. The issue with create was the method signature mismatch that @spadgett fixed.

**Comment by csrwng** [comment]
@mfojtik - yup, we can detect services... we should show them

**Comment by csrwng** [comment]
@liggitt merge?

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
