### PR TITLE
provider recorder to attach detach controller

### PR DESCRIPTION
**Pull request by rootfs**
@gnufied @childsb 

attach/detach controller uses recorder in operation_executor.go, but openshift forgets to provide one

### CODE REVIEW

**Comment by rootfs** [comment]
@eparis

**Comment by rootfs** [comment]
fix master panic in https://bugzilla.redhat.com/show_bug.cgi?id=1397693

**Comment by gnufied** [comment]
[test]

**Comment by childsb** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by gnufied** [comment]
So this commit was never cherry picked to OSE-3.4 and bug about panic still exists in 3.4. I am going to open the PR for 3.4

**Pull request merged**
