### PR TITLE
Drop capabilities in s2i build container by default

### PR DESCRIPTION
**Pull request by csrwng**
The container that is launched by s2i (outside of Kube control) currently allows an escalation of privilege via su or sudo. We can prevent this by dropping the same capabilities that are dropped for regular pods when running under the restricted SCC. 

Fixes BZ 1315187

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @mfojtik @liggitt

**Comment by csrwng** [comment]
[testonlyextended][extended:core(builds)]

**Comment by bparees** [comment]
I think you can avoid the builder image build by just including the customized assemble script as ".s2i/bin" in the context dir you upload as the binary input, no?

**Comment by csrwng** [comment]
I also set the root password in the builder image and install 'expect'

**Comment by bparees** [comment]
so you do.  lgtm, pending resolution to the tests failing.

**Comment by csrwng** [comment]
@bparees, I opened issues for the tests that failed:
https://github.com/openshift/origin/issues/7904
https://github.com/openshift/origin/issues/7906
https://github.com/openshift/origin/issues/7910
https://github.com/openshift/origin/issues/7911

none of those are related to this change.
[test]

**Comment by bparees** [comment]
@csrwng thanks, lgtm.
[merge]

**Pull request merged**
