### PR TITLE
Fix for etcd client oneshot cluster member cycling

### PR DESCRIPTION
**Pull request by rrati**
backport of https://github.com/coreos/etcd/pull/8519

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton @liggitt can you guys review this pls? it is on the 3.7 list of blocker bugs.

**Comment by smarterclayton** [comment]
We won't support etcd2 in 3.7

**Comment by liggitt** [comment]
is this etcd2 only?

**Comment by smarterclayton** [comment]
Yes, this is etcd2 only.

**Comment by liggitt** [comment]
great, so only needed for 3.5/3.6

**Pull request closed without merging**
