### PR TITLE
make function addDefaultEnvVar cleaner

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/11292
[merge]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/11240
[merge]

**Comment by guangxuli** [comment]
hi, @csrwng sorry to bother you again,  can you take a look for this PR again? thanks :)

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/8571
[merge]

**Pull request merged**
