### PR TITLE
Bump to 1.16-beta.2

### PR DESCRIPTION
**Pull request by sttts**
- [x] @sjenning `CHECK(pod): glide.yaml: detach from fork: 1805 merged`
- [x] ~@jsafrane~ @sjenning @bparees @adambkaplan  `RECHECK: glide.yaml: remove pinning` for github.com/containers/storage
- [x] @deads2k `RECHECK: glide.yaml: remove pinning` – removed pinning
- [x] @sjenning `TODO(node): glide.yaml: recheck docker refs` – `github.com/docker/*` dependencies unchanged
- [x] @sjenning `UPSTREAM: <drop>: CHECK(node): disable pkg/kubelet/oom test that only runs as root`
- [x] @enj @stlaz `CHECK(api/auth): fixups extended tests`
- [x] @bparees @adambkaplan `CHECK(devex): fixups extended tests`
- [x] @squeed @danwinship `CHECK(sdn): fixups extended tests`
- [x] @s-urbaniak @brancz  `CHECK(metrics): fixups extended tests`
- [x] @ironcladlou `CHECK(network-edge): fixups extended tests`
- [x] @sjenning `UPSTREAM: <carry>: CHECK(node): disable --node-label validation for unknown` labels
- [x] @squeed @danwinship `CHECK(sdn): extended: fix networking helpers`
- [x] @squeed @danwinship  `CHECK(sdn): e2e: disable unsupported sdn features`
- [x] @squeed @danwinship `CHECK(sdn): e2e: temporarily disable headless test`
- [x] @jsafrane `CHECK(storage): e2e: disable tests which require SSH`
- [x] @soltysh `CHECK(workload): e2e: disable kubectl exec test with pod/name syntax` https://bugzilla.redhat.com/show_bug.cgi?id=1751654
- [x] @damemi @ingvagabund @ravisantoshgudimetla  `CHECK(workloads): extended: disable SchedulerPreemption tests again` https://bugzilla.redhat.com/show_bug.cgi?id=1751661
- [x] @enj `CHECK(mo): extended: add discovery endpointslices to etcd storage test`
- [x] @crawford @wking @abhinavdahiya `CHECK(cvo): extended: remove non-functional CVO status check failing with today's objx lib`
- [x] @sjenning `CHECK(node): extended: disable RuntimeClass tests requiring cri-o config`
- [x] @squeed @danwinship `CHECK(sdn): e2e: disable failing NetworkPolicy ingress test`
- [x] @csrwng `CHECK(cesarwong): extended: make HPA RC test serial, but disabled` https://bugzilla.redhat.com/show_bug.cgi?id=1744069

### CODE REVIEW

**Comment by deads2k** [comment]
terraform
/retest

**Comment by deads2k** [comment]
`TestStorageVersionHashes` unit failed twice

**Comment by sttts** [comment]
> `TestStorageVersionHashes` unit failed twice

Fixed (due to extensions/v1beta1 and apps/v1beta2 being reactivated). Will push when we have e2e test results.

**Comment by danwinship** [comment]
`[Feature:IPv6DualStackAlphaFeature]` should be added to `[Disabled:Alpha]`

In `[Disabled:Unimplemented]`, add
- `NetworkPolicy.*egress` - we don't support NetworkPolicy egress rules. https://jira.coreos.com/browse/SDN-51
- `NetworkPolicy.*named port` - We already have a skip for `NetworkPolicy between server and client should allow egress access on one named port` but the test got renamed. https://bugzilla.redhat.com/show_bug.cgi?id=1711602

`Services should implement service.kubernetes.io/headless` will need to be disabled until we rebase openshift/sdn to get the new proxy code.

These tests should not be failing and I'll investigate:
- `Services should preserve source pod IP for traffic thru service cluster IP` (used to work)
- `NetworkPolicy between server and client should allow ingress access from updated pod` (new test, not sure what's up)

**Comment by sttts** [comment]
broken CI
/retest

**Comment by sttts** [comment]
`fail [github.com/openshift/origin/test/extended/util/client.go:644]: Sep 10 14:08:54.425: read /tmp/configfile853443898: cannot allocate memory`

**Comment by sttts** [comment]
/retest

1 flake, 1 that should only run in serial

**Comment by s-urbaniak** [comment]
this lgtm for the prometheus tests :+1:

**Comment by sttts** [comment]
Fixed the TestBlockMapperMapDeviceNotSupportAttach 
 flake with https://github.com/kubernetes/kubernetes/pull/82697, and picked https://github.com/kubernetes/kubernetes/pull/82669.

**Comment by sttts** [comment]
CI terraform issues?

/retest

**Comment by wking** [comment]
> CI terraform issues?

Yeah, [the earlier e2e-aws failure][1] was [rhbz#1745196][2].  One of [two from the past 24 hours][3], so currently not a high priority, but still something we want to fix at some point :).

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23750/pull-ci-openshift-origin-master-e2e-aws/12731
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1745196
[3]: https://ci-search-ci-search-next.svc.ci.openshift.org/chart?name=.&search=unexpected%20new%20value%20for%20was%20present,%20but%20now%20absent

**Comment by sttts** [comment]
AWS DNS flake? No such host.

/retest

**Comment by sdodson** [comment]
@sttts this should be closed, correct?

**Comment by sttts** [comment]
@p0lyn0mial 's variant of this merged.

**Pull request closed without merging**
