### PR TITLE
deploy: emit events on the dc instead of its rcs

### PR DESCRIPTION
**Pull request by kargakis**
More helpful since people look for problems into the dc more often than looking at the respective rcs.

Fixes https://github.com/openshift/origin/issues/7295
Fixes https://github.com/openshift/origin/issues/5191

@smarterclayton @ironcladlou PTAL

### CODE REVIEW

**Comment by ironcladlou** [comment]
LGTM, good idea

**Comment by smarterclayton** [comment]
SGTM - didn't deep review, but if @ironcladlou is good let's [merge]

**Comment by kargakis** [comment]
```
[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i complete'...
ruby-sample-build-1   Source    Git@bd94cbb   Failed    9 seconds ago   9s
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i complete'
!!! Error in hack/../hack/../test/end-to-end/../../hack/util.sh:282
	'return 1' exited with status 1
Call stack:
	1: hack/../hack/../test/end-to-end/../../hack/util.sh:282 os::build:wait_for_end(...)
	2: hack/../hack/../test/end-to-end/core.sh:219 main(...)
Exiting with status 1
```
build flake

re[merge]

**Comment by smarterclayton** [comment]
This is the cgroups bug

On Mar 7, 2016, at 6:40 PM, Michail Kargakis <notifications@github.com>
wrote:

[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i
complete'...
ruby-sample-build-1   Source    Git@bd94cbb   Failed    9 seconds ago   9s
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep
-i complete'
!!! Error in hack/../hack/../test/end-to-end/../../hack/util.sh:282
    'return 1' exited with status 1
Call stack:
    1: hack/../hack/../test/end-to-end/../../hack/util.sh:282
os::build:wait_for_end(...)
    2: hack/../hack/../test/end-to-end/core.sh:219 main(...)
Exiting with status 1

build flake

re[merge]

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/7830#issuecomment-193508789>.

**Pull request merged**
