### PR TITLE
Fix pod template clipped issue

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://github.com/openshift/origin/issues/4489
Fixes https://github.com/openshift/origin/issues/3718
icon alignment and font sizing corrections
remove unused styles

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres for review

screenshots
mobile
desktop

**Comment by jwforres** [comment]
changes LGTM, just waiting on #5023 to get merged before rebuilding/merging this one

**Comment by jwforres** [comment]
@sg00dwin can rebase and rebuild now

**Comment by sg00dwin** [comment]
@jwforres rebased

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
