### PR TITLE
Add etcd3 dump tool

### PR DESCRIPTION
**Pull request by enj**
Simple CLI tool to dump everything from a running etcd3 server (handles decoding of API objects).  @stevekuznetsov could you write the BASH to use this?  I need to focus on some other stuff.

```
etcd3dump --endpoint='https://10.13.129.193:4001' --key-file="${BASE}/openshift.local.config/master/master.etcd-client.key" --cert-file="${BASE}/openshift.local.config/master/master.etcd-client.crt" --ca-file="${BASE}/openshift.local.config/master/ca.crt" > etcd3dump.json
```

cc @bparees 

xref: #14145 

[test]

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by kargakis** [comment]
We already have a tool for etcd, can't this be part of it as opposed to something separate?

https://github.com/openshift/origin/blob/master/tools/etcdhelper/etcdhelper.go

cc: @soltysh

**Comment by enj** [comment]
> We already have a tool for etcd, can't this be part of it as opposed to something separate?

@kargakis I was mostly trying to make a simple "dump all of etcd3 to stdout" (i.e. something that behaves like a curl to etcd2).  But yes, this could be added as another subcommand of the other tool.

**Comment by soltysh** [comment]
@enj the tool that @kargakis mentioned is also a simple tool to preview etcd contents, that was my idea. So I entirely agree to add your functionality to that tool, instead of creating another one. I bet the majority of logic can be shared.

**Comment by soltysh** [comment]
Yes, my intention was to have something like etcd2 provided wrt to client usage.

**Comment by stevekuznetsov** [comment]
Nit, but can we have the flags mirror `curl` so we can be clever with Bash? `--cert`, `--key`, `--cacert` ?

Will it handle P12 format for client cert+key? This is requires for OSX

**Comment by enj** [comment]
@stevekuznetsov @soltysh @kargakis PTAL at 33f49547728f38a345f235b34a6196ade18f95ac

I will drop 8abf228eb1dd927542c5d52aefa96759b86670ec once you guys are good.

**Comment by stevekuznetsov** [comment]
```patch
From 984b3dac65ff6cc8d6f7f7519cd9f286c39126d1 Mon Sep 17 00:00:00 2001
From: Steve Kuznetsov <skuznets@redhat.com>
Date: Tue, 16 May 2017 08:23:43 -0700
Subject: [PATCH] Dump contents of etcd v3 using the etcdhelper tool

When we are running tests with etcd v3 enabled, the `curl` approach to
recursively dumping contents from etcd will not work, even with the
correct keyspace, as the contents are encoded in protobuf. The
`etcdhelper` tool allows us to make a plain-text dump of the full
contents.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
 hack/lib/cleanup.sh | 32 ++++++++++++++++++++++++++++++--
 1 file changed, 30 insertions(+), 2 deletions(-)

diff --git a/hack/lib/cleanup.sh b/hack/lib/cleanup.sh
index a66f278..3c818fe 100644
--- a/hack/lib/cleanup.sh
+++ b/hack/lib/cleanup.sh
@@ -55,12 +55,40 @@ readonly -f os::cleanup::all
 #  None
 function os::cleanup::dump_etcd() {
 	if [[ -n "${API_SCHEME:-}" && -n "${API_HOST:-}" && -n "${ETCD_PORT:-}" ]]; then
-		os::log::info "[CLEANUP] Dumping etcd contents to $( os::util::repository_relative_path "${ARTIFACT_DIR}/etcd_dump.json" )"
-		os::util::curl_etcd "/v2/keys/?recursive=true" > "${ARTIFACT_DIR}/etcd_dump.json"
+		local dump_dir="${ARTIFACT_DIR}/etcd"
+		mkdir -p "${dump_dir}"
+		os::log::info "[CLEANUP] Dumping etcd contents to $( os::util::repository_relative_path "${dump_dir}" )"
+		os::util::curl_etcd "/v2/keys/?recursive=true" > "${dump_dir}/v2_dump.json"
+		os::cleanup::internal::dump_etcd_v3 > "${dump_dir}/v3_dump.json"
 	fi
 }
 readonly -f os::cleanup::dump_etcd
 
+# os::cleanup::internal::dump_etcd_v3 dumps the full contents of etcd v3 to a file.
+#
+# Globals:
+#  - ARTIFACT_DIR
+#  - API_SCHEME
+#  - API_HOST
+#  - ETCD_PORT
+# Arguments:
+#  None
+# Returns:
+#  None
+function os::cleanup::internal::dump_etcd_v3() {
+	local full_url="${API_SCHEME}://${API_HOST}:${ETCD_PORT}"
+
+	local etcd_client_cert="${MASTER_CONFIG_DIR}/master.etcd-client.crt"
+	local etcd_client_key="${MASTER_CONFIG_DIR}/master.etcd-client.key"
+	local ca_bundle="${MASTER_CONFIG_DIR}/ca-bundle.crt"
+
+	os::util::ensure::built_binary_exists 'etcdhelper'
+
+	etcdhelper --cert "${etcd_client_cert}" --key "${etcd_client_key}" \
+	           --cacert "${ca_bundle}" --endpoint "${full_url}" dump
+}
+readonly -f os::cleanup::internal::dump_etcd_v3
+
 # os::cleanup::prune_etcd removes the etcd data store from disk.
 #
 # Globals:
-- 
2.9.3
```

**Comment by soltysh** [comment]
Yup, that looks good!

**Comment by enj** [comment]
[merge]

@stevekuznetsov @bparees feel free to nag the people with green button if you need etcd3 dumps sooner than the next few days...

**Comment by bparees** [comment]
thanks for doing this @enj

**Pull request merged**
