### PR TITLE
remove extraneous escapes

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
fixes: https://github.com/openshift/origin/issues/2141

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@liggitt ptal.

**Comment by liggitt** [comment]
phantomjs flake, re[test]

**Comment by liggitt** [comment]
did you want to remove `route/rest.go#escapeNewLines` or leave that to @pweil- ?

**Comment by liggitt** [comment]
question on `escapeNewLines`, changes LGTM otherwise

**Comment by bparees** [comment]
@liggitt i'm worried about removing it at all, to be honest...  we could have users out there who copied our example and would be broken (I assume?) if stopped substituting the \\n right?

if we do agree to keep it, i'll update the comment on it though.

**Comment by pweil-** [comment]
How about a validation that rejects it so we can get rid of the bad code?

**Comment by liggitt** [comment]
@pweil- did your TLS validation PR get to a place we were happy with?

**Comment by pweil-** [comment]
no, it has been back burner for SCCs.  I'm hoping to get some time in the evening (lol) this week to get back to it.

**Comment by liggitt** [comment]
ok, I'm fine merging this now... @pweil-, want another issue to track removing `escapeNewLines` and adding validation?

**Comment by liggitt** [comment]
[merge]

**Comment by pweil-** [comment]
Yes. I'm also going to go ahead and run a manual test with some example routes before I'm DFD just to ease my mind about the files being written correctly.

**Comment by pweil-** [comment]
Tested with an edge terminated route successfully

**Comment by bparees** [comment]
[merge]

**Pull request merged**
