### PR TITLE
service catalog: updates for upstream v0.1.16

### PR DESCRIPTION
**Pull request by jboyd01**

### CODE REVIEW

**Comment by jpeeler** [comment]
/test service-catalog
v0.1.16 image is available now, so hopefully this passes

**Comment by jpeeler** [comment]
Service catalog job passed, the run reported from the bot is outdated (currently catalog tests have been disabled). PR is good to go.

**Comment by pmorie** [comment]
/lgtm cancel

@jboyd01 tells me that there are still issues with admission control that need to be worked out.

**Comment by pmorie** [comment]
/lgtm

@jboyd01 is going to handle the admission issues separately

**Pull request merged**
