### PR TITLE
UPSTREAM: 38137: glusterfs: Fix all gid types to int to prevent failures on 32bit systems

### PR DESCRIPTION
**Pull request by obnoxxx**

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM [test][merge]

**Comment by jsafrane** [comment]
[test]

**Comment by eparis** [comment]
[merge]

**Comment by jsafrane** [comment]
[test]
flake: #12157

**Comment by smarterclayton** [comment]
ok to direct merge

**Pull request merged**
