### PR TITLE
Eliminate idle waits in router_test.go

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Deflate the test by forcing all changes to be level driven and active poll, rather than slow waits.  Removed all sleeps.  With this change router tests have to assert the change first, then test any invariants (i.e. Make a change, verify you see it, then check whether old data is present.  Also logs the router failure).

@ramr review please

**Comment by smarterclayton** [comment]
Or @pweil-

**Comment by pweil-** [comment]
LGTM, +1 to dumping the logs on failure.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
