### PR TITLE
Router should tolerate not having permission to write status

### LINKED ISSUE #7452: Regression: router is error when i update it for 1.1.3
hi,
when i change the route images to 1.1.3.it is error,the error log as:
User "system:openshift-router" cannot update routes/status in project "default"
router-error
but when i use openshift/origin-haproxy-router:v1.1.1.1 or openshift/origin-haproxy-router:v1.1.2 that will be ok.
router-ok
I update the route form 1.0.x to 1.1.x/1.1.2 that also is ok。
hown can i do for the 1.1.3?
thank!

### PR DESCRIPTION
**Pull request by smarterclayton**
Ensures that the router is backwards compatible until roles are updated. Fixes a 1.1.3 regression.

Fixes #7452

### CODE REVIEW

**Comment by smarterclayton** [comment]
@pweil- review please since ram is out

**Comment by smarterclayton** [comment]
[test]

**Comment by pweil-** [comment]
good call - LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
