### PR TITLE
STOR-1823: Remove payload tests that use shared-resource CSI driver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1823

This PR:
- removes the builds/volumes tests that depend on the shared resource CSI driver
- reworks the storage/inline tests to use a dummy CSIDriver object to test the admission plugin
- removes related manifests that are no longer used

/cc @openshift/storage @adambkaplan @gabemontero

### CODE REVIEW

**Comment by dobsonj** [comment]
All of the e2e-gcp-ovn-builds failures were due to image pull failures:
```
Pull image still failed due to error: initializing source docker://image-registry.openshift-image-registry.svc:5000/openshift/ruby:3.0-ubi8: reading manifest 3.0-ubi8 in image-registry.openshift-image-registry.svc:5000/openshift/ruby: manifest unknown
```
That should be fixed by https://github.com/openshift/origin/pull/29134

The other jobs look like unrelated flakes
/retest

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

These tests can (and _should_) be migrated to a test suite for the Builds for OpenShift layered product. The test should be in a modified form that utilizes core Shipwright features.

cc @sayan-biswas @apoorvajagtap @avinal @ayushsatyam146 @jitendar-singh

**Review by bertinatto — COMMENTED** [review]
The removal of the tests was acked by @adambkaplan. Replacing SharedResourceDriver with a CSIDriver object to test inline also makes sense.

/approve

**Comment by jsafrane** [comment]
/test e2e-gcp-ovn-builds
tide says it's required

**Pull request merged**
