### PR TITLE
Remove moment timezone

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@spadgett @jwforres

**Comment by liggitt** [comment]
drops timezone data (180kb) and datepicker js (40kb) which we're not using

**Comment by jwforres** [comment]
Lgtm

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
[merge] for queue

**Comment by spadgett** [comment]
LGTM

**Comment by liggitt** [comment]
integration/e2e/asset tests passed in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/640/

confirmance tests had unrelated downwardapi failure in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/752/

merging to unblock queue

**Pull request merged**
