### PR TITLE
Resuse existing imagestreams with new-app

### PR DESCRIPTION
**Pull request by coreydaley**
https://trello.com/c/BOR33gza/1559-3-reuse-existing-imagestreams-with-new-app-appcreationtechdebt

### CODE REVIEW

**Comment by coreydaley** [comment]
[(3) Reuse existing imagestreams with new-app [app_creation][tech_debt]](https://trello.com/c/BOR33gza/1559-3-reuse-existing-imagestreams-with-new-app-appcreationtechdebt)

**Comment by coreydaley** [comment]
@openshift/sig-developer-experience ptal

**Comment by gabemontero** [comment]
Curious if the reuse is obvious or at least discernible from the `oc new-app` output.... suppose the question of whether it should be obvious/discernible is also valid.

@coreydaley - can you provide sample output  from the consecutive invocations like in the card description, or duplicating your cmd.sh test from the command line, so we can review that as well?

thanks

**Comment by coreydaley** [comment]
@bparees @gabemontero ptal

Sample command output:

```
$ oc new-build -D $'FROM node:8\nRUN echo "Test"' --name=node8
--> Found Docker image 6f1597c (8 hours old) from Docker Hub for "node:8"

    * An image stream will be created as "node:8" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "node8:latest"
      * Every time "node:8" changes a new build will be triggered

--> Creating resources with label build=node8 ...
    imagestream "node" created
    imagestream "node8" created
    buildconfig "node8" created
--> Success
    Build configuration "node8" created and build triggered.
    Run 'oc logs -f bc/node8' to stream the build progress.
```
```
$ oc get is
NAME      DOCKER REPO                       TAGS      UPDATED
node      172.30.1.1:5000/myproject/node    8         5 seconds ago
node8     172.30.1.1:5000/myproject/node8
``` 
```
$ oc new-build -D $'FROM node:10\nRUN echo "Test"' --name=node10
--> Found Docker image 8753ede (8 hours old) from Docker Hub for "node:10"

    * An image stream will be created as "node:10" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "node10:latest"
      * Every time "node:10" changes a new build will be triggered

--> Creating resources with label build=node10 ...
    imagestreamtag "node:10" created
    imagestream "node10" created
    buildconfig "node10" created
--> Success
    Build configuration "node10" created and build triggered.
    Run 'oc logs -f bc/node10' to stream the build progress.
```

```
$ oc get is
NAME      DOCKER REPO                        TAGS      UPDATED
node      172.30.1.1:5000/myproject/node     10,8      2 seconds ago
node10    172.30.1.1:5000/myproject/node10             
node8     172.30.1.1:5000/myproject/node8
```

**Comment by bparees** [comment]
> An image stream will be created as "node:10" that will track the source image

let's just change that to always say "imagestream tag" which is more accurate.  (even in the first run).

**Comment by coreydaley** [comment]
@bparees updated in latest push

**Comment by bparees** [comment]
@coreydaley take off the wip

/lgtm

**Pull request merged**
