### PR TITLE
Commands must not use the factory outside of Run

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/11513

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by smarterclayton** [comment]
Thanks - I think I have exact same thing in https://github.com/openshift/origin/pull/11516

**Comment by fabianofranz** [comment]
@smarterclayton ok, feel free to pick yours, just note you have to adjust the long desc. Also, you can refer the upstream commit instead of `<carry>`, which is https://github.com/kubernetes/kubernetes/pull/35427

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
@smarterclayton this requires merge tag from you now, given past DCUT.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
