### PR TITLE
Use generic start utilities in test-cmd

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Use generic start utilities in test-cmd

There is no reason other than historical cruft that the command tests do
not use the generic and shared startup code in `hack/lib/start.sh`. This
patch finally converges the two startup scenarios.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Stop using loopback address for API_HOST

The original choice to use a loopback address instead of running
`openshift start --print-ip` was made for historical reasons before the
newer and more useful IP utility was available. We do not regress by not
forcing the loopback address for this test.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Start registry using administrative credentials

If a user has not exposed the `$ADMIN_KUBECONFIG` as the default
`$KUBECONFIG` to use for the `oc` client, `os::start::registry` will
need to pass the configuration file for all of the client calls, not
only the first one.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Dry out start code to use `$ADMIN_KUBECONFIG`

We provide the `$ADMIN_KUBECONFIG` variable for use after the server has
been run once to place it, so we should use it everywhere where we are
intending to use the administrative kubeconfig.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Allow for configuration of profiling with `$OPENSHIFT_PROFILE`

In order for the generic start utilities to support the command tests,
it is necessary for a user to be able to specify which profiling mode
they would like.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Allow for using network plugins with `$NETWORK_PLUGIN`

In order for the central start utilities to support the command tests,
it is necessary for a user to be able to optionally provide network
plugins to the configuration step.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Reformatted Bash and cleaned up cruft in scripts

All of the extra information that was printed by cruft in the command
test is available from more central locations. It is no longer necessary
to print this information in the test itself.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

supersedes https://github.com/openshift/origin/pull/10055

@liggitt could you please review the two commits with `[REVIEW]` prefixes
@deads2k @csrwng @smarterclayton PTAL/FYI

[test]

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
OK, saw this fail -- @deads2k @sttts @ncdc why would `oc get projects -o name` sometimes reply with `project/name` but sometimes with `projects/name`?

**Comment by stevekuznetsov** [comment]
Hmm maybe my compiled version locally was too old?

**Comment by deads2k** [comment]
The 1.6 rebase switched to plurals.

**Comment by stevekuznetsov** [comment]
@deads2k thanks for clarity re[test]

**Comment by stevekuznetsov** [comment]
Other `[REVIEW]` commit was reviewed by Clayton, [merge]]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/576/) failed from the following flakes:
 - [integration](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/576/testReport/junit/github/com_openshift_origin_test_end-to-end_core/test_end_to_end_core_sh_15__executing__oc_get__n_test_pods__l_name_database__expecting_any_result_and_text__Running___re_trying_every_0_2s_until_completion_or_60_000s/) failed on: https://github.com/openshift/origin/issues/14090

re[merge]

**Pull request merged**
