### PR TITLE
Exclude myself from most of the OWNERS files

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @simo5 @enj

### CODE REVIEW

**Comment by simo5** [comment]
Ok, let's hold a second on merging this, we may want to make some other changes, let's use this to make all the changes we need at once.

**Comment by enj** [comment]
@php-coder I purposefully added you and the rest of the team to help smear the review burden.  But it's up to you on if you want to be in the files.

**Comment by php-coder** [comment]
Added exclusion for @tiran and @legionus as well.

**Comment by enj** [comment]
/approve

@simo5 LGTM if you are happy.

**Comment by php-coder** [comment]
/retest

PTAL @mfojtik

**Comment by mfojtik** [comment]
@dobbymoodge question: what happens when somebody is removed from the organization? do we have process to remove that users from all OWNERS files? (I guess it is not security problem, because they will be removed from the org, but I guess we need some "pruning" ;-)

/lgtm

(merging with green button as this is not overlapping with anything and it is simple OWNERS change)

**Comment by kargakis** [comment]
testing

/cherrypick release-3.7

**Comment by kargakis** [comment]
@mfojtik you can follow https://github.com/kubernetes/test-infra/issues/5175 for what you are asking

**Pull request merged**
