### PR TITLE
Move master config ghosts to /etc/origin/master/

### PR DESCRIPTION
**Pull request by ashcrow**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1469034

### CODE REVIEW

**Comment by sdodson** [comment]
Not calling this a blocker, we'll merge when master opens again.

**Comment by sdodson** [comment]
[merge]

**Comment by ashcrow** [comment]
Rebasing again.

**Comment by ashcrow** [comment]
@openshift-bot 🐝 😶

**Pull request merged**
