### PR TITLE
f5 poolname fix

### PR DESCRIPTION
**Pull request by rajatchopra**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1395153

### CODE REVIEW

**Comment by rajatchopra** [comment]
@ramr @Miciah 
cc @knobunc @openshift/networking

**Comment by rajatchopra** [comment]
[test]

**Comment by knobunc** [comment]
[test]

**Comment by ramr** [comment]
LGTM

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
