### PR TITLE
Force uri.js to reinstall

### PR DESCRIPTION
**Pull request by liggitt**
tmp workaround for #6651 to remove the broken uri.js dependency

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@jwforres :-/

**Comment by jwforres** [comment]
LGTM for temporary patch

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8541/ failed with https://github.com/openshift/origin/issues/6259
```
FAILURE after 59.189s: hack/../test/cmd/newapp.sh:149: executing 'oc get imagestreamtags installable:token' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
```
[test]

**Comment by liggitt** [comment]
not needed, fixed in https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3143/

**Pull request closed without merging**
