### PR TITLE
new-app: Add ability to specify a context directory

### LINKED ISSUE #2052: new-app doesn't support pointing at git subfolder
There does not appear to be a way to tell new app "use the /foo/bar/baz subfolder of the repo I am pointing at to build this project"

### PR DESCRIPTION
**Pull request by kargakis**
sample run: http://pastebin.com/GceNW87k

Doesn't break any existing new-app functionality...

Closes #2052 and #1877

@smarterclayton ptal

### CODE REVIEW

**Comment by smarterclayton** [comment]
We really don't want to be messing with urls like this.  Fragments are safe because they aren't sent to the server.  We can just take a single context-dir argument that applies to all passed source repositories for now.

**Comment by smarterclayton** [comment]
Someone could have a Git repo exposed with URL parameters.

**Comment by kargakis** [comment]
@smarterclayton I've reworked this to use a `--context-dir` flag though I've added the ability of specifying multiple context directories. PTAL

**Comment by smarterclayton** [comment]
Add a simple test case in the new-app test cases please (units)

**Comment by kargakis** [comment]
@smarterclayton made `--context-dir` a signle string flag (assigns the directory to the first repository) and added a test for this

**Comment by kargakis** [comment]
@smarterclayton anything else for this?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
