### PR TITLE
This commit implements birthcry event for openshift proxy.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes bug 1270474
Link is here: https://bugzilla.redhat.com/show_bug.cgi?id=1270474

### CODE REVIEW

**Comment by pweil-** [comment]
I believe that this may be resolved in the rebase by the use of `NewProxyServerDefault` which provides a recorder.  Will double check after it lands

**Comment by liggitt** [comment]
nope, `openshift start node` doesn't use NewProxyServerDefault

**Comment by pweil-** [comment]
> nope, openshift start node doesn't use NewProxyServerDefault

I see, ProxyServer vs the embedded Proxier.  I have no objections then.

cc @smarterclayton

**Comment by aveshagarwal** [comment]
Rebased.

**Comment by smarterclayton** [comment]
LGTM [merge], thanks

**Pull request merged**
