### PR TITLE
lower log level of missing tag for image message

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/2915

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal.

**Comment by smarterclayton** [comment]
Does the UI show this tag as missing when you go look at the things in it?  Do our describe helpers do that?  If not, we should open an issue so that in all the UIs it's obvious which tags are missing.

**Comment by smarterclayton** [comment]
status does it - but may not be optimal

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
