### PR TITLE
Bug 1907938: Nodes goes into NotReady state (VMware)

### PR DESCRIPTION
**Pull request by p0lyn0mial**
we will carry a patch that allows the clients (Kubelet, KCM, etc.) to detect broken connections to the api server more quickly than the default TCP timeout of 15 minutes.

Note: this patch will be dropped in future releases once http2/ping is introduced.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by p0lyn0mial** [comment]
/hold

I need to regenerate the dependencies, `verify` keeps failing.

**Comment by p0lyn0mial** [comment]
> I need to regenerate the dependencies, verify keeps failing.

I had to change the commit msg only.

/hold cancel
/lgtm

**Comment by markmc** [comment]
(patch) affects real-world users, already released on 4.6

**Comment by markmc** [comment]
> > I need to regenerate the dependencies, verify keeps failing.
> 
> I had to change the commit msg only.
> 
> /hold cancel
> /lgtm

Ok, I'll add lgtm back

/lgtm

**Pull request merged**
