### PR TITLE
catalog: add RBAC rules for namespaced brokers

### PR DESCRIPTION
**Pull request by jpeeler**
@eriknelson @jmrodri @jboyd01

### CODE REVIEW

**Comment by eriknelson** [comment]
Those look correct to me.

**Comment by jpeeler** [comment]
@pmorie LGTM request
Maybe Jay should be added to the owners file?

**Comment by jpeeler** [comment]
@bparees I think Paul may be out, can you approve this?

**Comment by jpeeler** [comment]
I think this is failing due to flake #20157, but I can't find the logs to be entirely sure.

**Pull request merged**
