### PR TITLE
bump(github.com/openshift/openshift-sdn) c709df994a5bbecfa80fae62c201

### PR DESCRIPTION
**Pull request by pravisankar**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1323279 : https://github.com/openshift/openshift-sdn/pull/293 
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1320959 : https://github.com/openshift/openshift-sdn/pull/302
Make SDN watch resources more resilient: https://github.com/openshift/openshift-sdn/pull/289
Refer SDN plugin names and annotations by constants: https://github.com/openshift/openshift-sdn/pull/301

### CODE REVIEW

**Comment by pravisankar** [comment]
[test]

**Comment by pravisankar** [comment]
@openshift/networking please review and merge

**Comment by knobunc** [comment]
LGTM

**Comment by dcbw** [comment]
LGTM

**Comment by dcbw** [comment]
[merge]

**Comment by pravisankar** [comment]
Merge failure not related to this pr:
```
go tool pprof: signal: broken pipe
/data/src/github.com/openshift/origin/hack/lib/log.sh: line 30:  5729 Terminated              sar -A -o "${binary_logfile}" 1 86400 > /dev/null 2> "${stderr_logfile}"
make[1]: *** [test-assets] Error 141
...
[BFA] Scanning build for known causes...
....[BFA] Found failure cause(s):
[BFA] UI bindata.go conflict
[BFA] Done. 4s
```

**Comment by liggitt** [comment]
known issue, fixed in https://github.com/openshift/origin/pull/8725

**Comment by pravisankar** [comment]
[merge]

**Pull request merged**
