### PR TITLE
add log arguments

### PR DESCRIPTION
**Pull request by xgwang-zte**
miss one log argument

### CODE REVIEW

**Comment by xgwang-zte** [comment]
@knobunc @pweil-

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
flake https://github.com/openshift/origin/issues/10773

re[test]

**Comment by knobunc** [comment]
@pweil- thanks.  I was just trying to find the error :-)

**Comment by knobunc** [comment]
re-[test] flake was #10773

**Comment by pweil-** [comment]
[merge]

**Pull request merged**
