### PR TITLE
Bug 1786409: Merge pull request #23352 from jianzhangbjz/service-catalog

### PR DESCRIPTION
**Pull request by jianzhangbjz**
check ServiceCatalog basic usages in OCP 4.1.

### CODE REVIEW

**Comment by eparis** [comment]
What are we doing here? just updating some tests in 4.1?  why?

**Comment by jianzhangbjz** [comment]
@eparis In OCP 4.3 or 4.4, Service Catalog will throw alerts once it is installed. Other tests will fail on those alerts. So we remove these tests from the master branch(see #24323 #24315). But, we should test it in released 4.1.z, 4.2.z.

**Pull request closed without merging**
