### PR TITLE
[WIP] - Show service ports table in UI overview

### LINKED ISSUE #3662: Improve presentation of routing for services on overview page
The message is confusing. See  https://github.com/openshift/origin/issues/3610#issuecomment-119378462

### PR DESCRIPTION
**Pull request by spadgett**
Add a ports table for services displaying

   node port -> service port -> container port.

openshift_web_console

openshift_web_console

Fixes #3662

### CODE REVIEW

**Comment by spadgett** [comment]
@liggitt still working on this. The table doesn't look good without the node port column at medium or larger screen widths. I haven't tried making the table expand the full width with no padding, although I look the way it looks. I can do that, but currently the tile adds the padding.

There can be multiple load balanced IPs, so I couldn't put that in the node port column like service port.

@ajacobs21e let me know on expanding / collapsing the tile. Thanks!

**Comment by spadgett** [comment]
Need to add the load balanced IPs at least to the object describer.

**Comment by spadgett** [comment]
Waiting for https://trello.com/c/99sOcvsh

**Comment by spadgett** [comment]
@jwforres @liggitt I'm not sure where this would fit into a simplified overview design. I suggest we just add the table to the browse services page.

**Comment by jwforres** [comment]
let's do that for now, i plan to start implementing the new overview page later this week so we can see how things fit in then

**Comment by spadgett** [comment]
Closing for now. I'll submit a separate pull to add the table to browse services.

**Pull request closed without merging**
