### PR TITLE
remove kubectl from openshift (but not oc)

### PR DESCRIPTION
**Pull request by deads2k**
alternative to https://github.com/openshift/origin/pull/17264

This makes kubectl behave like kubectl even when it's a renamed oc.

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov I'm trying to stop renaming `openshift` to `kubectl`, but I'm trying to keep the code that allows `oc` when called `kubectl` running `kubectl`.  I can't figure out how all those bits are wired in the hack scripts.  Can I get a little help?

**Comment by stevekuznetsov** [comment]
@deads2k I totally didn't see your comment about the scripts until now - sorry! Let's sync tomorrow if you still need help.

**Comment by juanvallejo** [comment]
@deads2k this lgtm

**Pull request merged**
