### PR TITLE
add entrypoint for extended test

### PR DESCRIPTION
**Pull request by deads2k**
adds `hack/test-extended.sh [comma,separated,packages]`.

@ironcladlou @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@pmorie

**Comment by jhadvig** [comment]
@deads2k thanks for this. Saw that the change for the `test-cmd.sh` was reveerted due to the sudo issue. Will try to take a look on that and refact it.

**Comment by deads2k** [comment]
> @deads2k thanks for this. Saw that the change for the test-cmd.sh was reveerted due to the sudo issue. Will try to take a look on that and refact it.

The `set +e` might fix it.

**Pull request merged**
