### PR TITLE
made edge language less ambiguous

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
$ for package in $(find pkg/ -type d -path '*graph'); do grep -Enr '(head|tail)' "${package}"; done
pkg/build/graph/analysis/bc.go:275:	return false, dockerImageReference.ID, "an error occurred importing the image with hexadecimal ID %s into the image stream %s; inspect the images stream annotations for details"
pkg/api/kubegraph/edges.go:15:	// ExposedThroughServiceEdgeKind goes from a PodTemplateSpec or a Pod to Service.  Thehead should make the service's selector.
pkg/api/graph/test/bare-rc.yaml:10:      openshift.io/encoded-deployment-config: '{"kind":"DeploymentConfig","apiVersion":"v1beta1","metadata":{"name":"database","namespace":"test","selfLink":"/osapi/v1beta1/watch/deploymentConfigs/database","uid":"4725b5d3-dcdc-11e4-968a-080027c5bfa9","resourceVersion":"271","creationTimestamp":"2015-04-07T04:12:17Z","labels":{"template":"application-template-stibuild"}},"triggers":[{"type":"ConfigChange"}],"template":{"strategy":{"type":"Recreate"},"controllerTemplate":{"replicas":1,"replicaSelector":{"name":"database"},"podTemplate":{"desiredState":{"manifest":{"version":"v1beta2","id":"","volumes":null,"containers":[{"name":"ruby-helloworld-database","image":"centos/mysql-56-centos7","ports":[{"containerPort":3306,"protocol":"TCP"}],"env":[{"name":"MYSQL_USER","key":"MYSQL_USER","value":"user1CY"},{"name":"MYSQL_PASSWORD","key":"MYSQL_PASSWORD","value":"FfyXmsGG"},{"name":"MYSQL_DATABASE","key":"MYSQL_DATABASE","value":"root"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"PullIfNotPresent","capabilities":{}}],"restartPolicy":{"always":{}},"dnsPolicy":"ClusterFirst"}},"labels":{"name":"database","template":"application-template-stibuild"}}}},"latestVersion":1,"details":{"causes":[{"type":"ConfigChange"}]}}'
```

@deads2k I think this covers all the references.

**Comment by stevekuznetsov** [comment]
@deads2k anything left for this?

**Comment by deads2k** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
Looks like a flake on `e2e`:
```
!!! Error in hack/../hack/../test/end-to-end/../../hack/util.sh:282
	'return 1' exited with status 1
Call stack:
	1: hack/../hack/../test/end-to-end/../../hack/util.sh:282 os::build:wait_for_start(...)
	2: hack/../hack/../test/end-to-end/core.sh:216 main(...)
Exiting with status 1
```

**Pull request merged**
