### PR TITLE
use correct fixture path

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[testonlyextended][extended:core(without output image)]

**Comment by bparees** [comment]
@PI-Victor fyi.  not sure this test would have ever worked?

**Comment by PI-Victor** [comment]
@bparees i remember testing this over and over, didn't rebase locally today so i can try to see if they work

**Comment by bparees** [comment]
well it was failing because of the path issue locating the fixtures.  perhaps something changed in the relative directory structure since you delivered them?  anyway just a heads up for future tests you write.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
