### PR TITLE
jenkins: use port 3306 for mariadb

### PR DESCRIPTION
**Pull request by yselkowitz**
Apparently this slipped through the testing of https://github.com/openshift/origin/pull/26072﻿

Test failure seen in https://github.com/openshift/cluster-samples-operator/pull/379

/cc @gabemontero @akram

### CODE REVIEW

**Comment by gabemontero** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26268/pull-ci-openshift-origin-master-e2e-aws-jenkins/1408420415662985216 is the validation we need @yselkowitz and matches the test we ran in the samples operator PR

**Comment by gabemontero** [comment]
I'll revisit the error in the samples operator run here while we are running e2e-aws-jenkins .... don't remember the specifics of the test offhand and how the test jenkins pipelines are referenced

**Comment by gabemontero** [comment]
OK yeah now seeing what github.com/openshift/origin/test/extended/builds/pipeline_jenkins_e2e.go:560 is complaining about and that this test does  new-app directly on the bluegreen pipeline in examples, your change here @yselkowitz seems valid

/lgtm
/approve

though since you had to change bindata I suspect we'll need more approvals than just me

**Comment by gabemontero** [comment]
To reiterate what I mentioned in the samples PR, in all the non-sample non-build firefighting we had to do in https://github.com/openshift/origin/pull/26072 we forgot to run e2e-aws-jenkins

**Comment by gabemontero** [comment]
I'll look at openshift/release and see about forcing a trigger of e2e-aws-jenkins if the example/jenkins files are changed, as well as test/extended/builds/pipeline_*

**Comment by gabemontero** [comment]
@waveywaves @jkhelil FYI

**Comment by gabemontero** [comment]
I'm sure you'll recognize the e2e-gcp failure @yselkowitz

**Comment by yselkowitz** [comment]
Oh [all to well](https://github.com/openshift/origin/pull/26264)...

**Comment by gabemontero** [comment]
we got the same failure 

/hold

I have to run to an appointment, but will revisit after lunch

**Comment by yselkowitz** [comment]
looks like timeouts this time, let's try again:
/test e2e-aws-jenkins

**Comment by yselkowitz** [comment]
e2e-metal-ipi-ovn-ipv6 failure is https://bugzilla.redhat.com/show_bug.cgi?id=1975865

**Comment by gabemontero** [comment]
> looks like timeouts this time, let's try again:
> /test e2e-aws-jenkins

ok fingers crossed

in the interim I'm going to check out your branch and try it on my dev cluster

**Comment by yselkowitz** [comment]
> e2e-metal-ipi-ovn-ipv6 failure is https://bugzilla.redhat.com/show_bug.cgi?id=1975865

The "fix" for which should be https://github.com/openshift/origin/pull/26266

**Comment by gabemontero** [comment]
> > looks like timeouts this time, let's try again:
> > /test e2e-aws-jenkins
> 
> ok fingers crossed
> 
> in the interim I'm going to check out your branch and try it on my dev cluster

yeah it failed for me running locally in the same spot

I'm going to start diagnosing my local runs here, possibly adding some more debug and/or more test fixes if in fact they are needed

**Comment by gabemontero** [comment]
Yeah we need another change @yselkowitz .... the new-app output shows this route getting created:

`    route.route.openshift.io "nodejs-mariadb-example" created
`

But the test fails with trying to find

```
STEP: verifying that the main route has been switched to green
Jun 25 13:19:35.133: INFO: Running 'oc --namespace=e2e-test-jenkins-pipeline-qttkn --kubeconfig=/tmp/configfile460557126 get route nodejs-postgresql-example -o jsonpath={ .spec.to.name }'
Jun 25 13:19:35.674: INFO: Error running /usr/local/bin/oc --namespace=e2e-test-jenkins-pipeline-qttkn --kubeconfig=/tmp/configfile460557126 get route nodejs-postgresql-example -o jsonpath={ .spec.to.name }:
StdOut>506:43
Error from server (NotFound): routes.route.openshift.io "nodejs-postgresql-example" not found
StdErr>
Error from server (NotFound): routes.route.openshift.io "nodejs-postgresql-example" not found506:43

```

lines 559 and 562 minimally need to be changed

**Comment by gabemontero** [comment]
actually there are quite a few `nodejs-postgresql` refs that I think will need to be changed

though postgreql is not in the same boat as mongodb, right ?

**Comment by yselkowitz** [comment]
No, there is a nodejs-postgresql-example in templates which is replacing most uses of nodejs-mongodb-example, but I thought the jenkins example was completely unrelated to that.  Let me take a look too.

**Comment by gabemontero** [comment]
> No, there is a nodejs-postgresql-example in templates which is replacing most uses of nodejs-mongodb-example, but I thought the jenkins example was completely unrelated to that. Let me take a look too.

I'm running a test locally with all the nodejs-postgresql refs changed in that  test ...will report back when it is done

**Comment by gabemontero** [comment]
> > No, there is a nodejs-postgresql-example in templates which is replacing most uses of nodejs-mongodb-example, but I thought the jenkins example was completely unrelated to that. Let me take a look too.
> 
> I'm running a test locally with all the nodejs-postgresql refs changed in that test ...will report back when it is done

My changes are basically what you just pushed @yselkowitz :-)

**Comment by gabemontero** [comment]
/hold cancel

I'll re-lgtm once we get some positive results

**Comment by gabemontero** [comment]
Sorry @yselkowitz I nuked my prior check out of this PR, re checked out, and ran the test, but it still fails.

I've started diagnosis and will report back when I have some details.

**Comment by gabemontero** [comment]
```
STEP: starting the pipeline build and waiting for it to complete
Jun 25 14:01:48.993: INFO: Running 'oc --namespace=e2e-test-jenkins-pipeline-znqx9 --kubeconfig=/tmp/configfile882208873 start-build nodejs-sample-pipeline -o=name'
Jun 25 14:01:49.528: INFO: 

start-build output with args [nodejs-sample-pipeline -o=name]:
Error><nil>
StdOut>
build.build.openshift.io/nodejs-sample-pipeline-1
StdErr>



Jun 25 14:01:49.529: INFO: Waiting for nodejs-sample-pipeline-1 to complete

Jun 25 14:02:15.906: INFO: WaitForABuild returning with error: The build "nodejs-sample-pipeline-1" status is "Failed"
Jun 25 14:02:15.906: INFO: Done waiting for nodejs-sample-pipeline-1: util.BuildResult{BuildPath:"build.build.openshift.io/nodejs-sample-pipeline-1", BuildName:"nodejs-sample-pipeline-1", StartBuildStdErr:"", StartBuildStdOut:"build.build.openshift.io/nodejs-sample-pipeline-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*v1.Build)(0xc0016a2000), BuildAttempt:true, BuildSuccess:false, BuildFailure:true, BuildCancelled:false, BuildTimeout:false, LogDumper:(util.LogDumperFunc)(nil), Oc:(*util.CLI)(0xc0017f6ea0)}
 with error: The build "nodejs-sample-pipeline-1" status is "Failed"
```

That is a pipeline strategy build.

So it tries a new-app 

```
          def templatePath = 'nodejs-mariadb-example'

....

                                  openshift.withProject() {
                                      // create a new application from the templatePath
                                      openshift.newApp(templatePath)
                                  }
```


And it fails with 

```
ERROR: new-app returned an error;
{err=W0625 18:02:13.274577     226 dockerimagelookup.go:300] container image remote registry lookup failed: you may not have access to the container image "docker.io/library/nodejs-mariadb-example:latest"
error:  local file access failed with: stat nodejs-mariadb-example: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "nodejs-mariadb-example"

Argument 'nodejs-mariadb-example' was classified as an image, image~source, or loaded template reference.

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
, verb=new-app, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=e2e-test-jenkins-pipeline-znqx9 --token=XXXXX new-app nodejs-mariadb-example -o=json , out=, status=1}

```

That is because there is no `nodejs-mariadb-example` template installed by samples operator.

Only

nodejs-mongodb-example                          An example Node.js application with a MongoDB database. For more information...    18 (4 blank)      8
nodejs-postgresql-example                       An example Node.js application with a PostgreSQL database. For more informati...   18 (4 blank)      8
nodejs-postgresql-persistent                    An example Node.js application with a PostgreSQL database. For more informati...   19 (4 blank)      9


I really think the path of least resistance is change back to nodejs-postgresql-example for this jenkins test.

**Comment by gabemontero** [comment]
Or I should say switch from mongodb to postgresql for this one vs. mongodb to mariadb

**Comment by yselkowitz** [comment]
> I really think the path of least resistance is change back to nodejs-postgresql-example for this jenkins test.

It's not really "back", because it never was postgresql.  There still seems to be some conflation here between the template from the sample and the pipeline definition of the same name, but obviously I haven't found where that line is exactly.

This is going to take more than a find-and-replace, so
/hold

**Comment by gabemontero** [comment]
> > I really think the path of least resistance is change back to nodejs-postgresql-example for this jenkins test.
> 
> It's not really "back", because it never was postgresql. There still seems to be some conflation here between the template from the sample and the pipeline definition of the same name, but obviously I haven't found where that line is exactly.

yeah not "back" ... I tried to correct myself with https://github.com/openshift/origin/pull/26268#issuecomment-868751376
> 
> This is going to take more than a find-and-replace, so
> /hold

I'm as well working in my local copy at trying to move to nodejs-postrgresql-example from the spots where you tried to move off of nodejs-mongodb-example to the non-existent nodejs-mariadb-example 

When I have something that works locally I'll report back.

**Comment by yselkowitz** [comment]
@gabemontero how is it possible that this is failing in **4.8**?  The big origin PR was only merged into master after 4.8 branched.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/829/pull-ci-openshift-kubernetes-release-4.8-e2e-aws-jenkins/1408481494824914944

**Comment by gabemontero** [comment]
> @gabemontero how is it possible that this is failing in **4.8**? The big origin PR was only merged into master after 4.8 branched.
> 
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/829/pull-ci-openshift-kubernetes-release-4.8-e2e-aws-jenkins/1408481494824914944

no idea at first blush .... but sorry, can only multi task so much (got non jenkins threads I'm having to work today too) :-/  .... I'll see about that once I'm done with this guy, but it may not be until Monday ... or maybe @akram @waveywaves @jkhelil can help you early Monday their time in the interim 

wrt to these changes, I have the samplespipeline.yaml ported to use postgresql and working locally for me, where I basically merged that template with the official nodejs-postgresql-example template

I'm now diving into the bluegreen.yaml and attempting something similar

**Comment by yselkowitz** [comment]
> @gabemontero how is it possible that this is failing in **4.8**? The big origin PR was only merged into master after 4.8 branched.

Sigh, I figured it out.  This is related to the Jenkins tests which download their templates directly from github instead of extracting from the bindata.  Not only did that make it impossible to test their changes before they were merged, but now the changes from master are being pulled into stable branches, which was never the intention.  This will require PRs for the stable branches to not use master.  I'll start with 4.8, and we'll need to go from there.  What fun.

**Comment by gabemontero** [comment]
> > @gabemontero how is it possible that this is failing in **4.8**? The big origin PR was only merged into master after 4.8 branched.
> 
> Sigh, I figured it out. This is related to the Jenkins tests which download their templates directly from github instead of extracting from the bindata. Not only did that make it impossible to test their changes before they were merged, but now the changes from master are being pulled into stable branches, which was never the intention. This will require PRs for the stable branches to not use master. I'll start with 4.8, and we'll need to go from there. What fun.

was this the test we commented out in your last PR ?  where I'm going to move it to the jenkins client plugin repo?

**Comment by gabemontero** [comment]
> > > @gabemontero how is it possible that this is failing in **4.8**? The big origin PR was only merged into master after 4.8 branched.
> > 
> > 
> > Sigh, I figured it out. This is related to the Jenkins tests which download their templates directly from github instead of extracting from the bindata. Not only did that make it impossible to test their changes before they were merged, but now the changes from master are being pulled into stable branches, which was never the intention. This will require PRs for the stable branches to not use master. I'll start with 4.8, and we'll need to go from there. What fun.
> 
> was this the test we commented out in your last PR ? where I'm going to move it to the jenkins client plugin repo?

or maybe the rhel only version of that based at a quick glance of your new PR?

**Comment by gabemontero** [comment]
no wait that was in the actual Jenkinsfile, right?

**Comment by gabemontero** [comment]
@yselkowitz I have all 4 jenkins tests passing for me now locally where I've moved what was originally mongodb based, which you then moved to mariadb, but is now postgresql based.

I'll have a PR up in a moment, and IMO we close this PR.

**Comment by gabemontero** [comment]
OK ... I now see you made similar changes to #26274 @yselkowitz and had a green e2e..... sorry, with all the juggling this afternoon, did not catch that in time

thanks for playing along :-)

**Pull request closed without merging**
