### PR TITLE
Fix for tito 0.6.0

### LINKED ISSUE #3570: Tito tooling is not compatible with tito v0.6.0
Our tito custom builder relied on calling test-setup-specfile.pl which was removed from tito in v0.6.0. Need to update things to address this.

Feel free to assign this to me.

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #3570

### CODE REVIEW

**Comment by sdodson** [comment]
@brenton PTAL, in short tito version 0.6 moved from using a perl script to munge the spec file to a built in function.

**Comment by brenton** [comment]
makes sense. [merge]

**Comment by sdodson** [comment]
[test] there's no chance the failure is related to this change

**Comment by brenton** [comment]
[merge]

**Pull request merged**
