### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by pweil-**
@deads2k @pmorie @liggitt @smarterclayton 

I'm at the point of refactoring and I need some assistance.  I have all of the changes in for the new storage interface for our api objects and a few other items that have changed.  The current output of a compile is below.  Need some guidance or contributions for where to get the codec in the current setup and the correct way to pull back in the master config for v1beta3 (the types are already in).  

:sos: 

```
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/pkg/cmd/server/kubernetes
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/kubernetes/master.go:48: c.Master.EnableV1Beta3 undefined (type *master.Config has no field or method EnableV1Beta3)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/kubernetes/master_config.go:137: unknown master.Config field 'EnableV1Beta3' in struct literal
# github.com/openshift/origin/pkg/cmd/server/origin
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:416: c.EtcdHelper.Codec undefined (type storage.Interface has no field or method Codec)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master.go:417: c.EtcdHelper.Codec undefined (type storage.Interface has no field or method Codec)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/run_components.go:158: c.EtcdHelper.Client undefined (type storage.Interface has no field or method Client)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/run_components.go:253: c.EtcdHelper.Codec undefined (type storage.Interface has no field or method Codec)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/run_components.go:280: c.EtcdHelper.Codec undefined (type storage.Interface has no field or method Codec)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/run_components.go:292: c.EtcdHelper.Codec undefined (type storage.Interface has no field or method Codec)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/swagger.go:25: dec.Info undefined (type swagger.ApiDeclaration has no field or method Info)
_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/swagger.go:28: dec.Info undefined (type swagger.ApiDeclaration has no field or method Info)
```

### CODE REVIEW

**Comment by liggitt** [comment]
You should be able to drop these:
UPSTREAM: <carry>: Ensure no namespace on create/update root scope types … 	1a74518
UPSTREAM: revert 6cc0c51: Ensure no namespace on create/update root s… … 	dd69971

**Comment by liggitt** [comment]
You should be able to squash these into a single commit:
UPSTREAM: 9009: Retry service account update when adding token reference 	1d968b7
UPSTREAM: revert da0a3d: 9009: Retry service account update when addi… … 	64c217b
UPSTREAM: 9009: Retry service account update when adding token reference 	a2863c7

**Comment by deads2k** [comment]
I think you should submit a patch upstream to expose the `Codec` on the `storage.Interface`.  It was probably an oversight.

**Comment by deads2k** [comment]
We carried patches on swagger.  You should see if the level really bumped or no in godeps.json and decide whether to simply remove those files from your bump commit (likely) or reapply patches.

**Comment by liggitt** [comment]
I'm pretty sure we were carring a patch for github.com/google/cadvisor as well... @smarterclayton do you know if that got picked up upstream?

**Comment by pweil-** [comment]
I have squashed, fixed up, and reorganized the commits.  This is now compiling.  I will work on the test refactoring now.  

Still TODO:

1.  The v1beta3 types are in but the api version enablement is not complete
2.  Do I need to reset the cadvisor dep (will look at the diffs)

**Comment by jimmidyson** [comment]
@pweil- Can you include GoogleCloudPlatform/kubernetes#11562 too please?

**Comment by liggitt** [comment]
@jimmidyson it looks like the rebase commit is from two days ago... https://github.com/GoogleCloudPlatform/kubernetes/pull/11562 merged 13 days ago... is it not already included?

**Comment by deads2k** [comment]
> @pweil- Can you include GoogleCloudPlatform/kubernetes#11562 too please?

Having been through this several times, it's really difficult to start picking extra patches while you're trying to deconflict the list what is in/out/carry/revert/transitive during the rebase.  I'd suggest that @pweil- create a followup issue to double check things like this.

**Comment by jimmidyson** [comment]
@liggitt Not from what I can see, no. Checked @pweil- branch but can't see the change. Looks like github is doing some weird stuff though so might just be the github interface not working properly...

@deads2k Fair enough.

**Comment by liggitt** [comment]
@jimmidyson it is included. github won't show you the whole diff in html mode because it's enormous... https://github.com/pweil-/origin/commit/8ef7c79a2fd30385a41e91e259729213ebc938e5.diff shows the change you're interested in

**Comment by jimmidyson** [comment]
@liggitt Yeah checked PR branch out locally & can see the change. Thanks. As you were ;)

**Comment by smarterclayton** [comment]
cAdvisor should have been picked up upstream, although I haven't checked.

**Comment by smarterclayton** [comment]
Agree Codec on Interface was an oversight, although I'm not totally sure we *need* it.

**Comment by pweil-** [comment]
working unit tests, running through cmd/int next.

**Comment by pweil-** [comment]
Well, I know what my issue is, just not how to solve it or what broke.  It looks like I'm running into errors for SARs that apparently can be queried at both the root scope and namespace scoped.  This gist demonstrates the error I'm receiving when  cluster scoped SAR is requested but it works for namespace scoped SARs  https://gist.github.com/pweil-/500838cabfd7a9caa07e

**Comment by pweil-** [comment]
Of course as soon as I enter that comment I find that the upstream api installer changes are causing it https://github.com/pweil-/origin/commit/ce9f34fe5d1349772ef74ea4fc4cd0dbeb8d844d#diff-1b1b1aa202a43ff4509abc0b0a82ed78

**Comment by smarterclayton** [comment]
Upstream removed the ability to call SARS on root scope.  David's change
should fix it, or we can restore the old fix temporarily

On Aug 5, 2015, at 6:39 PM, Paul Weil <notifications@github.com> wrote:

Well, I know what my issue is, just not how to solve it or what broke. It
looks like I'm running into errors for SARs that apparently can be queried
at both the root scope and namespace scoped. This gist demonstrates the
error I'm receiving when cluster scoped SAR is requested but it works for
namespace scoped SARs https://gist.github.com/pweil-/500838cabfd7a9caa07e

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4003#issuecomment-128172043>.

**Comment by pweil-** [comment]
> David's change should fix it, or we can restore the old fix temporarily

It was a one liner to add it back in once I found it so I have that done and test-cmd works.  Running through int now.

**Comment by smarterclayton** [comment]
Be sure to mention in the other issue to revert our patch

On Aug 5, 2015, at 7:17 PM, Paul Weil <notifications@github.com> wrote:

David's change should fix it, or we can restore the old fix temporarily

It was a one liner to add it back in once I found it so I have that done
and test-cmd works. Running through int now.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4003#issuecomment-128181597>.

**Comment by pmorie** [comment]
My god it's full of SARS

**Comment by pweil-** [comment]
assets updated, working test-go.sh, test-cmd.sh, test-integration.sh

**Comment by pmorie** [comment]
Build failure when running the kube unit tests:

```
$ TEST_KUBE=1 hack/test-go.sh 
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/jsonpath/jsonpath.go:26:2: cannot find package "github
.com/GoogleCloudPlatform/kubernetes/third_party/golang/template" in any of:
        /usr/lib/golang/src/github.com/GoogleCloudPlatform/kubernetes/third_party/golang/template (from $GOROOT)
        /home/pmorie/code/origin/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/third_party/golang/template (from $GOPATH)
        /home/pmorie/code/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/third_party/golang/template
```

**Comment by pmorie** [comment]
Travis failed for the same reason my local build did.  The origin unit tests did work, though.

**Comment by pmorie** [comment]
@pweil- Have you run test-end-to-end.sh yet?

**Comment by pmorie** [comment]
I got some errors running test-integration locally, but it might have been PEBCAK

**Comment by pweil-** [comment]
hrm, I'm not able to reproduce this locally for some reason

```
ok  	github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api	0.513s
ok  	github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1	0.008s
```
I'll ping you when you get online

**Comment by pweil-** [comment]
also, fwiw, those packages do not exist in master: https://github.com/openshift/origin/tree/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/third_party/golang

**Comment by pweil-** [comment]
@pmorie - it looks like one of the Kube tests is failing in travis but didn't fail for me locally.  Can you repull this and see if you get the same thing?

**Comment by pweil-** [comment]
Successful hack/test-end-to-end.sh in vagrant.  Still trying to figure/reproduce out why the kube event test fails in travis

**Comment by pmorie** [comment]
I get a clean unit test run locally, but have some failures in integration.  I'm going to run an end-to-end and then see if I get the same problem in master with the integration tests.

**Comment by deads2k** [comment]
[test]

**Comment by pmorie** [comment]
I got a clean E2E run locally.  @deads2k are the new extended tests enabled in Jenkins?

**Comment by pweil-** [comment]
Current status: travis is failing on the verifying the swagger spec.  Locally I can clean, make, generate, and verify with no problem.

**Comment by pmorie** [comment]
@pweil- on it

**Comment by pmorie** [comment]
Clean unit tests so far

**Comment by pmorie** [comment]
More integration errors: https://gist.github.com/pmorie/f676c6ed59e176129c81

**Comment by pmorie** [comment]
Wth.  This thread looked weird in gmail.  I had problems with the swagger
spec earlier as well.

**Comment by pweil-** [comment]
> I had problems with the swagger spec earlier as well.

I got this fixed up last night.  The tests seem to be failing in different ways in travis which is what I could use some extra eyes on @pmorie.   For some reason I'm unable to reproduce these failures.  I thought maybe it was some randomization in the tests but that wasn't obvious.  I still can't reproduce your int failure either.  Retried this morning:

```
ok      TestConcurrentBuildControllers
ok      TestConcurrentBuildImageChangeTriggerControllers
ok      TestConcurrentBuildPodControllers
```

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
Some pointers on "interesting refactors" that I'd like extra eyes on:

1.  (anyone) Changing some config items to pointers: https://github.com/pweil-/origin/commit/3c5d7ed22cc170452a398218cd14e749297553c2#diff-6b3f8d88a1a6440b819ca69284def1c8
2.  @deads2k This cherry-pick had lots of conflicts so I pulled it back in manually: https://github.com/pweil-/origin/commit/3fcc0f46284813e3e93b95657ed946d6db2c32cf
3.  (anyone) The etcd client is no longer exposed by the storage implementation so I added it to master config: https://github.com/pweil-/origin/commit/3c5d7ed22cc170452a398218cd14e749297553c2#diff-15f4fc39e330bb36dff2d28d3297e439

**Comment by deads2k** [comment]
The main bump is touching `Godeps/_workspace/src/github.com/jteeuwen/go-bindata/release.go`, but I don't see it in `godeps.json`.  Any chance you accidentally rolled back a patch?

**Comment by deads2k** [comment]
Same question for `Godeps/_workspace/src/github.com/skynetservices/skydns`

**Comment by deads2k** [comment]
Is there a reason to keep the two v1beta3 <carry> patches separate?  The seem closely tied.

**Comment by deads2k** [comment]
squash "UPSTREAM: <carry>: Correct v1 deep_copy_generated.go" and "UPSTREAM: <carry>: Add deprecated fields to migrate 1.0.0 k8s v1 data"

**Comment by deads2k** [comment]
I think we should take a couple followup issues, squash down a couple related "UPSTREAM: <carry>" patches (patch + fix) that belong together, and then merge this.

**Comment by markturansky** [comment]
The recycler stuff looks good, paul.  I'll be sure to test it through it
after the rebase is merged.

**Comment by pmorie** [comment]
@markturansky The time to test is really before the rebase lands in master.

**Comment by markturansky** [comment]
Fair enough.  I'll pull the branch :)

**Comment by pmorie** [comment]
@pweil- The carry patch looks good.

**Comment by pmorie** [comment]
@deads2k @liggitt @pweil- 

> squash "UPSTREAM: : Correct v1 deep_copy_generated.go" and "UPSTREAM: : Add deprecated fields to migrate 1.0.0 k8s v1 data"

Good eye, David.  They can be squashed together -- the deep_copy_generated.go commit is something that was missed in the original upstream patch that I needed in order to get the upstream unit tests working.

**Comment by liggitt** [comment]
I plan to do a final sweep since the last rebase to make sure no UPSTREAM commits got lost... @pweil- you ready for that?

**Comment by pweil-** [comment]
5 minutes.  I'm done all the requested squashing. Rebasing on master, regenerating assets since jenkins complained.

@deads2k - applying the upstream patch for the kubelet config split was rejected.  I pulled in the relevant code since there were only minor changes in the diff against my manual patch.  I'll ping you to re-review that in a moment

**Comment by liggitt** [comment]
hmm... assets shouldn't need rebuilding. make sure you didn't change the go-bindata version we're using

**Comment by pweil-** [comment]
@liggitt it got changed but reverted.  Since I already generated earlier from my screw up I needed to put it back.  Should be good now, the last commit in that tree is you upstream for encoding assets in ASCII.  Checked in and ready for review.

@deads2k - ready for your eyeballs too

**Comment by deads2k** [comment]
re[test]

**Comment by pweil-** [comment]
bump another [test] for a timeout.

based on the previous test's logs I *think* what is happening here is that the kubelet is failing to mount the volumes when running containerized origin and the registry/router pods are not getting created.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3947/artifact/origin/artifacts/e2e/logs/container-origin.log

```
E0807 18:38:41.182099       1 kubelet.go:1190] Unable to mount volumes for pod "router-1-deploy_default": exit status 1; skipping pod
E0807 18:38:41.195744       1 kubelet.go:1190] Unable to mount volumes for pod "docker-registry-1-deploy_default": exit status 1; skipping pod
```

I was able to duplicate this in my local env but don't know the cause yet.  It doesn't happen in non-containerized e2e.

Steps to reproduce:

```
hack/build-release.sh && hack/build-images.sh

sudo docker run --rm -it --name="origin"   --privileged --net=host   -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys:ro -v /var/lib/docker:/var/lib/docker:rw   -v "/tmp/openshift.containerized.volumes":"/tmp/openshift.containerized.volumes":rw   "openshift/origin:latest" start --volume-dir=/tmp/openshift.containerized.volumes --images="openshift/origin-\${component}:${tag}" --loglevel=4

sudo docker exec origin openshift admin registry --create --credentials="./openshift.local.config/master/openshift-registry.kubeconfig" --images="openshift/origin-\${component}:${tag}"
```

**Comment by smarterclayton** [comment]
Did you drop my mount changes?  Possible that's missing in the rebase (what
went in upstream != what we've been testing with).

On Aug 7, 2015, at 5:19 PM, Paul Weil <notifications@github.com> wrote:

bump another [test] for a timeout.

based on the previous test's logs I *think* what is happening here is that
the kubelet is failing to mount the volumes when running containerized
origin and the registry/router pods are not getting created.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3947/artifact/origin/artifacts/e2e/logs/container-origin.log

E0807 18:38:41.182099       1 kubelet.go:1190] Unable to mount volumes
for pod "router-1-deploy_default": exit status 1; skipping pod
E0807 18:38:41.195744       1 kubelet.go:1190] Unable to mount volumes
for pod "docker-registry-1-deploy_default": exit status 1; skipping
pod

I was able to duplicate this in my local env but don't know the cause yet.
It doesn't happen in non-containerized e2e.

Steps to reproduce:

hack/build-release.sh && hack/build-images.sh

sudo docker run --rm -it --name="origin"   --privileged --net=host
-v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys:ro -v
/var/lib/docker:/var/lib/docker:rw   -v
"/tmp/openshift.containerized.volumes":"/tmp/openshift.containerized.volumes":rw
  "openshift/origin:latest" start
--volume-dir=/tmp/openshift.containerized.volumes
--images="openshift/origin-\${component}:${tag}" --loglevel=4

sudo docker exec origin openshift admin registry --create
--credentials="./openshift.local.config/master/openshift-registry.kubeconfig"
--images="openshift/origin-\${component}:${tag}"

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4003#issuecomment-128836171>.

**Comment by pweil-** [comment]
[test] some more

**Comment by pweil-** [comment]
> Did you drop my mount changes?  Possible that's missing in the rebase (what
> went in upstream != what we've been testing with).

Yup.  Thanks for the pointer.  It looked like all those changes were internal but pulling the old version of the nsenter file back in gave me a clean e2e-docker run.

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
@smarterclayton @liggitt @deads2k - lights are now green

**Comment by smarterclayton** [comment]
Open a follow up item for me please

On Aug 9, 2015, at 7:14 PM, Paul Weil <notifications@github.com> wrote:

Did you drop my mount changes? Possible that's missing in the rebase (what
went in upstream != what we've been testing with).

Yup. Thanks for the pointer. It looked like all those changes were internal
but pulling the old version of the nsenter file back in gave me a clean
e2e-docker run.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4003#issuecomment-129260101>.

**Comment by deads2k** [comment]
lgtm

**Comment by deads2k** [comment]
@pweil- Can you confirm that the bindata files didn't actually change?  Squashing "update assets" into "non-interesting refactors" should produce no changes.  Otherwise there will be a concern about potential changes in the bindata tool itself.

**Comment by pweil-** [comment]
@deads2k - diffed against head, no changes. Squashed into the other commit.

**Comment by deads2k** [comment]
[merge]

**Comment by pweil-** [comment]
> Open a follow up item for me please

Created https://github.com/openshift/origin/issues/4076

**Pull request merged**
