### PR TITLE
Sync Service Catalog v.0.0.23

### PR DESCRIPTION
**Pull request by jboyd01**

### CODE REVIEW

**Comment by pmorie** [comment]
Nice job @jboyd01 🏆 💯

**Comment by jboyd01** [comment]
@pmorie all set for review and merge, the origin/unit failure should be ignored (its non-blocking) - more in email to aos-devel from Steve & others.

**Comment by liggitt** [comment]
squash and merge commit should be combined

not sure how we're marking `<carry>` commits for catalog... might be worth prefixing with `catalog:`

looks fine at a quick glance otherwise

**Comment by jboyd01** [comment]
@liggitt I don't think I can squash the squash & merge commits.  These commits are on a subtree:  'cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog'

If I do a "git rebase -i HEAD~4"  it doesn't include the "merge" commit:

pick 9db7f35946 apps: add unit test for deployment config metrics
pick 41fb245c72 Squashed 'cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/' changes from 06b897d198..7011d9e816
pick 0db6a2e4e1 catalog: add RBAC for serviceplans and serviceinstances/reference
pick 0e360c28cb <carry>: Set external plan name for service-catalog walkthrough

my git-fu isn't the strongest, I'm happy to take some guidance/direction here.

**Comment by liggitt** [comment]
ah, didn't realize git did different things for those subtrees
/retest

**Pull request merged**
