### PR TITLE
Revert "Add extended tests for oc image mirror"

### PR DESCRIPTION
**Pull request by eparis**
Reverts openshift/origin#19720

fixes https://github.com/openshift/ose/issues/1269

### CODE REVIEW

**Comment by eparis** [comment]
@legionus

**Comment by smarterclayton** [comment]
Blocks deploy to stg, we’ll have to pick this back up after.

**Comment by eparis** [comment]
I redid the commit so it had 'bump(*)'. Hopefully CI will be happy.

**Pull request merged**
