### PR TITLE
add --read-only opt to oc set volumes

### PR DESCRIPTION
**Pull request by juanvallejo**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594218

cc @soltysh

### CODE REVIEW

**Comment by juanvallejo** [comment]
@soltysh removing hold on this as rebase has landed.

/hold cancel

**Comment by soltysh** [comment]
For some unknown to me reason this hangs constantly on: when creating a project to test `test/cmd/secrets.sh`. I'm cherry-picking this into #20139 and I'll re-run tests and try to merge there. 
/hold

**Comment by juanvallejo** [comment]
Closing. This merged as part of https://github.com/openshift/origin/pull/20139

**Pull request closed without merging**
