### PR TITLE
WIP: Pass STI build container DNS config to STI builder

### PR DESCRIPTION
**Pull request by csrwng**
Fixes issues with name lookups inside the container launched by STI to run assemble scripts.
Depends on https://github.com/openshift/source-to-image/pull/208.

### CODE REVIEW

**Comment by csrwng** [comment]
@mfojtik ptal - will finalize once the prereq PR in STI is merged.
@danmcp fyi - this is the second part of the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1225410

**Comment by mfojtik** [comment]
@csrwng how about other build types?

**Comment by csrwng** [comment]
we don't run containers from other build types... at least not that we control. If you run a separate container in a custom build, it's going to be your responsibility to make sure the proper dns config is set on it.

**Comment by mfojtik** [comment]
@csrwng should we document that somewhere for the custom build? how about docker build and you fetching something during docker build?

**Comment by csrwng** [comment]
hmm, so docker build is going to be a different issue, because the build is running on the node's docker daemon... the daemon needs to be configured with the proper dns. For custom builds, yes we should document.

**Comment by mfojtik** [comment]
@csrwng  https://github.com/GoogleCloudPlatform/kubernetes/blob/bade36c7dd10fdd03b554dd87dbb066b6b1623b4/pkg/kubelet/kubelet.go#L992

**Comment by csrwng** [comment]
Closing in favor of a documentation solution -- each node will need to get its resolv.conf updated to use the openshift master as its first entry.

**Pull request closed without merging**
