### PR TITLE
Wait longer for etcd startup in integration tests

### LINKED ISSUE #5605: test-integration.sh times out starting etcd
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6588/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6587/console

```
ERROR: gave up waiting for http://127.0.0.1:44001/version
```

### PR DESCRIPTION
**Pull request by smarterclayton**
It's possible not to form a quorum in 20s. Try doubling to 40s

Fixes #5605

[test]

### CODE REVIEW

**Comment by liggitt** [comment]
it's a single server... are we expecting a quorum?

**Comment by smarterclayton** [comment]
It's a quorum with itself

**Comment by smarterclayton** [comment]
Now with 100% more printing out wtf is going on

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Did not fix https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6822/console and did not log errors

**Pull request merged**
