### PR TITLE
update extended test to point to correct version tool

### PR DESCRIPTION
**Pull request by stevekuznetsov**
fixes https://github.com/openshift/origin/issues/6553

@bparees @gabemontero

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[testonlyextended][extended:core]

**Comment by bparees** [comment]
lgtm, will wait to see that the extended tests at least run.

**Comment by stevekuznetsov** [comment]
@bparees extended test looks good

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@bparees this might be worth a force-merge

**Pull request merged**
