### PR TITLE
bug 1952473: Dump pod displacement during upgrade

### PR DESCRIPTION
**Pull request by ingvagabund**
/hold

### CODE REVIEW

**Comment by soltysh** [comment]
@ingvagabund this looks good, but how should I read the output (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26045/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1384245042595500032/artifacts/e2e-gcp-upgrade/openshift-e2e-test/artifacts/pod-placement-data.json) are you envisioning providing some visualization similarly to what David did with intervals?

**Comment by ingvagabund** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26045/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1384245042595500032/artifacts/e2e-gcp-upgrade/openshift-e2e-test/artifacts/pod-transitions.txt is more suitable for this. Though, eventually yes, I'd like to provide similar output as David did.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by soltysh** [comment]
@smarterclayton fyi

**Pull request merged**
