### PR TITLE
UPSTREAM: 23793: Make ConfigMap volume readable as non-root

### PR DESCRIPTION
**Pull request by pmorie**
Upstream patch for kubernetes/kubernetes#23793

### CODE REVIEW

**Comment by pmorie** [comment]
[test][extended:core("ConfigMap")]

**Comment by pmorie** [comment]
looks like the test failure was a flake :snowflake: 

[test]

**Comment by pmorie** [comment]
Flaked again.  [test]

**Comment by pmorie** [comment]
[test]

**Comment by liggitt** [comment]
bindata failure fixed in master, re[test]

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@smarterclayton @liggitt help a bro out and tag?

**Comment by liggitt** [comment]
LGTM, [merge]

**Comment by smarterclayton** [comment]
Import flake [merge]

**Comment by pmorie** [comment]
:snowflake: 

[merge]

**Pull request merged**
