### PR TITLE
[3.10] Allow configuration of ResourceGroup in Azure StorageClass

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1596319

Contains these PRs:

* https://github.com/kubernetes/kubernetes/pull/65217
* https://github.com/kubernetes/kubernetes/pull/65516
* https://github.com/kubernetes/kubernetes/pull/65443

@openshift/sig-storage, PTAL

### CODE REVIEW

**Comment by gnufied** [comment]
Is resource group available anywhere in pv/pvc after provisioning? Will it be needed for delete or something else?

**Comment by jsafrane** [comment]
Reading Azure docs, a resource group must be created by admin before setting up the storage class. And it's up to the admin to remove it.

**Comment by jsafrane** [comment]
Closing in favor of https://github.com/openshift/ose/pull/1340

**Comment by smarterclayton** [comment]
@knobunc can you approve?

**Comment by knobunc** [comment]
/lgtm
/approve

Over to you @smarterclayton

**Pull request merged**
