### PR TITLE
Add missing types to Web Console server type map

### LINKED ISSUE #3722: PVC is not created from a template in the web console
If creating an app from a template, an included PVC is not created.

Steps to reproduce (worked for me):

1. Create or clean a project.
2. Create an app from a template (`postgresql-persistent` in my case)
3. See the error message `Error syncing pod, skipping: failed to instantiate volume plugin [...]: persistentvolumeclaims "postgresql" not found`.

Creating the claim manually from the template's JSON instantiates a PVC successfully.

This is on 3.0.0, installed with `openshift-ansible` (tag `3.0.0-4`).

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #3722 

@liggitt PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
Still need to add error handling to prevent runtime errors on unknown types.

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
follow up PR with error handling for unknown types

**Comment by spadgett** [comment]
@liggitt I had the wrong endpoint for one type, which I've fixed. Please take another look. I also added error handling.

**Comment by liggitt** [comment]
Which type was wrong?

**Comment by spadgett** [comment]
`PersistentVolumeClaims`, which I had mapped to `persistentvolumes` ...

**Comment by rassie** [comment]
Any idea when this patch could be available in OSE or how I could build a workaround until it is?

**Comment by liggitt** [comment]
LGTM, [merge]

**Comment by sdodson** [comment]
@rassie ~ 2 weeks for OSE release pending QE and all the normal disclaimers about scheduling. If you need it in OSE before that can you open a support ticket and reference this issue? I can work with support to get you a test build before then.

**Pull request merged**
