### PR TITLE
Updates to the 503 application unavailable page.

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres

**Comment by smarterclayton** [comment]
Screenshot.  Also, how big is this?

**Comment by sg00dwin** [comment]
@smarterclayton, @jwforres 
-rw-r--r--  1 stevegoodwin  staff  64337 Apr  4 14:01 error-page-503.http

Full
full

Mobile
mobile

**Comment by smarterclayton** [comment]
I'd prefer it be more like 4-8k.

**Comment by sg00dwin** [comment]
I'll pull out the 'open sans' bold font-face and see if that bring is under.

**Comment by sg00dwin** [comment]
@smarterclayton Even with embedding only one @font-face it's still larger. Do you want me to drop the 'open sans'?
-rw-r--r--  1 stevegoodwin  staff  30426 Apr  4 14:31 font-only.html
-rw-r--r--  1 stevegoodwin  staff   1740 Apr  4 14:30 markup-only.html

**Comment by smarterclayton** [comment]
Yeah, let's drop the fonts and use whatever is close enough that comes with
the browser.

**Comment by sg00dwin** [comment]
@jwforres updated pr

full
mobile

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
