### PR TITLE
switch to use upstream remote authentication and authorization

### PR DESCRIPTION
**Pull request by deads2k**
Switches our remove authentication and authorization to use the upstream versions so that we can remove duplicate code.

This is predicated on the notion that we do not support new kubelet and old apiserver.  If we support that combination, we cannot do this.

@smarterclayton @liggitt

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by smarterclayton** [comment]
@sdodson FYI the 3.6 upgrade would now explicitly block 3.6 kubelet from
running against any older server.

On May 2, 2017, at 6:13 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1103/)
(Base Commit: 67a30d2
<https://github.com/openshift/origin/commit/67a30d2fc7d4714319a1345cba794319c04a6a1b>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14011#issuecomment-298776776>,
or mute
the thread

**Comment by deads2k** [comment]
flake https://github.com/openshift/origin/issues/12072

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
provision again

re[test]

**Comment by sdodson** [comment]
> @sdodson FYI the 3.6 upgrade would now explicitly block 3.6 kubelet from running against any older server.

Ok, that shouldn't happen during any of our supported upgrade paths. We're always API/Controllers first.

When you say older you mean <= 1.5/3.5 or even within 1.6/3.6?

**Comment by deads2k** [comment]
@enj let's get this tied off.

**Comment by enj** [comment]
LGTM.

[merge]

**Comment by enj** [comment]
re[merge] flake on https://github.com/kubernetes/kubernetes/issues/45375

I will cherry pick the fix tomorrow.

**Comment by deads2k** [comment]
[merge]

**Comment by enj** [comment]
Flake #13980

**Pull request merged**
