### PR TITLE
networking requirements changes

### PR DESCRIPTION
**Pull request by rajatchopra**
- plugins should use daemonset as a preferred way of installation
 - plugins should be aware of possible conflicts with NetworkManager

### CODE REVIEW

**Comment by rajatchopra** [comment]
Maybe I should create a new section with 'caveats' and move point#7 there.

**Comment by pravisankar** [comment]
@rajatchopra @bparees 
https://github.com/openshift/origin/pull/19082/files#diff-b555946ea67e3109bb994d33e8bfa8ffR43
Build containers still needs docker build api when crio runtime is used?

**Comment by bparees** [comment]
> Build containers still needs docker build api when crio runtime is used?

yes.

**Comment by rhatdan** [comment]
Hopefull not for long.

**Comment by knobunc** [comment]
@bparees @derekwaynecarr will one of you approve this please.

**Pull request merged**
