### PR TITLE
jenkins: do not pull templates from master

### PR DESCRIPTION
**Pull request by yselkowitz**
Changes from development in master should not be pulled automatically
into stable branches.

/cc @gabemontero @akram

### CODE REVIEW

**Comment by yselkowitz** [comment]
Background in https://github.com/openshift/origin/pull/26268#issuecomment-868816610

**Comment by gabemontero** [comment]
Yeah your change here is not going to fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/829/pull-ci-openshift-kubernetes-release-4.8-e2e-aws-jenkins/1408481494824914944

You want to make the same change in 4.8 as we made in master branch at https://github.com/openshift/origin/blob/master/test/extended/builds/pipeline_origin_bld.go#L268

For that, we'll need a bugzilla 

Now, with the file you did change, I would also just comment that test out in the same way with this PR.  That will help the multi arch runs I worked with Jeremy and folks last year or 2019 whenever it was, where we don't use centos based images.

**Comment by gabemontero** [comment]
> Yeah your change here is not going to fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/829/pull-ci-openshift-kubernetes-release-4.8-e2e-aws-jenkins/1408481494824914944
> 
> You want to make the same change in 4.8 as we made in master branch at https://github.com/openshift/origin/blob/master/test/extended/builds/pipeline_origin_bld.go#L268

I can take on ^^

> 
> For that, we'll need a bugzilla
> 
> Now, with the file you did change, I would also just comment that test out in the same way with this PR. That will help the multi arch runs I worked with Jeremy and folks last year or 2019 whenever it was, where we don't use centos based images.

**Comment by gabemontero** [comment]
So bottom line, use this PR to comment out the offending client plugin test in the rhel only jenkins pipeline file, and I'll work on the backport of that to 4.8, etc.

**Comment by gabemontero** [comment]
https://github.com/openshift/origin/pull/26275 is up @yselkowitz

**Comment by yselkowitz** [comment]
> So bottom line, use this PR to comment out the offending client plugin test in the rhel only jenkins pipeline file, and I'll work on the backport of that to 4.8, etc.

Filed https://github.com/openshift/origin/pull/26278 in place of this.

**Pull request closed without merging**
