### PR TITLE
Issue #19226 Removed docker machine doc from cluster up usage message

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by mfojtik** [comment]
@praveenkumar I think @deads2k removed this in his PR that is tagged for merge

**Comment by praveenkumar** [comment]
@mfojtik I just rebased after @deads2k PR and there is still bit of doc which need to be updated.

**Comment by mfojtik** [comment]
/hold

@praveenkumar while you are here, can you also fix https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/status.go#L33 (and looks for any other leftovers?)

**Comment by praveenkumar** [comment]
@mfojtik I grepped occurrence of docker-machine in the source code excluding vendor directory and tried to update the doc or the usage string. I can also see there is some error code which now not relevant because of removal of machine code so removed that part also.

**Comment by praveenkumar** [comment]
@mfojtik Any idea why `extended_conformance_install` failed?

**Pull request merged**
