### PR TITLE
ignore namespace when processing templates

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/12277

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/cli-review ptal
[test]

**Comment by juanvallejo** [comment]
@bparees could we add a quick test under templates.sh? other than that this LGTM. Thanks!
cc @fabianofranz

**Comment by bparees** [comment]
@juanvallejo added, ptal

**Comment by juanvallejo** [comment]
@fabianofranz LGTM

**Comment by bparees** [comment]
[merge]

**Comment by fabianofranz** [comment]
LGTM

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11452
flake https://github.com/openshift/origin/issues/13749
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13650
[merge]

**Comment by jianzhangbjz** [comment]
@bparees Hi, one question, for below scenario:
1, Since all `csc` resources will be created in the `openshift-marketplace` namespace, so I hardcode it. Like below:
```yaml
mac:olm jianzhang$ cat csc.yaml 
apiVersion: v1
kind: Template
metadata:
  name: csc-template
objects:
- apiVersion: operators.coreos.com/v1
  kind: CatalogSourceConfig
  metadata:
    name: "${NAME}"
    namespace: openshift-marketplace
  spec:
    targetNamespace: "${TESTNAMESPACE}"
    packages: etcd
```
2, But, when I `process` it, this `namespace: openshift-marketplace` option is dropped automatically.
So, how to solve it? Only change the `namespace: openshift-marketplace` option to `namespace:${MARKETPLACENAMESPACE} `? I cannot understand why we ignore the `namespace` strings. Could you help explain it? Thanks!
```json
mac:olm jianzhang$ oc process -f csc.yaml -p NAME=test TESTNAMESPACE=test
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "operators.coreos.com/v1",
            "kind": "CatalogSourceConfig",
            "metadata": {
                "name": "test"
            },
            "spec": {
                "packages": "etcd",
                "targetNamespace": "test"
            }
        }
    ]
}
```

**Comment by bparees** [comment]
> But, when I process it, this namespace: openshift-marketplace option is dropped automatically.
So, how to solve it? Only change the namespace: openshift-marketplace option to namespace:${MARKETPLACENAMESPACE} ? I cannot understand why we ignore the namespace strings. Could you help explain it? Thanks!

yes, the only way to force the resource to be created in a particular namespace is to parameterize the namespace value.

processing a template drops the namespace from the resources (unless they are parameterized) 

I don't remember the exact history of why processing a template drops hardcoded namespace values, i think it was to make it easier to share templates where someone might have specified a namespace but that someone else was trying to instantiate it into a different namespace.

**Comment by bparees** [comment]
btw this behavior is documented:
https://docs.openshift.com/container-platform/4.1/openshift_images/using-templates.html#templates-writing-parameters_using-templates

```
If an object definition’s metadata includes a fixed namespace field value, the field will be stripped out of the definition during template instantiation. If the namespace field contains a parameter reference, normal parameter substitution will be performed and the object will be created in whatever namespace the parameter substitution resolved the value to, assuming the user has permission to create objects in that namespace.
```

**Comment by jianzhangbjz** [comment]
@bparees Got it. Thanks for your clarification!

**Pull request merged**
