### PR TITLE
Get email via GitHub API if user has no public email

### LINKED ISSUE #17658: GitHub oauth provider gets blank email
When using the GitHub oauth provider to log in, the user's email does not always get added to the identity's extra meta data.

This is because the call to `https://api.github.com/user` can return null for the email if user has not selected a Public email in their public profile here https://github.com/settings/profile.

However, with the `user: email` scope, you can call `https://api.github.com/user/emails` to see all of the user's email addresses and then filter by primary. Here is an example response:
```
[
  {
    "email": "email1@example.com",
    "primary": false,
    "verified": true,
    "visibility": null
  },
  {
    "email": "email2@example.com",
    "primary": true,
    "verified": true,
    "visibility": "public"
  }
]
```

##### Version
```
openshift version
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
```

##### Steps To Reproduce
1. Use a GitHub user with no email selected for "Public email" under https://github.com/settings/profile.
2. Log in to your OpenShift dashboard using the GitHub IDP with that user.
3. Check the newly created identity:
  ```
  oc get identities GitHub.com:<id> -o yaml
  ```

##### Current Result

It does not show an email against the identity.

##### Expected Result

It shows the user's primary email from GitHub.

### PR DESCRIPTION
**Pull request by enj**
When configured to use the GitHubIdentityProvider, the user endpoint was previously used as the sole source for a user's email.  This fails if the user has no public email set.  Now we additionally query the user email endpoint if needed.  Since we already request the user:email scope, this requires no additional permissions from the user.

Signed-off-by: Monis Khan <mkhan@redhat.com>

---

Fixes #17658

/assign @simo5

@openshift/sig-security

### CODE REVIEW

**Comment by enj** [comment]
@aliscott interested in testing this?

**Comment by enj** [comment]
/hold

I probably should test it first 😄

**Comment by enj** [comment]
This works as expected in my local testing.

**Comment by enj** [comment]
I will wait for @liggitt to have a look.

**Comment by liggitt** [comment]
didn't look closely, but seems generally ok

**Comment by enj** [comment]
> didn't look closely, but seems generally ok

Ship it! :shipit: 😄 

/hold cancel
/retest

**Comment by enj** [comment]
/retest

Flake #17697

**Pull request merged**
