### PR TITLE
Respect scopes during SARs

### PR DESCRIPTION
**Pull request by deads2k**
Turns out we don't use it much.  Last commit is unique.

I'll add some tests

### CODE REVIEW

**Comment by deads2k** [comment]
> Should add a test to the integration node_auth_test that exercises scoped tokens

We spoke this morning.  We need the webhook authenticator types from upstream and we can wire this up to work properly.  For now its empty.

**Comment by deads2k** [comment]
> I'd prefer a helper func that takes a user.Info and SAR/LSAR and populates the user/groups/scopes to unify the place that logic is done

done

**Comment by liggitt** [comment]
open a follow-up issue to track the remote authorizer/webhook work and to add a test to node_auth exercising it, then LGTM

**Comment by deads2k** [comment]
created https://github.com/openshift/origin/issues/8988

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
