### PR TITLE
buildlogs: dont redirect to host but to IP instead

### PR DESCRIPTION
**Pull request by TomasTomecek**
since host might not have DNS set up

### CODE REVIEW

**Comment by smarterclayton** [comment]
Be aware that upstream is talking about moving these around https://github.com/GoogleCloudPlatform/kubernetes/pull/4434

Can you add a test case that exercises this?

**Comment by TomasTomecek** [comment]
to be honest, this patch haven't solved my issue in the end: my VM has 2 IP address which are in 2 different networks -- therefore I would prefer if there was some configuration how to do the redirect (I solved the issue by "hardcoding" the URL to the kubernetes API end point in my tool which fetches the logs -- the tool is not asking openshift for the redirect)

**Comment by smarterclayton** [comment]
Logs are really just a simple hack today.  There will eventually a be a log streaming/proxy that you connect to, not the proxy of the backend.  Also, the client should be using the proxy on the master to accomplish this today, which means the IP has to work from the master to the node, not from the client to the node.

----- Original Message -----

**Comment by TomasTomecek** [comment]
Makes sense to me. Let's close this then.

**Pull request closed without merging**
