### PR TITLE
Add post-rebase missing carry patches

### PR DESCRIPTION
**Pull request by mfojtik**
Should fix CRD validation and nullable and carry some fixes to CRD post start hooks.

/cc @deads2k

### CODE REVIEW

**Comment by soltysh** [comment]
One unit flake fixed in https://github.com/openshift/origin/pull/22477

**Comment by mfojtik** [comment]
```
Flaky tests:

[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] removes definition from spec when one versin gets changed to not be served [Suite:openshift/conformance/parallel] [Suite:k8s]

Failing tests:

[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] updates the published spec when one versin gets renamed [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for CRD without validation schema [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for multiple CRDs of different groups [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for multiple CRDs of same group and version but different kinds [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for multiple CRDs of same group but different versions [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (xfs)] volumes should allow exec of files on the volume [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Comment by mfojtik** [comment]
all these seems to be picked and merged, closing.

**Pull request closed without merging**
