### PR TITLE
UPSTREAM: 37009: fix permissions when using fsGroup

### PR DESCRIPTION
**Pull request by sjenning**
xref https://github.com/kubernetes/kubernetes/pull/37009

@derekwaynecarr @pmorie

### CODE REVIEW

**Comment by ncdc** [comment]
@sjenning can you update this to match the latest upstream changes, including the e2es?

**Comment by sjenning** [comment]
@ncdc updated.  the secrets e2e tests don't match upstream because some refactoring that took place upstream hasn't been included in the origin base.

**Comment by pmorie** [comment]
@sjenning you can pull that refactor commit in if it's not burdensome.

**Comment by sjenning** [comment]
@ncdc this has merged upstream.  I resynced and it is ready to go.  Can you move it along?

**Comment by derekwaynecarr** [comment]
LGTM [merge]

**Comment by sjenning** [comment]
Flake #9642 [test]

**Comment by sjenning** [comment]
still hitting yum mirror failure :frowning:

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by smarterclayton** [comment]
Should this be in 1.4?

**Comment by sjenning** [comment]
@smarterclayton yes, the PR is here https://github.com/openshift/origin/pull/11960

**Comment by derekwaynecarr** [comment]
@smarterclayton - its a nice to have but not a must-have.  either way, i tagged the 1.4 pr.

**Pull request merged**
