### PR TITLE
use a reflector to drive the pod monitor to avoid watch event compression

### PR DESCRIPTION
**Pull request by deads2k**
Informers are very nice for level driven things, but we want to use edge triggers for our event monitor, so use the bare reflector.  This helped with events previously.

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

looking at results, we should try rewriting the duplicate IP detection and then carefully inspect the pod edge events in here before merge.

**Comment by deads2k** [comment]
this is looking good now

/hold cancel

**Review by dgoodwin — COMMENTED** [review]
/lgtm

**Comment by deads2k** [comment]
replaced by https://github.com/openshift/origin/pull/27114

**Pull request closed without merging**
