### PR TITLE
Update consumers of ClusterVersion based on API change

### PR DESCRIPTION
**Pull request by smarterclayton**
The context for "what version is the cluster moving towards or at" is
roughly answered by the desired version field and is a drop in for all
existing calls.

### CODE REVIEW

**Comment by smarterclayton** [comment]
/hold 

Re building dependencies from clean, gorilla was suspect.

**Comment by deads2k** [comment]
generated files are failing

**Comment by deads2k** [comment]
I pulled this into https://github.com/openshift/origin/pull/21775 and fixed the generated bits

**Pull request closed without merging**
