### PR TITLE
remove test dependencies on openshift-controller-manager

### PR DESCRIPTION
**Pull request by deads2k**
To avoid vendoring ocm, we need to remove test dependencies.  I copied in minor helper functions to get tests passing, they are API based, so they cannot change without breaking other consumers too, so the copy actually works well.

### CODE REVIEW

**Comment by deads2k** [comment]
Grr gofmt

/retest

**Comment by deads2k** [comment]
vpc
/retest

**Comment by deads2k** [comment]
tagged via slack

**Comment by deads2k** [comment]
s3
/retest

**Comment by deads2k** [comment]
the block is spurious.  https://github.com/kubernetes/test-infra/pull/13533

**Comment by deads2k** [comment]
ginkgo ordering fixes, retagging.

**Comment by sttts** [comment]
Same build test failure I see in my PR.

**Comment by adambkaplan** [comment]
/hold

Need fix for e2e-aws-builds to land first

**Comment by adambkaplan** [comment]
/hold cancel

Note #23452 fixes issue with using obsolete ruby version in some tests

**Pull request merged**
