### PR TITLE
builds - Configure Runtime Registries from image.config.openshift.io

### PR DESCRIPTION
**Pull request by adambkaplan**
Replaces configuration sourced from build.config.openshift.io

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold
Has parent PRs that need to merge first

**Comment by bparees** [comment]
/lgtm
/hold
(hold pending @deads2k's sign off on the bump changes)

**Comment by bparees** [comment]
@adambkaplan not sure why your bump PR isn't showing a merge conflict and this one is, but it is..

**Comment by bparees** [comment]
i think this is a legit failure, looks like an e2e test needs to be updated:
```
openshift-tests [Feature:Builds][Serial][Slow] alter builds via cluster configuration registries config context should allow registries to be blacklisted [Suite:openshift]
```

**Comment by bparees** [comment]
replacing this with https://github.com/openshift/origin/pull/22063

**Comment by adambkaplan** [comment]
@bparees this is what happens when I'm on PTO and our failures are dominated by install/deployment issues.

**Comment by bparees** [comment]
> @bparees this is what happens when I'm on PTO and our failures are dominated by install/deployment issues.

yeah, it's tough when the signal to noise ratio is so low.

**Comment by bparees** [comment]
(now go back on PTO!)

**Comment by adambkaplan** [comment]
/close

This was merged in https://github.com/openshift/origin/pull/22063

**Pull request closed without merging**
