### PR TITLE
Adding additional persistent volumes for image_ecosystem tests

### PR DESCRIPTION
**Pull request by coreydaley**
Should resolve: #17714 & #17651

### CODE REVIEW

**Comment by coreydaley** [comment]
@openshift/sig-developer-experience ptal

**Comment by bparees** [comment]
/lgtm
/hold
(hold pending passing image eco)

**Comment by coreydaley** [comment]
@bparees looks like all tests are passing

**Comment by bparees** [comment]
@coreydaley you're welcome to remove the hold yourself in the future.
/hold cancel

**Pull request merged**
