### PR TITLE
Use kube auth interfaces for union and group

### PR DESCRIPTION
**Pull request by enj**
Collapses a little bit of the shared interfaces.

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
[test]

**Comment by enj** [comment]
@deads2k PTAL whenever you get a chance.

xref: #13247

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
re[merge]

**Comment by deads2k** [comment]
@enj find the flake to reference and i'll rekick.

**Comment by enj** [comment]
@deads2k not a flake - GCE is broken.  Steve disabled the test suite so it shouldn't get in the way anymore.

**Comment by deads2k** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
Your merge job had a deadlock on `oc logs` in the integration suite -- I aborted it as I didn't really want to wait for the timeout to hit since this was in the critical path for other merges.

**Comment by deads2k** [comment]
> Your merge job had a deadlock on oc logs in the integration suite -- I aborted it as I didn't really want to wait for the timeout to hit since this was in the critical path for other merges.

Known flake or fresh in this pull?

**Comment by stevekuznetsov** [comment]
Really hard to tell without artifacts. We've had some sort of `logs -f` deadlock/output issues for year(s?) now ... Sorry for squashing, but the circumstances this morning were special.

**Comment by enj** [comment]
@stevekuznetsov did I break it somehow?

**Comment by stevekuznetsov** [comment]
@enj yeah you did :\

**Comment by stevekuznetsov** [comment]
(no, you didn't)

**Comment by enj** [comment]
re[test] plz?

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
