### PR TITLE
Reconcile deleted namespaces out of cluster quota status

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1401073

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by liggitt** [comment]
[test]

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
github timeout flake, [merge]

**Pull request merged**
