### PR TITLE
create staging repo for project reservation

### PR DESCRIPTION
**Pull request by deads2k**
Making a place for us to argue about how to do this.  The vision goes something like this: instead of creating a new api/admission plugin (mostly done here: https://github.com/openshift/origin/pull/15840), we'll reserve project names by creating a CRD and an admission webhook.

Options:
 1. separate project.  We'd have to create new CI to handle merging (or accept manual merging) and @abhgupta in online will need some way to build and package it reliably.  This does allow complete separation between separate things and that is very appealing.
 2. staging repo.   We'd have the same CI and we'd have a way to package it (maybe).  It is possible to have a separate vendor path (see what I've done here with glide), but it is a little error prone (you can accidentally match too high).
 3. compiled admission plugin using a CRD.  I'm against this.  It doesn't make sense to end up half-pregnant.
 4. give up and accept https://github.com/openshift/origin/pull/15840.  I'm ok with this, but it won't flush out problems with the admission webhook.

I'm partial to option 1 if we can get agreement that the build and packaging is going to be solved by the two people already undertaking it.

As a short description of why this is an API server.  We added the power in kube 1.8 to indicate a different group/version for your kind.  Assuming all those bits work, then I ought to be able to create an apiserver which serves its own `AdmissionReview.v1alpha1.admission.k8s.io` endpoint out of `/apis/projectreservation.openshift.io/v1alpha1/projectreservations` that re-uses all the "normal" machinery and server bits, leaving me to simply wire a resource name, a command name, and a `func(AdmissionReview) (AdmissionReview,error)` so that every later admission webhook is trivial.

@smarterclayton @liggitt which way shall we go?

### CODE REVIEW

**Comment by mfojtik** [comment]
4 million LoC?

**Comment by deads2k** [comment]
> 4 million LoC?

`glide`.  It pulls the entire repos and seems to lack a prune option.

**Comment by mfojtik** [comment]
I'm in favor of 1). We need to figure out how to extend ourself without bloating the openshift/origin repo which is already too big. We also need tools and processes how to build and ship these extensions where needed.

**Comment by sttts** [comment]
@deads2k for new code we should have good reason not to do (2) or even (1). Do we need an initial project to implement (1) in CI? Would this serve well to get CI ready to work with non-monolithic projects?

**Comment by deads2k** [comment]
> @deads2k for new code we should have good reason not to do (2) or even (1). Do we need an initial project to implement (1) in CI? Would this serve well to get CI ready to work with non-monolithic projects?

I'm pursuing 1 and betting on @mfojtik to make sure that the prereq build bits are done.

What about the idea of re-using the genericapiserver.  Does the plan seem like it would work?

**Comment by smarterclayton** [comment]
Would recommend calling it kubernetes-namespace-reservation, doesn't need to be project specific IIRC

**Comment by dgoodwin** [comment]
(1) and kubernetes-namespace-reservation both sound good to me.

For our other Online specific pods running in cluster we're working towards using builds straight from source with Docker strategy, for a lot of reasons. See https://github.com/openshift/online-archivist for example and there's also an Ansible role there we use to create the build/deployment config and image streams. If this is going generic Kubernetes the Ansible might not make sense in the same repo, but we can find a home for it if so.

For our needs I don't think we need packaging/OSBS builds, I'd rather just keep it straight from source. If or when we want it infront of customers then perhaps OSBS + straight to our registry might make sense but I think from our perspective, that is not required right now.

**Comment by deads2k** [comment]
Moved to https://github.com/openshift/kubernetes-namespace-reservation/pull/1

**Pull request closed without merging**
