### PR TITLE
bump(github.com/openshift/source-to-image): caa5fed4d6c38041ec1396661b66faff4eff358d

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal.

[test]

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
ec2 issues
[merge]

**Comment by mfojtik** [comment]
[merge] (everyone in the team should add his merge)

**Comment by bparees** [comment]
[merge]

**Pull request merged**
