### PR TITLE
Use kube shared informer for secrets in pull secrets controller

### PR DESCRIPTION
**Pull request by mfojtik**
@deads2k @ncdc I hope none of you touched this (it was on PM techdebt list).

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@smarterclayton this should reduce the secret caches a little bit.

**Comment by smarterclayton** [comment]
My or already fixes this

**Comment by smarterclayton** [comment]
My pr

**Comment by mfojtik** [comment]
@smarterclayton yeah, noticed that 10 minutes after i sent this pr ;-) at least I had a base to review yours.

**Pull request closed without merging**
