### PR TITLE
Bug 1793324: specify nodejs version because default is now 12 and 3.1…

### PR DESCRIPTION
**Pull request by akram**
…1 only has 8

### CODE REVIEW

**Comment by akram** [comment]
cc @gabemontero

**Comment by gabemontero** [comment]
bummer @akram 

your change triggered an image eco run

the image ecosystem run is most likely going to need forms of https://github.com/openshift/origin/pull/24378 and https://github.com/openshift/origin/pull/24391

I'll take a stab at using the cherrypick bot to get them on 3.11, but most likely you'll have to manually pick them.

All the same ... for this change specifically 
/hold
in case image-eco perpetually fails like I suspect it will
/lgtm
since what you have so far is good for the e2e's in openshift/jenkins repo

**Comment by gabemontero** [comment]
yep the auto cherry picks failed

that said image eco passed ... if you look at the run https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24548/test_pull_request_origin_extended_image_ecosystem_311/78/ all the tests are being skipped !!!

I'll refrain from editorializing. 

/hold cancel

**Comment by gabemontero** [comment]
/assign @bparees 

need him vs. @adambkaplan for clusterup and test/extended bindata

**Pull request merged**
