### PR TITLE
stop silently ignoring bad default imagechangetriggers

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal, had a customer who was very confused by why their ICT wasn't working because we were silently dropping it and thus never hitting the validation error.

I think we originally were dropping them for backwards compatibility reasons, but i think it's better to throw the error at this point.

**Comment by bparees** [comment]
[test]

**Comment by csrwng** [comment]
@bparees so looking back at https://github.com/openshift/origin/pull/6952 the reason that we wanted the conversion is that existing data would not validate correctly. Is that no longer a concern?

**Comment by bparees** [comment]
@csrwng we seriously need schema migration on upgrade :(

so if someone has an old buildconfig in etcd that would fail this validation...  what are the implications?

presumably if they go to edit it, they'll get an error on save, unless part of their edit fixes the issue.

but i guess when the controller goes to update the BC for any reason (eg updating the lastVersion), it would be unable to do the update due to the validation error, so the BC would be effectively disabled?

**Comment by csrwng** [comment]
yes, I would think so.

**Comment by bparees** [comment]
i'm half inclined to do this anyway since those people have broken BCs, but i guess we shouldn't.

not sure what else we can do here.

**Comment by csrwng** [comment]
Maybe the fact that the trigger was dropped can be surfaced to the user in some form? by adding an annotation maybe?

**Comment by bparees** [comment]
i guess that's something (though in this case i don't think the user even retrieved their BC to look at it)

**Comment by csrwng** [comment]
maybe it's beyond the scope of this, but if it's an annotation that both the cli and web console recognize then they can return the proper warning when something is created. You could even use it for unrecognized yaml fields.

**Comment by bparees** [comment]
that is a nice idea.
@smarterclayton any opinion?

**Comment by smarterclayton** [comment]
Write a migration in the new framework?

**Comment by smarterclayton** [comment]
Annotation is a bit much.  At minimum leave a todo to strengthen validation in v2

**Comment by bparees** [comment]
> Write a migration in the new framework?

pointer?

**Comment by bparees** [comment]
> Annotation is a bit much. At minimum leave a todo to strengthen validation in v2

i don't see how we can strengthen the validation ever, as long as there is the potential for old objects to be around that would fail that validation?

**Comment by smarterclayton** [comment]
We'd require the migration.

On Jun 29, 2016, at 7:17 AM, Ben Parees <notifications@github.com> wrote:

Annotation is a bit much. At minimum leave a todo to strengthen validation
in v2

i don't see how we can strengthen the validation ever, as long as there is
the potential for old objects to be around that would fail that validation?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9615#issuecomment-229369581>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p1KBKCMd1z92sE1y1jCq4ya6bOo5ks5qQn5egaJpZM4JAdO3>
.

**Comment by bparees** [comment]
so migration is currently optional, even if we introduce logic for it?

**Comment by smarterclayton** [comment]
We can block an upgrade on migration once you have a migration.

On Jun 29, 2016, at 7:59 AM, Ben Parees <notifications@github.com> wrote:

so migration is currently optional, even if we introduce logic for it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9615#issuecomment-229383507>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p-vUwCGjAXASJjC16GzZFpj0qS-gks5qQog3gaJpZM4JAdO3>
.

**Comment by bparees** [comment]
in talking to @deads2k it sounds like we don't actually have a migration framework yet.  so i guess i'm going to let this sit a while.

**Comment by deads2k** [comment]
> in talking to @deads2k it sounds like we don't actually have a migration framework yet. so i guess i'm going to let this sit a while. (#9240)

You could help review https://github.com/openshift/origin/pull/9240 :)

**Comment by deads2k** [comment]
Near as I've been able to tell, it still doesn't have enough information to follow the normal:
 1. make all masters accept new
 2. stop all masters from writing old
 3. migrate all data
 4. stop accepting old.

**Comment by smarterclayton** [comment]
You could take 9240 and try to write a new migration and then complain
about things so I can fix them too

On Jun 30, 2016, at 10:51 AM, David Eads <notifications@github.com> wrote:

in talking to @deads2k <https://github.com/deads2k> it sounds like we don't
actually have a migration framework yet. so i guess i'm going to let this
sit a while. (#9240 <https://github.com/openshift/origin/pull/9240>)

You could help review #9240 <https://github.com/openshift/origin/pull/9240>
:)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9615#issuecomment-229736717>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p98wyJU6gcvxd-m1ofO9ZNZEacwEks5qRAIZgaJpZM4JAdO3>
.

**Comment by smarterclayton** [comment]
We would block ansible on an exit code 0 from the hypothetical migration.

On Jun 30, 2016, at 10:53 AM, David Eads <notifications@github.com> wrote:

Near as I've been able to tell, it still doesn't have enough information to
follow the normal:

   1. make all masters accept new
   2. stop all masters from writing old
   3. migrate all data
   4. stop accepting old.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9615#issuecomment-229736995>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p6SWLOs3z5A2pvNuda5GksrKiDhTks5qRAJSgaJpZM4JAdO3>
.

**Comment by smarterclayton** [comment]
This does not require an online migration yet

On Jun 30, 2016, at 10:53 AM, David Eads <notifications@github.com> wrote:

Near as I've been able to tell, it still doesn't have enough information to
follow the normal:

   1. make all masters accept new
   2. stop all masters from writing old
   3. migrate all data
   4. stop accepting old.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9615#issuecomment-229736995>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p6SWLOs3z5A2pvNuda5GksrKiDhTks5qRAJSgaJpZM4JAdO3>
.

**Pull request closed without merging**
