### PR TITLE
address redundant line if new-app error output

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/13491

@openshift/devex ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
Hit flake https://github.com/openshift/origin/issues/12007 and flake https://github.com/openshift/origin/issues/12629 in conformance suite.  Everything else clean.

**Comment by gabemontero** [comment]
@bparees per flakes noted, please repost merge at your convenience.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
