### PR TITLE
[release 4.6] Bug 1906011: UPSTREAM: 96310: PV e2e: fix race in NFS recycling test

### PR DESCRIPTION
**Pull request by tsmetana**
Fixes flake in the NFS recycling e2e test. Backport of https://github.com/openshift/kubernetes/pull/441

### CODE REVIEW

**Comment by markmc** [comment]
(patch manager) @tsmetana there doesn't appear to be any actual changes in this PR?

/hold

**Comment by tsmetana** [comment]
> (patch manager) @tsmetana there doesn't appear to be any actual changes in this PR?

This is weird... No idea how did I do that. Should be OK now.

**Comment by tsmetana** [comment]
The verify-deps test suggests I'm not using a correct way to backport the fix...

**Pull request closed without merging**
