### PR TITLE
UPSTREAM: backport a couple iptables-restore locking PRs

### PR DESCRIPTION
**Pull request by dcbw**
@eparis @openshift/networking @knobunc

### CODE REVIEW

**Comment by danwinship** [comment]
There are just straight cherry-picks? If so, LGTM, I already reviewed them upstream

**Comment by knobunc** [comment]
LGTM too.

**Comment by dcbw** [comment]
> There are just straight cherry-picks? If so, LGTM, I already reviewed them upstream

Yes, straight cherry-picks from upstream.  I didn't bother with one patch that touches iptables_test.go, because we don't really run tests against vendored stuff AFAIK.  Could add that one if we want (https://github.com/kubernetes/kubernetes/pull/45481)

**Comment by imcsk8** [comment]
LGTM

**Comment by eparis** [comment]
3 reviewers and no one put it in the queue? Or even added [test] ?
[merge]

**Comment by dcbw** [comment]
re [test] flake https://github.com/openshift/origin/issues/14090

**Comment by danwinship** [comment]
flake  #14197 [test]

**Pull request merged**
