### PR TITLE
Remove overwrite_bootstrappolicy and pkg/cmd/server/admin/legacyetcd

### PR DESCRIPTION
**Pull request by juanvallejo**
Fixes https://github.com/openshift/origin/issues/15817

This patch solves a few of the items (currently checked) from #17309
Removes the file `pkg/cmd/server/admin/overwrite_bootstrappolicy.go`
which has been deprecated (and had some dependencies on `pkg/oc`.
It also removes the deprecated package `pkg/cmd/server/admin/legacyetcd`.

cc @deads2k @liggitt @openshift/cli-review

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM
@openshift/sig-security any concerns?

**Comment by enj** [comment]
LGTM

@juanvallejo please confirm that you traced all of the dependencies, this should fix #15817

**Comment by deads2k** [comment]
@liggitt will you allow it pre-rebase?

**Comment by deads2k** [comment]
@mfojtik manually checked.  Nothing crazy in the rebase regarding this.  tagging.

/lgtm

@juanvallejo  get it green.

**Comment by simo5** [comment]
@juanvallejo run make update and resubmit ?

**Comment by deads2k** [comment]
And test-cmd failure is legit

**Comment by simo5** [comment]
@juanvallejo you need to remove the test that explicitly tests the command you just removed I guess :-)

**Pull request merged**
