### PR TITLE
add wildfly 10.1 spec

### PR DESCRIPTION
**Pull request by chrira**
Added wildfly 10.1 spec pointing to wildfly-101-centos7.
Updated wildfly:latest to 10.1 image stream.

### CODE REVIEW

**Comment by bparees** [comment]
you'll need to run "hack/update-generated-bootstrap-bindata.sh" because we embed this imagestream in go code as well for oc cluster up.

if you don't have a full dev environment available to do that, let me know and i can just redo this pull.

**Comment by chrira** [comment]
pkg/bootstrap/bindata.go is now updated such that the tests pass again

**Comment by bparees** [comment]
excellent, please squash your commits and i'll merge.

**Comment by chrira** [comment]
the squashing is done

**Comment by bparees** [comment]
[merge]

**Comment by chrira** [comment]
test/cmd/debug.sh updated to expect wildfly-101-centos7 as latest wildfly image

**Comment by bparees** [comment]
[merge]

**Pull request merged**
