### PR TITLE
 Revert "Revert "test/extended/util: allow tests to be skipped based on platform""

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Reverts #23299
Also move the regex calculation out of the hot-loop.

/cc @smarterclayton

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
For e2e error on azure [here](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23301/pull-ci-openshift-origin-master-e2e-azure/19)
`[Feature:Platform] Managed cluster should should expose cluster services outside the cluster [Suite:openshift/conformance/parallel]`
opened bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1725259

**Comment by smarterclayton** [comment]
For some reason e2e-aws is missing its junit output in artifacts/e2e-aws-junit/*.xml, which is why it's listed as 37/37.  The most recent run for that test in other PRs is correctly outputting the file.

**Comment by smarterclayton** [comment]
CPU use looks more normal (3-4 core).  I really want to know why junits aren't being output though.

**Comment by abhinavdahiya** [comment]
> CPU use looks more normal (3-4 core). I really want to know why junits aren't being output though.

@smarterclayton https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23301/pull-ci-openshift-origin-master-e2e-aws/10601 is reporting the junit tests...

**Comment by smarterclayton** [comment]
That was a very unusual set of failures in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23301/pull-ci-openshift-origin-master-e2e-azure/23

/retest

**Comment by abhinavdahiya** [comment]
/retest

ping @smaterclayton

**Comment by abhinavdahiya** [comment]
the last one failed pretty badly :(

/retest

**Comment by abhinavdahiya** [comment]
ping @smarterclayton

**Pull request merged**
