### PR TITLE
make build config and instantiate consistent rest strategy

### PR DESCRIPTION
**Pull request by deads2k**
Prereq to https://github.com/openshift/origin/pull/2735

@liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
Approved

**Comment by deads2k** [comment]
> Approved

Still needs review, correct?

**Comment by liggitt** [comment]
Yes, doing so asaipc

**Comment by smarterclayton** [comment]
You can throw this to @derekwaynecarr if necessary

**Comment by smarterclayton** [comment]
LGTM [test]

**Comment by liggitt** [comment]
does the same issue exist with pods/* upstream?

**Comment by liggitt** [comment]
did this merge with the other pull, and does the same issue exist for pods/*?

**Comment by deads2k** [comment]
> did this merge with the other pull, and does the same issue exist for pods/*?

Yes, it merged.  I'm pretty sure we have different problems for pods/*.  
 1. bindings - I *think* that if I have rights to `pods/foo/binding`, I can craft an API object to bind `pods/bar`.  
 1. status - I think I can use `pods/foo/status` to update fields other than `status` inside of the pod

**Comment by smarterclayton** [comment]
----- Original Message -----
> > did this merge with the other pull, and does the same issue exist for
> > pods/*?
> 
> Yes, it merged.  I'm pretty sure we have different problems for pods/*.
>  1. bindings - I *think* that if I have rights to `pods/foo/binding`, I can
>  craft an API object to bind `pods/bar`.
>  1. status - I think I can use `pods/foo/status` to update fields other than
>  `status` inside of the pod

You can edit metadata, which is intentional.

**Pull request closed without merging**
