### PR TITLE
remove unnecessary rest methods

### PR DESCRIPTION
**Pull request by deads2k**
Remove unnecessary methods from RESTStorage types and tidy up registry errors

@smarterclayton @liggitt

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k there are plenty of those in BuildLog and Template REST, care about removing those as well?

**Comment by deads2k** [comment]
@mfojtik I think I got template REST already: https://github.com/deads2k/origin/blob/deads-registry-errors/pkg/template/registry/rest.go.  I missed one on buildlog, getting it now.

**Comment by deads2k** [comment]
buildlog added.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
