### PR TITLE
don't block creation on lack of delete powers

### PR DESCRIPTION
**Pull request by deads2k**
Create and delete aren't the same thing, but the alternatives seem worse.  This stops checking for deletion powers on create.

WIP so we don't accidentally merge this without an upstream pull.

@bparees @openshift/sig-master

### CODE REVIEW

**Comment by soltysh** [comment]
> Create and delete aren't the same thing, but the alternatives seem worse. This stops checking for deletion powers on create.

Where this is coming from that we need to open the discussion for changing it?

**Comment by liggitt** [comment]
> Where this is coming from that we need to open the discussion for changing it?

template service broker sets up ownerref relationships on created objects at creation time. we don't really want to give it delete permissions just to pass this check. it doesn't seem unreasonable to let the creator of an object declare an owning object. protecting against an update adding an ownerref and triggering deletion is more valuable.

**Comment by enj** [comment]
> it doesn't seem unreasonable to let the creator of an object declare an owning object

That sounds OK.  I am wondering if there are any weird `read` semantics we need to consider.  For example, can you probe for the existence of resource `A` (that you cannot see) by setting ownerrefs on resource `B` (which you own) and seeing if your resource `B` gets immediately GC'd?  I am not sure what that gets you, but it does remind of blind SQL injection attacks.

@openshift/sig-security

**Comment by liggitt** [comment]
You need to know the uid...

**Comment by tnozicka** [comment]
+1; I have hit the same issue as service catalog with openshift-acme

**Comment by enj** [comment]
> You need to know the uid...

Ah I forgot about that.  Do not really see any issue with this then.

**Comment by deads2k** [comment]
Opened upstream.  Ready for review.  This is not a clean pick.

**Pull request merged**
