### PR TITLE
Change gitserver-persistent template's deploy strategy to Recrate

### PR DESCRIPTION
**Pull request by shiywang**
to address this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1386482)

### CODE REVIEW

**Comment by csrwng** [comment]
@shiywang please also change it for the ephemeral template as well so we can stay consistent

**Comment by shiywang** [comment]
@csrwng updated, thanks

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/11452
[merge]

**Pull request merged**
