### PR TITLE
cli: make oc rsync impl re-useable

### PR DESCRIPTION
**Pull request by sanchezl**
Re-factor rsync command impl so that it can be re-used.
For example:
```go
rsyncOptions := &rsync.RsyncOptions{
  Source:        rsync.NewPathSpec("my-pod", "/must-gather/"),
  Destination:   rsync.NewPathSpec("", "/my/local/dir"),
  . . . 
}
rsyncOptions.RunRsync() 
```

### CODE REVIEW

**Comment by csrwng** [comment]
@sanchezl it looks fine to me. Somebody from the @openshift/sig-developer-experience should also take a look since they technically own it.

**Comment by soltysh** [comment]
This nicely cleans our CLI :+1: following current direction, thank you!
/retest

**Pull request merged**
