### PR TITLE
WIP: Preserve scaling factor of prior deployment

### PR DESCRIPTION
**Pull request by ironcladlou**
When scaling up a new deployment and a prior deployment exists,
preserve the replica count of the prior deployment. If no prior
deployment exists, use the template replica count.

### CODE REVIEW

**Comment by ironcladlou** [comment]
This addresses  #2017. The PR is currently incomplete; I have a couple of tests to fix, but wanted to get the approach out there for early review.

**Comment by smarterclayton** [comment]
At the time we create the new zero rc for the next deployment, can we not set the same annotation the rolling updater uses to record what the next deployment should be at?  Then setting that can be a responsibility of the deployment controller.

**Comment by smarterclayton** [comment]
Also, what if an autoscaler runs at any point in the deployment cycle on the old or new rc?  What should happen?

**Comment by ironcladlou** [comment]
@smarterclayton 
>At the time we create the new zero rc for the next deployment, can we not set the same annotation the rolling updater uses to record what the next deployment should be at? Then setting that can be a responsibility of the deployment controller.

Woah, that's a really good idea. I'm going to start over from that premise.

**Pull request closed without merging**
