### PR TITLE
bump(github.com/openshift/source-to-image): 392ce24366d6e8c69fac61fcf…

### PR DESCRIPTION
**Pull request by jupierce**
…124f0e11a224faa

fixes https://github.com/openshift/origin/issues/9645

### CODE REVIEW

**Comment by jupierce** [comment]
@bparees Contains glog replacement

**Comment by bparees** [comment]
lgtm, [merge]

**Comment by bparees** [comment]
retracting merge only because i'm paranoid about extended tests now, so:
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[testextended][extended:core(images)]

**Comment by bparees** [comment]
failure is known and will be fixed shortly.
[merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
flakes https://github.com/openshift/origin/issues/9444 and https://github.com/openshift/origin/issues/4351
[merge]

**Comment by bparees** [comment]
https://github.com/openshift/source-to-image/pull/528 has merged, this PR will need to be updated w/ the new bump and then hopefully it will pass tests.

**Pull request closed without merging**
