### PR TITLE
Prevent concurrent deployer pod creation

### PR DESCRIPTION
**Pull request by ironcladlou**
When cancelling deployer pods while the deployment is still in a New
phase, transition the deployment to a non-terminal phase so that the
other controllers don't think the deployment is complete/failed before
the deployer pods for the cancelled deployment have actually terminated.

For https://github.com/openshift/origin/issues/8403

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Comment by smarterclayton** [comment]
Flaked on https://github.com/kubernetes/kubernetes/issues/24125 [merge]

**Comment by kargakis** [comment]
LGTM

I am still wondering why the deployer cancellation I added didn't work even with the deployment transitioned to failed.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Opened #8502 for the flake

**Pull request merged**
