### PR TITLE
Router sets its dns name in admitted routes test

### PR DESCRIPTION
**Pull request by pecameron**
This is a unit test case for code in PR12195

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@smarterclayton @knobunc here it the requested test case from PR12195 review comments. PTAL

**Comment by pecameron** [comment]
@knobunc I made your last requested code change PTAL

flake: test/end-to-end/core.sh:363: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration': the output content test failed #12678

**Comment by knobunc** [comment]
[test]

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
