### PR TITLE
Increasing allowed openshift-node-config size

### PR DESCRIPTION
**Pull request by adammhaile**
@smarterclayton or @liggitt can one of you please merge this so we can unblock the builds?
New size is 31, so just bumped one above that. But I can set to whatever you want.

### CODE REVIEW

**Comment by deads2k** [comment]
The last merge wasn't forced.  Any idea why we're different?

**Comment by liggitt** [comment]
@deads2k this is failing when built in ose, which apparently builds with a different golang or different options

**Comment by adammhaile** [comment]
@liggitt @deads2k both as far as I'm aware. I agree that needs to be sorted, but as discussed in email the plan here is to just get us unblocked ASAP and *then* figure that out. Without this we cannot build 3.11

**Comment by smarterclayton** [comment]
Make sure we have a bugzilla assigned to the golang team and link it in here please.

**Comment by adammhaile** [comment]
@smarterclayton - Who on the golang team should it be assigned to? Never
dealt with them before.

**Comment by smarterclayton** [comment]
Derek Parker is the manager - he can route you to the right person / component

**Pull request merged**
