### PR TITLE
add step for getting the jenkins service ip

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
@bparees should we print the IP addresses to user when you create the template using new-app? We do print what is created, but it would be nice to also print the IP. (I know that oc status does that, but it is one more command I have to run ;-)

**Comment by bparees** [comment]
@mfojtik I'm guessing we used to print it, which is why the doc said what it did.  somewhere along the lines that went away, not sure why.  I assume it was part of @smarterclayton's refactor that made the new-app output more descriptive.

**Comment by mfojtik** [comment]
@bparees I guess it was removed because `oc status` does show that information

**Pull request merged**
