### PR TITLE
Cherry pick for vsphere patches

### PR DESCRIPTION
**Pull request by erinboyd**
Cherry pick for various vsphere patches to fix panic:
UPSTREAM: 39751: Changed default scsi controller type
UPSTREAM: 39752: Fix panic in vSphere cloud provider
UPSTREAM: 39754: Fix fsGroup to vSphere
UPSTREAM: 39757: Fix space in volumePath in vSphere
UPSTREAM: 40693: fix for vSphere DeleteVolume
UPSTREAM: 41217: Fix wrong VM name is retrieved by the vSphere Cloud Provider
UPSTREAM: 41226: Fix for detach volume when node is not present/ powered off

### CODE REVIEW

**Comment by erinboyd** [comment]
@eparis @childsb

**Comment by wongma7** [comment]
build is failing 'cause there is a missing colon in the second commit

 	UPSTREAM: 39752 Fix panic in vSphere cloud provider
 	UPSTREAM: 39752: Fix panic in vSphere cloud provider

**Comment by erinboyd** [comment]
@wongma7 fixed!

**Comment by gnufied** [comment]
[test]

**Comment by gnufied** [comment]
Okay I have gone back and looked over the commits in both `cloudprovider/vsphere` and `volume/vsphere_volume` and I think we have everything we need. @erinboyd confirms provisioning works now. 

So def. lgtm to me.

/lgtm

**Comment by childsb** [comment]
[merge]

**Pull request merged**
