### PR TITLE
Bug 1718542: Fix egress monitoring for some rare corner cases.

### PR DESCRIPTION
**Pull request by rkojedzinszky**
In a case when a pod sends traffic using egressIP, and receives
no reply, we should no treat that as the node being offline. Thus
start sending ping probes upon our first suspicion that the
node might be offline, but actually dont report for the first time
as that would be confusing.

Also, anytime we encounter received packets reset the retries counter.

### CODE REVIEW

**Comment by dcbw** [comment]
@rkojedzinszky looks like there's a unit test error:
```
=== RUN   TestEgressVXLANMonitor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16a619c]

goroutine 48 [running]:
github.com/openshift/origin/pkg/network/common.(*EgressIPTracker).lookupNodeIP(0x0, 0x2011776, 0xb, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/network/common/egressip.go:464 +0x3c
github.com/openshift/origin/pkg/network/common.(*EgressIPTracker).Ping(0x0, 0x2011776, 0xb, 0x3b9aca00, 0x0)
	/go/src/github.com/openshift/origin/pkg/network/common/egressip.go:481 +0x5a
created by github.com/openshift/origin/pkg/network/node.(*egressVXLANMonitor).check
	/go/src/github.com/openshift/origin/pkg/network/node/vxlan_monitor.go:225 +0x1651
FAIL	github.com/openshift/origin/pkg/network/node	0.556s
```
What line of code is `/go/src/github.com/openshift/origin/pkg/network/common/egressip.go:464` in your tree?

**Comment by danwinship** [comment]
Looks fine but this needs to be merged to master first. I've filed https://github.com/openshift/origin/pull/23089 for that.

**Comment by danwinship** [comment]
@rkojedzinszky can you change the title to "Bug 1718542: Fix egress monitoring for some rare corner cases." please? (ie, prepend "Bug 1718542: ", exactly like that)

**Pull request merged**
