### PR TITLE
Bug 1901982: clean up remaining build busybox refs after claytons overhaul

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
e2e-gcp-builds clean, which is all that this PR affects ... e2e-gcp is clean, meaning the handful of build tests there are clean as well

/assign @adambkaplan 

/retest

**Comment by gabemontero** [comment]
bump @adambkaplan 

have clean e2e's

**Comment by gabemontero** [comment]
/hold

gonna add the change needed to address https://bugzilla.redhat.com/show_bug.cgi?id=1904683 as well in this PR

**Comment by gabemontero** [comment]
> /hold
> 
> gonna add the change needed to address https://bugzilla.redhat.com/show_bug.cgi?id=1904683 as well in this PR

well, I don't have perms to create the analogous image on quay.io

I've reached out to those who might ... based on how that goes, may solve this is  a separate PR

**Comment by gabemontero** [comment]
> > /hold
> > gonna add the change needed to address https://bugzilla.redhat.com/show_bug.cgi?id=1904683 as well in this PR
> 
> well, I don't have perms to create the analogous image on quay.io
> 
> I've reached out to those who might ... based on how that goes, may solve this is a separate PR

Trying out https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md#to-add-a-new-image for docker.io/openshifttest/test-build-roots2i:latest

**Comment by gabemontero** [comment]
> > > /hold
> > > gonna add the change needed to address https://bugzilla.redhat.com/show_bug.cgi?id=1904683 as well in this PR
> > 
> > 
> > well, I don't have perms to create the analogous image on quay.io
> > I've reached out to those who might ... based on how that goes, may solve this is a separate PR
> 
> Trying out https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md#to-add-a-new-image for docker.io/openshifttest/test-build-roots2i:latest

which I think would be best in a separate PR

/hold cancel

@adambkaplan PTAL

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
e2e-gcp-builds passed with this same commit with https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25740/pull-ci-openshift-origin-master-e2e-gcp-builds/1334854164437536768

the errors now are lower level ... bunch of cannot list nodes in the k8s e2e code 

will try it one more time, then may skip

/retest

**Comment by gabemontero** [comment]
Yeah https://github.com/openshift/origin/pull/25752 and https://coreos.slack.com/archives/CEKNRGF25/p1607517832067700 are going after these recent 'cannot list nodes in the k8s e2e code'

**Comment by gabemontero** [comment]
gonna try

/test e2e-gcp-image-ecosystem

to compare with our current e2e-gcp-builds predicament 

will skip later on to clear it out if needed

**Comment by gabemontero** [comment]
/hold 

while we chase down why e2e-gcp-builds can no longer get past k8s e2e setup

between @soltysh and I we have a couple of diagnostic / potential work around PRs cooking

**Comment by gabemontero** [comment]
can unhold once https://github.com/openshift/origin/pull/25754 merges

**Pull request merged**
