### PR TITLE
UPSTREAM: 31881: make function ReadDockerConfigFile more flexible

### PR DESCRIPTION
**Pull request by guangxuli**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/31881

Releated PR: https://github.com/openshift/origin/pull/10608

### CODE REVIEW

**Comment by danmcp** [comment]
@guangxuli Is this needed in origin right now or can it wait till the next rebase?

**Comment by guangxuli** [comment]
@danmcp I think we should add this now, #10608 will use this public function to get docke config file from our own custom path. Why not add this since we know it should be updated.  :) we don't need to think about this when rebasing kubernetes next time. thanks.

**Comment by liggitt** [comment]
> @danmcp I think we should add this now, #10608 will use this public function to get docke config file from our own custom path. Why not add this since we know it should be updated. :) we don't need to think about this when rebasing kubernetes next time. thanks. 

I didn't know #10608 was the intended use. The upstream function takes a list of search paths, then appends a fixed filename within that directory. #10608 is trying to pass specific filenames into that utility method. I don't think #10608 is significant enough to carry a pick and remove it during the next rebase

**Comment by guangxuli** [comment]
@liggitt I am not sure why file `.dockerconfigjson` not handle in the kubenetes docker tool code releated PR?  kubernetes/kubernetes#31881, and why openshift do that? The specific file `.dockerconfigjson` is the main difference between our code and kubenetes's docker tools code.

**Comment by liggitt** [comment]
`.dockerconfigjson` is read because the build code is reading from files in a secret, which don't allow multiple directory levels

**Pull request closed without merging**
