### PR TITLE
Enable Priority admission plugin by default as priority and preemption feature is enabled by default now.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr @sjenning @liggitt @deads2k @ravisantoshgudimetla

### CODE REVIEW

**Comment by liggitt** [comment]
probably should wait until we pick up 1.11.1 which includes compatibility fixes to this plugin

**Comment by aveshagarwal** [comment]
> probably should wait until we pick up 1.11.1 which includes compatibility fixes to this plugin

But now there is no restriction without this plugin. so having some restriction is always better that no restriction at all. But anyway, I am fine with waiting for this PR: https://github.com/kubernetes/kubernetes/pull/65593 if you really meant this.

**Comment by liggitt** [comment]
I meant https://github.com/kubernetes/kubernetes/pull/65739

**Comment by aveshagarwal** [comment]
> I meant kubernetes/kubernetes#65739

ok. Sounds good.

**Comment by liggitt** [comment]
already enabled in https://github.com/openshift/origin/pull/20354/commits/b4d5829ce9e5a5dd982df2ffe73d74307c02c8a3

**Pull request closed without merging**
