### PR TITLE
Generated image clients

### PR DESCRIPTION
**Pull request by soltysh**
This adds generated clients for the following resources:

- ImageStream
- ImageStreamTag
- ImageStreamImport
- ImageSignature

I've also updated `make update` to build before generating completions. 

@ncdc ptal
@smarterclayton fyi, since you're gonna needs this in your trigger PR

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
Apparently we generate too much, so I've dropped `ImageStreamTag`, `ImageStreamImport` and `ImageSignature`, since for those `List` is not needed, but there's no current way to prevent generator from generating those, yet.

**Comment by ncdc** [comment]
> Apparently we generate too much

What do you mean?

**Comment by soltysh** [comment]
@ncdc I got `List()` generated for IST, ISI and IS although none of them has `*List` object, which result in integration build failure. Generation should look for existence of those and generate only if present. Additionally those 3 objects have only limited set of methods available. That's why I decided not to generate them, yet.

**Comment by smarterclayton** [comment]
No comments from me

**Comment by soltysh** [comment]
I assume no objections is ok to merge.

[merge]

**Pull request merged**
