### PR TITLE
Render image trigger From field for deploy configs

### LINKED ISSUE #874: The deploymentConfig describer isn't aware of From field of image change triggers
The CLI describer for deployment configs needs to be made aware of the new From field of image change triggers. It currently won't render the trigger details correctly unless using the legacy RepositoryName field.

### PR DESCRIPTION
**Pull request by ironcladlou**
Render deployment image trigger From field when present.

Closes #874.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@pmorie PTAL.

**Comment by pmorie** [comment]
LGTM, but travis failed @ironcladlou

**Comment by pmorie** [comment]
[test]

**Comment by ironcladlou** [comment]
Looks like something's up with Jenkins. Also, I now want to change this slightly in response to #858, so let's hold off for a bit.

**Comment by ironcladlou** [comment]
Replaced by #910

**Pull request closed without merging**
