### PR TITLE
Verify yum installed rpms

### PR DESCRIPTION
**Pull request by tdawson**
If yum does not see an rpm in it's repo, it will skip installing that package, and return success.
Since yum returned a success, docker continues with the build, even with missing rpms.
This check verifies all the rpms were installed, and if they aren't, will fail the docker build.

### CODE REVIEW

**Comment by tdawson** [comment]
[test]

**Comment by sdodson** [comment]
@mfojtik @bparees I think it makes sense to include the yum verification stuff you guys put together in s2i, agree?

**Comment by sdodson** [comment]
[test] again log output missing

**Comment by bparees** [comment]
@sdodson +1

**Comment by tdawson** [comment]
I found the problem, it's trying to install "hg", which used to fail silently, but now with the new check it critically fails.  So, these failures are good.  They are catching errors already that we've missed all this time.
Fixing, and I'll have an updated pull request in a bit.

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
I've finally gotten the bugs worked out.  This last test failed on something that doesn't appear to have anything to do with my changes.

**Comment by sdodson** [comment]
LGTM, @smarterclayton merge? Something like this was done in s2i to work around yum silently failing to install packages whenever it installs at least one of the packages requested.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by tdawson** [comment]
[test]

**Pull request merged**
