### PR TITLE
UPSTREAM: 16127: Bump cAdvisor

### PR DESCRIPTION
**Pull request by smarterclayton**
Referenced from #5107

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test] @jimmidyson

**Comment by smarterclayton** [comment]
Sigh:

```
Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:30:2: C source files not allowed when not using cgo: statvfs.c
!!! Error in hack/../hack/common.sh:131
	'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 1
Call stack:
	1: hack/../hack/common.sh:131 os::build::build_binaries(...)
	2: hack/build-cross.sh:17 main(...)
Exiting with status 1
```

**Comment by jimmidyson** [comment]
I've since removed that in cadvisor...

**Comment by jimmidyson** [comment]
Removal in cadvisor v0.19.2 tag. Need to make this bump upstream too for some other fixes too but away for a week so not able to get to that soon.

**Comment by smarterclayton** [comment]
I'll try to cherry pick that, thanks.

On Oct 30, 2015, at 6:49 PM, Jimmi Dyson <notifications@github.com> wrote:

Removal in cadvisor v0.19.2 tag. Need to make this bump upstream too for
some other fixes too but away for a week so not able to get to that soon.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5548#issuecomment-152668666>.

**Pull request closed without merging**
