### PR TITLE
Fix docker tag command in hack/build-images.sh

### PR DESCRIPTION
**Pull request by mkumatag**
Fix for https://github.com/openshift/origin/issues/9431

### CODE REVIEW

**Comment by mkumatag** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
If something is already tagged, what happens when we remove `-f`

**Comment by mkumatag** [comment]
Nothing happens if we remove -f in any case, here is the example:

```
[root@kumatagi ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              47bcc53f74dc        3 months ago        1.113 MB
[root@kumatagi ~]# docker tag busybox:latest busybox:1.0
[root@kumatagi ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             1.0                 47bcc53f74dc        3 months ago        1.113 MB
busybox             latest              47bcc53f74dc        3 months ago        1.113 MB
[root@kumatagi ~]# docker tag busybox:latest busybox:1.0
[root@kumatagi ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             1.0                 47bcc53f74dc        3 months ago        1.113 MB
busybox             latest              47bcc53f74dc        3 months ago        1.113 MB
[root@kumatagi ~]#
```

**Comment by smarterclayton** [comment]
Thanks, LGTM [merge]

**Comment by mkumatag** [comment]
@smarterclayton can you invoke [merge] one more time please?

**Comment by smarterclayton** [comment]
[merge]

**Comment by mkumatag** [comment]
@smarterclayton failed again :(

**Comment by mkumatag** [comment]
@smarterclayton can you call merge one more time ?

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
