### PR TITLE
Add more resource to watch

### PR DESCRIPTION
**Pull request by xueqzhan**
This is mainly port of code from https://github.com/dgoodwin/origin/tree/observer-rw to add more resources to watch. 

[TRT-469](https://issues.redhat.com/browse/TRT-469)

### CODE REVIEW

**Comment by dgoodwin** [comment]
I need this functionality asap but I'd like to be able to see it work, however i don't see any presubmits the observer is wired up to. Ken is there a non-aggregated job we could run payload-job command against?

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-ovn-ipv6

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-sdn-serial

**Comment by dgoodwin** [comment]
can't get results to see if this is working here, but Ken is confident it's good to go.

/lgtm

**Pull request merged**
