### PR TITLE
back project cache with local authorizer

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/5737

### CODE REVIEW

**Comment by deads2k** [comment]
I did not do a very controlled check, but creating a bunch of projects by hand after this change looks like 
pprof cpu-20151106122038


as opposed to the picture in the issue which I reproduced before.

**Comment by deads2k** [comment]
@liggitt This eliminates half of all server requests in @ironcladlou's runs

**Comment by ironcladlou** [comment]
LGTM, and confirmed as being enough to resolve #5737

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
adding to the milestone while we consider it

**Comment by smarterclayton** [comment]
Do we know what types don't have conversions?

**Comment by smarterclayton** [comment]
[extended:core]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
This is LGTM, and looks as simple as possible.  @liggitt agree this is low risk high payoff?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

On Nov 7, 2015, at 12:24 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6989/)
(Extended Tests: core)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5760#issuecomment-154734043>.

**Comment by smarterclayton** [comment]
[test]

On Nov 7, 2015, at 1:00 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6990/)
(Extended Tests: core)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5760#issuecomment-154740061>.

**Comment by liggitt** [comment]
LGTM. This backs the project cache with the same authorizer that is used to satisfy the localresourceaccessreview request submitted previously.

The only difference between the localresourceaccessreview call and this impl is that an empty namespace was explicitly disallowed when processing a localresourceaccessreview, but I verified that
1. all callers of `Review()` set a namespace
2. this implementation of `Review()` does the right thing when presented with an empty namespace (returns the list of users and groups that can get all namespaces)

**Comment by smarterclayton** [comment]
[merge], although this may result in test flakes due to improved performance, so I'll be watching for them today (this does not result in goroutine scheduling like previous flow did)

**Comment by smarterclayton** [comment]
```
Error from server: unable to find api field in struct BuildConfig for the json field "metadata"
!!! Error in test/cmd/builds.sh:32
	'oc patch bc/ruby-sample-build -p "{\"spec\":{\"output\":{\"to\":{\"name\":\"${REAL_OUTPUT_TO}\"}}}}"' exited with status 1
Call stack:
	1: test/cmd/builds.sh:32 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:281
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:281 main(...)
Exiting with status 1
```

I have trouble seeing how this is related.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Worried that we're seeing a lot of flakes here, but none of them look attributable so far.  Testing more

**Pull request merged**
