### PR TITLE
avoid conflict updating custom build role

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/17596

(I don't really consider this a proper fix, but apparently oc adm isn't going to get the proper fix so this is as close as we're getting).

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal
/assign @jim-minter

**Comment by jim-minter** [comment]
I just saw lines https://github.com/openshift/origin/blob/master/test/extended/builds/forcepull.go#L83-L89 , take a look ...

**Comment by bparees** [comment]
Yeah that's gonna need the same change. I'll update this tomorrow.

**Comment by bparees** [comment]
@jim-minter updated

**Comment by bparees** [comment]
@jim-minter ignore this for the moment.  it's still broken.

**Pull request merged**
