### PR TITLE
bump(github.com/openshift/openshift-sdn) ba3087afd66cce7c7d918af10ad

### PR DESCRIPTION
**Pull request by pravisankar**
Fix for issue https://github.com/openshift/openshift-sdn/issues/291 (priority/p0) => https://github.com/openshift/openshift-sdn/pull/292

Better/more SDN logging for debugging networking problems => https://github.com/openshift/openshift-sdn/pull/296, https://github.com/openshift/openshift-sdn/pull/295

Remove unnecessary cookies from node ovs rules => https://github.com/openshift/openshift-sdn/pull/274, https://github.com/openshift/openshift-sdn/pull/294

### CODE REVIEW

**Comment by pravisankar** [comment]
@smarterclayton @eparis @knobunc @dcbw  can we merge this pr for 3.2?
This has fix for priority/p0 issue and better logging that helps in sdn troubleshooting (low risk).

**Comment by pravisankar** [comment]
[test]

**Comment by smarterclayton** [comment]
Approved

**Comment by dcbw** [comment]
LGTM

**Comment by knobunc** [comment]
LGTM

**Comment by eparis** [comment]
[merge]

**Pull request merged**
