### PR TITLE
Don't need to test same stuff twice

### PR DESCRIPTION
**Pull request by smarterclayton**
* Only test assets or code, but not both.  
* Move verify into its own task on the makefile. 
* Enable testing of Go 1.5. 
* Make everything pass on Mac.

### CODE REVIEW

**Comment by danmcp** [comment]
@smarterclayton Bump

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
