### PR TITLE
Errors must be always shown in oc status

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/14794

@smarterclayton @juanvallejo PTAL

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by juanvallejo** [comment]
LGTM

**Comment by fabianofranz** [comment]
flake https://github.com/openshift/origin/issues/13271 re[test]

**Comment by fabianofranz** [comment]
[merge][severity: blocker]

**Comment by fabianofranz** [comment]
flake [merge][severity: blocker]

**Comment by fabianofranz** [comment]
flake https://github.com/openshift/origin/issues/10162
 [merge][severity: blocker]

**Comment by fabianofranz** [comment]
flake [merge][severity: blocker]

**Pull request merged**
