### PR TITLE
Remove ncdc from OWNERS

### PR DESCRIPTION
**Pull request by enj**
As a courtesy since Andy does not work at Red Hat anymore.

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
@stevekuznetsov

**Comment by deads2k** [comment]
@sdodson @stevekuznetsov second time I've seen this this morning

```
Stage ENSURE BUILT VERSION OF ORIGIN IS INSTALLED [00h 00m 07s] failed.
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/3383

/retest

**Comment by stevekuznetsov** [comment]
Queue is broken

**Comment by kargakis** [comment]
/retest

The job should be fixed now

**Pull request merged**
