### PR TITLE
fixed LDAP test file extensions

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k fixing tech debt for https://github.com/openshift/origin/issues/4851

### CODE REVIEW

**Comment by deads2k** [comment]
[test][extended:ldap_groups]

**Comment by deads2k** [comment]
@stevekuznetsov This needs a clean extended run before we can merge it.

**Comment by stevekuznetsov** [comment]
@deads2k Sure. I haven't seen this before, do you understand what happened here: 
```
Public key for openvswitch-2.4.0-1.el7.centos.x86_64.rpm is not installed
--------------------------------------------------------------------------------
Total                                              6.3 MB/s |  18 MB  00:02     
Retrieving key from https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg
Importing GPG key 0x669B00E2:
 Userid     : "maxamillion_origin-next (None) <maxamillion#origin-next@copr.fedorahosted.org>"
 Fingerprint: d035 03ff a639 e74e ddc0 430c c38b 81dd 669b 00e2
 From       : https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg
Running transaction check
Running transaction test


Transaction check error:
```
 ?

**Comment by stevekuznetsov** [comment]
Looks like two installations of `systemd` conflicted with each other? @bparees have you seen this before?

**Comment by stevekuznetsov** [comment]
Flake on `yum install` with `systemd` [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7790/console)

https://github.com/openshift/origin/issues/6301

**Comment by stevekuznetsov** [comment]
re[test][extended:ldap_groups]

**Comment by stevekuznetsov** [comment]
re[test][extended:ldap_groups]

**Comment by deads2k** [comment]
Green extended run [merge]

**Pull request merged**
