### PR TITLE
Duplicate serials were being handed out because objects were copied

### LINKED ISSUE #3594: certs with overlapping issuer/serials being generated
Seen occasionally in test logs:
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/1934/console

curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

### PR DESCRIPTION
**Pull request by smarterclayton**
Hand out one CA per process.

Fixes #3594

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test] @liggitt

**Comment by liggitt** [comment]
LGTM, [merge]

**Comment by liggitt** [comment]
weird:
```
The Service "sinatra-app-example" is invalid:spec.clusterIP: invalid value '172.30.17.49': provided IP is already allocated
!!! Error in hack/test-cmd.sh:729
  'oc create -f test/fixtures/app-scenarios' exited with status 1
```

**Comment by liggitt** [comment]
[merge]

**Comment by smarterclayton** [comment]
Are we explicitly choosing an IP for sinatra?

**Comment by smarterclayton** [comment]
We are, because they are examples (i think)

**Comment by liggitt** [comment]
it's in the fixture (which was probably a dump of a running service)

**Pull request merged**
