### PR TITLE
1.3 crash picks

### PR DESCRIPTION
**Pull request by ncdc**
Cherry picks of

- kubernetes/kubernetes#29594
- kubernetes/kubernetes#30291
- kubernetes/kubernetes#29743
- kubernetes/kubernetes#29531
- kubernetes/kubernetes#29672
- kubernetes/kubernetes#29581
- kubernetes/kubernetes#28744
- kubernetes/kubernetes#28697
- kubernetes/kubernetes#26680 (partial)

for https://github.com/openshift/origin/issues/9790#issuecomment-240848141

cc @smarterclayton @eparis @timothysc @sttts @ingvagabund @derekwaynecarr @pmorie

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ingvagabund** [comment]
With respect to the origin master HEAD (e5178ecf398e8e568ed83fdfdfed5c9d483276c1):

- [ ] ~~https://github.com/kubernetes/kubernetes/pull/28153 https://github.com/kubernetes/kubernetes/commit/06082b1bdf4c9ff93e5acf33da49f0b091a47d3e Fixed goroutinemap race on Wait()~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25255 https://github.com/kubernetes/kubernetes/commit/e0b8595f92ef8f1f82f6983f4e6cb20e579a9020 Merge pull request #25255 from ingvagabund/e2e-framework-util-StartPods-panic-for-zero-replicas~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27831 https://github.com/kubernetes/kubernetes/commit/de1719ed87bbeb75feed5205b15d1ccea09b8dc5 Merge pull request #27831 from quinton-hoole/2016-06-21-fix-panic-in-dns-zone-creation~~ {federation not in origin}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27435 https://github.com/kubernetes/kubernetes/commit/8bc4e9bc136a2c175035da5d54f6a4d0298e93b0 Merge pull request #27435 from wojtek-t/fix_delta_fifo_race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27341 https://github.com/kubernetes/kubernetes/commit/5d702a32c14a764397d9d1dd96ed4e994b47072d Fix race in informer~~ {already cherry picked in origin master}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/37345 https://github.com/kubernetes/kubernetes/commit/80d1ae764288ec163bd11dbbf109aa3c4d7327be Fix panic in TestUnschedulableNodes~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26410 https://github.com/kubernetes/kubernetes/commit/335da9b125539a11afeb02ddc61c37e9b722ec89 Merge pull request #26410 from jsafrane/fix-test-race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26410 https://github.com/kubernetes/kubernetes/commit/2d43e4549e76ab1444f6febbecdd159d3dc0c40b Fix data race in volume controller unit test.~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26642 https://github.com/kubernetes/kubernetes/commit/903821354e8b9c14a4991a729dcbe9a04b520bde Merge pull request #26642 from wojtek-t/fix_kubelet_test_panics~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26642 https://github.com/kubernetes/kubernetes/commit/13b57f8ffb6a395541ba7fb5b2b80b798ada6b87 Fix panic in kubelet test~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26619 https://github.com/kubernetes/kubernetes/commit/ee74cc4354d3201b6095fec805e5c5a95700a54f Fix fake event recorder race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26564 https://github.com/kubernetes/kubernetes/commit/d002cb1d634fe2a305d10abfef938f309895a9a2 Fix apiservers crashes~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26177 https://github.com/kubernetes/kubernetes/commit/1d40f471b4c4e9a7da9616cabfbc7727a022ad19 rkt: Fix docker auth config save directory to avoid race.~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26397 https://github.com/kubernetes/kubernetes/commit/d00dec782536349716a79ed59a7f4be904d62de4 Merge pull request #26397 from euank/fixReadOnlyRootfsPanic~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26397 https://github.com/kubernetes/kubernetes/commit/ecfd8f723f00068a66778f4819d30eedac532395 rkt: Fix panic in setting ReadOnlyRootFS~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26398 https://github.com/kubernetes/kubernetes/commit/7e0b9bfa66b7aeebfc8a18feb0d82dffe96a85c0 kubenet: Fix panic when teardown run before setup~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26407 https://github.com/kubernetes/kubernetes/commit/071cfe608640a1808c16f85ef1b7a42b556fb570 Merge pull request #26407 from saad-ali/fixRaceReconcilerTest~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26407 https://github.com/kubernetes/kubernetes/commit/3c345abafd024853d8ff0fb332db6076cfc610c5 Fix DATA RACE in unit tests: reconciler_test.go~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26078 https://github.com/kubernetes/kubernetes/commit/f79998a9b1592b8872e3bead9b8d59918274bb1a Fix panic when the namespace flag is not present~~ {already cherry-picked in rebase}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26025 https://github.com/kubernetes/kubernetes/commit/22649a19d01a2eecfd0ab846fac5bb6a037bbb0e Fix panic in auth test failure~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25690 https://github.com/kubernetes/kubernetes/commit/b7a31ad2615524cefcb82ed4b3832e2105147410 Merge pull request #25690 from fabianofranz/fixes_panic_on_roundtripper_when_tls_under_proxy~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25690 https://github.com/kubernetes/kubernetes/commit/5940040c96d49f5c894d1117ebea572fea73110a Fixes panic on round tripper when TLS under a proxy~~ {the same as the one above}
- [X] https://github.com/kubernetes/kubernetes/pull/25308 https://github.com/kubernetes/kubernetes/commit/a167a6b4df92a6a61c4a9c3e37b7b0f7ef6e0dd6 Merge pull request #25308 from AdoHe/deployment_panic {simple cherry-pick, fixed panic}
- [X] https://github.com/kubernetes/kubernetes/pull/25308 https://github.com/kubernetes/kubernetes/commit/d1480cd8dfe9edc5109d6825b9df67ef96af9079 fix rollout nil panice issue {the same as the one above}

**Comment by ncdc** [comment]
25308 isn't a clean cherry-pick because the history command has changed after 1.3. But we probably could massage it into our code.

**Comment by derekwaynecarr** [comment]
All the picks look good to me.  The pick for 29672 is good, but I could not see what underlying issue it fixed, seemed like a change to just code hygiene since there was no reference to a material panic it prevented.

**Comment by ingvagabund** [comment]
$ ``GOPATH=/root go test  -race -cover -covermode atomic -timeout 120s github.com/openshift/origin/pkg/cmd/server/origin``
I0819 14:39:24.137802    7405 <autogenerated>:1] &{dev  [wheel group-impersonater] map[]} is acting as &{system:admin  [some-group] map[]}
I0819 14:39:24.138378    7405 <autogenerated>:1] &{dev  [wheel system-group-impersonater] map[]} is acting as &{system:admin  [some-system:group] map[]}
I0819 14:39:24.138841    7405 <autogenerated>:1] &{dev  [wheel] map[]} is acting as &{system:admin  [system:authenticated] map[]}
I0819 14:39:24.139295    7405 <autogenerated>:1] &{dev  [regular-impersonater] map[]} is acting as &{tester  [system:authenticated system:authenticated:oauth] map[]}
I0819 14:39:24.141462    7405 <autogenerated>:1] &{dev  [sa-impersonater] map[]} is acting as &{system:serviceaccount:foo:default  [system:serviceaccounts system:serviceaccounts:foo system:authenticated] map[]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x91fc39]

goroutine 111 [running]:
panic(0x392bca0, 0xc82000e0f0)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3ff
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/unversioned.(*limitRanges).List(0xc82039d220, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/unversioned/limit_ranges.go:56 +0x109
github.com/openshift/origin/pkg/image/admission.NewLimitVerifier.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3f7e318, ...)
	/root/src/github.com/openshift/origin/pkg/image/admission/imagestream_limits.go:23 +0xbb
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache.(*ListWatch).List(0xc82019ebe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:80 +0x86
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82069c680, 0xc820058d20, 0x0, 0x0)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:258 +0x3d0
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:202 +0x54
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc82019ec20)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x2b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc82019ec20, 0x3b9aca00, 0x0, 0x445101, 0xc820058d20)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xca
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc82019ec20, 0x3b9aca00, 0xc820058d20)
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x51
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/root/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:205 +0x327
FAIL	github.com/openshift/origin/pkg/cmd/server/origin	0.287s

**Comment by ingvagabund** [comment]
So "UPSTREAM: 29743: Fix race condition found in JitterUntil" is the culprit

**Comment by ingvagabund** [comment]
Putting the ``runtime.HandleCrash()`` gets rid of the panic. Which was removed due to https://github.com/kubernetes/kubernetes/pull/29743#discussion-diff-72658271: "Remove this function. We are switching to a world where it's safe for apiserver to panic, since it will be restarted by kubelet."

Works for containerized world. So either put back the call or skip the cherry-pick as @derekwaynecarr suggests.

**Comment by timothysc** [comment]
Isn't this actually exposing a real issue though?

**Comment by timothysc** [comment]
@ingvagabund Given where we are at in the release cycle think putting it back in makes sense, but imho we need to re-eval in the next cycle issues we are actually glossing over.

**Comment by derekwaynecarr** [comment]
@timothysc - I agree it could cover a real issue, I have decided to carry a patch that keeps handle crash, and we can open an issue to evaluate that carry after release.

see https://github.com/openshift/origin/pull/10541

**Comment by derekwaynecarr** [comment]
closing in favor of #10541

**Pull request closed without merging**
