### PR TITLE
OCPBUGS-7616: Revert Revert "bump(k8s): 1.26"

### PR DESCRIPTION
**Pull request by sanchezl**
Revert https://github.com/openshift/origin/pull/27736 and bump o/k to pick up  https://github.com/openshift/kubernetes/pull/1480.

### CODE REVIEW

**Comment by sanchezl** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-sdn

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
the problem from https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-27738-nightly-4.13-console-aws/1627987008972394496 is known and tracked in https://issues.redhat.com/browse/OCPBUGS-7632
/hold cancel

**Pull request merged**
