### PR TITLE
add v1alpha1 version for config.openshift.io

### PR DESCRIPTION
**Pull request by tremes**
This should hopefully fix https://issues.redhat.com/browse/OCPBUGS-4559

### CODE REVIEW

**Comment by dgoodwin** [comment]
Could you clarify why this is only surfacing on techpreview + sdn?

**Comment by deads2k** [comment]
/hold

this area is under refactoring https://github.com/openshift/origin/pull/27596

**Comment by tremes** [comment]
@deads2k I see. So the original error message (event) from the [OCPBUGS-4559](https://issues.redhat.com/browse/OCPBUGS-4559) will disappear.  However, it's still not clear to me how this works with techpreview clusters (is a new TP resource not being watched at all?). Can I somehow run the resourcewatch locally (when running tests)?

**Comment by wking** [comment]
#27625 is a robot-pick of #27596 back to 4.12.

**Comment by tremes** [comment]
Fixed with https://github.com/openshift/origin/pull/27596

**Pull request closed without merging**
