### PR TITLE
PSP reviews: client

### PR DESCRIPTION
**Pull request by soltysh**
This is a cherry-pick of https://github.com/openshift/origin/pull/12478 onto 1.5 branch. It also includes the last fix from here: https://github.com/openshift/origin/pull/13044

@pweil- @mfojtik ptal
@sdminonne fyi

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
[(5) Create CLI for SCC access check](https://trello.com/c/nTdsLTZ9/804-5-create-cli-for-scc-access-check)

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/13046.

[test]

**Comment by soltysh** [comment]
@pweil- @mfojtik  all master PRs are merged, the tests are green are we good to go with this one?

**Comment by mfojtik** [comment]
LGTM

**Comment by pweil-** [comment]
+1 to all the pre-merge testing with fork ami that you guys did to get this stable for 1.5.  Thanks!

[merge]

**Pull request merged**
