### PR TITLE
Bug 1693018: Add CSRF to token request endpoint

### PR DESCRIPTION
**Pull request by enj**

### CODE REVIEW

**Comment by stlaz** [comment]
Code looks fine, integration test needs fixing. Did not manually test this.

**Comment by eparis** [comment]
`rpc error: code = 2 desc = oci runtime error: exec failed: container "d96b7713556b447939ed7e1cd96c0b4f1e162d3577cc1243e1c741851e41410d" does not exist`
seems unrelated
/retest

**Pull request merged**
