### PR TITLE
move alerting tests into invariants only

### PR DESCRIPTION
**Pull request by deads2k**
we currently run both [late] tests and invariants.  This moves us towards an invariant-only model to avoid double counting.

### CODE REVIEW

**Comment by neisw** [comment]
Is it needing `make update-bindata`?

**Comment by dgoodwin** [comment]
Yeah looks like it does need a bindata update. Otherwise lgtm.

**Comment by deads2k** [comment]
> Yeah looks like it does need a bindata update. Otherwise lgtm.

labelling per comment

/retest-required

**Comment by dgoodwin** [comment]
Is the new backstop test: disruption_tests: [sig-arch] Check if alerts are firing during or after upgrade success

Note: Old one was: [sig-instrumentation][Late] Alerts shouldn't report any unexpected alerts in firing or pending state [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]

**Comment by dgoodwin** [comment]
The failures cannot be related to removing the old alerting tests. I think it's time to override and stop waiting for CI here. I started work on alerting on Friday and it would be helpful to reduce the number of classes of alerting tests to deal with asap.

/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-aws-ovn-fips

**Comment by deads2k** [comment]
simple rebase, relabelling.

**Comment by deads2k** [comment]
simple rebase, retagging.

**Pull request merged**
