### PR TITLE
disable recently problematic mongo/mysql replica tests (will diagnose…

### PR DESCRIPTION
**Pull request by gabemontero**
… in PRs)

@openshift/sig-developer-experience fyi / ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
getting some `Stage PROVISION CLOUD RESOURCES [00h 01m 04s] failed.`

will retry in a bit

**Comment by bparees** [comment]
once this merges we need to revert https://github.com/openshift/release/pull/817

**Comment by gabemontero** [comment]
image_ecosystem passed

**Comment by gabemontero** [comment]
conformance install failed cause of `Stage PROVISION CLOUD RESOURCES [00h 03m 01s] failed.`

**Comment by gabemontero** [comment]
Hmmm .. the gcp test is still picking up the mysql_replica.go test:

```
 openshift mysql replication MySQL replication template for 5.7: https://raw.githubusercontent.com/sclorg/mysql-container/master/examples/replica/mysql_replica.json [Suite:openshift/conformance/parallel] 5m48s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\sopenshift\smysql\sreplication\s\sMySQL\sreplication\stemplate\sfor\s5\.7\:\shttps\:\/\/raw\.githubusercontent\.com\/sclorg\/mysql\-container\/master\/examples\/replica\/mysql\_replica\.json\s\[Suite\:openshift\/conformance\/parallel\]$'

/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:218
Expected error:
    <*errors.errorString | 0xc42004b560>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:44

```

I suppose I need to comment out the contents vs. getting clever with the `Describe` text

**Comment by gabemontero** [comment]
Same thing with the extended_conformance_install:

```
Summarizing 2 Failures:

[Fail]  openshift mysql replication  [It] MySQL replication template for 5.7: https://raw.githubusercontent.com/sclorg/mysql-container/master/examples/replica/mysql_replica.json [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:104

[Fail]  openshift mongodb replication (with statefulset)  [It] should instantiate the template [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mongodb_replica_statefulset.go:82

```

**Comment by gabemontero** [comment]
And image_ecosystem ran clean:  https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19654/test_pull_request_origin_extended_image_ecosystem/844/

**Pull request merged**
