### PR TITLE
Add descriptions to all API fields

### PR DESCRIPTION
**Pull request by ironcladlou**

### CODE REVIEW

**Comment by ironcladlou** [comment]
@smarterclayton Any reason not to do this?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Will review afterwards - we need to get this in and do a pass on cleanup close to release - thanks for starting this.

**Comment by ironcladlou** [comment]
That asset test has it out for me...

**Comment by ironcladlou** [comment]
[merge] again, I don't know if this is a flake.

**Pull request merged**
