### PR TITLE
the router tests demand access to the 1936 port

### PR DESCRIPTION
**Pull request by rajatchopra**
to fix issue #12784

[test]

### CODE REVIEW

**Comment by rajatchopra** [comment]
@marun This should be harmless right? Just wondering how were the router /healthz checks ever working without this.

**Comment by rajatchopra** [comment]
@ramr you have reviewed it, mark it formally please?

@bparees could we get a merge on this?

**Comment by bparees** [comment]
I'd like to make sure we understand why this ever works today before merging the change.

**Comment by ramr** [comment]
@bparees  in order for this test to succeed in isolation those 3 ports need to be open. 
So from a specific test perspective - that's a requirement. 

Now as re: in conjunction with other tests and it sometimes passing (we don't see anything in the logs to indicate it ran), it could be:
1. Either the test never ran - which means we have some test selection criteria am not aware off.
2. Or then for it to succeed, something else is "unblocking" iptables. Because by default, the rules
    block any ports other than 22 and 10250.  See: https://github.com/openshift/origin/blob/master/images/dind/node/iptables#L12 
  Supposition was the e2e tests but am not certain about that. See comments in #12784

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
