### PR TITLE
pick up recent quickstart changes

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi

### CODE REVIEW

**Comment by bparees** [comment]
needs bindata

**Comment by bparees** [comment]
@gabemontero also i don't see a jenkins change here, what were you trying to pick up?

**Comment by gabemontero** [comment]
On Thu, Jul 26, 2018 at 5:01 PM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> also i don't see a jenkins
> change here, what were you trying to pick up?
>
yeah the intent was only the jenkins rhel7 image stream, but as we
discussed on IRC
you already updated that

and in fact, when I ran the script, it tried to revert to
redhat.access.registry.com

**Comment by gabemontero** [comment]
bindata pushed

**Pull request merged**
