### PR TITLE
Go 1.8 fixes for e2e tests

### PR DESCRIPTION
**Pull request by detiber**
Currently alternative architecture builds require go 1.8, so we are currently unable to run e2e tests for those builds.

I'm still working through the list of fixes needed to be able to run the e2e suite.

### CODE REVIEW

**Comment by smarterclayton** [comment]
You need to split the kube godeps bump into its own, and rename your commit message:

```
UPSTREAM: elazarl/goproxy: <PR>: Message
UPSTREAM: 44113: Message
```

**Comment by detiber** [comment]
@smarterclayton is that what you had in mind for splitting the commits?

**Comment by detiber** [comment]
[test]

**Comment by detiber** [comment]
@smarterclayton This should now be ready. It unblocks the ability to run the e2e tests on alternative arches. There may still need to be additional followup based on specific test failures, but I'd like to try and get this incorporated as soon as possible.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[severity:bug]

**Comment by smarterclayton** [comment]
[severity:blocker] for other teams, has no risk to origin.

**Comment by detiber** [comment]
@smarterclayton I think this needs another [merge] tag

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] flakes

**Comment by smarterclayton** [comment]
[merge] in case that was more flakes

**Pull request merged**
