### PR TITLE
Show spec and status tags for image repos

### PR DESCRIPTION
**Pull request by ncdc**
Update `osc get imagerepository` to show spec tags and status tags.

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton looking for feedback on what to call the 2 tag columns.
[test]

**Comment by smarterclayton** [comment]
Tags | Images maybe

**Comment by ncdc** [comment]
Do you want it to show something like this?

```
Tags: another=latest,tag2=sha256:deadbeef
Images: latest=sha256:abcd1234,tag2=sha256:abab1323
```

**Comment by smarterclayton** [comment]
Those tags are going to be massive.  Not sure what the best way to show them is but I would say it needs to be tabular

**Comment by ncdc** [comment]
Yeah, this is what I have with just a few:

```
Name:           busybox
Created:        2015-03-23 11:30:06 -0400 EDT
Labels:         <none>
Spec Tags:      spectag1=tag1
Status Tags:    latest=sha256:6021bbdd685de16c091e228a390ecd79074c1dce60806daba712c2491d7e7a1f,spectag1=sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16,tag1=sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16,tag2=sha256:5d6483b8ddba1fcc2921ed8c819910cc1433a8a36894555b73ad77c087a2fcce
Registry:       172.30.17.46:5000/andy/busybox
```

**Comment by ncdc** [comment]
@smarterclayton how is this?

```
Name:           busybox
Created:        2015-03-23 11:30:06 -0400 EDT
Labels:         <none>
Tags:           spectag1=tag1
Images          spectag1=sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
                tag1=sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
                tag2=sha256:5d6483b8ddba1fcc2921ed8c819910cc1433a8a36894555b73ad77c087a2fcce
                latest=sha256:6021bbdd685de16c091e228a390ecd79074c1dce60806daba712c2491d7e7a1f
Registry:       172.30.17.46:5000/andy/busybox
```

**Comment by ncdc** [comment]
I do think that people coming to this with just a Docker background will scratch their heads a bit trying to figure out the difference between Tags and Images.

**Comment by smarterclayton** [comment]
I don't like that either.  I would combine this into one list:

spectag1 - requested source (tag1)
  current image pull spec / <hash> creation date
tag1
  current image pull spec / <hash> creation date

or similar.  Or maybe:

tag1 <creation date> <pull spec> <id> (from spec.tag value)
     <creation date> <pull spec> <id>
     <creation date> <pull spec> <id>
tag2 <creation date> <pull spec> <id>


----- Original Message -----

**Comment by ncdc** [comment]
When Bob creates tag `foo` that points at `alice/repo:bar`, should we resolve that to an immutable image id?

**Comment by smarterclayton** [comment]
For now, we should in the status.  When we add following other image repos we'll want that.

**Comment by ncdc** [comment]
Ok, it's doing that in the status currently, so no work is needed there.

I want to arrive at a decision on the format before I change the code again. I feel like we're moving toward what you see in the yaml output. What should we be showing in `describe` vs `-o yaml`?

**Comment by smarterclayton** [comment]
Users need to be able to see pull specs, tags, dates, and at least enough of the digest id to use it.  If the pull spec includes the digest we can omit the digest.

**Comment by ncdc** [comment]
The pull spec will include the digest. And it has to be the entire thing right now - there's not yet support for shortening digests when referencing them.

**Comment by smarterclayton** [comment]
The pull spec is guaranteed to include the digest in all cases?  That's not true, especially when using an external registry.

----- Original Message -----

**Comment by ncdc** [comment]
You're right, it won't always have it for external registries. I think the only real safe way to display the data without line wrapping is to have each tag entry use multiple lines.

**Comment by smarterclayton** [comment]
We don't need to include the image twice though, which should mean it would be fairly short in most cases

----- Original Message -----

**Comment by ncdc** [comment]
So something like this?
```
spectag1(latest) 172.30.17.46:5000/andy/busybox@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16 (2015-03-23 11:30:06 -0400 EDT)
```

where `spectag1` is the tag, `(latest)` indicates it's a virtual tag the user set in the spec to point to `latest`, `172.30.17.46:5000/andy/busybox@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16` is the pull spec, and `(2015-03-23 11:30:06 -0400 EDT)` is the timestamp.

**Comment by smarterclayton** [comment]
We have relative timestamps.

----- Original Message -----

**Comment by ncdc** [comment]
Sure, we can do relative. But overall, how do you like the structure?

**Comment by smarterclayton** [comment]
```
spectag1 -> \tlatest\t<relative date>\t<pullspec>\t<id if different>
```

**Comment by ncdc** [comment]
Maybe it should be `spectag1 (tracks latest) ...` or `spectag1 (tracks mysql:55) ...`

**Comment by smarterclayton** [comment]
tracks could work, but if you put an absolute reference it's really pinned.  we may want to say that.

**Comment by ncdc** [comment]
> spectag1 -> \tlatest\t<relative date>\t<pullspec>\t<id if different>

we won't always have `latest` if it's a tag that came in via a push

**Comment by smarterclayton** [comment]
Not sure what you mean?  I can push to a given tag name.

----- Original Message -----

**Comment by ncdc** [comment]
If I do `docker push andy/busybox:latest` do you want

`latest -> \tlatest\t<date>\t<pullspec>`

**Comment by smarterclayton** [comment]
If the tags are the same we should give some indication that means something

**Comment by ncdc** [comment]
If you never update the spec tags, and you're only pushing real images to the registry, then you'll always have latest -> date, pullspec (includes id). If you update the spec tags, that's when we'll want to show that you've created a virtual tag that points to or tracks some other tag or pinned image.

Also, I'm not sure how long we'll be able to support these virtual taggings. At some point, Docker may validate that the tag you're pulling is what you actually get.

**Comment by ncdc** [comment]
Can't say I'm crazy about this, but PTAL:

```
Tags  (tag)           (spec)              (relative time) (pull spec)
      latest          <pushed>            5 minutes ago   172.17.30.15:5000/andy/busybox@sha256:deadbeef
      spectag1        latest              5 minutes ago   172.17.30.15:5000/andy/busybox@sha256:deadbeef
      spectag1        latest              6 minutes ago   172.17.30.15:5000/andy/busybox@sha256:abcd1234
      spectag1        qe_ready            1 hour ago      172.17.30.15:5000/andy/busybox@sha256:99999999
      extref          mysql:latest        2 days ago      mysql:latest
```

**Comment by smarterclayton** [comment]
You don't need to indent it, make the headers consistent with other places that do headers (ALLCAPS). Also, don't write the same "tag" or "spec" multiple times (so it's clearly ordered)

**Comment by ncdc** [comment]
Do you want headers for a `describe` call?

**Comment by smarterclayton** [comment]
If a user wouldn't be clear on what the value was, we should have them.  If you look at describe node you'll start to see some of this for the conditions.  They use CamelCase.

----- Original Message -----

**Comment by ncdc** [comment]
I can do something like this but it's still super wide:

```
Tags:
  Tag           Spec            Created         PullSpec                                                                                        Image
  latest        <pushed>        10 hours ago    registry:5000/foo/bar@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
                                36 hours ago    registry:5000/foo/bar@sha256:062b80555a5dd7f5d58e78b266785a399277ff8c3e402ce5fa5d8571788e6bad
  spec1         latest          10 hours ago    registry:5000/foo/bar@sha256:4bd26aef1ce78b4f05ede83496276f11e3343441574ca1ce89dffd146c708c16
  spec2         mysql:latest    10 hours ago    mysql:latest                                                                                    e52c6534db85036dabac5e71ff14e720db94def2d90f986f3548425ea27b3719
```

**Comment by smarterclayton** [comment]
It is what it is

**Comment by ncdc** [comment]
@smarterclayton what about the fact that TagEvent doesn't keep track of the spec tag value that we talked about the other day - should we add it?

**Comment by smarterclayton** [comment]
Sure

**Comment by ncdc** [comment]
Superseded by #1525

**Pull request closed without merging**
