### PR TITLE
UPSTREAM: Validate port protocol case strictly

### LINKED ISSUE #3257: No validation failure when creating resource with incorrect `spec.ports.protocol`
The server accepts POST requests with invalid port protocols like lower-case values.

This POST request with ` "protocol": "tcp"` was accepted.

```
{
  "kind": "Service",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "nodejs-ex",
    "namespace": "another",
    "selfLink": "/api/v1beta3/namespaces/another/services/nodejs-ex",
    "uid": "1be471b1-147f-11e5-af3c-080027c5bfa9",
    "resourceVersion": "2870",
    "creationTimestamp": "2015-06-16T23:26:26Z",
    "labels": {
      "generatedby": "OpenShiftWebConsole",
      "name": "nodejs-ex"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "tcp",
        "port": 8080,
        "targetPort": 8080,
        "nodePort": 0
      }
    ],
    "selector": {
      "deploymentconfig": "nodejs-ex"
    },
    "portalIP": "172.30.51.110",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}
```

It's also a problem creating deployment configurations with container templates, `spec.template.spec.containers.ports`.

See #3253

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3257

### CODE REVIEW

**Comment by liggitt** [comment]
Upstream PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/9919

**Comment by smarterclayton** [comment]
Too risky to take

**Comment by liggitt** [comment]
@smarterclayton disagree... allowing in values that won't work is bad... things that make use of the protocols expect exact matches

**Comment by smarterclayton** [comment]
Until upstream merges it we're stuck - not going to reject things that upstream accepts.

**Comment by liggitt** [comment]
merged upstream

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
```
[INFO] Verifying the docker-registry is up at 172.30.229.192
ERROR: gave up waiting for http://172.30.229.192:5000/healthz
```

**Comment by liggitt** [comment]
re[merge]

**Pull request merged**
