### PR TITLE
Poll in bootstrap user e2e test

### PR DESCRIPTION
**Pull request by enj**
The OAuth server may not be ready when this test runs.  Thus we need to poll for a while to make sure any failures are not flakes.

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Will this fix failures like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1266/pull-ci-openshift-installer-master-e2e-aws/3889#openshift-tests-the-bootstrap-user-should-successfully-login-with-password-decoded-from-kubeadmin-secret-suiteopenshiftconformanceparallel ?

**Comment by stlaz** [comment]
@abhinavdahiya yes

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to initialize the cluster: Cluster operator network has not yet reported success"
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22070/pull-ci-openshift-origin-master-e2e-aws/4468/build-log.txt

**Comment by crawford** [comment]
In the [last failure](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22070/pull-ci-openshift-origin-master-e2e-aws/4511), I see the following in the network operator:

```
...

2019/02/19 19:50:14 Updated ClusterOperator with status:
conditions:
- lastTransitionTime: "2019-02-19T19:09:40Z"
  status: "False"
  type: Failing
- lastTransitionTime: "2019-02-19T19:50:14Z"
  message: |-
    DaemonSet "openshift-multus/multus" is not available (awaiting 1 nodes)
    DaemonSet "openshift-sdn/ovs" is not available (awaiting 1 nodes)
    DaemonSet "openshift-sdn/sdn" is not available (awaiting 1 nodes)
  reason: Deploying
  status: "True"
  type: Progressing
- lastTransitionTime: "2019-02-19T19:50:14Z"
  message: |-
    DaemonSet "openshift-multus/multus" is not available (awaiting 1 nodes)
    DaemonSet "openshift-sdn/ovs" is not available (awaiting 1 nodes)
    DaemonSet "openshift-sdn/sdn" is not available (awaiting 1 nodes)
  reason: Deploying
  status: "False"
  type: Available

...

2019/02/19 19:51:13 all objects successfully applied
<end of log>
```

The operator says "all objects successfully applied", but is stuck waiting for one more node to come up. @squeed is this expected? Am I misinterpreting that final message?

**Comment by danwinship** [comment]
"all objects successfully applied" means it has *created* the DaemonSet (and all other objects it needed to create) but not necessarily that it's ready.

The pod deployment error can be found in [workers-journal.gz](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22070/pull-ci-openshift-origin-master-e2e-aws/4511/artifacts/e2e-aws/nodes/workers-journal.gz):

```
Feb 19 19:25:20 ip-10-0-158-22 hyperkube[4064]: E0219 19:25:20.182193    4064 remote_runtime.go:119] StopPodSandbox "6dd5d37cdf637ce37ead5e70320eaeb54c312d1d72f9e3b00dfb37193eb277db" from runtime service failed: rpc error: code = Unknown desc = failed to stop infra container k8s_POD_ovs-lfpbl_openshift-sdn_d81b0ae7-347b-11e9-8ff7-0a21ab5c09ba_0 in pod sandbox 6dd5d37cdf637ce37ead5e70320eaeb54c312d1d72f9e3b00dfb37193eb277db: failed to stop container "6dd5d37cdf637ce37ead5e70320eaeb54c312d1d72f9e3b00dfb37193eb277db": failed to find process: os: process not initialized
```

This seems to have started happening in the last day or so? *Mostly* to the SDN OVS pod, although sometimes to other pods too

**Comment by smarterclayton** [comment]
It's possible that the bootstrap pivot broke something, or we landed a crio change.  Can you guys tie the knot with both the rhcos and runtime teams?

**Comment by smarterclayton** [comment]
/hold

You still failed: 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22070/pull-ci-openshift-origin-master-e2e-aws/4531#openshift-tests-the-bootstrap-user-should-successfully-login-with-password-decoded-from-kubeadmin-secret-suiteopenshiftconformanceparallel

I'm going to mark the job flaky and you can reenable once it's fixed

**Comment by smarterclayton** [comment]
Disabling the test in https://github.com/openshift/origin/pull/22088 please make sure someone owns restoring

**Comment by enj** [comment]
Once https://github.com/openshift/cluster-kube-apiserver-operator/pull/260 is merged we should be good.

**Comment by enj** [comment]
/hold cancel

This should work as expected now.

**Comment by enj** [comment]
/hold

Needs some work.

**Comment by enj** [comment]
/hold cancel

Got the ginko stuff sorted out.

**Pull request merged**
