### PR TITLE
Bug 2008926: etcd-storage-test: mark node ready to save it for 5min from cloud provider

### PR DESCRIPTION
**Pull request by sttts**
Upstream runs this as integration test, but we do as e2e. Hence, nodes can be deleted.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
+1

**Comment by dgoodwin** [comment]
+1 from me thank you @sttts

**Comment by aojea** [comment]
the test passed 
```
: [sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial]
```
/retest

**Comment by dgoodwin** [comment]
/lgtm

Worth a shot.

**Comment by sttts** [comment]
Different flakes.

/retest

**Pull request merged**
