### PR TITLE
Remove etcd vertical scaling test.

### PR DESCRIPTION
**Pull request by dgoodwin**
This test is extremely disruptive to the cluster and while lots of work
was done to try to keep invariant tests happy, it has continued to
surface problems that are failing jobs and blocking payloads and code
shipping to the org.

After discussion with etcd team we're agreed this is a bad fit for the
serial suite and will continue to cause problems for any future
invariant checks we add. It should be moved to separate jobs and run on
etcd related pull requests and possibly as a periodic.

Removing to help improve aws-serial pass rates.

[TRT-358](https://issues.redhat.com//browse/TRT-358)

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by dgoodwin** [comment]
> * Can you file a bug (so we can backport this to 4.11)?
> 

I've got bug ready for 4.11: https://bugzilla.redhat.com/show_bug.cgi?id=2101538
Looks like we can't file 4.12 bugs so hopefully that isn't required yet. I'll align the above once I cherry pick over.

>     * It probably doesn't make much of a difference but it's probably a little nicer -- can we add the tests to the broken list with a link to whatever jira or bug we're using to track moving it to it's own suite/job? https://github.com/openshift/origin/blob/master/test/extended/util/annotate/rules.go#L31

I asked twice about what they'd prefer and got no answer, so I'm thinking trust them to handle it when they can, if they want the coverage back. I do not know if it will come back in origin or elsewhere, it may, but it also could end up separate, in which case I'd rather just remove it for now and let them handle it.

**Comment by dgoodwin** [comment]
Apologies i needed a go mod vendor due to the removed code.

**Comment by stbenjam** [comment]
/retitle Bug 2101538: Remove etcd vertical scaling test.

**Pull request merged**
