### PR TITLE
allow image trigger controller to create custom builds

### LINKED ISSUE #17074: chaining builds via imagestreamtags not triggering
I'm trying to start a custom strategy build when an image stream tag changes (chaining builds), but currently this is not working, and the second build never seems to start. Not sure if i'm missing something obvious but it looks like it should work and it's basically the same as things like [openshift-tagger](https://github.com/YannMoisan/openshift-tagger-custom-builder) do it, however whatever I do it doesn't seem to work.

##### Version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce

1. add some root build config that you want to trigger another build from, doesn't matter what.
2. create your chained bc similar to the following, in this case it's using the real image I am trying to use, which will get the latest image stream tag, retag it according to a label in openshift and push it to docker hub (but that shouldn't matter anyway)
 
```
kind: BuildConfig
apiVersion: v1
metadata:
  name: chained-tagger
  labels:
    application: my-project
spec:
  output:
    pushSecret:
      name: docker-hub
  strategy:
    type: "Custom"
    customStrategy:
      exposeDockerSocket: true
      from:
        kind: DockerImage
        name: tomwhiston/openshift-image-tagger
      forcePull: true
      env:
      - name: BUILD_IMAGE
        value: root-image-name
      - name: DEBUG
        value: "true"
      - name: OUTPUT_NAMESPACE
        value: "my-namespace"
      - name: PUSH_CLEANUP
        value: "true"
      - name: PUSH_IMAGE
        value: "true"
  triggers:
  - type: ImageChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: my-project:latest
```
3. trigger root build

##### Current Result

After the root build is completed and the image stream tag is updated (checked with `oc get imagestreamtag`) the chained-tagger build is not triggered

##### Expected Result

chained-tagger build is started

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #17074

### CODE REVIEW

**Comment by jim-minter** [comment]
@smarterclayton @bparees making this change appears to resolve #17074 but I want to confirm with you if it's safe to do or not?
#17074 is somewhat of an echo of #14725, which was resolved in #14792; I think maybe this diff was missing from #14792?

@bparees I'm wondering what test coverage is appropriate for this.  Also is it worth implementing the event that was suggested in #14725?

**Comment by bparees** [comment]
> @bparees I'm wondering what test coverage is appropriate for this. 

we should have an e2e test that verifies ICT triggered builds, it sounds like it needs to test triggering all 4 kinds of builds (s2i, docker, custom, pipeline).


>  Also is it worth implementing the event that was suggested in #14725?

@jim-minter where would we attach the event?  to the buildconfig that we tried to trigger?

**Comment by jim-minter** [comment]
> @jim-minter where would we attach the event? to the buildconfig that we tried to trigger?

That would make sense to me.

**Comment by bparees** [comment]
you can drop the prune flake commit, i believe @miminar's fix has merged.

**Comment by jim-minter** [comment]
@bparees ptal

**Pull request merged**
