### PR TITLE
UPSTREAM: 46315: Fix provisioned GCE PD not being reused if already e…

### PR DESCRIPTION
**Pull request by wongma7**
…xists

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1453078

Had to apply patch manually because gce cloud provider has not been refactored here as it has been upstream.

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by gnufied** [comment]
lgtm

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by smarterclayton** [comment]
Flaked, direct merging.

**Pull request merged**
