### PR TITLE
Add cursor pointer to service component

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@liggitt this was missed from my last commit

**Comment by liggitt** [comment]
Build bindata

**Comment by sg00dwin** [comment]
@liggitt bindata file added

**Comment by liggitt** [comment]
Hmm, bindata diff should only be about 1 line...

**Comment by sg00dwin** [comment]
This sounds like the previous issue I had where the bindata file wasn't being generated correctly, because of some issue. 

I generated another bindata file (following the below commands from jessica, that was a workaround) on the ec2 instance and updated the pull. 

vagrant sync-openshift3 -s --dont-install --no-images
vagrant ssh
cd /data/src/github.com/openshift/origin
hack/build-assets.sh
exit
rsync fedora@<ec2_hostname>:/data/src/github.com/openshift/origin/pkg/assets/bindata.go pkg/assets/bindata.go

**Comment by liggitt** [comment]
[merge]

**Comment by smarterclayton** [comment]
transient [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
