### PR TITLE
move dockerregistry to staging

### PR DESCRIPTION
**Pull request by deads2k**
Moving the dockerregistry to staging and vendoring with glide.

@stevekuznetsov I've got a weird problem at the moment.  if I set `export GOPATH=/home/deads/workspaces/openshift/src/github.com/openshift/origin/staging` and do `go build github.com/openshift/docker-registry/cmd/dockerregistry` it works fine.  If I just run `make WHAT=vendor/github.com/openshift/docker-registry/cmd/dockerregistry` it fails with 
```
vendor/github.com/openshift/docker-registry/vendor/google.golang.org/cloud/storage/acl.go:101: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
vendor/github.com/openshift/docker-registry/vendor/google.golang.org/cloud/storage/acl.go:174: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
```

any ideas?

### CODE REVIEW

**Comment by bparees** [comment]
@miminar @dmage @legionus fyi

**Comment by dmage** [comment]
After merge, the master copy will live at `./staging/src/github.com/openshift/docker-registry`, right?

**Comment by deads2k** [comment]
> After merge, the master copy will live at ./staging/src/github.com/openshift/docker-registry, right?

Correct.  With a vendor folder maintained by glide and pruned by dep.  I think the only thing blocking this is the compile problem.

**Comment by dmage** [comment]
@deads2k we have old [modules in google.golang.org](https://github.com/openshift/origin/tree/38e59cf61dcd3a1510e945c8dbaba76847bf75d4/vendor/github.com/docker/distribution/vendor).

**Comment by deads2k** [comment]
Alright, I think I solved the build problem. If this works, I think this is the first step and the second is to switch over to use `openshift/client-go` which will *hopefully* let us snip some of the conflict vendor folders in this subsection of the product.

**Comment by dmage** [comment]
"github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/**github.com/docker/libtrust**".PrivateKey does not implement "github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/**github.com/docker/distribution/vendor/github.com/docker/libtrust**".PrivateKey (wrong type for PublicKey method)

**Comment by deads2k** [comment]
Well, I now have a stupid problem.

```
[deads@deads-02 origin]$ hack/test-integration.sh 
++ Building go targets for linux/amd64: test/integration/integration.test
[INFO] hack/build-go.sh exited with code 0 after 00h 00m 56s
[INFO] [CLEANUP] Cleaning up temporary directories
--- FAIL: TestIntegration (0.05s)
    --- FAIL: TestIntegration/TestV2RegistryGetTags (0.26s)
    	runner_test.go:123: FAILED TestV2RegistryGetTags, retrying:
    		panic: http: multiple registrations for /debug/requests
    		
    		goroutine 1 [running]:
    		net/http.(*ServeMux).Handle(0x11611500, 0x6f92220, 0xf, 0xf5c11a0, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2254 +0x610
    		net/http.(*ServeMux).HandleFunc(0x11611500, 0x6f92220, 0xf, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2286 +0x55
    		net/http.HandleFunc(0x6f92220, 0xf, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2298 +0x4b
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace.init.1()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace/trace.go:122 +0x42
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace/trace.go:1080 +0x1cd
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/grpc.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/grpc/trace.go:121 +0x5f
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/internal/opts.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/internal/opts/option.go:25 +0x4e
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/option.go:101 +0x58
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/registry/storage/driver/gcs.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go:874 +0xa5
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/pkg/cmd/dockerregistry.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/pkg/cmd/dockerregistry/dockerregistry.go:394 +0xc8
    		github.com/openshift/origin/test/integration.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/test/integration/webhook_test.go:699 +0x258
    		main.init()
    			github.com/openshift/origin/test/integration/_test/_testmain.go:428 +0x53
    	runner_test.go:119: panic: http: multiple registrations for /debug/requests
    		
    		goroutine 1 [running]:
    		net/http.(*ServeMux).Handle(0x11611500, 0x6f92220, 0xf, 0xf5c11a0, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2254 +0x610
    		net/http.(*ServeMux).HandleFunc(0x11611500, 0x6f92220, 0xf, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2286 +0x55
    		net/http.HandleFunc(0x6f92220, 0xf, 0x7220b00)
    			/home/deads/.gvm/gos/go1.8.3/src/net/http/server.go:2298 +0x4b
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace.init.1()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace/trace.go:122 +0x42
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/golang.org/x/net/trace/trace.go:1080 +0x1cd
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/grpc.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/grpc/trace.go:121 +0x5f
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/internal/opts.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/internal/opts/option.go:25 +0x4e
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/vendor/google.golang.org/cloud/option.go:101 +0x58
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/registry/storage/driver/gcs.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go:874 +0xa5
    		github.com/openshift/origin/vendor/github.com/openshift/docker-registry/pkg/cmd/dockerregistry.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/vendor/github.com/openshift/docker-registry/pkg/cmd/dockerregistry/dockerregistry.go:394 +0xc8
    		github.com/openshift/origin/test/integration.init()
    			/home/deads/workspaces/openshift/src/github.com/openshift/origin/test/integration/webhook_test.go:699 +0x258
    		main.init()
    			github.com/openshift/origin/test/integration/_test/_testmain.go:428 +0x53
    		
FAIL

```

Turns out that if you accidentally have paths to two different vendored copies of `golang.org/x/net/trace` your process will panic at runtime because of course it would.  The simplest "solution" at the moment is just to remove the one needed to compile in docker-registry until we've split the tests.  I may do that.

**Comment by deads2k** [comment]
cloud provision

/retest

**Comment by deads2k** [comment]
Given my vendoring problems, I think I'm going to give in and only have external types in the client.  I think its a real shame to not have a hubbed version for people to use for version independence and easy handling, but I can't seem to find a way to half-strip vendor dependencies for people and pulling in all of kube to get the internal types and conversion is sub-par.

@mfojtik @sttts want to try to talk me out of it?

**Comment by sttts** [comment]
About pruning the vendor/ folder:

- https://github.com/rancher/trash
- https://github.com/sgotti/glide-vc

Maybe they are lighter in runtime than dep.

**Comment by dmage** [comment]
Any news?

**Comment by deads2k** [comment]
> Any news?

golang vendoring is awful.

This is on hold until we get a 3.8 client-go.  Way too risky for 3.7. :(

**Pull request closed without merging**
