### PR TITLE
ImageStreamImage/ImageRepositoryTag virtual rsrcs

### PR DESCRIPTION
**Pull request by ncdc**
Add ImageStreamImage and ImageRepositoryTag virtual resources so you can
get them via `osc get` and `osc describe`.

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton can we do something like this?
[test]

**Comment by smarterclayton** [comment]
Lgtm

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
Transient ec2 issue in previous merge failure.

[merge]

**Pull request merged**
