### PR TITLE
UPSTREAM: 25537: e2e make ForEach fail if filter is empty, fix no-op tests

### PR DESCRIPTION
**Pull request by derekwaynecarr**
https://github.com/kubernetes/kubernetes/pull/25537

/cc @smarterclayton @pweil-

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
actually, waitFor is not in the code in origin yet, so need to pull those out.

**Comment by derekwaynecarr** [comment]
ok, i think this should be fine... we can't pull the waitFor pieces until we have the new framework, but this has the log line pieces.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Didn't fix it

On May 12, 2016, at 6:30 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/3792/)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/8870#issuecomment-218904471>

**Comment by pweil-** [comment]
Do you still need to pull in the first commit (https://github.com/kubernetes/kubernetes/pull/25537/commits/5f0d1f04b8c10064498ae5ee53adc763bc718673)?  The `framework/util.go` isn't in our dep yet but `util.go` exists so it would need to be a backport.

**Comment by smarterclayton** [comment]
We need this fixed asap

On May 13, 2016, at 8:22 AM, Paul Weil <notifications@github.com> wrote:

Do you still need to pull in the first commit (kubernetes/kubernetes@5f0d1f0
<https://github.com/kubernetes/kubernetes/pull/25537/commits/5f0d1f04b8c10064498ae5ee53adc763bc718673>)?
The framework/util.go isn't in our dep yet but util.go exists so it would
need to be a backport.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/8870#issuecomment-219028124>

**Comment by derekwaynecarr** [comment]
@pweil- @smarterclayton - updated.  marking for [test]

**Comment by smarterclayton** [comment]
Thanks

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
