### PR TITLE
stop skipping build valuefrom test on gce

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@coreydaley ptal.  I can't remember why we needed this one test in particular to be skipped before, but i assume now that we have updated tagged images we don't need to skip it anymore?

/test extended_builds

**Comment by deads2k** [comment]
> /lgtm (don't know whether this is necessary or not)

@jim-minter it is.  `/approve` is used either like a second vote of "lgtm" or (since ben is has top level powers) an "I agree this is a good idea, but I haven't looked at it in any detail".  Nothing merges without at least one lgtm.

**Comment by coreydaley** [comment]
@bparees yep, that was why we were skipping it, since the gce tests don't build new images. 

/lgtm

**Comment by bparees** [comment]
well the GCE test passed, that's a good sign.
/retest

**Pull request merged**
