### PR TITLE
UPSTREAM: add flattening and minifying options to config view #6761

### PR DESCRIPTION
**Pull request by deads2k**
@derekwaynecarr This pulls in https://github.com/GoogleCloudPlatform/kubernetes/pull/6761.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
UI re[merge]

**Comment by deads2k** [comment]
image pull failure re[merge]

**Comment by deads2k** [comment]
bind already in use re[merge]

**Comment by liggitt** [comment]
For posterity:
```
I0415 12:58:09.021149   20937 net.go:39] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc208c228a0), Err:0x6f}, trying again: "127.0.0.1:55393"
F0415 12:58:09.146409   20937 master.go:450] listen tcp 127.0.0.1:55393: bind: address already in use
```

**Comment by derekwaynecarr** [comment]
One step closer....

@sallyom we should talk about how we can start to use this stuff

**Pull request merged**
