### PR TITLE
OCPBUGS-38359: NetworkSegmentation tests: fix the IPv6 node IP detection

### PR DESCRIPTION
**Pull request by kyrtapz**
Internal IPs are exact addresses so the previous IP family check always returned false.

### CODE REVIEW

**Comment by kyrtapz** [comment]
NetworkSegmentation tests passed in dualstack and ipv6 jobs.

**Comment by stbenjam** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6 openshift/api#1997
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm openshift/api#1997

**Comment by stbenjam** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6 openshift/api#1997
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm openshift/api#1997

**Comment by kyrtapz** [comment]
Both [metal-ipi-ovn-bm](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-api-1997-openshift-origin-28997-nightly-4.18-e2e-metal-ipi-ovn-bm/1823347616511954944)  and [metal-ipi-ovn-ipv6](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-api-1997-openshift-origin-28997-nightly-4.18-e2e-metal-ipi-ovn-ipv6/1823344687663026176#1:build-log.txt%3A30) passed. 
e2e-aws-ovn-serial is a known issue discussed here: https://redhat-internal.slack.com/archives/C01CQA76KMX/p1723563363417759
/test e2e-aws-ovn-fips

**Pull request merged**
