### PR TITLE
resync openshift-sdn

### PR DESCRIPTION
**Pull request by danwinship**
Picks up
https://github.com/openshift/openshift-sdn/pull/186,
https://github.com/openshift/openshift-sdn/pull/189, and
https://github.com/openshift/openshift-sdn/pull/188

Closing
https://bugzilla.redhat.com/show_bug.cgi?id=1272295 and
https://bugzilla.redhat.com/show_bug.cgi?id=1273659

(openshift-sdn's pkg/firewalld is removed because kubernetes's pkg/util/iptables now has firewalld support after the last rebase)

@pravisankar

### CODE REVIEW

**Comment by pravisankar** [comment]
[merge]

**Comment by danwinship** [comment]
[test]

**Comment by pravisankar** [comment]
[test] again

**Comment by danwinship** [comment]
The travis-ci failure seems like a travis-ci problem. The tests pass fine locally (and travis is failing in a k8s test that this branch doesn't modify).

**Comment by pravisankar** [comment]
re[test]

**Comment by pravisankar** [comment]
[mege]

**Comment by pravisankar** [comment]
[merge]

**Comment by eparis** [comment]
travis CI:
```
--- FAIL: TestForwardPorts-2 (0.06s)
	portforward_test.go:269: forward 2 ports with bidirectional data: server expected to receive "ghij", got "" for port 6000
E1026 17:14:51.897723   10495 portforward.go:353] error copying from local connection to remote stream: write tcp 127.0.0.1:57297: broken pipe
I1026 17:14:51.899349   10495 portforward.go:244] Forwarding from 127.0.0.1:5555 -> 5555
I1026 17:14:51.899555   10495 portforward.go:244] Forwarding from [::1]:5555 -> 5555
E1026 17:14:51.905267   10495 portforward.go:230] Unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use
E1026 17:14:51.905365   10495 portforward.go:230] Unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use
W1026 17:14:51.905421   10495 portforward.go:169] Unable to listen on port 5555: All listeners failed to create with the following errors: listen tcp4 127.0.0.1:5555: bind: address already in use, listen tcp6 [::1]:5555: bind: address already in use
FAIL
```

**Comment by eparis** [comment]
Both Jenkins jobs complained about not being able to find `Error from server: imageStreamTag "mysql:latest" not found` Not how this one is to blame for that....

**Comment by danwinship** [comment]
AFAICT neither the jenkins failure nor the travis failure is related to this PR

**Comment by eparis** [comment]
Can you spend a few minutes trying to figure out why something was on port 5555 in travis? We certainly don't want that to keep biting us or others...

**Comment by eparis** [comment]
[merge]

**Pull request merged**
