### PR TITLE
Remove patch for sa public key configuration

### PR DESCRIPTION
**Pull request by marun**
Upstream already supports providing multiple keys in multiple files.

### CODE REVIEW

**Comment by stlaz** [comment]
```
# github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator
vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go:4:2: imported and not used: "fmt"
vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go:17:2: imported and not used: "github.com/openshift/origin/vendor/k8s.io/client-go/util/keyutil"
```

**Comment by marun** [comment]
> # github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator
> vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go:4:2: imported and not used: "fmt"
> vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go:17:2: imported and not used: "github.com/openshift/origin/vendor/k8s.io/client-go/util/keyutil"

Thanks! I was too lazy to discover how to do a trivial build in the repo, and left it to CI. And then every single CI job failed for an unrelated reason. :/

**Comment by stlaz** [comment]
lol, it's fine, actually just running `make` should build you hyperkube, no need to go all the way to building images

**Comment by marun** [comment]
Ugh... aws failures are due to unrelated docker build failure and gcp failures are due to a previously-ported quota issue.

**Pull request merged**
