### PR TITLE
setup binary input for custom builds properly

### PR DESCRIPTION
**Pull request by bparees**
bug 1560661

https://bugzilla.redhat.com/show_bug.cgi?id=1560661

### CODE REVIEW

**Comment by bparees** [comment]
@wozniakjan ptal

**Comment by wozniakjan** [comment]
I can reproduce the original issue but when I swap `openshift` binary with the one build from this source, I get
```
Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "docker-registry-1-9cbh4_default" network: CNI request failed with status 400: 'missing HostVeth
```

I am pretty sure it has nothing to do with your change and is a problem of my test environment, but at the moment, I am unable to validate it works

**Comment by bparees** [comment]
> I am pretty sure it has nothing to do with your change and is a problem of my test environment, but at the moment, I am unable to validate it works

fyi in general on PR reviews you're not being asked to test the fix, just validate that the code change looks reasonable, appears to address what it says it is addressing, and make any suggestions you might have about a better approach, potential pitfalls, etc.

Testing this fix is particularly problematic (independent of the issue you ran into) because it requires a custom builder image that is reading from stdin to consume the binary input content.

**Comment by wozniakjan** [comment]
> Testing this fix is particularly problematic (independent of the issue you ran into) because it requires a custom builder image that is reading from stdin to consume the binary input content.

that part I managed, I think, it is testing the new, built from source, openshift binary that was giving me a hard time

> fyi in general on PR reviews you're not being asked to test the fix, just validate that the code change looks reasonable, appears to address what it says it is addressing, and make any suggestions you might have about a better approach, potential pitfalls, etc.

in that case /lgtm

**Comment by bparees** [comment]
@wozniakjan commands have to be on their own line.

**Pull request merged**
