### PR TITLE
fabiano no longer a thing

### PR DESCRIPTION
**Pull request by fabianofranz**
Removes me from lists of reviewers and approvers.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
😢 
/lgtm

**Comment by juanvallejo** [comment]
Hm, I'm seeing this same test failure in my PR:
```
/go/src/github.com/openshift/origin/hack/lib/build/binaries.sh: line 22: go: command not found
/go/src/github.com/openshift/origin/hack/lib/build/binaries.sh: line 22: go: command not found
[FATAL] Required `go` binary was not found in $PATH.
[ERROR] PID 6: hack/lib/build/binaries.sh:155: `local -a binaries=("$@")` exited with status 1.
```

**Comment by stevekuznetsov** [comment]
Yeah, should be fixed now.

/retest

**Pull request merged**
