### PR TITLE
Better error message when JavaScript is disabled

### PR DESCRIPTION
**Pull request by jawnsy**
This change provides a more descriptive error message when JavaScript
is disabled, including a link to a web site that explains how to enable
JavaScript in various browsers.  It also provides information about
alternatives (i.e. to use the command-line client.)

Closes: #8076

Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by jwforres** [comment]
realized from this that with our navigation changes we now no longer have any openshift branding on this page when you dont have JS enabled, @sg00dwin is going to take a look at that and contribute a follow-on change to this

@jawnsy your bindata.go diff doesn't look right, run clean-assets/install-assets/build-assets again, we picked up a new version of uglifyjs a week or so ago, thats probably why

**Comment by sg00dwin** [comment]
@jawnsy opened a pull request to your branch that adds a branded header. https://github.com/jawnsy/origin/pull/1

cc @jwforres

**Comment by jawnsy** [comment]
Merged in @sg00dwin's change (thanks!) and amended both commits with the results of bindata, so that both commits are independently buildable (helpful if doing a `git bisect`.)

Screenshot on Chrome, looking nifty:

screenshot from 2016-03-23 10-28-06

However when the vertical height is low, some of the message gets cut off:

screenshot from 2016-03-23 10-29-36

**Comment by jwforres** [comment]
so discussed this with @spadgett and there are concerns with linking to that website that is out of our control, particularly from an enterprise perspective.  the message and style changes are still good to do, if we can resolve the one issue with it getting cut off

**Comment by jawnsy** [comment]
> there are concerns with linking to that website that is out of our control

Yeah, I can understand that. It seemed reasonably trustworthy given the list of authors, but you never know what will happen to the site or the domain in the future (e.g. if the owners decide to stop renewing it, and it gets registered by someone else.)

It really depends on whether we expect people to know how to enable JavaScript; I guess it could be argued that, since most browsers enable JS out-of-the-box, users would know how to re-enable it (since they would've had to explicitly disable it.) And if they're using an extension like NoScript, they would know how to disable it.

@jwforres Should I keep the lightened `background-color` style? It won't be necessary anymore without the link in there, since there are no contrast issues otherwise.

Also my CSS-fu is pretty weak, if you have tips for preventing the overlap, let me know. Otherwise I guess I'll play with `margin-top` and `padding-top` type settings.

**Comment by jwforres** [comment]
@sg00dwin can you look at the overlap issue?

I think the lighter color is still fine, it makes the contrast with the
text a little better

**Comment by jawnsy** [comment]
@jwforres Hey, I tried my hand at fixing the overlap issue (amended @sg00dwin's commit) by:

* Removing `top: 20%`
* Adding `margin-top: 100px` (the header bar is always 70px or so because it has `min-height: 50px; margin-bottom: 21px`)
* Changing the `transform` to `transformX(-50%)` so that it no longer tries to center along the y-axis.

Here's what it looks like in Firefox:

screenshot from 2016-03-23 17-22-33

Chrome:

screenshot from 2016-03-23 17-20-21

You can still get weird behaviour if you shrink the viewport *very* small and scroll, but I think that's enough of a corner case that it wouldn't be an issue.

screenshot from 2016-03-23 17-26-34

**Comment by jwforres** [comment]
check how it looks at mobile resolution

**Comment by jwforres** [comment]
@jawnsy is what is currently in the PR what your latest screenshots show?  i think we are fine with that, its such an edge case.  @sg00dwin checked mobile already and said it looks fine there

**Comment by jawnsy** [comment]
@jwforres Yep, the latest screenshots show what is in the latest PR. Do you know if @sg00dwin checked on mobile before, or after, my changes? Because I might have broken mobile with my attempt to prevent the overlap. I haven't had a chance to check with Chrome's dev tools/mobile emulator yet.

**Comment by jawnsy** [comment]
Screenshots of mobile from the latest PR contents (using Chrome's simulator tool)

screenshot from 2016-03-24 14-07-45
screenshot from 2016-03-24 14-07-37
screenshot from 2016-03-24 14-07-30

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
