### PR TITLE
sdn: garbage-collect dead containers to recover IPAM leases

### PR DESCRIPTION
**Pull request by dcbw**
Cherry-pick of https://github.com/openshift/origin/pull/11964 to release-1.4

### CODE REVIEW

**Comment by dcbw** [comment]
@openshift/networking @knobunc

**Comment by knobunc** [comment]
[test]

**Comment by knobunc** [comment]
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1395183

**Comment by knobunc** [comment]
Known, unrelated, flake: https://github.com/openshift/origin/issues/11685

All relevant tests passed.  [merge]

**Comment by knobunc** [comment]
[merge] flaked https://github.com/openshift/origin/issues/10988

**Pull request merged**
