### PR TITLE
Merge scc_validation_test.go into validation_test.go

### PR DESCRIPTION
**Pull request by php-coder**
Merge tests for `validation.go` into a single file `validation_test.go`. Prior this change it was counter-intuitive that some tests were reside in a different file.

PTAL @pweil- @deads2k 
CC @simo5

### CODE REVIEW

**Comment by deads2k** [comment]
straight move?
/lgtm
/retest-not-required

**Comment by php-coder** [comment]
> straight move?

@deads2k Yes.

**Comment by php-coder** [comment]
Tests failed with error 
```
--- FAIL: TestRouter (0.01s)
	router_test.go:75: Error starting container openshift/origin-haproxy-router : no such image
```
that is caused by:
```
[openshift/origin-egress-router] Trying other mirror.
[openshift/origin-egress-router] https://mirror.csclub.uwaterloo.ca/fedora/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
[openshift/origin-egress-router] Trying other mirror.
[openshift/origin-egress-router]  One of the configured repositories failed (Extra Packages for Enterprise Linux 7 - x86_64),
[openshift/origin-egress-router]  and yum doesn't have enough cached data to continue. At this point the only
[openshift/origin-egress-router]  safe thing yum can do is fail. There are a few ways to work "fix" this:
[openshift/origin-egress-router]      1. Contact the upstream for the repository and get them to fix the problem.
[openshift/origin-egress-router]      2. Reconfigure the baseurl/etc. for the repository, to point to a working
[openshift/origin-egress-router]         upstream. This is most often useful if you are using a newer
[openshift/origin-egress-router]         distribution release than is supported by the repository (and the
[openshift/origin-egress-router]         packages for the previous distribution release still work).
[openshift/origin-egress-router]      3. Run the command with the repository temporarily disabled
[openshift/origin-egress-router]             yum --disablerepo=epel ...
[openshift/origin-egress-router]      4. Disable the repository permanently, so yum won't use it by default. Yum
[openshift/origin-egress-router]         will then just ignore the repository until you permanently enable it
[openshift/origin-egress-router]         again or use --enablerepo for temporary usage:
[openshift/origin-egress-router]             yum-config-manager --disable epel
[openshift/origin-egress-router]         or
[openshift/origin-egress-router]             subscription-manager repos --disable=epel
[openshift/origin-egress-router]      5. Configure the failing repository to be skipped, if it is unavailable.
[openshift/origin-egress-router]         Note that yum will try to contact the repo. when it runs most commands,
[openshift/origin-egress-router]         so will have to try and fail each time (and thus. yum will be be much
[openshift/origin-egress-router]         slower). If it is a very temporary problem though, this is often a nice
[openshift/origin-egress-router]         compromise:
[openshift/origin-egress-router]             yum-config-manager --save --setopt=epel.skip_if_unavailable=true
[openshift/origin-egress-router] failure: repodata/repomd.xml from epel: [Errno 256] No more mirrors to try.
```

/test end_to_end

**Comment by php-coder** [comment]
>  /retest-not-required

It didn't work.

@stevekuznetsov Does our bot support this command?

**Comment by php-coder** [comment]
Problems with mirrors:
```
Failure summary:

  1. Host:     localhost
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "package_version":
               MODULE FAILURE
               
               check "docker_image_availability":
               Some dependencies are required in order to check Docker image availability.
               Unable to install required packages on this host:
                   skopeo,
                   python-docker-py
               Failure talking to yum: failure: repodata/repomd.xml from rhel-7-server-ose-3.3-rpms: [Errno 256] No more mirrors to try.
               https://mirror.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               
               check "docker_storage":
               Some dependencies are required in order to query docker storage on host:
               Unable to install required packages on this host:
                   python-docker-py
               Failure talking to yum: failure: repodata/repomd.xml from rhel-7-server-ose-3.3-rpms: [Errno 256] No more mirrors to try.
               https://mirror.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/latest/RH7-RHAOS-3.3/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

/test extended_conformance_install_update

**Pull request merged**
