### PR TITLE
add initial delay to probe to allow router time to come up

### PR DESCRIPTION
**Pull request by pweil-**
See:  https://github.com/openshift/origin/issues/1504#issuecomment-88945808

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by sdodson** [comment]
:+1: I believe I tested this manually and it didn't fix the problem but my environment likely suffered from https://github.com/GoogleCloudPlatform/kubernetes/pull/6110 at the time so it may have been an invalid test. I used 10s

**Comment by jimmidyson** [comment]
@sdodson - i've just tried it manually & it looks like a problem with the liveness probe functionality actually. Pod is terminated by failed liveness probe but even with initial delay set to 10s the container is terminated < 10s after it's started.

So this PR doesn't fix the underlying problem sadly,

**Comment by pweil-** [comment]
ugh...well so much for that

**Comment by jimmidyson** [comment]
I've done a watch curl... on the router pod & get connection refused up until liveness probe kills it so it could just be very slow to start up... playing with increasing initial probe delay now.

**Comment by pweil-** [comment]
ok, let me know what you're seeing and I'll modify this to match if a good number is found.  

One other thing I just though of, you could try stopping openshift, starting one of the failed containers manually, nsenter it and run the reload script in /var/lib/haproxy.  If it is a config issue then that script should error.  

Of note, the reload script is only run after a commit on a service/route but there should always be the default master service for it to pull in.

**Comment by jimmidyson** [comment]
Well 60 seconds works fine... not sure why it takes so long to start up of course.

**Comment by pweil-** [comment]
I think I may have figured it out.  If the probe starts prior to a watch event for one of the default services being consumed it will not see the router as started since the reload script has not yet been run.

I was able to do this on my local machine:

1.  Start openshift
1.  Create a router
1.  See bad routers in docker ps -a
1.  Kill openshift
1.  Manually start the docker container for a bad router
1.  Checkout /var/lib/containers/router (no routes.json)
1.  Checkout /var/lib/haproxy/conf haproxy.config is 0 bytes

@jimmidyson can you confirm that you see the same thing?  If so I think we can permanently fix this with a) a call to commit when the plugin starts to get it going and b) providing a default haproxy config that can be used pre-consumption of events

**Comment by pweil-** [comment]
although I really though 5-10 seconds would be just fine.  Maybe in the event of a pull the timestamp of creation (k8s uses the createdAt timestamp but I only looked briefly in the kubelet) earlier than when the container is actually created so it starts probing immediately instead of 10 seconds AFTER it has really started

**Comment by pweil-** [comment]
> although I really though 5-10 seconds would be just fine. Maybe in the event of a pull the timestamp of creation (k8s uses the createdAt timestamp but I only looked briefly in the kubelet) earlier than when the container is actually created so it starts probing immediately instead of 10 seconds AFTER it has really started

Wow, that was one mangled sentence.  What I meant to say is: perhaps the k8s timestamp of creation does not accurately reflect when the actual docker container started so it ends up passing the initialDelaySeconds earlier than expected, especially in the case of pulling an image.  I only could reproduce this when I removed the image from docker and it had to re-pull it.

**Comment by jimmidyson** [comment]
I think it is just slow at starting haproxy tbh. Starting haproxy with a default haproxy config would be easiest I think.

**Pull request closed without merging**
