### PR TITLE
Invalidate discovery cache before migration commands

### PR DESCRIPTION
**Pull request by enj**
This change updates the migration commands to invalidate and refetch the cached discovery information on disk.  This makes it so that the REST mapper will never use stale discovery data.

Signed-off-by: Monis Khan <mkhan@redhat.com>

/assign @deads2k @smarterclayton

### CODE REVIEW

**Comment by enj** [comment]
@deads2k so this is an attempt to address some of the weird issues that @sdodson has seen during some upgrades that may be caused by stale discovery data.  In my last conversation with @smarterclayton he pointed out that we should have a more general approach to getting the latest discovery information (something like `--latest` for CLI commands backed by some `Latest` method on the discovery interface).  Is there any established convention on this upstream?

cc @openshift/cli-review

**Comment by deads2k** [comment]
As long as you know it's racy since you're dealing with files on disk, I'm ok with it.

**Pull request merged**
