### PR TITLE
default resolution rule policy to the imagepolicy default

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/19775

### CODE REVIEW

**Comment by bparees** [comment]
actually there are two issues/questions w/ the original code:

1) the policy defaulting was only being applied if no resolution rules were explicitly defined by the user
2) the policy defaulting is only being applied to resolution rules that are covered by an execution rule

this PR changes both of those (defaults all resolution rules, does not look at execution rule coverage), but perhaps the right solution is to just fix (1) (apply defaulting to all resolution rules, but only if an execution rule covers them).  @smarterclayton I need the reasoning behind the covering logic.

**Comment by bparees** [comment]
@GrahamDumpleton fyi

**Comment by liggitt** [comment]
I *think* the current behavior stemmed from this: https://github.com/openshift/origin/pull/15868#issuecomment-324164912

**Comment by smarterclayton** [comment]
This was to preserve back compat with 3.6.  It is *very* possible any
changes here could break running applications.

I’m tempted to say we put a hold on changes to the api until we move this
to an operator logic and then migrate all existing config to an api object,
dropping support for the old config (or letting it be left in legacy mode).



On May 19, 2018, at 11:39 AM, Ben Parees <notifications@github.com> wrote:

actually there are two issues/questions w/ the original code:

   1. the policy defaulting was only being applied if no resolution rules
   were explicitly defined by the user
   2. the policy defaulting is only being applied to resolution rules that
   are covered by an execution rule

this PR changes both of those (defaults all resolution rules, does not look
at execution rule coverage), but perhaps the right solution is to just fix
(1) (apply defaulting to all resolution rules, but only if an execution
rule covers them). @smarterclayton <https://github.com/smarterclayton> I
need the reasoning behind the covering logic.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/19766#issuecomment-390413061>,
or mute
the thread

**Comment by bparees** [comment]
>  This was to preserve back compat with 3.6.  It is *very* possible any changes here could break running applications.

Can we agree that if, after applying the existing defaulting logic (which is only applied to the default resolution rules), there is a resolution rule w/ no policy set(that would be one explicitly defined by the user), we should set that resolution rule's policy to the global default?

If we do not do that, the configuration is invalid and the cluster fails to start, so there should be no risk of changing existing behavior for a working cluster, it just ensures that someone who, in the future, writes a configuration that relies on the documented defaulting behavior, will get a working cluster and not a validation error.

**Comment by bparees** [comment]
(i've updated the PR to reflect that proposal)

**Comment by bparees** [comment]
> Are you confident this can't accidentally regress deployed 3.9 clusters when they upgrade?

From what i understand (which is worth sanity checking), if someone manually defined a resolution rule and did not define a policy for it, it will fail validation (policy is a required field).  So any configurations this would affect are already invalid/failing to start.  The intent here is just to help people who write a new config going forward.

**Comment by bparees** [comment]
@smarterclayton beginning of 3.11 feels like a good time to merge this...

**Comment by bparees** [comment]
/hold cancel

@smarterclayton @liggitt i'm feeling pretty good about this, have i convinced you?

**Comment by liggitt** [comment]
> From what i understand (which is worth sanity checking), if someone manually defined a resolution rule and did not define a policy for it, it will fail validation (policy is a required field). So any configurations this would affect are already invalid/failing to start. The intent here is just to help people who write a new config going forward.

and we want to default the half they didn't specify? is that going to cause us problems if those defaults change in the future, and the changes don't mesh with the resolution rule they provided?

**Comment by bparees** [comment]
> and we want to default the half they didn't specify? is that going to cause us problems if those defaults change in the future, and the changes don't mesh with the resolution rule they provided?

The api docs indicate that if the rule itself doesn't specify a value, the default value is pulled from the global policy setting(which is set by them).  However the implementation didn't actually do that. 
(instead you'd get an error indicating the value was required).  

The sole purpose of this PR is to bring the behavior in line w/ the api doc.  If we think the api doc behavior is not what we want, we can change the api docs and require that you always specify a policy for every rule, instead of allowing there to be a global policy that the rules inherit, but the global policy that is inherited by the rules by default seemed like a reasonable behavior to me.

I wouldn't think we'd be allowed to change the defaults (which in this case would be the default global policy, I guess).

**Comment by liggitt** [comment]
> The api docs indicate that if the rule itself doesn't specify a value, the default value is pulled from the global policy setting(which is set by them). However the implementation didn't actually do that.
(instead you'd get an error indicating the value was required).
> 
> The sole purpose of this PR is to bring the behavior in line w/ the api doc.

Ok. 

> I wouldn't think we'd be allowed to change the defaults (which in this case would be the default global policy, I guess).

Clayton will have to refresh my memory… I thought new types could get default rules added for them

**Comment by bparees** [comment]
for reference this is the current api doc:
https://github.com/openshift/origin/blob/dd68e3fc28d543ebec06f320e905abb555307c75/pkg/image/admission/apis/imagepolicy/types.go#L60-L62

**Comment by bparees** [comment]
technically i guess it doesn't say it inherits the global default if not specified, but the claim that it "overrides it" would imply that it's optional/uses the global value normally.

**Comment by bparees** [comment]
> Clayton will have to refresh my memory… I thought new types could get default rules added for them

@liggitt new types of what? this change only affects resolutionrules (e.g. not executionrules and not necessarily a new type of rule if we introduced one).

**Comment by liggitt** [comment]
> @liggitt new types of what? this change only affects resolutionrules (e.g. not executionrules and not necessarily a new type of rule if we introduced one).

I misread the defaulting... if they specify any resolution rules, we don't contribute any of the default ones, which might expand to include rules for new resource types in the future.

> However the implementation didn't actually do that. (instead you'd get an error indicating the value was required).

does that mean that someone that doesn't specify any resolution rules gets an error? the defaults here don't set a policy value:

https://github.com/openshift/origin/blob/dab335cdf67c7cc29be8d7206583952dc447e033/pkg/image/admission/apis/imagepolicy/v1/defaults.go#L24-L34

**Pull request merged**
