### PR TITLE
Add logging to project request failures

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k @abhgupta logs errors if the initial project creation fails with an unexpected error

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
[merge]

**Comment by abhgupta** [comment]
@liggitt Are you planning on cherry-picking this fix into OCP 3.3 ?

**Comment by liggitt** [comment]
picking it would probably be good

**Pull request merged**
