### PR TITLE
sync excluder sections in spec with master

### PR DESCRIPTION
**Pull request by ingvagabund**
ssia

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM

**Comment by sdodson** [comment]
[merge][severity: blocker]

**Comment by stevekuznetsov** [comment]
LGTM

**Comment by ingvagabund** [comment]
@stevekuznetsov not sure if it CI failures are related to the PR

**Comment by stevekuznetsov** [comment]
The build on backport branches is broken right now, @kargakis is fixing it

**Comment by sdodson** [comment]
> The build on backport branches is broken right now, @kargakis is fixing it

Fixed within the next day or two or will it take longer?

**Comment by stevekuznetsov** [comment]
Will merge and roll out today https://github.com/openshift/aos-cd-jobs/pull/314/

**Comment by kargakis** [comment]
[test]

**Comment by sdodson** [comment]
I see what you did there, sneaky.

**Comment by kargakis** [comment]
lol

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/14493 [test]

**Comment by ingvagabund** [comment]
@stevekuznetsov any idea what is wrong now? Or just re-run the merge?

**Comment by kargakis** [comment]
[test]

**Comment by sdodson** [comment]
[test]

**Pull request closed without merging**
