### PR TITLE
pick --raw for oc get

### PR DESCRIPTION
**Pull request by deads2k**
This allows us to gather metrics by telling someone to run `oc get --raw /metrics` instead of having them trying to specify curl CA and client key/cert pairs.

Straightforward pick.  @fabianofranz in case you want a quick look.

### CODE REVIEW

**Comment by fabianofranz** [comment]
LGTM [test]

**Comment by fabianofranz** [comment]
@deads2k looks good, merge at will. @smarterclayton

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
Device mapper https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8287/ re[merge]

**Comment by stevekuznetsov** [comment]
This is really great! We can finally get rid of all of that pretty obtuse `curl` usage

**Pull request merged**
