### PR TITLE
oc: ConfigMap build sources

### PR DESCRIPTION
**Pull request by adambkaplan**
oc extensions from #19655 

Separate PR to allow for oc rebase/refactor.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold
for rebase

**Comment by adambkaplan** [comment]
@deads2k please cancel hold once oc is ready to accept new features

**Comment by adambkaplan** [comment]
[(5) Allow using a ConfigMap as an input to a build [builds]](https://trello.com/c/RMKJxJUm/1020-5-allow-using-a-configmap-as-an-input-to-a-build-builds)

**Comment by bparees** [comment]
@adambkaplan can you rebase this so the extra commits go away?

**Comment by adambkaplan** [comment]
@bparees rebased

**Comment by adambkaplan** [comment]
/retest

Potentially impacted by flake #20149

**Comment by adambkaplan** [comment]
/retest

Flake #20168

**Pull request merged**
