### PR TITLE
deploy: drop unnecessary resource handlers to reduce dc requeues

### PR DESCRIPTION
**Pull request by kargakis**
No reason to enqueue deployment configs on rc ADDs since there is no
new info deployment configs don't know at that point (adoption is not
possible). No reason to enqueue on pod ADDs since the only reasons we
need pod notification are 1) to bring back DELETEd pods and 2) to
update the deployment config status with AvailableReplicas once a pod
is UPDATEd to Ready/Available.

cc: @mfojtik @smarterclayton 

[test]

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
Can somebody from @openshift/team-origin-committers rekick Jenkins?

**Comment by soltysh** [comment]
@kargakis no need for it, just need to link flake ;)

Flake https://github.com/openshift/origin/issues/12116

[test]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM since adoption is not possible.

[merge]

**Comment by kargakis** [comment]
flake is https://github.com/openshift/origin/issues/12157

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/12184 [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/8571 [merge]

**Pull request merged**
