### PR TITLE
Use relative URIs in create flow links

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1236471

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by spadgett** [comment]
Hm.

```
Running "protractor:phantomjs" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.229.74.162:49247/wd/hub
Spec started


/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Error communicating with the remote browser. It may have died.
```

**Comment by liggitt** [comment]
test passed cleanly, re[merge]

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/2286 is open to look into switching to headless chrome for UI e2e tests

**Pull request merged**
