### PR TITLE
Add support for dynamic storage provisioning in example quickstart applications

### PR DESCRIPTION
**Pull request by hroyrh**
For each app template I have added an additional template that provides support for dynamic storage provisioning.

### CODE REVIEW

**Comment by liggitt** [comment]
@bparees I thought we were trying to reduce duplicate templates... do we know how we want to demo the cross product of languages/frameworks with all our storage options?

**Comment by bparees** [comment]
> @bparees I thought we were trying to reduce duplicate templates... do we know how we want to demo the cross product of languages/frameworks with all our storage options?

service linking. :)

**Comment by bparees** [comment]
@hroyrh by dynamic storage provisioning do you mean persistent volumes?

**Comment by liggitt** [comment]
yeah, these templates look like clones with PersistentVolumeClaims and volume mounts added

**Comment by hroyrh** [comment]
@bparees Yes, I have included PersistentVolumeClaims with storage class annotations so that users can request dynamically provisioned storage.

**Comment by bparees** [comment]
@hroyrh I don't foresee us including this change, the quickstarts are just intended to be sample starting points for applications, users who want persistent storage can certainly update the template or the deploymentconfigs created by the template, to use persistent storage, but we don't want to maintain all those permutations of the templates.

The other way to get persistent storage is to instantiate one of the DB templates, and link your application to that (by setting appropriate env variables):
https://github.com/openshift/origin/tree/master/examples/db-templates

**Comment by jeremyeder** [comment]
OK -- we wanted to see if it was possible to avoid carrying our own forked copies of the examples by putting these upstream into Origin (and we have more examples coming, too).  Our alternative is to keep them with the rest of the test suite, in the svt repo.  We thought they might be generically useful to Origin users.

https://github.com/openshift/svt/tree/master/openshift_scalability/content/quickstarts

**Comment by bparees** [comment]
Unfortunately it's a fine line for us between providing useful examples, and burdening ourselves with a ton of examples that we need to ensure keep working and are up to date w/ the latest best practices.

I should also note that if you look at the readme for the quickstarts you'll see that we don't maintain the template files in origin, we keep them upstream in their app repos and use a script to pull them into origin.

**Comment by bparees** [comment]
(also making use of templates that reference PVs requires you have taken some more advanced steps in setting up your cluster, so if you try to use them out of the box you're likely to fail)

**Comment by jeremyeder** [comment]
OK.  We will have to carry these.  Thanks.

**Pull request closed without merging**
