### PR TITLE
disable cluster up 3.7 test for now

### PR DESCRIPTION
**Pull request by jim-minter**
see #17867

### CODE REVIEW

**Comment by spadgett** [comment]
/test extended_conformance_install

@jim-minter Hope you don't mind me tagging your PR for test. I need the fix for #17575 :)

**Comment by jim-minter** [comment]
> @jim-minter Hope you don't mind me tagging your PR for test. I need the fix for #17575 :)

@spadgett not in the least, but I'm a bit in despair that re-testing and re-testing should be necessary for a one line diff that comments out a test :(

**Pull request merged**
