### PR TITLE
Preserve existing oauth client secrets on startup

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1302946

Previously, we were updating the secrets for the internal OAuth clients on every launch. This causes problems with HA environments. This PR preserves existing client secrets and just updates the challenge and redirect URI settings on launch.

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
@wshearn fyi

**Comment by liggitt** [comment]
@brenton which branches do we need to cherry pick this into?

**Comment by brenton** [comment]
@liggitt, enterprise-3.1.  However, I went ahead an created the PR for you to review.

**Pull request merged**
