### PR TITLE
trt-1150: move lock so prevent multiple file updates in single commit

### PR DESCRIPTION
**Pull request by neisw**
Min version of [28062](https://github.com/openshift/origin/pull/28062) 

- Just pull in the moved lock for now.  This will slow down commits, we want to evaluate these changes in isolation.

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
I don't see any `observers-resource-watch` in the presubmit artifacts (e.g., like [this one](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade/1681159665896919040/artifacts/e2e-gcp-ovn-upgrade/observers-resource-watch/))

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by DennisPeriquet** [comment]
The [resource-watch-store.tar](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-origin-28065-ci-4.14-e2e-azure-ovn-upgrade/1681618058151464960/artifacts/e2e-azure-ovn-upgrade/observers-resource-watch/artifacts/resource-watch-store.tar) with `git status` still shows:

```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   cluster-scoped-resources/config.openshift.io/apiservers/cluster.yaml
        modified:   cluster-scoped-resources/config.openshift.io/authentications/cluster.yaml
        modified:   cluster-scoped-resources/config.openshift.io/builds/cluster.yaml
        modified:   cluster-scoped-resources/config.openshift.io/clusteroperators/authentication.yaml
        modified:   cluster-scoped-resources/config.openshift.io/clusteroperators/baremetal.yaml
...
```

**Comment by neisw** [comment]
Yeah, the errors in the logs are gone but we still have unstaged changes.  Interestingly it seems to be under namespaces/ and cluster-scoped-resources/ for both that run and one we looked at before...

**Comment by neisw** [comment]
/hold

needs more evaluation

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by deads2k** [comment]
heck, why not.  @neisw owns checking results and reverting if needed.'

/lgtm
/approve

**Pull request merged**
