### PR TITLE
[3.5] Backport etcdhelper

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/15209

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

/assign kargakis

**Comment by mfojtik** [comment]
@soltysh PTAL since this was originally your commit.

**Comment by mfojtik** [comment]
[merge]

**Comment by kargakis** [comment]
@mfojtik not sure this is going to merge

**Comment by mfojtik** [comment]
force merging this as there are other issues in 3.5 that will prevent this to merge... one issue at the time :-)

**Comment by kargakis** [comment]
ack

**Pull request merged**
