### PR TITLE
use emptydir for sample-app volumes

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/8236

@mfojtik ptal

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by kargakis** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by wanghaoran1988** [comment]
@bparees Seems still cannot work, for the templates, there are some "pre","post" pod will created for the database deployment, so if their are no volume for te pre/post pod define, the deploy will fail too.
option 1. remove the pre/post pods in the dc , I already have a try , it works
option 2. add the volume for the pre/post pods, I have no idea how to add , but seems it is redundant for the custormer
option 3. we remove the docker volume define in our dockerfile like this(not sure whether will have new problem): .https://github.com/openshift/mongodb/blob/master/2.4/Dockerfile#L53

So ,ben, what's your idea for this ?

**Pull request merged**
