### PR TITLE
fix up the jenkins example

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
This doesn't yet work because of this issue:
https://github.com/openshift/origin/issues/1154

which causes the prod version to never get deployed (the push of the prod tag is ignored).

Otherwise I think this is good to go...note that i had to update the build logic to actually use tags on output.. @smarterclayton this is what i emailed you about.  please take a look at the change to the build controller.  If we don't do this, builds using To are always going to be pushed to latest, near as i can tell, despite the comments in BuildOutput.To which imply there is some preferred tag (unless "latest" is that preferred tag)

**Comment by bparees** [comment]
@deads2k @liggitt this will (once the aforementioned issue is closed) get the jenkins sample working again for the current state of the code.  if there's more that's going to be needed for roles, please let me know what needs to be done and when.  (or just include the work w/ your other changes :) )

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng this also fixes the issue of populating the output image spec as well as using the output tag field (which was previously being ignored).  please review.

**Comment by csrwng** [comment]
@bparees - I was thinking about this a little more and I thought that it would be more correct to change BuildStatus to a struct with a field contains the actual output image reference used instead of us modifying the spec. Basically bring the build resource more inline with what's upstream (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L590-L600). Though I'm not sure this PR is the right vehicle for that ;-)

**Comment by bparees** [comment]
no it's defnitely not. :)

how do you feel about this solution for now?

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
Added test cases for the new label copying, Tag using, and imagereference updating functionality.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
