### PR TITLE
openshift/origin-release:golang-1.x: install openssl

### PR DESCRIPTION
**Pull request by php-coder**
`openssl` binary required for tests that check certificates, see #11814

PTAL @stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We build these in the PR test process, so you don't need to do this as a prerequisite PR.

**Comment by php-coder** [comment]
Ok, will do it in #11814 Thanks!

**Comment by php-coder** [comment]
Unfortunately, it didn't for for me and tests fails because `openssl` isn't installed.

**Comment by stevekuznetsov** [comment]
Was it not doing a Docker build for the release image used to run the test?

**Comment by php-coder** [comment]
When I said "for me" I mean not on my machine but in Jenkins. Do our scripts do docker build for the release image?

**Comment by stevekuznetsov** [comment]
Yes, although I just realized we probably do that in the e2e test job. So @smarterclayton someone could introduce breaking changes to the release image for the `check` job, right?

**Comment by smarterclayton** [comment]
Yes

**Comment by stevekuznetsov** [comment]
Wonderful. Sorry for the confusion @php-coder, I've wasted a lot of your time by not understanding all the intricacies of this image correctly. This pull _is_ a necessary pre-requisite, then. @smarterclayton I don't like how we have this set up, crashing the queue on a PR that tests green is a no-go.

**Comment by smarterclayton** [comment]
Yeah, once we have more control we'll do a PR run that verifies a release
image change is green.

On Dec 5, 2016, at 9:49 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Wonderful. Sorry for the confusion @php-coder <https://github.com/php-coder>,
I've wasted a lot of your time by not understanding all the intricacies of
this image correctly. This pull *is* a necessary pre-requisite, then.
@smarterclayton <https://github.com/smarterclayton> I don't like how we
have this set up, crashing the queue on a PR that tests green is a no-go.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12095#issuecomment-264872872>,
or mute
the thread

**Comment by php-coder** [comment]
Steve, could you reopen this PR then? (I don't have permissions to do so.)

**Comment by stevekuznetsov** [comment]
Seems like I don't, either. Weird.

**Comment by stevekuznetsov** [comment]
@danmcp do you know what permission is lacking for me to re-open this? Or for @php-coder to re-open his own PR that he closed?

**Comment by stevekuznetsov** [comment]
Oh, nevermind, you deleted the branch that was backing this, that means we can't re-open it.

**Comment by php-coder** [comment]
Oops, my fault. I'm sorry for bothering you with that.

**Comment by stevekuznetsov** [comment]
You'll also want to edit `images/release/Dockerfile`

**Comment by php-coder** [comment]
@stevekuznetsov Done.

**Comment by stevekuznetsov** [comment]
[merge]

**Pull request merged**
