### PR TITLE
test: fix the operator images test to skip succeeded containers

### PR DESCRIPTION
**Pull request by mfojtik**
This whitelist installer and pruner pods that cause the test to fail with:

```
Jan 21 11:36:14.826: INFO: Error running &{/usr/bin/oc [oc --namespace=openshift-kube-controller-manager --config=/tmp/admin.kubeconfig exec revision-pruner-4-master-1.ci-op-0y5bbkz0-4c0cd.origin-ci-int-aws.dev.rhcloud.com -c pruner -- cat /etc/redhat-release] []   error: cannot exec into a container in a completed pod; current phase is Succeeded
 error: cannot exec into a container in a completed pod; current phase is Succeeded
```

Not sure who is the owner of this test.

/cc @derekwaynecarr

### CODE REVIEW

**Comment by deads2k** [comment]
These names match short lived pods that will be racy when trying to exec into them.

/lgtm

**Comment by mrunalp** [comment]
Looks good :+1:

**Comment by mrunalp** [comment]
@rphillips ptal

**Pull request merged**
