### PR TITLE
UPSTREAM: 71440: Fix for race condition caused by concurrent fsnotify (CREATE and REMOVE) in kubelet/plugin_watcher.go

### PR DESCRIPTION
**Pull request by sjenning**
upstream https://github.com/kubernetes/kubernetes/pull/71440

xref https://github.com/openshift/origin/pull/22021#issuecomment-463274704

@derekwaynecarr @rphillips

### CODE REVIEW

**Comment by sjenning** [comment]
fyi @squeed @dcbw

**Comment by rphillips** [comment]
/cancel hold

looks like a stuck job :/

**Comment by rphillips** [comment]
/hold cancel

looks like a stuck job :/

**Comment by sjenning** [comment]
@rphillips this looks like a legit unit test failure here.  can you take a look?

**Comment by smarterclayton** [comment]
Do we still need this?

**Comment by squeed** [comment]
doubt it. it was blocking CI for a while.. seems to have gone away.

**Pull request closed without merging**
