### PR TITLE
Typo in deployment controller factory

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by mfojtik** [comment]
@pmorie how this passed the unit tests? ;-)

LGTM

**Comment by soltysh** [comment]
In the unit tests we're using mock objects for this, this should be caught in integration or e2e tests, though :fearful: still LGTM

**Comment by pmorie** [comment]
[test]

**Comment by ironcladlou** [comment]
LGTM [merge]

**Comment by ironcladlou** [comment]
[merge]

**Pull request merged**
