### PR TITLE
auto-create a jenkins service account

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@tnozicka fyi, we'll now auto-create a jenkins service account when we create jenkins, and grant it the edit role (we do not grant edit to the default service account).

@csrwng ptal.

**Comment by csrwng** [comment]
@bparees the change looks fine to me... but is this something we do elsewhere? I was kind of reluctant to do it for the git server service account because you're basically modifying policy for you instead of asking you to do it explicitly

**Comment by bparees** [comment]
@csrwng yeah @liggitt and @deads2k have similar concerns.  To be honest, I had the same concerns, but I think I got agreement from @smarterclayton that this was the way to go, so let's see what he has to say or if i misunderstood him.

@deads2k and @liggitt were particularly concerned that now anyone who has access to create a buildconfig in the project (but perhaps no other access) can now:
1) create a pipeline buildconfig
2) causes a jenkins svc account to be created w/ edit permission
3) the user can then run an abitrary jenkinsfile that (in one of a variety of ways) picks up/exposes the service account token/secret
4) the user now has edit permission to the project.

**Comment by smarterclayton** [comment]
We already have a way to limit access to build configs of type
Jenkinsfile.  Only editors have that permission by default.  Editors by
default have all the permissions described.  Admins who care can edit their
templates.  Admins who want to restrict who can create pods should take
creating pods away from editors.

**Comment by deads2k** [comment]
@smarterclayton This changes allows a project editor to trick the system into creating an editor with non-expiring tokens, which are more easily compromised than a user token.

More than that, any project-admin who tries to constrain a user to only creating builds can't.  By doing this, the cluster-admin has stripping the ability of a project-admin to delegate some editing permissions and not others.

Requiring a project-admin to explicitly opt-in by binding the jenkins SA seems like an easy enablement step that eliminates a "create build" to "do anything an editor can" escalation attack.

**Comment by smarterclayton** [comment]
On May 24, 2016, at 4:08 PM, David Eads <notifications@github.com> wrote:

This changes allows a project editor to trick the system into creating an
editor with non-expiring tokens, which are more easily compromised than a
user token.


They're not tricking the platform, they're using it.


More than that, any project-admin who tries to constrain a user to only
creating builds can't.


They can disable Jenkins, change the default template, or deny access to
building Jenkins.


By doing this, the cluster-admin has removed the ability of a project-admin
to delegate some mutating permissions and not others. For instance, a
project-admin can no longer grant the ability to create build without also
granting the ability to create a deploymentconfig.

Requiring a project-admin to explicitly opt-in by binding the jenkins SA
seems like an easy enablement step that eliminates a "create build" to "do
anything an editor can" escalation attack.


It is no more escalating than "request-project" which does everything
described above plus grants project admin.  Admins concerned about this
should disable Jenkins and new project.

**Comment by liggitt** [comment]
+1 for making the choice explicit. I'm even ok with the cluster admin setting the jenkins template to give the edit role, I just don't think it should be the default, so that it happens without either the cluster-admin or project admin knowing the implications and making the choice.

**Comment by smarterclayton** [comment]
> This changes allows a project editor to trick the system into creating an
editor with non-expiring tokens, which are more easily compromised than a
user token.

They're not tricking the platform, they're using it.

> More than that, any project-admin who tries to constrain a user to only
creating builds can't.

They can disable Jenkins, change the default template, or deny access to
building Jenkins.

By doing this, the cluster-admin has removed the ability of a project-admin
to delegate some mutating permissions and not others. For instance, a
project-admin can no longer grant the ability to create build without also
granting the ability to create a deploymentconfig.

> Requiring a project-admin to explicitly opt-in by binding the jenkins SA
seems like an easy enablement step that eliminates a "create build" to "do
anything an editor can" escalation attack.

It is no more escalating than "request-project" which does everything
described above plus grants project admin.  Admins concerned about this
should disable Jenkins and new project.

**Comment by smarterclayton** [comment]
Just like new-project is enabled by default, Jenkins will be enabled by default to be useful.  If we disable Jenkins, we should disable new project (which we won't do, because it makes the platform unuseful).

I'm happy to have enterprise disable Jenkins by default, but I suspect few people actually want that.

**Comment by smarterclayton** [comment]
Capturing what we discussed in IRC for continuing tomorrow:

* OOTB, we want project editors to be able to install Jenkins and get the
full edit experience
* Cluster admins who want to restrict Jenkins to not start this way should
be able to
* Cluster admins may want to set up projects so that users can only build,
but not deploy (or not deploy in the jenkins project) - examples:
  * By creating a sub-project for the user that does the deployment, where
pods aren't run with jenkins
  * Or by simply only using build actions but within jenkins master (seems
unlikely - I think we can punt on this and limit it to just "cluster admin
can create projects that can use builds except jenkins")
* Project admins might want to allow someone to just do builds
  * A building user also implicitly has tag (they can specify the
destination image stream), which potentially could be an escalation if they
could push to the same image stream used for jenkins or a pod running under
a higher-than-viewer SA
  * Could be the same scenario as for cluster admin - org admin creates a
project, grants access to a builder user.  Builder SA only has permission
to push to another namespace image stream?
  * Project admins can't enable the "unsafe" builders today, only cluster
admins
  * I don't want to block this use case, but it's not a top priority for me.
* Enabling Jenkins should not require a migration for existing projects.
But existing clusters probably should have to take an affirmative action to
enable jenkins.

**Comment by deads2k** [comment]
In a world with only three roles (v2), allowing an "editor" to create something that also has "edit" powers makes sense and isn't concerning.  In a world where you can express any permission you want, some implied powers makes sense (creating rcs allows creating pods, creating builds allows tagging images).  Some don't make sense: creating builds allows deleting secrets and other builds.

Based on our IRC conversation, I'm worried that the `JenkinsPipelineBuildStrategy` may have been created without any escalation checking built in.  Resources that take escalating action based on changes protected themselves, see the various image APIs as an example.  Just because a user is allowed to create or modify a build, doesn't mean that user should have indirect power to delete other builds.  I think that regardless of how we resolve the "how does the SA get rights" question, we still have to consider the "should anyone who can modify a build be allowed to delete any other builds (or any other non-create build action)" question.  I think the answer is no and that an API level defense against escalation is both reasonable and possible.  A covers check inside of build `RESTStorage` for these creates and updates could compare to see if the mutating user has at least the power of the SA controlling jenkins.

That still wouldn't fully resolve the "you just turned your personal permission into permission for a well-known, never-expiring token" problem, but it at least reduces the problem to that.

**Comment by smarterclayton** [comment]
I think that might be useful in general.  We have use cases for
escalating components, and use cases for non-escalating.

The general problem can be stated as "am I allowed to do all the
actions described in this template", and "can I delegate to someone to
create this template with a higher role".  We have no concept of
"permissions required to create a specific template" other than
falling back to name, which I think is problematic.

 I do think the more complex use case where I can create builds that
result in pods being created in other projects will be fairly common,
and that's a harder equivalence to determine (that should definitely
be explicit delegation).

The general service account token problem may be something we have to
solve anyway. But push secrets, serving certs, and client certs also
will continue to allow escalation, and do so in a fairly hard to audit
pattern.

**Comment by deads2k** [comment]
If we admit that its escalating "create build" to "delete anything", then the two choices I see are:
 1. Stop the direct escalation by doing a covers check in the build RESTStorage.  This would make it significantly less problematic to allow the JenkinsBuildController to escalate the user and create a rolebinding (this still makes me cranky, but with a covers check my argument is weaker).
 2. Accept that making a rolebinding requires the user to have the power to create a rolebinding.  This would alleviate any concern I have because it means that the project-admin (or cluster-admin if using a default project template) chose to make "create build" mean "delete anything".  I think that doing it this way will work more easily with our existing infrastructure.

One you thing you glossed over in IRC was why it was essential that an editor be able to create the SA rolebinding.  I get that an editor needs to be able to make a JenkinsBuild, but once the rolebinding is made, he'll be able to create as many as he wants.  You could even make the experience seamless for a project-admin by having the RESTStorage impersonate the calling user to create a rolebinding if the SA doesn't have the proper permissions.  

If the editor wants to use a JenkinsBuild, but the SA doesn't have rights, that same RESTStorage could return an error that explains the situation and even provides a command for the project-admin.  If the project-admin decides not to do that, I'm not seeing why we should escalate an editor to do it in a namespace where the project-admin doesn't want it.

**Comment by deads2k** [comment]
Simple demonstration here: https://github.com/openshift/origin/pull/9022

**Comment by bparees** [comment]
@deads2k now that your admission control PR has merged, ptal again.

**Comment by deads2k** [comment]
I thought we had more than just a single template that would need modification.

**Comment by bparees** [comment]
@deads2k this is the only template that currently auto-defines a service account for jenkins and it's the one we'd intend to use with the pipeline flow.  The other jenkins templates could be modified to create service accounts for themselves to make life easier for users, but that's not the main concern right now.

**Comment by deads2k** [comment]
lgtm

**Comment by bparees** [comment]
[merge]

**Pull request merged**
