### PR TITLE
Remove EPEL from our base images

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Let's see what breaks

**Comment by rootfs** [comment]
I cannot pull openshift/origin-source, but if nothing breaks, then lgtm

**Comment by stevekuznetsov** [comment]
@smarterclayton are we seriously not using EPEL for anythign

**Comment by smarterclayton** [comment]
@tnozicka was this supposed to be fixed? https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16028/test_pull_request_origin_extended_conformance_gce/6982/

**Comment by stevekuznetsov** [comment]
I'm speechless that we dealt with EPEL flakes for ... years? and seemingly were not even using it ...

**Comment by smarterclayton** [comment]
Where'd the submit queue link go?

**Comment by stevekuznetsov** [comment]
Which one?

**Comment by smarterclayton** [comment]
The submit queue.

**Comment by tnozicka** [comment]
@smarterclayton no, but I have a PR to address it https://github.com/openshift/origin/pull/16061
(the other error with this test is fixed)

**Pull request merged**
