### PR TITLE
add InsecureSkipVerify flag for LDAP

### PR DESCRIPTION
**Pull request by vbehar**
for tls.Config, to accept any certificate when talking to a TLS-enabled LDAP server

### CODE REVIEW

**Comment by deads2k** [comment]
I don't like the idea of allowing my authentication layer (which is handling passwords and determining usernames) to connect to an external server without actually confirming that its talking to the server its expecting to see.

This change would allow someone to intercept the traffic and simply return, "yes, he's root".  I don't think that's a good setting to have.

@liggitt you probably have an opinion too.

**Comment by liggitt** [comment]
I don't want to enable skipping TLS verification for server-side auth infrastructure. What LDAP server are you using which does not have a cert valid for its hostname?

**Comment by usawa** [comment]
@liggitt , one example is when multiple ldap servers are beside a proxy/VIP, and not only one LDAP server. In this case the VIP has his own CN, and LDAPS servers (three of them) have another. In order to confirm it's ok, before creating/asking for new certificates (wildcard or altSubjectName), we could use this parameter. This flag is the same as using "TLS_REQCERT never" in ldap.conf. In our case, VIP and LDAP servers are internal. 

But it's not the problem. You should give people and admins the choice to do it or not, example for testing purposes. 

Another way for openshift should be to accept multiple LDAP servers in its connection string. Like linux daemons way (e.g sssd) : 

ldap_uri = ldaps://ldapmaster-0:636, ldaps://ldapmaster-1:636, ldaps://ldapmaster-2:636

with round-robin and check for example.

**Comment by liggitt** [comment]
> You should give people and admins the choice to do it or not, example for testing purposes.

I've seen too many production systems ignoring TLS verification to be comfortable providing this option. 

Per the LDAP RFC:

> In order to prevent man-in-the-middle attacks, the client MUST verify the server's identity (as presented in the server's Certificate message. 

https://tools.ietf.org/html/rfc4513#section-3.1.3

**Comment by usawa** [comment]
@liggitt I agree with you. So. Any way to specify multiple ldap servers ?

**Comment by vbehar** [comment]
ok so maybe it would be better to close this PR and open an issue to support multiple LDAP servers ?

**Comment by liggitt** [comment]
I do think this PR should be closed. However, I'm not sure multiple (non-load-balanced) LDAP servers is a common enough use case for openshift to support directly. You could likely accomplish that using Apache+mod_authnz_ldap (which supports multiple LDAP servers) as an auth proxy with the request header identity provider.

**Pull request closed without merging**
