### PR TITLE
UPSTREAM: kubernetes-incubator/cluster-capacity: 78: Remove resources that are not needed to run cluster  capacity analysis.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@derekwaynecarr @eparis it needs merge tag.

**Comment by eparis** [comment]
[merge]

**Comment by eparis** [comment]
[test]

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]

not having this fix requires cluster capacity to read all cluster secrets.

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
