### PR TITLE
Make the DIND image creation script executable

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@marun FYI

[merge]

**Comment by marun** [comment]
arg, sorry!

**Comment by derekwaynecarr** [comment]
hit the big green button to unblock queue.

**Comment by stevekuznetsov** [comment]
@smarterclayton why are we building the _base_ images inside of our test jobs? I thought the whole point was to do that in the AMI? Initially I thought this was not a huge issue but it was failing  PR test jobs, not just the base/devenv.

/cc @danmcp

**Comment by smarterclayton** [comment]
Occasionally someone needs to change it.  It's something that is more
coupled to our process than the release image, but could be handled
separately.  I'm open to kicking it to base ami completely as long as we
have a way to update it.

On Dec 15, 2016, at 3:24 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> why are we building the
*base* images inside of our test jobs? I thought the whole point was to do
that in the AMI? Initially I thought this was not a huge issue but it was
failing PR test jobs, not just the base/devenv.

/cc @danmcp <https://github.com/danmcp>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12282#issuecomment-267434251>,
or mute
the thread

**Comment by stevekuznetsov** [comment]
> but could be handled separately. 

AFAICT the _only_ reason we have two image building scripts is that one should not be running in our tests since it builds the base images.

> as long as we have a way to update it.

That being said, I don't we do have a toggle for this at run-time, so yeah, this was perhaps not thought all the way through whenever it was implemented in the first place.

**Comment by smarterclayton** [comment]
Originally it used the docker cache - so rebuild was a no-op.  Not the case
with imagebuilder.

On Dec 15, 2016, at 4:03 PM, Steve Kuznetsov <notifications@github.com>
wrote:

but could be handled separately.

AFAICT the *only* reason we have two image building scripts is that one
should not be running in our tests since it builds the base images.

as long as we have a way to update it.

That being said, I don't we do have a toggle for this at run-time, so yeah,
this was perhaps not thought all the way through whenever it was
implemented in the first place.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/12282#issuecomment-267443230>,
or mute
the thread

**Pull request merged**
