### PR TITLE
UPSTREAM: 27435: Fix bugs in DeltaFIFO

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/9638

merged upstream, fixes flake and correctness problem

[merge]

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM!

**Comment by deads2k** [comment]
why didn't you [merge]?

**Comment by bparees** [comment]
i have no idea why this still isn't merging when we run with pre-test success, would love for @danmcp to take a look if he can:
https://ci.openshift.redhat.com/jenkins/job/process_pull_requests/264289/console

**Comment by danmcp** [comment]
@bparees Your run: https://ci.openshift.redhat.com/jenkins/job/process_pull_requests/264290/console

didn't do anything because of:

Waiting till next run to see if mergeability is in flux

**Comment by bparees** [comment]
@deads2k i am still seeing fuzz failures after this merged.  is there something we can revert to get things stable?

**Comment by bparees** [comment]
@danmcp what dictates "mergability being in flux"?  @deads2k and i hit the merge pre-test success button multiple times.

**Comment by danmcp** [comment]
@bparees The GitHub API gets a little flaky typically right after something merges.  We don't want to start a testing a PR that might have a merge conflict so we wait till we get a clean run checking for mergability before we start testing anything.

**Pull request merged**
