### PR TITLE
On Windows, use CRLF line endings in oc edit

### PR DESCRIPTION
**Pull request by smarterclayton**
Adds `--windows-line-endings` to oc edit and defaults to whatever is correct for the current OS.

@fabianofranz

### CODE REVIEW

**Comment by fabianofranz** [comment]
Let me do some testing on windows.

**Comment by liggitt** [comment]
`--crlf`?

**Comment by fabianofranz** [comment]
Looks good on Windows, line endings are fixed. There is still the "in use by another process" issue left to fix what Grant [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1273975), I'll look at it.
I like `--crlf` but apart that LGTM.

**Comment by smarterclayton** [comment]
No one should ever have to specify this, it's only there for testing and workarounds.  I'd rather be clear than terse for infrequent flags.

**Comment by fabianofranz** [comment]
Along with https://github.com/openshift/origin/pull/5306 fixes https://bugzilla.redhat.com/show_bug.cgi?id=1273975.

**Comment by fabianofranz** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge] again

**Comment by fabianofranz** [comment]
Fixes https://github.com/openshift/origin/issues/4904

**Comment by xingxingxia** [comment]
@smarterclayton  I verified the issue-related bug https://bugzilla.redhat.com/show_bug.cgi?id=1259056. Bug I find another similar issue in Windows OS: 'oc get <resource type> <resource name> -o json > a.json', use notepad to open a.json, all lines are in one line, too. It is the same with YAML format. Would you plan to fix this too?
PS: If the command has no '> a.json', it outputs lines ok.

**Comment by smarterclayton** [comment]
It's definitely an issue we should discuss, but should be separate.

**Pull request merged**
