### PR TITLE
Add verification of generated content to make test

### PR DESCRIPTION
**Pull request by liggitt**
Update generation scripts to use common env setup
Add verification to `make test`, used by Jenkins

### CODE REVIEW

**Comment by liggitt** [comment]
@danmcp `make test` isn't running the `verify-generated-*.sh` tests, so Jenkins is letting in changes which don't update docs/conversions/etc...

**Comment by danmcp** [comment]
[merge]

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
I want to get a clean Jenkins and Travis test run on this before we merge

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
