### PR TITLE
Fixes for unnecessary scrollbars in certain areas and situations

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett This contains a fix for the topology view. So far, I'm unable to recreate the horizontal scrollbar for the builds bar chart.

**Comment by spadgett** [comment]
> So far, I'm unable to recreate the horizontal scrollbar for the builds bar chart.

I think I fixed it in #7364

**Comment by sg00dwin** [comment]
@spadgett ok good to hear. PR ready for review/merge

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Missing bindata.

**Comment by sg00dwin** [comment]
@spadgett bindata added

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
