### PR TITLE
Fix breadcrumb on next steps page

### LINKED ISSUE #6547: Breadcrumb broken on next steps page creating from source
I was creating from a source repository, and I received this error clicking on the builder image name in the breadcrumb on the next steps page.

openshift_web_console

/cc @jwforres @fabianofranz

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #6547

### CODE REVIEW

**Comment by spadgett** [comment]
@fabianofranz PTAL. The `sourceURL` parameter is no longer used when creating from source.

**Comment by fabianofranz** [comment]
LGTM

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
