### PR TITLE
update rollback cmd to deal with external versions

### PR DESCRIPTION
**Pull request by juanvallejo**
Updates the rollback command to use external versions.
Depends on https://github.com/openshift/origin/pull/20291

cc @deads2k

### CODE REVIEW

**Comment by juanvallejo** [comment]
Relevant changes begin here: https://github.com/openshift/origin/pull/20331/files#diff-32be1cab5563f3dfa28c5d7b5211e7b2

**Comment by mfojtik** [comment]
@juanvallejo before you put a pin into your voodoo doll of me, I can take this PR over and rework it to match the changes introduced in https://github.com/openshift/origin/pull/20019 and also switch the other commands to external clients with corresponding helpers for you. WDYT?

**Comment by mfojtik** [comment]
@juanvallejo guess this can be closed unless I forgot to switch something.

**Comment by juanvallejo** [comment]
@mfojtik yep, can be closed. Thanks

**Pull request closed without merging**
