### PR TITLE
Fix for etcd client oneshot cluster member cycling

### PR DESCRIPTION
**Pull request by rrati**
Backport of https://github.com/coreos/etcd/pull/8519

### CODE REVIEW

**Comment by deads2k** [comment]
@rrati the pick was clean?

**Comment by rrati** [comment]
@deads2k More or less.  The changes to the _test file aren't included because this version of etcd didn't have the tests.  The changes to the client code applied cleanly.

**Comment by deads2k** [comment]
lgtm

Do you have an issue or bug to tie to this?

**Comment by rrati** [comment]
A customer BZ, but no github issue

**Comment by liggitt** [comment]
remind me how we're managing picks for non-kube repos? also, an issue to track bumping to a release that includes this would be good (and an issue for kube, which is impacted the same way)

**Comment by sttts** [comment]
Do we have a backport of this into origin master? The upstream PR only merged into etcd 3.3+.

**Comment by liggitt** [comment]
it was backported into etcd 3.2.8 in https://github.com/coreos/etcd/commit/15e9510d2c0674675333008ec8524c1df5d05328 and picked up in 3.7+ in https://github.com/openshift/origin/commit/6032f62b9f39876e1ef3af74b6bdb3913cd11a38#diff-1c6011bace39f9ad159c10fa9a674a3a

**Comment by mfojtik** [comment]
@liggitt how about 3.2.16 we have in 3.9 ?

**Comment by liggitt** [comment]
yes, >= 3.2.8

verified this fix is in master:
https://github.com/openshift/origin/blob/1e041c8692a1fbb264dbfc34ab859599198547c7/vendor/github.com/coreos/etcd/client/client.go#L375-L398

3.9:
https://github.com/openshift/origin/blob/6d21b7d9d48a5a4397194453d739b7549cfeb2c5/vendor/github.com/coreos/etcd/client/client.go#L375-L398

3.8:
https://github.com/openshift/origin/blob/ff72b3f80a21d23160ee2314beae9013cecbcb49/vendor/github.com/coreos/etcd/client/client.go#L375-L398

3.7:
https://github.com/openshift/origin/blob/a8deba51020d25cf835d50458de7f463be7bc238/vendor/github.com/coreos/etcd/client/client.go#L375-L398

**Comment by sttts** [comment]
@liggitt without any deeper knowledge of the client code: all your references point to the etcd2 client, not the clientv3 package.

**Comment by liggitt** [comment]
hmm, true. I wonder if there was a similar issue with the etcd 3 client

**Comment by sttts** [comment]
But even in v3, there is a 10 second context passed to the dial func. How can that block for 15 minutes? (@mfojtik noticed that)

**Comment by sttts** [comment]
With persistent grpc connections we certainly do not talk about a Dial call here.

**Pull request merged**
