### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by pweil-**
Fix typos or incur wrath: :skull:  https://github.com/openshift/origin/pull/1438#issuecomment-86151932

### CODE REVIEW

**Comment by pweil-** [comment]
[merge]

**Comment by pweil-** [comment]
```
Your merge powers have no effect here, pweil-
        .
       /'
      //
  .  //
  |\ /7
 /' " \     
.   ☉☉    
| (    \    
|  '._  '    
/   \ '-' 
 

```

**Comment by pmorie** [comment]
[merge] I'll save you @pweil-

**Comment by pweil-** [comment]
:relieved:

**Pull request merged**
