### PR TITLE
correct serialisation of tsb json schemas

### LINKED ISSUE #14439: Template broker sends `service-instances` instead of `service_instances` in parameter schemas object
The template broker is sending the following parameters using the following JSON:

```
      "schemas": {
       "service-instances": {
        "create": {
         "parameters": {
            ...
```

But the service catalog is expecting `service_instances` instead:

https://github.com/kubernetes-incubator/service-catalog/blob/97d278a41eee2bf81896f2d1359c8ba6b66fa0c2/pkg/brokerapi/schemas.go#L22

This prevents the catalog from adding the parameter schema to the service class.

##### Version

oc v3.6.0-alpha.1+0bea328-833
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+1bf8a17-976
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Enable template broker in master-config.yaml
2. Run pkg/template/servicebroker/test-scripts/catalog.sh and view the output

cc @jim-minter @pmorie @jwforres @bparees

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #14439

### CODE REVIEW

**Comment by csrwng** [comment]
@jim-minter is there a reason camel case is not used?

**Comment by spadgett** [comment]
@csrwng The property name comes from the OpenService Broker API spec, so it's not something we can change. Currently still a proposal in OpenService Broker API, but implemented by service catalog as an alpha feature.

**Comment by spadgett** [comment]
Thanks @jim-minter parameters are coming through for me with this change:

openshift catalog components 2017-06-01 14-50-58

@pmorie fyi

**Comment by csrwng** [comment]
LGTM

**Comment by spadgett** [comment]
@jim-minter Looks like it's changing in the OSB spec to `service_instance` and `service_binding`. See

https://github.com/kubernetes-incubator/service-catalog/pull/912

cc @pmorie

**Comment by jim-minter** [comment]
thanks @spadgett PR updated to today's version of the spec. @csrwng please merge.

**Comment by csrwng** [comment]
@jim-minter unless this is a blocker, I will merge on Monday

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
