### PR TITLE
update the apps scheme install for the new pattern

### PR DESCRIPTION
**Pull request by deads2k**
Switches the apps group to use the new scheme install pattern to simplify installation of suitable schemes.

You can see how it simplifies scheme.go to allow us to focus which types we want to be able to convert.

/assign @mfojtik 

@mfojtik you've been in these files.

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
@mfojtik is merging that in https://github.com/openshift/origin/pull/20348#issuecomment-406199496 (this can be closed when that merges, or before)

**Comment by mfojtik** [comment]
got in via 
https://github.com/openshift/origin/pull/20348

**Pull request closed without merging**
