### PR TITLE
UPSTREAM: google/cadvisor: 1722: Skip subcontainer update on v2 calls

### PR DESCRIPTION
**Pull request by sjenning**
3.6 pick of https://github.com/openshift/origin/pull/15873

xref google/cadvisor#1722

@derekwaynecarr @eparis @smarterclayton

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
sweet.

/approve
/lgtm

**Comment by sjenning** [comment]
Flake https://github.com/openshift/origin/issues/15941

**Pull request merged**
