### PR TITLE
print typed podlist for correct serialization

### PR DESCRIPTION
**Pull request by juanvallejo**
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1473455
Backporting https://github.com/openshift/origin/pull/15411

cc @deads2k @fabianofranz

### CODE REVIEW

**Comment by liggitt** [comment]
```
[WARNING] !!! gofmt needs to be run on the following files: 
./pkg/cmd/admin/node/listpods.go
[FATAL] Try running 'gofmt -s -d [path]'
[FATAL] Or autocorrect with 'hack/verify-gofmt.sh | xargs -n 1 gofmt -s -w'
```

**Comment by joelsmith** [comment]
So this missed getting in for 3.6 because of a missing gofmt run on the changed code?

**Comment by liggitt** [comment]
yes, and is still needed

**Comment by juanvallejo** [comment]
@liggitt wondering if you could tag once more, thanks

**Comment by fabianofranz** [comment]
Good to merge.

**Pull request merged**
