### PR TITLE
OCPBUGS-1967: allow 2.5% disruption for 4.9 controlplane availability test

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
/hold

we need to gather some insights into why these disruption test failure has increased in 4.8 to 4.9 upgrade jobs.

**Comment by tkashem** [comment]
from the discussion we had
> i think it's safe to say we have very little confidence in the data and tests in 4.9. i personally would recommend disabling those tests unless you're prepared for massive investment to bring it up to speed with the current 4.12 stack, which I suspect would be a very large effort.

/hold cancel

**Comment by mfojtik** [comment]
Overriding invalid-bug because this change only affects 4.9.z

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
