### PR TITLE
add some debug to old jenkins plugin tests

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
So on the image-eco failure, the jenkins deployment for jenkins_plugins.go failed.

In looking at the pod status, it shows `ProgressDeadlineExceeded`

In looking at the logs, it is using the image we currently have where we try to do the plugin mgr / update center stuff on startup ... the PR to update jenkins-2-centos:latest, https://github.com/openshift/jenkins/pull/531, is still pending as we try to get the s2i test to pass so we can merge

Also, are template update into master PR https://github.com/openshift/origin/pull/18832 is yet to merge with test flakes

I'll get another test run here while I circle back to those two PRs

**Comment by gabemontero** [comment]
the debug added to this PR helped me with diagnosing the image_ecosysetm failure (in that it allowed me to rule out some possibilities ;-) )

turns out, it looks like the `git clone` on the s2i strategy `frontend` build hung, and the other steps did not start ... here is the ouput from dumping the various containers of the build pod:

```
Mar  7 16:33:14.226: INFO: Running 'oc logs --config=/etc/origin/master/admin.kubeconfig --namespace=extended-test-jenkins-plugin-kznxn-xlcvq pod/frontend-1-build -c git-clone'
Mar  7 16:33:14.543: INFO: Log for pod "frontend-1-build"/"git-clone"
---->
Cloning "https://github.com/openshift/nodejs-ex.git" ...
	Commit:	93fc25fd35068aa311f4722e4d7e5187b06edd7b (Merge pull request #170 from dharmit/add-minishift-to-readme)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Tue Mar 6 13:34:31 2018 -0500
<----end of log for "frontend-1-build"/"git-clone"

Mar  7 16:33:14.543: INFO: Running 'oc logs --config=/etc/origin/master/admin.kubeconfig --namespace=extended-test-jenkins-plugin-kznxn-xlcvq pod/frontend-1-build -c manage-dockerfile'
Mar  7 16:33:15.007: INFO: Log for pod "frontend-1-build"/"manage-dockerfile"
---->

<----end of log for "frontend-1-build"/"manage-dockerfile"

Mar  7 16:33:15.007: INFO: Running 'oc logs --config=/etc/origin/master/admin.kubeconfig --namespace=extended-test-jenkins-plugin-kznxn-xlcvq pod/frontend-1-build -c sti-build'
Mar  7 16:33:15.368: INFO: Log for pod "frontend-1-build"/"sti-build"
---->

<----end of log for "frontend-1-build"/"sti-build"
```

so, I believe this is "environmental"

**Comment by bparees** [comment]
@gabemontero From what I can see, this is the the tar/stdin closure issue.  the git clone container finished(it is not what hung).  The container doing the tar injection ("frontend-1-build"/"sti-build").  Because of where it hangs, there's no output yet generated unless you have a higher build loglevel set.

(and there's no output from managedockerfile because it had nothing to do)

**Comment by gabemontero** [comment]
ok cool thanks for the confirmation @bparees 

so am I correct in assuming a vendor bump for source-to-image into origin is coming?

**Comment by gabemontero** [comment]
sorry, just saw ... it is https://github.com/openshift/origin/pull/18882

**Pull request merged**
