### PR TITLE
import prefix

### PR DESCRIPTION
**Pull request by deads2k**
adds a fix for TSB from https://github.com/openshift/origin/pull/15727

### CODE REVIEW

**Comment by deads2k** [comment]
Reviewed and lgtm'd https://github.com/openshift/origin/pull/15727 (stefan's).  Tagging.

**Comment by deads2k** [comment]
@smarterclayton how long must we keep using the non-groupified groups?  This change is changing the output from `oc run` to the groupified version.  It skews one release now.  We ok with it?

@sttts got it to build, but now
```
test/cmd/basicresources.sh:313: executing 'oc run --dry-run foo --image=bar -o "go-template={{.kind}} {{.apiVersion}}"' expecting success and text 'DeploymentConfig v1'
FAILURE after 0.259s: test/cmd/basicresources.sh:313: executing 'oc run --dry-run foo --image=bar -o "go-template={{.kind}} {{.apiVersion}}"' expecting success and text 'DeploymentConfig v1': the output content test failed
Standard output from the command:
DeploymentConfig apps.openshift.io/v1
```

**Comment by mfojtik** [comment]
@deads2k dry-run has been broken before AFAIK, i think this will make it a little bit worse :)

**Comment by deads2k** [comment]
> @deads2k dry-run has been broken before AFAIK, i think this will make it a little bit worse :)

Got it fixed.

**Comment by sttts** [comment]
🎉 

@deads2k thanks for getting this merged!

**Pull request merged**
