### PR TITLE
Bug 1176815 - Improve error reporting for build-log

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@jhadvig @soltysh can you review this pls?

[test]

**Comment by jhadvig** [comment]
@mfojtik I've tested the change and it works properly, but you will need to update the TC's, cause they are failing due to this change.

**Comment by soltysh** [comment]
@mfojtik you need to get tests working :wink:

**Comment by mfojtik** [comment]
@soltysh uups, I forget to update them, should be all green now.

**Comment by jhadvig** [comment]
@mfojtik LGTM

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
