### PR TITLE
[WIP] s2i dockerfile build

### PR DESCRIPTION
**Pull request by adambkaplan**
In progress branch for s2i dockerfile build.
Still uses the docker daemon under the hood, invoking s2i's `--as-dockerfile` build to then run a standard Dockerfile-based image build.

@coreydaley @bparees fyi

### CODE REVIEW

**Comment by bparees** [comment]
@nalind fyi

**Comment by adambkaplan** [comment]
s2i Dockerfiles use options that are not supported by the RHEL distribution of docker. Extended build tests won't work until buildah is merged in.

**Comment by adambkaplan** [comment]
end_to_end needs @coreydaley post-commit hooks to work properly

**Pull request closed without merging**
