### PR TITLE
controller: move shared informers in separate package

### PR DESCRIPTION
**Pull request by kargakis**
@deads2k @smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
`FAIL	github.com/openshift/origin/pkg/project/admission/lifecycle [build failed]`

**Comment by deads2k** [comment]
[merge]

**Comment by kargakis** [comment]
@deads2k once you tag once, you don't need to tag again. The job is rerun with every new push

**Comment by deads2k** [comment]
> @deads2k once you tag once, you don't need to tag again. The job is rerun with every new push

just losing my mind on a friday.

**Comment by kargakis** [comment]
yum, [merge]

**Pull request merged**
