### PR TITLE
Remove gradle e2e tests

### PR DESCRIPTION
**Pull request by akram**
Remove gradle e2e tests as we are removing it from jenkins maven agent image while migrating to openjdk-11

/assign @gabemontero 
/assign @adambkaplan

### CODE REVIEW

**Comment by akram** [comment]
By the way, 
it would be good if we can archive https://github.com/openshift/gs-spring-boot-spock if it is not used somewhere else.
The last commit has 4 years+.

Who should I ask?
cc @waveywaves

**Comment by akram** [comment]
/assign @ironcladlou

@ironcladlou could you PTAL ?
it is purely code removal.

**Comment by gabemontero** [comment]
/approve

/lgtm

@akram I assume you'll go after https://github.com/openshift/jenkins/blob/master/agent-maven-3.5/Dockerfile.localdev#L18-L21 and https://github.com/openshift/jenkins/blob/master/agent-maven-3.5/Dockerfile.localdev#L33 once this test is gone, correct?

**Comment by akram** [comment]
> /approve
> 
> /lgtm
> 
> @akram I assume you'll go after https://github.com/openshift/jenkins/blob/master/agent-maven-3.5/Dockerfile.localdev#L18-L21 and https://github.com/openshift/jenkins/blob/master/agent-maven-3.5/Dockerfile.localdev#L33 once this test is gone, correct?

Yes @gabemontero , the PR was already on its way:
https://github.com/openshift/jenkins/pull/923/files#diff-8a588ed4aabe9558419fc13944e736fdL18

**Comment by akram** [comment]
They timed out after 4 hours
/test e2e-aws-jenkins

**Pull request merged**
