### PR TITLE
Revert "skip tsb tests on GCE until new images are published"

### PR DESCRIPTION
**Pull request by bparees**
This reverts commit 3e9c66cc1449f691751bd9cb20b1e7a0e7b0a028.

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton fyi

**Comment by deads2k** [comment]
supercedes https://github.com/openshift/origin/pull/15837 ?

**Comment by bparees** [comment]
talked to @deads2k offline, going to merge this one.

**Pull request merged**
