### PR TITLE
3.6.x: UPSTREAM: 49992: Correctly handle empty watch event cache

### PR DESCRIPTION
**Pull request by liggitt**
pick of https://github.com/openshift/origin/pull/15614

### CODE REVIEW

**Comment by liggitt** [comment]
weird router build failure
/retest

**Comment by liggitt** [comment]
```
make: *** No rule to make target `build-router-e2e-test'.  Stop.
```

@stevekuznetsov - why are the 3.6 jobs trying to run things only found in the makefile on master?

**Comment by stevekuznetsov** [comment]
@deads2k you need to backport your changes to 3.6

**Comment by liggitt** [comment]
> @deads2k you need to backport your changes to 3.6

that's not right... we should have a 3.6 job that is not affected by changes made to master CI

**Comment by stevekuznetsov** [comment]
@liggitt yes, that would be a perfect world. We don't live in that world today

**Comment by liggitt** [comment]
parent is merged

**Pull request merged**
