### PR TITLE
[Backport] Add router option to bind ports only when ready

### PR DESCRIPTION
**Pull request by imcsk8**
By default the router binds ports 80 and 443 even if no routing
configuration is available.  This may be desirable when haproxy is
serving traffic directly to clients.  However, the f5 loadbalancer will
treat bound ports as indicating that a backend is ready to receive
traffic.  This means that router pods that are starting or restarting
may be put into rotation before they are ready to serve the current
route state and clients may see 503s for perfectly healthy backend
endpoints.  To avoid this possibility, this change adds an
option (BIND_ONLY_WHEN_READY/--bind-only-when-ready) to the router that
ensures that ports are bound only when a router instance has route and
endpoint state available.

Reference: bz1383663

### CODE REVIEW

**Comment by marun** [comment]
Not sure if you're allowed to edit labels yet, but when you gain the ability please make sure to add ``component/networking`` to networking PRs so that other members of the team can discover them.  Another way of notifying people is cc'ing the team group as I've done at the bottom of this comment.

This PR is 4.4k additional lines rather than the 247 lines added by the original PR.  Looks like the completions are to blame, you'll need to regenerate them.  Run ``make verify`` locally to validate the backport and it will provide instructions on what to do when it detects the problem.

cc: @openshift/networking

**Comment by marun** [comment]
Make sure to update this PR by amending the commit and force pushing.

**Comment by imcsk8** [comment]
thanks @marun !

**Comment by knobunc** [comment]
@imcsk8 please look at the build error.  It looks like it's failing go build or go fmt at a quick glance.

**Comment by knobunc** [comment]
@imcsk8 Ping

**Comment by imcsk8** [comment]
This went out of my radar, i'm checking it

**Comment by knobunc** [comment]
Not merging for 3.3 at this point.

**Pull request closed without merging**
