### PR TITLE
Bug 1782467: update image eco perl imagestream refs from EOL 5.24 to 5.26

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @bparees 
(for bindata)
@openshift/openshift-team-developer-experience FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
needed for https://github.com/openshift/cluster-samples-operator/pull/209

**Comment by gabemontero** [comment]
/assign @adambkaplan 
I see him in the owners file now
/unassign @bparees

**Comment by bparees** [comment]
we should add more people to the testdata owners file...  @adambkaplan should probably be in it at a minimum.

**Comment by gabemontero** [comment]
/hold

https://bugzilla.redhat.com/show_bug.cgi?id=1783530 is now blocking us

**Pull request merged**
