### PR TITLE
Split prometheus rules into its own configmap

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @mfojtik got any idea why permissions in `/etc/prometheus/prometheus.yml` are not applied correctly when it's mounted with `subPath`?

```
level=error ts=2017-11-29T12:10:16.50690078Z caller=main.go:356 msg="Error loading config" err="couldn't load configuration (--config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: permission denied"
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why is this necessary?  ENOCONTEXT

**Comment by kargakis** [comment]
Because we want to use our own prometheus.rules in api.ci and there is no way to patch configmap keys currently.

**Comment by kargakis** [comment]
See https://github.com/openshift/release/pull/447 + https://github.com/openshift/release/pull/448

**Comment by smarterclayton** [comment]
Bug on not being able to patch config map keys?

**Comment by kargakis** [comment]
There is https://trello.com/c/DnJ6S2zI/1077-cliupstream-easier-editing-of-config-map-keys but it doesn't seem to be getting fixed anytime soon.

**Comment by kargakis** [comment]
Ok, I think I am hitting https://github.com/kubernetes/kubernetes/issues/54487

**Comment by kargakis** [comment]
I have a workaround so we won't need these changes.
```
oc set volume sts/prometheus -c prometheus --add -t configmap --configmap-name=prometheus-rules -m /etc/prometheus/prometheus.rules --sub-path=..data/prometheus.rules
```
on our side

**Comment by smarterclayton** [comment]
Ok.  I’m potentially open to changes but I want to get a feel for how
people need to use it before we commit.

On Nov 30, 2017, at 10:46 AM, OpenShift CI Robot <notifications@github.com>
wrote:

@kargakis <https://github.com/kargakis>: The following tests *failed*, say
/retest to rerun them all:
Test name Commit Details Rerun command
ci/openshift-jenkins/extended_clusterup af2e611
<https://github.com/openshift/origin/commit/af2e611a409830a9264592d6aa85bed24e524613>
link
<https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17507/test_pull_request_origin_extended_clusterup/176/>
/test
extended_clusterup
ci/openshift-jenkins/extended_conformance_install af2e611
<https://github.com/openshift/origin/commit/af2e611a409830a9264592d6aa85bed24e524613>
link
<https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17507/test_pull_request_origin_extended_conformance_install/3240/>
/test
extended_conformance_install

Full PR test history <https://openshift-gce-devel.appspot.com/pr/17507>. Your
PR dashboard <https://openshift-gce-devel.appspot.com/pr/kargakis>. Please
help us cut down on flakes by linking to
<https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests>
an open issue
<https://github.com/openshift/origin/issues?q=is:issue+is:open> when you
hit one in your PR.

Instructions for interacting with me using PR comments are available here
<https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md>.
If you have questions or suggestions related to my behavior, please file an
issue against the kubernetes/test-infra
<https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
repository. I understand the commands that are listed here
<https://github.com/kubernetes/test-infra/blob/master/commands.md>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/17507#issuecomment-348227734>,
or mute
the thread

**Comment by kargakis** [comment]
Another thing I had to patch in this template is emptyDir for data -> volumeTemplate. Should we offer a persistent version of the template similar to what we do elsewhere?

**Comment by smarterclayton** [comment]
I don't really want to do that until we get the "config layering" stuff.

I'm going to turn the rule_files include into a wildcard, and then add a
global wildcard.  That'll allow you to inject a config map into an
arbitrary directory via a fileglob.

**Pull request closed without merging**
