### PR TITLE
WIP: repeatedly exercise stdin in exec

### PR DESCRIPTION
**Pull request by liggitt**
debugging for https://bugzilla.redhat.com/show_bug.cgi?id=1552670

### CODE REVIEW

**Comment by liggitt** [comment]
@derekwaynecarr @gabemontero were you seeing issues with stdin streaming related to builds? getting reports of ~25% failure rates in https://bugzilla.redhat.com/show_bug.cgi?id=1552670 and https://bugzilla.redhat.com/show_bug.cgi?id=1550644

**Comment by mrunalp** [comment]
https://github.com/jim-minter/docker/commit/missing_closewrite might fix this.

**Comment by mrunalp** [comment]
cc: @jim-minter

**Comment by gabemontero** [comment]
On Wed, Mar 7, 2018 at 1:12 PM, Jordan Liggitt <notifications@github.com>
wrote:

> @derekwaynecarr <https://github.com/derekwaynecarr> @gabemontero
> <https://github.com/gabemontero> were you seeing issues with stdin
> streaming related to builds? getting reports of ~25% failure rates in
> https://bugzilla.redhat.com/show_bug.cgi?id=1552670 and
> https://bugzilla.redhat.com/show_bug.cgi?id=1550644
>
Yep, see what @bparees has noted in
https://github.com/openshift/source-to-image/pull/855 and
https://github.com/openshift/origin/issues/18862#issuecomment-371224917

**Comment by mrunalp** [comment]
Upstream PR https://github.com/moby/moby/issues/36516

**Comment by liggitt** [comment]
Confirmed hung after just a couple attempts:
```
[INFO] Restore configured to enable mirroring

Running test/end-to-end/core.sh:135: executing 'echo -n a | oc exec -i -n default docker-registry-3-zrrlc cat' expecting success and text 'a'...
SUCCESS after 0.308s: test/end-to-end/core.sh:135: executing 'echo -n a | oc exec -i -n default docker-registry-3-zrrlc cat' expecting success and text 'a'
Standard output from the command:
a
There was no error output from the command.
Running test/end-to-end/core.sh:136: executing 'echo -n a | oc exec -i -n default docker-registry-3-zrrlc cat' expecting success and text 'a'...
```

**Comment by liggitt** [comment]
picked client change.
/retest

**Comment by liggitt** [comment]
`oc exec` calls all passed

**Comment by liggitt** [comment]
`oc exec` tests indicate the client fix helps. closing in favor of https://github.com/openshift/origin/pull/18882

**Pull request closed without merging**
