### PR TITLE
add minimal SCC changes to switch to CRD

### PR DESCRIPTION
**Pull request by deads2k**
SCC defaulting.  It's important or the API contract is broken.  This adds defaulting on write, *not reads*.  This ok only because we have no old data. Doing it this way ensures that the data is in a good state.  You cannot add new defaulting rules and only default on writing.

@openshift/sig-auth

### CODE REVIEW

**Comment by deads2k** [comment]
previous was lgtmd

**Comment by deads2k** [comment]
/hold

waiting on https://github.com/openshift/cluster-monitoring-operator/pull/343

**Comment by deads2k** [comment]
This is the same as the other lgtmd one

**Comment by deads2k** [comment]
/retest 

for images

**Comment by deads2k** [comment]
infra appears to be flaking hard

/retest

**Comment by sallyom** [comment]
[this](https://github.com/openshift/origin/pull/22658) will follow

**Comment by deads2k** [comment]
Upgrade worked https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22737/pull-ci-openshift-origin-master-e2e-aws-upgrade/432/artifacts/e2e-aws-upgrade/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions.yaml, but flaked on flaky test https://search.svc.ci.openshift.org/?search=replicaset+%22rs%22+never+became+ready&maxAge=168h&context=2&type=all

Merging to free up followups in parallel.

**Pull request merged**
