### PR TITLE
properly categorize the stop and start intervals

### PR DESCRIPTION
**Pull request by deads2k**
https://github.com/openshift/origin/pull/28137 on top of the revert

criteria are
1. node update events showing
2. aggregated payload jobs pass disruption
4. events are not duplicated

### CODE REVIEW

**Comment by dgoodwin** [comment]
/lgtm
/hold 

Holding for payload test results, per our call we want to see agg disruption pass, but we should be careful if something else shows up that doesn't look like a flake.

**Comment by deads2k** [comment]
1. periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade - pass
2. periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade - running
3. periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade - failed to even complete the build (6 minute failure)
4. periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade - running
5. periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade - network policy failures, but disruption passed
6. periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade - failed to even build (6 minutes failure)

**Comment by deads2k** [comment]
no conflict with the one that just merged.  The disruption looks good.  We identified the source previously and confirmed this fixes the source

**Pull request merged**
