### PR TITLE
Remove duplicate oauth2 library

### PR DESCRIPTION
**Pull request by kargakis**
Ref issue: https://github.com/openshift/origin/issues/1312

### CODE REVIEW

**Comment by kargakis** [comment]
We need to bump `golang.org/x/oauth2` to a newer version.

**Comment by kargakis** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
@deads2k review

**Comment by deads2k** [comment]
I see these usages in our prereqs:
```
Godeps/_workspace/src/github.com/RangelReale/osin/example/goauth2client/goauth2client.go:	"code.google.com/p/goauth2/oauth"
Godeps/_workspace/src/github.com/google/cadvisor/storage/bigquery/client/client.go:	"code.google.com/p/goauth2/oauth"
Godeps/_workspace/src/github.com/google/cadvisor/storage/bigquery/client/client.go:	"code.google.com/p/goauth2/oauth/jwt"
```

I think that only way this can keep building after removing `code.google.com/p/goauth2/oauth` is if the bigquery/client package is orphaned (never referenced).  Can you find out why we have it and either remove it or get it updated for the new dependency?

I'm not too worried about the RangelReale test, but for completeness they'd probably appreciate a patch.

**Comment by kargakis** [comment]
> Can you find out why we have it and either remove it or get it updated for the new dependency?

I can't find it anywhere in OpenShift-specific code. cadvisor is a Kubernetes dependency so I guess in order for these imports to be removed, the change has to start from cadvisor all the way up to us. I have submitted an issue about it: https://github.com/google/cadvisor/issues/608

**Comment by deads2k** [comment]
I didn't see usage in kubernetes either.  Do you?

**Comment by kargakis** [comment]
> I didn't see usage in kubernetes either. Do you?

I didn't see either but lemme double-check.

**Comment by smarterclayton** [comment]
I believe it's referenced by cloud providers.  It's a transitive dependency to GCE.

----- Original Message -----

**Comment by deads2k** [comment]
from kubernetes/master:
```
grep -r "github.com/google/cadvisor/storage/bigquery" *
Godeps/_workspace/src/github.com/google/cadvisor/storage/bigquery/bigquery.go:	"github.com/google/cadvisor/storage/bigquery/client"
Godeps/_workspace/src/github.com/google/cadvisor/storage/bigquery/client/example/example.go:	"github.com/google/cadvisor/storage/bigquery/client"
```

It's not even in `Godeps.json`.

**Comment by kargakis** [comment]
Yep, nothing in Godeps or in any Kubernetes code.

**Comment by deads2k** [comment]
@kargakis try to get it pulled from kube.  If they accept it, add another `UPSTREAM` patch and we'll merge this in.  If they don't, at least we'll know why we have this zombie dependency.

**Comment by kargakis** [comment]
> @kargakis try to get it pulled from kube. If they accept it, add another UPSTREAM patch and we'll merge this in. If they don't, at least we'll know why we have this zombie dependency.

https://github.com/GoogleCloudPlatform/kubernetes/pull/5788

**Comment by deads2k** [comment]
I see that some of the upstream changes are going in.  Do you have a pull for updated kubernetes to the new cadvisor?  Once kube has it, this is good to go.

**Comment by kargakis** [comment]
> I see that some of the upstream changes are going in. Do you have a pull for updated kubernetes to the new cadvisor? Once kube has it, this is good to go.

https://github.com/GoogleCloudPlatform/kubernetes/pull/5931

**Comment by kargakis** [comment]
Updated cAdvisor is live in Kubernetes: https://github.com/GoogleCloudPlatform/kubernetes/pull/5934
@deads2k mind bumping it in OpenShift and then merging this?

**Comment by kargakis** [comment]
This can be merged since the latest Kube rebase.

**Comment by deads2k** [comment]
[merge]

**Comment by kargakis** [comment]
[test]

**Pull request merged**
