### PR TITLE
Rename STI to s2i in extended test

### PR DESCRIPTION
**Pull request by mfojtik**
Canary for: https://github.com/openshift/origin/issues/4442

### CODE REVIEW

**Comment by mfojtik** [comment]
[testextendedonly][extended:core(environment)]

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(environment)]

**Comment by mfojtik** [comment]
@kargakis this should fix the broken test, lgty  ?

**Comment by kargakis** [comment]
Mind fixing the message in https://github.com/openshift/origin/pull/5027/files#diff-3f942814e05f71c7a002e72031d6fc5eR71?

**Comment by mfojtik** [comment]
@kargakis lol yes :-)

**Comment by mfojtik** [comment]
@kargakis done, also squashed.

**Comment by kargakis** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
