### PR TITLE
Fix the apiversion for dockerbuild and custombuild json files

### PR DESCRIPTION
**Pull request by xiuwang**
PTAL

### CODE REVIEW

**Comment by danmcp** [comment]
@bparees Review please.

**Comment by bparees** [comment]
@xiuwang can you clean up the trigger types too?  they are camel case now:
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L102-L113

**Comment by xiuwang** [comment]
@bparees comments addressed, please take a look, thx.

**Comment by bparees** [comment]
@xiuwang that diff doesn't look right...did you look at what github is showing as the diff for this pr?  also please squash your commits.

**Comment by bparees** [comment]
also you should fill in your username in your git client, your commits are showing up "fedora cloud user" right now.

**Comment by xiuwang** [comment]
@bparees Very strange,I have mofidied the right code in sti json file, but after commit the file, it always show the wrong diff code.Could you help me check it?

**Comment by bparees** [comment]
@xiuwang i'm not really in a position to debug your git environment, if you can't determine what has happened in your branch maybe it would be better to just create a new branch and re-make the changes and open a new PR using that new branch and then close this one.

**Comment by xiuwang** [comment]
@bparees Seem it's not my git environment issue.Colleagues modify the trigger part PR, it's same with mine...

**Comment by mfojtik** [comment]
@xiuwang looks good now, can you squash to one commit?

**Comment by xiuwang** [comment]
@mfojtik Merge changes to one commit. PTLA. Thanks

**Comment by bparees** [comment]
@xiuwang this commit is still removing triggers from the sample application template.

**Pull request closed without merging**
