### PR TITLE
[WIP] oc cluster up: add `--scc` flag

### PR DESCRIPTION
**Pull request by tchughesiv**
Offer an easy way to use different OpenShift scc's via `oc cluster up`. 
```shell
$ oc cluster up --help | grep scc
      --scc='restricted': Default security context constraint for authenticated users

$ oc cluster up --version=latest --scc=nonroot
$ oc new-app registry.centos.org/container-examples/starter-arbitrary-uid
$ oc get pod starter-arbitrary-uid-1-d4ws4 -o yaml | grep scc
    openshift.io/scc: nonroot
```
Non-existent scc example:
```shell
$ oc cluster up --version=latest --scc=anyui
"anyui" is not a valid scc. Use one of these:
 - privileged
 - nonroot
 - hostmount-anyuid
 - hostaccess
 - restricted
 - anyuid
 - hostnetwork

Continuing with default scc settings.
```

### CODE REVIEW

**Comment by deads2k** [comment]
It's not clear to me what this is trying to do.  Are you trying to add a particular SCC to the developer user?  If so, that's an anti-goal.  We want to encourage good security practice and that means that users should run with "normal" SCC powers.   If they really need additional power, they can become a cluster-admin and take the explicit action to opt-in to a non-standard security configuration.

**Comment by tchughesiv** [comment]
Yes to your question... the goal was a fast/easy way to execute a deployment w/ different scc's in a dev environment. I 100% agree w/ encouraging good security practice, which is why the default of restricted doesn't change.

This idea came from the fact that k8s solutions and docker.io images aren't always portable to openshift and its not always obvious why. I was asked if there was a way to easily check images/solutions against different scc's. Also, I think this flag would probably bring more awareness to developers that these security contexts exist in openshift and are potential affecting their container at runtime.

That said, completely understand if we don't want to consider adding this flag.

**Comment by deads2k** [comment]
> Yes to your question... the goal was a fast/easy way to execute a deployment w/ different scc's in a dev environment. I 100% agree w/ encouraging good security practice, which is why the default of restricted doesn't change.

Doing that is going to be remain a post step so that the default security stance of `oc cluster up` is secure.  A user who wants to make it insecure can do so, but taking the explicit step ensures that he is aware at some level that he is doing a naughty a thing.

**Comment by php-coder** [comment]
@tchughesiv In order to make a cluster less secure and works like Kubernetes/Docker you may follow this advice: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

It should help in most cases (it won't allow you to run privileged pods, but all users will be able to run their pods under `root` user by default).

**Pull request closed without merging**
