### PR TITLE
UPSTREAM: 73041: fix some race conditions in logs -f

### PR DESCRIPTION
**Pull request by giuseppe**
Backport of: https://github.com/giuseppe/kubernetes/tree/fix-logs

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Last 2 runs have been successful :) We can keep on kicking this.

**Comment by giuseppe** [comment]
opened a PR for Kubernetes here: https://github.com/kubernetes/kubernetes/pull/73041

**Comment by giuseppe** [comment]
after few successful runs, it seems like the issue is still there: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21795/pull-ci-openshift-origin-master-e2e-aws/2476/

**Comment by mrunalp** [comment]
We could try using oc logs instead of oc logs -f to see if we can isolate the fsnotify issue from other potential iops throttling issues.

**Comment by giuseppe** [comment]
@mrunalp that sounds like a great idea.  Opened a PR to try it out: https://github.com/openshift/origin/pull/21826

**Comment by giuseppe** [comment]
upstream got merged.  Rebased :arrow_up:

**Comment by giuseppe** [comment]
tests are green

**Comment by smarterclayton** [comment]
/approve

will have to assess post merge for flakes

**Comment by giuseppe** [comment]
>  I'm looking at the original PR and I see accompanying e2e, any reason why this was skipped?

no, my mistake.  I've pushed a fixed version now

**Comment by mrunalp** [comment]
@soltysh can you take a look and remove the hold if it looks fine now?

**Pull request merged**
