### PR TITLE
Use image utils from library-go 

### PR DESCRIPTION
**Pull request by soltysh**
Builds on top of #22962 and #22979, only 2 last commits matter. 

/assign @mfojtik @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
squash in import restrictions

/lgtm

**Comment by soltysh** [comment]
> squash in import restrictions

Done, retagging.

**Comment by soltysh** [comment]
Fixed unit and picked a commit from #22967 to solve problem with unit test for `pkg/image/controller/trigger`. Self-tagging.

**Comment by deads2k** [comment]
this one isn't building.

**Comment by soltysh** [comment]
Rebased with only last commit, since other prereqs merged. Self-tagging.

**Comment by soltysh** [comment]
/hold 
until I fix problems

**Comment by soltysh** [comment]
Fixed unit test, removing hold and tagging back.

**Pull request merged**
