### PR TITLE
UPSTREAM: 27541: Attach init container

### PR DESCRIPTION
**Pull request by smarterclayton**
It should be possible to attach to init containers.

Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1364017

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@fabianofranz @ncdc

**Comment by fabianofranz** [comment]
LGTM

**Comment by ncdc** [comment]
This doesn't match 28012. It's actually a partial cherry pick of 27541. Not sure which of those two you actually want, since 28012 changes the code added in 27541... ?

**Comment by smarterclayton** [comment]
Repicked

**Comment by ncdc** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
