### PR TITLE
delete refs to https://github/gabemontero

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
[testextended][extended:core(openshift pipeline plugin)]

**Comment by bparees** [comment]
needs hack/update-generated

**Comment by gabemontero** [comment]
pushed bindata .. thx

**Comment by bparees** [comment]
lgtm pending test pass

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/14236
[test]

**Comment by gabemontero** [comment]
test hit flake https://github.com/openshift/origin/issues/14236

**Pull request merged**
