### PR TITLE
Missing loading message on browse pages

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/6974
Fixes https://github.com/openshift/origin/issues/6968
Fixes https://github.com/openshift/origin/issues/7030

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett fyi, initial pass, but @sg00dwin has changes in his PR that will affect more pages, so i'm holding off till that goes in to fix those as well.

**Comment by spadgett** [comment]
The interaction feels much better only showing the builds table on the first tab.

**Comment by jwforres** [comment]
@spadgett updated but worried this may conflict with the big build config editor PR for the build-config view, so hold off on merging this till that goes in

**Comment by jwforres** [comment]
@spadgett rebased, although i suspect this will conflict with your changes to the actions on build.html  but go ahead and review whats there if you havent already

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@smarterclayton for 1.1.2

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
