### PR TITLE
tag: Support deleting a tag with -d

### PR DESCRIPTION
**Pull request by kargakis**
@ncdc @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
If we don't want `-d` anymore (since `oc delete istag` is going to delete both spec and status), I will refactor this to keep just the changes that conform to the hacking guide (`*Options` struct with `Complete`, `Validate`, and `Run*`).

@ncdc @smarterclayton

**Comment by ncdc** [comment]
I think Clayton & I need to have a bigger discussion about the relationship
between spec and status, tracking vs one-time importing, etc.

On Wed, Aug 12, 2015 at 11:26 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
Closing this as it needs some work for rebasing and isn't a high priority at all.

@ncdc please let me know the outcome of your discussion if/when that happens.

**Comment by smarterclayton** [comment]
We still need to support this.

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@smarterclayton @soltysh PTAL

**Comment by kargakis** [comment]
@pweil- should we have a Trello card for this?

**Comment by pweil-** [comment]
@kargakis - if it requires QE then you'll need a Trello or BZ

**Comment by kargakis** [comment]
> @kargakis - if it requires QE then you'll need a Trello or BZ

Trello'd: https://trello.com/c/v0BkAuyH/526-delete-spec-tags-using-oc-tag

**Comment by danmcp** [comment]
@soltysh @smarterclayton Bump

**Comment by soltysh** [comment]
I was reveiwing this some but apparently I didn't submit that comment. The general idea or rather a question I had to @smarterclayton. After talking with @kargakis I come up with this usecase:
I'm importing tags from default registry (`spec.dockerImageRepository`), afterwards I remove one of them. Both status and spec (although there's none for that UC) are deleted. Then a reimport happens which results in the tag being reimported, because there's no information we should not. Unless this will use the mechanics I've introduced in #4853 which should then set the removed tag as reference. What do you think?

**Comment by soltysh** [comment]
OK, my previous comment is regarding the other imagestreamtag deletion, I was again misleaded :wink: I've deleted it not to mislead others.

**Comment by smarterclayton** [comment]
knowing a tag was imported automatically is actually kind of important.
Deleting a tag though should remove spec and status, and an admin running
"import all tags" in the repo would expect to get that tag recreated.
Whole repo import is a hammer, so it's ok to treat it that way.

**Comment by soltysh** [comment]
@kargakis there's a failure in test, please take a look and we'll move those IS PRs forward:
```
_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/tag_test.go:23: undefined: "k8s.io/kubernetes/pkg/util".Now
_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/tag_test.go:30: undefined: "k8s.io/kubernetes/pkg/util".Now
```

**Comment by kargakis** [comment]
@soltysh fixed the test

**Comment by soltysh** [comment]
[test] if that is green I'm merging it as is.

**Comment by soltysh** [comment]
Forgot to put the magic LGTM!

**Comment by kargakis** [comment]
Jenkins is green, rekicking Travis which most probably flaked (cannot load it for a magical reason)

**Comment by soltysh** [comment]
The flaky test is from k8s. I'm ok with that.
[merge]

**Comment by kargakis** [comment]
:snowflake: 
```
ERROR: gave up waiting for https://127.0.0.1:28443/healthz

!!! Error in hack/test-cmd.sh:346
	'return 1' exited with status 1
```
re[merge]

**Pull request merged**
