### PR TITLE
bump(github.com/openshift/source-to-image): 69a0d96663b775c5e8fa942401c7bb9ca495e8f0

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jupierce fyi

**Comment by bparees** [comment]
@smarterclayton ptal/merge, this is part of the logging changes you wanted.

**Comment by smarterclayton** [comment]
LGTM [merge] (although I may complain later about some of these)

**Comment by smarterclayton** [comment]
Volumes flake:

=== BEGIN TEST CASE ===
test/cmd/volumes.sh:41: executing 'oc set volume
dc/test-deployment-config --remove --name=vol2' expecting success
FAILURE after 1.194s: test/cmd/volumes.sh:41: executing 'oc set volume
dc/test-deployment-config --remove --name=vol2' expecting success: the
command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: Operation cannot be fulfilled on deploymentconfigs
"test-deployment-config": the object has been modified; please apply
your changes to the latest version and try again
=== END TEST CASE ===


Volumes have an open issue to use patch.


[test]

**Comment by bparees** [comment]
[merge]


On Tue, Jun 21, 2016 at 11:27 PM, OpenShift Bot <notifications@github.com>
wrote:

> continuous-integration/openshift-jenkins/test SUCCESS (
> https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/5213/)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/pull/9471#issuecomment-227633490>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3tq7NsYNmQWcoxHyr4Mu5e811Whoks5qOKuigaJpZM4I7HIv>
> .
>



-- 
Ben Parees | OpenShift

**Pull request merged**
