### PR TITLE
Update protected OpenShift namespaces: openshift-machine-api

### PR DESCRIPTION
**Pull request by enxebre**
Needs:
https://github.com/openshift/machine-api-operator/pull/202
https://github.com/openshift/installer/pull/1215
https://github.com/openshift/cluster-autoscaler-operator/pull/43

### CODE REVIEW

**Comment by enxebre** [comment]
cc @deads2k @derekwaynecarr

**Comment by enxebre** [comment]
ping @derekwaynecarr @smarterclayton @deads2k

**Comment by deads2k** [comment]
lgtm

**Pull request merged**
