### PR TITLE
Web console support for deleting individual builds and deployments

### PR DESCRIPTION
**Pull request by spadgett**
Allow deleting individual builds, deployments, and replication controllers from the UI.

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by liggitt** [comment]
When you delete replication controllers from the CLI, it scales them to 0 as waits for status.replicas to be 0 before deleting the RC. Otherwise you orphan pods. Same for deployment configs to deployments to pods. I'm a little concerned about adding delete operations in the UI that can orphan things

**Comment by spadgett** [comment]
We don't cascade when deleting a deployment config, so we should be OK there. (There's a trello card to support cascading.)

I could just close this. Wondering how useful it is anyway if you can't multi-select to delete multiple builds or deployments. It would be painful to delete them one by one.

**Comment by jwforres** [comment]
I can buy the argument for deployments, but RCs that aren't deployments I
can see wanting a delete button.  Also keep in mind we do allow you to
create builds without using build configs.

Some alternatives in the short term (before we do cascading deletes)...
disabling the delete button on RC's that aren't scaled to zero.  But would
need to be clear why the button was disabled.  Or having it enabled but the
modal is different, instead is a message like "This deployment can't be
deleted until it has been scaled down to zero pods." and just an OK button.
  Or the same modal with an error message in it and the Delete button in
the modal is disabled.

**Comment by spadgett** [comment]
For now, I've disabled the button if the replication controller has status replicas and added a tooltip explaining. iOS still only needs one touch when the button is enabled.

@jwforres PTAL

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
