### PR TITLE
Remove docker IP from server certs

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k

**Comment by deads2k** [comment]
Won't we still appear as that docker bridge IP to things like the deployer pods?

**Comment by liggitt** [comment]
I don't think so... the deployment controller passes in the master address as an env var... I don't think we're using the service envvars

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k curl's `--resolve` param requires an IP to resolve to... passing a Host header tests the routes without requiring we know the IP of API_HOST

**Comment by liggitt** [comment]
@deads2k got clean test runs with this

**Comment by deads2k** [comment]
alright, then [merge]

**Pull request merged**
