### PR TITLE
Deprecate ImageRepository, Add ImageStream

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by smarterclayton** [comment]
This is LGTM, we can clean it up afterwards.  A few things like ensuring tags have a consistent ordering (which might mean we can't use the map internally) can be done afterwards.  Merge when you get a green.

**Comment by ncdc** [comment]
Getting tired of these flakey `hack/test-cmd.sh: line 73: openshift: command not found` failures, grrr

**Comment by smarterclayton** [comment]
That sounds new... Do we have an issue open and someone assigned to triage it?

**Comment by ncdc** [comment]
@smarterclayton it pops up every so often. I've been seeing it every so often for a long time now, but not enough to be annoying. I'll file an issue.

**Comment by ncdc** [comment]
Opened #1579 for the flakey failure

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
GREEN!!!!!

[merge]

**Comment by smarterclayton** [comment]
deploy_trigger_test is commented out - can you restore that?

**Pull request merged**
