### PR TITLE
Update documentation to use 'osc create' consistently

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton fyi, this is pending release image update.

### CODE REVIEW

**Comment by mfojtik** [comment]
Travis is failing because this PR require: https://github.com/openshift/origin/pull/698

**Comment by smarterclayton** [comment]
Ok, the new binaries are out.

**Comment by smarterclayton** [comment]
Rebase

**Comment by mfojtik** [comment]
@smarterclayton rebased

**Comment by smarterclayton** [comment]
[merge]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
```
 ~/go/src/github.com/openshift/origin → ./hack/build-assets.sh 

Running "wiredep:app" (wiredep) task
Warning: Cannot read property 'main' of undefined Use --force to continue.

Aborted due to warnings.
```

@jwforres any idea what is wrong here? :(

**Comment by smarterclayton** [comment]
Rebase and try again?

**Comment by mfojtik** [comment]
@smarterclayton crossing fingers....

**Comment by mfojtik** [comment]
@jwforres i'm stuck here... I cleaned assets, build them again and I still got the failure....

**Comment by mfojtik** [comment]
@jwforres ok, I just found that ./hack/build-assets.sh gives me different results inside vagrant f20 and my host arch linux.... We should do this compilation inside Docker container.

**Comment by smarterclayton** [comment]
Why are they different?  Agree on in that image.

**Comment by mfojtik** [comment]
@smarterclayton the images (PNG) are different which is why the Jenkins job fails... I think the result depends on what versions of libpng you have installed in your system...

**Comment by mfojtik** [comment]
\o/ finally

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
