### PR TITLE
Only show scroll links when log is offscreen

### LINKED ISSUE #5566: We should show the follow log link before 25 lines
I've seen the log scroll of the page before the 25 lines are reached. I'd prefer to just start following the logs right away rather than having to wait.

/cc @jwforres @benjaminapetersen

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #5566

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres please review

**Comment by jwforres** [comment]
Since you are using some native DOM checks, did you check both IE 10 and IE 11 just to be safe

**Comment by spadgett** [comment]
I tested IE 11. Let me check on 10.

**Comment by spadgett** [comment]
Having trouble with my IE 10 environment, but MDN says they're supported since IE 6. 

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight

**Comment by jwforres** [comment]
LGTM
@openshift/team-project-committers fixes some usability weirdness with the appearance of follow log / top of log links, if any part of the log is off screen they will show up now

**Comment by spadgett** [comment]
@jwforres added an extra set of parens around the or condition in `updateScrollLinks`

**Comment by jwforres** [comment]
LGTM, just needs approval

**Comment by smarterclayton** [comment]
Approved, relatively low risk

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
[test]

**Pull request merged**
