### PR TITLE
UPSTREAM: google/cadvisor: 1642 : cAdvisor fs metrics should appear in /metrics

### PR DESCRIPTION
**Pull request by smarterclayton**
Filesystem metrics are missing

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@sjennings @directxman12 backport for 3.6

**Comment by smarterclayton** [comment]
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by smarterclayton** [comment]
flake deployments [merge]

**Pull request merged**
