### PR TITLE
run extended tests post-rebase

### PR DESCRIPTION
**Pull request by liggitt**
pick of https://github.com/openshift/origin/pull/18816 on top of https://github.com/openshift/origin/pull/19137

### CODE REVIEW

**Comment by liggitt** [comment]
@openshift/sig-storage can you take a look at the extended failures in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19260/test_pull_request_origin_extended_conformance_gce/18727/?

seeing these after pulling in 1.10:

* `[sig-storage] CSI Volumes [Feature:CSI] Sanity CSI plugin test using hostPath CSI driver should provision storage with a hostPath CSI driver [Suite:openshift/conformance/parallel] [Suite:k8s]`
* `[sig-storage] EmptyDir wrapper volumes should not conflict [Suite:openshift/conformance/parallel] [Suite:k8s]`
* `[sig-storage] Volumes iSCSI [Feature:Volumes] should be mountable [Suite:openshift/conformance/parallel] [Suite:k8s]`

**Comment by jsafrane** [comment]
> CSI Volumes [Feature:CSI] Sanity CSI plugin test using hostPath CSI driver should provision storage with a hostPath CSI driver

Logs:

```
Failed: Error: failed to start container "hostpath-driver": Error response from daemon: linux mounts: Path /var/lib/kubelet/pods is mounted on / but it is not a shared mount.
```

Hmm, we need either newer docker from RHEL 7.5 or our own custom systemd service for it. How can we do that?

**Comment by jsafrane** [comment]
> EmptyDir wrapper volumes should not conflict

That's actually a regresssion, Kubernetes requires newer git than it's in RHEL 7.
This can be fixed relatively easily. It will break mount containers, but git volume has been deprecated upstream, so we probably don't care.

```
FailedMount: MountVolume.SetUp failed for volume "git-volume" : failed to exec 'git clone http://172.30.8.217:2345 test': Unknown option: -C
```

Filled https://bugzilla.redhat.com/show_bug.cgi?id=1565553

**Comment by jsafrane** [comment]
> Volumes iSCSI [Feature:Volumes] should be mountable 

There is typo in image name: `k8s.gcr.io/volume-icsci:0.1`. I'll fix it upstream and in Origin.

**Comment by jsafrane** [comment]
> EmptyDir wrapper volumes should not conflict

origin PR: https://github.com/openshift/origin/pull/19359

**Pull request closed without merging**
