### PR TITLE
Fix for Bug 1285647

### PR DESCRIPTION
**Pull request by sg00dwin**
Border width will be expanded when long value added in Environment Variables for project

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres 

Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1285647

ffbugfix

**Comment by sg00dwin** [comment]
Fix for https://github.com/openshift/origin/issues/6025

routebug

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
