### PR TITLE
tools: stop updating v1beta3 deep copies/conversions

### PR DESCRIPTION
**Pull request by kargakis**
Closes https://github.com/openshift/origin/issues/7582

@deads2k @liggitt @smarterclayton PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by deads2k** [comment]
@liggitt Looks reasonable to me.  You know of any reason this would bite us?

**Comment by liggitt** [comment]
I would keep the deep copy

**Comment by kargakis** [comment]
> I would keep the deep copy

Mind explaining why? Aren't the already existing deep copies enough for what can be in storage as v1beta3?

**Comment by liggitt** [comment]
if we never add another defaulted field to v1beta3, sure, but we still are (see https://github.com/openshift/origin/commit/13919a5f84211c6a642c19c0c58ed45b8a4516e7#diff-d252205044846e765b0f52910d8ab0ed)

**Comment by liggitt** [comment]
actually, same applies to conversion, since defaulting and conversion are required for new fields with default values to come in successfully from a deserialized v1beta3

**Comment by deads2k** [comment]
> actually, same applies to conversion, since defaulting and conversion are required for new fields with default values to come in successfully from a deserialized v1beta3

Defaults aren't auto generated, so this doesn't affect that one way or the other.

Adding the fields to v1beta3 only needs to happen if you're converting internal to v1beta3, which we don't.  Since we don't have a need to add new fields (we never convert back to v1beta3), I'm not seeing why conversions or deep copies matter.

**Comment by liggitt** [comment]
if a new field comes in, we write a defaulter for it, and deep copy isn't updated, are you sure there is no point in the conversion path that uses deep copy and would lose the new field's value?

**Comment by deads2k** [comment]
You're thinking that we *do* need to be worried about adding fields to allow round tripping through v1beta3?  Why would I ever end up in a case doing that?  Maybe output version, but I'd call that thin.  It'll never round-trip back in because never added the fields.

If we never add the fields, I don't see how a fresh v1beta3 deep copy would help.

**Comment by liggitt** [comment]
not round tripping, defaulting new fields

**Comment by liggitt** [comment]
we added a new field to v1beta3 just this week

**Comment by deads2k** [comment]
Forgot that we don't have a target for defaulting.  That makes me a little cranky.

@kargakis that'd be a no for this pull.

**Pull request closed without merging**
