### PR TITLE
Bug 1840872: UPSTREAM: 88440: Report deleted pod status correctly

### PR DESCRIPTION
**Pull request by rphillips**
This is a cherry-pick of #24841

Note: This includes an additional carry patch for 4.2 to fix the testfile ginkgo calls.

### CODE REVIEW

**Comment by rphillips** [comment]
original bot cherry pick : https://github.com/openshift/origin/pull/25036

**Comment by ashcrow** [comment]
/retitle Bug 1840872: UPSTREAM: 88440: Report deleted pod status correctly

**Pull request merged**
