### PR TITLE
WIP: Registry image pruning reworked

### LINKED ISSUE #3333: Registry pruning improvements
When pruning images and layers, the `oadm prune images` command:
1. determines which images and layers can be pruned
2. removes images and updates image streams in etcd
3. makes multiple http requests to the registry to prune layers and signatures

Instead of sending multiple http requests to the registry, it would be better to store information about which layers and signatures the registry needs to prune. The registry could periodically query OpenShift for that data and act on it.

This has multiple benefits:
1. a potential significant reduction in the number of http requests needed to prune content from the registry
2. less divergence from the upstream registry code base - we had to modify its internals pretty heavily to support deleting signatures and deleting layers via http requests

HA note - if there are multiple replicas of the registry pod, it is probably a good idea to have the registry's pruning task scheduled a bit randomly. For example, replica 1 might run the job at 13 minutes after the hour, while replica 2 might run it at 27 minutes after the hour.

### LINKED ISSUE #4339: Update docker registry package
https://github.com/docker/distribution/releases

When that time comes, [code.google.com/p/go-uuid/uuid](https://github.com/openshift/origin/tree/master/Godeps/_workspace/src/code.google.com/p/go-uuid/uuid) which is a duplicate of [https://github.com/pborman/uuid](https://github.com/openshift/origin/tree/master/Godeps/_workspace/src/github.com/pborman/uuid) can be removed from our deps.

### PR DESCRIPTION
**Pull request by miminar**
Rebases docker/distribution to current upstream master with [storage API expose patch](https://github.com/docker/distribution/pull/1050) applied.

Replaces `/admin/*` routes with just `/admin/prune` that triggers garbage collection.

Garbage collection loads repositories (ImageStreams and ImageStreamDeletions), all their manifest revisions (Images) and dependend objects (layers and signatures). Manifest revision is marked for deletion if it has `DeletionTimestamp` set. Repository is marked for deletion if it is listed among `ImageStreamDeletions`. Any other dependent, loaded  object is preserved if it's referenced by at least one object not marked for deletion.

Resolves #3333
Resolves #4339

TODOs:
- ~~Find a way, how to keep `ImageStreamDeletion` type without the need to export it in cli (which now prevents OSO's compilation).~~ `ImageStreamDeletion`s can now be described.
- ~~Rework `oadm prune` command to just mark obsolete Images for deletion.~~
- ~~Rework deletion of image streams to mark for deletion any referenced image, delete image stream itself and add its name to `imageStreamDeletions`.~~ done
- ~~Define finalizer for Images and trigger its `Finalize()` from inside of docker registry.~~ done
- Remove `admin/prune` route - now used for testing.
- Test it.
- Let the garbage collection runs be configured.

### CODE REVIEW

**Comment by miminar** [comment]
@ncdc, @kargakis: PTAL.

**Comment by ncdc** [comment]
> Rework deletion of image streams to mark for deletion any referenced image

This brings up an interesting question. Let's say I push `project/repo1:latest`, then do `oc tag project/repo1:latest project/repo2:sometag`, and then delete `project/repo1`. If you delete the image because you've deleted repo1, you can no longer pull `project/repo2:sometag` because it points to the image you've just marked for deletion.

**Comment by ncdc** [comment]
cc @smarterclayton

**Comment by ncdc** [comment]
I would like to get rid of the custom /admin route(s) if possible.

Also, when reapplying carried patches, please cherry-pick them individually instead of bundling them into a new commit. It is crucial that patches have commit messages with `UPSTREAM (docker/distribution): <pr #>: <description>`. Or if there isn't an upstream PR and we want to just carry the patch, replace `<pr #>` with `carry`.

**Comment by kargakis** [comment]
> and then delete project/repo1

@ncdc should we not allow deleting image streams that have symlinks?

**Comment by miminar** [comment]
@ncdc If you delete the image because you've deleted repo1, you can no longer pull project/repo2:sometag because it points to the image you've just marked for deletion.

I'm not sure, how `oc tag` works. Ideally, it would create a new manifest with almost identical content except for Name and Tag and re-push. Re-push is needed to create layer links and signatures. Layers are already there. I'd rather have tags in consistence with registry's storage instead of preventing deletion if there were any tags created.

> Also, when reapplying carried patches, please cherry-pick them individually instead of bundling them into a new commit.

I'll try to look them up.

**Comment by liggitt** [comment]
can you add `UPSTREAM: PR|<carry>|<drop>: ...` to the titles of all the commits that touch the distribution Godeps?

**Comment by liggitt** [comment]
and any commits that are just straight godep adds/bumps should have titles of `bump(<dep name>): <version hash>`

**Comment by smarterclayton** [comment]
Is this targeted to 3.1?  It's really, really late to be making changes here.

**Comment by ncdc** [comment]
These are huge changes. I think we need to consider this for 3.2 instead.

**Comment by liggitt** [comment]
agree :fearful:

**Comment by miminar** [comment]
Yeah, that's what I was afraid of happening once we decided to go with finalization and watching its scope extending over the code base. But I agree with you. I'd rather not rush with these changes and give them a second thought.

I'll break up the changes into smaller, tested pieces to make it easier to digest and review.

**Comment by soltysh** [comment]
@miminar are you going to pick it up now that we're post 1.1? I'd love to see this in.

**Comment by miminar** [comment]
@soltysh I'd love to. However, it's still blocked on #4339 which in turn is block on upstream. They respond neither to comments nor on irc. It worries me. I don't know what to do about it.

**Comment by danmcp** [comment]
@miminar What are the next steps here?

**Comment by miminar** [comment]
@danmcp rebase it, split it into smaller pieces for review and write proper tests. This can be closed anyway.

**Pull request closed without merging**
