### PR TITLE
UPSTREAM: 53857: kubelet sync pod throws more detailed events

### PR DESCRIPTION
**Pull request by joelsmith**
Also includes the following upstream dependant PRs:

UPSTREAM: 50350: Wait for container cleanup before deletion
UPSTREAM: 48970: Recreate pod sandbox when the sandbox does not have an IP address.
UPSTREAM: 48589: When faild create pod sandbox record event.
UPSTREAM: 48584: Move event type
UPSTREAM: 47599: Rerun init containers when the pod needs to be restarted

xrefs:
https://github.com/kubernetes/kubernetes/pull/53857
https://github.com/kubernetes/kubernetes/pull/50350
https://github.com/kubernetes/kubernetes/pull/48970
https://github.com/kubernetes/kubernetes/pull/48589
https://github.com/kubernetes/kubernetes/pull/48584
https://github.com/kubernetes/kubernetes/pull/47599

### CODE REVIEW

**Comment by joelsmith** [comment]
Marked `do-not-merge/work-in-progress` since the upstream PR isn't merged and is similarly marked. I'll track that PR and update this one as necessary with any code updates.

cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
/kind bug

Will merge on green

**Comment by joelsmith** [comment]
/retest
Looks like the broken test extended_conformance_install_update
is happy again.

**Comment by joelsmith** [comment]
Closed by mistake (fat fingered on my phone)
/retest

**Comment by sjenning** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16865/origin-ci-verify-origin/215/

Saying you need to run hack/update-generated-swagger-spec.sh.  Suggest rebasing and running that.

Could also be this though:
https://github.com/openshift/origin/issues/16720

**Comment by joelsmith** [comment]
@sjenning While that test shows up as red on the dashboard, it's not the one that's keeping this PR out of the merge queue. That's https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16865/test_pull_request_origin_extended_conformance_gce/9734/ which has a baffling error that I can't reproduce on my own system.

I tried rebasing and updating the swagger API, but it ended up being a no-op.

**Comment by sjenning** [comment]
So out of the last 4 test runs:

Failed 3 times, passed on latest run:
Service Catalog [localhost] ansible_service_broker : validate Dockerhub registry settings

Failed on the latest run but not before:
[Feature:DeploymentConfig] deploymentconfigs with enhanced status [Conformance] should include various info in status [Suite:openshift/conformance/parallel]

Let's roll the dice again.

/retest

**Comment by sjenning** [comment]
might be related to closed flake https://github.com/openshift/origin/issues/13644 ?

**Comment by joelsmith** [comment]
@derekwaynecarr it's passing the tests now

**Pull request merged**
