### PR TITLE
bug 2060406: test: bump apirequests upper bounds for VSphere and AWS single node

### PR DESCRIPTION
**Pull request by ingvagabund**
**periodic-ci-openshift-release-master-nightly-4.11-openshift-e2e-aws-single-node-workers-upgrade-conformance** sequence:

69 68 63 61 62 64 78 60 69 53 66 52 73 64 66 57 61 59 64 68 65 67 52 58 60 68 57 64 57 57 71 65 86

Giving 64 as the median

**periodic-ci-openshift-release-master-nightly-4.11-e2e-vsphere-techpreview-serial** sequence:

101 111 94 86 101 90 109 77 115 138 105 91 102 104 93 86 90 78 65 92 88 110 110 84 100 113 89 100 99 95 99 87 107 86 89 71 108 90 124 95 62 93 96 90 94 90 87 88 80 96 85 88 105 109 107 88 85 91 130 98 102 81 93 94

There are some spikes but mostly holding around 93/94 based on the median.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold 
I've proposed bumping these limits slightly a bit more, 69 and 99, to cover a bit more, I'm fully aware that's a bit more than median.

**Comment by ingvagabund** [comment]
The bounds my code computes are more theoretical. Versus what is reported by the CI. Sometimes it is the median, sometimes only half of it

/hold cancel
/retest-required

**Pull request merged**
