### PR TITLE
EmptyDir security context

### PR DESCRIPTION
**Pull request by pmorie**
Depends on #3037

### CODE REVIEW

**Comment by pmorie** [comment]
@smarterclayton @pweil- FYI but not really ready for review yet.

**Comment by smarterclayton** [comment]
Did this get merged in SCC?

**Comment by pweil-** [comment]
The permissions portion of this was merged in https://github.com/openshift/origin/pull/3115.  The context setting portion is still in the works by @pmorie.

**Comment by smarterclayton** [comment]
What is the ETA?

**Comment by pmorie** [comment]
@smarterclayton I'm working on it now, hope to have it working / tested tonight.

**Comment by pmorie** [comment]
@smarterclayton @pweil- @liggitt I'm getting clean e2e runs with this code.  Adding tests now.

**Comment by pmorie** [comment]
@smarterclayton @pweil- I'm probably going to extract an interface for a thing that does chcon so we can test that the right context was passed to it in the unit tests

**Comment by pmorie** [comment]
@smarterclayton Should we rename 'Level' to 'Range' ?

**Comment by pmorie** [comment]
@smarterclayton Since `Level` really represents the `Range`

**Comment by smarterclayton** [comment]
I'm ok with the changes, have you validated creating an empty dir with enforcing set?  We need to re enable SELinux as a follow up in vagrant (please spawn an issue for that).

**Comment by pmorie** [comment]
@smarterclayton creating an emptyDir w/ enforcing works.  I'm running through the e2e w/ enforcing on now but the registry's running an accepting pushes, secrets are working, etc so far.

**Comment by pmorie** [comment]
@smarterclayton E2E passes with selinux enforcing.  I still have a few more tests I want to write.

**Comment by pmorie** [comment]
@smarterclayton it's no sleep till brooklyn for me wrt this tonight

**Comment by smarterclayton** [comment]
K, follow up for an integration test in test-integration-docker.sh or something in our e2e to explicitly verify we can write to the empty dir.  Let me know when done.

**Comment by pmorie** [comment]
@smarterclayton It's exercised in the e2e because the registry uses an emptyDir directly for its storage

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@smarterclayton Does jenkins run with SELinux enabled?

**Comment by smarterclayton** [comment]
No, it needs to be reenabled after we cut 3.0

**Comment by pmorie** [comment]
@smarterclayton I think this is ready for final review:

1.  E2E passes with SELinux enforcing
2.  Upstream E2E for emptyDir works

Oops, I forgot to run the upstream secrets E2E, but I'm positive it will work since the use-cases for secrets are obviously working in the e2e.

**Comment by pmorie** [comment]
Upstream e2e for secrets doesn't work because the service account has to reference the secret.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by pmorie** [comment]
For: https://github.com/GoogleCloudPlatform/kubernetes/pull/9844

**Pull request merged**
