### PR TITLE
Add DNS support to OpenShift

### PR DESCRIPTION
**Pull request by smarterclayton**
Still remaining - add e2e test for services.

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@deads2k review please

**Comment by brenton** [comment]
A few (hopefully quick) questions:

* This is slightly different than how Kubernetes integrates with SkyDNS, right?  It seems like they plan to run it in pods.  I'm curious why we'd take a different approach.  I guess we're mostly enabling a easy out of the box integration.  The Kubernetes way would likely still work, right?
* Is the intention for cluster dns to provide services _only_ for pods?  I ask mostly because we'd probably have a few more security requirements if we allow arbitrary clients to contact this service.  At a minimum we might want to have some sort of rate limiting.

**Comment by smarterclayton** [comment]
> On Mar 9, 2015, at 9:15 AM, Brenton Leanhardt <notifications@github.com> wrote:
> 
> A few (hopefully quick) questions:
> 
> This is slightly different than how Kubernetes integrates with SkyDNS, right?
Yes, Kubernetes is copying service data into the etcd schema.  This bypasses that.
> It seems like they plan to run it in pods. I'm curious why we'd take a different approach. I guess we're mostly enabling a easy out of the box integration. The Kubernetes way would likely still work, right?
Efficiency.  If we need to we'll eventually have `openshift start dns`.  However, I think this is just something easier to do on the masters.
> Is the intention for cluster dns to provide services only for pods? I ask mostly because we'd probably have a few more security requirements if we allow arbitrary clients to contact this service. At a minimum we might want to have some sort of rate limiting.
Check upstream, they do a few things to limit simultaneous queries.  However, this is internal cluster focused right now.

**Comment by smarterclayton** [comment]
Comments addressed.

**Comment by deads2k** [comment]
lgtm [merge]

**Pull request merged**
