### PR TITLE
Rework ui presentation and markup for builds view. Inclusion of noscript and >ie9 browser support messages.

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres ready for review/merge

**Comment by jwforres** [comment]
@sg00dwin include a screenshot of what the builds page looks like with these changes

**Comment by jwforres** [comment]
also screenshots of what the noscript and IE9 messages look like

**Comment by sg00dwin** [comment]
nojs

**Comment by jwforres** [comment]
could we add a border to that?

**Comment by sg00dwin** [comment]
screen shot 2015-03-18 at 9 30 11 am

nojs2

**Comment by sg00dwin** [comment]
still working on getting the ie9 screenshot

**Comment by sg00dwin** [comment]
@jwforres ^^^ screenshots

**Comment by jwforres** [comment]
Need to revisit IE9 now that my JS related fixes went in yesterday, may want to just take out the IE9 support message from this PR for now and go back and take a look cleaning up IE9 styles later

**Comment by sg00dwin** [comment]
@jwforres took out the ie9 msg and regenerated bindata

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
unrelated failure [merge]

**Comment by jwforres** [comment]
and again [merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
