### PR TITLE
add system logger SCC

### PR DESCRIPTION
**Pull request by pweil-**
Fixes https://github.com/openshift/origin/issues/8504

@sosiouxme - want to test with this branch and see if there is anything else necessary on this SCC for normal operations without access to `privileged`?

### CODE REVIEW

**Comment by sosiouxme** [comment]
I'll give it a go

**Comment by sosiouxme** [comment]
When I tried it with a local Elasticsearch storage volume, I got events like:

`failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: Cannot start container cb5f41b89c85a83ba07ffdff2f82ef63a693cc59dd6d0d175618057b6b716a03: [9] System error: could not synchronise with container process"`

**Comment by sosiouxme** [comment]
Same thing with fluentd actually. Could be something I did wrong... but things seem to work when they're not under this scc.

**Comment by pweil-** [comment]
closing due to inactivity

**Pull request closed without merging**
