### PR TITLE
install-assets: retry bower update

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

On Oct 30, 2015, at 6:25 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6499/)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5553#issuecomment-152664348>.

**Comment by liggitt** [comment]
[test]

**Comment by spadgett** [comment]
This breaks hack/install-assets.sh for me on OS X.

```
➜  origin git:(throttle-scroll) ✗ hack/install-assets.sh
hack/install-assets.sh: line 21: syntax error near unexpected token `>'
```

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/5561

**Pull request merged**
