### PR TITLE
yaml-enable the registry rate limiting config

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @legionus @dmage @mfojtik is there a reason these fields were not annotated for yaml previously?  I want to add doc on how to configure rate limiting via the config file rather than via env variables and this seems like a pre-req to that.

**Comment by miminar** [comment]
Not sure, but it LGTM.

**Comment by bparees** [comment]
@dmage ok, i've updated it to be all lowercase. ptal again.

**Comment by bparees** [comment]
(with it all being lowercase I don't think the annotations are strictly needed, but it removes some ambiguity anyway)

**Pull request merged**
