### PR TITLE
[3.6][Backport] Prune orphaned blobs on registry storage

### PR DESCRIPTION
**Pull request by miminar**
Resolves [bz#1479340](https://bugzilla.redhat.com/show_bug.cgi?id=1479340)
Backports openshift/origin#14585

### CODE REVIEW

**Comment by miminar** [comment]
Obsoletes openshift/ose#827

**Comment by bparees** [comment]
@miminar doesn't this need to be backported to the ose repos's 3.6 release, not origin's, at this point?

**Comment by miminar** [comment]
@bparees I was told that it will be merged to ose automatically once merged here.

**Comment by miminar** [comment]
The same problem as with other `release-3.6` PR https://github.com/openshift/origin/pull/16138#issuecomment-327449225

**Comment by bparees** [comment]
@miminar that wasn't my understanding.  @brenton are backports to origin:release-3.6 automatically being pulled into the ose release 3.6.x branch for errata releases?  My understanding was we had to backport to ose manually.

**Comment by bparees** [comment]
@jupierce may know too ^^^

**Comment by jupierce** [comment]
@bparees We are leaving open the opportunity to merge into origin:release-1.6 for a time because ose CI is not functional. Once ose CI is operational again, engineering will be asked to merge directly into ose.

**Comment by bparees** [comment]
@jupierce got it, thanks.

**Comment by miminar** [comment]
Issue #16143 once again.
/retest

**Comment by miminar** [comment]
Still #16143 
/retest

**Comment by miminar** [comment]
Cool. The extended tests work again. I've just added some fixes for the failing extended tests (#15779 and #15807).

**Pull request merged**
