### PR TITLE
Bug 1988176: [release-4.6] Add test of documented backup/restore procedure

### PR DESCRIPTION
**Pull request by marun**
The 4.6 backport of a [restore script change](https://github.com/openshift/cluster-etcd-operator/pull/624) would benefit from a disruptive job that was capable of validating the documented backup/restore procedure. This PR backports the following PRs to get backup restore testing passing against the release-4.6 branch:

- https://github.com/openshift/origin/pull/25707
-  https://github.com/openshift/origin/pull/25723

/cc @hexfusion @smarterclayton

### CODE REVIEW

**Comment by aravindhp** [comment]
Note to self: waiting on lgtm

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Pull request merged**
