### PR TITLE
[3.7] UPSTREAM: 57422: Rework method of updating atomic-updated data volumes

### PR DESCRIPTION
**Pull request by joelsmith**
See #18165 for background info.

### CODE REVIEW

**Comment by sjenning** [comment]
flake https://github.com/openshift/origin/issues/16994
/test extended_conformance_gce

**Comment by jsafrane** [comment]
We usually don't backport things to old Origin releases, we use OSE instead.

**Comment by jsafrane** [comment]
ok, we do backport important fixes :-)

/lgtm

**Pull request merged**
