### PR TITLE
Increase journald rate limiter when running test-end-to-end-docker.sh

### LINKED ISSUE #12558: test/end-to-end/core.sh:376: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10167/consoleFull:

```
FAILURE after 0.223s: test/end-to-end/core.sh:375: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
NAME                 READY     STATUS    RESTARTS   AGE
kubectl-with-token   1/1       Running   0          5s
```

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #12558 by increasing rate limiter values while `running test-end-to-end-docker.sh`. Additionally, this re-enables the tests that were disabled due to that error. 

@stevekuznetsov ptal
@smarterclayton fyi

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by smarterclayton** [comment]
Why aren't we just changing the base ami?

**Comment by smarterclayton** [comment]
Is there an issue to ansible team that disables this (or has the discussion about it) as well?  I can't think of a good reason for user logs to get thrown away in the long run.

**Comment by soltysh** [comment]
> Is there an issue to ansible team that disables this (or has the discussion about it) as well? I can't think of a good reason for user logs to get thrown away in the long run.

I'll open a PR in a few. 

> Why aren't we just changing the base ami?

@stevekuznetsov was hesitant to do that, but I'm fine with having this explicit here.

**Comment by smarterclayton** [comment]
I'd prefer to change the base ami if we would also be making ansible changes to a recommended configuration.

The tradeoff of losing app data is pretty important - that needs to be understood by an admin.  Not ignored.

**Comment by stevekuznetsov** [comment]
@smarterclayton my comment to @soltysh was that we should run against the cluster set up by `openshift-ansible` and that this should be a short patch to get us there. not sure I want to change the base ami if the installer is going to arm wrestle for who gets to set the real values

**Comment by soltysh** [comment]
The ansible change was submitted here: https://github.com/openshift/openshift-ansible/pull/3753

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/13271.

[test]

**Comment by soltysh** [comment]
@smarterclayton since the discussion with ansible folks is under way, are you ok with this merging as is. This will fix our problems and gets our test back, which was excluded temporarily?

**Comment by smarterclayton** [comment]
LGTM

**Comment by soltysh** [comment]
Thx, will merge on green tests.

**Comment by soltysh** [comment]
Hmmm... it looks like this increased rate limits uncovered some error:
```
[INFO] Validating exec
Running test/end-to-end/core.sh:463: executing 'oc exec -p frontend-1-2tcnx id' expecting success and text '1000'...
SUCCESS after 0.274s: test/end-to-end/core.sh:463: executing 'oc exec -p frontend-1-2tcnx id' expecting success and text '1000'
Standard output from the command:
uid=1000050000 gid=0(root) groups=0(root),1000050000

Standard error from the command:
W0324 10:00:15.686149   16605 cmd.go:337] -p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.

Running test/end-to-end/core.sh:464: executing 'oc rsh pod/frontend-1-2tcnx id -u' expecting success and text '1000'...
Connection to 172.18.8.26 closed by remote host.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
```
I'll try to dig into it more, in that case.

**Comment by soltysh** [comment]
I've rebased this and will wait for tests. The error I've pointed in previous comment doesn't look like caused by this PR (seen in others as well). I'll give it a fresh run. When green will merge based on previous approval.

**Comment by soltysh** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@mfojtik @dobbymoodge so here's a fun fact ... the `merge-pretest-success` merged this in _while_ the merge job was running. and the merge job hung for six hours and the rest of the queue was broken but nevertheless it seems weird that we can merge while a job is already running .... I really do not like the pretest success feature and we should be _super_ careful with it

**Comment by dobbymoodge** [comment]
@stevekuznetsov Whoah, that is weird.

**Comment by mfojtik** [comment]
@stevekuznetsov hrm, shouldn't the pretest merge create some lock file (or merge job) that wiill block till the premerge/merge finishes?

**Comment by stevekuznetsov** [comment]
Maybe it should. Still wouldn't have helped if it got pushed in this PR before the merge job started. I think we have a very complex system that entirely depends on merges happening serially. The pre-test success option breaks that assumption and I don't think all of the edge cases or interactions were ever taken into account. Especially with the cross repo tests, it's more dangerous tipsy than ever before. I've never been a huge fan of the option but I'd rather see effort put into getting us SubmitQueue and Prow than trying to untangle pre-test success.

**Pull request merged**
