### PR TITLE
Revert "Increase journald rate limiter when running test-end-to-end-docker.sh"

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Reverts openshift/origin#13529

[test][merge]

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton if you're around and like green buttons... all yours

**Comment by stevekuznetsov** [comment]
fixes https://github.com/openshift/origin/issues/13662

**Comment by enj** [comment]
cc @soltysh

**Comment by mfojtik** [comment]
force merged to unblock the merge queue. @stevekuznetsov i'm sorry for this mess :/

**Comment by soltysh** [comment]
I'm very sorry for all the trouble my PR caused 😭

**Pull request merged**
