### PR TITLE
SCCs: remove reconciliation and bootstrap code

### PR DESCRIPTION
**Pull request by stlaz**
Remove unused bootstrap code. Also remove the `oc adm policy reconcile-sccs` command which should no more be used as the reconciliation is now performed by CVO with KAS-O manifests.

### CODE REVIEW

**Comment by stlaz** [comment]
@openshift/sig-auth

**Comment by mrogers950** [comment]
@stlaz This LGTM, but needs a rebase.

**Comment by stlaz** [comment]
Depends on https://github.com/openshift/origin/pull/22756

**Comment by enj** [comment]
/uncc

@stlaz @sttts @mfojtik

**Pull request closed without merging**
