### PR TITLE
Fix manpage formatting for list items

### PR DESCRIPTION
**Pull request by juanvallejo**
Related trello card: https://trello.com/c/SbXIB0sW/595-3-cli-man-pages-for-oc-oadm-openshift
Fixes bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1351059

There is a bug in the package github.com/cpuguy83/go-md2man/md2man that causes lists to be rendered incorrectly in manpages, with arbitrary characters and no linebreaks between items.

##### Before
```
       0

              item  "start": after old deployments are scaled to zero item "pre": after the pre hook completes (even
              if no hook specified) item "mid": after the mid hook completes (even if no hook specified) item A per‐
              centage of the deployment, based on which strategy is in use

       0

              item  "0%"    Recreate  after the previous deployment is scaled to zero item "N%"   Recreate after the
              acceptance check if this is not the first deployment item "0%"   Rolling  before the  rolling  deploy‐
              ment is started, equivalent to "pre" item "N%"   Rolling  the percentage of pods in the target deploy‐
              ment that are ready item "100%" All      after the deployment is at full scale, but  before  the  post
              hook runs
```

##### After
```
              · "start": after old deployments are scaled to zero

              · "pre": after the pre hook completes (even if no hook specified)

              · "mid": after the mid hook completes (even if no hook specified)

              · A percentage of the deployment, based on which strategy is in use

              · "0%"   Recreate after the previous deployment is scaled to zero

              · "N%"   Recreate after the acceptance check if this is not the first deployment

              · "0%"   Rolling  before the rolling deployment is started, equivalent to "pre"

              · "N%"   Rolling  the percentage of pods in the target deployment that are ready

              · "100%" All      after the deployment is at full scale, but before the post hook runs
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
@fabianofranz could you take a look please? thanks!

**Comment by fabianofranz** [comment]
LGTM, [merge]

@juanvallejo Once this gets merged please move the bug to ON_QA with a comment pointing to this PR. Also, does this affect upstream? If so might be worth submitting the patch or at least open an issue to let them know. Tks!

**Comment by juanvallejo** [comment]
Possible flake? re[test]

**Comment by juanvallejo** [comment]
@fabianofranz 
> does this affect upstream? If so might be worth submitting the patch or at least open an issue to let them know

So far, I have not seen the use of "*" to indicate lists in any of their commands' help. Use of "*" and "-" in our commands was the overall cause for misprinted lists on the man pages. I will keep checking though.

**Comment by fabianofranz** [comment]
flake, [merge] again

**Comment by fabianofranz** [comment]
Plz Jenkins, can't we have nice things on a friday night? re[merge]

**Comment by fabianofranz** [comment]
[ḿerge]

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
\o/

**Pull request merged**
