### PR TITLE
UPSTREAM: drop: short flags for oc create configmap

### PR DESCRIPTION
**Pull request by sosiouxme**
fixes issue https://github.com/openshift/origin/issues/9078

### CODE REVIEW

**Comment by sosiouxme** [comment]
@deads @liggitt thoughts on the short flag choices?

**Comment by liggitt** [comment]
`f` means "file containing API object definitions" in almost every other context

**Comment by deads2k** [comment]
> f means "file containing API object definitions" in almost every other context

Agree.  Didn't see this until I already commented on the issue.  @deads2k, :)

**Comment by deads2k** [comment]
I'm fine with the idea in concept, but I think we should get it merged upstream first so we don't end up with scripts that only work for openshift's kubectl.

Oh, an `-l` means "label selector" in most commands too.  Bad luck on the letters :)

**Comment by sosiouxme** [comment]
True, so a question is whether `f` is more strongly associate with a file or with the API object contents. Regardless, I'm open to alternatives.

**Comment by sosiouxme** [comment]
I'm bringing it up here to try to figure it out before submitting upstream, but we can go the other direction if you'd like.

**Comment by sosiouxme** [comment]
I guess this would need to apply to `oc create secret generic` as well since it has the same two flags.

**Comment by sosiouxme** [comment]
@deads2k @liggitt I looked at the other `oc create` subcommands for clues, but none of them have options like this. Of course, the rest are not very much like creating a hash, which `oc create secret|configmap` are.

I think the context here is different enough that if the short flags don't already have an evident application, their familiarity works to our advantage.

Now, `-l` in the context of creating something could conceivably have another use - setting a label on the configmap/secret (not a bad idea to be able to do that without a separate `oc label` invocation), so there is grounds for confusion. Perhaps a good alternative is `-s` (for "scalar" or "set").

But `-f` is pretty clearly for supplying a file. It doesn't make sense to define a configmap/secret from a file in this context, but it does make a lot of sense to define one of its keys with a file, and I can't think of anything better than `-f` for that. Can you?

**Comment by deads2k** [comment]
`-f` is standard across all commands, including `oc create`.  Having a flag change in meaning that significantly for a single command would be frustrating.

I don't think that `-i` for input files and `-s` for string literals would collide yet, but @csrwng probably wants `-i` for his `oc set` changes (and I might too).

**Comment by sosiouxme** [comment]
`-f` doesn't exist yet for any `oc create` subcommand. I still think it's better, but it's not a big deal to me. Do we have any precedent for anything using `-i` (or in fact, anything other than `-f`) to mean a file input?

I'll make an upstream issue for it if we can at least settle on a preliminary idea for the flags.

**Comment by deads2k** [comment]
> Do we have any precedent for anything using -i

No.  @csrwng, @eparis, and I want a new flag for `kubectl` commands that means "use this file content as input" instead of the `-f` meaning of "use this file to get resource/name tuples".  `-i` actually feels pretty natural to me.

**Comment by eparis** [comment]
I know upstream is growing strongly opposed to short flags as a rule, and I think we should be to. Unless a flag is going to be used like 75% of the time, we shouldn't make a shorthand at all....

**Comment by sosiouxme** [comment]
If you're creating a configmap or a secret, you're going to be putting contents in it. I would think these flags would be used 100% of the time.

**Comment by ncdc** [comment]
Don't forget about `-i` in `run/exec/attach`.

**Comment by sosiouxme** [comment]
If anyone would like to poke this upstream the PR is https://github.com/kubernetes/kubernetes/pull/27640

**Pull request closed without merging**
