### PR TITLE
Use utilruntime.HandleError instead of glog.Error in openshift SDN

### PR DESCRIPTION
**Pull request by pravisankar**
- This ensures that we get rate limiting, non user errors are reported to sentry and also that hotloop requests get processed.

### CODE REVIEW

**Comment by pravisankar** [comment]
@smarterclayton @openshift/sig-networking PTAL

**Comment by danwinship** [comment]
@smarterclayton did you really mean to just replace every call to glog.Errorf in pkg/network with a call to utilruntime.HandleError instead? If so, shouldn't we fix utilruntime.HandleError to take a format string and args so we don't have to say "utilruntime.HandleError(fmt.Errorf("blah blah blah: %v", err))"? And if not, when are we supposed to and not supposed to use HandleError rather than glog.Errorf?

**Comment by smarterclayton** [comment]
Yes.  That is our Kubernetes and OpenShift wide policy.  ANY place we eat
an error, should be HandleError.  If it's not actually an error, but a
warning, it should be V(2).Infof or higher and handled explicitly.
 glog.Errorf is basically the equivalent of Java "try {} catch (Exception
e) {}" and we want to be able to audit all the sites and route those errors.

We don't want to change HandleError to be Errorf because what gleg.Errorf
is printing is actually an error, and when we add nested stack traces and
error wrappers in the future, having a formatter would break that (there
are places preparing for that).  We want the actual error object so that we
can report it to external services like sentry (all panics get sent to
sentry today).

**Comment by smarterclayton** [comment]
Note that HandleError does rate limiting and de-dup which prevents
pathological failure modes where controllers crash loop.  We want a central
point of control for "something fell out the bottom of the code"

**Comment by pravisankar** [comment]
@smarterclayton Why V(2).Infof() is preferred over Warningf()? Currently we do print 20+ warnings as glog.Warningf in pkg/network

**Comment by smarterclayton** [comment]
Well, it's more:

1. does it happen all the time?  then why is happening all the time and why
are we warning, we should fix it instead.  If it's really a debugging
message, give it a debug level
2. if it happens rarely it can be a warning

The underlying philosophy is that logging too much can break you as much as
logging too little.

**Comment by danwinship** [comment]
> We don't want to change HandleError to be Errorf because what gleg.Errorf is printing is actually an error, and when we add nested stack traces and error wrappers in the future, having a formatter would break that

But there isn't a single place in this patch where we just call `utilruntime.HandleError(err)`. In every single case, we want to log an additional message beyond the raw error itself, so we end up having to call `fmt.Errorf()` to wrap that message in an error so we can pass it to HandleError. eg:

    utilruntime.HandleError(fmt.Errorf("Invalid TTL value for domain: %q, err: %v, defaulting ttl=%s", dns, err, defaultTTL.String()))

**Comment by pravisankar** [comment]
On Wed, Jan 31, 2018 at 9:58 AM, Dan Winship <notifications@github.com>
wrote:

> We don't want to change HandleError to be Errorf because what gleg.Errorf
> is printing is actually an error, and when we add nested stack traces and
> error wrappers in the future, having a formatter would break that
>
> But there isn't a single place in this patch where we just call
> utilruntime.HandleError(err). In every single case, we want to log an
> additional message beyond the raw error itself, so we end up having to call
> fmt.Errorf() to wrap that message in an error so we can pass it to
> HandleError. eg:
>
> utilruntime.HandleError(fmt.Errorf("Invalid TTL value for domain: %q, err: %v, defaulting ttl=%s", dns, err, defaultTTL.String()))
>
>
There are couple of places in this patch where we call
utilruntime.HandleError(err)

https://github.com/openshift/origin/pull/18343/files#diff-ee33a97446bc9c289d9d689af0ba2c07R49
https://github.com/openshift/origin/pull/18343/files#diff-ee33a97446bc9c289d9d689af0ba2c07R98

But yes, majority of them are of the format 'utilruntime.HandleError(fmt.
Errorf('.
I think a wrapper that takes the formatter, creates an error object and
calls utilruntime.HandleError(err) would be clean.

**Comment by smarterclayton** [comment]
fmt.Errorf( is 10 characters :)  It's not the end of the world

On Wed, Jan 31, 2018 at 1:38 PM, Ravi Sankar Penta <notifications@github.com

**Pull request merged**
