### PR TITLE
OSASINFRA-3109: networking: add a test for control plane LB

### PR DESCRIPTION
**Pull request by EmilienM**
For on-prem platforms, check whether the HAproxy & Keepalived pods are
running, depending on the configuration of the Platform.

If using the internal LB managed by OpenShift, it should be running.
If running UPI or an External LB, it should not be running.

### CODE REVIEW

**Comment by EmilienM** [comment]
The errors in `ci/prow/verify` will be fixed by https://github.com/openshift/origin/pull/27746

**Comment by cybertron** [comment]
/lgtm

Assuming ci passes once the jobs are fixed.

**Comment by EmilienM** [comment]
testing vsphere UPI via https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-vsphere-modern/1630372478419210240

**Pull request merged**
