### PR TITLE
fix manifestlist mirroring

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
```
 oc image mirror docker.io/library/ruby:2 172.30.206.161:5000/p1/ruby:2 --insecure

```
still fails with:
```
error: unable to push manifest to 172.30.206.161:5000/p1/ruby: manifest invalid: manifest invalid
```

though.  Presumably because our registry doesn't support manifest lists.

**Comment by smarterclayton** [comment]
lgtm, won't merge it yet though while sorting out master.

**Comment by bparees** [comment]
/hold

@smarterclayton you can put your lgtm on it and i'll remove the hold when it's time.

**Pull request merged**
