### PR TITLE
Cleanup Vagrantfile

### PR DESCRIPTION
**Pull request by pravisankar**
Specify default values only once.

### CODE REVIEW

**Comment by pravisankar** [comment]
@marun @rajatchopra PTAL

**Comment by rajatchopra** [comment]
Looks good.
[test]

**Comment by rajatchopra** [comment]
[test] again

**Comment by pravisankar** [comment]
[merge]

**Comment by rajatchopra** [comment]
[merge]

**Comment by rajatchopra** [comment]
re [merge]

**Comment by pravisankar** [comment]
[merge]

**Pull request merged**
