### PR TITLE
provider recorder to attach detach controller

### PR DESCRIPTION
**Pull request by rootfs**
fix bz https://bugzilla.redhat.com/show_bug.cgi?id=1427227

@gnufied @jsafrane @childsb

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by jsafrane** [comment]
[test]

**Comment by jsafrane** [comment]
@rootfs, please follow commit guidelines and add `UPSTREAM: xyz` to the commit message.

**Comment by jsafrane** [comment]
oops, sorry, it's OpenShift master, not vendor/kubernetes master...

**Comment by jsafrane** [comment]
@rootfs, we need also PR against origin/master so it's fixed in 1.6.

**Comment by jsafrane** [comment]
[merge]

**Pull request merged**
