### PR TITLE
bump(*) ibm-ingress2 changes from API

### PR DESCRIPTION
**Pull request by AndreaM12345**

### CODE REVIEW

**Comment by AndreaM12345** [comment]
results of hack/update-deps.sh:
```git status
Refresh index: 100% (56964/56964), done.
On branch ibm-ingress2
Your branch is up to date with 'origin/ibm-ingress2'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   glide.lock
	modified:   glide.yaml
	modified:   vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
	modified:   vendor/github.com/openshift/api/config/v1/types_feature.go
	modified:   vendor/github.com/openshift/api/config/v1/types_infrastructure.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/go.mod
	modified:   vendor/github.com/openshift/api/hack/update-protobuf.sh
	modified:   vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
	modified:   vendor/github.com/openshift/api/operator/v1/types_ingress.go
	modified:   vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/apiserver-library-go/go.mod
	modified:   vendor/github.com/openshift/apiserver-library-go/go.sum
	modified:   vendor/github.com/openshift/client-go/go.mod
	modified:   vendor/github.com/openshift/client-go/go.sum
	deleted:    vendor/github.com/openshift/library-go/pkg/dependencymanagement/doc.go
	modified:   vendor/github.com/stretchr/objx/.codeclimate.yml
	modified:   vendor/github.com/stretchr/objx/.travis.yml
	deleted:    vendor/github.com/stretchr/objx/Gopkg.lock
	deleted:    vendor/github.com/stretchr/objx/Gopkg.toml
	modified:   vendor/github.com/stretchr/objx/README.md
	modified:   vendor/github.com/stretchr/objx/Taskfile.yml
	modified:   vendor/github.com/stretchr/objx/accessors.go
	modified:   vendor/github.com/stretchr/objx/accessors_test.go
	modified:   vendor/github.com/stretchr/objx/codegen/template.txt
	modified:   vendor/github.com/stretchr/objx/codegen/template_test.txt
	modified:   vendor/github.com/stretchr/objx/codegen/types_list.txt
	deleted:    vendor/github.com/stretchr/objx/constants.go
	modified:   vendor/github.com/stretchr/objx/conversions.go
	modified:   vendor/github.com/stretchr/objx/conversions_test.go
	modified:   vendor/github.com/stretchr/objx/map.go
	modified:   vendor/github.com/stretchr/objx/map_test.go
	modified:   vendor/github.com/stretchr/objx/type_specific_codegen.go
	modified:   vendor/github.com/stretchr/objx/type_specific_codegen_test.go
	modified:   vendor/github.com/stretchr/objx/value.go
	modified:   vendor/github.com/stretchr/objx/value_test.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/github.com/openshift/api/config/v1/types_features_test.go
	vendor/github.com/openshift/api/third_party/
	vendor/github.com/openshift/library-go/pkg/dependencymagnet/
	vendor/github.com/stretchr/objx/.github/PULL_REQUEST_TEMPLATE.md
	vendor/github.com/stretchr/objx/go.mod
	vendor/github.com/stretchr/objx/go.sum
	vendor/github.com/stretchr/objx/type_specific.go
	vendor/github.com/stretchr/objx/type_specific_test.go```

**Comment by AndreaM12345** [comment]
PR follows changes from the API PR https://github.com/openshift/api/pull/557

**Comment by soltysh** [comment]
/ok-to-test
/hold
for the api PR to merge first

**Comment by AndreaM12345** [comment]
Andreas-MacBook-Pro:origin andreama$ git status
Refresh index: 100% (56968/56968), done.
On branch ibm-ingress2
Your branch is up to date with 'origin/ibm-ingress2'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   glide.lock
	modified:   glide.yaml
	modified:   vendor/github.com/containerd/continuity/fs/copy.go
	modified:   vendor/github.com/containerd/continuity/fs/copy_linux.go
	modified:   vendor/github.com/containerd/continuity/fs/copy_unix.go
	deleted:    vendor/github.com/containerd/continuity/fs/stat_bsd.go
	deleted:    vendor/github.com/containerd/continuity/fs/stat_linux.go
	modified:   vendor/github.com/containerd/continuity/sysx/nodata_unix.go
	modified:   vendor/github.com/openshift/api/Dockerfile.build
	modified:   vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
	modified:   vendor/github.com/openshift/api/config/v1/types_feature.go
	modified:   vendor/github.com/openshift/api/config/v1/types_features_test.go
	modified:   vendor/github.com/openshift/api/config/v1/types_infrastructure.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/go.mod
	modified:   vendor/github.com/openshift/api/go.sum
	modified:   vendor/github.com/openshift/api/image/v1/generated.pb.go
	modified:   vendor/github.com/openshift/api/image/v1/generated.proto
	modified:   vendor/github.com/openshift/api/image/v1/register.go
	modified:   vendor/github.com/openshift/api/image/v1/types.go
	modified:   vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
	modified:   vendor/github.com/openshift/api/imageregistry/v1/register.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/types.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
	modified:   vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
	modified:   vendor/github.com/openshift/api/operator/v1/register.go
	modified:   vendor/github.com/openshift/api/operator/v1/types_authentication.go
	modified:   vendor/github.com/openshift/api/operator/v1/types_ingress.go
	modified:   vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/client-go/go.mod
	modified:   vendor/github.com/openshift/client-go/go.sum
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image_client.go
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
	modified:   vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imageregistry_client.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/generic.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/interface.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
	modified:   vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
	modified:   vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
	modified:   vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
	modified:   vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
	modified:   vendor/github.com/openshift/library-go/go.mod
	modified:   vendor/github.com/openshift/library-go/go.sum
	modified:   vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
	modified:   vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
	modified:   vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
	modified:   vendor/k8s.io/kubernetes/cmd/kubelet/app/options/options.go
	modified:   vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
	modified:   vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go
	modified:   vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters.go
	modified:   vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters_test.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/named_certificates.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/named_certificates_test.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/server_test.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/tlsconfig.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/shufflesharding/shufflesharding_test.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/errors/errors.go
	modified:   vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
	modified:   vendor/k8s.io/kubernetes/test/e2e/generated/bindata.go
	modified:   vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-attacher.yaml
	modified:   vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
	modified:   vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-provisioner.yaml
	modified:   vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-resizer.yaml
	modified:   vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-snapshotter.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/github.com/containerd/continuity/fs/stat_darwinfreebsd.go
	vendor/github.com/containerd/continuity/fs/stat_linuxopenbsd.go
	vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
	vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
	vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
	vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
	vendor/github.com/openshift/client-go/examples/build/app
	vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagetag.go
	vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
	vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
	vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/listers/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/
	vendor/github.com/openshift/library-go/test/library/metrics/

**Comment by AndreaM12345** [comment]
updated results of hack/update-deps.sh: after openshift/api was merged:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   glide.lock
	modified:   vendor/github.com/containerd/continuity/fs/copy.go
	modified:   vendor/github.com/containerd/continuity/fs/copy_linux.go
	modified:   vendor/github.com/containerd/continuity/fs/copy_unix.go
	deleted:    vendor/github.com/containerd/continuity/fs/stat_bsd.go
	deleted:    vendor/github.com/containerd/continuity/fs/stat_linux.go
	modified:   vendor/github.com/containerd/continuity/sysx/nodata_unix.go
	modified:   vendor/github.com/openshift/api/Dockerfile.build
	modified:   vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
	modified:   vendor/github.com/openshift/api/config/v1/types_feature.go
	modified:   vendor/github.com/openshift/api/config/v1/types_features_test.go
	modified:   vendor/github.com/openshift/api/config/v1/types_infrastructure.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/go.mod
	modified:   vendor/github.com/openshift/api/go.sum
	modified:   vendor/github.com/openshift/api/image/v1/generated.pb.go
	modified:   vendor/github.com/openshift/api/image/v1/generated.proto
	modified:   vendor/github.com/openshift/api/image/v1/register.go
	modified:   vendor/github.com/openshift/api/image/v1/types.go
	modified:   vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
	modified:   vendor/github.com/openshift/api/imageregistry/v1/register.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/types.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
	modified:   vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
	modified:   vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
	modified:   vendor/github.com/openshift/api/operator/v1/register.go
	modified:   vendor/github.com/openshift/api/operator/v1/types_authentication.go
	modified:   vendor/github.com/openshift/api/operator/v1/types_ingress.go
	modified:   vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
	modified:   vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
	deleted:    vendor/github.com/openshift/apiserver-library-go/glide.lock
	deleted:    vendor/github.com/openshift/apiserver-library-go/glide.yaml
	modified:   vendor/github.com/openshift/apiserver-library-go/hack/update-generated-deep-copies.sh
	modified:   vendor/github.com/openshift/client-go/go.mod
	modified:   vendor/github.com/openshift/client-go/go.sum
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image_client.go
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
	modified:   vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imageregistry_client.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/generic.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/interface.go
	modified:   vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
	modified:   vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
	modified:   vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
	modified:   vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
	modified:   vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
	modified:   vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
	modified:   vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
	modified:   vendor/github.com/openshift/library-go/go.mod
	modified:   vendor/github.com/openshift/library-go/go.sum
	modified:   vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
	modified:   vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
	modified:   vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
	modified:   vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
	modified:   vendor/github.com/openshift/library-go/test/library/encryption/helpers.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/github.com/containerd/continuity/fs/stat_darwinfreebsd.go
	vendor/github.com/containerd/continuity/fs/stat_linuxopenbsd.go
	vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
	vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
	vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
	vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
	vendor/github.com/openshift/apiserver-library-go/go.mod
	vendor/github.com/openshift/apiserver-library-go/go.sum
	vendor/github.com/openshift/apiserver-library-go/pkg/dependencymagnet/
	vendor/github.com/openshift/client-go/examples/build/app
	vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagetag.go
	vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
	vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
	vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake/fake_imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/informers/externalversions/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/imageregistry/listers/imageregistry/v1/imagepruner.go
	vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/client-go/operator/listers/operator/v1/csisnapshotcontroller.go
	vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/
	vendor/github.com/openshift/library-go/test/library/metrics/
```

**Comment by AndreaM12345** [comment]
looks like the master has been updated already so thinking this one can be closed

**Pull request closed without merging**
