### PR TITLE
Replace legacy IS informer with generated informers everywhere

### PR DESCRIPTION
**Pull request by smarterclayton**
Also make it available to GC. Remove "images" from GC for now.

Only the last two commits are new to this PR.

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Build flake

**Comment by smarterclayton** [comment]
@mfojtik this is part of a chain, please review image stream generator changes

**Comment by mfojtik** [comment]
@smarterclayton LGTM good stuff. this will probably break you: https://github.com/openshift/origin/pull/14317 (or you break me 👿 )

**Comment by smarterclayton** [comment]
[merge] but I bet you beat me in

**Pull request merged**
