### PR TITLE
UPSTREAM: 52515: Clarify predicates name to clean confusing.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@sjenning @stevekuznetsov 

The commits are a bit modified for 3.7. Also the title seems a bit confusing but I just copied it from upstream PR.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I don't think I can make the approval call on the backport, but thank you for doing this.

/lgtm

**Comment by aveshagarwal** [comment]
flakes: https://github.com/openshift/origin/issues/16802

**Comment by aveshagarwal** [comment]
flakes: https://github.com/openshift/origin/issues/14385

**Comment by aveshagarwal** [comment]
The last one is spooky:
```
Result | FAILURE
-- | --
Tests | 0 failed / 6085 succeeded

```

**Comment by aveshagarwal** [comment]
Thoough it shows that no failure:

```
Result | FAILURE
-- | --
Tests | 0 failed / 6084 succeeded
```

But there seems to be a failure here:

```
In suite "github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/volume/flocker", test case "TestNewUnmounter" was skipped:
=== RUN   TestNewUnmounter
--- SKIP: TestNewUnmounter (0.00s)
	flocker_test.go:291: broken
[WARNING] While the jUnit report found no failed tests, the `go test` process failed.
[WARNING] This usually means that the unit test suite failed to compile.
[ERROR] hack/test-go.sh exited with code 2 after 00h 31m 43s
make: *** [test-unit] Error 2
[ERROR] PID 12616: hack/lib/build/environment.sh:166: `return "${exitcode}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/environment.sh:166: `return "${exitcode}"`
[INFO] 		  2: hack/lib/build/environment.sh:275: os::build::environment::withsource
[INFO] 		  3: hack/env:42: os::build::environment::run
[INFO]   Exiting with code 2.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINI
```

**Comment by aveshagarwal** [comment]
```
[WARNING] `go test` had the following output to stderr:
# github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/core
vendor/k8s.io/kubernetes/plugin/pkg/scheduler/core/generic_scheduler_test.go:417: undefined: err in err.Error
vendor/k8s.io/kubernetes/plugin/pkg/scheduler/core/generic_scheduler_test.go:418: undefined: err in err.Error
[INFO] No compiled `junitreport` binary was found. Attempting to build one using:
[INFO]   $ hack/build-go.sh tools/junitreport
++ Building go targets for linux/amd64: tools/junitreport
[INFO] hack/build-go.sh exited with code 0 after 00h 00m 09s
[INFO] jUnit XML report placed at _output/scripts/test-go/artifacts/gotest_report_QkgkH.xml
Of 6103 tests executed in 2597.673s, 6084 succeeded, 0 failed, and 19 were skipped.
In suite "github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/cloudprovider/pro
```

**Comment by aveshagarwal** [comment]
I think I found the issue, will update and submit.

**Comment by aveshagarwal** [comment]
flakes: https://github.com/openshift/origin/issues/16810 and https://github.com/openshift/origin/issues/16012 and https://github.com/openshift/origin/issues/16812

/test integration

**Comment by aveshagarwal** [comment]
@sjenning @stevekuznetsov could you tag lgtm again?

**Comment by aveshagarwal** [comment]
flakes: https://github.com/openshift/origin/issues/16837, https://github.com/openshift/origin/issues/16838

/test extended_conformance_gce

**Pull request merged**
