### PR TITLE
[WIP] Expose build metrics

### PR DESCRIPTION
**Pull request by vbehar**
Hi guys,

It would be great to have more insights on the builds for monitoring/alerting. For the "run" part, there are already lots of metrics exposed in prometheus format by kubernetes, but for the build there is nothing.

How do you feel about exposing some build metrics in prometheus format ? I've started by recording the distribution of builds duration directly in the controller - don't know if it's the right place to put it.

If you agree, I will add more metrics, for example the builds phase (to be able to see if there are lots of build errors)

### CODE REVIEW

**Comment by danmcp** [comment]
@bparees @mwringe Review please

**Comment by mwringe** [comment]
Where does this metric end up exactly? Just under the /metrics endpoint, or somewhere else?

**Comment by bparees** [comment]
this is intended for a cluster administrator, compared w/ the existing build stats that are exposed to the openshift user via the web console?

@smarterclayton this feels above my paygrade, what's are philosophy around prometheus?

**Comment by vbehar** [comment]
yes, it is exposed under the /metrics endpoint, with the other metrics from kubernetes.
and yes, it is intended for a cluster admin, so that we could build global dashboards with grafana (getting data from prometheus), or setup prometheus alerting.

**Comment by mwringe** [comment]
The Prometheus endpoint is not something we handle with cluster metrics, so I have no opinion on this.

If we want something like this brought into our cluster metrics system, then it needs to go through cAdvisor/Heapster

**Comment by smarterclayton** [comment]
So for this metric specifically, it's already available from our API.  Keeping track of it in the controller doesn't seem to add much.

**Pull request closed without merging**
