### PR TITLE
Bug 1860832: Ensure Azure availability zone is always in lower cases

### PR DESCRIPTION
**Pull request by enxebre**
cherry-pick https://github.com/kubernetes/kubernetes/pull/89877

### CODE REVIEW

**Comment by eparis** [comment]
/approve
because joel indicated he needed someone to take a look

**Comment by ehashman** [comment]
@eparis can you or someone else approve the cherry-pick?

**Comment by eparis** [comment]
e2e-gcp-gather-extra, after the ci test, appears to fail, not the testin itself...

**Comment by eparis** [comment]
If the batch fails, i'll merge by hand in the morning.

**Pull request merged**
