### PR TITLE
require templateinstance delete, not update, on unbind

### PR DESCRIPTION
**Pull request by bparees**
bug 1554141

https://bugzilla.redhat.com/show_bug.cgi?id=1554141

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k @pmorie @jwforres @eparis potential workaround.  Checking for delete permission is probably "good enough" for what we're trying to accomplish here.

**Comment by bparees** [comment]
i've confirmed you can delete the project w/ existing provisions/binds with this change.

however @pmorie is investigating whether the ASB is also vulnerable to this problem.  In theory any broker which expects the unbind call to come from someone w/ more permissions than the namespace-controller has, can run into this.

**Comment by eparis** [comment]
Is there an intelligent way to check update, and only if the fails and if it is a delete to check for delete? Is switching to delete going to, possibly, break non-namespace controllers users?

**Comment by bparees** [comment]
On Mar 13, 2018 9:52 AM, "Eric Paris" <notifications@github.com> wrote:

Is there an intelligent way to check update, and only if the fails and if
it is a delete to check for delete? Is switching to delete going to,
possibly, break non-namespace controllers users?


It's possible to do(well not quite what you described but we could just Sar
check for update *or* delete permissions). But it's hard for me to imagine
a user who can provision to their namespace and bind, and has update
permissions, but does not have delete permissions, so it doesn't seem worth
taking into account to me?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/18948#issuecomment-372671915>,
or mute
the thread

**Comment by eparis** [comment]
extended conformance install looks like openshift-ansible problem
extended conformance gce looks wacky and no way realted to this.

**Pull request merged**
