### PR TITLE
Bug 1229555 - fix broken example in oc new-app

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
Why not the same example as in `oc help`?  Or is it?

**Comment by fabianofranz** [comment]
@smarterclayton good catch, I kept the NodeJS sample but let's be concise with `oc -h`. Fixed.

**Comment by fabianofranz** [comment]
[merge]

**Comment by smarterclayton** [comment]
I don't care which example we use in the end, just that they're the same.

**Comment by fabianofranz** [comment]
re[merge]

**Pull request merged**
