### PR TITLE
Kube 1.4 cherry picks

### PR DESCRIPTION
**Pull request by ncdc**
xref #11642

I've added a drop commit to fix the e2es panicking. We'll see how it goes.

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test] #10228

**Comment by soltysh** [comment]
That additional commit LGTM.

**Comment by smarterclayton** [comment]
[merge]

**Comment by timothysc** [comment]
It looks like we dropped the etcd3 perf changes...  so, I would pretty much never recommend to go clientv3 then.   

/cc @mffiedler

**Comment by ncdc** [comment]
@timothysc dropped as in they used to be there and we accidentally removed them, or we didn't get around to pulling them in?

**Comment by timothysc** [comment]
@ncdc there was a question on the original issue #11642 about whether to pull them in, so it looks like an oversight.

**Comment by ncdc** [comment]
@smarterclayton do you want upstream 35205 in?

**Comment by soltysh** [comment]
Both of the doubtful PRs are:
- 35205 - contains fixes to etcd3
- 33699 - moves informer to client

and I decided not to include them by default due to possible complications at this point in time. I'm leaving that decision to @smarterclayton about both of them.

**Comment by smarterclayton** [comment]
Pretty sure we need 35205 - is it a hard patch?

On Nov 2, 2016, at 3:50 PM, Maciej Szulik <notifications@github.com> wrote:

Both of the doubtful PRs are:

   - 35205 - contains fixes to etcd3
   - 33699 - moves informer to client

and I decided not to include them by default due to possible complications
at this point in time. I'm leaving that decision to @smarterclayton
<https://github.com/smarterclayton> about both of them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/11709#issuecomment-257978897>,
or mute
the thread

**Comment by soltysh** [comment]
Not sure if hard, but a big one. I'll give it a shot on my way to Brno.

**Pull request merged**
