### PR TITLE
remove deads2k from some of the more specific packages

### PR DESCRIPTION
**Pull request by deads2k**
Removing myself from some of the more specific packages that I'm not heavily involved in.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Pros:

we did it

Cons: 

we don't have the bots posting emojis on merges

/cc @kargakis @smarterclayton

**Comment by smarterclayton** [comment]
Let's pick a better emoji.  Can we do an explosion?  An elephant?

**Comment by stevekuznetsov** [comment]
You can do anything if you only believe

**Comment by fabianofranz** [comment]
> we don't have the bots posting emojis on merges

blocker issue, P0

**Comment by kargakis** [comment]
That's the heart plugin in prow if you want to enable it.

**Pull request merged**
