### PR TITLE
only set the build timestamps exactly once

### PR DESCRIPTION
**Pull request by bparees**
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1475557

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal
/test extended-builds

**Comment by bparees** [comment]
hm. need to rework how starttime is handled still.

**Comment by bparees** [comment]
@csrwng ok now it should be ready for review.

**Comment by csrwng** [comment]
@bparees so now we set the log snippet even if the build is not failed. Is that ok?

**Comment by bparees** [comment]
> @bparees so now we set the log snippet even if the build is not failed. Is that ok?

hm..  well we won't find a log snippet to set unless the pod failed, but i should probably make the check better.

**Comment by bparees** [comment]
@csrwng updated.

**Comment by bparees** [comment]
note that the idea here is to rely on update.IsEmpty() now.

**Comment by csrwng** [comment]
> note that the idea here is to rely on update.IsEmpty() now.

You should also check whether LogSnippet is empty before setting it.

**Comment by bparees** [comment]
>      You should also check whether LogSnippet is empty before setting it.

good catch. done.

**Comment by smarterclayton** [comment]
A follow up for a test that verifies builds only write once ina variety of scenarios would be appreciated.

**Comment by smarterclayton** [comment]
Link to release 3.6 pr here please.

**Comment by bparees** [comment]
incidentally our shouldIgnore check on handleBuild should already be keeping us out of a lot of this code (any build that's failed, with a timestamp, and with a logsnippet, will be ignored) so it's a bit of belt+suspenders.

**Comment by bparees** [comment]
lgtm re-added, only change was to the tests.

**Comment by bparees** [comment]
backport PR: https://github.com/openshift/origin/pull/15487

**Pull request merged**
