### PR TITLE
Allow for generic `rpmbuild` options and SRPM builds

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Publishing RPMs to official repositories often requires that specific
`rpmbuild` options are used that do not make sense to use by default. We
can simply expose a generic `$RPM_BUILD_OPTS` variable to allow users to
pass these in verbatim. Similarly, official publishing of these RPMs
will also require source RPM builds, which are very quick and we can do
by default.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by arilivigni** [comment]
[test]

**Comment by arilivigni** [comment]
@stevekuznetsov I made the changes to support the SRPM.  I can generate a

**Comment by arilivigni** [comment]
This PR has the changes needed
https://github.com/openshift/origin/pull/14038

**Pull request closed without merging**
