### PR TITLE
restructure run policy test and add logging

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/9533

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(using build configuration runPolicy)]

**Comment by bparees** [comment]
@mfojtik @gabemontero ptal.  i'm pretty sure there were systemic issues with the "counter" logic that was in place previously, given the possibility of receiving multiple events for a given build (all of which might have a phase of "running").  I think this flow is cleaner, it basically amounts to:

* expect a cancel event for build 2 at some point (strictly speaking this should happen after build 1 completes, but i'm willing to leave that untested..if it gets canceled, i'm happy).
* expect an event with phase running for build 1 followed by a run event for build 2 (and ignore any extra run events for any build)
 *ensure there are never 2 builds running at the same time.

**Comment by mfojtik** [comment]
@bparees 👍

**Comment by bparees** [comment]
@mfojtik doh. now i see why you had to wait for build 1 to be running before scheduling the other builds :)

**Comment by gabemontero** [comment]
Also, I can't seem to add an in-line comment since the line wasn't changed, but line 219 has 
`fmt.Printf("[%s] build %s is %s", build.Name, b.Name, b.Status.Phase)`
That debug is *NOT* going to show up in the extended test logs.  It needs to be `e2e.Logf` or `fmt.Fprintf(g.GinkgoWriter, ...)`

**Comment by bparees** [comment]
thanks @gabemontero, i've changed it to a logf.

**Comment by gabemontero** [comment]
oops ...need to remove the `fmt` import

**Comment by bparees** [comment]
one pass, see if we can get a few more.
[testextended][extended:core(using build configuration runPolicy)]

**Comment by bparees** [comment]
2/2
[testextended][extended:core(using build configuration runPolicy)]

@gabemontero @mfojtik any other comments?

**Comment by gabemontero** [comment]
nope igtm

**Comment by bparees** [comment]
[merge]

**Pull request merged**
