### PR TITLE
blacklist the ThirdPartyResource kind from other resources page

### PR DESCRIPTION
**Pull request by jwforres**
also clears any alerts when switching between different kinds because it seemed weird that they persisted

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

fyi the "ThirdPartyResource" kind is how a cluster admin enables a third party resource, if there are actual third party resources those show up as their own kinds, only cluster admins can list ThirdPartyResource.  It actually shouldn't even be listed as a cluster scoped resource, upstream issue that needs to be resolved.

**Comment by spadgett** [comment]
LGTM

**Comment by liggitt** [comment]
ThirdPartyResource *really* should not be a namespaced resource... there's an open issue to make them cluster-scoped.

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
