### PR TITLE
sdn: metrics fixes for review comments

### PR DESCRIPTION
**Pull request by dcbw**
Fixes: https://github.com/openshift/origin/pull/16518

Fixes for comments on the code that happened after it merged.

@smarterclayton @danwinship @eparis @knobunc

### CODE REVIEW

**Comment by smarterclayton** [comment]
Does this also fix #16629?

**Comment by smarterclayton** [comment]
Changes look fine

**Comment by imcsk8** [comment]
LGTM

**Comment by danwinship** [comment]
/hold
because it doesn't fix #16629 and it should

**Comment by dcbw** [comment]
@danwinship @smarterclayton updated to fix https://github.com/openshift/origin/issues/16629

**Pull request merged**
