### PR TITLE
Shim build config to oc adm drain

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1525340

@deads2k @smarterclayton if this is reasonable, I will open the upstream PR.

### CODE REVIEW

**Comment by soltysh** [comment]
Just make sure to open the upstream PR and replace those 0's in the commit title 😉

**Comment by deads2k** [comment]
I think that @juanvallejo has a good explanation of the general challenge here: https://github.com/kubernetes/kubernetes/pull/56864.  In the general case, adding a factory method doesn't help.

**Comment by deads2k** [comment]
/hold

I think we should take https://github.com/kubernetes/kubernetes/pull/56864 instead.

**Comment by mfojtik** [comment]
@deads2k agree, mea culpa that I was not looking for open PR's

**Pull request closed without merging**
