### PR TITLE
OCPBUGS-23102: Revert "[sig-instrumentation] tests fail due to JSON parsing error."

### PR DESCRIPTION
**Pull request by simonpasquier**
Reverts openshift/origin#28320

### CODE REVIEW

**Comment by stbenjam** [comment]
/retitle OCPBUGS-23102: Revert "[sig-instrumentation] tests fail due to JSON parsing error."

**Comment by raptorsun** [comment]
A fixed version of the reverted PR is ready https://github.com/openshift/origin/pull/28390

**Pull request merged**
