### PR TITLE
Ability to upload templates

### PR DESCRIPTION
**Pull request by gruiz17**
* add upload button directive for uploading any resource
* add ability to upload templates from UI
* add uploading to the data service

### CODE REVIEW

**Comment by liggitt** [comment]
@jwforres @jcantrill what happened to the upload directive we had for the route cert/key stuff. That seemed like a lightweight way to do file upload. Does the directive in this PR cleanly separate the mechanism of getting the file's content from the process of using it (to upload API content, use the content as a route cert, etc)? Also, does it support non-fileapi browsers? The other mechanism we had would fall back to a textarea you could paste content into

**Comment by jcantrill** [comment]
@liggitt Its checked in but not viewed in the console because we nixed that particular functionality when there was issues understanding what to do with multiple services; but the code is here: https://github.com/openshift/origin/blob/master/assets/app/scripts/directives/oscRouting.js

**Comment by jcantrill** [comment]
@liggitt actually the routing directive references https://github.com/openshift/origin/blob/master/assets/app/views/directives/osc-file-input.html

**Comment by gruiz17** [comment]
@liggitt So the way I have this implemented right now, the directive doesn't actually do much other than exist as a button to call a method to upload a file, and flash an alert if it fails to upload.

The actual uploading is taken care of in a new method on DataService, called `createFromUpload`. It basically takes the data via ng-file-upload's `Upload.http` method (which takes the JSON file's content directly) and POSTs it to `/oapi/v1/namespaces/{namespaces}/templates`, as per what the [OpenShift Docs](https://docs.openshift.org/latest/rest_api/openshift_v1.html) say on creating a template.

I chose to put a new method on the data service in order to use `_getNamespace` and `_urlForResource`.

As for browser compatibility, the [ng-file-upload](https://github.com/danialfarid/ng-file-upload) module only uses (flash) FileAPI to upload if the browser does not support HTML5 FormData, via including `ng-file-upload-shim`

**Comment by liggitt** [comment]
Yeah, we're not going to do a flash only solution. I'd use the existing file input directive we already had

**Comment by liggitt** [comment]
Is there a reason to upload the template just to use the "new from template" wizard? That could operate on a template content directly without even uploading it

**Comment by gruiz17** [comment]
@liggitt from what i understand, ng-file-upload is not a Flash-only solution. Rather, it only defaults to flash when the browser can't use HTML5 uploading (as in, when the user's on IE8/IE9 etc). Correct me if I'm wrong, though.

And the reason for uploading I suppose would be to already have all the services, images, etc. available already, with the only input needed being the necessary environment variables.

**Comment by liggitt** [comment]
Not sure what you mean. Uploading a template doesn't create anything. All it does is store the template content for the wizard to use. Uploading only has value if you expect the template to be reused in the system multiple times.

**Comment by liggitt** [comment]
Ah, misunderstood the flash comment. I'll defer to @jwforres on the file upload question, though if I recall, that module was pretty big for what we actually used

**Comment by jwforres** [comment]
For the question of what file upload directive to use, I would prefer the ng-file-upload so that we aren't maintaining our own.

@gruiz17 based on the code you have written so far, it seems like what you are trying to accomplish is to use your own template to immediately create content in your project.  That is actually a different trello card https://trello.com/c/fonu3qc5   The goal of the card you have in progress is actually to create a Template resource in the project so that it will be added to the catalog on the Create page so that it will be available to all the members of your project to create from multiple times.  It sounds like we need to switch cards?

If  you are just trying to immediately create content from an uploaded template, then the UX should be upload the template file's content into the UI, and then it takes you to the createFromTemplate page so the user can fill out labels, env vars, etc.

**Comment by jwforres** [comment]
@gruiz17 bump, see previous comment

**Comment by gruiz17** [comment]
@jwforres ohhh, right, i see

okay, let's switch cards

(again, sorry about being MIA)

**Comment by gruiz17** [comment]
@jwforres i've created a new pr! https://github.com/openshift/origin/pull/4861

**Pull request closed without merging**
