### PR TITLE
change argument --wildcardpolicy to --wildcard-policy in 'oc expose'

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
To keep 'oc create route' and 'oc expose' consistant change the
--wildcardpolicy flag to --wildcard-policy in 'oc expose'

Bug 1391786 [Link](https://bugzilla.redhat.com/show_bug.cgi?id=1391786)

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@knobunc @openshift/cli-review

**Comment by knobunc** [comment]
[test]

**Comment by juanvallejo** [comment]
Thanks for this, lgtm as well from a cli perspective

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
[test]

**Pull request merged**
