### PR TITLE
publish master to origin-4.5-kubernetes-1.17.1

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

I need to make sure that https://github.com/openshift/origin/pull/24572 actually works

**Comment by sttts** [comment]
cc @marun

**Comment by p0lyn0mial** [comment]
I think that I need to switch `origin` to a new branch first

**Comment by p0lyn0mial** [comment]
/hold cancel

I asked Stefan and there's no need to move the new commits. The publishing bot will add them.

**Pull request merged**
