### PR TITLE
Use image id instead of docker spec in imagechange controller

### PR DESCRIPTION
**Pull request by csrwng**
Fixes bug 1247116

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @ncdc ptal

**Comment by ncdc** [comment]
I discussed this at length with @smarterclayton a long time ago. We decided that triggering off of a change in the pull spec was the appropriate methodology. Please don't merge without getting Clayton's opinion, and both builds and deployments should be using identical logic.

**Comment by bparees** [comment]
the current behavior is breaking expectations here:
https://bugzilla.redhat.com/show_bug.cgi?id=1247116

@sdodson fyi this is the bug/PR i mentioned on your way out.

**Comment by bparees** [comment]
@ncdc if i'm building off mybuilder:latest why would i want to get rebuilt each time a new image was pushed to latest?

**Comment by smarterclayton** [comment]
Don't use latest?  Reading...

On Jul 27, 2015, at 6:50 PM, Ben Parees <notifications@github.com> wrote:

@ncdc <https://github.com/ncdc> if i'm building off mybuilder:latest why
would i want to get rebuilt each time a new image was pushed to latest?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3923#issuecomment-125372572>.

**Comment by bparees** [comment]
1) s/would/wouldn't/ above.
2) "if i am building off ruby:2.0, why wouldn't i want to get rebuilt when a new version of the ruby:2.0 image gets pushed for a security fix?"

**Comment by ncdc** [comment]
I understand the bz, and I understand the behavior you want, but it's not as simple as changing the logic to key off of image id. Not all entries you get back from `imageapi.LatestTaggedImage` will have an image id. You can run `oc tag` and get an entry in an image stream's status.tags that only has a pull spec (because it's a pure DockerImageReference that didn't come from an import or a push).

We probably need to discuss this in some more detail to come up with a comprehensive solution.

**Comment by ncdc** [comment]
For images coming from the integrated registry, the pull spec will always be a digest reference / pull by id. The possibility of not having an image id is an issue for external registries and images.

**Comment by smarterclayton** [comment]
Because you're using an external registry, there is no way to force a new image to be pulled to the node.  So this change doesn't actually fix the problem unless the deployment and build also "pull always".  Since we don't support proxy or redirection of images (so that we could offer a virtual tag), there is no way to guarantee the behavior we want to happen for deployment (that you can roll forward and back).

If the behavior of build is pull always you might get away with this.  However, changing the value you write here will force a rebuild of anything that is image change triggered in the platform, which I don't know that you want.

**Comment by smarterclayton** [comment]
The real fix would be to support virtual tags such that a docker pull of the image does the right thing.

**Comment by smarterclayton** [comment]
Actually the real fix is to drop support for old registries.

**Comment by smarterclayton** [comment]
Crap, we need a card for that...

**Comment by sdodson** [comment]
so this is probably not a regression then?

**Comment by sdodson** [comment]
And we'd need to push for registry.access.redhat.com to support v2 api.

**Comment by ncdc** [comment]
It's not a regression

**Comment by smarterclayton** [comment]
Although, if you look at deployment, I bet we actually do trigger a
redeployment on this because we check both id and tag, we just only store
the tag.

On Tue, Jul 28, 2015 at 9:01 AM, Cesar Wong <notifications@github.com>
wrote:

> Closed #3923 <https://github.com/openshift/origin/pull/3923>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3923#event-367193434>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request closed without merging**
