### PR TITLE
use valid commit for binary build test

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/9525

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(starting a build using CLI)]

**Comment by bparees** [comment]
@gabemontero ptal, the test in question passed, the remaining failure is the one to be addressed by @jupierce's logging changes.

**Comment by gabemontero** [comment]
lgtm

**Comment by gabemontero** [comment]
was the old commit just wrong, or did it become too old or something?

**Comment by bparees** [comment]
> was the old commit just wrong, or did it become too old or something?

I didn't really dig into it, but i suspect it has to do with this warning in the test:

 			// NOTE: This actually takes the commit from the origin repository. If the
 			// test-build-app changes, this commit has to be bumped.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9549

**Comment by bparees** [comment]
[test]

**Pull request merged**
