### PR TITLE
Delegated auth for router metrics allows anonymous

### PR DESCRIPTION
**Pull request by smarterclayton**
Because we are using delegated auth, the server can allow anonymous
access, and so we can receive either a 401 or 403. Test for both.

@rajatchopra even for anonymous users we ask the master if the user has permission, so forbidden is correct now when this mode is on (admin could choose to grant that permission if they wanted).

### CODE REVIEW

**Comment by smarterclayton** [comment]
/retest
Flakes, it looks like.  install test went green.

**Comment by gabemontero** [comment]
@smarterclayton should the tests under `test/extended/prometheus` be updated as well ?

**Comment by smarterclayton** [comment]
If you want to open a follow up, this is blocking the queue.

**Comment by smarterclayton** [comment]
Going to direct merge since there are other things in the queue and this is piling up.

**Pull request merged**
