### PR TITLE
UPSTREAM: <carry>: kubelet: change image-gc-high-threshold below docker dm.min_free_space

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/40432

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1408309

@derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by sjenning** [comment]
I think it flaked deploying the env

```
error: replication controller "docker-registry-1" has failed progressing
```

try to [merge] again

**Comment by derekwaynecarr** [comment]
re [merge]

**Pull request merged**
