### PR TITLE
DO NOT MERGE - Bump log level to 5 for debug

### PR DESCRIPTION
**Pull request by smarterclayton**
@ncdc this should help reproduce

[test]

### CODE REVIEW

**Comment by ncdc** [comment]
@stevekuznetsov said we could look into getting rid of the 20M cap now that artifacts are in s3

**Comment by stevekuznetsov** [comment]
Might want to leave *some* cap to stop hot-loops from eating up 10GB /cc @danmcp

**Comment by ncdc** [comment]
Sure, but presumably we can go way higher than 20MB?

**Comment by stevekuznetsov** [comment]
It is on my list to get a good profile of usage so we can determine average long length, etc, at which point we can make the truncation at the 99th percentile or whatever. Now that we fixed that god-damn `ListMeta` nag line we should have decreased our logfile length by a significant amount ...

**Comment by stevekuznetsov** [comment]
If you want to muck with the limit, the logic is here: https://github.com/openshift/origin/blob/master/hack/util.sh#L528-L539

**Comment by smarterclayton** [comment]
I really hope this fails.  I don't want to waste the good run on this PR.

**Pull request closed without merging**
