### PR TITLE
Revert "Added Git logging to build output"

### PR DESCRIPTION
**Pull request by oatmealraisin**
This reverts commit 2da96c65aefc6ee33c422e6cdcb16eb5c35848e5.

### CODE REVIEW

**Comment by oatmealraisin** [comment]
[testextended][extended:core(builds)]

**Comment by PI-Victor** [comment]
@oatmealraisin after looking int it i don't think that the tests failed because of your PR. this might not be necessary

**Comment by oatmealraisin** [comment]
@PI-Victor I'm still going to let it run to completely absolve myself ;)  Thank you for looking into this!

**Comment by oatmealraisin** [comment]
@bparees @PI-Victor The same tests are failing, closing this pull

**Comment by bparees** [comment]
@oatmealraisin yeah the issue is here: https://github.com/openshift/origin/pull/10540

**Pull request closed without merging**
