### PR TITLE
Fix SA OAuth test flake

### PR DESCRIPTION
**Pull request by liggitt**
Change poll to retry on conflict, refetch each time in order to actually retry with new data

fixes https://github.com/openshift/origin/issues/8701#issuecomment-232556736

### CODE REVIEW

**Comment by liggitt** [comment]
related to flake noted in https://github.com/openshift/origin/issues/8701#issuecomment-232555312

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@bparees PTAL

**Comment by smarterclayton** [comment]
LGTM

**Comment by bparees** [comment]
lgtm too :)

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
