### PR TITLE
only skip setting app label if the existing app label uses a different value

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal
@jwforres fyi

**Comment by bparees** [comment]
[test]

**Comment by csrwng** [comment]
@bparees is this to be consistent with the web UI? ... I thought in the previous pull you explicitly decided not to set an app label if one exists, regardless of its value

**Comment by bparees** [comment]
>  I thought in the previous pull you explicitly decided not to set an app label if one exists, regardless of its value

you have a better memory than me.  do you also remember why i thought that was the right thing to do? :)

it was triggered by a discussion w/ @jwforres and while I was looking at the code it seemed like there was no good reason not to do it this way.

**Comment by jwforres** [comment]
i'm ok either way, but honestly its probably easier for us to explain to people that if anything in there has an app label that we won't add one for them?

**Comment by bparees** [comment]
> i'm ok either way, but honestly its probably easier for us to explain to people that if anything in there has an app label that we won't add one for them?

maybe. i can go either way too.  this approach has the nicety of asserting consistency across the app labels if someone accidentally left it off one of the objects (Again, assuming the value they did set matches what we want to set).  

but i'm happy to close this too if we want.

**Comment by csrwng** [comment]
Sorry, had a meeting ... so here's the previous discussion:
https://github.com/openshift/origin/pull/10789#discussion_r80252967

**Comment by jwforres** [comment]
yeah we were having the exact same argument there :)  i say close this and i'll tweak my changes to not do the comparison

**Comment by bparees** [comment]
@csrwng ok, i'm going to trust our former selves and close this.  thanks for pulling up the history.

**Pull request closed without merging**
