### PR TITLE
Rebase STI to pickup .sti/environment support

### PR DESCRIPTION
**Pull request by mfojtik**
This rebase brings the support for `.sti/environment` file to Origin (see: https://github.com/openshift/source-to-image/pull/145) (Trello#499)

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@soltysh PTAL

**Comment by soltysh** [comment]
LGTM

**Comment by mfojtik** [comment]
[test] again

**Comment by mfojtik** [comment]
[test]

**Comment by soltysh** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge] again?

**Comment by mfojtik** [comment]
@smarterclayton @bparees it seems like there is some race condition in intergration test in Jenkins:

```
--- FAIL: TestSimpleImageChangeBuildTrigger (0.13 seconds)
	deploy_trigger_test.go:317: Starting test openshift
	imagechange_buildtrigger_test.go:69: Expected build with base image registry:8080/openshift/test-image:ref-2, got registry:8080/openshift/test-image:ref-1
```

If I run integration tests manually, then I don't get this error. @smarterclayton @soltysh said you were modifying the test run to run in separate processes, could this be related to that?

**Comment by soltysh** [comment]
From my observations on this we're using `test-image-repo` name in two separate tests [imagechange_buildtrigger_test.go](https://github.com/openshift/origin/blob/master/test/integration/imagechange_buildtrigger_test.go#L26) and [deploy_trigger_test.go](https://github.com/openshift/origin/blob/master/test/integration/deploy_trigger_test.go#L101) and this might be the root cause for this problem. I'd suggest renaming it in one of those files.

**Comment by smarterclayton** [comment]
They're sequentially run, so the only race possible is within the test

**Pull request merged**
