### PR TITLE
Split up SDN master/node/proxy/CNI code

### PR DESCRIPTION
**Pull request by danwinship**
Right now `pkg/sdn/plugin` is a mix of code that runs on the master and code that runs on nodes. This splits things up. I think it makes sense? @openshift/networking what do you think?

This gets rid of the `pkg/sdn/plugin` directory completely; node-specific code is now in `pkg/sdn/node` because it doesn't actually use the network plugin API at all any more.

### CODE REVIEW

**Comment by rajatchopra** [comment]
Looks clean to me. Squash the commits maybe.

**Comment by danwinship** [comment]
/test extended_conformance_gce
flake #15801

**Comment by imcsk8** [comment]
LGTM

**Comment by knobunc** [comment]
I will say the right incantation on Monday to allow it to merge :-)

**Comment by danwinship** [comment]
flake #15969 
/retest

**Comment by smarterclayton** [comment]
/approve

On Aug 29, 2017, at 12:57 PM, OpenShift Merge Robot <
notifications@github.com> wrote:

[APPROVALNOTIFIER] This PR is *NOT APPROVED*

This pull-request has been approved by: *danwinship
<https://github.com/openshift/origin/pull/15781#>*, *knobunc
<https://github.com/openshift/origin/pull/15781#issuecomment-325726406>*,
*pravisankar
<https://github.com/openshift/origin/pull/15781#issuecomment-325727423>*
We suggest the following additional approver: *smarterclayton*

Assign the PR to them by writing /assign @smarterclayton in a comment when
ready.

The full list of commands accepted by this bot can be found here
<https://github.com/kubernetes/test-infra/blob/master/commands.md>.
Needs approval from an approver in each of these OWNERS Files:

   - *hack/lib/OWNERS
   <https://github.com/openshift/origin/blob/master/hack/lib/OWNERS>*
   - *pkg/cmd/OWNERS
   <https://github.com/openshift/origin/blob/master/pkg/cmd/OWNERS>*
   - pkg/sdn/OWNERS
   <https://github.com/openshift/origin/blob/master/pkg/sdn/OWNERS>
   [danwinship,knobunc,pravisankar]

You can indicate your approval by writing /approve in a comment
You can cancel your approval by writing /approve cancel in a comment

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/15781#issuecomment-325727461>,
or mute
the thread

**Pull request merged**
