### PR TITLE
update secret commands to give usage errors

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/3109

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/2497/ `ERROR: gave up waiting for http://172.30.101.179:5000/healthz`

re[merge]

**Comment by deads2k** [comment]
`ERROR: gave up waiting for http://172.30.101.240:5000/healthz`

re[merge]

**Comment by deads2k** [comment]
feeling lucky?  re[merge]

**Pull request merged**
