### PR TITLE
make each SA client QPS/Burst proportional to the old limit

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Add a comment and make it "> 0" then lgtm

**Comment by deads2k** [comment]
> Add a comment and make it "> 0" then lgtm

Will updated, but I think negative qps people get what they deserve.  Not like its more broken for them.

**Comment by deads2k** [comment]
@smarterclayton I've tagged this one.  I'll leave the picks up to you.

**Comment by deads2k** [comment]
> @smarterclayton I've tagged this one. I'll leave the picks up to you.

see https://github.com/openshift/origin/pull/15479 and https://github.com/openshift/ose/pull/812

**Pull request merged**
