### PR TITLE
Update hack/verify-gofmt.sh for go1.5

### PR DESCRIPTION
**Pull request by dcbw**

### CODE REVIEW

**Comment by dcbw** [comment]
@liggitt

**Comment by mfojtik** [comment]
@stevekuznetsov do you remember if there was a specific reason why we don't have gofmt enabled for go 1.5 ?

**Comment by stevekuznetsov** [comment]
Yes, I tried updating it and it didn't seem to pick anything up. You could try enabling `shadow` checks, and unless you see a whole host of issues, that needs to be diagnosed before we upgrade. I have a PR in flight doing that.

**Comment by liggitt** [comment]
govet or gofmt?

**Comment by stevekuznetsov** [comment]
Sorry, misread the title. The reason `gofmt` wasn't enabled was that both were done in the same pull which got stalled due to `go vet` failures. No reason not to enable this now.

**Comment by liggitt** [comment]
LGTM, [merge]

**Comment by stevekuznetsov** [comment]
flake: https://github.com/openshift/origin/issues/6259

**Comment by dcbw** [comment]
[test]

**Comment by dcbw** [comment]
[test]

**Comment by dcbw** [comment]
[test]

**Comment by dcbw** [comment]
@liggitt seems to need another [merge] now that the test flakes have been resolved

**Comment by dcbw** [comment]
[test]

**Comment by pravisankar** [comment]
re[merge]

**Pull request merged**
