### PR TITLE
Final SDN cleanup

### PR DESCRIPTION
**Pull request by danwinship**
Origin is currently vendoring openshift/sdn only so that it can (1) build an `openshift-controller-manager` subcommand that hasn't been used since 3.11, (2) build an image that no one is building from this repo any more, (3) test that `openshift-sdn --help` prints the expected output.

Obsoletes #23407 

/assign @deads2k @tnozicka

### CODE REVIEW

**Comment by deads2k** [comment]
yeeehaw

/lgtm

**Comment by deads2k** [comment]
@danwinship rebase?

**Comment by danwinship** [comment]
@deads2k despite the red X this seems ready to go except for needing a new "lgtm" after I rebased it

**Comment by deads2k** [comment]
/hold

want to see if https://github.com/openshift/origin/pull/23475 (which includes this), gets the instant merge.

**Comment by deads2k** [comment]
cluster set up 

/retest

**Pull request merged**
