### PR TITLE
OCPBUGS-3819: Add bond cni test

### PR DESCRIPTION
**Pull request by mmirecki**
Adding a test case for the bond-cni.
The test checks if a pod with a bond is created successfully, and then checks connectivity between two pods with bond interfaces.

### CODE REVIEW

**Comment by mmirecki** [comment]
/cc @knobunc
Could you please take a look

**Comment by mmirecki** [comment]
@knobunc @deads2k @dcbw @danwinship @smarterclayton @bparees @mfojtik 
Can you please take a look at this?

**Comment by mmirecki** [comment]
@dgoodwin @akram @coreydaley @dmage @gangwgr @jadhaj @jitendar-singh
Could you please apply the  backport-risk-assessed, cherry-pick-approved labels?
Thanks

**Comment by mmirecki** [comment]
@kasturinarra @pamoedom @prietyc123 @stbenjam 
Can you please apply the backport-risk-assessed  label?
Thanks

**Comment by pamoedom** [comment]
Hi @mmirecki, please note that from the persons you pinged above, only @stbenjam has credentials to add `backport-risk-assessed` label. You can check [here](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/origin/_pluginconfig.yaml) the whole list for both labels if needed.

Regards.

**Comment by bparees** [comment]
i'll apply it manually.  Given this is affecting tests and not production code, the risk is low (the only real risk is that it opens a hole for a regression to be introduced elsewhere, and since it's adding tests, not changing them, that risk is also low)

**Pull request merged**
