### PR TITLE
bump(*): pick cadvisor fix

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/openshift/google-cadvisor/pull/4

`make update-deps` came in with some other changes too :disappointed:

google#2004
xref https://bugzilla.redhat.com/show_bug.cgi?id=1691023

@soltysh @deads2k @sttts @derekwaynecarr

### CODE REVIEW

**Comment by sjenning** [comment]
Review needed for non-cadvisor related change brought in the bump

@deads2k for https://github.com/openshift/containers-image/pull/1
- package: github.com/containers/image
  repo:    https://github.com/openshift/containers-image.git
  version: openshift-3.8

@mrunalp @nalind for https://github.com/openshift/moby-moby/pull/1
- package: github.com/docker/docker
  repo:    https://github.com/openshift/moby-moby.git
  version: openshift-3.10-docker-b68221c

@smarterclayton for https://github.com/openshift/imagebuilder/pull/123
- package: github.com/openshift/imagebuilder
  version: openshift-3.11

I have no idea how there are changes for a `version` that is a commit id :disappointed: 
- package: github.com/vmware/photon-controller-go-sdk
  version: 4a435daef6ccd3d0edaac1161e76f51a70c2589a

**Comment by smarterclayton** [comment]
imagebuilder#123 is fine

**Comment by mrunalp** [comment]
docker changes look fine

**Comment by sjenning** [comment]
The photon changes are just gofmt changes toggling [back](https://github.com/openshift/origin/commit/811166a4cada6b9234bea0b01c073887ade4897a#diff-e35c5edc171f1308f2e5021542f2e099) and [forth](https://github.com/openshift/origin/commit/b4ac13b2ee2e7c4178fe3dde7453fef182edc3fa#diff-e35c5edc171f1308f2e5021542f2e099) and [back](https://github.com/openshift/origin/commit/ad6022688e2317839fd56a61f4490831a634a9a9#diff-e35c5edc171f1308f2e5021542f2e099) again :disappointed:

**Comment by deads2k** [comment]
@sjenning mine is fine and sorry about that.

/lgtm

**Comment by sjenning** [comment]
rebasing to get fix from https://github.com/openshift/origin/pull/22379

**Comment by sjenning** [comment]
readding lgtm since nothing changed

**Pull request merged**
