### PR TITLE
UPSTREAM: 12488: use package from out value

### PR DESCRIPTION
**Pull request by pweil-**
Reference: https://github.com/GoogleCloudPlatform/kubernetes/pull/9971/files#diff-a04b3a7a947b2fc4e8a132fe9bf04569L155

@smarterclayton @liggitt 

Fixes https://github.com/openshift/origin/issues/4087

### CODE REVIEW

**Comment by liggitt** [comment]
Did it change any generated files?

**Comment by pweil-** [comment]
no, I ran the generate script upstream and in Origin and had no diffs

**Comment by liggitt** [comment]
LGTM, [merge]

**Comment by pweil-** [comment]
rebased but this is already upstream and is in @deads2k 's rebase pr

**Comment by liggitt** [comment]
Go ahead and close then

**Pull request closed without merging**
