### PR TITLE
make templateinstance immutability message less unfriendly

### PR DESCRIPTION
**Pull request by jim-minter**
bug 1457613

### CODE REVIEW

**Comment by bparees** [comment]
doesn't require any test updates?

**Comment by jim-minter** [comment]
it didn't - no - but: updated.

**Comment by bparees** [comment]
thanks.
[merge]

**Comment by jim-minter** [comment]
flake #12072 @bparees please can you hit merge again?

**Comment by bparees** [comment]
@jim-minter still in the queue

**Pull request merged**
