### PR TITLE
re-enable cgroups for builds, but set a lower maximum value for the "default(no limit)" behavior.

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/8201

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @mrunalp ptal
[test]

**Comment by mrunalp** [comment]
:+1:

**Comment by bparees** [comment]
@mrunalp i'm going to let this sit for the moment pending what you learn from the kernel team, but we can merge it if needed.

**Comment by mrunalp** [comment]
@bparees Sounds good. I have emailed them. I will let you know once they get back.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
I'm going to merge this and we can iterate on the optimal / correct since this isn't flaking.  [merge]

**Comment by mrunalp** [comment]
This is what Larry Woodman from the kernel team has to say. I think your fix is a good workaround. Or we could even change it to the value that we get for total memory from `free -m`.
> the values written to both mem.limit_in_bytes and memsw.limit_in_bytes are rounded up to the next whole page size(4096 on x86_64) so if mem.limit_in_bytes+4095|4096 is greater than mem.memsw.limit_in_bytes+4095|4096 the write will fail regardless of the size you are trying to write
...
> Thats right, 9223372036854775807(dec) is 0x7FFFFFFFFFFFFFFF(hex) which is the maximum 64-bit signed number(unlimited).  This overflows when the +4095|4096 described above is applied with the echo so it fails.

**Comment by bparees** [comment]
ok cool, thanks @mrunalp.  will close the issue.

**Pull request merged**
