### PR TITLE
Update default hostnames in cert

### LINKED ISSUE #3279: Kubernetes master cert uses old DNS names
See https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/master_args.go#L484

Still has "openshift.default.local", "kubernetes.default.local", "kubernetes-ro.default.local" rather than new DNS names "kubernetes.default.svc.cluster.local", etc.

Have to turn off hostname verification for any SSL comms inside the cluster which is not good.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3279

Update to correct hostname for services

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton merge

**Comment by liggitt** [comment]
See also https://github.com/detiber/openshift-ansible/pull/48

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[test] again

**Pull request merged**
