### PR TITLE
add cifs-utils to origin rpm

### LINKED ISSUE #18236: need cifs-utils in origin package
Running origin node on Azure needs cifs-utils package to mount Azure file (i.e. SMB), as documented [here](https://github.com/kubernetes/examples/blob/master/staging/volumes/azure_file/README.md)

##### Version
1.8

### PR DESCRIPTION
**Pull request by rootfs**
fix #18236 and BZ 1536362

cifs-utils and dependency add 19MB 

@stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm
/hold

Holding for @smarterclayton or @sdodson to chime in

**Comment by sdodson** [comment]
@rootfs cifs-utils is not on atomic host. In a containerized installation cifs-utils may only be available inside the container. Will that work?

**Comment by rootfs** [comment]
@sdodson yes, that should work. The problem in the BZ happened in node container.

**Comment by sdodson** [comment]
@rootfs what about https://bugzilla.redhat.com/show_bug.cgi?id=1536362 is that same problem?

**Comment by sdodson** [comment]
Sorry, I meant https://bugzilla.redhat.com/show_bug.cgi?id=1537872

**Pull request merged**
