### PR TITLE
UPSTREAM: 30510: Endpoint controller logs errors during behavior

### PR DESCRIPTION
**Pull request by derekwaynecarr**
FIxes https://bugzilla.redhat.com/show_bug.cgi?id=1347425

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
/cc @ncdc @smarterclayton 

I was unable to use `hack/cherry-pick` to do this pick, it looks like @smarterclayton last bumped the Godeps, but I am unable to find the referenced revision.

```shell
[decarr@localhost origin (cherry-pick-30510)]$ UPSTREAM_REMOTE=upstream hack/cherry-pick.sh 30510
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
++ pr/30510 appears to have merged at f98de240614410b5c719bf4210a990c6835fcab5
++ Generating patch for 9fe15e7376a6ba8774fc3b584214d0eb841553c6..038c754b7fe8238e40aa8e5c15db9002e9d6254a onto 507d3a7 ...
fatal: Cannot update paths and switch to branch 'last_upstream_branch' at the same time.
Did you intend to checkout '507d3a7' which can not be resolved as commit?
[ERROR] PID 25481: hack/cherry-pick.sh:44: `git checkout -b last_upstream_branch "${lastrev}"` exited with status 128.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/cherry-pick.sh:44: `git checkout -b last_upstream_branch "${lastrev}"`
[INFO]   Exiting with code 128.
```

**Comment by smarterclayton** [comment]
Git fetch openshift?

On Aug 15, 2016, at 11:06 AM, Derek Carr <notifications@github.com> wrote:

/cc @ncdc <https://github.com/ncdc> @smarterclayton
<https://github.com/smarterclayton>

I was unable to use hack/cherry-pick to do this pick, it looks like
@smarterclayton <https://github.com/smarterclayton> last bumped the Godeps,
but I am unable to find the referenced revision.

[decarr@localhost origin (cherry-pick-30510)]$
UPSTREAM_REMOTE=upstream hack/cherry-pick.sh 30510
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
++ pr/30510 appears to have merged at f98de240614410b5c719bf4210a990c6835fcab5
++ Generating patch for
9fe15e7376a6ba8774fc3b584214d0eb841553c6..038c754b7fe8238e40aa8e5c15db9002e9d6254a
onto 507d3a7 ...
fatal: Cannot update paths and switch to branch 'last_upstream_branch'
at the same time.
Did you intend to checkout '507d3a7' which can not be resolved as commit?
[ERROR] PID 25481: hack/cherry-pick.sh:44: `git checkout -b
last_upstream_branch "${lastrev}"` exited with status 128.
[INFO]      Stack Trace:
[INFO]        1: hack/cherry-pick.sh:44: `git checkout -b
last_upstream_branch "${lastrev}"`
[INFO]   Exiting with code 128.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/10415#issuecomment-239826423>,
or mute
the thread

**Comment by ncdc** [comment]
[merge]

**Comment by derekwaynecarr** [comment]
@smarterclayton - i forgot `git fetch openshift`.  Ideally, cherry-pick should do that for me, no?

**Pull request merged**
