### PR TITLE
Sync catalog v0.1.0-rc1

### PR DESCRIPTION
**Pull request by jboyd01**
syncing Service Catalog v0.1.0rc1 to Origin

### CODE REVIEW

**Comment by spadgett** [comment]
@jboyd01 FYI, you'll probably also need to update 

https://github.com/openshift/origin/blob/master/install/service-catalog-broker-resources/template-service-broker-registration.yaml#L12-L13

for the name change.

**Comment by pmorie** [comment]
You'll need to change the API version in the apiservice resource which is hard-coded here:

https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/servicecatalog.go#L132

I think we ought to consider moving this into the template - it's not clear to me why this is embedded in the code.

**Pull request merged**
