### PR TITLE
UPSTREAM: 54597: kubelet: check for illegal container state transition

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @sjenning @smarterclayton @mfojtik 

Fixes: https://github.com/openshift/origin/issues/17487

### CODE REVIEW

**Comment by tnozicka** [comment]
disregard: submit queue ping

**Comment by tnozicka** [comment]
submit queue stuck...
/test all

**Comment by sjenning** [comment]
I see this change twice in the log for `release-3.8` and `master` now
```
$ git log --oneline origin/master | grep "check for illegal container"
21271eb483 UPSTREAM: 54597: kubelet: check for illegal container state transition
912426b0f5 UPSTREAM: 54597: kubelet: check for illegal container state transition
$ git log --oneline origin/release-3.8 | grep "check for illegal container"
21271eb483 UPSTREAM: 54597: kubelet: check for illegal container state transition
912426b0f5 UPSTREAM: 54597: kubelet: check for illegal container state transition
$ git log --oneline origin/release-3.7 | grep "check for illegal container"
912426b0f5 UPSTREAM: 54597: kubelet: check for illegal container state transition
```
Is it reverted somewhere in 3.8/master then reapplied by this PR? fyi @frobware

**Comment by sjenning** [comment]
```
$ git log --oneline origin/release-3.8 -- vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
21271eb483 UPSTREAM: 54597: kubelet: check for illegal container state transition
c4b40b3f40 bump(k8s.io/kubernetes): 0d5291cc63b7b3655b11bc15e8afb9a078049d09 - v1.8.1
912426b0f5 UPSTREAM: 54597: kubelet: check for illegal container state transition
```
Seems the bump to 1.8.1 reverted it.  I guess nothing to see here.  Weird workflow though.

**Pull request merged**
