### PR TITLE
[DO_NOT_MERGE] bump broker waitforready timeout

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/15405

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(templates)]

**Comment by bparees** [comment]
stop. this didn't fix anything.

**Comment by smarterclayton** [comment]
Definitely not detecting the issue

**Comment by bparees** [comment]
hm. it re-added the approved label? was it supposed to do that?

**Comment by jim-minter** [comment]
IMO this PR should definitely *not* be merged.

**Comment by bparees** [comment]
@jim-minter once it evolved beyond seeing if bumping the timeout to 30s would fix the issue, there were no plans to merge it.

**Pull request closed without merging**
