### PR TITLE
Remove flakiness in webhook test

### LINKED ISSUE #4245: Flake in TestWebhookGitHubPushWithImageStream test
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4235/console
Either a race in the test or in the actual API
```
--- FAIL: TestWebhookGitHubPushWithImageStream-2 (6.82s)
	webhookgithub_test.go:278: Wrong response code, expecting 200, got %!s(int=500): {
		  "kind": "Status",
		  "apiVersion": "v1",
		  "metadata": {},
		  "status": "Failure",
		  "message": "Internal error occurred: could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
		  "reason": "InternalError",
		  "details": {
		    "causes": [
		      {
		        "message": "could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again"
		      }
		    ]
		  },
		  "code": 500
		}!
FAIL
```

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #4245

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by liggitt** [comment]
I think we also need to fix the webhook to not return a 500 in that case… you should get a 429 Conflict. That should be added and tested (though that can be a separate PR)

**Comment by bparees** [comment]
I think you should remove the other imagechangetrigger too (in the otherbuildconfig definition)

**Comment by csrwng** [comment]
@bparees updated

**Comment by bparees** [comment]
[merge]

**Pull request merged**
