### PR TITLE
add no_proxy environment variables

### PR DESCRIPTION
**Pull request by guangxuli**
Add no_proxy environment variables for localhost if behind a proxy, if not, the connections to localhost in some scripts will time out.

### CODE REVIEW

**Comment by guangxuli** [comment]
@smarterclayton @stevekuznetsov PTAL,thanks.

**Comment by stevekuznetsov** [comment]
This seems like the sort of thing that end users should be setting in their environments (like `~/.bashrc`) and not something we should be touching in our scripts.

**Comment by guangxuli** [comment]
@stevekuznetsov thanks for you review. Yes, there are some ways to resolve this problem, but I think it is very convenient to users who don‘t need to consider to any network configuration .Otherwise, it will take a long time to fix some test errors.

**Comment by stevekuznetsov** [comment]
@smarterclayton what's your opinion on this one?

**Comment by liggitt** [comment]
no messing with no_proxy inside script files... we should strictly honor the existing environment

**Pull request closed without merging**
