### PR TITLE
add selinux go build tag on linux

### PR DESCRIPTION
**Pull request by rphillips**
With the 1.16 rebase we found the selinux build tag was found to be missing. We need this patch to enable proper labeling within the go-selinux package for 1.14 origin releases and prior.

ref: https://github.com/openshift/origin/blob/master/vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go#L1

/cc @sjenning @mrunalp @smarterclayton @derekwaynecarr @eparis @deads2k

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is there an selinux e2e test that would capture this?

**Comment by mrunalp** [comment]
@haircommander is looking into e2e test for this.

**Comment by smarterclayton** [comment]
Updates?  This is concerning for lots of reasons, why aren't be positive that this is doing the right thing when enabled?

**Comment by rphillips** [comment]
@haircommander is actively working on a test

**Comment by haircommander** [comment]
After a couple of days testing (with the help of @mrunalp and @rphillips) I have determined SELinux is working as expected (properly setting labels on processes and volumes) in 4.2. I don't know if we need this PR

**Comment by rphillips** [comment]
Sounds like we can close it. Thanks for verifying that @haircommander .

**Pull request closed without merging**
