### PR TITLE
UPSTREAM: 73739: Parallelize iSCSI tests

### PR DESCRIPTION
**Pull request by tsmetana**
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1711627

cc: @jsafrane @bertinatto @gnufied

### CODE REVIEW

**Comment by jsafrane** [comment]
I don't see any iscsi tests in e2e-aws logs, please enable them.

**Comment by jsafrane** [comment]
`Could not resolve host: mirrors.fedoraproject.org` ???

/retest

**Comment by tsmetana** [comment]
Two of the iSCSI tests failed again.
/hold

**Comment by tsmetana** [comment]
The error is weird: I added some debugging messages to the tests to get some clue what is going on.

**Comment by tsmetana** [comment]
This thing needs to wait until the iSCSI gets fixed properly: there were issues found at the kernel level. There's no way to run iSCSI tests reliably yet.

**Pull request closed without merging**
