### PR TITLE
Remove API initialization from dockerregistry

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by miminar** [comment]
@bparees There's no single green run of `
ci/openshift-jenkins/extended_conformance_crio` for any PR in a known history. I don't think we need to block this PR because of this test.

**Comment by dmage** [comment]
@miminar this PR doesn't have the kind/bug label, that's why it doesn't go to merge queue.

**Comment by bparees** [comment]
@dmage @legionus @miminar keep in mind that the registry effectively lives here now:
https://github.com/openshift/image-registry

So anything we merge into origin is going to have to get copied over to that repo  (once that repo is stable we can probably do a bulk merge).

**Comment by bparees** [comment]
(but it might be better to go ahead and cherry-pick changes as we go so we don't lose track of them or lose the history)

**Pull request merged**
