### PR TITLE
Remove a pointless cast

### PR DESCRIPTION
**Pull request by danwinship**
noticed by @eparis

### CODE REVIEW

**Comment by imcsk8** [comment]
Code looks ok LGTM

**Comment by danwinship** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
I want to prioritize https://github.com/openshift/origin/pull/13317 -- it is a bug fix -- removing merge tag for now.

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by eparis** [comment]
do things [merge] sometimes?

**Comment by stevekuznetsov** [comment]
@eparis what was the issue?

**Comment by eparis** [comment]
[test] flake was https://github.com/openshift/origin/issues/12661
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/136/

**Comment by eparis** [comment]
[merge] while I look up the flake

**Comment by eparis** [comment]
I reached out to clayton to see if he recognized it.  Because I don't...

**Pull request merged**
