### PR TITLE
Fix RWO warning with percentages

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik fixes the warning since the default case (25%-25%) is broken.

/assign mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
do we have test exercising this?

LGTM

**Comment by kargakis** [comment]
@mfojtik see the fixture change

[test]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
@stevekuznetsov @smarterclayton 15m to do a git clone of origin .... I am not using emptyDir though..

**Comment by stevekuznetsov** [comment]
@kargakis shouldn't the response here also tell you it's responding to your comment with the command?

**Pull request merged**
