### PR TITLE
Remove sti-image-builder from our build-images flow

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: #1683

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees @smarterclayton PTAL

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by bparees** [comment]
isn't this something we're going to want if/when we build our images in openshift?  would it be better to just remove it from build-images?

**Comment by mfojtik** [comment]
@bparees the image I'm removing here is 'weak' anyway and if we are going to build a builder based on OpenShift we will have to think about how to get the latest S2I release and how to promote the builder images anyway...

**Comment by bparees** [comment]
ok.

**Pull request merged**
