### PR TITLE
make images and sample templates components

### PR DESCRIPTION
**Pull request by deads2k**
Removes the `--image-streams` field, makes it a component, and the functionality now works with `oc cluster up --enable=*,-centos-imagestreams,rhel-imagestreams`, but it should be really rare that people use it.  We choose a good default based on compile values.

### CODE REVIEW

**Comment by deads2k** [comment]
@mfojtik combined with yours, is this all of them?

**Comment by mfojtik** [comment]
/lgtm

@deads2k i believe so, can't think of anything else that we can componetize.

**Pull request merged**
