### PR TITLE
Use assets/config.local.js if present for development config

### PR DESCRIPTION
**Pull request by spadgett**
Make it easier to modify options like metrics URL, logging URL, and API server hostname for web console development.

@jwforres @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Nice! Prob just need a short explanation in the `assets/README.md` file.

**Comment by jwforres** [comment]
Need to add a watch for it for when you change it after grunt's already running

**Comment by jwforres** [comment]
config.js was already supposed to be the development mode file, I'm assuming you just don't like that its tracked in Git and shows up as a diff?  but we cant take it out since tests rely on it being there.

**Comment by spadgett** [comment]
> Need to add a watch for it for when you change it after grunt's already running

Yeah, I have a watch.

**Comment by spadgett** [comment]
> config.js was already supposed to be the development mode file, I'm assuming you just don't like that its tracked in Git and shows up as a diff?

It's difficult to modify since it's a tracked file and easy to accidentally commit.

**Comment by jwforres** [comment]
Ok, im not opposed to the idea.

**Comment by spadgett** [comment]
Maybe this should be `assets/app/config.js`? That won't get put in bindata, will it?

**Comment by benjaminapetersen** [comment]
Yeah... makes sense that the files would be siblings:

- config.js
- config.local.js

**Comment by spadgett** [comment]
@jwforres Updated. Both files are now under the top-level assets folder. If config.local.js doesn't exist, config.js is used.

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
LGTM and its passed testes, @spadgett ready to merge it?

**Comment by spadgett** [comment]
@jwforres thanks, [merge]

**Comment by spadgett** [comment]
re[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
