### PR TITLE
Create template-service-broker subpackage and image

### PR DESCRIPTION
**Pull request by sdodson**
My intent is to create the image in this PR too but I'm having trouble getting origin built at all right now.

```
++ Building go targets for linux/amd64: images/pod cmd/dockerregistry cmd/gitserver vendor/k8s.io/kubernetes/cmd/hyperkube pkg/network/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback examples/hello-openshift
can't load package: package github.com/openshift/origin/pkg/network/sdn-cni-plugin: cannot find package "github.com/openshift/origin/pkg/network/sdn-cni-plugin" in any of:
        /usr/lib/golang/src/github.com/openshift/origin/pkg/network/sdn-cni-plugin (from $GOROOT)
        /home/rdu/sdodson/go/src/github.com/openshift/origin/pkg/network/sdn-cni-plugin (from $GOPATH)
[ERROR] PID 7568: hack/lib/build/binaries.sh:228: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 1.
[INFO]          Stack Trace: 
[INFO]            1: hack/lib/build/binaries.sh:228: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"`
[INFO]            2: hack/lib/build/binaries.sh:158: os::build::internal::build_binaries
[INFO]            3: hack/lib/build/binaries.sh:141: os::build::build_binaries
[INFO]            4: hack/build-cross.sh:75: os::build::build_static_binaries
[INFO]   Exiting with code 1.
[ERROR] PID 7462: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")` exited with status 1.
[INFO]          Stack Trace: 
[INFO]            1: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")`
[INFO]            2: hack/lib/build/binaries.sh:141: os::build::build_binaries
[INFO]            3: hack/build-cross.sh:75: os::build::build_static_binaries
[INFO]   Exiting with code 1.
error: Bad exit status from /var/tmp/rpm-tmp.uQabdB (%build)
```

### CODE REVIEW

**Comment by deads2k** [comment]
@sdodson looks to be building here

/retest

**Comment by sdodson** [comment]
@deads2k should be good to go, need to get process started on internal release management stuff.
/retest

**Comment by deads2k** [comment]
@sdodson @stevekuznetsov What's the next step to get the image to appear here: https://hub.docker.com/u/openshift/ ?

**Comment by sdodson** [comment]
@smarterclayton looks like we broke the push_origin_release job https://ci.openshift.redhat.com/jenkins/job/push_origin_release/1480/consoleFull#9597313135898c58db7602c31c0eab717 can you get that repo created in docker hub?

**Pull request merged**
