### PR TITLE
Template parameters broken in new-app

### LINKED ISSUE #8668: oc new-app with multiple parameters regression
I noticed this starting to happen today, if I have a template that i try to process and create using `oc new-app`

1) if there are no parameters to pass in, this works as expected
2) if there are multiple parameters, with different attempts of the same command (!!) I get different parameter names coming back as "unexpected"
I've experimented using multiple "-p" parameters and using a comma delimited list with single "-p"
I've also tried explicitly adding "--template=" before the template name

I can confirm the template is valid since `oc process {template} -v .... | oc create -f -` still works.

##### Version
openshift v1.3.0-alpha.0-169-g68d9241
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0

##### Steps To Reproduce
1. Have a template file that has multiple parameters to set:
```
https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/support.yaml
```
2. Run oc new-app with providing multiple parameters: 
```
oc new-app -f templates/support.yaml --param OAUTH_SECRET=HKS3jTwLQHdEOj0WrOlx1Z71xTYHQAlktcalH3m0tYwo4LOEsKoDcVs703Vr3W9S --param KIBANA_HOSTNAME=kibana.example.com --param KIBANA_OPS_HOSTNAME=kibana-ops.example.com --param IMAGE_PREFIX_DEFAULT=172.30.192.225:5000/logging/
```
##### Current Result
Different parameters are coming back as "unexpected parameter name"
`error: unexpected parameter name "OAUTH_SECRET"`

##### Expected Result
The template should be processed and the objects should be created

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #8668, condition was reversed.  Need to add a test

### CODE REVIEW

**Comment by smarterclayton** [comment]
@csrwng review

**Comment by smarterclayton** [comment]
[test]

**Comment by csrwng** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
