### PR TITLE
Bug 1753502: UPSTREAM: 82503: Reorder symlinks to prevent path escapes

### PR DESCRIPTION
**Pull request by sallyom**
/cc @soltysh

### CODE REVIEW

**Comment by sallyom** [comment]
need this: https://github.com/openshift/origin/pull/24143  and then backport to 3.10 b4 this will be green

**Comment by stevekuznetsov** [comment]
/hold

This has been re-tested so many times we've reached the limit of how many times we can report a failed message to GitHub. Please rebase.

**Pull request merged**
