### PR TITLE
This would make CI for 4.10 in vSphere environment wee bit happier

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2009823

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

Can you link to the HW13 and HW15 variants in CI for 4.10 in a pull comment before releasing the hold please.

/hold

**Comment by gnufied** [comment]
UPI installs which default to HW 13 - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-vsphere-upi/1443602998302347264

IPI installs which default to HW 15 - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-vsphere/1443823131947962368

**Comment by deads2k** [comment]
thanks

/hold cancel

**Pull request merged**
