### PR TITLE
Precompile Angular templates

### LINKED ISSUE #3611: Pre-build console templates into $templateCache to reduce ajax requests
There is an npm package called [grunt-angular-templates](https://www.npmjs.com/package/grunt-angular-templates) that will pre-compile templates into JavaScript functions that can be registered into Angular's $templateCache & reduce ajax requests while the app is running.  This could be a useful performance optimization.

### PR DESCRIPTION
**Pull request by spadgett**
Use `grunt-angular-templates` to precompile our Angular templates and add them to the `$templateCache` to reduce AJAX requests.

TODO:

- [x] Reenable minification

Fixes #3611 
See also #3790

### CODE REVIEW

**Comment by liggitt** [comment]
Precompiles to single javascript strings in bindata are going to drastically increase merge conflicts on template changes. Not sure that is a reason to avoid this, just noting it.

**Comment by danmcp** [comment]
@spadgett Bump

**Comment by spadgett** [comment]
Blocked by a bug in our version of `htmlmin` when using `preserveLineBreaks: true`. Unfortunately, the latest `grunt-contrib-htmlmin` doesn't have the fix.

**Comment by liggitt** [comment]
can you report it to grunt-contrib-htmlmin to drive an update?

**Comment by spadgett** [comment]
Opened https://github.com/gruntjs/grunt-contrib-htmlmin/issues/111

**Comment by spadgett** [comment]
I missed before that we were locking to html-minifier 0.7.0. grunt-contrib-htmlmin uses a fuzzy match, `^0.7.0`. Upgraded to 0.7.2, and everything works.

[test]

**Comment by spadgett** [comment]
fork_ami: https://ci.openshift.redhat.com/jenkins/job/fork_ami/67/

**Comment by spadgett** [comment]
Rebased.

**Comment by spadgett** [comment]
Rebased.

**Comment by jwforres** [comment]
LGTM, we can merge once we get QE sign off

**Comment by spadgett** [comment]
Accidental close.

**Comment by spadgett** [comment]
New fork ami: https://ci.openshift.redhat.com/jenkins/job/fork_ami/68/

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@sg00dwin @benjaminapetersen FYI, when this merges you will definitely need to rebase any open PRs you have and rebuild the assets

**Comment by spadgett** [comment]
> FYI, when this merges you will definitely need to rebase any open PRs you have and rebuild the assets

@sg00dwin @benjaminapetersen run a full clean / install / build assets.

**Pull request merged**
