### PR TITLE
Bump to kube 1.18.3

### PR DESCRIPTION
**Pull request by marun**
/cc @sttts @p0lyn0mial @mfojtik @soltysh

### CODE REVIEW

**Comment by marun** [comment]
Upgrade tests are green:

- (test upgrade 4.4 openshift/origin#25015)[https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/11743]
- (test upgrade 4.5 openshift/origin#25015)[https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/11742]
-  (test upgrade openshift/origin#25015 openshift/origin#25015)[https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/11748]

**Comment by marun** [comment]
gcp upgrade tests are currently blocked by a quota issue.

**Comment by mfojtik** [comment]
this does not need valid bug, we bumping the levels of kube to improve stability and get fixes from maintenance level of kube.

**Pull request merged**
