### PR TITLE
allow retry of 500 errors on image push

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/13955

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/devex ptal

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by coreydaley** [comment]
lgtm

**Comment by jim-minter** [comment]
Ick.  The whole RetriableErrors thing is pretty grotty.  In this case, the fsouza client should allow casting to a docker.Error and checking if .Status == 500.  Doing that would avoid making a future refactor of RetriableErrors harder.
Also note, this is a copy/paste from vendor/github.com/openshift/source-to-image/pkg/docker/docker.go.

**Comment by bparees** [comment]
in general i agree that checking error message text isn't a pattern we want to reinforce.

anyway @csrwng has suggested pushing back on the registry team that the registry should be retrying this (if the condition that lead to the 500 is retriable), so this PR is probably going to just get closed.

**Pull request closed without merging**
