### PR TITLE
UPSTREAM: 47904: prioritize messages for long steps

### PR DESCRIPTION
**Pull request by deads2k**
upstream pick for https://bugzilla.redhat.com/show_bug.cgi?id=1462446

already merged upstream [test]

### CODE REVIEW

**Comment by eparis** [comment]
Removed merge tag as this appears to be an older iteration of the upstream code.

**Comment by deads2k** [comment]
> Removed merge tag as this appears to be an older iteration of the upstream code.

Oh, `hack/cherry-pick.sh` you have failed me

**Comment by deads2k** [comment]
> Removed merge tag as this appears to be an older iteration of the upstream code.

fixed [merge]

**Comment by eparis** [comment]
wtf did it do?  Thank you.

**Comment by smarterclayton** [comment]
[test]

**Comment by eparis** [comment]
green test, deep queue, low risk, in your go!

**Pull request merged**
