### PR TITLE
Added volume plugins to match upstream

### LINKED ISSUE #2433: Pod can't consume a PVClaim - storage plugins not loaded?
I fixed up the docs on creating an example PV + PVC + pod:
https://github.com/openshift/openshift-docs/pull/395

... however something is still not quite working. When I created my pod, it sits in Pending forever and OpenShift has this message in the journal:

`I0522 03:05:47.267683    1654 event.go:203] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"whatever\", Name:\"mypod\", UID:\"46114970-002d-11e5-ae4e-22000ab3877e\", APIVersion:\"v1beta3\", ResourceVersion:\"14869\", FieldPath:\"\"}): reason: 'failedSync' Error syncing pod, skipping: can't use volume plugins for (volume.Spec){Name:(string)myvol VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaimVolumeSource:(*api.PersistentVolumeClaimVolumeSource){ClaimName:(string)claim1 ReadOnly:(bool)false}} PersistentVolumeSource:(api.PersistentVolumeSource){GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> HostPath:(*api.HostPathVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil>}}: no volume plugin matched`

@markturansky Since all the VolumeSource plugins seem to be nil I'm wondering if there is some additional config needed or just a tweak to the code to add the NFSVolumeSource at startup?

### PR DESCRIPTION
**Pull request by markturansky**
@smarterclayton The list of plugins in OpenShift did not match what is upstream.  PTAL?

 @sosiouxme The error in http://pastebin.test.redhat.com/285172 is "missing plugin", so this will resolve #2433.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Instead of this method, we should just call cmd/kube-apiserver/app#Plugins instead, since we've already statically loaded them there.

**Comment by markturansky** [comment]
@smarterclayton I see how we're doing both in origin/pkg/cmd/server/kubernetes.

In cmd/server/kubernetes/node.go we bring in our own pkg/kubelet/app/plugins as well as GCP/kubernetes/cmd/kubelet/app.  I can entirely replace the former with the latter.  

Is there any reason to keep our own list of plugins as opposed to relying on upstream's list?  Will we ever vary the plugins provided?

**Comment by markturansky** [comment]
nevermind, futureproofing. it would be easy enough to add that back should that need arise.  

OS now directly uses kubelet's list of plugins.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
