### PR TITLE
UPSTREAM: 16818: Namespace controller should always get latest state …

### PR DESCRIPTION
**Pull request by derekwaynecarr**
…prior to deletion

This fixes slow-down when doing bulk namespace deletions.

/cc @smarterclayton @ncdc @eparis

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1277912

**Comment by smarterclayton** [comment]
We'll do formal review in the morning.

On Nov 4, 2015, at 6:33 PM, Derek Carr <notifications@github.com> wrote:

…prior to deletion

This fixes slow-down when doing bulk namespace deletions.

/cc @smarterclayton <https://github.com/smarterclayton> @ncdc
<https://github.com/ncdc> @eparis <https://github.com/eparis>
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/openshift/origin/pull/5720
Commit Summary

   - UPSTREAM: 16818: Namespace controller should always get latest state
   prior to deletion

File Changes

   - *M*
   Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go
   <https://github.com/openshift/origin/pull/5720/files#diff-0> (23)
   - *M*
   Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller_test.go
   <https://github.com/openshift/origin/pull/5720/files#diff-1> (82)

Patch Links:

   - https://github.com/openshift/origin/pull/5720.patch
   - https://github.com/openshift/origin/pull/5720.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5720>.

**Comment by smarterclayton** [comment]
The e2e tests wedge as soon as we try the "namespace" test https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6906/consoleFull

**Comment by smarterclayton** [comment]
Changes LGTM

**Comment by smarterclayton** [comment]
Actually, we need this anyway... [merge]

**Comment by smarterclayton** [comment]
Your unit tests didn't compile.

**Comment by derekwaynecarr** [comment]
Fixed

**Comment by derekwaynecarr** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton removed merge tag, wasn't sure how you wanted to batch this

**Comment by liggitt** [comment]
adding [merge] per @smarterclayton

**Pull request merged**
