### PR TITLE
we are already production ready

### PR DESCRIPTION
**Pull request by akostadinov**
we are already production ready AFAIK so altering that statement

### CODE REVIEW

**Comment by smarterclayton** [comment]
Please do not open branches in Origin.

**Comment by smarterclayton** [comment]
Please reopen on a branch from your fork and I'll merge this.

**Comment by akostadinov** [comment]
Sorry, it was quick fix via web UI and I didn't realize it's gonna create a branch in origin. Strange.

**Comment by smarterclayton** [comment]
There's a drop down now which lets you get the choice - it's not obvious
unless you know to look for it.

**Pull request closed without merging**
