### PR TITLE
Fixes extended tests failing because of rails 5 upgrade on rails-ex repo

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
[testextended](core)

**Comment by coreydaley** [comment]
[testextended][extended:core]

**Comment by coreydaley** [comment]
[test]

**Comment by coreydaley** [comment]
[testextended][extended:core]

**Comment by coreydaley** [comment]
[test]

**Comment by coreydaley** [comment]
[testextended][extended:core]

**Comment by coreydaley** [comment]
Failed due to a possible test flake
Issue #11903

**Comment by coreydaley** [comment]
[test]

**Comment by coreydaley** [comment]
[testextended][extended:core]

**Comment by coreydaley** [comment]
@bparees 
Since the test that I fixed is NOT failing now, and the extended tests that are failing are failing for everyone it seems, can we go ahead and merge this?

**Comment by bparees** [comment]
yup, thanks @coreydaley 

[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
