### PR TITLE
Fix deployment CLI ops link and make all doc links https

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1285690

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
Should this be HTTPS as well?

```
         default:
           return "http://docs.openshift.org/latest/welcome/index.html";
```

LGTM otherwise

**Comment by jwforres** [comment]
Yes, good catch

**Comment by jwforres** [comment]
[merge]

**Comment by deads2k** [comment]
re[merge]

**Comment by deads2k** [comment]
[test]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
