### PR TITLE
integration: add multiple ict deployment test

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik @smarterclayton

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
```
Running TestTriggers_MultipleICTs...
ok      TestTriggers_MultipleICTs
```

**Comment by kargakis** [comment]
one more [test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/8427 [test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
new-app flake
```
FAILURE after 2.367s: test/cmd/basicresources.sh:312: executing 'oc new-app https://github.com/openshift/ruby-hello-world' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: can't look up Docker image "centos/ruby-22-centos7": Internal error occurred: error retrieving repository: server returned 403
error: no match for "centos/ruby-22-centos7"
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3303/consoleFull

[merge]

**Pull request merged**
