### PR TITLE
UPSTREAM: 49230: use informers for quota calculation

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1473370
bug 1473370

see: https://github.com/kubernetes/kubernetes/pull/49230

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@deads2k - i see no reason we do not pick this into origin/master now.

/fyi @eparis @smarterclayton

**Comment by derekwaynecarr** [comment]
[test]

**Comment by smarterclayton** [comment]
Lgtm

On Jul 19, 2017, at 7:53 PM, Derek Carr <notifications@github.com> wrote:

[test]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/15358#issuecomment-316554929>,
or mute
the thread

**Comment by derekwaynecarr** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test][

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
