### PR TITLE
Switch to using github.com/openshift/imagebuilder

### PR DESCRIPTION
**Pull request by smarterclayton**
Also cleanup some Godeps incorrectness that crept in after a Godep save

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test] @liggitt please take a look at the bump changes.  I've already pushed stable-20160804 (shame this isn't the year 3216)

**Comment by liggitt** [comment]
bump LGTM, I was surprised to see github.com/onsi/ginkgo/ginkgo and github.com/jteeuwen/go-bindata/go-bindata leave Godeps.json

**Comment by smarterclayton** [comment]
Neither of those are actually included in the dependency tree - they are binaries we invoke.

**Comment by smarterclayton** [comment]
So godep save can't save them.

**Comment by smarterclayton** [comment]
[test] #9938

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
