### PR TITLE
adding X-Forwarded-For header to reencrypt route

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
add X-Forwarded-For header for reencrypt routes, just as it is for edge routes

Bug: 1449022 [Link](https://bugzilla.redhat.com/show_bug.cgi?id=1449022)

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@openshift/networking @knobunc PTAL

**Comment by JacobTanenbaum** [comment]
[test]

**Comment by knobunc** [comment]
@JacobTanenbaum Can you take the : out of the commit message in "Bug: 1449022" please?  I think the : confuses the commit hook's parser.

**Comment by knobunc** [comment]
@JacobTanenbaum thanks.  [merge]

**Comment by eparis** [comment]
[merge] looking for flake number

**Pull request merged**
