### PR TITLE
install ceph luminous package in centos7 based image

### LINKED ISSUE #17287: ceph-common 0.94.5 in the docker image origin-base is outdated
The provided ceph-common package is from October 2015 and completly outdated. The Dockerfile of origin-base should include at least ceph-common v10.2.0 Jewel or newer. The parameters imageFormat and imageFeatures of Kubernetes 1.7 are not supported for OpenShift Origin 3.7 in this condition.

kind: StorageClass
apiVersion: storage.k8s.io/v1
parameters:
  imageFormat: "2"
  imageFeatures: "layering"

### PR DESCRIPTION
**Pull request by rootfs**
fix #17287

@stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Are there any other options? Depending on EPEL here makes CI very unstable

**Comment by rootfs** [comment]
@stevekuznetsov unfortunately no, see http://docs.ceph.com/docs/luminous/install/get-packages/

**Comment by stevekuznetsov** [comment]
I'm not seeing EPEL involved here: http://docs.ceph.com/docs/luminous/install/get-packages/#rpm-packages

**Comment by rootfs** [comment]
It is there:
`Some Ceph packages (e.g., EPEL) must take priority over standard packages`

Without epel, installation just failed:

```console
# docker run -ti centos:7 bash
[root@a1d24973b47e /]# rpm -Uvh https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm
Retrieving https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm
warning: /var/tmp/rpm-tmp.La1rrT: Header V4 RSA/SHA256 Signature, key ID 460f3994: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:ceph-release-1-1.el7             ################################# [100%]
[root@a1d24973b47e /]# yum install -y ceph-common
Loaded plugins: fastestmirror, ovl
Ceph                                                                                                                                                 | 2.9 kB  00:00:00
Ceph-noarch                                                                                                                                          | 2.9 kB  00:00:00
base                                                                                                                                                 | 3.6 kB  00:00:00
ceph-source                                                                                                                                          | 2.9 kB  00:00:00
extras                                                                                                                                               | 3.4 kB  00:00:00
updates                                                                                                                                              | 3.4 kB  00:00:00
(1/7): Ceph-noarch/primary_db                                                                                                                        | 6.0 kB  00:00:00
(2/7): base/7/x86_64/group_gz                                                                                                                        | 156 kB  00:00:00
(3/7): ceph-source/primary_db                                                                                                                        |  17 kB  00:00:00
(4/7): Ceph/x86_64/primary_db                                                                                                                        | 270 kB  00:00:00
(5/7): extras/7/x86_64/primary_db                                                                                                                    | 130 kB  00:00:00
(6/7): base/7/x86_64/primary_db                                                                                                                      | 5.7 MB  00:00:00
(7/7): updates/7/x86_64/primary_db                                                                                                                   | 3.6 MB  00:00:01
Determining fastest mirrors
 * base: mirror.math.princeton.edu
 * extras: linux.cc.lehigh.edu
 * updates: mirror.math.princeton.edu
Resolving Dependencies
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: librbd1 = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libcephfs2 = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-rados = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-cephfs = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-rgw = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-rbd = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: librados2 = 2:12.2.1-0.el7 for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.0)(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-prettytable for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.1)(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: python-requests for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libtcmalloc.so.4()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: librbd.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: librados.so.2()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libcephfs.so.2()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libsnappy.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libfuse.so.2()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libaio.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libradosstriper.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libceph-common.so.0()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package fuse-libs.x86_64 0:2.9.2-8.el7 will be installed
---> Package gperftools-libs.x86_64 0:2.4-8.el7 will be installed
--> Processing Dependency: libunwind.so.8()(64bit) for package: gperftools-libs-2.4-8.el7.x86_64
---> Package libaio.x86_64 0:0.3.109-13.el7 will be installed
---> Package libcephfs2.x86_64 2:12.2.1-0.el7 will be installed
---> Package libibverbs.x86_64 0:13-7.el7 will be installed
--> Processing Dependency: rdma-core(x86-64) = 13-7.el7 for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: perl(warnings) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: perl(strict) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: perl(Getopt::Long) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: perl(File::Basename) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: libnl-route-3.so.200(libnl_3)(64bit) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: libnl-3.so.200(libnl_3)(64bit) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: /usr/bin/perl for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: libnl-route-3.so.200()(64bit) for package: libibverbs-13-7.el7.x86_64
--> Processing Dependency: libnl-3.so.200()(64bit) for package: libibverbs-13-7.el7.x86_64
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package libradosstriper1.x86_64 2:12.2.1-0.el7 will be installed
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
---> Package python-cephfs.x86_64 2:12.2.1-0.el7 will be installed
---> Package python-prettytable.noarch 0:0.7.2-3.el7 will be installed
---> Package python-rados.x86_64 2:12.2.1-0.el7 will be installed
---> Package python-rbd.x86_64 2:12.2.1-0.el7 will be installed
---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7_1.noarch
---> Package python-rgw.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: librgw2 = 2:12.2.1-0.el7 for package: 2:python-rgw-12.2.1-0.el7.x86_64
--> Processing Dependency: librgw.so.2()(64bit) for package: 2:python-rgw-12.2.1-0.el7.x86_64
---> Package snappy.x86_64 0:1.1.0-3.el7 will be installed
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package libnl3.x86_64 0:3.2.28-4.el7 will be installed
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
---> Package librgw2.x86_64 2:12.2.1-0.el7 will be installed
---> Package libunwind.x86_64 2:1.2-2.el7 will be installed
---> Package perl.x86_64 4:5.16.3-292.el7 will be installed
--> Processing Dependency: perl-libs = 4:5.16.3-292.el7 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Socket) >= 1.3 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) >= 1.10 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl-macros for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl-libs for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads::shared) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(constant) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::Local) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Storable) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Socket) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::XHTML) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::Search) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Filter::Util::Call) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Temp) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec::Unix) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec::Functions) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Path) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Exporter) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Cwd) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Carp) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: libperl.so()(64bit) for package: 4:perl-5.16.3-292.el7.x86_64
---> Package perl-Getopt-Long.noarch 0:2.40-2.el7 will be installed
--> Processing Dependency: perl(Pod::Usage) >= 1.14 for package: perl-Getopt-Long-2.40-2.el7.noarch
--> Processing Dependency: perl(Text::ParseWords) for package: perl-Getopt-Long-2.40-2.el7.noarch
---> Package python-urllib3.noarch 0:1.10.2-3.el7 will be installed
--> Processing Dependency: python-six for package: python-urllib3-1.10.2-3.el7.noarch
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-urllib3-1.10.2-3.el7.noarch
---> Package rdma-core.x86_64 0:13-7.el7 will be installed
--> Processing Dependency: pciutils for package: rdma-core-13-7.el7.x86_64
--> Processing Dependency: initscripts for package: rdma-core-13-7.el7.x86_64
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package initscripts.x86_64 0:9.49.39-1.el7 will be installed
--> Processing Dependency: sysvinit-tools >= 2.87-5 for package: initscripts-9.49.39-1.el7.x86_64
--> Processing Dependency: iproute for package: initscripts-9.49.39-1.el7.x86_64
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
---> Package pciutils.x86_64 0:3.5.1-2.el7 will be installed
--> Processing Dependency: pciutils-libs = 3.5.1-2.el7 for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: libpci.so.3(LIBPCI_3.5)(64bit) for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: libpci.so.3(LIBPCI_3.3)(64bit) for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: libpci.so.3(LIBPCI_3.1)(64bit) for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: libpci.so.3(LIBPCI_3.0)(64bit) for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: hwdata for package: pciutils-3.5.1-2.el7.x86_64
--> Processing Dependency: libpci.so.3()(64bit) for package: pciutils-3.5.1-2.el7.x86_64
---> Package perl-Carp.noarch 0:1.26-244.el7 will be installed
---> Package perl-Exporter.noarch 0:5.68-3.el7 will be installed
---> Package perl-File-Path.noarch 0:2.09-2.el7 will be installed
---> Package perl-File-Temp.noarch 0:0.23.01-3.el7 will be installed
---> Package perl-Filter.x86_64 0:1.49-3.el7 will be installed
---> Package perl-PathTools.x86_64 0:3.40-5.el7 will be installed
---> Package perl-Pod-Simple.noarch 1:3.28-4.el7 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
--> Processing Dependency: perl(Encode) for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
---> Package perl-Pod-Usage.noarch 0:1.63-3.el7 will be installed
--> Processing Dependency: perl(Pod::Text) >= 3.15 for package: perl-Pod-Usage-1.63-3.el7.noarch
--> Processing Dependency: perl-Pod-Perldoc for package: perl-Pod-Usage-1.63-3.el7.noarch
---> Package perl-Scalar-List-Utils.x86_64 0:1.27-248.el7 will be installed
---> Package perl-Socket.x86_64 0:2.010-4.el7 will be installed
---> Package perl-Storable.x86_64 0:2.45-3.el7 will be installed
---> Package perl-Text-ParseWords.noarch 0:3.29-4.el7 will be installed
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
---> Package perl-Time-Local.noarch 0:1.2300-2.el7 will be installed
---> Package perl-constant.noarch 0:1.27-2.el7 will be installed
---> Package perl-libs.x86_64 4:5.16.3-292.el7 will be installed
---> Package perl-macros.x86_64 4:5.16.3-292.el7 will be installed
---> Package perl-threads.x86_64 0:1.87-4.el7 will be installed
---> Package perl-threads-shared.x86_64 0:1.43-6.el7 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el7 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
---> Package python-six.noarch 0:1.9.0-2.el7 will be installed
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package hwdata.x86_64 0:0.252-8.6.el7 will be installed
---> Package iproute.x86_64 0:3.10.0-87.el7 will be installed
--> Processing Dependency: libmnl.so.0(LIBMNL_1.0)(64bit) for package: iproute-3.10.0-87.el7.x86_64
--> Processing Dependency: libxtables.so.10()(64bit) for package: iproute-3.10.0-87.el7.x86_64
--> Processing Dependency: libmnl.so.0()(64bit) for package: iproute-3.10.0-87.el7.x86_64
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
---> Package pciutils-libs.x86_64 0:3.5.1-2.el7 will be installed
---> Package perl-Encode.x86_64 0:2.51-7.el7 will be installed
---> Package perl-Pod-Escapes.noarch 1:1.04-292.el7 will be installed
---> Package perl-Pod-Perldoc.noarch 0:3.20-4.el7 will be installed
--> Processing Dependency: perl(parent) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: perl(HTTP::Tiny) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: groff-base for package: perl-Pod-Perldoc-3.20-4.el7.noarch
---> Package perl-podlators.noarch 0:2.5.1-3.el7 will be installed
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
---> Package sysvinit-tools.x86_64 0:2.88-14.dsf.el7 will be installed
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package groff-base.x86_64 0:1.22.2-8.el7 will be installed
---> Package iptables.x86_64 0:1.4.21-18.2.el7_4 will be installed
--> Processing Dependency: libnfnetlink.so.0()(64bit) for package: iptables-1.4.21-18.2.el7_4.x86_64
--> Processing Dependency: libnetfilter_conntrack.so.3()(64bit) for package: iptables-1.4.21-18.2.el7_4.x86_64
---> Package libmnl.x86_64 0:1.0.3-7.el7 will be installed
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
---> Package perl-HTTP-Tiny.noarch 0:0.033-3.el7 will be installed
---> Package perl-parent.noarch 1:0.225-244.el7 will be installed
--> Running transaction check
---> Package ceph-common.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: libleveldb.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: libbabeltrace-ctf.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: 2:ceph-common-12.2.1-0.el7.x86_64
---> Package libnetfilter_conntrack.x86_64 0:1.0.6-1.el7_3 will be installed
---> Package libnfnetlink.x86_64 0:1.0.1-4.el7 will be installed
---> Package librados2.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-12.2.1-0.el7.x86_64
---> Package librbd1.x86_64 2:12.2.1-0.el7 will be installed
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-12.2.1-0.el7.x86_64
--> Finished Dependency Resolution
Error: Package: 2:ceph-common-12.2.1-0.el7.x86_64 (Ceph)
           Requires: libbabeltrace-ctf.so.1()(64bit)
Error: Package: 2:ceph-common-12.2.1-0.el7.x86_64 (Ceph)
           Requires: liblz4.so.1()(64bit)
Error: Package: 2:librbd1-12.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:librados2-12.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:ceph-common-12.2.1-0.el7.x86_64 (Ceph)
           Requires: libleveldb.so.1()(64bit)
Error: Package: 2:ceph-common-12.2.1-0.el7.x86_64 (Ceph)
           Requires: libbabeltrace.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@a1d24973b47e /]#
```

**Comment by megian** [comment]
Check the comments here that the leveldb is causing the dependency to EPEL and a possible way with the package centos-release-ceph-luminous to prevent EPEL repos https://bugs.launchpad.net/puppet-ceph/+bug/1562998

**Comment by rootfs** [comment]
@megian thanks for the pointer
@stevekuznetsov epel removed

**Comment by stevekuznetsov** [comment]
This seems reasonable to me. Thanks for finding a workaround.

@smarterclayton any comments here?

/lgtm
/approve
/hold
/retest

**Comment by smarterclayton** [comment]
Should be in the same RUN statement.

**Comment by rootfs** [comment]
@stevekuznetsov @smarterclayton folded into same RUN now.

**Pull request merged**
