### PR TITLE
Upstream: make docker bridge configuration more dynamic

### PR DESCRIPTION
**Pull request by sdodson**
This replicates https://github.com/openshift/openshift-sdn/pull/78 in the integrated sdn-ovs. Please see that PR for details on how I've tested it.

I've duplicated the docker.service.d dropfile here but we could add it to the godep to ensure that we don't miss any future changes. The rel-eng directory has some additional cruft and there's no go code so I'm fine either way.

### CODE REVIEW

**Comment by sdodson** [comment]
I forgot to mention, I included this in OSE Beta4 as it helps the situation where openshift-node depends on docker but docker fails to start because it's configured with a bridge that doesn't exist at boot time. Thus far I've not heard anyone complain about issues created by that change.

**Comment by sdodson** [comment]
@rajatchopra @smarterclayton If we can get this in for 1.0 I'd appreciate it. upstream openshift-sdn PR is yet to be merged too.

**Comment by rajatchopra** [comment]
@sdodson openshift-sdn-ovs.conf deletes the  /run/openshift-sdn/docker-network environment file. Does this mean stopping openshift-node will remove that file? If so, then it is a blocker for our next task which deals with 'do not restart docker daemon if SDN does not need reconfiguring".

**Comment by sdodson** [comment]
@rajatchopra I'm fine with not removing it via ExecStopPost. Assuming ovs and all that had already been set up properly by openshift-sdn-ovs, what happens when you create a new container and openshift-sdn-ovs isn't running?

**Comment by rajatchopra** [comment]
With ExecStopPost removed, this looks good to me.

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
