### PR TITLE
Improve web console metrics error message

### PR DESCRIPTION
**Pull request by spadgett**
Show a more detailed error including the hawkular-metrics URL. If the problem is with self-signed certs, it gives the user a chance to accept the cert.

metrics-error

@jwforres @smarterclayton

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres ready for code review, but I need to configure metrics properly to test before merging.

**Comment by spadgett** [comment]
I've verified metrics work fine with the change when properly configured.

Here's an example with error details from Hawkular:

openshift_web_console

**Comment by jwforres** [comment]
LGTM, ready to merge?

**Comment by spadgett** [comment]
@jwforres Thanks. Rebased to avoid any bindata problems.

[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
