### PR TITLE
refactored hack/text and added tests to CI

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Refactored `hack/text.sh` to use functions instead of aliases, and to not color on non-TTY calls. Added the test-cmd wrapper function tests to CI though `make check-test`.

Fixes https://github.com/openshift/origin/issues/6013

/cc @deads2k

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Jenkins seems to have moved from `test-go` to `test-cmd` without running these tests ...

**Comment by deads2k** [comment]
> Jenkins seems to have moved from test-go to test-cmd without running these tests ...

Just add it to to the `test/cmd` folder and call it a day.

**Comment by stevekuznetsov** [comment]
I don't think that is ideologically correct - `test/cmd` scripts are buckets of integration tests that assume a lot about their environment, this has nothing to do with them.

**Comment by stevekuznetsov** [comment]
Flake in Jenkins on [`test-end-to-end`](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7367/console):
```
!!! Error in hack/../test/end-to-end/core.sh:245
	'grep -q "unable to validate against any security context constraint"' exited with status 0 1
Call stack:
	1: hack/../test/end-to-end/core.sh:245 main(...)
Exiting with status 1
```

**Comment by stevekuznetsov** [comment]
First commit moved to https://github.com/openshift/origin/pull/6012. Updated this PR to include the tests, special-cased inside of `test-cmd` and redirected to a artifact file.

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by stevekuznetsov** [comment]
@deads2k This is dependent on the `edit` PR as that one contains the TTL commit now.

**Comment by stevekuznetsov** [comment]
@deads2k rebased & ready

**Comment by deads2k** [comment]
still lgtm [merge]

**Comment by stevekuznetsov** [comment]
Flake waiting for an image endpoint... same as https://github.com/openshift/origin/issues/5559:
```
--- FAIL: TestRegistryClientQuayIOImage-4 (10.00s)
	dockerregistryclient_test.go:132: unexpected error: error checking for V2 registry at https://quay.io/v2/: Get https://quay.io/v2/: net/http: TLS handshake timeout
FAIL
```

**Pull request merged**
