### PR TITLE
UPSTREAM: 45352: Pod (Anti)affinity shouldn't be respected across namespaces.

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1483119
Upstream fix+unit test: 
https://github.com/kubernetes/kubernetes/pull/45352
https://github.com/kubernetes/kubernetes/pull/45152

/cc @sjenning

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla change your commit mesage to be same as title of this PR. I mean commit must also have UPSTREAM: 45352:.

**Comment by ravisantoshgudimetla** [comment]
@deads2k @smarterclayton Can I get approval on this one?

**Comment by deads2k** [comment]
already merged upstream

/approve

**Pull request merged**
