### PR TITLE
extended: fix latest deployment test flakes 

### PR DESCRIPTION
**Pull request by kargakis**
[test]

### CODE REVIEW

**Comment by kargakis** [comment]
Heh, got it
```
STEP: waiting for the first rollout to complete
Sep 22 06:32:55.906: INFO: Latest rollout of dc/deployment-simple (rc/deployment-simple-1) is complete.
STEP: updating the deployment config in order to trigger a new rollout
STEP: waiting for the second rollout to complete
Sep 22 06:32:55.945: INFO: Latest rollout of dc/deployment-simple (rc/deployment-simple-1) is complete.
```
Our test utility is broken so it will never wait for the second deployment to complete. cc: @mfojtik @smarterclayton

**Comment by kargakis** [comment]
> Our test utility is broken so it will never wait for the second deployment to complete. cc: @mfojtik @smarterclayton

Or maybe not broken and we just need to wait a bit for changes to show up in the api

**Comment by kargakis** [comment]
@mfojtik ptal

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
> You are in the build queue at position: 17

Where is my vip merge ?

**Comment by kargakis** [comment]
This PR is so successful

**Pull request merged**
