### PR TITLE
UPSTREAM: 64541: Add more kubectl auth reconcile flags

### PR DESCRIPTION
**Pull request by mrogers950**
A pick for https://github.com/kubernetes/kubernetes/pull/64541 to go along with the --dry-run addition, they were split between 1.11 and 1.12.
@juanvallejo @deads2k

### CODE REVIEW

**Comment by juanvallejo** [comment]
@mrogers950 
> A carry for kubernetes/kubernetes#64541

why a carry instead of a pick?

**Comment by mrogers950** [comment]
@juanvallejo 
> why a carry instead of a pick?
Don't know, I guess that means I should do a pick then :)

**Comment by mrogers950** [comment]
@juanvallejo thanks, updated.

**Pull request merged**
