### PR TITLE
Owners for CLI completions

### PR DESCRIPTION
**Pull request by fabianofranz**
More OWNERS, PTAL @stevekuznetsov @liggitt.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Eh, no harm in merging. No need to bug someone on the global list.

**Comment by bparees** [comment]
@stevekuznetsov there is harm in merging, this broke verification for everyone.  reverting.

**Comment by bparees** [comment]
(caused https://github.com/openshift/origin/issues/15597)

**Comment by stevekuznetsov** [comment]
Eek. Sorry

**Pull request merged**
