### PR TITLE
Clean up requested project if there are errors creating template items

### PR DESCRIPTION
**Pull request by liggitt**
Cleans up projects that fail halfway through a project creation, reported in https://bugzilla.redhat.com/show_bug.cgi?id=1367432

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.  wouldn't mind having a test though.

**Comment by liggitt** [comment]
working on it

**Comment by liggitt** [comment]
[test]

**Comment by mfojtik** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
[merge]

**Comment by mfojtik** [comment]
double merge! 🌈

**Pull request merged**
