### PR TITLE
Add placement and container to popover and tooltip into popover.js so…

### PR DESCRIPTION
**Pull request by sg00dwin**
… that messages aren't hidden when spanning multiple scrollable areas.
Removed all instances of data-placement and data-container from markup.
 - Fixes https://github.com/openshift/origin/issues/7723

@jwforres 
@spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
It looks like `"auto"` will default to top and switch to bottom if there's not enough space above. I think for most tooltips, this is probably better. It's certainly better on mobile. I tested in iOS Simulator, and things are working fine (except for a few problems we know of like #6153).

@jwforres Opinion on this for 1.2?

**Comment by jwforres** [comment]
i'm ok with it @spadgett you tested both a tooltip and a popover?

**Comment by spadgett** [comment]
@jwforres I'll check both. Also need to test when a tooltip is recreated because dynamic content changes (like route warnings).

**Comment by spadgett** [comment]
LGTM

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
