### PR TITLE
WIP - Parallel image import streams

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by deads2k** [comment]
@liggitt are you going to keep pursuing this or shall I fix up sometime after 1.1.1?

**Comment by liggitt** [comment]
It's not at the top of my list, and I wouldn't consider it a blocker.

**Comment by smarterclayton** [comment]
It hasn't been an issue yet

**Comment by deads2k** [comment]
> @smarterclayton, is this still needed with the import changes?

It'll come for free given an informer, workqueue, and delayed re-queue tracking retries.

**Comment by smarterclayton** [comment]
Probably not - the scheduler has to be taken into account before an import
can be dispatched

**Comment by deads2k** [comment]
> Probably not - the scheduler has to be taken into account before an import
> can be dispatched

Interesting.  I'd've written the scheduler as either a scheduled job (ideal) or as an entity that can kick the main import controller (less ideal).  You're thinking of doing it as something else?

**Comment by smarterclayton** [comment]
It has to deal with requeueing and ordering if a retry fails.
Solvable, but annoying.

**Pull request closed without merging**
