### PR TITLE
bootstrap: fix mount handling in OSX

### PR DESCRIPTION
**Pull request by mfojtik**
Builds on https://github.com/openshift/origin/pull/18939 and https://github.com/openshift/origin/pull/18944 deals with shared mounts we need for openshift.volumes directory in Docker for Mac.

/cc @deads2k

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k e2e tests were using `host-data-dir` and `host-volume-dir`... not sure if this was not done to move the etcd storage into `/tmp`...

**Comment by mfojtik** [comment]
@deads2k hope the last commit will reveal the failed test mystery

**Comment by mfojtik** [comment]
@deads2k I think the last commit should put this misery to end :-)

**Comment by mfojtik** [comment]
@stevekuznetsov is there a way to make this work:

```
[INFO] [12:21:11+0000] Archiving all base directories to /data/src/github.com/openshift/origin/_output/scripts/clusterup/artifacts/clusterup ...
cp: cannot access ‘/tmp/tmp.ahcabOy039/clusterup/console/openshift.local.clusterup/etcd/member’: Permission denied
```

I'm trying to use `sudo` now, not sure if it is enabled in our CI.

**Comment by deads2k** [comment]
@mfojtik did CI for webconsole get updated?  

@spadgett

**Pull request merged**
