### PR TITLE
if no openshift-tests image can be auto-detected or specified, skip it

### PR DESCRIPTION
**Pull request by deads2k**
Also continues running tests if starting data collection failed and let the junit reflect it.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6

**Comment by deads2k** [comment]
build problems

/retest-required

**Comment by deads2k** [comment]
it appeared to work.  I'm labelling since we're hitting ovn-ic upgrade problems and need our disruption checking.

**Comment by deads2k** [comment]
/test all

ipv6 passed btw.

**Pull request merged**
