### PR TITLE
Bug 1256319: get: Fix nil timestamp output

### LINKED ISSUE #4275: ImageStreamTag updated 292 years ago
Using the following `ImageStream` definition:

```json

{
  "kind": "ImageStream",
  "apiVersion": "v1",
  "metadata": {
    "name": "openldap",
    "creationTimestamp": null
  },
  "spec": {
    "dockerImageRepository": "openshift/openldap-2441-centos7",
    "tags": [
      {
        "tag": "latest",
        "annotations": {
          "description": "Provides OpenLDAP v2.4.41",
          "iconClass": "fa-server",
          "tags": "server,openldap",
          "version": "2.4.41"
        }
      }
    ]
  },
  "status": {
    "dockerImageRepository": ""
  }
}
```
I do the following:

```sh
$ oc create -f test/extended/fixtures/ldap/ldapserver-imagestream.json 
imagestream "openldap" created
$ oc get imagestreamtag openldap:latest
NAME              DOCKER REF                                                                                                UPDATED         IMAGENAME
openldap:latest   openshift/openldap-2441-centos7@sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a   292 years ago   sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a
```

And I see that the last updated date was `292 years ago`.

@bparees

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #4275 

@stevekuznetsov @pweil- @ncdc

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
I would have expected `nil` time to bring us to 1970 instead of 1723, interesting.

**Comment by ncdc** [comment]
I think we also want to copy the timestamp from the event (https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L63) to the ImageStreamTag (https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L91), right?

Also, have you fully read the discussion in #4275? I don't think we've yet resolved which dates should be displayed where.

**Comment by ncdc** [comment]
Please don't merge this as is as it doesn't really fix the issue. The problem is that the date is always null, when it shouldn't be.

**Comment by kargakis** [comment]
> Also, have you fully read the discussion in #4275? I don't think we've yet resolved which dates should be displayed where.

The discussion in the issue feels like a discussion for a separate issue.

**Comment by ncdc** [comment]
I'm fine with that being a separate issue, but I believe the true fix for 4275 is to make ist.CreationTimestamp not be null (by taking the value from the event).

**Comment by kargakis** [comment]
@ncdc updated to pass the event timestamp in the tag
```
NAME              DOCKER REF                                                                                                UPDATED          IMAGENAME
openldap:latest   openshift/openldap-2441-centos7@sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a   22 minutes ago   sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a
```

**Comment by ncdc** [comment]
Add/update test to verify the time is being set correctly?

**Comment by kargakis** [comment]
```
rest_test.go:268: happy path: timestamp: expected 2015-03-24 09:38:00 +0000 UTC, got 2015-03-24 09:38:00 +0000 UTC
```
This is interesting

**Comment by kargakis** [comment]
Ok, this is ready @ncdc

**Comment by ncdc** [comment]
LGTM. @smarterclayton PTAL

**Comment by kargakis** [comment]
hmm, there is one more test that needs to be fixed

**Comment by smarterclayton** [comment]
I don't have any issues with this.

**Comment by kargakis** [comment]
`formatRelativeTime` is involved enough so I restored it back to it original state (it's used mostly in output that describes past times, alongside *ago*, but it's also used for running states eg. in deployments.)

Tests pass, this is ready **now**

**Comment by ncdc** [comment]
Cool, that sounds better.

**Comment by ncdc** [comment]
[merge]

**Comment by kargakis** [comment]
```
- UnknownError: unknown error: [$injector:unpr] Unknown provider: dateRelativeFilterProvider <- dateRelativeFilter
http://errors.angularjs.org/1.3.8/$injector/unpr?p0=dateRelativeFilterProvider%20%3C-%20dateRelativeFilter
```
re[merge]

**Comment by kargakis** [comment]
one more [merge]

**Pull request merged**
