### PR TITLE
[WIP] Allow importing images from another image stream

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
I don't think we should be allowing this, I believe it was by design that we do *not* allow you to do this.

@smarterclayton @mfojtik @liggitt @soltysh who has the history on this?

**Comment by dmage** [comment]
This restriction was added in #17953. Before that it was a valid operation.

**Comment by dmage** [comment]
> tag "mytag" points to existing ImageStreamTag "otherimage:mytag", it cannot be re-imported"

@soltysh do you remember why we deny to re-import an image from another image stream?

**Comment by bparees** [comment]
I'm pretty sure it was to avoid people using the imageimport controller(which has global privileges) to pull in information about someone else's image that they can't directly access.

**Comment by dmage** [comment]
@bparees this check is made by CLI, so I don't think that security is a reason.

**Comment by bparees** [comment]
> @bparees this check is made by CLI, so I don't think that security is a reason.

it wouldn't be the first time we screwed something like this up :)

**Comment by bparees** [comment]
@dmage why close?

**Comment by dmage** [comment]
@bparees you are right, ImageStreamImport works only with DockerImage, and it's not easy to change this because of security concerns.

**Comment by bparees** [comment]
@dmage so it sounds like we have a bug that we are allowing these imports for tags not named "latest".

**Comment by dmage** [comment]
@bparees we don't have implementation for it.

**Comment by bparees** [comment]
> @bparees we don't have implementation for it.

@dmage i'm talking about my comment 3 here:
https://bugzilla.redhat.com/show_bug.cgi?id=1530340#c3

in which we do appear to perform an import for a cross-stream tag named "latest".

**Comment by dmage** [comment]
@bparees I saw this, but I can't reproduce it.

**Comment by bparees** [comment]
ok, let's continue the discussion as far as what the behavior should be, in the bug.

**Pull request closed without merging**
