### PR TITLE
Make `oc observe --type-env-var` pass current env vars

### PR DESCRIPTION
**Pull request by tksm**
Fixes https://github.com/openshift/origin/issues/13190

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM, but could you add a quick test to verify this in `test/cmd/observe.sh`?

**Comment by tksm** [comment]
Thank you. I added a test for --type-env-var https://github.com/openshift/origin/pull/13192/commits/50281772cdb529df9a34011b8c1eb303f22019fe

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
