### PR TITLE
ensure build start time is always set

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1443687

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
standard pipeline flakes.
[merge]

**Pull request merged**
