### PR TITLE
Cherry-picking upstream commits prior to the next rebase

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Needed to ultimately fix project/namespace termination in Origin

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
Need to update this after #1573 to pick up the namespace_controller change

**Comment by derekwaynecarr** [comment]
@jwforres @liggitt @deads2k review please?  this was the update I made to Kube that was part of blocking project deletion in Origin https://github.com/GoogleCloudPlatform/kubernetes/pull/6246

**Comment by deads2k** [comment]
I'll trust it.  [merge]

**Comment by derekwaynecarr** [comment]
Re [merge]

**Pull request merged**
