### PR TITLE
Enable Scaleio volume

### PR DESCRIPTION
**Pull request by rootfs**
@childsb

### CODE REVIEW

**Comment by rootfs** [comment]
[test]

**Comment by enj** [comment]
@deads2k do changes to the 3.6 branch now mean 3.6.1?

**Comment by vladimirvivien** [comment]
@rootfs seems there the CI infrastructure is failing during test with several of the followings.  Retesting does not seem to make the problem go away.
```
--- FAIL: TestRouter (0.03s)
	router_test.go:75: Error starting container openshift/origin-haproxy-router : no such image
```

**Comment by rootfs** [comment]
@vladimirvivien thanks!

@stevekuznetsov can you help? thanks!

**Comment by stevekuznetsov** [comment]
Backports to release-3.6 are blocked on #15771

**Comment by rootfs** [comment]
thanks @stevekuznetsov !

**Comment by rootfs** [comment]
@childsb all green, can you merge?

**Comment by eparis** [comment]
this is not something we should fix in origin 3.6.

**Comment by vincenzodnp** [comment]
Hello there.
I followed the example to integrate Openshift 3.6 / K8S 1.6 with ScaleIO.
I'm able to create the secret, the storageclass and a pod with a ScaleIO volume attached, but when I try to create a pvc, it stays in pending state and I get the errore in title ("no volume plugin matched")

Following system info:
OS: Centos7
Kernel: 3.10.0-514.el7.x86_64
ScaleIO: 2.0.13
Openshift: Origin 3.6
K8s: v1.6.1+5115d708d7

```
kubectl get pvc
NAME             STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc-sio-small  Pending                                                                            sio-k8s        15m
```

```
kubectl describe sc sio-k8s
Name:		sio-k8s
IsDefaultClass:	No
Annotations:	<none>
Provisioner:	kubernetes.io/scaleio
Parameters:	fsType=xfs,gateway=https://192.168.20.254/api,protectionDomain=default,secretRef=sio-secret,storagePool=default,system=scaleio
Events:		<none>
```
```
oc get event pvc-sio-small.150cced22d69293b 
LASTSEEN   FIRSTSEEN   COUNT     NAME            KIND                    SUBOBJECT   TYPE      REASON               SOURCE                        MESSAGE
4m         19m         62        pvc-sio-small   PersistentVolumeClaim               Warning   ProvisioningFailed   persistentvolume-controller   no volume plugin matched
```

**Pull request closed without merging**
