### PR TITLE
TRT-1898: Revert "NO-JIRA: address malformed CMO configmap post-test"

### PR DESCRIPTION
**Pull request by xueqzhan**
Reverts openshift/origin#29309; tracked by https://issues.redhat.com/browse/OCPBUGS-45153

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

This PR has causd the nightly failures for many techpreview jobs. Here is one example: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-techpreview/1861677512929579008

Test is stuck with this error:

  I1127 09:11:20.327512 62130 client.go:421] Project "e2e-test-monitoring-collection-profiles-mqvzf" has been fully provisioned.
    STEP: restoring the original configuration for the operator @ 11/27/24 09:11:21.232
    [INTERRUPTED] in [AfterAll] - github.com/openshift/origin/test/extended/prometheus/collection_profiles.go:99 @ 11/27/24 09:26:06.355
    ------------------------------
    Interrupted by User
    First interrupt received; Ginkgo will run any cleanup and reporting nodes but will skip all remaining specs.  Interrupt again to skip cleanup.
    Here's a current progress report:
      [sig-instrumentation][OCPFeatureGate:MetricsCollectionProfiles] The collection profiles feature-set initially, in a homogeneous default environment, should expose default metrics [Suite:openshift/conformance/parallel] (Spec Runtime: 14m49.846s)
        github.com/openshift/origin/test/extended/prometheus/collection_profiles.go:140
        In [AfterAll] (Node Runtime: 14m45.187s)
          github.com/openshift/origin/test/extended/prometheus/collection_profiles.go:99
          At [By Step] restoring the original configuration for the operator (Step Runtime: 14m45.123s)
            github.com/openshift/origin/test/extended/prometheus/collection_profiles.go:104

          Spec Goroutine
          goroutine 236 [select]
            github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc000fa2070, {0x7e574e8, 0xc23fb80}, 0x1, {0x0, 0x0, 0x0})
              github.com/onsi/gomega@v1.34.2/internal/async_assertion.go:538
            github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000fa2070, {0x7e574e8, 0xc23fb80}, {0x0, 0x0, 0x0})
              github.com/onsi/gomega@v1.34.2/internal/async_assertion.go:145
          > github.com/openshift/origin/test/extended/prometheus.init.func1.2()
              github.com/openshift/origin/test/extended/prometheus/collection_profiles.go:118
            github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0xc006c77b00?, 0xc006c5fe00?})
              github.com/onsi/ginkgo/v2@v2.20.2/internal/node.go:472
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
              github.com/onsi/ginkgo/v2@v2.20.2/internal/suite.go:901
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 1
              github.com/onsi/ginkgo/v2@v2.20.2/internal/suite.go:888
    ------------------------------

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:

/payload-job periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-techpreview

CC: @rexagod

### CODE REVIEW

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-techpreview

**Comment by sosiouxme** [comment]
payload job passed
/lgtm

**Comment by rexagod** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-ipv6-techpreview

**Pull request merged**
