### PR TITLE
bump(github.com/coreos/etcd):v3.2.1

### LINKED ISSUE #15313: Fix etcd level
The rebase backlevelled etcd: etcd regressed to v3.1.5, needs to be 3.2.1.  @smarterclayton has a pull https://github.com/deads2k/origin/pull/35 that tried to restore it, but it didn't build. 

This is a delivery-blocker that I'll have to sort out

### PR DESCRIPTION
**Pull request by liggitt**
fixes #15313, pick of https://github.com/openshift/origin/pull/15315 with fixed godep.json and kube type fix

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
Oddly consistent failure:
```
Resume build
	Test Result (3 failures / -3)
github.com/openshift/origin/test/cmd/sdn/netnamespaces.test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$'
github.com/openshift/origin/test/cmd/sdn/netnamespaces.test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$'
github.com/openshift/origin/test/cmd/sdn/netnamespaces.test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$'
```

**Comment by liggitt** [comment]
Failure at https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3260/

Re[test]

**Comment by deads2k** [comment]
[merge]

**Comment by liggitt** [comment]
sdn.sh passes locally
[merge][severity:blocker]

**Comment by liggitt** [comment]
green except test_pull_request_origin_check in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3260/

green test_pull_request_origin_check in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3265/

**Comment by liggitt** [comment]
known flake on cli token log streaming. merging to unblock the alpha tag

**Pull request merged**
