### PR TITLE
Align with other cli descriptions

### PR DESCRIPTION
**Pull request by YuPengZTE**
dot

Signed-off-by: yupeng yu.peng36@zte.com.cn

### CODE REVIEW

**Comment by danmcp** [comment]
I would remove the period from the one that has it instead.

**Comment by fabianofranz** [comment]
@YuPengZTE thanks for the PR! Note that since this PR changes command docs, you have to run `hack/update-generated-docs.sh` and add the generated assets.

**Comment by YuPengZTE** [comment]
Thanks @fabianofranz, I run hack/update-generated-docs.sh, the info is that have no file to commit,like this:
root@yupeng-VirtualBox:/home/yupeng/github.com/openshift/origin# ./hack/update-generated-docs.sh 
++ Building go targets for linux/amd64: tools/gendocs tools/genman
++ Placing binaries
/home/yupeng/github.com/openshift/origin/hack/build-go.sh took 1673 seconds
Assets generated in /home/yupeng/github.com/openshift/origin//docs/generated
Assets generated in /home/yupeng/github.com/openshift/origin//docs/man/man1
Assets generated in /home/yupeng/github.com/openshift/origin//docs/man/man1
Assets generated in /home/yupeng/github.com/openshift/origin//docs/man/man1
root@yupeng-VirtualBox:/home/yupeng/github.com/openshift/origin# git status
位于分支 devDot
您的分支与上游分支 'origin/devDot' 一致。
无文件要提交，干净的工作区

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
