### PR TITLE
openshift-sdn update

### PR DESCRIPTION
**Pull request by dcbw**
Pulls in fixes for:

https://github.com/openshift/openshift-sdn/pull/244
https://github.com/openshift/openshift-sdn/pull/227

### CODE REVIEW

**Comment by eparis** [comment]
[merge]

**Comment by eparis** [comment]
[test] for funzies!

**Comment by eparis** [comment]
And now
https://github.com/openshift/origin/issues/6651
not going to bother retesting...

**Comment by liggitt** [comment]
there's no point retesting or merging until we clear up the #6651. Once we do, we'll kick relevant PRs

**Comment by eparis** [comment]
That's why I said I wasn't going to   :)

**Comment by liggitt** [comment]
[test][merge]

**Pull request merged**
