### PR TITLE
UPSTREAM: Allow recyclers to be configurable

### PR DESCRIPTION
**Pull request by markturansky**
see upstream:  https://github.com/GoogleCloudPlatform/kubernetes/pull/9870

Also, allows OS to configure recyclers:  #3187 

@smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by markturansky** [comment]
@smarterclayton is this stuck?  

The test failure above is completely unrelated to what I've done.

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
