### PR TITLE
test/e2e/upgrade: Relax 'too long' soft timeout for rollback jobs

### PR DESCRIPTION
**Pull request by wking**
`durationToSoftFailure` was added in 4447a19e86 (#25411), but didn't get the 2x on rollbacks we'e been adding to `maximumDuration` since a53efd5e27 (#22726).  That's recently been causing [the cluster-version operator's A->B->A rollback CI jobs to time out][1].  This commit catches `durationToSoftFailure` up with the "2x on rollbacks" approach, and also mentions "aborted" in messages for those types of tests, to help remind folks what's going on.

An alternative approach would be to teach `clusterUpgrade` to treat rollbacks as two separate hops (one for A->B, and another for B->A).  But that would be a more involved restructuring, and since we already had the 2x `maximumDuration` precedent in place, I haven't gone in that direction.

/assign @deads2k @smarterclayton

[1]: https://github.com/openshift/cluster-version-operator/pull/514#issuecomment-801242495

### CODE REVIEW

**Comment by smarterclayton** [comment]
lgtm, unfortunately can't use cluster bot to test rollback right now.  did you get a chance to manually test?

**Comment by wking** [comment]
I've floated openshift/release#16911.  If/when that lands, we can launch the test locally here to confirm this is working as expected.

**Comment by wking** [comment]
openshift/release#16911 landed.  Pull in a rollback CI job:

/test e2e-aws-upgrade

**Comment by wking** [comment]
[The AWS job][1] will fail on an API-server hiccup, but here's the new code:

```console
$ curl -s 'https://prow.ci.openshift.org/log?container=test&id=1372297649784360960&job=pull-ci-openshift-origin-master-e2e-aws-upgrade' | grep -1 'Starting upgrade\|aborted'

Mar 17 22:31:53.446: INFO: Starting upgrade to version= image=registry.build02.ci.openshift.org/ci-op-0nlcgytg/release@sha256:5e4c3bd76ea87ddef0581a8d0595659bba78a9ca326e9e540a62e0fac0e17163 attempt=afb37aec-a6c3-43fe-b582-d077fe50ba44
STEP: continuously hitting pods through the service's LoadBalancer
Mar 17 22:31:53.718: INFO: Upgrade will be aborted and the cluster will roll back to the current version after 100% of operators have upgraded
Mar 17 22:31:53.982: INFO: cluster upgrade is Progressing: Working towards registry.build02.ci.openshift.org/ci-op-0nlcgytg/release@sha256:5e4c3bd76ea87ddef0581a8d0595659bba78a9ca326e9e540a62e0fac0e17163: downloading update
--
Mar 18 00:25:44.427: INFO: cluster upgrade is Progressing: Working towards 4.8.0-0.ci.test-2021-03-17-212401-ci-op-0nlcgytg: 643 of 669 done (96% complete)
Mar 18 00:25:54.426: INFO: Completed aborted upgrade to registry.build02.ci.openshift.org/ci-op-0nlcgytg/release@sha256:2d4154a229980aa89214cbd1c9ea3ebbc0b65992d7e3e18a8eb4312f4a4e4868
Mar 18 00:25:54.520: INFO: Waiting on pools to be upgraded
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25977/pull-ci-openshift-origin-master-e2e-aws-upgrade/1372297649784360960

**Comment by wking** [comment]
Also, 22:31 -> 23:27 -> 00:25 are 1h legs respectively, `durationToSoftFailure` is 75m, and we did not fail a `should be fast` test-case, so we know that the doubling part is working too.

**Pull request merged**
