### PR TITLE
add oapi endpoint as allowable by system:anonymous

### PR DESCRIPTION
**Pull request by jcantrill**
@deads2k @liggitt  review??

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why is status checker the role you care about here (although this change is correct for status checking)?

**Comment by liggitt** [comment]
Role could be better named, that's just where we started collecting non resource endpoints containing server info

**Comment by liggitt** [comment]
LGTM, as an exact match of https://github.com/openshift/origin/pull/3633 :)

**Comment by smarterclayton** [comment]
For 3.0.1 and 3.1 we should document how to reset your bootstrap policy (system rules).  Can we do that in UPGRADE.md as a follow up and add it to any release that changes system roles?

**Comment by smarterclayton** [comment]
Hrm, meant to leave this on the other one.

**Comment by liggitt** [comment]
resetting bootstrap policy is a big hammer that includes cluster role bindings... pretty sure we want role updates only in most scenarios

**Comment by smarterclayton** [comment]
That's what I meant.  We need that easy to use.

On Tue, Jul 14, 2015 at 11:39 PM, Jordan Liggitt <notifications@github.com>
wrote:

> resetting bootstrap policy is a big hammer that includes cluster role
> bindings... pretty sure we want role updates only in most scenarios
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3709#issuecomment-121477652>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Merged in #3633

**Pull request closed without merging**
