### PR TITLE
Support block profile by pprof webserver

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
Without `runtime.SetBlockProfileRate(1)`,  block will show `0` as below.
~~~
profiles:
0	block
1358	goroutine
1178	heap
13	threadcreate
~~~

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by nak3** [comment]
`hack/verify-generated-conversions.sh` failed. It looks like [this PR](https://github.com/openshift/origin/commit/c48745a7f7c0d7719ecc3b693298f44b87741957) fix it. 

I rebased this PR.
Could you please run merge again @smarterclayton ?

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
