### PR TITLE
Remove --version from oc cluster up and replace it with hidden --tag flag

### PR DESCRIPTION
**Pull request by soltysh**
@deads2k as promised last week. I only ripped off the current `--version` from everywhere and replaced it with hidden `--tag` flag, updating the docs accordingly warning the tag flag should not be used for anything else than just origin dev. Not sure if we should add some kind of check for that,

/assign @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
@soltysh I think you need to chase this through the origin docs too and send an email out to our mailing lists.

/lgtm

**Comment by deads2k** [comment]
Do we care about the `--image` flag at all?  Do we support cluster up on OSE images without retagging them maybe?  How about marking that hidden and indicating what its for in help.

**Comment by soltysh** [comment]
This was already approved, so re-applying the labels.

**Comment by soltysh** [comment]
Rebase, re-applying labels.

**Pull request merged**
