### PR TITLE
Remove downward api call for Jenkins kubernetes example

### PR DESCRIPTION
**Pull request by mfojtik**
Depends on: https://github.com/openshift/jenkins/pull/86

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees hmm, now I'm thinking if we need this for backward compatibility (iow. when the "namespace" file is not in the /var/run/secrets (OSE, older versions...). However, having this in the template will always assure that the PROJECT_NAME is set so the script that reads it in the image does not make sense anymore...

**Comment by bparees** [comment]
what happens if PROJECT_NAME doesn't get set at all?  (because it's not in the template and it's not in /var/run/secrets)

**Comment by mfojtik** [comment]
@bparees we fail to inspect the project and autoconfigure kubernetes slaves (it is not hard failure, jenkins will still continue to work).

**Comment by bparees** [comment]
@mfojtik considering we're shipping that function with OSE3.2, i'm not worried about people on old versions i guess.

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
@bparees ok, then I guess it is safe to merge :)

**Pull request merged**
