### PR TITLE
Let .kubeconfig be a single-source config for API clients

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Between this and @pmorie secrets PR going in, we may actually be able to blog a good example of running origin on top of a kube with minimal effort.

/cc @smarterclayton we need this for demo next week based on what i experimented with today

**Comment by smarterclayton** [comment]
Can you rebase with upstream merged now?

**Comment by liggitt** [comment]
@deads2k last two commits?

**Comment by deads2k** [comment]
lgtm [merge]

**Pull request merged**
