### PR TITLE
Added more logging to image building process

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Been finding this annoying while debugging image build flakes

@smarterclayton or @bparees  PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why not just print out the actual command instead?

**Comment by stevekuznetsov** [comment]
I wasn't interested in seeing `oc ex dockerbuild` since it didn't give me any new information

**Comment by smarterclayton** [comment]
It would give you the two arguments you printed out.

**Comment by stevekuznetsov** [comment]
I don't really know what implementation you were looking for to "print out the actual command" but unless there's an issue with the logging statements that I added ... I'm not sure I want or need any other information than what I put in that `echo`.

**Comment by smarterclayton** [comment]
```
set -x
oc ex dockerbuild ...
set +x
```
or if you can do it an one-liner.

**Comment by smarterclayton** [comment]
Sorry for not being clearer, the #1 failure here is you want to debug it
locally as soon as it fails.  So printing the command is extremely useful
because the 90% debug case is: a) checkout that commit, b) cut and paste
the exact image build (or that and the parents).  Printing out the command
solves both problems (what is being built, and what someone would have to
do next to debug)

**Comment by stevekuznetsov** [comment]
The stack-trace refactor in #8527 gets you exactly what you want

**Pull request closed without merging**
