### PR TITLE
[release-1.11] Backport cronjobs fixes

### PR DESCRIPTION
**Pull request by runcom**
needed by https://github.com/openshift/origin/pull/21193 to continue chasing down test flakes

@smarterclayton @soltysh @mrunalp PTAL

### CODE REVIEW

**Comment by runcom** [comment]
Not sure about the CI, it's complaining about golang version

**Comment by smarterclayton** [comment]
This looks like it is broken on https://github.com/openshift/service-catalog/pull/31 @jboyd01 the VM build environment looks different than the test environment you built in.

**Comment by smarterclayton** [comment]
I updated the jobs, the next retest should bypass the failure

**Comment by mrunalp** [comment]
All green.

**Comment by runcom** [comment]
Approve needed

**Pull request merged**
