### PR TITLE
new-app: Avoid extra declaration

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by smarterclayton** [comment]
What is the extra allocation?

**Comment by kargakis** [comment]
> What is the extra allocation?

`list`

**Comment by smarterclayton** [comment]
There is only one allocation since we're passing a pointer in.

**Comment by kargakis** [comment]
> There is only one allocation since we're passing a pointer in.

Yep, my bad. s/allocation/declaration

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
