### PR TITLE
[DO NOT MERGE] broke test/cmd/edit

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/cc @deads2k

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@deads2k good news

**Comment by deads2k** [comment]
> @deads2k good news

Alright, not all hosed.  Still weird.

**Comment by stevekuznetsov** [comment]
I'm going to stick it somewhere in the middle and see if we get the artefact.

**Pull request closed without merging**
