### PR TITLE
OLM: Fix tests that check on pods when external ControlplaneToplogy

### PR DESCRIPTION
**Pull request by alvaroaleman**
In the external controlplane case, these pods have to be fetched from a different cluster.

Ref https://issues.redhat.com/browse/HOSTEDCP-257

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/assign @awgreene
could you have a look, please?

**Comment by awgreene** [comment]
Accidentally added both the approve and lgtm labels
/lgtm cancel

**Comment by awgreene** [comment]
Accidentally added both the approve and lgtm labels
/approve cancel

**Comment by alvaroaleman** [comment]
@awgreene @joelanford updated the change to check on the pods in the management cluster when testing a hypershift cluster, PTAL

**Pull request merged**
