### PR TITLE
fix image input extended test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal

**Comment by jim-minter** [comment]
@bparees all lgtm - fwiw a little context/background in the pr might have saved some detective work on this end, but it didn't hurt for me to do the legwork.

**Comment by bparees** [comment]
[testextended][extended:core(build with image source)]

**Comment by bparees** [comment]
@jim-minter yeah sorry, it started out as a simple fix to the fixture which was never running the right type of build before, but then i discovered that when fixed, it actually exposed a bug(nil pointer) in the from image handling logic.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
