### PR TITLE
Updating external examples

### PR DESCRIPTION
**Pull request by coreydaley**
Updating the external examples
Needed for pull request #18708

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal
It looks like the last library updates are overwriting the reference to the jenkins 3.10 image tag in my pr, and causing my tests to fail.

**Comment by bparees** [comment]
> It looks like the last library updates are overwriting the reference to the jenkins 3.10 image tag in my pr, and causing my tests to fail.

not sure why that would be the case since you're updating the imagestreams to v3.10 in your PR, but

/lgtm

**Comment by coreydaley** [comment]
@bparees it does seem weird, but looking at the results of the two failed tests (that I wrote for this pr), that is what i have seen cause that result, as it did locally when the library pr overwrote my local changes when i rebased.

**Pull request merged**
