### PR TITLE
use route to access prometheus instead of exec pods.

### PR DESCRIPTION
**Pull request by deads2k**
This reduces the dependency chain and eliminates a source of error.  Just use the route directly.

### CODE REVIEW

**Comment by tkashem** [comment]
why did we use exec pods originally, any historical context?

/lgtm

**Comment by tkashem** [comment]
waiting for https://github.com/openshift/origin/pull/26711 to merge first

/hold

**Comment by deads2k** [comment]
alert query still work!

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26740/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1481296112697479168

pushed additional commit to handle initialization without clientconfig. no longer requires updated library-go. removing hold and retagging.

**Comment by deads2k** [comment]
bypassing bug requirement to address CI problem from kube update

**Pull request merged**
