### PR TITLE
fix: wrap InitializeReleasePullSpecString in check for HasNoOptionalCapabilities

### PR DESCRIPTION
**Pull request by eggfoobar**
wrap InitializeReleasePullSpecString in check for HasNoOptionalCapabilities

### CODE REVIEW

**Comment by dtantsur** [comment]
metal-ipi-ovn-ipv6 passed, that's a good sign!

**Comment by DennisPeriquet** [comment]
@dtantsur @eggfoobar is there anything holding us back from merging this?

**Comment by DennisPeriquet** [comment]
I don't think the failure in e2e-aws-ovn-serial has anything to do with this PR.

**Comment by DennisPeriquet** [comment]
nothing changed so the e2e-aws-ovn-fips failure has nothing to do with the PR (as it passed before)

**Pull request merged**
