### PR TITLE
Remove old RPMs and the Dockerfiles that depend on them

### PR DESCRIPTION
**Pull request by smarterclayton**
In 4.0 only oc and hyperkube should be in use. Remove all other RPMs and clean up the old style Dockerfiles. Remove Dockerfiles moved to openshift/images. Limit what is built when make is run
on Linux.

Rename the remaining RPMS from `atomic-openshift|origin` to `openshift-*` and add `Provides: atomic-openshift-*` for historical users.

### CODE REVIEW

**Comment by deads2k** [comment]
why not
/lgtm

**Comment by smarterclayton** [comment]
Not ready yet, still making changes ;)

**Comment by smarterclayton** [comment]
Blocked by https://github.com/openshift/ci-operator/pull/289

**Comment by smarterclayton** [comment]
@sosiouxme @adammhaile please review, this removes images that are already in another repo, old dockerfiles, drops old rpms, and renames the rpms as openshift-clients and openshift-hyperkube, leaving provides there.

@cgwalters FYI as well, you should be unimpacted by this due to provides, I hope.

**Comment by cgwalters** [comment]
Is there an rpm-md repo built from this PR?  Ah I see in the logs `2019/03/07 06:09:59 RPMs being served at http://rpm-repo-ci-op-6gjqpvm9.svc.ci.openshift.org/ ` but I guess the CI namespace is expired.

I think we can do a local build+test.

**Comment by adammhaile** [comment]
@smarterclayton Just to confirm, these have already been updated in ocp-build-data?
looks fine, just want to be sure.

**Comment by smarterclayton** [comment]
All the images should be (last week).  Rpms no.

@cgwalters you can just kick /test images and it’ll be up in around 15-20m

**Comment by smarterclayton** [comment]
As Luke mentioned we’ll need to untag the old rpms from the compose

**Comment by ashcrow** [comment]
I'll update the RHCOS builds to only include `openshift-hyperkube` and `openshift-clients` in terms of `openshift-*` packages.

**Comment by sosiouxme** [comment]
ACK
I'll need to remove the RPM definitions and keep the pkgs out of the compose. Hm, for RHCOS do I need to put the new `openshift` pkg in the puddle?

**Comment by ashcrow** [comment]
I've staged the PR for RHCOS. Once the new packages are building and available let us know and we'll merge the changes.

**Comment by smarterclayton** [comment]
Tagging, will notify folks when this merges so there are no surprises.

**Comment by RiteshWalia** [comment]
Is there any fix/workaround for this issue #22815 ?

**Pull request merged**
