### PR TITLE
Bug 1196138 add newline char for: openshift ex router, output

### PR DESCRIPTION
**Pull request by sspeiche**
@danmcp if you could help nudge along

### CODE REVIEW

**Comment by danmcp** [comment]
@sspeiche Can you collapse these down into 1 commit please.

**Comment by danmcp** [comment]
[merge]

**Comment by sspeiche** [comment]
@danmcp didn't intend to replace it in the first place, I shouldn't have use my master branch for this PR but things are right now or can use my branch just for this fix https://github.com/sspeiche/origin/tree/bug1196138

**Comment by danmcp** [comment]
@sspeiche If you want to switch the branch you need to close this PR and open a new one.  Not the test cases are failing above.  I would recommend trying to run them locally to recreate.

**Comment by sspeiche** [comment]
replaced with https://github.com/openshift/origin/pull/1423

**Pull request closed without merging**
