### PR TITLE
Make csrf and session cookies httpOnly

### PR DESCRIPTION
**Pull request by liggitt**
Addresses half of https://bugzilla.redhat.com/show_bug.cgi?id=1221882

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by deads2k** [comment]
Don't we still want cookies when running in https?  Maybe this isn't doing what I think it's doing?

**Comment by liggitt** [comment]
Heh, yeah, bad name. HttpOnly removed the ability of JavaScript to access the cookies.

**Comment by deads2k** [comment]
The more you know.... [merge]

**Pull request merged**
