### PR TITLE
rules review endpoint for other user

### PR DESCRIPTION
**Pull request by mfojtik**
Original PR: https://github.com/openshift/origin/pull/10611

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k see the last three commits and feel free to cherry-pick to your branch or merge this ;-)

**Comment by mfojtik** [comment]
[test]

**Comment by deads2k** [comment]
lgtm.  free to merge on green

**Comment by mfojtik** [comment]
@deads2k can you check on your laptop the protobuf files? for some reason travis reports they are wrong

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@deads2k I think this is now good to merge (the flake was device mapper in conformance, the other tests passed).

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
