### PR TITLE
deploy: collapse deployer into deployments controller

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton I wasn't hot about finishing this but the thing is that the deployer pod controller currently uses its own pod and rc caches whereas the deployment controller is sharing, a possible source for races?

Closes https://github.com/openshift/origin/issues/9296

[test]

@ironcladlou @mfojtik fyi

### CODE REVIEW

**Comment by smarterclayton** [comment]
Change looks ok, why not delete the old code though?

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
I will remove the controller in a follow-up

**Comment by kargakis** [comment]
> I will remove the controller in a follow-up

Removed in a separate commit here

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/9129, [test]

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
@ironcladlou can you help me do a pass here?

**Comment by ironcladlou** [comment]
Will take a look

**Comment by ironcladlou** [comment]
This LGTM me too, more awesome work as usual. Is there any intent to do another level of collapsing of this into the deploymentConfigController (using the same strategy to enqueue DCs on RC update) or would that make the controller too unwieldy?

**Comment by kargakis** [comment]
> This LGTM me too, more awesome work as usual. Is there any intent to do another level of collapsing of this into the deploymentConfigController (using the same strategy to enqueue DCs on RC update) or would that make the controller too unwieldy?

I think we will always need the deployment controller and we may avoid precreating replica sets for upstream deployments, if we have a separate path in this controller that handles/tags appropriately those replica sets.

**Comment by kargakis** [comment]
@smarterclayton any other comment here? I will update the deployment controller to start retrying on update conflicts in a follow-up.

**Comment by smarterclayton** [comment]
No, [merge]

**Pull request merged**
