### PR TITLE
Rebase to Kube 0.14

### PR DESCRIPTION
**Pull request by smarterclayton**
@pweil- please see the commit on how ports have changed.

### CODE REVIEW

**Comment by smarterclayton** [comment]
So much rebase...

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Squash incoming

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@mfojtik / @bparees after this change lands someone needs to investigate osc build-logs (it's failing in the end-to-end tests).  It might be @derekwaynecarr's changes to require namespace to be specified interacting with the test, but I wasn't able to run it down in a short period of time.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
@pweil- if this doesn't merge tonight I'll need your help looking at TestRouter.  I'm seeing:

```
$ docker logs e0156da40fb3
I0410 05:35:04.312742       1 router.go:64] Commiting router changes
E0410 05:35:04.334364       1 router.go:131] Error reloading router: exit status 127
 Reload output: + config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ path_map_file=/var/lib/haproxy/conf/os_http_be.map
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ '[' -n '' ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid
/var/lib/haproxy/reload-haproxy: line 18: /usr/sbin/haproxy: No such file or directory
F0410 05:35:04.334429       1 router.go:45] exit status 127
```

in the docker logs when it tries to start haproxy, but don't know why.

**Comment by pweil-** [comment]
that is strange.  I pulled this PR locally, built the images, and ran the container.

```
[vagrant@openshiftdev origin]$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                CREATED             STATUS              PORTS               NAMES
023ee241b46b        openshift/origin-haproxy-router:ee831e7   "/usr/bin/openshift-   13 seconds ago      Up 12 seconds       80/tcp              sharp_lumiere       
[vagrant@openshiftdev origin]$ docker inspect 023ee | grep Pid
        "PidMode": "",
        "Pid": 7004,
[vagrant@openshiftdev origin]$ sudo nsenter -m -u -n -i -p -t 7004
[root@023ee241b46b /]# ll /usr/sbin/haproxy
-rwxr-xr-x. 1 root root 800656 Mar  6 00:30 /usr/sbin/haproxy
[root@023ee241b46b /]# 
```

**Comment by pweil-** [comment]
running hack/test-integration-docker.sh locally did show one issue for me.  The v1beta3 ns is not supported by the http master simulator correctly, it was only registering v1beta1 urls.  This fixes it for me.  

```
func (s *TestHttpService) startMaster() error {
	masterServer := http.NewServeMux()
	apis := []string{"v1beta1", "v1beta2", "v1beta3"}

	for _, version := range apis {
		masterServer.HandleFunc(fmt.Sprintf("/api/%s/endpoints", version), s.handleEndpointList)
		masterServer.HandleFunc(fmt.Sprintf("/api/%s/watch/endpoints", version), s.handleEndpointWatch)
		masterServer.HandleFunc(fmt.Sprintf("/osapi/%s/routes", version), s.handleRouteList)
		masterServer.HandleFunc(fmt.Sprintf("/osapi/%s/watch/routes", version), s.handleRouteWatch)
	}

	masterServer.HandleFunc("/", s.handleHelloMaster)

	if err := s.startServing(s.MasterHttpAddr, masterServer); err != nil {
		return err
	}

	return nil
}
```

```
ok      TestRouter
ok      TestRouterPathSpecificity
```

**Comment by pweil-** [comment]
Travis flaked on one run with a bind address already in use but the other two runs passed and jenkins passed as well in my test PR: https://github.com/openshift/origin/pull/1690

**Comment by smarterclayton** [comment]
Open a pull to my branch

**Comment by pweil-** [comment]
submitted

**Comment by bparees** [comment]
@smarterclayton what's the failure mode/error message for build-logs?

**Comment by smarterclayton** [comment]
It says build not found (even though it does).  It might be a namespace bug, or it could be a redirect bug.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
