### PR TITLE
Display OpenShift resources in `oc get` default info

### PR DESCRIPTION
**Pull request by smarterclayton**
Spawned kubernetes/kubernetes#15451 to make this generic

### CODE REVIEW

**Comment by kargakis** [comment]
LGTM [merge]

Fixes https://github.com/openshift/origin/issues/3981

@soltysh fyi we are carrying this UPSTREAM patch until  kubernetes/kubernetes#15451 gets fixed

**Comment by kargakis** [comment]
```
==================
WARNING: DATA RACE
Write by goroutine 14:
  sync.raceWrite()
      /usr/lib/golang/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /usr/lib/golang/src/sync/waitgroup.go:124 +0xf9
  net/http/httptest.(*Server).Close()
      /usr/lib/golang/src/net/http/httptest/server.go:168 +0x80
  github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory.TestCreateFromConfig()
      /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory_test.go:94 +0x644
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:456 +0xdc

Previous read by goroutine 21:
  sync.raceRead()
      /usr/lib/golang/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /usr/lib/golang/src/sync/waitgroup.go:66 +0xfa
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /usr/lib/golang/src/net/http/httptest/server.go:198 +0x5c
  net/http.serverHandler.ServeHTTP()
      /usr/lib/golang/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /usr/lib/golang/src/net/http/server.go:1361 +0x117c

Goroutine 14 (running) created at:
  testing.RunTests()
      /usr/lib/golang/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /usr/lib/golang/src/testing/testing.go:494 +0xe4
  main.main()
      github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/_test/_testmain.go:116 +0x384

Goroutine 21 (running) created at:
  net/http.(*Server).Serve()
      /usr/lib/golang/src/net/http/server.go:1910 +0x464
==================
E1012 09:45:44.218992   30942 factory.go:280] Error scheduling bar foo: <nil>; retrying
PASS
coverage: 75.9% of statements
Found 1 data race(s)
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory	1.065s
```
Race in the upstream test factory, irrelevant to this PR. I'll report this upstream or send a PR.

re[merge]

**Comment by kargakis** [comment]
> Race in the upstream test factory, irrelevant to this PR. I'll report this upstream or send a PR.

Ok, this is a race in the go stdlib:
https://github.com/golang/go/issues/12789
https://github.com/golang/go/issues/12781

**Comment by kargakis** [comment]
re[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/5025 flake

[merge]

**Comment by liggitt** [comment]
[test]

**Pull request merged**
