### PR TITLE
Fix race in imageprogress test

### PR DESCRIPTION
**Pull request by csrwng**
Fixes potential problem with simultaneous write in unit test by using a mutex.

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
@smarterclayton fyi

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
test hit flake from #9444

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/4351
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9548
[merge]

**Comment by csrwng** [comment]
flake #9683 
[merge]

**Pull request merged**
