### PR TITLE
test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[testextended][extended:core(templates)]

**Comment by bparees** [comment]
@stevekuznetsov reproducing the multiple extended tests issue here.  I don't immediately see how https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended.yml#L18-L24 is related to the issue i'm observing.

**Comment by bparees** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Oh. Yeah. The job would often time out when doing this anyway as it would chain the two together. We should document somewhere that this isn't supported anymore.

**Pull request closed without merging**
