### PR TITLE
Bug 1861214: test: network: unskip endpoint slices

### PR DESCRIPTION
**Pull request by aojea**
unskip the test
[sig-network] EndpointSliceMirroring should mirror a custom Endpoints resource through create update and delete

### CODE REVIEW

**Comment by aojea** [comment]
The test is passing, this should be good to go,  ping @marun 

/retest
can't understand the `ci/prow/e2e-cmd — Job failed.` though

**Comment by marun** [comment]
@aojea e2e-cmd is known flakey, and anyway is not required to merge (see lack of 'Required' button).

**Comment by marun** [comment]
/hold

Please close, I'm unskipping as part of the 1.19 rebase.

**Comment by aojea** [comment]
> /hold
> 
> Please close, I'm unskipping as part of the 1.19 rebase.

/Close

**Pull request closed without merging**
