### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rhcarvalho**
1. gitghub -> github
2. if you're using vagrant, then <username> = openshift

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@mfojtik one more simple fix, PTAL

**Comment by mfojtik** [comment]
@rhcarvalho another hit from typokiller? :D

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by rhcarvalho** [comment]
@mfojtik Found with visual inspection this time... with some free time or contribution we could add a web UI to typokiller and leave it running against origin@master :)

**Pull request merged**
