### PR TITLE
deal with RawPath field added to url.URL in go1.5

### PR DESCRIPTION
**Pull request by gabemontero**
fixes https://github.com/openshift/origin/issues/6455

@liggitt @rhcarvalho PTAL

@bparees FYI (and of course TAL if you like :-) )

### CODE REVIEW

**Comment by rhcarvalho** [comment]
I'd prefer to ditch the `reflect.DeepEqual` and use a single `if got.Scheme != want.Scheme || got.Host != want.Host || got.User.Username() != want.User.Username() || got.Path != want.Path`, with a note that the URL struct differs between 1.4 and 1.5 so we cannot use DeepEqual as long as we support go1.4.

**Comment by rhcarvalho** [comment]
```go
// Compare only the url.URL fields we're interested in instead of using
// reflect.DeepEqual, because the url.URL struct has different fields in go1.4
// and go1.5.
if got.Scheme != want.Scheme || got.Host != want.Host || got.User.Username() != want.User.Username() || got.Path != want.Path {
	t.Errorf("%s: got %#v, want %#v", scenario, *got, want)
}
```

wdyt?

**Comment by bparees** [comment]
Agree, my brain hurts reading that existing if check between the go-version and the things it's comparing, if we know what we care about (and it's not an obscene nested structure) let's just check it directly and call it a day.

**Comment by gabemontero** [comment]
ok cool - I had only kept the DeepCopy stuff because I assume there would be pressure from reviewers to keep it since we converted to that originally;

glad I overthought and we can switch back to the field by field compare

changes pushed

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
The go unit test which this PR addresses passed in the merge job:

`ok  	github.com/openshift/origin/pkg/generate/git	0.026s	coverage: 29.2% of statements`

The merge job failed later on in hack/../test/cmd/newapp.sh, which is unrelated to this change.

Can we either re-hit the merge button or force the merge?

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8337/ had basically the same results as last time;  the git unit test addressed by this PR still passes, but one of the newapp cmd tests unrelated to this test fails.

merge queue needs cleaning up ..

**Comment by bparees** [comment]
[merge]

**Comment by deads2k** [comment]
re[merge]

**Comment by bparees** [comment]
@deads2k ?

**Comment by deads2k** [comment]
> @deads2k ?

didn't pay attention and just went through the process pull request job.

also [test]

**Pull request merged**
