### PR TITLE
Bug 1268000 - replace Image.DockerImageReference with value from status.

### LINKED ISSUE #5481: Proposal to add DockerImageReference to ImageStreamTag
This idea came from tackling https://bugzilla.redhat.com/show_bug.cgi?id=1268000. The general flow is as follows: 
1. Image import controller imports images in non-deterministic order, which for v1 registries with multiple tags pointing to the same id means, that the first seen image will be imported, all the others will always point to this one. This also means that the `Image.DockerImageReference` will always point to that first imported image.
2. First build occurs, triggered by ConfigChange trigger, this build saves the `DockerImageReference` returned from `Image.DockerImageReference` (`GetImageStreamTag` call in `generator.go`).
3. ImageChange controller notices change to ruby:2.0 image, resolves that, but since it's reading straight from stream, it uses `LatestTaggedImage(stream, tag)` which returns `TagEvent` which has `DockerImageReference` that might be different from `Image.DockerImageReference` from 1 and might sometimes trigger the 2nd build. Usually the `DockerImageReference` in `TagEvent` is similar to what was specified in image spec.

There are two solutions to this problem:
1. Rework `resolveImageStreamReference` so that for `ImageStreamTag` it reads the stream and then uses `LatestTaggedImage(stream, tag)` to get the same value we do in ImageChange controller (step 3).
2. Extend `ImageStreamTag` with `DockerImageReference`, especially that under the cover (see [imagestreamtag.Get](https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L64) is using `LatestTaggedImage(stream, tag)` and has that information.

My preference, as the title points to, is no 2. Because this will also fix the problem of getting proper information when doing `oc get istag/ruby:2.0`. Additionally we'll have consistent behavior all over the places. The former solution is a quick fix for this particular place and not the whole problem. When I was talking to @ncdc he also mentioned removing (or at least trying to) `Image.DockerImageReference` field, which the latter could help with. This would also allow better address the problem in #5391 where we return 404 for tags that are references. We could return empty image, but still provide valid metadata information about it.

@miminar @ncdc @bparees @smarterclayton opinions?

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #5481 and https://bugzilla.redhat.com/show_bug.cgi?id=1268000.

@miminar @ncdc ptal

### CODE REVIEW

**Comment by liggitt** [comment]
will this break the way we are using this field's value to correlate image streams with deployments in https://github.com/openshift/origin/blob/master/assets/app/scripts/services/imageStreamResolver.js#L58

cc @jwforres

**Comment by ncdc** [comment]
See my comment here: https://github.com/openshift/origin/issues/5481#issuecomment-152302608

**Comment by miminar** [comment]
LGTM. [#5481 (comment)](https://github.com/openshift/origin/issues/5481#issuecomment-152302608) seems covered to me.

**Comment by soltysh** [comment]
I don't see any more objections.
[merge]

**Comment by soltysh** [comment]
I've rebased the PR, because the error:
```
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/pkg/image/registry/imagestreamtag
_output/local/go/src/github.com/openshift/origin/pkg/image/registry/imagestreamtag/rest.go:133: undefined: imageWithMetadata
_output/local/go/src/github.com/openshift/origin/pkg/image/registry/imagestreamtag/rest.go:133: cannot assign to imageWithMetadata.DockerImageReference
_output/local/go/src/github.com/openshift/origin/pkg/image/registry/imagestreamtag/rest.go:133: undefined: event
```
completely doesn't make sense to me. It looked as if local merge failed along the way.

**Comment by soltysh** [comment]
Previous rebase for some reason didn't picked up the changes, this finally does.

**Comment by soltysh** [comment]
integration test failure, which I forgot about to check before :/

**Pull request merged**
