### PR TITLE
Bug 1939232: Update tests to use Ruby 2.7

### PR DESCRIPTION
**Pull request by vrutkovs**
Ruby 2.5 is EOL and would be removed in the next round of cluster-samples-operator updates.

Related to https://github.com/openshift/cluster-samples-operator/pull/360

TODO:
* [x] https://github.com/openshift/ruby-hello-world/pull/121 to use Ruby 2.7 in sample git repo

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @bparees 

e2e-gcp-builds is passing here since the changes I noted in https://github.com/openshift/builder/pull/222#issuecomment-796920855 are present

**Comment by gabemontero** [comment]
technically the failing jobs are not required, and CI has been a bit unhealthy today, but let's try them more before skipping

my guess here is that this PRs changes at most might have bearing on e2e-agnostic-cmd, as some of the oc cmd line test are build related and historically like to use ruby

/retest

**Comment by vrutkovs** [comment]
`e2e-agnostic-cmd` fails with
```
executing 'oc get imagestreamtags ruby:2.7' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out\nStandard output from the command:\nStandard error from the command:\nError from server (NotFound): imagestreamtags.image.openshift.io \"ruby:2.7\" not found\n...
```
Not sure why, OCP's samples operator should have imported it

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/retitle Bug 1939232: Update tests to use Ruby 2.7

**Comment by gabemontero** [comment]
image-eco hit `   * could not run steps: step e2e-gcp-image-ecosystem failed: failed to acquire lease: resources not found `

**Pull request merged**
