### PR TITLE
UPSTREAM: drop: Add extra logs for flake analysis

### PR DESCRIPTION
**Pull request by jsafrane**
Trying to debug https://bugzilla.redhat.com/show_bug.cgi?id=1698829

@wongma7, PTAL

It does extra DescribeInstances after detach, otherwise it just logs stuff and does not prevent the bug in any way.

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
thx

**Comment by wongma7** [comment]
/lgtm
just commit msg i see

**Comment by jsafrane** [comment]
Yes, Travis is now happy

**Comment by wongma7** [comment]
oof, test failing for now because of https://bugzilla.redhat.com/show_bug.cgi?id=1699469.

I ran the statefulset test myself for a couple hours today and didn't see it fail once either. I guess things need to happen in parallel for it to fail. most of the time the 3 pods get scheduled 1 to each worker.

**Comment by jsafrane** [comment]
@wongma7, this is embarrassing, but we don't log level 4 in e2e tests :-(. I got 37 occurrences of "assignment call for already-assigned volume" since this was merged, but all of them are useless.

PR will follow shortly.

**Pull request merged**
