### PR TITLE
move more integration tests to e2e

### PR DESCRIPTION
**Pull request by deads2k**
The tests are all moves.

/assign @stlaz

### CODE REVIEW

**Comment by deads2k** [comment]
Mo thought it was fine in person.

**Comment by sallyom** [comment]
@deads2k this fails for me locally, hm.. 
```
Failing tests:

[Feature:UserAPI] users can manipulate groups [Suite:openshift/conformance/parallel]
```

**Comment by deads2k** [comment]
@sallyom can you provide failure details. It's likely to be an interaction and details will help find it. I'm betting it's running multiple times and not cleaning up

**Comment by deads2k** [comment]
made names unique to avoid flakes.  Retagging.

**Pull request merged**
