### PR TITLE
[release-4.6] Bug 1900991: test/extended/router: add idle/unidle e2e test

### PR DESCRIPTION
**Pull request by frobware**
This is a manual backport of PR #25850.

An explicit test to assert that a service that is idled will be
unidled when a GET request occurs on the route.

### CODE REVIEW

**Comment by frobware** [comment]
This will fail in CI until the following merge:

- https://github.com/openshift/oc/pull/727
- https://github.com/openshift/openshift-apiserver/pull/183
- https://github.com/openshift/openshift-controller-manager/pull/167
- https://github.com/openshift/origin/pull/25855

**Review by knobunc — APPROVED** [review]

**Comment by frobware** [comment]
/hold

Working out which of the following is not present:

- openshift/oc#727
- openshift/openshift-apiserver#183
- openshift/openshift-controller-manager#167

**Comment by bparees** [comment]
i'm approving, but please keep an eye on the tests on this PR, if it doesn't pass and merge i'll have to remove the CPA label at the end of the week.

(and of course if the tests that are failing are introduced/modified by this PR, that warrants further investigation)

**Comment by frobware** [comment]
> i'm approving, but please keep an eye on the tests on this PR, if it doesn't pass and merge i'll have to remove the CPA label at the end of the week.
> 
> (and of course if the tests that are failing are introduced/modified by this PR, that warrants further investigation)

This will continue to fail until https://github.com/openshift/router/pull/253 merges.

**Comment by bparees** [comment]
> This will continue to fail until openshift/router#253 merges.

ok, that one's been approved so hopefully it goes in soon.

**Pull request merged**
