### PR TITLE
bug 1784848: fix up ruby-25-centos7 tag check logic

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by adambkaplan** [comment]
off to the races with #24319

**Comment by smarterclayton** [comment]
why did this break?

**Comment by bparees** [comment]
> why did this break?

SCL team pushed new tags to the repository, so our very loose regex checking started failing when the imagestream imported more tags than we expected.

**Comment by wking** [comment]
#24319 has landed, and this PR already reverts its changes :heavy_check_mark: 

[unit][1] failed.  Error from [here][2] looks like a panic:

```
=== RUN   TestYAMLLimits/3MB_map_with_alias/utilyaml
coverage: 0.0% of statements
panic: test timed out after 3m0s

goroutine 70 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc000124000, 0xaf50f5, 0xe, 0xb12358, 0x0)
	/usr/local/go/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc000124000)
	/usr/local/go/src/testing/testing.go:1202 +0xa7
testing.tRunner(0xc000124000, 0xc000113cd8)
	/usr/local/go/src/testing/testing.go:909 +0x19a
testing.runTests(0xc00000e560, 0xf099d0, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x522
testing.(*M).Run(0xc00002a380, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x300
main.main()
	_testmain.go:94 +0x338

goroutine 6 [chan receive]:
github.com/openshift/origin/vendor/k8s.io/klog.(*loggingT).flushDaemon(0xf16180)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/klog/klog.go:1018 +0xae
created by ...
...
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24322/pull-ci-openshift-origin-master-unit/11220
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24322/pull-ci-openshift-origin-master-unit/11220/artifacts/unit/unit_report_CCxnP.xml

**Comment by bparees** [comment]
> unit failed. Error from here looks like a panic:

@wking i don't think that has to do w/ this PR, do you?

**Comment by mfojtik** [comment]
/hold

The number of changes in bindata seems off? Can we confirm it has the right data? Feel free to un-hold if yes.

**Comment by bparees** [comment]
bindata fixed
/hold cancel

**Pull request merged**
