### PR TITLE
Add test to detect config changes

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

/cc @sdodson @detiber this test will notify anyone who adds things to config that they need to file issues for doc and install.

**Comment by deads2k** [comment]
Necessary, but not sufficient.  We need to make sure that a mostly operational server starts up from config produced at earlier levels.

@danmcp How frequently do we run the extended tests and exactly which script/scripts are called?

**Comment by deads2k** [comment]
Still, it's a start.  [merge]

**Comment by liggitt** [comment]
> Necessary, but not sufficient. We need to make sure that a mostly operational server starts up from config produced at earlier levels.

Agree, on my list to do eventually... that'll be in the other direction, take a snapshot of "final" v1 config output, load and validate it, or something similar

**Comment by danmcp** [comment]
@deads2k Not sure.  I am not sure there is any process in place there yet.  I know @mfojtik worked on it a while back.

**Pull request merged**
