### PR TITLE
UPSTREAM: 69890: Run static pods before bootstrap

### PR DESCRIPTION
**Pull request by smarterclayton**
Perform bootstrapping in the background when client cert rotation is on,
enabling static pods to start before a control plane is reachable.

Argument that we enable this in master now for testing and to allow the installer to start consuming it.  We then backport it to 1.12 when the rebase lands.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@aaronlevy @crawford @deads2k @sjenning this has been tested manually pretty well.  since we haven't rebased to 1.12 yet, we could merge this and then update the installer - allowing us to use static pods even if bootstrapping while the master is down (I tested on a one node master cluster).  the delta for a 1.12 backports is pretty small, so it's a low risk carry for us to develop against while we finish out the upstream.  At worst, we just get extra testing.  So I'd probably say we should merge even assuming it changes some upstream, assume that we can carry it throughout 4.0 if necessary, and then hopefully have it in 1.13.

/retest

**Comment by deads2k** [comment]
> @aaronlevy @crawford @deads2k @sjenning this has been tested manually pretty well. since we haven't rebased to 1.12 yet, we could merge this and then update the installer - allowing us to use static pods even if bootstrapping while the master is down (I tested on a one node master cluster). the delta for a 1.12 backports is pretty small, so it's a low risk carry for us to develop against while we finish out the upstream. At worst, we just get extra testing. So I'd probably say we should merge even assuming it changes some upstream, assume that we can carry it throughout 4.0 if necessary, and then hopefully have it in 1.13.

Yeah, it makes sense for us to do this.

**Comment by smarterclayton** [comment]
Crio is super flaky.  I’m going to spawn issues for it, but for now I’m going to merge to unblock static pods

**Pull request merged**
