### PR TITLE
UPSTREAM: 32222: print resource kind prefix on single resource type

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/32222
Fixes: https://github.com/openshift/origin/issues/10839

This patch forces the HumanReadablePrinter to display resource kind
prefixes when there is only one type of resource to show and a specific
resource type has not been specified as an argument to `oc get`

##### Before
`$ oc get all`
```
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)                 AGE
kubernetes   172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   2m
```

##### After
`$ oc get all`
```
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)                 AGE
svc/kubernetes   172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   2m
```

@openshift/cli-review @jwforres

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by fabianofranz** [comment]
LGTM

**Comment by juanvallejo** [comment]
@fabianofranz PTAL

**Comment by fabianofranz** [comment]
[merge]

**Comment by juanvallejo** [comment]
merge [conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6310/) test flaked on https://github.com/openshift/origin/issues/10951

**Comment by juanvallejo** [comment]
[conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6340/) test flaked on https://github.com/openshift/origin/issues/10773 re[test]

**Comment by juanvallejo** [comment]
[conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6349/) test flaked on https://github.com/openshift/origin/issues/9548
[integration](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/6232/) test flaked on https://github.com/openshift/origin/issues/11058
re[test]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
