### PR TITLE
Correcting colspan value to resolve cosmetic bug with missing right b…

### LINKED ISSUE #7769: Routes table header missing right border
openshift_web_console

Also the Create Route button no longer aligns with the right edge of the table. (Could be related to #7736.)

/cc @jwforres @sg00dwin @rhamilto

### PR DESCRIPTION
**Pull request by rhamilto**
…order on <thead>

Resolves #7769 

@spadgett, review and merge, please.

### CODE REVIEW

**Comment by rhamilto** [comment]
screen shot 2016-03-03 at 2 56 49 pm

**Comment by rhamilto** [comment]
Oops.  Hold, please.  I missed the second part about the button.  Fixing now...

**Comment by rhamilto** [comment]
Ok, @spadgett.  Both issues should now be fixed.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
