### PR TITLE
Implement deployment hooks

### PR DESCRIPTION
**Pull request by ironcladlou**
This PR implements [deployment hooks](https://github.com/openshift/origin/blob/master/docs/proposals/post-deployment-hooks.md), and replaces the now defunct #1456.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@pmorie @smarterclayton 

There's still polish, tests, and docs to work through, but you should be able to get a good idea of where this is going.

**Comment by ironcladlou** [comment]
[test] out of curiosity

**Comment by smarterclayton** [comment]
structurally this looks fine to me.

**Comment by ironcladlou** [comment]
@smarterclayton @pmorie this is ready for an in-depth review.

**Comment by smarterclayton** [comment]
Can you add an extended test or this to the e2e scenario?

**Comment by ironcladlou** [comment]
@smarterclayton 
>Can you add an extended test or this to the e2e scenario?

Working through that now.

**Comment by ironcladlou** [comment]
e2e coverage for pre and post hook is in and works okay.

**Comment by ironcladlou** [comment]
Documentation in progress: https://github.com/openshift/openshift-docs/pull/296

**Comment by smarterclayton** [comment]
Paul can you do a review?  I don't have any substantial questions.

**Comment by smarterclayton** [comment]
Does this require us to give the deployer additional permissions?

**Comment by ironcladlou** [comment]
>Does this require us to give the deployer additional permissions?

Apparently not. The deployer's a pod in the same namespace as the DC, and it already has permission to create other pods in the same namespace.

**Comment by smarterclayton** [comment]
@deads2k intentional?

----- Original Message -----

**Comment by deads2k** [comment]
@smarterclayton We have a separate deployer role, but we haven't tied down permissions.  Right now, system:deployers have * on *.

**Comment by pmorie** [comment]
@ironcladlou almost LGTM.  It looks like the recreate strategy tests should be making more detailed checks on the state of RCs passed to `Update` instead of just testing that an RC was passed to `Update` (or not).

**Comment by ironcladlou** [comment]
>@ironcladlou almost LGTM. It looks like the recreate strategy tests should be making more detailed checks on the state of RCs passed to Update instead of just testing that an RC was passed to Update (or not).

As discussed in chat: The existing recreate tests make assertions on replica counts (the only state the strategy mutates).

**Comment by pmorie** [comment]
LGTM

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
