### PR TITLE
better build names

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton this isn't using GenerateName because the Rest endpoint isn't setup to do all the BeforeCreate logic to process and use GenerateName like the k8s Rest endpoints are.  It was either this, or do significant rework of the existing Build REST endpoint to make it more closely follow the k8s pattern.  Given the other REST refactor work you mentioned coming, i opted for this path for now.

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
That's fine

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by brenton** [comment]
fyi, It seemed like this broke sti builds in my environment.  I'll file an issue shortly with details.

**Comment by brenton** [comment]
Hmm... things seem to be working now.  Carry on...

**Pull request merged**
