### PR TITLE
[sig-arch][Late] operators should not create watch channels very often [Suite:openshift/conformance/parallel]

### PR DESCRIPTION
**Pull request by ingvagabund**
Measure the amount of watch requests per operator per bucket and upper bound it in case
an operator introduces an error leading to opening too many watch requests in short time.

https://issues.redhat.com/browse/WRKLDS-291

### CODE REVIEW

**Comment by ingvagabund** [comment]
From `pull-ci-openshift-origin-master-e2e-gcp`:
```
[36mINFO[0m[2021-06-07T13:22:33Z] passed: (1.9s) 2021-06-07T13:20:00 "[sig-arch][Late] operators should not create watch channels very often [Suite:openshift/conformance/parallel]" 
```

**Review by soltysh — APPROVED** [review]
My only worry is keeping those upper bounds up-to-date, especially that they are very granular (per platform). I'd like to have 2nd pair of eye on it.
/lgtm
/approve
/hold
/assign @deads2k

**Comment by soltysh** [comment]
Spoke with David on slack
/hold cancel

**Comment by deads2k** [comment]
Having a cap on the number of requests made by parts of the payload is important. We cut the number by 20% in 4.8.  A test that keeps us from getting worse is a good idea.

I haven't reviewed this implementation, but current state plus a percentage is a good starting point.  It may eventually be necessary to phrase it as qps in some way.

**Pull request merged**
