### PR TITLE
TRT-1493: Add monitortest for cloud function on aws

### PR DESCRIPTION
**Pull request by DennisPeriquet**
TODO:

- [x] Ensure metal sdn test does not have disruption (this test should be skipped on metal)
- [x] Confirm 3 non-metal jobs have 0s disruption on aws-network-liveness

Hit an endpoint (on a VM behind a load-balancer in aws) to test aws connectivity during test runs in a way that (attempts to) mimic pods in an Openshift cluster.  This way we can compare disruption problems noted in TRT-1466.

Here's a test to see if the LB is working on AWS (should return 200):

```bash
url=http://trt-openshift-tests-endpoint-lb-1161093811.us-east-1.elb.amazonaws.com/health
echo $(curl -sk -w "%{http_code}" -o response.txt -H "Audit-ID: 12345" "$url")
```

The VM/LB has been up for days in the TRT aws account:

```
$ date
Sun Feb 18 19:28:25 EST 2024
$ url=http://trt-openshift-tests-endpoint-lb-1161093811.us-east-1.elb.amazonaws.com/health
$ echo $(curl -sk -w "%{http_code}" -o response.txt -H "Audit-ID: 12345" "$url")
200
```

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
/hold

Until problems in https://issues.redhat.com/browse/TRT-1522 are resolved, this PR is not to merge.

**Comment by dgoodwin** [comment]
/lgtm

With A29y on this wouldn't be anything I'd consider critical, however you are watcher next week so feel free to label if you'd like it to go in.

**Pull request merged**
