### PR TITLE
[DO NOT MERGE] Run SDN after Proxy to ensure correct bridge-nf-call-iptables value

### PR DESCRIPTION
**Pull request by dcbw**
https://bugzilla.redhat.com/show_bug.cgi?id=1294061

### CODE REVIEW

**Comment by dcbw** [comment]
[testonlyextended][extended:networking]

**Comment by liggitt** [comment]
Aren't all of those async? Changing the order doesn't seem like it would reliably fix the issue.

**Comment by dcbw** [comment]
@liggitt The pieces of SDN and the Proxy that are in conflict are actually synchronous.

**Comment by dcbw** [comment]
[test][extended]

**Comment by dcbw** [comment]
@liggitt I've got another openshift-sdn bump to fix one issue that I found while fixing this, but I want to make sure the reorder passes all the tests before I submit that openshift-sdn bump with this PR.  And unfortunately we need sort out https://github.com/openshift/origin/pull/6684 first.

**Comment by eparis** [comment]
I (double) checked and the two calls are definitely in synchronous code paths. Assuming this tests out ok, it LGTM.

**Comment by dcbw** [comment]
extended test failure appears to be a flake:

panic: test timed out after 1m0s

goroutine 43 [running]:
testing.func·008()
	/usr/lib/golang/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x19b2d60, 0x204b260, 0x2, 0x2, 0xc208059e01)
	/usr/lib/golang/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208179720, 0x2a015e0)
	/usr/lib/golang/src/testing/testing.go:485 +0xe1
main.main()
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_testmain.go:126 +0x382

goroutine 9 [syscall, 1 minutes]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x43

goroutine 42 [runnable]:
math/big.nat.norm(0xc2084c5400, 0x11, 0x25, 0xc20818b0e0, 0x21, 0x24)
	/usr/lib/golang/src/math/big/nat.go:61
math/big.nat.divLarge(0xc2084c5400, 0x10, 0x25, 0xc20818b0e0, 0x21, 0x24, 0xc20818afc0, 0x20, 0x24, 0xc2082ee000, ...)
	/usr/lib/golang/src/math/big/nat.go:594 +0xfa0
math/big.nat.div(0xc2084c5400, 0x10, 0x25, 0xc20818b0e0, 0x20, 0x24, 0xc20818afc0, 0x20, 0x24, 0xc2082ee000, ...)
<etc>

which looks like our AWS instances just take too long to run crypto/rsa.GenerateMultiPrimeKey()

**Comment by dcbw** [comment]
[test][extended]

**Comment by dcbw** [comment]
It turns out re-ordering isn't safe for the multitenant plugin, so we'll work around this another way.

**Comment by dcbw** [comment]
@danwinship will take it from here with a different patch.

**Pull request closed without merging**
