### PR TITLE
Bump openshift-sdn

### PR DESCRIPTION
**Pull request by rhcarvalho**
Related to  #8454.

@kargakis PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
You might hold on this till the rebase lands.

**Comment by kargakis** [comment]
merging in a while...

**Comment by rhcarvalho** [comment]
no problem with waiting, the changes are coming from a PR that merged just now, so it won't be in the rebase (the previous version was just prior to my PR in openshift-sdn).

**Comment by smarterclayton** [comment]
Failing verify

**Comment by rhcarvalho** [comment]
> Failing verify

Oh, I saw it failed to verify generated docs, I didn't imagine the generated docs depended on code from Godeps.

Updated.

**Comment by smarterclayton** [comment]
[test]

**Comment by rhcarvalho** [comment]
ping, green tests :)

**Comment by kargakis** [comment]
@mfojtik I think this doesn't affect your rebase, does it?

**Comment by mfojtik** [comment]
yeah, I will pick this for the rebase

**Comment by rhcarvalho** [comment]
All this is doing is removing the '$ ' from CLI examples in openshift-sdn... how is it related to the rebase?

**Comment by rhcarvalho** [comment]
ping

**Comment by soltysh** [comment]
@rhcarvalho fix it in openshift-sdn repo. @mfojtik will be bumping the sdn after the reabse and he'll pick your changes then.

**Comment by rhcarvalho** [comment]
@soltysh that was the easy part, done and merged 11 days ago...
https://github.com/openshift/openshift-sdn/pull/308

Apart from bumping, it's also necessary to update the generated docs.

**Comment by soltysh** [comment]
@rhcarvalho our update all should make that work, and even if @mfojtik forgets that verify should catch it.

**Comment by rhcarvalho** [comment]
Superseded by #9014.

**Pull request closed without merging**
