### PR TITLE
Handle null items array from bad api responses

### PR DESCRIPTION
**Pull request by jwforres**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1331324

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

fyi @smarterclayton we'll handle the incorrect api cleanly, dont trust random third party resources to not make the same mistake

**Comment by jwforres** [comment]
test failure was just the AWS flake [test]

**Comment by jwforres** [comment]
Image import timeout [merge]

**Comment by jwforres** [comment]
and aws failure [merge]

**Comment by jwforres** [comment]
Aws again [merge]

**Comment by jwforres** [comment]
Seriously, [merge] already

**Comment by jwforres** [comment]
... [merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
