### PR TITLE
UPSTREAM: 23078: Check claimRef UID when processing a recycled PV

### PR DESCRIPTION
**Pull request by swagiaal**
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1310587

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by swagiaal** [comment]
[test]

**Comment by swagiaal** [comment]
[test]

**Comment by ncdc** [comment]
This has NOT merged upstream yet

**Comment by ncdc** [comment]
Upstream has merged.

**Comment by ncdc** [comment]
@liggitt merge?

**Comment by ncdc** [comment]
Need to fix a potential issue w/the upstream PR. Once that's ready, I'll close this and submit a replacement.

**Comment by swagiaal** [comment]
@ncdc whats the issue upstream ?

**Comment by liggitt** [comment]
the code assumes a non nil claim is usable without checking if there is a non nil error

**Comment by swagiaal** [comment]
> the code assumes a non nil claim is usable without checking if there is a non nil error

Hmm.. I don't think I follow

**Comment by ncdc** [comment]
@swagiaal with this patch the way it's currently coded, you could potentially get back an error that isn't "not found" and a non-nil claim. It's more appropriate to do this:

1. If we got an error and it's not a "not found" error, return the error
2. Otherwise, if the error we got was "not found" or the claim's UID is different, make the volume available again

See https://github.com/kubernetes/kubernetes/pull/23548 for what I did

**Comment by ncdc** [comment]
LGTM. @smarterclayton merge?

**Comment by smarterclayton** [comment]
Do you approve?

**Comment by ncdc** [comment]
Yes. @childsb please sign off.

**Comment by childsb** [comment]
looks good, added the LGTM label

**Comment by smarterclayton** [comment]
Approved [merge]

**Pull request merged**
