### PR TITLE
Update hello-openshift OWNERS files

### PR DESCRIPTION
**Pull request by sgreene570**
`images/hello-openshift/OWNERS`: Add initial owners for the `hello-openshift` art dockerfile. This owners file is a copy-paste of the current `examples/hello-openshift/OWNERS` file (with the addition of myself). 

`examples/hello-openshift/OWNERS`: Add myself to the `hello-openshift` code maintainers OWNERS file.

/cc @wking @yselkowitz

### CODE REVIEW

**Comment by yselkowitz** [comment]
I don't actually work on OpenShift full time so I probably shouldn't be listed.

**Comment by sgreene570** [comment]
> I don't actually work on OpenShift full time so I probably shouldn't be listed.

ack, thanks for fyi.

**Comment by yselkowitz** [comment]
It really shouldn't be this hard to update OWNERS...
/retest

**Pull request merged**
