### PR TITLE
Fix reuse of release build on nfs mount

### PR DESCRIPTION
**Pull request by marun**
hack/build-go.sh attempts to use release archives if they are present,
but untarring on an nfs mount requires that the --no-same-owner flag be
used to prevent tar from trying to change ownership on extracted
files (which can fail even for root on nfs).

### CODE REVIEW

**Comment by marun** [comment]
cc: @smarterclayton @liggitt

**Comment by smarterclayton** [comment]
Will need to be rebased on top of #7080

**Comment by marun** [comment]
@smarterclayton rebased

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
