### PR TITLE
Various idiomatic fixes throughout the repo

### PR DESCRIPTION
**Pull request by kargakis**
Contains:
    * Comment fixes
    * Variable renaming
    * Grouping of imports into logical groups (stdlib, 3rd party, openshift)
    * makes golint a bit happier overall

### CODE REVIEW

**Comment by smarterclayton** [comment]
Maybe got bit by a compilation change?  Client reference isn't there.

**Comment by kargakis** [comment]
I have removed the markdown stuff since the original code has been slightly edited in another commit.

**Comment by smarterclayton** [comment]
Great, will merge this as soon as we cut 0.2.3

**Comment by kargakis** [comment]
Rebased on current master and did a bit more imports grouping

**Comment by smarterclayton** [comment]
LGTM [merge] thanks!

**Pull request merged**
