### PR TITLE
Use cmdutil.PrintSuccess to print objects

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton wasn't this the one you didn't want to change because it rippled into docs?

`oc start-build`

**Comment by smarterclayton** [comment]
Yes.  Not a 3.1 change and we have to support old behavior.

**Comment by fabianofranz** [comment]
@smarterclayton Ok, meaning we should only go through commands that *already* support `--output` for now?

**Comment by smarterclayton** [comment]
Yes

**Comment by fabianofranz** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
