### PR TITLE
change default bulk image import from 5 to 50

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton `make update` isn't updating `pkg/cmd/server/apis/config/v1/swagger_doc.go`  is there some trick?

**Comment by simo5** [comment]
On Wed, 2018-05-16 at 12:26 -0700, Ben Parees wrote:
> @smarterclayton make update isn't updating
> pkg/cmd/server/apis/config/v1/swagger_doc.go is there some trick?

make update-api

HTH,
Simo.

**Comment by bparees** [comment]
@simo5 oddly this passed the verify test as is....  would have expected it to complain?

**Comment by smarterclayton** [comment]
I would have expected it to complain as well.

**Comment by bparees** [comment]
`make update-api` didn't generate any additional changes..perhaps something has bit-rotted?

**Comment by simo5** [comment]
Ah I guess for the comment change...

**Comment by bparees** [comment]
> Ah I guess for the comment change...

yes

**Comment by bparees** [comment]
@smarterclayton do you want this in 3.10?

**Comment by bparees** [comment]
@smarterclayton still care about this?

**Pull request merged**
