### PR TITLE
rebase to kube 1.11 GA

### PR DESCRIPTION
**Pull request by deads2k**
Creepy. no changes.

### CODE REVIEW

**Comment by deads2k** [comment]
@liggitt pkg/api tests look suspicious since we went to jsoniter

**Comment by deads2k** [comment]
note to self, test-integration is probably failing on the both namespaced and not removal. Try to push through instead of repicking.

**Comment by deads2k** [comment]
another note to self, default GC quota list

**Comment by liggitt** [comment]
> @liggitt pkg/api tests look suspicious since we went to jsoniter

hmm, yes, those are exactly the things ugorji let in before that bit us when we tried to drop it. I had forgotten, but past me was mean enough to add tests to not let me forget. This requires more thought on what the best path out of this mess is.

**Comment by deads2k** [comment]
verify `Container test exited with code 2, reason OOMKilled`

/retest

**Comment by deads2k** [comment]
Only change is Jordan's.  Tagging

**Comment by deads2k** [comment]
@smarterclayton I've got one more critical backwards compatibility fix that I'll finish tomorrow and you'll be good to upgrade

**Pull request merged**
