### PR TITLE
Change godep path

### PR DESCRIPTION
**Pull request by deads2k**
I need this as a pre-step to the rebase to avoid merge conflicts on virtually every updated file.

@danmcp @smarterclayton I think we'll need to stop the merge queue for this.  I can't get consistent test runs with anything merging that has kube imports and I'll have to rebase it on the latest in master.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by ncdc** [comment]
Merge queue temporarily disabled

**Comment by deads2k** [comment]
> wha? was this a bug before?

Yes.  The name got reassigned during the repack, but kube packages were first alphabetically.

**Comment by liggitt** [comment]
actually reviewed, LGTM

**Comment by deads2k** [comment]
[vipmerge]!

**Comment by smarterclayton** [comment]
I'm glad we can bring such joy to your life.

On Wed, Aug 12, 2015 at 9:51 AM, OpenShift Bot <notifications@github.com>
wrote:

> Merged #4121 <https://github.com/openshift/origin/pull/4121>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4121#event-380325478>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request merged**
