### PR TITLE
Validate clusterquota status totals

### PR DESCRIPTION
**Pull request by liggitt**
based on #11621

wanted to open separately since I'm not positive what tightening this will do to existing CRQs with invalid status. does the reconciler recompute the total or just apply deltas based on observed namespace deltas?

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k do you know whether this is safe to add if there are CRQs with invalid statuses, or do we need cleanup logic?

**Comment by deads2k** [comment]
> wanted to open separately since I'm not positive what tightening this will do to existing CRQs with invalid status. does the reconciler recompute the total or just apply deltas based on observed namespace deltas?

Reconciliation should eventually get it.  Might take a while though.

**Comment by ncdc** [comment]
Is this still for 1.4?

**Comment by liggitt** [comment]
I'm not confident enough in how the system would react if a clusterquota status update suddenly started getting rejected for validation reasons to put this in 1.4

**Pull request closed without merging**
