### PR TITLE
Remove 12MB from the oc binary

### PR DESCRIPTION
**Pull request by smarterclayton**
@liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
Hmm, there's no shared location we can move the constant?

**Comment by smarterclayton** [comment]
URL retrieval / generation is the responsibility of the client.  There
should be a client interface probably.

On Thu, Jul 16, 2015 at 3:56 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Hmm, there's no shared location we can move the constant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3744#issuecomment-122070571>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
At least make it a constant in the package with a todo to rework it

**Comment by liggitt** [comment]
Nits, LGTM

**Comment by smarterclayton** [comment]
I don't want a public constant, because then people will use it.

On Thu, Jul 16, 2015 at 4:00 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Nits, LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3744#issuecomment-122071604>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Also, we can't change this value anyway, so having a common constant is
deceptive.

On Thu, Jul 16, 2015 at 4:02 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> I don't want a public constant, because then people will use it.
>
> On Thu, Jul 16, 2015 at 4:00 PM, Jordan Liggitt <notifications@github.com>
> wrote:
>
>> Nits, LGTM
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3744#issuecomment-122071604>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
