### PR TITLE
don't expose oapi types as 'all'

### PR DESCRIPTION
**Pull request by juanvallejo**
cc @deads2k 

Backport of https://github.com/openshift/origin/pull/18085

Addresses https://github.com/openshift/origin/issues/18473#issuecomment-363445708

### CODE REVIEW

**Comment by deads2k** [comment]
clean pick?

**Comment by juanvallejo** [comment]
@deads2k 
> clean pick?

Yeah

**Comment by deads2k** [comment]
if it's a clean pick

/lgtm

**Pull request merged**
