### PR TITLE
Add ability to capture request/response headers and cookies

### PR DESCRIPTION
**Pull request by rsevilla87**
HAProxy allows to capture request/response headers and cookies, this PR make users able to capture these headers or cookies and print them in a log.
Also added strings.Split to template helpers functions that could be very useful in a future.

### CODE REVIEW

**Comment by rsevilla87** [comment]
@pweil- PTAL

**Comment by pweil-** [comment]
thanks for the PR @rsevilla87, I'll tag some of the networking folks for review.

/assign @knobunc

**Comment by rsevilla87** [comment]
PTAL @openshift/sig-networking

**Comment by rsevilla87** [comment]
New PR open at https://github.com/openshift/router/pull/2

**Pull request closed without merging**
