### PR TITLE
Merge Service Catalog v 0.0.21 to Origin

### PR DESCRIPTION
**Pull request by jboyd01**
Merge Service Catalog v 0.0.21 to Origin

### CODE REVIEW

**Comment by jboyd01** [comment]
passes Service Catalog e2e locally.
/retest

**Comment by pmorie** [comment]
@jboyd01 

Looks like the example template needs to be updated with the new admission controller and bindata regenerated.

**Comment by jboyd01** [comment]
@pmorie yes, I did miss a new Admission Controller.  I've added it and regen'd bindata.  Teach me to fish - - where'd you see this error that indicated the missing controller?

**Comment by spadgett** [comment]
Are we going to add the feature gate flag for originating identity to the service catalog template?

**Comment by pmorie** [comment]
@jboyd01 I didn't see an error that indicated it - I knew to look for it because it was in the 0.0.21 release.

Also, we need to ensure that the feature flag for originating identity is enabled in the template used by `oc cluster up`

**Comment by jboyd01** [comment]
ok, should be ironed out this time.  The BrokerAuthSarCheck admission controller is enabled as is OriginatingIdentity.

**Comment by jboyd01** [comment]
extended_networking_minimal failing with no route to host....
/test extended_networking_minimal

**Comment by bparees** [comment]
i assume i'm only reviewing the template yaml changes, so that part lgtm.

**Comment by gabemontero** [comment]
need an api review as well, right? ... at least the label has been added ... bump @openshift/api-review

**Comment by pmorie** [comment]
@gabemontero I don't understand why the api-review label is on there - on our other rebase PRs for catalog it's also been added but it isn't clear why.  I imagine that it might be because the rebase contains API files - which are not up for review since they're coming from upstream.

**Comment by deads2k** [comment]
> need an api review as well, right? ... at least the label has been added ... bump @openshift/api-review

It's trigger on types.go changes.  This one is a false positive because it's a fake repo inside of our real repo.

**Comment by gabemontero** [comment]
thanks @deads2k 

with passing tests, let's remove the label and merge this puppy then :-) (assuming that is what is blocking its presence on https://origin-sq-status-ci.svc.ci.openshift.org/#/queue)

**Comment by deads2k** [comment]
> thanks @deads2k
> 
> with passing tests, let's remove the label and merge this puppy then :-) (assuming that is what is blocking its presence on https://origin-sq-status-ci.svc.ci.openshift.org/#/queue)

Different flag.  This pull touches samples and something in `oc cluster up`, so its waiting for approval on changing those things.

**Comment by deads2k** [comment]
> Different flag. This pull touches samples and something in oc cluster up, so its waiting for approval on changing those things.

@gabemontero this commit in particular `catalog: enable OriginatingIdentity`.  @bparees could do it if he knows that its doing.

**Comment by bparees** [comment]
i verbally approved that already: https://github.com/openshift/origin/pull/16457#issuecomment-331315832

but sure, labels updated.  they don't actually block merging anyway as far as i know.

**Comment by deads2k** [comment]
> i verbally approved that already: #16457 (comment)
> 
> but sure, labels updated. they don't actually block merging anyway as far as i know.

oh, you need to say

/approve

to give the right label

**Comment by deads2k** [comment]
> bparees added api-approved and

`api-approval` doesn't block merge.

**Comment by bparees** [comment]
I was only approving the template change so i did not want to use /approve.

i haven't reviewed any of the other commits, nor do i intend to.

**Pull request merged**
