### PR TITLE
add default resource requests to registry creation

### LINKED ISSUE #8820: Upgrade QoS tier for the registry
Similar to what was done for the router in https://github.com/openshift/origin/pull/8495

@miminar @legionus @soltysh

### PR DESCRIPTION
**Pull request by legionus**
Fix #8820 

@soltysh @miminar @kargakis

### CODE REVIEW

**Comment by legionus** [comment]
[test]

**Comment by kargakis** [comment]
LGTM

@smarterclayton are you ok with this?

**Comment by soltysh** [comment]
LGTM

**Comment by smarterclayton** [comment]
Yes [merge]

**Pull request merged**
