### PR TITLE
[WIP] More CLI global flags fixes

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/openshift/origin/issues/9348

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton Did this fix the issue? Then I'll open the PR in Cobra and remove WIP here.

**Comment by smarterclayton** [comment]
I avoided the problem for now, wasn't in the critical path.  We can try
after the rebase lands.

**Comment by smarterclayton** [comment]
Still see:

```
-    flags+=("--container-hints=")
     flags+=("--context=")
-    flags+=("--docker=")
-    flags+=("--docker-env-metadata-whitelist=")
-    flags+=("--docker-only")
-    flags+=("--docker-root=")
-    flags+=("--docker-run=")
-    flags+=("--enable-load-reader")
-    flags+=("--event-storage-age-limit=")
-    flags+=("--event-storage-event-limit=")
-    flags+=("--global-housekeeping-interval=")
-    flags+=("--housekeeping-interval=")
     flags+=("--httptest.serve=")
```

**Comment by fabianofranz** [comment]
@smarterclayton give this another try. Remember you have to `make clean` since there are Cobra changes. I don't see the flags you referred in https://github.com/openshift/origin/pull/9743#issuecomment-231848111 anymore. I it looks good I'll have to propose it in Cobra so that we have `ExcludeGlobalFlagSet`.

**Comment by smarterclayton** [comment]
Did you regen and check in the completions?

**Comment by fabianofranz** [comment]
> Did you regen and check in the completions?

@smarterclayton yep.

**Comment by smarterclayton** [comment]
Hrm, still omitted a bunch of things for me when I did that.

**Comment by fabianofranz** [comment]
> Hrm, still omitted a bunch of things for me when I did that.

Can you paste the diff?

**Comment by fabianofranz** [comment]
@smarterclayton is this still an issue? Any unwanted flags being added to man/completions on Mac?

**Comment by smarterclayton** [comment]
Yes, all of them.

**Pull request closed without merging**
