### PR TITLE
UPSTREAM: 68007: Orphan DaemonSet when deleting with --cascade option set

### PR DESCRIPTION
**Pull request by soltysh**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1623352

/assign @mfojtik

### CODE REVIEW

**Comment by juanvallejo** [comment]
lgtm, could we maybe add a test for this?

**Comment by soltysh** [comment]
I wouldn't bother, this is *ONLY* in 3.11, the next release does not have this code path.

**Comment by soltysh** [comment]
/hold
There's a bug that @tnozicka pointed out in the upstream PR.

**Comment by soltysh** [comment]
Fixed the error @tnozicka pointed out.

/hold cancel

Re-applying labels back.

**Comment by soltysh** [comment]
@deads2k not sure who will be in charge of the next rebase, but heads up that although this is a valid upstream PR it should be dropped during next rebase since this path is removed in 1.12.

**Pull request merged**
