### PR TITLE
Remove duplicate integration tests and ones testing things we don't ship

### PR DESCRIPTION
**Pull request by deads2k**
Integration tests are not free.  They take maintenance on most rebases and run a parallel wiring that bears little to no resemblance to our actual installs.  Many date back to before upstream had e2e tests and are duplicates of ones we pushed upstream.  Others only exist because we used to have parallel apiserver and controller wiring which we have since removed.

This pull removes integration test which are not providing additional value to us.  I grouped them into commits based on why they were removed for future devs.

@openshift/sig-master

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by deads2k** [comment]
known flakes, just affects integration tests, improves reliability and a fair likelihood of conflict. merging

**Pull request merged**
