### PR TITLE
oc set probe/triggers: set output version

### PR DESCRIPTION
**Pull request by csrwng**
Adds an output version and allows pass-thru of objects that were not modified by the command.

Enables changing a list of objects that are streamed in, like:
```
$ oc new-app https://my.git.repo -o yaml | oc set probe --liveness --open-tcp=8080 -f - -o yaml | oc create -f - 
```

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k or @kargakis ptal

**Comment by kargakis** [comment]
LGTM

**Comment by csrwng** [comment]
[merge]

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
