### PR TITLE
Bump sti image to v0.4

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@mfojtik this is necessary, right?

**Comment by mfojtik** [comment]
yes, we did more fixes last days to support pull secrets and fixing couple
bugs... @bparees do we need to do release to pick the changes here?

**Comment by bparees** [comment]
the last time I rebased origin w/ new STI code, I did not bother to do a release (or update this obviously).  don't tell @soltysh  :)

At this point i think we might as well wait until your STDERR and the save-artifacts fixes go in before we cut another STI release and rebase/fix this.

**Comment by soltysh** [comment]
@bparees actually you did release when bumping IIRC, [see this](https://github.com/openshift/source-to-image/releases/tag/v0.4).

**Comment by bparees** [comment]
@soltysh I did another bump in origin just a day or two ago to pick up my env merge changes.

**Comment by soltysh** [comment]
@bparees cheater :stuck_out_tongue_winking_eye:

**Comment by mfojtik** [comment]
@soltysh @sdodson @bparees hold on till the recent changes land in source-to-image repo and do 0.5 release with all fixes included.

**Comment by sdodson** [comment]
Shall we close this and just make sure that when we bump the godep for 0.5 we also bump the release in the docker image?

**Comment by bparees** [comment]
yeah, i'll just handle this when i rebase origin on sti 0.5

**Pull request closed without merging**
