### PR TITLE
add ext test for pipeline bc deletion behavior

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience ptal

new test to validate recent bug fix in sync plugin

### CODE REVIEW

**Comment by bparees** [comment]
/retest

Do we have a test for the other part of your PR?  Ensuring that if the BC was created by jenkins, it gets deleted when the jenkins job is deleted, but otherwise it is not deleted?

**Comment by gabemontero** [comment]
On Tue, Feb 27, 2018 at 10:43 PM Ben Parees <notifications@github.com>
wrote:

> /retest
>
> Do we have a test for the other part of your PR? Ensuring that if the BC
> was created by jenkins, it gets deleted when the jenkins job is deleted,
> but otherwise it is not deleted?
>
not yet

Some more involved there including some things we have yet to do from our
extended teats

I propose get this in and circle back to the other piece after sorting out
some other issues for 3.9

**Comment by bparees** [comment]
> I propose get this in and circle back to the other piece after sorting out
some other issues for 3.9

sounds good.

**Comment by gabemontero** [comment]
OK, tests passing

@bparees - per the exchanges culminating with https://github.com/openshift/origin/pull/18769#issuecomment-369112865 so you have more review you want to do, or should we merge

**Comment by bparees** [comment]
/lgtm

btw @coreydaley has a PR for doing the build delete/job delete flow, maybe you can get him to add the annotation checking bit to his tests.

**Pull request merged**
