### PR TITLE
don't add ICT for source images if build is binary

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/15224

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@openshift/devex ptal

**Comment by jim-minter** [comment]
lgtm

**Comment by bparees** [comment]
thanks, will merge after 3.6 branch is cut.

**Comment by bparees** [comment]
[merge][severity:blocker]  (not sure if the severity check has been lifted on master after the 3.6 branch was cut)

**Pull request merged**
