### PR TITLE
Bug 1879554: Use multi-arch registry for buildah images

### PR DESCRIPTION
**Pull request by r4f4**
At least until https://github.com/containers/buildah/issues/2002 is resolved.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by r4f4** [comment]
CC @yselkowitz

**Comment by yselkowitz** [comment]
Thanks!
/retest

**Comment by shawn-hurley** [comment]
I don't think that I am the correct person to review this. 

/cc @adambkaplan @bparees

**Pull request merged**
