### PR TITLE
make export-all work in failures

### PR DESCRIPTION
**Pull request by deads2k**
We need to be a cluster-admin to export everything from all namespaces.

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by deads2k** [comment]
```
The 'new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet
or is only on the local system.

See 'new-app' for examples.
!!! Error in test/cmd/newapp.sh:15
	'[ "$(oc new-app library/php mysql -o yaml | grep 3306)" ]' exited with status 1
Call stack:
	1: test/cmd/newapp.sh:15 main(...)
```

re[test]

**Comment by deads2k** [comment]
> re[test]

Looks like docker connectivity.

**Comment by deads2k** [comment]
dockerhub in a different spot re[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
