### PR TITLE
Improve the UX of the local image build script

### PR DESCRIPTION
**Pull request by stevekuznetsov**
An explanatory comment about how the script operates as well as
available arguments and environment variables should clear up the
usage and possibilities for this script. The script now also detects
when the user has requested an image that the script does not know
how to build.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @bparees @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
Its better, but if I'm going to be picky, it would be good to see an actual example of requesting multiple different images to be built, or a typical CLI usage syntax like name-of-script

**Comment by stevekuznetsov** [comment]
@jwforres added example, usage string, made it print on any of `-h` `--h` `-help` `--help`.

**Comment by stevekuznetsov** [comment]
@bparees

**Comment by bparees** [comment]
tested?

**Comment by stevekuznetsov** [comment]
```
$ hack/build-local-images.py haproxy-router
[ERROR] The provided image names (haproxy-router) did not match any buildable images.
[ERROR] This script knows how to build:
	openshift/origin
	openshift/origin-docker-builder
	openshift/node
	openshift/origin-recycler
	openshift/origin-deployer
	openshift/origin-sti-builder
	openshift/openvswitch
	openshift/origin-f5-router

$ hack/build-local-images.py f5-router
[INFO] Building f5-router...
Sending build context to Docker daemon 318.6 MB
Step 1 : FROM openshift/origin-f5-router
 ---> f43cb218e492
Step 2 : ADD bin/openshift /usr/bin/openshift
 ---> Using cache
 ---> 3f56d30d9cce
Successfully built 3f56d30d9cce

$ hack/build-local-images.py -h
Quickly re-build images depending on OpenShift Origin build artifacts.

This script re-builds OpenShift Origin images quickly. It is intended
to be used by developers for quick, iterative development of images
that depend on binaries, RPMs, or other artifacts that the Origin build
process generates. The script works by creating a temporary context
directory for a Docker build, adding a simple Dockerfile FROM the image
you wish to rebuild, ADDing in static files to overwrite, and building.

The script supports ADDing binaries from origin/_output/local/bin/linux/amd64/
and ADDing static files from the original context directories under the
origin/images/ directories.

Usage:
  [OS_DEBUG=true] [OS_IMAGE_PREFIX=prefix] build-local-images.py [IMAGE...]

  Specific images can be specified to be built with either the full name
  of the image (e.g. openshift3/ose-haproxy-router) or the name sans prefix
  (e.g. haproxy-router).

  The following environment veriables are honored by this script:
   - $OS_IMAGE_PREFIX: one of [openshift/origin, openshift3/ose]
   - $OS_DEBUG: if set, debugging information will be printed

Examples:
  # build all images
  build-local-images.py

  # build only the f5-router image
  build-local-images.py f5-router

  # build with a different image prefix
  OS_IMAGE_PREFIX=openshift3/ose build-local-images.sh

Options:
  -h,--h, -help,--help: show this help-text
```

**Pull request merged**
