### PR TITLE
UPSTREAM: 53753: Reduce log spam in qos container manager

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by kargakis** [comment]
flaked on https://github.com/openshift/origin/issues/13708

/retest

**Comment by joelsmith** [comment]
Looks like another flake
/test extended_conformance_install_update

**Comment by joelsmith** [comment]
Another flake
/test extended_conformance_install_update

**Comment by joelsmith** [comment]
Another flake
/test extended_conformance_gce

**Pull request merged**
