### PR TITLE
Since #8399 was closed I'm reverting this change, hopefully that'll also fix travis

### PR DESCRIPTION
**Pull request by soltysh**
@stevekuznetsov that's what was wrong, mind taking a look?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@soltysh can you leave the commit as it would be created with `git revert` ?

**Comment by soltysh** [comment]
Will do right away.

**Comment by stevekuznetsov** [comment]
```sh
	if grep -q 'no Docker socket found' "${LOG_DIR}/openshift.log" && command -v journalctl >/dev/null 2>&1; then
		# the Docker daemon crashed, we need the logs
		journalctl --unit docker.service --since -4hours > "${LOG_DIR}/docker.log"
	fi
```

**Comment by stevekuznetsov** [comment]
@soltysh make a second commit and `git apply` this patch:
```diff
diff --git a/hack/util.sh b/hack/util.sh
index 24f5a66..63606ef 100644
--- a/hack/util.sh
+++ b/hack/util.sh
@@ -269,7 +269,7 @@ function cleanup_openshift() {
                set -u
        fi
 
-       if grep -q 'no Docker socket found' "${LOG_DIR}/openshift.log"; then
+       if grep -q 'no Docker socket found' "${LOG_DIR}/openshift.log" && command -v journalctl >/dev/null 2>&1; then
                # the Docker daemon crashed, we need the logs
                journalctl --unit docker.service --since -4hours > "${LOG_DIR}/docker.log"
        fi
```

**Comment by stevekuznetsov** [comment]
LGTM @danmcp please tag for merge

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
