### PR TITLE
Update origin.spec to add BuildRequires for goversioninfo

### PR DESCRIPTION
**Pull request by detiber**
Currently we are having difficulty building from master in CBS for the CentOS PaaS SIG because of the lack of BuildRequires for goversioninfo. This PR updates the spec file accordingly, and also moves towards using CBS built RPMs for requirements where possible.

- Use centos-paas7-multiarch-el7-build repo instead of centos-paas-sig-openshift36 repo for the source image, this provides access to goversioninfo, but also allows for further multi-arch support of the build tooling as well.
- Update release images
  - install protoc from RPM for all release images
  - install goversioninfo from RPM for all release images
  - install golang from RPM for golang-1.8 release image only (will provide a followup PR for golang-1.9 once it is available in CBS)
- Update origin.spec:
  - update golang version requirement to >= 1.8.3
  - add BuildRequires for goversioninfo to openshift-redistributable-clients subpackage

### CODE REVIEW

**Comment by detiber** [comment]
@tdawson @jupierce As we discussed yesterday, wanted to get some feedback on the initial attempt, but if this looks acceptable, then I will break into 3 separate PRs (source image, release image, spec update) so that we can get them merged in an order that will not break tests.

**Comment by detiber** [comment]
@jupierce @stevekuznetsov iirc the release images are updated outside of the CI process, so if this approach is deemed as acceptable, then when I break this into the three PRs, the release image would need to be created and pushed following the merging of the second PR.

**Comment by stevekuznetsov** [comment]
I'm not super happy about using an out-of-band repo for some of this stuff but since the whole image is not part of a critical path anywhere I think it should be fine. The images should be built once the commit changing the Dockerfiles gets merged.

**Comment by detiber** [comment]
> I'm not super happy about using an out-of-band repo for some of this stuff but since the whole image is not part of a critical path anywhere I think it should be fine. The images should be built once the commit changing the Dockerfiles gets merged.

@stevekuznetsov we already are using the CentOS PaaS SIG repo currently. I'd be happy to move all of the packages to a repo on the mirror host if that is preferrable.

**Comment by detiber** [comment]
@stevekuznetsov would like to revisit this one

**Comment by detiber** [comment]
@stevekuznetsov are you able to update the release images or is that something that Clayton needs to do?

**Comment by stevekuznetsov** [comment]
They should be triggered automatically by a Docker Hub build

**Comment by detiber** [comment]
@stevekuznetsov looks like docker hub builds are failing because origin-source does not exist there, so origin-base has been failing for 3 months, and the origin-release builds failed because they did not get the repo update in origin-base through origin-source.

**Pull request merged**
