### PR TITLE
Vendor registry packages differently to enable GCS

### PR DESCRIPTION
**Pull request by smarterclayton**
Allows registry to have different packages than Kube.

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test] @mfojtik @pweil-  @ncdc this will work in Go 1.6, but not in 1.4.  For 1.4, it'll have to be a custom GOPATH.

I need to add the build logic to build this separately still.

**Comment by ncdc** [comment]
😿😿😿 I think what we're having to do here deserves some crying cats 😿😿😿

**Comment by smarterclayton** [comment]
Surprisingly, it's not as bad as I thought.  With some scripting it would
probably be a trivial update.

On Jun 7, 2016, at 8:34 PM, Andy Goldstein <notifications@github.com> wrote:

😿😿😿 I think what we're having to do here deserves some crying cats 😿😿😿

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9211#issuecomment-224454862>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_pw5e4dirfR4E3rOh8Nsks42uwMXAks5qJg4UgaJpZM4Iwdmf>
.

**Comment by ncdc** [comment]
Sure, but it's ~25k LOC that we'd ideally not have to carry along

**Comment by smarterclayton** [comment]
I'm starting to change my mind a bit here - I would rather use their
dependencies and have us change them willy nilly.  I think we're going to
see this problem get worse (this is just the beginning).

On Jun 7, 2016, at 8:37 PM, Andy Goldstein <notifications@github.com> wrote:

Sure, but it's ~25k LOC that we'd ideally not have to carry along

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9211#issuecomment-224455230>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_pyu1o6Vl3pdydO5UYBb6jhAEUe9Dks5qJg6rgaJpZM4Iwdmf>
.

**Comment by ncdc** [comment]
We also discussed splitting the registry into a separate repo and having it vendor in all the deps it needs. Maybe we wouldn't have conflicting versions then, since what the registry would need to pull in from Kube and Origin should be relatively small. I'm not saying I want to go this route, but it's maybe starting to sound a bit better?

**Comment by smarterclayton** [comment]
Today it would not be relatively small, but once we have a client library,
yes.

On Jun 7, 2016, at 8:46 PM, Andy Goldstein <notifications@github.com> wrote:

We also discussed splitting the registry into a separate repo and having it
vendor in all the deps it needs. Maybe we wouldn't have conflicting
versions then, since what the registry would need to pull in from Kube and
Origin should be relatively small. I'm not saying I want to go this route,
but it's maybe starting to sound a bit better?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9211#issuecomment-224456523>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p3BYewuKnPvOKBFvDGNr9KzI8J07ks5qJhDdgaJpZM4Iwdmf>
.

**Comment by smarterclayton** [comment]
Alright, this is now updated with build and test.

**Comment by smarterclayton** [comment]
I cut the package imports down a bit and will push once I see a jenkins run.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by mfojtik** [comment]
@legionus FYI (this is not affecting you yet ;-)

**Comment by pweil-** [comment]
also, @miminar

**Comment by smarterclayton** [comment]
When we land distribution 2.4 we'd need to do the same thing here, ping me
and I'll go over what is necessary.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Ready for review - once we merge this I'll do a backport.

On Jun 8, 2016, at 5:50 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test SUCCESS (
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/4623/)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9211#issuecomment-224740420>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p1DBzy4osKvZU-UUgL0MgmkzRQZwks5qJzkzgaJpZM4Iwdmf>
.

**Comment by miminar** [comment]
I don't think this will work with go 1.5 without exporting `GO15VENDOREXPERIMENT=1` as well.

**Comment by miminar** [comment]
This has been addressed already by @legionus in #8938 (on review). See https://github.com/openshift/origin/pull/8938/commits/4390daddfbe7ffb13344f4ef78362ff54aeb046a for exported `GO15VENDOREXPERIMENT=1`. Nevertheless, I'm fine with merging this before #8938.

**Comment by smarterclayton** [comment]
The change in that PR should adopt this pattern.  Go vendor experiment
should not be required, we only build on 1.6.  For backport the fix
will involve GOPATH, not vendor.

**Comment by smarterclayton** [comment]
We don't support go 1.5.

**Comment by mfojtik** [comment]
@smarterclayton can you and @legionus talk about merging the efforts so @legionus don't have to rework his PR from scratch?

**Comment by smarterclayton** [comment]
His PR only has to handle the parts that this handles - specifically, the GCS changes.  His PR doesn't have to change dramatically.

I need this in - is there any feedback on this approach at this point?

**Comment by smarterclayton** [comment]
@mfojtik this is going to go in before the rebase.

**Comment by miminar** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by mfojtik** [comment]
@smarterclayton I think this will break me terribly, but rebase made me stronger and I can survive... so I'm sending you the rage face: :rage3:

**Comment by smarterclayton** [comment]
You should just be able to grab the carry in - unless you changed Docker
distribution???

**Comment by mfojtik** [comment]
@smarterclayton i don't think I did, but I think you're right.

**Pull request merged**
