### PR TITLE
UPSTREAM: 43982: Fix deletion of Gluster, Ceph and Quobyte volumes

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1459461

@rootfs @gnufied for review
@childsb @eparis for merge

(we really miss CI for storage...)

### CODE REVIEW

**Comment by humblec** [comment]
LGTM.

**Comment by jsafrane** [comment]
[test]

**Comment by rootfs** [comment]
lgtm

**Comment by childsb** [comment]
[merge][severity:blocker]

**Pull request merged**
