### PR TITLE
switch build logs to use client, not storage

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1499016

stage pick of https://github.com/openshift/origin/pull/16705

/assign bparees
/assign jupierce

did I get the right spot?  What's the bugzilla number?

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

haven't seen the BZ from @jupierce yet.

**Comment by deads2k** [comment]
> haven't seen the BZ from @jupierce yet.

@jupierce just so I don't later get smacked by @derekwaynecarr could you make me a bugzilla and link it here?

**Comment by jupierce** [comment]
@deads2k  https://bugzilla.redhat.com/show_bug.cgi?id=1499016

**Pull request merged**
