### PR TITLE
UPSTREAM: 30836:  fix Dynamic provisioning for vSphere

### PR DESCRIPTION
**Pull request by gnufied**
This PR does the following,

Fixes an error 'A specified parameter was not correct:' occurs while dynamically provisioning the volumes.
Adds VSAN support for dynamic provisioning.

### CODE REVIEW

**Comment by gnufied** [comment]
grr, my bad - the script (hack/cherry-pick.sh) generated that PR number and I thought it would be correct.  fixing it.

**Comment by childsb** [comment]
[test]

**Comment by gnufied** [comment]
It is flaking on #11094 and #11560

**Comment by erinboyd** [comment]
LGTM

**Comment by eparis** [comment]
did you fix the numbers?

**Comment by eparis** [comment]
I updated the PR title, but I still see it in the commit message

**Comment by gnufied** [comment]
There is some problem with github or something else. I did amend the commit and also changed the PR title - as you can see from multiple PR change "events" logged in this PR.  Are you still seeing commit message to be wrong? I can see correct PR number in commit message.

**Comment by erinboyd** [comment]
@childsb @rootfs Can one of you please help us. It's critical this gets merged

**Comment by childsb** [comment]
Flake #11094 
Flake #11560
[test]

**Comment by rootfs** [comment]
I am not sure if this merge is sufficient, there is another one
https://github.com/kubernetes/kubernetes/pull/34997

**Comment by erinboyd** [comment]
Yes, Ritesh mentioned he would be submitting another PR today.
I was aware of it.
We will need to cherry pick it as well.
Erin

**Comment by gnufied** [comment]
@rootfs that PR has been already merged into origin master.

**Comment by erinboyd** [comment]
yes, https://github.com/openshift/origin/pull/11574

**Comment by childsb** [comment]
per email with dan

[merge]

**Comment by gnufied** [comment]
Flaked on https://github.com/openshift/origin/issues/10773

**Comment by childsb** [comment]
flake #10773
[merge]

**Comment by gnufied** [comment]
Flaked on https://github.com/openshift/origin/issues/11661

**Comment by childsb** [comment]
[merge]

**Pull request merged**
