### PR TITLE
Bug 1739085: Fix multi-version CRD and admission webhook

### PR DESCRIPTION
**Pull request by markusthoemmes**
See https://bugzilla.redhat.com/show_bug.cgi?id=1739085 and https://github.com/kubernetes/kubernetes/pull/79495 for reference.

### CODE REVIEW

**Comment by mfojtik** [comment]
/retitle Bug 1739085: Fix multi-version CRD and admission webhook

**Comment by markusthoemmes** [comment]
Is this issue likely caused by the change here?

**Comment by mfojtik** [comment]
/hold

@markusthoemmes the e2e tests are red, we need to determine whether this change broke them.

**Comment by derekwaynecarr** [comment]
I will review when the e2e tests are no longer red.  To confirm, no change was needed in master as this was already fixed in 1.14?

**Comment by pmorie** [comment]
@derekwaynecarr 

> To confirm, no change was needed in master as this was already fixed in 1.14?

That's correct - this issue appears not be present on 1.14

**Comment by markusthoemmes** [comment]
@derekwaynecarr Redness is gone 🙂

**Comment by sttts** [comment]
> @derekwaynecarr
> 
> > To confirm, no change was needed in master as this was already fixed in 1.14?
> 
> That's correct - this issue appears not be present on 1.14

I bet this was fixed in 1.15 only, not in 1.14.

**Comment by markusthoemmes** [comment]
@sttts at least the issue was not reproducible on 1.14. AFAIK nobody has doublechecked in-code if it's impossible to appear in 1.14.

**Comment by sttts** [comment]
@markusthoemmes actually, maybe we accidently fixed that already in 1.14 when adding alpha conversion.

**Comment by bbrowning** [comment]
@sttts This was fixed upstream in 1.14 by https://github.com/kubernetes/kubernetes/pull/74154

**Comment by pmorie** [comment]
@derekwaynecarr @mfojtik @sttts QE has verified that 4.2 isn't affected: https://bugzilla.redhat.com/show_bug.cgi?id=1739235

**Comment by mfojtik** [comment]
/hold cancel

Patch manager need to approve.

**Pull request merged**
