### PR TITLE
Added Label to DockerConfig

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@ncdc this will allow to query the 'Labels' field in `osc get image XYZ`. We still have to talk how to make them useful for the ImageStream 'tags' (which are currently in the spec).

@smarterclayton thoughts?

**Comment by mfojtik** [comment]
@ncdc @smarterclayton as I understand it, the ImageStream provides the 'global' tags/metadata for the UI. Since the imageStream might import multiple Images and each image might have its own set of Labels(?) I'm not sure where or how we are going to show them.

**Comment by ncdc** [comment]
osc get image won't be allowed for users. They'll have to get isimage or istag. I'll review this in a couple of hours.

**Comment by mfojtik** [comment]
@ncdc this initial PR is just about having the Labels from the image available inside OpenShift. How to use them, is still a topic for discussion :-)

**Comment by smarterclayton** [comment]
We probably want to copy all labels to annotations directly (if the key spaces are aligned).

**Comment by mfojtik** [comment]
@smarterclayton what if you have image with multiple tags that has different labels? is that even possible? if so what labels we should be copying.... also we discussed yesterday how to handle updating labels (iow. you change the label value in new version of the image)

**Comment by ncdc** [comment]
@mfojtik speaking purely from a Docker perspective, for v1 images, it is possible for multiple tags to refer to the same image ID. For v2 images, schemaVersion=1 (I'll call this v2.1), it is not possible, as each v2.1 image manifest has the namespace, repo, and tag in it (and if you change any of those 3 variables, you get a new ID). There are talks for v2.2+ images to remove namespace, repo, and tag from the manifest (and moving them to tag objects instead), which would allow multiple tags to refer to the same image ID, but that code doesn't exist yet for v2+.

From an OpenShift ImageStream perspective, we could have an IS where multiple tags point to the same image. For example, if you set up "latest" to track another tag, like "2.0", then you'd have (roughly)

```
status.tags[latest].items[0].image=sha256:abc...
status.tags[2.0].items[0].image=sha256:abc...
```

Any requests for ISTag latest or 2.0 would return the same image.

**Comment by ncdc** [comment]
@mfojtik any luck with the conversion and/or fuzzer issues?

**Comment by mfojtik** [comment]
still working on this... I will have time to fix this today evening or
tomorrow morning.

**Comment by mfojtik** [comment]
@ncdc I was looking into this today and whatever I do in conversion it always explode on different place... The easiest solution is to add Label field into 'dockerpre012'. In that case conversion and everything else works. I assume that field will be ignored or just set to empty map (as the pre012 does not support Labels?)

@ncdc is that acceptable?

**Comment by ncdc** [comment]
Assuming time is of the essence that works for me. Otherwise, we'll need someone with more fuzzer and conversion experience to help out. @smarterclayton what's your opinion?

**Comment by smarterclayton** [comment]
It's fine for it to be empty in older APIs, but please add a comment to the older pre012 version indicating this is not actually supported and that will be empty.

**Comment by mfojtik** [comment]
@smarterclayton @ncdc comment added, I think it is good to merge. The labels will be imported and we should follow up on how to merge them with ImageStream annotations.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
