### PR TITLE
Change references from Docker registry to container image registry.

### PR DESCRIPTION
**Pull request by rhatdan**
Trying to remove as many references to Docker as possible.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
@rhatdan the "api" dir is generated content, so you can't update it directly (that is likely why the verify test is failing).

Cleaning those up would require updating all the godoc in our api types and then regen'ing the api doc.

**Comment by rhatdan** [comment]
@bparees I think this is ready now.

**Comment by adambkaplan** [comment]
@rhatdan looks like master team bit you here. `openshift-kube-apiserver` is now upstream. See #23218

**Comment by rhatdan** [comment]
@bparees @adambkaplan How do I retrigger travis here?

**Comment by adambkaplan** [comment]
@rhatdan your changes alter `vendor/` code (surprised this isn't causing the `verify` test to fail). Only `UPSTREAM` and `bump(*)` commits can do this. Please revert those.

**Comment by rhatdan** [comment]
Oops @adambkaplan Thanks for pointing that out.  I caught those earlier, but these leaked through.

**Pull request merged**
