### PR TITLE
UPSTREAM: 47731: Use endpoints informer for the endpoint controller.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr  @smarterclayton 

Fixes https://github.com/openshift/origin/issues/14710

Note: I had to manually merge changes and due to this, the commits might not match exactly. 

It has following 2 complete upstream PRs: 
https://github.com/kubernetes/kubernetes/pull/47731  (with some modifications/additions).
https://github.com/kubernetes/kubernetes/pull/47788

And one partial PR to make above PRs compile:
https://github.com/kubernetes/kubernetes/pull/44408

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Going to hold for 3.6.1 potentially [test] again

**Comment by aveshagarwal** [comment]
Updated this PR after kube-1.7 rebase landed.

**Comment by smarterclayton** [comment]
Lgtm for 1.7, [merge] to get soak time on master

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
