### PR TITLE
UPSTREAM: 18804: Fix nodeport service compat with default-deny fw

### PR DESCRIPTION
**Pull request by marun**
This change ensures that the userspace proxy can whitelist the proxy
ports for NodePort services to ensure compatibilty with default deny
firewalls

### CODE REVIEW

**Comment by marun** [comment]
cc: @eparis @danwinship

**Comment by marun** [comment]
@danwinship I'd like to ensure the userspace proxy and the iptables proxy get tested in CI, but am I correct in assuming there's currently no way to deploy openshift with the userspace proxy enabled?

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/6967 with https://github.com/danwinship/origin/pull/2 will allow that

**Comment by eparis** [comment]
Should be fixed by #7269

**Comment by marun** [comment]
Fix is now in the tree.

**Pull request closed without merging**
