### PR TITLE
add master-config validation that complains about using troublesome a…

### PR DESCRIPTION
**Pull request by deads2k**
…dmission chains

Fixes https://github.com/openshift/origin/issues/9738

@csrwng ptal

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by csrwng** [comment]
LGTM 👍

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/9959 re[test] [merge]

**Comment by deads2k** [comment]
conformance hang re[test] re[merge]

**Comment by deads2k** [comment]
build image problem, re[test] re[merge]

**Pull request merged**
