### PR TITLE
Allow system:registry to use layers API

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
was it done in master already? not seeing it there either.

**Comment by dmage** [comment]
@bparees in master this role is created by the image registry operator.

**Comment by smarterclayton** [comment]
What about in 3.11?

**Comment by bparees** [comment]
> What about in 3.11?

?  this is a PR against 3.11.  The change is already in 4.0 via the registry operator (as @dmage reminded me).

**Comment by smarterclayton** [comment]
Sorry, it looked like the others.

**Comment by dmage** [comment]
It seems the new permission was tested on CI cluster, can we unhold this PR?

**Comment by dmage** [comment]
Nothing is changed, amended to reset CI checks.

**Comment by bparees** [comment]
@dmage feel free to re-apply the lgtm label manually in such cases

/lgtm

**Comment by bparees** [comment]
@adambkaplan @dmage i'm going to manually merge this since it looks like the SC catalog job is borked and everything else is passing, but can one of you chase down the owner of that job and figure out what needs to be done with it so it doesn't block things in the future?

**Comment by adambkaplan** [comment]
@bparees sc team is on it.

**Pull request merged**
