### PR TITLE
Bug 1704356: Backport AWS cloud-provider improvements

### PR DESCRIPTION
**Pull request by huffmanca**
This backports the following upstream PRs:

  https://github.com/kubernetes/kubernetes/pull/78276
  https://github.com/kubernetes/kubernetes/pull/78601
  https://github.com/kubernetes/kubernetes/pull/78140

This addresses the issue in [BZ-1704356](https://bugzilla.redhat.com/show_bug.cgi?id=1704356).

### CODE REVIEW

**Comment by gnufied** [comment]
Can you also link BZ against which this PR was made?

**Comment by huffmanca** [comment]
> Can you also link BZ against which this PR was made?

I've updated the original comment to include a link to the BZ.

**Comment by childsb** [comment]
/lgtm
/approve

@smarterclayton can you review / approve?  We dont have permissions

**Pull request merged**
