### PR TITLE
Workaround slow ECDHE in F5 router tests

### PR DESCRIPTION
**Pull request by Miciah**
This commit fixes https://github.com/openshift/origin/issues/4407.

[test]

### CODE REVIEW

**Comment by Miciah** [comment]
@liggitt, it looks like this resolves the issue.  Does the workaround look acceptable?

**Comment by Miciah** [comment]
5.386s.  Just over 5s.   https://travis-ci.org/openshift/origin/jobs/77716827#L337

**Comment by liggitt** [comment]
yeah, that's fine for this test. Can you open another issue to investigate the issue generally (to find out whether we should be doing something similar for our production endpoints (for performance), and what the implications of preferring non-ECDHE ciphers are)

**Comment by liggitt** [comment]
[merge]

**Comment by Miciah** [comment]
The failure doesn't look related to this PR: TestRegistryClientConnectPulpRegistry and TestRootRedirect failed.

**Pull request merged**
