### PR TITLE
Wait for pod to be running in e2e test

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/11240

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@ncdc @liggitt @kargakis I don't think this fix the root problem here (the pods taking longer to start), but at least plumb the e2e.

@ncdc you mentioned that kubectl exec flakes rapidly in upstream... is that due to container create time increase and the the exec has low timeouts?

**Comment by kargakis** [comment]
LGTM [merge]

**Comment by mfojtik** [comment]
[test]

(aborted previous job because yum failure...)

**Comment by mfojtik** [comment]
[test]

(aborted previous job because yum failure...)

**Comment by ncdc** [comment]
No, the upstream exec flakes are happening because of what appears to be a
docker bug

**Comment by mfojtik** [comment]
[test] 

another yum flake

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
yum and https://github.com/openshift/origin/issues/11094 [test]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/8571

**Comment by mfojtik** [comment]
[test] flaked on https://github.com/openshift/origin/issues/9624

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
removing merge... this PR does not help as the issue is the `--attach` timeout.

**Comment by mfojtik** [comment]
@kargakis PTAL again... instead of relying on attach, we wait for the pod to succeed and then get the container logs (my hope is that will be more reliable...) @ncdc cc

**Comment by kargakis** [comment]
Don't we want to test --attach?

**Comment by mfojtik** [comment]
@kargakis I think we want to test that you can use the service account.

**Comment by kargakis** [comment]
Fine by me, just make sure we have a test for --attach somewhere, otherwise open an issue.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/openshift/origin/pull/11444

**Pull request closed without merging**
