### PR TITLE
move unrelated extended tests out of images

### PR DESCRIPTION
**Pull request by bparees**
* create a different folder imageapis
* move limitrange_admission and quote_admission tests out
* change tags to imageapis

### CODE REVIEW

**Comment by bparees** [comment]
@PI-Victor i had to update extended_tests.go also because of the package change, so i'm redoing your PR here.

**Comment by bparees** [comment]
[testextended][extended:core(imageapis)]

**Comment by PI-Victor** [comment]
@bparees i was waiting on the tests to see what fails. at least i see what i missed :) didn't know that's where we load the tests.

**Comment by bparees** [comment]
>  i was waiting on the tests to see what fails. at least i see what i missed :) didn't know that's where we load the tests.

right, well the tests failed because the ginkgo filter didn't find any matches to "imageapis" because of the missing line i added.  thanks to @stevekuznetsov for telling me what was wrong.

of course the tests are still going to fail (which is why we started down this road in the first place), but at least we'll see that they are runnable.

**Comment by bparees** [comment]
in this case failure means success, so [merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9355
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8192/

[test]

**Pull request merged**
