### PR TITLE
Add a peak RSS probe to the exit code describer

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by soltysh** [comment]
This will help nailing down bugs, and is not changing product, should be merged right away.
/kind bug 
/lgtm

**Comment by stevekuznetsov** [comment]
@smarterclayton the reason this doesn't work is we're not running with privileged containers and there's no `sudo` in the container obviously

**Pull request closed without merging**
