### PR TITLE
Bug 1275902 - fix help text for name field on create from image

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1275902

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
I think the wording was meant to suggest that name only had to be unique within the project, but I'm fine with the change.

Maybe just

"Identifies the resources created for this application."

?

**Comment by jwforres** [comment]
updated

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
