### PR TITLE
Remain in the current project at login if possible

### PR DESCRIPTION
**Pull request by liggitt**
On login, we were listing the projects available to the current user, selecting the current one if it is in that list, defaulting to the first project in the list otherwise

If this is done right after a project is created or a role is granted, the project list cache may not include the project yet. If the list of projects does not include our current one, attempt a direct get before switching to a different project.

Fixes https://github.com/openshift/origin/issues/10274

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
> can you add tests

it's not well-structured for mocking client calls for unit tests, reworking that is a bigger change than I want to make at the moment. test-cmd also exercises login quite a bit. will open a follow up issue

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
[merge]

**Comment by soltysh** [comment]
AWS failure:
```
/var/lib/jenkins/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/region_methods.rb:6:in `validate_aws_region': Unknown region: "<AMI_REGION>" (ArgumentError)
```

re-[merge]

**Pull request merged**
