### PR TITLE
tests/extended: remove openshift-monitoring from QoS check exclusion list

### PR DESCRIPTION
**Pull request by sjenning**
@brancz @derekwaynecarr

### CODE REVIEW

**Comment by brancz** [comment]
I think @paulfantom is currently on things around this, I just want a double check from him, then this is good to go from my side.

/lgtm
/hold

(feel free to remove the hold if you feel this won't impact you doing your changes @paulfantom )

**Comment by sjenning** [comment]
```
$ oc get pod prometheus-k8s-0 -ojson | jq '.spec.containers[] | "\(.name) \(.resources.requests)"'
"prometheus null"
"prometheus-config-reloader {\"cpu\":\"100m\",\"memory\":\"25Mi\"}"
"rules-configmap-reloader {\"cpu\":\"100m\",\"memory\":\"25Mi\"}"
"prometheus-proxy null"
"kube-rbac-proxy null"
"prom-label-proxy null"

$ oc get pod prometheus-k8s-0 -ojson | jq '.status.qosClass'
"Burstable"
```
Because some of the containers in the pod have resource requests, the pod is already `Burstable` and the e2e test will pass.

However, we do need to set proper requests on the primary `prometheus` container to a minimum of `cpu: 100m, memory: 500Mi`. fyi @paulfantom

**Comment by paulfantom** [comment]
Resource requests should be assigned to all components after https://github.com/openshift/cluster-monitoring-operator/pull/365 gets merged.

**Pull request merged**
