### PR TITLE
Change sorting logic for deployment logs

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik @ironcladlou @deads2k

### CODE REVIEW

**Comment by kargakis** [comment]
@deads2k PTAL in the last commit

**Comment by kargakis** [comment]
@mfojtik PTAL since you will need to get familiar with deployment logs before you proceed with https://github.com/openshift/origin/issues/9294

**Comment by deads2k** [comment]
lgtm, not sure if you have a preferred merge order.

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
