### PR TITLE
bump(*)

### PR DESCRIPTION
**Pull request by adambkaplan**
Pulling in cluster-level config objects for the build controller and image registry.

### CODE REVIEW

**Comment by bparees** [comment]
@adambkaplan the controllers aren't reading those objects(only the operators are) so why is this bump needed right now?

The controllers are getting their config from the controllermanagerconfig api object, right?

**Comment by deads2k** [comment]
/hold

this is backleveling kube.

**Comment by deads2k** [comment]
@mfojtik @sttts looks like the publishing problem I found earlier.

**Comment by bparees** [comment]
> @bparees there is a corresponding change to the controller manager API object to add the path to where the CA bundle is mounted.

ok, go ahead and add all the controller code changes that consume the new field as part of this PR (in a separate commit).

**Comment by adambkaplan** [comment]
@bparees I've started this work in #21362, closing this in favor of that PR (will do the proper bump there).

**Pull request closed without merging**
