### PR TITLE
Update 1.4 with all build tooling from 1.5

### PR DESCRIPTION
**Pull request by smarterclayton**
Will allow RPM builds from base.

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov back porting our release scripts to 1.4 to make multi-branch testing easier.

**Comment by stevekuznetsov** [comment]
why not cherry-picks of the commits? but OK this sounds good. 1.3 would also be perfect but I am not sure it's feasible

**Comment by smarterclayton** [comment]
Cherry-picks touch other things, and I want only the changes in the particular directories (i.e. no test changes).

**Comment by smarterclayton** [comment]
@stevekuznetsov this is green on both suites now - can you do a final pass?

**Comment by smarterclayton** [comment]
Nothing in hack/ has changed, everything outside of hack is different

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Needs two tests rearranged / disabled for 1.4 (one needs to be marked local)

**Comment by smarterclayton** [comment]
Flake https://github.com/openshift/release/issues/17

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Add even more test flake fixes to 1.4

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
