### PR TITLE
Fix upstream AWS issues

### PR DESCRIPTION
**Pull request by mfojtik**
Ref: https://github.com/openshift/origin/issues/13025

@jsafrane PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by jsafrane** [comment]
@gnufied, AFAIK it was on your TODO list, PTAL

**Comment by jsafrane** [comment]
[merge]

**Comment by jsafrane** [comment]
[test]
flake: #11016

**Comment by jsafrane** [comment]
[merge]

**Pull request merged**
