### PR TITLE
Strip whitespace in AllowAllPasswordIdentityProvider, add auth logging

### PR DESCRIPTION
**Pull request by liggitt**
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1309566 for AllowAllPasswordIdentityProvider

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
protractor test flake https://github.com/openshift/origin/issues/6618
[test]

**Comment by deads2k** [comment]
> protractor test flake #6618
> [test]

Please add flake indications: https://ci.openshift.redhat.com/jenkins/failure-cause-management/ .  I added one for this.

**Comment by deads2k** [comment]
The commits look unrelated, but other than one minor comment and thinking that allowing `bob`, `bob `, and `bob  ` is asking for future pain we don't need (disallowing it, they'd get pain they deserve and never ask us about it), it looks ok.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
