### PR TITLE
Upgrade golang-1.7 to 1.7.5

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1435261

Upgrades Go 1.7 from 1.7.4 to 1.7.5 to fix the TLS handshake timeout issue[1][2][3] seen by several users of macOS Sierra.

Basically the issue adds an overhead of ~3.5 seconds to the TLS handshake (more depending on the size of cert/key and networking conditions, like under VPN or proxy, we've seen it add around 6 seconds to the handshake). FYI our TLS handshake timeout is 10 seconds (Golang default and used by most tools).

There's a fix and it was backported[4] and is part of 1.7.5[5][6].

[1] https://github.com/golang/go/issues/18688
[2] https://github.com/golang/go/issues/18141
[3] https://github.com/golang/go/issues/18203
[4] https://github.com/golang/go/commit/5c2b5ee3c8271c3d19d8f0c38804983950c752bf
[5] https://golang.org/doc/devel/release.html#go1.7.minor
[6] https://github.com/golang/go/issues?q=milestone%3AGo1.7.5

@smarterclayton @jwforres PTAL

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
We should probably consider backporting to 1.5.

**Comment by smarterclayton** [comment]
You have to regenerate the fake RPM when you do this.  And after you do this, yes backport.

**Comment by smarterclayton** [comment]
Actually, no backport needed since these images are only built in master.

**Comment by fabianofranz** [comment]
@smarterclayton done, PTAL

**Comment by stevekuznetsov** [comment]
We'll also need the newer Golang in https://cbs.centos.org/repos/paas7-openshift-origin36-candidate/x86_64/os/Packages/ /cc @tdawson

**Comment by smarterclayton** [comment]
Lgtm [merge]

Can you also bump 1.8 to 1.8.1?  :)

**Comment by fabianofranz** [comment]
flaked on https://github.com/openshift/origin/issues/13271 re[merge]

**Comment by smarterclayton** [comment]
[merge] flake on upgrade package lookup

**Comment by fabianofranz** [comment]
@smarterclayton 1.8.1 is in https://github.com/openshift/origin/pull/13836

**Comment by smarterclayton** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
