### PR TITLE
SDN test should wait longer for namespaces

### PR DESCRIPTION
**Pull request by smarterclayton**
Flaking heavily in master

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k integration is continually flaking, this is extracted from my integration refactor where it stomped that

**Comment by smarterclayton** [comment]
e2e failed building images but didn't exit: https://github.com/openshift/origin/issues/15702

**Comment by smarterclayton** [comment]
Passed integration.  Force merging.

**Comment by deads2k** [comment]
> @deads2k integration is continually flaking, this is extracted from my integration refactor where it stomped that

You think that non-parallel it takes more than two seconds to observe a create?

**Comment by smarterclayton** [comment]
Fairly sure - but the retry logic is not properly printing out the second
run logs correctly.

**Comment by deads2k** [comment]
> It's not just failing to observe the creation of the newly-created namespace. It doesn't even observe the existence of "default". Maybe something is causing startup of the shared informer to be unexpectedly slow?

Hard to believe that would happen just *this* informer/handler pair and never another or at least not to anything approaching the same degree

**Comment by smarterclayton** [comment]
Note that some of the runs were from before the fix to the start hook
landed.  I'm still watching for the second set of hooks.

**Comment by smarterclayton** [comment]
Might be a hook init failure:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/15248/test_pull_request_origin_integration/5706/build-log.txt
or
could be the latent flake we have in project watch test.

After this merged I saw no more oadmpodnetwork flakes.

**Pull request merged**
