### PR TITLE
Bug 1883345: [release-4.5] Re-enable skipped conformance tests for IBM Cloud

### PR DESCRIPTION
**Pull request by jmcmeek**
Cherry-pick of #25220

Re-enabling selected tests now that associated bugs have been fixed and are in the Red Hat OpenShift on IBM Cloud v4.3 builds.
```
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should provide ingress metrics
[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics
[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container
```

### CODE REVIEW

**Comment by jmcmeek** [comment]
@csrwng FYI.  Got back to work on cherry-picking this.  Hope I did it right.

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by csrwng** [comment]
/retitle: Bug 1883345: [release-4.5] Re-enable skipped conformance tests for IBM Cloud

**Comment by csrwng** [comment]
@derekwaynecarr ptal

**Comment by csrwng** [comment]
/retitle Bug 1883345: [release-4.5] Re-enable skipped conformance tests for IBM Cloud

**Pull request merged**
