### PR TITLE
Fix intervals mistakenly showing mass node NotReady

### PR DESCRIPTION
**Pull request by dgoodwin**
This was caused by some bag logic here that assumed to closed a node NotReady interval any time we see an interval with a node in the locator, and a reason of Ready, which was picking up container Readys incorrectly. Nodes are not actually flapping as it appeared.

Fix by being more careful with the source of the interval so we know we're interpreting the precise intervals we intend.

[TRT-1327](https://issues.redhat.com//browse/TRT-1327)

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

Need to check intervals charts.

**Comment by stbenjam** [comment]
/retest
/lgtm

Some infra issue with yum repos

**Comment by dgoodwin** [comment]
Node NotReady intervals now look correct.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28351/pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade/1717206733232803840

**Pull request merged**
