### PR TITLE
retry integration failures to suppress the long tail of flakes

### PR DESCRIPTION
**Pull request by deads2k**
Most flakes are uncommon.  Our e2e tests retry a failing test once to see if it passes a second time.  This is fine as long as we can track the failures.

This retries a failing integration test in CI if it fails.  There is a spot to wire a hook to track the flake so we can chase it down later.

@stevekuznetsov I'd like to see an issue about tracking this.  I'm fine with having a second source of junit failures to even just track the names and $out.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/approve no-issue

@deads2k not immediately obvious to me how we want to track this stuff -- we can put it in a well known place and have Jenkins aggregate it on that master's filesystem for a while, then you can hack at it manually?

**Comment by deads2k** [comment]
> @deads2k not immediately obvious to me how we want to track this stuff -- we can put it in a well known place and have Jenkins aggregate it on that master's filesystem for a while, then you can hack at it manually?

I'm going to write up an issue for this.  

@csrwng fyi

**Comment by deads2k** [comment]
This only touches test integration.  I plan to manually merge on a clean test-integration job to help jobs succeed.

**Comment by deads2k** [comment]
green integration, merging

**Comment by deads2k** [comment]
Wow, this really seems to have cleared a lot.  Remind me to check that at least *some* still fail.

**Comment by deads2k** [comment]
> Wow, this really seems to have cleared a lot. Remind me to check that at least some still fail.

I checked locally and it appeared to fail correctly, but the volume of good pulls surprises me.

**Comment by stevekuznetsov** [comment]
> Wow, this really seems to have cleared a lot.

Underlying issue that it takes 2h30m integration to finish _successfully_ remains

**Comment by liggitt** [comment]
clayton profiled the integration tests, and 20% of the time is generating openapi specs, and 40% is GC from openapi objects

**Comment by deads2k** [comment]
> I checked locally and it appeared to fail correctly, but the volume of good pulls surprises me.

and that many were just flaking and this stops them from failing.  Bad test here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5038/

**Comment by smarterclayton** [comment]
It's very likely the router problems are actual low failure rate bugs that need to be fixed.  It's entirely possible many of the router problems we've had have been hiding in the "flake" bucket but we're actually real bugs.

Retry is ok to get the queue working, but if it's not followed by fixing the flakes, it's making the problem worse.  Most of these tests have no excuse for failing once.

**Comment by deads2k** [comment]
> Retry is ok to get the queue working, but if it's not followed by fixing the flakes, it's making the problem worse. Most of these tests have no excuse for failing once.

Looking at our list: http://pastebin.test.redhat.com/505129, it looks like we have maybe 3 or 4 real problems and 30 random failures.

**Comment by smarterclayton** [comment]
Those 3 or 4 problems are probably all release blockers :)

**Comment by deads2k** [comment]
> Those 3 or 4 problems are probably all release blockers :)

Sure, but did you have any way to figure out which 90% of the flakes were just flakes before?

**Pull request merged**
