### PR TITLE
Disable resource quota

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Disable resource quota tests.

### CODE REVIEW

**Comment by deads2k** [comment]
@ravisantoshgudimetla time should be devoted to figuring out why the feature gate detection is wrong.  It's probably looking locally at the way the test was executed maybe?

**Comment by sjenning** [comment]
@deads2k can we merge this in the meantime?  it is blocking a stream of things that needs to happen to disable some gates that have potential it cause us pain with no benefit in 4.1.

**Comment by ravisantoshgudimetla** [comment]
> time should be devoted to figuring out why the feature gate detection is wrong. It's probably looking locally at the way the test was executed maybe?

To be clear, I have spent some time debugging and the best thing that we could come up with is:

- Bump `openshift/api` when feature gate changes are merged.
- Update this block, https://github.com/openshift/origin/blob/master/test/extended/util/test.go#L317-#L420 from disable/enabled flags from openshift/api once the bump happens programatically after reading disabled/enabled flags in openshift/api.

While I am not sure, if the above approach is clean, this would ensure that origin, individual operators and api repos are in sync to so that we don't see surprises when we are disabling/enabling certain tests.

**Comment by deads2k** [comment]
> @deads2k can we merge this in the meantime? it is blocking a stream of things that needs to happen to disable some gates that have potential it cause us pain with no benefit in 4.1.

You should make a story to fix the debt coming off of this.  Imagine one turned on in tech preview. You'd have no tests.

/approve

/assign @sjenning 
if he wants to lgtm

**Pull request merged**
