### PR TITLE
improve bash completions for namespace flags

### PR DESCRIPTION
**Pull request by juanvallejo**
Related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1405961

Adds support for bash and zsh --namespace flag value completion.
Will suggest all available namespaces for a `--namespace` flag, and suggest all resources in the chosen namespace

@openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
@fabianofranz `./hack/verify-generated-completions.sh` passes locally, however the jenkins / travis test does not seem to be generating up to date completions

**Comment by fabianofranz** [comment]
@juanvallejo passed here locally too.

**Comment by juanvallejo** [comment]
@fabianofranz hm, I rebased with latest master in hopes that will fix generated completions check. I'll re[test] once more

**Comment by fabianofranz** [comment]
[merge]

**Comment by juanvallejo** [comment]
conformance flaked on https://github.com/openshift/origin/issues/11887 re[test]

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
