### PR TITLE
Add missing permission when running 'oc cluster up --metrics'

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by csrwng** [comment]
@mwringe looks like gofmt is complaining, but other than that, LGTM

**Comment by mwringe** [comment]
@csrwng ok, fixed. Is there anything else that I can do to get this merged?

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/11873
flake https://github.com/openshift/origin/issues/9076

[merge]
[test]

**Pull request merged**
