### PR TITLE
Fix display when build has not started, no startTimestamp exists

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/6616

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
In the builds table, we use `build.status.startTimestamp || build.metadata.creationTimestamp`:

```
            <td data-title="Started">
              <relative-timestamp timestamp="build.status.startTimestamp || build.metadata.creationTimestamp"></relative-timestamp>
              <span>- {{(build.status.startTimestamp || build.metadata.creationTimestamp) | date : 'short'}}</span>
            </td>
```

I think we should be consistent whatever approach we take. "Not started" is probably more accurate.

**Comment by jwforres** [comment]
Ok will fix it there as well

**Comment by spadgett** [comment]
Thanks, we should update here too:

https://github.com/openshift/origin/blob/master/assets/app/views/browse/build-config.html#L106

**Comment by jwforres** [comment]
updated

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
