### PR TITLE
Alerts-proxy points to wrong container (to buffer instead to manager)…

### PR DESCRIPTION
**Pull request by mjudeikis**
Change the port there alert-proxy points. Now, alert-manager route gives 404.

### CODE REVIEW

**Comment by smarterclayton** [comment]
I thought this was intentional - @zgalor

**Comment by mjudeikis** [comment]
If it was intentional - the intention is not clear... :)

**Comment by mjudeikis** [comment]
@smarterclayton @zgalor As I understand still will be default frontend for alert management, where alert-buffer would be for something like CloudForms or external integrations to integrate with?

In addition, Grafana points to Prometheus directly. 

On the same note, Im working now on extending our examples with additional templates and rules. By any change, it was already done? And do we have any high-level diagram on architecture?

**Comment by smarterclayton** [comment]
The installation by default is intended to support external consumption of
alerts by manage iq.  We did not have a concrete plan to support the alert
manager UI, which is another reason why it isn't default

On Wed, Jan 3, 2018 at 3:25 PM, Mangirdas Judeikis <notifications@github.com

**Comment by zgalor** [comment]
@mjudeikis this is intentional.
the alertbuffer holds the alert history (that alertmanager can't provide) and it is the API endpoint for external applications such as CloudForms.

The reason you get 404 is that you need to access the specific `/topic/alerts` path to see the alerts.
this is a generic buffer, any other topic an be populated with messages. In this setup, only `alerts` topic is populated.

In our development setup, we added a debug service + route to access alertmanager UI, it's a very simple piece of code:
https://github.com/container-mgmt/cm-ops-flow/blob/master/expose_alertmanager.sh

We did not add another route+service+proxy to the actual deployment because we didn't want to overcomplicate it (Pod already has 5 containers). I also believe this architecture will soon change with the plan for HA setup.

**Comment by mjudeikis** [comment]
@zgalor make sense... I would recommend adding a separate route for buffer and alert-manager. As now its complicating setup for those, who are used to standard Prometheus deployment where the alert manager is the main source to send alerts. In addition, buffer deployment should be disableable, as not every customer will want to use CF as alerting, and not every customer will have CF deployed. So it does not make sense to run it if you don't need.

Any doc for planned HA deployment? I might pitch in.

**Pull request closed without merging**
