### PR TITLE
handle setting triggers on BCs with no default ICT

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/13805

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/devex ptal

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/13606
[test]

**Comment by mfojtik** [comment]
[merge]

flake: https://github.com/openshift/origin/issues/13426

**Comment by smarterclayton** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
