### PR TITLE
Upstream cherry picks

### PR DESCRIPTION
**Pull request by liggitt**
Picks for https://github.com/openshift/origin/issues/6766

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
these are all picks of PRs merged upstream into the 1.2 release branch, but I'd like a sanity check before we pick them

@smarterclayton check 23034, 23141, 23456
@derekwaynecarr check 23143
@danwinship / @dcbw check 23325
@markturansky check 23457

**Comment by markturansky** [comment]
@liggitt 23457 LGTM

**Comment by danwinship** [comment]
23325 lgtm

**Comment by derekwaynecarr** [comment]
@liggitt 23143 lgtm

**Comment by smarterclayton** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
