### PR TITLE
make service name a parameter

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/3181

### CODE REVIEW

**Comment by bparees** [comment]
@mnagy ptal.

@thoraxe fyi.

@smarterclayton approval needed.

**Comment by bparees** [comment]
(or not since this doesn't rise to the level of a p0)

**Comment by bparees** [comment]
[test]

**Comment by thoraxe** [comment]
Having an issue with the MySQL one for example:

```
[joe@ose3-master beta4]$ osc logs database-1-kn0k3
Running mysql_install_db ...
mkdir: cannot create directory '/var/lib/mysql/data': Permission denied
chmod: cannot access '/var/lib/mysql/data/mysql': Permission denied
mkdir: cannot create directory '/var/lib/mysql/data': Permission denied
chmod: cannot access '/var/lib/mysql/data/test': Permission denied
Installing MySQL system tables...
150615 16:39:12 [Warning] Can't create test file /var/lib/mysql/data/database-1-kn0k3.lower-test
150615 16:39:12 [Warning] Can't create test file /var/lib/mysql/data/database-1-kn0k3.lower-test
/opt/rh/mysql55/root/usr/libexec/mysqld: Can't change dir to '/var/lib/mysql/data/' (Errcode: 13)
150615 16:39:12 [ERROR] Aborting

150615 16:39:12 [Note] /opt/rh/mysql55/root/usr/libexec/mysqld: Shutdown complete


Installation of system tables failed!  Examine the logs in
/var/lib/mysql/data for more information.

You can try to start the mysqld daemon with:

    shell> su -s /bin/bash - mysql -c 'scl enable mysql55 -- /opt/rh/mysql55/root/usr/libexec/mysqld --skip-grant --general-log &'

and use the command line tool /opt/rh/mysql55/root/usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> scl enable mysql55 -- mysql -u root mysql
    mysql> show tables

Try 'scl enable mysql55 -- mysqld --help' if you have problems with paths.  Using --log
gives you a log in /var/lib/mysql/data that may be helpful.

Please consult the MySQL manual section
'Problems running mysql_install_db', and the manual section that
describes problems on your OS.  Another information source are the
MySQL email archives available at http://lists.mysql.com/.

Please check all of the above before submitting a bug report
at http://bugs.mysql.com/
```

I feel like we saw this issue previously but I can't remember what the resolution was.

**Comment by thoraxe** [comment]
NVM - just had to remove the volume defs.

**Comment by thoraxe** [comment]
LGTM.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
