### PR TITLE
Remove description field from types

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/7786

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@kargakis FYI

**Comment by deads2k** [comment]
Can you write a reflective test to make sure we don't miss any and none creep back in?  We already have similar tests for watching our API. `TestInternalJsonTags` as a for instance.

**Comment by mfojtik** [comment]
@deads2k yes, good idea

**Comment by mfojtik** [comment]
@deads2k updated the existing `checkDescriptions` test

**Comment by deads2k** [comment]
Test must be broken.  Its not checked in, but its not failing.  If you don't feel like looking into it, let me know when you merge this.

lgtm

**Comment by mfojtik** [comment]
@deads2k of course I forgot to push ;-)

**Comment by deads2k** [comment]
lgtm [merge]

**Pull request merged**
