### PR TITLE
Bz1654044

### PR DESCRIPTION
**Pull request by pecameron**
Cherry pick PR 21723 and PR 21796.

bug: 1654044
https://bugzilla.redhat.com/show_bug.cgi?id=1654044

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@danwinship PTAL

**Comment by pecameron** [comment]
@dcbw @danw do we still want to do this?

**Comment by danwinship** [comment]
is it needed to fix bz 1654044? If not, then I'd say no

**Comment by pecameron** [comment]
@danwinship at one point you said it was needed in 3.11 and 3.10 is that no longer the case? If we still need it I can drop the bug reference.

**Comment by danwinship** [comment]
I mean, 3.11 and earlier releases will have some of the same problems 4.0 used to with recovering after a service restart. But they *always* had those problems, and we never got around to fixing them, because restarts happen a lot less in 3.x. So if we don't have some specific customer issue that would be fixed by this backport, then it might not be worth the potential instability that the changes would introduce.

Hence my question: do we still believe that we need these changes in order to fix 1654044, or does the CNI conf fix alone already fix their problem?

**Comment by pecameron** [comment]
@danwinship This fix doesn't seem to have any impact on the problem. The tmpfile.d file seems to be the cure. Weibin has been testing with and without the fix. I am happy with closing this if its not needed.

**Comment by danwinship** [comment]
ok, let's close it then

**Pull request closed without merging**
