### PR TITLE
jUnit parsing for test-cmd output

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This PR introduces a new package, `cmd/junitparser`, which is a self-contained binary that parses the jUnit-directed output of `test-cmd`. The spec for that output will be determined soon.

TODO:
* ~~determine final output format for the output file for `test-cmd`~~
* ~~unit testing~~

/cc @danmcp @smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
lowecase bump

**Comment by deads2k** [comment]
I'll read the rest later. 

Please show sample usage.  Is there a related pull that generates this output from `test-cmd`?  We spoke yesterday and I suggested using the `expect_*` functions to output to an intermediate format

**Comment by stevekuznetsov** [comment]
@deads2k The related pull for `test-cmd` is https://github.com/openshift/origin/pull/5719. I think there will be two (parallel) series of output - one that's colorful and human-readable to `stdout`, and another specifically formatted for jUnit parsing (with this package). Sample usage is in the README and example input files will be added for unit tests.

**Comment by liggitt** [comment]
package typo: s/juntreport/junitreport/

**Comment by stevekuznetsov** [comment]
Good catch.

**Comment by stevekuznetsov** [comment]
Added unit testing. This is ready for review @smarterclayton @deads2k @liggitt

**Comment by stevekuznetsov** [comment]
I don't have high hopes for the upstream part of this - the maintainer hasn't been on GitHub in a couple months and there are pulls on the project that he closed because he didn't get around to seeing them before they became irrelevant. We may need to internalize that code-base. If we do that, I'll refactor it to accept different parsing extensions better.

**Comment by deads2k** [comment]
> I don't have high hopes for the upstream part of this - the maintainer hasn't been on GitHub in a couple months and there are pulls on the project that he closed because he didn't get around to seeing them before they became irrelevant. We may need to internalize that code-base. If we do that, I'll refactor it to accept different parsing extensions better.

Is there a better project to pull?  It's a small amount of code, so I don't have a huge objection, but you may as well make sure.

**Comment by soltysh** [comment]
I agree with @deads2k, but instead of loosing time to find such parser, how about writing one? From my previous experience with parsers and available resources ([here](http://blog.gopheracademy.com/advent-2014/parsers-lexers/) and [here](https://golang.org/cmd/yacc/)) I think that shouldn't be that hard. I can help you with that, or even take ownership for the parser part.

**Comment by stevekuznetsov** [comment]
Not that I saw, no. This specific project also was only made for go unit
test output so I could write my own that's better suited to handling
multiple parsing backends and formatting frontends.

**Comment by stevekuznetsov** [comment]
I've written the parsing pieces already, so doing the rest should be fairly straightforward.

**Comment by soltysh** [comment]
:+1:

**Comment by stevekuznetsov** [comment]
I will give the upstream maintainer some time before I take those actions. I've got the changes now in upstream commits. This is ready @deads2k

**Comment by stevekuznetsov** [comment]
Closing in favor of an internal solution.

**Pull request closed without merging**
