### PR TITLE
Use client interface for DCReaper

### PR DESCRIPTION
**Pull request by mdalstein**
This PR aims at aligning the openshift DeploymentConfig Reaper method signature to the [kubernetes ReplicationController Reaper](https://github.com/openshift/origin/blob/v1.3.0-alpha.2/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/stop.go#L91) already using a client interface.

The goal is not only to be consistent with k8s but also to enable unit testing of the DCReaper through fake clients, which is not possible as of today.

@sdminonne , @kargakis : FYI

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by sdminonne** [comment]
[test]

**Comment by mfojtik** [comment]
Flake: https://github.com/openshift/origin/issues/10051

this change LGTM, lets wait for at least one clean test run and then merge

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
