### PR TITLE
deep copy when creating build from buildconfig

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik added triggers to buildconfig describer, @soltysh fixed the buildconfig/build updating issue and added test cases.  review please.

**Comment by bparees** [comment]
here's what the describer output looks like now:
$ openshift cli describe buildConfig ruby-sample-build
Name:				ruby-sample-build
Annotations:			<none>
Created:			2015-01-15 15:43:59 -0500 EST
Strategy:			Custom
Builder Image:			172.30.17.3:5001/openshift/ruby-20-centos
Environment:			OPENSHIFT_CUSTOM_BUILD_BASE_IMAGE=172.30.17.3:5001/openshift/ruby-20-centos
Source Type:			Git
URL:				git://github.com/openshift/ruby-hello-world.git
Output Image:			openshift/origin-ruby-sample:latest
Output Registry:		172.30.17.3:5001
Webhook Github:			localhost/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/github
Webhook Generic:		localhost/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/generic
Image Repository Trigger:	ruby-20-centos
- Tag:				latest
- Image:			172.30.17.3:5001/openshift/ruby-20-centos
- LastTriggeredImageID:		d5667919de4785d2396a88703e30613482d01faf4c0684c4aa1d9683d5e33531

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
Lgtm

**Comment by mfojtik** [comment]
lgtm

**Comment by soltysh** [comment]
@bparees it would be good to also fix it (with tests :wink:) for [GenerateBuildFromBuild](https://github.com/openshift/origin/blob/master/pkg/build/util/generate.go#L27-L34) since we're doing exactly the same thing there, just with `Build->Build` objects.

**Comment by bparees** [comment]
@soltysh I debated fixing that one, I guess I will.

**Comment by soltysh** [comment]
LGTM.

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Review by DorisJeanParish — COMMENTED** [review]
I need the my debit card fix ID:04992193

**Pull request merged**
