### PR TITLE
UPSTREAM: 76021: Fix create secret generic paths examples

### PR DESCRIPTION
**Pull request by soltysh**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1693054

/assign @mfojtik

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
for after the rebase lands

**Comment by mfojtik** [comment]
/lgtm

Feel free to unhold when rebase lands.

**Comment by wking** [comment]
/hold

^stopping the restest bot because it keeps hitting [`error: build error: no such image`][1].  Tracking issue is [rhbz#1696483][2], in which @stevekuznetsov said:

> If this is affecting a PR, contact #forum-testplatform for intervention as the build cache in CI jobs will continually hit this issue and will not re-try the build.

so I've done that too ;).


[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22450/pull-ci-openshift-origin-master-e2e-aws/6376
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1696483

**Comment by soltysh** [comment]
/hold 
cancel, applying workaround

**Comment by wking** [comment]
[`could not wait for build: could not find build bin`][1].  Don't see anyone talking about that yet...

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22450/pull-ci-openshift-origin-master-images/4369

**Comment by wking** [comment]
Heh, finally :)

**Pull request merged**
