### PR TITLE
Add multi-node tests

### PR DESCRIPTION
**Pull request by legionus**
To test a multi-node cluster configuration uses docker. To reduce the complexity
of testing system being used host-based network.

@kargakis @pweil- please review this madness

### CODE REVIEW

**Comment by kargakis** [comment]
cc: @deads2k @liggitt

**Comment by pweil-** [comment]
There was a recent discussion about the number of supported deployment environments and how to reduce that number.  Specifically, in addition to bare metal, we are supporting ansible, vagrant (including multi-node vagrant), and docker-in-docker scripts.  

In the interest of having less to maintain, let's get input from folks that are probably using the multi-node setup the most for development: networking.  Maybe this can be worked in to or replace the existing dind scripts, I'd like to not introduce yet another setup.

@eparis @ramr @rajatchopra @danwinship @knobunc

**Comment by danwinship** [comment]
FYI there's an @openshift/networking team you can tag. And @marun would be the best person to ask about this anyway since he did the docker-in-docker stuff.

**Comment by marun** [comment]
@legionus Have you used openshift's dind deployment [1] and found it wanting?  The networking team is already using it for development and ci testing [2] of multinode openshift, and ideally I would like to see dind evolve rather than replace it with something brand new.

1: https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-and-test-using-a-docker-in-docker-cluster 
2: https://ci.openshift.redhat.com/jenkins/job/networking_extended/

**Comment by legionus** [comment]
Yes, I saw it, but `OPENSHIFT_DIND_DEV_CLUSTER=true vagrant up` is too slow for me. That's why I wrote this.

Anyway, decision has been made I'll not insist on my changes. I'll try to rewrite my tests with dind.

**Comment by marun** [comment]
@legionus The initial startup of deploying a cluster with vagrant is slow, yes, and if that cost had to be paid all the time it wouldn't be useful.  As per the docs, though, the reason for the slowness is installing dependencies in the vm and images.  Once that's done, cluster management with hack/dind-cluster.sh can be much faster.  Here's some other tips that may improve your experience:

 - Setting OPENSHIFT_SKIP_BUILD=true will skip the go build and just deploy.  On a reasonable host it will take ~30s to tear down and relaunch a cluster.
 - It's possible to deploy multiple clusters on a given host by varying the OPENSHIFT_INSTANCE_PREFIX flag when invoking dind-cluster.sh.  This is used by the test/extended/networking.sh to run a separate cluster per network plugin without affecting user-launched clusters.  
 - dind-cluster.sh creates an .rc file for each cluster it deploys as an additional way to manage multiple clusters.  source the rc, then 'oc' etc target the cluster associated with the rc.
 - dind-cluster.sh has a 'redeploy' command that can rebuild binaries, push them to the cluster nodes and restart the services.  If used with the skip build flag it will take ~3s to refresh the code on the cluster.
 - It's suggested but not necessary to provision dind clusters in a vm.  I defaulted to a vm to support users who weren't on linux, but if you are ok with disabling selinux (or figuring out how to run it with selinux) it can run as easily directly on your host.  Just make sure to read the docs in dind-cluster.sh so you're aware of what it's doing.

Hope this helps, and let me know if you have further issues.

**Comment by legionus** [comment]
I have a problem with dind-cluster.sh. I can't run the registry in a cluster. Here is my log:

https://gist.github.com/legionus/eb88f460cc832be25e5b

Can you help me ?

**Comment by marun** [comment]
@legionus A few comments:

 - It appears from the gist that you are not running latest master since disabling the sdn node is not happening at the end of deployment.  #7813 changed that order (among other things) to speed things up a bit.
 - The failure to retrieve logs is likely the result of a too-restrictive firewall that was preventing the api from talking to the kubelet.  This was fixed by #7261.
 - Special pods like the integrated docker registry and the router interact with openshift and depend on the use of secrets to acquire the configuration/certs necessary to do so.  Unfortunately docker < 1.10 doesn't support mount propagation and this is required for secrets to work under dind.  I have a PR pending on docker 1.10 GA (#7668) that I have tested to support secrets properly.  As per the PR's description, it will be necessary to install docker 1.10 on the host and ensure that mount propagation for the daemon is not set to private.

**Comment by pweil-** [comment]
@legionus in light of the above comment you could add the extended test that uses dind and check the docker version in the test startup to determine whether or not the test should be skipped on unsupported machines for now.  There are other tests that do the same thing.  The one that comes to mind is supplemental groups, however supplemental groups is not using semver and it should be (which is my fault).  We probably want to change that test while we're at it.

https://github.com/pweil-/origin/blob/2cb2a753beb0de6830d93d4c179a82125288e5a9/test/extended/security/supplemental_groups.go#L99-99

**Comment by pweil-** [comment]
I would recommend adding a helper function so that it is globally available and just call that function with the required minimum supported version.

**Pull request closed without merging**
