### PR TITLE
Changes to support openshift-sdn reorganization

### PR DESCRIPTION
**Pull request by pravisankar**
Depends on https://github.com/openshift/openshift-sdn/pull/159

### CODE REVIEW

**Comment by danwinship** [comment]
needs to remove plugins/osdn too right?

**Comment by pravisankar** [comment]
No need to remove plugins/osdn dir.
I'll create a bump commit once we merge https://github.com/openshift/openshift-sdn/pull/159 and that will sync openshift-sdn/pkg --> origin/Godeps/_workspace/src/openshift/openshift-sdn/pkg and
openshift-sdn/plugins/osdn --> origin/plugins/osdn

**Comment by danwinship** [comment]
ah... I didn't notice that that's what sync-to-origin.sh did. But it shouldn't do that; that means you're not allowed to edit origin/plugins/osdn, because it will get overwritten by the next openshift-sdn merge. And there's no reason origin needs to be pulling that code out of origin/plugins/osdn rather than openshift-sdn/plugins/osdn (via Godeps).

**Comment by pravisankar** [comment]
Removed origin/plugins/osdn, sdn plugins will be synced to origin/Godeps/.../openshift-sdn/plugins/

**Comment by pravisankar** [comment]
@danwinship PTAL

**Comment by danwinship** [comment]
lgtm

**Comment by pravisankar** [comment]
[merge]

**Pull request merged**
