### PR TITLE
OPNET-606: on-prem: fix haproxy test to include openstack and vsphere

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
/retitle OPNET-606: on-prem: fix haproxy test to include openstack and vsphere

**Comment by deads2k** [comment]
/lgtm
/approve
/hold

holding so you can confirm output.  Feel free to release the hold once confirmed.

**Comment by mkowalski** [comment]
/hold cancel

I can see intervals in OpenStack job -- https://sippy.dptools.openshift.org/sippy-ng/job_runs/1851997926524456960/pull-ci-openshift-origin-master-e2e-openstack-ovn/openshift_origin/29252/intervals?filterText=&intervalFile=e2e-timelines_spyglass_20241031-162919.json&overrideDisplayFlag=0&selectedSources=OperatorAvailable&selectedSources=OperatorProgressing&selectedSources=OperatorDegraded&selectedSources=APIServerGracefulShutdown&selectedSources=KubeEvent&selectedSources=NodeState&selectedSources=OnPremHaproxyMonitor

**Pull request merged**
