### PR TITLE
Bug 2089276: Detect and use the packet capture interface for EgessIP tests.

### PR DESCRIPTION
**Pull request by andreaskaris**
Detect and use the packet capture interface for EgressIP tests. In the
case of SDN, this is the default route of the nodes. In the case of
OVNK, replicate logic found in the OVNK repo to find the main system
interface that belongs to bridge br-ex. Using the physical egress
interface for packet captures fixes a bug where the same interface would
be accounted for 2x.

Fixes failures on OpenShift SDN with the current implementation:
* https://search.ci.openshift.org/?search=Feature%3AEgressIP&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
* https://prow.ci.openshift.org/job-history/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-azure-techpreview-serial

Tested on GCP OVNKubernetes (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] only pods matched by the pod selector should have the EgressIPs [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be updated [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
~~~

Tested on AWS OVNKubernetes (/)
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] only pods matched by the pod selector should have the EgressIPs [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be updated [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
~~~

Tested on GCP OpenShift SDN (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] EgressIPs can be assigned automatically [Skipped:Network/OVNKubernetes] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
~~~

Tested on AWS OpenShift SDN (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] EgressIPs can be assigned automatically [Skipped:Network/OVNKubernetes] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
~~~

Tested on Azure OpenShift SDN (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] EgressIPs can be assigned automatically [Skipped:Network/OVNKubernetes] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
~~~

### CODE REVIEW

**Comment by andreaskaris** [comment]
@jluhrsen Can you PTAL?

**Comment by jluhrsen** [comment]
/lgtm

btw, the aws-serial failure is a new common problem prom failure. you'll have to
/retest
it a bunch of times to get it to pass I think.

**Pull request merged**
