### PR TITLE
oc: inform about switch to the same project

### PR DESCRIPTION
**Pull request by kargakis**
@deads2k PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by deads2k** [comment]
Why is the distinction valuable?  I see the command as declarative, not imperative, and the end result is identical.

**Comment by kargakis** [comment]
@deads2k this mimics `git checkout`. End result is the same but UX is slightly better?

cc: @fabianofranz

**Comment by deads2k** [comment]
Code looks fine.  I'll leave the UI decision up to @fabianofranz .

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/9089 flake

[merge]

**Comment by kargakis** [comment]
same flake, re[merge]

**Comment by kargakis** [comment]
[merge]

**Comment by deads2k** [comment]
flake fixed [merge]

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/7706 flaked

[merge]

**Comment by kargakis** [comment]
[merge]

**Comment by fabianofranz** [comment]
srsly [merge]

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
