### PR TITLE
Migrate YAML files to v1beta3

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton @kargakis FYI

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by kargakis** [comment]
:+1:

**Comment by mfojtik** [comment]
@smarterclayton comment restored

**Comment by mfojtik** [comment]
@liggitt fixed ServiceAccount

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
