### PR TITLE
add a wordpress template

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@markturansky ptal.

**Comment by bparees** [comment]
@thoraxe fyi

**Comment by bparees** [comment]
[test]

**Comment by markturansky** [comment]
The mysql pod starts up fine but I must have an imageStream error of some kind and cannot make the wordpress image.

**Comment by markturansky** [comment]
```
E1106 16:51:10.230253   12016 config_controller.go:55] error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:10.230281   12016 factory.go:175] Retrying BuildConfig default/wordpress-mysql-example: error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:11.224935   12016 config_controller.go:20] Handling BuildConfig default/wordpress-mysql-example
I1106 16:51:11.224970   12016 config_controller.go:38] Running build for BuildConfig default/wordpress-mysql-example
I1106 16:51:11.228360   12016 generator.go:169] Generating Build from BuildConfig: default/wordpress-mysql-example, LastVersion: 0
I1106 16:51:11.228759   12016 generator.go:436] Resolving ImageStreamReference php:5.5 of Kind ImageStreamTag in namespace openshift
I1106 16:51:11.228985   12016 generator.go:453] Error resolving ImageStreamTag reference php:5.5 in namespace openshift: imageStream "php" not found
E1106 16:51:11.229261   12016 config_controller.go:55] error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:11.229288   12016 factory.go:175] Retrying BuildConfig default/wordpress-mysql-example: error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:12.224820   12016 config_controller.go:20] Handling BuildConfig default/wordpress-mysql-example
I1106 16:51:12.224849   12016 config_controller.go:38] Running build for BuildConfig default/wordpress-mysql-example
I1106 16:51:12.263757   12016 generator.go:169] Generating Build from BuildConfig: default/wordpress-mysql-example, LastVersion: 0
I1106 16:51:12.264218   12016 generator.go:436] Resolving ImageStreamReference php:5.5 of Kind ImageStreamTag in namespace openshift
I1106 16:51:12.264423   12016 generator.go:453] Error resolving ImageStreamTag reference php:5.5 in namespace openshift: imageStream "php" not found
E1106 16:51:12.264671   12016 config_controller.go:55] error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:12.264696   12016 factory.go:175] Retrying BuildConfig default/wordpress-mysql-example: error instantiating Build from BuildConfig default/wordpress-mysql-example: imageStream "php" not found
I1106 16:51:12.265836   12016 nodecontroller.go:607] Nodes ReadyCondition updated. Updating timestamp: {Capacity:map[cpu:{Amount:8.000 Format:DecimalSI} memory:{Amount:16699486208.000 Format:BinarySI} pods:{Amount:40.000 Format:DecimalSI}] Phase: Conditions:[{Type:Ready Status:True LastHeartbeatTime:2015-11-06 16:50:57 -0500 EST LastTransitionTime:2015-11-06 16:48:27 -0500 EST Reason:KubeletReady Message:kubelet is posting ready status}] Addresses:[{Type:LegacyHostIP Address:10.0.0.14} {Type:InternalIP Address:10.0.0.14}] DaemonEndpoints:{KubeletEndpoint:{Port:10250}} NodeInfo:{MachineID:70faa825adab496e89b2e18a5a180e5d SystemUUID:816D361F-7953-CB11-9F88-81232D0B0718 BootID:87c06778-011d-482f-a4e6-1e20d048dd7f KernelVersion:4.1.6-200.fc22.x86_64 OsImage:Fedora 22 (Twenty Two) ContainerRuntimeVersion:docker://1.7.1.fc22 KubeletVersion:v1.2.0-alpha.1-1107-g4c8e6f4 KubeProxyVersion:v1.2.0-alpha.1-1107-g4c8e6f4}}
 vs {Capacity:map[cpu:{Amount:8.000 Format:DecimalSI} memory:{Amount:16699486208.000 Format:BinarySI} pods:{Amount:40
```

**Comment by bparees** [comment]
@markturansky you've got to install the imagestreams first.
https://docs.openshift.org/latest/install_config/install/first_steps.html#creating-image-streams-for-openshift-images

https://github.com/openshift/origin/tree/master/examples/image-streams

**Comment by bparees** [comment]
(or install them now and run another build)

**Comment by bparees** [comment]
readme updated.

**Comment by markturansky** [comment]
thanks!

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
ui test failure.  [merge]

**Pull request merged**
