### PR TITLE
openshift-diagnostics => diagnostics subcommands

### PR DESCRIPTION
**Pull request by sosiouxme**
Builds on commit from https://github.com/openshift/origin/pull/17773 (diagnostics: individual parameters).
Removes `openshift-diagnostics` in favor of hidden `oc adm diagnostics` subcommands as proposed with https://github.com/openshift/origin/pull/18149#issuecomment-358924865.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534513 and https://github.com/openshift/origin/issues/18141

### CODE REVIEW

**Comment by sosiouxme** [comment]
Fixed bug that e2e test uncovered. Should be good now.
Other test failure was a flake.

**Comment by sosiouxme** [comment]
@deads2k any chance we could get this in today?

One more alternative: don't try to make these diagnostics subcommands. Instead, just create hidden `oc adm inpod-diagnostics` or similar. That wouldn't require pulling in the other PR.

**Comment by juanvallejo** [comment]
/lgtm
from a cli perspective

**Comment by sosiouxme** [comment]
Rebased and squashed.

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18186/test_pull_request_origin_extended_conformance_install/5951/ looks like https://github.com/openshift/origin/issues/17882
/test extended_conformance_install

**Comment by sosiouxme** [comment]
@juanvallejo and @deads2k this is just waiting for your lgtm and approval (respectively). Base PR https://github.com/openshift/origin/pull/17773 was lgtm/approved but needed tweaks to pass tests; we can ask @soltysh to lgtm that again if you want to merge it separately, or do both at once via this PR. Just looking to proceed with this blocker however you think that's best.

**Comment by juanvallejo** [comment]
@sosiouxme looks like completions were the only thing that changed in https://github.com/openshift/origin/pull/17773? If so, @deads2k I'm fine with merging it in one go in this PR.

/lgtm

**Comment by deads2k** [comment]
I'm fine with it in principle.  @soltysh has final approval.

@soltysh check the owners files and figure out which one you don't have rights to.

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin/pull/17773 merged so this is really just the second commit.

**Comment by soltysh** [comment]
> @soltysh check the owners files and figure out which one you don't have rights to.

docs/man was one, but this PR touches much more dirs: hack, images, contrib which I don't need approval rights for oc itself.

**Comment by sosiouxme** [comment]
Rebased (should have seen that coming).

**Comment by stevekuznetsov** [comment]
/lgtm
for rebase commit

**Comment by sosiouxme** [comment]
Bad luck, https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18186/test_pull_request_origin_extended_conformance_gce/14947/ hit a rare one -- https://github.com/openshift/origin/issues/15059

/retest

**Pull request merged**
