### PR TITLE
UPSTREAM: 16052: Control /etc/hosts in the kubelet

### PR DESCRIPTION
**Pull request by smarterclayton**
Kubelet now manages /etc/hosts instead of docker

Referenced from #5107

[test]

@liggitt @ncdc needs review and a fair confidence it will work.

### CODE REVIEW

**Comment by smarterclayton** [comment]
[extended:core]

**Comment by ncdc** [comment]
I can look after the upgrade script work is done, or I can put that all in Steve's hands if you want me to review this now.

**Comment by smarterclayton** [comment]
DNS is broken in Docker 1.8 without this.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
I need someone familiar with the Kubelet, doesn't have to be you.

**Comment by liggitt** [comment]
where is the docker prereq being managed?

**Comment by smarterclayton** [comment]
It's already in 1.8 and 1.9 from RH

**Comment by liggitt** [comment]
we're prereqing 1.8.x?

**Comment by smarterclayton** [comment]
[test]

**Comment by eparis** [comment]
Yes, storage requirements adds a 1.8.2 pre-req

**Pull request merged**
