### PR TITLE
add `oc adm version` command

### PR DESCRIPTION
**Pull request by juanvallejo**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1498356

Adds version cmd to `oc adm`

**Example**
```
$ oc adm version
oc adm v3.7.0-alpha.1+afd90cd-822-dirty
kubernetes v1.7.0+80709908fd

...
```

cc @openshift/cli-review

### CODE REVIEW

**Comment by detiber** [comment]
@juanvallejo I commented on the bz as well, but doesn't `oc version` already provide this?

**Comment by juanvallejo** [comment]
@detiber 
>  I commented on the bz as well, but doesn't oc version already provide this?

Thanks, if I'm understanding the bugzilla correctly, it would solve a scriptability use-case on platforms where we don't ship the oadm binary

**Comment by detiber** [comment]
> Thanks, if I'm understanding the bugzilla correctly, it would solve a scriptability use-case on platforms where we don't ship the oadm binary

@juanvallejo that is my understanding as well. Currently they are running `oadm version` and requested `oc adm version` be added. I'm just not sure what is gained by having an `oc adm version` command that isn't already available by using `oc version`. The user already has the oc client, otherwise they couldn't run `oc adm` commands. The only benefit I see to adding an `oc adm version` command is that one could blindly replace all instances of `oadm` with `oc adm` in existing scripts.

**Comment by stevekuznetsov** [comment]
I think I'm in agreement with @detiber here, not sure of the value add here.

**Comment by fabianofranz** [comment]
Closing as per my comment in [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=1498356).

**Pull request closed without merging**
