### PR TITLE
allow proxy values to be specified with non-http git uris

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
bug 1397475

@oatmealraisin ptal.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
forgot @oatmealraisin is on pto.  @csrwng ptal.

**Comment by csrwng** [comment]
@bparees the change LGTM. Just curious though, what is the use case?

**Comment by bparees** [comment]
@csrwng sorry my commit message was a bit obscure, it's this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1397475

**Comment by bparees** [comment]
basically the scenario is when you have a cluster proxy default setup, but your buildconfig uses ssh.

**Comment by bparees** [comment]
[merge]

**Comment by csrwng** [comment]
@bparees thx, makes sense

**Pull request merged**
