### PR TITLE
DO NOT MERGE Add podpreset to edit and view role

### PR DESCRIPTION
**Pull request by pmorie**
Adds appropriate permissions for `PodPreset` to the edit and view roles.

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by derekwaynecarr** [comment]
i had discussed this with @liggitt -- i am not sure the precedent of doing this by default for features that are disabled, versus doing it as a post-install hook.

**Comment by pmorie** [comment]
@derekwaynecarr yeah, agree - I had a good heart, garbage brain.

**Comment by enj** [comment]
Did you forget `admin`?

And yes, it seems strange to add permissions for something that is not enabled but I will defer to @deads2k and @liggitt for what we have done in the past.

**Comment by enj** [comment]
I think we decided against this so closing.

**Pull request closed without merging**
