### PR TITLE
Wait until animation finishes to call chart.flush()

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1289843

@jwforres We can still open an upstream bug, but this is basically what we were doing before and works around the problem reliably in my testing.

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
