### PR TITLE
Default DNS name should change

### PR DESCRIPTION
**Pull request by smarterclayton**
@deads2k this isn't perfect but it's better than what we have

### CODE REVIEW

**Comment by liggitt** [comment]
we'd expect a route to be "foo.router.default.svc.cluster.local"? I didn't think the route dns bits were using service resolution

**Comment by deads2k** [comment]
I don't see why this matters.  I don't object, but I don't see why we'd care.

**Comment by deads2k** [comment]
> we'd expect a route to be "foo.router.default.svc.cluster.local"?

"my-service.my-project.router.default.svc.cluster.local" instead of "my-service.my-project.router.router.default.local" .

**Comment by smarterclayton** [comment]
router.default.local doesn't point to anything.
 router.default.vc.cluster.local does.  It means out of the box, inside the
cluster, routes resolve by default in a standard setup.

On Fri, Jul 17, 2015 at 7:42 AM, David Eads <notifications@github.com>
wrote:

> we'd expect a route to be "foo.router.default.svc.cluster.local"?
>
> "my-service.my-project.router.default.svc.cluster.local" instead of
> "my-service.my-project.router.router.default.local" .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3749#issuecomment-122253031>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> router.default.local doesn't point to anything.
>  router.default.vc.cluster.local does.  It means out of the box, inside the
> cluster, routes resolve by default in a standard setup

Why didn't our e2e router test catch this?  Do we need to update that test?

**Comment by smarterclayton** [comment]
It doesn't test the wildcard setup - it can though.

On Jul 17, 2015, at 10:44 AM, David Eads <notifications@github.com> wrote:

router.default.local doesn't point to anything.
router.default.vc.cluster.local does. It means out of the box, inside the
cluster, routes resolve by default in a standard setup

Why didn't our e2e router test catch this? Do we need to update that test?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3749#issuecomment-122297858>.

**Comment by deads2k** [comment]
> It doesn't test the wildcard setup - it can though.

You want to do it here or open another issue?  This lgtm, I'll leave the merge to you depending on your preference.

**Comment by smarterclayton** [comment]
I'm testing it now.

On Fri, Jul 17, 2015 at 10:53 AM, David Eads <notifications@github.com>
wrote:

> It doesn't test the wildcard setup - it can though.
>
> You want to do it here or open another issue? This lgtm, I'll leave the
> merge to you depending on your preference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/3749#issuecomment-122300180>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
It's too hard to make work - I'm getting weird hangs.  [merge] will come
back later.

On Fri, Jul 17, 2015 at 12:40 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> I'm testing it now.
>
> On Fri, Jul 17, 2015 at 10:53 AM, David Eads <notifications@github.com>
> wrote:
>
>> It doesn't test the wildcard setup - it can though.
>>
>> You want to do it here or open another issue? This lgtm, I'll leave the
>> merge to you depending on your preference.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/3749#issuecomment-122300180>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
