### PR TITLE
Fix EmptyDir mounting for dind

### PR DESCRIPTION
**Pull request by marun**
Support for mount propagation is included in docker 1.10.  This fixes EmptyDir support for dind which allows secrets and the downward api to work correctly (#6589).

This patch was tested against upstream docker 1.10 on fedora 23.  It was necessary to remove MountFlags=private from the upstream provided /usr/lib/systemd/system/docker.service to allow the nested docker to use shared propogation on /.  

This PR should not be merged until the official docker 1.10 packages land in fedora 23.

[skuznets edit:]
fixes https://github.com/openshift/origin/issues/9279

### CODE REVIEW

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by knobunc** [comment]
LGTM (once fedora has the new version)

**Comment by marun** [comment]
[test]

**Comment by marun** [comment]
@danwinship This PR is finally useful now that docker 1.10 is the default in fedora and centos.  It fixes the test failure you were seeing.

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by marun** [comment]
@stevekuznetsov How to run the networking extended tests to verify this before merge?

**Comment by stevekuznetsov** [comment]
Very recently we've changed the syntax...

`[testextended][extended:networking]`

**Comment by marun** [comment]
@openshift/networking @smarterclayton Please merge asap so the pre-merge job can be re-enabled.

**Comment by smarterclayton** [comment]
Running https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_pull_requests_origin_networking/1148/

**Comment by stevekuznetsov** [comment]
`test_pr_origin_extended:networking != test_pull_requests_origin_networking` ? That's news to me

**Comment by stevekuznetsov** [comment]
`test_pull_requests_origin_networking`:
```
vagrant sync-origin -s --dont-install
vagrant test-origin --extended "$EXTENDED_TESTS" -d --skip-check --skip-image-cleanup
```

`test_pr_origin_extended`:
```
vagrant sync-origin -s
vagrant test-origin --extended "$EXTENDED_TESTS" -d --skip-check --skip-image-cleanup --image-registry ci.dev.openshift.redhat.com:5000
```

Is there a functional difference?

**Comment by smarterclayton** [comment]
network run passed [merge]

**Comment by marun** [comment]
@stevekuznetsov --image-registry is unnecessary - a remnant of a failed experiment.  Not sure what's up with the differing sync-origin commands.

**Comment by stevekuznetsov** [comment]
@smarterclayton we should probably bring those jobs in sync and get rid of
one of them, then.

**Comment by smarterclayton** [comment]
Technically networking and conformance are just test suites - extended is a
pattern for multiple suites.  So there's nothing really to remove - we just
don't run the other suites on PRs because they aren't useful enough yet on
their own or are too slow.

**Pull request merged**
