### PR TITLE
Remove duplicate uuid package

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
Hmm, still used in `docker/distribution`
```
Godeps/_workspace/src/github.com/docker/distribution/context/context.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/context/http.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/context/trace.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/registry/storage/layerstore.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/registry/storage/purgeuploads.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/registry/storage/purgeuploads_test.go:	"code.google.com/p/go-uuid/uuid"
Godeps/_workspace/src/github.com/docker/distribution/Godeps/Godeps.json:	"ImportPath": "code.google.com/p/go-uuid/uuid",
Godeps/_workspace/src/github.com/docker/distribution/notifications/bridge.go:	"code.google.com/p/go-uuid/uuid"
```

**Comment by kargakis** [comment]
Newest version of `docker/distribution` uses its own `uuid` package though upgrade from 2.0 to 2.1 has its own implications ...

https://github.com/docker/distribution/releases/tag/v2.1.0

**Comment by liggitt** [comment]
maybe open an issue to track updating the docker distribution... we're probably not going to do that right this moment. maybe mention removing this UUID package in the issue

**Comment by kargakis** [comment]
done: https://github.com/openshift/origin/issues/4339

**Comment by kargakis** [comment]
@pweil- fyi

**Pull request closed without merging**
