### PR TITLE
use k8s helper to retrieve tls client config

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1441929

### CODE REVIEW

**Comment by bparees** [comment]
@ncdc ptal

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by ncdc** [comment]
@bparees looks good. You test it manually?

**Comment by bparees** [comment]
@ncdc yeah

**Comment by bparees** [comment]
[merge]

**Pull request merged**
