### PR TITLE
UPSTREAM: kubernetes-incubator/cluster-capacity: 81: Fix cluster-capacity to avoid pending pods not created by it.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1449891

@derekwaynecarr @sjenning  @eparis @chengzhang1016

### CODE REVIEW

**Comment by aveshagarwal** [comment]
[test]

**Comment by eparis** [comment]
[test] no way this break oc new-app....

**Comment by eparis** [comment]
[test]
[merge]  though on green test this should go by hand.

**Comment by eparis** [comment]
test clean. 0 core risk. merging by hand to keep queue open for important things.

**Pull request merged**
