### PR TITLE
use new api install method

### PR DESCRIPTION
**Pull request by deads2k**
reacts to https://github.com/openshift/api/pull/67

### CODE REVIEW

**Comment by deads2k** [comment]
dependent merged.  This is the minimal change required to move forward with other API changes.  We'll better integrate later.

**Comment by deads2k** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20200/test_pull_request_origin_extended_builds/1882/

```
 1. Hosts:    localhost
     Play:     Service Catalog
     Task:     openshift_service_catalog : oc_process
     Message:  [{u'kind': u'Role', u'returncode': 1, u'stdout': u'', u'cmd': u'/bin/oc create -f /tmp/extension-apiserver-authentication-reader-zmm2fh -n kube-system', u'results': {}, u'stderr': u'Error from server (AlreadyExists): error when creating "/tmp/extension-apiserver-authentication-reader-zmm2fh": object is being deleted: roles.rbac.authorization.k8s.io "extension-apiserver-authentication-reader" already exists\n'}, {u'cmd': u'/bin/oc create -f /tmp/extension-apiserver-authentication-reader-binding-121HB6 -n kube-system', u'kind': u'RoleBinding', u'returncode': 0, u'results': {}}]
```

/retest

**Comment by liggitt** [comment]
tests are green, nothing overlapping merged to master since. queue is down, merging to unblock other API bumps ahead of 3.11 freeze

**Pull request merged**
