### PR TITLE
Treat the missing binary message as an info not warning

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov your failing job links don't work.

**Comment by stevekuznetsov** [comment]
Hm. Thats weird

**Comment by stevekuznetsov** [comment]
Those jobs died before uploading anything to GCS. I'll add a jenkins link so at least there's a way to figure it out

**Pull request merged**
