### PR TITLE
UPSTREAM: google/cadvisor: 1722: Skip subcontainer update on v2 calls

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/google/cadvisor/pull/1722

This change results in a significant CPU reduction on the node.

@derekwaynecarr @eparis @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Commit name needs to be `UPSTREAM: google/cadvisor: 11...: ....`

**Comment by smarterclayton** [comment]
You can self apply lgtm after the commit name is fixed

**Comment by sjenning** [comment]
encountering test issue https://github.com/openshift/origin/issues/15874

**Pull request merged**
