### PR TITLE
UPSTREAM: googleapis/gnostic/compiler: 00000: Bad perf

### PR DESCRIPTION
**Pull request by smarterclayton**
Detected in #15326

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k this was 6 million allocations during integration test start (out of about 16 million total).  I think that might shave as much as a third off the total time remaining on integration (rerunning the bits).

We should work with upstream.

**Comment by deads2k** [comment]
> @deads2k this was 6 million allocations during integration test start (out of about 16 million total). I think that might shave as much as a third off the total time remaining on integration (rerunning the bits).

Heh, ouch.  Want to compare against my big hammer? https://github.com/openshift/origin/pull/15537  We don't actually need openapi for integration tests

**Comment by smarterclayton** [comment]
I figured out what he was using the regex for.  String prefixes.  So I'm going to fix that and get a good upstream.  I don't think we'll have to turn off open api after that, but I was not seeing it in my profiles after I fixed the obvious stuff.

**Comment by deads2k** [comment]
> I figured out what he was using the regex for. String prefixes. So I'm going to fix that and get a good upstream. I don't think we'll have to turn off open api after that, but I was not seeing it in my profiles after I fixed the obvious stuff.

My pull got test-integration to 90 minutes, this one is at 110 minutes.

**Comment by smarterclayton** [comment]
Might be useful to know where that 20s is coming from.

**Pull request closed without merging**
