### PR TITLE
Add DisableAttachDetachReconcilerSync new flag to master_config_test

### PR DESCRIPTION
**Pull request by soltysh**
This is a followup to #12481, the new flag wasn't added to tests, so we won't know when it changes during next rebase.

@deads2k we've spoke about it on IRC, ptal

### CODE REVIEW

**Comment by deads2k** [comment]
> This is a followup to #12481, the new flag wasn't added to tests, so we won't know when it changes during next rebase.

Won't we know if it changes because it will no longer match the zero value?

**Comment by soltysh** [comment]
I think we keep all around to inform, yes we know about it and it should be just that value, if that was changed be explicit about your actions. At least that's how I understood that test to work.

**Comment by deads2k** [comment]
> I think we keep all around to inform, yes we know about it and it should be just that value, if that was changed be explicit about your actions. At least that's how I understood that test to work.

Ok. No strong opinion. If you can merge pulls, this can merge.

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
