### PR TITLE
[release-4.12] Update annotations to account for removal of duplicate whitespace

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-666](https://issues.redhat.com//browse/TRT-666)

Since the 1.25 rebase, these tests no longer have the double whitespace in their names, so they are no longer properly skipped.  Metal IPv6 jobs are running these build tests[1] that do not work in disconnected environments.

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-ovn-ipv6/1589866980129640448

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
No longer needed

**Pull request closed without merging**
