### PR TITLE
let registry-admin delete his project

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/8714

Also cleans up the API groups in the roles I touched.

@legionus ptal

### CODE REVIEW

**Comment by legionus** [comment]
@deads2k I don't have enough competence in this, but LGTM.

**Comment by deads2k** [comment]
> @deads2k I don't have enough competence in this, but LGTM.

@liggitt @sgallagher This should be adding "delete" "projects" and separating the rules so they have the proper API groups.

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by sub-mod** [comment]
needed for https://github.com/cockpit-project/cockpit/pull/4346

**Pull request merged**
