### PR TITLE
Bug 1713674: toggle ssh parameters if ssh-auth source secret includes a known_host…

### PR DESCRIPTION
**Pull request by gabemontero**
…s setting

manually cherr-picked the 3.11 comment in https://github.com/openshift/origin/pull/23782 given the issues there with the e2e-gcp-crio job

/assign @adambkaplan
/assign @bparees 
@openshift/openshift-team-developer-experience FYI

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Not clear if cherry-pick-approver is enabled for this branch

@gabemontero @bparees does `extended_conformance_install` run the build suite for 3.9?

**Comment by gabemontero** [comment]
only a subset at best @adambkaplan 

back in the 3.9 days, with rosie and aos-cd-jobs, I think it used to be

/test extended_builds

**Comment by gabemontero** [comment]
which is what I see in the 3.10 PR, but it doesn't seem to work here (at least anymore)

And when I look at ci.openshift.redhat.com, I only see test_branch_origin_extended_builds_310 and _311

I suspect the best we'll get for 3.9 is conformance install

**Pull request merged**
