### PR TITLE
make the build generator rely on clients, not registries

### PR DESCRIPTION
**Pull request by deads2k**
To be separated into API servers, different API groups cannot rely upon direct etcd access to other API groups.  Also, with the introduction of the "system:masters" authenticator, the loopback client does not have a bootstrapping order problem.

This pull eliminates some direct to etcd access by the build generator.

### CODE REVIEW

**Comment by deads2k** [comment]
> /test extended_builds

wow, it takes longer than the install_update?

**Comment by deads2k** [comment]
> wow, it takes longer than the install_update?

@bparees is this all serial or something?  This is bonkers.

**Comment by bparees** [comment]
@deads2k 
```
OPENSHIFT_SKIP_BUILD='true' KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY=true JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="\[builds\]"
```

that's all it's doing.  I wouldn't expect that to be any different than how we run any other ginkgo tests, no?

**Comment by deads2k** [comment]
final count 2h50m.  Note to self to check on this tomorrow.  Having our queue stuck for three hours for it to run would suck.

**Comment by bparees** [comment]
3 hours is on par with the other runs. Why it's not parallel I'm not sure
(if indeed it's not)

Ben Parees | OpenShift

**Pull request merged**
