### PR TITLE
sync openshift-sdn

### PR DESCRIPTION
**Pull request by danwinship**
Includes
- https://github.com/openshift/openshift-sdn/pull/269 - remove some dead code
- https://github.com/openshift/openshift-sdn/pull/272 - fix a bug in the bandwidth shaping code
- https://github.com/openshift/openshift-sdn/pull/270 - refactoring
- https://github.com/openshift/openshift-sdn/pull/276 - add macvlan annotation to support egress-router (#8330)

@openshift/networking PTAL

### CODE REVIEW

**Comment by eparis** [comment]
Is this stuff we NEED in 3.2?  Or should we wait for 3.3.

**Comment by danwinship** [comment]
ok, so i was thinking the egress router was 3.3 but it's really 3.2... man, I wish someone had told me. I could have been slacking off.

Anyway, we need the patch for 272 to fix something else that already landed in origin. What is the right way to do that? A kubernetes-style UPSTREAM commit?

**Comment by eparis** [comment]
I think so, yes.

**Comment by pravisankar** [comment]
Do not merge this PR without this change https://github.com/openshift/openshift-sdn/pull/278

**Comment by eparis** [comment]
@danwinship you could have been slacking off.  I suggest we close this PR and you/ravi work together for a bugfix only set of cherry-picks....

**Comment by danwinship** [comment]
ok

**Pull request closed without merging**
