### PR TITLE
authentication: define image for basic auth provider

### PR DESCRIPTION
**Pull request by sosiouxme**
https://trello.com/c/5VJeE8Tu/370-ldap-basicauthurl-image

### CODE REVIEW

**Comment by liggitt** [comment]
Do we want this in repo? Feels like a good standalone example

**Comment by sosiouxme** [comment]
@liggitt it's a good question. Initially this was targeted at a standard [LDAP authenticator](https://trello.com/c/5VJeE8Tu/370-ldap-basicauthurl-image). You're doing that a different way, plus we don't support mod_ldap, so the use case is less essential now. I'm certainly open to moving it elsewhere if preferred.

Was also wondering who would review this if we keep it in origin?

**Comment by liggitt** [comment]
Since this is more of an example server for the basic auth identity provider to connect to, I wouldn't make it part of origin... not sure if there's a better back-end to target as an example, with LDAP now being supported natively

**Comment by sosiouxme** [comment]
@danmcp can you make me a repository to put this in? Or if there's a better place to put examples...

Perhaps "basic-authentication-provider-example" repo

**Comment by danmcp** [comment]
@sosiouxme https://github.com/openshift/basic-authentication-provider-example

**Comment by danmcp** [comment]
@sosiouxme Should this be closed?

**Comment by sosiouxme** [comment]
Oh yeah, definitely. Sorry.

**Pull request closed without merging**
