### PR TITLE
dockerless testing

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@nalind is there another package we need to add to the build environment to address this?

```
# github.com/openshift/origin/vendor/github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:8:25: fatal error: btrfs/ioctl.h: No such file or directory
#include <btrfs/ioctl.h>
^
```

**Comment by nalind** [comment]
@bparees that file is provided by `btrfs-progs-devel`, but my preference would be to use the `exclude_graphdriver_btrfs` build tag to disable that logic.

**Comment by bparees** [comment]
> @bparees that file is provided by btrfs-progs-devel, but my preference would be to use the exclude_graphdriver_btrfs build tag to disable that logic.

Looks like it is set(by you), for the product build:
https://github.com/openshift/origin/pull/20886/commits/1bbcb63baf6fd2400451bb2d8111c59342c0be1c#diff-46fa39904016cc844c1eb2b49f35c156R13

Can you try to track down where else it needs to be set for the test logic?

**Comment by nalind** [comment]
@bparees Okay, I think https://github.com/nalind/origin/commit/0319e8d9170e2fe575f89794c1758a29f0bf89f6 is the right set of changes to get tests to run with the right tags.

**Comment by bparees** [comment]
@nalind thanks, updated this PR w/ that commit instead of the old one.  let's see where we get.

**Comment by bparees** [comment]
@nalind building locally i'm still seeing this failure (also ioctl.h still seems to be required):

```
# github.com/openshift/origin/vendor/github.com/containers/image/docker/daemon
vendor/github.com/containers/image/docker/daemon/client.go:33:14: undefined: client.ParseHostURL
```

**Comment by bparees** [comment]
looks like imagebuilder is expecting a newer version of docker than what origin is currently vendoring.

**Comment by bparees** [comment]
hm, well adding the flag here seems to have fixed both problems:
https://github.com/openshift/origin/pull/20886/commits/8fd8798681098ca34c7f09e88a261847fedad64a

**Comment by bparees** [comment]
(at least locally)

**Comment by nalind** [comment]
@bparees  That looks like a bug.  Opened https://github.com/projectatomic/buildah/pull/997.

**Pull request closed without merging**
