### PR TITLE
Automated cherry pick of #16784 #16741 #16721

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #16784 #16741 #16721 on stage.

#16784: Use config map for election with start controllers
#16741: Move browser safe proxy logic into an authorizer
#16721: Base random controller leader ID on machine info

### CODE REVIEW

**Comment by enj** [comment]
@eparis @smarterclayton @jupierce I will let you guys decide if you feel these are critical enough for stage.

**Comment by jupierce** [comment]
After talking with @enj, these don't sound critical.

**Pull request closed without merging**
