### PR TITLE
UPSTREAM: 53069: Align imagefs eviction defaults with image gc defaults

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/kubernetes/kubernetes/pull/53069

https://trello.com/c/dTvvtua7

@derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
need to update node config test in origin

**Comment by sjenning** [comment]
updated node config test

**Comment by sjenning** [comment]
@derekwaynecarr can I get lgtm on this? previous test run passed everything but travis.  needed to break the test change out of the UPSTREAM commit.

**Pull request merged**
