### PR TITLE
Bug 1318920: emit events for failed cancellations

### PR DESCRIPTION
**Pull request by kargakis**
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1318920

I cannot reproduce the race described in the issue as it is really a corner case but this PR is a good shot at fixing it.

@ironcladlou PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by ironcladlou** [comment]
So, the way cancellation is implemented today is basically best-effort: you can mark the deployment cancelled, but without a server-side API call which sets deadline and waits for the deployer pod to actually exit nonzero, you can never be sure in advance your cancellation will work.

This PR as-is will transform a successful deployment into a failed deployment when the user missed their chance to cancel, which seems incorrect.

Some solutions:

1. Change the CLI messaging and documentation to make it clear that cancellation is best-effort, and modify the deployer pod controller to clear the cancellation information if the deployment already succeeded. I think this might be necessary in the short-term no matter what to avoid these inconsistent states (a successful deployment with cancellation metadata assigned).
2. Implement a server-side cancellation mechanism which enables a blocking call from the API which can tell the caller definitively whether the cancellation effective.

Thoughts?

cc @smarterclayton

**Comment by kargakis** [comment]
> This PR as-is will transform a successful deployment into a failed deployment when the user missed their chance to cancel, which seems incorrect.

Note that we will never expose the deployment as Complete so users won't see their deployments going from Complete to Failed.

Another thing to note: upstream deployments implement `oc deploy --cancel` as `kubectl rollout undo` which rolls back to the previous version *regardless* of the deployment state - nevermind that there arent any deployment states currently). When users try to cancel they essentially want to rollback to a previous version or trash if it's the first deployment, right?

**Comment by soltysh** [comment]
@ironcladlou the docs are already warning you it's best-effort, see https://docs.openshift.org/latest/dev_guide/deployments.html#canceling-a-deployment

**Comment by soltysh** [comment]
@kargakis I'd stay away from cancel=rollback, that might not be the case always.

**Comment by kargakis** [comment]
> @kargakis I'd stay away from cancel=rollback, that might not be the case always.

But that is how `oc deploy --cancel` works right now. If there is no previous successful deployment, we fail, if not we rollback to the latest complete.

**Comment by kargakis** [comment]
> But that is how oc deploy --cancel works right now. If there is no previous successful deployment, we fail, if not we rollback to the latest complete.

(Supposing the dc passed to the command has a running deployment)

**Comment by smarterclayton** [comment]
We should separate "pause" verb from "rollback" from "cancel".  Today,
cancel means "abort this new deployment" (and abort results in the old
state).  Pause means "hold".  Rollback probably means "abort whatever is
happening and make the new target X".

Do we agree on those definitions?

**Comment by kargakis** [comment]
@smarterclayton agreed on the definitions. Implementing cancel for upstream deployments will be interesting. What are we supposed to do here? Cancel the deployment if the deployer pod has exited successfully or not? Is something client-side enough?

**Comment by smarterclayton** [comment]
Cancel upstream is effectively rollback (until upstream implements process
based deployments).  Cancel downstream involves process termination.

I'm not sure cancellation has to be more than best effort.  Why does a
client need a blocking call, vs something async?  By definition, if you
cancel before it completes, it's canceled.  Do we properly rollback from
the failed deployment?

On Mon, Mar 21, 2016 at 12:37 PM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
> Do we properly rollback from the failed deployment?

Yes, eventually the deploymentconfig controller will reconcile the dc and scale up the latest complete while scaling down everything else. 

> I'm not sure cancellation has to be more than best effort. Why does a client need a blocking call, vs something async? By definition, if you cancel before it completes, it's canceled. Do we properly rollback from the failed deployment?

Best-effort async call is fine for cancel. It seems to me though that the burden of terminating the process should move out of the deployment controller directly to the user. Right now:
```shell
# foo is Running

# user cancels foo
$ oc deploy foo --cancel
Canceled "foo" deployment...
# foo will be marked as canceled if it is not Complete/Failed; here is 
# the race window where foo can be Running but its deployer pod just
# Succeeded. So the deployer controller updates foo to Complete.

# foo is marked as canceled, deployment controller picks it up.
# If the deployer controller already marked foo as Complete, it
# stays Complete (We should cleanup the cancel annotations). 
# If foo is still running/pending/new, the deployment controller
# will set ActiveDeadlineSeconds to all the deployer pods of foo
# resulting in foo naturally being canceled.
$ oc describe foo
```

What if `oc deploy --cancel` would directly set ActiveDeadlineSeconds to the deployer pod IFF the deployer pod is running? Eventually we should abstract it under an API call.

**Comment by smarterclayton** [comment]
Interesting.  What would be the equivalent upstream?  The API call is what
concerns me - we *want* this to be an API mutation.  If it isn't, then all
clients are hard to port.  If we can make up an API on
deploymentconfig/foo/CANCEL_ACTION that solves this use case and is
possible to get upstream, that would be ok.  We would probably need some
sort of input to that action that includes parameters that allow the client
to be specific (cancel the current deployment, cancel a specific deployment
if it is running, etc).

**Comment by kargakis** [comment]
> What would be the equivalent upstream?

I think you already answered this in your previous post. Until upstream has process based deployments, --cancel for them is default rollback. They expose a deployments/rollback endpoint which [mutates](https://github.com/kubernetes/kubernetes/blob/d124deeb2f1e4428066f4aed13be5aaa0f042cf5/pkg/registry/deployment/etcd/etcd.go#L176) the deployment spec. Then the controller picks the deployment up, sees it has rollback populated and performs it.

**Comment by smarterclayton** [comment]
Sorry, I meant, what would be the equivalent subresource in existence today
upstream that equates to our cancel or abort?

On Tue, Mar 22, 2016 at 12:36 PM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
[deployments/rollback](https://github.com/kubernetes/kubernetes/blob/2777cd7e758ed4126e8a255793bec0e0c88ac86f/pkg/master/master.go#L719) which is hooked up in `kubectl rollout undo` is the closest. There is no cancel subresource upstream since there is no concept of canceling a running deployment. That's why I prefer to have the work happen in the client for now.

@ironcladlou what do you think about `--cancel` looking directly at the deployer pod phase and maybe setting ActiveDeadlineSeconds? Would definitely reduce the race window for Complete canceled deployments if not eliminate it?

**Comment by soltysh** [comment]
@kargakis wouldn't setting ADS on a deployer pod leave the deployment in an unknown state, since you might kill it in the middle of his work. Wouldn't be better just to get cancellation information inside the deployer pod and react to it?

**Comment by kargakis** [comment]
> @kargakis wouldn't setting ADS on a deployer pod leave the deployment in an unknown state, since you might kill it in the middle of his work. 

That's how --cancel is designed to work and is currently working. The deployment is marked as canceled by oc and then the deployment controller sets ADS on all deployer pods of that deployment. I am proposing to have the ADS set directly by the clients. I just verified that the console cancels deployments in the same way so we would need that api call:/

> Wouldn't be better just to get cancellation information inside the deployer pod and react to it?

Since it's a separate process, killing it and letting the deploymentconfig controller handle rolling back seems more convenient to me.

**Comment by ironcladlou** [comment]
If you just set ADS from the client, where is it recorded the the reason for the failure is a user cancellation? That context is explicitly captured and presented to users today. Rolling up the ADS assignment AND the assignment of a failure reason etc. into the client seems like a step backwards.

**Comment by kargakis** [comment]
I see. I am not a fan of two different assignments in the same call either. How about just looking at the deployer pod phase for now?

**Comment by ironcladlou** [comment]
I'm not sure I saw an answer to why this previous option isn't viable:

> [...] modify the deployer pod controller to clear the cancellation information if the deployment already succeeded. [...]

**Comment by kargakis** [comment]
> [...] modify the deployer pod controller to clear the cancellation information if the deployment already succeeded. [...]

The main problem here is that we already have told them that their deployment was canceled. And I don't think that rewording that message would help any more. But if you all are ok with rewording the message and making sure that users are aware they just run a best-effort command then I am ok with it.

**Comment by smarterclayton** [comment]
Is the confusion from users today that they cancel, but it still says
succeeded?  If so, could we say "Succeeded before cancel recorded" or
simply suppress the fact that it was cancelled?

On Wed, Mar 23, 2016 at 11:14 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
> Is the confusion from users today that they cancel, but it still says succeeded?

Yes, that's what https://bugzilla.redhat.com/show_bug.cgi?id=1318920 is about.

> If so, could we say "Succeeded before cancel recorded" or simply suppress the fact that it was cancelled?

"Succeeded before cancel recorded" as an event on the dc? That sounds ok. I don't think we really care about cancel after the fact. We can remove the annotation and be done with it. My concern is the message shown when running --cancel might misguide.

**Comment by kargakis** [comment]
Updated to emit an event in case of a complete deployment marked as canceled (plus removing the cancel annotations). I would like to merge https://github.com/openshift/origin/pull/8147 first and rebase this on top.

**Comment by kargakis** [comment]
@ironcladlou @smarterclayton this is ready, ptal

**Comment by smarterclayton** [comment]
[test]

**Comment by kargakis** [comment]
flake https://github.com/openshift/origin/issues/8039

[test]

**Comment by pweil-** [comment]
@ironcladlou any objections now that tests are green?

**Comment by ironcladlou** [comment]
LGTM

**Comment by pweil-** [comment]
[merge]

**Comment by pweil-** [comment]
flake https://github.com/openshift/origin/issues/8039

re[merge]

**Pull request merged**
