### PR TITLE
Cleanup root directory

### PR DESCRIPTION
**Pull request by sdodson**
@smarterclayton @dgoodwin 
Rebased #4655 and fixes rpm builds via tito

### CODE REVIEW

**Comment by dgoodwin** [comment]
LGTM. Probably a good idea to separate the various non-tito things from rel-eng dir as well. :+1:

**Comment by sdodson** [comment]
@dgoodwin  Ok, lemme review that directory structure.

**Comment by sdodson** [comment]
Good to go, let me know if you'd like me to squash everything down to 1 or 2 commits. As it is now I think there's some intermediate commits that don't leave things in a good state.

**Comment by sdodson** [comment]
@smarterclayton PTAL the functional diff from your original PR is that we have a .tito directory and origin.spec in the root of the repo. That's the best we can do right now.

**Comment by smarterclayton** [comment]
That's fine - go ahead and squash what you need to squash and I'll merge.  Thanks!

**Comment by sdodson** [comment]
Squashed everything down. Ready to merge.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Thanks

**Pull request merged**
