### PR TITLE
Enable cloudfront storage backend for docker-registry

### PR DESCRIPTION
**Pull request by miminar**
This brings in a new dependency (github.com/AdRoll/goamz/cloudfront).

### CODE REVIEW

**Comment by ncdc** [comment]
@miminar title wrong?

**Comment by miminar** [comment]
@ncdc good catch, thanks.

**Comment by smarterclayton** [comment]
Rebase please

**Comment by miminar** [comment]
Rebased.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
