### PR TITLE
Bug 1717739: ClusterOperators should specify related objects

### PR DESCRIPTION
**Pull request by jmencak**
See: https://github.com/openshift/cluster-node-tuning-operator/pull/64

### CODE REVIEW

**Comment by jmencak** [comment]
@bparees ,  @gabemontero, PTAL, thanks!

**Comment by bparees** [comment]
/lgtm

@jmencak fyi in general the github suggested reviewers are not a great starting point.  This should have been explicitly assigned (/assign) to someone on the team that owns node-tuning.

**Comment by bparees** [comment]
@jmencak i've also cleaned up your BZ reference in the PR title.

**Comment by jmencak** [comment]
@bparees , thanks, much appreciated!

**Pull request merged**
