### PR TITLE
[RPMs] Move /opt/cni/bin into node subpackage from sdn-ovs

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
master PR at #13351

**Comment by sdodson** [comment]
@dcbw PTAL

**Comment by smarterclayton** [comment]
@knobuc if you can get a reviewer here

**Comment by sdodson** [comment]
@knobunc

**Comment by smarterclayton** [comment]
Is this required for 1.5?

**Comment by sdodson** [comment]
Nice to have, not a blocker.

**Comment by sdodson** [comment]
@smarterclayton We should close this unless we believe we'll ever build origin 1.5 rpms again.

**Pull request closed without merging**
