### PR TITLE
regen protos

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
LGTM [merge] - fixing the generation in https://github.com/openshift/origin/pull/10458

**Comment by bparees** [comment]
@smarterclayton updated to include regen'd completions also..not sure when they got out of sync or why it wasn't caught.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by bparees** [comment]
jenkins appears to be hosed (bad origin repo in the workspace), i may have fixed it but probably not:

[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
