### PR TITLE
Bug 1888004: [release-4.4] move image ecosystem e2e suite from centos to rhel; create rhel only jenkins e2e suite

### PR DESCRIPTION
**Pull request by jaypoulz**
Manual cherry-pick of https://github.com/openshift/origin/pull/25014
I updated each individual commit with compatible changes, but I want to run it against a multi-arch 4.4 cluster to verify that it works.

### CODE REVIEW

**Comment by deepsm007** [comment]
@gabemontero @ironcladlou  Can we get a cherry pick approval for this? It will unblock an expansion of automated testing for image streams on P/Z.

**Comment by gabemontero** [comment]
/lgtm

@deepsm007 - cherry pick approvals are done on a scheduled basis by a group of  OCP architects on a rotating basis.  The approvals typically happen on Wednesdays.  If you want to try to get this week's patch manager (I believe it is @bparees this week) to approve things off schedule, you either reach out on #forum-release I believe  to find out who it isor catch who it is on the aos-devel email list, and then contact them directly.

It will be up to their discretion whether you get it today, or have to wait until next Wednesday.

**Comment by bparees** [comment]
> @deepsm007 - cherry pick approvals are done on a scheduled basis by a group of OCP architects on a rotating basis. The approvals typically happen on Wednesdays.

we survey the list wed/thur/fri, so i'll review the list today and tag this if i don't see any issues.

**Pull request merged**
