### PR TITLE
Add support for github teams

### PR DESCRIPTION
**Pull request by liggitt**
Resolves https://github.com/openshift/origin/issues/11882

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by mfojtik** [comment]
@liggitt does this also handle a user that has been removed from a team in GitHub or we don't handle that for other providers and they have to be removed manually?

**Comment by mfojtik** [comment]
one question, LGTM otherwise

**Comment by smarterclayton** [comment]
Ooo.... ahh....

**Comment by liggitt** [comment]
@mfojtik not sure I understand the question. This gates access at login time. If the user is not in one of the allowed teams at login time, they cannot log in.

**Comment by enj** [comment]
I think @mfojtik's question makes more sense if you sync openshift groups with github groups.  I don't think we are doing that though...

**Comment by liggitt** [comment]
updated with validation (either set organizations or teams, not both) and added warnings to github/google providers if they are left open to any user (instead of being restricted to a particular team, organization, or hostedDomain)

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
