### PR TITLE
dind: rm docker volumes natively (added in 1.9)

### PR DESCRIPTION
**Pull request by marun**
Assuming dind doesn't need to support docker < 1.9.

cc: @openshift/networking

### CODE REVIEW

**Comment by marun** [comment]
[testonlyextended][extended:networking]

**Comment by dcbw** [comment]
I think we might want to support docker 1.8 for a bit more, at least until Fedora 23 gets docker 1.10.  docker 1.9 has a specific problem with ShmSize and Kubernetes right now that will get fixed with 1.10.

**Comment by marun** [comment]
@dcbw Fair enough, I didn't realize there were problems with 1.9.

**Comment by eparis** [comment]
Fedora 1.9 is supposed to be getting the shmmem fix....

**Comment by dcbw** [comment]
@eparis not that I can see...  current docker fedora package git is on 1.10, it just hasn't been built and released yet

**Comment by dcbw** [comment]
@marun I'd actually keep this open and park it for a couple weeks then try to merge again

**Comment by eparis** [comment]
@ncdc what's the deal with fedora docker 1.9. you were looking at that (shmem) right?

**Pull request closed without merging**
