### PR TITLE
Tolerate being unable to access OpenShift resources in status

### PR DESCRIPTION
**Pull request by smarterclayton**
It should be possible to run status against a raw kube server.

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
Spawned from #10821

**Comment by kargakis** [comment]
Will this work if/when we get a graph API?

**Comment by smarterclayton** [comment]
I don't see graph API happening soon, and it would probably be an extension
API anyway and optional.

On Sep 8, 2016, at 7:32 AM, Michail Kargakis <notifications@github.com>
wrote:

Will this work if/when we get a graph API?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/10823#issuecomment-245570054>,
or mute
the thread

**Comment by smarterclayton** [comment]
@deads2k as I mentioned

**Comment by fabianofranz** [comment]
re[test]
@smarterclayton is this good to go?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Yes but it needs an extended test to be safe (a regular extended test).  It
won't break existing users though.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge] because someone just asked for this and it's low risk

**Comment by smarterclayton** [comment]
[merge] idling flake

**Pull request merged**
