### PR TITLE
tests/cluster: Check for machinesets, not platforms

### PR DESCRIPTION
**Pull request by cgwalters**
We need to support running the e2e tests against AWS UPI for
example.

### CODE REVIEW

**Comment by cgwalters** [comment]
(I didn't test this test)

**Comment by JoelSpeed** [comment]
Seems to make sense to me, let's see if the tests pass and it's not been skipped

**Comment by cgwalters** [comment]
Hmm, I may be wrong about UPI.  I noticed in some of the machineset tests we've cargo culted the ibmcloud exclusion too.

**Comment by cgwalters** [comment]
Hmm there also don't seem to be any UPI periodics...a [prow upi search](https://prow.ci.openshift.org/?job=*upi*) only turns up PR runs for the installer.

OK but looking at the [artifacts from this 4.4 UPI run](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upi-4.4/1296407171671527424) I do see that there are zero machinesets/machines.

**Comment by cgwalters** [comment]
OK fixed the `s/machineset/machinesets/` typo, let's see...

**Comment by mfojtik** [comment]
@cgwalters this makes sense to me, if it pass lets tag it

**Comment by cgwalters** [comment]
> [sig-cluster-lifecycle][Feature:Machines][Early] Managed cluster should have same number of Machines and Nodes [Suite:openshift/conformance/parallel]

Passed (i.e. was not skipped).

**Comment by deads2k** [comment]
/skip ci/prow/e2e-aws-fips
/skip ci/prow/e2e-gcp

The test this changed ran successfully.  the failure is https://bugzilla.redhat.com/show_bug.cgi?id=1872282 .  This can improve aws upi.

/lgtm
/approve
/hold cancel

**Pull request merged**
