### PR TITLE
minor fixes made while debugging image_ecosystem extended test failure

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter what's the state of this? looks good to merge to me.

**Comment by jim-minter** [comment]
@bparees had been holding it in case there was anything else to add; please merge

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
will manually merge if extended tests pass, to save queue time.

**Comment by bparees** [comment]
looks like PV issues on the cluster, none of the failures are related to the tests being changed. manually merging.

**Pull request merged**
