### PR TITLE
replace registry.redhat.io refs with internal image registry refs in image-eco

### PR DESCRIPTION
**Pull request by gabemontero**
See https://github.com/openshift/builder/pull/228#issuecomment-802309995

image-eco currently broken

### CODE REVIEW

**Comment by gabemontero** [comment]
will most likely minimally need https://github.com/openshift/origin/pull/25986 to bypass e2e-gcp-upgrade for merging

**Comment by gabemontero** [comment]
ok the actual image eco tests pass, the failure in it was some unrelated prometheus thing

` [sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured`

/retest

**Comment by gabemontero** [comment]
ok the previous prometheus error is a flake vs. permfail

image-eco now green

unclear on metal-ipi-ovn-ipv6

/retest

**Comment by gabemontero** [comment]
all green e2e's 

/assign @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
