### PR TITLE
Use rbac.PolicyRule directly for DiscoveryRule

### LINKED ISSUE #15826: RBAC Migration Followup #13: Use RBAC discovery rule
Make RBAC discovery rule authoritative in `pkg/authorization/apis/authorization/types.go`

### PR DESCRIPTION
**Pull request by mrogers950**
Fixes #15826

### CODE REVIEW

**Comment by enj** [comment]
@mrogers950 update test fixtures.

**Comment by mrogers950** [comment]
I've updated the test fixtures.

**Comment by enj** [comment]
@mrogers950 lets get this fixed.

**Comment by mrogers950** [comment]
@enj rebased.

**Comment by enj** [comment]
/lgtm

Test fixture change is cosmetic.

**Pull request merged**
