### PR TITLE
Add conversions between RC and RS

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k just these two are merged, ptal

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@mfojtik test failed

**Comment by mfojtik** [comment]
@deads2k i'm looking at that

**Comment by mfojtik** [comment]
Closed as https://github.com/openshift/origin/pull/10136#event-741591003 was merged.

**Pull request closed without merging**
