### PR TITLE
docker builder cannot retrieve source from git when user name is not git

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @csrwng FYI - the origin side PR for fixing / consolidating URL/git clone spec validation, etc.

PTAL when you get the chance.

thx

### CODE REVIEW

**Comment by deads2k** [comment]
Is this a bump or a patch?  bumps should be `bump(name/of/your/godep): <commit of godep>`  upstreams should be `UPSTREAM: name/of/godep: PR#: description`

**Comment by gabemontero** [comment]
this PR is intended to address internal bugzilla 1268478

**Comment by deads2k** [comment]
> Is this a bump or a patch? bumps should be bump(name/of/your/godep): <commit of godep> upstreams should be UPSTREAM: name/of/godep: PR#: description

Heh, sorry, I meant the commit message, not the pull request message.  Take a look through the `git log`

**Comment by gabemontero** [comment]
no worries - will do

**Comment by kargakis** [comment]
Seems like a bump to me
```
bump(github.com/openshift/source-to-image):20c763f82a4361a60bbd2fcbc809ea5d07e59957
```

**Comment by bparees** [comment]
@openshift/team-origin-committers ptal.  the bump commit message is getting straightened out.

**Comment by gabemontero** [comment]
I believe the bump commit message is correct now.

**Comment by gabemontero** [comment]
note the examples I saw in `git log` did NOT have `:`

**Comment by bparees** [comment]
> note the examples I saw in git log did NOT have :

yeah some do and some don't, we haven't been good about consistency there, but i believe the process says it is supposed to be there.  so we're trying to get better going forward.

**Comment by smarterclayton** [comment]
@bparees do you think this meets the release bar?

**Comment by bparees** [comment]
@smarterclayton well i did.  i'm slowly talking myself out of it.

**Comment by smarterclayton** [comment]
Your call

**Comment by bparees** [comment]
as @gabemontero noted, it's not a regression, we'll punt it and put it in post-3.1.  i'll move the bug to upcoming release so it's not on the blocker list.

**Pull request closed without merging**
