### PR TITLE
Add missing newlines in oc tag

### PR DESCRIPTION
**Pull request by soltysh**
@miminar ptal

@mfojtik @pweil- for approval this is simple fix, but makes the UX sooo much better :)

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
@stevekuznetsov I'm looking into https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/185/ and nothing failed, but bot states differently, what did you do to him 😉

**Comment by mfojtik** [comment]
Approved for 1.5 (new line fixed needs to merge ASAP ;-)

[merge]

**Comment by stevekuznetsov** [comment]
Very weird -- if we see the bot get it wrong again I'll dig more, never seen that before.

**Comment by soltysh** [comment]
Previous problem was fixed.

[merge]

**Comment by soltysh** [comment]
Flake #10773.

[merge]

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
