### PR TITLE
Typo in HACKING.md

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by mfojtik** [comment]
Thanks! :-)

**Comment by mfojtik** [comment]
/lgtm cancel

@patriot1burke actually can you please remove the word 'sh*t' from the commit message? ;-)

**Comment by patriot1burke** [comment]
Sorry about title...the typo made me chuckle a bunch and thought you guys might have a chuckle too.... cheers.

**Comment by enj** [comment]
@patriot1burke remove it from the commit message as well :)

**Pull request closed without merging**
