### PR TITLE
ETCD-578: Fix etcd profiles e2e test to check returned status for upd…

### PR DESCRIPTION
**Pull request by dusk125**
…ated value

### CODE REVIEW

**Comment by dusk125** [comment]
CEO update has merged, this should move along now

/retest-required

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/hold 
verify failure is real

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips
this doesn't seem to be related

**Comment by dusk125** [comment]
unrelated failure

/test e2e-aws-ovn-serial

**Pull request merged**
