### PR TITLE
UPSTREAM: 70206: test/e2e/apps: fix race in cronjob test

### PR DESCRIPTION
**Pull request by runcom**
Backport https://github.com/kubernetes/kubernetes/pull/70206 for CRI testing in https://github.com/openshift/origin/pull/21193

@smarterclayton @soltysh PTAL

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by runcom** [comment]
Wrong commit message, I'll fix it

**Comment by runcom** [comment]
Just missing a label in github now

**Pull request merged**
