### PR TITLE
clean up buildconfig webhook handlers

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/devex ptal

**Comment by gabemontero** [comment]
so aside from presumably following the *correct* pattern, does this change also facilitate prometheus working with the webhook endpoint (per an exchange I saw between @bparees and @smarterclayton on IRC yesterday) ?

**Comment by bparees** [comment]
> so aside from presumably following the correct pattern, does this change also facilitate prometheus working with the webhook endpoint (per an exchange I saw between @bparees and @smarterclayton on IRC yesterday) ?

should have no effect on that (the prometheus webhook metrics actually do exist already, as it turns out).  So this is purely an internal cleanup and we don't need to do anything additional for metrics.

**Comment by gabemontero** [comment]
On Fri, Oct 6, 2017 at 12:58 PM, Ben Parees <notifications@github.com>
wrote:

> so aside from presumably following the correct pattern, does this change
> also facilitate prometheus working with the webhook endpoint (per an
> exchange I saw between @bparees <https://github.com/bparees> and
> @smarterclayton <https://github.com/smarterclayton> on IRC yesterday) ?
>
> should have no effect on that (the prometheus webhook metrics actually do
> exist already, as it turns out). So this is purely an internal cleanup and
> we don't need to do anything additional for metrics.
>
cool thanks for the info

**Pull request merged**
