### PR TITLE
Re-enable oc run --attach tests

### LINKED ISSUE #11240: Re-enable `oc run --attach` verifications once the docker logs api fix is vendored
```
Running test/end-to-end/core.sh:331: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'In project test'...
SUCCESS after 0.016s: test/end-to-end/core.sh:331: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'In project test'
Standard output from the command:
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
I1005 22:44:47.756240       1 merged_client_builder.go:122] Using in-cluster configuration
I1005 22:44:47.789231       1 merged_client_builder.go:122] Using in-cluster configuration
I1005 22:44:47.792214       1 merged_client_builder.go:122] Using in-cluster configuration
I1005 22:44:47.792372       1 merged_client_builder.go:145] Using in-cluster namespace
In project test on server https://172.30.0.1:443
pod/cli-with-token runs openshift/origin:6cd347a
2 warnings identified, use 'openshift cli status -v' to see details.

There was no error output from the command.
Running test/end-to-end/core.sh:332: executing 'oc delete pod cli-with-token' expecting success...
SUCCESS after 0.289s: test/end-to-end/core.sh:332: executing 'oc delete pod cli-with-token' expecting success
Standard output from the command:
pod "cli-with-token" deleted

There was no error output from the command.
Running test/end-to-end/core.sh:334: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default'...
FAILURE after 0.015s: test/end-to-end/core.sh:334: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed
Standard output from the command:
Waiting for pod test/cli-with-token-2 to be running, status is Pending, pod ready: false
Waiting for pod test/cli-with-token-2 to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
Waiting for pod test/cli-with-token-2 to terminate, status is Running

There was no error output from the command.
[ERROR] PID 30321: hack/lib/cmd.sh:229: `return "${return_code}"` exited with status 1.
[INFO]      Stack Trace: 
[INFO]        1: hack/lib/cmd.sh:229: `return "${return_code}"`
[INFO]        2: test/end-to-end/core.sh:334: os::cmd::expect_success_and_text
[INFO]   Exiting with code 1.
[ERROR] PID 29510: hack/test-end-to-end-docker.sh:94: `${OS_ROOT}/test/end-to-end/core.sh` exited with status 1.
[INFO]      Stack Trace: 
[INFO]        1: hack/test-end-to-end-docker.sh:94: `${OS_ROOT}/test/end-to-end/core.sh`
[INFO]   Exiting with code 1.
[INFO] Stacked plot for log subset "iops" written to /tmp/openshift/test-end-to-end-docker//logs/iops.pdf
[INFO] Stacked plot for log subset "paging" written to /tmp/openshift/test-end-to-end-docker//logs/paging.pdf
[INFO] Stacked plot for log subset "cpu" written to /tmp/openshift/test-end-to-end-docker//logs/cpu.pdf
[INFO] Stacked plot for log subset "queue" written to /tmp/openshift/test-end-to-end-docker//logs/queue.pdf
[INFO] Stacked plot for log subset "memory" written to /tmp/openshift/test-end-to-end-docker//logs/memory.pdf

[FAIL] !!!!! Test Failed !!!!
```

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #11240 

This goes in line with #18438, same situation, same problems. 

/assign @stevekuznetsov 
/assign @smarterclayton

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/retest
/lgtm

This should work fine now since we have vendored the lib and are not using `journald`?

**Comment by stevekuznetsov** [comment]
@soltysh looks bad?

/lgtm cancel

**Comment by soltysh** [comment]
> @soltysh looks bad?

Yeah, will need to check it out.

**Comment by soltysh** [comment]
I needed to change the invocation in the `oc run` commands, since there's no `cli` subcommand anymore, so I needed to call `oc` explicitly. Should be good now.

**Comment by soltysh** [comment]
I think it's worth waiting for https://github.com/openshift/release/pull/597 to merge.

**Comment by soltysh** [comment]
I've rebased it, let's see where we are with it.

**Comment by soltysh** [comment]
@damemi which part of this you're dropping, if this stays ptal otherwise I'll close this.

**Comment by soltysh** [comment]
Not needed anymore.

**Pull request closed without merging**
