### PR TITLE
remove internal build client

### PR DESCRIPTION
**Pull request by mfojtik**
Build on generator PR which is in merge queue (ignore first 2 commits)...

This removes the `pkg/build/generated` entirely and sweeps the usage in external and integration tests and replacing it with external client/api.

/cc @deads2k 
/cc @bparees

### CODE REVIEW

**Comment by deads2k** [comment]
yay!

/lgtm
/hold

in case someone else wants a look

**Comment by smarterclayton** [comment]
Your tests aren’t passing

/hold

**Comment by mfojtik** [comment]
Fixed tests, re-applying the LGTM label. For some reason the 3 tests above are showing as failed but the PR test history show them all green?

/refresh

**Pull request merged**
