### PR TITLE
image: transform api groups to legacy resources in admission

### PR DESCRIPTION
**Pull request by mfojtik**
Ref: https://github.com/openshift/origin/issues/13412

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton i think I missed your comment :) this is the actual PR, can you please comment with the another hole you think this might expose?

**Comment by smarterclayton** [comment]
Don't try transforming in the controller itself.  Transform when admission is called.  That preserves legacy behavior (user defines "builds") as well as prevents accidental slip ups (user only defines "builds.builds.openshift.io").

Have you reviewed all the other admission controllers for config that has resources in it?

**Comment by mfojtik** [comment]
@smarterclayton gotcha

**Comment by mfojtik** [comment]
@smarterclayton i briefly went trough other admission controller (origin) and unless I'm missing something, only image policy admission actually have list of resources it applies to.  If that is true and we fix this, we should be safe, but perhaps another person should go trough them as well to be 100% confident ( @soltysh @enj ?)

**Comment by mfojtik** [comment]
[test]

@smarterclayton PTAL

**Comment by mfojtik** [comment]
Flake: https://github.com/openshift/origin/issues/13386

[test]

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Pull request merged**
