### PR TITLE
Fix typos in router code

### PR DESCRIPTION
**Pull request by louyihua**
Various typos, most in comments, are fixed.
And the unnecessary "_" receiver is also removed.

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by louyihua** [comment]
Maybe this can be merged?

**Comment by pweil-** [comment]
[merge]

**Comment by louyihua** [comment]
Seems weird failure?

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/10489
https://github.com/openshift/origin/issues/12923

re[merge]

**Comment by louyihua** [comment]
Seems still the same failure?
Rebased to the current master, hope this will be fine.

**Comment by pweil-** [comment]
let's try this again...

re[test]

**Comment by pweil-** [comment]
[merge]

**Pull request merged**
