### PR TITLE
Fix image pruning with both strong & weak refs

### PR DESCRIPTION
**Pull request by ncdc**
Fix a logic error where an image could incorrectly be considered
prunable if there were both strong and weak references from an image
stream to the image.

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by soltysh** [comment]
LGTM

**Comment by pweil-** [comment]
[merge]

**Comment by smarterclayton** [comment]
Can we cherry-pick this into 1.5 as well?

**Comment by soltysh** [comment]
@smarterclayton see linked PRs.

**Pull request merged**
