### PR TITLE
bump(github.com/openshift/source-to-image): 48e62fd57bebba14e1d0f7a40a15b65dafa5458c

### PR DESCRIPTION
**Pull request by csrwng**
Fixes BZ 1321308

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
[merge] again

**Comment by mfojtik** [comment]
@csrwng @bparees can we wait till https://github.com/openshift/source-to-image/pull/446 lands as well?

**Comment by mfojtik** [comment]
too late :-)

**Pull request merged**
