### PR TITLE
Set cache control headers for protected requests

### PR DESCRIPTION
**Pull request by smarterclayton**
Sets Cache-Control: no-store on all authenticated apis

@liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
@spadgett can you pull this into your env and verify this fixes IE 10?

**Comment by smarterclayton** [comment]
[test]

**Comment by spadgett** [comment]
@liggitt testing now

**Comment by liggitt** [comment]
LGTM, pending @spadgett verifying it works. FYI, things in the unauthenticated mux:
* OAuth (sets its own cache-control headers)
* UI (sets its own etag headers)

**Comment by spadgett** [comment]
The fix works.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
