### PR TITLE
UPSTREAM: Allowing ActiveDeadlineSeconds to be updated for a pod

### PR DESCRIPTION
**Pull request by abhgupta**
@derekwaynecarr if the upstream PR is good, then please merge this as well.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Link the upstream PR here

**Comment by abhgupta** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8890

**Comment by derekwaynecarr** [comment]
I assume you tested this with your deployment code and things were all good?

**Comment by abhgupta** [comment]
Hold off while I fix this stupid commit mixup.

**Comment by abhgupta** [comment]
@derekwaynecarr tested manually with a pod update. And changed the commit both upstream and here to block 0.

**Comment by abhgupta** [comment]
@derekwaynecarr Added test case for removing the attribute.

**Comment by ironcladlou** [comment]
I've verified this patch fixes the deployment cancellation support.

**Comment by derekwaynecarr** [comment]
We can [merge] this now, and carry the patch until upstream merge goes in given acceptance of the use case, if not the code yet.

**Comment by abhgupta** [comment]
re[merge] - hit the timeout

**Comment by ironcladlou** [comment]
[merge] already!

**Pull request merged**
