### PR TITLE
[WIP] Fetch layer sizes from internal Docker registry

### PR DESCRIPTION
**Pull request by miminar**
When Docker 1.10 is used to build images, layer sizes won't be stored in
resulting manifests. They need to be fetched from internal Docker registry.

Depends on:
- https://github.com/kubernetes/kubernetes/pull/20446
- #7128

TODOs:
- [ ] - decide, how to initialize resource quota controller with a
        docker registry certificate authority
- [ ] - decide, how to pass certificate and key of secured registry
        to the controller
- [ ] - update image objects in etcd with metadata (layer sizes) fetched
        from the registry to prevent future re-fetches
- [ ] - add a test with a properly faked registry server

### CODE REVIEW

**Comment by miminar** [comment]
@smarterclayton fyi.

I'd be glad for any clue regarding using registry's certificate files (cert. authority, tls cert and key) inside of origin's controller.

**Comment by smarterclayton** [comment]
We definitely want the image size to remain in the OpenShift image, so I don't know that you need to change anything except when we write the image to the server we need to also load the layer sizes.

**Comment by liggitt** [comment]
+1 for continuing to store image size in the API

**Comment by miminar** [comment]
@smarterclayton Of course! How simple. Thank you.

Closing now.

**Pull request closed without merging**
