### PR TITLE
Reenable deploy_trigger_test

### PR DESCRIPTION
**Pull request by ncdc**
Redo of #2069

### CODE REVIEW

**Comment by ncdc** [comment]
Compilation error from rebase fixed
[test]

@smarterclayton

**Comment by ncdc** [comment]
Travis flake was the TestDNS race

**Comment by ncdc** [comment]
Looking at the newapp_test.go breakage now

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
newapp_test breakage was due to a GitHub outage (we try to git clone)

**Comment by ironcladlou** [comment]
LGTM

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
Getting tired of seeing `UnknownError: Error communicating with the remote browser. It may have died.`

[merge]

**Pull request merged**
