### PR TITLE
WIP template(instance) completion detection

### PR DESCRIPTION
**Pull request by jim-minter**
https://trello.com/c/Q59Wgwjl/1127-8-template-completion-detection-templatebroker

### CODE REVIEW

**Comment by jim-minter** [comment]
@smarterclayton @deads2k @liggitt @bparees @coreydaley this is a dubious partial sketch for https://trello.com/c/Q59Wgwjl which aims to allow the template service broker to optionally delay reporting provision complete until certain objects in a template "are ready".  I'd very much appreciate your feedback and thoughts on at least the following areas to try to improve it:

- the approach of allowing template authors to annotate objects in a template which should be waited for (currently just implemented deploymentconfigs) - is that ok to pursue?

- whether to allow template authors to specify a timeout after which an object is deemed to be terminally unready (if it hasn't overtly failed before).  I'm not sure I love this and I don't yet know how to implement it properly (e.g. unless wildly reducing the controller relist interval).  I'm concerned that the case of "build failed, DC never became ready" may be problematic without a timeout, and choosing a platform timeout is even worse than punting the problem to the template author.

- where to put logic that determines whether an object is "complete"/in progress/failed - e.g. for deploymentconfigs, check their conditions; for a service, see if it has endpoints, etc.  Not clear if/how this could be made explicitly and usably configurable rather than a black box.

- using an annotation as well as a label to map from an instantiated object back to its template instance, which may possibly be in another namespace (I wish we could just use a label but can't put '/' in a label :cry:)

- where to aim to put this logic - if it can be cleaned up enough to be part of the templateinstance controller (my preference) or whether it's inevitable that it should be offloaded to the template service broker?

**Comment by deads2k** [comment]
A similar request came from @simon3z some time ago.  Having to tailor this per-resource seems sub-par, since the generic problem of "I instantiated a template, how do I know when it is done" is generic all resources.

As I recall, we kicked around the idea of having a readiness check for overall health (like we do in our e2e test) and the idea of having jsonpath expressions.

**Comment by bparees** [comment]
> As I recall, we kicked around the idea of having a readiness check for overall health (like we do in our e2e test) and the idea of having jsonpath expressions.

that would be effectively possible with this (well i haven't looked at what @jim-minter implemented, but at least what we discussed during planning) since you can define the "template readiness check" annotation on your deployment config and as long as the deploymentconfig won't pass readiness until your whole template is ready, you're all set.  You don't have to define readiness for all the resources, just for some top level resource that represents the state of the whole set.

**Comment by deads2k** [comment]
> on your deployment config and as long as the deploymentconfig won't pass readiness until your whole template is ready, you're all set.

But when run using Deployments, DaemonSets, StatefulSets, or Jobs, you're left without a solution until we port it around.  The same thing would happen trying to chase around any other resource that we wanted to support.

**Comment by smarterclayton** [comment]
A solution that doesn't solve for at least D and SS is not a solution.

**Comment by smarterclayton** [comment]
Jobs too probably

**Comment by jim-minter** [comment]
Moving to https://github.com/openshift/origin/pull/15361

**Pull request closed without merging**
