### PR TITLE
Changed image names for ImageRepository objects, since it was using two exactly the same in different tests

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik this is to address the race problem you've had in https://github.com/openshift/origin/pull/1138, see this [comment](https://github.com/openshift/origin/pull/1138#issuecomment-75971828)

//cc @bparees @smarterclayton

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by bparees** [comment]
lgtm but i'm not sure why it's necessary, aren't these tests isolated enough to avoid this problem?

**Comment by mfojtik** [comment]
@bparees got a race today with STI environment PR... this seems to cause it...

**Comment by mfojtik** [comment]
LGTM

On Wed, Feb 25, 2015 at 5:12 PM, OpenShift Bot <notifications@github.com>
wrote:

> Evaluated for origin up to 8ed39ca
> <https://github.com/openshift/origin/commit/8ed39ca2643a1a003b6c6fb421c75a5d68609a17>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/1144#issuecomment-75989172>.
>



-- 
-----------------------------------------------
Michal Fojtik <mi@mifo.sk <mfojtik@mifo.sk>>
Red Hat OpenShift, Engineering

**Comment by soltysh** [comment]
> lgtm but i'm not sure why it's necessary, aren't these tests isolated enough to avoid this problem?

I was hoping for that, since @smarterclayton put each of them in separate process in https://github.com/openshift/origin/commit/5bcc9176c7a1c6826e0813a526c3d2b4f098b574
But since we're actually using exactly the same image name, we're asking for troubles with that, so it's better no to do it IMHO.

**Comment by bparees** [comment]
@mfojtik yeah i saw the discussion, just not convinced this is the solution.  or the right solution, anyway.  if our integration tests are still coupled, we ought to figure out why.

**Comment by mfojtik** [comment]
[merge]

@bparees will merge this with a little hope it will fix https://github.com/openshift/origin/issues/1158

**Pull request merged**
