### PR TITLE
Add `--image-for` and `--output` to `oc adm release info`

### PR DESCRIPTION
**Pull request by smarterclayton**
`--image-for=TAG` lets a user get the exact pull spec out of the payload or
return an error. Allows scripting around a particular payload, for instance
to get the installer or CLI binary out of the image referenced in the
payload.

The `--output` command acts like `oc image info` and prints a semi-formal
API output of the info gathered for scripting.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@wking parallels the CVO behavior and intended for admin scripting by (for now) ART and QE to let them get the installer binary out of the payload without having to execute the payload.

@vikaslaad @tbielawa you can use this to get the installer binary with:

```
oc image extract $( oc adm release info registry.svc.ci.openshift.org/openshift/origin-release:v4.0 --image-for=installer ) --file /usr/bin/openshift-installer
```

or the oc cli with:

```
oc image extract $( oc adm release info registry.svc.ci.openshift.org/openshift/origin-release:v4.0 --image-for=cli ) --file /usr/bin/oc
```

**Comment by vikaslaad** [comment]
@mffiedler

**Pull request merged**
