### PR TITLE
Debug command should default to pods

### PR DESCRIPTION
**Pull request by smarterclayton**
@kargakis not for 1.2

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by kargakis** [comment]
lgtm

**Comment by deads2k** [comment]
I'd really like this command to do a priority order search for locating "a thing with a podspec with the name `foo`".  This is an uncommon command and when I use it I really want it to "just work".  Given the weight of what its going to be doing afterwards, running a series of GETs to find a pod or rc or dc seems like it would be a nice feature.

**Comment by smarterclayton** [comment]
Agree, can you spawn an issue or add t to the existing "improve debug"?

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request closed without merging**
