### PR TITLE
Output more helpful cancel message

### LINKED ISSUE #6339: Flake in test/cmd/builds.sh: oc cancel-build build/ruby-sample-build-1
seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7860 run from https://github.com/openshift/origin/pull/6330:
```
Running hack/../test/cmd/builds.sh:113: executing 'oc cancel-build build/ruby-sample-build-1' expecting any result and text 'A cancellation event was already triggered for the build ruby-sample-build-1.'; re-trying every 0.2s until completion or 60.000s...
FAILURE after 59.535s: hack/../test/cmd/builds.sh:113: executing 'oc cancel-build build/ruby-sample-build-1' expecting any result and text 'A cancellation event was already triggered for the build ruby-sample-build-1.'; re-trying every 0.2s until completion or 60.000s: the output content test failed
Standard output from the command:
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #6339

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
[test]

**Comment by jwforres** [comment]
LGTM

**Comment by bparees** [comment]
so how was that test ever passing?

**Comment by liggitt** [comment]
Race condition if the cancel was processed slowly enough and phase hadn't been updated yet

**Comment by bparees** [comment]
@jhadvig fyi.

**Pull request merged**
