### PR TITLE
Kube GC improvements backports

### PR DESCRIPTION
**Pull request by ncdc**
Use shared informers for GC if possible
Update required verbs for deletable resources
Allow list of ignored resources to be customized

@smarterclayton @liggitt @deads2k @sttts @mfojtik

### CODE REVIEW

**Comment by ncdc** [comment]
This seems to work locally. It logged that it was using shared informers for GC where it could. It can't, however, use shared informers for OpenShift resources, because the Kubernetes GarbageController doesn't have access to any shared informers other than those in Kubernetes. We could modify the GC configuration to take in something like

```go
type MonitorFactory interface {
  MonitorFor(resource schema.GroupResource) (cache.Controller, error)
}
```

and then allow OpenShift to use one of its own that knows how to look up shared informers for both Kubernetes and OpenShift resources. Do you think this change is worth doing, given the desire to have OpenShift run on top of Kubernetes?

[test]

**Comment by smarterclayton** [comment]
Given that it probably saves us 20 duplicate informers, I think it's worth
it.  If you don't have time to get to it, I will

On May 25, 2017, at 5:06 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test Running (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1784/)
(Base Commit: d03a427
<https://github.com/openshift/origin/commit/d03a42705bb5d92c8f92f99501ba5a0530ffbc62>
)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14358#issuecomment-304124559>,
or mute
the thread

**Comment by smarterclayton** [comment]
Tests have a few failures, otherwise LGTM.  The MonitorFor we should try to get for 3.6 if we can - we need to get our cache counts down to hit our scale numbers.

**Comment by ncdc** [comment]
@smarterclayton latest commit hopefully fixes the test issues

**Comment by smarterclayton** [comment]
Worked, was flake.

**Comment by smarterclayton** [comment]
[merge][severity:blocker] serious performance regression

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test] flake fox was force merged

**Comment by smarterclayton** [comment]
Failed due to idler flake, force merging

**Pull request merged**
