### PR TITLE
Update CNI for host local fix

### PR DESCRIPTION
**Pull request by dcbw**
CNI updated to get fixes for host-local plugin allocations on IP subnet boundaries.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1392296

@openshift/networking

### CODE REVIEW

**Comment by knobunc** [comment]
[test]

**Comment by danwinship** [comment]
[testextended][extended:networking]

**Comment by danwinship** [comment]
So there's a lot of new code there, but I guess it's replacing code that has only had two weeks of testing within OpenShift anyway... Is this all considered stable upstream? Is there anything in particular in there that you know for sure we want other than the host-local fixes?

**Comment by knobunc** [comment]
[test]

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
