### PR TITLE
Upgrade golang-1.8 to 1.8.1

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1435261

@smarterclayton @stevekuznetsov PTAL

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge] thanks

**Comment by smarterclayton** [comment]
[merge] flake on #13650

**Comment by smarterclayton** [comment]
[merge]

**Comment by fabianofranz** [comment]
[merge]

**Comment by smarterclayton** [comment]
Direct merging so we can test against 1.8.1 builds

**Pull request merged**
