### PR TITLE
Update documentation for new --host-network option.

### PR DESCRIPTION
**Pull request by ramr**
Update router documentation for new --host-network option. 
Merge once #4026 is merged.

### CODE REVIEW

**Comment by ramr** [comment]
@pweil-  docs for the host network PR - PTAL. Thx

**Comment by pweil-** [comment]
fancy template!  LGTM

**Comment by rajatchopra** [comment]
Looks nice.
[merge]

**Comment by rajatchopra** [comment]
re [merge]

**Pull request merged**
