### PR TITLE
bump(github.com/fsouza/go-dockerclient) 25bc220b299845ae5489fd19bf89c5278864b050

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik @liggitt ptal

**Comment by bparees** [comment]
(we need the image.go change for cgroup support)

**Comment by liggitt** [comment]
need to be paired with an upstream pull to bump to the same level, and pass e2e tests upstream

**Comment by liggitt** [comment]
@ncdc

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@liggitt upstream pull: https://github.com/kubernetes/kubernetes/pull/20033

**Comment by bparees** [comment]
@liggitt upstream pull has passed testing i believe: https://github.com/kubernetes/kubernetes/pull/20033

**Comment by liggitt** [comment]
Travis failed: https://travis-ci.org/kubernetes/kubernetes/builds/104205190

**Comment by bparees** [comment]
not for a reason related to the PR (`output: fatal: Not a valid object name upstream/release-1.1`), do you have the power to kick it?

**Comment by liggitt** [comment]
I thought it was this:
```
Your godeps changes are not reproducable:
...
```

**Comment by bparees** [comment]
@liggitt hm, well i didn't touch stretchr so it still seems like a flake or unrelated issue.

**Comment by liggitt** [comment]
LGTM at a glance, want a second from @ncdc

**Comment by liggitt** [comment]
is there a minimum docker API version for these new options, or do we need to worry about that?

**Comment by bparees** [comment]
looks like it was introduced in https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.18.md

**Comment by ncdc** [comment]
I may have time tonight. If not, it'll probably be mid morning or early
afternoon before I get to it. PTO from Snowzilla + a backlog of emails = a
lot of stuff to catch up on.

**Comment by ncdc** [comment]
LGTM, API changes are only additive

**Comment by bparees** [comment]
@liggitt is this going to mess you up if it merges?

**Comment by liggitt** [comment]
Nope, go ahead

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
