### PR TITLE
Bug 1455472: restore docker binary inside the RPM

### PR DESCRIPTION
**Pull request by kargakis**
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1455472

@stevekuznetsov @jupierce 

Signed-off-by: Michail Kargakis <mkargaki@redhat.com>

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@kargakis this was just errantly introduced in 2f7d826ad6bed85e00b3df3db40f25bebb965662 ? LGTM

**Comment by kargakis** [comment]
yeah, [merge]

**Comment by stevekuznetsov** [comment]
[merge][severity: blocker]

**Comment by kargakis** [comment]
Hm, now I remember why I added docker there - the node image expects to find [this script](https://github.com/openshift/origin/blob/master/images/node/scripts/docker) in /usr/local/bin.

**Comment by kargakis** [comment]
@giuseppe can you please weigh in on https://bugzilla.redhat.com/show_bug.cgi?id=1455472?

**Comment by giuseppe** [comment]
@kargakis sure, just had a look at it.  Is `/usr/local/bin/docker` supposed to be used only by the node when running as a container?

I don't know all the details behind it, but if we want to use it from the host, should the script check if /rootfs exists before using it or am I missing something?

```bash
if test -e /rootfs; then
    exec chroot /rootfs docker "${@}"
fi

exec /usr/bin/docker "${@}"
```

**Comment by stevekuznetsov** [comment]
@sdodson since you are the author of that `docker` script -- maybe you can clarify here as well.

**Comment by sdodson** [comment]
Yes, it should only be used inside the node image.

If you want it inside the rpm we should add the test to see if /rootfs exists, probably best to test /rootfs/usr/bin/docker actually but I don't see any purpose in including this script outside of the node image.

**Comment by kargakis** [comment]
Yeah, it seems that fix is reasonable - @jupierce can you pull somebody in to vet this change and push the fix? Not in a laptop for the next week :)

**Comment by sdodson** [comment]
That fix being removing the wrapper from the rpm?

**Comment by kargakis** [comment]
I was talking about what Giuseppe is proposing. The alternative is moving the wrapper back in the Dockerfile. I am not sure what is more correct.

**Comment by giuseppe** [comment]
I've proposed that fix as I was not really sure of all the implications.  Now that I've a bit more context, I agree with @sdodson: I think it is better to drop it from the `.rpm` and have it only in the node image.

**Pull request closed without merging**
