### PR TITLE
add a security test to verify capabilities

### PR DESCRIPTION
**Pull request by yuvalk**
This will test the restricted scc is really restricted,
including only
0x000000000000051b=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_setpcap,cap_net_bind_service

Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is there a human readable diff for this?  Would be better to print that if it exists so that someone who isn't familiar with the low level linux stuff can still triage.

**Comment by yuvalk** [comment]
> Is there a human readable diff for this? Would be better to print that if it exists so that someone who isn't familiar with the low level linux stuff can still triage.

yeah,
good idea,
you mean beside what I provided in the commit msg I guess

I will add a call to capsh --decode on both values, to get that

**Comment by umohnani8** [comment]
This should pass after https://github.com/openshift/machine-config-operator/pull/2051 gets in

**Comment by umohnani8** [comment]
@smarterclayton @mrunalp this is ready to be merged, PTAL

**Pull request merged**
