### PR TITLE
TRT-1578: Enable operator degraded check

### PR DESCRIPTION
**Pull request by xueqzhan**
Start with failing operators that are degraded during test. We will capture all operators and analyze cases to see if exceptions should be created.

### CODE REVIEW

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-upgrade periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-upgrade periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-gcp-ovn-rt-upgrade periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-aws-ovn-conformance periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-upgrade periodic-ci-openshift-release-master-nightly-4.18-fips-payload-scan periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-upgrade

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-fips-payload-scan

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-upgrade-ovn-single-node

**Comment by neisw** [comment]
/lgtm

I see the degraded flakes in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29002/pull-ci-openshift-origin-master-e2e-aws-ovn-upgrade/1829489570433994752

**Pull request merged**
