### PR TITLE
temporarily remove the new-app conformance test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton approve?

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@mfojtik @jim-minter fyi.  we'll continue the investigation, but this is tripping up the merge queue way too often.

**Comment by bparees** [comment]
sms approval received.

**Comment by mfojtik** [comment]
@bparees sure, I will investigate this today.

**Pull request merged**
