### PR TITLE
BUG 1685322: fix init container check and prevent running to pending …

### PR DESCRIPTION
**Pull request by gabemontero**
…phase transition attempts

/assign @bparees (in case Adam does is not in the 3.11 OWNERS file)
/assign @adambkaplan

### CODE REVIEW

**Comment by bparees** [comment]
>  /assign @bparees (in case Adam does is not in the 3.11 OWNERS file)

if he's not, he should fix that :)

**Comment by gabemontero** [comment]
Yeah https://github.com/openshift/origin/blob/release-3.11/pkg/build/OWNERS has no Adam in it

**Pull request merged**
