### PR TITLE
Expose Openshift configs in test jobs

### PR DESCRIPTION
**Pull request by kargakis**
@stevekuznetsov @deads2k

### CODE REVIEW

**Comment by kargakis** [comment]
I still don't see the file populated in the artifacts 😢 

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/16536/test_pull_request_origin_cmd/3509/artifacts/generated/

**Comment by kargakis** [comment]
Hrm, we seem to be missing `OS_BUILD_ENV_PRESERVE` in the job.

**Comment by stevekuznetsov** [comment]
You're looking in the wrong place:

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/16536/test_pull_request_origin_cmd/3509/artifacts/scripts/test-cmd/openshift.local.config/

**Comment by kargakis** [comment]
Oh, that settles it then.

**Comment by stevekuznetsov** [comment]
/lgtm cancel

real error:

```
chmod: cannot access ‘/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/openshift.local.config/master/admin.kubeconfig’: No such file or directory
```

**Pull request closed without merging**
