### PR TITLE
Kube 1.4 cherry picks

### PR DESCRIPTION
**Pull request by soltysh**
Resovles #11565. 

@liggitt @smarterclayton ptal
@pweil- @mfojtik fyi
### The summary (master #PR: title (cherry-pick #PR) - why):
- 33052: Bump cAdvisor Godeps version to official release tag - Only updated Godep.json to match 1.4 release, no actual change happened.
- 33086: Fix possible panic in PodAffinityChecker (33166) - Small fix, but can save us from nil panic
- 33170: Remove closing audit log file and add error check when writing to audit (33172) - Improve audit logging, especially when log operation fails
- 33346: disallow user to update loadbalancerSourceRanges (33513) - Changes Service validation, not sure we want to wait, but there's a TODO about being
  able to modify that
- 32807: Fix race condition in setting node statusUpdateNeeded flag (34038) - Race fix
- 32914: Limit the number of names per image reported in the node status (34157) - Fix OOM master etcd on big clusters
- ~~34000: Set deserialization cache size based on target memory usage (34213) - To reduce memory usage to reasonable levels in smaller clusters~~
- 33796: Fix issue in updating device path when volume is attached multiple times (34215) - P0 fixing wrong AWS volume mount issue
- 33735: Fixes in HPA: consider only running pods; proper denominator in avg (34224) - Update which pods are calculated for HPA
- 33968: scheduler: initialize podsWithAffinity (34266) - Fix panic in scheduler
- 34076: Remove headers that are unnecessary for proxy target (34280) - P1 issue
- 34694: Handle DeletedFinalStateUnknown in NodeController (34803) - Fix panic in NodeController caused by receiving DeletedFinalStateUnknown object from the cache.
- 34809: NodeController waits for informer sync before doing anything (34813) - P0 issue
- 34251: Fix nil pointer issue when getting metrics from volume mounter (34296) - Possible nil pointer panic
- 34851: Only wait for cache syncs once in NodeController (34861) - P0 in branch 1.4, P1 in master
- 34895: Fix non-starting node controller in 1.4 branch - P0 in branch 1.4
- 34955: HPA: fixed wrong count for target replicas calculations (35406) - P0 issue
- 35071: Change merge key for VolumeMount to mountPath (35208) - Fixes VolumeMounts edit operation
- 35273: Fixed mutation warning in Attach/Detach controller (35633) - Fixes cache mutation
- 34368: Node status updater should SetNodeStatusUpdateNeeded if it fails to (35653) - Fix node status update

Not sure about:
- 35205 - contains fixes to etcd3
- 33699 - moves informer to client

### CODE REVIEW

**Comment by smarterclayton** [comment]
Are any of those cherry picks *not* from 1.4?

**Comment by smarterclayton** [comment]
[test]

**Comment by soltysh** [comment]
> Are any of those cherry picks *not* from 1.4?

Nope, just 1.4 branch.

**Comment by timothysc** [comment]
Just out of curiosity, does anything break if we just updated the godep ref?  It seems like we're applying a wand here.

**Comment by smarterclayton** [comment]
I did a patch rebase but it was failing upstream e2e and is too risky right now.  We have to rebase 90 patches upstream right now in order to pick a new bump (which if this had been started two weeks ago would have been the right choice).

**Comment by derekwaynecarr** [comment]
This needs to pull in https://github.com/kubernetes/kubernetes/pull/33806 to fix https://github.com/openshift/origin/issues/11199

**Comment by soltysh** [comment]
@derekwaynecarr I've cherry picked that, but it was a bit tricky, mind having a look if that's ok?
@smarterclayton https://github.com/openshift/origin/commit/b0c9f3b7c2808fe63626a0d0f60a0dd1c472cf78 and https://github.com/openshift/origin/commit/960774831eef8ac426e793106f21a5765f55a246 are dropped (1st - manually reverted, 2nd - reverted during upgrading cAdvisor)
@bparees I had to revert s2i bump @PI-Victor did, just fyi since it was pointing to non-existent commit

**Comment by bparees** [comment]
@soltysh did you talk to @PI-Victor about that?  those changes are important.

**Comment by soltysh** [comment]
@bparees yes, if there's a requirement to have those changes in, we need to create a branch and have a official commit that is reachable.

**Comment by soltysh** [comment]
@derekwaynecarr I had to split the cadvisor cherry-pick into two, one is the bump and the other is that cherry-pick itself. (the commit checker was complaining otherwise).

**Comment by ncdc** [comment]
I thought we stated that it was rather late to be pulling in 34000?

**Comment by soltysh** [comment]
> I thought we stated that it was rather late to be pulling in 34000

Haven't heard about it, but if you say so it can be easily dropped.

**Comment by ncdc** [comment]
@soltysh see https://github.com/openshift/origin/pull/10719#issuecomment-256618029

**Comment by soltysh** [comment]
@ncdc @mfojtik pointed me to the comment before about having those in, I'll blame him ;) but sure I can remove it.

**Comment by soltysh** [comment]
I dropped 34000, updated client-go to latest 1.4 and updated generated clientset. Hopefully that should be good.

**Comment by derekwaynecarr** [comment]
@soltysh -- the cadvisor bump looks good to me.  @sjenning fyi this would fix your issue if you want to verify against this PR.

**Comment by sjenning** [comment]
@derekwaynecarr on it

**Comment by sjenning** [comment]
@derekwaynecarr I confirmed this does fix #11199

**Comment by soltysh** [comment]
Rebased against latest master and fixed the errors that showed up in tests.

**Comment by mwringe** [comment]
Is this being tracking in a bugzilla for OCP anywhere?

**Comment by smarterclayton** [comment]
Tests are panicking

**Comment by ncdc** [comment]
I'll start looking into the panics.

**Comment by ncdc** [comment]
The panic is because our vendored copies of `k8s.io/kubernetes/pkg/client/restclient.Config` and `k8s.io/client-go/pkg/client/restclient.Config` don't have the same fields. They're identical except the former adds 1: `Timeout`. And `vendor/k8s.io/kubernetes/test/e2e/framework/framework.go#getClientRepoConfig` expects the structs to match.

**Comment by timothysc** [comment]
ETA on fixes?  This is blocking a bunch of stuff.

**Comment by ncdc** [comment]
Working on it

**Comment by ncdc** [comment]
This is why the former struct has Timeout and the latter doesn't: https://github.com/openshift/origin/pull/11104

**Comment by ncdc** [comment]
Testing a fix in #11709

**Comment by smarterclayton** [comment]
Moving to #11709

**Pull request closed without merging**
