### PR TITLE
stop running the TSB in the main apiserver

### PR DESCRIPTION
**Pull request by deads2k**
The last commit here stops serving the TSB from the apiserver.  I'm expecting failures, so this is flushing them out for me.

I've left the types to do separately in case it breaks the patch command used elsewhere to add this to the config.

### CODE REVIEW

**Comment by deads2k** [comment]
@jim-minter can you confirm that these are the only two tests that require it to be enabled?

```
Extended.[templates] templateservicebroker security test should pass security tests
Extended.[templates] templateservicebroker end-to-end test should pass an end-to-end test
```

**Comment by jim-minter** [comment]
@deads2k Correct.

**Comment by jim-minter** [comment]
don't know if there's more coming but lgtm so far

**Comment by deads2k** [comment]
> don't know if there's more coming but lgtm so far

I've got to start using the templates and move these tests into the normal conformance bucket.  Then this will be ready.

**Comment by deads2k** [comment]
@jim-minter please take another look. I've remove more dead code.

This is blocked on https://github.com/openshift/origin/pull/15677 and https://github.com/openshift/origin/pull/15707

**Comment by jim-minter** [comment]
Will it be possible for templateServiceBrokerConfig be removed from pkg/cmd/server/api/v1/types.go?  Is this the point at which it can happen?  If so, doing a grep -r templateServiceBrokerConfig and fix-up would be good.

**Comment by jim-minter** [comment]
otherwise still lgtm

**Comment by deads2k** [comment]
> Will it be possible for templateServiceBrokerConfig be removed from pkg/cmd/server/api/v1/types.go? Is this the point at which it can happen? If so, doing a grep -r templateServiceBrokerConfig and fix-up would be good.

It's on my list, but on my list to do separately. I'm not completely sure what will happen to the installer if I do it.

**Comment by deads2k** [comment]
prereqs have merged.  tagging

**Pull request merged**
