### PR TITLE
Bug 1833824: unskip template extended tests

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick because bot failed

see https://github.com/openshift/origin/pull/24912#issuecomment-626173702

### CODE REVIEW

**Comment by gabemontero** [comment]
aws flakes

/retest

**Comment by gabemontero** [comment]
ok `[Conformance][Templates]` e2e tests passed in e2e-gcp without additional change as manual testing had shown;
change in master branch was only needed since it vendored 1.18 k8s

/assign @bparees

**Comment by bparees** [comment]
@sdodson test code changes only so should be safe to cherry pick

**Pull request merged**
