### PR TITLE
Bug 1854311: 4.5: UPSTREAM: 91307: CSI: Modify VolumeAttachment check to use Informer/Cache

### PR DESCRIPTION
**Pull request by jsafrane**
Backported version of https://github.com/openshift/origin/pull/25109
@openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/assign @knobunc 
for backport approval

**Comment by fromanirh** [comment]
to fix the aws-serial lane you will need this https://github.com/openshift/origin/pull/25284

**Pull request merged**
