### PR TITLE
[1.4] Change logging deployer image name from 'logging-deployment' to 'logging-deployer'

### PR DESCRIPTION
**Pull request by csrwng**
Backport of https://github.com/openshift/origin/pull/13151

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
PodDisruption extended test will fail until https://github.com/openshift/origin/pull/13174 merges

**Comment by smarterclayton** [comment]
Is this going to cleanly merge?

**Comment by smarterclayton** [comment]
[test]

**Pull request closed without merging**
