### PR TITLE
UPSTREAM: containers/image: <carry>: Do not check lifetime for v3 gpg signature

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/15489

@mtrmac 

With this fix:

```
$ oc adm verify-image-signature sha256:582cb940a6e730dbdffee7cc5e1983522fdeeb3c40bea7373b255a209124cc02 --expected-identity=registry.access.redhat.com/rhel7:latest --public-key=/tmp/redhat.pub --save

$ oc describe istag rhel7:latest
Image Signatures:
			Name:		sha256:582cb940a6e730dbdffee7cc5e1983522fdeeb3c40bea7373b255a209124cc02@rhel7
			Type:		AtomicImageV1
			Status:		Verified
			Issued By:	199E2F91FD431D51
			Signature is Trusted (verified by user "test-admin" on 2017-07-27 10:44:00 +0200 CEST)
			Signature is ForImage ( on 2017-07-27 10:44:00 +0200 CEST)
```

### CODE REVIEW

**Comment by mtrmac** [comment]
ACK.

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/13536

**Comment by kargakis** [comment]
Shouldn't be tagged as critical since the freeze tomorrow should be for 3.6

**Comment by kargakis** [comment]
/joke

should not work

**Pull request merged**
