### PR TITLE
OCPBUGS-39030: kube-apiserver rollout: wait for stability before exiting

### PR DESCRIPTION
**Pull request by stbenjam**
We are sometimes leaving this test with kube-apiserver operator "Progressing" -- this triggers a failure in gather-extra of the "operator conditions kube-apiserver" test, which expects operators to be stable when the job finishes.

Before we return from this test, make sure kube-apiserver is not progressing.

### CODE REVIEW

**Comment by neisw** [comment]
/lgtm
/hold
unhold when you are ready

**Comment by stbenjam** [comment]
/hold cancel

This does what I wanted

**Pull request merged**
