### PR TITLE
Docker distribution 2.5.1

### PR DESCRIPTION
**Pull request by legionus**

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton I thought you reworked the vendor dir for the dockerregistry stuff... does this look right?

**Comment by liggitt** [comment]
I think the issue was conflicting sub-dependencies... I'm pretty sure we need docker/distribution to have its own vendor dir, as it does today

**Comment by smarterclayton** [comment]
Yeah, but I'm rebasing kube and it's going to land before this, so don't
get hung up on that

**Comment by legionus** [comment]
I added this to keep track of progress. There is still a lot of work. I still need to check what will happen due to the removal of `signaturesStorage`.

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HDvNs4kE&#x2F;738-5-rebase-docker-distribution-to-2-5-0"> (5) Rebase docker&#x2F;distribution to 2.5.0</a>

**Comment by mfojtik** [comment]
This LGTM. Nice job @legionus !

@smarterclayton @liggitt do you guys have any final comments before we merge this? AFAIK this is mostly bug fixing and pickup of our patches to Docker distribution, together with some improvements to storage drivers.

**Comment by smarterclayton** [comment]
Changes LGTM.  Are there any new tests we need?

**Comment by liggitt** [comment]
can we run the extended tests for builds and images, since those have been hit by previous docker bumps?

**Comment by mfojtik** [comment]
[testonlyextended][extended:core(builds)]

**Comment by liggitt** [comment]
@smarterclayton were you expecting massive vendor deletions?

**Comment by smarterclayton** [comment]
the vendor carry looked correct.

**Comment by legionus** [comment]
re[test]

**Comment by mfojtik** [comment]
[test] 

(amazon problem)

**Comment by mfojtik** [comment]
[merge]

flake: https://github.com/openshift/origin/issues/8571

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by legionus** [comment]
[test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10988 [merge]

**Pull request merged**
