### PR TITLE
Measure container restarts over an interval instead of absolute

### PR DESCRIPTION
**Pull request by smarterclayton**
We run these tests after disruptive events where restarts are
necessary. Instead of looking at absolute restart count, capture
the number of initial restarts and then compare subsequent runs
to ensure the count is smaller. We double the time interval and
halve the number of failing restarts in order to ensure we capture
slow restart failures (full backoff is 5m, but we can catch slow
but not limited backoff).

### CODE REVIEW

**Comment by wking** [comment]
[images][1]:

```
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2...501ab66378d954ee8617: unauthorized: authentication required
```

Dunno what that's about.

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/25115/pull-ci-openshift-origin-master-images/1272645199763345408

**Comment by hexfusion** [comment]
fips
> Jun 16 14:53:01.193 E ns/e2e-test-build-webhooks-d2ph5 pod/pushbuild-1-build node/ip-10-0-190-41.us-west-1.compute.internal container/git-clone container exited with code 1 (Error): Cloning "http://my.docker/build" ...\nerror: fatal: unable to access 'http://my.docker/build/': Could not resolve host: my.docker; Unknown error\n

https://search.apps.build01.ci.devcluster.openshift.com/?search=fatal%3A+unable+to+access+%27http%3A%2F%2Fmy.docker&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by smarterclayton** [comment]
GCP passed, going to mark this green to unblock e2e-aws-disruptive

**Pull request merged**
