### PR TITLE
[DO_NOT_MERGE] hack-lib: set internal registry hostname

### PR DESCRIPTION
**Pull request by miminar**
To make sure it gets whitelisted.

### CODE REVIEW

**Comment by bparees** [comment]
not clear why this is causing problems in conjunction w/ the ansible install.  the ansible install should be setting the internal hostname already so in any situation where the ansible installer created the cluster, shouldn't this be set already?

**Comment by miminar** [comment]
The relevant configuration of registry domain name happens in ansible. I'm closing this and will continue debugging in the ansible PR.

**Pull request closed without merging**
