### PR TITLE
Work-around oc delete issues in newapp tests

### LINKED ISSUE #19588: Cmd test fails "oc delete all -l app=testapp2"
Test flake in cmd tests - the "delete all" test seems to fail, potentially because the application under test has already been deleted.

##### Version
v3.10.0-alpha0

##### Current Result
Test failure: github.com/openshift/origin/test/cmd/newapp test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success 1.66s

##### Expected Result
Test passes.

##### Additional Information
Failed test: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19532/test_pull_request_origin_cmd/13227/
Logs:
```
=== BEGIN TEST CASE ===
test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success
FAILURE after 1.658s: test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success: the command returned the wrong error code
Standard output from the command:
deploymentconfig.apps.openshift.io "testapp2" deleted
buildconfig.build.openshift.io "testapp2" deleted
imagestream.image.openshift.io "testapp2" deleted

Standard error from the command:
Error from server (NotFound): builds.build.openshift.io "testapp2-1" not found
=== END TEST CASE ===
```

### PR DESCRIPTION
**Pull request by adambkaplan**
* Addresses timing issues with reap/GC on build objects
* Explicit deletes for services, dc, bc, and imagestreams

Fixes #19588

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
`all` should pick up the necessary resources, this seems weird.

**Comment by deads2k** [comment]
> /hold
> all should pick up the necessary resources, this seems weird.

Yeah, looks like you're just looking for a wait until you don't get any resources back, right?

**Comment by soltysh** [comment]
This was fixed in https://github.com/openshift/origin/pull/19616
/close

**Pull request closed without merging**
