### PR TITLE
Create an official admin command

### PR DESCRIPTION
**Pull request by smarterclayton**
Move methods from 'ex' under it. Also makes overwrite-policy default
to a dry run.

@deads2k review

### CODE REVIEW

**Comment by deads2k** [comment]
I'd like to fix up the policy command names when we move them.  
```
add-user-to-role
add-group-to-role
remove-user-from-role
remove-group-from-role
```

Otherwise, lgtm.

**Comment by smarterclayton** [comment]
I think we need to schedule a comprehensive review of all command names and set some patterns.  Lots of "ex" stuff (and CLI stuff) is still pretty raw.

----- Original Message -----

**Comment by deads2k** [comment]
@smarterclayton Can we fix those four in particular during this move?  I don't mind touching it up afterwards in https://github.com/openshift/origin/pull/1454.

Can you fix the merge conflicts so we can drop this in?   https://github.com/openshift/origin/pull/1454 touches a lot of the same files and I'd like to go on top this as opposed to the other way around.

**Comment by smarterclayton** [comment]
Fixed.  remove-user-from-project is now remove-user (since it's under policy)

----- Original Message -----

**Comment by deads2k** [comment]
I'd swear that middle commit just got bigger....

[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
