### PR TITLE
Disable deployment config detail message updates

### LINKED ISSUE #5706: Deployment config status update can indefinitely accumulate message contents
When the deployment config status updater sees an image change trigger move from invalid to valid, the old invalid message can grow by being appended each time the details are recomputed (even more quickly if multiple image change triggers exist for the config).

### PR DESCRIPTION
**Pull request by ironcladlou**
Disable deployment config detail message updates until the performance
issues with it are resolved.

Fixes #5706

### CODE REVIEW

**Comment by ironcladlou** [comment]
@smarterclayton

**Comment by ironcladlou** [comment]
Can be reenabled with something like #5530

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
In the meantime we can support this via oc status.

**Pull request merged**
