### PR TITLE
Image push/pull policy updates

### PR DESCRIPTION
**Pull request by ncdc**
Allow anyone to pull images from the openshift project.

Allow editors to pull and push images.

### CODE REVIEW

**Comment by ncdc** [comment]
@liggitt @deads2k @smarterclayton

**Comment by deads2k** [comment]
lgtm.

It does seem a little weird that it's not part of this group: https://github.com/openshift/origin/blob/master/pkg/authorization/api/types.go#L57.  Most of the time, don't rights to all those objects go together?

**Comment by ncdc** [comment]
I think @smarterclayton wanted to separate who could see info about an image stream from who could actually pull.

**Comment by liggitt** [comment]
Yeah view in API != pull

**Comment by liggitt** [comment]
LGTM, @smarterclayton merge?

**Comment by deads2k** [comment]
> I think @smarterclayton wanted to separate who could see info about an image stream from who could actually pull.

Because they should be separate by default or because it needs to be possible to be separate?  If they commonly go together and uncommonly need to be separated, then adding to the group makes sense.

**Comment by liggitt** [comment]
Similar to pod/exec, I think. We didn't want anyone to accidentally get it from a group definition.

**Comment by deads2k** [comment]
`pod/exec` ended up that way because `get` on `pod/exec` allowed mutation.  That's not the case here.

**Comment by smarterclayton** [comment]
Approved [merge]

**Pull request merged**
