### PR TITLE
add verbose logging to new-app flake and remove extraneous tryuntil logging

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
adds logging to try to debug https://github.com/openshift/origin/issues/5318

@smarterclayton ptal.

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
This is fixed by my change... there's no point to testing it?

**Comment by bparees** [comment]
yeah i didn't know you'd already fixed that.  I still want to keep the redirect to dev/null because the output is trashing the logs, but i'll remove the loglevel 5.

**Comment by smarterclayton** [comment]
I'd prefer to print something.  The error message that is printed is often useful for debugging true failures.

**Comment by bparees** [comment]
@smarterclayton updated to just strip down the tryuntil output.

**Comment by bparees** [comment]
> I'd prefer to print something. The error message that is printed is often useful for debugging true failures.

then we either need to change it to print the last failure only, or reduce the retry interval.  it's making a mess of the logs right now and makes it look like things are broken that actually are fine.

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
