### PR TITLE
Improve display of logs in web console

### PR DESCRIPTION
**Pull request by spadgett**
Fill screen height and move ellipsis to bottom. Improve display of details and actions above log.

screen shot 2016-04-04 at 10 22 05 am

screen shot 2016-04-04 at 10 22 23 am

@smarterclayton @jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by smarterclayton** [comment]
Love it

**Comment by smarterclayton** [comment]
Approved for 3.2 if you think it is low risk enough.

**Comment by jwforres** [comment]
@spadgett LGTM if you are happy with the amount of testing you've done so far i think we can merge

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
