### PR TITLE
Accessibility: make enter key work when confirming project name

### PR DESCRIPTION
**Pull request by spadgett**
Use a form and make the button `type="submit"` so that the enter keys works when typing the project name to delete.

@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
And hitting enter when focus is on the cancel button still cancels right

**Comment by spadgett** [comment]
It should. I'll confirm.

**Comment by spadgett** [comment]
Yes, pressing enter with the cancel button focused correctly cancels.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
