### PR TITLE
Fix cadvisor in integration test

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
@danmcp seeing a weird error: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5507/consoleText

```
+ '[' -n '' ']'
+ echo '[extended:<test1>,<test2>] is required with testonlyextended'
[extended:<test1>,<test2>] is required with testonlyextended
```

**Comment by deads2k** [comment]
jenkins issue re[test]

**Comment by deads2k** [comment]
failure in the diag test.

```
I1007 18:40:46.544106   28652 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc20a823bc0), Err:0x6f}, trying again: "ip-172-18-0-82:10250"
I1007 18:40:47.545281   28652 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc2096e1fb0), Err:0x6f}, trying again: "ip-172-18-0-82:10250"
I1007 18:40:48.546424   28652 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc20a5f6870), Err:0x6f}, trying again: "ip-172-18-0-82:10250"
I1007 18:40:49.547556   28652 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc20a6b3650), Err:0x6f}, trying again: "ip-172-18-0-82:10250"
I1007 18:40:50.548873   28652 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc20a6b3860), Err:0x6f}, trying again: "ip-172-18-0-82:10250"
I1007 18:40:51.110748   28652 nodecontroller.go:572] Cancelling pod Eviction on Node: ip-172-18-0-82
--- FAIL: TestDiagNodeConditions-2 (16.75s)
	diag_nodes_test.go:22: unexpected error: dial tcp 172.18.0.82:10250: connection refused
```

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
