### PR TITLE
Remove special handling of --token and --context for whoami

### PR DESCRIPTION
**Pull request by liggitt**
Remove the deprecated flags so we can specify client credentials directly with `whoami`

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k @juanvallejo

**Comment by deads2k** [comment]
@liggitt anything you need to do for a release-note?

**Comment by deads2k** [comment]
lgtm, just the question about release note

**Comment by juanvallejo** [comment]
lgtm as well

**Comment by juanvallejo** [comment]
[test]

**Comment by liggitt** [comment]
in 1.4 release notes in https://github.com/openshift/openshift-docs/issues/2933#issuecomment-250586558

will add to 1.5 release notes as well

**Comment by liggitt** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/133/) failed from the following flakes:
 - [conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/133/testReport/junit/(root)/Extended/_networking__router__openshift_routers_The_HAProxy_router_should_override_the_route_host_with_a_custom_value/) failed on: #12322 

re[merge]

**Pull request merged**
