### PR TITLE
Re-pick Upstream 53916: update .dockercfg content to config.json

### PR DESCRIPTION
**Pull request by juanvallejo**
This change was introduced in https://github.com/openshift/origin/pull/16868 and lost during the 1.8.1 rebase: https://github.com/openshift/origin/pull/17115/commits/c4b40b3f401472203fcef1927f3c5ce40da07056

cc @bparees @openshift/cli-review

### CODE REVIEW

**Comment by bparees** [comment]
@juanvallejo I doubt this fixes https://github.com/openshift/origin/issues/17523 since i don't think that user was on a post-1.8 rebase version of origin... were they?

**Comment by juanvallejo** [comment]
@bparees 
> I doubt this fixes #17523 since i don't think that user was on a post-1.8 rebase version of origin... were they?

Hm, they seem to be using oc 3.6, although [per this comment](https://github.com/openshift/origin/issues/17523#issuecomment-349566547), the issue also seems to be happening with 3.7 clients

**Comment by juanvallejo** [comment]
@bparees I had assumed the issue to be related to the format in which the secret data was being stored per this comment: https://github.com/openshift/origin/issues/17523#issuecomment-351435439

I assumed the secret data they were getting when creating a secret using `oc create secret docker-registry ...` was in .dockercfg format, then when they exported this data and created a new secret with it by passing it to the `.dockerconfigjson` parameter, they then reported the secret to work after adding it to imagePullSecrets

**Comment by bparees** [comment]
@juanvallejo well i think you're right that what they created is being created in the .dockercfg format.  But I still haven't heard why that's wrong, since our project secrets use that format too.

Anyway i think this is a good catch but probably not the root cause of the issue.

**Comment by juanvallejo** [comment]
ping @fabianofranz

**Comment by juanvallejo** [comment]
ping @deads2k

**Comment by deads2k** [comment]
@juanvallejo is this the broken fix or the proper fix?

**Comment by soltysh** [comment]
This is already addressed in several PRs of mine. See https://bugzilla.redhat.com/show_bug.cgi?id=1531511 for the entire list of those.

**Pull request closed without merging**
