### PR TITLE
move cakephp e2e skip down a level to make openshift-tests happy

### PR DESCRIPTION
**Pull request by gabemontero**
@adambkaplan @sallyom let's see if this still skips cakephp in the e2e's while we wait on the upstream fix

@sallyom let me know what you see when you run locally with this

### CODE REVIEW

**Comment by sallyom** [comment]
/lgtm

_who can know all the wonky ways of ginkgo?_

**Comment by gabemontero** [comment]
> /lgtm
> 
> _who can know all the wonky ways of ginkgo?_

:-)

in addition to pass/fail, I'll inspect the image-ecosystem e2e run and verify that the expected set of tests are run except for the cakephp ones

**Comment by gabemontero** [comment]
oh, and @sallyom told us in slack that with the skip moved down her local runs were now as expected

**Review by soltysh — APPROVED** [review]
/approve

**Comment by gabemontero** [comment]
OK if you look at the "Tests Passed" section of https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25644/pull-ci-openshift-origin-master-e2e-gcp-image-ecosystem/1321804477623177216 you'll see plenty of 

`[sig-devex][Feature:ImageEcosystem]`

tests passing ... just not any of the cakephp ones

**Comment by gabemontero** [comment]
hey @soltysh ... this new agnostic cmd e2e has a failure with:

```
Running test/cmd/env.sh:21: executing 'oc get dc/testdc -o jsonpath='{ .spec.template.spec.containers[?(@.name=="default-container")].env }'' expecting success and not text 'name.?\:.?key'...
FAILURE after 30.000s: test/cmd/env.sh:21: executing 'oc get dc/testdc -o jsonpath='{ .spec.template.spec.containers[?(@.name=="default-container")].env }'' expecting success and not text 'name.?\:.?key': the command returned the wrong error code
```

known flake/issue?  or something to look into?

**Comment by soltysh** [comment]
that test should not be required for origin, it wasn't before it was renamed to agnostic, lemme fix that.
/override ci/prow/e2e-agnostic-cmd

**Comment by gabemontero** [comment]
e2e-aws-serial failiure:
- 3 sig-scheduling failures
- 1 sig-network 1 sig-arch flay

/test e2e-aws-serial

**Pull request merged**
