### PR TITLE
remove dead cancel code

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal, pretty sure this code is unreachable.. see:
https://github.com/openshift/origin/pull/8191/files#diff-661252da3ac92a7bc8779d5eee2f7601L85
and
https://github.com/openshift/origin/pull/8191/files#diff-661252da3ac92a7bc8779d5eee2f7601L93

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Pull request merged**
