### PR TITLE
use the test namespace so the registry imagerepo update works

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @ironcladlou @pmorie  something appears to have changed recently w/ the docker registry callback to update the imagerepo where it now tries to automatically determine the imagerepo name based on the namespace information, which broke the sample app (though not the end-to-end test because it used "test" as the namespace).

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
or rather it tries to determine the namespace of the imagerepo based on the imagerepo name, which did not align in this case.

**Comment by smarterclayton** [comment]
LGTM, missed the doc when I changed [merge]

**Pull request merged**
