### PR TITLE
Use errors.New() instead of fmt.Errorf() where possible.

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @bparees

### CODE REVIEW

**Comment by bparees** [comment]
what's the benefit to making this change over having a consistent way of generating errors?

**Comment by bparees** [comment]
(I understand there is some overhead to calling Errorf even though we aren't formatting anything, but error paths don't tend to be performance bottlenecks)

**Comment by php-coder** [comment]
My IDE (IntelliJ IDEA) shows me these lines as warnings and this is annoying. I wouldn't fix these otherwise :)

**Comment by bparees** [comment]
can you turn off that warning? :)

**Comment by bparees** [comment]
lgtm, but post 3.3.

**Comment by PI-Victor** [comment]
personally i support this change (i know nobody asked :)). i think we all know fmt.Errorf should be used only when you want to format the error. we're using it everywhere, which i think is wrong.
on the other hand, if now you want to format the error you'll have to revert the whole change.
i think it's more Go's fault than the way we do it.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
