### PR TITLE
Bug 1860830: Ensure Azure availability zone is always in lower cases

### PR DESCRIPTION
**Pull request by enxebre**
Cherry-pick https://github.com/kubernetes/kubernetes/pull/89878

### CODE REVIEW

**Comment by enxebre** [comment]
cc @jim-minter @mjudeikis @deads2k @mfojtik

**Comment by enxebre** [comment]
cc @sdodson @mrunalp for patch manager approval

**Comment by sttts** [comment]
/hold

Changes to vendor/k8s.io/kubernetes need a proper commit message: `UPSTREAM: 12345: text` where 12345 is the upstream PR with the change.

**Comment by enxebre** [comment]
>Changes to vendor/k8s.io/kubernetes need a proper commit message: UPSTREAM: 12345: text where 12345 is the upstream PR with the change.

Thanks. Updated. We need to put a script and block CI on it.

**Comment by tnozicka** [comment]
> We need to put a script and block CI on it.
there is one but it got broken. The fix is tracked in https://github.com/openshift/origin/pull/25366

**Comment by enxebre** [comment]
/retest

@sttts you good to cancel the hold now?

**Comment by enxebre** [comment]
cc @sdodson for cherry-pick-approved label.

**Pull request merged**
