### PR TITLE
Fix extended networking service tests to retry updates on conflict

### LINKED ISSUE #14197: networking-minimal services flake "Failed to get endpoints"
Expected error:
        <*errors.errorString | 0xc421b8d0b0>: {
            s: "Failed to get endpoints for e2e-tests-net-services1-01zbr/service-9jzp2",
        }
        Failed to get endpoints for e2e-tests-net-services1-01zbr/service-9jzp2
    not to have occurred

This can occur on any of the tests in services.go:

"should allow connections to another pod on the same node via a service IP"
"should allow connections to another pod on a different node via a service IP"
"should prevent connections to pods in different namespaces on the same node via service IPs"
"should prevent connections to pods in different namespaces on different nodes via service IPs"
"should allow connections to services in the default namespace from a pod in another namespace on the same node"
"should allow connections to services in the default namespace from a pod in another namespace on a different node"
"should allow connections from pods in the default namespace to a service in another namespace on the same node"
"should allow connections from pods in the default namespace to a service in another namespace on a different node"

### PR DESCRIPTION
**Pull request by danwinship**
Service tests are currently flaking because apparently the endpoints controller believes that there are no pods (even un-ready ones) backing the service sometimes:

    May 12 20:32:13 nettest-master openshift[137]: I0512 20:32:13.660931     137 endpoints_controller.go:445] Update endpoints for e2e-tests-net-services1-jnk1d/service-8nc7r, ready: 0 not ready: 0

The code in the test updates the pod without retrying-on-failure; something must have changed elsewhere recently that causes some other part of the code to update new pods immediately after creation (or at least changed the timing of an existing potential conflict that we were reliably avoiding).

Fixes #14197 

(hopefully)

@openshift/networking @smarterclayton @stevekuznetsov

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@ncdc does any of this ring a bell? did the rebase land something like this? Do we need to update other tests that do similar things?

**Comment by ncdc** [comment]
@stevekuznetsov retrying on conflict is generally a good thing to do. I don't recall offhand what, if anything, might have started mutating the pod in 1.6. You can check the master api logs for PUT and PATCH requests and see if you can find a culprit.

**Comment by danwinship** [comment]
> Do we need to update other tests that do similar things?

Everything is supposed to be retrying-on-update anyway. Hopefully the reason it didn't break anywhere else is because everywhere else was already doing it right.

> You can check the master api logs for PUT and PATCH requests and see if you can find a culprit.

There are 2 PUTs to the pod's /status right after creation, but I don't know if that's new.

**Comment by imcsk8** [comment]
Code looks good. Will test manually

**Comment by knobunc** [comment]
[merge]

**Comment by danwinship** [comment]
flake #14245 [merge]

**Comment by danwinship** [comment]
flake #14236 [test]

**Pull request merged**
