### PR TITLE
Issue 4632 - remove 'Project' from the project overview header

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/4632

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett just going to make this change for now because we need the screen real estate the header gives us for the view switcher between tile vs topology views

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
unrelated [merge]

**Comment by jwforres** [comment]
needed to update e2e test to match [merge]

**Pull request merged**
