### PR TITLE
sdn: remove need for locking in pod tests

### PR DESCRIPTION
**Pull request by dcbw**
Fixes: https://github.com/openshift/origin/issues/11640

@openshift/networking @soltysh

### CODE REVIEW

**Comment by danwinship** [comment]
It seems like all the locking stuff is just an artifact from an earlier version of the CNI PR, when there was actually parallelism in podManager... The way things work now, filling in the expected pod list in parallel with making the requests just adds complication to podTester without actually doing anything more to test the functionality of podManager. You should just make all of the addExpectedPod() calls before any of the addRequest() calls, and then you won't need any locking at all.

**Comment by dcbw** [comment]
@danwinship good point, fixed and repushed.

**Comment by danwinship** [comment]
LGTM although the commit message summary still talks about "under pod lock"
[test]

**Comment by knobunc** [comment]
```
!!! gofmt needs to be run on the following files: 
./pkg/sdn/plugin/pod_test.go
```

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
