### PR TITLE
Router: Changed default resource resync interval from 10mins to 30mins

### PR DESCRIPTION
**Pull request by pravisankar**
- Resyncs are mainly intended for robustness. Mainly to handle the case
where the resource handler failed to process the item and we hope this
will be fixed if we process the item again after sometime(resync interval).
Yes, this may fix some transient errors but if we resync frequently then
there could be big penalities.

- Currently router watches these resources: routes, endpoints, nodes,
namespaces, ingresses and secrets. When we have many routes
(like several thousand in online case), processing these items takes
long time, router reload itself takes few seconds (not milliseconds).
Due to short resync interval there will be constant churn of reprocessing
of all the items for all these resources.

- Earlier we needed shorter resync interval because sharded router was depending
on this interval but with #16039 that limitation is removed.

10 mins seems aggressive for some rare transient errors, changed defaults
to 30 mins. Admin can edit router deployment config if they need custom resync interval.

Fixed project sync interval in router

### CODE REVIEW

**Comment by pravisankar** [comment]
@knobunc @eparis @rajatchopra PTAL

**Comment by eparis** [comment]
/hold
Is there a bz or other specific problem this is trying to address? Admittedly we should never need the resync, but 30 minutes seems like an aweful long time...

**Comment by pravisankar** [comment]
@eparis 
We use 30 mins resync interval in openshift SDN. I'm assuming transient problems are rare and in most cases when it fails first time, it is highly likely that it will also fail next time. Any recommendations?
There is no open bug for this but the second commit fixes the issue where project sync interval could be negative if tunable resync interval is very low.

**Comment by imcsk8** [comment]
LGTM

**Comment by eparis** [comment]
/lgtm
but lets leave this held until master opens for 3.8.

**Pull request merged**
