### PR TITLE
Add TLS support to docker client

### PR DESCRIPTION
**Pull request by csrwng**
Allows new-app to connect to Boot2docker daemon on the Mac

### CODE REVIEW

**Comment by csrwng** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by liggitt** [comment]
Ca and cert/key should be individually specifiable, not hardcoded subpaths

**Comment by liggitt** [comment]
Ca or cert specification implies TLS mode

**Comment by liggitt** [comment]
Probably don't need the verify=1 env

**Comment by csrwng** [comment]
boot2docker only sets DOCKER_CERT_PATH and DOCKER_TLS_VERIFY

**Comment by csrwng** [comment]
doesn't set individual vars for ca or cert... and if DOCKER_TLS_VERIFY != 1, then the client should ignore the DOCKER_CERT_PATH

**Comment by liggitt** [comment]
I think that's a bad envvar mapping. If that's what boot2docker forces on us, I'd rather contain that in a function that populated a sane config struct with individual fields

**Comment by csrwng** [comment]
https://docs.docker.com/articles/https/

**Comment by liggitt** [comment]
Can't ca and cert/key still be independent? It doesn't look like ca is required to do cert/key and vice-versa.

**Comment by csrwng** [comment]
Hmm, not from what I've seen in the docker client, plus the go-dockerclient makes you send it a path for ca, but it's possible.

**Pull request merged**
