### PR TITLE
Retry image import conflicts

### PR DESCRIPTION
**Pull request by smarterclayton**
Create on ImageStreamMappings mutates the stream under the covers,
which means we need to reread the repo to get the latest copy.
Retry a limited number of times on conflicts.

@ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM. Need tests?

**Comment by smarterclayton** [comment]
Not going to do any at this point.  Maybe in a few weeks.

**Comment by ncdc** [comment]
np

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
