### PR TITLE
Wait longer for healthz during integration tests

### PR DESCRIPTION
**Pull request by enj**
Adding post start hooks makes it take longer for the server to report that it is healthy.  Thus we wait longer to ensure that the server actually failed to start.

Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
@smarterclayton my best guess for https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16017/test_pull_request_origin_integration/6650

**Comment by enj** [comment]
@stevekuznetsov why did the bot remove the approved label?

**Comment by stevekuznetsov** [comment]
Bot's being silly

**Pull request merged**
