### PR TITLE
Add descriptions to v1 policy api, remove deprecated field

### PR DESCRIPTION
**Pull request by derekwaynecarr**
@deads2k - please review.

Authorization part for #2632

### CODE REVIEW

**Comment by deads2k** [comment]
Wow, that was boring.  [merge]

**Comment by derekwaynecarr** [comment]
We need to make a point of requiring description on all code reviews.. we should verify it as part of merge queue so I can avoid this mundane process for a ton of areas in future.

**Comment by deads2k** [comment]
> We need to make a point of requiring description on all code reviews.. we should verify it as part of merge queue so I can avoid this mundane process for a ton of areas in future.

how portable is `hack/verify-description.sh` from upstream?

**Comment by derekwaynecarr** [comment]
@deads2k - I plan to look at this after doing this description work to avoid letting any regressions slip in before release

**Comment by deads2k** [comment]
The upstream checker was a hack based on magic filenames and grep.  I built a quick unit test to navigate the schemes and use reflection: https://github.com/openshift/origin/pull/2751

**Pull request merged**
