### PR TITLE
Router has an expired certificate by default

### PR DESCRIPTION
**Pull request by pecameron**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1349144

The haproxy router has a default certificate that has expired.
The certificate is used in reporting errors. The admin is
encouraged to supply a certificate as part setting up the router.
When that is not done this certificate used.

New Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 15068095030625975298 (0xd11ca0989e4a3c02)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=XX, ST=SomeState, L=SomeCity, O=SomeOrganization,
OU=SomeOrganizationUnit,
CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Validity
            Not Before: Jul  6 14:10:12 2016 GMT
            Not After : Jul  6 14:10:12 2026 GMT
        Subject: C=XX, ST=SomeState, L=SomeCity, O=SomeOrganization,
OU=SomeOrganizationUnit,
CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ..........
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier:
                DirName:/C=XX/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationUnit/CN=ip-10-35-63-192/emailAddress=root@ip-10-35-63-192
                serial:D1:1C:A0:98:9E:4A:3C:02

            X509v3 Subject Key Identifier:
                98:C9:38:24:CF:B5:7A:51:D8:EE:62:7A:A1:C2:40:AB:8A:80:BE:47
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment,
Data Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            Signature Algorithm: sha256WithRSAEncryption
                ............

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by smarterclayton** [comment]
@liggitt I'm not sure we should be checking in a cert anymore.

**Comment by liggitt** [comment]
definitely not, it should be generated per instance, otherwise it leads people to trust an uncontrolled private key

**Comment by smarterclayton** [comment]
Does this mean the router command needs to be generating one?  Or do we rely on the generated service cert?

**Comment by pecameron** [comment]
@liggitt @smarterclayton    I made a mistake the first time I pushed this to openshift/origin/bz1349144 PR9648. This time I pushed the same change to pcameron/origin/bz1349144 and created PR9719. So I need to find out how to get rid of PR9648. Neither one passes tests and I don't know what to fix to get either to pass.

Second, the bug is to replace an expired default cert.with one that is not expired. Clayton checked in the original cert, but it sounds like we don't want a default cert any more. How do we come to agreement on this?

I have been told that this default cert is only used when the router wants to respond to an error. It is a totally bogus cert (look at the details). This is my first time playing around with certs and I can use advise in what to do.
Thanks
phil

**Comment by knobunc** [comment]
@smarterclayton @liggitt: Do we just want to remove the default cert entirely and aly ways generate one with oadm router when no default cert is provided on the command line?  If so... do we want to use the openshift CA to sign the cert?  Or make it self-signed as we do today?  Also, do we want to make the subject something sane?  Or make it entirely bogus as todays default is?

My preference would be to make oadm router make a self-signed cert with a bogus subject.  What are your thoughts?

**Comment by pecameron** [comment]
@smarterclayton @liggitt @knobunc 
OK its been a while. How do we reach a decision on this?

**Comment by pecameron** [comment]
We decided not to do this.

**Pull request closed without merging**
