### PR TITLE
TRT-1347: Add ability to indicate a monitor test was skipped

### PR DESCRIPTION
**Pull request by stbenjam**
Currently when the image-registry is unavailable, the monitor tests all just come back successful with no additional data.  This is a bit confusing, since there's no indication that monitor didn't run other than the extremely short duration of the tests.  This introduces a NotSupportedError type that the monitor tests can return which will cause the tests to be skipped instead of faked success.

### CODE REVIEW

**Comment by dgoodwin** [comment]
This looks good, but there are some other monitortests using notSupportedReason which should probably get flipped as well.

**Comment by stbenjam** [comment]
I've updated the others, and took this out of draft.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28425/pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6/1729917490231775232 looks correct, image-registry reports skipped on metal

**Comment by dgoodwin** [comment]
/lgtm cancel

Just saw it was still wip, but it looks good.

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-upgrade

**Pull request merged**
