### PR TITLE
check for correct exiterr type on oc exec failures

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(replication)]

**Comment by bparees** [comment]
@gabemontero ptal, this should fix the recent rash of image extended test failures.  We weren't retrying the error, so if the replication wasn't immediate, we'd fail.

**Comment by gabemontero** [comment]
igtm .... curious, did some of the test infrastructure issues today lead to more initial errors on the query, and hence uncovered this failure to retry?

If so, I wonder how long this caused us pain, but other issues masked it :-)

**Comment by bparees** [comment]
@gabemontero i'm not sure, i guess that this test used to always replicate fast enough that the first check passed, and now replication is slower, but i'm not sure why.  when i tested locally the replication appeared to be instantaneous, but when i ran the extended test locally, it did indeed fail.. i couldn't figure out the difference.  possibly it has to do w/ the type of persistent volume being used.

**Comment by bparees** [comment]
failing test was a replication test from k8s picked up by my insufficiently specific filter, unrelated to this.

[merge]

**Comment by gabemontero** [comment]
On Wed, Aug 3, 2016 at 2:14 PM, Ben Parees <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> i'm not sure, i guess that
> this test used to always replicate fast enough that the first check passed,
> and now replication is slower, but i'm not sure why. when i tested locally
> the replication appeared to be instantaneous, but when i ran the extended
> test locally, it did indeed fail.. i couldn't figure out the difference.
> possibly it has to do w/ the type of persistent volume being used.
>
gotcha - thx

**Pull request merged**
