### PR TITLE
Fix typo in example `oc run` command.

### PR DESCRIPTION
**Pull request by dustymabe**
-tty is not an option. --tty is.

### CODE REVIEW

**Comment by deads2k** [comment]
We generate that doc from this file here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go#L55 . Can you update this file, then build it, then run `hack/update-generated-docs.sh`?

The commit would need to be named `UPSTREAM: <drop>: fix run example`, because its an upstream change that's already fixed in kube that we'll pick up in the next rebase.

@kargakis you mind taking this one?

**Comment by dustymabe** [comment]
if you'll pick it up in the next rebase then it's probably not worth fixing?

**Comment by deads2k** [comment]
> if you'll pick it up in the next rebase then it's probably not worth fixing?

We're likely to cut another tagged release before then and I'd rather have my examples correct.  Small improvements matter too.

**Comment by dustymabe** [comment]
> Can you update this file, then build it, then run hack/update-generated-docs.sh?

I ran that after updating the run.go file but it didn't change anything `-tty` is still in `docs/generated/oc_by_example_content.adoc`

> 
> The commit would need to be named UPSTREAM: <drop>: fix run example, because its an upstream change that's already fixed in kube that we'll pick up in the next rebase.

What is <drop>? The git commit of where it dropped in upstream?

**Comment by kargakis** [comment]
@deads2k sure

@dustymabe drop means that this change is already in Kubernetes or the next rebase will include changes that make this change unnecessary. Anyway, an indication to the poor guy doing the rebase to drop this patch. Try to 'make clean build' before running the update script.

**Comment by dustymabe** [comment]
@kargakis yeah, but what is the number in the messages I see in the git log? is that git short commit of the upstream place it was fixed?

**Comment by kargakis** [comment]
> We generate that doc from this file here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go#L55 . Can you update this file, then build it, then run hack/update-generated-docs.sh?

Actually we have our own examples. @dustymabe you need to edit this [example](https://github.com/openshift/origin/blob/ed29520da014c76ba83072b9c3609bce01aa0565/pkg/cmd/cli/cmd/wrappers.go#L313). Also, while here can you verify that the commented examples work and uncomment them?

**Comment by kargakis** [comment]
Will submit in https://github.com/openshift/origin/pull/6401 to get this in. @dustymabe try working on separate branches and not the master.

**Comment by kargakis** [comment]
This PR has been superceded by #6401, it can close now.

**Comment by dustymabe** [comment]
Closing. superceded by #6401

**Pull request closed without merging**
