### PR TITLE
Remove flag hard-coding

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@pweil- @smarterclayton ptal

**Comment by pweil-** [comment]
LGTM, In my latest PR the docker command has the `loglevel` flag set by default too so folks can get better info out of the router at runtime.

**Comment by pweil-** [comment]
[merge]

**Comment by pmorie** [comment]
@ironcladlou @smarterclayton help a brother out and tag this thing.  I'm annoyed that I left it in in the first place.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
