### PR TITLE
Add --scheduled to import-image

### LINKED ISSUE #15644: Support for --scheduled flag on oc import-image
When working with a remote Docker registry, there are various ways to import images into OpenShift. One of them is `oc tag`, which can be used to create an `ImageStreamTag` that points to a remote image. Providing the `--scheduled` flag to `oc tag` tells OpenShift to periodically ensure that the ImageStreamTag is up to date. For example:
```
oc tag registry.example.com/myimage:mytag myproject/myimage:mytag --scheduled
```
Running this command will ensure that the `myimage:mytag` ImageStreamTag in `myproject` is kept up to date. It does this by setting `scheduled` to `true` [in the `TagImportPolicy`][TagImportPolicy].

Another way to import images into OpenShift is with `oc import-image`. Rather than directly creating an `ImageStreamTag` that happens to refer to a remote image, this command explicitly tells OpenShift to import a remote image and create `ImageStreamTag`s as necessary. By default, `oc import-image` will attempt to import a single tag (`latest` if unspecified), but, if given the `--all` flag, it will import all the tags available for that image. If there are a lot of tags on an image that you want to track, this is much nicer than running `oc tag` for each one. Unfortunately, `oc import-image` has no `--scheduled` flag, meaning there is no simple way to get OpenShift to keep them all up to date. It would be nice if this functionality were supported.

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
```

##### Additional Information
The good news is that this is supported by the API used by `oc import-image`. This command calls [`/oapi/v1/namespaces/{namespace}/imagestreamimports`][import-image API], which takes an `ImageStreamImport` object, which, after a few layers, contains a `TagImportPolicy` object. To elaborate:
```
oc import-image my-project/my-image --from=registry.example.com/my-image --all
```
This command `POST`s an `ImageStreamImport` object that looks like this:

<details>

<summary><code>ImageStreamImport</code> document produced by <code>oc import-image</code></summary>

```json
{
  "kind": "ImageStreamImport",
  "apiVersion": "v1",
  "metadata": {
    "name": "my-image",
    "namespace": "my-project",
    "resourceVersion": "15839355",
    "creationTimestamp": null
  },
  "spec": {
    "import": true,
    "repository": {
      "from": {
        "kind": "DockerImage",
        "name": "registry.example.com/my-image"
      },
      "importPolicy": {},
      "referencePolicy": {
        "type": ""
      }
    }
  },
  "status": {}
}
```

</details> 

As an aside, the `--from` flag can be omitted from the call to `oc import-image` if the `ImageStream` already exists and has a value in `spec.dockerImageRepository`.

Adding a `scheduled` property with value `true` to the `importPolicy` field causes everything to work as expected. For reference, that means a document like this:

<details>
<summary><code>ImageStreamImport</code> document that schedules tag update checks</summary>

```json
{
  "kind": "ImageStreamImport",
  "apiVersion": "v1",
  "metadata": {
    "name": "my-image",
    "namespace": "my-project",
    "resourceVersion": "15839355",
    "creationTimestamp": null
  },
  "spec": {
    "import": true,
    "repository": {
      "from": {
        "kind": "DockerImage",
        "name": "registry.example.com/my-image"
      },
      "importPolicy": {
        "scheduled": true
      },
      "referencePolicy": {
        "type": ""
      }
    }
  },
  "status": {}
}
```

</details>

[TagImportPolicy]: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-tagimportpolicy
[import-image API]: https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-an-imagestreamimport-2

### PR DESCRIPTION
**Pull request by elyscape**
Fixes #15644.

### CODE REVIEW

**Comment by juanvallejo** [comment]
@elyscape lgtm, mind adding a small test in importimage_test.go?

**Comment by elyscape** [comment]
@juanvallejo Tests added.

**Comment by miminar** [comment]
/assign @juanvallejo 
For the approval.

**Comment by miminar** [comment]
```
./pkg/oc/cli/cmd/importimage.go
[WARNING] !!! gofmt needs to be run on the following files: 
[FATAL] Try running 'gofmt -s -d [path]'
[FATAL] Or autocorrect with 'hack/verify-gofmt.sh | xargs -n 1 gofmt -s -w'
```
Just this and you're good to go. Please excuse the line order.

**Comment by elyscape** [comment]
@miminar Fixed.

**Comment by miminar** [comment]
/assign @fabianofranz
as `pkg/oc` approver.

**Comment by elyscape** [comment]
This failure appears to have been a result of #15715.

**Pull request merged**
