### PR TITLE
Start using Go 1.9 to build

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton is this targeting 3.8 or 3.9?

**Comment by smarterclayton** [comment]
both

**Comment by smarterclayton** [comment]
@liggitt i assume you have a fix for https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17293/test_pull_request_origin_unit/5616/#githubcomopenshiftoriginvendork8siokubernetespkgmaster-testtypetags in rebase?

**Comment by liggitt** [comment]
Upstream isn't building with 1.9 until 1,9

**Comment by smarterclayton** [comment]
I'd like to go to 1.9 ASAP - golang 1.8 will be EOL before we ship 3.8, and I don't want 3.8 binaries built with a different go version

**Comment by stevekuznetsov** [comment]
@smarterclayton looks like a real failure

```
import_known_versions_test.go:121: Unexpected type uint in schema.GroupVersionKind{Group:"batch", Version:"__internal", Kind:"Job"}
import_known_versions_test.go:123: batch.Job:
import_known_versions_test.go:123:   batch.JobSpec:
import_known_versions_test.go:123:     api.PodTemplateSpec:
import_known_versions_test.go:123:       api.PodSpec:
import_known_versions_test.go:123:         []api.Volume:
import_known_versions_test.go:123:           api.Volume:
import_known_versions_test.go:123:             api.VolumeSource:
import_known_versions_test.go:123:               *api.EmptyDirVolumeSource:
import_known_versions_test.go:123:                 api.EmptyDirVolumeSource:
import_known_versions_test.go:123:                   *resource.Quantity:
import_known_versions_test.go:123:                     resource.Quantity:
import_known_versions_test.go:123:                       resource.infDecAmount:
import_known_versions_test.go:123:                         *inf.Dec:
import_known_versions_test.go:123:                           inf.Dec:
import_known_versions_test.go:123:                             big.Int:
import_known_versions_test.go:123:                               big.nat:
import_known_versions_test.go:123:                                 big.Word:
```

/lgtm cancel

so the re-tester bot stops trying on this one

**Comment by liggitt** [comment]
needs https://github.com/kubernetes/kubernetes/commit/06205696ae3d4629fa17194a3d967fae6e632e29#diff-450943002fd8b9d889ac68d523aa5a08

**Pull request merged**
