### PR TITLE
Correct secret type in oc secrets new-{basic,ssh}auth

### LINKED ISSUE #10804: Creating basicauth or sshauth secret will create secret with type Opaque
Creating _Secret_ using `oc secrets new-basicauth` or `oc secrets new-sshauth` will create secret with type `Opaque`. 
`oc secrets new-basicauth` should create secret of type `kubernetes.io/basic-auth`
`oc secrets new-sshauth` should create secret of type `kubernetes.io/ssh-auth`

cc'ing @csrwng

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #10804

### CODE REVIEW

**Comment by csrwng** [comment]
LGTM
[test]

**Comment by jim-minter** [comment]
fixed up test script, [test]

**Comment by jim-minter** [comment]
flake #8571 
[test]

**Comment by jim-minter** [comment]
flake #8571 
[test]

**Comment by jim-minter** [comment]
flake #8571 
[test]

**Comment by jim-minter** [comment]
flake #10773
flake #11240

**Comment by csrwng** [comment]
[merge]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/11240
[merge]

**Pull request merged**
