### PR TITLE
Remove curl usage from test cmd to prevent cert flakes

### PR DESCRIPTION
**Pull request by enj**
curl + nssdb have started to flake with

curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

after 266aa46bd0a5728d3a8831a6321cd1c3fd8b2360 was merged.  This change replaces curl with wget until we can figure out how to correctly handle these cert issues.

Signed-off-by: Monis Khan <mkhan@redhat.com>

/kind bug
/assign @smarterclayton @stevekuznetsov 

@openshift/sig-security 

@mrogers950 can you figure out a better solution for this?

### CODE REVIEW

**Comment by enj** [comment]
See https://openshift-gce-devel.appspot.com//build/origin-ci-test/pr-logs/pull/18634/test_pull_request_origin_cmd/10416/ and https://openshift-gce-devel.appspot.com//build/origin-ci-test/pr-logs/pull/18634/test_pull_request_origin_cmd/10416/ as examples.

**Comment by liggitt** [comment]
Seems like reverting that PR would be a better response.

**Comment by liggitt** [comment]
Seems like reverting that PR would be a better response.

**Comment by enj** [comment]
Superseded by #18713

**Pull request closed without merging**
