### PR TITLE
Disable a local storage serial test

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Great, 

```
Replaced Dockerfile FROM image pipeline:src

Pulling image docker-registry.default.svc:5000/ci-op-3gjsmkl5/pipeline@sha256:0d365947e43a20ec4cc49c4d9e09df725312bac8c3ee74c3278dcd9aff3c8c18 ...
error: build error: no such image
```

I thought we fixed this in 3.11?  if so, I may need to pull a new image to all the nodes @bparees

**Comment by bparees** [comment]
> I thought we fixed this in 3.11? if so, I may need to pull a new image to all the nodes @bparees

unfortunately not.  The code was fixed in imagebuilder but the origin code itself did not get fixed:

https://github.com/openshift/origin/pull/20941

at this point that PR should be recreated against 3.11 since for 4.0 all this stuff is changing anyway (and that code is moving out of origin).

**Comment by bparees** [comment]
the bug you want to watch is https://bugzilla.redhat.com/show_bug.cgi?id=1626228

**Comment by smarterclayton** [comment]
@bparees is this test known flaky or known broken?  Let’s disable if so.

On Oct 4, 2018, at 8:03 AM, OpenShift CI Robot <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton>: The following test
*failed*, say /retest to rerun them all:
Test name Commit Details Rerun command
ci/openshift-jenkins/extended_builds 6b3e8b5
<https://github.com/openshift/origin/commit/6b3e8b518fd0e3768ac8fb3d2835eea09a25bf36>
link
<https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21165/test_pull_request_origin_extended_builds/2674/>
/test
extended_builds

Full PR test history <https://openshift-gce-devel.appspot.com/pr/21165>. Your
PR dashboard <https://openshift-gce-devel.appspot.com/pr/smarterclayton>.
Please help us cut down on flakes by linking to
<https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests>
an open issue
<https://github.com/openshift/origin/issues?q=is:issue+is:open> when you
hit one in your PR.

Instructions for interacting with me using PR comments are available here
<https://git.k8s.io/community/contributors/guide/pull-requests.md>. If you
have questions or suggestions related to my behavior, please file an issue
against the kubernetes/test-infra
<https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
repository. I understand the commands that are listed here
<https://go.k8s.io/bot-commands>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/21165#issuecomment-426992917>,
or mute
the thread

**Comment by bparees** [comment]
> @bparees is this test known flaky or known broken? Let’s disable if so.

i was just looking into it this morning.  we're going to revert the change that appears to have broken it and continue investigating.  

/cc @gabemontero

**Comment by bparees** [comment]
https://github.com/openshift/jenkins-client-plugin/pull/187 should fix it.
/retest

**Pull request merged**
