### PR TITLE
remove unneeded vendor tests

### PR DESCRIPTION
**Pull request by PI-Victor**
fixes https://github.com/openshift/origin/issues/11695

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by PI-Victor** [comment]
`The following commits contain Godeps changes but aren't declared as UPSTREAM:`
interesting, how do i mark them as upstream? do they physically need to be upstream?

**Comment by smarterclayton** [comment]
Oh, you need to change your commit message to be:

bump(*): remove unused _test.go files

**Comment by PI-Victor** [comment]
it would be better not to merge this right now, but wait for 1.4 to close.
https://github.com/openshift/origin/issues/11695#issuecomment-257811720
i added the 1.5 milestone to it

**Comment by bparees** [comment]
@PI-Victor can you rebase this?

**Comment by PI-Victor** [comment]
@bparees done.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by PI-Victor** [comment]
flake https://github.com/openshift/origin/issues/11004 
@bparees can you try again?

**Pull request merged**
