### PR TITLE
OCPBUGS-7833: Rework no optional capabilities rules

### PR DESCRIPTION
**Pull request by jsafrane**
Rework `[Skipped:NoOptionalCapabilities]` rules:

* Skip all tests that require `Feature:VolumeSnapshotDataSource`, it needs CSISnapshot capability.
* Skip all in-tree AWS tests, they require Storage capability.
* Don't skip tests that are skipped elsewhere.
* Enable all other tests, they should pass.

### CODE REVIEW

**Comment by jsafrane** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-no-capabilities

**Comment by jsafrane** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-ovn-no-capabilities

**Comment by jsafrane** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-ovn-no-capabilities

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
