### PR TITLE
Bug 1846431: UPSTREAM: 90377: Fix exclusive CPU allocations being deleted at container restart

### PR DESCRIPTION
**Pull request by cynepco3hahue**
ref: kubernetes/kubernetes#90377

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@vpickard Can you please provide the relevant Bugzilla?

**Comment by cynepco3hahue** [comment]
@sjenning @rphillips The PR is ready for review, can you please take a look?

**Comment by bparees** [comment]
i believe @sjenning is leading the node team while @rphillips is out.

/assign @sjenning 
/unassign

**Comment by cynepco3hahue** [comment]
The fix will be available for free after the rebase on top of 1.19.

**Pull request closed without merging**
