### PR TITLE
Bug 1986003: bump k8s.io to 1.22.0-rc.0

### PR DESCRIPTION
**Pull request by soltysh**
@hexfusion for etcd changes
@jmencak and @sjug for  `test/extended/cluster`, specifically `Get rid of --viper-config which was removed in k8s` commit

### CODE REVIEW

**Comment by jsafrane** [comment]
Lot of storage tests fail pulling images, e.g. there are missing in [a hostpath test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26366/pull-ci-openshift-origin-master-e2e-gcp/1422251017608630272/artifacts/e2e-gcp/openshift-e2e-test/artifacts/junit/_sig-storage_CSI_Volumes/_Driver_csi-hostpath_/_Testpattern_CSI_Ephemeral-volume_default_fs_ephemeral/should_create_read-only_inline_ephemeral_volume_Suite_openshift_conformance_parallel_Suite_k8s_/pod-event.log):

quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-hostpathplugin-v1-7-1-stEGUP3RdCxjBvZm
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-node-driver-registrar-v2-2-0-FC5zbVTQJjyKeWTN
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-livenessprobe-v2-3-0-Tj890_7cIpcf5FNv
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-attacher-v3-2-1-0hG8IcuRv5znfyad
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-provisioner-v2-2-1-6ayZekCswACr2PZ
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-resizer-v1-2-0-faYe_5IxC3bYJ5aV
quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-snapshotter-v4-1-1-1mL85KiLHcB-HQCq

**Comment by jsafrane** [comment]
Failures both e2e-gcp-csi and e2e-aws-csi (and other CSI jobs) are known bugs, we need updated CSI drivers.
```
multiVolume [Slow] should concurrently access the volume and restored snapshot from pods on the same node
```

https://bugzilla.redhat.com/show_bug.cgi?id=1988371
https://bugzilla.redhat.com/show_bug.cgi?id=1988373

These jobs are not mandatory, we probably don't need to disable these tests.

**Comment by soltysh** [comment]
> Lot of storage tests fail pulling images, e.g. [a hostpath test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26366/pull-ci-openshift-origin-master-e2e-gcp/1422251017608630272/artifacts/e2e-gcp/openshift-e2e-test/artifacts/junit/_sig-storage_CSI_Volumes/_Driver_csi-hostpath_/_Testpattern_CSI_Ephemeral-volume_default_fs_ephemeral/should_create_read-only_inline_ephemeral_volume_Suite_openshift_conformance_parallel_Suite_k8s_/pod-event.log) needs:

@jsafrane updated those just minutes ago.

**Comment by jsafrane** [comment]
Sorry, I found these two missing images:
```
Back-off pulling image "quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-attacher-v3-2-0-XMbbzU2ED4Dglu2H"
Back-off pulling image "quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-snapshotter-v4-0-0-1JRsupiNS_D6T7c_"
```

**Comment by soltysh** [comment]
> Sorry, I found these two missing images:
> 
> ```
> Back-off pulling image "quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-attacher-v3-2-0-XMbbzU2ED4Dglu2H"
> Back-off pulling image "quay.io/openshift/community-e2e-images:e2e-k8s-gcr-io-sig-storage-csi-snapshotter-v4-0-0-1JRsupiNS_D6T7c_"
> ```

Should be fine now.

**Comment by jsafrane** [comment]
Looks good from storage perspective.

**Comment by soltysh** [comment]
/override ci/prow/e2e-agnostic-cmd

These are not required and I'll continue debugging test-cmd separately.

**Comment by soltysh** [comment]
Based on https://github.com/openshift/origin/pull/26366#issuecomment-896622967
/override ci/prow/e2e-aws-csi
/override ci/prow-e2e-gcp-csi

**Comment by soltysh** [comment]
Based on #26366 (comment)
/override ci/prow/e2e-aws-csi
/override ci/prow/e2e-gcp-csi

**Comment by soltysh** [comment]
Based on #26366 (comment)
/override ci/prow/e2e-aws-csi
/override ci/prow/e2e-gcp-csi
These are optional:
/override ci/prow/e2e-agnostic-cmd 

/test e2e-aws-single-node

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-single-node
it's optional

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

Thank you for the bump @soltysh 

cc @romfreiman for SNO changes.

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp-builds 
it's optional

/test e2e-gcp-upgrade
/test e2e-gcp

**Pull request merged**
