### PR TITLE
increase watch timeout for build controller test

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/9503

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by deads2k** [comment]
I don't expect that this will fix the problem since its failing on: 
`I0623 12:38:12.079408   28455 controller.go:280] No build found for pod integration/mock-buildios2q-build`.  Looks like a latent cache problem to me

**Comment by bparees** [comment]
@deads2k you sure that message is correlated to this test failure?  we have a test in that same file that deletes a build object while leaving the pod around, and it ran (successfully) before the failure: TestBuildDeleteController

**Comment by deads2k** [comment]
> @deads2k you sure that message is correlated to this test failure?

Yes, we start a new server for each test.

**Pull request merged**
