### PR TITLE
rebase to kube 1.14

### PR DESCRIPTION
**Pull request by deads2k**
Builds locally, gathering CI data.

 - [x] [images](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-images/4314) 
 - [x] [verify](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-verify/4121)
 - [x] [unit](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-unit/4685) - flake.  Seen one
   - [ ] `vendor/k8s.io/kubernetes/pkg/controller/podautoscaler TestLegacyScaleDownRCImmediately`
 - [x] [integration](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-integration/4605)
 - [x] [cmd](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-cmd/3478) 
 - [ ] aws - 5/731 remaining
 - [x] serial - previous scheduling (will skip)
 - [ ] builds - 1 failure.  new kubelet filename too long.  I recommend skipping.
 - [x] [image-ecosystem](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-e2e-aws-image-ecosystem/234) 
 - [x] [image-registry](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-e2e-aws-image-registry/368) 

[full test history](https://openshift-gce-devel.appspot.com/pr/22478)

### CODE REVIEW

**Comment by deads2k** [comment]
/test e2e-aws-serial

no such image is a known flake

**Comment by deads2k** [comment]
```
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/podautoscaler TestLegacyScaleDownRCImmediately 15s
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-unit/4682

/retest

**Comment by mfojtik** [comment]
```
Failing tests:

[Feature:AnnotationTrigger] Annotation trigger reconciles after the image is overwritten [Suite:openshift/conformance/parallel]
[sig-auth] [Feature:DynamicAudit] should dynamically audit API calls [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network] Services should be rejected when no endpoints exist [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-network] Services should implement service.kubernetes.io/service-proxy-name [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Dynamic PV (default fs)] provisioning should access volume from different nodes [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] provisioning should access volume from different nodes [Suite:openshift/conformance/parallel] [Suite:k8s]
```

/retest

**Comment by jsafrane** [comment]
@deads2k `CSI Volumes CSI Topology test using GCE PD driver *` will be fixed by https://github.com/kubernetes/kubernetes/pull/76191 when it gets merged, you can pick it to your branch

**Comment by wongma7** [comment]
I will work on a fix upstream for `[Testpattern: Dynamic PV (default fs)] provisioning should access volume from different nodes`, issue is that the test assumes kubernetes.io/hostname label matches node name but it doesn't for us

**Comment by deads2k** [comment]
/retest

no such image

**Comment by deads2k** [comment]
/retest

no such image

**Comment by deads2k** [comment]
could not wait for RPM repo server to deploy

/retest

**Comment by deads2k** [comment]
aws-flake that we'll get in 1.13 too: `CustomResourcePublishOpenAPI` seen in the 1.13 pick
`openshift-tests [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]`

/retest

**Comment by deads2k** [comment]
aws-builds failed on something new:
```
  Warning  FailedCreatePodSandBox  25s (x48 over 10m)  kubelet, ip-10-0-155-216.ec2.internal  Failed create pod sandbox: mkdir /var/log/pods/e2e-test-long-names-bcqz5_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890a-1-build_6f7fa029-57b7-11e9-92a3-123fac2a4770: file name too long
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22478/pull-ci-openshift-origin-master-e2e-aws-builds/1246

@sjenning

**Comment by wongma7** [comment]
fix for `provisioning should access volume from different node` has merged: https://github.com/kubernetes/kubernetes/pull/76193 feel free to pick it!

**Comment by deads2k** [comment]
CustomResourcePublishOpenAPI again, but now we have a conflict.  I'm going to go look at something else.  Maybe making this easier when it comes to it.

**Pull request closed without merging**
