### PR TITLE
Etcdhelper improvements

### LINKED ISSUE #14278: etcdhelper: add a README file with usage
As an OpenShift developer I'd like to have ability to read about `etcdhelper` utility in human readable format. At this time it looks like a private tool.

Right now, to build it, I did:
```console
$ cd tools/etcdhelper
$ go build
```

When I'm executing it with `-h` option it shows me only flags and not the options (where is `ls`, `get` and `dump`?):
```console
$ ./etcdhelper -h
Usage of ./etcdhelper:
  -alsologtostderr
    	log to standard error as well as files
  -cacert string
    	Server TLS CA certificate.
```

Also I couldn't run it because of error:
```console
$ ./etcdhelper dump
ERROR: unable to connect to etcd: grpc: timed out when dialing
```

CC @soltysh @enj

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #14278.

/assign @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
@soltysh you want to make a test that forces this to stay in sync? I think your discovery about storage version is still valid too.

**Comment by soltysh** [comment]
> @soltysh you want to make a test that forces this to stay in sync? I think your discovery about storage version is still valid too.

Hehe, I think I 'broke you' you desire tests more than I do now :stuck_out_tongue_winking_eye:

**Comment by soltysh** [comment]
@deads2k I've added the tests and created https://github.com/openshift/origin/issues/18874 to track the switch to groupified storage version for openshift resources. 

/retest

**Pull request merged**
