### PR TITLE
log event for invalid output error

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/3235

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k ptal.

**Comment by bparees** [comment]
Note that the other problem, that handleError was being called on every retry, was already fixed separately:
https://github.com/openshift/origin/blob/master/pkg/build/controller/factory/factory.go#L36-L45

**Comment by bparees** [comment]
```
$ oc describe build ruby-sample-build-1
Name:			ruby-sample-build-1
Created:		9 minutes ago
Labels:			buildconfig=ruby-sample-build,name=ruby-sample-build,template=application-template-stibuild
Build Config:		ruby-sample-build
Status:			New
Duration:		waiting for 9m16s
Build Pod:		ruby-sample-build-1-build
Strategy:		Source
Image Reference:	DockerImage openshift/ruby-20-centos7:latest
Incremental Build:	yes
Source Type:		Git
URL:			git://github.com/openshift/ruby-hello-world.git
Output to:		origin-ruby-sample:latest
Output Spec:		<none>
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason		Message
  Fri, 26 Jun 2015 17:34:51 -0400	Fri, 26 Jun 2015 17:44:06 -0400	567	{build-controller }			invalidOutput	Error starting build: the ImageStream default/origin-ruby-sample cannot be used as the output for Build default/ruby-sample-build-1 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
```

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM

**Comment by deads2k** [comment]
lgtm [merge]

**Pull request merged**
