### PR TITLE
fix for bz1465304 - use regular escaping of the resource

### PR DESCRIPTION
**Pull request by rajatchopra**
Fix for bz: https://bugzilla.redhat.com/show_bug.cgi?id=1465304

@lihongan Review please. Thanks.

/cc @openshift/networking

### CODE REVIEW

**Comment by pravisankar** [comment]
@rajatchopra I do not see anyone using 'iControlUriVserverId()', may be we should delete this method if we don't need it anymore?

**Comment by rajatchopra** [comment]
@pravisankar Point taken. Removed the unused function. Thanks.

**Comment by pravisankar** [comment]
[merge]

**Comment by rajatchopra** [comment]
[test] flake #13271

**Comment by eparis** [comment]
[test]

**Comment by knobunc** [comment]
[test] Last flaked on https://github.com/openshift/origin/issues/14043

**Pull request merged**
