### PR TITLE
when loop until last, no need conitue loop

### PR DESCRIPTION
**Pull request by weizhanxu**

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by smarterclayton** [comment]
Is this fixing a bug?  I'm cautious about changing code like this without a strong reason.

**Comment by weizhanxu** [comment]
yes，this is not a bug，just optimize. @smarterclayton

**Comment by weizhanxu** [comment]
CI  failed not because my modify code. How can  run it again. I think this optimize  code also necessary, it makes the function logic  more clear. @smarterclayton

**Comment by php-coder** [comment]
@smarterclayton If we won't merge it, I'm suggesting to close it then. Otherwise let's merge it while its not outdated.

**Comment by smarterclayton** [comment]
[test]

Sorry for the long delay on this, agree it's better.

**Comment by smarterclayton** [comment]
Actually, I reread what the code is.  The continue is intentional - we actually just want to go the the next bucket but "last" is special.  So this code is correct as is.

**Pull request closed without merging**
