### PR TITLE
Revert "Revert "Implemented a single-directive library import for Origin Bash scripts""

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Reverts openshift/origin#8850

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[testonlyextended][extended:networking]

**Comment by stevekuznetsov** [comment]
@smarterclayton I don't think my changes caused the networking failure... this revert of the revert is working fine and I've not made any changes to the original PR.

**Comment by smarterclayton** [comment]
See
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/190/console

On May 11, 2016, at 7:14 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> I don't think my
changes caused the networking failure... this revert of the revert is
working fine and I've not made any changes to the original PR.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/8852#issuecomment-218617547>

**Comment by stevekuznetsov** [comment]
Closing for #8853

**Pull request closed without merging**
