### PR TITLE
Configure vagrant proxies

### PR DESCRIPTION
**Pull request by santospm**
Proxy configuration is essential within a corporate environment.  Vagrant will check the user has the proxy variables configured (http(s)_proxy, no_proxy) and extend their values to vagrant [if the proxyconf is installed)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Hi @santospm, can you split out the CPU part from the proxy part?  We set the CPU/memory requirements as a min reasonable amount for OpenShift, and you can always configure it in your `.vagrant-openshift.json` file if you want it to be different.

**Comment by santospm** [comment]
Done! I over looked the fact that I can override them with env variables.

**Comment by smarterclayton** [comment]
Looks good - can you squash them down into one commit?

**Comment by danmcp** [comment]
@santospm Looks like this still needs a squash

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Pull request closed without merging**
