### PR TITLE
Workaround: perform a Docker pull before running a Docker build on an image with SHA digest

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by smarterclayton** [comment]
?

**Comment by csrwng** [comment]
So there is currently a Docker bug (in 1.7) that fails building Dockerfile's with a FROM ref to a private registry that requires auth. It has been fixed in 1.8.

**Comment by csrwng** [comment]
@bparees fyi

**Comment by smarterclayton** [comment]
And this fixes it how?

On Aug 21, 2015, at 5:38 PM, Cesar Wong <notifications@github.com> wrote:

So there is currently a Docker bug (in 1.7) that fails building
Dockerfile's with a FROM ref to a private registry that requires auth. It
has been fixed in 1.8.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4323#issuecomment-133569863>.

**Comment by smarterclayton** [comment]
Why would this just not be something we backport to the docker packages?

**Comment by bparees** [comment]
Impatience, mostly.

Ben Parees | OpenShift

**Comment by smarterclayton** [comment]
Won't every rhel user hit this?

On Aug 21, 2015, at 6:33 PM, Ben Parees <notifications@github.com> wrote:

Impatience, mostly.

Ben Parees | OpenShift
On Aug 21, 2015 5:58 PM, "Clayton Coleman" <notifications@github.com> wrote:

> Why would this just not be something we backport to the docker packages?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4323#issuecomment-133575585>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4323#issuecomment-133580363>.

**Comment by bparees** [comment]
Every RHEL user doing a docker build via a v2 digest FROM where the image
does not exist locally, maybe?

Ben Parees | OpenShift

**Comment by smarterclayton** [comment]
This has "we would backport this fix" written all over it.  We should open
a bug against rhel and make sure Dan W knows about it.

On Aug 21, 2015, at 9:05 PM, Ben Parees <notifications@github.com> wrote:

Every RHEL user doing a docker build via a v2 digest FROM where the image
does not exist locally, maybe?

Ben Parees | OpenShift
On Aug 21, 2015 19:57, "Clayton Coleman" <notifications@github.com> wrote:

> Won't every rhel user hit this?
>
> On Aug 21, 2015, at 6:33 PM, Ben Parees <notifications@github.com> wrote:
>
> Impatience, mostly.
>
> Ben Parees | OpenShift
> On Aug 21, 2015 5:58 PM, "Clayton Coleman" <notifications@github.com>
> wrote:
>
> > Why would this just not be something we backport to the docker packages?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openshift/origin/pull/4323#issuecomment-133575585>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4323#issuecomment-133580363>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4323#issuecomment-133592580>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4323#issuecomment-133621350>.

**Comment by bparees** [comment]
That was my instinct but I succumbed to trying to get it fixed more
urgently. Sorry Cesar :(

Ben Parees | OpenShift

**Comment by ncdc** [comment]
Do you have a link to the Docker issue and/or PR that fixes it?

**Comment by csrwng** [comment]
https://github.com/docker/docker/commit/02c7bbefb8841e5e86a4b9d467defa668e3ea613

**Comment by csrwng** [comment]
@ncdc I initially thought that auth was broken only for references that contained a sha digest, but that's not the case... as you can see from the commit it's mainly the format of the auth map.

**Pull request closed without merging**
