### PR TITLE
Reorganized master code

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k @liggitt  PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov promise that this is just a straight shuffle (no tweaks) and the re-org lgtm.

**Comment by stevekuznetsov** [comment]
@deads2k So they're not [completely identical](https://www.diffchecker.com/s4y5r18n) but the changes are:
* in the original `master.go`, `kapi`and `api` were the same import
* someone called a service `svc` and I enjoy vowels

**Comment by stevekuznetsov** [comment]
[test]

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
