### PR TITLE
Router: Pin to haproxy-1.5.10, use CPU=generic

### PR DESCRIPTION
**Pull request by sdodson**
So we don't have a moving target

### CODE REVIEW

**Comment by sdodson** [comment]
@pweil- for your consideration We may want to look at using the packages shipped in centos/rhel unless you've already found them to be too old. They're 1.5.4+backports.

**Comment by pweil-** [comment]
LGTM, ran through use cases at https://github.com/pweil-/hello-nginx-docker successfully.  @sdodson - travis ci has been flaky, you may need to amend the commit to bump tests again.  Tagging for int test.

**Comment by pweil-** [comment]
[test]

**Comment by sdodson** [comment]
@pweil- Travis just seems flaky, can you merge this? I don't have the privileges to do so.

**Comment by pweil-** [comment]
@pmorie @smarterclayton hear our call, might mergers!  The travis-ci gods have frowned upon us due to our lack of swagger (`2015/02/02 14:12:27 [restful/swagger] Swagger(File)Path is empty ; no UI is served.  curl: (7) couldn't connect to host`).  I don't have permissions in travis to manually restart these tests.

This fixes issues we had with compilation of arch specific instructions and pins us to a known working release of HAProxy.  Tested by @thoraxe and myself on Friday.

**Comment by smarterclayton** [comment]
That failure is a transient.  Check under your seats... everyone gets a brand new [merge]!

**Comment by smarterclayton** [comment]
LGTM

**Comment by pweil-** [comment]
:tada: :balloon:

**Comment by smarterclayton** [comment]
re[merge]

**Pull request merged**
