### PR TITLE
Bump spf13/cobra and spf13/pflag

### PR DESCRIPTION
**Pull request by fabianofranz**
To get in sync with https://github.com/kubernetes/kubernetes/pull/17779

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by liggitt** [comment]
does this match upstream or do we need corresponding PRs there?

**Comment by fabianofranz** [comment]
@liggitt needs upstream.

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
Upstream PR https://github.com/kubernetes/kubernetes/pull/17779

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
