### PR TITLE
Remove DeprecatedDownwardAPIVolumeSource from protobuf

### PR DESCRIPTION
**Pull request by ncdc**
@smarterclayton @liggitt @deads2k @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
So if I understand the effect correctly, we'll have a client and server level that improperly serializes `VolumeSources` for protobuf.

**Comment by ncdc** [comment]
There was a bug in the generator that accidentally allowed this field to go into VolumeSource when it never should have. Since we haven't switched protobuf on yet, while the risk isn't 100% that someone will run into an issue, I'm optimistic it won't actually hit anyone.

**Comment by pweil-** [comment]
@ncdc  is this a dupe of https://github.com/openshift/origin/pull/11997/commits? Just noticed 3 PRs with the same name when triaging and these had the exact same change counts

* this PR
* https://github.com/openshift/origin/pull/11999
* https://github.com/openshift/origin/pull/11997

**Comment by pweil-** [comment]
Disregard, I see they are targeting different versions.  Thanks!

**Comment by liggitt** [comment]
@pweil- different branches

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
ok to merge?

**Comment by ncdc** [comment]
Flake #9642 [test]

**Comment by ncdc** [comment]
Flake #11557 [test]

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
I think this was #11016 [merge]

**Comment by ncdc** [comment]
#10988 [merge]

**Pull request merged**
