### PR TITLE
Remove v1beta1

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by ncdc** [comment]
```
../../../local/go/src/github.com/openshift/origin/test/integration/buildclient_test.go:295: bcClient declared and not used
```

**Comment by smarterclayton** [comment]
@ncdc @bparees please review the last commit

**Comment by smarterclayton** [comment]
Integration tests did not catch that builds didn't work when they had a build.output.to of an ImageStream, which means we probably need to improve those tests

**Comment by ncdc** [comment]
Testing locally w/my image api cleanup branch

**Comment by smarterclayton** [comment]
E2e passes but I think there's an integration failure, looking at that more.

----- Original Message -----

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
I went with a much simpler change - this was actually build output losing tag in conversion, and not resetting To

**Comment by ncdc** [comment]
`fatal: Unable to create '/data/src/github.com/openshift/origin-bare/refs/heads/master.lock': File exists.
`

lovely

[test]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
