### PR TITLE
Update rules for upstream deployment rollbacks

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
merge?

**Comment by mfojtik** [comment]
Approved for 1.4 [merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10228, https://github.com/openshift/origin/issues/11661, and https://github.com/openshift/origin/issues/11662

**Comment by mfojtik** [comment]
[merge]

**Comment by kargakis** [comment]
#11661 [test]

**Pull request merged**
