### PR TITLE
cli: fix bulk generator to prefer legacy group

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/13447

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by csrwng** [comment]
Tested on Mac/RHEL - fixes cluster up for me. Tested new-app, new-build, import-image and they worked as well

**Comment by mfojtik** [comment]
@smarterclayton found 3 more places where we need to add this.

**Comment by mfojtik** [comment]
add fix for create route command that also used InfoForObject.

**Comment by smarterclayton** [comment]
Add a test case to verify this doesn't break again?

**Comment by mfojtik** [comment]
@smarterclayton test updated to guard that the preferred gvk is not moved.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
Flake on deployment timeout [merge]

**Pull request merged**
