### PR TITLE
Support private, non-https registries on image import

### PR DESCRIPTION
**Pull request by smarterclayton**
@ncdc review

### CODE REVIEW

**Comment by ncdc** [comment]
Is this correct - `allowInsecure` has 2 meanings that go together:

1. Don't verify the registry's certificate
1. If the registry isn't talking https, try falling back to http

**Comment by ncdc** [comment]
LGTM

**Comment by ncdc** [comment]
If you want me to test this manually, I can do it later (probably tomorrow). Otherwise, if you're confident it works (and I assume it did from your demo today), feel free to merge.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
