### PR TITLE
UBI images

### PR DESCRIPTION
**Pull request by smarterclayton**
Reduce the size of origin images by moving to UBI based images.  Switch to multistage builds in place.  Shrink SDN.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@adammhaile @sosiouxme an example of what new origin/ocp images would look like (same for both platforms).  Lots more work here to do, but would probably have this merged in parallel with testing so we can cut over slowly.

**Comment by adammhaile** [comment]
@smarterclayton ack, thanks. Looks fine to me. The only concern is that if any of the base images change (ose-base -> cli is common) we need to know about it before the changes are committed.

**Comment by smarterclayton** [comment]
So the plan here is going to be two phases:

1. add the new `.rhel` images, update the origin images but not change base
2. update CI, smoke test for a few days
3. update ocp-build-data to point to `.rhel`
4. update the spec files to remove building the old packages (this I need help with)
5. remove the old RHEL images

**Pull request merged**
