### PR TITLE
UPSTREAM: 25907: Fix detection of docker cgroup on RHEL

### PR DESCRIPTION
**Pull request by ncdc**
@smarterclayton @derekwaynecarr

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by smarterclayton** [comment]
just to be clear, is docker-current a script or the binary?  Aren't existing deployments broken without this fix (3.1, 3.2)?

**Comment by ncdc** [comment]
docker-current is the name of the binary. My backport to 3.2.0.x has merged. My backport to 3.2.1 is still open. IIRC this code to detect the docker cgroup was added in 3.2 and it's not in 3.1. @derekwaynecarr is that correct?

**Comment by smarterclayton** [comment]
So OSE would only work with docker-current?

On May 27, 2016, at 10:52 AM, Andy Goldstein <notifications@github.com>
wrote:

docker-current is the name of the binary. My backport to 3.2.0.x has
merged. My backport to 3.2.1 is still open. IIRC this code to detect the
docker cgroup was added in 3.2 and it's not in 3.1. @derekwaynecarr
<https://github.com/derekwaynecarr> is that correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9060#issuecomment-222167276>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p16Ic4Yq5vT6OvRY4XPiO9caxuPlks5qFwUlgaJpZM4IojrU>
.

**Comment by ncdc** [comment]
This PR makes it so we determine docker's pid by its pidfile. It should work for both docker-current and docker-latest.

**Comment by smarterclayton** [comment]
Great.

**Comment by smarterclayton** [comment]
Let's hold merge for rebase.

**Comment by derekwaynecarr** [comment]
@smarterclayton @ncdc - the pidof docker check was introduced in kube 1.2, so it should not be origin 3.1.

There was a separate pidof docker check in kube 1.1 here:
https://github.com/kubernetes/kubernetes/blob/v1.1.0/pkg/kubelet/container_manager_linux.go#L254

But it was only followed if you specified the container to place docker in:
https://github.com/kubernetes/kubernetes/blob/v1.1.0/pkg/kubelet/container_manager_linux.go#L149

Which we did not do in origin since we assumed systemd.

**Comment by smarterclayton** [comment]
Ok

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
[merge]

**Comment by lvthillo** [comment]
@smarterclayton I performed the ansible installation and I seem to have this issue.
I found the kubelet issue
```
container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
```

**Comment by ncdc** [comment]
@lvthillo what does `openshift version` show?

**Comment by lvthillo** [comment]
@ncdc 
```
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
```
I described this in my ansible: 
```
deployment_type=origin
openshift_pkg_version=-1.2.0-4.el7
```

**Comment by ncdc** [comment]
This PR was merged after 1.2. It's available in 1.3.0-alpha.2 and later.

**Comment by lvthillo** [comment]
@ncdc Okay thanks, I saw the workaround: 
`
ln docker-current docker` but where do I have to execute this command?

**Comment by ncdc** [comment]
@lvthillo I would assume in /usr/bin on your nodes.

**Comment by lvthillo** [comment]
@ncdc thanks
```
cd /usr/bin
ln docker-current docker
ln: failed to create hard link 'docker': File exists
```
I just deleted the file docker and reset the link. Than I restarted my node but still the same issue.

**Comment by lvthillo** [comment]
```
[root@node01 bin]# ls -l | grep "docker"
lrwxrwxrwx.   1 root root          14 Jun 28 16:27 docker -> docker-current
-rwxr-xr-x.   1 root root    43193474 Jun 24 14:10 docker-current
-rwxr-xr-x.   1 root root       27660 May 10 16:45 docker-storage-setup
lrwxrwxrwx.   1 root root          18 Jun 28 14:59 openshift-docker-build -> /usr/bin/openshift
-rwxr-xr-x.   1 root root         928 May 25 21:04 openshift-sdn-docker-setup.sh
```

**Comment by ncdc** [comment]
I don't think that workaround will work. Prior to this PR, the code runs `pidof docker`, which I don't think will work because the actual running process is `docker-current`.

**Comment by lvthillo** [comment]
Hmm okay, but I need to find a way to let this work on 1.2.0 without showing these logs. There is no other thing I can do?

**Comment by ncdc** [comment]
I'll defer to @smarterclayton as to whether or not he wants to backport this to 1.2.

**Comment by lvthillo** [comment]
@ncdc The newest version (without specifing the version in ansible) is still 1.2.0 so I keep seeing the log every 5 minutes. I hope this fix will also be implemented in 1.2.0 because that's a 'stable' release. No alpha.

**Comment by jacderida** [comment]
Hi,

I am also encountering this problem. I wanted to deploy 1.3.0-alpha.2, but I don't actually know how you get the Ansible installer to do it. 

I set openshift_pkg_version=-1.3.0-alpha.2 in the inventory for the install. It then fails:
```
TASK [openshift_common : Install the base package for versioning] **************
fatal: [dcp-master.westeurope.cloudapp.azure.com]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'origin-1.3.0-alpha.2' found available, installed or updated", "rc": 0, "results": []}
```
Looking at the code for the installer, from what I can see, it's just using yum to install the master or node package. However, yum only has these versions:
```
[root@dcp-master ~]# yum list available origin-master --showduplicates
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Available Packages
origin-master.x86_64                           1.1.6-1.git.9999.9c5694f.el7                             centos-openshift-origin
origin-master.x86_64                           1.2.0-1.git.10183.7386b49.el7                            centos-openshift-origin
origin-master.x86_64                           1.2.0-2.el7                                              centos-openshift-origin
origin-master.x86_64                           1.2.0-4.el7                                              centos-openshift-origin
origin-master.x86_64                           1.2.1-1.el7                                              centos-openshift-origin
```

Is there a way to get the installer to use the 1.3 alpha version?

Cheers,

Chris

**Pull request merged**
