### PR TITLE
Observe should exit when enough reflector errors occur

### PR DESCRIPTION
**Pull request by smarterclayton**
A production service lost networking configuration and was unable to
continue. The reflector just broke and stayed broken, which means the
observe starved. observe should respect `--maximum-errors` as well.
Rather than complicating the code by trying to mix error counts the list
error count is tracked separately, meaning after some amount of seconds
we exit.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@openshift/sig-master 

We have this problem in other controllers, but observe has `--maximum-errors` and this bit it.

**Comment by soltysh** [comment]
> @openshift/sig-master
> 
> We have this problem in other controllers, but observe has --maximum-errors and this bit it.

@smarterclayton would you mind be more specific about that?

**Comment by smarterclayton** [comment]
Router for example loops forever at 1s intervals if the admin didn’t grant access to services at namespace scope, without backoff or any ability to report that failure.  For most components that’s ok, for a lot of others it may not be.  At some point we need to fix that so that backoff or failure is possible.

In this case observe typically deals with a single resource - if you cannot access that resource the controller is worthless.

**Comment by smarterclayton** [comment]
I suspect we would just add something to reflector and informer which is an error handler.

**Comment by soltysh** [comment]
Created https://github.com/openshift/origin/issues/19274.

**Pull request merged**
