### PR TITLE
fix case for events

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/5677

### CODE REVIEW

**Comment by deads2k** [comment]
@simon3z If you need it now.  This won't merge for 3.1

**Comment by simon3z** [comment]
Thanks @deads2k

**Comment by deads2k** [comment]
@kargakis ptal

**Comment by kargakis** [comment]
LGTM

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
@jwforres 

[merge]

**Pull request merged**
