### PR TITLE
Bump v2 registry

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
Requires #1774 and Docker 1.6 before this can be merged

**Comment by ncdc** [comment]
@smarterclayton I just added a commit that removes the simulated pull by id generator for the DockerImageReference struct. Now, if the referenced ID parses a digest, it uses v2 pull by id. Otherwise, it treats it as a tag (simulated v1 pull by id via tag).

**Comment by ncdc** [comment]
I've got another force push coming that updates the registry codebase to the v2.0.0 tag...

**Comment by sdodson** [comment]
@ncdc when you merge this please merge #1748

**Comment by ncdc** [comment]
@sdodson thanks for the notice. I'm also wondering if we need some code in origin somewhere that prints a fatal message if the user tries to start up master/node with Docker < 1.6?

**Comment by markturansky** [comment]
Thanks for the lesson on Fatal logging.  LGTM from what I can tell :)

**Comment by sdodson** [comment]
@ncdc Seems prudent for node though I have no idea how to do that, perhaps check for minimum api levels in the client?

You're welcome to yank that commit into this PR and close my PR so things are more atomic.

**Comment by smarterclayton** [comment]
Kubelet does that, but we allow starting on master.  Check the upstream kubelet min docker version health check code

**Comment by smarterclayton** [comment]
This is LGTM - let me know when the base and regular AMI's are built.

**Comment by ncdc** [comment]
Just waiting on 1.6 RPMs

**Comment by ncdc** [comment]
1.6 RPMs are available. https://ci.openshift.redhat.com/jenkins/job/openshift3_base_ami/600/ completed successfully for Fedora and it has 1.6. I've requested a new build of openshift3_ami.

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
spurious failure [test]

**Comment by smarterclayton** [comment]
Doesn't have docker 1.6?

**Comment by ncdc** [comment]
The ami with 1.6 won't build the release - that's the email from this morning.

**Comment by ncdc** [comment]
No whammies no whammies no whammies [test]

**Comment by ncdc** [comment]
EC2 whammy :-( [test]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
