### PR TITLE
Add missing fuzzers for AnonymousConfig test

### PR DESCRIPTION
**Pull request by mfojtik**
@deads2k I hope I did this right ;-)

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by deads2k** [comment]
Looks right, but we still have codec, negotiatedserializer, roundtripper, and func for roundtripper.  The Auth bits don't need a fuzzer.

**Comment by mfojtik** [comment]
@deads2k PTAL

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by mfojtik** [comment]
[merge]

it seems like yum is not having the best day today...

**Pull request merged**
