### PR TITLE
Extend the e2e suite to a broader range of tests

### PR DESCRIPTION
**Pull request by smarterclayton**
Drops all selectivity and includes tests by default

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Do you have +/- on number of tests and runtime for this?

**Comment by smarterclayton** [comment]
Fixes #17416 by broadening the test scope.  still have slim down the set for known failures.

**Comment by mfojtik** [comment]
@bparees can you check the build extended_conformance_gce errors? Seems valid but I don't understand what is broken there ;)

**Comment by bparees** [comment]
looks like the build steps are just legitimately running faster than we ever would have expected:

```
I1124 08:48:34.085820       1 tar.go:296] Adding to tar: /tmp/build/inputs/Dockerfile as Dockerfile
Step 1 : FROM centos/ruby-22-centos7
Trying to pull repository docker.io/centos/ruby-22-centos7 ... 
latest: Pulling from docker.io/centos/ruby-22-centos7
Digest: sha256:d885792a9118edd0504bc9194b2a34c3d076c95775f2da715e5d21532d25ce42
 ---> 161690d448ba
Step 2 : ENV "BUILD_LOGLEVEL" "5"
 ---> Running in 6c02f5989db8
 ---> f45a7ff0eece
Removing intermediate container 6c02f5989db8
Step 3 : USER root
 ---> Running in bfee690dcd08
 ---> 6feee10cd0ea
Removing intermediate container bfee690dcd08
Step 4 : ENV "OPENSHIFT_BUILD_NAME" "test-1" "OPENSHIFT_BUILD_NAMESPACE" "extended-test-build-timing-pjmwx-w2fmt"
 ---> Running in 3d04802a5cb9
 ---> 8d317cb61be1
Removing intermediate container 3d04802a5cb9
Step 5 : LABEL "io.openshift.build.namespace" "extended-test-build-timing-pjmwx-w2fmt" "io.openshift.build.name" "test-1"
 ---> Running in a9b2146f9784
 ---> 70d77e10fc2c
Removing intermediate container a9b2146f9784
Successfully built 70d77e10fc2c
I1124 08:48:34.924613       1 cfg.go:39] Locating docker auth for image docker-registry.default.svc:5000/extended-test-build-timing-pjmwx-w2fmt/test:latest and type PUSH_DOCKERCFG_PATH
```

which is what the test failure output is telling you.  Reduce the expected stage timings to great than 1ms instead of 1000ms and it should be good.  The purpose of the test is just to ensure the timings are not zero.

**Comment by smarterclayton** [comment]
Green, merging so we get back to approximate coverage.

**Comment by smarterclayton** [comment]
@mrunalp what I mentioned

**Comment by mrunalp** [comment]
@smarterclayton Thanks!

**Pull request merged**
