### PR TITLE
[3.9] Bug 1749930: ImageGC fixes

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Comment by sjenning** [comment]
this PR is missing a follow on commit that fixed a panic that this change introduces.  See the 3.10 PR.

https://github.com/openshift/origin/pull/23183

The 3.10 PR would need to merge before this one.
/hold

**Comment by jottofar** [comment]
@sjenning I did pickup that panic fix but included everything in one commit:
https://github.com/openshift/origin/blob/8d3126c7e5a26ddd3cb513b471ad6bfe705e5388/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go#L106

**Comment by jottofar** [comment]
@sjenning also, isn't the 3.10 PR just waiting for approval?

**Comment by jottofar** [comment]
@sjenning still need action on this please

**Comment by derekwaynecarr** [comment]
this doesn't appear to compile...  how was this verified?

**Comment by rphillips** [comment]
build passes 

/lgtm

**Pull request merged**
