### PR TITLE
UPSTREAM: 47367: add client side event spam filtering

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref https://github.com/kubernetes/kubernetes/pull/47367

addresses event spam in large cluster sizes

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
marking wip while i update the godep for juju

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
right now, this matches the upstream.

/cc @eparis @sjenning @smarterclayton

**Comment by eparis** [comment]
```
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
# github.com/openshift/origin/vendor/k8s.io/client-go/tools/record
vendor/k8s.io/client-go/tools/record/events_cache.go:457: syntax error: unexpected <<, expecting }
[ERROR] PID 142: hack/lib/build/binaries.sh:223: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 2.
```

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
@eparis - sorry i had pushed something wrong, still getting back my muscle memory.

**Comment by derekwaynecarr** [comment]
flaked on "oc new-app should succeed with a --name of 58 characters"

[test]

**Comment by derekwaynecarr** [comment]
re [test]

**Comment by derekwaynecarr** [comment]
flake on oc new-app re [test]

**Comment by derekwaynecarr** [comment]
flake creating the cluster [test]

**Comment by derekwaynecarr** [comment]
[test]

**Comment by derekwaynecarr** [comment]
success!

**Comment by eparis** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] integration tests suddenly started hitting a job level timeout

**Comment by eparis** [comment]
I'm going to tag with [merge] again The network test failed waiting for 3 dind nodes to be ready. There isn't much I'd say this PR was impossible to blame for...

**Comment by eparis** [comment]
of course the second time network looks just fine...

**Pull request merged**
