### PR TITLE
router - depricate -expose-metrics --metrics-image

### PR DESCRIPTION
**Pull request by pecameron**
bug 1499026
https://bugzilla.redhat.com/show_bug.cgi?id=1499026
1499026 - Deprecate oc adm router --expose-metrics and --metrics-image

OCP 3.11

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc @smarterclayton PTAL

**Comment by knobunc** [comment]
@smarterclayton What is the deprecation policy around this?  Can we just remove it?  Or do we have to have a note in the docs and the command line flags for N releases and then we can remove the functionality after N + M releases?

**Comment by pecameron** [comment]
@knobunc @smarterclayton I think we added the deprecation note in 3.7. 
Somebody else removed the code except for the command line options. The options before this PR were ignored, this PR removes them. Don't know when that happened.
docs pr 8803 removes the note.

**Comment by smarterclayton** [comment]
We generally preserve the flags for a long time because the best outcome is
we break someone who has them in a script somewhere.

On Apr 19, 2018, at 11:15 AM, Phil Cameron <notifications@github.com> wrote:

@knobunc <https://github.com/knobunc> @smarterclayton
<https://github.com/smarterclayton> I think we added the deprecation note
in 3.7.
Somebody else removed the code except for the command line options. The
options before this PR were ignored, this PR removes them. Don't know when
that happened.
docs pr 8803 removes the note.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/19432#issuecomment-382774256>,
or mute
the thread

**Comment by dcbw** [comment]
@smarterclayton how long is "a long time"?  A couple origin releases?

**Comment by smarterclayton** [comment]
3-4 releases

**Comment by pecameron** [comment]
@knobunc PTAL

**Comment by pecameron** [comment]
@smarterclayton so is this ready to merge? Do we need to wait longer?

**Comment by pecameron** [comment]
@knobunc looks like this is all set except another approval.

**Comment by sdodson** [comment]
@juanvallejo bump for contrib approval

**Comment by pecameron** [comment]
@knobunc @juanvallejo @sdodson @smarterclayton This has been hanging around for quite a while. Is there something we need to do to get this merged?

**Comment by pecameron** [comment]
@sdodson @knobunc It seems to be a timeout:
Readiness probe failed: Get https://10.128.0.12:8443/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Does this really relate to the changes in this PR?

**Pull request merged**
