### PR TITLE
make TSB conformant with respect to multiple parallel operations

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by bparees** [comment]
worth adding a test that does multiple binds/unbinds concurrently for a few iterations?  I know we can't guarantee we hit the conflict but it would be a nice smoke test.

**Comment by bparees** [comment]
(otherwise lgtm. should be backported to ose:enterprise-3.7 and ose:enteprise-3.8)

**Comment by jim-minter** [comment]
tests added, thanks

**Comment by bparees** [comment]
provision test?

**Comment by jim-minter** [comment]
provision test added.

**Pull request merged**
