### PR TITLE
etcd 01 bump

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/15313

Only the last commit is new.  Should merge after the rebase  [test]

### CODE REVIEW

**Comment by deads2k** [comment]
Oh, and it's @smarterclayton's commit, so when I merge it, it's legal :)

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
[test]

**Comment by liggitt** [comment]
didn't bump godeps.json, which means the etcd version check will fail

**Comment by liggitt** [comment]
included v3.2.1 godep changes in https://github.com/openshift/origin/pull/15321

**Pull request closed without merging**
