### PR TITLE
minor fixes to oc set resources 

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
- Implementing --dry-run and --local flags correctly 
-  fixes an issue where setting a request/limit deletes any previously set request/limit

bug: 1388404 [Link](https://bugzilla.redhat.com/show_bug.cgi?id=1388404)

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@knobunc

**Comment by knobunc** [comment]
[test]

**Comment by dcbw** [comment]
LGTM

**Comment by knobunc** [comment]
[merge]

**Comment by kargakis** [comment]
This got reverted upstream. Is there an open PR that submits it again?

**Comment by JacobTanenbaum** [comment]
Yes there is a new PR:[36174](https://github.com/kubernetes/kubernetes/pull/36174)

**Comment by kargakis** [comment]
cool, thanks

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/11775 [test]

**Pull request merged**
