### PR TITLE
enforce feature constraints

### PR DESCRIPTION
**Pull request by deads2k**
1. on create, only allow a whitelist of options
2. on update, allow untouched fields to remain, but if they are touched, they are subject to normal validation
3. on update, do not allow changing from techpreview to not techpreview
4. ban all features.config.openshift.io deletion to prevent deletion and recreation without techpreview

/assign @derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
the code looks good, but we should probably have a few unit tests.

**Comment by deads2k** [comment]
> the code looks good, but we should probably have a few unit tests.

sure

**Pull request merged**
