### PR TITLE
Bash completion regen for oc/oadm rename

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@fabianofranz PTAL and tag clayton/dan for a merge if you're ok with it, it's broke right now as it is.

**Comment by fabianofranz** [comment]
LGTM, @smarterclayton please spell the magic words.

**Comment by smarterclayton** [comment]
A-P-P-R-O-V-E-D-S spells banana

**Comment by fabianofranz** [comment]
[merge] as per approval of our lord commander

**Pull request merged**
