### PR TITLE
Update probe to use healthz port

### PR DESCRIPTION
**Pull request by ramr**
@smarterclayton @pweil-  PTAL. Thx

FYI - update probe change related to the healthz port PR (https://github.com/openshift/origin/pull/6030).

### CODE REVIEW

**Comment by ramr** [comment]
@smarterclayton  /bump

**Comment by ramr** [comment]
@smarterclayton  since #6030 has merged, this now is now ready for review. PTAL thx.

**Comment by smarterclayton** [comment]
Hrm - can you rebase so the first commit disappears?

**Comment by ramr** [comment]
@smarterclayton  rebased and the first commit is gone.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
