### PR TITLE
Scheduler has an official default name

### PR DESCRIPTION
**Pull request by smarterclayton**
@abhgupta

### CODE REVIEW

**Comment by smarterclayton** [comment]
Found in #7165

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by abhgupta** [comment]
@smarterclayton retrospective review - I believe this was the only remaining change that was required. @deads2k seems to have made the other changes required to handle the default scheduler upstream change a couple of weeks back.

The annotation for the scheduler name on the pod is still optional and the default scheduler is picked up if it is missing. So, there is no other impact as far as I can see.

**Comment by smarterclayton** [comment]
Thanks

**Pull request merged**
