### PR TITLE
Bug 1270728 - username in the secret don't override the username in the source URL

### PR DESCRIPTION
**Pull request by liggitt**
Dupe of #5322 so @csrwng can review while @jhadvig is offline

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by csrwng** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
flake:
```
Godeps/_workspace/bin/go-bindata: No such file or directory
```

**Comment by liggitt** [comment]
[test]

**Pull request merged**
