### PR TITLE
Don't ignore errors reported during Docker push/pull

### PR DESCRIPTION
**Pull request by mtrmac**
<s>DO NOT MERGE AS IS: This includes a commit which manually patches in **UNMERGED** https://github.com/openshift/imagebuilder/pull/97 ; that probably needs to happen only after that PR is reviewed, and in some other way than this manual patch.</s>

Longer-lived Docker API operations report only trivial errors (e.g. invalid syntax) as HTTP status codes; the rest is reported in the body of the response, along with other progress messages.

Right now `openshift/imagebuilder/imageprogress` ignores such errors; https://github.com/openshift/imagebuilder/pull/97 fixes that, and this PR modifies OpenShift to take advantage of this (and, in some cases, to close the `imageprogress` objects and to terminate the associated goroutines).

<s>For now **absolutely untested** beyond existing local unit tests; I’ll check whether testing this can be easily incorporated into them.</s>

### CODE REVIEW

**Comment by mtrmac** [comment]
(See individual commit messages for details.)

**Comment by mtrmac** [comment]
> For now **absolutely untested** beyond existing local unit tests; I’ll check whether testing this can be easily incorporated into them.

`pkg/builder/dockerutil.{pullImage,pushImage}` had existing unit tests, so I have extended them to verify this as well; `pkg/oc/clusterup/docker/dockerhelper` has almost no tests, so I’m not too inclined to build all that infrastructure right now.

**Comment by bparees** [comment]
@mtrmac can you recreate this PR against ose 3.10 and origin 3.11?

**Comment by mtrmac** [comment]
> @mtrmac can you recreate this PR against ose 3.10 and origin 3.11?

#21195 for 3.11; I’ll do 3.10 after I get the necessary access rights.

**Comment by mtrmac** [comment]
FWIW this is still applicable to master, so rebased. (And the PR no longer includes the already performed rebase of origin/imagebuilder.)

**Comment by mtrmac** [comment]
> I’ll do 3.10 after I get the necessary access rights.

Done as well.

**Comment by bparees** [comment]
/hold
all this code has been moved into openshift/builder and that code is about to be replaced due to https://github.com/openshift/builder/pull/5

after that PR merges we can revisit what the push/pull logic needs to do in terms of writing output and handling errors.

**Comment by bparees** [comment]
i'm 99% certain this is irrelevant to 4.0 since we're now using buildah to push/pull, but @mtrmac can you talk with @nalind to confirm there's no equivalent to this that we need to worry about when using buildah to push/pull?

**Comment by bparees** [comment]
@nalind ok, can you make a PR against openshift/builder?

at some point i think we're also going to have to clean up the output from buildah when it pulls/pushes.  Either by wrapping/parsing the output, as we did with docker, or by changing it in buildah itself.  But that is not an immediate concern.

**Comment by mtrmac** [comment]
> all this code has been moved into openshift/builder and that code is about to be replaced due to [openshift/builder#5](https://github.com/openshift/builder/pull/5)

Just to make sure, this includes a change to `pkg/oc/clusterup/docker/util/helper.go`; is that going away entirely as well? I’ll rebase this (dropping the `pkg/build/builder` parts which are no longer applicable) in a bit.

**Comment by mtrmac** [comment]
> @mtrmac can you talk with @nalind to confirm there's no equivalent to this that we need to worry about when using buildah to push/pull?

There’s no logical equivalent of this for `buildah`; with no HTTP involved, errors are AFAIK always reported using just an `error` value.

That said, the code still exists in `dockerutil.go`, although called only by tests.

> We probably want to have the pullImage/pushImage methods in DockerBuilder and S2IBuilder use retryImageAction to get that back. I think that the version from this PR that switches to having retryImageAction use a callback would make that easier.

I’ll rebase this PR to the openshift/builder repo, then, including the `dockerPullImage`/`dockerPushImage` fixes; if you want them dropped afterwards, sure, you can drop them just as easily before and after the fix :)

**Comment by mtrmac** [comment]
Rebased this PR, now applies only to pkg/oc/clusterup/docker/util/helper.go .

Filed https://github.com/openshift/builder/pull/10 for the moved part.

**Comment by bparees** [comment]
@mtrmac pretty sure cluster up will be going away, but for now it's worth getting the fix in... can you squash these commits and i'll lgtm?

**Comment by mtrmac** [comment]
@bparees squashed.

**Comment by mtrmac** [comment]
3ba3a423b8ddfb71c129d899d9ebe153ae1903ed has removed `oc cluster` entirely, so this is no longer necessary.

**Pull request closed without merging**
