### PR TITLE
bump apis/rework externalRegistryHostname api

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/retest


Ben Parees | OpenShift

**Comment by bparees** [comment]
@openshift/sig-master ok this bump is complete/ready for review.

**Comment by bparees** [comment]
@adambkaplan ptal

/retest

**Comment by bparees** [comment]
(there is likely at least one followup api bump to do, but i want to get this merged so that people are not blocked from bumping origin anymore)

**Comment by mfojtik** [comment]
/hold

@soltysh feel free to unhold this if you're fine with this with regards to landing 1.12 rebase.

**Pull request merged**
