### PR TITLE
Add the DenyExecOnPrivileged admission control plugin to origin

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
@smarterclayton fyi

**Comment by smarterclayton** [comment]
LGTM

**Comment by deads2k** [comment]
Were you able to think of way to keep our admission controllers in sync with kube via a unit test?

**Comment by csrwng** [comment]
@deads2k I need to add one.

**Comment by deads2k** [comment]
> @deads2k I need to add one.

If it's reasonable, lets do it before this merges.

Also, you hit the https://github.com/openshift/origin/issues/4245 flake.

**Comment by smarterclayton** [comment]
This should go in now - you can add the test in a follow up

On Aug 19, 2015, at 9:08 AM, David Eads <notifications@github.com> wrote:

@deads2k <https://github.com/deads2k> I need to add one.

If it's reasonable, lets do it before this merges.

Also, you hit the #4245 <https://github.com/openshift/origin/issues/4245>
flake.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4250#issuecomment-132585291>.

**Comment by csrwng** [comment]
[test]

**Comment by deads2k** [comment]
Please link issues to detect unused admission controllers and low severity issue to make that e2e test into an integration test.  I'd like to keep e2e focused on running the basic scenario, not testing permission edges.

lgtm [merge]

**Comment by csrwng** [comment]
https://github.com/openshift/origin/issues/4265

**Pull request merged**
