### PR TITLE
Fix limit ranger

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/7401

@derekwaynecarr downstream pick of https://github.com/kubernetes/kubernetes/pull/21470
@sosiouxme fyi

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
got lgtm upstream, p1 for us [merge]

**Comment by sosiouxme** [comment]
@deads2k are you doing the same thing for ResourceQuota? Basically any admission controller that has the pattern of keeping a watch-filled cache would have the same problem...

**Comment by deads2k** [comment]
> @deads2k are you doing the same thing for ResourceQuota? Basically any admission controller that has the pattern of keeping a watch-filled cache would have the same problem...

@danmcp?  This seems like the most severe "default allow" admission plugin I know of, but the concept could be generalized.

**Pull request merged**
