### PR TITLE
disconnect openapi aggregation

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/15326

This does the minimal diff to disconnect the openapi aggregation to make future picks/fixes easier to bring back.

@liggitt @sttts @smarterclayton ptal.

### CODE REVIEW

**Comment by deads2k** [comment]
hopefully this is a little faster.

**Comment by deads2k** [comment]
This is expected to significantly decrease test-integration time.  Bumping to the top of the queue.

**Comment by liggitt** [comment]
took 20 minutes off the time

**Comment by smarterclayton** [comment]
Of the remaining 0.8 core seconds.... 0.6 core seconds are directly attributable to openapi parsing on startup.

**Comment by deads2k** [comment]
> Before: one integration test took about 40 wall seconds and about 38 core seconds.
> After: one integration test took about 20 wall seconds and 0.8 core seconds

But lacked sufficient imagination.  It's taking me something like six seconds to have openapi start even *with* this pull.  I think this should still go in, but I'll keep chasing it.  We don't need openapi for integration tests.

**Comment by sttts** [comment]
Hou, what a difference. What made it that slow?

**Comment by deads2k** [comment]
I don't see any swagger changes between the test and now.  letting it through without a retest

**Comment by smarterclayton** [comment]
I think I might have found the 20 characters that make all of this go away :)

**Pull request merged**
