### PR TITLE
Remove unused Java import package

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Seems like this should go into the Cluster Capacity upstream first.

/cc @aveshagarwal

**Comment by apupier** [comment]
> Seems like this should go into the Cluster Capacity upstream first.

do you mean that it needs to be fixed here https://github.com/kubernetes-incubator/cluster-capacity/blob/master/vendor/k8s.io/kubernetes/examples/storage/cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java#L38 ?
How to know that something is coming from upstream and from which repo?

**Comment by apupier** [comment]
I created https://github.com/kubernetes-incubator/cluster-capacity/pull/91
(currently an issue with the CLA but I sent a mail to helpdesk@rt.linuxfoundation.org)

**Comment by stevekuznetsov** [comment]
Even in that repo it is a vendor -- looks like k8s/examples is the root

**Comment by apupier** [comment]
> Even in that repo it is a vendor -- looks like k8s/examples is the root

how did you find the root?
What is a "vendor"? This terminology comes from which ecosystem?

**Comment by apupier** [comment]
created https://github.com/kubernetes/examples/pull/142

**Comment by stevekuznetsov** [comment]
This is normal Golang terminology for third-party dependencies.

**Comment by apupier** [comment]
it has been fixed upstream, is something needed to incorporate the modifications?

**Comment by stevekuznetsov** [comment]
We pull it in from upstream. @aveshagarwal

**Pull request closed without merging**
