### PR TITLE
Always chcon node volume dir

### PR DESCRIPTION
**Pull request by ncdc**
Always try to chcon the volume dir to svirt_sandbox_file_t, regardless
of whether or not the dir previously existed. This is required to avoid
SELinux denials that occur when the volume dir is created prior to
starting the node and it doesn't have the correct SELinux label.

@smarterclayton @pmorie @rhatdan @bparees @deads2k @danmcp @liggitt

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by rhatdan** [comment]
Any reason to do this versus creating the container using :z or :Z on the volume mount?

**Comment by ncdc** [comment]
The node may run "bare" or containerized. If it's bare, we have to get the labeling correct. If it's containerized, we're running with `--pid=host`, which means :z/:Z are no-ops. This is the only way I've found so far that guarantees the chcon happens.

**Comment by smarterclayton** [comment]
LGTM - merge if you're comfortable

**Comment by ncdc** [comment]
It's no "worse" than we were before - this change makes it so chcon is called every time we start the node, instead of only if it's the node startup that creates the volume dir.

**Comment by ncdc** [comment]
[test]

**Comment by pmorie** [comment]
LGTM, [merge]

**Pull request merged**
