### PR TITLE
updated issue template

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@danmcp @smarterclayton @bparees PTAL

I've never liked the 'how reproducible' ... it's not proper English. 

I will say as a dev and not a user, this template is a little annoying as it forces me to delete all that nonsense on every issue I make that isn't a usability bug.

### CODE REVIEW

**Comment by smarterclayton** [comment]
`CTRL+A DEL <insert complaints here>` but yes I agree.

[merge]

**Comment by bparees** [comment]
> I will say as a dev and not a user, this template is a little annoying as it forces me to delete all that nonsense on every issue I make that isn't a usability bug.

maybe you should open an issue complaining about that.

the template isn't just for usability bugs, not sure why you say that.  unless by "usability" you mean in the most general/broadest of senses, in which case everything is a usability bug.

**Comment by stevekuznetsov** [comment]
@bparees Usability as in "I am trying to use OpenShift". I opened an issue earlier today that was about some of the tech debt we have in our graph implementation that would never need this information. Any of the issues that had been created to track all of the implementation specifics for LDAP sync would never have needed that info. Any of the issues that track the various issues we have with our support code never need that information.

**Comment by stevekuznetsov** [comment]
I just wonder if we're optimizing for the (very) uncommon case here.

**Comment by bparees** [comment]
There's a good chance things like that should be being handled either
1) via a trello card so it gets sized/scheduled appropriately
2) via bugzilla so QE gets involved in the process of testing the changes

The issue process, though we have gotten out of the habit of treating it as such due to laziness/convenience, is really more for external users.  The github issue flow doesn't work very well into our processes.

**Comment by bparees** [comment]
> I just wonder if we're optimizing for the (very) uncommon case here.

uncommon to you perhaps, but most of the issues I see do come from users, not internal developers.

**Comment by stevekuznetsov** [comment]
> uncommon to you perhaps, but most of the issues I see do come from users, not internal developers.

Of the issues on the first page right now, two or three of twenty five are from non-developers.

That being said, I guess it does make more sense of those sorts of things to be Trello cards. Point taken.

**Comment by mfojtik** [comment]
i am all for making the template slimmer for us, on the other hand i like
to give users clues about how to gather additional info when they find a
bug and they reporting it.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
