### PR TITLE
Print resource kind when `oc get all` outputs multiple resources of the same type

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/37636
Related comment: https://github.com/kubernetes/kubernetes/issues/37533#issuecomment-263405125

This patch ensures that a resource prefix is added to multiple items of
the same kind, when using `oc get all`. Before, a prefix was added only
when a single item was returned on `oc get all`, but ignored if only a
single resource kind existed but multiple items for that kind were
returned.

**Example**
```
$ oc get all
No resources found.

$ oc create service loadbalancer testsvc1 --tcp=8080
$ oc get all
NAME               CLUSTER-IP       EXTERNAL-IP                     PORT(S)    AGE
svc/testsvc1       172.30.119.220   172.46.100.155,172.46.100.155   8080/TCP   1h

$ oc create service loadbalancer testsvc2 --tcp=8081
$ oc get all
NAME               CLUSTER-IP       EXTERNAL-IP                     PORT(S)    AGE
svc/testsvc1       172.30.119.220   172.46.100.155,172.46.100.155   8080/TCP   1h
svc/testsvc2       172.30.241.197   172.46.164.158,172.46.164.158   8081/TCP   1h
```

@openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
conformance check flaked on https://github.com/openshift/origin/issues/10162

**Comment by juanvallejo** [comment]
conformance flake https://github.com/openshift/origin/issues/9379 re[test]

**Comment by juanvallejo** [comment]
@fabianofranz Upstream merged! https://github.com/kubernetes/kubernetes/pull/37636 PTAL

**Comment by fabianofranz** [comment]
@juanvallejo Thanks! Needs a squash.

**Comment by juanvallejo** [comment]
@fabianofranz 
> Thanks! Needs a squash.

Done!

**Comment by juanvallejo** [comment]
flaked on https://github.com/openshift/origin/issues/13271 re[test]

**Comment by juanvallejo** [comment]
cc @fabianofranz

**Comment by fabianofranz** [comment]
[merge]

**Comment by sosiouxme** [comment]
This is gonna fail unless you add priority: bug to it... and I'm not sure it's a bug?

**Comment by fabianofranz** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@juanvallejo is this supposed to only contain the test?

**Comment by juanvallejo** [comment]
@stevekuznetsov 
> is this supposed to only contain the test?

Yeah, any non-test changes were brought in during the last rebase

**Pull request merged**
