### PR TITLE
make sure we can unbind a deleted templateinstance

### PR DESCRIPTION
**Pull request by bparees**
won't pass tests until https://github.com/openshift/origin/pull/18416 has merged and new images are pushed.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm cancel

No need to keep running tests on this until prerequisites are fulfilled?

**Comment by bparees** [comment]
the pre-reqs *are* fulfilled.
https://github.com/openshift/origin/pull/18416 is merged.

**Pull request merged**
