### PR TITLE
remove non best practice zookeeper example

### PR DESCRIPTION
**Pull request by bparees**
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1515943

### CODE REVIEW

**Comment by bparees** [comment]
/assign @mfojtik 
(since it doesn't sound like you guys want to create a statefulset example)

**Comment by bparees** [comment]
(actually it looks like a stateful set example w/ zookeeper exists: https://github.com/openshift/origin/tree/master/examples/statefulsets/zookeeper)

so there is even less reason to keep this around.

**Comment by bparees** [comment]
@smarterclayton @liggitt any objections?

**Comment by liggitt** [comment]
none from me

**Comment by prateek1192** [comment]
The stateful set example link seems to be broken.

**Comment by bparees** [comment]
@prateek1192 it's here: https://github.com/openshift/origin/tree/release-3.9/examples/statefulsets/zookeeper

but since that was removed after 3.9 i have no idea if it still works on newer clusters or not, or whether any of the images it depends on have bit-rotted in the meantime.

**Pull request merged**
