### PR TITLE
Update documentation for DC conditions

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/origin/issues/14855

@mfojtik @jim-minter 

Signed-off-by: Michail Kargakis <mkargaki@redhat.com>

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis ❤️ it 

don't you need to update swagger && friends?

[test]

**Comment by kargakis** [comment]
> don't you need to update swagger && friends?

No, this is not part of the schema, merely the value of a condition.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/14829 [test]

**Comment by kargakis** [comment]
@mfojtik lgty?

**Comment by mfojtik** [comment]
[merge]

**Comment by deads2k** [comment]
re[test]

**Pull request merged**
