### PR TITLE
introduce virtual image concept to handle scratch images

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/7389

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal

**Comment by kargakis** [comment]
@bparees wrong PR title?

**Comment by smarterclayton** [comment]
Yeah, wrong commit.  Although I like that you added virtual ;)

**Comment by bparees** [comment]
@kargakis @smarterclayton whooops, i confused hub.  fixed.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
