### PR TITLE
S2i a839689 bump

### PR DESCRIPTION
**Pull request by oatmealraisin**
This unifies the CreateLocalGitDirectory function, which was previously copied to multiple locations.

Probably shouldn't get merged until [s2i/567](https://github.com/openshift/source-to-image/pull/567) is resolved

@bparees @php-coder ptal?

### CODE REVIEW

**Comment by bparees** [comment]
you're going to need to redo this bump after that PR is merged...  (so that we are bumping the godep to the merge commit in s2i master.  i am assuming this currently bumps the godep to your commit in your branch, and until that gets into master i don't want to risk merging this and confusing things if you change your commit)

**Comment by oatmealraisin** [comment]
So we should close this PR?

**Comment by bparees** [comment]
that's probably easier than fixing it up after the s2i changes are merged

**Comment by oatmealraisin** [comment]
Roger!

**Pull request closed without merging**
