### PR TITLE
Fix new-app help for app-from-image

### PR DESCRIPTION
**Pull request by csrwng**
Fixes https://github.com/openshift/origin/issues/2708

### CODE REVIEW

**Comment by csrwng** [comment]
@sosiouxme ptal

**Comment by sosiouxme** [comment]
I guess that's it for the docker image example :)

Is there any way to have `osc new-app myregistry.com/mycompany/mysql` work? as that is a valid image spec and the top of the help indicates you can just supply and IMAGE.

But if that's hard, don't let it hold this up.

**Comment by csrwng** [comment]
It should work... taking a look

**Comment by csrwng** [comment]
@sosiouxme - the registry/namespace/name argument should work in the latest code. It was fixed with https://github.com/openshift/origin/pull/2704.

**Comment by sosiouxme** [comment]
+1 confirmed that's fine now, thanks. [merge] this yes?

**Pull request merged**
