### PR TITLE
add image change trigger example to json

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by mfojtik** [comment]
lgtm 

btw. does metadata exists in v1beta1?

**Comment by bparees** [comment]
seems to, it's working... are you referring to any specific type?  I see it here:
https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta1/types.go#L10

**Comment by mfojtik** [comment]
yeah, sorry I am always confused with k8s versioning....

**Comment by bparees** [comment]
[merge]

**Pull request merged**
