### PR TITLE
Migrate utility scripts into `hack/lib'

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Now that we are enabled by #8853 we can begin some cleanup.

@smarterclayton PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test] me

**Comment by stevekuznetsov** [comment]
[test] me

**Comment by stevekuznetsov** [comment]
@smarterclayton this is ready

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
@smarterclayton this needs a re-kick please

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
Conformance flake on #9364

**Comment by stevekuznetsov** [comment]
flaked on EPEL nonsense ,... https://github.com/openshift/origin/issues/8571

@smarterclayton please re-tag

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
We hit https://github.com/openshift/origin/issues/8571 again...

**Comment by stevekuznetsov** [comment]
@smarterclayton mind re-tagging?

**Comment by stevekuznetsov** [comment]
@smarterclayton please re-tag

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
