### PR TITLE
start breaking deps on pkg/oc

### PR DESCRIPTION
**Pull request by juanvallejo**
Begin breaking dependencies on the `pkg/oc` subtree from the rest of the codebase.
https://docs.google.com/document/d/1mS-KRkU8zjCleBNi3WWhLtkH10hb8h4ajpFM743jnqg

The following is a list of files whose dependency on `pkg/oc` packages needs to be broken:

- [x] ~~pkg/generate/app/cmd/describe.go~~ (moved `pkg/generate/app/cmd` -> `pkg/oc/generate/app/cmd`) https://github.com/openshift/origin/pull/17332
- [x] ~~pkg/build/generator/generator.go~~ https://github.com/openshift/origin/pull/17332
- [x] pkg/cmd/server/start/master_args.go (https://github.com/openshift/origin/pull/17473)
- [x] **pkg/cmd/server/start/kubernetes/kubernetes.go** https://github.com/openshift/origin/pull/17335
- [x] pkg/cmd/server/admin/create_kubeconfig.go (shares code with `oc login`) https://github.com/openshift/origin/pull/17357
- [x] pkg/cmd/server/admin/overwrite_bootstrappolicy.go (will delete *pkg/cmd/server/admin/overwrite_bootstrappolicy.go* and *pkg/cmd/server/admin/legacyetcd/\**) https://github.com/openshift/origin/pull/17336
- [x] **pkg/cmd/infra/router/template.go** https://github.com/openshift/origin/pull/17335
- [x] **pkg/cmd/infra/router/f5.go** https://github.com/openshift/origin/pull/17335
- [x] **pkg/cmd/infra/deployer/deployer.go** https://github.com/openshift/origin/pull/17335
- [x] **pkg/cmd/infra/builder/builder.go** https://github.com/openshift/origin/pull/17335
- [x] pkg/cmd/openshift/openshift.go (https://github.com/openshift/origin/pull/17486 and https://github.com/openshift/origin/pull/17482)
- [x] *pkg/cmd/util/clientcmd/factory_object_mapping.go (see https://github.com/openshift/origin/pull/17309#issuecomment-344408870)* (*will move `clientcmd` pkg to `pkg/oc`* https://github.com/openshift/origin/pull/17356)
- [x] *pkg/cmd/util/clientcmd/factory_client_access.go (see https://github.com/openshift/origin/pull/17309#issuecomment-344408870)* (*will move `clientcmd` pkg to `pkg/oc`* https://github.com/openshift/origin/pull/17356)
- [x] ~~pkg/cmd/admin/policy/modify_roles_test.go~~ https://github.com/openshift/origin/pull/17332
- [x] pkg/diagnostics/cluster/roles.go (depends on `pkg/oc/admin/policy`: *will move to pkg/oc*) https://github.com/openshift/origin/pull/17393
- [x] pkg/diagnostics/cluster/rolebindings.go (depends on `pkg/oc/admin/policy`: *will move to pkg/oc*) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/client/config_loading.go (*will move to pkg/oc*) https://github.com/openshift/origin/pull/17393
- [x] *pkg/diagnostics/network/setup.go (*will move to pkg/oc*) https://github.com/openshift/origin/pull/17393
- [x] **pkg/federation/kubefed/kubefed.go** https://github.com/openshift/origin/pull/17335

**bold** = only depend on `pkg/oc` for the `NewCmdVersion` logic - will make simple version helper outside of `pkg/oc` to resolve

cc @liggitt @deads2k @mfojtik @bparees

### CODE REVIEW

**Comment by deads2k** [comment]
@juanvallejo  can you dig into this one:  pkg/cmd/infra/builder/builder.go ? I'm betting its a function for going from kubeconfig file to clientConfig.  the image-registry hit a similar problem

**Comment by juanvallejo** [comment]
@deads2k sure, will look into it now

**Comment by juanvallejo** [comment]
@deads2k The dependency is only on `NewCmdVersion`. [The file](https://github.com/openshift/origin/blob/master/pkg/cmd/infra/builder/builder.go#L74) defines command [entry points](https://github.com/openshift/origin/blob/master/pkg/cmd/openshift/openshift.go#L61) for:

```
$ openshift-sti-build
$ openshift-docker-build
$ openshift-git-clone
$ openshift-manage-dockerfile
$ openshift-extract-image-content
```

The same is true for [pkg/cmd/infra/router/f5.go](https://github.com/openshift/origin/blob/master/pkg/cmd/infra/router/f5.go#L155)

Any chance we could just make all of these subcommands under `oc`?
The alternative would be to move or duplicate the code under `pkg/oc/cli/cmd/version.go`, or to remove the `version` subcommand from the above.

**Comment by deads2k** [comment]
`pkg/generate/app/cmd/` says `oc` to me.  Who uses it?

**Comment by juanvallejo** [comment]
@deads2k `pkg/generate/app/cmd/describe.go` was the only file I found with a reference to `pkg/oc` - was using a time formatter in the pkg/oc/cli/describe/helpers.go

**Comment by deads2k** [comment]
> @deads2k pkg/generate/app/cmd/describe.go was the only file under that subtree I found with a reference to pkg/oc - was using a time formatter in the pkg/oc/cli/describe/helpers.go. Addressed in a5e30bb

@juanvallejo `pkg/generate/app/cmd` is only imported by packages under `pkg/oc`.  Move it under `pkg/oc`

**Comment by juanvallejo** [comment]
- `pkg/cmd/util/clientcmd/factory_object_mapping.go` -> depends on the oc `describe#DescriberFor` method

- `pkg/cmd/util/clientcmd/factory_client_access.go` -> depends on the oc `describe#NewHumanReadablePrinter` method AND `pkg/oc/cli/config#NewOpenShiftClientConfigLoadingRules` method

**Comment by juanvallejo** [comment]
[pkg/cmd/server/start/master_args.go](https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/master_args.go#L366) depends on generated bootstrap bindata, which is under `pkg/oc/bootstrap` - not sure how we plan to address this

**Comment by juanvallejo** [comment]
`pkg/cmd/server/admin/overwrite_bootstrappolicy.go` depends on the cli describer. Apparently it is used by the `oc adm overwrite-policy` command, but seems to be defined under `pkg/cmd/server` since it deals with authorization storage. Can this be moved under `pkg/oc`?

**Comment by sosiouxme** [comment]
@juanvallejo what would it mean to "move some of the diagnostic commands under pkg/oc"? I don't think there's a reason to have `oc adm diagnostics` command definitions live outside `pkg/oc/admin`.

**Comment by juanvallejo** [comment]
@deads2k only dependency left to address is [pkg/cmd/openshift/openshift.go](https://github.com/openshift/origin/blob/master/pkg/cmd/openshift/openshift.go#L24-L32) which brings in nine packages from `pkg/oc`

**Pull request closed without merging**
