### PR TITLE
oc should use only external types

### PR DESCRIPTION
**Pull request by deads2k**
/assign @soltysh

### CODE REVIEW

**Comment by deads2k** [comment]
I'm betting it's because of the naughty dep I found in https://github.com/openshift/origin/pull/22996

**Comment by deads2k** [comment]
This matches our overall arc. Tagging

**Comment by soltysh** [comment]
@deads2k looks like
```

**Comment by deads2k** [comment]
/hold

For the fix in the later pull. Weird that it flakes

**Comment by deads2k** [comment]
add the naughty dep fix

**Comment by soltysh** [comment]
/hold
until I debug that

**Pull request closed without merging**
