### PR TITLE
New flag to oc new-build to produce no output

### LINKED ISSUE #5296: It should be possible to have no output for a build
Extracted from #4980.

We will likely need to introduce another command line option that cannot be used together with `--to`.

### PR DESCRIPTION
**Pull request by rhcarvalho**
Closes #5296.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @smarterclayton PTAL
[test]

**Comment by bparees** [comment]
add a validation error if they specify "--to" or "--to-docker" and "--no-output"?

**Comment by rhcarvalho** [comment]
> add a validation error if they specify "--to" or "--to-docker" and "--no-output"?

I had thought of it and tried that out earlier and chose to not attempt to throw errors and simply produce no output (meaning --no-output takes precedence).

Reasoning (AFAICT):

1. there's no standard way in cobra to declare mutually exclusive flags.
2. there's no clean way to tell whether a flag was not provided vs. it was provided with the zero-value for its type. Unless manually reparsing the args, these would behave the same:

        oc new-build <src> --to-docker=false --to '' --no-output
        oc new-build <src> --no-output

**Comment by bparees** [comment]
good enough for me. thanks.
[merge]

**Pull request merged**
