### PR TITLE
UPSTREAM: 27392: allow watching old resources with kubectl

### PR DESCRIPTION
**Pull request by sjenning**
xref https://github.com/kubernetes/kubernetes/pull/27392

xref https://bugzilla.redhat.com/show_bug.cgi?id=1298500

Fixes bug 1298500

@ncdc @smarterclayton @liggitt

### CODE REVIEW

**Comment by ncdc** [comment]
[merge]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
[merge]

**Comment by liggitt** [comment]
@smarterclayton want to hold this for the bump?

**Pull request merged**
