### PR TITLE
move flagtypes to point of use

### PR DESCRIPTION
**Pull request by stlaz**
This ties up on https://github.com/openshift/origin/pull/23102 by moving the --loglevel flag back to just `oc`

Desc of orig PR:
```
Flagtypes had

    dead net flag type
    addr only used by oc and integration tests: move to oc
    add flags for glog, but we have generic goflag mirroring that I placed in the top level commands.

This eliminates another shared package
```

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

You can put my changes into your commit.  Or not if you want to avoid blame.

**Comment by stlaz** [comment]
Meh, needed to add generated completions.

**Comment by stlaz** [comment]
Removed the import that was breaking import verification and opened a PR in cluster-network-operator repo so that this change does not break it.

**Comment by stlaz** [comment]
Rebased on top of current master.
/lgtm
^-- the rebase conficts were only in import restrictions and completions

**Comment by deads2k** [comment]
what a value add!

/lgtm

**Pull request merged**
