### PR TITLE
add oauth-proxy login to kubeadmin tests

### PR DESCRIPTION
**Pull request by stlaz**
This mocks web-based login to oauth-server when redirected
from the oauth-proxy.

/assign @lilic

### CODE REVIEW

**Comment by stlaz** [comment]
Credits for the oauth-server page login mocking code go to @mrogers950, I merely took it, cleaned it a bit and adapted it for this purpose

**Comment by stlaz** [comment]
It's a bit hard to predict which repo can break this, but running at least this one test in authn-operator and oauth-proxy should be a must, I think it should be possible to add it in ci-operator config. I'll try to see about that.

**Comment by lilic** [comment]
>, I think it should be possible to add it in ci-operator config. I'll try to see about that.

Sounds good to me, not a blocker for this right now, we can merge this as well to run for those repos just now. Thanks!

**Pull request closed without merging**
