### PR TITLE
cluster up: override port forwarding if using docker machine

### PR DESCRIPTION
**Pull request by csrwng**
Using a docker machine should take precedence over the port forwarding setting.

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
@spadgett fyi

**Comment by bparees** [comment]
lgtm [merge]

**Comment by csrwng** [comment]
Opened issue for test flake: https://github.com/openshift/origin/issues/9999

**Comment by csrwng** [comment]
flakes: 
https://github.com/openshift/origin/issues/9548 
https://github.com/openshift/origin/issues/9490
https://github.com/openshift/origin/issues/9959

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
