### PR TITLE
always generate a config which contains aggregator keys for cluster up

### PR DESCRIPTION
**Pull request by deads2k**
The aggregator is always on in 3.7.  We should just go ahead and create keys for it.

[test]

### CODE REVIEW

**Comment by bparees** [comment]
what will happen when this logic is used to start a 3.6 server?  (or a 3.5 or 3.4 one...)

**Comment by deads2k** [comment]
Nothing, since they are excluded on parse, but my local copy is version gated.  I'll repsuh tomorrow am

**Comment by bparees** [comment]
I actually might prefer the non-version gated change.  I'd like to leave as much version-specific logic out of cluster up as possible.

**Comment by deads2k** [comment]
wow, that turned into a weird looking diff.

**Comment by bparees** [comment]
lgtm

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@bparees might want to start getting used to

/lgtm

**Pull request merged**
