### PR TITLE
CNF-6711 filter storage tests

### PR DESCRIPTION
**Pull request by qJkee**

### CODE REVIEW

**Comment by qJkee** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-no-capabilities 4.12

**Comment by qJkee** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-no-capabilities

**Comment by qJkee** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-no-capabilities

**Comment by bparees** [comment]
@qJkee can you squash these commits?

**Comment by qJkee** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-no-capabilities

**Comment by qJkee** [comment]
@bparees 
Yes, let me check the payload job first and then i'll do a squash

**Comment by bparees** [comment]
opened https://issues.redhat.com/browse/OCPBUGS-6796

/override ci/prow/e2e-gcp-ovn-upgrade

**Pull request merged**
