### PR TITLE
Use global LRU cache for layer sizes

### LINKED ISSUE #9779: Let's cache layers size globally
As a follow-up for #9115, let's cache layer sizes globally in a thread-safe
LRU cache. The solution in mentioned PR doesn't really utilize a cache because
during each new import, a new importer is created, whose `Import()` method is
invoked just once.

Let the cache be shared accross for all the imports happening in image import
controller.

### PR DESCRIPTION
**Pull request by legionus**
Fix #9779

@miminar please review.

### CODE REVIEW

**Comment by smarterclayton** [comment]
What performance improvement does this yield?  A quick benchmark would be helpful to set context.

**Comment by miminar** [comment]
I cannot disagree with having the benchmark. The PR looks good to me though.

**Comment by smarterclayton** [comment]
For this I'd ask you to create a reusable benchmark that is somewhat relevant that exposes that this does improve the problem.

**Comment by legionus** [comment]
@smarterclayton @miminar I added a test showing that an additional requests are not happening to already loaded layers. This means that the cache will reduce the number of network requests in case of import the converted images (v2 -> v1).

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
re[test]

**Comment by legionus** [comment]
[test]

**Comment by smarterclayton** [comment]
Great, thanks.

**Comment by smarterclayton** [comment]
Any other comments?  Otherwise this LGTM

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
