### PR TITLE
allow templateinstance updates for GC

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/14809 (I think)

[test]

### CODE REVIEW

**Comment by deads2k** [comment]
GC attempts to do a patch of finalizers and/or ownerrefs on objects as part of deletion.  We need to make sure that its always allowed to do that.

**Comment by jim-minter** [comment]
lgtm; thanks for that

**Comment by deads2k** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by liggitt** [comment]
This seems like it will happen often enough that we should have an integration test that creates one of every object, attempts to delete it with foreground deletion policy, and ensures the garbage collector can patch it and clean it up

**Pull request merged**
