### PR TITLE
[release-3.11] Bug 1769952: React to openshift/ruby-hello-world changes

### PR DESCRIPTION
**Pull request by adambkaplan**
Update to use ruby-25-centos7 image

### CODE REVIEW

**Comment by bparees** [comment]
/hold

pretty sure this is beating its head against a wall, please investigate the failures.

**Comment by adambkaplan** [comment]
/hold

As with 4.1, there are other changes that likely need to go in here as well.

**Comment by sallyom** [comment]
@adambkaplan see this, too: https://github.com/openshift/origin/pull/24143#issuecomment-553900421

**Comment by adambkaplan** [comment]
/close

Replaced by #24189

**Pull request closed without merging**
