### PR TITLE
UPSTREAM: 8530: GCEPD mounting on Atomic

### PR DESCRIPTION
**Pull request by pweil-**
@swagiaal @markturansky - I picked this in from the upstream patch since it was missed in the rebase.  Can I get some eyes on it to double check the changes?  

Fixes: https://github.com/openshift/origin/issues/4088

/cc @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
should probably wait until @deads2k's rebase lands

**Comment by markturansky** [comment]
@swagiaal Looks fine AFAICT but you're the better reviewer here for this patch.

**Comment by pweil-** [comment]
rebased to current master.  @swagiaal - bump for a quick look

**Comment by pweil-** [comment]
rebased again.  @swagiaal @markturansky - any other feedback?

/cc @deads2k

**Comment by swagiaal** [comment]
@pweil- travis is showing extra imports you missed but otherwise LGTM

**Comment by pweil-** [comment]
fixed - @deads2k ready when the light goes green

**Comment by pweil-** [comment]
@deads2k bump 

[test] again, this has been hanging out a while

**Comment by deads2k** [comment]
looks like a match to upstream.  [merge]

**Pull request merged**
