### PR TITLE
make set triggers tolerate new secretReference format

### PR DESCRIPTION
**Pull request by bparees**
bug 1532142

https://bugzilla.redhat.com/show_bug.cgi?id=1532142

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees Seems like a lot of duplicate code, 4 very similar sets of code for each of the 3 main sections that you updated, could have implications having to keep them all in sync for future updates, but probably not worth spending much time on right now.

I think you should add a test for the issue that was reported in the bugzilla to make sure that we don't have any kind of regression on this.

Otherwise it lgtm

**Comment by bparees** [comment]
tests added.  won't pass until https://github.com/openshift/origin/pull/18023 merges.

**Pull request merged**
