### PR TITLE
add jenkins to imagestream definitions

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
rhel7 image is not available yet, so don't merge this until it is.

**Comment by bparees** [comment]
@sdodson we're going to want to add the 2 jenkins templates to the set that are auto packaged/registered by ansible.

**Comment by sdodson** [comment]
@bparees Do you know when the rhel image will be live?

**Comment by bparees** [comment]
@sdodson the rhel image is live now.

**Comment by bparees** [comment]
[merge]

**Comment by sdodson** [comment]
@bparees there's no template to accompany the image?

**Comment by bparees** [comment]
@sdodson templates are in here: https://github.com/openshift/origin/tree/master/examples/jenkins

you can ignore the application-template.json, that's for the demo.

**Pull request merged**
