### PR TITLE
UPSTREAM: 45345: Support "fstype" parameter in dynamically provisioned PVs

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1469001

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @rootfs  @wongma7 
FYI, there is an old azure_dd provisioner in 3.7 so I did not add fsType there. Rest of the provisioners is directly from referenced upstream PR.

**Comment by pospispa** [comment]
LGTM

**Comment by jsafrane** [comment]
filled #16235

**Comment by wongma7** [comment]
/retest
https://github.com/openshift/origin/issues/12072
https://github.com/openshift/origin/issues/16246

**Pull request merged**
