### PR TITLE
Updated gofmt & golint with go1.4

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by smarterclayton** [comment]
Gofmt generates different constraints for 1.4 than 1.3, which means if someone runs gofmt 1.4, then tries to build with 1.3, it will fail.

**Comment by soltysh** [comment]
@smarterclayton that makes sense, still I'm pretty sure we want to enable go1.4 (I tripped with this today when working on STI) and eventual error will be caught during travis tests. Can you also point to those differences?

**Comment by nak3** [comment]
FYI, but Kuberenetes has already included it.
https://github.com/GoogleCloudPlatform/kubernetes/pull/4663/files

**Comment by smarterclayton** [comment]
Covered by #2006

**Pull request closed without merging**
