### PR TITLE
add required field to sample templates

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@spadgett ptal.
[test]

**Comment by spadgett** [comment]
Should `ADMIN_USERNAME` and `ADMIN_PASSWORD` in ruby hello world be required as well?

**Comment by spadgett** [comment]
If we update `application-template-stibuild.json`, should we update the other templates in `examples/sample-app`?

**Comment by bparees** [comment]
> Should ADMIN_USERNAME and ADMIN_PASSWORD in ruby hello world be required as well?

no, they aren't actually used for anything as i recall.  they were for demonstration purposes, the empty value won't hurt anything.

> If we update application-template-stibuild.json, should we update the other templates in examples/sample-app?

i'm not too worried about those, they aren't well publicized samples.

**Comment by spadgett** [comment]
OK, LGTM

**Comment by bparees** [comment]
[merge]

**Pull request merged**
