### PR TITLE
network: add runtime-changeable log levels

### PR DESCRIPTION
**Pull request by dcbw**
Via SIGUSR1, looping between 1 and 6, but starting at 6 the first
time you USR1 either master or node.

@openshift/networking @openshift/sig-networking @squeed @knobunc @danwinship

### CODE REVIEW

**Comment by danwinship** [comment]
So is there any standard for this between different components, and if not, should there be?

**Comment by squeed** [comment]
Seems good for debugging, but I wonder if there's a way to roll this out in a more automated way?

ConfigMap changes, for example, are applied to the pod(s) in question without a restart. We could define a logging configuration file, write it as a config map, then watch that file for changes. Then the operator (or an end user) could just update the contents of that file to enable verbose logging.

This is starting to look a lot like javalog :-).

**Comment by dcbw** [comment]
@danwinship AFAIK there isn't a standard because we don't have logfile options for all of our command-line options, because the logging CLI options are glog and not OpenShift. Not a bad idea though.

 @squeed do we need broader agreement from OpenShift then on what this logging config file would look like? It could also be CRD too.

But one big point of having this *not* in a configmap that's global to the daemonset is that we usually want debugging on a specific node, not cluster-wide. It can heavily impact disk usage and performance on the node so should be scoped appropriately. Can we do that using a configmap for a specific node?

**Comment by squeed** [comment]
Ah, good point re: cluster-wide logging load. 

There isn't an easy way to set a configmap on a per-node basis. The easiest thing I can think of is to include the NodeName in the logging configuration. Defining loglevels as a CRD could also work.

I wonder if other people have thought about this.

**Comment by smarterclayton** [comment]
I'd really like to make this a more specific debug endpoint that you connect to, like cockroachdb' s log spy.  That's a more focused solution (connect, stream logs at a high level).

**Comment by dcbw** [comment]
@smarterclayton or like Kubelet's debuglog server?

**Comment by smarterclayton** [comment]
you mean `/logs/`?  cockroach's log spy is an endpoint you hit that streams higher level trace to you on request and then when you disconnect, stops.  So it's a better citizen.

We really need the "/debug/" drop in endpoint that is auth protected so everyone has the right stuff (profiling, logs, etc)

**Comment by dcbw** [comment]
> you mean `/logs/`? cockroach's log spy is an endpoint you hit that streams higher level trace to you on request and then when you disconnect, stops. So it's a better citizen.
> 
> We really need the "/debug/" drop in endpoint that is auth protected so everyone has the right stuff (profiling, logs, etc)

@smarterclayton yes, please! Would add that to all the network stuff in a heartbeat.

**Pull request closed without merging**
