### PR TITLE
Upstream picks

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@danmcp more infrastructure flakes:
```
==> openshiftdev: Waiting for instance to become "ready"...
==> openshiftdev: Instance is not created. Please run `vagrant up` first.
The instance never became "ready" in AWS. The timeout currently
set waiting for the instance to become ready is 240 seconds.
Please verify that the machine properly boots. If you need more time
set the `instance_ready_timeout` configuration on the AWS provider.
Build step 'Execute shell' marked build as failure
```
and
```
==> openshiftdev:  -- Assigning a public IP address in a VPC: false
There was an error talking to AWS. The error message is shown
below:

InternalError => An internal error has occurred
```
re[test]

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton for review

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
