### PR TITLE
UPSTREAM: 28234: Make sure --record=false is acknowledged when passed to commands

### PR DESCRIPTION
**Pull request by damemi**
Cherry-pick of upstream commit:

Ensures that when --record=false is explicity set that no ChangeCauseAnnotations are set on the object. Previously, if --record=true was used then all following actions triggered a ChangeCauseAnnotation even if --record=false was set, due to the prior ChangeCauseAnnotation existing.

Reference to bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1351127

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@damemi rebase needed (FAILURE: Generated docs up to date, but generated man pages out of date. Please run hack/update-generated-docs.sh)

**Comment by ncdc** [comment]
@smarterclayton when can we get generated docs etc out of the repo? Rebasing for an error like this shouldn't be necessary.

**Comment by smarterclayton** [comment]
It's probably pretty far down the priority list.

**Comment by pweil-** [comment]
flakes https://github.com/openshift/origin/issues/10002 https://github.com/openshift/origin/issues/9548 https://github.com/openshift/origin/issues/9490

re[test]

**Comment by pweil-** [comment]
@ncdc were you ok with this one merging?  Tests are green.

**Comment by ncdc** [comment]
LGTM [merge]

**Pull request merged**
