### PR TITLE
OCPBUGS-7833: Fix pattern match for snapshot tests

### PR DESCRIPTION
**Pull request by jsafrane**
Round brackets must be escaped in regular expressions.

cc @openshift/storage 

I will rework the matching rules in a subsequent PR, I don't like matching exact test names that may break when upstream test is renamed or a new one is added.

### CODE REVIEW

**Comment by jsafrane** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-ovn-no-capabilities

**Comment by bparees** [comment]
/approve

we only need one of either this PR or https://github.com/openshift/origin/pull/27746 though

**Comment by jsafrane** [comment]
/close
in favor of https://github.com/openshift/origin/pull/27745

**Pull request closed without merging**
