### PR TITLE
cmd: set user-agent for openshift apiserver and controller manager

### PR DESCRIPTION
**Pull request by mfojtik**
The goal is to distinguish between openshift-apiserver and openshift-controller from other components that are today reported in prometheus as `hypershift`.

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k added carry as requested, please check if I plumbed all the places.

**Comment by mfojtik** [comment]
/hold

I will try to rework this to plumb the https://github.com/mfojtik/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/config.go#L303 to use the cobra.Command or something to make this sane.

**Comment by soltysh** [comment]
> I will try to rework this to plumb the https://github.com/mfojtik/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/config.go#L303 to use the cobra.Command or something to make this sane.

When doing so, have a look at the patterns we use in https://github.com/openshift/origin/blob/master/pkg/oc/cli/shim_kubectl.go and maybe go similar path with `DefaultKubernetesUserAgent`

**Comment by mfojtik** [comment]
closing, see: 
https://github.com/openshift/origin/pull/22033

**Pull request closed without merging**
