### PR TITLE
bump(github.com/openshift/source-to-image): c99ef8b29e94bdaf62d5d5aefa74d12af6d37e3c

### PR DESCRIPTION
**Pull request by bparees**
makes https://github.com/openshift/origin/issues/8737 debuggable.

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @mfojtik ptal

**Comment by mfojtik** [comment]
LGTM (also introduces changes to volume mounting which should not affect origin and some refactoring from Slava)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@mfojtik needs re-review, i had to update origin due to the injection/volume type renames.  (see 2nd commit)

**Pull request merged**
