### PR TITLE
Allow POST access to node stats for cluster-reader and system:node-reader

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://github.com/openshift/origin/issues/5041

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL
@jimmidyson fyi

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by jimmidyson** [comment]
fwiw lgtm

**Comment by liggitt** [comment]
flake: https://github.com/openshift/origin/issues/5056

**Pull request merged**
