### PR TITLE
Fix router test flakes

### LINKED ISSUE #6797: TestRouterHealthzEndpoint is flaking
```
Running TestRouterHealthzEndpoint...
failed  TestRouterHealthzEndpoint
I0122 13:31:36.235788    3961 plugins.go:60] Registered admission plugin "SecurityContextConstraint"
I0122 13:31:36.235888    3961 plugins.go:60] Registered admission plugin "SCCExecRestrictions"
I0122 13:31:36.235901    3961 plugins.go:60] Registered admission plugin "OriginPodNodeEnvironment"
I0122 13:31:36.235909    3961 plugins.go:60] Registered admission plugin "OriginNamespaceLifecycle"
I0122 13:31:36.235915    3961 plugins.go:60] Registered admission plugin "BuildByStrategy"
Started, serving at 172.18.3.223:8080
Started, serving at 172.18.3.223:8888
Started, serving at 172.18.3.223:8889
Started, serving TLS at 172.18.3.223:8443
Stopping listener at 172.18.3.223:8080
Stopping listener at 172.18.3.223:8888
Stopping listener at 172.18.3.223:8889
Stopping listener at 172.18.3.223:8443
Server message: accept tcp 172.18.3.223:8080: use of closed network connectionStopping listener at 172.18.3.223:8080
Stopping listener at 172.18.3.223:8888
Stopping listener at 172.18.3.223:8889
Stopping listener at 172.18.3.223:8443
Server message: accept tcp 172.18.3.223:8888: use of closed network connectionStopping listener at 172.18.3.223:8080
Stopping listener at 172.18.3.223:8888
Stopping listener at 172.18.3.223:8889
Stopping listener at 172.18.3.223:8443
Server message: accept tcp 172.18.3.223:8889: use of closed network connectionStopping listener at 172.18.3.223:8080
Stopping listener at 172.18.3.223:8888
Stopping listener at 172.18.3.223:8889
Stopping listener at 172.18.3.223:8443
Server message: accept tcp 172.18.3.223:8443: use of closed network connection--- FAIL: TestRouterHealthzEndpoint-2 (31.09s)
	router_test.go:889: Test with "stats port enabled" unable to verify response: Get http://127.0.0.1:1936/healthz: dial tcp 127.0.0.1:1936: connection refused
	router_test.go:893: TestRouterHealthzEndpoint with "stats port enabled" failed! No Response body.
FAIL
[INFO] Dumping etcd contents to /tmp/openshift/test-integration//artifacts/TestRouterHealthzEndpoint-etcd_dump.json
```

### PR DESCRIPTION
**Pull request by ramr**
Some fixes due to some refactoring done. The probe needs an initial delay to allow the router to 
start up + harden the tests a lil' more by waiting for the router to come up and become available.

Fixes #6797 

@smarterclayton  PTAL Thx

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge] thanks

**Comment by ramr** [comment]
rebased with coalesce changes and reapplied the fixes in this PR.

**Comment by smarterclayton** [comment]
Raft flake, [merge]

**Comment by liggitt** [comment]
Same "failed to propose"? I thought we had those beat...

**Comment by smarterclayton** [comment]
Might be different - or we could be writing more to disk now.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
