### PR TITLE
UPSTREAM: 47731: Use endpoints informer for the endpoint controller. 

### LINKED ISSUE #14710: Endpoints controller is dumb
On 3.5 It looks like it's refreshing every 30s, and it's doing a live GET before update, and somehow we're generating 100 GET calls / second on a set of 10k endpoints.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr 

Fixes #14710

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

FYI @smarterclayton @liggitt @eparis

**Comment by aveshagarwal** [comment]
@stevekuznetsov prow seems to be working extra hard on its first day, and insisting for approval every few minutes.

**Comment by aveshagarwal** [comment]
As prow asked: /assign @smarterclayton

**Comment by stevekuznetsov** [comment]
@aveshagarwal yeah, we found a bug in the approval code upstream -- considering a fix or rolling back that feature for now

**Comment by aveshagarwal** [comment]
Its been taken care in https://github.com/openshift/origin/pull/16575 so closing this.

**Pull request closed without merging**
