### PR TITLE
extended: add readiness test for initial deployments

### PR DESCRIPTION
**Pull request by kargakis**
Closes https://github.com/openshift/origin/issues/9752

@mfojtik

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM (post-1.3.0)

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/10487 [test]

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
