### PR TITLE
`env_file` option of docker-compose supported

### LINKED ISSUE #9082: Unable to use 'env_file' with `oc import docker-compose -f ...`
Hi,

I am using this [docker-compose.yaml](https://gist.github.com/containscafeine/77730e682f3c3a0a7dba2dd8731f5c9c) file, which has one of the services using `env_file` like this:

```yaml
  frontend:
    build: ./frontend/.
    links:
    - hello
    ports:
    - "80:8080"
    labels:
    - "app=frontend"
    - "hystrix.enabled:true"
    env_file:
    - msa_env
```

`oc import docker-compose -f docker-compose.yaml` errors out because apparently `env_file` is not yet supported.

##### Version
```bash
oc v1.3.0-alpha.1-20-g30f598e-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
```

##### Current Result
```bash
[root@localhost redhat-helloworld-msa]# oc import docker-compose -f docker-compose-subs.yaml 
ERRO[0000] Failed to parse service frontend: Can not use env_file in file /root/redhat-helloworld-msa/docker-compose-subs.yaml no mechanism provided to load files 
E0530 08:26:08.295448   10051 project.go:129] Could not parse config for project redhat-helloworld-msa : Can not use env_file in file /root/redhat-helloworld-msa/docker-compose-subs.yaml no mechanism provided to load files
error: Can not use env_file in file /root/redhat-helloworld-msa/docker-compose-subs.yaml no mechanism provided to load files
```
##### Expected Result
The environment variables mentioned in the file at `env_file`, should be passed to the specified service.

### PR DESCRIPTION
**Pull request by surajssd**
Now user can add `env_file` in the docker-compose file and it will work with `oc import docker-compose`.

Fixes #9082

### CODE REVIEW

**Comment by smarterclayton** [comment]
Lgtm, [merge] thanks

**Comment by smarterclayton** [comment]
[merge] extended test failure due to docker crash

**Comment by smarterclayton** [comment]
[test] secret unmount flake

**Comment by smarterclayton** [comment]
[test] Secret unmount flake

**Comment by smarterclayton** [comment]
[test] conformance hang

**Comment by smarterclayton** [comment]
[test] conformance runs forever

**Comment by stevekuznetsov** [comment]
re[test]
re[merge]

**Pull request merged**
