### PR TITLE
registry: reenable logstash formatter

### LINKED ISSUE #15296: fix BREAK logstash formatting
The rebase broke `BREAK logstash formatting` in `pkg/cmd/dockerregistry/dockerregistry.go` because of version mismatches.

### PR DESCRIPTION
**Pull request by miminar**
Resolves #15296

### CODE REVIEW

**Comment by miminar** [comment]
@dmage PTAL
@mfojtik FYI

**Comment by miminar** [comment]
[test][testextended][extended:core(ImagePruning)]

**Comment by mfojtik** [comment]
LGTM

/approve

**Comment by miminar** [comment]
Flake #15432. re-[test]

**Comment by miminar** [comment]
Flake #15452 for the extended test. Flake #15453 for the regular test.

**Comment by miminar** [comment]
re-[test]

**Comment by miminar** [comment]
@mfojtik lgty? :)

**Pull request merged**
