### PR TITLE
pkg/oc/cli/admin/release: Add --insecure

### PR DESCRIPTION
**Pull request by wking**
Matching `oc image mirror --insecure`.  This lets callers avoid:

```console
$ podman run -d -p 5000:5000 --name registry docker.io/library/registry
$ oc adm release mirror --from=registry.svc.ci.openshift.org/openshift/origin-release:v4.0 --to localhost:5000/openshift-v4.0
info: Mirroring 79 images to localhost:5000/openshift-v4.0 ...

error: unable to connect to localhost:5000/openshift-v4.0: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
...
error: unable to connect to localhost:5000/openshift-v4.0: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
error: an error occurred during planning
```

when the local registry only speaks HTTP.

Ideally we could turn this off only for pushes, allowing us to pull from a remote registry over HTTPS but push to the local registry over HTTP.  But `oc image mirror` doesn't seem to support that level of granularity.  And even though the coarse `--insecure` allows access over HTTP, we should still be using HTTPS where possible, so the risk of leaking secrets from a properly-configured registry is small.  Although maybe there are increased man-in-the-middle risks?  I'm not entirely clear on whether `--insecure` weakens our "acceptable" HTTPS quality as well (like `curl --insecure`), or if it's just limited to the documented "allow HTTPS too".

CC @smarterclayton.

### CODE REVIEW

**Comment by wking** [comment]
On the other hand, this may not be much use unless we can talk the cluster into pulling over HTTP.  Launching a cluster based on an image mirrored to an insecure registry is giving me errors like:

```console
[core@wking-bootstrap ~]$ journalctl -f
...
Oct 16 05:26:40 wking-bootstrap bootkube.sh[1350]: Trying to pull 192.168.122.1:5000/openshift-v4.0:release...Failed
Oct 16 05:26:40 wking-bootstrap bootkube.sh[1350]: unable to pull 192.168.122.1:5000/openshift-v4.0:release: unable to pull image: Error determining manifest MIME type for docker://192.168.122.1:5000/openshift-v4.0:release: pinging docker registry returned: Get https://192.168.122.1:5000/v2/: http: server gave HTTP response to HTTPS client
...
```

**Comment by wking** [comment]
> On the other hand, this may not be much use unless we can talk the cluster into pulling over HTTP. 

CRI-O's docs [have][1]:

> Enabling `--insecure-registry` is useful when running a local registry. However, because its use creates security vulnerabilities, **it should ONLY be enabled for testing purposes**. For increased security, users should add their CA to their system's list of trusted CAs instead of using `--insecure-registry`.

So while this PR may be useful for consistency with `oc image mirror`, it's probably not very useful for the local-registry case.  I've opened a very-WIP openshift/installer#472 as part of supporting a local registry with a self-signed cert.

[1]: https://github.com/kubernetes-sigs/cri-o/blame/v1.11.6/docs/crio.8.md#L85

**Comment by smarterclayton** [comment]
The intention is that all "docker registry" modifier security related flags would be on all `oc image` and all relevant `oc adm release` commands.

**Comment by smarterclayton** [comment]
You need to run hack/update-generated-completions.sh

**Comment by wking** [comment]
> You need to run hack/update-generated-completions.sh

Done with 2bb9c08 -> 7524633.

**Comment by wking** [comment]
[Unit][1] (and basically everyone I checked) died with:

```
E1016 20:44:24.147738      11 event.go:209] Unable to write event: 'Post https://172.30.0.1:443/api/v1/namespaces/ci-op-n4ibmm3g/events: dial tcp 172.30.0.1:443: connect: connection refused' (may retry after sleeping)
2018/10/16 20:44:25 Ran for 3m23s
error: could not run steps: could not wait for build: could not list builds: Get https://172.30.0.1:443/apis/build.openshift.io/v1/namespaces/ci-op-n4ibmm3g/builds?fieldSelector=metadata.name%3Dsrc: dial tcp 172.30.0.1:443: connect: connection refused
```

Looking at [the unit history][2], I'm just very unlucky ;).

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21266/pull-ci-openshift-origin-master-unit/493/build-log.txt
[2]: https://deck-ci.svc.ci.openshift.org/?repo=openshift%2Forigin&job=pull-ci-openshift-origin-master-unit

**Comment by flaper87** [comment]
@wking can we do this for the `new` subcommand too? When creating a new release, the command fails to talk to a registry that has a self-signed certificate.

**Comment by wking** [comment]
> can we do this for the `new` subcommand too?

Done (and rebased onto master) with 7524633 -> 4fd4121.

**Comment by flaper87** [comment]
I don't know why the `ci/prow/cmd` job is stuck

**Comment by soltysh** [comment]
> I don't know why the `ci/prow/cmd` job is stuck

Stuff has changed in the mean time, re-testing should solve the problem :wink:

**Comment by flaper87** [comment]
The `oc adm release new --insecure` works when pushing new images but it fails when I try to overwrite some of the images in the release:

This command fails with: `Unable to connect to the server: x509: certificate signed by unknown authority`

```
oc adm release new -n openshift machine-config-operator=10.1.8.88:8787/openshift/machine-config-operator:latest  --from-image-stream=origin-v4.0 --to-image=10.1.8.88:8787/shiftstack/origin-release:v4.0
```

Whereas this one works:

```oc adm release new -n  --from-image-stream=origin-v4.0 --to-image=10.1.8.88:8787/shiftstack/origin-release:v4.0```

**Comment by cgwalters** [comment]
I didn't know this PR existed and started on it in https://github.com/openshift/machine-config-operator/pull/496#issuecomment-467619085 too

One higher level question though; how hard/hacky would it be to use the cluster CA from the active `KUBECONFIG`?

**Comment by wking** [comment]
> One higher level question though; how hard/hacky would it be to use the cluster CA from the active `KUBECONFIG`?

For the registry access?  I'd have expected that was already happening for registries that belong to the cluster (e.g. via [this][1]).  Is it not?

I've pushed  4fd4121be8 -> 1607ad7d15, rebasing onto master and addressing (I think) @flaper87's [`ExtractOptions.Insecure` suggestion][1].

[1]: https://github.com/openshift/origin/pull/21266#pullrequestreview-177547267

[1]: https://github.com/openshift/origin/blob/b70b342c5623d11a0f31d0e962beca6b6f4b6c25/pkg/oc/cli/admin/release/new.go#L208-L212

**Comment by cgwalters** [comment]
I still need this PR for https://github.com/openshift/machine-config-operator/pull/496

**Pull request closed without merging**
