### PR TITLE
Allow basic users to 'get' StorageClasses

### PR DESCRIPTION
**Pull request by wongma7**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449608

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by wongma7** [comment]
[test]

**Comment by wongma7** [comment]
[test]

https://github.com/openshift/origin/issues/13943

**Comment by childsb** [comment]
[merge][severity:blocker]

**Comment by wongma7** [comment]
Running hack/test-util.sh:354: executing 'current_time_millis_mod_1000' expecting any result and text 'typo'; re-trying every 0.2s until completion or 1.000s...
FAILURE after 0.217s: hack/test-util.sh:354: executing 'current_time_millis_mod_1000' expecting any result and text 'typo'; re-trying every 0.2s until completion or 1.000s: the command timed out
Standard output from the command:
success
Standard error from the command:

**Comment by childsb** [comment]
[merge][severity:blocker]

**Pull request merged**
