### PR TITLE
UPSTREAM: openshift/source-to-image: 584: fix WaitGroup usage in Execute

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @liggitt ptal

this is new pull for the s2i upstream patch that
- based off of the 1.3 branch
- pulled in the suggestion from @liggit that has been merged into s2i

Unless @bparees says otherwise, we'll wait for the s2i bump into 1.4 to update master.

### CODE REVIEW

**Comment by bparees** [comment]
this lgtm, we'll also need a PR against ose's 3.3 branch to get it into 3.3.1.

@danmcp @smarterclayton I don't know the controls on merges to 1.3.1, am i free to merge this?

**Comment by gabemontero** [comment]
fyi the ose pr is https://github.com/openshift/ose/pull/372

**Comment by gabemontero** [comment]
@bparees @smarterclayton @danmcp bump / is 1.3.1 open?

fwiw, the ose 3.3.1 version of this has been merged and verified by QE.

**Comment by gabemontero** [comment]
@bparees are we still interested in getting this fix into 1.3 ?

**Pull request closed without merging**
