### PR TITLE
Fix 404 error in Jenkins plugin extended tests

### LINKED ISSUE #12383: [test][extended] openshift pipeline plugin returns 404
Not sure what's causing this, so i'm opening ~a temporary~ an issue.
The openshift pipeline plugin extended tests are returning 404.
See https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/807/

logs:
https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/807/consoleFull#40473246556cbb9a5e4b02b88ae8c2f77

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #12383

### CODE REVIEW

**Comment by csrwng** [comment]
[testextended][extended:core(openshift pipeline plugin)]

**Comment by csrwng** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
LGTM

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
