### PR TITLE
Fixup router test hostnames 

### PR DESCRIPTION
**Pull request by ramr**
fixup tests - good catch @Miciah

@Miciah @rajatchopra  PTAL   Thx

### CODE REVIEW

**Comment by rajatchopra** [comment]
Done to preserve the certs, right?
LGTM

**Comment by ramr** [comment]
Yeah quick fix to preserve the certs for now. Maybe generate a different set later.

**Comment by rajatchopra** [comment]
[merge]

**Comment by rajatchopra** [comment]
flaky failure. re [merge]

**Pull request merged**
