### PR TITLE
[Release-3.11] Bug 1881133: haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant

### PR DESCRIPTION
**Pull request by sgreene570**
This is the 3.11 backport of https://github.com/openshift/router/pull/140 as per https://bugzilla.redhat.com/show_bug.cgi?id=1881133. This change is a whitespace only change. 

---

rfc2616 and rfc7230 both demand that in HTTP messages lines be ended with CRLF.
Although both RFCs stipulate that LF-only line endings MAY or even SHOULD be accepted, It's better to be fully compliant. Very picky HTTP clients, such as web access firewalls, may trip over this and blame Openshift's router.
This PR is whitespace-only and converts all LF line terminators in this file to CRLF.

### CODE REVIEW

**Comment by sgreene570** [comment]
unit tests are known flakey on 3.11 right now
@knobunc could you review and tag this PR when you get the chance?

**Comment by simonkrenger** [comment]
@knobunc any updates on this PR?

**Comment by frobware** [comment]
> unit tests are known flakey on 3.11 right now

3.11 related BZs to address the flakes are:

- https://bugzilla.redhat.com/show_bug.cgi?id=1879445
- https://bugzilla.redhat.com/show_bug.cgi?id=1890328

**Pull request merged**
