### PR TITLE
Validate CSRF in external oauth flow

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k review

**Comment by deads2k** [comment]
I don't know a lot about cookies, but it seems like if we now require them to login we ought to let someone know....

Otherwise looks fine.

**Comment by liggitt** [comment]
Login page already used cookies for csrf. Session uses cookie-based storage as well. I'll add a follow-up on my list to detect when cookies are disabled and display a message instead of just looping

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
> I don't know a lot about cookies

Cookies are delicious delicacies

**Pull request merged**
