### PR TITLE
Rebase Kubernetes onto 0.12

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@soltysh @mfojtik can one of you investigate this in the morning - it looks like either the redirector on build logs or on pod logs has changed, and now build logs rest is broken (double setting the response).

```
ruby-sample-build-c9a03552-ceb0-11e4-8e9b-080027c5bfa9   STI                 Complete            build-ruby-sample-build-c9a03552-ceb0-11e4-8e9b-080027c5bfa9
[INFO] Success running command: 'osc get -n test builds | grep -i complete' after 258 seconds
[INFO] Build ruby-sample-build-c9a03552-ceb0-11e4-8e9b-080027c5bfa9 finished
F0320 03:30:02.702779    3919 buildlogs.go:41] Get http://http:/127.0.0.1:10250/containerLogs/test/build-ruby-sample-build-c9a03552-ceb0-11e4-8e9b-080027c5bfa9/sti-build: dial tcp: lookup http: no such host
```

**Comment by soltysh** [comment]
I'll have a look at it right after planning.

**Comment by soltysh** [comment]
@smarterclayton fixed in https://github.com/smarterclayton/origin/pull/9 With this I found that upstream adds currently `http://` by default in the redirector (see [here](https://github.com/smarterclayton/origin/blob/rebase_kube/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/redirect.go#L89)) but they didn't (see [here](https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/redirect.go#L88))
It's flaky IMHO, they should allow you to set the Scheme for yourself, don't you think?

**Comment by smarterclayton** [comment]
@liggitt owns making this work upstream because he's about to update the proxy to be secure to the backend (which is broken today in their model).

Thanks for the fix.

----- Original Message -----

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
