### PR TITLE
add newline to login output

### PR DESCRIPTION
**Pull request by deads2k**
Output was missing a newline and it annoyed me.

### CODE REVIEW

**Comment by deads2k** [comment]
@juanvallejo @fabianofranz

**Comment by juanvallejo** [comment]
LGTM

**Comment by deads2k** [comment]
@mfojtik what are the merge rules at the moment?

**Comment by mfojtik** [comment]
@deads2k bug fixes only AFAIK, I think this sort-of qualifies and seems minor risk :)

[merge]

**Comment by imcsk8** [comment]
LGTM

**Comment by smarterclayton** [comment]
The merge rules are horribly ugly missing newlines get merged ASAP.

**Pull request merged**
