### PR TITLE
db-templates: mongodb ephemeral dc should automatically resolve

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton @php-coder @bparees 

Fixes https://github.com/openshift/origin/issues/8367

Got it working on https://github.com/openshift/origin/pull/8746 but I think there is no difference on master.

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by bparees** [comment]
ew :(

and why was this only causing intermittent failures?

**Comment by kargakis** [comment]
Hm, I looked into why `automatic: false` wasn't respected every now and then and here is my theory:

When `automatic: true`, then everything will be smooth for you (probably). Since it's `false`, the image change controller will never cooperate with you. BUT the config change controller happens to use the same  [generator](https://github.com/openshift/origin/blob/6c6a0dc59bbf825191478bb86ba77a7d691acbf2/pkg/deploy/generator/config_generator.go#L25) which 1) resolves images and 2) doesn't care about `automatic`. Now since the mongodb image is imported, the time it will land varies. If it's fast (as being imported before the dc is created), then the config change controller by using the underlying [generator](https://github.com/openshift/origin/blob/6c6a0dc59bbf825191478bb86ba77a7d691acbf2/pkg/deploy/controller/configchange/controller.go#L45) will update the image. If it's slow, then the deployment will timeout eventually. Note that this is not a feature but one of the many bugs that come along with the generator:) #8746 fixes this once and for ever. For the extended test, setting automatic to true should be enough for now.

**Comment by kargakis** [comment]
cc: @ironcladlou

**Comment by smarterclayton** [comment]
Agree with your comment @kargakis - agree that if you don't set automatic: true you get what you deserve.  We could *maybe* hold the first deployment if the image field was empty and it had a trigger that had not resolved.

**Comment by kargakis** [comment]
> We could maybe hold the first deployment if the image field was empty and it had a trigger that had not resolved.

That's what I am doing in #8746. I thought that was what we always wanted to achieve but the current trigger controllers assume that images will land *after* the deploymentconfig is created and not before.

**Comment by kargakis** [comment]
[merge]

**Pull request merged**
