### PR TITLE
Prevent panic in import-image

### PR DESCRIPTION
**Pull request by smarterclayton**
Also format the errors from the server more accurately to convey error
information from the server.

@ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
What was the panic?

**Comment by smarterclayton** [comment]
stream was nil because err was returned.

On Tue, Aug 25, 2015 at 3:31 PM, Andy Goldstein <notifications@github.com>
wrote:

> What was the panic?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4366#issuecomment-134694800>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
LGTM

**Comment by smarterclayton** [comment]
[merge]

On Tue, Aug 25, 2015 at 4:29 PM, Andy Goldstein <notifications@github.com>
wrote:

> LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4366#issuecomment-134709012>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
