### PR TITLE
Don't use "kexec" as both a package name and a variable name

### PR DESCRIPTION
**Pull request by danwinship**
leftover nit from #9520, requested by @liggitt 

(we were previously using os/exec in a few places as well, but the interface returned by kexec.New() has the same API as os/exec, so renaming that variable to "exec" makes the os/exec import unnecessary/conflicting)

### CODE REVIEW

**Comment by danwinship** [comment]
@openshift/networking can someone take a look? easy fix

**Comment by pravisankar** [comment]
LGTM

**Comment by pravisankar** [comment]
[merge]

**Comment by pravisankar** [comment]
re[merge]

**Comment by dcbw** [comment]
Seems like a transient error... error: running '/bin/sh -c curl -L -o /etc/yum.repos.d/origin-next-epel-7.repo https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo &&     INSTALL_PKGS="openvswitch" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     chmod +x /usr/local/bin/*' failed with exit code 1

re[merge]

**Comment by danwinship** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7203/ flaked due to #9775, [merge]

**Comment by stevekuznetsov** [comment]
re[merge]

**Comment by dcbw** [comment]
Failure was:

+ vagrant ssh -c 'sudo journalctl --no-pager --all --lines=10000 --unit=docker'
/tmp/hudson3790246935591707680.sh: line 3: origin/artifacts/docker.journal: No such file or directory

**Comment by stevekuznetsov** [comment]
re[merge] -- that was a bad Jenkins job config

**Pull request merged**
