### PR TITLE
adding publishing rules for origin-4.5-kubernetes-1.17.1

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm
/approve

cc @marun

**Comment by marun** [comment]
@sttts How would I know whether the changes from this PR were correct?

**Comment by p0lyn0mial** [comment]
> @sttts How would I know whether the changes from this PR were correct?

@marun you need to check the publishing bot log file - https://api.ci.openshift.org/console/project/origin-publishing-bot/browse/deployment/openshift-kubernetes-bot?tab=history. Checking if there aren't any errors is enough.

@marun  You could also check the individual branches, to see if the changes were propagated. For example, for the previous version (`origin-4.4-kubernetes-1.17.1`) you could check if commits (from the appropriate stating directory) from https://github.com/openshift/kubernetes/tree/origin-4.4-kubernetes-1.17.1 were moved to https://github.com/openshift/kubernetes-client-go/tree/origin-4.4-kubernetes-1.17.1

**Pull request merged**
