### PR TITLE
Headless service targetPort compatibility

### PR DESCRIPTION
**Pull request by liggitt**
Restores validation of service ports to allow 1.0/1.1 targetPorts for headless services

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1309192#c15

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@smarterclayton what do you think?
cc @mwringe @brenton

**Comment by smarterclayton** [comment]
I'm tired of having to deal with breaks caused by tightened validations.  I don't know how this isn't a violation of backwards compatibility.

**Comment by liggitt** [comment]
Can argue it upstream before release

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/21680 upstream to revert the tightened validation

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
upstream has LGTM, [merge]

**Pull request merged**
