### PR TITLE
UPSTREAM: 75110: Send events before adding watchers in traversePluginDir

### PR DESCRIPTION
**Pull request by bertinatto**
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1695329

### CODE REVIEW

**Comment by bertinatto** [comment]
CC @openshift/storage

**Comment by jsafrane** [comment]
/lgtm
from CSI plugin registration POV

**Comment by bertinatto** [comment]
/assign @mfojtik 
for approval

**Pull request merged**
