### PR TITLE
UPSTREAM: 46437: Up namespace controller workers to 5

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
@deads2k @smarterclayton @liggitt FYI

**Comment by derekwaynecarr** [comment]
anticipate this will reduce flakes  [merge][severity: bug]

**Comment by ncdc** [comment]
Fixed master config test.

[merge][severity: bug]

**Comment by ncdc** [comment]
```
+ make test-extended SUITE=networking-minimal
test/extended/networking-minimal.sh 
++ Building go targets for linux/amd64: test/extended/extended.test
hack/build-go.sh took 479 seconds
[INFO] Starting 'networking' extended tests
[INFO] [CLEANUP] Cleaning up temporary directories
[INFO] Building docker-in-docker images
Building container images
Sending build context to Docker daemon  38.4 kB

Error response from daemon: Untar error on re-exec cmd: fork/exec /proc/self/exe: cannot allocate memory
[ERROR] PID 25977: hack/dind-cluster.sh:276: `${DOCKER_CMD} build -t "${image_name}" .` exited with status 1.
```

[test]

**Comment by smarterclayton** [comment]
The dind flake has been happening all day

On May 25, 2017, at 4:32 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test SUCCESS (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1776/)
(Base Commit: 4b3473a
<https://github.com/openshift/origin/commit/4b3473a110176fde9acb7fe393f6683cd47220e4>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/14352#issuecomment-304116146>,
or mute
the thread

**Pull request merged**
