### PR TITLE
Support Mulit-Arch Builds

### PR DESCRIPTION
**Pull request by jeffdyoung**
Same as https://github.com/openshift/origin/pull/22410

@sdodson

### CODE REVIEW

**Comment by jeffdyoung** [comment]
@sdodson All good now. Sorry for the 2nd PR.

**Comment by jichenjc** [comment]
@jeffdyoung could you please let me know whether this PR means we can build openshift on different platform (other than x86, but like arm , ppc ) etc? and will this PR enables master node running on x86 while worker node on other platform? (from code I assume not , can you help to confirm?) thanks 

FYI @bjhuangr

**Comment by jeffdyoung** [comment]
Hey @jichenjc. Yes, this will enable you to build the 4.2 containers on other archs. Unfortunately, this will not enable a mixed-arch cluster. There would be quite a bit of work for the 4.x release container, coreos, and the installer to make that happen.

For building 3.11 you can look at this repo:
https://github.com/multi-arch/openshift-fedora

We had re-based 3.11 from centos7 to fedora29 in order to support s390x. There is still work to be done with those scripts, but we've had to shift focus to delivering OCP 4.2 on power. 

Lastly, I'm leaving redhat.  @ausil, @andymcc will be continuing the openshift multi-arch work.

HTH

Jeff

**Comment by jichenjc** [comment]
hi @jeffdyoung , appreciate the info and understood it might take a lot of work to enable 4.x, so just want to double check and wish you good luck :)

**Comment by DanyC97** [comment]
@ausil fyi in case you were not aware of (just bumped into)

**Pull request merged**
