### PR TITLE
switch new project example repo to one that doesn't need a db

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/ruby-hello-world/issues/54

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal (for post 3.2)

**Comment by smarterclayton** [comment]
LGTM for post 1.2.

**Comment by smarterclayton** [comment]
You need to generate docs for this

**Comment by bparees** [comment]
thanks, done.

**Comment by bparees** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
