### PR TITLE
context.Context should be the first parameter of a function

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by legionus** [comment]
@YuPengZTE  Please explain why you need these changes ?

**Comment by YuPengZTE** [comment]
@legionus 
Context variables need to be used as the first parameter, generally named ctx.
When golint with https://github.com/golang/lint/commit/3390df4df2787994aea98de825b964ac7944b817,
the reslut show "context.Context should be the first parameter of a function"

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
@mfojtik merge please

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
