### PR TITLE
deploy: verify the deployer SA has perms to update tags

### PR DESCRIPTION
**Pull request by mfojtik**
fixes: https://github.com/openshift/origin/issues/10663

[test]

### CODE REVIEW

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge][severity:bug] this is a test flake fix, isolated in extended tests.

**Comment by tnozicka** [comment]
(re-applying for the new bot)
/lgtm
/approve

**Comment by tnozicka** [comment]
we are in DCUT and the new bot might not force it (although it should...)
/approve cancel

**Comment by tnozicka** [comment]
queue is stupid:
/lgmt cancel

**Pull request merged**
