### PR TITLE
suggest using default cluster port on internal server error

### PR DESCRIPTION
**Pull request by juanvallejo**
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1406066

This patch suggests using the default cluster port with the current host
used by a client, if the current port does not match the default port,
and the client receives an internal / unknown error from the server.

**Example**
```
$ oc login --server=https://10.13.137.149:8444 -u system:admin
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: Internal error occurred: unexpected response: 503
You may want to try using the default cluster port: https://10.13.137.149:8443
```

cc @openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by smarterclayton** [comment]
When does this happen?

**Comment by smarterclayton** [comment]
it's unlikely 503 means "use another port" in most setups.  It's more likely to mean "all servers are down".

I would replace both lines with a message like "error: The server was unable to respond - verify you have provided the correct host and port and that the server is currently running."

**Comment by juanvallejo** [comment]
@smarterclayton 
> When does this happen?

It happens when a client attempts to connect to a non-default (non-8443) open port and receives an error, as well as when a client attempts to connect to a non-default closed port. We were already suggesting that users try using the default cluster port if the client attempted to connect to a closed port.

> I would replace both lines with a message like "error: The server was unable to respond - verify you have provided the correct host and port and that the server is currently running."

Thanks, I have updated the error message to this one whenever a client attempts to connect to any open port and receives an error. Should this be the case as well for closed ports?

**Comment by smarterclayton** [comment]
I don't think we should suggest the default cluster port.  No OpenShift
installation I'm aware of except oc cluster up would use that port.

**Comment by juanvallejo** [comment]
@smarterclayton 
> I don't think we should suggest the default cluster port.  No OpenShift
installation I'm aware of except oc cluster up would use that port.

Okay, updated the last commit to return `error: The server was unable to respond - verify you have provided the correct host and port and that the server is currently running.` both when a client tries to log in to a closed port, and when it tries to log in to an open port but receives an internal / unknown error.

**Comment by juanvallejo** [comment]
conformance flaked on https://github.com/openshift/origin/issues/11775 re[test]

**Comment by juanvallejo** [comment]
@smarterclayton are there any further comments on this patch? Thanks!

**Comment by juanvallejo** [comment]
cc @fabianofranz

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
