### PR TITLE
Rebase onto latest Kubernetes

### PR DESCRIPTION
**Pull request by smarterclayton**
[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by derekwaynecarr** [comment]
Woo hoo!

**Comment by derekwaynecarr** [comment]
I looked in the branch and did not see it, but can we make sure we pull over all the contents in plugins directory for Kubernetes?  Specifically, all of the admission control plugins.

**Comment by smarterclayton** [comment]
You'll need something that imports them.

**Comment by derekwaynecarr** [comment]
I am admittedly ignorant on the process here, is there a pointer to a doc that says, hey you are trying to use a new part of kube, this is the process?

**Comment by smarterclayton** [comment]
https://github.com/tools/godep#add-a-dependency is all you should need to do

**Comment by smarterclayton** [comment]
@pweil- you're on deck - there's a comment about namespacing of routes not being fully implemented yet.  Are you only watching (intending to watch) the default namespace?

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge] while the iron is hot

**Pull request merged**
