### PR TITLE
Bug 1646886: bump cadvisor

### LINKED ISSUE #23492: Missing network metrics from cadvisor after some time
Hi,

I'm using okd 3.11 with cri-o. After some uptime of origin-node, cadvisor doesn't report all network metrics (e.g. `container_network_transmit_packets_total`).

##### Version
I've build own RPMs for Origin and installed this RPM yesterday (25.07.2019) without any changes from branch `release-3.11`. My hope was a possible fix.
```
11:01 $ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://s-openshift.mycompany.com:443
openshift v3.11.0+3b2d3b6-227
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. RSH to Prometheus instance
2. `curl -s -k -H "Authorization: Bearer [My-Token]" https://10.20.15.42:10250/metrics/cadvisor | grep container_network_transmit_packets_total | grep namespace=\"thanos\"`
```
container_network_transmit_packets_total{container_name="POD",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6588346a_aefa_11e9_ab2c_005056945e02.slice/crio-45848b690fe11481394b28c108b1fb25f31c5aaa41ff93ad4f56c71501dc90b6.scope",image="",interface="eth0",name="k8s_POD_thanos-querier-6d98c99694-dj8hg_thanos_6588346a-aefa-11e9-ab2c-005056945e02_0",namespace="thanos",pod_name="thanos-querier-6d98c99694-dj8hg"} 334942
container_network_transmit_packets_total{container_name="POD",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod69a3dfe5_aefa_11e9_ab2c_005056945e02.slice/crio-d07f32d58bd0b4240685147aa1af32e36f7558684c600a397c99af68a16c40c8.scope",image="",interface="eth0",name="k8s_POD_minio-2_thanos_69a3dfe5-aefa-11e9-ab2c-005056945e02_0",namespace="thanos",pod_name="minio-2"} 2.115004e+06
```
3. wait some time e.g. 5 hours.
4. Again without output `curl -s -k -H "Authorization: Bearer [My-Token]" https://10.20.15.42:10250/metrics/cadvisor | grep container_network_transmit_packets_total | grep namespace=\"thanos\"`

##### Current Result
After some hours network metrics disappear for interface eth0
Network_eth0

##### Expected Result
Stable network metrics from cadvisor.

### PR DESCRIPTION
**Pull request by sjenning**
pull in https://github.com/openshift/google-cadvisor/pull/7

The delta is huge because a `make update-deps` on a clean `origin/master` makes a lot of changes.  I've split up the bump(*) on the clean master into a separate commit.

Fixes #23492

### CODE REVIEW

**Comment by mrunalp** [comment]
ping @derekwaynecarr

**Comment by sjenning** [comment]
gah, didn't realize that e2e-aws-upgrade _normally_ takes 2h30m to pass and I restarted it :man_facepalming:

**Pull request merged**
