### PR TITLE
cAdvisor port is not exposed directly for security reasons so excluding this test.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ncdc

**Comment by ncdc** [comment]
I'm surprised you need to do this. Shouldn't the previous line cover this?

**Comment by aveshagarwal** [comment]
actually when I run "KUBECONFIG=./openshift.local.config/master/admin.kubeconfig extended.test --ginkgo.v=true --ginkgo.skip="" --ginkgo.focus="Conformance", infact both tests are being run, am I doing something run?

**Comment by ncdc** [comment]
I believe this is what @timothysc was referring to when he wrote https://github.com/openshift/origin/pull/10641#issuecomment-242420582.

The file you modified is read by test/extended/core.sh and `--ginkgo.skip` is automatically set up from that file.

I would say that the test invocation from the bz is incorrect.

**Comment by ncdc** [comment]
... incorrect in that it doesn't skip the tests that we know need to be skipped

**Comment by aveshagarwal** [comment]
@ncdc ok I will close it then. Because what you are saying makes sense.

**Pull request closed without merging**
