### PR TITLE
added deterministic identity mapper

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt PTAL

### CODE REVIEW

**Comment by danmcp** [comment]
@liggitt Bump

**Comment by liggitt** [comment]
@stevekuznetsov I'd rather update the existing provision mapper with flags to control behavior when user already exists (fail, uniquify, add, replace). See https://trello.com/c/cSa9BKUL/512-3-configurable-identity-user-provisioning-strategies for the strategies we'd want to support

**Comment by liggitt** [comment]
I'll probably start on those flags in the provisioning mapper next week if you want to table this

**Comment by stevekuznetsov** [comment]
@liggitt Fine to table.

**Pull request closed without merging**
