### PR TITLE
Remove unnecessary type conversions

### PR DESCRIPTION
**Pull request by rhcarvalho**
Small clean up of places where we converted time.Duration into time.Duration.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by bparees** [comment]
lgtm [merge]

**Comment by mfojtik** [comment]
[merge]

**Comment by rhcarvalho** [comment]
NOTFOUND? This is new to me.

**Comment by bparees** [comment]
> NOTFOUND? This is new to me.

I think dan may have rebuilt jenkins yesterday so it probably lost track of something.

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
@rhcarvalho this PR is cursed. [merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
