### PR TITLE
test/extended/prom: use coreos-pull-secret for pullsecret

### PR DESCRIPTION
**Pull request by abhinavdahiya**
The installer already pushes the pull secret to Secret `kube-system/coreos-pull-secret`. This allows installer to redact the pull-secret from the `cluster-config-v1` ConfigMap as ConfigMaps should not have secrets.

installer PR: https://github.com/openshift/installer/pull/1379
cluster-monitoring-operator PR: https://github.com/openshift/cluster-monitoring-operator/pull/286
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1686119

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@smarterclayton @deads2k green CI :)

**Comment by deads2k** [comment]
"should report telemetry if a cloud.openshift.com token is present" is in the pass list, not the skip list

/lgtm

**Pull request merged**
