### PR TITLE
Clarify router cmd ignoreError comments

### LINKED ISSUE #15822: RBAC Migration Followup #10: Fix router ignore error
Fix `ignoreError` in `pkg/oc/admin/router/router.go`

### PR DESCRIPTION
**Pull request by mrogers950**
fixes #15822
@enj @pweil-

### CODE REVIEW

**Comment by enj** [comment]
/lgtm
/test extended_conformance_gce

Test flakes on OOM

**Comment by enj** [comment]
@mrogers950 you will need add the case back:

`error: clusterrolebindings "router-router-role" already exists`

Comment each case with a version identifier.

**Comment by mrogers950** [comment]
> @mrogers950 you will need add the case back:
> 
> error: clusterrolebindings "router-router-role" already exists
> 
> Comment each case with a version identifier.
I'll add it back, but I'd like to know why running 'hack/test-cmd.sh router' locally doesn't show the same failure.

**Comment by enj** [comment]
> I'll add it back, but I'd like to know why running 'hack/test-cmd.sh router' locally doesn't show the same failure.

@mrogers950 the error is based on the code (not) being re-entrant.  Thus it is likely the CI runs code at some earlier point that sets up the router.  Running the code to set up the router a second time is not supposed to fail on the bindings already existing from the first invocation.

**Comment by mrogers950** [comment]
>@mrogers950 the error is based on the code (not) being re-entrant.  Thus it is likely the CI runs code at >some earlier point that sets up the router.  Running the code to set up the router a second time is not >supposed to fail on the bindings already existing from the first invocation.

@enj then that sounds like this is being exercised by a CI side-effect and we should have a test in test/cmd/router.sh that deletes and re-creates the route

**Comment by enj** [comment]
> then that sounds like this is being exercised by a CI side-effect and we should have a test in test/cmd/router.sh that deletes and re-creates the route

@mrogers950 excellent idea.  Please add one (either as part of this PR or a separate one).

**Comment by mrogers950** [comment]
> @mrogers950 excellent idea. Please add one (either as part of this PR or a separate one).

@enj I opened https://github.com/openshift/origin/pull/15940

**Comment by enj** [comment]
/retest

Flaked on #14575

**Pull request merged**
