### PR TITLE
Bug 1949050: k8s 1.21.1

### PR DESCRIPTION
**Pull request by soltysh**
/assign @mfojtik

### CODE REVIEW

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

**Comment by jsafrane** [comment]
/override ci/prow/e2e-aws-csi
Trying to stop retesting this job - is an optional one and we know it's broken.

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-csi 
it's known issue and is being actively worked on by the storage team

**Pull request merged**
