### PR TITLE
check all buildrequest options for validity against build type

### PR DESCRIPTION
**Pull request by bparees**
bug 1541914

https://bugzilla.redhat.com/show_bug.cgi?id=1541914

### CODE REVIEW

**Comment by bparees** [comment]
/unassign @danwinship 
/assign @gabemontero 
@openshift/sig-developer-experience ptal

**Comment by bparees** [comment]
(will backport this to 3.7, 3.6)

**Comment by coreydaley** [comment]
It seems like there should be a better way to do this validation, a list or yaml file based on the valid options for a specific build strategy and compare it to the buildrequest and throw error(s) based upone what is required and what is allowed for each build type.  It just seems like there is a lot of duplication of checking for things and returning very similar error messages, lots of duplicate code that doesn't need to be there and lots of places that things will have to be updated as options change vs updating a couple of lists or yaml files?

**Comment by bparees** [comment]
> But, it is also possible that I am over-thinking this ;)

this one. :)

**Pull request merged**
