### PR TITLE
cluster up: print last 10 lines of logs on errors after container started

### PR DESCRIPTION
**Pull request by csrwng**
improves logging for unexplained errors after server has started

### CODE REVIEW

**Comment by csrwng** [comment]
@gabemontero ptal

**Comment by smarterclayton** [comment]
Sample output?

**Comment by csrwng** [comment]
Sample output:
```
$ oc cluster up
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using nsenter mounter for OpenShift volumes
-- Checking Docker version ... OK
-- Creating volume share ... OK
-- Finding server IP ...
   Using 192.168.64.27 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.64.27:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0609 17:51:32.204655   23441 master.go:269] Started Web Console 0.0.0.0:8443/console/
     I0609 17:51:32.204662   23441 master.go:269] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
     I0609 17:51:32.314069   23441 ensure.go:224] No cluster policy found.  Creating bootstrap policy based on: /var/lib/origin/openshift.local.config/master/policy.json
     I0609 17:51:33.618001   23441 ensure.go:209] Created default security context constraint privileged
     I0609 17:51:33.621442   23441 ensure.go:209] Created default security context constraint nonroot
     I0609 17:51:33.625630   23441 ensure.go:209] Created default security context constraint hostmount-anyuid
     I0609 17:51:33.628949   23441 ensure.go:209] Created default security context constraint hostaccess
     I0609 17:51:33.631646   23441 ensure.go:209] Created default security context constraint restricted
     I0609 17:51:33.634807   23441 ensure.go:209] Created default security context constraint anyuid
     I0609 17:51:33.637186   23441 ensure.go:209] Created default security context constraint hostnetwork
```

**Comment by smarterclayton** [comment]
Is that an actual error or just synthetic?

**Comment by csrwng** [comment]
Just synthetic, to get an actual error is not easy :)

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
