### PR TITLE
Prepare to support loading admission control plugins

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This is the prerequisite to enabling the use of upstream admission control plug-ins in Origin.

We need to use the plug-in manager to load our plug-ins.

The returned admission handler will enforce that admission handlers are invoked in sequence, so after the next re-base, we will be able to just add "LimitRange" and "ResourceQuota" handlers in the array.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
rebased

**Comment by derekwaynecarr** [comment]
rebased.  @jwforres @smarterclayton - can either of you review?

**Comment by jwforres** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
rebased

**Comment by derekwaynecarr** [comment]
Closing this and will send another PR after #1034 is merged.

**Pull request closed without merging**
