### PR TITLE
Implement dynamic provisioners for GCE, AWS and OpenStack/Cinder

### PR DESCRIPTION
**Pull request by jsafrane**
Merge only after https://github.com/openshift/origin/pull/6291 and all the referenced PRs are merged upstream.

It's rebased version of referenced pull requests. I picked only tiny part of PR#17747, just to get `CreateDisk` and `DeleteDisk`.

Upstream PRs:
* https://github.com/kubernetes/kubernetes/pull/18601
* https://github.com/kubernetes/kubernetes/pull/18607
* https://github.com/kubernetes/kubernetes/pull/17747
* https://github.com/kubernetes/kubernetes/pull/18621

### CODE REVIEW

**Comment by jsafrane** [comment]
cc: @markturansky @pmorie

**Comment by jsafrane** [comment]
* Rebased to current version of #6291
* Picked final (=merged) versions of AWS and OpenStack/Cinder patches
* Still waiting for GCE to merge upstream

**Comment by ncdc** [comment]
Looks like this needs rebasing? It's still showing the commits from 6291.

**Comment by pmorie** [comment]
[test]

**Comment by ncdc** [comment]
@pmorie & I tested manually merging locally, as well as rebasing locally. The first 2 commits fall out either way, so this is probably safe to merge.

**Comment by ncdc** [comment]
```
/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 28: openshift: command not found
```

Haven't seen this one in a while...

[test]

**Comment by jsafrane** [comment]
Rebased to master + picked the latest GCE patch from upstream. All patches are merged in Kubernetes now and we should be ready to merge to OpenShift.

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
