### PR TITLE
cli: switch to generated clients (part 1)

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

failures are legit

**Comment by mfojtik** [comment]
@deads2k investigating the deployment log one, seems weird, like we missed registration of DeploymentLogOptions somewhere.

**Comment by mfojtik** [comment]
@deads2k @sttts seems like we missing something in registration: https://gist.github.com/mfojtik/c43e9d1a0967cb63c225e063fd80ff5a

**Comment by mfojtik** [comment]
failures should be fixed

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/16167

/retest

**Pull request merged**
