### PR TITLE
UPSTREAM: 37721: Fix logic error in graceful deletion

### PR DESCRIPTION
**Pull request by derekwaynecarr**
xref https://bugzilla.redhat.com/show_bug.cgi?id=1397356

Fixes https://github.com/openshift/origin/issues/12039

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Comment by derekwaynecarr** [comment]
fixed issue re [merge]

**Comment by derekwaynecarr** [comment]
re [merge]

**Pull request merged**
