### PR TITLE
images/node: remove kernel modules and other unnecessary packages

### PR DESCRIPTION
**Pull request by squeed**
This should shrink the image.

### CODE REVIEW

**Comment by squeed** [comment]
Oh, I bet we can remove even more deps.

**Comment by squeed** [comment]
Uh.
```

**Comment by squeed** [comment]
Uh,
```
WARNING: DATA RACE
Write at 0x00c420290360 by goroutine 27:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:325 +0x0
  github.com/openshift/origin/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents()
      /go/src/github.com/openshift/origin/vendor/github.com/fsnotify/fsnotify/inotify.go:287 +0x787

Previous read at 0x00c420290360 by goroutine 36:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:140 +0x0
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).traversePluginDir.func1.1()
      /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:191 +0x96
```
@sjenning maybe you know what's up?

**Comment by dcbw** [comment]
@squeed backport of https://github.com/kubernetes/kubernetes/pull/71440 from kube 1.13 is required

**Comment by smarterclayton** [comment]
/hold 

Will roll this into https://github.com/openshift/origin/pull/21918

**Pull request closed without merging**
