### PR TITLE
Rename deploy.* imports to apps.*

### PR DESCRIPTION
**Pull request by soltysh**
Followup to #16202.

@mfojtik ptal, since you asked for it :)

### CODE REVIEW

**Comment by soltysh** [comment]
This is currently waiting for https://github.com/openshift/origin/pull/17477 to merge first.

**Comment by soltysh** [comment]
I'm guessing this will have to wait for #17503 to land first.

**Comment by soltysh** [comment]
@deads2k this will conflict with the rebase (https://github.com/openshift/origin/pull/17576) so I'm leaving the decision to merge this to you.
/hold

**Comment by soltysh** [comment]
/hold
until #17576 merges

**Comment by deads2k** [comment]
First ones look ok.  I guess if it builds, we'll call it good.

/lgtm
/queue multiple-rebases

**Comment by soltysh** [comment]
https://github.com/openshift/origin/issues/17769 is biting this PR every time.

/retest

**Pull request merged**
