### PR TITLE
test-integration etcd verbosity controlled by OSTEST_VERBOSE_ETCD

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/9109.

@stevekuznetsov 
[test]

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
So this allows us to turn on `--loglevel 5` with a Bash envar? Won't we end up just turning it on in Jenkins? If we think that level of logging is useful, let's instead throw it into a logfile. If we're not sure that this level is useful, let's let the envar dictate the level `OS_TEST_ETCD_VERBOSITY=3`.

**Comment by deads2k** [comment]
> So this allows us to turn on --loglevel 5 with a Bash envar?

No, this lets you turn on an off the verbose etcd logging, but keeps glog at loglevel 5.

**Comment by deads2k** [comment]
> If we're not sure that this level is useful, let's let the envar dictate the level OS_TEST_ETCD_VERBOSITY=3.

capnslog doesn't use an int and we really only need the "default" and "verbose" switch.

**Comment by stevekuznetsov** [comment]
So, if we only have two levels and we've chosen already that "verbose" is the level at which we get the optimal amount of info, I don't see us turning it off in the Jenkins jobs, right? My original gripe was on the Jenkins consoles, not locally. So if we can't specifically turn off the spammy messages, let's instead log to a file so the logs on the Jenkins console are readable and if necessary, someone can debug with the etcd logs anyway.

**Comment by deads2k** [comment]
> So, if we only have two levels and we've chosen already that "verbose" is the level at which we get the optimal amount of info, I don't see us turning it off in the Jenkins jobs, right? My original gripe was on the Jenkins consoles, not locally. So if we can't specifically turn off the spammy messages, let's instead log to a file so the logs on the Jenkins console are readable and if necessary, someone can debug with the etcd logs anyway.

That level of logging is useless in the vast majority of cases.  I'd do it off by default everywhere.

**Comment by deads2k** [comment]
> let's instead log to a file so the logs on the Jenkins console are readable and if necessary, someone can debug with the etcd logs anyway.

I don't see much value in doing that.

**Comment by stevekuznetsov** [comment]
I understand what you mean after speaking with you -- let's get this merged so the integration logs aren't a nightmare.

**Comment by deads2k** [comment]
Heh, test even shows the benefit.

**Comment by deads2k** [comment]
> I understand what you mean after speaking with you -- let's get this merged so the integration logs aren't a nightmare.

I'd rather not force merge.  Who is looking at the image import problem?

**Comment by stevekuznetsov** [comment]
> let's get this merged

=== this LGTM, tag it. Not asking for a force-merge.

@legionus is looking at the issue and has a fix -- dockerhub API changed.

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
[test]

**Pull request merged**
