### PR TITLE
Fix a bug in the egress router README

### PR DESCRIPTION
**Pull request by danwinship**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1387645. Just a docs change so there's no reason to not get it in for 3.4. @knobunc PTAL

### CODE REVIEW

**Comment by knobunc** [comment]
[merge]

**Comment by danwinship** [comment]
flake #11016
[test]

**Comment by danwinship** [comment]
test flake #11747, merge flake  #11682
[test]

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
