### PR TITLE
don't build hello-openshift image

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
the hello-openshift binary needs to be built with the netgo flag so we get a static binary and our current build/release scripts don't make it easy to add a flag for a specific binary.  For now i'm pushing a properly built image and disabling the building of this image so it doesn't get overridden every time we build.

**Comment by bparees** [comment]
@ncdc @smarterclayton if you can show me the magic to add a flag to the go build for the hello-openshift binary, i'd rather do that, but i got lost in the shell scripts pretty quickly and it looked like there was no obvious place to inject specific flags for a specific artifact compilation.

**Comment by ncdc** [comment]
I don't believe it's possible to do per-artifact

**Comment by ncdc** [comment]
Wouldn't it make more sense to build everything using either `-tags netgo` or with glibc-static installed?

**Comment by bparees** [comment]
@ncdc i debated adding -tags netgo to everything...I wasn't sure what the performance implications were and it seemed like a scary change to add at this point in the release.

**Comment by ncdc** [comment]
Agreed, and I would think glibc-static would be a better option. @vbatts?

**Comment by bparees** [comment]
we can revisit building this differently later, but for now i'm merging this so it isn't broken anymore.

[merge]

**Comment by smarterclayton** [comment]
Why are we not fixing this the right way?

**Comment by bparees** [comment]
@smarterclayton see discussion above.  i'm still investigating it, but frankly i'm not sure it's worth building this image on every bulid anyway..it's basically a waste of time for something that's trivial and never changes.

**Comment by bparees** [comment]
and in my comment that you deleted i said we'd still look into fixing it the right way, but this was to get people going again in the meantime.

**Comment by smarterclayton** [comment]
I'd rather not have our primary example not be getting security updates.

----- Original Message -----

**Comment by bparees** [comment]
security updates?  it's a scratch image of a go binary.

**Comment by smarterclayton** [comment]
Go runtime has security bugs.

----- Original Message -----

**Pull request closed without merging**
