### PR TITLE
Display a relevant error message when hostname is missing

### LINKED ISSUE #5809: Invalid error messages when starting with an empty hostname
If you go to create the configuration with an empty hostname you will get an error message about `--node` missing:

`$ ./openshift start --write-config=openshift.local.config --hostname=`
>Wrote master config to: openshift.local.config/master/master-config.yaml
F1109 15:31:29.847067   26849 start_allinone.go:91] Server could not start: --node must be provided

If you add the `--node` option it will complain the `--node` is an unknown flag:

`$ ./openshift start --write-config=openshift.local.config --hostname= --node=test`
> Error: unknown flag: --node

Note that there is no `--node` option listed, there is a `--nodes` option though

### PR DESCRIPTION
**Pull request by ripcurld00d**
Fixes #5809

### CODE REVIEW

**Comment by smarterclayton** [comment]
Rebase please

**Comment by ripcurld00d** [comment]
@smarterclayton,
sorry for the delay. i will rebase this in the next hours.
regarding your question, there is a validation check in `RunNode`. however, it returns error with the wrong flag name.
i am sure there is a better way to handle it, for example, map the `all-in-one` switches to `master` and `node` switches and return the correct error using that map.

**Comment by ripcurld00d** [comment]
hoo snap... i closed it by accident.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Debug flake [test]

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
re[test]

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
