### PR TITLE
UPSTREAM: Remove CORS headers from pod proxy responses

### LINKED ISSUE #2619: Duplicate CORS headers when proxying service requests
When a proxied backend set CORS headers on their own, they get not removed when the OpenShift proxy sets his `Allow-Origin` header. This results in duplicate headers, which makes the browser croak. 

It seems, that this [code](https://github.com/openshift/origin/blame/945fb793cf68ba3836a75239b14b05fcbe44427a/pkg/util/httpproxy/upgradeawareproxy.go#L249-L256) is not called when doing a proxy request.

See fabric8io/fabric8#4033 for details.

### PR DESCRIPTION
**Pull request by csrwng**
Upstream PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/9159
Fixes #2619

### CODE REVIEW

**Comment by csrwng** [comment]
@liggitt fyi

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Comment by jimmidyson** [comment]
@csrwng @smarterclayton This is still not fixed in 0.6.2. Still got errors when proxying to pod under `/api/v1beta3/proxy/namespaces/default/pods/...`.

**Comment by liggitt** [comment]
Not sure that proxy was updated. The one under `/pods/foo/proxy` was the one that got fixed. Cesar?

**Comment by jimmidyson** [comment]
Yeah can see that - just switching to it, but the inconsistency between proxy URLs needs to be fixed. Proxying to services is still under old URL, pods under both... would like to just use this one new style URL tbh.

**Comment by liggitt** [comment]
The top level proxy is actually the older style and is limited to cluster admins by default. Still should be fixed, though.

**Comment by jimmidyson** [comment]
Yeah sorry that's what I mean service proxying is still under `proxy/namespaces/{namespaces}/services/{name}`. This is planned to be moved to `services/{name}/proxy` right to be consistent with pods proxying?

**Comment by smarterclayton** [comment]
Yes but it's not going to make 1.0 at this point.

**Comment by jimmidyson** [comment]
Yeah I kind of assumed that.

**Comment by liggitt** [comment]
@csrwng is there an upstream issue for `services/{name}/proxy`?

**Comment by csrwng** [comment]
There is now https://github.com/GoogleCloudPlatform/kubernetes/issues/10038

**Pull request merged**
