### PR TITLE
Bug 1976376: builds: comment out multi-namespace template test

### PR DESCRIPTION
**Pull request by gabemontero**
a pick of just @yselkowitz 's https://github.com/openshift/origin/pull/26072/commits/7e93e512f3ad715def2424f71a5b486e2c95aa69 to unwedge jenkins e2e's in 4.8

I will be porting this test to the jenkins client plugin e2e's

/assign @yselkowitz 

@akram @waveywaves @jkhelil @adambkaplan FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
@bparees - are you still the person to apply "group-lead-approved"  labels for build/jenkins extended test PRs?

There is a chain of cause and effect in the PRs referenced in the description that has lead to some of the jenkins e2e's perm failing across releases

Addressed in master/4.9, this is the first of the back ports.

**Comment by bparees** [comment]
> @bparees - are you still the person to apply "group-lead-approved" labels for build/jenkins extended test PRs?

i dunno, but i'm still a person who can, anyway :)

done.

**Comment by gabemontero** [comment]
On Fri, Jun 25, 2021 at 7:13 PM Ben Parees ***@***.***> wrote:

> @bparees <https://github.com/bparees> - are you still the person to apply
> "group-lead-approved" labels for build/jenkins extended test PRs?
>
> i dunno, but i'm still a person who can, anyway :)
>
> done.
>
thanks man

**Comment by gabemontero** [comment]
the e2e-aws-jenkins test is green, which is all we touched

/retest

for the unrelated fails

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by akram** [comment]
The test e2e-metal-ipi-ovn-dualstack seems to always fail. 

/hold

**Comment by gabemontero** [comment]
> The test e2e-metal-ipi-ovn-dualstack seems to always fail.
> 
> /hold 

https://github.com/openshift/origin/pull/26251 is suppose to be skipping those tests in 4.8.  They are already skipped in 4.9/master.

We can unhold once that merges.  It is on the merge queue but is hitting, including failures with e2e-aws-jenkins which this should address.  Will comment there.

**Comment by gabemontero** [comment]
/test e2e-aws-proxy

@adambkaplan 's fix for builds has merged

**Comment by gabemontero** [comment]
So the one failure in e2e-gcp is https://bugzilla.redhat.com/show_bug.cgi?id=1975938  per https://sippy.ci.openshift.org/?release=4.8

the metal-ipi-ovn-dualstack failures were reported on sippy for 4.8 but had not BZ ... I opened https://bugzilla.redhat.com/show_bug.cgi?id=1977885 via the link on sippy

and e2e-aws-jenkins is passing which is what this PR updates

the e2e-aws-proxy run is still in flight but should pass with @adambkaplan change from yesterday

@bparees or @smarterclayton - in order to unwind 4.8 e2e's, are either of you willing to override e2e-gcp and e2e-metal-ipi-ovn-dualstack so we can get this change into 4.8 and unblock e2e-aws-jenkins?

thanks

**Comment by gabemontero** [comment]
ah well ... other stuff in e2e-aws-proxy failed here in 4.8

that said, overriding gcp and metal-ipi @bparees @smarterclayton would still progress things along if you are amenable 

I'll research e2e-aws-proxy failures on 4.8 afterward

**Comment by bparees** [comment]
/override ci/prow/e2e-gcp
/override ci/prow/e2e-metal-ipi-ovn-dualstack 

will override proxy when @gabemontero refs a bug to get it back to green/confirms the failure is unrelated.  Note that @knobunc had also run into the proxy job failure and said he would investigate, i dunno if he found anything so you might check w/ him.

**Comment by bparees** [comment]
/override ci/prow/e2e-aws-proxy

confirmed the proxy job has a config issue that needs to be tackled.

**Comment by gabemontero** [comment]
> /override ci/prow/e2e-aws-proxy
> 
> confirmed the proxy job has a config issue that needs to be tackled.

thanks for following up @bparees

**Pull request merged**
