### PR TITLE
fix forcepull setup build config

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/6299

@bparees PTAL

### CODE REVIEW

**Comment by gabemontero** [comment]
[testextendedonly][extended:core(forcepull)]

**Comment by bparees** [comment]
lgtm, will wait for extended test results.

**Comment by bparees** [comment]
unfortunately this is probably going to fail until the centos issue is resolved and the system can actually build images again.

**Comment by gabemontero** [comment]
interesting ... i did a git fetch after seeing https://github.com/openshift/origin/pull/6306 and https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7807/ and was able to run hack/build-base-images.sh and hack/build-images.sh, and am (knock on wood) running extended tests locally (and hence was able to confirm the fix locally)

but I see that subsequent builds have failed, so it must still be flaky somehow

**Comment by gabemontero** [comment]
[testextendedonly][extended:core(forcepull)]

**Comment by bparees** [comment]
@gabemontero it's [testonlyextended][extended:core(forcepull)]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
flake `F1215 00:46:47.045647   32368 etcd.go:38] Unable delete key: 100: Key not found (/openshift.io) [1055]`

[merge]

**Pull request merged**
