### PR TITLE
Bug 1722919: Pin openshift to release-4.1 branches 

### PR DESCRIPTION
**Pull request by soltysh**
/assign @mfojtik @sttts @deads2k @smarterclayton

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
this change is good, but we need a bz to pass verification.  can you link to a bz?

**Comment by soltysh** [comment]
@derekwaynecarr done, ptal

**Comment by jwforres** [comment]
@soltysh can you get one of the origin reviewers to LGTM this, after that i'll approve it for cherry-pick since the change is not relevant to 4.2

**Pull request merged**
