### PR TITLE
Remove update percent

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik @smarterclayton removes updatePercent which we were supposed to remove in [1.1](https://github.com/openshift/origin/blob/master/UPGRADE.md#origin-10x--ose-30x) with a slight implication - `oadm router` from old clients will create routers with 25%-25% instead of 0-25% in new servers.

See https://bugzilla.redhat.com/show_bug.cgi?id=1378587 for more info.

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
cc: @openshift/api-review

**Comment by smarterclayton** [comment]
Please add a write up to the 1.4 deprecation notices (UPGRADES.md) and add it to the 1.4 release notes.

**Comment by smarterclayton** [comment]
Removal is approved.

**Comment by mfojtik** [comment]
image

**Comment by kargakis** [comment]
updated UPGRADE.md [merge]

@smarterclayton not sure what release notes are you talking about? Should I just `Edit release` for https://github.com/openshift/origin/releases/tag/v1.4.0-alpha.0 and add it there or are these notes in a different place?

**Comment by smarterclayton** [comment]
Create an openshift-docs bug that says 1.4.0 release notes and add a
comment on there that includes this change (basically like we did for 1.3)

On Mon, Sep 26, 2016 at 11:28 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
Done: https://github.com/openshift/openshift-docs/issues/2933

**Pull request merged**
