### PR TITLE
Better formatting for jenkinsfile example

### PR DESCRIPTION
**Pull request by danmcp**

### CODE REVIEW

**Comment by danmcp** [comment]
@bparees PTAL

**Comment by bparees** [comment]
lgtm [merge]

**Comment by danmcp** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/11779/ failed with flake: https://github.com/openshift/origin/issues/11887

**Comment by danmcp** [comment]
[test]

**Comment by danmcp** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/11788/ failed with flake: https://github.com/openshift/origin/issues/11887

**Pull request merged**
