### PR TITLE
Allow the configuration of individual controllers

### PR DESCRIPTION
**Pull request by deads2k**
@mfojtik I was thinking something like this.  Untested, but it actually has a good shot at working.

### CODE REVIEW

**Comment by mfojtik** [comment]
tested manually and it works

@smarterclayton using this we should be able to disable malfunctioning controller by updating the master-config.

/lgtm

**Comment by mfojtik** [comment]
@deads2k serialization...

**Comment by kargakis** [comment]
```
./pkg/cmd/server/origin/controller/interfaces.go
./pkg/cmd/server/start/controllers.go
[FATAL] Try running 'gofmt -s -d [path]'
[FATAL] Or autocorrect with 'hack/verify-gofmt.sh | xargs -n 1 gofmt -s -w'
```

**Comment by deads2k** [comment]
@mfojtik @bparees now with fixed migration to respect the old settings.  ptal.

**Pull request merged**
