### PR TITLE
[WIP] DO NOT MERGE - Configure autoscaling in the web console

### PR DESCRIPTION
**Pull request by spadgett**
Requires #6333. Not ready for code review.

https://trello.com/c/SRc3zRmO

openshift_web_console

- [ ] Rebase on #6333 when available
- [ ] Show autoscaling information on browse pages and possibly overview
- [ ] Support modifying autoscaling after creation
- [ ] Prevent manual scaling when an autoscaler is defined

/cc @jwforres @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Nice, this is helpful to see how you are planning on using.  Will update you soon.

**Comment by jwforres** [comment]
Hmmm, it seems weird to me that you specify an exact number of replicas, and then also specify a range.

**Comment by spadgett** [comment]
@jwforres Trying to decide how it should look if we disable the replicas for autoscaling. Radio buttons?

openshift_web_console

**Comment by jwforres** [comment]
hmm seems ok at the moment, but at some point you are going to be able to
auto-scale based on other metrics besides CPU so is that disabled section
going to grow big enough that its weird to show it all disabled? maybe we
can change it then if thats the case

**Comment by spadgett** [comment]
@DirectXMan12 FYI

**Comment by DirectXMan12** [comment]
Since I haven't worked with the web UI before, I'm unsure of how hard this would be, but it might be a good idea to ensure that the target RC or DC has CPU requests set on its pods.  According to the questions/issues that I've received, needing CPU requests set continues to be one of the most confusing part of autoscaling for people, so warning about the lack of CPU requests in the UI would probably be a good idea.  Along that line of thought, it might also be a good idea to show the calculated expected CPU for alongside the percentage input.

**Comment by benjaminapetersen** [comment]
@spadgett pushed up a new working version of APIGroups.  Have a couple TODOs yet to polish up, but I think we can give autoscaling a test with it.

**Comment by spadgett** [comment]
@DirectXMan12 Thanks, I'm looking at adding support for requests and limits to the web console first. We have a card for that anyway. 

>  needing CPU requests set continues to be one of the most confusing part of autoscaling for people

I think we should call it out more clearly in the autoscaling topic, maybe as a `[NOTE]` block.

https://docs.openshift.org/latest/dev_guide/pod_autoscaling.html

**Comment by spadgett** [comment]
@ajacobs21e FYI

**Comment by spadgett** [comment]
Closing for now. I'll reopen when we're ready to tackle this.

**Pull request closed without merging**
