### PR TITLE
Only pass --ginkgo.skip when focus is absent

### LINKED ISSUE #6255: Extended tests are not properly bypassing ginkgo.skip when focused
Running --focus="HAProxy" does not trigger the test - you have to clear skip with SKIP="XXX" which is wrong.  It's possible we have something wrong with focus.

### PR DESCRIPTION
**Pull request by smarterclayton**
Bash sucks

Fixes #6255

### CODE REVIEW

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
