### PR TITLE
upkeep: updated data set for 4.12

### PR DESCRIPTION
**Pull request by eggfoobar**
alerts comparisons were above allowed leeway of `1m0s`
| Name | Release | From | Arch | Network | Platform | Time Increase |
| ---- | ------- | ---- | ---- | ------- | -------- | ------------- |
| etcdGRPCRequestsSlow | 4.12 |  | amd64 | sdn | gcp | 12m2.64s |
| etcdGRPCRequestsSlow | 4.12 | 4.11 | amd64 | ovn | aws | 4m41.34s |
| etcdGRPCRequestsSlow | 4.12 |  | amd64 | sdn | vsphere | 4m39.75s |
| etcdGRPCRequestsSlow | 4.12 |  | arm64 | ovn | aws | 3m7.01s |
| etcdGRPCRequestsSlow | 4.12 |  | amd64 | ovn | aws | 3m7.01s |
| etcdGRPCRequestsSlow | 4.12 |  | arm64 | sdn | aws | 2m52.2s |
| etcdGRPCRequestsSlow | 4.12 |  | amd64 | sdn | aws | 2m52.2s |
| etcdGRPCRequestsSlow | 4.12 | 4.12 | amd64 | ovn | aws | 2m51.48s |
| etcdGRPCRequestsSlow | 4.12 | 4.11 | amd64 | sdn | azure | 2m48.57s |
| PrometheusOperatorWatchErrors | 4.12 | 4.10 | amd64 | sdn | aws | 2m48.15s |
| etcdGRPCRequestsSlow | 4.12 | 4.11 | amd64 | sdn | aws | 2m46.8s |
| etcdGRPCRequestsSlow | 4.12 | 4.11 | arm64 | sdn | aws | 2m46.8s |
| etcdGRPCRequestsSlow | 4.12 | 4.11 | amd64 | ovn | gcp | 2m46.22s |
| etcdGRPCRequestsSlow | 4.12 |  | amd64 | ovn | aws | 1m16.52s |

disruptions comparisons were above allowed leeway of `1m0s`
| Name | Release | From | Arch | Network | Platform | Time Increase |
| ---- | ------- | ---- | ---- | ------- | -------- | ------------- |
| kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 10m0.45s |
| kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 9m46.02s |
| oauth-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 8m49.5s |
| oauth-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 8m46.66s |
| openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 5m36.38s |
| openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 5m32.14s |
| cache-kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 5m13.11s |
| cache-kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 5m8.26s |
| cache-oauth-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 4m49.8s |
| cache-oauth-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 4m48.56s |
| cache-openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 3m18.88s |
| cache-openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 3m8.82s |
| kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m59.46s |
| kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m44.06s |
| openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m41.29s |
| openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m32.78s |
| ingress-to-console-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m32.34s |
| ingress-to-console-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m29.44s |
| cache-openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m20.75s |
| cache-kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m18.98s |
| cache-openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m18.81s |
| cache-oauth-api-reused-connections | 4.12 |  | amd64 | ovn | azure | 1m17.21s |
| cache-kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure | 1m16.72s |
| cache-oauth-api-new-connections | 4.12 |  | amd64 | ovn | azure | 1m14.04s |
| oauth-api-new-connections | 4.12 |  | amd64 | ovn | azure | 1m13.79s |
| ingress-to-console-reused-connections | 4.12 | 4.12 | amd64 | ovn | aws | 1m7.91s |
| ingress-to-oauth-server-reused-connections | 4.12 | 4.11 | amd64 | sdn | azure | 1m5.74s |

Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by dgoodwin** [comment]
I've filed https://issues.redhat.com/browse/TRT-553 to try to figure out what we do about Azure. 

File was last updated Aug 18, I can't explain why it looks so much worse now, it looks consistently terrible. 

4.11 exhibits the same symptom even further back. I don't see a regression in the graphs but it's nearly impossible to tell with them in their current state. https://issues.redhat.com/browse/TRT-552 to get that addressed.

The etcdGRPCRequestsSlow will help with a lot of job failures and we have a card already tracking this work.

/lgtm

**Comment by dgoodwin** [comment]
Worth noting the disruption values for most backends are likely double the real value, which is being fixed in #27415.

I also need this to merge before that can to pickup the new cache backend data on single node.

**Comment by stbenjam** [comment]
We're just updating some json
/override ci/prow/e2e-aws-ovn-fips
/override ci/prow/e2e-aws-ovn-serial 
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-gcp-ovn-upgrade

**Comment by dgoodwin** [comment]
@eggfoobar We discovered yesterday that some of the problems are massively influenced by single Topology, and ha isn't growing nearly like that, which doesn't seem to be in your chart. Is that being considered in your code to generate?

**Comment by eggfoobar** [comment]
@dgoodwin Good point! I just added the topology to the table being printed and this is what it shows up as now

disruptions comparisons were above allowed leeway of `1m0s`
| Name | Release | From | Arch | Network | Platform | Topology | Time Increase |
| ---- | ------- | ---- | ---- | ------- | -------- |--------- | ------------- |
| kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 10m0.45s |
| kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 9m46.02s |
| oauth-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 8m49.5s |
| oauth-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 8m46.66s |
| openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 5m36.38s |
| openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 5m32.14s |
| cache-kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 5m13.11s |
| cache-kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 5m8.26s |
| cache-oauth-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 4m49.8s |
| cache-oauth-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 4m48.56s |
| cache-openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 3m18.88s |
| cache-openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 3m8.82s |
| kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m59.46s |
| kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m44.06s |
| openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m41.29s |
| openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m32.78s |
| ingress-to-console-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 1m32.34s |
| ingress-to-console-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |single | 1m29.44s |
| cache-openshift-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m20.75s |
| cache-kube-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m18.98s |
| cache-openshift-api-reused-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m18.81s |
| cache-oauth-api-reused-connections | 4.12 |  | amd64 | ovn | azure |ha | 1m17.21s |
| cache-kube-api-new-connections | 4.12 | 4.12 | amd64 | ovn | azure |ha | 1m16.72s |
| cache-oauth-api-new-connections | 4.12 |  | amd64 | ovn | azure |ha | 1m14.04s |
| oauth-api-new-connections | 4.12 |  | amd64 | ovn | azure |ha | 1m13.79s |
| ingress-to-console-reused-connections | 4.12 | 4.12 | amd64 | ovn | aws |ha | 1m7.91s |
| ingress-to-oauth-server-reused-connections | 4.12 | 4.11 | amd64 | sdn | azure |ha | 1m5.74s |

**Pull request merged**
