### PR TITLE
add edge terminated route to sample app

### PR DESCRIPTION
**Pull request by pweil-**
@bparees @smarterclayton Please review.  Tested locally with the sti build example.

### CODE REVIEW

**Comment by bparees** [comment]
can you update the e2e test to use this router instead of (or in addition to) the way it's testing routing today?  I assume you'll need to pass a host header to curl rather than update /etc/hosts.

(in fact it might be better if the instructions specified that too, rather than making users update /etc/hosts)

**Comment by smarterclayton** [comment]
Agreed

----- Original Message -----

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
@bparees `--resolve` has changed my life.  Not only did it make the test-end-to-end.sh work with secure routes but it helped me lose 10 lbs in a week without dieting.  I will apply it liberally to all my example repos for routing.

**Comment by bparees** [comment]
lgtm.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
