### PR TITLE
Bug 1388026 - Ensure deletion of namespaces created by network diagnostics command

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by knobunc** [comment]
[test]

**Comment by danwinship** [comment]
Isn't there another "oadm diagnostic" that runs pods? I don't see any cleanup code like this anywhere else... what does it do?

**Comment by pravisankar** [comment]
Yes, there is 'oadm diagnostics DiagnosticPod' that launches a pod in the namespace pointed by kubeConfig current context and does auth/dns checks. If the cmd is interrupted(ctrl C), created pod is not deleted. This is an issue but it is only one pod. 
In network diags, we create a bunch of namespaces and pods/services inside these namespaces. If the cmd is interrupted, you will see a ton of pods/services not cleaned up. This PR will catch interrupt, terminate signals and does the clean up before exiting. 
In the normal case (no interruption), both DiagnosticPod/NetworkCheck sub-cmds will do the clean up.

**Comment by danwinship** [comment]
ok LGTM

**Comment by knobunc** [comment]
[merge]

**Pull request merged**
