### PR TITLE
NO-JIRA: bump library-go

### PR DESCRIPTION
**Pull request by sanchezl**
Needed to pickup https://github.com/openshift/library-go/pull/1697.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Comment by vrutkovs** [comment]
```
Apr 26 10:00:47.365 - 928s  W namespace/openshift-marketplace pod/certified-operators-pwhlp alert/KubePodNotReady alertstate/firing severity/warning ALERTS{alertname="KubePodNotReady", alertstate="firing", namespace="openshift-marketplace", pod="certified-operators-pwhlp", prometheus="openshift-monitoring/k8s", severity="warning"}
```
/retest

**Pull request merged**
