### PR TITLE
remove a revert on the upstream test infrastructure

### PR DESCRIPTION
**Pull request by deads2k**
This revert will be long term debt if we cannot address it.  I'm reverting the revert here so that I can see what I've got in a prettier diff.

### CODE REVIEW

**Comment by sttts** [comment]
What is reverted and why?

**Comment by deads2k** [comment]
we are unreverting https://github.com/kubernetes/kubernetes/pull/69105 (referenced in commit name).  it was reverted during the rebase because the code unconditionally registers flags which are subsequently written differently in openshift-tests in ways that no longer functioned right.  There are other e2e flag pulls behind this one from storage.

**Comment by deads2k** [comment]
/hold

Something changed and this isn't referencing the right thing anymore. :(

**Comment by deads2k** [comment]
/hold

need to be sure that the list of e2es look correct.

**Comment by deads2k** [comment]
871 tests ran which matches other pulls that aren't doing this.  Here we go!

**Pull request merged**
