### PR TITLE
Make HTML in bindata more mergeable

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@jwforres PTAL. Post-beta1

**Comment by liggitt** [comment]
I wasn't positive about removing comments... it seemed to leave the special IE conditional comments, and I didn't see it removing anything else we cared about. We're not using comment directives, are we?

**Comment by jwforres** [comment]
The IE conditionals would have been all that i would have worried about.  We don't have anything else special in comments.

**Comment by jwforres** [comment]
LGTM

**Comment by mfojtik** [comment]
[test]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
