### PR TITLE
put new quota size in extended test

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @dgoodwin PTAL .... the conformance tests run this extended test.

### CODE REVIEW

**Comment by gabemontero** [comment]
[testonlyextended][extended:core(quota)]

**Comment by gabemontero** [comment]
ok cool the extended test that was failing now passed with the above run

**Comment by bparees** [comment]
lgtm but i don't want to much w/ someone else's extended tests, so will let @dgoodwin sign off first.

**Comment by gabemontero** [comment]
Cool / agreed

**Comment by dgoodwin** [comment]
Nothing to it, LGTM, apologies I didn't think about that when I checked out your first PR @gabemontero

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
Thanks for the confirm @dgoodwin  - no worries

**Comment by gabemontero** [comment]
Fixes https://github.com/openshift/origin/issues/8789

**Comment by bparees** [comment]
@gabemontero fixes needs to be in the PR description, not a comment, to auto-close an issue.  I went ahead and closed #8789 manually.

**Comment by gabemontero** [comment]
Ah - that's right - my bad - thanks @bparees

**Pull request merged**
