### PR TITLE
Verify manifest before accepting

### PR DESCRIPTION
**Pull request by soltysh**
Referenced blobs need to be checked for presence in a destination repository before accepting incoming manifest. Otherwise, user will be able to pull image without previous access to its blobs.

Resolves [bug 1388018](https://bugzilla.redhat.com/show_bug.cgi?id=1388018).

This is a cherry-pick of #12182.

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
@miminar @mfojtik @pweil- @smarterclayton fyi

**Comment by smarterclayton** [comment]
LGTM barring green tests.

**Comment by miminar** [comment]
LGTM

**Comment by smarterclayton** [comment]
[test]

**Comment by miminar** [comment]
Flake #12184. re-[test]

**Comment by soltysh** [comment]
Flake https://github.com/openshift/origin/issues/10951
[test]

**Comment by soltysh** [comment]
[merge]

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
