### PR TITLE
Do not clone etc in _output directory if it is already cloned

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
@smarterclayton we hit this issue once... I think during vagrant provision. You OK with merge?

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Looks like this doesn't work on the test server.

**Comment by smarterclayton** [comment]
Reopen if you fix this.

**Pull request closed without merging**
