### PR TITLE
deploy: cleanup strategy code

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik cleans up the strategy code a bit and partially addresses https://github.com/openshift/origin/issues/11854

### CODE REVIEW

**Comment by kargakis** [comment]
@mfojtik quick review here

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@mfojtik ping

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/12112 and https://github.com/openshift/origin/issues/10228 [merge]

**Pull request merged**
