### PR TITLE
 add better logging for oc cluster up component install

### PR DESCRIPTION
**Pull request by deads2k**
last commit is unique.

This creates a "logs" directory alongside our config directories and tracks the install containers stdout and stderr output.

@stevekuznetsov Where do I need to copy directories to in order to have my logs picked up on failures?

/assign @soltysh

### CODE REVIEW

**Comment by mfojtik** [comment]
/lgtm

Having logs from these components helps problem diagnostic.

**Comment by stevekuznetsov** [comment]
@deads2k are these the logs you wanted? https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/18901/test_pull_request_origin_extended_clusterup/537/artifacts/scripts/clusterup/artifacts/

**Pull request merged**
