### PR TITLE
add discovery rest mapper

### PR DESCRIPTION
**Pull request by deads2k**
@mfojtik @soltysh Does this resolve your "hitting the wrong jobs endpoint" problem?

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by soltysh** [comment]
LGTM, although still doesn't help with the rebase. I'll be digging into it tomorrow. You can merge this at will.

**Comment by deads2k** [comment]
> LGTM, although still doesn't help with the rebase. I'll be digging into it tomorrow. You can merge this at will.

This exposed a server-side problem, it did correctly identify which version to use, right?

**Comment by soltysh** [comment]
Yup, everything worked as expected.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
