### PR TITLE
Use latest php version for the cluster-loader template

### LINKED ISSUE #25433: cluster-loader outdated php version
When running the cluster-loader with the official instructions https://docs.openshift.com/container-platform/4.5/scalability_and_performance/using-cluster-loader.html and default parameters (no custom config file), it fails because:

```
Aug 21 12:20:42.288 W ns/clusterloader-cakephp-mysql0 buildconfig/cakephp-mysql-example reason/BuildConfigInstantiateFailed error ins
tantiating Build from BuildConfig clusterloader-cakephp-mysql0/cakephp-mysql-example (0): Error resolving ImageStreamTag php:7.1 in n
amespace openshift: unable to find latest tagged image (27 times)
```

##### Version
```
Client Version: 4.4.17
Server Version: 4.4.17
Kubernetes Version: v1.17.1+20ba474
```

##### Steps To Reproduce
1. Follow the instructions to run the cluster-loader in a freshly installed OCP4 cluster

##### Current Result
The cluster-loader tool fails because it requires a php version which is not available in OCP4
https://github.com/openshift/cluster-samples-operator/blob/master/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json#L454

##### Expected Result
The cluster-operator deploys the latest php image available.

##### Additional Information
https://github.com/openshift/origin/blob/master/test/extended/testdata/cluster/quickstarts/cakephp-mysql.json#L454

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #25433

### CODE REVIEW

**Comment by sjug** [comment]
Could we batch the fixes together given they're so small?

**Comment by e-minguez** [comment]
Closing it in favor of #25630

**Comment by e-minguez** [comment]
> Could we batch the fixes together given they're so small?

See #25630

**Pull request closed without merging**
