### PR TITLE
[RPMS] Add extended.test to /usr/libexec/origin/extended.test

### PR DESCRIPTION
**Pull request by sdodson**
Ship this via a subpackage as it's a 69MiB binary

### CODE REVIEW

**Comment by sdodson** [comment]
@timothysc @jayunit100 FYI
@tdawson mind taking a look, this is the most sane location I could come up with for the generically named 'extended.test' binary

**Comment by timothysc** [comment]
@sdodson sgtm +1 for libexec & subpackage.  I'll poke @ingvagabund for packaging expertise.

**Comment by tdawson** [comment]
LGTM :+1:

**Comment by jeremyeder** [comment]
@xltian -- need to negotiate getting this run via CI

**Comment by jayunit100** [comment]
Looks good to me to thanks.  I guess we don't need to use  the hack/build-go abstraction . I think I built it this way once and it works the same

**Comment by sdodson** [comment]
The hack/build-go.sh scripts don't work inside koji/brew right now so unfortunately we do some odd stuff. Looks like the binary runs as expected.

```
[root@ose3-master ~]# KUBECONFIG=/etc/origin/master/admin.kubeconfig /usr/libexec/atomic-openshift/extended.test --ginkgo.skip="should becomes" --ginkgo.focus="EmptyDir"
I0311 15:35:44.929296    2940 plugins.go:62] Registered admission plugin "ServiceAccount"
I0311 15:35:44.932840    2940 plugins.go:46] Registered cloud provider "aws"
I0311 15:35:44.933540    2940 plugins.go:46] Registered cloud provider "gce"
Running Suite: Extended Core
============================                                                                                                       
Random Seed: 1457728544       
Will run 18 of 333 specs
...
Ran 18 of 333 Specs in 207.707 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 315 Skipped PASS
[root@ose3-master ~]#                                          
```

**Comment by sdodson** [comment]
@brenton should be good to merge

**Comment by brenton** [comment]
[merge]

**Comment by ingvagabund** [comment]
Looks fine, %{_libexecdir}/%{name} is owned only by one subpackage.

What is intention of the binary? Is it self-standing binary? Does not it need any other auxiliary test files? What about some short md file describing simple example how to use it?

**Comment by ingvagabund** [comment]
Ok, it is a self-standing binary for running unit tests. IIUC, you can ship core.sh, all.sh and other *.sh files from [1] as well.

[1] https://github.com/openshift/origin/tree/master/test/extended

**Comment by sdodson** [comment]
@jayunit100 whatya say about other files we may need to ship? I actually know nothing of the test suite so need guidance from someone who does.

**Comment by ingvagabund** [comment]
Spam number 3: From [1]:

```
/usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.
```

Although it says it is for binaries, I can find a lot of ``Bourne-Again shell script`` and ``POSIX shell script`` files under my /usr/libexec directory. Though, can not find better directory for both the binary and auxiliary shell scripts in [1].

[1] https://www.linuxbase.org/betaspecs/fhs/fhs/ch04s07.html
[2] https://www.linuxbase.org/betaspecs/fhs/fhs/ch04.html

**Comment by timothysc** [comment]
You have no idea how much time this has saved me.  

```sudo yum install atomic-openshift-tests```

thx @jayunit100 & @sdodson 

/cc @mattf

**Pull request merged**
