### PR TITLE
remove bad exit

### PR DESCRIPTION
**Pull request by pweil-**
@soltysh looks like you left an exit in there https://github.com/openshift/origin/pull/16128

cc @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh (!)

/lgtm

**Comment by bparees** [comment]
@pweil- @soltysh @mfojtik @stevekuznetsov how did the PR that introduced the `exit 1` pass tests?

**Comment by stevekuznetsov** [comment]
Looks like it's not run when we set up the server with Ansible, it's in the standup code

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/13708
/retest

**Comment by soltysh** [comment]
> @soltysh looks like you left an exit in there #16128

I feel sooo ashamed now 😢

**Pull request merged**
