### PR TITLE
Fix DNS in oc cluster up for user having DNS on localhost

### PR DESCRIPTION
**Pull request by tnozicka**
It's way too late for Friday evening but there is something wrong in the `oc cluster up` with DNS, at least if you run dnsmasq on your machine, but I don't think this is enough to fix it.

### CODE REVIEW

**Comment by tnozicka** [comment]
I guess this should fix the broken forwarding, still need to fix
```
E0817 19:09:39.065293       1 reflector.go:136] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused
E0817 19:09:39.065310       1 reflector.go:136] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Endpoints: Get https://localhost:8443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused
```
which is probably bad apiserver IP in config

**Comment by tnozicka** [comment]
The informer failures went away with rebase.

**Comment by tnozicka** [comment]
I am gonna describe the use case a bit more:
if you are running a dnsmasq locally (e.g. if using VPN to call the VPN's DNS only for queries in its domain) your `cat /etc/resolv.conf` looks like this
```
 # Generated by NetworkManager
search redhat.com
nameserver 127.0.0.1
```
copying this into the kube-dns container running on "different localhost" is pretty much pointless as the dns is not running in there but on the actual host where `oc cluster up` was run. 

As that record is effectively unusable `oc cluster up` can do best effort work of replacing it with a public IP, the openshift cluster is configured with. User can specify --public-hostname flag to influence this and give us a hint.

As dnsmasq by default listens on `127.0.0.1` user also has to configure dnsmasq to listen on that IP he specified in `--public-hostname` flag.

Tested to work at least on my machine with dnsmasq (managed by NetworkManager).

**Comment by tnozicka** [comment]
@knobunc @openshift/sig-networking PTAL, you own this code

**Comment by tnozicka** [comment]
ping @knobunc @openshift/sig-networking

**Comment by danwinship** [comment]
DNS is @openshift/sig-network-edge not sig-networking. (No this is not obvious.)

**Comment by deads2k** [comment]
> This mechanism seems coupled to linux. For example, the way you'd approach "adapting" the resolver configuration on MacOS would be totally different (e.g. files in /etc/resolver).

@ironcladlou `oc cluster up` only runs on linux.

@mcurry-rh @derekwaynecarr Are we going to support `oc cluster up` on systems that have dnsmasq on.  That's on by default now, right?

**Comment by tnozicka** [comment]
>No objections to merging it if you tested, but my team isn't going to be testing or prioritizing support for this host configuration right now.

@ironcladlou Yes, I have tested it, I can't run clusterup without it so I'll be likely the first one to find if it breaks.

**Comment by ironcladlou** [comment]
Pretty sure that allowing the user to set `--cluster-dns=$IP` in the kubelet config/flags would be a more stable approach here, but I don't know offhand how to propagate that through oc cluster.

**Comment by ironcladlou** [comment]
Current patch also assumes that the nameserver being replaced is actually bound to the host IP and not just loopback.

**Comment by tnozicka** [comment]
>Pretty sure that allowing the user to set --cluster-dns=$IP in the kubelet config/flags would be a more stable approach here, but I don't know offhand how to propagate that through oc cluster.

Seems like that would replace the whole mechanism of using the `/etc/resolv.conf` now. I'd say until such a switch is made this is a valid fix for how it is done now.

I am gonna stress this once more. After removing `openshift start` the only developer path is to use `oc cluster up`. If it doesn't work, I am blocked! I really need this fixed, that's why I've gone down the rabbit hole and fixed it myself because it is urgent!

I have to pick this to every branch I work on and I am gonna accidentally merge it with some of them eventually.

> Current patch also assumes that the nameserver being replaced is actually bound to the host IP and not just loopback.

Yes (https://github.com/openshift/origin/pull/20688#issuecomment-416239888)

I'd guess the same issue is gonna exist with the other approach since kubelet is running in a container so localhost!=localhost. Maybe the loopback could be mounted into a container but I haven't gone that far.

**Comment by tnozicka** [comment]
@ironcladlou thank you

**Pull request merged**
