### PR TITLE
deploy: move cli-related packages in cmd

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton PTAL

@deads2k @bparees let's consolidate all cli-related interfaces under *subpackage*/cmd. Mentioning you since pkg/authorization, pkg/user, and pkg/build already have a reaper package.

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by smarterclayton** [comment]
Please save all major refactors for post rebase.

**Comment by kargakis** [comment]
Flaked on https://github.com/openshift/origin/issues/9766

[test]

**Comment by kargakis** [comment]
same flake as before

[test]

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
