### PR TITLE
UPSTREAM: 46299: Fix in-cluster kubectl --namespace override

### LINKED ISSUE #13780: Cannot list resources from other namespaces inside a pod
Even though I have the permissions.
```
[mkargaki@dhcp129-211 configmap-rollout]$ oc project
Using project "kube-system" on server "https://127.0.0.1:8443".
[mkargaki@dhcp129-211 configmap-rollout]$ oc get po
NAME                          READY     STATUS    RESTARTS   AGE
cm-trigger-2242473228-s02bx   1/1       Running   0          3m
[mkargaki@dhcp129-211 configmap-rollout]$ oc get deploy -n myproject
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
alpine    1         1         1            1           1h
[mkargaki@dhcp129-211 configmap-rollout]$ oc exec -it cm-trigger-2242473228-s02bx -- oc get deploy -n myproject --loglevel=9000
I0415 14:32:43.274889     184 merged_client_builder.go:122] Using in-cluster configuration
I0415 14:32:43.275472     184 cached_discovery.go:112] returning cached discovery info from /root/.kube/172.30.0.1_443/servergroups.json
I0415 14:32:43.275550     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/apps/v1beta1/serverresources.json
I0415 14:32:43.275594     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/authentication.k8s.io/v1beta1/serverresources.json
I0415 14:32:43.275633     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/autoscaling/v1/serverresources.json
I0415 14:32:43.275667     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/batch/v1/serverresources.json
I0415 14:32:43.275707     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/batch/v2alpha1/serverresources.json
I0415 14:32:43.275749     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/certificates.k8s.io/v1alpha1/serverresources.json
I0415 14:32:43.275828     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/extensions/v1beta1/serverresources.json
I0415 14:32:43.275861     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/policy/v1beta1/serverresources.json
I0415 14:32:43.275929     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/storage.k8s.io/v1beta1/serverresources.json
I0415 14:32:43.276231     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/v1/serverresources.json
I0415 14:32:43.276333     184 merged_client_builder.go:145] Using in-cluster namespace
I0415 14:32:43.276505     184 cached_discovery.go:112] returning cached discovery info from /root/.kube/172.30.0.1_443/servergroups.json
I0415 14:32:43.276568     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/apps/v1beta1/serverresources.json
I0415 14:32:43.276629     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/authentication.k8s.io/v1beta1/serverresources.json
I0415 14:32:43.276696     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/autoscaling/v1/serverresources.json
I0415 14:32:43.276757     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/batch/v1/serverresources.json
I0415 14:32:43.276836     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/batch/v2alpha1/serverresources.json
I0415 14:32:43.276907     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/certificates.k8s.io/v1alpha1/serverresources.json
I0415 14:32:43.277040     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/extensions/v1beta1/serverresources.json
I0415 14:32:43.277110     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/policy/v1beta1/serverresources.json
I0415 14:32:43.277172     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/storage.k8s.io/v1beta1/serverresources.json
I0415 14:32:43.277648     184 cached_discovery.go:70] returning cached discovery info from /root/.kube/172.30.0.1_443/v1/serverresources.json
I0415 14:32:43.279380     184 merged_client_builder.go:122] Using in-cluster configuration
I0415 14:32:43.279537     184 merged_client_builder.go:122] Using in-cluster configuration
I0415 14:32:43.279873     184 cached_discovery.go:112] returning cached discovery info from /root/.kube/172.30.0.1_443/servergroups.json
I0415 14:32:43.280001     184 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjbS10cmlnZ2VyLXRva2VuLXEwMnd0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImNtLXRyaWdnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzZDkzZTE0ZC0yMWUxLTExZTctYTJkZS02OGY3Mjg0MGU3ZGYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06Y20tdHJpZ2dlciJ9.AeiUaTaoD9Lc7BeG56nJGlnm5b8JD6WSCvNfA9c1dYT2H_Qmwf_3Maht3prqIwpKAl-ivqdWXsET9DzEWcn406QeHNC6ElGuYPm-GDCuVgHguNVYSZNLFlBNzCuXSYnerb9ZDa_UncKM9-ERsIJaQoWVHJM-X1sb2nRQSl_yJQW3UTSbteW1e_bi7wqar682njl4c9SdH-CKfR4hhDNjy3Ybxr31oCTb-GpsqdwJTGa9E5F29n8MG26oUWBudELbDLvMLvYvHyQnHJmLNyMZDK8WYkBFAEJj-Vq7FjPjpZLhjcdpEg_n1zW9W_QnDQ2DnhpOQYrk-rx0_YkfcybdTw" -H "Accept: application/json" -H "User-Agent: oc/v1.5.2+43a9be4 (linux/amd64) kubernetes/43a9be4" https://172.30.0.1:443/apis/extensions/v1beta1/namespaces/kube-system/deployments
I0415 14:32:43.308921     184 round_trippers.go:318] GET https://172.30.0.1:443/apis/extensions/v1beta1/namespaces/kube-system/deployments 200 OK in 28 milliseconds
I0415 14:32:43.308946     184 round_trippers.go:324] Response Headers:
I0415 14:32:43.308956     184 round_trippers.go:327]     Cache-Control: no-store
I0415 14:32:43.308963     184 round_trippers.go:327]     Content-Type: application/json
I0415 14:32:43.308970     184 round_trippers.go:327]     Content-Length: 1813
I0415 14:32:43.308977     184 round_trippers.go:327]     Date: Sat, 15 Apr 2017 14:32:43 GMT
I0415 14:32:43.309042     184 request.go:905] Response Body: {"kind":"DeploymentList","apiVersion":"extensions/v1beta1","metadata":{"selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/deployments","resourceVersion":"2320"},"items":[{"metadata":{"name":"cm-trigger","namespace":"kube-system","selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/deployments/cm-trigger","uid":"cb5aaa17-21e7-11e7-a2de-68f72840e7df","resourceVersion":"2269","generation":1,"creationTimestamp":"2017-04-15T14:28:29Z","labels":{"run":"cm-trigger"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"cm-trigger"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"cm-trigger"}},"spec":{"volumes":[{"name":"trigger","configMap":{"name":"cm-trigger","defaultMode":329}},{"name":"kube-cache","emptyDir":{"medium":"Memory"}}],"containers":[{"name":"cm-trigger","image":"openshift/observe:latest","args":["--all-namespaces","configmaps","--","/usr/bin/cm-trigger/trigger.sh"],"ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"trigger","mountPath":"/usr/bin/cm-trigger"},{"name":"kube-cache","mountPath":"/root/.kube"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"cm-trigger","serviceAccount":"cm-trigger","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":1,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-04-15T14:28:29Z","lastTransitionTime":"2017-04-15T14:28:29Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."}]}}]}
NAME         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
cm-trigger   1         1         1            1           4m
```

@smarterclayton @deads2k @liggitt

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #13780

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm, [merge]

**Comment by ncdc** [comment]
[test]

**Comment by ncdc** [comment]
#13977 [test]

**Comment by ncdc** [comment]
[merge][severity: bug]

**Pull request merged**
