### PR TITLE
oc new-app git error handling 

### PR DESCRIPTION
**Pull request by mjudeikis**
Adds git based workflows errors filtering where errors should not be raised.
solves:
bz1534916
bz1470374

Mainly these are needed due how `git` cli is behaving with secure git repositories, or how we do code detection. 

We could remote some of these "hacky" checks if we move our git implementation to golang based one. Something like https://github.com/src-d/go-git

### CODE REVIEW

**Comment by mjudeikis** [comment]
I want to add something like:
`WARNING: git authentication was detected. Build might require source secret to access code.`

+ test broken. checking

**Comment by mjudeikis** [comment]
After sleeping on this, I can say I dont like it... It changes the behaviour of the `oc new-app` and `oc new-build`. After some looking into this might be too big break. 

I would better do something like: 
https://github.com/openshift/origin/compare/master...mjudeikis:bugzilla_1470374_2?expand=1 
Where we state when issue occurs and suggest other flag to disable code detection:

```
with no git:
[root@default origin]# oc new-app -i openshift/ruby --code https://github.com/openshift/ruby-hello-world
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
error: Code detection is not possible. If you want skip it add flag --code-detection=false
```

and with git
```
[root@default origin]# oc new-app --image-stream=openshift/ruby:latest --code=https://github.com/openshift/fakerepo.git 
Username for 'https://github.com': dummynonexistingaccount
Password for 'https://dummynonexistingaccount@github.com': 
error: shallow cloning repository "https://github.com/openshift/fakerepo.git" to "/tmp/gen270431341" failed: Cloning into '/tmp/gen270431341'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/openshift/fakerepo.git/'

[root@default origin]# oc new-app --image-stream=openshift/ruby:latest --code=https://github.com/openshift/fakerepo.git 
Username for 'https://github.com': mjudeikis
Password for 'https://mjudeikis@github.com': 
error: Code detection is not possible. If you want skip it add flag --code-detection=false
[root@default origin]# 
```

And in noGit case we can do:
```
if !git.IsGitInstalled(){
  &app.CodeDetection=false
}
```

**Comment by bparees** [comment]
> After sleeping on this, I can say I dont like it... It changes the behaviour of the oc new-app and oc new-build. 

what are the behavior changes?  (in terms of overall result to the user)

**Comment by mjudeikis** [comment]
So now with private repo it fails like this:
```
[root@default origin]#  oc new-app --image-stream=openshift/ruby:latest --code=https://github.com/openshift/fakerepo.git
Username for 'https://github.com': asd
Password for 'https://asd@github.com': 
error: shallow cloning repository "https://github.com/openshift/fakerepo.git" to "/tmp/gen428766815" failed: Cloning into '/tmp/gen428766815'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/openshift/fakerepo.git/'
```

And I would suggest capture cases like this and add `--code-detection=false` where it suggest to turn off code-detection and use same flags. 
```
[root@default origin]# oc new-app --image-stream=openshift/ruby:latest --code=https://github.com/openshift/fakerepo.git 
Username for 'https://github.com': mjudeikis
Password for 'https://mjudeikis@github.com': 
error: Code detection is not possible. If you want skip it add flag --code-detection=false
[root@default origin]# `
```

**Pull request closed without merging**
