### PR TITLE
Convert sample-app examples from json to yaml

### PR DESCRIPTION
**Pull request by PI-Victor**
@bparees before i go any further just for readability purposes, is this ok?
also updated to ruby-23-centos7 and s/sti/s2i/

### CODE REVIEW

**Comment by PI-Victor** [comment]
[test]

**Comment by PI-Victor** [comment]
p.s.: want to convert imagestreams and quickstarts, because that's where people look when getting started

**Comment by bparees** [comment]
i have concerns about changing the webhook example.  we're trying to mimic what github actually sends, does github send yaml?  if not, then the example should stay json.

this is also going to require a lot of sifting through tests and documentation that reference these files since the names are changing.

**Comment by PI-Victor** [comment]
yes, i had doubts as well about the webhook example, will revert.
yep, also changing that these days, just wanted to know if it's ok to pursue this. will update the docs and whatnot to reflect the changes.

**Comment by bparees** [comment]
@PI-Victor yeah it's an ok thing to pursue (when you are blocked on your trello cards and don't have higher priority bugs/issues you can work on), you'll make @smarterclayton very happy i think.  You might work with @coreydaley since this could play into the example consolidation work he's got for this sprint.

**Comment by bparees** [comment]
@PI-Victor is this still a work in progress?  if so, can you label it as such in the PR title?

**Comment by PI-Victor** [comment]
done. i'll try, among other things, to wrap it up tomorrow. or even later today.

**Comment by PI-Victor** [comment]
the good news, this is no longer WIP. the bad new is... it's long and very hard to review. 🤣

**Comment by bparees** [comment]
ouch.  well let's start by seeing that you haven't broken any tests.

**Comment by PI-Victor** [comment]
i already see something, i think there are hardcoded jsons, will have a look and submit a PR to fix, or revert the changes in this one

**Comment by smarterclayton** [comment]
Yay!

**Comment by bparees** [comment]
With that level of enthusiasm hopefully you can help review it :)


Ben Parees | OpenShift

**Comment by coreydaley** [comment]
@PI-Victor Did you use a json -> yaml converter utility or did you re-create them by hand?
Also, did you run them through a yaml validator?
Sorry if you already answered these to Ben or whoever.

**Comment by coreydaley** [comment]
I'm seeing a lot of tests that still seem to refer to the old .json files
I used the following command in the test directory:
grep -r "\.json" * | grep "examples"
http://pastebin.test.redhat.com/446421

There might be a catch 22-ish situation with the ones that are pulling the .json files from github...

**Comment by PI-Victor** [comment]
@coreydaley thanks! atom has a json2yaml and also a linter, which was very helpful.
i'll try to finish this today, i've updated all readmes, tests that use the fixture path, and scripts. let's see what else fails. :-)

**Comment by coreydaley** [comment]
@PI-Victor Looks like all buy one check passed!
Looks like you just need to update the docs with hack/update-generated-docs.sh
(Might also want to run make verify locally and see if something else needs run also)

**Comment by PI-Victor** [comment]
oh, mon dieu! one stupid extra json file checked out incorrectly and it caused havoc. i hope now it would work.

**Comment by PI-Victor** [comment]
@bparees do you have any idea why this damn thing keeps regenerating json files?
locally it works perfectly
on jenkins go-bindata generates a completely different thing
it keeps adding json files out of nowhere, do we have some sort of special config in the test env?

```
===== Verifying Generated Bootstrap Bindata =====
Generating bootstrap bindata...
Diffing current bootstrap bindata against freshly generated bindata
--- /go/src/github.com/openshift/origin/pkg/bootstrap/bindata.go	2017-01-20 17:44:21.000000000 +0000
+++ _output/verify-bootstrap-bindata/pkg/bootstrap/bindata.go	2017-01-20 17:56:09.294973985 +0000
@@ -1,27 +1,47 @@
 // Code generated by go-bindata.
 // sources:
+// examples/image-streams/image-streams-centos7.json
 // examples/image-streams/image-streams-centos7.yaml
+// examples/image-streams/image-streams-rhel7.json
 // examples/image-streams/image-streams-rhel7.yaml
+// examples/db-templates/mariadb-ephemeral-template.json
 // examples/db-templates/mariadb-ephemeral-template.yaml
+// examples/db-templates/mariadb-persistent-template.json
 // examples/db-templates/mariadb-persistent-template.yaml
+// examples/db-templates/mongodb-ephemeral-template.json
 // examples/db-templates/mongodb-ephemeral-template.yaml
+// examples/db-templates/mongodb-persistent-template.json
 // examples/db-templates/mongodb-persistent-template.yaml
+// examples/db-templates/mysql-ephemeral-template.json
 // examples/db-templates/mysql-ephemeral-template.yaml
+// examples/db-templates/mysql-persistent-template.json
 // examples/db-templates/mysql-persistent-template.yaml
+// examples/db-templates/postgresql-ephemeral-template.json
 // examples/db-templates/postgresql-ephemeral-template.yaml
+// examples/db-templates/postgresql-persistent-template.json
 // examples/db-templates/postgresql-persistent-template.yaml
+// examples/db-templates/redis-ephemeral-template.json
 // examples/db-templates/redis-ephemeral-template.yaml
+// examples/db-templates/redis-persistent-template.json
 // examples/db-templates/redis-persistent-template.yaml
+// examples/jenkins/application-template.json
+// examples/jenkins/jenkins-ephemeral-template.json
 // examples/jenkins/jenkins-ephemeral-template.yaml
+// examples/jenkins/jenkins-persistent-template.json
 // examples/jenkins/jenkins-persistent-template.yaml
 // examples/jenkins/pipeline/bluegreen-pipeline.yaml
 // examples/jenkins/pipeline/mapsapp-pipeline.yaml
 // examples/jenkins/pipeline/maven-pipeline.yaml
 // examples/jenkins/pipeline/samplepipeline.yaml
+// examples/quickstarts/cakephp-mysql.json
 // examples/quickstarts/cakephp-mysql.yaml
+// examples/quickstarts/dancer-mysql.json
 // examples/quickstarts/dancer-mysql.yaml
+// examples/quickstarts/django-postgresql.json
 // examples/quickstarts/django-postgresql.yaml
+// examples/quickstarts/nodejs-mongodb.json
 // examples/quickstarts/nodejs-mongodb.yaml
+// examples/quickstarts/rails-postgresql.json
 // examples/quickstarts/rails-postgresql.yaml
 // examples/logging/logging-deployer.yaml
 // pkg/image/admission/imagepolicy/api/v1/default-policy.yaml
@@ -68,6 +88,852 @@ func (fi bindataFileInfo) Sys() interfac
 	return nil
 }
```

**Comment by bparees** [comment]
not offhand, sorry.

**Comment by coreydaley** [comment]
I'm not able to replicate the issue locally, following as closely as i can
to what the jenkins build does.

Is there any way to look at the vagrant image we use? or the aws image?

**Comment by PI-Victor** [comment]
@smarterclayton @stevekuznetsov do anyone of you guys know why verify-bootstrap-bindata.sh keeps generating .json files inside of jenkins? i've changed all the examples to yaml files, the test passes locally and in travis, but fails in jenkins.

see https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/10410/console

**Comment by stevekuznetsov** [comment]
I'm not familiar with `go-bindata` -- maybe @jwforres will know?

**Comment by PI-Victor** [comment]
cc @csrwng

**Comment by jwforres** [comment]
yeah @csrwng is probably the right person for that set of bindata stuff, its what is used by cluster up

**Comment by PI-Victor** [comment]
i'm inclined to believe the git branch is dirty for this PR or something else - like, whatever issues there was, it's been fixed now, because the tests pass here: https://github.com/openshift/origin/pull/12662 and the bind-bootstrap-bindata works just fine.
so i'm closing this PR and continuing to work there
cc: @bparees

**Pull request closed without merging**
