### PR TITLE
 add minimal SCC changes to switch to CRD

### PR DESCRIPTION
**Pull request by deads2k**
this doesn't include any validation.  Let's see if we can land before the east coast gets really angry.

### CODE REVIEW

**Comment by deads2k** [comment]
infra

/test all

**Comment by deads2k** [comment]
/hold

waiting on https://github.com/openshift/cluster-monitoring-operator/pull/343

**Comment by deads2k** [comment]
Teraform

/retest

**Comment by squeed** [comment]
This PR (and #22737) is failing pretty consistently with `level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating: timed out waiting for the condition"`

Do you think it is caused by these PRs, or is a monitoring bug?

**Pull request closed without merging**
