### PR TITLE
Temporary fix to bump timeout to 300s

### PR DESCRIPTION
**Pull request by sdodson**
Remove this once we merge #1298

### CODE REVIEW

**Comment by sdodson** [comment]
@liggitt mind merging this as a temporary fix, currently systemd kills openshift-master on start up because it takes longer than the 90s default.

**Comment by liggitt** [comment]
sure, [merge]

**Comment by liggitt** [comment]
@sdodson can you add the revert to the other PR?

**Comment by sdodson** [comment]
@liggitt Yup, will do.

**Pull request merged**
