### PR TITLE
Example health checker pod that reports prometheus metrics

### PR DESCRIPTION
**Pull request by smarterclayton**
The test is in bash, mimics an end user experience (not with external
auth). Other checker pods could run like this. Simplest possible
expression of an app.

This would be something you deploy and monitor. If it isn't reporting, the test is "down". Other metrics can be tracked.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Don’t we need a service with required annotation to round out example?

**Comment by smarterclayton** [comment]
Done, also cleaned up the retry logic.

**Comment by smarterclayton** [comment]
bah, wget is too old.  :(

**Comment by smarterclayton** [comment]
@aweiteka

**Comment by aweiteka** [comment]
Why a statefulset?

**Comment by smarterclayton** [comment]
TODO: 
* [ ] drop builds from it (perf, scale issues)
* [ ] move to openshift-ansible as an APB
* [ ] dump the output for this from CI?
* [ ] thoughts on logging

**Comment by aweiteka** [comment]
In my testing I'm not seeing any latency "step" label except "new-app". I'm missing build/deploy/exposed metrics labels even though those steps had completed. Not sure where the issue is.

With just the latency data and 'application_create_up == 0' how would we determine which step has failed?

**Comment by smarterclayton** [comment]
If you rsh into the serve container, what is in /srv/metrics?

**Comment by smarterclayton** [comment]
Switched to not use build

**Comment by pweil-** [comment]
@brenton

**Comment by sosiouxme** [comment]
After it has run for a while, the `check` container is considered to be crashlooping (even with successful exit) and backs off running. Maybe it would be better to let configuration determine how often to re-run, rather than sleeping in the container?

As @aweiteka asked, why a `StatefulSet`?

Clever use of the platform as scheduler. Very simple publisher. Is there a desire to use this general model with multiple checks of this type? I.e. define a container per check and they can run on different schedules and all write to a published volume.

**Pull request closed without merging**
