### PR TITLE
UPSTREAM: 52046: [BugFix] Soft Eviction timer works correctly

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Backport for soft evictions to work correctly.

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1542166

/cc @aveshagarwal

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla thanks. 

@derekwaynecarr could you provide lgtm and approval?

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla just noticed that you have created it for 3.7 not for 3.6? is there any reason for that? Also I think you will have to create one for ose 3.6 too.

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla also I am assuming that this is already fixed in 3.9?

**Comment by ravisantoshgudimetla** [comment]
@aveshagarwal The bug is fixed in 3.8 and above. IIRC last time, @sjenning suggested that we need to backport to 3.7 before we go to 3.6. So, I created for 3.7 and I am testing for 3.6(which should fail as well) and then will raise for 3.6

> Also I think you will have to create one for ose 3.6 too.

Yes, I will once these origin PRs merge.

**Comment by aveshagarwal** [comment]
> Yes, I will once these origin PRs merge.

Somehow I thought that you needed to create only for ose 3.6 and 3.7, are you sure you need to create for origin 3.6/3.7 too?

**Comment by ravisantoshgudimetla** [comment]
> Somehow I thought that you needed to create only for ose 3.6 and 3.7, are you sure you need to create for origin 3.6/3.7 too?

Yes, I just checked my old PRs, I had to raise PRs to origin before OSE.

**Comment by ravisantoshgudimetla** [comment]
Closing this as PR has been against OSE has been merged.

**Pull request closed without merging**
