### PR TITLE
add audit logging to apiserver starts

### PR DESCRIPTION
**Pull request by deads2k**
Adds audit logging to help debug https://github.com/openshift/origin/issues/14990

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by stevekuznetsov** [comment]
LGTM as long as I understood the earlier conversation to mean `test-cmd.sh` was the suite this was targeting -- you're not going to get this patch on any other job as they're using the Ansible installer.

**Comment by deads2k** [comment]
> LGTM as long as I understood the earlier conversation to mean test-cmd.sh was the suite this was targeting -- you're not going to get this patch on any other job as they're using the Ansible installer.

Ok, can get we get a separate issue for those?  I don't know where and how to wire that to be on.

**Comment by deads2k** [comment]
[merge]

**Pull request merged**
