### PR TITLE
fix bad scope nil deref in endpoints update

### LINKED ISSUE #15922: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
https://sentry.io/red-hat/openshift-3-dev-preview-int/issues/333820561/

```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "/builddir/build/BUILD/atomic-openshift-git-0.c420cf9/_output/local/go/src/github.com/openshift/origin/pkg/cmd/util/serviceability/panic.go", line 28, in CapturePanic-fm
  File "/builddir/build/BUILD/atomic-openshift-git-0.c420cf9/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go", line 51, in HandleCrash
  File "/usr/lib/golang/src/runtime/asm_amd64.s", line 514, in call32
  File "/usr/lib/golang/src/runtime/panic.go", line 489, in gopanic
  File "/usr/lib/golang/src/runtime/panic.go", line 63, in panicmem
...
(8 additional frame(s) were not displayed)

runtime error: invalid memory address or nil pointer dereference
```

### PR DESCRIPTION
**Pull request by sjenning**
fixes #15922

@derekwaynecarr @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
@openshift/networking does this need backport

**Comment by danwinship** [comment]
No, that code is from the kube 1.7 rebase

**Comment by enj** [comment]
@smarterclayton shouldn't out tooling detect this as a variable shadowing issue?

**Comment by smarterclayton** [comment]
We disable most shadowing because of false positives on err.  This is an
actual legitimate case, hidden in the weeds.

**Pull request merged**
