### PR TITLE
Add builds to status, also make status pluggable

### PR DESCRIPTION
**Pull request by smarterclayton**
Adds builds and deployments to `osc status`

@jwforres review - to see sample output, uncomment the t.Logf at the bottom of projectstatus_test.go and run:

    hack/test-go.sh pkg/cmd/cli/describe -v -test.run=TestProjectStatus

### CODE REVIEW

**Comment by smarterclayton** [comment]
Upstream pull is https://github.com/GoogleCloudPlatform/kubernetes/pull/6493

**Comment by jwforres** [comment]
instead of saying

```
build 1 running about a minute ago
```

can you say

```
build 1 running for 1 minute
```

that is the approach we took in the console

alternatively...

```
build 1 started running about a minute ago
```

As it is currently the grammar is off..

**Comment by jwforres** [comment]
The `<-` hanging on the end of the line feels strange

```
		service sinatra-app-example (172.30.17.47:8080 -> 8080)
		  sinatra-app-example deploys sinatra-app-example:latest <-
		    building git://github.com/mfojtik/sinatra-app-example with docker.io/openshift/ruby-20-centos7:latest
```

**Comment by jwforres** [comment]
Is this supposed to indicate a build is in progress?

```
building git://github.com/mfojtik/sinatra-app-example with docker.io/openshift/ruby-20-centos7:latest
```

Or is this like when you had it saying "deploying" and I had you change it to "deploys"

**Comment by smarterclayton** [comment]
The latter.

----- Original Message -----

**Comment by smarterclayton** [comment]
It's really to indicate continuity (if the line was shorter it would all be on one line)

----- Original Message -----

**Comment by smarterclayton** [comment]
We're using docker's human units, which does the "about a ".  I'm fine with started running.

----- Original Message -----

**Comment by jwforres** [comment]
other than that, the output lgtm.

**Comment by smarterclayton** [comment]
Comments addressed.

----- Original Message -----

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
