### PR TITLE
etcd clusters must negotiate to reach v3 mode, wait

### LINKED ISSUE #12993: Tests fail due to `etcdserver: not capable`
Swagger spec failed to generated because the clustered failed to come up successfully:

```
12:43:19 Running hack/lib/start.sh:296: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s...
12:43:19 FAILURE after 159.641s: hack/lib/start.sh:296: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s: the command timed out
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check_future/275/consoleFull#157290065256c015c5e4b05b79524e5a2f

### PR DESCRIPTION
**Pull request by smarterclayton**
Otherwise we can start making calls to the cluster while it is still in v2 mode.

Fixes #12993

@liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm [merge]

**Comment by liggitt** [comment]
should https://github.com/kubernetes/kubernetes/pull/39821/ have done this as well?

**Comment by smarterclayton** [comment]
Only embedded servers have to do it.

**Comment by smarterclayton** [comment]
ClusterVersion() can be nil, apparently.  I have no version yet I must
negotiate, or something.

**Pull request merged**
