### PR TITLE
remove source repo from pipeline buildconfig

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal.  pipeline buildconfig's don't need a source reference if they include the Jenkinsfile content directly embedded, like this one does.  the source repo is just confusing.

**Comment by gabemontero** [comment]
agreed .... lgtm

over time, do we have a preference wrt promoting the embedded style vs. storing the jenkinsfile in a repo (we see the later with the various jenkins repos like jenkins core or the fabric stuff)

**Comment by bparees** [comment]
@gabemontero my guess is most people will want it in a repo so they can do git commits to update their pipeline definition, send it through a PR review process, etc.  but for purposes of our sample, it's simpler if it's self contained.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
