### PR TITLE
Pull HAProxy from the CentOS PaaS sig repo only

### PR DESCRIPTION
**Pull request by smarterclayton**
@eparis

### CODE REVIEW

**Comment by eparis** [comment]
Is this the right fix, or have we pushed haproxy18 to the wrong repo and should fix that instead?

**Comment by smarterclayton** [comment]
Testing with the paas7-common build tag.

**Comment by sdodson** [comment]
Revert my commit in this PR too, it looks like it's still pulling from the 38 testing repo in the CI job.

**Comment by eparis** [comment]
I have https://github.com/openshift/origin/pull/18066/files which hopefully we will be able to merge and we'll just close this one.

**Comment by smarterclayton** [comment]
Please base your change on this - we shouldn't be mixing the repos in the
same file.  Cherry-picking my commit is enough.

**Pull request closed without merging**
