### PR TITLE
bump(github.com/RangelReale/osin): c07b3bd1ee57089f63e6325c0ea035ceed2e905c

### PR DESCRIPTION
**Pull request by liggitt**
Updated to latest version to pick up improvements:
1. Made spec compliant (if multiple redirect_uris are registered, client must provide one) (ensured our CLI client only has a single redirect_uri registered, for that reason)
2. redirect_uris are validated against traversal attacks
3. requested scopes are validated against granted scopes by osin

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k review

**Comment by deads2k** [comment]
Looks like the default token gen is still an off-brand UUID generator?  Does that matter to us?

**Comment by liggitt** [comment]
No, we override the out of box impl

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
UI re[merge]

**Comment by deads2k** [comment]
Same UI failures in three tests.  Removing the merge tags so you can diagnose.

**Comment by liggitt** [comment]
Yay tests... UI was expecting "bearer" case-sensitively... updated. re[merge]

**Pull request merged**
