### PR TITLE
UPSTREAM: Variable expansion

### PR DESCRIPTION
**Pull request by pmorie**
@derekwaynecarr You came for the upstream, why not stay for the patch?

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by pmorie** [comment]
@pweil- Can you bring yourself to review this code?

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by pmorie** [comment]
This is for two upstream pulls:

1. https://github.com/GoogleCloudPlatform/kubernetes/pull/7936
2. https://github.com/GoogleCloudPlatform/kubernetes/pull/8149

**Pull request merged**
