### PR TITLE
add some optimized functions in example/deployment 

### PR DESCRIPTION
**Pull request by yuexiao-wang**
It is poorly readable that the incoming parameters of function is so lengthiness.  I add some functions to instead of  lengthiness  parameters which is clearly understanded

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@mfojtik PTAL
Thanks！

**Comment by mfojtik** [comment]
@yuexiao-wang looks good to me, thanks! Can you please reword the commit message and make it more descriptive?

**Comment by yuexiao-wang** [comment]
Hi mfojtik,
I have reworded the commit messages. 
Thanks!
@mfojtik PTAL

**Comment by mfojtik** [comment]
@yuexiao-wang I don't see the commit message changed :-)

**Comment by yuexiao-wang** [comment]
@mfojtik PTAL
I' m sorry, and have changed the commit messages. 
Thanks!

**Comment by yuexiao-wang** [comment]
@mfojtik PTAL
How about this PR? Thanks!

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
