### PR TITLE
deploy: validate minReadySeconds against default deployment timeout

### PR DESCRIPTION
**Pull request by kargakis**
@mfojtik PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
@openshift/api-review

**Comment by smarterclayton** [comment]
This is new for 1.3, right?  LGTM if so.

**Comment by kargakis** [comment]
> This is new for 1.3, right? LGTM if so.

Yes, MinReadySeconds was merged a couple of days ago but this was missed

[merge]

**Comment by kargakis** [comment]
secrets [merge]

**Comment by kargakis** [comment]
#9965 [merge]

**Pull request merged**
