### PR TITLE
consistently kebab case urls in web console

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Update/rebased on the recent theme-f1.  Was easier to just create a new branch than fuss with the template differences.  [Previous closed PR is here](https://github.com/openshift/origin/pull/6707/files).

- kebab case urls (and matching view templates)
- add legacy redirects

Gist of comments from previous PR:
- `redirectTo` does keep query strings
- not an easy way to get a deprecation warning in a redirect path (but, is only 3 at this point)
- kebab case chosen over camelCase or snake_case because it requires fewest changes for consistency & follows best practices for how browsers/crawlers understand the hyphen as a non-word character (doubleClickMe, double_click_me, double-click-me).  

@spadgett @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM except you need to rebase again :-\

**Comment by jwforres** [comment]
also be warned that https://github.com/openshift/origin/pull/6976 touches a lot of templates and needs to get merged first

**Comment by benjaminapetersen** [comment]
heh.  i love to rebase!  :sweat_smile:

**Comment by spadgett** [comment]
You might wait for what's in the merge queue now and #6976 to merge before rebasing.

**Comment by spadgett** [comment]
@benjaminapetersen clear to rebase :)

**Comment by benjaminapetersen** [comment]
yay! :grinning:

**Comment by benjaminapetersen** [comment]
rebased!

**Comment by spadgett** [comment]
Missing a `create-route` in project.html.

**Comment by benjaminapetersen** [comment]
Got it!

**Comment by spadgett** [comment]
LGTM [merge]

**Comment by spadgett** [comment]
Need to update tests for the URL changes.

**Comment by benjaminapetersen** [comment]
Ah, the redirects didn't catch.  Can do.

**Comment by spadgett** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
updated

**Comment by benjaminapetersen** [comment]
first test failed, second passed...

**Comment by spadgett** [comment]
```
Element not found: .breadcrumb li a
...
(/data/src/github.com/openshift/origin/assets/test/integration/helpers.js:75:11)
    at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:138:13)
```

**Comment by spadgett** [comment]
authenticated_e2e-user_new_project_when_creating_a_new_project_should_successfully_create_a_new_project_png__1024x1987_

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
The merge failure above looks unrelated. I think I've seen the error, though, on rare occasions. It's possible we have a timing issue around project creation.

/cc @jwforres

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
