### PR TITLE
Update external examples

### PR DESCRIPTION
**Pull request by rhcarvalho**
Update examples including build hooks.

- ~~https://github.com/openshift/cakephp-ex~~ (https://github.com/openshift/cakephp-ex/issues/24)
- ~~https://github.com/openshift/dancer-ex~~ (https://github.com/openshift/dancer-ex/issues/29)
- [x] https://github.com/openshift/django-ex/pull/29
- [x] https://github.com/openshift/golang-ex/pull/11
- ~~https://github.com/openshift/nodejs-ex~~ (https://github.com/openshift/nodejs-ex/issues/32)
- [x] https://github.com/openshift/rails-ex/pull/42

### CODE REVIEW

**Comment by rhcarvalho** [comment]
:gift: If adding golang-ex to the list, need to:

1. Have extended test  (`sample_repos.go`)
2. Update docs (see https://github.com/openshift/openshift-docs/pull/1627)

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by mfojtik** [comment]
i'm OK with opting out the golang-ex for now (we really don't have builder for go we control and the point of that example is exercise the onbuild in S2I which we will disable for only anyway ;-)

**Comment by rhcarvalho** [comment]
Yeah, I don't intend to add Go for now. The comment above was a reminder from an IRC conversation with @bparees, in case we decided to add it.

BTW we're also adding other changes recently merged to other example repos, not only build-hooks.

**Comment by bparees** [comment]
lgtm
[merge]

**Pull request merged**
