### PR TITLE
Make the default quorum reads

### PR DESCRIPTION
**Pull request by smarterclayton**
Ensures that controllers like GC won't delete resources incorrectly.

[test]

### CODE REVIEW

**Comment by enj** [comment]
Do we have any tests to determine the performance hit for etcd v2 and v3?

**Comment by smarterclayton** [comment]
@mffiedler to test with quorum on for everything set 

```
kubernetesMasterConfig:
  apiServerArguments:
    etcd-quorum-read:
    - "true"
```

I think given what we know this is the practical option.  Inclined to merge as is and then iterate as necessary.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
In the interests of unblocking us, I think we should get correct, then come
back and be selective.  Going to [merge].

**Comment by mfojtik** [comment]
@smarterclayton thanks! yeah, @sttts already came with a proposal of adding Quorum:true into GetOptions{} which seems reasonable to me. If we have that, we can fix the GC client to always set this and be safe there.

I'm going to still continue investigation on the DC/deployer issue as something is telling me the quorum was not the only thing that causes this.

**Comment by sttts** [comment]
@mfojtik compare @smarterclayton's https://github.com/openshift/origin/pull/14571. That's basically my proposal with a special resourceVersion constant.

**Comment by mfojtik** [comment]
@sttts yeah saw it, not sure if I like `ResourceVersion`... i think addition to GetOptions{} is less API disturbing?

**Comment by sttts** [comment]
@mfojtik @smarterclayton how does an old apiserver react if it see `Quorum` as `resourceVersion`? An aditional field in `GetOptions` is just ignored by the parameter codec.

**Comment by mfojtik** [comment]
@smarterclayton just tested this and can still reproduce the deployer gone missing error :-/ 

```
I0612 10:04:53.170649   11268 wrap.go:42] GET /api/v1/namespaces/default/deploymentconfigs/router: (1.794058ms) 404 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/010d313/system:serviceaccount:kube-system:generic-garbage-collector] 192.168.64.3:43176]
```

**Comment by mfojtik** [comment]
@smarterclayton @deads2k see something fishy in the URL above? How about `/api` instead of `/oapi` ? /me facepalms

**Comment by smarterclayton** [comment]
#14571 was a sketch, but yes, we'd probably need another flag.  I think I'm
leaning towards opt out of quorum is the correct thing to do, vs opt in
(which we've said over and over, but haven't acted on).  So basically we
can treat that as an optimization if necessary.

**Comment by sttts** [comment]
My vote goes for opt-out as well. I am sure a number of controllers are not prepared for sudden 404s or old data.

**Comment by jeremyeder** [comment]
@mffiedler could you please enumerate in this issue, the list of test permutations that we discussed this morning?

**Comment by mffiedler** [comment]
"Standard" cluster horizontal workload: 300 nodes, 1K namespaces, 6K pods (4K running).   This is the config we have the most previous release data with.

Run the workload on 3.6-latest for:

1. etcd v2 storage mode
2. greenfield etcd v3 storage mode, etcd-quorum-read=false
3. greenfield etcd v3 storage mode, etcd-quorum-read=true
4. migrate etcd v2 storage for this workload to etcd v3 

pbench data will be gathered during load up and @ steady state for all cases.

**Comment by enj** [comment]
No etcd v2 with etcd-quorum-read=true?

**Comment by mffiedler** [comment]
@enj  Added it. Thanks.

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/14590

[merge]

**Comment by smarterclayton** [comment]
I need to consider whether events should be disabled from quorum reads by default.  Endpoints are actually our worst quorum read.

**Comment by smarterclayton** [comment]
Based on initial perf feedback (30% more io with this set, but 20% less CPU in v2) I'm going to merge this now so we are "safe" and then continue to revise.  Customers can revert to prior release behavior by setting the flag to quorum-read "false" in the config.

**Comment by stevekuznetsov** [comment]
[[CI] Decompose test_pull_requests_origin into the different underlying jobs](https://trello.com/c/sxR2pLmz/262-ci-decompose-testpullrequestsorigin-into-the-different-underlying-jobs)

**Comment by smarterclayton** [comment]
@stevekuznetsov is this link actually you?

**Comment by stevekuznetsov** [comment]
Unclear what happened there ... accidental fat-fingered copy-paste?

**Pull request merged**
