### PR TITLE
Handle port bindings

### LINKED ISSUE #9083: port bindings in docker-compose.yaml not honored by `oc import docker-compose ...`
Hi,

I am using this [docker-compose.yaml](https://gist.github.com/containscafeine/37bc4388d0a08fefd39774cbdef56f41) file which has the port bindings for services described like this:

``` yaml
version: "2"
services:
  hello:
    image: containscafeine/hello
    ports:
    - "13371:8080"
    labels:
     - "app=hello"
     - "hystrix.enabled=true"
```

`oc import docker-compose -f docker-compose.yaml` works just fine, but the services are not exposed to the specified port in the `docker-compose.yaml`, but instead to the port mentioned in the `EXPOSE` directive in the respective Dockerfiles of the services.
##### Version

``` bash
oc v1.3.0-alpha.1-20-g30f598e-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
```
##### Steps To Reproduce
- `wget https://gist.githubusercontent.com/containscafeine/37bc4388d0a08fefd39774cbdef56f41/raw/53482698f99a8033117901aa26c045f55c9c16f5/docker-compose-port-fail-oc.yaml`
- `oc import docker-compose -f docker-compose-port-fail-oc.yaml`
##### Current Result

``` bash
# oc get svc
NAME                 CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
aloha                172.30.133.98    <none>        8080/TCP            15m
api-gateway          172.30.69.132    <none>        8080/TCP            15m
bonjour              172.30.28.251    <none>        8080/TCP            15m
frontend             172.30.27.8      <none>        8080/TCP            15m
hello                172.30.106.233   <none>        8080/TCP            15m
hola                 172.30.33.74     <none>        8080/TCP            15m
...
...
```
##### Expected Result

The services should get exposed to the ports specified in the `docker-compose.yaml` file, instead to the exposed ports (that should be the default behavior, but overridden by the values set in the `docker-compose.yaml`.)

### PR DESCRIPTION
**Pull request by surajssd**
For a port binding declared as `HOST:CONTAINER` assign `CONTAINER` port to container definition and `HOST` port to service's 'port' created for that particular service.

Fixes #9083

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM, [merge] thanks

**Comment by surajssd** [comment]
@smarterclayton updated with code changes, rebased!

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[merge] #9959

**Comment by smarterclayton** [comment]
Looks like the test-cmd test for import docker-compose is broken because of this change.  You need to regenerate the stored test file in order to pass a merge.

**Pull request closed without merging**
