### PR TITLE
debug for extended test pv creation

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/14972

### CODE REVIEW

**Comment by bparees** [comment]
only test failure was the pipeline one that @gabemontero is looking into.  merging.

**Comment by stevekuznetsov** [comment]
@bparees why did we merge this?

**Comment by bparees** [comment]
@stevekuznetsov it's more than debug at this point, it's the fix.  it just also adds debug.

**Comment by bparees** [comment]
@stevekuznetsov https://github.com/openshift/origin/pull/15553/files#diff-f4a17e7c84ee9f2a9cb2d480ebc033e9R1048

admittedly i should have removed the commented out line, but w/e. it's been a day.

**Comment by stevekuznetsov** [comment]
@bparees ok, just wanted ACK that we were intending to keep the print statements, etc

**Comment by bparees** [comment]
> @bparees ok, just wanted ACK that we were intending to keep the print statements, etc

yeah i think they may be useful if we have issues in the future.

**Pull request merged**
