### PR TITLE
Update of openshift logos font to the latest JBoss logo.

### PR DESCRIPTION
**Pull request by sg00dwin**
Fix for https://github.com/openshift/origin/issues/3270 and https://bugzilla.redhat.com/show_bug.cgi?id=1233502

Also, added the following based on request from jlucky
.icon-magento, .icon-ghost, .icon-angularjs, .icon-hhvm, .icon-hack, .icon-ceylon, .icon-middleman, .icon-owncloud

### CODE REVIEW

**Comment by sg00dwin** [comment]
@liggitt

**Comment by danmcp** [comment]
@sg00dwin @jwforres Bump

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
Need to address the readability of the current logo at small sizes before we merge this

**Comment by danmcp** [comment]
@sg00dwin Still valid?  Needs a rebase.

**Comment by jwforres** [comment]
@danmcp we have asked them for a logo that works at small sizes and never heard back. See https://github.com/openshift/origin/issues/3270#issuecomment-130410837

The one we have in this PR looks terrible at small sizes so we aren't merging it.  We should probably just close this PR since we still have the issue to track this and we will need to re-run the iconfont stuff when we get the new one.  Is that ok @sg00dwin  ?

**Comment by danmcp** [comment]
@sg00dwin @jwforres Bump

**Pull request closed without merging**
