### PR TITLE
Bash completion updates

### PR DESCRIPTION
**Pull request by nak3**
This patches includes:
- Fix for `oc cancel-build <tab>` to get build instead of pod
- Support for  `oc export <tab>` to get resources
- Update for `oc set {env,volumes,probles,triggers}`

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by danmcp** [comment]
@fabianofranz Review please

**Pull request closed without merging**
