### PR TITLE
Add templates to list of authorized resources

### PR DESCRIPTION
**Pull request by csrwng**
Added "templates" to the resource types that get used for the bootstrap policy.

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k - pls review

**Comment by deads2k** [comment]
Should a user with the `view` role be able to post to the `template` endpoint?

**Comment by csrwng** [comment]
they should not, posting to a template endpoint will create a new template in the registry

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by deads2k** [comment]
This time I really mean it!  [merge]

**Pull request merged**
