### PR TITLE
UPSTREAM: 39998: Cinder volume attacher: use instanceID instead of NodeID when verifying attachment

### PR DESCRIPTION
**Pull request by jsafrane**
cc @rootfs @childsb

### CODE REVIEW

**Comment by jsafrane** [comment]
Forgot to mention, it fixes https://bugzilla.redhat.com/show_bug.cgi?id=1420645

**Comment by rootfs** [comment]
LGTM

**Comment by jsafrane** [comment]
[test]

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
[merge]

**Comment by childsb** [comment]
[merge]

**Comment by eparis** [comment]
[merge] again. the failure looks to be in deployer pods and have no relation to this PR

**Pull request merged**
