### PR TITLE
should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by php-coder** [comment]
@mfojtik Could you re-run the merge process?

**Comment by mfojtik** [comment]
@YuPengZTE can you please make sure we don't have this anywhere else in the codebase and fix it?

**Comment by php-coder** [comment]
@YuPengZTE just to be sure that you won't do useless work: don't modify files inside of the `vendor/` directory because it's a third-party code and most likely it won't be merged.

**Comment by YuPengZTE** [comment]
Address this problem in master on today, close it.

**Pull request closed without merging**
