### PR TITLE
Updates db replica extended tests to use nfs backed persistent volumes

### LINKED ISSUE #7102: Extended test "openshift postgresql replication" does not work remotely
```
• Failure [27.311 seconds]
[images][postgresql] openshift postgresql replication
/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:38
  postgresql replication works for registry.access.redhat.com/rhscl/postgresql-94-rhel7 [It]
  /Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:36

  Expected error:
      <*exec.Error | 0xc82055cbe0>: {
          Name: "chcon",
          Err: {
              s: "executable file not found in $PATH",
          },
      }
      exec: "chcon": executable file not found in $PATH
  not to have occurred

  /Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:73
--------------------
```

Extended tests should not assume they are on the same host - they need to be using a container to do these manipulations.  Blocks running e2e against a remote cluster.

Spawned from #7094

### PR DESCRIPTION
**Pull request by coreydaley**
This pull request is intended to build upon the NFS backed persistent volumes introduced in #18708 for the Jenkins extended tests.
The main goal is to remove the dependency on host path volumes for persistent volumes in our tests so that they can be run in parallel across a cluster.

Fixes #7102

### CODE REVIEW

**Comment by coreydaley** [comment]
@openshift/sig-developer-experience ptal

**Comment by bparees** [comment]
/lgtm
/hold
(pending passing tests)

**Comment by gabemontero** [comment]
ooh that is an old github issue

**Comment by coreydaley** [comment]
@bparees all tests are green

**Pull request merged**
