### PR TITLE
Allow local reference to other image

### LINKED ISSUE #7792: Cannot pull from istag referencing image in another repository of internal registry
Reproducer:

    $ docker tag docker.io/hello-world 172.30.104.152:5000/tmp/hello-world:latest
    $ docker push 172.30.104.152:5000/tmp/hello-world:latest
    The push refers to a repository [172.30.104.152:5000/tmp/hello-world] (len: 1)
    0a6ba66e537a: Pushed 
    b901d36b6f2f: Pushed 
    latest: digest: sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1 size: 2748

    $ oc tag -n tmp hello-world@sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1 mybase:latest
    Tag mybase:latest set to hello-world@sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1.

    *$ oc describe -n tmp istag
    Name:           sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Created:        2 minutes ago
    Labels:         <none>
    Annotations:    openshift.io/image.managed=true
    Docker Image:   172.30.104.152:5000/tmp/hello-world@sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Image Name:     sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Image Size:     633 B (first layer 601 B, last binary layer 32 B)
    Image Created:  4 months ago
    Author:         <none>
    Arch:           amd64
    Command:        /hello
    Working Dir:    <none>
    User:           <none>
    Exposes Ports:  <none>
    Docker Labels:  <none>

    Name:           sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Created:        2 minutes ago
    Labels:         <none>
    Annotations:    openshift.io/image.managed=true
    Docker Image:   172.30.104.152:5000/tmp/hello-world@sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Image Name:     sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Image Size:     633 B (first layer 601 B, last binary layer 32 B)
    Image Created:  4 months ago
    Author:         <none>
    Arch:           amd64
    Command:        /hello
    Working Dir:    <none>
    User:           <none>
    Exposes Ports:  <none>
    Docker Labels:  <none>

    $ # note the first pull is successful because all the blobs are already downloaded in Docker daemon's storage
    $ docker pull 172.30.104.152:5000/tmp/mybase:latest                                                                                                                                                                                           
    Trying to pull repository 172.30.104.152:5000/tmp/mybase ... latest: Pulling from tmp/mybase
    Digest: sha256:bb5c16ecd58633d4088140acb6ee386c5c3b09a8f03c517a288093415f0c09d1
    Status: Downloaded newer image for 172.30.104.152:5000/tmp/mybase:latest

    $ docker rmi -f 0a6ba66e537a
    Untagged: 172.30.104.152:5000/tmp/hello-world:latest
    Untagged: 172.30.104.152:5000/tmp/mybase:latest
    Untagged: docker.io/hello-world:latest
    Deleted: 0a6ba66e537a53a5ea94f7c6a99c534c6adb12e3ed09326d4bf3b38f7c3ba4e7
    Deleted: b901d36b6f2fd759c362819c595301ca981622654e7ea8a1aac893fbd2740b4c
    $ # the second pull needs to repull all the blobs and fails
    $ docker pull 172.30.104.152:5000/tmp/mybase:latest
    Trying to pull repository 172.30.104.152:5000/tmp/mybase ... latest: Pulling from tmp/mybase
    b901d36b6f2f: Pulling fs layer 
    0a6ba66e537a: Pulling fs layer 
    not found
    Error: image tmp/mybase:latest not found

Tested with Docker 1.8.2 and 1.9.1. Test to confirm this is in #7790.

See also https://github.com/openshift/origin/pull/7128#issuecomment-191754538 and https://github.com/openshift/origin/pull/7763#issuecomment-191968269 for more background.

### PR DESCRIPTION
**Pull request by legionus**
Fix #7792 

@smarterclayton @miminar @pweil- please review

### CODE REVIEW

**Comment by legionus** [comment]
[test]

**Comment by pweil-** [comment]
@soltysh

**Comment by miminar** [comment]
Pullthrough may be [disabled](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L98) in the configuration. This needs to work even in such case.

**Comment by legionus** [comment]
Yes, but by default it is enabled. If we want this to work we need to duplicate almost all of this functionality.

**Comment by soltysh** [comment]
@miminar @legionus other option is to have pullthrough enabled for this particular case always.

**Comment by miminar** [comment]
I think this is such a special case that it should be handled in its own middleware wrapper regardless of pullthrough being enabled or not. Moreover it doesn't make sense to create an http proxy for a local blob store. We should instantiate correct local repository object the context and let it serve the request directly.

**Comment by legionus** [comment]
Yes. Let's merge this fix and will lower the priority. I will make another PR to make local references always available.

**Comment by miminar** [comment]
I'm still opposed to constructing http proxy to local blob store.

**Comment by soltysh** [comment]
I've tested this fix locally and it doesn't address the problem, unfortunately. From my yesterday debugging I see the path is totally different than pullthrough, it returns [here](https://github.com/openshift/origin/blob/2ddfc71bf4f24d35afbf4085b1e26ae64bffa107/pkg/dockerregistry/server/repositorymiddleware.go#L255) and never reaches pullthrough. I'm leaning towards @miminar opposition with this approach. I still wonder if the version before pullthrough worked, does any of you guys checked that?

**Comment by legionus** [comment]
@miminar I thought about a separate middleware, but this approach seemed to me more versatile. And I'm not sure, but maybe it will be needed to work with daemonset.

**Comment by liggitt** [comment]
Does this allow escalation between namespaces via a referencing image tag?

**Comment by legionus** [comment]
@liggitt If I understand you correctly, then Yes.

**Comment by liggitt** [comment]
>> Does this allow escalation between namespaces via a referencing image tag?
>
> @liggitt If I understand you correctly, then Yes.

Currently, the registry enforces auth based on the pull spec. If I attempt to pull "/foo/bar:latest", the registry checks if I have "get imagestreams/layers" rights on namespace "foo". If this allows "bar:latest" to point to an imagestream in namespace "bar", where is the check being done that ensures I have "get imagestreams/layers" rights on namespace "bar"?

**Comment by miminar** [comment]
@liggitt the authorization check will be done as proposed in https://github.com/openshift/origin/issues/7792#issuecomment-199229554. This PR will be rewritten or replaced with a new one.

**Comment by legionus** [comment]
After discussion, we decided to go the other way.

**Pull request closed without merging**
