### PR TITLE
STOR-1425: Update to Kubernetes 1.28

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-aws-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-driver-toolkit: 99546b94-6cc7-4e03-8c15-2a21a0f2c923
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-single-node
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-azure-sdn
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-azure-upgrade-cnv: 58d63ba6-2206-4193-be28-f71e58e41da2
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-serial-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-csi
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-sdn
/payload-job periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade

**Comment by soltysh** [comment]
We got green gcp-ovn-upgrade in https://pr-payload-tests.ci.openshift.org/runs/ci/ebf66820-5964-11ee-88a9-125429a75a30-0

/override ci/prow/e2e-gcp-ovn-upgrade

**Pull request merged**
