### PR TITLE
fix skip from https://github.com/openshift/origin/pull/23253 so as to…

### PR DESCRIPTION
**Pull request by gabemontero**
… not skip jenkins e2e

/assign @bparees 

@deads2k @adambkaplan fyi

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

but if this file is the future of running these tests, let's rename it in the future.....  it's not an api version compatibility test any more, it's just how we're running what used to be integration tests (i guess?)

**Comment by gabemontero** [comment]
/hold

until I can confirm tests are actually executed

**Comment by gabemontero** [comment]
e2e-aws-jenkins tests are still running but I was able to confirm they are no longer skipped

```
gmontero ~ $ oc logs e2e-aws-jenkins -c test
secret/support created
started: (0/1/4) "[Feature:Builds][Feature:Jenkins][Slow] openshift pipeline build jenkins-client-plugin tests using the ephemeral template [Suite:openshift]"

started: (0/2/4) "[Feature:Jenkins][Slow]jenkins repos e2e openshift using slow openshift pipeline build Sync plugin tests using the persistent template [Suite:openshift]"

started: (0/3/4) "[Feature:Jenkins][Slow]jenkins repos e2e openshift using slow openshift pipeline build Sync plugin tests using the ephemeral template [Suite:openshift]"

passed: (4m30s) 2019-06-25T19:46:45 "[Feature:Jenkins][Slow]jenkins repos e2e openshift using slow openshift pipeline build Sync plugin tests using the persistent template [Suite:openshift]"

started: (0/4/4) "[Feature:Builds][Feature:Jenkins][Slow] openshift pipeline build Sync plugin tests using the ephemeral template [Suite:openshift]"

gmontero ~ $ 
``

thx for the quick fix suggestion @bparees 

/hold cancel

**Pull request merged**
