### PR TITLE
Don't mutate build.spec in API when creating build pod

### LINKED ISSUE #2977: Build spec.output.to mutates from ImageStream to DockerImage during run
Introduced in https://github.com/openshift/origin/commit/41596110b6d279fa130319b8d80e8d47f032d8ae#diff-661252da3ac92a7bc8779d5eee2f7601 which sets dockerreference and deletes output.to when creating the build pod

This confuses the UI, which associates builds with deployment triggers (https://github.com/openshift/origin/issues/2975)

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #2977

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton review

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Comment by smarterclayton** [comment]
These might actually be real failures

**Comment by liggitt** [comment]
unmerged, need to fix test

**Comment by liggitt** [comment]
updated tests, [merge]

**Pull request merged**
