### PR TITLE
strip template prefix from TSB annotations

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/16755

### CODE REVIEW

**Comment by bparees** [comment]
/assign @jim-minter 
/unassign @gabemontero @danwinship 

@jim-minter ptal, i will need to update the upstream templates too but i wanted to at least ensure all the local ones are consistent with the new code first.  Once this merges i'll update the upstream templates.

**Comment by jim-minter** [comment]
@bparees have lgtm'd this, but wondering why you didn't straight remove the consts from pkg/template/apis/template/constants.go?

**Comment by bparees** [comment]
> @bparees have lgtm'd this, but wondering why you didn't straight remove the consts from pkg/template/apis/template/constants.go?

i'm leaving support for the old values in the TSB until i get the upstream templates updates to not use it.  some loose semblance of backwards compatibility.

but i'll remove it before 3.7 ships.

@rcernich fyi, not sure if your templates have the template.openshift.io annotations in them, but we're renaming them as seen here.

**Comment by rcernich** [comment]
@bparees, will the old annotations continue to work?  Which version is this change targeted at?

**Comment by bparees** [comment]
> @bparees, will the old annotations continue to work? Which version is this change targeted at?

@rcernich the old annotations will not continue to work, we're just changing the behavior since we never supported the old behavior.  this will be the first time the TSB GAs.  this will be for 3.7.

**Comment by rcernich** [comment]
@bparees, thanks.  Looks like we're not using the "template" prefix, so hopefully, we're good to go.

**Pull request merged**
