### PR TITLE
Simplify the deploy trigger int test

### PR DESCRIPTION
**Pull request by ironcladlou**
The deploy trigger test got complicated at some point. Simplify it.

The only thing that needs tested here is whether the ImageStream event results in a newly generated DeploymentConfig.

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @abhgupta 

cc @ncdc just in case since you seem to have touched this when you re-enabled the tests.

**Comment by abhgupta** [comment]
[merge] LGTM

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
[merge], this was a casualty of flakes which have been fixed

**Pull request merged**
