### PR TITLE
Add --local & --dry-run flags to `oc set` sub-commands

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/36071
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1390139

Related PR (adds `--local` and `--dr-run` flags to `oc set resources`): https://github.com/openshift/origin/pull/11694

Partially addresses: https://github.com/openshift/origin/issues/7899

some `oc set ...` sub-commands do not implement `--dry-run` or `--local`
options. This patch adds these missing options to all sub-commands and
ensures that backwards compatibility remains for commands that treat the
--output option as a ``dry-run flag.

##### Example
```
$ oc set image dc dctest dctest-1=default/testimage:latest --dry-run
NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
dctest    1          1         1         config

$ oc set image dc dctest dctest-1=default/testimage:latest -o name
deploymentconfig/dctest

$ oc set build-secret mysecret --push --all -o
custom-columns=NAME:.metadata.name
NAME
gitauthtest
repo-base

$ oc set build-secret mysecret --push --all --dry-run
NAME          TYPE      FROM      LATEST
gitauthtest   Source    Git       1
NAME        TYPE      FROM      LATEST
repo-base   Docker    Git       8
```

##### Affected commands

- [x] `oc set build-hook`
- [x] `oc set image` (Also fixed upstream in https://github.com/kubernetes/kubernetes/pull/36071)
- [x] `oc set probe`
- [x] `oc set resources` (fixed in https://github.com/openshift/origin/pull/11694)
- [x] `oc set triggers`
- [x] `oc set volume`
- [x] `oc set env`
- [x] `oc set deployment-hook`
- [x] `oc set build-secret`
- [x] `oc set route-backends`

Restoring https://github.com/openshift/origin/pull/11733

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
flake https://github.com/openshift/origin/issues/14122 re[test]

**Comment by fabianofranz** [comment]
[merge] tks @juanvallejo!

**Comment by smarterclayton** [comment]
This requires `--local`, but `--local` doesn't behave correctly after this PR for `oc set probe` or several others - just fails if the server is down.

**Comment by smarterclayton** [comment]
Local means "doesn't require a running server"

**Pull request merged**
