### PR TITLE
UPSTREAM: 15944: DaemonSet controller modifies the wrong fields

### PR DESCRIPTION
**Pull request by smarterclayton**
Extracted from #5107

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
FAILURE: Generation of fresh spec failed:
[INFO] Creating certificates for the OpenShift server
/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 78: openshift: command not found
!!! Error in /data/src/github.com/openshift/origin/hack/../hack/util.sh:78
	'openshift admin ca create-master-certs --overwrite=false --cert-dir="${MASTER_CONFIG_DIR}" --hostnames="${SERVER_HOSTNAME_LIST}" --master="${MASTER_ADDR}" --public-master="${API_SCHEME}://${PUBLIC_MASTER_HOST}:${API_PORT}"' exited with status 127
Call stack:
	1: /data/src/github.com/openshift/origin/hack/../hack/util.sh:78 configure_os_server(...)
	2: /data/src/github.com/openshift/origin/hack/update-generated-swagger-spec.sh:46 main(...)
Exiting with status 1
```

This is back

[test]

**Comment by smarterclayton** [comment]
```
See 'new-app' for examples.
error: component "mongo" had only a partial match of "mongodb" - if this is the value you want to use, specify it explicitly
!!! Error in test/cmd/newapp.sh:18
	'[ "$(oc new-app mongo -o yaml | grep library/mongo)" ]' exited with status 1
Call stack:
	1: test/cmd/newapp.sh:18 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:2
```

@csrwng this is new

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by liggitt** [comment]
pretty sure the upstream PR was wrong. see https://github.com/kubernetes/kubernetes/pull/15944/files#r43844930

**Pull request merged**
