### PR TITLE
fixing/removing "to to" from help texts and comments

### PR DESCRIPTION
**Pull request by goern**
This is a trivial change. I stumbled upon there 'to to's while using the `oc` command...

### CODE REVIEW

**Comment by mfojtik** [comment]
flake: https://github.com/openshift/origin/issues/16716

**Comment by mfojtik** [comment]
@goern you need to do the change in `shell_parser.go` in openshift/imagebuilder repo and then bump the godep.

**Comment by goern** [comment]
@mfojtik  one done, how to bounce the godeps? #newbiequestionasked

**Pull request closed without merging**
