### PR TITLE
Bump registry

### LINKED ISSUE #4415: Unable to push to internal registry using Docker 1.8 due to "Error parsing HTTP response: invalid character 'M' looking for beginning of value: "Method not allowed\n""
Env:
---
~~~
$ openshift version
openshift v1.0.5-73-g29f82f4
kubernetes v1.1.0-alpha.0-1605-g44c91b1
~~~

~~~
$ docker version
Client:
 Version:      1.8.1.fc21
 API version:  1.20
 Package Version: docker-io-1.8.1-2.git32b8b25.fc21.x86_64
 Go version:   go1.4.2
 Git commit:   32b8b25/1.8.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1.fc21
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   32b8b25/1.8.1
 Built:        
 OS/Arch:      linux/amd64
~~~

**NOTE**: I tested on Fedora21 with docker 1.8. But I could reproduce CentOS7 with docker 1.8

Issue:
---
- With docker v1.8, S2I build failed because it can't push to docker reigstry with this error

~~~
"Error parsing HTTP response: invalid character 'M' looking for beginning of value: "Method not allowed\n""
~~~

- Please see [entire log](https://paste.fedoraproject.org/260763/)

Reproduce steps:
---
- step-1. Running docker 1.8

- step-2. Running openshift (in my case stndalone mode)

- step-3. Run S2I
  - eg) `oc new-app https://github.com/nak3/helloworld-v3.git -l app=hello`
  - I tested `oc new-app https://github.com/openshift/sti-python.git --context-dir=3.3/test/standalone-test-app -l app=python --strategy=source`, but same result.
  - I tested Custom storategy but it is same result.

- step-4. Check build log (pushing to the docker registry failed due to the invalid character error)

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #4415

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
@ncdc @pweil-

**Comment by kargakis** [comment]
```
$ docker version
Client:
 Version:      1.8.1.fc21
...

$ oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-2dgil    1/1       Running   0          11s
docker-registry-1-deploy   1/1       Running   0          14s

$ oc new-app https://github.com/openshift/sti-python.git --context-dir=3.3/test/standalone-test-app -l app=python --strategy=source
W0904 09:27:49.466080    1677 pipeline.go:245] A service will not be generated for DeploymentConfig "sti-python" because no exposed ports were detected. Use 'oc expose dc "sti-python" --port=[port] --generator=service/v1' to create a service.
imagestreams/python
imagestreams/sti-python
buildconfigs/sti-python
deploymentconfigs/sti-python
Build "sti-python" created and started - you can run `oc status` to check the progress.
Run 'oc status' to view your app.

$ oc build-logs sti-python-1
F0904 09:29:01.862796       1 builder.go:47] Build error: image "library/python@sha256:b0cb2aa05ba50d9a02baf1f5bfdb2d27ef787a20e62555f55d8467c382a67b87" must specify a user that is numeric and within the range of allowed users
```

**Comment by ncdc** [comment]
@smarterclayton the bump from docker/distribution v2.0.0 to v2.0.1 does have 3 Godep bumps (https://github.com/docker/distribution/compare/v2.0.0...v2.0.1#diff-681659ab9abb4b4883e78e8aaa980dba):

- github.com/AdRoll/goamz/aws
- github.com/AdRoll/goamz/cloudfront (we aren't importing this currently)
- github.com/AdRoll/goamz/s3

Should we make sure we have at least the same hashes or newer for the aws and s3 deps?

**Comment by ncdc** [comment]
@kargakis I saw that Jenkins passed, so that's good. I'm assuming that `Build error: image "library/python@sha256:b0cb2aa05ba50d9a02baf1f5bfdb2d27ef787a20e62555f55d8467c382a67b87" must specify a user that is numeric and within the range of allowed users` is unrelated to this change?

**Comment by kargakis** [comment]
Hmm, i processed and created `application-template-stibuild.json` and I still get 
```
I0904 11:27:11.030504       1 sti.go:151] Pushing 172.30.232.91:5000/test/origin-ruby-sample:latest image ...
F0904 11:27:12.914053       1 builder.go:47] Build error: Failed to push image: Error parsing HTTP response: invalid character 'M' looking for beginning of value: "Method not allowed\n"
```

**Comment by ncdc** [comment]
Are you running the registry image from your branch? I was getting that
before I realized that I was running the wrong image.

**Comment by ncdc** [comment]
LGTM

**Comment by smarterclayton** [comment]
Yes

On Sep 4, 2015, at 7:22 AM, Andy Goldstein <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> the bump from
docker/distribution v2.0.0 to v2.0.1 does have 3 Godep bumps (
docker/distribution@v2.0.0...v2.0.1#diff-681659ab9abb4b4883e78e8aaa980dba
<https://github.com/docker/distribution/compare/v2.0.0...v2.0.1#diff-681659ab9abb4b4883e78e8aaa980dba>
):

   - github.com/AdRoll/goamz/aws
   - github.com/AdRoll/goamz/cloudfront (we aren't importing this currently)
   - github.com/AdRoll/goamz/s3

Should we make sure we have at least the same hashes or newer for the aws
and s3 deps?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4519#issuecomment-137709816>.

**Comment by ncdc** [comment]
I'm ready to merge if everyone else is @pweil- @liggitt @smarterclayton

**Comment by mfojtik** [comment]
:+1:

**Comment by ncdc** [comment]
[merge]

**Pull request merged**
