### PR TITLE
[DO NOT MERGE] break test-cmd

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/cc @deads2k

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by deads2k** [comment]
Alright, it worked.

**Comment by stevekuznetsov** [comment]
Maybe the directory structure is different on the ami? Maybe the script doesn't have permissions to remove the directory?

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
@deads2k Still broken

**Comment by stevekuznetsov** [comment]
re[test] and hope for artifacts

**Comment by stevekuznetsov** [comment]
@deads2k We have [artifacts](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7458/artifact/origin/artifacts/cmd/lQRS/wrappers.txt)! (this succeeded because I put the `exit 1` in the wrong place.)

**Pull request closed without merging**
