### PR TITLE
Fix up SDN CNIServer startup security logic

### PR DESCRIPTION
**Pull request by danwinship**
SDN pods always log the errors:

    E0418 15:36:07.273730    2304 cniserver.go:149] failed to remove old pod info socket: remove /var/run/openshift-sdn: device or resource busy
    E0418 15:36:07.273814    2304 cniserver.go:152] failed to remove contents of socket directory: remove /var/run/openshift-sdn: device or resource busy

at startup. This is because they're trying to delete the existing cniserver directory, but it's actually a mountpoint.

The reason it wants to delete and recreate the directory is because the CNIServer socket needs to be in a mode 0700 directory or else it's not secure. But `/var/run/openshift-sdn` currently ends up being mode 0755, meaning non-root users would have access to the socket and could spoof openshift-sdn into doing certain things on their behalf.

We can't easily fix the directory permissions because it's a mountpoint. (We'd have to somehow ensure that the directory had been created with the correct permissions on the host beforehand.) So this fixes things by putting the socket into a subdir of `/var/run/openshift-sdn` instead, so we can ensure that `/var/run/openshift-sdn/cniserver` is root-readable-only even if `/var/run/openshift-sdn` isn't. This also makes openshift-sdn fail if it can't set things up correctly, rather than just logging an error and continuing

### CODE REVIEW

**Comment by danwinship** [comment]
/hold
why didn't it notice when I said (trying again...)
/test e2e-aws-upgrade

**Comment by danwinship** [comment]
@dcbw updated; see new initial comment. We were totally screwing this up before...

**Comment by danwinship** [comment]
/hold cancel
(I'd holded it because the bot wasn't picking up my request for an e2e-aws-upgrade test, but then it did)

**Comment by squeed** [comment]
This PR (and #22731) is failing pretty consistently with `level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating: timed out waiting for the condition"`

Do you think it is caused by these PRs, or is a monitoring bug?

**Comment by squeed** [comment]
Whoops, wrong PR, ignore that message.

**Pull request merged**
