### PR TITLE
backport upstream Cinder fixes

### PR DESCRIPTION
**Pull request by rootfs**
fix BZ #1427701 and #1444828

@childsb @pospispa @gnufied @eparis @sttts

### CODE REVIEW

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
@sttts test failed on `The following UPSTREAM commits modify Godeps repos other than the repo the commit declares:`

how to upgrade vendor code?

**Comment by rootfs** [comment]
opened #14009 for gophercloud upgrade.

**Comment by rootfs** [comment]
[test]

**Comment by pospispa** [comment]
LGTM

This PR is a superset of my https://github.com/openshift/origin/pull/13954 that's why I will close https://github.com/openshift/origin/pull/13954 without being merged.

**Comment by rootfs** [comment]
@childsb @eparis can you merge this? Need the fixes for a couple of BZs. Thanks.

**Comment by rootfs** [comment]
looks a transit yum repo err in CI test.
@childsb @eparis

**Comment by pospispa** [comment]
Note: I'd like to backport https://github.com/kubernetes/kubernetes/pull/44798 but I found out that this PR is a prerequisite for my backport.

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
FLAKE https://github.com/openshift/origin/issues/14122

**Comment by rootfs** [comment]
@childsb @eparis Can you merge it? There is a test flake but we need the fixes going forward. Thanks.

**Comment by eparis** [comment]
[test][merge]

**Comment by rootfs** [comment]
FLAKE https://github.com/openshift/origin/issues/8502

**Comment by eparis** [comment]
[merge]

**Pull request merged**
