### PR TITLE
Consolidate config

### PR DESCRIPTION
**Pull request by ashcrow**
Includes / requires: PR#4125

For both OpenShift and Atomic Enterprise:

- Master configs will be generated if none are found.
- Node configs will be generated if none are found as lone as the master is installed.
- All-In-One services have been removed.

### CODE REVIEW

**Comment by ashcrow** [comment]
cc @sdodson / @brenton / @devop-mmcgrath

**Comment by ashcrow** [comment]
@sdodson removed symlink and changed the sysconfigs to point to master-config.yaml for both masters.

**Comment by sdodson** [comment]
LGTM

**Comment by ashcrow** [comment]
@brenton I believe this is ready to go.

**Comment by brenton** [comment]
[merge]

**Pull request merged**
