### PR TITLE
Add an OPENSHIFT-ADMIN-OUTPUT-RULES chain for admins to use

### PR DESCRIPTION
**Pull request by danwinship**
This came out of a discussion with the Online ops people; it is currently difficult for admins to add their own iptables rules for filtering/rate-limiting/etc, because we prepend our own rule `-j ACCEPT`-ing all outgoing SDN traffic, so they have to do something like, wait for OpenShift to prepend its rule, and then prepend their own rule before it, and of course this is totally fragile against future OpenShift changes. This patch makes OpenShift create an empty chain solely for use by admins who want to add rules that apply before OpenShift's rules (since this seemed like something other users might want too).

Trello card: https://trello.com/c/dnZHuI5R

This conflicts with #13465 and will have to be rewritten if that merges first, but we'll still want to commit this version of the patch to 3.5 anyway.

@openshift/networking PTAL

### CODE REVIEW

**Comment by eparis** [comment]
$bikeshed: Is that a good name. It seems like OPENSHIFT is the on who would add rules to the chain. Not a huge deal to me. Don't bikeshed on that more than a minute or so...

**Comment by danwinship** [comment]
Entirely valid point, especially since #13465 defines three chains with OPENSHIFT in the name that we *don't* want people editing. But in both cases the intent was to make it obvious who was creating the chain, and to avoid conflicts with other chains (the same way upstream prefixes all its chains with "KUBE").

Maybe add "ADMIN" or "USER" to the chain name? And shorten "OPENSHIFT" to "OS" to compensate... Although "OS-ADMIN-OUTPUT-FILTERING" sounds like it's for filtering administrators or "administrator output".

**Comment by dcbw** [comment]
I think it should have OPENSHIFT somewhere in the name, since that's what's making the chain and that's the purpose of the chain.  Could just do "OPENSHIFT-ADMIN-OUTPUT-FILTER" to keep it under 30 chars.

**Comment by danwinship** [comment]
I went with OPENSHIFT-ADMIN-OUTPUT-RULES... That seems pretty clear I think?

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
[merge]... last failed due to "FAILURE: Generated bootstrap bindata out of date. Please run hack/update-generated-bindata.sh" which can not be related.

**Comment by danwinship** [comment]
flake #14334 [merge]

**Pull request merged**
