### PR TITLE
Bug 1719044: client switch between 3.7 and 3.9 broke creation of clus…

### PR DESCRIPTION
**Pull request by gabemontero**
…ter level resources; ensure namespace is empty string for cluster level resources

@openshift/sig-developer-experience 

/assign @adambkaplan 

cherry pick of fix to 4.1.z

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
the change appears to have already been verified in 4.2 per https://bugzilla.redhat.com/show_bug.cgi?id=1718412

/cherry-pick-approved

**Comment by gabemontero** [comment]
master PR https://github.com/openshift/origin/pull/23047 merged 8 days ago

**Comment by eparis** [comment]
Looks like this didn't actually get the label last time. Whoops.

**Pull request merged**
