### PR TITLE
azure fixes

### PR DESCRIPTION
**Pull request by rootfs**
@childsb @eparis

### CODE REVIEW

**Comment by rootfs** [comment]
[test]

**Comment by rootfs** [comment]
[merge]

**Comment by gnufied** [comment]
lgtm!

**Comment by eparis** [comment]
last [test] looks like https://github.com/openshift/origin/issues/12007
go ahead and [merge]

**Comment by smarterclayton** [comment]
Is this included in the rebase or slated for after?

**Comment by smarterclayton** [comment]
[merge]

**Comment by weherdh** [comment]
@rootfs Hi, some colleagues met this issue these days, when we will merge this PR and provide the fix? Thanks

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Several flakes, all known

**Pull request merged**
