### PR TITLE
extended: deployment with multiple containers using a single ICT

### PR DESCRIPTION
**Pull request by kargakis**
The instantiate PR fixed https://bugzilla.redhat.com/show_bug.cgi?id=1381833, this PR adds a test that verifies the fix. @mfojtik ptal

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by mfojtik** [comment]
@kargakis LGTM, thanks for removing the conformance tags

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/11240 and https://github.com/openshift/origin/issues/11094 [merge]

**Pull request merged**
