### PR TITLE
UPSTREAM: 46460: Add configuration for encryption providers

### PR DESCRIPTION
**Pull request by php-coder**
A follow-up to #14517: backport of https://github.com/kubernetes/kubernetes/pull/46460 Without this change it's impossible to pass an encryption config location to the apiserver.

PTAL @smarterclayton @simo5

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM once you fix the completions

**Comment by smarterclayton** [comment]
[severity:blocker] for encryption testing [merge]

**Comment by php-coder** [comment]
[[security] [SCCFSI] Encrypt secrets at REST in etcd](https://trello.com/c/yhuQZ3NP/905-security-sccfsi-encrypt-secrets-at-rest-in-etcd)

**Pull request merged**
