### PR TITLE
Push recycler image

### PR DESCRIPTION
**Pull request by liggitt**
Include new recycler image in push list.

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton PTAL
@brenton not sure if this script is used for OSE images or not

**Comment by ncdc** [comment]
LGTM

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by brenton** [comment]
@liggitt, it's not use for OSE but thanks for the heads up.

**Comment by liggitt** [comment]
@smarterclayton green jenkins, your call

**Comment by smarterclayton** [comment]
I'm going to grab this and a few others - I like Jessica's UI changes

**Pull request merged**
