### PR TITLE
remove route host since online does not tolerate it.

### PR DESCRIPTION
**Pull request by bparees**
bug 1504518

https://bugzilla.redhat.com/show_bug.cgi?id=1504518

### CODE REVIEW

**Comment by yapei** [comment]
@bparees  Hi Ben, any reason we closed the PR ?  I thought the customized route host would be removed from our origin templates after your PR merged 😄

**Comment by bparees** [comment]
@yapei i closed it due to the comment i put in the bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1504518#c5

**Pull request closed without merging**
