### PR TITLE
Add an option to oc project to print as shell var

### PR DESCRIPTION
**Pull request by chmouel**
Add an option so oc project can show as shell variables so easily
sourcable from shell.

### CODE REVIEW

**Comment by deads2k** [comment]
Can you add some detail about this is needed?  It's not obvious to me why I would want to do this instead of simply using my kubeconfig file.

**Comment by smarterclayton** [comment]
Since we don't read those values they aren't as helpful as they could be - could we instead support a -o output method that had the ability to do all the output we have today, and then make the current context easy?  I.e. the `-o jsonpath={}` syntax.  I'm not opposed though to `oc config view` having flags that specifically print the following:

* user name
* current context
* current server

**Comment by smarterclayton** [comment]
I'm not opposed to current context or server or user being part of *some* command

**Comment by deads2k** [comment]
`oc config view` already supports golang templates and upstream added a current-context command.

**Comment by smarterclayton** [comment]
These seem like flags on config view to me - getting access to the four
most common things you'd want to script isn't unreasonable.  Templates make
sense for other commands because there are lots and lots of fields

**Comment by deads2k** [comment]
> These seem like flags on config view to me - getting access to the four
> most common things you'd want to script isn't unreasonable.  Templates make
> sense for other commands because there are lots and lots of fields

Upstream wants to revamp `kubectl config` with https://github.com/kubernetes/kubernetes/issues/20605 .

@chmouel I don't think we want to add a flag like this instead.  You can use `oc config view --template='golang template'` to pull specific values.

**Pull request closed without merging**
