### PR TITLE
Fix dangling commas in example json files

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees can you review?

**Comment by mfojtik** [comment]
LGTM

We should also run JSON formatter for all JSON files we have to make them all consistent. Something like http://stedolan.github.io/jq

**Comment by mfojtik** [comment]
@csrwng thanks for doing this, it was on my TODO list as everytime I opened a JSON we have in vim, syntactic plugin screams with formatting errors ;-)

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by csrwng** [comment]
This works for me for finding issues in the current directory:
```
for f in *.json; do echo $f; cat $f | python -m json.tool > /dev/null; done
```

**Pull request merged**
