### PR TITLE
sdn should ignore containers that have net=host

### PR DESCRIPTION
**Pull request by rajatchopra**
reflecting changes from upstream sdn

### CODE REVIEW

**Comment by danmcp** [comment]
[test] and [merge]

**Comment by danmcp** [comment]
@smarterclayton FYI

**Comment by smarterclayton** [comment]
If we keep openshift SDN around much longer that bash file needs to be something we make a lot more maintainable and "real"

**Comment by danmcp** [comment]
@smarterclayton https://github.com/openshift/openshift-sdn/pull/87

**Comment by danmcp** [comment]
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1232718

**Comment by smarterclayton** [comment]
This doesn't actually fix the ip origin problem?

**Comment by danmcp** [comment]
@smarterclayton It's to allow the router pod to use the setting.

**Comment by smarterclayton** [comment]
Which makes sense, but is this a fix for the origin ip issue

**Comment by rajatchopra** [comment]
No, this issue does not solve the origin ip issue by itself. But if we use the solution in #3297, then this one better be in too.

**Comment by smarterclayton** [comment]
The docker proxy blocking the source IP is the information I was looking for.  I don't have an objection to using the host network other than the impact that has on the rest of the cluster.  For instance, is a pod ip set in the pod status?  If not, the internal router service won't resolve.  It may also mean health checks aren't accurate or have bugs.  How will we measure it?

**Comment by rajatchopra** [comment]
@smarterclayton You are right. The pod IP will not be set because docker inspect will not return anything. Internal router service will not resolve.

**Comment by smarterclayton** [comment]
When the router binds, it's going to bind to all addresses on the host.  Is that what we want?  Or is the router going to have to bind to a specific ip?

**Pull request merged**
