### PR TITLE
Cleanup all asset related files in origin

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett @liggitt since github cant handle the diff very well, this pr:

- removes everything under assets/ except for a README.md that points people to the new repo
- deletes all the old hack/*-assets.sh scripts, the only script there now should be vendor-console.sh
- moves the doc.go (which explains what the assets go pkg does) and assets.go (which has the godep import for go-bindata) under the pkg/assets/ dir where they probably should have been to begin with

**Comment by jwforres** [comment]
[test]

**Comment by deads2k** [comment]
`hack/verify-gofmt.sh | xargs -n 1 gofmt -s -w'`

**Comment by jwforres** [comment]
@deads2k thanks fixed

**Comment by spadgett** [comment]
Would be nice to have instructions for vendoring in assets/README

Asset changes LGTM. Will defer to @liggitt and @deads2k on the go changes.

**Comment by deads2k** [comment]
ret[test] for conformance.

**Comment by deads2k** [comment]
lgtm, just want to see conformance do something normal.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
