### PR TITLE
increase the podLogTimeout for downward volume test

### PR DESCRIPTION
**Pull request by mfojtik**
Increase timeout for the test based on https://github.com/kubernetes/kubernetes/pull/33165

### CODE REVIEW

**Comment by mfojtik** [comment]
Based on the linked issue, this depends on the sync-internal, but not sure which one. 

@jsafrane @smarterclayton any ideas?

**Comment by mfojtik** [comment]
/retest

prometheus flake...

**Comment by deads2k** [comment]
open this upstream

**Comment by mfojtik** [comment]
/retest

@deads2k i will, need to make sure this fixes it, will run couple more retests, but so far this PR didn't hit the flake (other PR's are flaking hard on this).

**Comment by mfojtik** [comment]
@deads2k @jsafrane ok, this seems to fix that flake, I haven't seen it in any test run here.

**Comment by mfojtik** [comment]
@deads2k upstream: https://github.com/kubernetes/kubernetes/pull/57099

I haven't seen this flake here, so this might fix it.

**Pull request merged**
