### PR TITLE
disable broken test

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by wking** [comment]
[An example][1] of what this is dodging:

```
=== RUN   TestIntegration/TestRegistryClientAPIv1
=== PAUSE TestIntegration/TestRegistryClientAPIv1
=== CONT  TestIntegration/TestRegistryClientAPIv1
    --- FAIL: TestIntegration/TestRegistryClientAPIv1 (0.96s)
        runner_test.go:129: FAILED TestRegistryClientAPIv1, retrying:
            
                dockerregistryclient_test.go:246: openshift/schema-v1-test-repo was pushed by Docker 1.8.2
                dockerregistryclient_test.go:207: error retrieving tag: server returned 503
            
            === OUTPUT
            
            I0507 20:53:58.449311   30859 client.go:493] Getting repository openshift/origin-not-found from https://registry.hub.docker.com
            I0507 20:53:58.634619   30859 client.go:493] Getting repository openshift/schema-v1-test-repo from https://registry.hub.docker.com
        runner_test.go:125: 
                dockerregistryclient_test.go:246: openshift/schema-v1-test-repo was pushed by Docker 1.8.2
                dockerregistryclient_test.go:207: error retrieving tag: server returned 503
            
            === OUTPUT
            
            I0507 20:53:58.977906   30874 client.go:493] Getting repository openshift/origin-not-found from https://registry.hub.docker.com
            I0507 20:53:59.081769   30874 client.go:493] Getting repository openshift/schema-v1-test-repo from https://registry.hub.docker.com
```

A commit message / PR subject like `test/integration/dockerregistryclient: Disable v1 API test` or some such might be more specific ;).

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22771/pull-ci-openshift-origin-master-integration/6274

**Comment by bparees** [comment]
It's going to get reverted as soon as we get to the bottom of the failure,
I wasn't too worried about the commit history...


Ben Parees | OpenShift

**Comment by bparees** [comment]
failures unrelated to this test-code only change and this is blocking people, manually merging.

**Pull request merged**
