### PR TITLE
Ensure default ingress cidr is a private range

### PR DESCRIPTION
**Pull request by marun**
Addresses #12313

cc: @openshift/networking 

Doc updates: https://github.com/openshift/openshift-docs/issues/3441

### CODE REVIEW

**Comment by marun** [comment]
This was an oversight on my part.  I followed the suggestion from https://github.com/openshift/origin/issues/10387#issuecomment-239563195 without double checking it was a private range.  This change and the doc change should ensure future installations work as expected.

**Comment by knobunc** [comment]
[test]

**Comment by eparis** [comment]
[merge]

**Comment by danwinship** [comment]
should that be a const somewhere rather than hardcoding it in 3 places?

**Comment by smarterclayton** [comment]
This is not compatible with old clusters - changing the default means that anyone who set this up and got the value defaulted from their config will now see a different value if you change it.

**Comment by smarterclayton** [comment]
Removing merge.

**Comment by smarterclayton** [comment]
Please link the doc updates here and make sure it's in the next release notes (any clusters deployed with the old value are broken on update)

**Comment by smarterclayton** [comment]
Next origin release notes, that is.  Breaking API change approved.

**Comment by marun** [comment]
Added constant as per @danwinship.  I'm not confident that it's defined in the right place, though.

**Comment by marun** [comment]
@smarterclayton If old clusters will be broken on update, do defaults that aren't explicitly set not get written into the serialized config?

**Comment by smarterclayton** [comment]
An admin has to actually generate a serialized config with the defaults.  An old config (from v1.0) would have the default value internally, but the file on disk would not have the default.  Various upgrade actions may have led to it getting written, but we can't assume it.

Basically, defaults are part of public API and changing them breaks old clusters.  Exception granted in this case because:

1. Extremely unlikely users used this by default except in test / dev environments
2. It's a security risk to use this default
3. You will be writing up very good documentation and ensuring all potentially users affected will be able to react :)

It would be good in the doc/errata/upgrade warnings to describe exactly what happens if the cluster gets restarted with a different default ip range (i.e. are all their external IPs changed, which could result in production apps no longer taking traffic), etc etc.

**Comment by marun** [comment]
So should the pr for openshift-docs be updated to include mention of the impact of a cidr change?  And where should errata/upgrade warnings go?

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
@marun: I would say the docs should be updated to cover that.  As to the errata procedure, I'm not sure.

**Comment by smarterclayton** [comment]
For the next origin release notes (if this gets backported to 1.4, or 1.5)
there has to be a clear must upgrade section.  The release notes for 1.5 (
OpenShift 1.5/3.5 Release Notes Tracker)
<https://github.com/openshift/openshift-docs/issues/3404> or 1.4 (OpenShift
1.4/3.4 Release Notes Tracker
<https://github.com/openshift/openshift-docs/issues/2933>) should include
it.

**Pull request merged**
