### PR TITLE
os/Dockerfile: Use dnf, pin repos, and clean cache

### PR DESCRIPTION
**Pull request by ashcrow**
- Clean the dnf/yum cache before running commands
- Pin Fedora repos
- Call dnf directly instead of yum

### CODE REVIEW

**Comment by ashcrow** [comment]
```
Error getting repository data for built, repository not found
```

**Comment by ashcrow** [comment]
I'm looking to see where `built.repo` is defined. I'm wondering if it may have been accidentally removed somewhere but is still expected by this build.

**Comment by ashcrow** [comment]
Looks like `f29` required in the name for other dependencies in the CI set up. Switched back to f29 to see if it passes.

**Comment by ashcrow** [comment]
Looking to pin repos instead of using mirrors.

**Comment by ashcrow** [comment]
The image builds fine, just need to get past the other CI targets.

**Comment by ashcrow** [comment]
`no such image` :confused: 

/test e2e-cmd

**Comment by jlebon** [comment]
Is the motivation here using mirrors because they can flake? If a build observes many of them failing in a single run, there might something else wrong which using a specific mirror won't fix.

**Comment by ashcrow** [comment]
@jlebon more or less yes. The Fedora mirrors have been flaky at random times causing significant failures.

**Comment by ashcrow** [comment]
`s: "error waiting for the pod 'test-cmd' to complete: the pod errored trying to run the command",`

/test e2e-cmd

**Comment by ashcrow** [comment]
Failed: ```
[Suite:openshift/test-cmd][Serial][Disruptive] test-cmd: test/cmd/policy-storage-admin.sh [Suite:openshift] expand_less
```

/test e2e-cmd

**Comment by cgwalters** [comment]
Ultimately though, if we're going to use Fedora content in CI, we need to make the mirroring more robust, not work around it at every call site.

That said another way to work around this would be changing the system to use coreos-assembler instead like https://github.com/openshift/machine-config-operator/pull/682

**Comment by ashcrow** [comment]
> Ultimately though, if we're going to use Fedora content in CI, we need to make the mirroring more robust, not work around it at every call site.

True. This PR is attempting to work around the pain for the short term, not a forever fix.

**Comment by vrutkovs** [comment]
```
FAILURE after 0.000s: test/cmd/basicresources.sh:175: executing 'oc set probe -f /var/tests/test/cmd/testdata/hello-openshift/hello-pod.json --local -o yaml --liveness --get-url=https://127.0.0.1:port/path' expecting success and text 'port: port': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
error: --get-url could not be parsed as a valid URL: parse https://127.0.0.1:port/path: invalid port ":port" after host
[ERROR] hack/lib/cmd.sh:241: `return "${return_code}"` exited with status 1.
```
/retest

**Comment by jlebon** [comment]
I guess if it helps in the short-term...
/approve

(But again, it's not clear to me if this would fix the original issue. IIRC, multiple mirrors were failing in a single run, right?)

**Pull request closed without merging**
