### PR TITLE
Rename service-serving-cert-signer to service-ca

### PR DESCRIPTION
**Pull request by mrogers950**
These changes go along with https://github.com/openshift/service-serving-cert-signer/pull/21 but requires some coordination with the repo.  The following will be needed:

- [ ] Rename of repo: github.com/openshift/service-serving-cert-signer to github.com/openshift/service-ca
- [ ] Land https://github.com/openshift/service-serving-cert-signer/pull/21, release origin-service-ca image
- [ ] Update origin-service-ca image version https://github.com/openshift/origin/blob/master/install/openshift-service-cert-signer-operator/install.yaml#L67
- [x] Vendor in openshift/service-ca to replace openshift/service-serving-cert-signer deps (I think these deps may be removed instead?) 
- [x] Update remaining service-cert-signer reference used by https://github.com/openshift/origin/pull/20868: https://github.com/openshift/origin/pull/20868/files#diff-30124ef0b7c47ee691dfd10c07a38276R14
@openshift/sig-master @openshift/sig-security @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
@simo5 please confirm you want this for 3.11

**Comment by sttts** [comment]
❤️ for the rename.

**Comment by mrogers950** [comment]
end_to_end and extended_clusterup will fail until we push an openshift/origin-service-ca image

**Comment by mrogers950** [comment]
Rebased and updated the namespace/secret references added in #20868 to take care of checklist item 4.

**Pull request closed without merging**
