### PR TITLE
Link to the github page for github repositories

### PR DESCRIPTION
**Pull request by mnagy**
This is the first shot at https://trello.com/c/EYjk0mU7/455-3-add-links-for-build-artifacts-uicomp-codefreeze

If you want to review the regex, this migth be handy: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp

### CODE REVIEW

**Comment by bparees** [comment]
@jcantrill @csrwng if one of you has a few minutes can you take a peek at this and let @mnagy know if he's on the right track?  Thanks.

**Comment by csrwng** [comment]
lgtm

**Comment by mnagy** [comment]
Rebased and fixed bindata.go. Also added an -u flag to asset diff test, just to make it more readable.

@csrwng PTAL

**Comment by bparees** [comment]
are you going to link commits, images, etc in a different PR?

**Comment by mnagy** [comment]
@bparees Yeah, I think I'd prefer that.

**Comment by mnagy** [comment]
@bparees @csrwng ok, so is the bottom line that it's ok as it is, with regards to linking?

**Comment by csrwng** [comment]
@mnagy yes

**Comment by mnagy** [comment]
OK, in that case, can we get this merged?

**Comment by bparees** [comment]
@mnagy @csrwng aren't you still only linking github.com urls?  i thought we agreed in the discussion we should link all urls.

**Comment by mnagy** [comment]
@bparees any url that's https will also be linked, without any modifications.

**Comment by bparees** [comment]
@mnagy ok got it.
[merge]

**Pull request merged**
