### PR TITLE
images: include package containing  thin_ls in base

### LINKED ISSUE #10940: Seeing thin_ls errors from v1.3.0
@ncdc @derekwaynecarr what does this mean?

```
E0916 02:07:46.850102    4248 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
output:

I0
```

### PR DESCRIPTION
**Pull request by sjenning**
Fixes #10940 

@derekwaynecarr @ncdc @smarterclayton @lukegb @marekjelen @PiotrKlimczak

Testing notes:
```
make release
hack/build-base-images.sh
hack/build-images.sh
oc cluster up --version=latest
docker exec -ti <origin-id> /bin/sh
which thin_ls
```

### CODE REVIEW

**Comment by ncdc** [comment]
lgtm

**Comment by smarterclayton** [comment]
Did this build correctly on RHEL?

**Comment by smarterclayton** [comment]
Just want to make sure the packages are in place.

**Comment by sjenning** [comment]
@smarterclayton trying to build on RHEL now just to be sure.  If I can ever get my test machine registered with subscription-manager...

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
