### PR TITLE
Use versioned object when recording changes using --record

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes BZ 1372653

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis @soltysh @smarterclayton @fabianofranz PTAL (submitting upstream PR for this)

This is fixing a regression in `oc patch`

**Comment by liggitt** [comment]
definitely needs a test

**Comment by mfojtik** [comment]
@liggitt will add one in test-cmd

**Comment by liggitt** [comment]
would like a unit test if possible as well, so upstream can share the same test

**Comment by mfojtik** [comment]
@liggitt I will add unit test in upstream if you're ok with that (added simple test-cmd test to prove this works for both kube and origin resources)

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@liggitt unit test for kube added.

**Comment by mfojtik** [comment]
[test]

**Comment by ncdc** [comment]
Is this still for 1.4?

**Comment by mfojtik** [comment]
(was already picked in the rebase.)

**Pull request closed without merging**
