### PR TITLE
Log an error when config data contains unknown fields

### LINKED ISSUE #19914: master-config.yaml with invalid keys are not validated
Sometimes our users put keys in YAML in subtly incorrect indentation. This does not cause any validation errors or anything like that and master controllers start just fine but intended purpose of putting the key in YAML does not work.

YAML being whitespace senstive makes it harder to notice. Can we just start validating the keys in YAML and print warning or errors or even refuse to start the process if something is wrong with YAML?

Examples:
1. https://bugzilla.redhat.com/show_bug.cgi?id=1582231
2. https://bugzilla.redhat.com/show_bug.cgi?id=1570085

### PR DESCRIPTION
**Pull request by enj**
This change logs an error in the following format:

`Encountered config error json: unknown field "foobar" in object *config.MasterConfig`

when config data contains unknown fields.  It is written with the assumption that it will be changed to a fatal error at some future point (we will likely need to add some oc commands to help validate the various config objects).

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #19914

### CODE REVIEW

**Comment by enj** [comment]
/assign @deads2k @smarterclayton @sdodson @jupierce 

Note that in the time that I started working on this and actually made the PR, #19070 merged, meaning that if this was a fatal check, the `disabledFeatures: null` in all old master configs would die with `E0326 16:05:49.941695    5476 helpers.go:133] Encountered config error json: unknown field "disabledFeatures" in object *config.MasterConfig, raw JSON: ...`

**Comment by enj** [comment]
cc @soltysh I vaguely remember you complaining about a customer issue caused by a typo in a master config file...

**Comment by enj** [comment]
> I don't want errors on this. At least not yet. A warning would be ok.

So leave the PR as-is since it only glogs?

**Comment by enj** [comment]
@deads2k where is the warning code you were referring to?

**Comment by deads2k** [comment]
> @deads2k where is the warning code you were referring to?

blast from the past.   I was thinking of this: https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_master.go#L267-L275

**Comment by deads2k** [comment]
The warning method called there is used by the diagnostics too.

**Comment by soltysh** [comment]
I'd love this be in for 3.11!

**Comment by enj** [comment]
@soltysh @stevekuznetsov who do we harass to get CI to be on Go 1.10?

**Comment by soltysh** [comment]
> @soltysh @stevekuznetsov who do we harass to get CI to be on Go 1.10?

@stevekuznetsov or @dobbymoodge is my wild guess :wink:

**Comment by soltysh** [comment]
But I thought we already are, since the rebase landed and it requires 1.10, no?

**Comment by enj** [comment]
The test failures are all compile errors due to CI not being on Go 1.10.

**Pull request merged**
