### PR TITLE
Append tokenSecret to serviceaccount.secrets after create tokenSecret…

### PR DESCRIPTION
**Pull request by wjiangjay**
… for dockercfgSecret

### CODE REVIEW

**Comment by liggitt** [comment]
The token secret isn't intended for direct mounting, but rather for inclusion in the dockercfg secret. Is there an issue this is resolving?

**Comment by wjiangjay** [comment]
When do automation things, some scenario want obtain all the service account token secrets from service account structure.

So if this is intended to do this, will close this patch. Just confirm with you.

Actually I forgot the secrets will be mounted to pods after appended to the service account.

**Comment by liggitt** [comment]
> When do automation things, some scenario want obtain all the service account token secrets from service account structure.

If that's what they want, they would need to list secret objects directly and filter by type/service account annotation. 

> if this is intended to do this, feel free to close this patch

Yes, this is working as intended

**Comment by wjiangjay** [comment]
@liggitt  Thanks for explain this.

**Comment by akostadinov** [comment]
@liggitt , why do we have 2 token secrets to begin with? Is it documented why we have two and what is the purpose of each one of them?

**Comment by liggitt** [comment]
one is for mounting into containers and presenting to the kubernetes API

one is for wrapping in a dockercfg secret and presenting to the in-cluster registry.

**Pull request closed without merging**
