### PR TITLE
Fix panic when tag is nil when creating istag

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik ptal

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh compilation failure: `pkg/image/registry/imagestreamtag/rest_test.go:537: too many arguments in call to storage.Create`

**Comment by smarterclayton** [comment]
I need this fixed if it is going to merge today

**Comment by smarterclayton** [comment]
Moving to #15541 which has the test fixed

**Pull request closed without merging**
