### PR TITLE
enable builds for 32-bit arm

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@maxamillion where are we using this downstream? The changes look good

**Comment by maxamillion** [comment]
@stevekuznetsov I am in Fedora, yes. If acceptable, I'd rather push upstream than carry the patch around in the Fedora package.

**Comment by maxamillion** [comment]
@stevekuznetsov I just realized I have a typo in the patch I sent to you. Pushing fix.

**Comment by stevekuznetsov** [comment]
@maxamillion can you squash and we will merge?

**Pull request closed without merging**
