### PR TITLE
CSRF updates

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k PTAL at the first two commits

@jwforres PTAL at the bindata commit... more than just my changes came in, but I assume that's because we're not re-vendoring on every commit

**Comment by deads2k** [comment]
@liggitt as I recall, this was a clean pick, right?

**Comment by liggitt** [comment]
yes

**Comment by deads2k** [comment]
This is fine then.

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/3955/ failed with https://github.com/openshift/origin/issues/7165 (`should create and run a job in user project`)

**Pull request merged**
