### PR TITLE
Use base64url to decode id_token

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of https://github.com/openshift/origin/pull/14420

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
[merge][severity:bug]

**Comment by liggitt** [comment]
```
OS_ONLY_BUILD_PLATFORMS="linux/amd64" hack/build-release.sh
/go/src/github.com/openshift/origin/hack/lib/build/environment.sh: line 67: docker: command not found
[ERROR] PID 63: hack/lib/build/environment.sh:67: `docker create ${additional_context} "${env[@]+"${env[@]}"}" "${release_image}" "${cmd[@]+"${cmd[@]}"}"` exited with status 127.
```

that seems problematic... @stevekuznetsov, are the 1.5 CI environments known to be non-functional?

**Comment by stevekuznetsov** [comment]
@liggitt no, never seen `docker` missing before... wow

**Comment by stevekuznetsov** [comment]
@kargakis we need to back-port changes to the 1.5 branch so that `hack/env make release` works on it. Right now it's trying to do a `docker` build inside of the container where there is no `docker`.

**Comment by kargakis** [comment]
> @kargakis we need to back-port changes to the 1.5 branch so that hack/env make release works on it. Right now it's trying to do a docker build inside of the container where there is no docker.

Why can't we simply change the job to not do `make release` when it's called with a branch that RPM installs are not implemented (>1.6)?

**Comment by kargakis** [comment]
But use the old scripts that `make release` was using

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
[merge][severity:blocker]

**Pull request merged**
