### PR TITLE
Disable --patch for oc update

### LINKED ISSUE #1642: osc update --patch doesn't work as advertised
```
$ _output/local/go/bin/osc  update -h
Update a resource by filename or stdin.
[...]
	# Update a pod by downloading it, applying the patch, then updating. Requires apiVersion be specified.
	$ osc update pods my-pod --patch='{ "apiVersion": "v1beta1", "desiredState": { "manifest": [{ "cpu": 100 }]}}'

Options:
  -f, --filename=[]: Filename, directory, or URL to file to use to update the resource.
      --patch='': A JSON document to override the existing resource. The resource is downloaded, patched with the JSON, then updated.
```

OK, let's try that out:

```
$ _output/local/go/bin/osc   get nodes
NAME                LABELS                  STATUS
172.16.4.110        region=infra,zone=NA    Schedulable,Ready
172.16.4.113        region=normal,zone=z1   Schedulable,Ready
172.16.4.146        region=normal,zone=z1   Schedulable,Ready
172.16.4.152        region=normal,zone=z2   Schedulable,Ready
172.16.4.158        region=normal,zone=z2   Schedulable,Ready
172.16.4.159        region=infra,zone=NA    Schedulable,Ready
$ cat > /tmp/foonode.json
{                
        "apiVersion": "v1beta1",
        "labels": {
                "region": "infra",
                "zone": "NA",
                "foo": "bar"
            }
}
$ _output/local/go/bin/osc  update node 172.16.4.110 --patch=`cat /tmp/foonode.json`
F0408 12:23:02.342063    3568 update.go:52] Error: Must provide resource and name command line params
see 'osc update -h' for help.
```

Now, it could easily be the case I did something wrong. But if so, it should tell me what that is, because I clearly followed the example and provided the parameters. If I need to add kind or name to the json, it should tell me that, not this. Or if the help is wrong, fix that and this message.

While fixing this might be a good time to also have --patch support using -f to supply a filename? Putting JSON on the cmdline is awkward.

### PR DESCRIPTION
**Pull request by kargakis**
Closes #1642, #2693 
upstream PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/8983

### CODE REVIEW

**Comment by mfojtik** [comment]
oh my favorite feature :)

**Comment by mfojtik** [comment]
LGTM

**Comment by thoraxe** [comment]
@sdodson  we may need to watch this.

**Comment by kargakis** [comment]
@smarterclayton any news on this? It's still disabled upstream and I coudln't find any PR re-enabling it...

**Comment by smarterclayton** [comment]
Approved LGTM [merge]

**Pull request merged**
