### PR TITLE
Change box url and name back

### PR DESCRIPTION
**Pull request by danmcp**

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @pmorie @mfojtik @rajatchopra I know there was some churn and confusion in here recently, just making sure everybody is aware of the changes.

**Comment by danmcp** [comment]
@ironcladlou I really want to know what that confusion was myself.  What was here previously didn't work at all.

**Comment by mfojtik** [comment]
LGTM

**Comment by danmcp** [comment]
Also what is this supposed to be:  https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_20_latest.box

**Comment by rajatchopra** [comment]
@danmcp That is the one we need for Networking to work. Has the supported kernel+OVS package installed.

**Comment by danmcp** [comment]
@rajatchopra k.  I think the right way to do this is add the packages to the vagrant-openshift plugin install steps rather than upload custom boxes.

**Comment by mfojtik** [comment]
@danmcp for all-in-one virtualbox VM, there is hack/provision-full.sh we can run as provision shell to install all needed packages.

**Comment by rajatchopra** [comment]
@danmcp We tried that, we were not able to upgrade the kernel that way. Lot of work was needed to put together the grub2config so that the latest kernel gets picked up upon reboot after the 'yum update'.

**Comment by danmcp** [comment]
@rajatchopra Ok so the second option is to update the _os image instead of building another_os image.

**Comment by rajatchopra** [comment]
@danmcp Got it. But do not merge this PR yet then, or networking will break. Will work with @ironcladlou to update the existing image.

**Comment by danmcp** [comment]
@rajatchopra Does this work at all now though?  It was checked in with box_name changed to name making vagrant up not even work for example.

**Comment by danmcp** [comment]
@rajatchopra And to be clear I am talking about the all in one case.  Not the multi minion ones.

**Comment by danmcp** [comment]
Chatted with @rajatchopra and his change was intended for only the multi minion code block.  So I am merging this to get back to a working state for the all in one scenario.

**Comment by danmcp** [comment]
[merge]

**Comment by danmcp** [comment]
@mfojtik Are you saying that's what you want to do or just that it's a workaround?

**Comment by mfojtik** [comment]
@danmcp a workaround, atm. if you are on all-in-one and you do vagrant up you end up with vanilla f20 box without packages installed (docker, golang && co), running that script manually fixes it.

**Comment by danmcp** [comment]
@mfojtik Got ya.  If you can to do that after this pull you can always origin-init with --stage=os  and then run provision.

**Pull request merged**
