### PR TITLE
Bug 1803088: 4.1: UPSTREAM: 87673: blank out value for unbounded client label

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by mfojtik** [comment]
next patch manager: this need to merge next week. ping @sttts if you need details.

**Comment by bparees** [comment]
@mfojtik per slack discussion should this be closed since 4.1 only gets very critical fixes?

**Comment by sdodson** [comment]
/close
Does not meet the merge criteria for 4.1 now that it's EOL.

**Pull request closed without merging**
