### PR TITLE
change BC ICT to automatic=true (more deterministic)

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

@php-coder @kargakis FYI

### CODE REVIEW

**Comment by bparees** [comment]
the files in the quickstarts dir shouldn't be updated manually, see the note at the end of the README.md in that dir.

also you've got an extraneous bindata.go update in the commit.

**Comment by kargakis** [comment]
LGTM

@smarterclayton @ironcladlou an ICT should always be automatic - if I set it I want it to work. Config change triggers and automatic should be collapsed into Paused. If my deployment is paused I don't want automatic, if my deployment is not paused I want template changes and icts to be able to trigger. Simple as that.

**Comment by gabemontero** [comment]
the bindata.go update was from a failure from make verify, but i'll undo the quickstarts and bindata.go, then see if that makes a difference

**Comment by liggitt** [comment]
If imageChangeParams is nil, does automatic already default to true?

**Comment by bparees** [comment]
> but i'll undo the quickstarts and bindata.go, then see if that makes a difference

get the changes to the templates merged into the upstream repos and then run the hack update script mentioned in the readme and include those changes in this PR.  the changes will almost certainly look exactly like what you did by hand, but it's preferred to use the script in case the upstream templates have diverged in other ways.

**Comment by liggitt** [comment]
Bootstrap bindata is supposed to change if quick starts change, right?

**Comment by kargakis** [comment]
> If imageChangeParams is nil, does automatic already default to true?

Automatic is part of imageChangeParams. We don't do any defaulting once imageChangeParams is set but that doesn't get into the way of the config controller: https://github.com/openshift/origin/pull/8843#issuecomment-218550661 :)

**Comment by liggitt** [comment]
I just wanted to make sure it defaults to true in the typical case where someone sets an image change trigger, and doesn't specify any parameters.

**Comment by kargakis** [comment]
Well, if you want your image trigger to work you need to set it to true and I think it's the most typical case. Maybe though you want automatic deployments on config updates but not on image updates? (where automatic: false would make sense).

**Comment by gabemontero** [comment]
@bparees ok i undid the quickstarts / bindata.go for now; I'll run `hack/update-external-examples.sh` once the *-ex merges are done

**Comment by bparees** [comment]
> Bootstrap bindata is supposed to change if quick starts change, right?

yeah, sorry @gabemontero i forgot that's the new file @csrwng introduced to embed the templates as code for his startup stuff.  so it's fine that that file changed.

**Comment by bparees** [comment]
> Maybe though you want automatic deployments on config updates but not on image updates? (where automatic: false would make sense). 

that was our intent in setting it to false because for pods with ephemeral storage, we wanted to minimize the situations under which the pod would get torn down without the user taking an explicit action.

**Comment by liggitt** [comment]
I'm talking about a trigger like this: `{"type":"ImageChange"}`

Do we default automatic to something sane there?

**Comment by gabemontero** [comment]
ok ... quickstarts / bindata.go (re) updated ... turns out, there were additional changes in the *-ex templates

**Comment by kargakis** [comment]
> I'm talking about a trigger like this: {"type":"ImageChange"}
> 
> Do we default automatic to something sane there?

We are talking about the same thing:) No, we don't. Left to Go.

**Comment by kargakis** [comment]
> that was our intent in setting it to false because for pods with ephemeral storage, we wanted to minimize the situations under which the pod would get torn down without the user taking an explicit action.

So basically you are asking for https://github.com/openshift/origin/issues/6934. I would love to have it resolved in any case (had a pull somewhere that did it) but @smarterclayton had other thoughts.

**Comment by bparees** [comment]
@gabemontero ironically what's currently in this dir is actually more correct than the upstream templates :(

the quickstarts dir already got manually updated by this PR: https://github.com/openshift/origin/pull/8248/files  when we should have updated the upstream templates.  so we need to go fix the upstream templates still to introduce those volume definitions.

**Comment by kargakis** [comment]
> So basically you are asking for #6934. I would love to have it resolved in any case (had a pull somewhere that did it) but @smarterclayton had other thoughts.

You would have to unset the config change trigger though i think. Because not all template changes are image changes but image changes are template changes:)

**Comment by gabemontero** [comment]
@bparees looks like the nodejs-mongodb was updated with the volume/volumeMount changes, though in a slightly different fashion than what was done in origin ... let me know if we should leave the nodejs-ex version as is, or change the volume/volumeMount stuff to match what was done in origin

**Comment by bparees** [comment]
i think we can leave nodejs as is.  you're just referring to the volume name being parameterized, right?

**Comment by gabemontero** [comment]
Yep that's it

**Comment by gabemontero** [comment]
ok @bparees, template updates now (re)include the volume/volumeMount stuff, plus the existing diffs from nodejs-ex

**Comment by bparees** [comment]
lgtm [merge]

**Pull request merged**
