### PR TITLE
[DO_NOT_MERGE] Use ImageStreamTag uniformly throughout deployment API

### PR DESCRIPTION
**Pull request by ironcladlou**
This is a WIP for https://github.com/openshift/origin/issues/2511

### CODE REVIEW

**Comment by deads2k** [comment]
This will bound https://github.com/openshift/origin/pull/2611.  ETA?

**Comment by smarterclayton** [comment]
Someone else should probably get involved here and help.

**Comment by ironcladlou** [comment]
My branch is now out of date but should give somebody a head start.

**Comment by danmcp** [comment]
@ironcladlou Bump

**Comment by ironcladlou** [comment]
Closing this PR and handing it over to @kargakis

**Pull request closed without merging**
