### PR TITLE
Increase verbosity level for BehaviorOnPanic

### PR DESCRIPTION
**Pull request by mfojtik**
@smarterclayton that message is messing up Jenkins ;-) https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_openshift3/856/console

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by smarterclayton** [comment]
Why is it messing up Jenkins?

**Comment by smarterclayton** [comment]
This code runs before glog params are specified, which means you can't log at v(anything).  So we can't change this.

**Comment by mfojtik** [comment]
@smarterclayton does it mean we need deal with the fact that this message will be always displayed?

**Comment by smarterclayton** [comment]
In test cases?  Yes.  But you can reset it after the server is started - we don't run control loops in the cli

**Comment by mfojtik** [comment]
@smarterclayton yeah in test cases... can't we just use environment variable for those to set the log level?

**Comment by smarterclayton** [comment]
I don't see the value, in that it's just one more thing that has to be tested and confirmed.  Clearing OPENSHIFT_ON_PANIC="" after the server is started in test/cmd and test/end-to-end is fine to me.

----- Original Message -----

**Pull request closed without merging**
