### PR TITLE
Allow image importing to work with proxy

### PR DESCRIPTION
**Pull request by jkhelil**
Trello card:  https://trello.com/c/Obmso4qn/510-allow-image-importing-to-work-with-proxy
Looking for review @soltysh

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by soltysh** [comment]
LGTM

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
