### PR TITLE
added LDAP entries for other schemas

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt Please sanity-check this. I've added the equivalent entries for the Active Directory and enhanced Active Directory schemas.

### CODE REVIEW

**Comment by deads2k** [comment]
[test][extended:core]

**Comment by liggitt** [comment]
don't you need to update the base dns in the tests? (e.g. test/extended/authentication/ldap_group_sync.go)?

**Comment by liggitt** [comment]
ah, maybe not until the image is built/pushed?

**Comment by stevekuznetsov** [comment]
Ah yes that test is currently not functional if I understand correctly. We'll need to change those DNs when we make it work. I'm hoping we can make the test use the command and config files soon.

**Comment by liggitt** [comment]
this looked reasonable as I ran past with my hair on fire :runner: :fire:

**Comment by stevekuznetsov** [comment]
Who needs code reviews when you have emoji?

**Comment by deads2k** [comment]
[test][extended:authentication]

**Comment by deads2k** [comment]
The extended test worked in https://github.com/openshift/origin/pull/4833#issuecomment-145130523.

**Comment by deads2k** [comment]
`ldapsearch` isn't showing people under "ou=people,ou=ad,dc=example,dc=com"

**Comment by deads2k** [comment]
This doesn't work.  mark [WIP]

**Comment by stevekuznetsov** [comment]
Changed to use `testPerson` schema, added in https://github.com/openshift/openldap/pull/11

**Comment by stevekuznetsov** [comment]
Updated for @deads2k pull config. I don't think any other changes are necessary.

**Comment by stevekuznetsov** [comment]
Now depends on https://github.com/openshift/origin/pull/5017

**Comment by deads2k** [comment]
the image push is running now.  [merge]

**Pull request merged**
