### PR TITLE
stop producing oauth-server binary and images

### PR DESCRIPTION
**Pull request by deads2k**
Since https://jira.coreos.com/browse/ART-787 is ready, stop producing the oauth-server image from origin.

/assign @sanchezl

### CODE REVIEW

**Comment by sanchezl** [comment]
I don't think you can remove the `Dockerfile.rhel` until you get rid of the CI config that uses it:
https://github.com/openshift/release/blob/cba7d53c382f35a31cf23ce302f5d95842cb7e56/ci-operator/config/openshift/origin/openshift-origin-master.yaml#L32-L39

**Comment by deads2k** [comment]
s3

/retest

**Comment by tnozicka** [comment]
we should remove it from hypershift 
https://github.com/openshift/origin/blob/b21503e65c6bcc724f1c43b2c187a664779b3746/cmd/hypershift/main.go#L74-L78

**Comment by deads2k** [comment]
> we should remove it from hypershift

already gone

**Pull request merged**
