### PR TITLE
Remove NotV2Registry check from redhat registry import test

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/origin/issues/7706

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

@deads2k

**Comment by smarterclayton** [comment]
Lgtm [merge] (does this fix both parts?)

**Comment by mfojtik** [comment]
@smarterclayton haven't tested this yet, what is the second part?

**Comment by mfojtik** [comment]
@smarterclayton nvmd, fixed the second part as well

**Comment by smarterclayton** [comment]
[merge]

**Comment by mfojtik** [comment]
@smarterclayton not yet :-)

**Comment by mfojtik** [comment]
[merge]

**Comment by ncdc** [comment]
flake #9938 #9929 [test]

**Comment by ncdc** [comment]
[vipmerge]

**Comment by mfojtik** [comment]
\o/

**Pull request merged**
