### PR TITLE
Bump origin-web-console (140a1f1)

### PR DESCRIPTION
**Pull request by jwforres**
cc @spadgett

### CODE REVIEW

**Comment by jwforres** [comment]
so the thing i dont like is that it has all that relative path detail in the comments so when different people run it then its going to change based on where they have their console repo at :-\

**Comment by jwforres** [comment]
@spadgett @liggitt I feel like the fact that the comments contain the full source path is actually a bug based on the definition behind the existence of the -prefix option of go-bindata

https://github.com/jteeuwen/go-bindata/blob/master/doc.go#L100

**Comment by spadgett** [comment]
LGTM other than the paths. It would be good to know how they are used. go-bindata debug mode?

**Comment by jwforres** [comment]
alright fixed it so its at least a sibling of origin in the path structure, would still like to look into dumping these paths altogether

[merge]

**Pull request merged**
