### PR TITLE
Add auto_unmount option for GlusterFS fuse mounts.

### PR DESCRIPTION
**Pull request by humblec**
UPSTREAM: <carry>: Add `auto_unmount` mount option for glusterfs fuse mount
    
    Bug#https://bugzilla.redhat.com/show_bug.cgi?id=1424680

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@jsafrane @rootfs @gnufied Please review.

**Comment by gnufied** [comment]
We should use commit comment such as - "UPSTREAM: <carry>: <message>" if commit isn't a cherry pick of upstream PR.

**Comment by gnufied** [comment]
lgtm to me.

**Comment by eparis** [comment]
we do not add things like this to old origin releases. OSE could be considered.

**Comment by gnufied** [comment]
yeah communicated same to Humble in IRC. he is going to open a PR against OSE.

**Pull request closed without merging**
