### PR TITLE
Validate wildcard certs against non-wildcard namedCertificate names

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1309435

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm[merge]

**Comment by liggitt** [comment]
copr error, [merge]

**Comment by liggitt** [comment]
unrelated new-app failure, [merge]

**Comment by deads2k** [comment]
> unrelated new-app failure, [merge] [test]

Did it have a specific "flake" indication in jenkins so they can vote on which flakes are the most important.

**Comment by liggitt** [comment]
It had a cause detection, but no linked issue

**Comment by deads2k** [comment]
> It had a cause detection, but no linked issue

Specific or generic?  Clayton's been adding generic ones that aren't related to flakes so that he doesn't have to look at the log.

**Pull request merged**
