### PR TITLE
(1.4) Fix excluder

### PR DESCRIPTION
**Pull request by tdawson**
Fix excluder usage bug
Exclude the excluders
docker-excluder excludes up to 1.20

### CODE REVIEW

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
Flake: #11649
[test]

**Comment by tdawson** [comment]
Flake: #12116
[test]

**Comment by tdawson** [comment]
Flake: #12112
[test]

**Comment by tdawson** [comment]
Flake: #12112
[merge]

**Comment by sdodson** [comment]
@tdawson I think this is may be out of date with some recent fixes or maybe those fixes are only appropriate for OCP?

**Comment by tdawson** [comment]
@sdodson I think the changes you are refering to are the exlusion of the excluders that are in this pull request.  Those exclusions are not needed in OCP, but for Origin, I think they are vital.  All of the origin rpms, and centos origin rpms, are in the same yum repository.  So excluding the excluders is necessary.  Otherwise you might update your docker exclusions, and update to a newer docker, before you update your openshift. packages.

**Comment by sdodson** [comment]
@tdawson yup, you're right. [merge]

**Comment by tdawson** [comment]
Flake: #12157
[merge]

**Pull request merged**
