### PR TITLE
Bug 1740264: Dockerfiles: verify package installation

### PR DESCRIPTION
**Pull request by pecameron**
bug 1740264
https://bugzilla.redhat.com/show_bug.cgi?id=1740264

SDN-503 Dockerfiles: verify that packages are installed
https://jira.coreos.com/browse/SDN-503

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@sdodson @smarterclayton PTAL
backport of openshift/sdn #21

**Comment by sdodson** [comment]
/approve

If this weren't a backport I'd say we should wait for https://github.com/openshift/images/pull/11 to be picked into release-4.1 instead. Once that's done can you make sure to clean this up?

**Comment by pecameron** [comment]
@sdodson look at https://jira.coreos.com/browse/SDN-503
This fix is in a lot of places.

**Comment by pecameron** [comment]
@sdodson It appears that openvswitch2.11 (fast datapath) is missing in the 4.1 build. Could you take a look?

**Comment by sdodson** [comment]
> @sdodson It appears that openvswitch2.11 (fast datapath) is missing in the 4.1 build. Could you take a look?

There's no openvswitch2.11 package in the datapath repo for 4.1 like there is 4.2. I don't know which SRE team this refers to, but that would be the team to check with I guess. https://github.com/openshift/release/pull/4572/

**Comment by pecameron** [comment]
@sdodson @smarterclayton @squeed  What steps does it take to fix the 4.1 sdn build? At present 4.1 sdn will not work. We need to get openvswitch2.11 into the build. Who handles this? Who should I talk to?

**Comment by pecameron** [comment]
@sdodson @smarterclayton Is this PR ready to merge?

**Comment by pecameron** [comment]
@sdodson Can this be merged?

**Comment by sdodson** [comment]
/retitle Bug 1740264: Dockerfiles: verify that package installation

**Comment by sdodson** [comment]
/bugzilla refresh
Also requires patch manager approval I believe.
/assign @derekwaynecarr

**Comment by eparis** [comment]
This does not have a 4.2 bug associated. But since this is entirely internal and not customer facing, I'm letting it through.

**Pull request merged**
