### PR TITLE
test/cmd/sdn.sh fixups

### PR DESCRIPTION
**Pull request by danwinship**
Sorry, @stevekuznetsov I meant to ping you on #11055 before merging but I forgot... Anyway, this should address your comments there

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Changes LGTM, will merge on green [test]s. Thanks for the follow-up!

**Comment by stevekuznetsov** [comment]
@danwinship:
```
=== RUN   TestExampleObjectSchemas
--- FAIL: TestExampleObjectSchemas (0.22s)
	examples_test.go:141: ../test/integration/testdata/test-egress-network-policy.json does not have a test case defined
```

**Comment by dcbw** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
[merge]

**Pull request merged**
