### PR TITLE
OCPBUGS-6850: [release-4.12] upgrade/adminack: guarantee one admin ack check post-upgrade

### PR DESCRIPTION
**Pull request by petr-muller**
This is a cherry-pick of https://github.com/openshift/origin/pull/27645 and https://github.com/openshift/origin/pull/27678

- upgrade/adminack: guarantee one admin ack check post-upgrade
- upgrade/adminack: optimize the post-upgrade check
- upgrade/adminack: simplify polling and unblock "guaranteed" post-upgrade check
- upgrade/adminack: wait up to 4m until gate propagates to upgradeable

/hold

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
GitHub is acting funny: the commits from this PR are merged including the merge commit but for some reason the PR stays open.

**Comment by petr-muller** [comment]
https://github.com/openshift/origin/commit/35f8c051dd32b99490634ef52d73bb280d66194c
/shrug

**Pull request closed without merging**
