### PR TITLE
OCPBUGS-967: temporarily disable IngressClass test, which is changed in upstream in 1.25

### PR DESCRIPTION
**Pull request by soltysh**
/assign @candita

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-serial
this PR removes one test from being run, and isn't directly affected by these failures, and it should help with merging the k8s 1.25 bump

**Comment by kikisdeliveryservice** [comment]
This PR will unblock some of our payload tests for the [1.25 bump](https://github.com/openshift/kubernetes/pull/1360). Right now I see this blocked on required e2e-aws-ovn-serial which is basically red: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-origin-master-e2e-aws-ovn-serial

As this PR only _disables_ a test, can we override this so we can merge and so we can move our payload testing past this to get a better signal for the k8s bump?

**Pull request merged**
