### PR TITLE
bump(github.com/openshift/source-to-image) 08e663119911bcae4ef2a243689886f36b997702

### PR DESCRIPTION
**Pull request by jhadvig**
@kargakis PTAL

### CODE REVIEW

**Comment by jhadvig** [comment]
I left the comments empty, as suggested

**Comment by kargakis** [comment]
Actually update the comments with the tag that you are rebasing onto

**Comment by kargakis** [comment]
This should happen automatically by godep though:)

**Comment by jhadvig** [comment]
@kargakis updated :ok_hand:

**Comment by kargakis** [comment]
LGTM

deferring to @mfojtik for merging

**Comment by jhadvig** [comment]
Closing in favour of https://github.com/openshift/origin/pull/5372

**Pull request closed without merging**
