### PR TITLE
bug 1875586: make scaling test wait until the node can take workloads

### PR DESCRIPTION
**Pull request by deads2k**
more constrained version of https://github.com/openshift/origin/pull/25474

We found that we got valuable signal on this test, like https://bugzilla.redhat.com/show_bug.cgi?id=1870343

### CODE REVIEW

**Comment by elmiko** [comment]
is the thinking here to be a little more conservative on what we remove? (just curious)

**Comment by deads2k** [comment]
> is the thinking here to be a little more conservative on what we remove? (just curious)

Yeah.  I recognized at least one test that I personally added because fips broke it.

**Comment by elmiko** [comment]
makes sense to me, i'll hold off on adding lgtm so that @michaelgugino can take a look.

**Comment by deads2k** [comment]
/hold

This is actually catching bugs for us.  It is failing on a couple platforms.  I'll update tomorrow to make it wait for nodes to be ready with network and schedulable.

**Comment by deads2k** [comment]
/hold cancel

@mfojtik ptal

**Pull request merged**
