### PR TITLE
oadm ca create-signer-cert: rename --expire-days to --signer-expire-days

### PR DESCRIPTION
**Pull request by php-coder**
After merging https://github.com/openshift/origin/pull/11814 I got a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1405297) which demonstrates that one of the options works differently depend on the command that is executed. This fact puzzles users and UX-unfriendly. I want to rename it while it's not too late.

#### Current behavior:
- `--expire-days` in 99% affects lifetime of the non-CA certificates
- in case of `oadm create-signer-cert` it alters lifetime of the CA-certificate (because that is what this command does)

#### Proposed behavior:
- `--expire-days` always set lifetime of the non-CA certificates
- `oadm create-signer-cert`: option `--expire-days` replaced by `--signed-expire-days`

@fabianofranz @soltysh PTAL.
CC @mfojtik @liggitt

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM, but you need to update completions (`hack/update-generated-completions.sh`). @openshift/api-review any objections for this change?

**Comment by liggitt** [comment]
I have a slight preference for keeping it as-is (in `create-signer-cert` *all* the flags are only relevant to the signer, so we have `--cert`, `--key`, etc), but I don't feel super strongly

**Comment by soltysh** [comment]
Actually, after 2nd thought I agree with Jordan. This particular command (`create-signer-cert`) addresses ca.crt and all the options work against it. I'd suggest closing this BZ as not a bug and leaving this as is.

**Comment by mfojtik** [comment]
+1 to @liggitt and @soltysh two "signer" in one command seems ugly.

**Pull request closed without merging**
