### PR TITLE
Bug 1963909: move verify run test from tools to cli image; narrow scope to /run/secrets

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick required since bot encountered merge conflict with 4.7 PR

### CODE REVIEW

**Comment by xiuwang** [comment]
E2E result has validated this change. 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26177/pull-ci-openshift-origin-release-4.6-e2e-aws-fips/1396796722524459008

/label qe-approved

**Comment by gabemontero** [comment]
though the run failed, the updated tests in e2e-gcp-builds passed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26177/pull-ci-openshift-origin-release-4.6-e2e-gcp-builds/1397197704370589696

/retest

**Comment by gabemontero** [comment]
bump @coreydaley need a new lgtm - thanks

**Comment by xiuwang** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26177/pull-ci-openshift-origin-release-4.6-e2e-aws-fips/1397197704215400448 passed
And will wait the 4.6 nightly periodic to complete and mark bug to verified.

/lgtm

**Pull request merged**
