### PR TITLE
Include origin-egress-http-proxy image in the release

### PR DESCRIPTION
**Pull request by pravisankar**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1475752

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking @eparis please review/merge

**Comment by pravisankar** [comment]
This only includes 'origin-egress-http-proxy' image in the release.
How do we include 'ose-egress-http-proxy' image in the enterprise release? I'm guessing some other change required in openshift/ose repo. Let me know if you have any pointers...

/cc @openshift/networking

**Comment by stevekuznetsov** [comment]
For enterprise pushes /cc @jupierce @smunilla

**Pull request merged**
