### PR TITLE
UPSTREAM: 9384: Make empty_dir unit tests work with SELinux disabled

### PR DESCRIPTION
**Pull request by pmorie**
@smarterclayton @ncdc

### CODE REVIEW

**Comment by pmorie** [comment]
[test]

**Comment by ncdc** [comment]
Was this missed in the last rebase?

**Comment by pmorie** [comment]
@ncdc yes -- the upstream PR has this change.

**Comment by pmorie** [comment]
@ncdc It's possible I didn't add them in, actually.

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
