### PR TITLE
3.11: Fix iSCSI multipath issues

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1637413

@openshift/sig-storage @humblec

### CODE REVIEW

**Comment by jsafrane** [comment]
@openshift/storage PTAL

**Comment by wongma7** [comment]
/lgtm

https://github.com/openshift/origin/pull/21216/commits/bd2173925c25d46bd52e955fd2943f434e90c454 is missing a newline somewhere..

**Pull request merged**
