### PR TITLE
UPSTREAM: 49142: Slow-start batch pod creation of rs, rc, ds, jobs

### PR DESCRIPTION
**Pull request by joelsmith**
xref https://github.com/kubernetes/kubernetes/pull/49142
upstream issue: https://github.com/kubernetes/kubernetes/issues/49145

### CODE REVIEW

**Comment by deads2k** [comment]
This looks fairly invasive.  Is it a regression from 3.6?  Did it get picked into 1.7?  Is there an issue or bug corresponding to the pick?

**Comment by joelsmith** [comment]
@deads2k sorry, I forgot to edit the PR comments with the xref to upstream. Also, I'm happy to have you review if you like, but @derekwaynecarr reviewed upstream so it might be easier to have him also review this pick PR. I'll go update the PR comment now with xref details.

**Comment by deads2k** [comment]
> @deads2k sorry, I forgot to edit the PR comments with the xref to upstream. Also, I'm happy to have you review if you like, but @derekwaynecarr reviewed upstream so it might be easier to have him also review this pick PR. I'll go update the PR comment now with xref details.

My concern is more about impacts to being able to pick future maintenance into 3.7.  Having a description of the problem is important to judging the tradeoff.  Thanks for the links.

**Comment by joelsmith** [comment]
The upstream PR has merged and will be in 1.8. @derekwaynecarr is this ready for a review?

**Comment by derekwaynecarr** [comment]
@deads2k -- this protects against the following: https://github.com/kubernetes/kubernetes/issues/49145

**Comment by derekwaynecarr** [comment]
@joelddiaz - i would like the upstream fix to soak a few days before merging this.

**Comment by derekwaynecarr** [comment]
wrong joel, @joelsmith -- i want to let this soak for a few days upstream before merging.

**Comment by joelsmith** [comment]
Thanks, sounds good.

**Comment by sjenning** [comment]
@derekwaynecarr https://github.com/kubernetes/kubernetes/pull/49142 has been in upstream 10 days  now.  How long did we want this to soak?

xref https://trello.com/c/vzi3Mhi3

**Comment by sjenning** [comment]
integration test is currently broken https://github.com/openshift/origin/issues/16323

**Pull request merged**
