### PR TITLE
[DO_NOT_MERGE] ignore me

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[testextended][extended:core(templates)]

**Comment by bparees** [comment]
@stevekuznetsov @dobbymoodge so i take it from https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended.yml#L18-L24 that the two separate testextended comments i made above are not expected to work.  The result in the job is:

```
+ [[ -z '' ]]
+ [[ core(templates),core(builds) =~ ^(.*)\((.*)\)$ ]]
+ SUITE='core(templates),core'
+ FOCUS=builds
```

Somehow i thought this used to work, but if the right way to do it is a single focus for the core suite, that's fine.

**Comment by dobbymoodge** [comment]
@bparees I thought you could do e.g. `core(templates,builds)`. I'll dig in a bit to see what reality dictates.

**Comment by dobbymoodge** [comment]
@bparees from https://github.com/onsi/ginkgo/blob/master/README.md :

>  `ginkgo -focus="REGEXP"` and `ginkgo -skip="REGEXP"` allow you to specify a subset of tests to run via regular expression


So maybe `core(templates|builds)` would work? @stevekuznetsov would probably be able to say for sure.

**Comment by bparees** [comment]
Yes that does work. But I was still surprised multiple tags weren't
combined, even if it meant running the core suite multiple times with
different focuses.

Ben Parees | OpenShift

**Comment by stevekuznetsov** [comment]
We explicitly decided to stop supporting this behavior, but did not get around to getting rid of that supporting logic in Rosie.

**Pull request closed without merging**
