### PR TITLE
bootstrap-policy: add /readyz to system:discovery

### PR DESCRIPTION
**Pull request by sttts**
This way the ELB can access /readyz without authentication.

### CODE REVIEW

**Comment by deads2k** [comment]
`UPDATE_BOOTSTRAP_POLICY_FIXTURE_DATA=true hack/test-go.sh pkg/cmd/server/bootstrappolicy` to get green

/lgtm

**Comment by enj** [comment]
/hold

Still need bootstrap data YAML update.

**Comment by sttts** [comment]
@enj updated the yaml.

/hold cancel

**Comment by enj** [comment]
/hold

We want to update the origin specific RBAC policy.

**Comment by enj** [comment]
https://github.com/openshift/origin/blob/8157540d7663a32f3a572931a614a308d8445065/pkg/authorization/apis/authorization/types.go#L43

**Comment by sttts** [comment]
The upper spot is the policy installed by openshift-apiserver. It is not for the kube resources (though it looks like we have to prune it from historic kube rules in there).

**Comment by enj** [comment]
/hold cancel

Origin and kube RBAC bootstrapping was split in 4.x so this location makes sense.

After we rebase on 1.14 this will need to move to `system:public-info-viewer`.

**Pull request merged**
