### PR TITLE
Add List to token client

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@enj PTAL
cc @markturansky

**Comment by enj** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by markturansky** [comment]
@liggitt what version of Origin/OSE would this land in? I'm wondering if we need to cherry-pick this or if I hack my own version by casting to the RestClient.

**Comment by liggitt** [comment]
1.5 unless we pick

**Comment by mfojtik** [comment]
[test]

**Pull request merged**
