### PR TITLE
Nuke oc

### PR DESCRIPTION
**Pull request by tnozicka**
moved to https://github.com/openshift/oc

image promotion change https://github.com/openshift/release/pull/4402

we keep cli-artifacts (mac and windows builds) until we support it in library-go (https://github.com/openshift/library-go/issues/477)

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
to do it in sync with promotion change

**Comment by tnozicka** [comment]
needs https://github.com/openshift/origin/pull/23403 first

**Comment by deads2k** [comment]
already gone

**Pull request closed without merging**
