### PR TITLE
Bug 1991980: Skipped non-standard openshift installed crd testing for ibmcloud

### PR DESCRIPTION
**Pull request by Joseph-Goergen**
https://bugzilla.redhat.com/show_bug.cgi?id=1991980

### CODE REVIEW

**Comment by Joseph-Goergen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1991980

**Comment by csrwng** [comment]
@ironcladlou ptal
This is to skip crd checks for resources that don't exist in a hosted cluster install

**Pull request merged**
