### PR TITLE
Switch to headless chrome for UI e2e tests - attempt #2

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
[test]

**Comment by liggitt** [comment]
```
[ ERR] Gave up waiting for: 'oc get -n test builds | grep -i complete'
[FAIL] !!!!! Test Failed !!!!
```

**Comment by jwforres** [comment]
Commits are all cleaned up, @liggitt double check things.  I switched back to calling grunt test-e2e and made that task use chrome instead of phantomjs since i ripped out the rest of the phantom support.

Waiting to merge until devenv_ami build 2189 is able to run

**Comment by liggitt** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
