### PR TITLE
Rebase service catalog to v0.0.17

### PR DESCRIPTION
**Pull request by jpeeler**
This rebases service catalog to the latest release.

### CODE REVIEW

**Comment by pmorie** [comment]
@jpeeler can you determine whether this version has the same issue as https://github.com/openshift/origin/issues/16141

**Comment by pmorie** [comment]
@jpeeler we need to ensure that:

- The templates in openshift are updated for the new resource names
- Any new admission controllers in the upstream are present in the openshift templates

We'll also need a follow-up after this to update the ansible installer.

**Comment by jmontleon** [comment]
I built images with this PR in attempt to use the updated service catalog but I am seeing an error from `oc cluster up --service-catalog=true`

```
-- Installing template service broker ... FAIL
   Error: failed to register broker with service catalog: timed out waiting for the condition
```

**Comment by jmontleon** [comment]
I built images with this PR in attempt to use the updated service catalog but I am seeing an error from `oc cluster up --service-catalog=true`

```
-- Installing template service broker ... FAIL
   Error: failed to register broker with service catalog: timed out waiting for the condition
```

**Comment by jpeeler** [comment]
@jmontleon This PR was canceled for merging because it's not ready to go after all. One problem that needs fixing is the kind in the template-service-broker-registration needs to be changed to ServiceBroker. There may be additional renames required as well (since broker is not the only name change that occurred in 0.0.17).

**Comment by spadgett** [comment]
@jmontleon My PR should address binding, but I need to test:

https://github.com/openshift/origin-web-console/pull/2048

**Comment by pmorie** [comment]
@spadgett has told me in person that this PR worked well for him.

/lgtm

**Comment by jmontleon** [comment]
@jpeeler @pmorie any insight into why we're still getting errors when the controller-manager tries to communicate with the ansible service broker over SSL?

```
ERROR: logging before flag.Parse: W0912 16:46:12.130863      37 controller_broker.go:208] Error getting broker catalog for broker "ansible-service-broker": Get https://asb-1338-ansible-service-broker.172.18.0.1.nip.io/v2/catalog: x509: certificate signed by unknown authority
```

**Comment by jmontleon** [comment]
Even with SSL disabled I also see errors that are preventing APB's and other apps from being properly populated in the UI.

```
ERROR: logging before flag.Parse: E0912 16:51:46.426900      64 reflector.go:201] github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61: Failed to list *v1alpha1.ServiceInstanceCredential: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list serviceinstancecredentials.servicecatalog.k8s.io at the cluster scope: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list all serviceinstancecredentials.servicecatalog.k8s.io in the cluster (get serviceinstancecredentials.servicecatalog.k8s.io)
ERROR: logging before flag.Parse: I0912 16:51:47.425899      64 reflector.go:236] Listing and watching *v1alpha1.ServiceBroker from github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61
ERROR: logging before flag.Parse: I0912 16:51:47.426863      64 reflector.go:236] Listing and watching *v1alpha1.ServiceInstance from github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61
ERROR: logging before flag.Parse: I0912 16:51:47.427976      64 reflector.go:236] Listing and watching *v1alpha1.ServiceInstanceCredential from github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61
ERROR: logging before flag.Parse: E0912 16:51:47.428047      64 reflector.go:201] github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61: Failed to list *v1alpha1.ServiceBroker: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list servicebrokers.servicecatalog.k8s.io at the cluster scope: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list all servicebrokers.servicecatalog.k8s.io in the cluster (get servicebrokers.servicecatalog.k8s.io)
ERROR: logging before flag.Parse: E0912 16:51:47.428410      64 reflector.go:201] github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated/externalversions/factory.go:61: Failed to list *v1alpha1.ServiceInstance: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list serviceinstances.servicecatalog.k8s.io at the cluster scope: User "system:serviceaccount:kube-service-catalog:service-catalog-controller" cannot list all serviceinstances.servicecatalog.k8s.io in the cluster (get serviceinstances.servicecatalog.k8s.io)
```

**Comment by jpeeler** [comment]
flake #16312

**Pull request merged**
