### PR TITLE
Restrict access to docker/custom builds

### PR DESCRIPTION
**Pull request by smarterclayton**
Change security description in README.md

Waiting to get a final statement

### CODE REVIEW

**Comment by mfojtik** [comment]
@TomasTomecek you might be interested in this one.

**Comment by TomasTomecek** [comment]
I indeed am, thanks Michal for headsup.

Does this change anything in process of spawning custom build pods? Right now, we need `cap_sys_admin`.

**Comment by smarterclayton** [comment]
This just requires a cluster admin to grant the privilege to create custom builds to a role, rather than it being on by default.

**Comment by TomasTomecek** [comment]
And is the `edit` role capable of doing custom builds? (CC @mmilata)

**Comment by liggitt** [comment]
@TomasTomecek with this change, admin and edit roles can only do source builds by default. cluster-admin users can do anything, and they can modify the "admin" and/or "edit" roles to allow docker or custom build permissions if desired

**Comment by smarterclayton** [comment]
@bparees @csrwng before this change has teeth, we need a way to ensure that the container running the user's build in is also limited like regular pods are.

----- Original Message -----

**Comment by smarterclayton** [comment]
@bparees can you link the issue/card for tracking making source build force non-root builder images for specific users here?

**Comment by bparees** [comment]
@smarterclayton https://trello.com/c/eGlfwXcs/603-3-prevent-sti-builder-images-from-running-as-root

**Comment by danmcp** [comment]
@smarterclayton Bump

**Comment by danmcp** [comment]
@smarterclayton Still valid?  Needs a rebase.

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Pull request closed without merging**
