### PR TITLE
Enable ServiceInternalTrafficPolicy tests in OVNK

### PR DESCRIPTION
**Pull request by tssurya**
We support ITP=local from 4.11 so let's enable the tests
for this feature which were disabled.

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>

### CODE REVIEW

**Comment by tssurya** [comment]
/hold
till https://github.com/openshift/ovn-kubernetes/pull/1049/commits/87ce7b6715fb4ad20933ec11b6547a4e1742caaa merges

**Comment by tssurya** [comment]
/hold cancel
downstream PR for the feature has merged.

**Comment by tssurya** [comment]
/hold,
good call on running the e2e-aws-ovn job, seems like one ITP test is failing which I don't know why...because it passed in upstream OVN-K...

**Comment by tssurya** [comment]
passing:
: [sig-network] Services should respect internalTrafficPolicy=Local Pod and Node, to Pod (hostNetwork: true) [Feature:ServiceInternalTrafficPolicy] [Suite:openshift/conformance/parallel] [Suite:k8s]
: [sig-network] Services should respect internalTrafficPolicy=Local Pod to Pod [Feature:ServiceInternalTrafficPolicy] [Suite:openshift/conformance/parallel] [Suite:k8s]

failing:
[sig-network] Services should respect internalTrafficPolicy=Local Pod (hostNetwork: true) to Pod [Feature:ServiceInternalTrafficPolicy] [Suite:openshift/conformance/parallel] [Suite:k8s]

**Comment by hardys** [comment]
Will this work for ipv6?  I'm looking at failures like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ironic-agent-image/43/pull-ci-openshift-ironic-agent-image-release-4.10-e2e-metal-ipi-ovn-ipv6/1519188822322057216) which I expected to pass since [this](https://github.com/openshift/ovn-kubernetes/pull/1043) NetworkPolicy fix landed so I'm wondering if we need to skip/fix NetworkPolicy tests for ipv6?

**Comment by knobunc** [comment]
/approve

Very excited to see this change!

**Comment by tssurya** [comment]
@knobunc : could we override the e2e-gcp-builds job on this one? 
e2e-gcp-builds is Perma Failing: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-origin-master-e2e-gcp-builds

**Comment by tssurya** [comment]
serial job also needs a skip due to https://issues.redhat.com/browse/OCPBUGS-1083 has nothing to do with this PR

**Comment by knobunc** [comment]
/override e2e-aws-ovn-serial

Unrelated issue that seems to be widespread -- https://issues.redhat.com/browse/OCPBUGS-1083

**Pull request merged**
