### PR TITLE
Naming inconsistancy fix

### PR DESCRIPTION
**Pull request by jhadvig**
@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM
@smarterclayton for approval, tiny fix so it says config map instead of secret

**Comment by smarterclayton** [comment]
Approved

**Comment by smarterclayton** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by smarterclayton** [comment]
Flake [merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
