### PR TITLE
Add oc command to open the console

### PR DESCRIPTION
**Pull request by cblecker**
This PR adds an experimental command to open the OpenShift console from the CLI. This might be useful enough to add in as actual top-level command (e.g. `oc console`), but I wasn't sure so I put it under the experimental heading.

It pulls data from the `consoles.config.openshift.io` cluster object. I previously had this retrieving route objects from the `openshift-console` namespace, but this may not be available in hosted offerings. By using the consoles.config.openshift.io object, cluster scoped GET permissions can be granted.. however, this means that this command is v4+ only.

By default, this URL will be opened in your default web browser. If the `--url` flag is passed, it will just print this URL and exit.

I'm handling specific error message from the API, but I'm not sure on verbiage for them, or if instead of directly handling these use cases, it would be better to just return the err directly.

### CODE REVIEW

**Comment by cblecker** [comment]
Okay, so I think I solved by glide issues:
- First off was https://github.com/openshift/origin/pull/23327. This was preventing me from touching deps on master.
- Second was a weird issue with the way that glide is handling dependencies for the new staging repo setup. If I add a new staging package, reference it somewhere in the code base, and then run glide, glide barfs because that new package isn't available in the master branch of the actively published repo.

For example, I created the `github.com/openshift/oc/pkg/cli/experimental/console` package in this PR. I needed to add it to `staging/src/github.com/openshift/oc/pkg/cli/cli.go` so that the new cobra commands could be registered. However, because this package doesn't exist on master, glide repeatedly failed with:

```
[ERROR] Error scanning github.com/openshift/oc/pkg/cli/experimental/console: cannot find package "." in:
        /root/.glide/cache/src/https-github.com-openshift-oc/pkg/cli/experimental/console
```

I fixed this by commenting out the import statement, running glide, and then uncommenting. This workflow will likely need to be addressed as the staging repo setup is moved forward.

I've rebased this PR based on #23327, but can rebase it once that one is merged.

**Comment by cblecker** [comment]
This is ready for review, but holding so that #23327 can be reviewed and merged first.
/hold

**Comment by cblecker** [comment]
/hold cancel
#23327 has been merged, so I rebased this one cleanly now.

Should be ready for review.

**Comment by deads2k** [comment]
I'm a -1 on this.  the kube-apiserver can redirect to the console already.  I'd expect the console team to have a config observer that writes to `consolePublicURL` to enable that functionality.

/hold

**Comment by cblecker** [comment]
Talked to @deads2k on Slack about this.

The API server should redirect to the console, if installed. It's not doing that right now. Opened up a BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1730905

As for the "open the URL directly in the browser" pieces, this may be better served by a oc/kubectl plugin. Going to take a look at that separately.

Going to close this PR for now, as there are better ways to do this that don't require cluster-admin or rbac changes.

**Pull request closed without merging**
