### PR TITLE
Revert runc picks

### PR DESCRIPTION
**Pull request by sjenning**
https://bugzilla.redhat.com/show_bug.cgi?id=1558183#c5

@derekwaynecarr @smarterclayton @liggitt @vikaschoudhary16 @jupierce

### CODE REVIEW

**Comment by jupierce** [comment]
@nhr will need to merge since this branch is locked down.

**Comment by smarterclayton** [comment]
The node isn't reporting healthy to systemd and is starting and failing every 5 minutes.  That's weird.

**Comment by smarterclayton** [comment]
Hrm, install is using the wrong ansible version.

**Comment by sjenning** [comment]
Not seeing why the node service is failing to restart from looking at the logs.  I don't even see a restart attempt.

**Comment by smarterclayton** [comment]
Because we were running against the wrong version of ansible.  Fixed

**Comment by sjenning** [comment]
@nhr all tests pass now.  need lgtm or just BGB merge?

**Pull request merged**
