### PR TITLE
Check ocm rollout between build tests

### PR DESCRIPTION
**Pull request by adambkaplan**
* Make sure the OCM rollout completes between disruptive test runs.

/assign @gabemontero 

fyi @openshift/openshift-team-developer-experience

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

builds are still red

**Comment by adambkaplan** [comment]
ping @gabemontero - assuming aws builds passes too I think we're good here.
Fixes env var flakiness I've observed in my ocm bump

**Comment by gabemontero** [comment]
it is gcp builds now :-)

/lgtm

**Comment by adambkaplan** [comment]
/retest

Jenkins ruby issue (now fixed)

**Pull request merged**
