### PR TITLE
Fix DC selectors for autoscaling

### PR DESCRIPTION
**Pull request by tnozicka**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1544496

Hotfix before https://github.com/openshift/origin/pull/18640

/cc @mfojtik @liggitt @DirectXMan12

### CODE REVIEW

**Comment by liggitt** [comment]
this LGTM as a short-term fix. will let @DirectXMan12 tag

**Comment by DirectXMan12** [comment]
blech.  Fine for a hotfix

/lgtm

**Pull request merged**
