### PR TITLE
add new SCL version imagestreams

### PR DESCRIPTION
**Pull request by bparees**
nodejs-4-centos is not available yet, will do a followup pull when it is.

### CODE REVIEW

**Comment by soltysh** [comment]
I can't wait to have it in :+1:

**Comment by bparees** [comment]
@sdodson @soltysh ptal.

**Comment by bparees** [comment]
[test]

**Comment by sdodson** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
known flake(existing issue)
[merge]


On Wed, Jun 29, 2016 at 6:00 PM, OpenShift Bot <notifications@github.com>
wrote:

> continuous-integration/openshift-jenkins/test FAILURE (
> https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/5583/)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/pull/9610#issuecomment-229502454>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3mAm4Z6jVTvnA77fZ_2_2QGnp1BCks5qQusbgaJpZM4JAVE7>
> .
>



-- 
Ben Parees | OpenShift

**Comment by soltysh** [comment]
k8s flake
re-[merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

@deads2k how exactly did this fuzzer flake manage to get merged?

**Comment by bparees** [comment]
[merge]

**Comment by deads2k** [comment]
> @deads2k how exactly did this fuzzer flake manage to get merged?

It's a flake which didn't fail in the merge job.  And it exposed a pretty severe deltaFifo bug, so go us.

**Pull request merged**
