### PR TITLE
fix rpm spec file to properly build man pages dynamically

### PR DESCRIPTION
**Pull request by tdawson**
A few bugs were fixed to allow rpm building in a koji environment.

### CODE REVIEW

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
[test]

**Comment by tdawson** [comment]
@sdodson Can I get a sanity check on this.

If you were wondering why I switched to using hack/update-generated-docs.sh
It ended up only being 10 seconds different, and we get the benefit of all the documents being updated, not just man pages.

**Comment by sdodson** [comment]
LGTM, I'll open a separate issue to see if we can get rid of the rsync dep, this looks scary to me https://github.com/openshift/origin/blob/master/hack/common.sh#L894-L895

**Comment by tdawson** [comment]
[merge]

**Pull request merged**
