### PR TITLE
don't include the project name in the new-app validation check

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/12911

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
this fix is needed to unbreak the merge queue, manually merging.

**Comment by stevekuznetsov** [comment]
Looks like this does successfully fix `check` jobs: https://ci.openshift.redhat.com/jenkins/view/Future%20Origin%20PR%20Test%20Jobs/job/test_pull_requests_origin_check_future/109/

**Comment by bparees** [comment]
@stevekuznetsov 🍾

**Pull request merged**
