### PR TITLE
Fix fake client race

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/2782/consoleText .

I promise to do the upstream pull after the dentist, but this should help clear the merge queue flakes.

@smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
@smarterclayton I'd like this as a patch while we wait for https://github.com/GoogleCloudPlatform/kubernetes/pull/10783 and take the refactoring hit during a rebase.

**Comment by kargakis** [comment]
Also https://github.com/openshift/origin/issues/3757

**Comment by ncdc** [comment]
@deads2k is the data race failure in https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/2784/consoleFull related to this?

**Comment by smarterclayton** [comment]
We should not embed locks - Lock should not be a valid interface option on the Client

LGTM [merge]

**Comment by kargakis** [comment]
> We should not embed locks - Lock should not be a valid interface option on the Client

`Fake` is not an interface and I don't see why it shouldn't implement the [Locker](http://golang.org/pkg/sync/#Locker) interface.

> A Locker represents an object that can be locked and unlocked. 

Upstream they are doing it the canonical way - embed on top of the field you mute.

**Comment by smarterclayton** [comment]
Where is no reason anyone outside of fake should lock fake.  fake controls
its members - not an outer class.

Point me to instances upstream and I'll open bugs.

On Jul 21, 2015, at 4:29 AM, Michail Kargakis <notifications@github.com>
wrote:

We should not embed locks - Lock should not be a valid interface option on
the Client

Fake is not an interface and I don't see why it shouldn't implement the
Locker <http://golang.org/pkg/sync/#Locker> interface.

A Locker represents an object that can be locked and unlocked.

Upstream they are doing it the canonical way - embed on top of the field
you mute.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/3791#issuecomment-123212194>.

**Pull request merged**
