### PR TITLE
Merge flatsdn and multitenant code

### PR DESCRIPTION
**Pull request by danwinship**
Corresponding to https://github.com/openshift/openshift-sdn/pull/208. This is mostly just a Godeps bump; the actual origin changes are just to the spec file and vagrant config.

@pravisankar

### CODE REVIEW

**Comment by pravisankar** [comment]
LGTM

**Comment by dcbw** [comment]
origin bits LGTM, now that https://github.com/openshift/openshift-sdn/pull/208 is merged we need a Godeps update though.

**Comment by danwinship** [comment]
rebased and updated; nothing changed but the commit id in Godeps.json.

(The bump commit is muddied a bit by the fact that it includes unrelated changes from openshift-sdn master... would it be better to do multiple bump commits instead to split things up?)

**Comment by pravisankar** [comment]
[merge]

**Comment by pravisankar** [comment]
re[merge]

**Comment by dcbw** [comment]
re[merge]

**Comment by pravisankar** [comment]
[merge] again

**Comment by dcbw** [comment]
Running "protractor:chrome" (protractor) task
    Starting selenium standalone server...
    [launcher] Running 1 instances of WebDriver
    Selenium standalone server started at http://172.18.14.99:51742/wd/hub
    Spec started

    **************************************************
    *                    Failures                    *
    **************************************************

    1)  authenticated e2e-user new project when creating a new project should successfully create a new project
      - Error: Element not found: .breadcrumb li a
    Wait timed out after 5040ms
      Wait timed out after 5040ms
        at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
        at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at notify (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
        at [object Object].then (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
        at Object.webdriver.promise.asap (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:767:11)
        at newFrame.onComplete (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
        at [object Object].webdriver.promise.Frame_.notify_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
        at [object Object]._onTimeout (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1901:11)
    ==== async task ====
    Element not found: .breadcrumb li a
        at [object Object].webdriver.promise.ControlFlow.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1410:15)
        at [object Object].webdriver.WebDriver.wait (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:646:21)
        at [object Object].to.(anonymous function) [as wait] (/data/src/github.com/openshift/origin/assets/node_modules/protractor/lib/protractor.js:62:25)
        at Object.exports.waitForPresence (/data/src/github.com/openshift/origin/assets/test/integration/helpers.js:73:11)
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:131:13)
        at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:94:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
    ==== async task ====
    Asynchronous test function: it()
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/jasminewd/index.js:93:33)
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/minijasminenode/lib/async-callback.js:45:37)
    Error
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:125:9)
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:116:7)
        at [object Object].<anonymous> (/data/src/github.com/openshift/origin/assets/test/integration/rest_api/project.js:115:5)

    Executed 14 of 14 specs (1 FAILED) in 48 secs.
    Shutting down selenium standalone server.
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 failed 1 test(s)
    [launcher] overall: 1 failed spec(s)
    [launcher] Process exited with error code 1
    >> 
    Fatal error: protractor exited with code: 1

Test flake I assume?  This doesn't appear to have anything to do with danw's changes.

**Comment by eparis** [comment]
[merge] stop flaking!!!

**Pull request merged**
