### PR TITLE
update to use last upstream generator

### PR DESCRIPTION
**Pull request by deads2k**
This updates the defaulters an the openapi gen to use the upstream binaries directly.

@sttts I can't see to use generate-internal-groups without weird things happening.  I'd like to collapse our six existing scripts into one for the majority of our generation needs and just have the config APIs be the outliers.

/assign sttts
/assign mfojtik

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm

@deads2k what are the weird things? Is our directory structure off?

**Comment by deads2k** [comment]
> @deads2k what are the weird things? Is our directory structure off?

it was trying to include versions in our internal client and the generated conversions ended up in the wrong spot.  I'm not sure what I did wrong.

**Pull request merged**
