### PR TITLE
Provide the sequence number in atomic-quick-start-tutorial.adoc

### PR DESCRIPTION
**Pull request by yuexiao-wang**
The sequence number should begins from 1 in document and keep the same style.
The first letter should be used by upper case letter in subtitle.

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by danmcp** [comment]
@yuexiao-wang This doesn't look right:

https://github.com/yuexiao-wang/origin/blob/856fb4f163e67605963b58512afeab141e148580/docs/atomic-quick-start-tutorial.adoc

with the 1. being a header.

**Comment by yuexiao-wang** [comment]
@danmcp PTAL
Thanks for your review! 
Now the header begin with the 1 as follows:
https://github.com/yuexiao-wang/origin/blob/fix-typos/docs/atomic-quick-start-tutorial.adoc

**Comment by danmcp** [comment]
Now that I look closer, I don't think this doc should even exist anymore.  @pweil- Thoughts?

**Comment by pweil-** [comment]
agree, will create a PR to remove

**Pull request closed without merging**
