### PR TITLE
Bug 1989423: Enable back HAProxy idle service connect test

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold

using this PR to test with for now

**Comment by jluhrsen** [comment]
@danwinship , we need the PRs in https://bugzilla.redhat.com/show_bug.cgi?id=1996689 to merge before
this goes in right?

**Comment by danwinship** [comment]
No. We merged the part of that that is required for this PR (note that the last e2e-gcp run passed the HAProxy idle test), but there didn't end up being a separate BZ for just that part. This PR is now mergeable.

**Comment by danwinship** [comment]
yup

**Pull request merged**
