### PR TITLE
use the upstream deep copy generator

### PR DESCRIPTION
**Pull request by deads2k**
This updates all of our api packages to follow the "normal" patter with apis/group/version, removes our own custom deep copy binary, uses the "normal" deep copy via direct execution.  Someday we may use the normal code-generator script, but this is a step in the right direction.

/assign @mfojtik 
/assign @sttts

### CODE REVIEW

**Comment by sttts** [comment]
lgtm

**Comment by deads2k** [comment]
closing in favor of https://github.com/openshift/origin/pull/18415

**Pull request closed without merging**
