### PR TITLE
Fix template decode error when using new-app to create from a named template

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by bparees** [comment]
fixes https://github.com/openshift/origin/issues/2016

**Comment by smarterclayton** [comment]
Also, I'd like to see a test case for this

**Comment by bparees** [comment]
would something in test-cmd.sh suffice?

**Comment by smarterclayton** [comment]
Yeah, esp. if the original error was an exit code.

----- Original Message -----

**Comment by bparees** [comment]
appears to return RC=1 prior to @csrwng 's fix so i think so.

**Pull request merged**
