### PR TITLE
re-enable jenkins client plugin ext tests

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi 

(there may be some timing issues to sort out with the test pipeline in the client-plugin repo, or an as yet tbd issue accessing oapi objects, with recent 3.10 changes ... let's see what happens)

### CODE REVIEW

**Comment by bparees** [comment]
change lgtm but looks like it is still failing.

**Comment by gabemontero** [comment]
Yeah same failure as before.  The only explanation that comes to my mind is back to a timing thing on the `oc process` actually completing.

I just instantiated that template manually and was able to get the dc with the same name:

```
gmontero ~ $ oc  get deploymentconfig.apps.openshift.io/mongodb
NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
mongodb   1          1         1         config,image(mongodb:3.2)
gmontero ~ $ oc  get deploymentconfig.apps.openshift.io/mongodb -o name
deploymentconfig.apps.openshift.io/mongodb
gmontero ~ $ 
```

Going the update the pipeline job in the client plugin repo and add a delay ... maybe some debug.

**Comment by gabemontero** [comment]
Here is the precise error in the pipeline run:

```
Caught: hudson.AbortException: Unable to retrieve object markup with get; action failed: {reference={}, err=Error from server (NotFound): deploymentconfigs.apps.openshift.io "mongodb" not found, verb=get, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=extended-test-jenkins-pipeline-jkvgw-tnxgk --token=XXXXX get deploymentconfig.apps.openshift.io/mongodb -o=json , out=, status=1}
```

**Comment by gabemontero** [comment]
Yep and re-confirmed, the vanilla image and that portion of the job runs for me when running locally:

```
Created service/mongodb from template with labels [template:mongodb-ephemeral-template, mylabel:myvalue, anotherlabel:anothervalue]
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] echo
Created deploymentconfig.apps.openshift.io/mongodb from template with labels [template:mongodb-ephemeral-template, mylabel:myvalue, anotherlabel:anothervalue]
[Pipeline] echo
Database will run in deployment config: deploymentconfig.apps.openshift.io/mongodb
[Pipeline] readFile
```

**Comment by gabemontero** [comment]
ok ...sorted it out... another client plugin PR / image update needed

Did verify *ALL* the client plugin ext tests locally this time.  Let's hope there are no more openshift/origin breaking changes before I get the stuff merged / updated

**Comment by gabemontero** [comment]
the ext builds test is passing now @bparees with the latest client plugin / image update

**Comment by bparees** [comment]
/lgtm
thanks for getting this working again

**Comment by gabemontero** [comment]
OK, we are now getting the same jenkins_plugin.go error that was in the overnight run:

`Operation cannot be fulfilled on namespaces "e2e-test-jenkins-pipeline-mdffm-2": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.`

Either there is a regression in that the ext test framework cleans up namespaces, or a new restriction has been put in place.

@coreydaley - as ext test babysitter, will you have cycles to check out recent commits to openshift/master, poll usual suspects about this?  If not, I'll circle back to it after some bug curation I need to do .... as a last resort, we can disable those old plugin tests in the interim.

**Comment by gabemontero** [comment]
Unit test failure:

```
=== RUN   TestAttacherAttach
panic: test timed out after 2m0s

goroutine 8 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0x139
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc42017e0f0, 0x1cf5e2d, 0x12, 0x1d70300, 0xc42050fbe8)
	/usr/local/go/src/testing/testing.go:790 +0x59b
testing.runTests.func1(0xc42017e0f0)
	/usr/local/go/src/testing/testing.go:1004 +0xa8
testing.tRunner(0xc42017e0f0, 0xc42050fd28)
	/usr/local/go/src/testing/testing.go:746 +0x16d
testing.runTests(0xc420168a00, 0x28642e0, 0x17, 0x17, 0xc4200e66c8)
	/usr/local/go/src/testing/testing.go:1002 +0x522
testing.(*M).Run(0xc4203adf20, 0x30)
	/usr/local/go/src/testing/testing.go:921 +0x207
main.main()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/volume/csi/_test/_testmain.go:142 +0x2f1

goroutine 19 [chan receive, 2 minutes]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x286fe60)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0xc3
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.0
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x23b

goroutine 36 [chan send, 2 minutes]:
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/watch.(*FakeWatcher).Modify(...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/watch/watch.go:140
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/volume/csi.TestAttacherAttach(0xc42017e1e0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:162 +0x61f
testing.tRunner(0xc42017e1e0, 0x1d70300)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
FAIL	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/volume/csi	120.096s
```

@openshift/sig-storage fyi ^^

**Comment by gabemontero** [comment]
ok thanks @gnufied 

on the test this PR is interested in, @bparees / @coreydaley , either the namespace cleanup got addressed, it is is just a flake that is hiding for the moment.

**Pull request merged**
