### PR TITLE
Update atomic registry quickstart artifacts

### PR DESCRIPTION
**Pull request by aweiteka**
- Enable hostname override in test script
- Patch registry console service to include port 80
- Extend node port range down to port 80
- Use --hostname arg when writing origin config
- Remove tty for unattended install / automated testing
- Fix oauthclient in console template
- Add readiness/liveliness checks in console template
- Misc bugfixes

### CODE REVIEW

**Comment by aweiteka** [comment]
@smarterclayton merge, please.

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by mohammedzee1000** [comment]
Hi, it appears this merge has failed.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
