### PR TITLE
Add SSL information to the backend

### PR DESCRIPTION
**Pull request by imcsk8**
Send PROXY protocol version 2 over connections for the internal connections so we pass more information to ourselves.
cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-send-proxy-v2-ssl

Created this PR as a copy of this one:
https://github.com/openshift/origin/pull/5974
Because it needed to be rebased and I can't edit it.

### CODE REVIEW

**Comment by imcsk8** [comment]
PTAL @openshift/networking

**Comment by knobunc** [comment]
Ivan, can you make sure that the comments in https://github.com/openshift/origin/pull/5974#issuecomment-263994689 are addressed please?

**Comment by imcsk8** [comment]
Yes, i'll check that out

**Comment by pravisankar** [comment]
@imcsk8 @knobunc is this pr still relevant?

**Comment by enj** [comment]
hack/verify-upstream-commits.sh is unhappy due to changes to commit checker.

**Comment by enj** [comment]
/lgtm cancel

To save CI resources.

**Pull request closed without merging**
