### PR TITLE
[stage] UPSTREAM: 53233: Remove containers from deleted pods once containers have exited

### PR DESCRIPTION
**Pull request by joelsmith**
This is a pick to stage of https://github.com/openshift/origin/pull/16913

### CODE REVIEW

**Comment by joelsmith** [comment]
/test extended_conformance_gce
Apparent flake:
```
  1. Hosts:    localhost
     Play:     Ensure all cloud resources necessary for the cluster, including instances, have been started
     Task:     Provision GCP resources
     Message:  Failed without returning a message.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: PROVISION TEST CLUSTER [00h 07m 56s] ##########
```

**Comment by kargakis** [comment]
flaked on https://github.com/openshift/origin/issues/16994

/retest

**Comment by sjenning** [comment]
stage has been recut. this change will come in from master.

**Pull request closed without merging**
