### PR TITLE
UPSTREAM: 21340: Tolerate individual NotFound errors in DeleteCollection

### PR DESCRIPTION
**Pull request by liggitt**
Hold pending rebase
@pweil-, I wasn't sure if you needed to pull this into the rebase PR or just wanted it as a follow-up

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by pweil-** [comment]
> I wasn't sure if you needed to pull this into the rebase PR or just wanted it as a follow-up

picked into the rebase, it was failing `test-cmd.sh` since namespaces got stuck in `Terminating` status.  Do you think we should at least log if a non-estimate error is returned in the namespace controller since it just swallows it and the defer to mark it as done is still executed?

**Comment by liggitt** [comment]
> Do you think we should at least log if a non-estimate error is returned in the namespace controller since it just swallows it and the defer to mark it as done is still executed?

it should do more than log... it shouldn't mark the namespace as done, or we could orphan content.

**Comment by liggitt** [comment]
can you open an upstream issue for that?

**Comment by pweil-** [comment]
:+1: though the ns will still exist because the finalizer isn't removed.  It's still a bad state.  Opening

**Comment by pweil-** [comment]
https://github.com/kubernetes/kubernetes/issues/21406

**Comment by liggitt** [comment]
closing, rolled into https://github.com/openshift/origin/pull/7269

**Pull request closed without merging**
