### PR TITLE
Don't delete deployer pods right away and let them be garbage collected

### PR DESCRIPTION
**Pull request by tnozicka**
Deleting deployer pod right away makes it harder to find out errors and now we have GC so it will be deleted anytime user removes owning RC. (Or revisionHistoryLimit removes that RC.)

@smarterclayton @mfojtik @kargakis WDYT?

### CODE REVIEW

**Comment by smarterclayton** [comment]
It's a big problematic for DC without history limit set.  Maybe this should be time / GC based instead of purely GC based (prune older than short T but within limits if set, else don't prune)

**Comment by smarterclayton** [comment]
"Bit problematic".

I agree in general we have GC like mechanisms to deal with cleanup.  Custom deployments that need volumes might be an issue.

**Comment by tnozicka** [comment]
@smarterclayton at first I thought not having revisionHistoryLimit would be problematic as well but:
 1. If you have revisionHistoryLimit you are probably ok
 2. If you don't and clean those RCs manually GC will clean corresponding deployers as well
 3. If you have mess of RCs and don't clean it; you will have corresponding mess with deployer pods. But since you were not bothered by RCs mess in the first place you probably aren't even with deployer pods

With that said the proposed TTL option looks good too. But people might wonder why it suddenly disappeared. Do we have TTL for any other object?

**Comment by tnozicka** [comment]
> Custom deployments that need volumes might be an issue.

@smarterclayton would you mind going a bit into detail here?

**Comment by tnozicka** [comment]
I guess you mean the ones that require such volume mounted only once but that should get unmounted when the pod finishes not when deleted, right?

Either way AFAIK we don't guarantee in the current implementation that the clean up would happen before a new deployment is created as those are asynchronous operations on different RCs.

**Comment by kargakis** [comment]
This seems fine to me. Do we set a default revision history limit in the new api version?

**Comment by tnozicka** [comment]
@kargakis yes, only in the new api group; I think it's 10.

**Comment by mfojtik** [comment]
Agree, this is fine by me as well, we have revisionHistoryLimit which is defaulted now to deal with the deployer pods. Trying to do GC job in deployer controller seems not working well, we should let the GC do it job.

**Comment by smarterclayton** [comment]
Is the deployer pod now marked as owed by the RC?

**Comment by kargakis** [comment]
Yes

**Comment by smarterclayton** [comment]
I'm ok with this then but we need to be 100% sure we can live with the
outcome.  How do we make sure this is safe?

On Sep 5, 2017, at 9:29 AM, Michail Kargakis <notifications@github.com>
wrote:

Yes

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/16130#issuecomment-327175150>,
or mute
the thread

**Comment by smarterclayton** [comment]
Will this impact pod object count quota?

On Sep 5, 2017, at 9:29 AM, Michail Kargakis <notifications@github.com>
wrote:

Yes

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/16130#issuecomment-327175150>,
or mute
the thread

**Comment by tnozicka** [comment]
Are finished pods (no containers running) accounted to quota or just running ones?

I don't feel strong about this PR if there are any doubts/concerns about the fallout.

There were 3 reason why I proposed that:
1. We have GC + revisionHistoryLimit which makes this work nicely without the cleanup in Deployer controller
1. When we dump po,rc,dc you can reason about the end state of deplyoer pod - like did it fail of succeeded? (to verify there is no error in transitioning between states in the controller.)
1. It reduces the chance of creating deployer pod twice - but we have to fix that race in deployer controller anyways so this is not much of a reason...

**Comment by smarterclayton** [comment]
@sjennings @derekwaynecarr on quota will we have any issues if we leave
terminated deployer pods around (and let them be collected when the RS is
pruned)?

**Comment by tnozicka** [comment]
@sjennings @derekwaynecarr bump

**Comment by kargakis** [comment]
/hold

Use `/hold cancel` to remove

**Comment by tnozicka** [comment]
@jcantrill I think this is what you were asking for



>@sjennings @derekwaynecarr on quota will we have any issues if we leave
terminated deployer pods around (and let them be collected when the RS is
pruned)?

@sjennings @derekwaynecarr bump `#2`

**Comment by jcantrill** [comment]
@tnozicka  I believe this would resolve by question which was:

* Have a post lifecycle hook
* fail policy is set to ignore
* how does one retrieve the logs

Presumably the container stays around so the logs will be available.

**Comment by tnozicka** [comment]
We should get this with deployer controller rewrite.
/close

**Pull request closed without merging**
