### PR TITLE
moved jUnit report for test-cmd to be consistent

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
AWS Infra flake:
```
There was an error talking to AWS. The error message is shown
below:

InsufficientInstanceCapacity => We currently do not have sufficient m4.large capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get m4.large capacity by not specifying an Availability Zone in your request or choosing us-east-1e, us-east-1c, us-east-1b.
```

**Comment by stevekuznetsov** [comment]
@smarterclayton will need a re-tag for AWS flake

**Comment by smarterclayton** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
`test-integration` flake on `TestNewAppRunBuilds`: #8444 
@smarterclayton please re-(re-)tag

**Pull request merged**
