### PR TITLE
e2e: Verify service account token and log cli errors

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k

**Comment by smarterclayton** [comment]
[testonlyextended][extended:core]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
With this change all known failing kube tests are excluded, and there are 4 origin failures.

**Comment by deads2k** [comment]
> With this change all known failing kube tests are excluded, and there are 4 origin failures.

Clearly I should have called it ugly before.

**Comment by liggitt** [comment]
@deads2k: "extended tests are useless"
@smarterclayton: (after making extended tests no longer useless) "nuh-uh"
@deads2k: "my work here is done"

**Comment by smarterclayton** [comment]
Serious Jedi mind tricks here.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
