### PR TITLE
UPSTREAM: 52440: add --dry-run option -> oadm <drain,cordon,uncordon>

### PR DESCRIPTION
**Pull request by juanvallejo**
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1491346

Adds a `--dry-run` flag to `oc adm <cordon, uncordon, drain>`

cc @openshift/cli-review

### CODE REVIEW

**Comment by juanvallejo** [comment]
cc @fabianofranz

**Comment by juanvallejo** [comment]
@fabianofranz or @soltysh mind re-adding /approve tag? thanks!

**Comment by soltysh** [comment]
@juanvallejo from what I see this is different than the current state of upstream pr, mind updating it?

**Comment by juanvallejo** [comment]
@soltysh 
> from what I see this is different than the current state of upstream pr, mind updating it?

it appears that `RunCordonOrUncordon` was updated upstream in patch [db120eb](https://github.com/kubernetes/kubernetes/commit/db120eb8caecf666bfea381aa5ae93f8d0e56ad7?diff=split). Will go ahead and bring ours up to date

**Comment by soltysh** [comment]
> it appears that RunCordonOrUncordon was updated upstream in patch db120eb. Will go ahead and bring ours up to date

I can't be done the way you did it, track the PR that introduced that commit (it's https://github.com/kubernetes/kubernetes/pull/48082 actually) and if it's relevant for us pick it. Otherwise just leave a comment and don't.

**Comment by juanvallejo** [comment]
@soltysh the PR that introduced the commit makes use of the `"k8s.io/api` dep, which we don't have. I can leave a comment stating this, and revert the last commit on this PR. Unless it'd be better to bring in that dependency as part of this patch, wdyt?

**Comment by soltysh** [comment]
@juanvallejo no, we don't have `k8s.io/api` because that was extracted from regular `k8s.io/kubernetes/pkg/api` as part of 1.8 work. Just replace the bits accordingly and drop the pieces we don't care.

**Comment by juanvallejo** [comment]
@soltysh @fabianofranz [upstream pr](https://github.com/kubernetes/kubernetes/pull/52440) has merged, wondering if you could give this one more pass?

**Comment by juanvallejo** [comment]
@soltysh @fabianofranz friendly ping

**Comment by juanvallejo** [comment]
@soltysh wondering if there is any further feedback? Thx.

**Comment by soltysh** [comment]
@juanvallejo squash the upstream changes into a single commit and you need to ping @deads2k for approval. Overall this LGTM.

**Comment by deads2k** [comment]
/approve

Only bugs are merging at the moment.  @fabianofranz can label if necessary.

**Comment by juanvallejo** [comment]
@soltysh thanks, upstream commits squashed

**Pull request merged**
