### PR TITLE
make sure imagestreams are imported before using them with new-app

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/6088

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal

**Comment by bparees** [comment]
[test]

**Comment by csrwng** [comment]
Feels like deja vu all over again :)
I could swear I put together a PR to do this... maybe I never submitted it? 
LGTM [merge]

**Comment by stevekuznetsov** [comment]
@bparees we are trying to use `os::cmd::try_until_success` and phase out the use of `tryuntil`. Do you have the bandwidth to fix that?

**Comment by stevekuznetsov** [comment]
@bparees I'll take it, actually.

**Comment by bparees** [comment]
good because my answer was no. :)

**Pull request merged**
