### PR TITLE
new-app: Don't set spec.tags in output streams

### LINKED ISSUE #3281: new-app shouldn't set spec.tags in the output image stream it creates
If you run this: `oc new-app https://github.com/openshift/ruby-hello-world -l name=ruby-hello-world`, you get this BC:

```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: 2015-06-17T18:54:18Z
  labels:
    name: ruby-hello-world
  name: ruby-hello-world
  namespace: openshiftplayground
  resourceVersion: "280"
  selfLink: /osapi/v1beta3/namespaces/openshiftplayground/buildconfigs/ruby-hello-world
  uid: 423c57b8-1522-11e5-8298-001c422dcd49
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ruby-hello-world:latest
...
```

and this IS:

```yaml
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: 2015-06-17T18:54:18Z
  labels:
    name: ruby-hello-world
  name: ruby-hello-world
  namespace: openshiftplayground
  resourceVersion: "263"
  selfLink: /osapi/v1beta3/namespaces/openshiftplayground/imagestreams/ruby-hello-world
  uid: 423b6e21-1522-11e5-8298-001c422dcd49
spec:
  tags:
  - from:
      kind: DockerImage
      name: library/ruby-hello-world:latest
    name: latest
status:
  dockerImageRepository: 172.30.115.182:5000/openshiftplayground/ruby-hello-world
  tags:
  - items:
    - created: 2015-06-17T18:54:18Z
      dockerImageReference: library/ruby-hello-world:latest
      image: ""
    tag: latest
```

Because this is the ImageStream to which builds push, there shouldn't be any `spec.tags` entry created.

### PR DESCRIPTION
**Pull request by kargakis**
FIxes #3281

@ncdc @csrwng PTAL

### CODE REVIEW

**Comment by csrwng** [comment]
looks good... please add a test case so we can document what we expect out of the ImageStream() method

**Comment by liggitt** [comment]
do the UI new app flows need to make any changes?

**Comment by csrwng** [comment]
the UI one looks fine - no spec https://github.com/openshift/origin/blob/master/assets/app/scripts/services/applicationGenerator.js#L235-L244

**Comment by kargakis** [comment]
@csrwng add unit tests for the ImageStream method covering most of its paths. PTAL

**Comment by kargakis** [comment]
[test]

**Comment by csrwng** [comment]
nice, LGTM

**Comment by kargakis** [comment]
@smarterclayton merge this?

**Comment by smarterclayton** [comment]
[merge]

**Comment by kargakis** [comment]
another [merge]

**Pull request merged**
