### PR TITLE
NO-JIRA: UserDefinedPrimaryNetworks: curl the KAPI IP through eth0

### PR DESCRIPTION
**Pull request by kyrtapz**
Instead of relying on routes use a specific interface for accessing KAPI.

cc: @trozet

### CODE REVIEW

**Comment by trozet** [comment]
/retitle NO-JIRA: UserDefinedPrimaryNetworks: curl the KAPI IP through eth0

**Comment by tssurya** [comment]
/retitle SDN-4930: UserDefinedPrimaryNetworks: curl the KAPI IP through eth0
for UDN PRs please use the EPIC number, thanks in advance!

**Pull request merged**
