### PR TITLE
Combine unique_host.go into host_admitter.go

### PR DESCRIPTION
**Pull request by louyihua**
Currently, host_admitter.go implements the function for ensuring only one route holds a (host, path) pair. So the function in unique_host.go is mainly replaced. Considering that unique_host.go contains bugs in processing route events, the other two functions of allowed namespaces & overrided hostnames are moved into host_admitter.go and unique_host.go should be deleted.
Note that the tests already in host_admitter.go are enough for the 'unique host' feature, so the test invovles UniqueHost plugin can be safely removed.

### CODE REVIEW

**Comment by pweil-** [comment]
@ramr

**Comment by marun** [comment]
I think it would be helpful to add a test that exhibits the reported behavior.

**Comment by ramr** [comment]
Thanks for the PR. It looks like the original assumption is invalid - its not due to the code but rather the ordering of events as they reach the router. 
Please see: https://github.com/openshift/origin/issues/12166 for details.

The issue is related to how we process change events - if routeA is modified after routeB you will get this exact same message  as well and that's expected because routeA holds `host.domain.tld/pathA` at that point in time and so blocks route B.

Please note that the system will correct itself in the next resync interval. The right fix would be to process the events in order - which would be a different fix. Thx

**Comment by louyihua** [comment]
@ramr
I'm sure this is a code bug rather than just an event processing order issue. I've tried what you say myself, and it still showed that route B is denied. You can only recover this state by reloading the router pod manually or deleting route A.
I'll explain why I think this is a code bug here. In the `HandleRoute` function, from L135~L153 it processes the case that one route may displace other route and this is where the bug happens. In the above scenario, before modifying the two routes, there will be two entries in `old := hostToRoute["www.example.com"]` -- first route A (old[0]) and then route B (old[1]). Then when step 3 is processed, the code here will just place the new info of route A in `old[1]`, but not delete its old info in `old[0]`. For simplification, we call the old info of route A as `route A*`, then `old[0]` holds route A* and `old[1]` holds route A. You can see, there will be no chance for the code to update `old[0]`, which will later deny any further route to claim `/pathA`.

**Comment by ramr** [comment]
@louyihua again you are ignoring the order in which events  and the actual events themselves are sent to the watcher process (the openshift-router process in this case).  The easiest way to explain is with some code and some way old school debugging mechanism - `printfs` rule!! ;^)

Let's dump some info from the `p.hostToRoute[host]`  map when we handle the different route events.  Basically see this gist (https://gist.github.com/ramr/334535bfdf56eea8b6f6b7f66159895e) for the git diff/changes.  I tagged the lines ramr, so its easy to grep/see 'em. 

And if you set the log level to 4 you can see some verbose logs. Note that you would have to edit the router dc and add the command and args to set the loglevel. 
`oc edit dc/router`
And then add something like:
```
image: openshift/origin-haproxy-router:latest
command:
    - /usr/bin/openshift-router
    - --loglevel=4
```

The image line have shown for reference, so you know where to insert the command. 

Try that and see the state of the `hostToRoute` map - here's the events I see after I have a route-a with '/pathA' and route-b with '/pathB' added and then I modify route-a and set the path to  '/pathB' - effectively displacing route-b.

Here's the log snippet from : https://gist.github.com/ramr/85d1181854c09ac7fefb0b979e9f236b#file-router-log-file-ab-flipflop-L481

```
I1209 04:11:09.770766       1 unique_host.go:218] Deleting routes for default/route-b
W1209 04:11:09.770775       1 unique_host.go:242] ramr: In DELETE.  Entries for host common.header.test: 
W1209 04:11:09.770781       1 unique_host.go:244] ramr:   default/route-a : /pathA
I1209 04:11:09.770789       1 plugin.go:228] Deleting route &TypeMeta{Kind:,APIVersion:,}
W1209 04:11:09.770936       1 unique_host.go:210] ramr: In ADD/MODIFY. Entries for host common.header.test: 
W1209 04:11:09.770959       1 unique_host.go:212] ramr:   default/route-a : /pathB
I1209 04:11:09.770970       1 status.go:233] admit: route already admitted
```

I do agree that we can clean this up but we have a lot of this code already changed with wildcard route support - new controller is in : https://github.com/openshift/origin/blob/master/pkg/router/controller/host_admitter.go

and eventually this would be replaced with a wee bit more code in there.

**Comment by louyihua** [comment]
@ramr Thanks very much for your detailed explaination.
I can understand what you say: the event order the router receives may cause different results in the current implemenation. But what I really concern about is that this CONFUSES users (including me): although different orders do not affect the objects' FINAL STATES in etcd (in my example, exchange the the execution order of step 3 & 4 gives consistent results in etcd), the router will give different FINAL responses if it receives events in different orders and such different responses CANNOT be fixed later even by a full resync (so why I call these responses FINAL) ! So I believe this INCONSISTENT IS A CODE BUG.
But as you said, I've noticed that there are similar codes in host_admitter.go and unique_host.go. So if the plan is to eliminate unique_host.go by host_admitter.go, I agree that we should work on host_admitter.go instead.

**Comment by louyihua** [comment]
@ramr I've checked that the code in host_admitter.go does not contain such inconsistent. So the only thing to do here is to let host_admitter.go do the work regardless of whether wildcard is enabled or not.

**Comment by ramr** [comment]
@louyihua  awesome ... thanks for the changes - will have to look at this over the next few days.
If someone else can take a look meanwhile - that would be great. 
@knobunc / @marun ?

**Pull request closed without merging**
