### PR TITLE
Make image prefix configurable in e2e tests

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by stevekuznetsov** [comment]
There are some other places like in `test/cmd/builds.sh` where we need this, otherwise LGTM

**Comment by kargakis** [comment]
@stevekuznetsov confirmed with @bparees and it doesn't really matter (not only for test/cmd/builds but for all test/cmd/* tests) since those tests just verify command behavior. Also last time I checked the origin_check suite wasn't even running Docker.

**Comment by kargakis** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
acl

**Pull request merged**
