### PR TITLE
Annotate routes with generated hosts

### LINKED ISSUE #2163: Add an annotation to routes with generated hosts
Clients (like the UI) will likely want to prefer showing routes with user-set hosts over generated hosts. When a generated host is assigned to a route, it would be helpful to also add an annotation with the source of the generated host (e.g. "openshift.io/hostGenerator":"...")

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #2163

### CODE REVIEW

**Comment by liggitt** [comment]
@ramr PTAL

**Comment by pweil-** [comment]
@liggitt - on update we should probably set the annotation to false if the host changes.  If it is removed it will not reallocate and fail validation so that scenario is ok.

**Comment by pweil-** [comment]
@ramr - the non-reallocation seems like a potential future issue for updates if there are rules that do the allocation and the data that drives those rules (like host uniqueness) change.

**Comment by liggitt** [comment]
@pweil- good call on update... routes aren't using generic etcd yet, so I don't have the old route available in update. You ok with a TODO in `Update` to update the annotation when we convert to generic registry?

**Comment by pweil-** [comment]
sure, sounds good.  In that case LGTM.  Use your mighty powers and unleash the merge!

**Comment by liggitt** [comment]
added todos, [merge]

**Comment by ramr** [comment]
@pweil- @liggitt  question here - am not clear here, do we (or the console really) need to know how the route is generated or what the route is? Because once the deployment is done, if you run ```openshift cli get routes -n $ns```, you should see the generated route - similar to if there was one defined for the service. If you treat ```etcd``` as the record of reference, you should have all that information.
As re: uniqueness, looked at this PR and the #2114 , isn't ```$service-$namespace[.$suffix]``` unique enough? Yeah, the embedded ```-``` characters might look weird but should work I think. Though that said it would be good to clean/strip those embedded characters or do a safe generated name.

**Comment by liggitt** [comment]
@ramr, yes we want to know if the route was generated. If there are multiple routes for a service, a custom route host (www.foo.com) is probably more important than a generated one (myservice-mynamespace.openshift.local), so the UI uses that as a hint to prioritize which one it displays as the primary route. You can still see all the routes if you want to

**Comment by liggitt** [comment]
the problem with combining the service and namespace with `-` in the generated case is that these will conflict:
Service: "foo", Namespace: "bar-baz", Generated host: "foo-bar-baz.$suffix"
Service: "foo-bar", Namespace: "baz", Generated host: "foo-bar-baz.$suffix"

**Comment by ramr** [comment]
@liggitt sure I can understand wanting to know that the route was auto-generated and the annotation PR is good (thanks for doing that). But my question was re: how the route was generated - that doesn't need to be visible/known, does it? The current (or generated) value can be retrieved from ```etcd```. 
And yeah, re: the route name collisions, as mentioned above - I agree that is something that could be a potential issue - will add a fix for that.  Do you offhand know the list of valid characters for service name and namespace? ```[a-zA-Z0-9-]```?

**Comment by liggitt** [comment]
> how the route was generated - that doesn't need to be visible/known, does it?

I could see it (maybe) being handy more for backend systems if multiple host generation methods were in play, but the UI wouldn't use that info

**Comment by liggitt** [comment]
service: `[a-z]([-a-z0-9]*[a-z0-9])?`
namespace: `[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`

**Comment by liggitt** [comment]
service can't contain `.`, but namespace can. I think the generated route being `$service.$namespace.$suffix` would prevent clashes

**Comment by ramr** [comment]
@liggitt  thx. Will fix to use dots instead ```.```. Though its a bit different from the old style ```$app-$ns[.$suffix]``` but think that should be ok ... hey, its a brave new world!!
@pweil-  that sound good?

**Comment by pweil-** [comment]
@ramr - dots are fine with me.  Ultimately, no, the allocation strategy doesn't need to be exposed.  What needs to happen is that when we move to v1beta3 we have a spec/status for route that can indicate failure conditions at any level, including a route that is allocated to router A but subsequently rejected by router A

**Comment by smarterclayton** [comment]
Routes should eventually have status that indicates everywhere they are exposed, and that info should also be present on service status.  There is an upstream issue tracking that.

**Pull request merged**
