### PR TITLE
add /spec access for node

### PR DESCRIPTION
**Pull request by liggitt**
pick of https://github.com/openshift/origin/pull/11014/ for 1.3.1

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k I'm seeing the `--raw` test fail against a node in negotiation... that actually doesn't surprise me, but I'm wondering how the test passed in master.

**Comment by deads2k** [comment]
> @deads2k I'm seeing the --raw test fail against a node in negotiation... that actually doesn't surprise me, but I'm wondering how the test passed in master.

Huh.  I don't know.  Bad cache lookup maybe?

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
yum failure, [merge]

**Pull request merged**
