### PR TITLE
make imagestreamimport test less timing sensitive

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/16941

### CODE REVIEW

**Comment by bparees** [comment]
/assign @enj 

@enj if this isn't what you're looking for/expecting, i'm going to need more details about your issue.

**Comment by enj** [comment]
@bparees I will cherry pick this into my PR and see if it helps make the test not flake.  I have no idea exactly why the test fails.

**Comment by enj** [comment]
@bparees no luck, still fails https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16850/test_pull_request_origin_integration/9680/

**Comment by enj** [comment]
(I do not understand the test well enough to tell you why it fails)

**Pull request closed without merging**
