### PR TITLE
Wait for service account token

### LINKED ISSUE #13912: oc login authorization failure
```
=== BEGIN TEST CASE ===
test/cmd/login.sh:93: executing 'oc login --token=' expecting success and text 'system:serviceaccount:project-foo:testserviceaccount'
FAILURE after 0.182s: test/cmd/login.sh:93: executing 'oc login --token=' expecting success and text 'system:serviceaccount:project-foo:testserviceaccount': the command returned the wrong error code; the output content test failed
Standard output from the command:
Authentication required for https://127.0.0.1:28443 (openshift)
Username: Password: Login failed (401 Unauthorized)

There was no error output from the command.
=== END TEST CASE ===
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1461/

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #13912

### CODE REVIEW

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@deads2k PTAL
@bparees FYI

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
re[test]

**Comment by liggitt** [comment]
re[test]

**Comment by deads2k** [comment]
flaked on https://github.com/openshift/origin/issues/13943 and https://github.com/openshift/origin/issues/13944

re[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
flake fix.  Manually merging

**Comment by liggitt** [comment]
> flake fix. Manually merging

relevant test (test_pull_request_origin_check) passed

**Pull request merged**
