### PR TITLE
Bug 1797044: [4.1] Clean up stale egress IP iptables rules on startup

### PR DESCRIPTION
**Pull request by danwinship**
Backport of https://github.com/openshift/sdn/pull/88 (on the way to 3.11...)

### CODE REVIEW

**Comment by danwinship** [comment]
/assign @knobunc @juanluisvaladas 
(Ben reviewed the master PR, openshift/sdn#88, Juan reviewed the 4.3 PR, openshift/sdn#100.)

This is a bugfix to a previous 4.1 backport, so it should be backported to 4.1.

**Comment by shawn-hurley** [comment]
At this point we are only accepting critical bug fixes for 4.1. This does not seem to meet that target, do you want to close it (and the BZ) or make a case for why it is critical?

**Comment by danwinship** [comment]
This is a fix to a previous backport, but it's mostly just cosmetic, I guess.

**Pull request closed without merging**
