### PR TITLE
UPSTREAM: 16432: Fixed race condition in pv binder

### PR DESCRIPTION
**Pull request by markturansky**
Resolves https://github.com/openshift/origin/issues/4829

Upstream PR: https://github.com/kubernetes/kubernetes/pull/16432

@pweil-

### CODE REVIEW

**Comment by pweil-** [comment]
@liggitt since you've already started reviewing this upstream.

@markturansky you'll want to make sure this is added to the upstream tracking issue.

**Comment by markturansky** [comment]
@liggitt upstream changes applied.  

There's a BZ for this issue, too: https://bugzilla.redhat.com/show_bug.cgi?id=1265187

**Comment by markturansky** [comment]
@liggitt I'm going to update this PR with all the feedback provided upstream so I can test thoroughly.  I'll add any other upstream changes as needed.

Thanks for helping me get this PR (and upstream's) squared away.

**Comment by markturansky** [comment]
@liggitt This PR now has all your feedback from upstream.

**Comment by eparis** [comment]
[test]

**Comment by markturansky** [comment]
@eparis I have a lot of feedback from @liggitt and @deads2k in the upstream PR.  I'll refresh this PR with the latest and greatest shortly.

**Comment by deads2k** [comment]
```
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go:70: undefined: testapi
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go:88: undefined: testapi
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node	0.068s	coverage: 56.7% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume [build failed]
```

**Comment by markturansky** [comment]
PR is updated with the latest from upstream.

@deads2k The latest code passes all tests for my locally.  That error you posted will hopefully disappear with the new commit I just pushed.

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
```
# github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go:70: undefined: testapi
_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go:88: undefined: testapi
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node	0.068s	coverage: 56.7% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume [build failed]
```

**Comment by markturansky** [comment]
Strange that just 1 import statement was missing after using hack/cherry-pick.  It is there now.

**Comment by markturansky** [comment]
Squashed per Jordan+IRC

**Comment by liggitt** [comment]
import added in https://github.com/markturansky/origin/commit/fb74ffaaaa0104612fb66174ca8452c18e08d128
[test][merge]

**Pull request merged**
