### PR TITLE
Skip newly enabled networkpolicy tests on IPv6

### PR DESCRIPTION
**Pull request by stbenjam**
These tests are not working correctly on Metal IPv6.  As we've already
reverted and unverted the kube bump several times, we can skip them for
now and TRT has opened a bug to track fixing them (https://bugzilla.redhat.com/show_bug.cgi?id=2072547)

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/hold

@stbenjam make sure it does what you want and then release the hold at your discretion.

**Comment by stbenjam** [comment]
/hold cancel

Metal IPv6 did what I want.

**Pull request merged**
