### PR TITLE
switch to template-service-broker binary

### PR DESCRIPTION
**Pull request by deads2k**
Switches to the new image.

@sdodson @stevekuznetsov did I get the local-image bit right?  I don't see this image pushed to docker hub yet.

### CODE REVIEW

**Comment by deads2k** [comment]
@ewolinetz notice the image name change in the template.

**Comment by ewolinetz** [comment]
@deads2k ack, what would the enterprise version of the image name be?

**Comment by deads2k** [comment]
> @deads2k ack, what would the enterprise version of the image name be?

I think it's `ose-template-service-broker`. @sdodson  please confirm

**Comment by stevekuznetsov** [comment]
Image should be pushed soon

**Comment by bparees** [comment]
lgtm

**Comment by sdodson** [comment]
> I think it's ose-template-service-broker. @sdodson please confirm

origin = 'openshift/origin-template-service-broker'
OCP = 'registry.access.redhat.com/openshift3/ose-template-service-broker' (not implemented yet)

**Comment by bparees** [comment]
@deads2k is this still blocked waiting for an origin release?

**Comment by bparees** [comment]
@deads2k this is going to need some concurrent ansible changes, no?

Also it makes cluster up incompatible yet again (a 3.8 oc binary won't be able to stand up a 3.7 cluster w/ service catalog).

**Comment by ewolinetz** [comment]
This should contain the necessary concurrent ansible change: https://github.com/openshift/openshift-ansible/pull/5726

**Comment by sdodson** [comment]
merge this first then we'll merge the ansible changes, it should continue to work without the ansible changes but the change won't be fully tested until those land.

**Comment by bparees** [comment]
I want to make sure we have a plan for how a 3.8 client binary can deploy the TSB on a 3.7 cluster before we merge this.

(and possibly also how a 3.7 client binary can deploy the TSB on a 3.8 cluster, but that's less critical).

I think the command may need to be more sophisticated to enable backwards compatibility for the image.

**Comment by deads2k** [comment]
> a 3.8 client binary can deploy the TSB on a 3.7 cluster before we merge this.

`oc cluster up`?

**Comment by bparees** [comment]
> oc cluster up?

yeah. the bane of your existence.

**Comment by bparees** [comment]
feel free to make @csrwng help you find a workable solution :)

**Comment by deads2k** [comment]
> (and possibly also how a 3.7 client binary can deploy the TSB on a 3.8 cluster, but that's less critical).

I don't think this is an important use-case.  Forward compatibility like that isn't going to be a reliable thing until you redesign cluster-up.



> I want to make sure we have a plan for how a 3.8 client binary can deploy the TSB on a 3.7 cluster before we merge this.

A plan or actually have it work?  If I understand the tagging scheme correctly, it should be possible to simply detect which tag was requested, right?

**Comment by bparees** [comment]
> A plan or actually have it work? If I understand the tagging scheme correctly, it should be possible to simply detect which tag was requested, right?

How about "have a plan I approve of."?

"include two TSB templates in the oc client binary and then pick which one to use based on the version tag that was requested" is not a plan i'm prepared to approve of just yet...(i might, but i'm going to need some convincing that any other solution is worse or significantly more complex)

**Comment by deads2k** [comment]
> "include two TSB templates in the oc client binary and then pick which one to use based on the version tag that was requested" is not a plan i'm prepared to approve of just yet...(i might, but i'm going to need some convincing that any other solution is worse or significantly more complex)

I think you'll get there.  We'll talk :)

**Comment by bparees** [comment]
spoke with @deads2k offline, i'm going to add a commit to this PR that introduces a 3.7 version of the TSB template and logic in cluster up to pick+deploy the right template for the right cluster version. (wheee).

**Comment by bparees** [comment]
version of this PR that adds cluster up N-1 compatibility: https://github.com/openshift/origin/pull/17338

**Comment by bparees** [comment]
@deads2k this can be closed since i'm carrying it in https://github.com/openshift/origin/pull/17338

**Comment by deads2k** [comment]
> @deads2k this can be closed since i'm carrying it in #17338

thanks

**Pull request closed without merging**
