### PR TITLE
Introduce group controls to SCC

### PR DESCRIPTION
**Pull request by pweil-**
Introduce new strategy knobs for supplemental groups and fsgroup to the SCC.  Both strategies are range based setup (which, in hindsight could've been done for the user strats - I think I will update the PSP proposal with this if folks like it).

In preparation for https://github.com/kubernetes/kubernetes/pull/14991 and <PR pending for FSGroups by @pmorie>

@swagiaal @pmorie @smarterclayton @liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
Al the other fields are phrased as capabilities, but groups are just nouns.  Would suggest RunWithSupplementalGroups and either UseFilesystemGroup or AllowFilesystemGroup

**Comment by smarterclayton** [comment]
Or RunWithFilesysyemGroup

**Comment by pweil-** [comment]
> Al the other fields are phrased as capabilities, but groups are just nouns. Would suggest RunWithSupplementalGroups and either UseFilesystemGroup or AllowFilesystemGroup

Dang, I knew you'd catch that.  I went with the new terminology style proposed in PSP.  I'll change it to be consistent.

**Comment by smarterclayton** [comment]
Well, in PSP did we change the overall structure to be more declarative?
If so, it's ok to have this align to PSP.  I just don't want it to be
inconsistently inconsistent.

On Oct 8, 2015, at 3:06 PM, Paul Weil <notifications@github.com> wrote:

Al the other fields are phrased as capabilities, but groups are just nouns.
Would suggest RunWithSupplementalGroups and either UseFilesystemGroup or
AllowFilesystemGroup

Dang, I knew you'd catch that. I went with the new terminology style
proposed in PSP. I'll change it to be consistent.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5014#issuecomment-146656726>.

**Comment by pweil-** [comment]
Yes, it is more declarative in PSP.  All of the Allow* cruft has been removed, the `RunAsUser` is left alone because it aligned directly with the SecurityContext field.  The names in this PR align with the PSP proposal to just use nouns.  

Current PSP proposal for reference:

```
    // Privileged determines if a pod can request to be run as privileged.
    Privileged bool `json:"privileged,omitempty"`
    // Capabilities is a list of capabilities that can be added.
    Capabilities []api.Capability `json:"capabilities,omitempty"`
    // Volumes allows and disallows the use of different types of volume plugins.
    Volumes VolumeSecurityPolicy `json:"volumes,omitempty"`
    // HostNetwork determines if the policy allows the use of HostNetwork in the pod spec.
    HostNetwork bool `json:"hostNetwork,omitempty"`
    // HostPorts determines which host port ranges are allowed to be exposed.
    HostPorts []HostPortRange `json:"hostPorts,omitempty"`
    // HostPID determines if the policy allows the use of HostPID in the pod spec.
    HostPID bool `json:"hostPID,omitempty"`
    // HostIPC determines if the policy allows the use of HostIPC in the pod spec.
    HostIPC bool `json:"hostIPC,omitempty"`
    // SELinuxContext is the strategy that will dictate the allowable labels that may be set.
    SELinuxContext SELinuxContextStrategyOptions `json:"seLinuxContext,omitempty"`
    // RunAsUser is the strategy that will dictate the allowable RunAsUser values that may be set.
    RunAsUser RunAsUserStrategyOptions `json:"runAsUser,omitempty"`
```

**Comment by smarterclayton** [comment]
Align with PSP

On Oct 8, 2015, at 3:54 PM, Paul Weil <notifications@github.com> wrote:

Yes, it is more declarative in PSP. All of the Allow* cruft has been
removed, the RunAsUser is left alone because it aligned directly with the
SecurityContext field. The names in this PR align with the PSP proposal to
just use nouns.

Current PSP proposal for reference:

    // Privileged determines if a pod can request to be run as privileged.
    Privileged bool `json:"privileged,omitempty"`
    // Capabilities is a list of capabilities that can be added.
    Capabilities []api.Capability `json:"capabilities,omitempty"`
    // Volumes allows and disallows the use of different types of
volume plugins.
    Volumes VolumeSecurityPolicy `json:"volumes,omitempty"`
    // HostNetwork determines if the policy allows the use of
HostNetwork in the pod spec.
    HostNetwork bool `json:"hostNetwork,omitempty"`
    // HostPorts determines which host port ranges are allowed to be exposed.
    HostPorts []HostPortRange `json:"hostPorts,omitempty"`
    // HostPID determines if the policy allows the use of HostPID in
the pod spec.
    HostPID bool `json:"hostPID,omitempty"`
    // HostIPC determines if the policy allows the use of HostIPC in
the pod spec.
    HostIPC bool `json:"hostIPC,omitempty"`
    // SELinuxContext is the strategy that will dictate the allowable
labels that may be set.
    SELinuxContext SELinuxContextStrategyOptions
`json:"seLinuxContext,omitempty"`
    // RunAsUser is the strategy that will dictate the allowable
RunAsUser values that may be set.
    RunAsUser RunAsUserStrategyOptions `json:"runAsUser,omitempty"`

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/5014#issuecomment-146668733>.

**Comment by pweil-** [comment]
@pmorie @deads2k @liggitt  - some review action on this now that we're agreed on the naming?

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
tagging some extra reviewers @soltysh @miminar

**Comment by smarterclayton** [comment]
What commit will carry the implementation of their enforcement?

**Comment by pweil-** [comment]
> What commit will carry the implementation of their enforcement?

I need to build that on top of the branch @swagiaal has so I can get his PRs for the api types which are not yet in upstream.  I am dependent on that for the supp groups and @pmorie 's upstreams for fsgroup (In progress)

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
