### PR TITLE
Make views translatable

### PR DESCRIPTION
**Pull request by tagoh**
There should be some required work to enable OpenShift internationalized completely, thought it may be a good idea to submit a PR for initial effort.
This change sets are missing the code for:
 * strings in UI where is defined in the configuration block. due to the limitation in AngularJS, we can't call other service there.
 * strings in tooltips
 * configuration to determine which language one prefers.

### CODE REVIEW

**Comment by liggitt** [comment]
@jwforres fyi

**Comment by liggitt** [comment]
Thanks for the pull request. I wonder if this is a bit premature. We have a mix of messages/content from the UI, the API, and display names in API objects (projects, templates, soon template parameters, etc). I think we should figure out how we would want to translate all of those before we decide on a particular mechanism for the UI. I'm also not as familiar with translation tools for angular… is the one in this PR considered the standard or does there need to be a comparison done to select one? @jwforres, any thoughts?

**Comment by jwforres** [comment]
The two main options seem to be angular-translate and anguler-gettext.  Why did you choose to go with gettext?

**Comment by tagoh** [comment]
Because most translators are familiar with gettext rather than the kinda  KVS in JSON and they are not also familiar with the technical things. if we would go ahead with angular-translate, we may see some troubles so that modifying JSON directly may introduces the breakage easily.

**Comment by tagoh** [comment]
Updated.

**Comment by tagoh** [comment]
BTW what's missing to get this PR merged in? I'll do my best for something I can do but I'm not quite sure what's the plan so far for something else I can't do or you are going to do. if any details, please let me know.

Basically it doesn't affect a lot to the behavior itself though, my concern on merging is, there are still some content depending on the English grammar with html tag structure, which is expected to see like a sentence in English on browsers though, it doesn't necessarily looks like that for translated one so that some languages doesn't follow the English grammar.

**Comment by juhp** [comment]
@liggitt @jwforres how can we move forward with this?

Would splitting up the patch help?

**Comment by jwforres** [comment]
There are concerns both with this particular approach and in general with trying to implement a translation framework right now:

1) This approach is using the strings themselves as the message ID for translation, what happens if you have the same word in english but intended for two different contexts that may need two different translations in certain languages?  We should probably be using an actual identifier.

2) The web console is made up of UI bits coming from a number of shared UI repositories, each of which would have to be independently translated. We need to agree amongst the various projects contributing angular components what angular translation tool we are going to use.  There are at least three other repos right now besides this one that would need translation.

3) We also have all of the templates the user can use to create content in their project.  Those templates contain names and descriptions that the UI exposes to end users.  https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples

4) The API returns status messages, error messages, phases, and other various things that we show directly to end users.

We need to have a larger discussion about the translation approach across the project stack, and need to approve a proposal before implementing something.  ( https://github.com/openshift/origin/tree/master/docs/proposals )  Once we add the framework and the English translation we will have to maintain that for every new feature we add moving forward.  It will add overhead to the project and slow it down.  We need to make sure we are taking the correct approach before we agree to take on that overhead.

**Comment by jwforres** [comment]
Opened an issue to start the discussion https://github.com/openshift/origin/issues/5831

**Comment by tagoh** [comment]
This seems no longer valid PR since the web console part has been separate to the origin-web-console. I've submited another one to that component https://github.com/openshift/origin-web-console/pull/51. FYI.

**Pull request closed without merging**
