### PR TITLE
don't block on stdout during binary build attach

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/15215

### CODE REVIEW

**Comment by csrwng** [comment]
lgtm once extended tests pass

**Comment by bparees** [comment]
(extended tests still being skipped for some reason)

**Comment by bparees** [comment]
@stevekuznetsov extended tests are still being skipped even when explicitly requested (as well as when they match filepath patterns).  Is this an understood issue?

**Comment by bparees** [comment]
@stevekuznetsov status says extended_builds was skipped, ci-bot says extended_builds failed, and gubernetator says "500 error".

**Comment by jim-minter** [comment]
There's further code below in pkg/build/registry/buildconfiginstantiate/rest.go which references https://github.com/kubernetes/kubernetes/issues/44448 and which I think also has to be removed.

**Comment by bparees** [comment]
/hold cancel

extended builds test has passed.

**Comment by bparees** [comment]
> There's further code below in pkg/build/registry/buildconfiginstantiate/rest.go which references kubernetes/kubernetes#44448 and which I think also has to be removed.

removed.

**Comment by stevekuznetsov** [comment]
Yeeesh -- @bparees this is the same bug I opened last week against `test-infra` IIRC. I'm not sure we have picked up the fix yet.

**Comment by bparees** [comment]
/hold
(hold for passing build tests)

**Comment by bparees** [comment]
/hold cancel
builds failure was known issue.

**Pull request merged**
