### PR TITLE
TRT-813: Disabling disruption fallback for upgrades

### PR DESCRIPTION
**Pull request by deepsm007**
https://issues.redhat.com/browse/TRT-813

/cc @xueqzhan

### CODE REVIEW

**Comment by dgoodwin** [comment]
Just needs a unit test adjustment, the other failures look unrelated even though rated high, lots of the loki problem, and I think the etcd scaling job has something else wrong.

It looks like we passed the gcp-ovn-upgrade, which is great.

**Comment by dgoodwin** [comment]
/approve
/lgtm cancel

Approved so anyone can lgtm once that test is adjusted.

**Comment by dgoodwin** [comment]
@neisw may be of interest, we didn't get another batch of risk analysis on this one.

**Comment by neisw** [comment]
It is still a manual process since we don't have it deployed anywhere, but I saw this too and kicked off the import locally.  I have the record and when import is done will run the commenter.

**Comment by neisw** [comment]
On a more positive note, openshift-technical-release-staff@redhat.com isn't getting spammed with each update any longer.  Sorry Deep hijacking your PR  ;-)

**Comment by dgoodwin** [comment]
> Job Failure Risk Analysis for sha: [ec6b3d5](https://github.com/openshift/origin/commit/ec6b3d510955c8d20d279c2dbb3eeef0d1d1c0e5)
> Job Name 	Failure Risk
> [pull-ci-openshift-origin-master-e2e-aws-ovn-cgroupsv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27701/pull-ci-openshift-origin-master-e2e-aws-ovn-cgroupsv2/1621226490752405504) 	High
> [pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27701/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-upgrade/1621226530602487808) 	High

@neisw a possible bug question on the above, the actual jobs don't seem to have risk analysis in the spyglass, any idea what's happening there?

**Pull request merged**
