### PR TITLE
don't run conformance tests w/ serial unless they are part of the focus

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/16626

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov @miminar @jim-minter I firmly believe this is the right solution to our current e2e serial testing w/ focus problem.  I know the long term vision is a separate serial suite (and ultimately no serial tests at all) but for now this gets the behavior closer to correct at a minimal cost, with minimal complexity, while preserving the ability to run focused tests on serial items.

**Comment by smarterclayton** [comment]
Several of the serial tests can't be focused with that.  But I'm fine if
this fits your immediate need.

Stop using serial.


On Oct 17, 2017, at 11:04 PM, Ben Parees <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> @stevekuznetsov
<https://github.com/stevekuznetsov> @miminar <https://github.com/miminar>
@jim-minter <https://github.com/jim-minter> I firmly believe this is the
right solution to our current e2e serial testing w/ focus problem. I know
the long term vision is a separate serial suite (and ultimately no serial
tests at all) but for now this gets the behavior closer to correct at a
minimal cost, with minimal complexity, while preserving the ability to run
focused tests on serial items.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/16919#issuecomment-337370872>,
or mute
the thread

**Comment by bparees** [comment]
> Stop using serial.

getting rid of the build test one here:
https://github.com/openshift/origin/pull/16924

registry ones are going to be a harder slog.

**Comment by jim-minter** [comment]
does this close #16626?
is it worth opening a tracking issue for migrating registry tests of serial?

**Comment by bparees** [comment]
> does this close #16626?

yes, updated the description.

> is it worth opening a tracking issue for migrating registry tests of serial?

yes, opened https://github.com/openshift/origin/issues/16942

**Pull request merged**
