### PR TITLE
bump(github.com/openshift/source-to-image): 7f58756254b0a65bf59fa87a8ecedad01ce6a85b

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
[test][extended:core(builds)]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
extended builds passed.
[testextended][extended:core(image_ecosystem)]

**Comment by bparees** [comment]
Expected failures.  [merge][severity:blocker]

Ben Parees | OpenShift

**Pull request merged**
