### PR TITLE
Use server side resource list in the client

### PR DESCRIPTION
**Pull request by pweil-**
to determine what builders to use in the graph and what types the "all" alias should include.

@liggitt - if this looks reasonable then I'll write up tests for the new methods.

```
# openshift server
[vagrant@openshiftdev origin]$ oc get all
NAME                TYPE      SOURCE
ruby-sample-build   Docker    git://github.com/openshift/ruby-hello-world.git
NAME                  TYPE      STATUS    POD
ruby-sample-build-1   Docker    New       ruby-sample-build-1-build
NAME                 DOCKER REPO                 TAGS      UPDATED
origin-ruby-sample                                         
ruby-20-centos7      openshift/ruby-20-centos7   latest    33 minutes ago
NAME       TRIGGERS                    LATEST VERSION
database   ConfigChange                1
frontend   ConfigChange, ImageChange   0
CONTROLLER   CONTAINER(S)               IMAGE(S)                     SELECTOR                                                        REPLICAS   AGE
database-1   ruby-helloworld-database   openshift/mysql-55-centos7   deployment=database-1,deploymentconfig=database,name=database   1          33m
NAME         HOST/PORT         PATH      SERVICE    LABELS                                      TLS TERMINATION
route-edge   www.example.com             frontend   template=application-template-dockerbuild   edge
NAME         CLUSTER_IP     EXTERNAL_IP   PORT(S)    SELECTOR        AGE
database     172.30.31.56   <none>        5434/TCP   name=database   33m
frontend     172.30.2.166   <none>        5432/TCP   name=frontend   33m
kubernetes   172.30.0.1     <none>        443/TCP    <none>          21h
NAME               READY     STATUS    RESTARTS   AGE
database-1-tps0t   1/1       Running   0          33m

# aes server
[vagrant@openshiftdev origin]$ oc get all
NAME                 DOCKER REPO                 TAGS      UPDATED
origin-ruby-sample                                         
ruby-20-centos7      openshift/ruby-20-centos7   latest    33 minutes ago
NAME       TRIGGERS                    LATEST VERSION
database   ConfigChange                1
frontend   ConfigChange, ImageChange   0
CONTROLLER   CONTAINER(S)               IMAGE(S)                     SELECTOR                                                        REPLICAS   AGE
database-1   ruby-helloworld-database   openshift/mysql-55-centos7   deployment=database-1,deploymentconfig=database,name=database   1          33m
NAME         HOST/PORT         PATH      SERVICE    LABELS                                      TLS TERMINATION
route-edge   www.example.com             frontend   template=application-template-dockerbuild   edge
NAME         CLUSTER_IP     EXTERNAL_IP   PORT(S)    SELECTOR        AGE
database     172.30.31.56   <none>        5434/TCP   name=database   33m
frontend     172.30.2.166   <none>        5432/TCP   name=frontend   33m
kubernetes   172.30.0.1     <none>        443/TCP    <none>          21h
NAME               READY     STATUS    RESTARTS   AGE
database-1-tps0t   1/1       Running   0          33m
```

### CODE REVIEW

**Comment by pweil-** [comment]
cc @fabianofranz @smarterclayton

**Comment by smarterclayton** [comment]
This is close but doesn't solve other problems.  I've been remiss in copying this across various discussion threads but we need to be listing the resources available as part of the API document for a particular version.  We have to get that agreed on upstream.  Once we have that, we should cache the list of server resources locally (I don't want to make a call to the server every time we need this).  It's not enough to get it from one endpoint, because there will be multiple API groups.

Hiding build from the CLI for 3.1 isn't more important in my mind than getting all of the above right.  If we did everything above and not hide it from the CLI I would not be concerned.

**Comment by smarterclayton** [comment]
And the lookup for this needs to fit into version negotiation, which needs to be changed so that we only do it at startup (version negotiation and the lookup of the resource list is a start).

**Comment by pweil-** [comment]
> Hiding build from the CLI for 3.1 isn't more important in my mind than getting all of the above right. If we did everything above and not hide it from the CLI I would not be concerned.

Ok.  In that case I think we're about as far as we can go on the AE CLI without the server side type exposure.  Will update that thread.

**Comment by smarterclayton** [comment]
The API stuff will probably fall on your team - Jordan and David have been
in the discussions about API discovery, and cloudforms has a dependency on
this as well.

On Aug 26, 2015, at 1:53 PM, Paul Weil <notifications@github.com> wrote:

Hiding build from the CLI for 3.1 isn't more important in my mind than
getting all of the above right. If we did everything above and not hide it
from the CLI I would not be concerned.

Ok. In that case I think we're about as far as we can go on the AE CLI
without the server side type exposure. Will update that thread.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/pull/4380#issuecomment-135106573>.

**Pull request closed without merging**
