### PR TITLE
Add extended tests for DC ControllerRef

### PR DESCRIPTION
**Pull request by tnozicka**
Test that DC controller adheres to [Three Laws of Controllers](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md#the-three-laws-of-controllers).

cc: @mfojtik @kargakis

### CODE REVIEW

**Comment by tnozicka** [comment]
[test]

**Comment by tnozicka** [comment]
Fixes https://github.com/openshift/origin/pull/14880

**Comment by tnozicka** [comment]
prerequisite for https://github.com/openshift/origin/pull/14907

**Comment by mfojtik** [comment]
LGTM [merge]

**Pull request merged**
