### PR TITLE
add version info to :latest imagestreamtags

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@luciddreamz ptal

**Comment by luciddreamz** [comment]
@bparees Looks good, thanks!

**Comment by smarterclayton** [comment]
Isn't this broken as soon as an admin tags in a new value?

**Comment by smarterclayton** [comment]
Isn't this a bug in the UI that should be following the annotation?

**Comment by luciddreamz** [comment]
@smarterclayton This was a fix for https://github.com/openshift/origin-web-console/issues/242

If there is a better fix or if this fix doesn't cover admin use-cases I'm all for doing something different. At the moment this just brings the :latest image stream description to parity with the :1.0 version tagged image streams, as was suggested in the thread on the above issue.

**Comment by luciddreamz** [comment]
@jwforres @spadgett Feel free to weigh in here

**Comment by bparees** [comment]
> Isn't this broken as soon as an admin tags in a new value?

@smarterclayton only if they don't also update the description when they do so.....

we did this so the web console wouldn't have to do crazy stuff to figure out what :latest really pointed to.

**Comment by bparees** [comment]
@sdodson this is the PR from the email thread.

**Comment by smarterclayton** [comment]
Define crazy stuff?  Chasing the tag?  Papering over the fact that
it's not doing the right thing seems worse.

**Comment by bparees** [comment]
> Define crazy stuff?  Chasing the tag? 

imo yes, I didn't feel it was a detail the console should have to worry about, but i'll leave it up to you and @jwforres to discuss.

**Comment by smarterclayton** [comment]
Since its exposed in the API and we respect it, I think it's
reasonable for clients to understand.

Istag for that ref should probably DTRT, but may not.

**Comment by bparees** [comment]
DTRT?

anyway if @jwforres signs up to do this in the console, we can close this PR.

**Comment by spadgett** [comment]
I'll look at updating the web console to chase the tags. It doesn't seem too bad.

**Comment by smarterclayton** [comment]
Do The Right Thing

**Comment by bparees** [comment]
Careful, Spike Lee watches this repo..

Ben Parees | OpenShift

**Comment by bparees** [comment]
closing since the web console is going to deal with this.

**Comment by jwforres** [comment]
so @spadgett started chasing the from tags, i question how far we want to chase them... through multiple levels of from's that can cross namespace boundaries that we may not be able to fetch details about as the end user?  We can do the simple things like from's within the same imagestream (which fixes the 'latest' problem on our OOTB stuff), or from's within the same namespace.

**Comment by smarterclayton** [comment]
Only tags in the same image stream are truly referential (in the sense
that tagging one results in the other being tagged).  All others must
be imported or explicitly tagged.  Tags with "reference=true" are
slightly different - the server code just points to whatever the pull
reference in status tags says (:latest reference=true to
some/other:tag will just use some/other:tag for build and deployment
triggers)

**Comment by spadgett** [comment]
Wondering if it's not better to show something like "ruby:latest (tracks ruby:2.3)" anyway?

**Pull request closed without merging**
