### PR TITLE
Use the privileged SCC for all kube e2e tests

### PR DESCRIPTION
**Pull request by smarterclayton**
Also prevent infinite waits on builds that never start due to missed or
invalid triggers.

[test][extended:core]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@liggitt @mfojtik

**Comment by mfojtik** [comment]
Running test/extended/core.sh...
# _/data/src/github.com/openshift/origin/test/extended
test/extended/extended_test.go:8:2: no buildable Go source files in /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/authentication
FAIL	_/data/src/github.com/openshift/origin/test/extended [setup failed]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
