### PR TITLE
Switch origin to use gotest2junit

### PR DESCRIPTION
**Pull request by smarterclayton**
Update a few other small changes that were made to the common scripts,
and remove special cased output from 3.10 for pushing releases
alongside.

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton Why am I revendoring this?  I shouldn't have to. I should be able to use a simple `go get` instead.

@juanvallejo do you know where this lives and how to depend on it so we don't end up copying everywhere

**Comment by smarterclayton** [comment]
Juan can take this out as a later step.  I’m more concerned right now with identifying and getting flakes out of the CI infra so other people aren’t impacted.  The two things are orthogonal.

**Comment by smarterclayton** [comment]
Juan, note that if you make changes to core scripts in hack you should do it in openshift/release and sync them to origin as you are testing.  That’s the canonical location for most of the release scripting, and other repos reuse it.

**Comment by smarterclayton** [comment]
Many of the origin scripts still need to be normalized and origin’isms split out - I’ve noticed people have been making changes here without keeping release up to date.

**Comment by soltysh** [comment]
> Juan, note that if you make changes to core scripts in hack you should do it in openshift/release and sync them to origin as you are testing. That’s the canonical location for most of the release scripting, and other repos reuse it.

Are we going to disallow changing them directly in origin at some point and guard against such problems?

**Comment by juanvallejo** [comment]
> Are we going to disallow changing them directly in origin at some point and guard against such problems?

Ideally we won't have the source for these tools in Origin in the future, and we'll simply build them from a source repo using `go get`

**Comment by stevekuznetsov** [comment]
Disallowing them should be very simple, just another verify script like the commit verifier

**Comment by deads2k** [comment]
> Disallowing them should be very simple, just another verify script like the commit verifier

That isn't the problem. The problem is making a copy of this tooling code in every split repo that we have.  It's messy and inconsistent and it doesn't have to be.

**Comment by juanvallejo** [comment]
@deads2k 
> do you know where this lives and how to depend on it so we don't end up copying everywhere

Opened PR addressing this here https://github.com/openshift/origin/pull/20261

**Pull request merged**
