### PR TITLE
allow sys_chroot cap on SCCs

### PR DESCRIPTION
**Pull request by pweil-**
Removes the requirement to drop chroot. 

@smarterclayton

### CODE REVIEW

**Comment by pweil-** [comment]
@openshift/security

**Comment by php-coder** [comment]
@bparees Should we allow this cap also to the building containers? Is it possible that we would need it?

**Comment by pweil-** [comment]
It is in the [default set of caps from docker](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) but we were requiring it to be dropped prior to this PR.

**Comment by php-coder** [comment]
@pweil- Was the previous comment, an answer to my question? I was asking about should we also remove it from this list: https://github.com/openshift/origin/blob/7d661a2f0a0d7f141df51268981f7cea783dbbc2/pkg/build/controller/strategy/sti.go#L35

**Comment by pweil-** [comment]
> I was asking about should we also remove it from this list:

Seems reasonable to remove it there if we're removing it from `restricted`

**Comment by bparees** [comment]
what's the basis for us not requiring it to be dropped any longer?  s2i is using that list of caps to drop because it runs the container directly, so it needs to manage the caps independently.

**Comment by pweil-** [comment]
`sys_chroot` is required by some of our containers that do scanning which led to our discussion of whether or not it should really be required as a drop.  Ultimately, the `chroot` call is not considered a security feature of the kernel and folks are still relying on DAC and SELinux in order to protect the system.  

Some references for posterity:

* https://access.redhat.com/blogs/766093/posts/1975883 
> The basic idea is that you can run a process inside of a chroot where it will not have access to various system resources; however, chroot is not a security feature.


* http://man7.org/linux/man-pages/man2/chroot.2.html
> In particular, it is not intended to be used
       for any kind of security purpose, neither to fully sandbox a process
       nor to restrict filesystem system calls.

**Comment by bparees** [comment]
@pweil- ok in that case can you remove it from the spot @php-coder noted as well?

**Comment by pweil-** [comment]
updated

**Comment by bparees** [comment]
s2i change lgtm

**Comment by pweil-** [comment]
[test]

**Comment by pweil-** [comment]
/assign @smarterclayton 

bump for review

**Comment by php-coder** [comment]
PTAL @smarterclayton

**Comment by smarterclayton** [comment]
/lgtm 

as well

**Comment by enoodle** [comment]
@pweil- @bparees @php-coder 
Hello,
Is this available in Openshift 3.7 (`oc v3.7.27`)? I am getting `operation not permitted` when trying to chroot inside a non privileged container.

**Comment by php-coder** [comment]
@enoodle Yes, it is:
```console
$ git tag --contains 2d59f8e4c059df09e339e2bb0355cdbc6a78279e | grep 3.7
v3.7.0
v3.7.0-rc.0
v3.7.1
```
I'd suggest you to do the following:
- check by what SCC a pod was admitted (`oc get pod <name> -o yaml | grep scc`)
- check whether the output of the `oc adm policy reconcile-sccs` command is empty
- check whether a pod is requesting `SYS_CHROOT` capability in its `securityContext`

HTH

**Comment by enoodle** [comment]
Thanks for your help @php-coder I indeed had to request this capability directly.

**Pull request merged**
