### PR TITLE
Fix recylcer image

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1598334

cc @deads2k @liggitt @childsb

### CODE REVIEW

**Comment by gnufied** [comment]
Again the failure here looks unrelated:

```
rror: timed out waiting for the condition
[ERROR] [11:54:21+0000] PID 3197: hack/lib/cmd.sh:241: `return "${return_code}"` exited with status 1.
[INFO] [11:54:21+0000] 		Stack Trace: 
[INFO] [11:54:21+0000] 		  1: hack/lib/cmd.sh:241: `return "${return_code}"`
[INFO] [11:54:21+0000] 		  2: test/extended/clusterup.sh:204: os::cmd::expect_success
[INFO] [11:54:21+0000] 		  3: test/extended/clusterup.sh:45: os::test::extended::clusterup::service_catalog
[INFO] [11:54:21+0000] 		  4: test/extended/clusterup.sh:390: os::test::extended::clusterup::run_test
[INFO] [11:54:21+0000]   Exiting with code 1.
[INFO] [11:54:21+0000] [CLEANUP] Beginning cleanup routines...
[INFO] [11:54:21+0000] [CLEANUP] Dumping cluster events to _output/scripts/clusterup/artifacts/events.txt
error: A server URL must be specified
[INFO] [11:54:21+0000] [CLEANUP] Dumping etcd contents to _output/scripts/clusterup/artifacts/etcd
[INFO] [11:54:21+0000] No compiled `etcdhelper` binary was found. Attempting to build one using:
[INFO] [11:54:21+0000]   $ hack/build-go.sh tools/etcdhelper
++ Building go targets for linux/amd64: tools/etcdhelper
[INFO] [11:55:12+0000] hack/build-go.sh exited with code 0 after 00h 00m 51s
ERROR: unable to create client config: open /tmp/openshift/clusterup/openshift.local.config/master/master.etcd-client.crt: no such file or directory
```

**Comment by eparis** [comment]
removing lgtm because i'm tired of the bot testing over and over and over and over

**Comment by gnufied** [comment]
The failure is surely a flake unrelated to this PR . I created a new github issue - https://github.com/openshift/origin/issues/20757

**Comment by childsb** [comment]
@gnufied opened an issue on the test flake, re-adding the lgtm

**Pull request merged**
