### PR TITLE
Cherry Pick: Fix base64.channel.k8s.io WebSocket protocol decoding

### LINKED ISSUE #4985: /exec endpoint with base64.channel.k8s.io does not decode data
The /exec WebSocket pod endpoint using the "base64.channel.k8s.io" protocol does not properly decode data.

If I open a WebSocket to ```.../exec?command=/bin/sh&...``` and ```ws.send("0", btoa("test"))``` I can see base64 characters being echoed.

### PR DESCRIPTION
**Pull request by stefwalter**
The frames in base64.channel.k8s.io were not being base64 decoded.

Fixes #4985

### CODE REVIEW

**Comment by liggitt** [comment]
all upstream commits need to have the `UPSTREAM: <pr#>: ...` title format. Coordinate with @smarterclayton about pulling this into his upstream PR and you can reuse the same PR number

**Comment by kargakis** [comment]
> all upstream commits need to have the UPSTREAM: <pr#>: ... title format.

This is helpful for future rebasers, see: https://github.com/openshift/origin/blob/master/HACKING.md#cherry-picking-an-upstream-commit-into-origin

**Comment by stefwalter** [comment]
Rebased, and changed thish pull request so it cherry-picks changes from @smarterclayton in https://github.com/kubernetes/kubernetes/pull/13885

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
