### PR TITLE
Add new option to exclude imagestream tag from pruning by regular expression

### PR DESCRIPTION
**Pull request by legionus**
Re-open #16580 

/cc @bparees @dmage @miminar 

associated docs:
https://github.com/openshift/openshift-docs/pull/6429

### CODE REVIEW

**Comment by ctrought** [comment]
Hi @legionus, I know this was quite some time back but I've been looking for a solution to have some more granularity over pruning of images and this looked to satisfy what I needed, to either exclude images from a namespace or specific tags (ie. latest) across many namespaces. Any particular reason this did not make it in?

**Comment by legionus** [comment]
@bparees @dmage ^

**Pull request closed without merging**
