### PR TITLE
Add build revision info to osc status

### PR DESCRIPTION
**Pull request by smarterclayton**
@bparees review

### CODE REVIEW

**Comment by bparees** [comment]
don't we want this in the regular describe build too?

**Comment by smarterclayton** [comment]
I'm sure we do.

**Comment by bparees** [comment]
so are you going to add it?

**Comment by smarterclayton** [comment]
Not in this pull

**Comment by bparees** [comment]
then lgtm i guess.

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/issues/1814 opened

**Pull request merged**
