### PR TITLE
Updating external examples

### PR DESCRIPTION
**Pull request by coreydaley**
*-ex repository templates have been updated so now we are
updating the ones included with origin

@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
@coredaley you're going to need to run hack/update-generated-bootstrap

**Comment by coreydaley** [comment]
@bparees updated, thanks!

**Comment by bparees** [comment]
[merge]

**Comment by coreydaley** [comment]
[test]

**Comment by csrwng** [comment]
[merge]

**Pull request merged**
