### PR TITLE
fix autoprovision enabled field name

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal, the actual json field name didn't get updated when i changed the struct. oops.

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by bparees** [comment]
TC fixed [merge]

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/7706
[merge]

**Pull request merged**
