### PR TITLE
Bug 1951728: Speed up vsphere volume provisioning

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1951728

### CODE REVIEW

**Comment by duanwei33** [comment]
I'm following JIRA issue DPTP-660 to do the pre-merge verification. Used the cluster-bot launching an env with the still open but Dev-approved PR(s).
The bug is pre-merge verified in [1951728#c2](https://bugzilla.redhat.com/show_bug.cgi?id=1951728#c2)

**Comment by duanwei33** [comment]
Adding QE lgtm.
/lgtm

**Comment by sdodson** [comment]
/close
The linked BZ has been closed EOL

**Pull request closed without merging**
