### PR TITLE
Revert "new-app: verify if API has required resources enabled"

### PR DESCRIPTION
**Pull request by bparees**
Reverts openshift/origin#20020

This doesn't work with cluster up (discovery doesn't work w/ aggretation).  Ask @deads2k for more details.

### CODE REVIEW

**Comment by deads2k** [comment]
As an overall experience with kubectl and oc CLIs, the commands create as much as possible and continue on failures. The commands are idempotent so they can be retried and they are pipeable to delete for cleanup. The original change ran afoul of those principles. Also, in 3.11 (maybe 3.10 too), the disableFeature that led to this is gone.

@wozniakjan @soltysh @juanvallejo @mfojtik

**Comment by deads2k** [comment]
This also flakes in e2e handling.

/lgtm

**Comment by bparees** [comment]
redoing this here: https://github.com/openshift/origin/pull/20781

**Pull request closed without merging**
