### PR TITLE
[DO_NOT_MERGE] trivial change of log

### PR DESCRIPTION
**Pull request by tedyu**

### CODE REVIEW

**Comment by bparees** [comment]
this change would need to be made upstream and then vendored into origin.

**Comment by tedyu** [comment]
@bparees 
I was investigating e2e-gcp-upgrade failure :

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/24686/pull-ci-openshift-origin-master-e2e-gcp-upgrade/2825/artifacts/e2e-gcp-upgrade/

which was for porting #89055 from upstream.

I opened this PR to try out several scenarios since e2e-gcp-upgrade doesn't exist upstream.

I am going to open another PR - please keep it open.

**Comment by bparees** [comment]
> I am going to open another PR - please keep it open.

got it, thank you for the explanation.

i've reopened this one but you can close it if you don't need it.

**Comment by tedyu** [comment]
It seems e2e-gcp-upgrade is failing in master branch.

Let's keep this open for a few days just in case there is other existing test failure.

**Pull request closed without merging**
