### PR TITLE
WIP: Rebase 1.6.0 beta3

### LINKED ISSUE #13419: protobuf loses distinction between nil and empty slice
See https://github.com/kubernetes/kubernetes/issues/43203

Origin has more resources that make use of that distinction than kube does

Need to resolve this before we release with protobuf storage enabled (or ship with controllers speaking protobuf)

## Interesting fields

In this table, "Differentiated" indicates whether Origin treats `nil` and `[]` interchangeably.

| Field | Shipped | `omitempty` | Nil-persistable  | Differentiated | Fix | Notes |
| ----- |--------- | ---------- | ----------------- | -------------- | --- | ----- |
| `v1.BrokerTemplateInstanceSpec.BindingIDs` | No | No | No | No | Add `omitempty` | Enforced by generated internal→external conversion |
| `v1.BuildConfigSpec.Triggers` | Yes | No | No | No |  | False positive; Enforced by custom external→internal conversion |
| `v1.BuildRequest.TriggeredBy` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.BuildSpec.TriggeredBy` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ClusterRole.Rules` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ClusterRoleBinding.Subjects` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ClusterRoleScopeRestriction.Namespaces` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ClusterRoleScopeRestriction.RoleNames` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.DeploymentDetails.Causes` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.EgressNetworkPolicySpec.Egress` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ExecNewPodHook.Command` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.GroupRestriction.Groups` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.GroupRestriction.Selectors` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.Image.DockerImageLayers` | Yes | No | Yes | No | TBD | None |
| `v1.ImageSignature.Content` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ImageSource.Paths` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.LocalSubjectAccessReview.GroupsSlice` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.PodSecurityPolicyReviewStatus.AllowedServiceAccounts` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.PolicyRule.APIGroups` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.PolicyRule.Resources` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.PolicyRule.Verbs` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ResourceAccessReviewResponse.GroupsSlice` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ResourceAccessReviewResponse.UsersSlice` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.Role.Rules` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.RoleBinding.Subjects` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.RouteStatus.Ingress` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ServiceAccountRestriction.Namespaces` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.ServiceAccountRestriction.ServiceAccounts` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.SubjectAccessReview.GroupsSlice` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.SubjectRulesReviewSpec.Groups` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.SubjectRulesReviewStatus.Rules` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.Template.Objects` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.TemplateInstanceStatus.Conditions` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.User.Groups` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.User.Identities` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.UserRestriction.Groups` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.UserRestriction.Users` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |
| `v1.UserRestriction.Selectors` | Yes | No | No | No |  | False positive; Enforced by generated internal→external conversion |

### PR DESCRIPTION
**Pull request by sttts**
Bump kubernetes to 1.6.0-beta3.

Fixes #13419 
xref #12458

- [ ] make sure storage.k8s.io objects remain encoded in etcd as v1beta1
- [x] HPA doesn't exist in extensions/v1beta1 any more. Make sure we don't break existing HPAs in etcd encoded as extensions/v1beta1

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
> Origin Action Required: Pull request cannot be automatically merged, please rebase your branch from latest HEAD and push again

@openshift-bot coming in with the sass

**Comment by mfojtik** [comment]
@mrunalp @runcom PTAL for reviewing the CRI-O kubelet parts

**Comment by mdshuai** [comment]
@mfojtik @mrunalp @runcom Will we official support CRI-O in 3.6? This need QE to test?

**Comment by sttts** [comment]
@mdshuai can you open an issue for that? Within this rebase PR we won't address new features.

**Comment by sttts** [comment]
Superseeded by https://github.com/openshift/origin/pull/13653

**Pull request closed without merging**
