### PR TITLE
Remove oauth-server dockerfile

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @deads2k @sttts 

/hold
for art changes and to sync on promotion change in https://github.com/openshift/release/pull/4404

### CODE REVIEW

**Comment by deads2k** [comment]
we can't do this until test-cmd is moved and integration is dead.

**Comment by tnozicka** [comment]
was this fixed in another PR as I see `ci/prow/cmd — Job succeeded.`

**Comment by deads2k** [comment]
thsi file is already gone

**Pull request closed without merging**
