### PR TITLE
WIP: adm-release-new: add --allow-non-digest-images

### PR DESCRIPTION
**Pull request by sttts**
For development purposes, referencing :latest images is super helpful. There should be a way to do this.

### CODE REVIEW

**Comment by smarterclayton** [comment]
I think we need to have a quick design discussion on this.  I agree it's valuable, but it prevents mirroring from working the way it is intended to.  You should probably use `oc adm release new ... --from-image=X --mirror=X` instead.

**Comment by smarterclayton** [comment]
Actually, `oc adm release new ...` as I suggested above is the intended way for you to do this for development purposes.  Mirroring a release does not allow mutating the release.

**Comment by sttts** [comment]
> Actually, oc adm release new ... as I suggested above is the intended way for you to do this for development purposes. Mirroring a release does not allow mutating the release.

@smarterclayton this is actually what I am trying to get working, i.e. `adm release new`:

```
oc adm release new \
  --from-release='registry.svc.ci.openshift.org/openshift/origin-release:v4.0' \
  --loglevel 7 --allow-missing-images --allow-non-digest-images \
  --to-image=docker.io/sttts/origin-release:latest \
  openshift-cluster-kube-apiserver-operator=docker.io/sttts/origin-cluster-kube-apiserver-operator:latest \
```

But the restriction to digest image reference makes this impossible.

I did not add a flag to the mirror command here intentionally. Only the logic is shared.

**Comment by sttts** [comment]
> EDIT: Hrm, although you shouldn't be erring out here (it was not intended to error out). Let me look further.

@smarterclayton do you mean a warning in the  `adm release new` case was intended? That would work for me of course.

**Comment by tnozicka** [comment]
If that error meant to be a warning, we save a CLI flag :)

**Comment by smarterclayton** [comment]
This is on my list to come back to - if we allow it I need to add something to taint the release to indicate we can’t mirror it or promote it to customers

**Comment by sttts** [comment]
@smarterclayton any progress here?

**Pull request closed without merging**
