### PR TITLE
apply upstream 9870

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/openshift/origin/issues/4171

### CODE REVIEW

**Comment by deads2k** [comment]
@markturansky I've reverted the old, applied the new patches, fixed two UPSTREAM patches that conflict with this change that we need, but I need help here: https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master.go#L72 .  The old `RecyclableVolumeConfig` is gone and the replacement is very different.  

Please open a pull against this branch containing the updated code and I'll merge it in.

**Comment by markturansky** [comment]
@deads2k thanks for merging those two commits of mine and I will submit a PR to your branch, as requested.

**Comment by deads2k** [comment]
@markturansky I suspect you reviewed some since you built the patch.  Can you review?

@liggitt care to take a look?

[test]

**Comment by markturansky** [comment]
LGTM

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
@markturansky those errors look real.  Any ideas?

**Comment by deads2k** [comment]
in case of flake re[merge]

**Comment by deads2k** [comment]
build problem which may have been fixed.  re[merge]

**Pull request merged**
