### PR TITLE
add DB icons and also add annotations to the 'latest' imagestream tags

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/5883

@jwforres ptal.

note that all the "latest" ISTs show up now....

### CODE REVIEW

**Comment by bparees** [comment]
screenshot at 2016-02-17 16 23 12

**Comment by bparees** [comment]
screenshot at 2016-02-17 16 24 14

**Comment by bparees** [comment]
@jwforres ok i took away the version info for all the "latest" ISTs.

I also added the new wildfly versions (9 and 10).

**Comment by bparees** [comment]
[test]

**Comment by jwforres** [comment]
LGTM @sdodson  fyi some default image stream updates

**Comment by sdodson** [comment]
> LGTM @sdodson fyi some default image stream updates

Are these changes compatible with v1.1 or only the latest?

**Comment by bparees** [comment]
@sdodson these changes should be, they are all minor changes.  but i don't remember if there is a larger delta between the current state of these imagestream definitions and what we shipped in 1.1.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
