### PR TITLE
Bug 1826499: IngressClass error test is flaky

### PR DESCRIPTION
**Pull request by smarterclayton**
The test races with the admission cache and is failing 5-7% of the
time in e2e runs.

### CODE REVIEW

**Comment by ironcladlou** [comment]
I actually suspect the admission controller itself is racy — if so, this change might be hiding the root problem, but I could be wrong

**Comment by smarterclayton** [comment]
Admission is completely racy.  An admission controller is an observer of cluster state and is independent across all three masters.  You may not assume admission happens across all masters at some point in time.

**Comment by ironcladlou** [comment]
What I mean is, in this specific case, my theory is a stale cache means the admission plugin erroneously admits the Ingress (i.e. were the cache to be fresh, the plugin would have rejected), and the system takes no corrective action to retroactively reject or repair the erroneously admitted Ingress.

**Comment by smarterclayton** [comment]
That is how admission works.  The same applies the other way - that's also how other admission controls work that check RBAC.

**Comment by ironcladlou** [comment]
>That is how admission works. The same applies the other way - that's also how other admission controls work that check RBAC.

Hrm — what exactly does admission set out to guarantee, then?

**Comment by ironcladlou** [comment]
The Ingress admission code seems to be declaring some invariant ("there shall exist only one 'default' IngressClass") but it's not clear to me that's actually enforced. Is that actually an invariant that needs enforcing? If so, how?

**Comment by smarterclayton** [comment]
If you create two, then some O(seconds) later you can't create new ingress.

**Comment by smarterclayton** [comment]
Admission in the presence of config or input changes has always behaved like this

**Comment by ironcladlou** [comment]
I believe you — it's just not something I'm deeply familiar with. Thanks for the info!

**Pull request merged**
