### PR TITLE
increase binary build timeout to 5 minutes

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/7489

### CODE REVIEW

**Comment by bparees** [comment]
ideally we'd make this an argument to start-build, but it's going to be hard to add that argument such that it only applies to binary builds and not all builds run from start-build, so going w/ the easy fix for now.
[merge]

**Comment by smarterclayton** [comment]
This can block a request in the server queue for a very long time.

**Comment by liggitt** [comment]
the API call actually hangs for the duration?

**Comment by bparees** [comment]
@smarterclayton elaborate?

and if true, how was 1 minute acceptable?

**Comment by bparees** [comment]
@liggitt i think the connection stays open because it can't stream the files from the client to the pod until the pod is running (the api doesn't "buffer" the files from the client, it streams them directly to the pod once it's up. i think.)

but as long as it doesn't block other requests, i don't see the problem.  streaming a 10gig file could also block a request in the queue for a long time.

**Comment by liggitt** [comment]
The number of "short" requests is limited. This API url probably isn't considered a long-running request, so if you had enough things holding on it, they could start blocking requests. Agree that 5 minutes isn't essentially different than 1 minute

**Comment by smarterclayton** [comment]
We need a better story for limiting requests to fix the problem that this
change only makes slightly worse.

**Pull request merged**
