### PR TITLE
Nuke yaml from all objects

### PR DESCRIPTION
**Pull request by mfojtik**
Yaml is nuked in upstream, so remove it from our objects as well to make things look consistent:

https://github.com/openshift/origin/pull/679/files#r23234265

@smarterclayton fyi

### CODE REVIEW

**Comment by bparees** [comment]
lgtm. i hope this was a sed script.

**Comment by mfojtik** [comment]
@bparees this time yes, this was a sed :-)

**Comment by mfojtik** [comment]
[test]

**Comment by soltysh** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Comment by smarterclayton** [comment]
A week from now you'll need to do another sweep because new stuff will still merge in.

**Pull request merged**
