### PR TITLE
don't expose oapi types as 'all'

### PR DESCRIPTION
**Pull request by deads2k**
/assign @juanvallejo 

golang didn't let this come out as clean as I may have hoped.

### CODE REVIEW

**Comment by juanvallejo** [comment]
Can confirm that this fixes 
https://bugzilla.redhat.com/show_bug.cgi?id=1523493

**Comment by juanvallejo** [comment]
Fixes https://github.com/openshift/origin/issues/17446

**Comment by deads2k** [comment]
> /refresh

@kargakis what is a "refresh"

**Comment by kargakis** [comment]
@deads2k refreshes github statuses but seems that the problem is different (Jenkins times out any connection and prow does not proceed with updating Github since these jobs wait to be started or have their status updated based on Jenkins).

**Pull request merged**
