### PR TITLE
fix if block ends with a return statement, so drop this else

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by enj** [comment]
I will defer this to @stevekuznetsov since he wrote the original.  There seems to be a lot of other code like this in the `ldap` stuff so I am not sure that it makes sense to change it.

**Comment by stevekuznetsov** [comment]
This is technically the more common and accepted Go idiom, but I don't have the bandwidth to get these PRs through.

**Comment by php-coder** [comment]
@enj @stevekuznetsov What is the resolution then? Merge or close?

**Comment by enj** [comment]
@php-coder no time to review this.  The whole file has this problem throughout.  Large changes like that will probably require additional tests to prevent regressions.

**Comment by enj** [comment]
Closing since the style issue occurs throughout this file.

**Pull request closed without merging**
