### PR TITLE
remove template.openshift.io/namespace parameter from template servicebroker and use context object instead

### PR DESCRIPTION
**Pull request by jim-minter**
also remove AcceptsIncomplete from ProvisionRequest struct after correction at
https://github.com/openservicebrokerapi/servicebroker/commit/e6d9b144b49ffb15be8599fcd942f01287c628fe

### CODE REVIEW

**Comment by jim-minter** [comment]
@jwforres fyi

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
also test failure is flake https://github.com/openshift/origin/issues/14597

**Pull request merged**
