### PR TITLE
Fix ext test namespace stuff

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/19513

Pulls in https://github.com/openshift/origin/pull/19110 commit so that ext image_ecosystem passes

@openshift/sig-developer-experience ptal

@cuppett fyi

### CODE REVIEW

**Comment by bparees** [comment]
looks like a net win to me.

/lgtm

**Comment by gabemontero** [comment]
The image eco test is still running but all the jenkins_plugin.go tests have passed

**Comment by gabemontero** [comment]
And so have all the s2i_php.go tests

**Comment by bparees** [comment]
yeah it's being *very* slow, not sure why.

**Comment by gabemontero** [comment]
Failures in three test files unrelated to the ones we touched:

```
Summarizing 3 Failures:

[Fail] [image_ecosystem][mysql][Slow] openshift mysql replication  [It] MySQL replication template for 5.7: https://raw.githubusercontent.com/sclorg/mysql-container/master/examples/replica/mysql_replica.json [Suite:openshift] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:104

[Fail] [Conformance][image_ecosystem][mongodb][Slow] openshift mongodb replication (with statefulset)  [It] should instantiate the template [Suite:openshift] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mongodb_replica_statefulset.go:81

[Fail] [image_ecosystem][Slow] openshift sample application repositories [image_ecosystem][php] test php images with cakephp-ex repo  Building cakephp app from new-app [It] should build a cakephp image and run it in a pod [Suite:openshift] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:78

```

**Comment by bparees** [comment]
looks to me like @coreydaley's NFS patching logic has broken:

```
Apr 27 16:10:58.758: INFO: Running 'oc patch --config=/tmp/e2e-test-mongodb-petset-replica-5vv9p-user.kubeconfig --namespace=e2e-test-mongodb-petset-replica-5vv9p template/mongodb-petset-replication --type json -p [{"op": "test", "path": "/objects/2/kind", "value":"PersistentVolumeClaim"},{"op": "add", "path":"/objects/2/spec/selector", "value": {"matchLabels":{"namespace":"e2e-test-mongodb-petset-replica-5vv9p"}}}]'
Apr 27 16:10:59.018: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc patch --config=/tmp/e2e-test-mongodb-petset-replica-5vv9p-user.kubeconfig --namespace=e2e-test-mongodb-petset-replica-5vv9p template/mongodb-petset-replication --type json -p [{"op": "test", "path": "/objects/2/kind", "value":"PersistentVolumeClaim"},{"op": "add", "path":"/objects/2/spec/selector", "value": {"matchLabels":{"namespace":"e2e-test-mongodb-petset-replica-5vv9p"}}}]] []   Error from server: Testing value /objects/2/kind failed
 Error from server: Testing value /objects/2/kind failed
 [] <nil> 0xc421712030 exit status 1 <nil> <nil> true [0xc42088b7d8 0xc42088b800 0xc42088b800] [0xc42088b7d8 0xc42088b800] [0xc42088b7e0 0xc42088b7f8] [0x9439b0 0x943ab0] 0xc421151320 <nil>}:
Error from server: Testing value /objects/2/kind failed
```

**Comment by gabemontero** [comment]
The sample_app failure failed at the `verifying string from app request` step ... seems similar to the change done for s2i_php ... or the count was not maintained ... the string is `"<span class=\"code\" id=\"count-value\">1</span>"`

**Comment by gabemontero** [comment]
revert my last comment ... instead:

```
• Failure [742.428 seconds]
[image_ecosystem][Slow] openshift sample application repositories
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:124
  [image_ecosystem][php] test php images with cakephp-ex repo
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:225
    
    /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:38
      Building cakephp app from new-app
      /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:56
        should build a cakephp image and run it in a pod [Suite:openshift] [It]
        /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:57

        Expected error:
            <*errors.errorString | 0xc420f312e0>: {s: "not progressing"}
            not progressing
        not to have occurred

        /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:78
```

@bparees says QE reported this recently as well ... seems intermittent

**Pull request merged**
