### PR TITLE
Nuke sdn

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @deads2k @sttts 

/hold
for tests and sync with image promotion in

### CODE REVIEW

**Comment by danwinship** [comment]
test-cmd:

    test/cmd/help.sh:34: executing 'openshift-sdn --help' expecting success and text 'Start OpenShift SDN node components'
    /go/src/github.com/openshift/origin/hack/lib/cmd.sh: line 337: openshift-sdn: command not found

That can just go away too though

**Comment by danwinship** [comment]
@tnozicka 

    diff --git a/test/cmd/help.sh b/test/cmd/help.sh
    index 49ac7ea8b9..23b5379eff 100755
    --- a/test/cmd/help.sh
    +++ b/test/cmd/help.sh
    @@ -34 +33,0 @@
    -os::cmd::expect_success_and_text 'openshift-sdn --help' 'Start OpenShift SDN node components'

**Comment by deads2k** [comment]
already gone

**Pull request closed without merging**
