### PR TITLE
UPSTREAM: 35206 update default run func for cmds containing sub-commands

### PR DESCRIPTION
**Pull request by juanvallejo**
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/35206

Fixes https://github.com/openshift/origin/issues/11043#event-822655239

This patch updates parent commands of sub-commands to exit with a usage
error and exit code 1 on an invalid (non-sub-command) argument.

**Example**

```
$ oc rollout
... [help output] ...

$ echo $?
0

$ oc rollout invalidsubcommand
error: unknown command "lol"
See 'oc rollout -h' for help and examples.

$ echo $?
1
```

cc @openshift/cli-review @kargakis @tnozicka

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by stevekuznetsov** [comment]
Isn't usage error usually `2`? Does `cobra` have return value constants somewhere?

**Comment by juanvallejo** [comment]
@stevekuznetsov 
> Isn't usage error usually 2?

From a few cases I've seen, UsageErrors have been returning `1` (e.g. https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/projects.go#L69)
```
$ oc projects extraneous_argument
error: no arguments should be passed
See 'oc projects -h' for help and examples.

$ echo $?
1
```

> Does cobra have return value constants somewhere?
[These](https://godoc.org/github.com/spf13/cobra#pkg-constants) are the only constants I've found in Cobra

**Comment by juanvallejo** [comment]
conformance flaked on https://github.com/openshift/origin/issues/11114 re[test]

**Comment by kargakis** [comment]
No need for the upstream commits to be separate. Have you opened a PR in Kube already?

**Comment by juanvallejo** [comment]
@kargakis 
> No need for the upstream commits to be separate. Have you opened a PR in Kube already?

Done! https://github.com/kubernetes/kubernetes/pull/35206

**Comment by juanvallejo** [comment]
networking test flaked on https://github.com/openshift/origin/issues/11567 re[test]

**Comment by kargakis** [comment]
Can you update the commit name of the UPSTREAM commit with the real PR #

**Comment by juanvallejo** [comment]
@kargakis 
> Can you update the commit name of the UPSTREAM commit with the real PR #

Done!

**Comment by fabianofranz** [comment]
[merge]

**Pull request merged**
