### PR TITLE
test-cmd: mktemp --suffix is not supported in Mac

### PR DESCRIPTION
**Pull request by kargakis**
@smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Also custom-docker-builder/build.sh and verify-jsonformat.sh

**Comment by smarterclayton** [comment]
LGTM [merge] although if you could fix the others in another PR I'd appreciate it

**Comment by kargakis** [comment]
updated those scripts too

[merge]

**Comment by kargakis** [comment]
TestCheckRemoteGit flake

[merge]

**Pull request merged**
