### PR TITLE
Remove generated_certs.d dir from vendored docker in cluster-capacity and service-catalog as it breaks checkout on Windows

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes https://github.com/openshift/origin/issues/14664

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@derekwaynecarr @jpeeler

**Comment by derekwaynecarr** [comment]
lgtm

[merge][severity:blocker]

**Comment by louyihua** [comment]
This PR solved my problem!

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
