### PR TITLE
Move NoNamespaceKeyFunc into origin

### LINKED ISSUE #3575: [post-rebase-work] upstream pull rejected
https://github.com/openshift/origin/commit/272fe767c184ac6e13bb726017a40e6bb60c3738 (UPSTREAM: Ensure no namespace on create/update root scope types) was rejected.

Refactor this to an origin utility so we can stop carrying the patch.

@liggitt yours

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #3575

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by deads2k** [comment]
Can you give a partial commit id for what this is reverting?  I know, but the next rebaser might not.

**Comment by deads2k** [comment]
Why not move the whole function to a new location?  I like it's additional protections.

**Comment by liggitt** [comment]
updated

**Comment by deads2k** [comment]
lgtm [merge]

**Pull request merged**
