### PR TITLE
[release-4.6] Bug 1977093: Add consolequickstarts and consoleplugins extensions to the authenticated rules

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @bparees

### CODE REVIEW

**Comment by jhadvig** [comment]
@bparees @spadgett is there a way how we could override the labels here, since for all the later versions we dont need this change, just for 4.6.

**Comment by bparees** [comment]
yeah i'll override

/lgtm

**Comment by bparees** [comment]
will still need to wait for cherry pick approval but hopefully that happens today (i'm not patch manager this week)

**Pull request merged**
