### PR TITLE
Automated cherry pick of #13563

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #13563 on release-1.5.

#13563: Update namespace finalizer to delete RoleBindingRestrictions

### CODE REVIEW

**Comment by enj** [comment]
@deads2k backport for 1.5, please merge.

**Comment by deads2k** [comment]
[merge]

**Comment by enj** [comment]
@stevekuznetsov Who can give this a green button merge?

https://github.com/openshift/ose/pull/673 is merged.

**Comment by stevekuznetsov** [comment]
Looks like @deads2k should own it but he's out so maybe @liggitt

**Comment by liggitt** [comment]
LGTM [merge]

**Comment by stevekuznetsov** [comment]
We would need:

c3b5b6af8cdbfb06b590d631d7e8465a7d7a737c
7509bc1aedbf724a90d1ba415b582a05fd53a59a
fdd525a871b79faac79645d8f93a7cdc8a0bd269
b95268c2cad60631429804413faa375b84dcd6f4

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/origin/pull/13610 provides them

**Comment by stevekuznetsov** [comment]
@liggitt removed merge... was just going to fail. should apply after the backports land

**Comment by enj** [comment]
@liggitt ready for merge now.

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
