### PR TITLE
refactored test to use upstream method

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@liggitt PTAL

### CODE REVIEW

**Comment by liggitt** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@liggitt  Looks like a weird Jenkins failure?

**Comment by liggitt** [comment]
```
fatal: Unable to create '/data/src/github.com/openshift/origin-bare/refs/heads/master.lock': File exists.
```

**Comment by deads2k** [comment]
Still lgtm.  @stevekuznetsov don't push after the merge tag or your pull will be rejected.

[merge]

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@liggitt Could you please bump this

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
