### PR TITLE
Update bash autocomplete, add verify check

### LINKED ISSUE #3376: Fix filename autocomplete for `oc secrets new`
Add bash autocompletion:
```
$ source rel-eng/completions/bash/oc
```

Try to use `<tab>` autocompletion for filenames:
```
$ touch myfile.txt
$ oc secrets new my-secret myfile<tab><tab>
```

### PR DESCRIPTION
**Pull request by liggitt**
Adds annotations to args that reference filenames to fix bash autocompletion
Adds verification script to ensure autocompletions stay up to date

Fixes #3376 for `oc secrets new` specifically

### CODE REVIEW

**Comment by liggitt** [comment]
@fabianofranz PTAL... pulls in fixes from @eparis for pflag and cobra, adds indicators of which params should autocomplete as filenames

**Comment by liggitt** [comment]
[test]

**Comment by fabianofranz** [comment]
I'm wondering if we could, instead of doing `MarkFlagFilename`, have a flag type that represents a filepath. Feels like the right structure for it, instead of making it a string then marking it as something more specific. Something like `flags.FilepathVarP`, would avoid the need to explicitly mark a string as a file and could do things like check for well-formedness, existence, etc beforehand. Doable, maybe a TODO for future?

**Comment by liggitt** [comment]
I thought about that, but lots of things have different validations around file paths...
* must exist / must not exist
* must be absolute / must be relative
* must be a file / must be a directory
* may not contain spaces / doesn't matter

This doesn't actually add any validation... I sort of didn't to imply that you would get validation for free...

**Comment by fabianofranz** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
