### PR TITLE
Bug 1842629: [release-4.4] openshift-tests: add run-resourcewatch command

### PR DESCRIPTION
**Pull request by damemi**
Backports the changes from https://github.com/openshift/origin/pull/24845 to add the `openshift-tests run-resourcewatch` command, to make this command available for upgrade e2es

### CODE REVIEW

**Comment by deads2k** [comment]
@damemi try to get green please

**Comment by damemi** [comment]
@deads2k this is finally ready to go, dependent 4.5 bug closed. If you can approve then we'll just need patch manager

**Pull request merged**
