### PR TITLE
unit-tests: fixed flake and race in image pruning 

### PR DESCRIPTION
**Pull request by miminar**
Resolves: https://github.com/openshift/origin/pull/16821#issuecomment-340758624

### CODE REVIEW

**Comment by miminar** [comment]
Resolves https://github.com/openshift/origin/pull/16821#issuecomment-340758624

/assign @bparees

**Comment by eparis** [comment]
This flake has been so bad getting things into the queue (>50% failure rate) that I'm going to break all the rules and merge by hand (it is green)

**Pull request merged**
