### PR TITLE
dockerless build controller updates

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@nalind fyi

**Comment by bparees** [comment]
@nalind ok this is passing the current (docker based) tests, ptal.  The intent here is to provide controller logic that can work with both the existing docker-based builder image and the coming dockerless builder image, so after this merges, and then after we land the dockerless builder image, we'll come back and pare down what is in here to just what is necessary for dockerless.

**Comment by nalind** [comment]
I'd consider checking for `/etc/containers/certs.d` and `/etc/docker/certs.d` volumes separately in `setupContainersCertificates()`, but either way this LGTM for accomplishing what's intended at this step.

**Comment by bparees** [comment]
> I'd consider checking for /etc/containers/certs.d and /etc/docker/certs.d volumes separately in setupContainersCertificates(), but either way this LGTM for accomplishing what's intended at this step.

updated, thanks.

**Pull request merged**
