### PR TITLE
[release-3.7] host diagnostics: update master unit names

### PR DESCRIPTION
**Pull request by sosiouxme**
backport #18542 for https://bugzilla.redhat.com/show_bug.cgi?id=1378883

### CODE REVIEW

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18556/test_pull_request_origin_extended_conformance_gce/15992/ and https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18556/test_pull_request_origin_extended_conformance_install/7220/ are both flake https://github.com/openshift/origin/issues/18569

/retest

**Comment by tnozicka** [comment]
3.7 console flake tracker: https://github.com/openshift/origin/issues/18573

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18556/test_pull_request_origin_extended_conformance_gce/16210/ has new flake https://github.com/openshift/origin/issues/18615 and https://github.com/openshift/origin/issues/18616
/retest

**Comment by sosiouxme** [comment]
@mfojtik can you lgtm?

**Comment by spadgett** [comment]
/unassign

@sosiouxme sorry, i'm not the best person to review :/
@mfojtik ptal

**Comment by sosiouxme** [comment]
no real point in backporting for origin

**Pull request closed without merging**
