### PR TITLE
Add "OAuth" prefix to oauth API types

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton behold, an immense pull request accomplishing nothing

**Comment by liggitt** [comment]
[test]

**Comment by smarterclayton** [comment]
Naming is hard

**Comment by liggitt** [comment]
tests pass, @smarterclayton review and merge at will

**Comment by smarterclayton** [comment]
LGTM [merge]

**Pull request merged**
