### PR TITLE
Prevent accidental binary size regressions

### PR DESCRIPTION
**Pull request by smarterclayton**
Simple build level check.

@liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
> @smarterclayton the released bits have already crossed this limit

the 3.9 bits are unintentionally large. work was done in the 3.10 timeframe to reign back in those sizes. this prevents regression to 3.9 levels

**Comment by mkumatag** [comment]
> the 3.9 bits are unintentionally large. work was done in the 3.10 timeframe to reign back in those sizes. this prevents regression to 3.9 levels

but somebody already reported issue for latest code - https://github.com/openshift/origin/issues/19635

**Pull request merged**
