### PR TITLE
Convert some documentation from Markdown to AsciiDoc

### PR DESCRIPTION
**Pull request by jawnsy**
Closes: #7648

### CODE REVIEW

**Comment by jawnsy** [comment]
`pandoc` did most of the heavy lifting, though I did manually go through each of these files to make sure that they displayed correctly, and also fixed any minor formatting errors.

This pull request is ready for review. @danmcp

**Comment by danmcp** [comment]
@openshift/team-origin-committers Thoughts?

**Comment by smarterclayton** [comment]
This will break links in other places.  So it's a non-backwards compatible change to our docs.  I'm fine with anything not commonly used, but I don't see much benefit for README or HACKING.

**Comment by bparees** [comment]
[shrug]

I second @smarterclayton's concerns about breaking links.  I think we even link to github from some of our official docs, so they should be scanned for references before this is merged.  (And if we're only changing some files but not others to retain referential compatibility, I would vote against it.  consistency/standardization between files is more useful than any benefits I see us gaining from this).

For anyone else reviewing this who's curious about the implications/benefits of changing to adoc, i found this summary useful:
https://github.com/awestruct/web-editor/issues/12#issuecomment-19943154

**Comment by jawnsy** [comment]
Thanks for the review, @bparees & @smarterclayton

I'll undo the changes for README and HACKING.

To @bparees' point, there's already no consistency between the docs (we use Markdown in some spots and AsciiDoc in others. For example, docs/atomic-quick-start-tutorial.adoc.)

I will check for references from our public docs back to GitHub, though I would humbly suggest that that's a bad idea - it means the docs are not self-contained (important for enterprise users with restrictive firewalls, that may not be able to access the Internet), and also that the version of the published docs may not match the version of the document on GitHub (which would likely be the latest commit, whereas the company may be using a previous version of OSE for example)

**Comment by liggitt** [comment]
All references should be relative, which lets them work within a branch or within a local clone

**Comment by jawnsy** [comment]
@liggitt Agreed! Some references were previously hard-coded to the https://github.com/openshift/origin repo, I've fixed some of those to make them relative links so that they work correctly in forks. I'm not sure if this is possible/simple to do with Markdown syntax, but it is possible with AsciiDoc.

I was referring to references from the pages on our public doc site (which is what I thought @bparees  was saying as well), for example from a page like https://docs.openshift.org/latest/install_config/upgrading/pacemaker_to_native_ha.html back to the GitHub. I think that linking this way is a bad idea, because now the published docs may be out of sync (generated from an older version of the code) than the latest version in GitHub (unless of course we're linking to specific commits, but that sounds awful.)

**Comment by bparees** [comment]
> I will check for references from our public docs back to GitHub, though I would humbly suggest that that's a bad idea - it means the docs are not self-contained (important for enterprise users with restrictive firewalls, that may not be able to access the Internet), 

Assuming it's being done at all (and i'm not 100% certain it is, i just have a vague sense there are a few cases), it's because there are tutorials/examples we carry in the origin repo that are useful references that we do not want to also carry in the official docs and keep in sync there.  eg: https://github.com/openshift/origin/tree/master/examples/jenkins, which I see you have not converted, so perhaps it is moot.  I'm aware of the versioning and accessibility issues of such external links, but in some cases it's an acceptable trade off.

**Comment by deads2k** [comment]
Unless there's some really useful power gained in asciidoc or we've actually had community complaints about mardown, I'm against.  I write proposals and documentation in both origin and kube and upstream kube is all markdown.  I don't see why I'd go the effort of using different formats.

**Comment by smarterclayton** [comment]
Good point about proposals, those need to stay markdown because they
often go upstream.

**Comment by jawnsy** [comment]
Okay, sounds like everyone is against this change, so I'll go ahead and just close this issue & PR.

**Pull request closed without merging**
