### PR TITLE
update kindToResource to match upstream

### PR DESCRIPTION
**Pull request by pweil-**
update kindToResource impl to match upstream

@liggitt - PTAL - figured I'd try my hand at it since I haven't touched any js in a while  

fixes https://github.com/openshift/origin/issues/6851

cc @jwforres

### CODE REVIEW

**Comment by pweil-** [comment]
[test]

**Comment by liggitt** [comment]
LGTM [merge]

**Comment by pweil-** [comment]
re[test]

**Comment by pweil-** [comment]
healthz and timeout flakes: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/539/

re[test]

**Comment by pweil-** [comment]
timed out again https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9700/consoleFull

```
panic: test timed out after 1m0s

goroutine 361 [running]:
testing.func·008()
	/usr/lib/golang/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:129 +0x4b
```

**Comment by pweil-** [comment]
re[test]

**Comment by pweil-** [comment]
finally

[merge]

**Pull request merged**
