### PR TITLE
Include name of port in pod template, switch to port/protocol format

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
Should it be 5432/TCP -> web instead of 5432 -> web/TCP ?

**Comment by jwforres** [comment]
@spadgett updated

**Comment by spadgett** [comment]
LGTM, we might open a follow on issue to change this in the object describers, too.

**Comment by jwforres** [comment]
Going to [merge] this part

I'll leave the issue open and fix the object describers tomorrow

**Pull request merged**
