### PR TITLE
Fix test fixture fields

### PR DESCRIPTION
**Pull request by kargakis**
@jhadvig @csrwng

### CODE REVIEW

**Comment by jhadvig** [comment]
:+1: LGTM

**Comment by kargakis** [comment]
[merge]

**Comment by csrwng** [comment]
:+1:  thank you

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6635 flake

[merge]

**Comment by kargakis** [comment]
> #6635 flake

again

[merge]

**Comment by kargakis** [comment]
imagestreamtag flake

[merge]

**Comment by liggitt** [comment]
[merge]

**Pull request merged**
