### PR TITLE
Remove generated internal informers

### PR DESCRIPTION
**Pull request by juanvallejo**
cc @deads2k @soltysh 

Removes generated internal informers and listers for packages that have already been updated to use external informers and listers.

### CODE REVIEW

**Comment by juanvallejo** [comment]
TODO: remove internal core informers in remaining files in separate PR:

- pkg/dns/serviceaccessor.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/images.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/project.go
- pkg/quota/controller/clusterquotamapping/clusterquotamapping.go

**Comment by deads2k** [comment]
Squash and lgtm

**Comment by juanvallejo** [comment]
@deads2k thanks, squashed

**Pull request merged**
