### PR TITLE
bump(openshift/source-to-image) 2e52377338d425a290e74192ba8d53bb22965b0d

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik @jhadvig ptal.

pre-req to finishing out the broken incremental builds issue.

**Comment by bparees** [comment]
[test]

**Comment by mfojtik** [comment]
```
_output/local/go/src/github.com/openshift/origin/pkg/build/builder/sti.go:99: cannot use r (type *os.File) as type *"github.com/fsouza/go-dockerclient".AuthConfigurations in argument to "github.com/openshift/source-to-image/pkg/docker".G
```

**Comment by bparees** [comment]
i will pull this into my main incremental PR as a second commit and fix there.

**Pull request closed without merging**
