### PR TITLE
Bug 1762040: Fix cosmetic template error

### PR DESCRIPTION
**Pull request by ironcladlou**
Backport of https://github.com/openshift/router/pull/20/commits/e9961a1eb712f79fbfe9c9b3d2902d833d784ea5

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @Miciah

**Comment by ironcladlou** [comment]
cc @knobunc

**Comment by Miciah** [comment]
/hold
CI is getting stuck here:
````
Nov 08 12:31:37 ip-172-18-7-51.ec2.internal origin-node[41800]: W1108 12:31:37.293705   41800 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 08 12:31:37 ip-172-18-7-51.ec2.internal origin-node[41800]: I1108 12:31:37.293836   41800 kubelet.go:2098] Container runtime status: Runtime Conditions: RuntimeReady=true reason: message:, NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 08 12:31:37 ip-172-18-7-51.ec2.internal origin-node[41800]: E1108 12:31:37.293856   41800 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24087/test_pull_request_origin_extended_conformance_install-release-3.11/1247/artifacts/journals/origin-node.service

**Comment by Miciah** [comment]
Looks like registry issues—I see a lot of "image ... not found" errors from registry.access.redhat.com in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/24087/test_pull_request_origin_extended_conformance_install-release-3.11/1247/artifacts/journals/docker.service.

**Pull request merged**
