### PR TITLE
[release-3.11] Added more conditions to set a reasonable DNSIP

### PR DESCRIPTION
**Pull request by bysnupy**
Refer this `PR`: https://github.com/openshift/origin/pull/21737#issuecomment-456854707 

* Version: `v3.11`

* Descrtipion: 
   Added `b`, `c` conditions. Complete conditions are the following.
   Usually `nodeIP` and `nodeName` is not setting up in the `node-config.yaml` (it can be setting up as `node groups`) but if `nodeName` is specified, the lookup IP can be `dnsIP`.
   So this change replace  `the network interface first ip address` with ` IP from the network interface used as default gateway` as default `dnsIP` value.

  - If DNSIP is configured `0.0.0.0`
    1.  Use `NodeIP` as Default
    2.  If the user has specified an `NodeName`,
        lookup the `IP` from `nodeName` and use the first `IPv4` address.
    3. Try to get the `IP` from the network interface used as `default gateway`.
    4. If not setting `DNSIP` through above steps, use the network interface first `IP` address.

It can be helpful to issues which caused unexpected cluster dns `IP`.
For examples, this fix is helpful for the following issues to resolve:
 - [Cannot set '--cluster-dns' value by dnsIP](https://bugzilla.redhat.com/show_bug.cgi?id=1662253)
 - [Nameserver value in /etc/resolv.conf file inside pods are inconsistent](https://github.com/openshift/origin/issues/21696)

### CODE REVIEW

**Comment by bysnupy** [comment]
Could you PTAL @danwinship if you're not busy ?

**Comment by lihongan** [comment]
@bysnupy Do you have a workaround for now? 
If yes, could you please help take a look at: https://bugzilla.redhat.com/show_bug.cgi?id=1680059

**Comment by bysnupy** [comment]
@lihongan I added a comment at above BZ.

From mobile

**Comment by pravisankar** [comment]
@bysnupy created https://github.com/openshift/origin/pull/22485 that will fix some of the issues in this pr, PTAL

**Comment by bysnupy** [comment]
Thank you for your working @pravisankar !
If the https://github.com/openshift/origin/pull/22485 is fixed, I’ll close this PR. :)

**Comment by bysnupy** [comment]
I close this `PR`, because this fix is included in https://github.com/openshift/origin/pull/22485 and https://github.com/openshift/origin/pull/22485 has merged.

**Pull request closed without merging**
