### PR TITLE
[3.9] revendor catalog 0.1.11

### PR DESCRIPTION
**Pull request by jboyd01**
revendor upstream Service Catalog v0.1.11
Change controller manager to listen securely over 6443
Controller Manager Service creates SSL cert & key
Added prometheus scrape over SSL for catalog controller

### CODE REVIEW

**Comment by jpeeler** [comment]
Service catalog test won't pass here due to oc cluster up syntax differing between master and 3.9 branch.

**Comment by jpeeler** [comment]
/retest
hack/verify-generated-bindata.sh might need investigating.

**Comment by jboyd01** [comment]
Getting two consistent failures:
verify is consistently bombing out on **verify-generated-bindata.sh**:
```FAILURE after 0.047s: hack/verify-generated-bindata.sh:17: executing 'diff -Naup /go/src/github.com/openshift/origin/pkg/oc/bootstrap/bindata.go _output/verify-bindata/pkg/oc/bootstrap/bindata.go' expecting success: the command returned the wrong error code
Standard output from the command:
--- /go/src/github.com/openshift/origin/pkg/oc/bootstrap/bindata.go	2018-03-29 00:33:19.000000000 +0000
+++ _output/verify-bindata/pkg/oc/bootstrap/bindata.go	2018-03-29 00:42:19.542465781 +0000
@@ -35,9 +35,7 @@
 // examples/logging/logging-deployer.yaml
 // examples/heapster/heapster-standalone.yaml
 // examples/prometheus/prometheus.yaml
-// examples/prometheus/prometheus.yaml.~master~
 // examples/service-catalog/service-catalog.yaml
-// examples/service-catalog/service-catalog.yaml.~master~
 // install/origin-web-console/console-config.yaml
 // install/origin-web-console/console-template.yaml
 // install/service-catalog-broker-resources/template-service-broker-registration.yaml
@@ -14655,1236 +14653,7 @@ func examplesPrometheusPrometheusYaml()
 	return a, nil
 }
 ```
This looks like there are two extra files here:  examples/prometheus/prometheus.yaml.~master~  and examples/service-catalog/service-catalog.yaml.~master~

Looks like these are present on my dev system, and running hack/update-generated-bindata is actually processing them.   Will re-submit with corrected bindata.go files.

**Comment by eparis** [comment]
This 3.9 PR is being closed. Any PR intended to be included in a future openshift enterprise release should be opened in the openshift enterprise repository.

**Pull request closed without merging**
