### PR TITLE
use new crio socket path via constant

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mrunalp @runcom ptal.

**Comment by bparees** [comment]
@deads2k @derekwaynecarr fyi.

**Comment by runcom** [comment]
LGTM

**Comment by smarterclayton** [comment]
Please stop taking constant dependencies from controllers onto components that should not be required for controllers.

**Comment by bparees** [comment]
> Please stop taking constant dependencies from controllers onto components that should not be required for controllers.

The crio team changed the value of this path between releases and we weren't using the constant and broke.  Making us carry our own copy of the value is fragile.

**Comment by deads2k** [comment]
> The crio team changed the value of this path between releases and we weren't using the constant and broke. Making us carry our own copy of the value is fragile.

Doing this creates a diamond dependency problem between controllers and kubelet that ends up left as debt for someone doing a rebase to try to sort out.  Someone unfamiliar with the code then has to decide how to reconcile competing levels of a fast moving dependency.  If you were actually speaking to cadvisor or interacted with it, this diamond is worth resolving.  If you aren't, incurring that debt seems questionable.

Even with this dependency you introduced, changing a constant value will still produce problems at runtime since you're trying to match constant values across components which are allows (and expected) to skew.

**Comment by smarterclayton** [comment]
Remember, this constant is an API.  You can't change this across
deployments without a corresponding change on both sides (i.e. they have to
expose two sockets at old and new locations to allow the control plane to
migrate).  So this is their problem for now.

**Pull request merged**
