### PR TITLE
Bug 1829331: UPSTREAM: 90715: Ignore NotFound error when cleaning up Gluster tests

### PR DESCRIPTION
**Pull request by jsafrane**
https://bugzilla.redhat.com/show_bug.cgi?id=1829331
https://github.com/kubernetes/kubernetes/pull/90715

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for the upstream PR to get merged

**Comment by bertinatto** [comment]
/lgtm
/hold cancel

Upstream got merged.

**Pull request merged**
