### PR TITLE
UPSTREAM: 88141: Don't try to create VolumeSpec immediately after underlying PVC is being deleted

### PR DESCRIPTION
**Pull request by tedyu**

### CODE REVIEW

**Comment by rphillips** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/88141

**Comment by sjenning** [comment]
/approve
thanks :+1:

**Comment by rphillips** [comment]
/retitle Bug 1814291: UPSTREAM: 88141: Don't try to create VolumeSpec immediately after underlying PVC is being deleted

**Pull request merged**
