### PR TITLE
Move labeling functions to util package

### PR DESCRIPTION
**Pull request by kargakis**
Labeling is (going to be) needed not only in the template package but also elsewhere

@mfojtik ptal

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis did you forget to move the function itself? or I am reading this wrong?

**Comment by kargakis** [comment]
> @kargakis did you forget to move the function itself? or I am reading this wrong?

I moved the whole files (`labels.go` and `labels_test.go`) since most of the functions are helpers to the `AddObjectLabels`.

**Comment by mfojtik** [comment]
@kargakis so my gmail must be lying to me be aid I can't see the commit with function :)

**Comment by kargakis** [comment]
@mfojtik what i forgot to do is to rename the package names. Now it's done.

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
