### PR TITLE
remove dead code and move non-generic files to point of use

### PR DESCRIPTION
**Pull request by deads2k**
Builds on already lgtm'ed https://github.com/openshift/origin/pull/15696

This eliminates the non-generic in `pkg/controller` so we can re-use the package for code that is more likely to be generic.  I had a start on this in the rbac controllers and I want to preserve the `Run`, `addHandler`, and error handling boilerplate.

### CODE REVIEW

**Comment by deads2k** [comment]
aws provision problem
/retest

**Comment by deads2k** [comment]
@soltysh @mfojtik easy cleanup pr

**Comment by soltysh** [comment]
@deads2k any reason for leaving `pkg/controllers` behind?

**Comment by deads2k** [comment]
> @deads2k any reason for leaving pkg/controllers behind, if it doesn't have any contents?

I was going to place the generic controller bit from the rbac controllers in here and start refactoring other controllers.  However, our controllers still look weird.

**Comment by soltysh** [comment]
> our controllers still look weird.

Tell me about it ;)

**Pull request merged**
