### PR TITLE
start pkg/oc

### PR DESCRIPTION
**Pull request by deads2k**
This does a bulk move of low fanout packages to `pkg/oc` so that we can start snipping unnecessary links, clean-up owner/approver files, and start working our way towards a separate `oc`.

This has the biggest impact on @fabianofranz and @juanvallejo, but I think it is a net-win for them.

@bparees @csrwng I moved `pkg/bootstrap` under `pkg/oc` where it gets included, but I kept and tidied the existing owners file.  You won't get bombarded with reviews for general CLI changes.

@smarterclayton we've talked about this direction.  I see this as a first step towards separating `oc` with minimal disruption so far.

### CODE REVIEW

**Comment by bparees** [comment]
bootstrap move lgtm.

**Comment by deads2k** [comment]
TestTriggers_configChange: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4908

/retest

**Pull request merged**
