### PR TITLE
Enable extended validation check on all routes admitted in by the router.

### PR DESCRIPTION
**Pull request by ramr**
Enabled extended validation check on all routes admitted in by the router and update generated docs/manpage.

@liggitt  PTAL Thx

### CODE REVIEW

**Comment by ramr** [comment]
[test]

**Comment by liggitt** [comment]
Is status written back to the route if the cert is invalid? Did we consider adding this validation to the route API?

**Comment by ramr** [comment]
Yes, the status is written back on invalid config/rejections etc. The issue with adding to the route API is that we could potentially break existing routes in etcd. Since we wanted to backport this, wouldn't it be more prudent to do this on admission into the router.

**Comment by ramr** [comment]
@liggitt  do you have any other comments on this or is it good to merge? Thx

**Comment by liggitt** [comment]
this looks fine. ideally, we would eventually add validation in the API anyway, to prevent all routers from having to implement this themselves (and work through the churn of continually rejecting routes with invalid certs)

**Comment by knobunc** [comment]
[merge]

**Comment by knobunc** [comment]
Flake https://github.com/openshift/origin/issues/8571 [merge]

**Pull request merged**
