### PR TITLE
Rebase service catalog to v0.1.3

### PR DESCRIPTION
**Pull request by jpeeler**
This is a rebase to 0.1.3 plus a patch to make e2e test work. Mostly this rebase is to ensure that works correctly.

### CODE REVIEW

**Comment by jpeeler** [comment]
@smarterclayton any chance you can approve this?

**Comment by pmorie** [comment]
/approve cancel

I'm going to wait until after 3.8 branch is cut for this to go in.

**Comment by deads2k** [comment]
> /approve cancel
> 
> I'm going to wait until after 3.8 branch is cut for this to go in.

killing jobs to free the queue. Will rekick

**Comment by jpeeler** [comment]
/retest
the last two runs haven't been picked up...

**Comment by jpeeler** [comment]
/retest
(the previous 3 attempts did not actually run)

**Comment by pmorie** [comment]
/approve cancel

We'll get this in after 1.9 rebase goes in.

**Comment by jpeeler** [comment]
The pending rebase PR is https://github.com/openshift/origin/pull/17576

**Comment by jpeeler** [comment]
My understanding is that the jenkins job extended_conformance_install_update isn't supposed to be running anymore, so I'm closing this and opening a new PR.

**Comment by jpeeler** [comment]
Reopening a new PR didn't work as I expected, so I might as well keep this one open.

**Comment by jpeeler** [comment]
/retest
last try for a while from me

**Comment by stevekuznetsov** [comment]
Going to label this to merge on green tests.

**Comment by jpeeler** [comment]
Was told earlier today that a new AMI image could potentially solve the flake issue I'm seeing here, so here goes one more time.

/test extended_conformance_install flake #17605

**Comment by jpeeler** [comment]
Saw some yum errors, trying again...
/test extended_conformance_install

**Comment by stevekuznetsov** [comment]
Merging after a conversation with @jpeeler and @pmorie

**Pull request merged**
