### PR TITLE
SPLAT-1439: Ignore edge workers when listing nodes

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Review by mtulio — COMMENTED** [review]
I'd suggest remove from the list as it seems valid for run on edge workloads:
- test/extended/kernel/common.go
- test/extended/machines/workers.go
- test/extended/olm/olm.go
- test/extended/security/labels.go
- test/extended/security/fips.go

Other than that it seems to be fine, WDYT?

**Comment by jcpowermac** [comment]
> I'd suggest remove from the list as it seems valid for run on edge workloads:
> 
>     * test/extended/kernel/common.go
> 
>     * test/extended/machines/workers.go
> 
>     * test/extended/olm/olm.go
> 
>     * test/extended/security/labels.go
> 
>     * test/extended/security/fips.go
> 
> 
> Other than that it seems to be fine, WDYT?

sgtm, updated

**Comment by mtulio** [comment]
Both e2e for AWS and edge zones are passing as expected.
/lgtm

**Pull request merged**
