### PR TITLE
Add Ceph RBD and Gluster provisioners

### PR DESCRIPTION
**Pull request by jsafrane**
There are several UPSTREAM and downstream patches in this PR, all of them adding necessary functionality to fix Gluster provisioner not to leak passwords and add Ceph RBD provisioner.

It would be tedious to merge the individual patches one by one and they depend on each other.

### CODE REVIEW

**Comment by jsafrane** [comment]
[test]

**Comment by jsafrane** [comment]
@rootfs @childsb @gnufied

**Comment by rootfs** [comment]
LGTM

**Comment by jsafrane** [comment]
[test]

**Comment by jsafrane** [comment]
tests flaked with #11452: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/353/console

**Comment by jsafrane** [comment]
[test]

**Comment by rootfs** [comment]
all green @childsb

**Comment by eparis** [comment]
[merge]

**Pull request merged**
