### PR TITLE
Use correct function to start the node process

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

[test]

@csrwng  -- did we just not hit this code path ever?
/cc @sub-mod

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Unrelated failures.... [merge] -- @csrwng ping

**Comment by csrwng** [comment]
@stevekuznetsov I believe we use this from extended tests:
https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L145
So it would seem that this should have failed when running extended tests

**Comment by stevekuznetsov** [comment]
@csrwng so the `os::start::node` is not defined anywhere AFAICT -- if you want to do more investigation & own this, feel free to remove the merge tag.

**Comment by csrwng** [comment]
@stevekuznetsov yes, let me take a look ... or at least extended tests still run with this change

**Comment by csrwng** [comment]
[testextended][extended:builds]

**Comment by csrwng** [comment]
[testextended][extended:core]

**Comment by csrwng** [comment]
@stevekuznetsov so this code path never gets hit from regular extended tests because it would only be used if starting with a different version of the master or controllers. Normally we just do the start-all-in-one.sh 
https://github.com/openshift/origin/pull/13138/files#diff-bfba85291c09fafd55c7eeb2344cbf7fL241

And the test that runs with a different version of the master/controllers doesn't need a node, so it always sets the flag to skip the node.

[LGTM]

**Comment by stevekuznetsov** [comment]
OK. [merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/710/) failed from the following flakes:
 - [conformance](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/710/testReport/junit/(root)/Extended/_Conformance__registry__migration__manifest_migration_from_etcd_to_registry_storage_registry_can_get_access_to_manifest__local_/) failed on: https://github.com/openshift/origin/issues/13183

re[merge]

**Pull request merged**
