### PR TITLE
Move docker specific scripts back into image directories

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1455472 for stage since we are building from stage for now

cc: @sdodson @jupierce

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

**Comment by kargakis** [comment]
Flakes are https://github.com/openshift/origin/pull/14036#issuecomment-304051604 and https://github.com/openshift/origin/issues/13559

**Comment by kargakis** [comment]
[merge]

**Comment by kargakis** [comment]
[test]

**Comment by sdodson** [comment]
LGTM

**Comment by kargakis** [comment]
Master build will be brewed later today

**Pull request closed without merging**
