### PR TITLE
Several "help" usability improvements

### PR DESCRIPTION
**Pull request by fabianofranz**
- Global options nuked from all `osc` and `openshift cli` commands
- Introduces `osc options` / `openshift cli options`
- Add a footer to `osc` and `openshift cli` help: *Use "openshift options" for a list of global command-line options*

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton @jwforres

**Comment by fabianofranz** [comment]
Improvements we want to address:

- create global options help command ("options") which we add to "osc", and then omit all globals from the help template, except maybe a few important ones and a generic "osc help options for more" tagline.
- when help shows subcommands, don't show anything except the command name (omit the usage chunks)
- Nuke the usage section on each command, people should always specify their own usage line, and then put other examples. I don't think we can fix this within Cobra without invasive changes, so we can do the simpler option (having it in long desc) now.
- double check all commands for having short descriptions
- get upstream commands to parameterize their short desc with an arg (or we can do a find and replace with a wrapper function for kubectl on specific commands).

**Comment by smarterclayton** [comment]
----- Original Message -----
> Improvements we want to address:
> 
> - create global options help command ("options") which we add to "osc", and
> then omit all globals from the help template, except maybe a few important
> ones and a generic "osc help options for more" tagline.
> - when help shows subcommands, don't show anything except the command name
> (omit the usage chunks)
> - Nuke the usage section on each command, people should always specify their
> own usage line, and then put other examples. I don't think we can fix this
> within Cobra without invasive changes, so we can do the simpler option
> (having it in long desc) now.

Why can't you omit the usage line from the template?

**Comment by fabianofranz** [comment]
Done

----- Original Message -----

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
