### PR TITLE
s/imagestraams/imagestreams/ in oc get help message

### PR DESCRIPTION
**Pull request by eparis**

### CODE REVIEW

**Comment by ncdc** [comment]
@openshift/team-project-committers

**Comment by ncdc** [comment]
LGTM

**Comment by ncdc** [comment]
[test]

**Comment by deads2k** [comment]
lgtm, but I'd like to hold the merge until we get some of the more critical fixes through the queue.  We seem to be having some failures.

**Comment by ncdc** [comment]
agreed

**Comment by deads2k** [comment]
Oh, and the commit message should be `UPSTREAM: <carry>: s/imagestraams/imagestreams/ in 'oc get'`.  We'll squash it down in the rebase.  Otherwise, we'll lose it.

**Comment by eparis** [comment]
@deads2k fixed

**Comment by kargakis** [comment]
> Oh, and the commit message should be UPSTREAM: <carry>: s/imagestraams/imagestreams/ in 'oc get'. We'll squash it down in the rebase. Otherwise, we'll lose it.

Even better add the issue number from upstream, like Clayton did, so in case it has been fixed, the next rebaser will know that he can drop it.

https://github.com/openshift/origin/commit/52bb8f40a79bbea6f5cf15ee5f9410354c4e26f4

**Comment by smarterclayton** [comment]
Approved via @ncdc

**Comment by eparis** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
