### PR TITLE
default oc set image to --source=docker

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/14487

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/cli-review ptal
@smarterclayton are you ok w/ this change in default behavior?

**Comment by smarterclayton** [comment]
Yes, but please make sure the examples are correct and that they explain how to use set image for image stream tags

**Comment by bparees** [comment]
@smarterclayton done:

```
$ oc set image -h
Update existing container image(s) of resources.

Usage:
  oc set image (-f FILENAME | TYPE NAME) CONTAINER_NAME_1=CONTAINER_IMAGE_1 ...
CONTAINER_NAME_N=CONTAINER_IMAGE_N [options]

Examples:
  # Set a deployment configs's nginx container image to 'nginx:1.9.1', and its
busybox container image to 'busybox'.
  oc set image dc/nginx busybox=busybox nginx=nginx:1.9.1
  
  # Set a deployment configs's app container image to the image referenced by
the imagestream tag 'openshift/ruby:2.3'.
  oc set image dc/myapp app=openshift/ruby:2.3 --source=imagestreamtag
  
  # Update all deployments' and rc's nginx container's image to 'nginx:1.9.1'
  oc set image deployments,rc nginx=nginx:1.9.1 --all
  
  # Update image of all containers of daemonset abc to 'nginx:1.9.1'
  oc set image daemonset abc *=nginx:1.9.1
  
  # Print result (in yaml format) of updating nginx container image from local
file, without hitting the server
  oc set image -f path/to/file.yaml nginx=nginx:1.9.1 --local -o yaml
```

**Comment by bparees** [comment]
api review signed off and example added for @smarterclayton.  self lgtming.

**Pull request merged**
