### PR TITLE
Adding meaningful comments deployments cannot be started/retried

### PR DESCRIPTION
**Pull request by abhgupta**
This is based on the suggestions by @sosiouxme in https://github.com/openshift/origin/issues/2370

### CODE REVIEW

**Comment by abhgupta** [comment]
@sosiouxme PTAL

**Comment by abhgupta** [comment]
[merge] reviewed by @sosiouxme

**Comment by sosiouxme** [comment]
LGTM

**Comment by abhgupta** [comment]
unrelated failure - [merge] again

**Pull request merged**
