### PR TITLE
Fix CLI help issues

### PR DESCRIPTION
**Pull request by fabianofranz**
Addresses [bug 1169685](https://bugzilla.redhat.com/show_bug.cgi?id=1169685) and all other remaining help issues.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton this addresses the remaining 'help' issues.

**Comment by smarterclayton** [comment]
can you link the upstream pulls here?

**Comment by fabianofranz** [comment]
@smarterclayton Upstream PR here: https://github.com/spf13/cobra/pull/51

**Comment by fabianofranz** [comment]
@smarterclayton Take a look at [hack/test-cmd.sh](https://github.com/fabianofranz/origin/blob/e2a70de811ebc07a489c41d855db7770d26b7298/hack/test-cmd.sh). I added several test cases there to cover all help scenarios, need to make sure that's what we expect and everything is covered.

**Comment by smarterclayton** [comment]
LGTM - jessica and I brainstormed some help improvements today - can be done in another issue, but things like:

* create global options help command ("options") which we add to "osc", and then omit all globals from the help template, except maybe a few important ones and a generic "osc help options for more" tagline.
* when help shows subcommands, don't show anything except the command name (omit the usage chunks)
* Nuke the usage section on each command, people should always specify their own usage line, and then put other examples.  I don't think we can fix this within Cobra without invasive changes, so we can do the simpler option (having it in long desc) now.
* double check all commands for having short descriptions
* get upstream commands to parameterize their short desc with an arg (or we can do a find and replace with a wrapper function for kubectl on specific commands).

**Comment by fabianofranz** [comment]
[merge]

**Comment by fabianofranz** [comment]
@smarterclayton Nice, pretty much what I was thinking too. I'll try to keep the invasive changes as much outside of Cobra / parameterized / custom funcs as possible, but I foresee at some point we forking it (already not completely confident I'll get my recent upstream proposals merged).

**Comment by fabianofranz** [comment]
@smarterclayton I'll copy these brainstorming ideas to a Github issue.

**Comment by smarterclayton** [comment]
Let's try to delay forking as long as possible.

**Comment by smarterclayton** [comment]
Can you do a quick pass on the easiest ones here today?  I want our help to be reasonable in beta.

**Pull request merged**
