### PR TITLE
WIP - Fix types for openshift-sdn to use ints

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@pravisankar this change is going in O(soon) because it blocks protobuf validation for 3.3.  Please take a look to see if you have any comments.  Briefly, all API integer types must be either 32 or 64, and internal types are also made identical.  Generally, propagating the specific type throughout the code is considered clearer.

**Comment by pravisankar** [comment]
LGTM
Now that openshift-sdn is merged into origin (https://github.com/openshift/origin/pull/9520), sdn file paths has changed. So need to reapply some of these changes.

**Comment by smarterclayton** [comment]
I'm in the middle of the rebase, can you help me clean this up and get it
ready to merge?

**Comment by pravisankar** [comment]
Yes, I'm on it.

On Thu, Jul 7, 2016 at 4:44 PM, Clayton Coleman <notifications@github.com>
wrote:

> I'm in the middle of the rebase, can you help me clean this up and get it
> ready to merge?
>
> On Thu, Jul 7, 2016 at 7:14 PM, Ravi Sankar Penta <
> notifications@github.com>
> wrote:
>
> > LGTM
> > Now that openshift-sdn is merged into origin (#9520
> > <https://github.com/openshift/origin/pull/9520>), sdn file paths has
> > changed. So need to reapply some of these changes.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/openshift/origin/pull/9386#issuecomment-231234923>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABG_p7aHWByGfqjSnx2FTblEK3uVFnD4ks5qTYhYgaJpZM4I3otz
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/pull/9386#issuecomment-231239646>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABM0hmCsgbcuvIFFTm2lo9SnJiMOlLElks5qTY9hgaJpZM4I3otz>
> .
>



-- 
-Ravi

**Comment by smarterclayton** [comment]
Hugely appreciated.

**Comment by pravisankar** [comment]
Updated pr: https://github.com/openshift/origin/pull/9748

**Pull request closed without merging**
