### PR TITLE
[BZ-1211516] Fix creating route even when choosing not to

### PR DESCRIPTION
**Pull request by jcantrill**
@jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
@jcantrill needs bindata, otherwise LGTM

**Comment by jcantrill** [comment]
[merge] @jwforres I think I added bindata in the time between you wrote this and we discussed it on IRC

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
What's the status of this?

**Comment by jcantrill** [comment]
To my knowledge, it is ready to be merged if it hasn't. Might need a rebate and a regeneration of bindata

**Comment by ncdc** [comment]
Transient failure in merge: `UnknownError: Error communicating with the remote browser. It may have died.`

**Pull request merged**
