### PR TITLE
Include option in console vendoring script to generate the branch and…

### PR DESCRIPTION
**Pull request by jwforres**
… commit automatically

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett update so we keep a consistent pattern for the vendor commit message, and to just save a few steps in the process till we can automate it

**Comment by jwforres** [comment]
so to vendor and create a commit for master branch you'd run

```
COMMIT=1 GIT_REF=master hack/vendor-console.sh
```

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
