### PR TITLE
Lowercase all errors

### PR DESCRIPTION
**Pull request by kargakis**
Thanks to https://gist.github.com/porjo/b331df0b3d7e33c30920

@smarterclayton 

WIP because I need to restore errors that shouldn't be lowercase like "cSRF error"

### CODE REVIEW

**Comment by liggitt** [comment]
can we hold this until after rebases and DCUT?

**Comment by kargakis** [comment]
> can we hold this until after rebases and DCUT?

Sure

**Comment by smarterclayton** [comment]
bindata is a generated file.

**Comment by danmcp** [comment]
@kargakis Needs rebase

**Pull request closed without merging**
