### PR TITLE
remove tech preview label from jenkins strategy

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton per your request.

**Comment by bparees** [comment]
/retest

Ben Parees | OpenShift

**Comment by bparees** [comment]
@openshift/api-review bump.

**Comment by liggitt** [comment]
LGTM?

**Comment by bparees** [comment]
@stevekuznetsov something seems messed up in prow?  why are tests not running on this PR (or at least status is not updating if they are running)

**Pull request merged**
