### PR TITLE
[WIP] DO NOT MERGE Rework of web console theme/design

### PR DESCRIPTION
**Pull request by sg00dwin**
Issues
- With the removal of tiles on detail pages, content feels less structured/grouped?
- Additionally, the vertical ellipsis icon for editing 'resource-actions-dropdown' is less noticeable.

Post add-on tasks
- [ ] Flash content issue when a project is empty, where the white page header and filter bar flashes then is replaced with showGetStarted content. 
- [ ] Project select title flickers if their are multiple projects, when switching views.
- [ ] Convert table list views into new item list design. Waiting for markup from patternfly team  https://www.patternfly.org/patterns/list-view/
- [ ] Convert tabs to alternate patternfly tab style and update structure to new design.
 * How to insert class on `<ul>` when using angular `<uib-tabset>`?
 * How to present tab content on grey background and tabs on white background?

### CODE REVIEW

**Comment by sg00dwin** [comment]
[test]

**Comment by sg00dwin** [comment]
[test]

**Comment by sg00dwin** [comment]
[test]

**Comment by sg00dwin** [comment]
[test]

**Comment by sg00dwin** [comment]
[test]

**Comment by spadgett** [comment]
@sg00dwin Can you make sure any follow on work not already fixed is captured in an issue?

We did update to the new tab styles (#6978).

**Comment by sg00dwin** [comment]
@spadgett will do

**Pull request closed without merging**
