### PR TITLE
Simplify pod node constraints

### PR DESCRIPTION
**Pull request by deads2k**
This updates PodNodeConstraints to only run against pods as we discussed a while back and then cleans up the related cruft.

/assign @ravisantoshgudimetla

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@deads2k - Thanks for the PR. Seems the integration tests are valid.

**Comment by mfojtik** [comment]
surprising that `TestGRPCService` is not fixed or disabled yet.

**Pull request merged**
