### PR TITLE
Adding border above builds without a service so that they look more c…

### PR DESCRIPTION
**Pull request by sg00dwin**
…onnected.

Fixes https://github.com/openshift/origin/issues/3617

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
@jwforres rebased. please tag again

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@sg00dwin looks like merge failed on bindata being incorrect

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
bindata looks right now [merge]

**Comment by jwforres** [comment]
[test] again

**Pull request merged**
