### PR TITLE
Enable exec/http proxy e2e test

### LINKED ISSUE #7097: kubectl e2e "should support exec through an HTTP proxy" can't run on Origin
Tries to build a static kubectl binary, which we don't support today.

Spawned by #7094

### PR DESCRIPTION
**Pull request by ncdc**
I tested this locally and it passed for me.

cc @smarterclayton 

Fixes #7097

### CODE REVIEW

**Comment by ncdc** [comment]
[test]

**Comment by timothysc** [comment]
We should add a canonical extended wrapper script that is the single source of truth.  Right now there are jenkins scripts, but we need something that feeds through to product. 

/cc @jayunit100 @sdodson

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by ncdc** [comment]
Lots o' flakes including #7706 [test]

**Comment by ncdc** [comment]
flake #9929 [merge]

**Comment by ncdc** [comment]
Will wait till after 1.3.0 lands to merge this as it's not as important as bug fixes

**Comment by ncdc** [comment]
Flake #10228 [test]

**Comment by ncdc** [comment]
[test] #11094

**Comment by ncdc** [comment]
FYI I don't think this test actually runs, even when we remove it from the skip list, because it's coded in the test itself to skip if the provider is local. I will see about making a change upstream to skip the test if the apiserver only serves http, so that we can run it successfully against a secured apiserver.

[merge] flake #10228

**Pull request merged**
