### PR TITLE
SCC API check: move

### PR DESCRIPTION
**Pull request by sdminonne**
@deads2k as discussed in #10450 here's is the PR with the _move_ without refactoring.

### CODE REVIEW

**Comment by sdminonne** [comment]
[test]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/7706  https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8425/ re[test]

**Comment by deads2k** [comment]
@sdminonne thanks, this looks straightforward.  Any issues I should review in detail or was it all just a straight move in preparation for the next step?

**Comment by sdminonne** [comment]
@deads2k , it's only the move. Next PR is going to be the small refactoring.

**Comment by deads2k** [comment]
> @deads2k , it's only the move. Next PR is going to be the small refactoring.

Ok.  Depending on how we look against code freeze, I may merge this on green.

**Comment by sdminonne** [comment]
re[test]

**Comment by deads2k** [comment]
[merge]

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/10489  https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/8477/ re[merge]

**Comment by deads2k** [comment]
yum re[merge]

**Comment by sdminonne** [comment]
@deads2k thanks

**Pull request merged**
