### PR TITLE
Remove pre CNI docker cleanup code from openshift SDN

### PR DESCRIPTION
**Pull request by pravisankar**
It's been few releases that we moved to CNI interfaces.
Previous release migrations should have done the pre CNI cleanup if needed.
So we no longer need this dead code.

### CODE REVIEW

**Comment by pravisankar** [comment]
/hold
Since this is not critical, we could merge this post 3.7 release

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by danwinship** [comment]
/lgtm
agree post-3.7

**Comment by pravisankar** [comment]
@openshift/networking  rebased, ptal

**Pull request merged**
