### PR TITLE
glog missing nodes

### PR DESCRIPTION
**Pull request by juanvallejo**
Depends on https://github.com/openshift/origin/pull/18466
Addresses https://github.com/openshift/origin/pull/18466#discussion_r166296275

cc @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
> Depends on #18466
> Addresses #18466 (comment)
> 
> Changes are in last commit.
> 
> cc @deads2k

Seems like the last commit stands along.  Try just that.

**Comment by juanvallejo** [comment]
@deads2k I think we should close this PR in favor of https://github.com/openshift/origin/pull/18625, which brings in these changes

**Comment by juanvallejo** [comment]
Closing. This change was introduced in https://github.com/openshift/origin/pull/18625

**Pull request closed without merging**
