### PR TITLE
Fix manpage directory structure

### PR DESCRIPTION
**Pull request by juanvallejo**
Addresses trello card: https://trello.com/c/SbXIB0sW/595-3-cli-man-pages-for-oc-oadm-openshift#comment-57722dd177bba5fd269f31be

Right now, manpages are stored in `docs/man/oc`, `docs/man/openshift`, `docs/man/oadm`.
The correct structure expected by a `MANPATH` is `docs/man/man1/*`

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by juanvallejo** [comment]
@fabianofranz Could you please take a look?

**Comment by fabianofranz** [comment]
@juanvallejo where is `traverse`  being used?

**Comment by juanvallejo** [comment]
@fabianofranz Sorry about that, `hack/recurse-cmd-tree.js` is an untracked file I was using on another branch. Accidentally staged it, but should be removed now.

**Comment by fabianofranz** [comment]
LGTM, [merge]

**Pull request merged**
