### PR TITLE
Remove autogenerated docs folder and gitserver

### PR DESCRIPTION
**Pull request by smarterclayton**
* Removed gitserver (someone can move it out if they want later)
* Removed checked in docs files
* Docs aren't generated for the openshift binary anymore, because we won't build RPMs for it and so it won't be visible to anyone in 4.0.  Operators also control this.

@bparees @juanvallejo @soltysh

### CODE REVIEW

**Comment by bparees** [comment]
we use the gitserver in our extended tests to test private repositories.

**Comment by smarterclayton** [comment]
We do, but we can continue using the previous tag.

**Comment by smarterclayton** [comment]
Multiple flakes, merging to avoid rebase conflicts

**Pull request merged**
