### PR TITLE
up: remove --env flag

### PR DESCRIPTION
**Pull request by mfojtik**
This removes the `--env` flag from cluster up. It was passed just to kubelet and it can cause more harm than good to support it. 

/cc @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

@mfojtik indicate a release-note that they can --write-config and update the static pod definition.

**Comment by deads2k** [comment]
/hold

It just occurred to me that the kubelet may be naughty.

@sjenning does the kubelet use env vars to control behavior?  If so, we'll hide this instead.

**Comment by sjenning** [comment]
> @sjenning does the kubelet use env vars to control behavior?

I don't know of any behavior that is controlled that way and a quick search for calls to `os.Environ()` turns up nothing

**Comment by mfojtik** [comment]
@deads2k merge?

**Pull request merged**
