### PR TITLE
check the olm --version

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@njhale @ecordell @tkashem  Could you help take a look at this PR? Thanks!

**Comment by bparees** [comment]
@jianzhangbjz your new test appears to be failing: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24009/pull-ci-openshift-origin-master-e2e-gcp/3556

**Comment by jianzhangbjz** [comment]
@bparees Thanks! I will debug it.

**Comment by jianzhangbjz** [comment]
@bparees Could you help `cherry-pick` my latest commit: https://github.com/openshift/origin/pull/23714/commits/88fd1e13565edb2ee08554820662880a612e4c50 for this PR? Thanks very much!

**Comment by bparees** [comment]
@jianzhangbjz done, please check it

**Comment by bparees** [comment]
/hold

this still doesn't appear to be passing.

**Comment by bparees** [comment]
@jianzhangbjz can you look into the failures?

**Comment by jianzhangbjz** [comment]
@bparees I checked this failure below, but I don't know how to solve it? What do you suggest? And, could you help rebase it? Thanks very much!
```console
level=error msg="Error: Error applying IAM policy to project \"openshift-gce-devel-ci\": Too many conflicts.  Latest error: Error setting IAM policy for project \"openshift-gce-devel-ci\": googleapi: Error 409: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff., aborted"
```

**Comment by bparees** [comment]
i think that's a CI infra issue.

/retest

**Comment by bparees** [comment]
btw this PR is now blocked because we can't update the deps until https://github.com/openshift/origin/pull/24254#discussion_r357874343 is resolved.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/24286 is the rebase PR, so this will need to wait for that.

**Comment by bparees** [comment]
@jianzhangbjz this test is failing again:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24009/pull-ci-openshift-origin-master-e2e-aws-fips/710

```
panic: spec was set twice: "[Feature:Platform] OLM should olm version should contain the source commit id [Suite:openshift/conformance/parallel]" and "[Feature:Platform] OLM should olm version should contain the source commit id [Suite:openshift/conformance/parallel]"

goroutine 1 [running]:
github.com/openshift/origin/pkg/test/ginkgo.(*MinimalReporter).SpecDidComplete(0xc003a4d180, 0xc00323b400)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/test/ginkgo/ginkgo.go:78 +0x326
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).reportSpecDidComplete(0xc002ed6500, 0xc00323b400, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:314 +0xd1
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc002ed6500, 0xc003fad950, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:202 +0x185
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc002ed6500, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x120
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc002ed6500, 0xc0046b0358)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00029b400, 0x5f95b80, 0xc003a4d180, 0x0, 0x0, 0xc0015b18a0, 0x1, 0x1, 0x6093880, 0xc00029d040, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x42b
github.com/openshift/origin/pkg/test/ginkgo.(*TestOptions).Run(0xc00437b1d0, 0xc004373c80, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/test/ginkgo/cmd_runtest.go:59 +0x41f
main.newRunTestCommand.func1(0xc004031680, 0xc004373c80, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:233 +0x11f
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc004031680, 0xc004373c40, 0x1, 0x1, 0xc004031680, 0xc004373c40)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc004030f00, 0x0, 0x5f9d560, 0x970bbc8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:864
main.main.func1(0xc004030f00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:68 +0x9c
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift-tests/openshift-tests.go:69 +0x341
```

**Comment by jianzhangbjz** [comment]
@bparees Thanks! I have rebased it and change it to `serial` run. Could you help to cherry-pick it? Thanks! #23714

**Comment by bparees** [comment]
> @bparees Thanks! I have rebased it and change it to serial run. Could you help to cherry-pick it? Thanks! #23714

done, but really at this point you should just go add a vendor bump to your PR and get it merged.  It's worth knowing how to do it (and it's as simple as running `hack/update-deps.sh` in origin).

**Comment by jianzhangbjz** [comment]
@bparees Thanks as always for your help! I will do that, thanks for your suggestions.

**Pull request merged**
